department-of-veterans-affairs/vets-api

- app/sidekiq/central_mail/submit_form4142_job.rb
- app/sidekiq/evss/disability_compensation_form/submit_form0781.rb
- app/sidekiq/evss/disability_compensation_form/submit_form526.rb
- app/sidekiq/evss/disability_compensation_form/submit_form526_cleanup.rb
- app/sidekiq/evss/disability_compensation_form/submit_form8940.rb
- lib/sidekiq/form526_backup_submission_process/submit.rb
- spec/lib/sidekiq/form526_backup_submission_process/submit_spec.rb
- spec/sidekiq/central_mail/submit_form4142_job_spec.rb
- spec/sidekiq/evss/disability_compensation_form/submit_form0781_spec.rb
- spec/sidekiq/evss/disability_compensation_form/submit_form526_cleanup_spec.rb
- spec/sidekiq/evss/disability_compensation_form/submit_form8940_spec.rb
- add / update / homogenize on-exhaustion hooks for 526 related sidekiq async jobs.  This allows for logs that can be aggregated on in Datadog, as well as the addition of stats D metrics.
- fix existing syntax issue with `Rails.logger` vs `::Rails.logger`
- [PR 2 of 2](https://github.com/department-of-veterans-affairs/vets-api/pull/14735)
- [ticket](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/67288)
- added RSpec tests
- manual click through and instantiation
- 526 Async submission
> Add exhaustion logging for 526 jobs (1 of 2)

- modules/simple_forms_api/app/models/simple_forms_api/vba_20_10206.rb
This fixes a bug where we use `vaFileNumber` for metadata but the FE actually sends back `ssn`. Now the metadata will accept both.
NA
> Accept ssn in addition to va file number for metadata

- .github/workflows/audit_service_tags.yml
- Follow-up to https://github.com/department-of-veterans-affairs/vets-api/pull/14239. I noticed this action was failing on the vets-api [k8s branch](https://github.com/department-of-veterans-affairs/vets-api/commits/k8s). (k8s is a temporary branch, but is essential to our deployments at the moment. The failure isn't blocking anything, but we don't want unnecessary failures muddying the water.)
- [Example failure](https://github.com/department-of-veterans-affairs/vets-api/actions/runs/7173372814/job/19532591406)
- This PR makes a change so that the audit_service_tags action only runs when there is a pull request to master. 
- I'm on Platform product team. 
- https://github.com/department-of-veterans-affairs/vets-api/pull/14239
- https://github.com/department-of-veterans-affairs/va.gov-team …
> Run audit_service_tags on PRs to master

- modules/simple_forms_api/app/form_mappings/vba_20_10206.json.erb
This adds more content to the Remarks box of the pdf for Simple Forms 20-10206, which were previously not being reflected on the pdf.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/854
Tests pass
This tortured logic in an erb template is making very clear to me that we need to refactor these erb templates and allow us to use method calls to populate the pdf. That will be a new year goal because we need to get this form done!
> Add more to the Remarks box for Simple Form 20-10206

- modules/claims_api/app/controllers/concerns/claims_api/v2/disability_compensation_validation.rb
- modules/claims_api/spec/lib/claims_api/v2/disability_compensation_validation_spec.rb
- modules/claims_api/spec/requests/v2/veterans/disability_compensation_request_spec.rb
* The only validation that needs to occur is to make sure the earliest confinement period comes after the earliest service beginDate. We do not need to verify it actually occurs inside an existing service block.   No other validations need to happen.
* removes some extra validating that was going on win regards to confinement periods and service duty periods Changes to be committed:
* Adds a spec file to handle testing validation methods directly
[API-32294](https://jira.devops.va.gov/browse/API-32294)
* RSpec
* Postman
modified:   modules/claims_api/app/controllers/concerns/claims_api/v2/disability_compensation_validation.rb
modified:   modules/claims_api/spec/requests/v2/veterans/disability_compensation_request_spec.rb
created: …
> API-32294 confinement date validation fix

- modules/simple_forms_api/app/form_mappings/vba_20_10206.json.erb
In my haste earlier today I failed to make my changes safe if `nil` results from the data calls while being `+`ed to strings. This is another thing I want to protect against if I get time to refactor this code a bit.
> Make form mapping safe for nil, Simple Forms 20-10206

- config/initializers/sidekiq.rb
Attempting to prepend env settings before sidekiq is initialized.
*(Describe what …
> Prepend env settings in vets-api-dev

- .github/CODEOWNERS
- config/redis.yml
- lib/sidekiq/attr_package.rb
- spec/lib/sidekiq/attr_package_spec.rb
This creates a new sidekiq class - `AttrPackage`
The goal of this class is the create an "attribute package" that could potentially contain PII or sensitive info, store it in redis, pass the redis key to your job and then inside your job retreive the package from redis and use the attributes in your job. The default expiration is 7 days but is an optional parameter
```ruby
require 'sidekiq/attr_package'
attr_package_key = Sidekiq::AttrPackage.create(icn: '123498767V234859', signature_name: 'John Doe', version: '1.0.0')
TermsOfUse::SignUpServiceUpdaterJob.perform_async(attr_package_key)
def perform(attr_key)
attrs = Sidekiq::AttrPackage.find(attr_key)
@icn = attrs[:icn]
@signature_name = attrs[:signature_name]
@version = attrs[:version]
end 
```
- …
> Create sidekiq attr package

- db/migrate/20231213145347_rename_form_data_to_form_data_ciphertext.rb
- db/schema.rb
This PR fixes a little mistake I made earlier when I neglected to name the KMS encrypted field `form_data_ciphertext` in the `form_submissions` table.
We have no `form_submissions` saved to the database yet so dropping the column should be no problem.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/71835
> Rename form_data to form_data_ciphertext

- modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb
- modules/simple_forms_api/spec/requests/v1/uploads_spec.rb
This PR will create a new `FormSubmission` every time we submit a form through the Simple Forms controller.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/71835
Tests written and passing.
> Create a new FormSubmission every time we submit a Simple Form

- .github/workflows/check-git-log.yml
Checks current branch unless ran via schedule which is now hourly.
This prevents getting ❌ed by other branches on your PR.
> Only check current branch unless we're triggered via schedule/cron

- modules/simple_forms_api/app/models/simple_forms_api/vba_40_0247.rb
- modules/simple_forms_api/spec/fixtures/form_json/vba_40_0247-min.json
- modules/simple_forms_api/spec/fixtures/form_json/vba_40_0247.json
- modules/simple_forms_api/spec/fixtures/form_json/vba_40_0247_with_supporting_document.json
This PR updates the 40-0247 model so that when we submit two PDFs, the second one has the correct number for # of certificates requested. I also took the liberty of updating our test data so that the number of certificates requested and the additional number of certificates requested are different numbers, making testing easier.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/719
> Use correct number for additional form number of certificates requested

- lib/va_profile/veteran_status/configuration.rb
Fixes a veteran_status Redis EMIS deprecation error that was noticed in production.
[Slack thread](https://dsva.slack.com/archives/C03LT909K1A/p1702492075679549)
> Fix Service Name for Veteran Status Redis

- modules/veteran/app/controllers/veteran/v0/accredited_representatives_controller.rb
- modules/veteran/app/docs/veteran/v0/accreditation.yaml
- modules/veteran/spec/requests/v0/accredited_representatives_spec.rb
- As part of the new MVP path for Find a Representative, this PR removes the ability to sort results by `distance_desc` (farthest to closest).
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/71824
`distance_desc` is now an invalid field value in Postman. All other values remain valid
- "Find a Representative" is not yet live in production. This change will only impact staging + internal testing.
> Remove ability to sort "Find a Representative" results by distance_desc

- app/sidekiq/bgs/flash_updater.rb
- app/sidekiq/central_mail/submit_form4142_job.rb
- app/sidekiq/evss/disability_compensation_form/submit_form0781.rb
- app/sidekiq/evss/disability_compensation_form/submit_form526.rb
- app/sidekiq/evss/disability_compensation_form/submit_form526_cleanup.rb
- app/sidekiq/evss/disability_compensation_form/submit_form8940.rb
- app/sidekiq/evss/disability_compensation_form/submit_uploads.rb
- app/sidekiq/evss/disability_compensation_form/upload_bdd_instructions.rb
- lib/logging/third_party_transaction.rb
- lib/sidekiq/form526_backup_submission_process/submit.rb
- spec/lib/sidekiq/form526_backup_submission_process/submit_spec.rb
- spec/sidekiq/bgs/flash_updater_spec.rb
- spec/sidekiq/central_mail/submit_form4142_job_spec.rb
- spec/sidekiq/evss/disability_compensation_form/submit_form0781_spec.rb
- spec/sidekiq/evss/disability_compensation_form/submit_form526_cleanup_spec.rb
- spec/sidekiq/evss/disability_compensation_form/submit_form8940_spec.rb
- spec/sidekiq/evss/disability_compensation_form/submit_uploads_spec.rb
- spec/sidekiq/evss/disability_compensation_form/upload_bdd_instructions_spec.rb
Revise `STATSD_KEY_PREFIX`, appending `exhausted` suffix within `sidekiq_retries_exhausted` block
- [ticket](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/67288)
- updated RSpec tests
- manual click through and instantiation
- 526 Async submission
> Modify STATSD_KEY_PREFIX

- modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb
This PR fixes a silly mistake I made where I sent `User` objects to `FormSubmission` instead of `UserAccount`s.
> Supply a user_account to FormSubmission instead of user

- modules/simple_forms_api/lib/simple_forms_api.rb
We discovered that even though we are stripping entered form data that might contain PII, user first and last names were being entered and then upcased behind the scenes. This ensures that even if they are upcased, they should be deleted from the error message.
> Strip upcased form data from error messages

- app/models/form_submission_attempt.rb
- app/sidekiq/benefits_intake_status_job.rb
- spec/sidekiq/benefits_intake_status_job_spec.rb
This PR fixes a problem where a complete form submission would be marked `success` rather than `vbms` in our state machine. It also adds a transition from `success` to `vbms` (which we aren't using yet, but may someday).
> Change sidekiq job to vbms rather than succeed

- Makefile
- Added `RAILS_ENV=test` to the `make spec` command because it was otherwise running rspec with development dependencies
> Update make spec

- app/models/form_submission_attempt.rb
This PR splits logging into error and non-error states so that we can more easily read the logs and determine where intervention might be needed. This will also help with reporting on DataDog, I believe.
> Improve logging for FormSubmissionAttempt state change

- modules/mobile/app/services/mobile/v0/claims/proxy.rb
- modules/mobile/spec/request/legacy_claims_decision_request_spec.rb
Changes not found behavior from 500 to 404
- https://github.com/department-of-veterans-affairs/va-mobile-app/issues/7519
Specs.
Unclear what impact this will have on FE, but at most it should change the error messaging. The problem is actually deeper and a ticket will be filed for a better fix.
> 7519: claims request decision not found

- app/models/form_submission_attempt.rb
We want to know which form we're attempting to submit. This will be useful for a DD Dashboard to aggregate over all form types and see if there are trends.
> Log the form_type with FormSubmissionAttempt

- modules/claims_api/spec/requests/v2/veterans/disability_compensation_request_spec.rb
Fixes failing test that was checking a dynamic date vs. static date value which was no longer outside the range it needed to be.
* Failing test on master
* RSpec
* modified: modules/claims_api/spec/requests/v2/veterans/disability_compensation_request_spec.rb
> Changes date for BDD to be dynamic instead of static so it stays outside of the range

- app/controllers/v0/disability_compensation_forms_controller.rb
- config/features.yml
- spec/requests/disability_compensation_form_request_spec.rb
- spec/requests/swagger_spec.rb
- Add  'disability_compensation_prevent_submission_job' feature flag to prevent submission job per user
- department-of-veterans-affairs/va.gov-team#69391
- hit the endpoint /submit_all_claim with this feature flag turned on and no submission job will be created
- response will have `"jid": 0`
- Form526 /submit_all_claim endpoint
> dbex/69391: gate submission job for certain users with Feature Toggle

- app/models/form_submission_attempt.rb
This PR fixes a mistake I made in logging from the `FormSubmissionAttempt` model where I was looking for a string and it ought to have been a Ruby symbol.
> Change string to symbol so that logging works

- .github/CODEOWNERS
docker-compose files were missing from CODEOWNERS file.
Added `docker-compose* @department-of-veterans-affairs/backend-review-group`
This CODEOWNERS file is valid.
> add docker-compose* to BE review group ownership

- modules/ask_va_api/app/controllers/ask_va_api/v0/inquiries_controller.rb
- modules/ask_va_api/app/lib/ask_va_api/attachments/entity.rb
- modules/ask_va_api/app/lib/ask_va_api/attachments/retriever.rb
- modules/ask_va_api/app/lib/ask_va_api/attachments/serializer.rb
- modules/ask_va_api/config/locales/get_attachments_mock_data.json
- modules/ask_va_api/config/routes.rb
- modules/ask_va_api/spec/app/lib/ask_va_api/attachments/entity_spec.rb
- modules/ask_va_api/spec/app/lib/ask_va_api/attachments/retriever_spec.rb
- modules/ask_va_api/spec/app/lib/ask_va_api/attachments/serializer_spec.rb
- modules/ask_va_api/spec/requests/v0/inquiries_spec.rb
- Developed `Attachments::Entity` and its Spec
- Implemented `Attachments::Retriever` and its Spec
- Created `get_attachments_mock_data.json`
- Implementing `download_attachment` Route, Action, and Spec
- department-of-veterans-affairs/ask-va#476
- created `unit test` and `integration test`
> BE | Ask VA Api: Created `Inquiries#download_attachment` endpoint

- config/features.yml
- We have removed the usage of `show_authenticated_menu_enhancements` feature toggle on the FE, so now we need to remove it from the api code.
- [department-of-veterans-affairs/va.gov-team#0000](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70769)
- tests pass, just removing a single toggle
Profile
> fix: remove toggle

- config/features.yml
- Removing the feature flag `burial_form_v2` as it is no longer needed
(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this …
> Removing feature flag. No longer needed

- app/sidekiq/benefits_intake_status_job.rb
This PR adds some summary stats to our `BenefitsIntakeStatusJob`, which should make it easier to have our dashboard show counts of pending forms.
> Add summary stats to daily benefits intake status job

- config/settings.yml
VA notify is receiving an excessive number of hits from the Debt team's API key. To better accommodate them I'm adjusting our throttle to send fewer requests per second.
[72343](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/72343)
specs pass
user email notifications for new copay statements
- The Debt team will hit VaNotify's api fewer that 15 times per second
> 72343 Adjust DMCs throttle for hitting VaNotify

- lib/evss/disability_compensation_form/form4142_processor.rb
- spec/sidekiq/central_mail/submit_form4142_job_spec.rb
The processing of 4142 forms, as part of the 526 form submission workflow, has experienced issues where special characters in a Veteran's first and/or last names would trigger a failure within the Central Mail EMMS API regex validation. The method implemented corrects for or removes any non-conforming characters in the generated metadata of a request body for a CentralMail submission. 
Zenhub ticket [#72321](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/72321)
Test added to validate the conversion of accented characters into their respective equivalents (e.g., `é` => `e`) and removal of characters that are not letters (both uppercase and lowercase), apostrophes, spaces, or hyphens. …
> Transliterate form 4142 metadata name values

- modules/veteran/app/serializers/veteran/accreditation/representative_serializer.rb
- modules/veteran/spec/serializers/accreditation/representative_serializer_spec.rb
- Added user_types to representative serializer
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/69742
- Added user_types to specified model attributes expected in the representative serializer spec
> Adding user_types attribute to representative serializer

- modules/ask_va_api/app/controllers/ask_va_api/v0/static_data_controller.rb
- modules/ask_va_api/spec/requests/v0/static_data_spec.rb
- Updated `StaticData#Index` to get `/topics` instead of `ping`
- department-of-veterans-affairs/ask-va#492
> BE | Ask VA API: GET `/topics` live data

- modules/appeals_api/app/services/appeals_api/pdf_construction/higher_level_review/v3/pages/additional_issues.rb
An incorrect check for the length of a representative email was raising errors when we tried to switch to v3 instead of v2 of the HLR form. This should fix the problem.
None
Manually tested. The automated PDF generation tests that we have for v3 of the HLR form cannot successfully run in the k8s branch of this repo for reasons we don't understand, so we haven't been able to add many automated tests for it.
- This updates the processing code for version 3 of the Higher-Level Review form so that it doesn't error when processing an HLR with a representative but no email for that representative. We have determined that, so far, this impacts roughly 2% of users, but this percentage may change significantly based on new submissions in the future.
> Fix email length bug in HLR v3 PDF submission

- modules/ask_va_api/app/services/crm/service.rb
- modules/ask_va_api/spec/services/crm/service_spec.rb
- CRM API needed an `organizationName` included in the `params`
- department-of-veterans-affairs/ask-va#492
> BE | Ask VA Api: Update Crm::Service params

- db/seeds/development.rb
- This PR updates the localhost seeds for the Chatbot service account configuration
- This does not have an impact on non-localhost stacks
> Updating seeds for chatbot service account config

- Gemfile.lock
- Our code checks expect the latest version of brakeman: https://github.com/department-of-veterans-affairs/vets-api/blob/master/.github/workflows/code_checks.yml#L27, so I've updated to the latest using `bundle update brakeman`.
- This failed here: https://github.com/department-of-veterans-affairs/vets-api/actions/runs/7330733936
- I was notified about it here: https://dsva.slack.com/archives/C039HRTHXDH/p1703605510200619
Before:
```
rebeccatolmach ~/git/vets-api bundle exec brakeman --ensure-latest --confidence-level=2
Could not find brakeman-6.1.1 in locally installed gems
```
After
```
rebeccatolmach ~/git/vets-api bundle update brakeman
...
Bundle updated!
rebeccatolmach ~/git/vets-api bundle exec brakeman --ensure-latest --confidence-level=2
Loading scanner...
Processing application …
```
> Update brakeman to 6.1.1

- lib/flipper/utilities/bulk_feature_checker.rb
- modules/appeals_api/app/sidekiq/appeals_api/flipper_status_alert.rb
- modules/appeals_api/spec/sidekiq/appeals_api/flipper_status_alert_spec.rb
- modules/va_forms/app/sidekiq/va_forms/flipper_status_alert.rb
- modules/va_forms/spec/sidekiq/flipper_status_alert_spec.rb
- modules/vba_documents/app/sidekiq/vba_documents/flipper_status_alert.rb
- modules/vba_documents/spec/sidekiq/flipper_status_alert_spec.rb
- spec/lib/flipper/utilities/bulk_feature_checker_spec.rb
This PR updates the Slack alerts generated by the `FlipperStatusAlert` jobs in the `AppealsApi`, `VAForms`, and `VBADocuments` modules (i.e. all modules owned by Lighthouse Team Banana Peels) in order to exclude "missing" feature flags from the alerts. (Disabled feature flags will continue to be included in the alert.)
Previously, it was believed that feature flags suddenly missing from the database were a problem in deployed environments, but this turned out not to be the case. (There was only a problem with disabled features.) In addition, the code in `Flipper::Utilities::BulkFeatureChecker` to check for missing flags was providing inconsistent false positive results, i.e. stating that features were "missing" when they were not.
Therefore, this PR also removes the `:missing` key from …
> API-32464: Remove Slack Alerts for Missing Feature Flags (`AppealsApi`, `VAForms`, `VBADocuments` Modules)

- .github/CODEOWNERS
- Gemfile
- Gemfile.lock
- config/initializers/active_model_serializers.rb
- upgrade `active_model_serializer` to v0.10.14
- remove `active_model_serializer` gem from `department-of-veterans-affairs` source
- add monkey patch to override `as_json` in `config/initializers/active_model_serializers.rb`
- v0.10.14 doesn't allow `id` to be `blank` which is why the monkey patch was required
- [Issue #72560](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72560)
- [Issue #71543](https://github.com/department-of-veterans-affairs/va.gov-team/issues/71543)
- local testing 
- comparing serialized data of spec/requests/va_profile/email_address_request_spec.rb
- API endpoints that use AMS including under app/controller, modules (appeals_api, meb_api, mobile, my_health, test_user_dashboard, va_forms, vba_documents, veteran)
> Upgrade active_model_serializer to v0.10.14 with monkey patch

- modules/appeals_api/app/controllers/appeals_api/v1/appeals_controller.rb
- modules/appeals_api/app/controllers/concerns/appeals_api/icn_parameter_validation.rb
- modules/appeals_api/app/controllers/concerns/appeals_api/openid_auth.rb
- modules/appeals_api/app/swagger/appeals_status/v1/swagger.json
- modules/appeals_api/app/swagger/appeals_status/v1/swagger_dev.json
- modules/appeals_api/lib/appeals_api/token_validation_client.rb
- modules/appeals_api/spec/docs/appeals_status/v1_spec.rb
- modules/appeals_api/spec/lib/token_validation_client_spec.rb
- modules/appeals_api/spec/requests/v1/appeals_controller_spec.rb
- modules/appeals_api/spec/support/doc_helpers.rb
- This makes the following changes to the Appeals Status API v1:
1. The `X-VA-User` header is no longer required or sent to Caseflow - this is not directly related to the other changes here, but we realized while discussing this ticket that this header may not actually be required at all, since results are returned regardless of whether we send it. If it turns out that this is not the case, we can revisit easily.
2. **For requests made with tokens with `veteran/*` scopes only**, the ICN parameter is no longer required. Instead, by default, the ICN is read from the token validation result (the response from the validation server). If the user sends an `icn` parameter even though it's optional, it must match the ICN read from this token. If it doesn't match, the result will be a 403 …
> API-32191 Use ICN from token in Appeals Status API

- Gemfile.lock
- modules/debts_api/lib/debts_api/v0/vha_fsr_form.rb
- modules/debts_api/spec/fixtures/fsr_forms/streamlined_fsr_form.json
- modules/debts_api/spec/lib/debt_api/v0/fsr_form_builder_spec.rb
- Updates FSR reason to always be "Automatically Approved, Waiver" when using streamlined waiver
-  Not a bug, just an update
- *Manually defines FSR reason to always be "Automatically Approved, Waiver", solution ensures all streamlined waivers have the proper reason regardless of user input*
- *debts-api team, yes*
- *N/A*
- [*Link to ticket created in va.gov-team repo*](https://github.com/department-of-veterans-affairs/va.gov-team/issues/67399)
- *Rspec changes, tested and working, specs green*
-  ```bundle exec rspec modules/debts_api/spec/lib/debt_api/v0/fsr_form_builder_spec.rb```
- ```ruby
it 'updates fsrReason' do
vha_form = form_builder.vha_forms.first.form_data
reasons = vha_form['personalIdentification']['fsrReason']
expect(reasons).to eq('Automatically Approved, Waiver')
end …
```
> 67399 - Update fsr reason to automatically approved, waiver

- modules/mobile/app/controllers/mobile/v0/prescriptions_controller.rb
- modules/mobile/spec/request/prescriptions_request_spec.rb
Front end wants a count of how many prescriptions are refillable. This PR updates the count to include that information
- [department-of-veterans-affairs/va.gov-team#7212](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/7212)
Updated specs
I added the `isRefillable` count to the existing count even though front end currently only wants `isRefillable`. I figured the count is already there and could be useful if they ever want to use it again. I understand if people think it's worth removing since it's currently unused, but I personally thought it's innocuous enough that it's worth keeping. LMK your thoughts!
> Mobile: Add count for isRefillable to prescriptions

- config/initializers/filter_parameter_logging.rb
Adds `document_type` to the list of parameters that won't be filtered in DataDog logs. My team is interested in being able to add a query parameter to calls to the V0::ClaimLetterController (/v0/claim_letters) to record the docType (a numeric value such as 184) that is being requested by va.gov
- department-of-veterans-affairs/va.gov-team#72469
> Adding document_type to list of allowed params for DataDog

- app/models/concerns/kms_encrypted_model_patch.rb
- setting the KMS_KEY_ROTATION_DATE as a constant had the effect of persisting a stale date during the new years code freeze as many pods weren't refreshed. By setting is as a method, the fresh date is always calculated
> Bug Fix: set kms_key_rotation_date with method instead of constant

- modules/claims_api/lib/claims_api/v2/disability_compensation_pdf_mapper.rb
- Adds check to see if we have reserves/fed activation info before trying to delete it.
[API-32277](https://jira.devops.va.gov/browse/API-32277)
- Postman
- rspec
Test by removing the following section:
```               
"reservesNationalGuardService": {
"obligationTermsOfService": {
"beginDate": "2016-11-24",
"endDate": "2017-11-17"
},
"unitName": "National Guard Unit Name",
"unitAddress": "1243 pine court",
"component": "National Guard",
"unitPhone": {
"areaCode": "555",
"phoneNumber": "5555555"
},
"receivingInactiveDutyTrainingPay": "YES"
},
```
modified:   modules/claims_api/lib/claims_api/v2/disability_compensation_pdf_mapper.rb
> API-32277-fed-act-delete-error

- config/features.yml
- modules/veteran/app/controllers/veteran/v0/accredited_representatives_controller.rb
- modules/veteran/spec/requests/v0/accredited_representatives_spec.rb
- Renamed `find_a_rep` feature toggle to `find_a_representative_enable_api`
- Added `find_a_representative_enable_frontend`
- Updated `find_a_rep` references
Delaying the removal of `find_a_representative` feature toggle (which gates the Find a Rep frontend) until references are updated in vets-website. This toggle will be removed once the frontend is referencing `find_a_representative_enable_frontend`.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/70842
> Updating find_a_rep feature toggle name

- modules/vba_documents/lib/vba_documents/upload_validator.rb
- modules/vba_documents/spec/lib/upload_validator_spec.rb
- Adds validations for zip code metadata when uploading a document via the Benefits Intake API (any version)
- [API-32243](https://jira.devops.va.gov/browse/API-32243)
- Updated and added specs
All versions of the Benefits Intake API
Do we need release notes for this? I'm leaning no because we're enforcing the metadata schema we already have, but I don't feel strongly.
> API-32243 Validate zipCode in Benefits Intake metadata

- modules/claims_api/lib/claims_api/v2/disability_compensation_pdf_mapper.rb
- modules/claims_api/spec/lib/claims_api/v2/disability_compensation_pdf_mapper_spec.rb
- Corrects mapper so when there is only one service period, that period is not mapped to 20D on the pdf.
[API-32157](https://jira.devops.va.gov/browse/API-32157)
- rspec
- Postman
1. Submit with one service period and check to see if 20D is empty (it should be)
2. Submit with two service periods and check the pdf to see if 20D is populated (it should be)
```
"servicePeriods": [
{
"serviceBranch": "Air Force",
"activeDutyBeginDate": "2008-11-14",
"activeDutyEndDate": "2023-10-30",
"serviceComponent": "Active",
"separationLocationCode": "98282"
},
{
"serviceBranch": "Air Force",
"activeDutyBeginDate": "2023-10-30",
"activeDutyEndDate": "2024-01-01",
"serviceComponent": "Active",
"separationLocationCode": "98282"
}
]```
modified:   modules/claims_api/lib/claims_api/v2/disability_compensation_ …
> API-32157-single-service-period-20D

- config/features.yml
It was observed that there were still calls to eMIS being utilized by the staging environment, as shown by [these datadog metrics](https://vagov.ddog-gov.com/metric/explorer?start=1704209855579&end=1704296255579&paused=false#N4Ig7glgJg5gpgFxALlAGwIYE8D2BXJVEADxQEYAaELcqyKBAC1pEbghkcLIF8qo4AMwgA7CAgg4RKUAiwAHOChASAtnADOcAE4RNIKtrgBHPJoQaUAbVBGN8qVoD6gnNtUZCKiOq279VKY6epbINiAiGOrKQdpYZAYgUJ4YThr42gDGSsgg6gi6mZaBZnHKGniqyIwY8to4xFgAdIL1IghwIlBNXAjyTUZBGhZNCDgIGGjAdQ1YyHCqEBoubQg8AAQARljrwJ0AbhBt6u08TRjLmfjtABQAlCB8oJHRubFYAEyJyRNpGdnKfKFYogd7lSrVWr1RpNTYYTIAa06 …
> Enable VA Profile and Disable eMIS for RI's

- modules/simple_forms_api/app/form_mappings/vba_21_0845.json.erb
This PR corrects a data mapping line where we weren't correctly checking a checkbox based on incoming data from the FE.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/891
> Simple Forms - Correctly check the Other checkbox on 21-0845

- modules/appeals_api/app/controllers/appeals_api/legacy_appeals/v0/legacy_appeals_controller.rb
- modules/appeals_api/app/swagger/legacy_appeals/v0/swagger.json
- modules/appeals_api/app/swagger/legacy_appeals/v0/swagger_dev.json
- modules/appeals_api/config/schemas/legacy_appeals/v0/params.json
- modules/appeals_api/spec/docs/legacy_appeals/v0_spec.rb
- modules/appeals_api/spec/requests/legacy_appeals/v0/legacy_appeals_controller_spec.rb
- modules/appeals_api/spec/requests/v1/appeals_controller_spec.rb
- modules/appeals_api/spec/support/shared_examples_for_icn_parameter_validation.rb
- spec/support/vcr_cassettes/caseflow/legacy_appeals_server_error.yml
- This is similar to #14874, but it implements the same behavior for the Legacy Appeals API v0 - the ICN parameter is now optional for requests using a veteran-scoped token, and remains required for representative- and system-scoped tokens.
- [API-32568](https://jira.devops.va.gov/browse/API-32568), which also includes Appealable Issues - I wasn't able to fit that part into this PR, so I'll make a follow-up PR for Appealable Issues.
- Added new specs
- Legacy Appeals API v0 (not yet in production)
> API-32568 Use ICN from token in Legacy Appeals API

- lib/simple_forms_api_submission/metadata_validator.rb
- spec/lib/simple_forms_api_submission/metadata_validator_spec.rb
This PR does a few things to the metadata validator:
1. Adds a zip code nationality flag so that we can default to `00000` even if we get a valid-looking zip code which is actually non-US (looking at you, Germany!).
2. Slightly modified the regex for first name and last name to accept a forward slash (`/`).
3. Inserts a dash (`-`) in 9 digit zip codes to make them 5+4 format and pass the regex.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/72750
Tests updated and passing.
> Add zip code flag to metadata validator

- config/features.yml
- lib/medical_records/client.rb
- spec/lib/medical_records/client_spec.rb
- Added the feature toggle for Care Summaries & Notes
- Added the "no-cache" header for Care Summaries & Notes
> Create Feature Flag for Care Summary and Notes
> 
> User Story: As a Medical Record team, we want to Create Feature Flag for Care Summary and Notes
> 
> GIVEN:
> WHEN:
> THEN:
> 
> Feature Flag Y/N ? Y
> 
> AC1 Feature Flag for Care Summary and Notes has been created
> AC2
> AC3
> AC4
> 
> Links to UCD:
> Sketch Link:
> Other Design Notes
> 
> Architectural Notes:
- Added a spec test for the "no-cache" header
- Feaure flag functionality will be tested on the frontend
> MHV-52911 Prep notes domain for production

- app/models/concerns/form526_claim_fast_tracking_concern.rb
- spec/sidekiq/evss/disability_compensation_form/submit_form526_all_claim_spec.rb
- This PR updates the 526 submission process to include a new special issue on claims eligible for EP400 Merge.
- I am part of the Claims Fast-Tracking crew's Employee Experience team.
- The new logic is behind the feature toggle `disability_526_ep_merge_api` which will remain disabled in production for the near future, until after EE team completes end-to-end testing.
- department-of-veterans-affairs/abd-vro#2148
- Added new rspec
- E2E testing in staging / VBMS UAT is planned once the VRO API server portion is complete.
* No user-visible behavior change
> Add special issue to EP400 merge-eligible claims

- modules/claims_api/app/controllers/claims_api/v2/veterans/power_of_attorney_controller.rb
- modules/claims_api/app/swagger/claims_api/v2/dev/swagger.json
- modules/claims_api/spec/requests/v2/veterans/power_of_attorney_request_spec.rb
- modules/claims_api/spec/requests/v2/veterans/rswag_power_of_attorney_spec.rb
- spec/support/schemas/claims_api/v2/errors/power_of_attorney/default.json
- Adds new lighthouse error handling to V2 POA
- Adds check for multiple representative_ids when poa_code is not for an organization
- Updates rswag and swagger documentation
- [API-32383](https://jira.devops.va.gov/browse/API-32383)
- Verified behavior in postman using `services/claims/v2/veterans/{veteranId}/power-of-attorney`:
- create local representative (1) with a poa code returned from any BGS lookup
- hit the endpoint and verify representative (1) is returned
- create another representative (2) with the same poa code and representative id as (1) but with a different first name
- hit the endpoint and verify representative (2) is returned
- create another representative (3) with the same poa code as (1) and (2) but with a different representative id
- hit the endpoint and verify a …
> API-32383 Handle duplicate poa entries

- config/features.yml
- modules/appeals_api/app/controllers/appeals_api/v2/decision_reviews/higher_level_reviews_controller.rb
- modules/appeals_api/app/controllers/appeals_api/v2/decision_reviews/supplemental_claims_controller.rb
- Ensures v3 of the form PDF is always used for Supplemental Claims and Higher-Level Reviews. These flags are already set to use v3 in production.
- Note that the NOD form never had a feature flag, but was updated months ago (there were no breaking changes to the form fields)
- Decision Reviews v2 and the Supplemental Claims v0 and Higher-Level Reviews v0 APIs.
> Remove feature flags for v3 appeals forms

- modules/claims_api/catalog-info.yaml
- Changes link to swagger doc for v1; 
- adds annotations for status. Right now it is pointed to the Vets API Dashboard on DataDog.
- release notes. Our altId is 'claims'
- more work is needed. We need to set up a synthetic test on dataDag and add our ID
- [API-30616](https://jira.devops.va.gov/browse/API-30616)
- not sure how I can test this yet
modified:   modules/claims_api/catalog-info.yaml
> API-30616-hub-updates-v1

- lib/gi/search_configuration.rb
- spec/lib/gi/search_configuration_spec.rb
- VFEP-1064: increase timeout for institution searches to fix DataDog errors
- increase search timeout from 2 seconds to 4 seconds
- VFEP Sustainment
- [vfep-1064](https://jira.devops.va.gov/browse/VFEP-1064)
- [github 15034](https://github.com/department-of-veterans-affairs/vets-api/issues/15034)
- DataDog errors related to timeout of institution searches
- Developer testing on local passed confirming searches work.  After deploy, on production check that DataDog errors go away.
timeouts on institution searches
> VFEP-1064: increase timeout for institution searches to fix DataDog errors

- app/controllers/v0/benefits_documents_controller.rb
The `BenefitsDocuments::Service.queue_document_upload` method expects a set of params, including a param called `tracked_item_ids` that should be an array of numbers. Vets-website is going to be sending this param as stringified JSON so that vets-api can parse the param value into an array of numbers. Adding a check to make sure that the value of `params[:tracked_item_ids]` is an instance of the String class, just in case we want to be able to send something else in the future
`params[:tracked_item_id]` should look like this before the conversion:
```ruby
puts params[:tracked_item_id] # => "[123,456]"
```
- department-of-veterans-affairs/va.gov-team#72886
(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do …
> Converting tracked_item_ids param to an array

- lib/forms/schemas/forms.json
- modules/va_forms/app/models/va_forms/form.rb
- modules/va_forms/app/sidekiq/va_forms/form_builder.rb
- modules/va_forms/spec/sidekiq/form_builder_spec.rb
Yesterday's deploy of #15045 brought to light the following issues with the `VAForms::FormBuilder` job. This PR resolves all of them.
1. The return of a `nil` `url` for a couple of new and invalid records broke the API contract between the VA Forms API and the `GET /v0/forms` endpoint, causing 500 errors on that endpoint. The change in this PR ensures that a `url` is always set, even if that url returns a 404.
2. The previous changes allowed a `sha256` to be `nil`. Our [VA Forms API documentation](https://developer.va.gov/explore/api/va-forms/docs?version=current) already states (and previously stated) that a `sha256` can be null. Therefore, this PR updates the schema validation yaml file that `GET /v0/forms` endpoint uses to validate the VA Forms API response, to allow for a string OR …
> API-32635: `VAForms::FormBuilder` Job Fixes

- app/services/sign_in/redirect_url_generator.rb
- lib/saml/post_url_service.rb
- spec/lib/saml/post_url_service_spec.rb
- spec/services/sign_in/redirect_url_generator_spec.rb
- Log redirects to terms-of-use page
- department-of-veterans-affairs/va.gov-team#72845
- login with a user that does not have terms accepted
- check logs for  `Redirecting to /terms-of-use,  {:type=>:sis}`
- Repeat for `ssoe` 
- `Redirecting to /terms-of-use,  {:type=>:ssoe}`
Terms of use, authentication
> [72845] Log terms-of-use redirects

- modules/va_forms/app/sidekiq/va_forms/form_builder.rb
- modules/va_forms/spec/sidekiq/form_builder_spec.rb
This PR:
1. Updates the `sidekiq_retries_exhausted` block in the `VAForms::FormBuilder` job to log more specific information about the job failure, adds error handling for the block itself, and fixes references to the form data from the job `args`.
2. Updates the logic for deleted form records in the `VAForms::FormBuilder` job by not attempting to fetch the PDF if the form is marked deleted (and setting `valid_pdf: false` and `sha256: nil` on deleted records by default). This change is being made because 43 out of 55 of our recurring failing `VAForms::FormBuilder` jobs are deleted records, and they are all failing due to invalid URLs. Their URLs will never be valid again, but the job did not take this into account previously. I can't think of a reason why we would want to continually …
> API-32635: `VAForms::FormBuilder` Job Improvements

- app/sidekiq/lighthouse/pension_benefit_intake_job.rb
- spec/sidekiq/lighthouse/pension_benefit_intake_job_spec.rb
- In order to track retry exhaustions for the Pensions Lighthouse submission, adds a StatsD metric to `Lighthouse::PensionBenefitIntakeJob`.
- [Link to ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70462)
- Temporarily set retries to 1, then added an error to `Lighthouse::PensionBenefitIntakeJob`.
- Confirmed that the exhaustion was triggered.
Pensions Benefits
> Add StatsD exhaustion metric to Pensions

- lib/map/sign_up/service.rb
- spec/lib/map/sign_up/service_spec.rb
Update provisioner logging to only log a success if the parsing is successful. Add a parsing error log.
- department-of-veterans-affairs/va.gov-team#73468
- This is hard to test without being on the VA network and our mocks only mock a successful response.
- Updated specs to cover parsing error case
MAP, Terms of use
> [73468] Update MAP provisioner logging to account for parsing errors

- modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb
- modules/simple_forms_api/spec/requests/v1/uploads_spec.rb
This PR limits which kinds of preparers go through Benefits Intake API vs the intent API. If the preparer is a third party they go through Benefits Intake API, even if they are logged in. Only if the preparer is a first party ('VETERAN' or 'SURVIVING_DEPENDENT') and logged in would they go through the intent API.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/902
Tests are updated and passing.
> Simple Forms 21-0966 third parties go through Benefits Intake API

- .github/CODEOWNERS
- This PR removes the defunct team [vfs-benefits-delivery](https://github.com/orgs/department-of-veterans-affairs/teams/vfs-benefits-delivery) from CODEOWNERS, in preparation for removing that GitHub team itself.
- `vfs-benefits-delivery` is not an active VFS team. As far as we could ascertain in this [Slack thread](https://dsva.slack.com/archives/C04KW0B46N5/p1704219957189839), "Benefits Delivery" refers to a project circa 2022 through early 2023 called RRD (Rapid Ready for Decision) that split into multiple current-day teams. The members of `vfs-benefits-delivery` are now on the Employee Experience and Disability Experience teams.
- I am on the Employee Experience team, which is responsible for the small remainder of RRD code still in vets-api. We have …
> Remove defunct team vfs-benefits-delivery from codeowners

- modules/appeals_api/app/swagger/higher_level_reviews/v0/swagger.json
- modules/appeals_api/app/swagger/higher_level_reviews/v0/swagger_dev.json
- modules/appeals_api/app/swagger/notice_of_disagreements/v0/swagger.json
- modules/appeals_api/app/swagger/notice_of_disagreements/v0/swagger_dev.json
- modules/appeals_api/app/swagger/supplemental_claims/v0/swagger.json
- modules/appeals_api/app/swagger/supplemental_claims/v0/swagger_dev.json
- modules/appeals_api/spec/factories/higher_level_reviews.rb
- modules/appeals_api/spec/factories/notice_of_disagreements.rb
- modules/appeals_api/spec/factories/supplemental_claims.rb
- modules/appeals_api/spec/fixtures/higher_level_reviews/v0/valid_200996.json
- modules/appeals_api/spec/fixtures/higher_level_reviews/v0/valid_200996_extra.json
- modules/appeals_api/spec/fixtures/higher_level_reviews/v0/valid_200996_minimum.json
- modules/appeals_api/spec/fixtures/notice_of_disagreements/v0/valid_10182.json
- modules/appeals_api/spec/fixtures/notice_of_disagreements/v0/valid_10182_extra.json
- modules/appeals_api/spec/fixtures/notice_of_disagreements/v0/valid_10182_minimum.json
- modules/appeals_api/spec/fixtures/supplemental_claims/v0/valid_200995.json
- modules/appeals_api/spec/fixtures/supplemental_claims/v0/valid_200995_extra.json
This is in support of API-32864, which involves validating the ICNs that we receive in OAuth tokens against the data we receive (to make sure people with veteran-scoped tokens can access only their own data, even if they can provide PII for someone else).
This makes two changes to support updates to ICN validation:
**First:**
The segmented appeals APIs use OAuth, so we use [this cassette with a successful token validation response](https://github.com/department-of-veterans-affairs/vets-api/blob/3e270c711dd14a2b2e49d98d5e012ff481261412/spec/support/vcr_cassettes/token_validation/v3/indicates_token_is_valid.yml#L89) with every successful request in our specs. This means that in every spec, the ICN `1012667145V762142` is returned as the veteran's ICN from the token. To confirm access is …
> Update ICNs in appeals form data fixtures

- modules/appeals_api/app/controllers/appeals_api/higher_level_reviews/v0/higher_level_reviews_controller.rb
- modules/appeals_api/app/controllers/appeals_api/notice_of_disagreements/v0/notice_of_disagreements_controller.rb
- modules/appeals_api/app/controllers/appeals_api/supplemental_claims/v0/supplemental_claims_controller.rb
- modules/appeals_api/app/controllers/concerns/appeals_api/openid_auth.rb
- modules/appeals_api/app/swagger/higher_level_reviews/v0/swagger.json
- modules/appeals_api/app/swagger/higher_level_reviews/v0/swagger_dev.json
- modules/appeals_api/app/swagger/notice_of_disagreements/v0/swagger.json
- modules/appeals_api/app/swagger/notice_of_disagreements/v0/swagger_dev.json
- modules/appeals_api/app/swagger/supplemental_claims/v0/swagger.json
- modules/appeals_api/app/swagger/supplemental_claims/v0/swagger_dev.json
In preparation for adding validations of token ICNs to these controllers, this PR removes the last of the inheritance relationships from Decision Reviews v2 in the NOD v0, HLR v0, and SC v0 APIs.
The goal here is to minimize the number of special cases required when validating submissions to these APIs based on the ICN in the OAuth token. Note that inheritance has already been removed from the other segmented APIs and from the evidence submission controllers for these APIs.
I made this PR separately from the actual changes for API-32864 because I figured this would make things easier to review. Behavior should not be changing at all with this PR.
- This is to support [API-32864](https://jira.devops.va.gov/browse/API-32864)
- No changes to specs, examples still pass
- Notice of …
> API-34864 Remove inheritance relationships in appeals segemented API controllers

- config/features.yml
- add new feature flag which will gate new API calls to `/contention-classification/claim-linker`
- https://github.com/department-of-veterans-affairs/vagov-claim-classification/issues/347
- n/a
> add new feature flag for claim linker

- Gemfile.lock
- app/controllers/v0/post911_gi_bill_statuses_controller.rb
- config/features.yml
- spec/controllers/v0/post911_gi_bill_statuses_controller_spec.rb
I'm a developer on the VA-IIR team.  We do not specifically own this project, but have been tasked to address issues in orphaned or lightly maintained projects.
The controller action, ` V0::Post911GIBillStatusesController#show` will will call a `render_error_json` function if a request to a service fails.  Depending on the failure, we can raise different Exception types.  If none of those special cases are satisfied, the default failure is to raise `Common::Exceptions::InternalServerError`.  
In that fallback case, we are not supplying the required `exception` argument to `InternalServerError.initialize()`, so an unhandled exception happens, which pops up on Sentry:
This PR includes code to create the required `exception` argument pass it to `InternalServerError.initialize()`.  Out of an …
> VA-IIR-285: provide an exception when raising InternalServerError

- config/features.yml
This [PR](https://github.com/department-of-veterans-affairs/vets-api/pull/15075) included a feature toggle.  `config/features.yml` has an error: [link](https://github.com/department-of-veterans-affairs/vets-api/blob/753e44753b4b5369f3cdf6ca0aee75b94a052bb9/config/features.yml#L745) the typo is `enabled_in_development`.  The key name is actually `enable_in_development`
> enabled_in_development -> enable_in_development

- config/features.yml
- Add representatives portal feature toggle
- [#72959](https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/72959)
- Feature toggle not being used
- None
- None
- Feature toggle enables the frontend of the representatives content (currently the dashboard)
- Feature toggle could enable backend code of representatives developed and built
- How do we feel about the toggle names: representatives_portal_frontend and representatives_portal_api
> 72959 Add representatives portal feature toggle

- modules/my_health/app/controllers/my_health/v1/threads_controller.rb
- modules/my_health/spec/request/v1/threads_request_spec.rb
- spec/support/schemas/message_threads_no_messages.json
- spec/support/vcr_cassettes/sm_client/threads/gets_threads_in_a_folder_no_messages.yml
**GIVEN** sending a request to MHV SM Patient API to retrieve a list of threads for a folder
**WHEN** a folder contains no threads/messages
**THEN** MHV SM API returns "400 Bad Request" error
**AND** vets-api just passes it to vets-website front end.
The error described above is not an accurate representation of an error, since the request is well structured and complies with documentation. A more standard pattern across API best practices is to return status 200 and a body of an empty array, since no values where found contained in that folder. "404 Not Found" is also not appropriate as we are passing `:folderId` in the request and the folder does exist. 
Main benefits:
clearing front end console of irrelevant error logging
reducing unnecessary error logging noise In DataDog for better …
> MHV 53459 Secure Messaging Handle "No messages in the requested folder" error

- lib/form1010_ezr/service.rb
- spec/lib/form1010_ezr/service_spec.rb
Switch from using `submit_form` to `submit_sync` for 1010ezr datadog statistics
I work for the 1010 team.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/73493
1010ezr form
> Stop using submit_form in 1010EZR datadog dashboard

- app/controllers/v0/benefits_claims_controller.rb
- spec/controllers/v0/benefits_claims_controller_spec.rb
- added claim type logging to `app/controllers/v0/benefits_claims_controller.rb`
- added rspec test to `spec/controllers/v0/benefits_claims_controller_spec.rb`
- department-of-veterans-affairs/va.gov-team#66043
- Manually verified that it logs claim type data
- added RSpec test and made sure that it passed
Adds additional logging to the Claims Status Tool
> [BE] CST: 66043 Log claim types to data dog

- app/controllers/v0/benefits_claims_controller.rb
- spec/controllers/v0/benefits_claims_controller_spec.rb
@RachalCassity @jerekshoe 
This amends the approved PR that was merged this morning (1/17/2024): https://github.com/department-of-veterans-affairs/vets-api/pull/15135
- added claim_id to logging in `app/controllers/v0/benefits_claims_controller.rb`
- updated related rspec test in `spec/controllers/v0/benefits_claims_controller_spec.rb`
- department-of-veterans-affairs/va.gov-team#66043
- Manually verified that it logs claim_id to log data
- updated RSpec test and made sure that it passed
Adds additional logging to the Claims Status Tool
> [BE] CST: 66043 added claim_id to claim type data being logged

- .github/PULL_REQUEST_TEMPLATE.md
When reviewing PRs, it's sometimes hard to know whether modified code is behind a feature flag or not. This piece of info impacts the code review. The Platform CoP was discussing how to have a better understanding of whether code is behind a flipper or not and we thought modifying the template was a good first step. 
- Slack conversation: https://dsva.slack.com/archives/C0460N83Y9G/p1704215947797249
- CoP meeting notes: https://vfs.atlassian.net/wiki/spaces/BCP/pages/2890563598/1+8+24#2%EF%B8%8F%E2%83%A3--Discussion
- This is what it will look like formatted: https://github.com/department-of-veterans-affairs/vets-api/blob/dfecc31f0283e1305cbf87928e8d8d22fd34cfd5/.github/PULL_REQUEST_TEMPLATE.md
The PR template for vets-api.
> Include more flipper questions in template

- modules/va_forms/app/services/va_forms/slack/messenger.rb
- modules/va_forms/app/sidekiq/va_forms/form_builder.rb
- modules/va_forms/spec/services/va_forms/slack/messenger_spec.rb
This PR updates the `VAForms::Slack::Messenger` to check the contents of the `Settings.va_forms.slack.enabled` setting before triggering any Slack notification (or not triggering a notification, if the value is `false`). Previously the `va_forms` module relied on engineers checking the Slack setting before every call to `VAForms::Slack::Messenger`, and so we had places where Slack notifications were being sent without checking the setting.
[API-33544](https://jira.devops.va.gov/browse/API-33544)
Ran the affected jobs locally to ensure they were successful, and added a new unit test for `VAForms::Slack::Messenger` for when the Slack enabled setting is set to `false`.
None
This PR impacts the `va_forms` module only, which is owned by my team.
No specific feedback requested.
> API-33544: Ensure All Slack Messages Sent by Forms API Check the `slack.enabled` Setting

- app/controllers/v0/pension_claims_controller.rb
- Added in previously missed param to pension_claims_controller#log_validation_error_to_metadata
- This is a bug introduced in a recent PR where we make a reference to a failed claim in a helper function, but forgot to pass in the claim data as a parameter.
- The fix is to pass the claim data to the helper function to fix the broken reference.
- Pension benefits team to own this code.
- [*Link to previous change of the code/bug (if applicable)*](https://github.com/department-of-veterans-affairs/vets-api/pull/15110)
- *If this …
> pass failed claim data to log_validation_error_to_metadata

- .github/workflows/code_checks.yml
- with #15070 merged, we no longer need to ignore this [CVE](https://nvd.nist.gov/vuln/detail/CVE-2023-49090), as it was fixed in carrierwave 3.0.5
> Remove statement to ignore CVE

- app/controllers/v0/ppiu_controller.rb
- app/controllers/v0/profile/ch33_bank_accounts_controller.rb
- spec/controllers/v0/profile/ch33_bank_accounts_controller_spec.rb
- spec/controllers/v0/profile/direct_deposits/disability_compensations_controller_spec.rb
- spec/requests/ppiu_request_spec.rb
The following warning was discovered in Datadog...
```
Job arguments to VANotifyDdEmailJob do not serialize to JSON safely. This will raise an error in
Sidekiq 7.0. See https://github.com/mperham/sidekiq/wiki/Best-Practices or raise an error today
by calling `Sidekiq.strict_args!` during Sidekiq initialization.
```
Updates Sidekiq args to simple JSON types - replaced symbols with strings.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/73346
> Update Sidekiq args to simple JSON types

- config/betamocks/services_config.yml
- config/settings.yml
- spec/support/vcr.rb
- This PR is to remove the oidc settings from the settings.yml so that the depending vsp-infra-application-manifests PR to remove okta settings can be merged.
- Lighthouse Team Pivot!
- 
- https://jira.devops.va.gov/browse/API-21864
- https://jira.devops.va.gov/browse/API-32302
> API-32302 delete remaining okta settings

- modules/claims_api/app/controllers/claims_api/v2/blueprints/power_of_attorney_blueprint.rb
- modules/claims_api/app/swagger/claims_api/v2/dev/swagger.json
- modules/claims_api/app/swagger/claims_api/v2/production/swagger.json
- modules/claims_api/spec/requests/v2/veterans/power_of_attorney_request_spec.rb
- spec/support/schemas/claims_api/veterans/power-of-attorney/get.json
- This pr updates the nested `{phone: {number: ""}}`  to `phoneNumber: ""` in the active POA V2 endpoint
- [API-33396](https://jira.devops.va.gov/browse/API-33396)
- Tested locally with Postman and a BGS tunnel to staging
Impact is to the POA V2 show endpoint
> API-33396 Update nested phone to phone_number for POA V2

- modules/claims_api/app/swagger/claims_api/v2/dev/swagger.json
- modules/claims_api/app/swagger/claims_api/v2/production/swagger.json
- modules/claims_api/spec/support/rswag_config.rb
- Update productionOauth and sandboxOauth descriptions to be:
"This API uses OAuth 2 with the client credential grant flow. [More info](https://developer.va.gov/explore/api/benefits-claims/client-credentials)",
[API-32555](https://jira.devops.va.gov/browse/API-32555)
modified:   modules/claims_api/spec/support/rswag_config.rb
> API-32555-fix-oauth-link-oas 

- app/models/form_profiles/va_1010ezr.rb
- spec/models/form_profile_spec.rb
Fail silently if EnrollmentEligibility service is not working so that the rest of the data can still be prefilled
1010 team
https://github.com/department-of-veterans-affairs/va.gov-team/issues/73840
will check sentry logs in production
1010ezr form prefill
> Fail silently if EnrollmentEligibility service is not working

- modules/vye/app/models/vye/pending_document.rb
- modules/vye/spec/factories/vye/pending_documents.rb
- modules/vye/spec/models/vye/pending_document_spec.rb
Starting development for **VYE (Verify Your Enrollment)** API.
- This API is part of the migration of WAVE (https://www.gibill.va.gov/wave/vba/) from a standalone Java app to the main va.gov Ruby or Rails site.
- It's being done to bring the app to a code base when development is more active.
- This pull request does the following:
- adds the pending documents model
- 
https://jira.devops.va.gov/browse/VYE-111
As:
VYE Developer
I need:
To create an API GET request
So that: 
Enrollment Verification status and Pending Documents are retrieved from the VYE database for the specified user when the API is called on
Needs to handle the edge case where the user is not enrolled in Chap 30/1606/1607 and there is no information to retrieve.
Acceptance Criteria: 
Enter the acceptance …
> Added PendingDocument model

- config/features.yml
This PR removes the 'va_online_scheduling_acheron_service' feature toggle.
fixes https://github.com/department-of-veterans-affairs/va.gov-team/issues/63663
N/A
VAOS
> 63663 Remove any references of va_online_scheduling_acheron_service feature toggle

- .github/CODEOWNERS
- Gemfile
- config/routes.rb
- lib/github_authentication/coverband_reporters_web.rb
- `coverband` starts on `require` and was being required in `routes.rb` so every file that got initialized before `routes.rb` would not have data.
- Move `coverband` to `production` and `development` gem group so it gets required when `config/boot` is run.
- remove `octo-identity` from `lib/github_authentication` `CODEOWNERS`
- Start server
- Navigate to http://localhost:3000/coverband. You should see data being collected on files
Coverband
> Fix coverband initialization

- modules/claims_api/app/swagger/claims_api/v2/dev/swagger.json
- modules/claims_api/app/swagger/claims_api/v2/production/swagger.json
- modules/claims_api/spec/requests/v2/veterans/rswag_evidence_waiver_spec.rb
* Updates ID shown in docs
* Compiles dev and production docs to show the change. 
[API-31570](https://jira.devops.va.gov/browse/API-31570)
modified:   modules/claims_api/spec/requests/v2/veterans/rswag_evidence_waiver_spec.rb
> Updates ID in parameters for 5103 docs, compiles docs to reflect change

- app/controllers/v0/benefits_claims_controller.rb
We want to add logging to DataDog to identify what percentage of users don't have a birls_id or a file_number. We have identified issues related to these users trying to perform common actions with our APIs, but we need to collect more information to determine how many users fall into this category. We would also like to see if there is a correlation between a user lacking a birls_id and a file number. This logging should not capture any PII
- department-of-veterans-affairs/va.gov-team/issues/74138
We may not be supporting users without birls_ids or file numbers in the future via modifications to our Pundit policy, so this code may be short lived …
> [CST] Adding logging when user doesn't have veteran identifiers

- modules/mobile/spec/models/lighthouse_assertion_spec.rb
- modules/mobile/spec/request/immunizations_request_spec.rb
- modules/mobile/spec/request/locations_request_spec.rb
- modules/mobile/spec/request/v1/immunizations_request_spec.rb
- modules/mobile/spec/services/lighthouse_health_service_spec.rb
Some mobile specs that use Lighthouse CCG authentication uses this line to spoof authentication.
allow(File).to receive(:read).and_return(rsa_key.to_s)
This is too generic and causes issues when trying to use files that are not rsa keys
https://github.com/department-of-veterans-affairs/va-mobile-app/issues/7614 …
> Mobile - Rspec stubbing File bug fix

- app/services/login/user_verifier.rb
- spec/services/login/user_verifier_spec.rb
This PR updates the new user creation log - `[Login::UserVerifier] New VA.gov user, type=#{login_type}, broker=#{auth_broker}` to also include the user's ICN as part of the log's extra context.
- [Add ICN to userverifier log](https://github.com/orgs/department-of-veterans-affairs/projects/1137/views/1?pane=issue&itemId=50548481)
- To test, perform an authentication with an IAL2/LoA3 user that does not already have a record on your vets-api instance, you should see the following log line
```ruby
Rails -- [Login::UserVerifier] New VA.gov user, type=logingov, broker=sis -- { :icn => "1008709396V637156" }
```
- If the new account isn't IAL2/LoA3 then it will not possess an ICN, resulting in a `nil` value
```ruby
Rails -- [Login::UserVerifier] New VA.gov user, type=idme, broker=sis -- { :icn …
```
> [74033] User Verifier ICN log

- modules/debts_api/app/controllers/debts_api/v0/financial_status_reports_calculations_controller.rb
- modules/debts_api/config/routes.rb
- modules/debts_api/lib/debts_api/v0/fsr_form_transform/enhanced_expense_calculator.rb
- modules/debts_api/lib/debts_api/v0/fsr_form_transform/expense_calculator.rb
- modules/debts_api/lib/debts_api/v0/fsr_form_transform/old_expense_calculator.rb
- modules/debts_api/spec/fixtures/pre_submission_fsr/enhanced_fsr_expenses.json
- modules/debts_api/spec/fixtures/pre_submission_fsr/non_enhanced_fsr_expenses.json
- modules/debts_api/spec/lib/debt_api/v0/fsr_form_transform/expense_calculator_spec.rb
- modules/debts_api/spec/request/debts_api/v0/financial_status_reports_calculations_controller_spec.rb
Porting the `getAllExpenses` and `getMonthlyExpenses` functions over from [vets-website](https://github.com/department-of-veterans-affairs/vets-website/blob/1b067a60ade8d458a24ac798e29984cbd57e0c91/src/applications/financial-status-report/utils/calculateExpenses.js#L90) to vets-api. 
- [72791](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/72791)
- specs and features added.
None currently. Will eventually impact the FSR submission process
> Expense Calculator

- app/controllers/v0/users_controller.rb
- Updates the `UsersController#show` method to no longer invoke additional logging via the `wrap_with_logging` method.
- These logs can be found by querying `@payload.action:"Loading User"` [in Datadog](https://vagov.ddog-gov.com/logs?query=%40payload.action%3A%22Loading%20User%22%20&cols=host%2Cservice&index=%2A&messageDisplay=inline&refresh_mode=sliding&stream_sort=desc&viz=stream&from_ts=1706049520100&to_ts=1706050420100&live=true)
- [Issue ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/73207)
- [Slack discussion](https://dsva.slack.com/archives/C053U7BUT27/p1706037175577139)
- Performed authentication and requested `/v0/user` route - confirmed "Loading User" log is not generated
> [73207] removes UsersController #show logging

- modules/vaos/app/services/vaos/v2/appointments_service.rb
Logging of missing ICNs is no longer needed. Removed missing ICN logging from AppointmentsService#get_appointments and AppointmentService#get_appointment methods.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/71272
> VAOS Remove Missing ICN Logging

- app/controllers/v0/benefits_claims_controller.rb
- spec/controllers/v0/benefits_claims_controller_spec.rb
Adding a field to the response of `V0::BenefitsClaimsController#show` to indicate whether the current_user an upload files to EVSS or not. We are aware of an issue where users without BIRLS IDs are unable to upload documents to EVSS. We are exploring options to modify the Claim Status Tool UI to indicate to these users that their uploads will not work while we work on a more permanent fix
- department-of-veterans-affairs/va.gov-team/issues/74409
Added a new spec to test that the `canUpload` fields value is correct and that the path to get the `canUpload`value is correct as well
- *Describe the steps required to verify your changes are working as expected. Exclusively stating …
> [CST] Add `canUpload` field to BenefitsClaimsController#show response

- config/settings.yml
- spec/factories/maintenance_windows.rb
- spec/sidekiq/pager_duty/poll_maintenance_windows_spec.rb
- eMIS is being decommissioned. We've stopped calling it from vets-api. This PR removes the PagerDuty eMIS references. There are more PRs to come with more eMIS deletion as part of the epic https://github.com/department-of-veterans-affairs/va.gov-team/issues/63326
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/72650
No new code. Passing specs is sufficient for testing.
None. Only removes emis from PagerDuty configuration in vets-api.
> remove and replace emis PagerDuty references

- .github/CODEOWNERS
I noticed in https://github.com/department-of-veterans-affairs/vets-api/pull/15233 that there was no codeowner for the `spec/fixtures/pdf_fill/21P-527EZ` path. This PR adds an owner. The [pensions team](https://github.com/orgs/department-of-veterans-affairs/teams/pensions) is responsible for that form. 
✅ CODEOWNERS file is valid
> Add missing path in CODEOWNERS

- lib/simple_forms_api_submission/metadata_validator.rb
- spec/lib/simple_forms_api_submission/metadata_validator_spec.rb
This PR fixes a subtle bug in the Metadata Validator where, if `nil` was given for a zip code, it would fail before the nil check. Just swapping the lines should resolve the issue. However, I failed to find a satisfactory way to test this change so I'd love any feedback on a reasonable way to test it. If we can't think of anything, I'm ok merging without a test exercising the precise bug, even though it is suboptimal.
> Fix metadata validator nil zip code bug

- app/models/concerns/form526_claim_fast_tracking_concern.rb
- app/sidekiq/evss/disability_compensation_form/submit_form526.rb
- lib/sidekiq/form526_job_status_tracker/job_tracker.rb
- A not null violation error is raised within the `Form526JobStatusTracker` when a job status update is attempted for a nil submission ID
- The submission ID in the job tracker's "on error" handlers is populated by the `with_tracking` block, outside of which occur both `prepare_for_evss!` and `send_post_evss_notifications!` service calls
- Analyzing stack traces of raised errors indicated failures directly attributed to outage exceptions when calling EVSS's `/ratedDisabilities` endpoint in the `prepare_for_evss!` step
- Relocating calls to both `prepare_for_evss!` and `send_post_evss_notifications!` within the `with_tracking` block should address the nil submission ID error
Error handling has been refactored and conditional logic introduced to:
1. return early if an exception is raised …
> DBEX: adjust with_tracking of 526 Submission

- config/sidekiq.yml
We recently encountered an issue where some of our scheduled Sidekiq jobs were not executing as planned. Upon investigating our logs, we identified `RTT warning can signal CPU saturation` [warnings](https://vagov.ddog-gov.com/logs?query=host%3Avets-api-sidekiq-%2A%20env%3Aeks-prod%20-status%3Ainfo%20%22Last%20RTT%20readings%20were%20%22%20&cols=host%2Cservice&index=%2A&messageDisplay=inline&refresh_mode=sliding&stream_sort=time%2Casc&viz=stream&from_ts=1703528705076&to_ts=1706120705076&live=true). These warnings suggest that our system is experiencing CPU …
> Adjust Sidekiq Concurrency for Optimal Performance

- modules/claims_api/app/swagger/claims_api/v2/dev/swagger.json
- modules/claims_api/app/swagger/claims_api/v2/production/swagger.json
- modules/claims_api/spec/requests/v2/veterans/rswag_power_of_attorney_spec.rb
- This pr adds an example ICN to the V2 active POA swagger docs
- [API-33634](https://jira.devops.va.gov/browse/API-33634)
- this is only an rswag change, so I looked at the local doc preview to verify
| Before | After |
|----|----|
|![image](https://github.com/department-of-veterans-affairs/vets-api/assets/144135615/cf2c3e3d-f7b7-4833-81e2-88a7fb6ce8e3)|![image](https://github.com/department-of-veterans-affairs/vets-api/assets/144135615/3c4503bb-b997-4cdd-a92b-e060e23f948d)|
This should only impact the developer docs
> API-33634 Add example ICN to active POA rswag

- modules/mobile/app/sidekiq/mobile/v0/vet360_linking_job.rb
- modules/mobile/spec/sidekiq/vet360_linking_spec.rb
This removes raising an error from the vet360 linking job in order to not clog up the dashboard and avoid making it look like the job failed when in fact it did not
https://github.com/department-of-veterans-affairs/va-mobile-app/issues/7653
Existing tests cover the errors
> Mobile: Vet360 Linking log error rather than raise

- modules/appeals_api/app/controllers/appeals_api/notice_of_disagreements/v0/notice_of_disagreements_controller.rb
- modules/appeals_api/app/controllers/appeals_api/supplemental_claims/v0/supplemental_claims_controller.rb
- modules/appeals_api/app/models/appeals_api/notice_of_disagreement.rb
- modules/appeals_api/app/models/appeals_api/supplemental_claim.rb
- modules/appeals_api/app/serializers/appeals_api/notice_of_disagreements/v0/notice_of_disagreement_serializer_with_pii.rb
- modules/appeals_api/app/serializers/appeals_api/supplemental_claims/v0/supplemental_claim_serializer_with_pii.rb
- modules/appeals_api/spec/models/notice_of_disagreement_spec.rb
- modules/appeals_api/spec/models/supplemental_claim_spec.rb
- modules/appeals_api/spec/requests/notice_of_disagreements/v0/notice_of_disagreements_controller_spec.rb
- modules/appeals_api/spec/requests/supplemental_claims/v0/supplemental_claims_controller_spec.rb
- modules/appeals_api/spec/serializers/notice_of_disagreement/v0/notice_of_disagreement_serializer_with_pii_spec.rb
- modules/appeals_api/spec/serializers/supplemental_claims/v0/supplemental_claim_serializer_with_pii_spec.rb
This is a follow-up to #15166 - it makes the same changes to the NOD and SC APIs that I made to the HLR API in that PR.
Note that since we're not enabling index endpoints, I took care of all the index-related stuff in #15166, so there's nothing related to index endpoints here.
- [API-32864](https://jira.devops.va.gov/browse/API-32864) is the ticket that these changes support
- Notice of Disagreements API v0
- Supplemental Claims API v0
(neither of these is yet in production)
> API-32864 Finish prep for token ICN validation in Notice of Disagreements and Supplemental Claims APIs

- config/features.yml
In this [ticket](https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/gh/department-of-veterans-affairs/va.gov-team/74147) we were asked to remove the ```sign_in_page_and_modal_experiment_lga``` feature flag from ```vets-api``` as we are no longer using it.
> removes experiemnt lga feature flag

- lib/hca/enrollment_eligibility/service.rb
- spec/lib/hca/enrollment_eligibility/service_spec.rb
Return nil if invalid date passed to parse_es_date, log the invalid date to PII logs table
- *This work is behind a feature toggle (flipper): no
1010 team
https://github.com/department-of-veterans-affairs/va.gov-team/issues/73842
will check logs in production
1010ezr form
> Return nil if invalid date passed to parse_es_date

- docs/setup/native.md
When setting up Vets API, devs have came across similar schema issues. These issues include duplicate tables when running migrations.  Looking through the support channel, I noticed that most issues have been resolved by running` rails db:setup`. The setup command has been added to the docs after the `bundle install` instructions to help developers in the future. 
**Slack threads**
- https://dsva.slack.com/archives/CBU0KDSB1/p1700077909276959?thread_ts=1699987358.970369&cid=CBU0KDSB1
- https://dsva.slack.com/archives/CBU0KDSB1/p1611158721200300?thread_ts=161 …
> Add db:setup to vets-api instructions to reduce setup errors

- modules/debts_api/lib/debts_api/v0/vha_fsr_form.rb
- modules/debts_api/spec/fixtures/fsr_forms/vha_fsr_form.json
VBS want box 37B of their FSR to contain a timestamp instead of a date.
- None
- Specs green
VHA financial status reports
Box 37B of the vha financial status report appears as a timestamp and not as a date.
> 71883 Change vha FSRs veteranDateSigned to a timestamp

- config/settings.yml
- lib/map/security_token/configuration.rb
- lib/map/security_token/service.rb
- spec/lib/map/security_token/service_spec.rb
- This PR adds a MAP Security token client for `appointments`, and maps it to an appropriate client_id
- 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/74157
MAP Service
> [74157] Adding appointments to MAP security token service

- config/features.yml
This adds a feature flag toggle,  **va_online_scheduling_clinic_filtering**, for planned work on adding the ability to turn clinic filtering by stop codes on or off.
The feature toggle flag will be removed once the clinic filtering has been implemented and tested, estimated 2 to 3 weeks.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/74659
> VAOS Add Feature Flag Toggle for Clinic Filtering

- config/features.yml
Remove all traces of household v2 flipper
[#62516](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/62516)
- manual
- None
> 62516 - remove HHV2 feature flags

- config/features.yml
- adding feature flags to control display of content and functionality 30 days (`t30`) and 5 days (`t5`) prior to transition
- https://jira.devops.va.gov/browse/MHV-53639
- N/A
Primarily is being adde for My Health - Secure Messaging
> MHV-53639 Feature flags for Facility 556 transition to Cerner (North Chicago)

- app/sidekiq/evss/disability_compensation_form/submit_form526.rb
- Marks a BIRLS ID as being tried when a non-retryable error is encountered, thus preventing an EVSS submission job from continuously running when the `prepare_for_evss!` call within the `perform` method on L94 raises a non-retryable error.
- Remedies updates made in [PR #15195](https://github.com/department-of-veterans-affairs/vets-api/pull/15195)
- Addresses [a report](https://dsva.slack.com/archives/C04KW0B46N5/p1706491399988779) of '"submitform 526 Worker Results" spiking something labeled "non-retryable errors"' and [another report](https://dsva.slack.com/archives/C04KW0B46N5/p1706549548179909?thread_ts=1706491399.988779&cid=C04KW0B46N5) of 'duplicates of the same 3 claim ids happening over and over.'
- Corresponding spec runs successfully after addition
Form 526 Submission attempts …
> DBEX: mark BIRLS ID as tried if non-retryable error raised

- app/sidekiq/benefits_intake_status_job.rb
This PR makes our StatsD a bit more sophisticated such that we can now track metrics on individual form types, rather than all forms that pass through the Benefits Intake Status Job. This will allow us to re-work the dashboard to rely on metrics instead of other data sources and display Pending forms in addition to the success and failed ones.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/976
> Track form submissions by id in DataDog with statsd metrics

- modules/claims_api/app/controllers/claims_api/v2/blueprints/power_of_attorney_blueprint.rb
- modules/claims_api/app/swagger/claims_api/v2/dev/swagger.json
- modules/claims_api/app/swagger/claims_api/v2/production/swagger.json
- modules/claims_api/spec/requests/v2/veterans/power_of_attorney_request_spec.rb
- modules/claims_api/spec/requests/v2/veterans/rswag_power_of_attorney_spec.rb
- spec/support/schemas/claims_api/veterans/power-of-attorney/post.json
- This pr makes the `id` attribute conditional in the POA V2 blueprint
- [API-33721](https://jira.devops.va.gov/browse/API-33721)
-Tested locally with postman
> API-333721 remove id attribute from active POA V2 endpoint

- modules/appeals_api/app/controllers/appeals_api/supplemental_claims/v0/supplemental_claims_controller.rb
- modules/appeals_api/app/swagger/higher_level_reviews/v0/swagger.json
- modules/appeals_api/app/swagger/higher_level_reviews/v0/swagger_dev.json
- modules/appeals_api/app/swagger/supplemental_claims/v0/swagger.json
- modules/appeals_api/app/swagger/supplemental_claims/v0/swagger_dev.json
- modules/appeals_api/spec/docs/higher_level_reviews/v0_spec.rb
- modules/appeals_api/spec/docs/supplemental_claims/v0_spec.rb
- modules/appeals_api/spec/requests/supplemental_claims/v0/supplemental_claims_controller_spec.rb
This makes the same changes to the Supplemental Claims API v0 that I made to the Higher-Level Reviews API v0 in #15259.
- [API-32864](https://jira.devops.va.gov/browse/API-32864)
- Supplemental Claims API v0 (not yet publicly available)
> API-32864 Validate token ICN for GET endpoints in Supplemental Claims API

- modules/debts_api/lib/debts_api/v0/vha_fsr_form.rb
Writing `veteranDateSigned` as a timestamp rather than a date string is causing problems down stream.
- Specs green
VHA FSR submissions
- We are able to successfully submit VHA FSRs
> 71883 correction

- modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_20_10206.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_21_0845.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_21_0966.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_21_0972.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_21_10210.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_21_4142.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_21p_0847.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_26_4555.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_40_0247.rb
- modules/simple_forms_api/app/models/simple_forms_api/vha_10_10d.rb
This PR adds a StatsD metric for form 21-4142 to track which type of user (ie, Veteran or Spouse or Child, etc.) is filling out the form. We want to be able to track this on Datadog so we can see the breakdown of which paths are being traveled by users through a form.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/975
This is not a user-facing feature, so I don't think it's worth testing. Happy to talk about counter-arguments though :)
> Start tracking which type of user is filling out a form

- modules/appeals_api/app/controllers/appeals_api/higher_level_reviews/v0/higher_level_reviews_controller.rb
- modules/appeals_api/app/controllers/appeals_api/notice_of_disagreements/v0/notice_of_disagreements/evidence_submissions_controller.rb
- modules/appeals_api/app/controllers/appeals_api/notice_of_disagreements/v0/notice_of_disagreements_controller.rb
- modules/appeals_api/app/controllers/appeals_api/supplemental_claims/v0/supplemental_claims/evidence_submissions_controller.rb
- modules/appeals_api/app/controllers/appeals_api/supplemental_claims/v0/supplemental_claims_controller.rb
- modules/appeals_api/app/swagger/higher_level_reviews/v0/swagger.json
- modules/appeals_api/app/swagger/higher_level_reviews/v0/swagger_dev.json
- modules/appeals_api/app/swagger/notice_of_disagreements/v0/swagger.json
- modules/appeals_api/app/swagger/notice_of_disagreements/v0/swagger_dev.json
- modules/appeals_api/app/swagger/supplemental_claims/v0/swagger.json
- modules/appeals_api/app/swagger/supplemental_claims/v0/swagger_dev.json
- modules/appeals_api/spec/docs/higher_level_reviews/v0_spec.rb
- modules/appeals_api/spec/docs/notice_of_disagreements/v0_spec.rb
- modules/appeals_api/spec/docs/supplemental_claims/v0_spec.rb
- modules/appeals_api/spec/requests/higher_level_reviews/v0/higher_level_reviews_controller_spec.rb
- modules/appeals_api/spec/requests/notice_of_disagreements/v0/notice_of_disagreements/evidence_submissions_controller_spec.rb
- modules/appeals_api/spec/requests/notice_of_disagreements/v0/notice_of_disagreements_controller_spec.rb
- modules/appeals_api/spec/requests/supplemental_claims/v0/supplemental_claims/evidence_submissions_controller_spec.rb
- modules/appeals_api/spec/requests/supplemental_claims/v0/supplemental_claims_controller_spec.rb
- This validates the ICN in the request's OAuth token for the following endpoints:
- `create` for Higher-Level Reviews v0
- `create` for Notice of Disagreements v0
- `create` for Supplemental Claims v0
- `create` for Notice of Disagreements v0 Evidence Submissions
- `create` for Supplemental Claims v0 Evidence Submissions
- `get` for Notice of Disagreements v0 Evidence Submissions (forgot this in my last few PRs for GET endpoints)
- `get` for Supplemental Claims v0 Evidence Submissions (forgot this in my last few PRs for GET endpoints)
- These requests will now return a 403 error when a user with a veteran-scoped OAuth token tries to access records belonging to another Veteran.
- [API-32629](https://jira.devops.va.gov/browse/API-32629)
- v0 HLR, NOD, and SC APIs (not yet in prod)
> API-32629 Validate token ICN for `create` endpoints in appeals v0 APIs

- lib/form1010_ezr/service.rb
- spec/requests/form1010_ezrs_request_spec.rb
- spec/support/vcr_cassettes/form1010_ezr/authorized_submit_async.yml
The `#submit_async` method was simply returning the unique job id from sidekiq, but the frontend was expecting a json response.  We instead now return a json object that the platform forms system will have no issue with.  
[https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/71784](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/71784)
- manual and automated
- will test on staging after enabling the `ezr_async` flag.
This impacts EZR submissions when the `ezr_async` flag is enabled
> 71784 - Add response when ezr_async is enabled

- modules/simple_forms_api/spec/fixtures/form_json/vba_40_0247.json
- modules/simple_forms_api/spec/requests/v1/uploads_spec.rb
This PR is a pretty cosmetic refactor of Simple Forms request tests. It favors `describe` blocks over the function definitions that were in place before and also removes some terminal output that was spamming me whenever I ran these locally. I vaguely intend to do more serious refactoring of the controller itself and ideally shorten this test file in the process (ie, move responsibilities off the controller).
> Refactor Simple Forms tests

- app/models/health_care_application.rb
- spec/requests/health_care_applications_request_spec.rb
Currently, vets-json-schema has `vaMedicalFacility` as an enum type.  This causes issues on validations if the Frontend 
is using Lighthouse as there are more facilities in that list than in the enum.  The update here solves the issue while we 
remove the code from vets-website and vets-json-schema.  
[https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/75189](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/75189)
- manual and automated
- 1010EZ submissions where `hca_use_facilities_API` is enabled.
> 75189 change validation for vaMedicalFacility

- Gemfile.lock
- Bump [crack](https://rubygems.org/gems/crack) to 0.4.6
- The newer version supports Ruby 3
- This is a dependency of [webmock](https://rubygems.org/gems/webmock)
- [https://github.com/department-of-veterans-affairs/va.gov-team/issues/75286](https://github.com/department-of-veterans-affairs/va.gov-team/issues/75286)
- Local full-suite testing
Webmock is only used in development and test Rails environment.
> bump crack to 0.4.6

- app/sidekiq/central_mail/submit_central_form686c_job.rb
- config/features.yml
- spec/sidekiq/central_mail/submit_central_form686c_job_spec.rb
- Remove flipper `dependents_central_submission_lighthouse`  and keep logic from flipper
- Files changed best viewed with "hide whitespace" enabled
- department-of-veterans-affairs/va.gov-team/issues/67518
- Unit tests ran
- This should be tested in staging environment due to lighthouse submission not possible locally
Lighthouse submission is now permanent for benefits submissions
> Remove Central Lighthouse Flipper for Benefits

- Gemfile.lock
- lib/va_profile/models/preferred_name.rb
- spec/lib/va_profile/models/preferred_name_spec.rb
Updates validation rules for preferred name to allow empty spaces.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/71381
> Preferred name spaces

- Gemfile.lock
- Bump [rgeo](https://rubygems.org/gems/rgeo) to 3.0.1
- This is a dependency of [activerecord-postgis-adapter](https://rubygems.org/gems/activerecord-postgis-adapter)
- [https://github.com/department-of-veterans-affairs/va.gov-team/issues/75341](https://github.com/department-of-veterans-affairs/va.gov-team/issues/75341)
- Local full-suite testing
> bump rgeo to 3.0.1

- Gemfile.lock
- Bump [http](https://rubygems.org/gems/http) to 5.2.0
- This is a dependency of [fhir_client](https://github.com/adhocteam/fhir_client)
- This also bumps `llhttp-ffi` to 0.5.0 and `minitest` to 5.22.0
- [https://github.com/department-of-veterans-affairs/va.gov-team/issues/75370](https://github.com/department-of-veterans-affairs/va.gov-team/issues/75370)
- Local full-suite testing
> bump http to 5.2.0

- app/controllers/v0/post911_gi_bill_statuses_controller.rb
- config/features.yml
- spec/controllers/v0/post911_gi_bill_statuses_controller_spec.rb
This PR is to remove the feature flag added in this [PR](https://github.com/department-of-veterans-affairs/vets-api/pull/15075) (fix a bug where an exception was raised without passing a required argument).
The parent ticket was part of the work to resolve [this issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65182) to resolve unknown errors in the Post911GIBillStatus API.
This functionality is now working, and we now have helpful errors which can be used to spin up new issues or enhancements.
- *This work is behind a feature …
> Feature flag cleanup: post_911_gibill_statuses_new_error_handling

- modules/veteran/app/controllers/veteran/v0/flag_accredited_representatives_controller.rb
Submitting a POST request to the flag_a_representative endpoint is returning a "Invalid Authenticity Token" 403 error in staging. Skipping verify_authenticity_token circumvents the issue locally. This change is temporary to confirm the controller is otherwise functional in staging.
To reproduce:
- Navigate to https://staging.va.gov/get-help-from-accredited-representative/find-rep/?address=43210&lat=40.001856&long=-83.014775&page=1&perPage=10&sort=distance_asc&type=veteran_service_officer&name
- Click the "Report outdated information" button on any of the search result card components
- This should trigger a modal with checkbox options. Select any option and click "Submit"
- Results in a 403
TEAM: Accredited Representative Management …
> Skipping verify_authenticity_token in flag_a_representative

- modules/claims_api/app/controllers/claims_api/v2/application_controller.rb
- Removes ICN from the claims_v2_logging method.
- [API-33993](https://jira.devops.va.gov/browse/API-33993)
- rspec
- Postman: ITF, POA, Claims, 526
modified:   modules/claims_api/app/controllers/claims_api/v2/application_controller.rb
> API-33993-remove-icn-logging-from-v2 

- modules/veteran/app/controllers/veteran/v0/flag_accredited_representatives_controller.rb
This PR reverts a temporary workaround submitted [in a previous PR ](https://github.com/department-of-veterans-affairs/vets-api/pull/15414) - namely, removing `verify_authenticity_token` from the `flag_accredited_representatives` controller for the purposes of testing the endpoint in staging. 
We've confirmed the endpoint can receive requests, so we will continue investigating the 403 issue outlined in the previous PR. 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/75311
> Remove skip_before_action in Find a Rep flag_accredited_reps controller

- config/features.yml
- lib/sidekiq/form526_backup_submission_process/processor.rb
Backup submission processing of form 526 has experienced failures triggered as a result of Benefits Intake API regex validations, including the presence of special characters (e.g., an apostrophe) in a Veteran's first and/or last names.
This PR adds a call to the [metadata validation library](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/simple_forms_api_submission/metadata_validator.rb). The validation cleans the passed metadata, aligning it with [Benefits Intake metadata requirements](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/75323#:~:text=https%3A//developer.va.gov/explore/api/benefits%2Dintake/docs%3Fversion%3Dcurrent).
According to the Benefits …
> DBEX: implement Metadata Validator for backup submissions

- modules/ask_va_api/app/controllers/ask_va_api/v0/static_data_controller.rb
- modules/ask_va_api/spec/requests/v0/static_data_spec.rb
- Updated `StaticData#index` to test out the new `/profile` endpoint from `CRM API`.
- 
- https://github.com/department-of-veterans-affairs/ask-va/issues/506
> be | Ask VA Api: Update StaticData#index

- app/sidekiq/benefits_intake_status_job.rb
This PR restores some code that was [previously deleted](https://github.com/department-of-veterans-affairs/vets-api/pull/15318). We want to track both submissions by form but also by all forms with `statsd`. This restores the incrementing lines for tracking by all forms. This will make the Datadog dashboard easier and faster to generate.
> Track all form submissions again

- modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_20_10206.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_21_0845.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_21_0966.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_21_0972.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_21_10210.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_21_4142.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_21p_0847.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_26_4555.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_40_0247.rb
- modules/simple_forms_api/app/models/simple_forms_api/vha_10_10d.rb
- modules/simple_forms_api/app/services/simple_forms_api/pdf_filler.rb
- modules/simple_forms_api/app/services/simple_forms_api/pdf_stamper.rb
- modules/simple_forms_api/spec/requests/v1/uploads_spec.rb
This PR adds two things to our filled PDFs:
1. Adds a datebox timestamp indicating to downstream services when the form was submitted.
2. Adds an auth status to the bottom of every page of the PDF indicating the authentication status of the user.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/949
Tests are passing and one new test written.
Here are some example shots.
Datestamp:
Unauthenticated:
Authenticated LOA3:
> Add datebox timestamp and auth info to bottom of PDF

- config/features.yml
This adds a feature toggle,  **va_online_scheduling_booking_exclusion**, for work needed to exclude Lovell sites from being scheduled for appointments before the sites are converted over to Oracle Health (Cerner).
The feature toggle flag will be removed once the Lovell sites switch from VistA to Oracle Health. This conversion process is expected to take approximately 30 days. Lovell has requested that no new appointments be scheduled via VAOS 30 days prior to their cutover.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/75454
> VAOS Add Feature Toggle for Excluding Captain James A. Lovell from Online Scheduling

- app/models/saved_claim/pension.rb
- spec/requests/pension_claims_controller_spec.rb
- All pensions mail now goes to a single address, so instead of returning regional_office addresses based on the veteran's zipcode, we return the same address every time. 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/75038
Pension Benefits
> Update pensions regional office

- modules/veteran/app/docs/veteran/v0/accreditation.yaml
Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/75767
Adds distance param to far search endpoints swagger documentation.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/75767
*(Describe what parts of the site …
> Add distance param to far search endpoints swagger documentation

- modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb
- modules/simple_forms_api/app/services/simple_forms_api/intent_to_file.rb
- modules/simple_forms_api/config/routes.rb
- modules/simple_forms_api/spec/requests/v1/uploads_spec.rb
- modules/simple_forms_api/spec/services/intent_to_file_spec.rb
- spec/support/vcr_cassettes/lighthouse/benefits_claims/intent_to_file/404_response_pension.yml
- spec/support/vcr_cassettes/lighthouse/benefits_claims/intent_to_file/404_response_survivor.yml
This PR adds a new endpoint to the Simple Forms API Controller: `get_intents_to_file`. This will return an object that contains all ITFs for the logged-in user.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/1012
> Add get_intents_to_file endpoint

- config/features.yml
- modules/veteran/app/controllers/veteran/v0/base_accredited_representatives_controller.rb
- modules/veteran/app/controllers/veteran/v0/flag_accredited_representatives_controller.rb
- modules/veteran/spec/requests/v0/base_accredited_representatives_shared_spec.rb
We are consolidating our feature toggles so that client and api share the same toggles for any given feature. Names and references have been updated in this PR. 
Leaving `find_a_representative_enable_frontend` as is until this PR is merged + references have been updated in vets-website. 
This PR also includes a temporary workaround to a 403 error associated with `our flag_accredited_representative` endpoint. Skipping verify_authenticity_token circumvents the issue, but is not a viable solution from a security perspective. This change is being introduced temporarily so that the ARM team can QA Find a Rep's UI and functionality. It does not impact production and it will be reverted. 
To reproduce:
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/75311
- …
> Updating find a rep feature toggle names

- Gemfile.lock
`ruby` platform was unintentionally removed [here](https://github.com/department-of-veterans-affairs/vets-api/commit/bd5ff6f2ea5804651951ed27be114759077064f6#diff-89cade48462044ee1b672dc5f4c3ec250fbd29effcd8932096a23c1283c6731fL1042). 
As a result the following platforms have been added:
- [arm64-darwin-22](https://github.com/department-of-veterans-affairs/vets-api/commit/bd5ff6f2ea5804651951ed27be114759077064f6#diff-89cade48462044ee1b672dc5f4c3ec250fbd29effcd8932096a23c1283c6731fR1048)
- [arm64-darwin-23](https://github.com/department-of-veterans-affairs/vets-api/commit/adc882e729da036c601ff13259ac64b650916465#diff-89cade48462044ee1b672dc5f4c3ec250fbd29effcd8932096a23c1283c6731fR1048)
- [x86_64-darwin-22](https://github.com/department-of-veterans-affairs/vets-api/commit/9581871a66f986493b …
> Add ruby platform back to Gemfile.lock

- config/features.yml
This adds a feature toggle, va_online_scheduling_cancellation_exclusion, for work needed to exclude Lovell sites from having appointments cancelled before the sites are converted over to Oracle Health (Cerner).
The feature toggle flag will be removed once the Lovell sites switch from VistA to Oracle Health. This conversion process is expected to take approximately 30 days. Lovell has requested that no appointments be cancelled via VAOS 30 days prior to their cutover.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/75510
> VAOS Add Feature Toggle for Excluding Captain James A. Lovell from Online Scheduling Cancellations

- modules/simple_forms_api/app/form_mappings/vba_40_0247.json.erb
This PR removes a newline that was causing the address country to be cut off on the PDF itself. See screenshot below.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/957
> Remove newline in 40-0247 simple form

- modules/veteran/spec/requests/v0/vso_accredited_representatives_spec.rb
- There was a lingering feature toggle reference to `find_a_rep` which should be `find_a_representative_enabled`.
> Fixed feature toggle reference. find_a_rep => find_a_representative_enabled

- config/features.yml
- Removes single toggle not used on vets-website anymore
- [FE PR that it was removed in](https://github.com/department-of-veterans-affairs/vets-website/pull/27744) has been merged and deployed
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/53549
- unit tests passing, only toggle is removed
Profile - Authenticated Experience
> remove toggle profile_use_field_editing_page

- modules/claims_api/lib/claims_api/v2/disability_compensation_documents.rb
- Sets the existing flipper feature to also disable the upload to Benefits Documents so we can load test and not generate ~1,800 sidekiq jobs.
- Can associate to Load Tests ticket - https://jira.devops.va.gov/browse/API-32188
> allows disabling uploads of supp documents for load tests

- config/settings.yml
- spec/support/vcr_cassettes/virtual_regional_office/ep_merge.yml
- spec/support/vcr_cassettes/virtual_regional_office/ep_merge_failure.yml
- Updates endpoint for vets-api to send requests to the EP Merge App in VRO
- I am part of the Claims Fast-Tracking crew's Employee Experience team. We work closely with the Disability Experience team which owns this code.
- The API call is behind a new feature toggle disability_526_ep_merge_api which will remain disabled in production for the near future.
Allows testing of Ep Merge App as discussed in this ticket:
* https://github.com/department-of-veterans-affairs/abd-vro/issues/2092
Updated rspecs
E2E testing in staging / VBMS UAT is planned once the VRO API server portion is complete
None as the feature is still toggled OFF
> Employee-Experience: Update path for EP Merge App within VRO

- .github/CODEOWNERS
- app/controllers/v0/rated_disabilities_discrepancies_controller.rb
- spec/controllers/v0/rated_disabilities_controller_spec.rb
- spec/controllers/v0/rated_disabilities_discrepancies_controller_spec.rb
- spec/support/vcr_cassettes/lighthouse/veteran_verification/disability_rating/200_deferred_response.yml
Lighthouse updated their Rated Disabilities endpoint in production. It no longer returns inactive ratings so we can remove that check, but they now return ratings that have a `decision` value of 'Deferred`. This PR updates the controllers logic to filter out deferred ratings so that we can determine if there are any other discrepancies
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/75855
Updated the VCR cassettes as LH doesn't return ratings with a `rating_end_date` not set to `null`. Also checking that deferred ratings are actually filtered out
> [Rated Disabilities] Updating logic for Rated Disabilities Discrepancies checks

- db/migrate/20240212184756_add_column_flagged_value_updated_at_and_new_unique_constraint.rb
- db/schema.rb
Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/75839
- add 'flagged_value_updated_at` column (datetime, nullable) to flagged_veteran_representative_contact_data
- create new unique constraint using new column
https://github.com/department-of-veterans-affairs/va.gov-team/issues/75839
- *What is the …
> Add column and new unique constraint

- config/features.yml
Remove show_header_v2 flipper as it is not in use.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11875
[Searched the DSVA Github repos for code instances](https://github.com/search?q=org%3Adepartment-of-veterans-affairs+show_header_v2&type=code) and removed the relevant code.
> VACMS-11875 Remove show_header_v2 flipper

- modules/veteran/app/models/veteran/flagged_veteran_representative_contact_data.rb
References https://github.com/department-of-veterans-affairs/va.gov-team/issues/75842
This PR removes `flagged_value_updated` from the list of ignored columns for `FlaggedVeteranRepresentativeContactData`.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/75842 …
> Remove ignored columns from FlaggedVeteranRepresentativeContactData

- .github/CODEOWNERS
- Remove `octo-identity` from `token_validation` code. looks like this is on the lighthouse side/
> Remove octo-identity from token_validation codeowners

- modules/claims_api/app/controllers/claims_api/v1/forms/disability_compensation_controller.rb
- modules/claims_api/spec/requests/v1/disability_compensation_request_spec.rb
- Removes personal info log
[API-33994](https://jira.devops.va.gov/browse/API-33994)
- rspec
- postman
modified:   modules/claims_api/app/controllers/claims_api/v1/forms/disability_compensation_controller.rb
modified:   modules/claims_api/spec/requests/v1/disability_compensation_request_spec.rb
> API-33994-remove-personal-info-log

- config/features.yml
Remove cerner_allow_partial_facilities flipper as it is not in use.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11861
Searched the DSVA Github repos for code instances ([for "cerner_allow_partial_facilities"](https://github.com/search?q=org%3Adepartment-of-veterans-affairs+cerner_allow_partial_facilities&type=code) and ["cernerAllowPartialFacilities"](https://github.com/search?q=org%3Adepartment-of-veterans-affairs+cernerAllowPartialFacilities&type=code)) and removed the relevant code.
> VACMS-11861 Remove cerner_allow_partial_facilities flipper

- config/features.yml
Remove show_new_view_test_lab_results_page flipper as it is not in use.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11872
[Searched the DSVA Github repos for code instances](https://github.com/search?q=org%3Adepartment-of-veterans-affairs+show_new_view_test_lab_results_page&type=code) and removed the relevant code.
> VACMS-11872 Remove show_new_view_test_lab_results_page flipper

- config/features.yml
Remove these flippers that are no longer in use:
- cerner_override_463
- cerner_override_531
- cerner_override_648
- cerner_override_663
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11859
Searched the DSVA Github repos for code instances and removed the relevant code:
- [cerner_override_463](https://github.com/search?q=org%3Adepartment-of-veterans-affairs+cerner_override_463&type=code)
- [cerner_override_531](https://github.com/search?q=org%3Adepartment-of-veterans-affairs+cerner_override_531&type=code)
- [cerner_override_648](https://github.com/search?q=org%3Adepartment-of-veterans-affairs+cerner_override_648&type=code)
- [cerner_override_663](https://github.com/search?q=org%3Adepartment-of-veterans-affairs+cerner_override_663&type=code)
> VACMS-11859 Removing old Cerner feature toggles

- modules/vaos/app/services/vaos/v2/appointments_service.rb
- modules/vaos/spec/services/v2/appointment_service_spec.rb
In this PR, logic was added to identify any appointment that is a 'Lovell appointment' and subsequently set its 'cancellable' attribute to 'false'. A Lovell appointment is identified if the location_id of the appointment starts with "556". The logic was added to **VAOS::V2::AppointmentsService#get_appointments** and **VAOS::V2::AppointmentService#get_appointment**. A new method **VAOS::V2::AppointmentsService#lovell_appointment?** was added to identify Lovell appointments. 
This is behind the feature toggle, **va_online_scheduling_cancellation_exclusion**. 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/75512
- The appointment cancellable was left as is before the change. The change sets the appointment cancellable flag to false if the appointment is a Lovell …
> VAOS Set Appointment Cancellable Flag to False for Lovell Appointments

- modules/veteran/app/sidekiq/representatives/update.rb
- modules/veteran/app/sidekiq/representatives/xlsx_file_processor.rb
- modules/veteran/spec/sidekiq/representatives/update_spec.rb
- modules/veteran/spec/sidekiq/representatives/xlsx_file_processor_spec.rb
Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/76291
Include attorney and agent phone numbers when processing The Trexler File.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/76291
- Tests were updated
- This only impacts the Find A Rep app which is currently being a feature flag.
> Include attorney and agent phone numbers when processing The Trexler File

- db/migrate/20240214212613_remove_required_constraint_from_client_config_access_token_audience.rb
- db/schema.rb
Remove client_configs.access_token_audience required constraint. this is in preparation to remove this column
- department-of-veterans-affairs/va.gov-team#75383
- migrate database - `rails db:migrate`
Sign-in service
> Migration: Remove required constraint from client_configs.access_token_audience

- modules/veteran/app/controllers/veteran/v0/vso_accredited_representatives_controller.rb
- modules/veteran/spec/requests/v0/vso_accredited_representatives_spec.rb
Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/76456
- Remove organization name search from FAR VSO (where 'O' stands for 'Officer') name search.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/76456
- Test for fuzzy name search on organizations was removed
FAR search (which is behind a feature flag)
> Remove org name search from FAR VSO (officer) name search

- modules/veteran/app/models/veteran/service/constants.rb
- modules/veteran/spec/requests/v0/vso_accredited_representatives_spec.rb
Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/76099
Increase `FUZZY_SEARCH_THRESHOLD` from `.3` to `.5`
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/76099
- Tests updated
- We're going to spot check the results in staging to see what affect this change has on them
- FAR search, which is behind a feature flag
> Increase FUZZY_SEARCH_THRESHOLD from .3 to .5

- modules/simple_forms_api/app/services/simple_forms_api/intent_to_file.rb
This PR removes the spot in the Simple Forms API where ICNs are logged to DataDog. [Per the announcement here](https://dsva.slack.com/archives/C01CJV0L9PS/p1707259837989739?thread_ts=1707155247.260139&cid=C01CJV0L9PS), ICNs are now considered PII.
> Remove ICN from Simple Forms logging

- config/features.yml
This PR adds a feature flag for the 10-10EZ application to be able to toggle a new set of form questions around Toxic Exposure Veterans may have had during service.
department-of-veterans-affairs/va.gov-team#74969
> Add feature flag for HCA Toxic Exposure questions

- modules/mobile/app/controllers/mobile/v0/awards_controller.rb
- modules/mobile/spec/request/awards_request_spec.rb
when the awards service fails, it returns a false boolean rather then an error. This changes the mobile controller to expect that and re-raise an error. 
https://github.com/department-of-veterans-affairs/va-mobile-app/issues/7931
*(Describe what parts of the …
> Mobile: Raise error on upstream service error. 

- modules/veteran/app/controllers/veteran/v0/flag_accredited_representatives_controller.rb
Reverts department-of-veterans-affairs/vets-api#15596
Getting this again:
```
{
"errors": [
{
"title": "Forbidden",
"detail": "Invalid Authenticity Token",
"code": "403",
"status": "403"
}
]
}
```
> Revert "Create before_action to explicitly set csrf token, remove verify_auth…"

- modules/check_in/app/controllers/check_in/v0/travel_claims_controller.rb
- modules/check_in/app/controllers/check_in/v2/sessions_controller.rb
- modules/check_in/config/initializers/statsd.rb
This PR adds `facilityType` as allowed param for SessionsController. This param will be used to differentiate between OH and VistA sites for DataDog metrics. This PR also includes updates to statsd metric names to correctly report the metrics based on the facilityType.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/75563
- local testing
> 75563 allow facilityType param, update statsd

- app/controllers/v0/backend_statuses_controller.rb
- app/serializers/backend_statuses_serializer.rb
- app/swagger/swagger/requests/backend_statuses.rb
- spec/requests/backend_status_request_spec.rb
- spec/support/schemas/backend_statuses.json
- spec/support/schemas_camelized/backend_statuses.json
Add `maintenance_windows` to `backend_statuses` response. This does not change the existing structure, it adds an additional `maintenance_windows` array inside attributes. This is to avoid making multiple api calls for downtime banners and notifications. 
```json
{
"data": {
"id": "",
"type": "pagerduty_external_services_responses",
"reported_at": "2024-02-15T20:02:39.000Z",
"statuses": [
{
"service": "Appeals",
"service_id": "appeals",
"status": "active",
"last_incident_timestamp": "2024-01-30T02:07:40.000Z"
},
...
],
"maintenance_windows": [
{
"id": 716,
"external_service": "idme",
"start_time": "2024-02-17T09:00:00.000Z",
"end_time": "2024-02-17T10:00:00.000Z",
"description": ""
},
{
"id": 715,
"external_service": "",
"start_time": "2024-02-17T09:00:00.000Z", …
```
> Add maintenence_windows to /v0/backend_statuses

- app/services/medical_copays/vbs/service.rb
Stakeholders are requesting that we temporarily halt sending these email notifications.
[76701](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/76701)
Specs green
MCP notification emails
For the time being we should not be sending MCP notification emails
> 76701 temporarily halting mcp email notification

- config/features.yml
Remove show_new_secure_messaging_page flipper
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11871
> VACMS-11871 Remove show_new_secure_messaging_page flipper

- db/migrate/20240214215514_add_flipper_indexes.rb
- db/schema.rb
- modules/apps_api/spec/requests/v0/application_directory_request_spec.rb
Remove migration file that added indexes to flipper tables
The indexes were already added but are not in the schema
> Remove flipper indexes from schema

- modules/debts_api/lib/debts_api/v0/vha_fsr_form.rb
- modules/debts_api/spec/fixtures/fsr_forms/combined_fsr_form.json
- modules/debts_api/spec/lib/debt_api/v0/fsr_form_builder_spec.rb
Currently, when building a vha form from a combined FSR we inadvertently use fsr reasons from both vha and vba. We should only be using reasons from vha copays for vha FSR submissions. 
[76409](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/76409)
Specs added
VHA financial status report submissions
VHA fsr (created from a combined fsr) will only use fsr reasons from its own copays. Not vba debts and not copays from other stations.
> 76409 vha FSRs should not include vba reasons

- modules/appeals_api/spec/requests/v2/supplemental_claims_controller_spec.rb
- modules/apps_api/spec/requests/v0/application_directory_request_spec.rb
- modules/my_health/spec/request/v1/threads_request_spec.rb
- spec/requests/connected_applications_request_spec.rb
- Remove `puts response.body` in `modules/apps_api/spec/requests/v0/application_directory_request_spec.rb`
- Remove `puts response` in `modules/my_health/spec/request/v1/threads_request_spec.rb`
- Remove 2 `puts` in `modules/appeals_api/spec/requests/v2/supplemental_claims_controller_spec.rb`
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/76887
- No new tests created
> Remove unnecessary puts

- app/controllers/v0/rated_disabilities_discrepancies_controller.rb
Adding 1151 Denied to the allowlist for rating decisions. The EVSS service returns those decisions currently so we would like to include them as well
> Adding 1151 Denied to the decision allowlist

- app/services/bgs/dependent_service.rb
- modules/mobile/spec/request/dependents_request_spec.rb
- spec/controllers/v0/dependents_applications_controller_spec.rb
- spec/services/bgs/dependent_service_spec.rb
- Perform pdf submission synchronously
- Rescue pdf submission error and submit to central submission
- Still raise error to Dependent Service for logging
- Rearrange most of submit code to allow for LoC linting
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/76139
- This was tested through console, dependent service was called with an existing claim and checked logs so that on failure of Pdf job the central job was attempted to be submitted
##
Functionally this shouldn't change anything for the site, most logic is kept consistent except to submit to central process in case of failure
> Submit to Central Submission Process if Pdf Submission Fails

- db/migrate/20240223173647_add_flipper_indexes.rb
- db/migrate/20240223183025_create_flipper_tables.rb
- db/schema.rb
The recent flipper upgrade 1.2.2 is causing confusion by generating a warning when you run a rails command such as `rails console`:
> Your database needs migrated to use the latest Flipper features.
> Run `rails generate flipper:update` and `rails db:migrate`.
If you run `rails generate flipper:update` it will generate a migration file for `CreateFlipperTables` and `db:migrate` will fail because the tables already exist. The warning is resolved _just_ with `rails db:migrate`
CreateFlipperTables isn't being properly skipped because the migration file doesn't exist in `db/migrate`
- Added CreateFlipperTables migration file to the flipper generator from creating a new migration file. 
- Added a migration for flipper indexes that only runs if the indexes don't exist. 
- Because I reset my …
> Flipper Update Generator Fix

- app/services/sign_in/access_token_audience_generator.rb
- app/services/sign_in/session_creator.rb
- app/services/sign_in/session_refresher.rb
- spec/services/sign_in/access_token_audience_generator_spec.rb
Update AccessToken `aud` to include an array of all client_ids that share_sessions. If a client does not share sessions it is the only one in the `aud` array.
The shared session `client_ids` are cached for 24 hours. It is 30% faster to read from the cache vs querying the database. This is called ~300,000 times per day and will increase as we add more clients. 
- department-of-veterans-affairs/va.gov-team#75383
- seed database - `rails db:seed`
- Sign-in using oauth=true
- grab `vagov_access_token` from cookies
- decode token in rails console:
```ruby
JWT.decode vagov_access_token, OpenSSL::PKey::RSA.new(File.read(Settings.sign_in.jwt_encode_key)), true, { algorithm: 'RS256' }
```
- You should see an array of client_ids in `aud` - `["vamock", "sample_client_web", "vaweb"]`
- Change `vaweb` …
> Update Access Token audience to support auto-auth

- app/services/sign_in/token_serializer.rb
- spec/services/sign_in/token_serializer_spec.rb
Set access_token cookie domain to :all. This will set the domain to the root e.g. `.va.gov`. Refactor setting cookies.
- department-of-veterans-affairs/va.gov-team#76745
- Sign in with SiS and check the cookies
Sign-in service, authentication
> Update access_token_cookie domain, refactor setting cookies

- app/models/user.rb
- app/services/users/exception_handler.rb
- lib/vic/id_card_attribute_error.rb
- spec/requests/authentication/standard_authentication_spec.rb
- I'm on the Platform Product team
This PR renames or removes strings, comments, etc. that needed cleaning up. This is scoped to files owned by the Identity team. 
- Part 6 from: https://github.com/department-of-veterans-affairs/va.gov-team/issues/72200
- Epic: https://github.com/department-of-veterans-affairs/va.gov-team/issues/63326
va.gov locally builds and I'm able to log in (user 5–Frank) and user response is populated.
The only impactful modification changes an error string from VIC.
> Delete emis references from Identity-owned files

- app/controllers/v0/claim_letters_controller.rb
- config/features.yml
- lib/claim_letters/claim_letter_test_data.rb
- spec/controllers/v0/claim_letters_controller_spec.rb
- Created `cst_include_ddl_5103_letters` feature toggle
- Updated `app/controllers/v0/claim_letters_controller.rb` to include `5130` doctypes when `cst_include_ddl_5103_letters` is enabled
- Updated `spec/controllers/v0/claim_letters_controller_spec.rb` unit test
- [Add 5103 letter(s) to DDL #72464](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72464)
CST DDL
> [CST] [DDL] [Backend] Added 5103 letters to DDL

- app/controllers/v0/sign_in_controller.rb
Add domain to access_token cookie delete. From the [docs](https://api.rubyonrails.org/classes/ActionDispatch/Cookies.html)
```
Please note that if you specify a :domain when setting a cookie, you must also specify the domain when deleting the cookie:
```
-  department-of-veterans-affairs/va.gov-team#76745
- department-of-veterans-affairs/vets-api#15626
- Sign in with SiS
- Logout
- Kinda hard to test on localhost but documentation supports it and `:all` is accepted
> Add domain to access_token cookie delete

- modules/veteran/app/sidekiq/representatives/queue_updates.rb
- modules/veteran/app/sidekiq/representatives/update.rb
- modules/veteran/spec/sidekiq/representatives/update_spec.rb
Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/76836
This Pull Request introduces an alternate approach to rate-limiting for the `Representatives::Update` jobs (instead of using  Sidekiq's `#window` rate-limiting feature). This method involves chunking an array of data rows - 1000 rows per job in production and 30 rows per job in other environments - and scheduling these jobs to execute sequentially, one minute apart.
By leveraging Sidekiq's `#perform_in` method instead of the `#window` rate-limiting option, we can manage the rate at which `Representatives::Update` jobs are processed. This method ensures that jobs are executed back-to-back in a non-blocking manner until the entire queue is processed. The `#perform_in` method allows us to specify a delay for …
> Implement an alternate and non-blocking way of rate-limiting Representatives::Update jobs

- modules/veteran/app/sidekiq/representatives/queue_updates.rb
- modules/veteran/app/sidekiq/representatives/update.rb
- modules/veteran/app/sidekiq/representatives/xlsx_file_processor.rb
- modules/veteran/spec/sidekiq/representatives/update_spec.rb
- modules/veteran/spec/sidekiq/representatives/xlsx_file_processor_spec.rb
Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/77024
This PR updates `Representatives::XlsxFileProcessor` to return arrays of hashes for each sheet instead of arrays of JSON strings.
Key Changes
- Data Structure Update: Changed XlsxFileProcessor output from JSON strings to a more direct and manageable array of hashes format.
- Sidekiq Job Serialization: Adjusted job enqueueing to serialize array slices of hashes into JSON strings just once, preventing double serialization and simplifying the process.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/77024
- Tests were updated …
> Fix bug with trexler file processing

- app/models/concerns/form526_claim_fast_tracking_concern.rb
- spec/sidekiq/evss/disability_compensation_form/submit_form526_all_claim_spec.rb
- This work is behind a feature toggle: `disability_526_ep_merge_api`
- This PR temporarily changes the name of the special issue used to identify claims eligible for EP400 Merge. The final special issue will be `EMP`, but while we wait for that to be added to EVSS, we'd like to do end-to-end testing in staging with an existing special issue `RRD` which we've used in the past.
- I am part of the Claims Fast-Tracking crew's Employee Experience team. We work closely with the Disability Experience team which owns this code.
- department-of-veterans-affairs/abd-vro#2641
- Prior to this change, the old behavior would add a `EP400 Merge Project` special issue to eligible claims.
- The Employee Exp team will be conducting end-to-end testing with the VRO team to verify that everything is working. …
> Temporarily change EP400 Merge special issue to RRD

- config/initializers/inflections.rb
- config/locales/exceptions.en.yml
- I'm on the Platform Product team
This PR deletes the last remaining emis references that the Platform is going to remove. The 10-10 team to handle emis mentions in [app/services/form1010cg/service.rb](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/services/form1010cg/service.rb). And mobile backend engineers will handle references to [EMIS_STATUS502](https://github.com/search?q=repo%3Adepartment-of-veterans-affairs%2Fvets-api%20EMIS_STATUS502&type=code) (which is why I didn't delete it in `exceptions.en.yml`)
- 7th and final part from: https://github.com/department-of-veterans-affairs/va.gov-team/issues/72200
- Epic: https://github.com/department-of-veterans-affairs/va.gov-team/issues/63326
va.gov locally …
> delete emis from inflections and exceptions

- config/betamocks/services_config.yml
Adds the Lighthouse Service History and Eligibility `rated_disabilities` endpoint to betamocks config
- *This work is behind a feature toggle (flipper):* **NO**
> Add Lighthouse Service History and Eligibility API to betamocks config

- import-va-certs.sh
- Import new certificate used by downstream
```
* Host benefits.vba.va.gov:443 was resolved.
* IPv6: (none)
* IPv4: 10.205.6.38
*   Trying 10.205.6.38:443...
* Connected to benefits.vba.va.gov (10.205.6.38) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: ./DigiCertGlobalG2TLSRSASHA2562020CA1.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256 / X25519 …
```
> chore(ssl): Import new certificate used by benefits.vba.va.gov

- .github/CODEOWNERS
- Gemfile
- Gemfile.lock
- config/routes.rb
- modules/representation_management/Gemfile
- modules/representation_management/README.rdoc
- modules/representation_management/Rakefile
- modules/representation_management/app/controllers/representation_management/v0/flag_accredited_representatives_controller.rb
- modules/representation_management/app/models/representation_management/flagged_veteran_representative_contact_data.rb
- modules/representation_management/app/serializers/representation_management/flagged_veteran_representative_contact_data_serializer.rb
- modules/representation_management/bin/rails
- modules/representation_management/config/routes.rb
- modules/representation_management/lib/representation_management.rb
- modules/representation_management/lib/representation_management/engine.rb
- modules/representation_management/lib/representation_management/version.rb
- modules/representation_management/representation_management.gemspec
- modules/representation_management/spec/models/representation_management/flagged_veteran_representative_contact_data_spec.rb
- modules/representation_management/spec/requests/v0/flag_accredited_representatives_spec.rb
- modules/representation_management/spec/spec_helper.rb
- spec/simplecov_helper.rb
- spec/spec_helper.rb
- Create `accredited_representatives ` module for us to move all of our 'Find a Rep' and 'Appoint a Rep' code into
- Fix CSRF issue in 'veteran' module by moving our code to our own, not-lighthouse module
- Resolves https://app.zenhub.com/workspaces/accredited-representation-management-team-64d0dc51d3e8f4788ac6ef96/issues/gh/department-of-veterans-affairs/va.gov-team/75311
- Start https://github.com/department-of-veterans-affairs/va.gov-team/issues/75019
- Tests were updated
This is a test to see if moving the `flag_accredited_representatives` endpoint out of the `veteran` module fixes the `csrf` issue we've been dealing. It this works, we'll need to delete this code from the veteran website.
(OPTIONAL)_What should the reviewers know in addition to the above. Is there …
> Create accredited_representatives module with flag_accredited_representatives create endpoint

- .github/workflows/code_checks.yml
- Gemfile.lock
Fix for rack-cors error failing during bundle-audit
https://github.com/cyu/rack-cors/issues/274
https://github.com/department-of-veterans-affairs/vets-api/actions/runs/8071154977/job/22052093362?pr=15700
https://dsva.slack.com/archives/C0460N83Y9G/p1709071048733899
> Resolve bundle-audit error

- modules/simple_forms_api/app/services/simple_forms_api/pdf_stamper.rb
This PR fixes an issue where we wanted to target LOA2 instead of LOA1 for certain messaging on the PDFs.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/949
> Use LOA2 instead of LOA3 for datebox timestamp logic

- app/sidekiq/bgs/job.rb
- app/sidekiq/bgs/submit_form674_job.rb
- app/sidekiq/bgs/submit_form686c_job.rb
- spec/sidekiq/bgs/submit_form674_job_spec.rb
- spec/sidekiq/bgs/submit_form686c_job_spec.rb
- When certain errors are detected in the error stack, immediately skip retries for 686c and 674 submissions
- department-of-veterans-affairs/va.gov-team/issues/72204
- Run job asynchronously in console with specific errors forced to be raised
- Check in logs and Sidekiq web UI to ensure job isn't retried and retries_exhausted block still runs
Site not impacted
> Filter Unwanted Errors from Retrying (Dependents Forms)

- .rubocop.yml
- Dangerfile
Add Danger check for `Gemfile.lock` `PLATFORMS`. Don't allow removal of `ruby` or addition of `darwin` platforms.
> Add Gemfile.lock Platforms Danger check

- app/controllers/v0/rated_disabilities_discrepancies_controller.rb
- spec/controllers/v0/rated_disabilities_discrepancies_controller_spec.rb
- spec/support/vcr_cassettes/lighthouse/veteran_verification/disability_rating/200_deferred_response.yml
Updating the check for active ratings to account for the fact that a rating with an end date in the future is still considered an active rating.
Added a new rating to the VCR cassette that has an end date in the future so that we could ensure that it is not filtered out by the `active?` check
> [Rated Disabilities] Update Rated disability discrepancy checks

- modules/claims_api/app/controllers/claims_api/v2/application_controller.rb
- modules/claims_api/spec/requests/v2/veterans/claims_request_spec.rb
- modules/claims_api/spec/requests/v2/veterans/evidence_waiver_request_spec.rb
- modules/claims_api/spec/requests/v2/veterans/intent_to_files_request_spec.rb
- modules/claims_api/spec/requests/v2/veterans/power_of_attorney_request_spec.rb
- *Team Dash*
- Adds system scopes to v2, except for 526 generate_pdf
- [API-34293](https://jira.devops.va.gov/browse/API-34293)
- *Describe what the old behavior was prior to the change: blanket scopes
- *Describe the steps required to verify your changes are working as expected. Exclusively stating 'Specs run' is NOT acceptable as appropriate testing* Use Postman to test each v2 service, changing the scopes
modified:   modules/claims_api/app/controllers/claims_api/v2/application_controller.rb
> API-34293-system-scopes

- config/features.yml
- Hub page in profile has been fully rolled out in production, so cleaning up toggle for it.
- FE PR already has been done and merged
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/72259
- Tested locally and verified that FE code already has been removed
> remove toggle for hub page

- config/features.yml
- config/settings.yml
- modules/simple_forms_api/app/services/simple_forms_api/confirmation_email.rb
- modules/simple_forms_api/spec/services/confirmation_email_spec.rb
- Create Trigger for Form 40-0247 Request a Presidential Memorial Certificate Submission Confirmation
- https://app.zenhub.com/workspaces/forms-strike-team-620c2914e703390013c4b414/issues/gh/department-of-veterans-affairs/vanotify-team/1225
-  `bundle exec rspec modules/simple_forms_api/spec/services/confirmation_email_spec.rb:104`
> Add confirmation email trigger for form 40-0247

- lib/medical_records/client.rb
- spec/support/vcr_cassettes/mr_client/get_a_health_condition.yml
- spec/support/vcr_cassettes/mr_client/get_a_list_of_allergies.yml
- spec/support/vcr_cassettes/mr_client/get_a_list_of_chemhem_labs.yml
- spec/support/vcr_cassettes/mr_client/get_a_list_of_clinical_notes.yml
- spec/support/vcr_cassettes/mr_client/get_a_list_of_diagreport_labs.yml
- spec/support/vcr_cassettes/mr_client/get_a_list_of_docref_labs.yml
- spec/support/vcr_cassettes/mr_client/get_a_list_of_health_conditions.yml
- spec/support/vcr_cassettes/mr_client/get_a_list_of_health_conditions_error.yml
- spec/support/vcr_cassettes/mr_client/get_a_list_of_labs_and_tests.yml
- spec/support/vcr_cassettes/mr_client/get_a_list_of_vaccines.yml
- spec/support/vcr_cassettes/mr_client/get_a_list_of_vitals.yml
- spec/support/vcr_cassettes/mr_client/get_a_single_lab_or_test.yml
- spec/support/vcr_cassettes/mr_client/get_full_list_of_labs_and_tests.yml
- spec/support/vcr_cassettes/mr_client/get_multiple_fhir_pages.yml
This reverts commit f6ec2978ab57a5def7ac3cb3dd2726b1c2240121.
- Rolling back a commit that caused errors when viewing Vaccines or Notes.
Original PR: https://github.com/department-of-veterans-affairs/vets-api/pull/15729
> MHV-53689: Revert: Added not entered in error flag to all MR list calls (#15729)

- modules/my_health/app/controllers/my_health/v1/prescriptions_controller.rb
- modules/my_health/spec/request/v1/prescriptions_request_spec.rb
- Updated renewable rx logic to include expired, discontinued meds for up to 6 months
https://jira.devops.va.gov/browse/MHV-55039
>In the prescriptions you may need to renew sections, the showing # should reflect all recently expired, discontinued, and meds that ran out of refills for the last 6 months
- New code is covered by unit test
- Ran tests locally
MHV medications app refill page
> MHV-55039-Update-Refill-Logic

- modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb
- modules/simple_forms_api/app/models/simple_forms_api/vha_10_10d.rb
Recently, we removed the combing of PDFs for 10-10D and separated them by attachment for S3 upload. This PR aims to get those attachments cleaning to an S3 bucket.
- Update vha_10_10d model to return file_paths instead of file_names
- Update UploadsController to handle multiple PDFs instead of just the compiled one at the end.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/73557
- Manual browser testing
- Test suite
`vha_10_10d1.pdf` is the optional PDF
- IVC Forms only
- needed for all IVC forms and attachments (including 10-10d, 10-7959f-1 and 2, and 10-7959a and c and other CHAMPVA forms
- the files need to be separated and available on PEGA S3
> 73557: All IVC Forms - Upload forms and separated PDF attachments into S3

- .github/CODEOWNERS
Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/77496
- Add `modules/representation_management` to`.github/CODEOWNERS` and make `@department-of-veterans-affairs/accredited-representation-management` the codeowner of the directory
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/77496
- `.github/CODEOWNERS`
> Add modules/representation_management to codeowners

- modules/representation_management/app/controllers/representation_management/v0/flag_accredited_representatives_controller.rb
References https://github.com/department-of-veterans-affairs/va.gov-team/issues/75311
Put the `flag_accredited_representatives` endpoint behind the `find_a_representative_flag_results_enabled` feature flag.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/75311 …
> FAR flag_accredited_representatives endpoint - add before_action :feature_enabled

- modules/vaos/app/exceptions/vaos/exceptions/backend_service_exception.rb
- modules/vaos/app/helpers/vaos/anonymizers.rb
- modules/vaos/app/services/vaos/middleware/response/errors.rb
- modules/vaos/app/services/vaos/middleware/vaos_logging.rb
- modules/vaos/spec/helpers/anonymizers_spec.rb
- modules/vaos/spec/request/v2/appointments_request_spec.rb
- modules/vaos/spec/services/middleware/vaos_errors_spec.rb
- modules/vaos/spec/services/middleware/vaos_logging_spec.rb
It was noted that during error logging, some URLs that contained ICNs were logged. This PR replaces the logged ICN with a SHA256 digest of the ICN. Logging in the following classes was modified: **VAOS::Exception::BackendServiceException**, **VAOS::Middleware::Errors**, and **VAOS::Middleware::VAOSLogging**. Added Helper **VAOS::Anonymizers**.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/77386
- Prior to the change ICNs in the URLs were logged, after the change a SHA256 digest of the ICN replaces the ICN when logging errors.
> VAOS Mask ICN in URL being logged in DataDog

- modules/simple_forms_api/spec/services/pdf_filler_spec.rb
- This spec has been failing often in PRs created to master for a couple months now. An example run can be found [here](https://github.com/department-of-veterans-affairs/vets-api/actions/runs/8138397192/job/22239117552?pr=15762)
- The respective team is currently investigating it, but we can't have this blocking engineers from submitting PRs anymore.
-
> Skip flakey PdfFiller spec

- lib/medical_records/client.rb
- spec/support/vcr_cassettes/mr_client/get_a_health_condition.yml
- spec/support/vcr_cassettes/mr_client/get_a_health_condition_error.yml
- spec/support/vcr_cassettes/mr_client/get_a_list_of_allergies.yml
- spec/support/vcr_cassettes/mr_client/get_a_list_of_chemhem_labs.yml
- spec/support/vcr_cassettes/mr_client/get_a_list_of_clinical_notes.yml
- spec/support/vcr_cassettes/mr_client/get_a_list_of_diagreport_labs.yml
- spec/support/vcr_cassettes/mr_client/get_a_list_of_docref_labs.yml
- spec/support/vcr_cassettes/mr_client/get_a_list_of_health_conditions.yml
- spec/support/vcr_cassettes/mr_client/get_a_list_of_health_conditions_error.yml
- spec/support/vcr_cassettes/mr_client/get_a_list_of_labs_and_tests.yml
- spec/support/vcr_cassettes/mr_client/get_a_list_of_vaccines.yml
- spec/support/vcr_cassettes/mr_client/get_a_list_of_vitals.yml
- spec/support/vcr_cassettes/mr_client/get_a_single_lab_or_test.yml
- spec/support/vcr_cassettes/mr_client/get_full_list_of_labs_and_tests.yml
- spec/support/vcr_cassettes/mr_client/get_multiple_fhir_pages.yml
All MR list calls have been modified to retrieve only records that are marked as "not entered in error". 
Domains that use the flag as `verification-status:not=entered-in-error`:
1. Allergies (AllergyIntolerance)
2. Health conditions (Condition)
Domains that use the flag as `status:not=entered-in-error`:
1. Vaccines (Immunization)
2. Summaries and notes (DocumentReference)
3. Vitals (Observation)
4. Labs and tests (DiagnosticReport, DocumentReference)
https://jira.devops.va.gov/browse/MHV-53689
All medical records tests involving a search type call have been modified to use the "not entered in error" flag, respective to their usage of the flag by domain. 
All domains were manually tested to verify the usability of the flag. Labs/tests and health conditions could only be verified to the …
> MHV-53689: Not entered in error flag added to all medical records calls

- modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb
- modules/simple_forms_api/spec/requests/v1/uploads_spec.rb
This PR modified the definition of `first_party?` to include _only_ veterans (and exclude surviving dependents). This will cause more users to have PDFs generated for them rather than going down the ITF API path.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/1086
> Remove surviving dependent as first party for 21-0966

- db/migrate/20240229150823_add_state_to_form_526_submissions.rb
- db/schema.rb
[Top level documentation for this improvement is here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/implementation/form_526_state_machine.md)
- [per the documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-database-migrations#vets-apidatabasemigrations-Good.4), the Form 526 State machine is being broken into 3 migrations.  This is the first which adds the requisite column to our form526 submission DB table.
- A subsequent PR will add the default state value
- A subsequent PR will add the model and implementation logic
- [Ticket](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/75526)
- …
> [DBX-75526.1] add aasm_state column to form526 subs

- app/controllers/v0/claim_letters_controller.rb
- fixed the allowed_doctypes method to use @current_user in the feature toggles instead of @user
- Bug fix for [Add 5103 letter(s) to DDL](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72464)
- [Add 5103 letter(s) to DDL](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72464)
- *What is the …
> [CST] [DDL] Feature toggle fix for DDL 5103 notices

- config/features.yml
- config/settings.yml
- modules/meb_api/app/controllers/meb_api/v0/education_benefits_controller.rb
- modules/meb_api/app/workers/meb_api/v0/submit_1990meb_form_confirmation.rb
- modules/meb_api/spec/requests/meb_api/v0/education_benefits_spec.rb
- spec/support/vcr_cassettes/dgi/get_claim_status_denied.yml
- spec/support/vcr_cassettes/dgi/get_claim_status_in_progress.yml
- spec/support/vcr_cassettes/dgi/submit_claim_failure.yml
- Adds template id settings for form 1990meb confirmation email templates
- Adds trigger for calling new sidekiq 1990meb confirmation email job
- Adds sidekiq job for fetching form 1990meb submission status and sending email
- Adds VCR yml files for test cases
https://app.zenhub.com/workspaces/forms-strike-team-620c2914e703390013c4b414/issues/gh/department-of-veterans-affairs/vanotify-team/1010
- Updated education_benefits_spec
- Added spec for new sidekiq job class
> feat: add 1990meb VA Notify confirmation email

- app/controllers/concerns/authentication_and_sso_concerns.rb
- app/controllers/concerns/sign_in/audience_validator.rb
- app/controllers/concerns/sign_in/authentication.rb
- app/services/sign_in/errors.rb
- config/settings.yml
- modules/mobile/app/controllers/mobile/application_controller.rb
- modules/mobile/spec/controllers/application_controller_spec.rb
- modules/mobile/spec/support/helpers/sis_session_helper.rb
- modules/mocked_authentication/lib/mocked_authentication.rb
- spec/controllers/sign_in/audience_validator_spec.rb
- spec/factories/sign_in/access_tokens.rb
- Adds optional access_token audience validation check for sign-in service clients. To add this validation, include the `SignIn::AudienceVerifier` module where `SignIn::Authentication` is included (or  where `SignIn::ApplicationController` is inherited) and add the `client_ids` you want to accept to `validates_access_token_audience`.
- This check is to ensure that sign-in service tokens generated for other clients and resource servers aren't accepted in vets-api.
```ruby
class MyController
include SignIn::Authentication
include SignIn::AudienceVerifier
validates_access_token_audience 'vaweb', 'vamock'
end
```
or
```ruby
class MyController < SignIn::ApplicationController
include SignIn::AudienceVerifier
validates_access_token_audience 'vaweb'
end
```
- …
> Validate access token audience

- app/services/form1010cg/service.rb
Remove unused code referencing eMIS
I work for the 1010 team
https://github.com/department-of-veterans-affairs/va.gov-team/issues/67941
1010cg form
> 10-10CG - eMIS Deprecation: Remove unused code referencing eMIS

- app/swagger/swagger/requests/profile.rb
- lib/lighthouse/direct_deposit/control_information.rb
- spec/controllers/v0/profile/direct_deposits/disability_compensations_controller_spec.rb
- spec/support/vcr_cassettes/lighthouse/direct_deposit/show/200_has_restrictions.yml
- spec/support/vcr_cassettes/lighthouse/direct_deposit/show/200_missing_edu_flag.yml
- spec/support/vcr_cassettes/lighthouse/direct_deposit/show/200_valid.yml
Lighthouse will be adding an additional control flag (`isEduClaimAvailable`) to the Direct Deposit API GET response that will be used to determine if a user can add or update Direct Deposit for Education Benefits.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/76716
Updated disability compensation controller specs.
> Add flag to enable direct deposit for education benefits

- modules/simple_forms_api/app/models/simple_forms_api/vba_21_10210.rb
This PR lets us start tracking user identity for simple forms form 21-10210 in DataDog.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/1097
> Track user identity for 21-10210

- modules/simple_forms_api/app/services/simple_forms_api/confirmation_email.rb
- modules/simple_forms_api/spec/services/confirmation_email_spec.rb
- Form 40-0247's disabled for authentication and doesn't load user data for current session. 
- Decided to send confirmation email only when user fills in email field in the form
- [Jira Ticket](https://app.zenhub.com/workspaces/forms-strike-team-620c2914e703390013c4b414/issues/gh/department-of-veterans-affairs/vanotify-team/1225)
- [Previous PR](https://github.com/department-of-veterans-affairs/vets-api/pull/15614)
> Disable user profile email in form 40-0247

- modules/simple_forms_api/app/services/simple_forms_api/pdf_filler.rb
- modules/simple_forms_api/spec/services/pdf_filler_spec.rb
This PR adds a conditional clause to test if a file exists before we try to access it. I'm adding this because we've had a flaky test around this line of the implementation. This change is unlikely to actually fix the flakiness but might make debugging easier.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/77299
Relevant tests are re-enabled.
> Try to (somewhat) properly resolve the flaky test in PDFFiller

- app/controllers/v0/claim_letters_controller.rb
- lib/claim_letters/claim_letter_test_data.rb
- spec/controllers/v0/claim_letters_controller_spec.rb
- Our team discovered that the doctypes for 5103 Notices were different than we thought they were. We also discovered an additional 5103 notice document and have added that into the allowed doctypes of the controller.
- [Add 5103 letter(s) to DDL](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72464)
- *What is …
> [CST] [DDL] [Backend] Updated the doctypes for 5103 notices in the DDL

- db/migrate/20240306150112_add_default_state_to_form526_submissions.rb
- db/schema.rb
This is PR 2 of 3 to add state to our `Form526Submission` model.  [It follows the first PR here](https://github.com/department-of-veterans-affairs/vets-api/pull/15736), per the [documentation about migrations and default values here](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-database-migrations#vets-apidatabasemigrations-Good.4)
- add a default value of 'unprocessed' to our form526_submissions table in the `aasm_state` column
**NOTE: this is not a wholeistic solution for end-to-end tracking.** This work simply allows us a persistent, simple, queryable, and non-human-error-prone way to track submission state outside of the normal submission flow, ie remediation.  There is a pretty good chance that this …
> [dbx-75526.2] add default state to form526 submissions

- app/controllers/concerns/sign_in/audience_validator.rb
Rescue JWT errors in overridden authentication method. These JWT errors are normal they just weren't getting handled correctly.
> Rescue JWT errors in overide method

- config/coverband.rb
- config/initializers/breakers.rb
- config/initializers/rack_attack.rb
- modules/meb_api/config/initializers/breakers.rb
- modules/mobile/spec/services/messaging_client_spec.rb
- Some files particularly several initializers created a new redis instance based on `config/redis.yml`. Instead they should use the global instance variable `$redis`
- Changed `Redis.new(REDIS_CONFIG[:redis].to_hash)` to `$redis` 
- Full suite of tests passed
> Swap Redis instance var for global var

- .github/CODEOWNERS
- Jenkinsfile
this has been failing on [commits to master](https://github.com/department-of-veterans-affairs/vets-api/commits/master/) because we deleted the vets-api build (on purpose). This CI action is not needed.
> Remove Build AMI step

- .github/CODEOWNERS
- Jenkinsfile
this has been failing on [commits to master](https://github.com/department-of-veterans-affairs/vets-api/commits/master/) because we deleted the vets-api build (on purpose). This CI action is not needed.
> Remove 'Build AMI' and 'Deploy Staging' steps

- app/controllers/v0/claim_letters_controller.rb
- spec/controllers/v0/claim_letters_controller_spec.rb
Added DataDog logging into DDL so we can track that the descriptions of the documents found within their metadata matches what we think those doctypes should be.
Fulfills what's requested by this ticket: [Log metadata of document type for each DDL document to DataDog](https://github.com/department-of-veterans-affairs/va.gov-team/issues/77937)
- [Log metadata of document type for each DDL document to DataDog](https://github.com/department-of-veterans-affairs/va.gov-team/issues/77937)
> [CST] [DDL] Added document type metadata logging to DDL and added a unit test for it

- config/features.yml
- find_a_representative_enabled actor_type is now cookie_id
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/77825
> Set feature toggle actor_type to cookie_id

- config/features.yml
This adds a feature toggle,  **va_online_scheduling_sts_oauth_token** , for work needed to replace the current JWT token with the new MAP STS OAuth token service.
The feature toggle flag will be removed once the current VAOS JWT token service is replaced with the MAP STS OAuth service.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/76148
> VAOS Add Feature Toggle for MAP STS OAuth Token

- modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb
This PR partially reverts an unintentional change whereby a log was switched back from including a hash to being string interpolated. I prefer the hash format.
> Convert uploads controller log to a preferable format

- config/features.yml
- modules/appeals_api/app/controllers/appeals_api/application_controller.rb
- modules/appeals_api/spec/controllers/application_controller_spec.rb
- modules/va_forms/app/controllers/va_forms/application_controller.rb
- modules/vba_documents/app/controllers/vba_documents/application_controller.rb
Updates APIs in the `appeals_api`, `va_forms`, and `vba_documents` modules so that they return an Unauthorized error if the request did not come through the gateway (only applies in production mode)
- [API-34434](https://jira.devops.va.gov/browse/API-34434)
- All endpoints in …
> API-34434 Reject non-gateway requests to some APIs

- .github/CODEOWNERS
- lib/common/file_helpers.rb
This PR checks for a non-`nil` path before checking if a File at that path exists. We ran into a problem where `path` was `nil` and causing tests to break. If the `path` is `nil` then there should be nothing to delete anyway, so this seems harmless to me.
> Check that path is not nil before checking for file existence

- config/coverband.rb
- Fix redis instantiation in coverband config file (revert to previous)
- None
- Manual testing
> Coverband Config with Redis

- db/migrate/20240312194623_add_change_history_to_va_forms_forms.rb
- db/schema.rb
This PR adds a `change_history` JSON field to the `va_forms_forms` table via a database migration, which builds upon #15887. This field is nullable and will track the history of SHA-256 changes that have occurred for a particular form. Future PRs will use this new field, populating and exposing it in our Forms API endpoints. The field is being added in order to reduce our usage of the `paper_trail` gem.
My team (Lighthouse Team Banana Peels) maintains the `va_forms` module.
- [API-33857](https://jira.devops.va.gov/browse/API-33857)
Confirmed that the database migration completed successfully and that our endpoints do not return this data just yet.
None
This PR impacts the `va_forms` module only.
No specific feedback requested.
> API-33857: Add a `change_history` JSONB Field to the `va_forms_forms` Table

- modules/vaos/app/services/vaos/v2/appointments_service.rb
- modules/vaos/spec/request/v2/appointments_request_spec.rb
- modules/vaos/spec/services/v2/appointment_service_spec.rb
- this work updates an avs appointment test id to return an empty field in order to help the frontend validate this use case
- GH#75801
- updated relevant avs tests to check against empty field, ran regression tests
> avs empty state validation

- Gemfile.lock
- app/controllers/v1/apidocs_controller.rb
- app/swagger/swagger/v1/requests/post911_gi_bill_statuses.rb
Following the addition of a new [rails controller](https://github.com/department-of-veterans-affairs/vets-api/pull/15718) at `v1/post911_gi_bill_status`, update the Swagger documentation.
> Add Swagger documentation /v1/post911_gi_bill_status

- modules/appeals_api/app/models/appeals_api/higher_level_review.rb
- modules/appeals_api/app/models/appeals_api/notice_of_disagreement.rb
- modules/appeals_api/app/models/appeals_api/supplemental_claim.rb
- modules/appeals_api/spec/models/higher_level_review_spec.rb
- modules/appeals_api/spec/models/notice_of_disagreement_spec.rb
- modules/appeals_api/spec/models/supplemental_claim_spec.rb
- Adds a `non_veteran_claimant` field to the metadata of all three types of appeals (NOD, HLR, SC). Also adds a `non_veteran_claimant?` method to the appeals to support this.
- [API-34148](https://jira.devops.va.gov/browse/API-34148)
- Higher-Level Reviews, …
> API-34148 Non-veteran claimant flag in appeal metadata

- modules/check_in/app/services/travel_claim/client.rb
- modules/check_in/spec/services/travel_claim/client_spec.rb
- modules/check_in/spec/sidekiq/travel_claim_submission_worker_spec.rb
- *Handling timeout exceptions when BTSSS endpoint takes longer time to respond*
- *https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/77678*
NA
> 77678 Handling timeout exception from BTSSS

- modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_20_10206.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_20_10207.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_21_0845.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_21_0966.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_21_0972.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_21_10210.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_21_4142.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_21p_0847.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_26_4555.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_40_0247.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_40_10007.rb
- modules/simple_forms_api/app/models/simple_forms_api/vha_10_10d.rb
- modules/simple_forms_api/app/models/simple_forms_api/vha_10_7959f_1.rb
- modules/simple_forms_api/spec/requests/v1/uploads_spec.rb
This PR moves where we track user identity so that we can add the `confirmation_code` to DataDog as well. This way we can keep track of particular user types with their actual form submissions.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/77983
> Slight refactor to add UUID to user identity tracking for simple_forms_api

- app/controllers/v0/benefits_claims_controller.rb
- spec/controllers/v0/benefits_claims_controller_spec.rb
- spec/support/vcr_cassettes/lighthouse/benefits_claims/show/200_response.yml
- Added status tracking to `app/controllers/v0/benefits_claims_controller.rb`
- Updated `spec/support/vcr_cassettes/lighthouse/benefits_claims/show/200_response.yml` to contain `NEEDED_FROM_YOU` statuses in tracked items
- Updated `spec/controllers/v0/benefits_claims_controller_spec.rb`
- [Update Evidence Request Logging](https://github.com/department-of-veterans-affairs/va.gov-team/issues/78342)
> Added status tracking to our tracked item logging for DataDog

- app/sidekiq/benefits_intake_status_job.rb
This PR configures Sidekiq to _not_ retry the `BenefitsIntakeStatusJob`. It's ok not to retry this one because it runs daily and doesn't affect operations; it's purely for status reporting. If we miss a day, it's not a big deal. If it fails once, it'd probably fail every retry.
> Do not retry the BenefitsIntakeStatusJob

- modules/debts_api/lib/debts_api/v0/vha_fsr_form.rb
We should not be assuming that the value of pHDfnNumber is an integer. Coerce to integer and then behave accordingly.
[78436](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/78436)
[67409](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/67409)
Specs green
FSR submission
VHA FSR submission behave as expected even if the value of pHDfnNumber is a string.
> 78436 coerce pHDfnNumber to integer

- modules/travel_pay/app/services/travel_pay/client.rb
It appears that in an updated version of Faraday, the json middleware only accepts 0 or 1 parameters. I was used to being able to specify a pattern to match for the content type, but this throws an ArgumentError exception if used in the previous way.
> Changed the way we used the json middleware to accommodate the faraday update

- modules/check_in/app/serializers/check_in/v2/appointment_data_serializer.rb
- modules/check_in/app/services/travel_claim/service.rb
- modules/check_in/spec/request/v2/patient_check_ins_request_spec.rb
- modules/check_in/spec/request/v2/pre_check_ins_request_spec.rb
- modules/check_in/spec/serializers/check_in/v2/appointment_data_serializer_spec.rb
- modules/check_in/spec/services/v2/lorota/service_spec.rb
This PR updates the appointment data serializer to handle Oracle Health data. Specifically, it handles the address fields in a separate location, and null values for demographics, demographics status.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/78335
- check in experience
> 78335 Update Appointment data serializer

- modules/simple_forms_api/app/models/simple_forms_api/vba_21p_0847.rb
This PR tracks users who fill out the 21P-0847 so that we can see what type of user filled out the form in DataDog.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/1110
> Track users for 21P-0847

- modules/travel_pay/app/services/travel_pay/client.rb
Faraday truncates the `server_url` to just the domain if you provide a `/` in your path. This is the reason we were getting 404s from the BTSSS API. 
So:
```ruby
connection(server_url: 'https://httpbin.org/links').get('/1/2')
connection(server_url: 'https://httpbin.org/links').get('1/2')
```
> Change absolute pathing (wrong) to relative pathing

- modules/simple_forms_api/app/models/simple_forms_api/vba_20_10206.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_21_0966.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_21_0972.rb
This PR tracks users for the remaining three simple forms:
- 20-10206
- 21-0972
- 21-0966
Until now I've been handling these one at a time but I figured the pattern was clear and small enough that I could just knock the rest out with one PR.
- [20-10206](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/1111)
- [21-0972](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/1112)
- [21-0966](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/1113)
> Track users for remaining three forms

- .github/workflows/build-and-publish.yaml
A failing `build-and-publish` workflow can look alarming (see screenshot). Some users think this is related to code being deployed to production. Rename to specify preview environments.
CI run.
> change workflow name to specify preview env

- app/sidekiq/decision_review/nod_send_email_job.rb
- spec/sidekiq/decision_review/nod_send_email_job_spec.rb
This fixes an error with a parameter name in the `DecisionReview::NodSendEmailJob` added in #15795
#15795
Manually tested the changes
* Same as #15795
> 76818: Fix parameter name for NodSendEmailJob

- app/models/async_transaction/base.rb
- app/models/in_progress_form.rb
- app/models/nod_notification.rb
- modules/appeals_api/app/models/appeals_api/higher_level_review.rb
- modules/appeals_api/app/models/appeals_api/notice_of_disagreement.rb
- modules/appeals_api/app/models/appeals_api/supplemental_claim.rb
- modules/claims_api/app/models/claims_api/auto_established_claim.rb
- modules/claims_api/app/models/claims_api/evidence_waiver_submission.rb
- modules/claims_api/app/models/claims_api/power_of_attorney.rb
- modules/claims_api/app/models/concerns/claims_api/file_data.rb
- modules/covid_vaccine/app/models/covid_vaccine/v0/expanded_registration_submission.rb
- modules/covid_vaccine/app/models/covid_vaccine/v0/registration_submission.rb
- modules/health_quest/app/models/health_quest/questionnaire_response.rb
- modules/vye/app/models/vye/user_info.rb
- Fixing the fallowing warning ahead of the bump to Rails 7.1:
- `DEPRECATION WARNING: Passing the coder as positional argument is deprecated and will be removed in Rails 7.2.`
- Fix: `serialize :payload, JsonMarshal::Marshaller` -> `serialize :payload, coder: JsonMarshal::Marshaller`
> Update serializer coder syntax per 7.1 deprecation message

- config/betamocks/services_config.yml
- config/settings.yml
- lib/va_profile/configuration.rb
This PR enables betamocks for the demographics service. This is needed so we can properly test some new [changes](https://github.com/department-of-veterans-affairs/vets-api/pull/15831) to the `Users::Profile` service that introduces demographic data.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/78572
* Fetch and checkout the `demographics` branch for the vets-api-mockdata repo.
* Enable betamocks locally.
* Start vets-api and vets-website.
* Login as a user.
* Get the access token jwt from the `vagov_access_token` cookie
* Get the request IP from the request headers in the network tab
* In the Rails console, execute:
```ruby
access_token_jwt = "<access token jwt from cookie>"
access_token = SignIn::AccessTokenJwtDecoder.new(access_token_jwt: …
```
> Enable mocking for demographics service

- modules/va_forms/spec/requests/v0/forms_request_spec.rb
A spec was added in #15968 but was failing due to a mistake that I made while writing the spec. The `last_sha256_change` field is modified when the record is saved (`before_save` callback), so I shouldn't have used a static date in the assertion.
My team (Lighthouse Team Banana Peels) maintains the `va_forms` module.
[API-33857](https://jira.devops.va.gov/browse/API-33857)
Spec is now passing consistently.
None
This PR impacts the `va_forms` module only.
No specific feedback requested for this PR.
> API-33857: Fix Failing `VAForms` Spec

- modules/appeals_api/app/controllers/appeals_api/application_controller.rb
- modules/appeals_api/spec/controllers/application_controller_spec.rb
- modules/va_forms/app/controllers/va_forms/application_controller.rb
- modules/vba_documents/app/controllers/vba_documents/application_controller.rb
- The `source` parameter wasn't adequate for these purposes in #15751 
- This uses `X-Consumer-Username` and `X-Consumer-ID` instead
- [API-34434](https://jira.devops.va.gov/browse/API-34434)
*(Describe what parts of the site are impacted and*if*code touched …
> API-34434 Check gateway headers in benefits base controllers

- .rubocop_todo.yml
- modules/claims_api/spec/requests/v1/disability_compensation_request_spec.rb
Hey there! We have a spec on the k8s branch that are [failing from this commit](https://github.com/department-of-veterans-affairs/vets-api/pull/15437/files)
[See failure details here](https://github.com/department-of-veterans-affairs/vets-api/actions/runs/8329503242/job/22791974863) (and in the screenshot below)
modules/claims_api/spec/requests/v1/disability_compensation_request_spec.rb:992
Claims API on Lighthouse is working on a fix, temp disabiling until them
> Temp disable this test

- modules/debts_api/app/controllers/debts_api/v0/financial_status_reports_controller.rb
- modules/debts_api/lib/debts_api/v0/vha_fsr_form.rb
The FSR service has logic that depends on controller params that up till now were not explicitly permitted.
[78436](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/78436)
[67409](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/67409)
Specs green
FSR submission
For FSR controller, `p_h_dfn_number` and `p_h_cerner_patient_id` should both be permitted params under `selected_debts_and_copays` field.
> 78436 station type issue

- modules/travel_pay/app/controllers/travel_pay/claims_controller.rb
- modules/travel_pay/app/controllers/travel_pay/pings_controller.rb
- modules/travel_pay/config/routes.rb
- modules/travel_pay/spec/controllers/pings_controller_spec.rb
Creates new `TravelPay::PingsController` and moves ping functionality out of `claims/index` (which will be needed later) into the new controller.
> Move travel pay ping endpoint to new controller

- db/migrate/20240318190236_add_user_profile_id_to_tables.vye.rb
- db/migrate/20240318190237_fix_address_names.vye.rb
- db/schema.rb
- modules/vye/db/migrate/20240316034337_add_user_profile_id_to_tables.rb
- modules/vye/db/migrate/20240318162206_fix_address_names.rb
https://jira.devops.va.gov/browse/VYE-253
https://jira.devops.va.gov/browse/VYE-254
As:
I need:
To separate data  from transient date.
So that: 
 Data that's not transient does not get purged.
No considerations
 Data that's not transient does not get purged.
Have to be moved out in separate tables
ICN
SSN 
Claim number 
Not a new feature, so there's no test component
No other considerations
As:
I need:
 To separate address data from BDN
So that: 
 It could be added to the addresses array in user profile
No considerations
So front end can see all the addresses
Will only show the last address to populate from
Testing …
> Serparate user profile  3 db up

- lib/periodic_jobs.rb
At some point, the descriptions of two unrelated Appeals API jobs got swapped, so the comments were no longer associated with the correct job. This PR resolves that issue.
My team (Lighthouse Team Banana Peels) maintains the `appeals_api` module.
No issue/ticket. Just something noticed while scanning code today and thought to fix.
Not needed, since this change only affects code comments.
None
This PR affects the `appeals_api` jobs only, and is not a functional change, just a change to comments.
No specific feedback requested.
> Fix `AppealsAPI` Sidekiq Job Descriptions

- modules/simple_forms_api/app/models/simple_forms_api/vha_10_10d.rb
Summary: This PR adds the UUID to the Metadata JSON file that will be uploaded to the PEGA S3 bucket.
This fulfills the ticket 75508. See "related issue"
https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/75508
- [ x] *New code is covered by unit tests*
Verified that the JSON is in the s3 bucket
It will affect 1010d and other IVC forms
UUID is in the JSON file
> add UUID to 1010d JSON output

- Dangerfile
- Update Dangerfile to allow `db/seeds` changes with app code changes. Seeds rely on app code so they are normally updated with other app changes. Plus, seeds are only used in development. 
- Danger still successfully catches when edits are made to `db/schema.rb` or `db/migrate/` and app code
- Tested app code changes and `db/seeds` change and no Danger error was generated
Danger check
> Update Dangerfile to allow db/seeds changes with app code changes

- modules/claims_api/app/services/claims_api/slack/failed_submissions_messenger.rb
- modules/claims_api/spec/services/failed_submissions_messenger_spec.rb
* Show ITF errored count but not the array of Ids
[API-34921](https://jira.devops.va.gov/browse/API-34921)
- *Describe what the old behavior was prior to the change* It showed the whole array of IDs
- *If this work is behind a flipper:* Yes, but it previously was so nothing new there.
* A sample of the test message can be seen below in the "screenshots" (This will be run …
> API-34921 remove itf ids from alerts

- db/migrate/20240315210805_drop_versions.rb
- db/schema.rb
Given that the `paper_trail` gem was removed in #15969, we can now safely remove the `versions` table that the gem previously used to store version history for the `VAForms::Form` model.
I confirmed on all `vets-api` environments that the table is only storing version history for the `VAForms::Form` model (see below). All data previously stored in this table has been migrated to the `va_forms_forms` table. My team (Lighthouse Team Banana Peels) maintains the `va_forms` module.
[API-33857](https://jira.devops.va.gov/browse/API-33857)
After running the migration, I ran the app locally and tested the forms `index` and `show` endpoints against my local dataset.
None
This PR impacts the `va_forms` module only. 
No specific feedback requested for this PR.
> API-33857: Remove `versions` Table Previously Used by the `paper_trail` Gem

- .github/CODEOWNERS
- config/form_profile_mappings/21P-527EZ.yml
- spec/models/form_profile_spec.rb
remove 'gender' from prefill json data
https://github.com/department-of-veterans-affairs/va.gov-team/issues/76858
https://github.com/department-of-veterans-affairs/vets-json-schema/pull/866
viewing the network response in browser devtools, 'gender' was present in the return json data from in_progress_forms controller when beginning an application.
removed the mapping of the attribute for pensions 527ez prefill
beginning a new pension application, prefill data no longer has 'gender' attribute
Pensions
> Pension 76858 Removed gender from prefill json data

- modules/mobile/app/controllers/mobile/v0/emails_controller.rb
- modules/mobile/app/controllers/mobile/v0/phones_controller.rb
Removed `evss/pciu/service` references in Mobile/v0 controllers. PCIU service will be depreciated soon. Mobile controllers use the `Mobile::V0::Profile::SyncUpdateService` instead of the PCIU service. VAProfile::Models build mobile records:
```
modules/mobile/app/services/mobile/v0/profile/sync_update_service.rb
...
...
def build_record(type, params)
"VAProfile::Models::#{type.capitalize}"
.constantize
.new(params)
.set_defaults(@user)
end
```
- department-of-veterans-affairs/va.gov-team#76174
> Removed pciu service requirement Mobile/v0 controllers

- db/migrate/20240319141429_add_ipf_data_to_form5655_submission.rb
- db/schema.rb
In the future we want to be able to rehydrate an InProgressForm from a 5655 submission. To facilitate this feature we need to persist ipf data inside the submission itself.
[72987](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/72987)
[78148](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/78148)
Specs green
The form5655_submissions table
ipf_data_ciphertext column is added to the form5655_submissions table
> 72987 Add ipf_data_ciphertext column to form5655_submissions

- modules/check_in/app/controllers/check_in/v2/patient_check_ins_controller.rb
- modules/check_in/spec/request/v2/patient_check_ins_request_spec.rb
- spec/support/vcr_cassettes/check_in/lorota/data/data_oracle_health_200.yml
This PR adds the logic to check if the incoming 'data' request is for OH sites (for travel claims) and doesn't call  CHIP `set_echeckin_started` in that case. For OH sites, currently there's no check_in functionaliy.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/78647
* check_in experience
> 78647 no call set_echeckin_started for OH travel claims

- app/models/messaging_preference.rb
- app/models/prescription_preference.rb
- app/swagger/swagger/schemas/vet360/email.rb
- lib/evss/pciu/service.rb
- lib/va_profile/models/email.rb
- spec/lib/va_profile/models/email_spec.rb
PCIU service will be deprecated soon. Currently, these 4 files are using the EVSS::PCIU::EmailAddress::VALID_EMAIL_REGEX.
-  PrescriptionPreference
-  MessagingPreference
-  Vets360 Email
-  VAProfile: Email
VaProfile has replaced PCIU. The `EVSS::PCIU::EmailAddress::VALID_EMAIL_REGEX` has been replaced with `VAProfile::Models::Email::VALID_EMAIL_REGEX`.
EVSS::PCIU::EmailAddress files will be removed after this has been merged.
- department-of-veterans-affairs/va.gov-team/issues/76165
- *Link to …
> Replaced PCIU::VALID_EMAIL_REGEX with VaProfile::VALID_EMAIL_REGEX

- spec/rails_helper.rb
This change is to eliminate the deprecation warning that I'm getting below.
Deprecation Warnings:
Rails 7.1 has deprecated the singular fixture_path in favour of an array.You should migrate to plural:
If you need more of the backtrace for any of these deprecations to
identify where to make the necessary changes, you can configure
`config.raise_errors_for_deprecations!`, and it will turn the
deprecation warnings into errors, giving you the full backtrace.
> fix for deprecation warning

- config/coverband.rb
- Fix redis instantiation in coverband config file. 
- Don't use global $redis variable for coverband config file
- None
- Manual testing
> replace global variable with new redis instance

- config/features.yml
- spec/requests/swagger_spec.rb
This PR fixes the initial deploy of BRD migration, where the Flipper flag `disability_compensation_lighthouse_brd` was accidentally omitted from `features.yml` (making it inaccessible from the Flipper dashboard)
- This work is behind a feature toggle (flipper): ~YES/NO~ this work is part of the feature toggle itself
- The `disability_compensation_lighthouse_brd` toggle was added to `features.yml`
- Disability Benefits Experience Team 1 (dBeX tReX 🦖)
- [78798](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/78798)
- Original [PR](https://github.com/department-of-veterans-affairs/vets-api/pull/15302/files)
- Feature toggle now shows up in /flipper/features
526EZ application
> added the BRD feature flag to features.yml

- app/controllers/concerns/sentry_controller_logging.rb
- app/controllers/v0/sign_in_controller.rb
- config/redis.yml
- config/settings.yml
- db/seeds/development.rb
- modules/accredited_representative_portal/app/controllers/accredited_representative_portal/application_controller.rb
- modules/accredited_representative_portal/app/controllers/accredited_representative_portal/v0/representative_users_controller.rb
- modules/accredited_representative_portal/app/controllers/concerns/accredited_representative_portal/authenticable.rb
- modules/accredited_representative_portal/app/models/accredited_representative_portal/representative_user.rb
- modules/accredited_representative_portal/app/services/accredited_representative_portal/representative_user_creator.rb
- modules/accredited_representative_portal/app/services/accredited_representative_portal/representative_user_loader.rb
- modules/accredited_representative_portal/config/routes.rb
- modules/accredited_representative_portal/spec/controllers/concerns/accredited_representative_portal/authenticable_spec.rb
- modules/accredited_representative_portal/spec/factories/representative_user.rb
- modules/accredited_representative_portal/spec/models/accredited_representatiive_portal/representative_user_spec.rb
- modules/accredited_representative_portal/spec/requests/accredited_representative_portal/application_spec.rb
- modules/accredited_representative_portal/spec/requests/accredited_representative_portal/v0/power_of_attorney_requests_controller_spec.rb
- modules/accredited_representative_portal/spec/requests/accredited_representative_portal/v0/representative_user_spec.rb
- modules/accredited_representative_portal/spec/routing/accredited_representative_portal/v0/representative_user_routing_spec.rb
- modules/accredited_representative_portal/spec/services/accredited_representative_portal/representative_user_creator_spec.rb
- modules/accredited_representative_portal/spec/services/accredited_representative_portal/representative_user_loader_spec.rb
- modules/accredited_representative_portal/spec/support/authentication.rb
- spec/controllers/v0/sign_in_controller_spec.rb
- Add auth flow for a representative user
- create a basic RepresentativeUser model
- Create RepresentativeUser creator and loader
- add access_token audience validation to arp controllers to only accept arp sessions
- department-of-veterans-affairs/va.gov-team#78007 
- department-of-veterans-affairs/va.gov-team#78002
- Seed `vets-api` database - `rails db:seed`
- Start `vets-api` - `rails s`
- Start `vets-website` - `yarn watch`
- Authenticate  through USiP - [http://localhost:3001/sign-in/?application=arp&oauth=true](http://localhost:3001/sign-in/?application=arp&oauth=true)
- Hit the `rep_user` endpoint - [http://localhost:3000/accredited_representative_portal/v0/user](http://localhost:3000/accredited_representative_portal/v0/rep_user)
- You should see JSON of the the `rep_user` you …
> Representative user auth flow

- app/models/form526_submission.rb
- app/sidekiq/evss/disability_compensation_form/submit_form526.rb
- lib/sidekiq/form526_backup_submission_process/submit.rb
- lib/sidekiq/form526_job_status_tracker/backup_submission.rb
- spec/lib/sidekiq/form526_backup_submission_process/submit_spec.rb
- spec/models/form526_submission_spec.rb
- spec/sidekiq/evss/disability_compensation_form/submit_form526_all_claim_spec.rb
- spec/sidekiq/evss/disability_compensation_form/submit_form526_spec.rb
*NOTE: this is PR 3 of 3 to add this logic*
- [PR 1](https://github.com/department-of-veterans-affairs/vets-api/pull/15736)
- [PR 2](https://github.com/department-of-veterans-affairs/vets-api/pull/15801)
We are about to do an audit in cooperation with VBMS to determine the success of our past year of remediation efforts.  Though VBMS is the source of truth, we need a way to easily mark submissions as conceptually 'done' or 'off our plate'.  
To date, we have been using the presence of `submitted_claim_id` and `backup_submitted_claim_id` to represent success via the primary or backup submission path, respectively.  
**This did not account for our 'failsafe' remediations**
Additionally, with a simple state machine in place we have a way to record the results of Lighthouse's status updates. …
> [dbx-num] add state machine to 526

- modules/vaos/app/services/vaos/v2/mobile_facility_service.rb
- modules/vaos/spec/services/v2/mobile_facility_service_spec.rb
Lovell sites no longer need to be excluded from appointment scheduling after the cutover to Oracle Health. The code that excluded Lovell sites has been removed.
This reverts commit 5ab933aa1a7c8a8b9e3dc4cd920a7a52e52a233b.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/78777
> VAOS Revert Remove Lovell Sites from Appointment Scheduling.

- modules/vaos/app/services/vaos/v2/appointments_service.rb
- modules/vaos/spec/services/v2/appointment_service_spec.rb
Removes, no longer required, code that prevents cancellation of Lovell site appointments. This is a revert of commit (0f0412d)
https://github.com/department-of-veterans-affairs/va.gov-team/issues/78780
Removed tests that covered deleted code. Ensured existing tests still pass.
> VAOS Revert Cancellation Exclusions at Lovell Clinics

- config/features.yml
Removing the `cst_use_lighthouse` and `cst_use_new_claim_cards` feature toggles from `features.yml` because they are no longer being used in vets-website
- department-of-veterans-affairs/va.gov-team/issues/77311
> [CST] Removing feature toggles that are no longer used

- modules/simple_forms_api/app/models/simple_forms_api/vha_10_10d.rb
This PR is to add 1010d metrics tracking in datadog.
Other forms like vba_21_10210 has the same metrics added
- [ x] *New code is covered by unit tests*
Unit testing completed. 
It only affects datadog monitoring
> add statsD and key for datadog tracing 1010d

- modules/appeals_api/config/mailinglists/report_daily.yml
[Slack thread](https://lighthouseva.slack.com/archives/CKUCFQAHJ/p1711387277761589?thread_ts=1699284572.857799&cid=CKUCFQAHJ)
None …
> Add Shaun Burdick to Decision Reviews email list

- app/controllers/v1/pension_ipf_callbacks_controller.rb
- app/models/pension_ipf_notification.rb
- config/features.yml
- config/routes.rb
- config/settings/test.yml
- db/schema.rb
- spec/controllers/v1/pension_ipf_callbacks_controller_spec.rb
- spec/factories/pension_ipf_notifications.rb
- spec/models/pension_ipf_notification_spec.rb
- *This work is behind a feature toggle (flipper): YES, the `pension_ipf_callbacks_endpoint` flipper*
- created a new notification status callback to be used for the pension IPF reminder notification that will be sent.
- Persists and logs notification status for any given transaction ID. PII is scrubbed from the logs.
- Pension Benefits team to own this work.
- The template is ready so once this is deployed to production and the endpoint is configured in VANotify, we can turn on the flipper.
- [*Link to ticket created in va.gov-team repo*](https://github.com/department-of-veterans-affairs/va.gov-team/issues/69766)
- [*Link to epic if not included in ticket*](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/6976 …
> Created a VANotify status endpoint for Pension IPF Notification

- config/features.yml
- Removed two unused flipper toggles
- Not a bug
- Team IIR, we are the current owners
https://github.com/department-of-veterans-affairs/va-iir/issues/465
https://github.com/department-of-veterans-affairs/va-iir/issues/242
- Prior to this change, two unused feature toggles appeared in flipper
- To verify, navigate to `http://localhost:3000/flipper/features` and confirm that these two toggles do not appear
- Testing consisted of a code search to confirm that these toggles are unused
None
This only affects …
> Removed unused Yellow Ribbon feature toggles

- modules/check_in/app/controllers/check_in/v2/patient_check_ins_controller.rb
- modules/check_in/app/models/check_in/v2/session.rb
- modules/check_in/app/services/v2/lorota/service.rb
- modules/check_in/spec/models/check_in/v2/session_spec.rb
- modules/check_in/spec/services/v2/lorota/service_spec.rb
For OH sites, there's no concept of "check in" currently, and so there's no concept of refresh appointments and those calls will fail if made. This PR checks the incoming parameter for facility_type = OH, and doesn't call CHIP's refresh_appointments for that case.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/78648
> 78648 do not call refresh_appts for OH claims

- Gemfile.lock
- modules/simple_forms_api/app/services/simple_forms_api/pdf_stamper.rb
- modules/simple_forms_api/spec/fixtures/form_json/form_with_dangerous_characters_21P_0847.json
- modules/simple_forms_api/spec/fixtures/form_json/form_with_dangerous_characters_21_0845.json
- modules/simple_forms_api/spec/fixtures/form_json/form_with_dangerous_characters_21_10210.json
- modules/simple_forms_api/spec/fixtures/form_json/form_with_dangerous_characters_21_4142.json
- modules/simple_forms_api/spec/fixtures/form_json/form_with_dangerous_characters_unhandled.json
- modules/simple_forms_api/spec/fixtures/form_json/vba_21_0845.json
- modules/simple_forms_api/spec/fixtures/form_json/vba_21_10210-min.json
- modules/simple_forms_api/spec/fixtures/form_json/vba_21_10210.json
- modules/simple_forms_api/spec/fixtures/form_json/vba_21p_0847-min.json
- modules/simple_forms_api/spec/fixtures/form_json/vba_21p_0847.json
- modules/simple_forms_api/spec/services/pdf_filler_spec.rb
- modules/simple_forms_api/spec/services/pdf_stamper_spec.rb
- Added a lambda method which verifies when a stamp has successfully been applied to a pdf
- Added test coverage surrounding new logic
- Updated existing test coverage for the pdf_stamper class to align with RSpec patterns
department-of-veterans-affairs/VA.gov-team-forms#1115
- PDF Stamping and Filling
> [1115] poc: add logic to verify a PDF was properly stamped

- lib/decision_review/utilities/pdf_validation/configuration.rb
This feature is controlled by a backend setting that is enabled in staging but not prod (yet): `Settings.decision_review.pdf_validation.enabled`
This fixes the configuration used in the [proxy service](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/decision_review/utilities/pdf_validation/service.rb) that was previously built but never fully switched on (see more details [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/74493#issuecomment-2012637042)) — we are now ready to use it, so I've been trying to fix the configurations to make sure it all works as expected. 
I recently learned that we are able to use the Decision Reviews API key in dev and staging as originally designed (through this service's [configuration inheriting the DR …
> [DR-74493] fix pdf validation config in prod

- config/features.yml
- modules/vaos/app/services/vaos/v2/systems_service.rb
Implementation and testing of VAOS clinic stop code filtering has been completed and it has been in place for over a month. The feature toggle and associated code is no longer needed.
This PR removes the **va_online_scheduling_clinic_filtering** feature toggle and associated Vets API code.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/78770
> VAOS Removed Clinic Stop Code Filtering Feature Toggle

- modules/vba_documents/app/sidekiq/vba_documents/upload_processor.rb
- modules/vba_documents/spec/request/v1/uploads_request_spec.rb
- modules/vba_documents/spec/request/v2/uploads_request_spec.rb
- modules/vba_documents/spec/sidekiq/upload_processor_spec.rb
A production issue began on March 25, 2024 where Benefits Intake API submissions were not being processed out of "uploaded" status. The issue is ongoing, and we suspect that it is caused by the job cancellation code, which is not in regular use. The job is currently succeeding quickly, but short-circuiting any of the real processing code, so it is not behaving as expected. No code changes were made this past week, so we suspect it may be related to the Redis upgrade. The job cancellation code calls Redis under the hood.
My team (Lighthouse Team Banana Peels) maintains the `vba_documents` module.
None, as this was discovered as a production issue.
Ensured that all Benefits Intake endpoints still return their expected response after removing the job cancellation code, and that records can …
> Remove Job Cancellation Code from `VBADocuments::UploadProcessor`

- modules/claims_api/lib/bgs_service/local_bgs.rb
- Match the BGS URI matching to be more specific for BGS
- no issue created
Requests to BGS (specifically using LocalBGS)
> Fix BGS breakers matching

- config/features.yml
- lib/disability_compensation/factories/api_provider_factory.rb
- lib/disability_compensation/providers/generate_pdf/evss_generate_pdf_provider.rb
- lib/disability_compensation/providers/generate_pdf/generate_pdf_provider.rb
- lib/disability_compensation/providers/generate_pdf/lighthouse_generate_pdf_provider.rb
- lib/sidekiq/form526_backup_submission_process/processor.rb
- spec/lib/disability_compensation/factories/api_provider_factory_spec.rb
- spec/lib/disability_compensation/providers/generate_pdf/evss_generate_pdf_provider_spec.rb
- spec/lib/disability_compensation/providers/generate_pdf/generate_pdf_provider_spec.rb
- spec/lib/disability_compensation/providers/generate_pdf/lighthouse_generate_pdf_provider_spec.rb
- spec/lib/sidekiq/form526_backup_submission_process/submit_spec.rb
- spec/lib/sidekiq/form526_job_status_tracker/job_tracker_spec.rb
- spec/support/disability_compensation_form/shared_examples/generate_pdf_service_provider.rb
"The palindrome ticket"
- FEATURE TOGGLE: disability_compensation_lighthouse_generate_pdf
- evss generate pdf provider
- lighthouse generate pdf provider stub
- unit tests
- [#77177](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/77177)
- Abstracts calls to EVSS /getPdf endpoint
- stubbed out Lighthouse /generatePdf provider
- backup process is still going through EVSS /getPdf endpoint
> dbex/77177: EVSS Migration - /generatePDF migration: Abstract references to EVSS /getpdf

- docker-compose-deps.yml
- docker-compose.review.yml
- docker-compose.yml
- docs/setup/native.md
- Updated the version of the REDIS docker instance from 5.0 to 6.2
- Bug is that, current `make up` fails due to version mismatch
- Update REDIS docker instance
- VES, we do not maintain
- No flipper
- https://dsva.slack.com/archives/CBU0KDSB1/p1711464627165309
- vets-api failed to start due to REDIS version mismatch
- Run `make up`
- I believe this is primarily a local environment change
(OPTIONAL)_What should the reviewers know in addition to the above. Is …
> Updating version of REDIS to 6.2 in the docker compose files.

- Gemfile.lock
- lib/rx/client.rb
- modules/mobile/spec/request/prescriptions_request_spec.rb
We were seeing an error when calling this with nil keys:
Common::Collection.bust([cache_key('getactiverx'), cache_key('gethistoryrx')])
We removed a failing test and updated methods related mobile-rx only.
More investigation is needed but for the time being this works.
No ticket related, investigating urgent issue
None
MHV mobile medications app
> removed cache busting for mobile rx

- spec/factories/mvi_profiles.rb
- spec/support/form1010cg_helpers/build_claim_data_for.rb
[faker](https://rubygems.org/gems/faker) v3.3.0 introduced a new warning: DEPRECATION WARNING: Faker::IDNumber is deprecated. Use Faker::IdNumber instead.
- Update Faker::IDNumber to Faker::IdNumber
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/79372
- No new tests added
> Fix Faker Deprecation Warning

- app/sidekiq/decision_review/nod_email_loader_job.rb
- spec/sidekiq/decision_review/nod_email_loader_job_spec.rb
Params for Sidekiq job need to be passed in as a hash instead of an object. This is owned by the Decision Reviews team.
#15795 
- Old behavior used a default S3 configuration so this issue did not occur until a separate S3 config was passed in
- Manually tested
* None aside from Sidekiq job queues
> 76818: Change config for NodEmailLoaderJob to use a hash

- db/migrate/20240313211432_add_status_to_inprogress_form.rb
- db/migrate/20240313211541_add_status_to_inprogress_form_default.rb
- db/schema.rb
- This work is behind a feature toggle (flipper): *NO*
- Adding new column to track submission status of in-progress forms internally
- Code is split into 3 PR's
- department-of-veterans-affairs/vets-api/pull/15873
- department-of-veterans-affairs/vets-api/pull/16094
- department-of-veterans-affairs/vets-api/pull/16097
- department-of-veterans-affairs/va.gov-team/issues/77171
- Ran db migration and rake task locally, verified code in final PR works
- ~[ ] *New code is covered by unit tests*~
- ~*Describe what the old behavior was prior to the change*~
- ~*Describe the steps required to verify your changes are working as expected. Exclusively stating 'Specs run' is NOT acceptable as appropriate testing*~
- ~*If this work is behind a flipper:*~
- ~*Tests need to be written for both the …
> Add Status Column to InProgressForm

- config/features.yml
- modules/vaos/app/controllers/vaos/v2/facilities_controller.rb
- modules/vaos/spec/request/v2/facilities_request_spec.rb
This PR removes the obsolete feature flag `va_online_scheduling_required_schedulable_param` and its references in this repo. This flag is currently enabled in [staging](https://staging-api.va.gov/v0/feature_toggles?cookie_id) and [production](https://api.va.gov/v0/feature_toggles).
For testing disable the following feature flags and confirm scheduling appointments are working as expected. Refer to [this checklist](https://github.com/department-of-veterans-affairs/va.gov-team/issues/59503#issuecomment-1626071303) for a full list of scenarios.
- Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/63682. 
- Prior to this change, `schedulable` is forced to `true` only if the feature flag is enabled. Now the feature flag is removed, this parameter is always set to …
> Remove reference to va_online_scheduling_required_schedulable_param feature flag

- lib/medical_records/client.rb
- spec/lib/medical_records/client_spec.rb
- Abstracted out the "no-cache" header so it is automatically added to all FHIR search query requests.
> Make sure we add the appropriate "no-cache" header for all domains.
- Added additional testing to verify no-cache header is added.
> MHV-56394 Add no-cache header to all FHIR search query requests

- .github/scripts/validate-datadog-yaml/datadog-schema2.2.json
- .github/workflows/datadog_service_catalog_update.yml
- .github/workflows/validate-datadog-changes.yml
- datadog-service-catalog/datadog-service-catalog.yml
- datadog-service-catalog/debt-resolution.yml
This PR does 2 things:
- exports the [MHV appointments service catalog entry](https://vagov.ddog-gov.com/apm/services/mhv-appointments/operations/rack.request/resources?dependencyMap=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&env=eks-prod&fromUser=false&groupMapByOperation=null&hostGroup=&operationName=rack.request&panels=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&resources=qson%3A%28data%3A%28visible%3A%21t%2Chits%3A%28selected%3Atotal%29%2Cerrors%3A%28selected%3Atotal%29%2Clatency%3A%28selected%3Ap95%29%2CtopN%3A%215%29%2Cversion%3A%211%29&summary=qson%3A%28data%3A%28visible%3A%21t%2Cerrors%3A%28selected%3Acount%29%2Chits%3A%28selected%3Acount%29%2Clatency%3A%28selected%3Alatency%2Cslot%3A%28agg%3A95%29%2Cdistribution%3A%28isLogScale%3A%21f%29%2CshowTraceOutliers%3A%21t%29%2Csublayer%3 …
> Add mhv-appointments to datadog service catalog

- lib/lighthouse/service_exception.rb
Due to a Faraday update in Dec 2023, the Faraday error response object contains request data by default. The `Lighthouse::ServiceException` class was logging the full response, so sensitive data from the request was being sent to Datadog.
The initial action taken was to remove some of the logging from `Lighthouse::ServiceException`.  This PR restores the logging and addresses this issue.  A ticket is set to be opened to apply additional enhancements/refactorings to this class.
Additionally, [PR #16105](https://github.com/department-of-veterans-affairs/vets-api/pull/16105) sets an option within the Faraday middleware to remove the request. 
[This postmortem](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/2024/2024-03-22%20-%20Profile%20-%20Cn …
> Add logging back to lighthouse service exception class

- modules/travel_pay/app/services/travel_pay/client.rb
- modules/travel_pay/spec/services/client_spec.rb
A discrepancy between the test faraday connection and the real faraday connection broke code due to false confidence in tests.
> Fixes error due to testing data

- app/services/claim_fast_tracking/max_rating_annotator.rb
- config/features.yml
- spec/services/claim_fast_tracking/max_rating_annotator_spec.rb
- spec/support/vcr_cassettes/virtual_regional_office/max_ratings_multiple.yml
- spec/support/vcr_cassettes/virtual_regional_office/max_ratings_none.yml
- This work is behind a feature toggle (flipper): **YES**
- Removes the previous feature toggle that enabled/disabled use of the VRO client to make requests to the Max-CFI API. Adds in a new feature toggle that enables sending requests for all conditions. If disabled, only requests for select disabilities are made to obtain the max rating from the Max-CFI API. Employee Experience is expanding max rating notices for all diagnostic codes, and want all requests to be made through that client for all conditions. This new feature toggle is to only show the unchanged max rating for tinnitus until the downstream API is ready for other diagnostic codes.
- I am part of the Claims Fast-Tracking crew's Employee Experience team. We work closely with the Disability Experience team which owns this …
> Update Employee Experience Max CFI API Feature toggle

- Gemfile.lock
- Which team do you work for, does your team own the maintenance of this component? 10-10 Health Enrollment team
- Updates the `vets_json_schema` version to the latest master revision via `bundle update vets_json_schema`
- 10-10 Health Enrollment Team
- [Ticket #78506](https://github.com/department-of-veterans-affairs/va.gov-team/issues/78506)
- confirmed that the version and revision are updated in Gemfile.lock
- I've left out the `bundle update`'s removal of the `sidekiq` gems and their `einhorn` dependency, per the README's instructions.
> Update vets_json_schema to new master version

- config/features.yml
- modules/check_in/app/services/travel_claim/client.rb
- modules/check_in/spec/services/travel_claim/client_spec.rb
- modules/check_in/spec/sidekiq/travel_claim_submission_worker_spec.rb
This PR removes the feature flag that was used to add the the code to increase the Faraday timeout to 120 seconds for travel claims API client. The code has been running correctly in production for a while, and this feature flag is no longer necessary.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/79628
> 79628 remove travel claims increase timeout flag

- modules/debts_api/lib/debts_api/v0/financial_status_report_service.rb
- modules/debts_api/lib/debts_api/v0/fsr_form_builder.rb
- modules/debts_api/spec/lib/debt_api/v0/fsr_form_builder_spec.rb
After submitting a 5655 submission we want to delete the related InProgressForm. This will prevent repeat submissions of the same FSR.
[78148](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/78148)
[72987](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/72987)
Specs added
FSR submission, Debt Portal
After all 5655 submissions for a combined FSR have been created the related InProgressForm is deleted.
> 78148 Delete InProgressForm after submitting 5655

- modules/ask_va_api/app/controllers/ask_va_api/v0/inquiries_controller.rb
- modules/ask_va_api/app/lib/ask_va_api/correspondences/creator.rb
- modules/ask_va_api/config/routes.rb
- modules/ask_va_api/spec/app/lib/ask_va_api/correspondences/creator_spec.rb
- modules/ask_va_api/spec/requests/v0/inquiries_spec.rb
1. **Service Class Addition:** Implemented `Correspondences::Creator` to handle the creation of replies, ensuring that business logic is encapsulated and reusable.
2. **Controller Action:** Added `Inquiries#create_reply` action, which utilizes the `Correspondences::Creator` to create a reply tied to a specific inquiry.
3. **Routing:** Extended `routes.rb` to include a new route `/inquiries/:id/reply/new`, facilitating the creation of new replies through a RESTful interface.
This update streamlines the process of replying to inquiries, making our interaction with users more efficient and organized.
- https://github.com/department-of-veterans-affairs/ask-va/issues/526
> Create `Inquiries#create_reply` endpoint

- modules/vba_documents/app/sidekiq/vba_documents/upload_processor.rb
This PR removes some performance benchmarking code that was added to the `VBADocuments::UploadProcessor` job last year in order to capture timing metrics on each step of the job. These metrics were used to determine the areas for performance improvement. The code was only intended to be put in place temporarily. This PR removes it to reduce the chances of a production error from the code and to improve readability of the job.
My team (Lighthouse Team Banana Peels) maintains the `vba_documents` module.
[API-35187](https://jira.devops.va.gov/browse/API-35187)
The `VBADocuments::UploadProcessor` job was run locally to confirm that behavior of the job did not change. In addition, all unit tests are still passing.
None
The PR impacts the `vba_documents` module only, and specifically the …
> API-35187: Remove Performance Benchmark Code from `VBADocuments::UploadProcessor`

- app/controllers/v1/pension_ipf_callbacks_controller.rb
- Added more temp logging for debugging bearer token auth issue in staging.
- Pension benefits team to own this change.
- https://github.com/department-of-veterans-affairs/vets-api/pull/16154
*(Describe what parts of the site are impacted and*if*code touched …
> added more temp logging to debug in staging

- app/controllers/v1/sessions_controller.rb
- This PR updates the SSOe login.gov verified authentication call to use the `exact` authn context instead of `min`. This is necessary because a regression was previously introduced when SSOe IAM interface with login.gov transitioned to using OIDC login.gov flow, and the way certain authn patterns work was changed.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/79732
SSOe Authentication
> [79732] Updating login.gov verified SSOe calls to use 'exact' authn context instead of 'min'

- lib/lighthouse/direct_deposit/control_information.rb
- spec/lib/lighthouse/direct_deposit/control_information_spec.rb
Add logic to direct deposit control information class.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/79248
`spec/lib/lighthouse/direct_deposit/control_information_spec.rb`
> Add logic to direct deposit control info

- modules/check_in/app/controllers/check_in/v2/patient_check_ins_controller.rb
- modules/check_in/spec/request/v2/demographics_request_spec.rb
- modules/check_in/spec/request/v2/patient_check_ins_request_spec.rb
- modules/check_in/spec/request/v2/pre_check_ins_request_spec.rb
- *Removing `check_in_experience_45_minute_reminder` feature flag*
- *[Link to ticket](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/79630)*
NA
> 79630 Removing check_in_experience_45_minute_reminder feature flag

- modules/vaos/app/controllers/vaos/v2/appointments_controller.rb
- modules/vaos/spec/controllers/v2/appointments_controller_spec.rb
This fixes the `NoMethodError: undefined method `any?' for nil:NilClass` errors seen in Staging when logging Cerner information. It adds safe navigation to the **VAOS::V2::Appointments#merge_facilities** method.
- [PR-16164](https://github.com/department-of-veterans-affairs/vets-api/pull/16164)
- Added RSpec test for the error condition
> VAOS Added Safe Navigation When Checking Location Value

- app/models/concerns/form526_claim_fast_tracking_concern.rb
- spec/sidekiq/evss/disability_compensation_form/submit_form526_all_claim_spec.rb
*This work is behind a feature toggle (flipper): YES* (`disability_526_ep_merge_api`)
This PR improves two aspects of EP400 Merging:
- Add Lighthouse-compatible open claim statuses that are equivalent to the existing EVSS ones
- Switch from StatsD to Rails.logger for more precise data visibility on DataDog
I am part of the Claims Fast-Tracking crew's Employee Experience team. We work closely with the Disability Experience team which owns this code.
- [Slack conversation](https://dsva.slack.com/archives/C01BVF2A3V0/p1712081164187339) about Lighthouse claim statuses
- Previous work in #14144 to tweak StatsD data format
- Old behavior: data logged to `StatsD.distribution`
- New behavior: data logged to `Rails.logger.info`
* No impact on users
> Improve EP Merge logging and claim status compatibility

- config/routes.rb
- lib/lighthouse/direct_deposit/error_parser.rb
- spec/controllers/v0/profile/direct_deposits/disability_compensations_controller_spec.rb
Two direct deposit changes:
- Add additional route `v0/profile/direct_deposits`.
- When `profile_show_direct_deposit_single_form` is on, set prefix on error codes to `direct.deposit` instead of `cnp.payment`.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/79767
Specs added to `disability_compensations_controller_spec.rb` to test:
- Additional route
- Feature flag for error code prefixes
> Update direct deposit error codes and add additional route

- modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb
- modules/simple_forms_api/app/services/simple_forms_api/pdf_stamper.rb
- modules/simple_forms_api/spec/fixtures/form_json/form_with_accented_chars_21_0966.json
- modules/simple_forms_api/spec/fixtures/form_json/form_with_non_latin_chars_21_0966.json
- modules/simple_forms_api/spec/requests/v1/uploads_spec.rb
This PR makes the simple forms controller specify if an error arises because of untransliteratable characters.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/864
New test written but it's mysteriously failing.
Instead of the scrubbed error, this is what we send to the FE:
> Handle transliteration errors separately from other errors in Simple Forms

- lib/lgy/service.rb
This PR more properly distinguishes between `lgy` and `lgy_sahsha`, which should have two different app ids and api keys.
> Specify lgy_sahsha in grant manager headers and endpoint

- modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb
- modules/simple_forms_api/spec/requests/v1/uploads_spec.rb
I had previously been under the incorrect assumption that our staging env ran in the Rails `staging` environment. But it actually runs in `production`. So my prior code won't work and I will take a blunter approach of just allowing all 26-4555 traffic to use the LGY API, for now. This will be reverted later, once we release the form and are confident that it works.
> Always send 26-4555 to SAHSHA regardless of auth status

- modules/travel_pay/app/services/travel_pay/client.rb
Found issue while working on https://github.com/department-of-veterans-affairs/va.gov-team/issues/73503 - looks like the `BTSSS-API-Client-Number` header is an `integer` that needs to be converted to a `string`. Sending this request without converting the header to a `string` caused some Faraday errors.
> Fix for implementing travel pay client number header

- lib/decision_review_v1/appeals/supplemental_claim_services.rb
- spec/requests/v1/supplemental_claims/contestable_issues_controller_request_spec.rb
Follow-up to #16176 to make things a little easier to review. This covers adding logging to SC contestable issues
https://github.com/department-of-veterans-affairs/va.gov-team/issues/65545
- Will do a test on staging to check that uploads/form submission both work and logs are showing up in DataDog as expected
The Supplemental Claims form
> [DR-65545] Log KPIs for Supplemental Claims (contestable issues)

- modules/vaos/app/controllers/vaos/v2/appointments_controller.rb
- modules/vaos/spec/request/v2/appointments_request_spec.rb
- We are not handling facilities lookup errors gracefully for logging purposes leading to an exception. This changes ensures we disable logging for these error cases. More details are in the linked issue.
- Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/80022
- A new test to ensure no logging is detected on facilities lookup error is added to ensure we handle this case gracefully.
N/A
N/A
> Ensure logging is disabled on facilities retrieval error

- lib/rx/client.rb
- modules/my_health/app/controllers/my_health/v1/prescriptions_controller.rb
- spec/lib/rx/client_spec.rb
- Update the refill_prescriptions function to return failed and successful ids.
- https://jira.devops.va.gov/browse/MHV-55962
MHV medications refill page
> Refill Confirmation Changes

- modules/vaos/app/controllers/vaos/v2/appointments_controller.rb
- modules/vaos/spec/request/v2/appointments_request_spec.rb
- This work is a fix to the logic that identifies cerner appointments and extracts values from facility details to check for a given substring
- ZH#80022
- tested functionality of new methods, ran regression tests
> extract values and check substring for cerner logging

- .github/CODEOWNERS
- app/models/saved_claim/burial.rb
- *NO*
- Added two new keys in anticipation of new upload keys for 530EZ V2
- Solution is adding the two new keys so that uploads can process
- [*Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses Jira*](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80173)
- Complete a V2 burial claim and confirm the uploads for additional evidence and military separation documents are attached.
Burials V2 …
> add new keys to attachment keys in anticipation of v2

- app/swagger/swagger/schemas/contacts.rb
- config/database.yml
- lib/va_profile/models/associated_person.rb
- lib/va_profile/profile/v3/health_benefit_bio_response.rb
- lib/va_profile/profile/v3/service.rb
- spec/controllers/v0/profile/contacts_controller_spec.rb
- spec/lib/va_profile/models/associated_person_spec.rb
- spec/lib/va_profile/profile/v3/health_benefit_bio_response_spec.rb
- spec/lib/va_profile/profile/v3/service_spec.rb
- spec/requests/va_profile/contacts_request_spec.rb
Prepare `profile_contacts` feature for canary release
- *This work is behind a feature toggle (flipper): YES* `profile_contacts`
- Adds call to `Sentry.set_extras` to include service response status code, primary error message, and audit id from source system when response is not ok
- Updates specs
- department-of-veterans-affairs/va.gov-team#79017
- *Describe what the old behavior was prior to the change*: Non 200 requests did not call `Sentry.set_extras`
- *Describe the steps required to verify your changes are working as expected. Exclusively stating 'Specs run' is NOT acceptable as appropriate testing*: Sign in with a user w/o a record in ES, verify Sentry/Datadog picks up debug data
- *Tests need to be written for both the flipper on and flipper …
> Adds debugging info to /v0/profile/contacts endpoint

- modules/vaos/app/schemas/appointments_index.json
- modules/vaos/app/services/vaos/v2/appointments_service.rb
Makes corrections to expected schema and prevents running the checks on empty data.
https://github.com/department-of-veterans-affairs/va-mobile-app/issues/8189
- specs. 
Could impact appointments index but shouldn't impact anything.
> 8189 appointments index schema corrections

- modules/mobile/lib/scripts/parse_rspec_xml.rb
- modules/mobile/spec/request/v1/user_request_spec.rb
This (hopefully) fixes a flaky spec, along with adds a script that helps us debug tests in the future
None
> Mobile: Add script that aids in debugging + Spec Fix

- app/controllers/v0/terms_of_use_agreements_controller.rb
- app/services/terms_of_use/provisioner.rb
- spec/controllers/v0/terms_of_use_agreements_controller_spec.rb
- spec/services/terms_of_use/provisioner_spec.rb
-Add more logging around ToU provisioning step
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/80259
- change [services/terms_of_use/provisioner.rb#L28](https://github.com/department-of-veterans-affairs/vets-api/blob/c7d8500391342fbbe7e92cc3442861a871c5fb79/app/services/terms_of_use/provisioner.rb#L28) to `if true`:
```ruby
if true
Rails.logger.error('[TermsOfUse] [Provisioner] update_provisioning error', { icn:, response: })
raise(Errors::ProvisionerError, 'Agreement not accepted')
end
``` 
- in rails console run:
```ruby
TermsOfUse::Provisioner.new(icn: '1234567V8902', first_name: 'Test', last_name: 'User', mpi_gcids: ['test']).perform
```
you should see the error log printed
```ruby
2024-04-08 11:00:40.710601 E [76673:12120 provisioner.rb:29] Rails -- …
```
> Add logging around tou provisioning

- config/features.yml
Added `cst_use_dd_rum` feature toggle to `vets-api`.
Files affected:
- `config/features.yml`
Ticket for this work: [Create feature toggle to test RUM PII masking](https://github.com/department-of-veterans-affairs/va.gov-team/issues/79925)
Related Frontend PR: [[CST] [Frontend] Added cst_use_dd_rum feature flag for used with CST DataDog RUM logging](https://github.com/department-of-veterans-affairs/vets-website/pull/29076)
> [CST] [Backend] Added feature toggle for CST to use DataDog RUM monitoring

- lib/decision_review_v1/service.rb
- spec/requests/v1/higher_level_reviews/contestable_issues_controller_request_spec.rb
- spec/requests/v1/higher_level_reviews_controller_request_spec.rb
In #13973, Eugene added more comprehensive logging for our NOD form and in #16176 / #16179 I added similar logging for Supplemental Claims — this PR adds similarly structured logging for Higher Level Reviews
https://github.com/department-of-veterans-affairs/va.gov-team/issues/65544
- Will do a test on staging to check that form submission and contestable issues work and logs are showing up in DataDog as expected
The Higher Level Reviews form
> [DR-65544] Log KPIs for Higher Level Reviews (create + contestable issues)

- app/models/form_attachment.rb
- spec/models/form_attachment_spec.rb
This PR fixes an issue where password-protected PDFs whose extensions were not downcased were uploaded to S3 without first being unlocked, thus resulting in the documents being inaccessible to downstream services.
- This work is behind a feature toggle (flipper): ~YES~/NO
- In addition to making the pdf extension evaluation case insensitive, the RegEx utilized for sanitizing error messages has also been modified to match the extension pattern case-insensitively.
- Disability Benefits Experience Team 2 (dBeX Carbs 🥖)
- [78539](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/78539)
- Corresponding test file passes with extension casing change
526EZ application document uploads and other …
> DBEX: make pdf extension evaluation case insensitive

- modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb
- modules/simple_forms_api/spec/requests/v1/uploads_spec.rb
This PR clears an InProgressForm whenever the authenticated user successfully submits that form. Not having this has caused some strange/buggy behavior and it seems like it's on us to clean these up on each submission.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/80432
New test written.
> Simple Forms delete InProgressForm with every successful form submission

- modules/mobile/app/controllers/mobile/v1/messages_controller.rb
- modules/mobile/spec/request/v1/messages_request_spec.rb
Fixes handling when excludeProvidedMessage param is false.
https://github.com/department-of-veterans-affairs/va-mobile-app/issues/8346
Specs. Will be tested on staging. 
Just the handling of this one param in this one controller.
> 8346: fix excludeProvidedMessage false handling

- app/services/claim_fast_tracking/max_rating_annotator.rb
- spec/services/claim_fast_tracking/max_rating_annotator_spec.rb
- This PR adjusts the logic to handle multiple disabilities with the same diagnostic code when assigning the `maximum_rating` to disabilities returned in the rated disabilities response used to populate information on the rated disabilities page of the Form 526EZ. 
- I am part of the Claims Fast-Tracking crew's Employee Experience team. We work closely with the Disability Experience team which owns this code.
- discovered during work on another ticket related to displaying the maximum rating: https://github.com/department-of-veterans-affairs/abd-vro/issues/2722 
- ticket to fix: https://github.com/department-of-veterans-affairs/abd-vro/issues/2849
- New code is covered by new unit tests for multiple disabilities with same diagnostic …
> Handle case where mutliple disabilities could have same diagnostic code.

- lib/pdf_fill/forms/va21p530v2.rb
- spec/fixtures/pdf_fill/21P-530V2/merge_fields.json
- bug discovered in E2E testing where PDF filler was not marking checkbox correctly. this ticket syncs the field names to match what vets-website sends 
- Fill out v2 Burial form, mark relationship to Veteran as Other or Funeral Home, submit form, pull PDF from Benefits Intake and validate it is marked correctly
- https://app.zenhub.com/workspaces/benefits-non-disability-645913c7d909c20011380ae8/issues/gh/department-of-veterans-affairs/va.gov-team/80575
- Manual testing of PDF after submission
(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with …
> [BUG] - Fixing mismatch between website and pdf mapper

- config/settings.yml
- lib/saml/post_url_service.rb
- lib/saml/url_service.rb
- spec/controllers/v1/sessions_controller_spec.rb
- spec/lib/saml/post_url_service_spec.rb
- Move terms of use enabled_clients to settings
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/80260
- https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2803
- https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2804
- Sign in with SSOe with a user that hasn't accepted ToU
- You should be required to accept before you're able to proceed 
Terms of use
> Move terms_of_use enabled_clients to settings

- Dangerfile
- app/controllers/appeals_base_controller.rb
I'm not sure why, but the Danger CI check in PRs started failing last night. [Example output](https://github.com/department-of-veterans-affairs/vets-api/actions/runs/8661505007/job/23752901332).
**Error**:
```
[!] Invalid Dangerfile file: uninitialized constant Danger::Dangerfile::VSPDanger::ChangeLimiter::OpenStruct
>          OpenStruct.new(
```
The failure was reported to support: https://dsva.slack.com/archives/CBU0KDSB1/p1712923438985509
> Require `ostruct` in Dangerfile

- config/features.yml
- modules/appeals_api/app/models/appeals_api/higher_level_review.rb
- modules/appeals_api/app/models/appeals_api/notice_of_disagreement.rb
- modules/appeals_api/app/models/appeals_api/supplemental_claim.rb
- modules/appeals_api/app/models/concerns/appeals_api/appeal_scopes.rb
- modules/appeals_api/app/services/appeals_api/remove_pii.rb
- modules/appeals_api/spec/services/appeals_api/remove_pii_spec.rb
- Uses updated logic for removal of PII from decision reviews records - this behavior is controlled by the `decision_review_updated_pii_rules` Flipper flag.
- See comments below
- [API-34961](https://jira.devops.va.gov/browse/API-34961)
- Affects PII clearing logic for Higher-Level Reviews, Notice of Disagreements, and Supplemental Claims within the Decision Reviews v2 API and the individual v0 APIs specific to each appeal type
> API-34961 Update Decision Reviews PII removal policy

- app/controllers/v0/profile/direct_deposits_controller.rb
- lib/lighthouse/direct_deposit/error_parser.rb
- lib/lighthouse/direct_deposit/error_response.rb
- spec/controllers/v0/profile/direct_deposits/disability_compensations_controller_spec.rb
Move `profile_show_direct_deposit_single_form` feature flag to direct deposit controller.  This flag will toggle error code prefixes for direct deposit.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/79767
- direct_deposits_controller_spec
- disability_compensations_controller_spec
> Update feature flag for direct deposit merge

- app/sidekiq/kms_key_rotation/batch_initiator_job.rb
- KmsKeyRotation::BatchInitiatorJob#gids_for_model doesn't include records with nil key
- Add `.or(model.where(encrypted_kms_key: nil))` to include in key rotation job
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/80721
- Manual testing
> KmsKeyRotation::BatchInitiatorJob nil encrypted_kms_key error

- db/migrate/20240411153944_create_average_days_for_claim_completions.rb
This is an immediate fix due to a missing colon which should've been done during the migration.
> Fixing missing atom symbol for field name.

- modules/ask_va_api/app/controllers/ask_va_api/application_controller.rb
- modules/ask_va_api/app/controllers/ask_va_api/v0/inquiries_controller.rb
- modules/ask_va_api/app/lib/ask_va_api/base_retriever.rb
- modules/ask_va_api/app/lib/ask_va_api/correspondences/entity.rb
- modules/ask_va_api/app/lib/ask_va_api/correspondences/retriever.rb
- modules/ask_va_api/app/lib/ask_va_api/correspondences/serializer.rb
- modules/ask_va_api/app/lib/ask_va_api/inquiries/retriever.rb
- modules/ask_va_api/config/locales/get_replies_mock_data.json
- modules/ask_va_api/spec/app/lib/ask_va_api/correspondences/entity_spec.rb
- modules/ask_va_api/spec/app/lib/ask_va_api/correspondences/retriever_spec.rb
- modules/ask_va_api/spec/app/lib/ask_va_api/correspondences/serializer_spec.rb
- modules/ask_va_api/spec/app/lib/ask_va_api/inquiries/retriever_spec.rb
- modules/ask_va_api/spec/app/lib/ask_va_api/optionset/retriever_spec.rb
- modules/ask_va_api/spec/app/lib/ask_va_api/optionset/serializer_spec.rb
- modules/ask_va_api/spec/requests/v0/inquiries_spec.rb
**Enhancements and Refactoring**
This pull request introduces several enhancements and refactoring across different modules of the application:
1. **Streamlined ApplicationController and Associated Specs:**
- Removed an unused `rescue` block from the `ApplicationController`.
- Aligned the `get_replies_mock_data.json` file with `CRM API` conventions.
- Resolved failing tests in the `Optionset` module's `retriever_spec.rb` and `serializer_spec.rb`.
2. **Enhanced Correspondences Module:**
- Improved functionality in the `Correspondences::Entity` class.
- Updated logic in the `Correspondences::Retriever` class.
- Revised serialization in the `Correspondences::Serializer` class.
3. **Enhanced Inquiries::Retriever and InquiriesController:**
- Unified the retrieval process using `BaseRetriever` …
> BE | Ask Va Api:  retrieve inquiries endpoint

- modules/simple_forms_api/app/models/simple_forms_api/vba_20_10207.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_21_0845.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_21_0966.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_21_0972.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_21_10210.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_21_4142.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_21p_0847.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_26_4555.rb
- modules/simple_forms_api/app/models/simple_forms_api/vha_10_7959f_1.rb
- modules/simple_forms_api/app/services/simple_forms_api/pdf_stamper.rb
- modules/simple_forms_api/spec/services/pdf_stamper_spec.rb
This PR takes part of the work from this draft PR: https://github.com/department-of-veterans-affairs/vets-api/pull/16242 and separates it into its own standalone PR. This should be more easily reviewable. I can then come back and apply part 2 in a separate PR and close out the aforementioned draft PR.
This is some refactoring of our PDF Stamper class with the ultimate aim of making it more uniform in how it handles desired stamps.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/1198
Tests altered and passing.
> Simple Forms: Refactor PDF Stamper Part 1

- lib/lighthouse/benefits_intake/metadata.rb
- spec/lib/lighthouse/benefits_intake/metadata_spec.rb
add metadata validation for centralized lighthouse benefits intake service
https://github.com/department-of-veterans-affairs/va.gov-team/issues/75579
https://github.com/department-of-veterans-affairs/vets-api/pull/16332
https://github.com/department-of-veterans-affairs/vets-api/pull/16324
- it is not needed to be behind a flipper, does not affect current applications
- tested locally via console
None
> Lighthouse Benefits Intake Metadata

- modules/mobile/app/services/mobile/v0/lighthouse_claims/proxy.rb
- modules/mobile/spec/request/claims_and_appeals_overview_request_spec.rb
This should reduce/remove claim decision letter 404s when combining lighthouse with EVSS
https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8324
Added test to ensure EVSSClaim are being created even when using lighthouse
(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, …
> Mobile: Create EVSSClaim even when using lighthouse

- .github/CODEOWNERS
- config/settings.yml
- lib/lighthouse/benefits_intake/configuration.rb
- spec/lib/lighthouse/benefits_intake/configuration_spec.rb
add configuration for centralized lighthouse benefits intake service
https://github.com/department-of-veterans-affairs/va.gov-team/issues/75579
https://github.com/department-of-veterans-affairs/vets-api/pull/16333
https://github.com/department-of-veterans-affairs/vets-api/pull/16324
- it is not needed to be behind a flipper, does not affect current applications
- tested locally via console
- add local config - [request sandbox api_key here](https://developer.va.gov/explore/api/benefits-intake/sandbox-access)
```
lighthouse:
benefits_intake:
host: https://sandbox-api.va.gov
path: /services/vba_documents
version: v1
use_mocks: false
api_key: API_KEY
```
None
> Lighthouse Benefits Intake Configuration

- db/migrate/20240411160306_create_accredited_organizations.rb
- db/schema.rb
References https://github.com/department-of-veterans-affairs/va.gov-team/issues/80656
This PR creates the following new table:
- accredited_organizations
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/80656
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/78731
- NA
The database
The schema.rb file
> Create accredited_organizations table

- modules/simple_forms_api/app/form_mappings/vba_20_10207.json.erb
- modules/simple_forms_api/app/services/simple_forms_api/pdf_stamper.rb
- modules/simple_forms_api/spec/fixtures/form_json/vba_20_10207-veteran.json
This small PR does two things:
1. Fix another data mapping bug with 20-10207 (the `Other1[0]` is on page 4 not 3)
2. When stamping the auth text, we want it to stamp on every page. Therefore we should _not_ pass a `page` argument.
The JSON update is incidental. It just makes the data make more sense.
> Fix 20-10207 mapping and date stamp bug

- modules/simple_forms_api/spec/requests/v1/uploads_spec.rb
This PR refactors the Simple Forms upload spec in hopes of quashing an intermittent test failure. It replaces all use of `VCR.use_cassette()` with `VCR.insert_cassette()` and `VCR.eject_cassette`. I haven't been able to get the tests to fail for me locally so this is kind of a stab in the dark.
> Refactor uploads spec, simple forms

- config/betamocks/services_config.yml
- config/settings.yml
- modules/simple_forms_api/spec/requests/v1/uploads_spec.rb
- modules/travel_pay/app/controllers/travel_pay/application_controller.rb
- modules/travel_pay/app/controllers/travel_pay/claims_controller.rb
- modules/travel_pay/app/controllers/travel_pay/pings_controller.rb
- modules/travel_pay/app/services/travel_pay/client.rb
> Merge master into k8s

- lib/saml/post_url_service.rb
- spec/lib/saml/post_url_service_spec.rb
- This PR updates the logic to determine whether to display the terms of use page to include authentication paths that may have originated with a Terms of Use enabled application but are now being authenticated with `custom` as a secondary part of the flow
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/80904
Authentication
> [80904] Creating a terms of use application check that occurs during secondary authentications with custom

- app/controllers/v0/profile/direct_deposits_controller.rb
- app/sidekiq/va_notify_dd_email_job.rb
- config/settings.yml
- lib/saml/post_url_service.rb
- modules/travel_pay/app/controllers/travel_pay/claims_controller.rb
- modules/travel_pay/app/controllers/travel_pay/pings_controller.rb
- modules/travel_pay/app/services/travel_pay/client.rb
- modules/travel_pay/spec/controllers/claims_controller_spec.rb
- modules/travel_pay/spec/controllers/pings_controller_spec.rb
- spec/controllers/v0/profile/direct_deposits_controller_spec.rb
- spec/lib/saml/post_url_service_spec.rb
- spec/sidekiq/va_notify_dd_email_job_spec.rb
https://dsva.slack.com/archives/C039HRTHXDH/p1713382904895529
> Fix conflict

- modules/ask_va_api/app/controllers/ask_va_api/v0/inquiries_controller.rb
- modules/ask_va_api/config/routes.rb
- modules/ask_va_api/spec/requests/v0/inquiries_spec.rb
- Created `test_create` endpoint to test `post` to `CRM API`
> BE | Ask Va Api: Add test_create endpoint

- modules/simple_forms_api/spec/requests/v1/uploads_spec.rb
> Added virus scan to uploads spec

- modules/claims_api/lib/bgs_service/local_bgs.rb
- modules/claims_api/lib/bgs_service/manage_representative_service.rb
- modules/claims_api/lib/bgs_service/manage_representative_service/read_poa_request.rb
- modules/claims_api/lib/bgs_service/manage_representative_service/update_poa_request.rb
- modules/claims_api/spec/lib/claims_api/manage_representative_service/read_poa_request_spec.rb
- modules/claims_api/spec/lib/claims_api/manage_representative_service/update_poa_request_spec.rb
- Refactor `LocalBGS#parsed_response` to streamline all "special cases" as one, particularly extricating the ITF special case
- Refactor `make_request` customization to come from arguments that caller passes instead
- Make BGS response transformation optional and opt out in `ManageRepresentativeService` operations (hypothesis is that the transformation has downsides and doesn't really have upsides, at least for this use case or whatever I could imagine)
> API-34439 option to not transform BGS response

- db/migrate/20240411161733_create_accredited_individuals_accredited_organizations.rb
- db/schema.rb
References https://github.com/department-of-veterans-affairs/va.gov-team/issues/80656
The following PRs must be merged first:
- https://github.com/department-of-veterans-affairs/vets-api/pull/16295
- https://github.com/department-of-veterans-affairs/vets-api/pull/16296
This PR creates the following new table:
- accredited_individuals_accredited_organizations
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/80656
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/78731
- NA
The database
The schema.rb file
> Create accredited_individuals_accredited_organizations table

- modules/accredited_representative_portal/app/services/accredited_representative_portal/representative_user_loader.rb
- Small updates to the `AccreditedRepresentativePortal::RepresentativeUserLoader` to remove unneeded logic related to MHV & DSLogon logins, as well as non-verified logins.
- These CSP types and ACRs are unavailable to ARP clients on USiP & will be blocked for ARP client authentications in new [SiS validation code](https://github.com/department-of-veterans-affairs/vets-api/pull/16241).
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/78003
- ARP authentication with ID.me & Login.gov users performed.
- Existing tests pass, CSP & ACR blocking logic covered in validation PR.
> [78003] removes MHV, DSLogon, and IAL/LOA1 references from rep user loader

- .github/CODEOWNERS
- app/models/form526_submission.rb
- app/sidekiq/form526_status_polling_job.rb
- lib/periodic_jobs.rb
- spec/factories/form526_submissions.rb
- spec/models/form526_submission_spec.rb
- spec/sidekiq/form526_status_polling_job_spec.rb
- Add a sidekiq job to poll the lighthouse benefits intake API for the status of form 526 submissions
- leverages the new  form 526 state to record results from the API
- adds a scope to the form 526 model for code readability
- schedules the job
- [ticket](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/77011)
- [ x ] *New code is covered by unit tests*
- previously we were manually polling these submissions and recording them in the state machine. This was relatively new, before that we simply weren't looking to see if things had failed.
- This job can be manually run in a production console safely, as data will only change in the way it's supposed to.
Form 526 backup submission
> Dbx 77011/add polling for backup submitted 526s

- config/features.yml
- We need a secondary feature toggle to turn on the new direct deposit single form for users during UAT. This PR adds a flag for that called `profile_show_direct_deposit_single_form_uat`
- We are also renaming the `profile_hide_direct_deposit_comp_and_pen` to be `profile_hide_direct_deposit` since it will no longer be related to comp and pen.
- 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/79412
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/80973
No UI changes
Profile -> Direct Deposit
> rename hide dd toggle, add uat toggle

- .github/CODEOWNERS
- app/models/ivc_champva_form.rb
- spec/factories/ivc_champva_forms.rb
- spec/models/ivc_champva_forms_spec.rb
After creating the table [here](https://github.com/department-of-veterans-affairs/vets-api/pull/16367) we needed to create a basic model with some lightweight tests.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/80872
None right now, new logic
Given that the system requires validation and tests for a new model,
When a IvcChampvaForms model is added,
Then I should be able to create, read, update, and delete products.
> 80872: Add ivc_champva_form model, factory and tests

- lib/lighthouse/direct_deposit/payment_account.rb
- spec/lib/lighthouse/direct_deposit/payment_account_spec.rb
Added validation rules to the direct deposit account number:
- allow alphanumeric
- ensure length is between 4 and 17
https://github.com/department-of-veterans-affairs/va.gov-team/issues/80306
- additional specs in `payment_account_spec.rb`
> Update direct deposit account number validation

- .github/CODEOWNERS
- modules/ivc_champva/app/controllers/ivc_champva/v1/uploads_controller.rb
- modules/ivc_champva/app/models/ivc_champva/vha_10_10d.rb
- modules/ivc_champva/app/models/ivc_champva/vha_10_7959c.rb
- modules/ivc_champva/app/models/ivc_champva/vha_10_7959f_1.rb
- modules/ivc_champva/app/models/ivc_champva/vha_10_7959f_2.rb
- modules/ivc_champva/app/services/ivc_champva/metadata_validator.rb
- modules/ivc_champva/lib/tasks/forms.rake
- modules/ivc_champva/spec/models/vha_10_10d_spec.rb
- modules/ivc_champva/spec/models/vha_10_7959c_spec.rb
- modules/ivc_champva/spec/models/vha_10_7959f_1_spec.rb
- modules/ivc_champva/spec/models/vha_10_7959f_2_spec.rb
- modules/ivc_champva/spec/services/metadata_validator_spec.rb
Wire up the logic to handle zip code formatting based on metadata country value.
- Add `country` to the form metadata methods
- Update tests accordingly
- Update `form.rake` for new forms
- Removed code that isn't in use
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/79708
- None, all new
> 79708: Add country to metadata to properly handle zipcode formatting

- config/initializers/datadog.rb
This PR adds configuration for [Datadog version tagging](https://docs.datadoghq.com/getting_started/tagging/unified_service_tagging/). This will support various quality of life improvements in datadog, and functionality like [faulty deployment detection](https://docs.datadoghq.com/watchdog/faulty_deployment_detection/).
This relies on https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2807, but can be committed before it is.
- datadog service configuration
> Send version information to datadog

- app/sidekiq/benefits_intake_status_job.rb
This PR begins logging time to transition for our forms as they work their ways through the Benefits Intake API. Ideally, I'll be able to graph average times on DataDog but I'm not 100% sure I'll know how to do that, or if my logging changes here will do what I want (so I'm open to recommendations if anyone has any!!). But hopefully this will be a reasonable first step.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/1197
I opted not to test anything here since it was all only logging to an exterior service, nothing application-critical. I'm happy to be convinced otherwise, though! 😄
> Simple Forms: Log time to transition for forms in BI API

- app/models/form_profile.rb
PCIU is deprecating. Supposedly, users that do not have a vet360_id are still using PCIU. This could have been an oversight during the upgrade from PCIU to VAProfile. Rails info log was added to ensure users are not using PCIU data. 
` if VAProfile::Configuration::SETTINGS.prefill && **user.vet360_id.present?**`
` @vet360_contact_info = VAProfileRedis::ContactInformation.for_user(user)`
`end`
- department-of-veterans-affairs/va.gov-team#76170
> Vet360 Contact Info Logging Added

- config/features.yml
- modules/mobile/app/controllers/mobile/messaging_controller.rb
- modules/mobile/app/models/mobile/v0/user_accessible_services.rb
- modules/mobile/spec/models/user_accessible_services_spec.rb
- modules/mobile/spec/request/attachments_request_spec.rb
- modules/mobile/spec/request/folders_request_spec.rb
- modules/mobile/spec/request/message_drafts_request_spec.rb
- modules/mobile/spec/request/messages_request_spec.rb
- modules/mobile/spec/request/threads_request_spec.rb
- modules/mobile/spec/request/triage_teams_request_spec.rb
- modules/mobile/spec/request/v1/messages_request_spec.rb
Remove the sm policy feature flag because it has been working in prod for long enough to determine its success
https://github.com/department-of-veterans-affairs/va-mobile-app/issues/8328
Removed tests related to the flipper being off
> Remove mobile sm policy feature flag

- modules/ask_va_api/app/controllers/ask_va_api/v0/inquiries_controller.rb
- modules/ask_va_api/app/lib/ask_va_api/inquiries/creator.rb
- modules/ask_va_api/spec/app/lib/ask_va_api/inquiries/creator_spec.rb
- modules/ask_va_api/spec/requests/v0/inquiries_spec.rb
- Updated `Inquiries::Creator`
- creator now make live `put` calls to `CRM API`
- Updated `InquiriesController`
- controller now is in line with update from `Inquiries::Creator`
- https://github.com/department-of-veterans-affairs/ask-va/issues/498
- [xI fixed|updated|added unit tests and integration tests for each feature (if applicable).
> BE | Ask Va Api:  `Inquiry` submit

- app/controllers/v0/terms_of_use_agreements_controller.rb
- app/models/sign_in/terms_code_container.rb
- app/services/sign_in/user_code_map_creator.rb
- spec/controllers/v0/terms_of_use_agreements_controller_spec.rb
- spec/factories/sign_in/terms_code_containers.rb
- spec/models/sign_in/terms_code_container_spec.rb
- spec/services/sign_in/user_code_map_creator_spec.rb
- This PR fixes the Terms of Use authentication flow for Sign in Service. A regression was introduced here when we removed the creation of the User model from the Sign in Service authentication flow itself, in favor of creating the user model after the auth flow was completed.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/81196
Authentication
> 81196 sign in service terms of use user error

- modules/ask_va_api/app/controllers/ask_va_api/v0/inquiries_controller.rb
- modules/ask_va_api/app/lib/ask_va_api/inquiries/creator.rb
- modules/ask_va_api/spec/app/lib/ask_va_api/inquiries/creator_spec.rb
- modules/ask_va_api/spec/requests/v0/inquiries_spec.rb
- Updated `Inquiries::Creator`
- Remove `params` key from `payload`
- Add in missing params in `inquiry_params`
- https://github.com/department-of-veterans-affairs/ask-va/issues/498
> BE | Ask Va Api: Fix `Inquiry Submit` bug

- modules/claims_api/app/swagger/claims_api/v2/dev/swagger.json
- modules/claims_api/app/swagger/claims_api/v2/production/swagger.json
- modules/claims_api/config/schemas/v2/526.json
- Adds max length as specified in the [PDF generator schema](https://blue.qa.lighthouse.va.gov/form-526ez-pdf-generator/v1/openapi.json) to 526 fields that do no currently specify a max length in 526.json.
[API-35334](https://jira.devops.va.gov/browse/API-35334)
- Confirmed locally that max lengths added to schema appear as expected in documentation.
- Confirmed max lengths added are enforced when validating or submitting a 526 submission
526 validation and submission
> Api 35334 526 docs max length

- modules/vaos/app/services/vaos/v2/appointments_service.rb
- modules/vaos/spec/services/v2/appointment_service_spec.rb
- This work is to implement investigative logging into the timezone info returned for the Manila, Philippines facility location
- New test to verify logging functionality, ran regression tests on preexisting functionality
> manila timezone info logging

- app/models/form526_submission.rb
- spec/models/form526_submission_spec.rb
- Two new states are being added to support the 526 state Audit (code yellow).  These are part of a larger project to 'exclude' submissions that have been processed, leaving us with a list of 'untouched' submissions
- The 526 'state machine' is really more of an end-of-life tagging system that was introduced to support our remediation and state auditing following multiple related code yellows.
- I'm part of the Disability & Benefits Experience team 2 (aka team crabs)
- [Ticket with context on the overarching problem, as well as this specific change](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/80624)
- Prior to this change …
> [DBX-80624] add 526 states for remediation audit

- .github/CODEOWNERS
- app/models/form_profile.rb
- app/models/form_profiles/va_107959f1.rb
- config/form_profile_mappings/10-7959F-1.yml
- config/settings.yml
- spec/models/form_profile_spec.rb
Add back-end logic to enable prefill for vets-website. 
- Added 10-7959F-1 for FormProfile
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/80367
- No actual testing. Can't add tests as we are moving from vets-json-schema. WAiting on FE
- Nothing live
> 80367: Add form profile for 10-7959F-1

- modules/claims_api/app/swagger/claims_api/v2/dev/swagger.json
- modules/claims_api/app/swagger/claims_api/v2/production/swagger.json
- modules/claims_api/spec/fixtures/v2/veterans/power_of_attorney/2122/invalid_poa.json
- modules/claims_api/spec/fixtures/v2/veterans/power_of_attorney/2122/valid.json
- modules/claims_api/spec/fixtures/v2/veterans/power_of_attorney/2122a/invalid_poa.json
- modules/claims_api/spec/fixtures/v2/veterans/power_of_attorney/2122a/valid.json
- modules/claims_api/spec/requests/v2/veterans/power_of_attorney_ind_request_spec.rb
- modules/claims_api/spec/requests/v2/veterans/power_of_attorney_org_request_spec.rb
- modules/claims_api/spec/requests/v2/veterans/rswag_power_of_attorney_spec.rb
- Updates documentation examples to use a value of "999999999999" for registrationNumber attribute of 2122 and 2122a submissions, as well as corresponding validate calls.
- Updates tests where appropriate to accommodate value change.
-[API-35595](https://jira.devops.va.gov/browse/API-35595)
- Confirmed locally that documentation examples for affected endpoints reflect the update value for registrationNumber
526 documentation.
> Api 35595 registration numbers

- app/controllers/v0/profile/direct_deposits_controller.rb
- lib/lighthouse/direct_deposit/control_information.rb
- spec/controllers/v0/profile/direct_deposits_controller_spec.rb
- spec/lib/lighthouse/direct_deposit/control_information_spec.rb
- Add temporary logging to controller.
- Refactored `control_information` to use `ActiveModel::Attributes` and `ActiveModel::AttributeAssignment`.  This helped with coercing request parameters.
- Added/updated specs.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/79250
Added/updated specs in:
- direct_deposits_controller_spec
- control_information_spec
> Add direct deposit logs

- db/migrate/20240424132506_remove_ssn_and_icn_from_vye_tables.vye.rb
- db/migrate/20240424132507_remove_address_details_from_vye_user_infos.vye.rb
- db/migrate/20240424132508_change_datetime_to_date.vye.rb
- db/migrate/20240424132509_update_verifications.vye.rb
- db/migrate/20240424132510_create_vye_bdn_clones.vye.rb
- db/migrate/20240424132511_add_to_vye_user_infos.vye.rb
- db/migrate/20240424132512_remove_from_vye_pending_document.vye.rb
- db/schema.rb
- modules/vye/db/migrate/20240303145700_remove_ssn_and_icn_from_vye_tables.rb
- modules/vye/db/migrate/20240305034315_remove_address_details_from_vye_user_infos.rb
- modules/vye/db/migrate/20240415205522_change_datetime_to_date.rb
- modules/vye/db/migrate/20240415220728_update_verifications.rb
- modules/vye/db/migrate/20240422033815_create_vye_bdn_clones.rb
- modules/vye/db/migrate/20240422043836_add_to_vye_user_infos.rb
- modules/vye/db/migrate/20240422051918_remove_from_vye_pending_document.rb
https://jira.devops.va.gov/browse/VYE-338
As:
I need:
To updated the API to reflex and display the updated interface for addresses, and pending enrollment verification.
So that: 
Frontend developers can display on the website
N/A
API show new interface
N/A
N/A
> Wire up the backend API to frontend (Backend)

- .github/workflows/deploy-template.yml
Avoid pulling from all remote manifest branches.
> Avoid pulling from all remote manifest branches

- modules/veteran/app/sidekiq/veteran/vso_reloader.rb
- modules/veteran/spec/sidekiq/veteran/vso_reloader_spec.rb
- This pr fixes a bug with the VSOReloader that prevented organization data from updating
- [81300](https://app.zenhub.com/workspaces/accredited-representation-management-team-64d0dc51d3e8f4788ac6ef96/issues/gh/department-of-veterans-affairs/va.gov-team/81300)
- [github link](https://github.com/department-of-veterans-affairs/va.gov-team/issues/81300)
- Old behavior was that the organization attributes did not update
- tested `Veteran::Service::Organization.import(vso_orgs, on_duplicate_key_update: %i[name phone state])` vs `Veteran::Service::Organization.import(vso_orgs, on_duplicate_key_ignore: true)` in the rails console to confirm old behavior and intended behavior
This will impact the active POA widget and anything that reads organization name, phone, and state
> [81300] Update VSOReloader to correctly upsert organization data

- config/features.yml
- Adds a feature toggle for the auth-only view of the 10-10EZR form.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/79804
- The 10-10EZR form
> #79804 [10-10EZR]: Add auth-only feature flipper

- modules/vye/app/models/vye/user_info.rb
- modules/vye/lib/tasks/vye.rake
- modules/vye/lib/vye/staging_data/build.rb
- modules/vye/spec/factories/vye/address_changes.rb
- modules/vye/spec/lib/vye/staging_data/build_spec.rb
- modules/vye/spec/serializers/verification_serializer_spec.rb
https://jira.devops.va.gov/browse/VYE-370
As:
Backend developer
I need:
To ensure frontend developers can access the staging site with staging users 
So that: 
Frontend developers can ensure VYE is working properly 
Frontend developers need to access staging site, using staging users, to ensure VYE is working properly prior to launch on VA.gov
Enter the acceptance criteria that will be used to test the user story. 
AC 1: Frontend developers can access the staging site using staging users 
AC 2: Frontend developers can make use of staging users
There are no testing considerations
There are no other considerations
> Upload seed data for frontend developers

- app/controllers/v0/sign_in_controller.rb
This PR refactors the client config lookup to memoize using key-value pairs, based on suggestions by @bosawt and @rileyanderson. This approach is preferable to removing memoization entirely, as explored in [this refactor](https://github.com/department-of-veterans-affairs/vets-api/pull/16424).
https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/gh/department-of-veterans-affairs/va.gov-team/81092
Regression test for signing in and logging out.
Not relevant.
Sign-in Service.
None.
> 81092: Refactor Client Config Memoization

- modules/ask_va_api/app/lib/ask_va_api/correspondences/retriever.rb
- modules/ask_va_api/app/lib/ask_va_api/inquiries/retriever.rb
- modules/ask_va_api/spec/app/lib/ask_va_api/correspondences/retriever_spec.rb
- modules/ask_va_api/spec/app/lib/ask_va_api/inquiries/retriever_spec.rb
- modules/ask_va_api/spec/requests/v0/inquiries_spec.rb
- modules/ask_va_api/spec/services/crm/crm_token_spec.rb
- modules/ask_va_api/spec/services/crm/service_spec.rb
- This PR introduce a fix for `Inquiries::Retriever`.
- The class was failing due to `Correspondences::Retriever` erroring.
> BE | Ask Va Api: Update `Correspondences::Retriever` and `Inquiries::Retriever`

- config/features.yml
This feature toggle will toggle on the refactored codepath for `ClaimsApi::LocalBGS` in [this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/16412).
> add `claims_api_local_bgs_refactor` feature toggle

- .github/CODEOWNERS
- app/models/evss_claim_document.rb
- config/locales/en.yml
- spec/fixtures/files/html.txt
- spec/requests/documents_spec.rb
EVSS rejects document uploads where the files extension does not match its contents. An example that we ran into in production was an HTML file that was uploaded with the TXT extension. We don't accept HTML files, so we have hypothesized that the user changed the extension to circumvent that restriction. Also added a new error message indicating that the extension of the file the user is attempting to upload does not match it's contents.
- department-of-veterans-affairs/va.gov-team/issues/81549
Added a new spec to test this use case. The fixture I added contains HTML but has the TXT extension, similar to the production case that caused issues originally
(OPTIONAL)_What should the reviewers …
> [CST] Ensure that EVSS doc upload files have extensions that matches their contents

- Gemfile.lock
- `sidekiq` 7.2.2 has a vulnerability and needed to be upgraded to 7.2.4
- `super_diff` 0.12.0 got yanked and needed to be upgraded to 0.12.1
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/81784
> Updgrade sidekiq and super_diff

- modules/simple_forms_api/app/models/simple_forms_api/vba_21_0966.rb
- modules/simple_forms_api/lib/simple_forms_api.rb
This PR more accurately filters out PII for form 21-0966 error messages.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/81261
> Add words_to_remove for simple forms 21-0966

- modules/mobile/app/controllers/mobile/v0/appointments_controller.rb
Summary
A recent change unintentionally caused a lot of errors on prod due to calling `.any?` on a non-array. This pr ensures we always are calling it on an array
https://github.com/department-of-veterans-affairs/va-mobile-app/issues/8488
None added
> Mobile: Protect against calling `.any?` on a non-array

- modules/vaos/app/schemas/appointments_index.json
Fixes known issues with appointments index contract schema. 
https://github.com/department-of-veterans-affairs/va-mobile-app/issues/8440
(OPTIONAL)_What should the reviewers know …
> 8440: fix appointments contract schema

- modules/ivc_champva/spec/services/pdf_filler_spec.rb
- modules/simple_forms_api/spec/services/pdf_filler_spec.rb
- Flaky specs have been related to destroying and creating PDF files that interfere with each other. This properly gives random names to the specs and deletes them at the appropriate time
> Fixing flaky pdf filler specs related to file names

- config/features.yml
- modules/appeals_api/app/controllers/concerns/appeals_api/pdf_downloads.rb
- modules/appeals_api/app/models/appeals_api/higher_level_review.rb
- modules/appeals_api/app/models/appeals_api/notice_of_disagreement.rb
- modules/appeals_api/app/models/appeals_api/supplemental_claim.rb
- modules/appeals_api/app/services/appeals_api/remove_pii.rb
- modules/appeals_api/spec/services/appeals_api/remove_pii_spec.rb
- Removes the `decision_review_updated_pii_rules` flag, and instead usees the new rules all the time
- These rules have been in use for several weeks, and records in production look like they're being cleared correctly
- This also allows for the removal of the old `pii_expunge_policy` scopes on appeal models
- I'll be making one more PR to remove the `decision_review_*_pii_expunge_enabled` flags so that PII is always expunged, but I skipped it in this PR for two reasons:
1. This may be enough to review on its own, and
2. Once we remove those last flags, it's questionable whether the appeal-specific sidekiq jobs need to exist anymore - their whole functionality was to check those appeal-specific flags and call `RemovePii.run` with the appropriate arguments. IMO we should consolidate them …
> API-34961 Remove Flipper flag for new PII removal rules in appeals APIs

- docker-compose.review.yml
- Switch back RI volume map to srv/vets-api
- This was causing errors with the settings from the devops repo [link](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/roles/review-instance-configure/vars/settings.local.yml)
- This was prevent log in via id.me on RIs
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/82033
> Update ri docker-compose web volumes 

- modules/vaos/app/services/vaos/v2/appointments_service.rb
- modules/vaos/spec/services/v2/appointment_service_spec.rb
The code previously anonymized (masked) ICNs before sending the failure details, both in the response and logs. With this commit, ICNs are no longer anonymized in the response, but are still anonymized in the log entries for the failures. The partial failures are processed using a new method, log_partial_errors. The purpose of these changes is to provide complete failure details in ICNs response while maintaining the ICN anonymization within the logs
https://github.com/department-of-veterans-affairs/va.gov-team/issues/81903
- Modified existing tests and added new tests to check logging.
> VAOS Removed Masking of ICNs in Appointment Response Failure Details

- app/controllers/v0/terms_of_use_agreements_controller.rb
- app/services/terms_of_use/acceptor.rb
- app/services/terms_of_use/decliner.rb
- lib/sidekiq/attr_package.rb
- spec/lib/sidekiq/attr_package_spec.rb
- spec/services/terms_of_use/acceptor_spec.rb
- spec/services/terms_of_use/decliner_spec.rb
- Change `Sidekiq::AttrPackage` key to random value to avoid race conditions where 2 jobs from the same user may be running at the same time
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/81819
- Accept or decline terms for a user - `localhost:3001/terms-of-use`
- Check sidekiq for enqueued job with hex key as argument - http://localhost:3000/sidekiq/queues/default
- Grab the argument and find the package in rails console
```ruby
Sidekiq::AttrPackage.find(<key>)
```
you should get a hash back with user information
- Open rails console - `rails c`
- Create a package and retrieve the key
```ruby
require 'sidekiq/attr_package'
Sidekiq::AttrPackage.create(icn: '123498767V234859', signature_name: 'John Doe', version: '1.0.0')
```
- Find the package with key
```ruby …
```
> Change Sidekiq::AttrPackage key to random value

- config/features.yml
- Summary: removed feature toggle profile_show_proof_of_veteran_status
- Team IIR, we are the new owners of this component
- [Ticket 533](https://github.com/department-of-veterans-affairs/va-iir/issues/533)
- Not inside an epic
- Prior to this change, the component was behind a feature toggle.  Now it is not.
- The feature toggle is no longer available in the Flipper UI.  The component is always available to users with an honorable discharge and at least one period of service..
None
This only impacts [one page](https://va.gov/profile/military-information).
None
> Removed feature toggle profile_show_proof_of_veteran_status

- modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb
- modules/simple_forms_api/app/services/simple_forms_api/pdf_uploader.rb
- modules/simple_forms_api/spec/requests/v1/uploads_spec.rb
- modules/simple_forms_api/spec/services/pdf_uploader_spec.rb
This refactor PR is in anticipation of needing to upload PDFs directly from the front end for the upcoming **Form Upload** functionality. For that functionality we'll want to bypass the PDF filling and stamping and submit directly to the Benefits Intake API.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/1257
New test written and passing.
> Simple Forms: Pull pdf upload out into a service

- modules/vaos/app/exceptions/vaos/exceptions/backend_service_exception.rb
- modules/vaos/app/helpers/vaos/anonymizers.rb
- modules/vaos/app/services/vaos/middleware/response/errors.rb
- modules/vaos/app/services/vaos/middleware/vaos_logging.rb
- modules/vaos/spec/helpers/anonymizers_spec.rb
- modules/vaos/spec/request/v2/appointments_request_spec.rb
- modules/vaos/spec/services/middleware/vaos_errors_spec.rb
- modules/vaos/spec/services/middleware/vaos_logging_spec.rb
The anonymization of URI ICNs during error logging was reverted to test whether it caused appointment cancellation errors in staging. The URI ICN anonymization was not the cause of the errors. This PR re-establishes the anonymization of URL ICNs during error logging.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/82150
- Re-installed the original tests to verify URI URL hashing during error logging.
> VOAS Reinstall URI ICN Anonymization when Logging Errors

- modules/claims_api/app/controllers/claims_api/v2/veterans/disability_compensation_controller.rb
- modules/claims_api/spec/requests/v2/veterans/disability_compensation_request_spec.rb
- Adds fine grained scopes to synchronous endpoint. 
- Adds tests.
- [API-35476](https://jira.devops.va.gov/browse/API-35476)
- Postman
- rspec
*** Don't forget to add `system/526.override` to however you generate your ccg tokens
modified:   modules/claims_api/app/controllers/claims_api/v2/veterans/disability_compensation_controller.rb
modified:   modules/claims_api/spec/requests/v2/veterans/disability_compensation_request_spec.rb
> API-35476-add-restricted-scope

- config/features.yml
Including feature toggle for new expense feature flag 
department-of-veterans-affairs/va.gov-team#68302
- [vets-api PR 29563](https://github.com/department-of-veterans-affairs/vets-website/pull/29563)
Feature flags
> [FSR] 68302 - Adding expense feature flag api

- .github/CODEOWNERS
- app/sidekiq/evss/disability_compensation_form/submit_form526.rb
- lib/lighthouse/benefits_claims/service.rb
- spec/lib/lighthouse/benefits_claims/service_spec.rb
- spec/sidekiq/evss/disability_compensation_form/submit_form526_all_claim_spec.rb
- spec/support/vcr_cassettes/lighthouse/benefits_claims/submit526/200_response.yml
- `disability_compensation_lighthouse_submit_migration`
- do not turn on the above flag. ever.
- #81611
- Return a parsable id from the lighthouse pipeline for the job status controller to consume
- meant to be a placeholder for testing in `staging`. do not turn on in `production`
- enables "e2e" testing from vets-website -> vets-api -> lighthouse -> VBMS
n/a
- preparing for form526 submission migration to lighthouse pipeline
> DBEX/81611: return parsable submitted_claim_id from the form526 submit job in the lighthouse pipeline

- app/sidekiq/central_mail/submit_form4142_job.rb
- Fix a logical bug with file deletion in the legacy 4142 job
- Add logging of the filenumber for visibility
- [Ticket for the original implementation](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/74810)
- [Ticket for this follow up work](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/82100)
- `File.delete(@pdf_path) if @pdf_path.present?` fails when the the `@pdf_path` string is present, but the file has already been deleted (the new Lighthouse implementation handles the deletion of this file).  The new logic checks for …
> [DBX-82100] patch logging and cleanup on 4142 job

- modules/simple_forms_api/app/controllers/simple_forms_api/v1/scanned_form_uploads_controller.rb
- modules/simple_forms_api/config/routes.rb
- modules/simple_forms_api/spec/requests/v1/scanned_form_uploads_spec.rb
This PR adds a new controller to the Simple Forms API: the ScannedFormUploadsController. This controller is meant to handle Form Upload, where the user can directly upload a PDF and this controller will pass it along to the Benefits Intake API.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/1277
Tests have been written for both actions.
> Add ScannedFormUploadsController

- .github/CODEOWNERS
Updating codeowners for the files that the Benefits Decision Reviews team often works with. I didn't remove all instances of `Benefits-Team-1` because some of the files seem to be owned by other teams (e.g. files related to 526, saved claim, etc)
https://github.com/department-of-veterans-affairs/va.gov-team/issues/66191
N/A
> [DR-66191] Update codeowners for decision reviews related files/directories

- app/services/medical_copays/vbs/service.rb
- app/sidekiq/copay_notifications/new_statement_notification_job.rb
- spec/sidekiq/copay_notifications/new_statement_notification_job_spec.rb
We're expecting a new attribute to be included in the body of the POST requests sent to our `/v0/medical_copays/send_statement_notifications` endpoint.
This PR intends to confirm that this attribute is coming through as expected.
[82585](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/82585)
Specs green
Copay notifications. `/v0/medical_copays/send_statement_notifications`
vets-api will log some of the non-PII statement metadata sent to `/v0/medical_copays/send_statement_notifications`
> 82585 Log some non-pii copay statement metadata

- modules/claims_api/lib/claims_api/v2/disability_compensation_pdf_mapper.rb
- modules/claims_api/spec/lib/claims_api/v2/disability_compensation_pdf_mapper_spec.rb
- Don't send contentions if there aren't any
- [API-36152](https://jira.devops.va.gov/browse/API-36152)
- Used to send an `[]` for empty contentions, now doesn't send contentions if there aren't any.
v2 526
> Api 36152 remove empty confinements

- db/migrate/20240502210842_add_device_secret_hash_to_oauth_sessions.rb
- db/schema.rb
- This PR is the schema changes necessary to enable a device secret to be utilized in the Sign in Service authentication flows. This is specifically used for a token exchange functionality
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/82120
- Authentication
> [82120] Adding hashed device secret to oauth sessions for sis token exchange flow

- modules/appeals_api/lib/appeals_api/stats_report.rb
- modules/appeals_api/spec/lib/stats_report_spec.rb
This PR adds a new "Veterans Impacted" section to the monthly Appeals API stats report that captures the unique Veteran ICNs that were associated with the previous month's appeal submissions. Stats are split out by appeal type (Higher Level Reviews, Notice of Disagreements, Supplemental Claims), and there is also a combined number.
My team (Lighthouse Team Banana Peels) owns the `appeals_api` module.
[API-34798](https://jira.devops.va.gov/browse/API-34798)
Unit tests have been added to test the new section of the report. Also generated the stats report locally against my local appeal test data.
This PR impacts the `appeals_api` module only, and specifically the monthly stats (email) report.
No specific feedback requested for this PR.
> API-34798: Add Veteran Impact Stats to Appeals API Stats Report

- app/controllers/v0/sign_in_controller.rb
- app/models/sign_in/client_config.rb
- app/models/sign_in/state_payload.rb
- app/services/sign_in/constants/auth.rb
- app/services/sign_in/errors.rb
- app/services/sign_in/state_payload_jwt_decoder.rb
- app/services/sign_in/state_payload_jwt_encoder.rb
- spec/controllers/v0/sign_in_controller_spec.rb
- spec/factories/sign_in/client_configs.rb
- spec/factories/sign_in/state_payloads.rb
- spec/models/sign_in/client_config_spec.rb
- spec/models/sign_in/state_payload_spec.rb
- spec/services/sign_in/state_payload_jwt_decoder_spec.rb
- spec/services/sign_in/state_payload_jwt_encoder_spec.rb
- This PR adds the `scope=device_sso` field to the Sign in Service `/authorize` endpoint. When calling `/authorize` with this field, the expectation is that the `state` value included in the params to the CSP redirect will include an object with the given `scope`.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/82117
Authentication
> [82117] Add device_sso field to SiS authorize endpoint

- config/features.yml
With the Toxic Exposure questions reaching a maturity of 60+ days in the Health Care Application, it is safe to remove the feature toggle that was activate these questions. This PR removes the reference to the feature flag, along with cleaning up a few extra remnants of the feature reference.
department-of-veterans-affairs/va.gov-team#81972
- Application is free of logic that restricts access to the Toxic Exposure questions
> Remove Health Enrollment TERA feature flag

- spec/services/users/profile_spec.rb
- If you attempt to assume the presence of a `UserVerification` record, several specs in the `profile_spec.rb` file fail. This is not a case that should be possible in actual usage, so we want to update these specs in a way that we can assume the presence of a `user.user_verification`
> Updating specs for user profile so that user verification presence can be assumed

- db/migrate/20240508190041_add_submit_endpoint_to_form526_submissions.rb
- db/schema.rb
Adds a `submit_endpoint` column enum attribute to the `form526_submissions` table to be utilized in determining to which service endpoint a claim should be submitted. Currently, the primary submission of all claims is to EVSS. Those failing primary submission are routed to a different service. With the introduction of a new version of form 526, claims that include a new toxic exposure section will be submitted through Lighthouse. Select Veterans will be provided with the opportunity to claim conditions related to toxic exposure when completing a new version of the form. The value of the `submit_endpoint` will be set when a submission is created and based on a Veteran's claim containing the toxic exposure section. The decision to use an enum attribute should benefit potential future (and …
> DBEX: add submit_endpoint to form526_submissions

- app/models/sign_in/access_token.rb
- app/models/sign_in/code_container.rb
- app/models/sign_in/session_container.rb
- app/models/sign_in/validated_credential.rb
- app/services/sign_in/code_validator.rb
- app/services/sign_in/session_creator.rb
- app/services/sign_in/token_serializer.rb
- app/services/sign_in/user_code_map_creator.rb
- spec/controllers/v0/sign_in_controller_spec.rb
- spec/factories/sign_in/access_tokens.rb
- spec/factories/sign_in/code_containers.rb
- spec/factories/sign_in/session_containers.rb
- spec/factories/sign_in/validated_credentials.rb
- spec/models/sign_in/access_token_spec.rb
- spec/models/sign_in/code_container_spec.rb
- spec/models/sign_in/session_container_spec.rb
- spec/models/sign_in/validated_credential_spec.rb
- spec/services/sign_in/session_creator_spec.rb
- spec/services/sign_in/token_serializer_spec.rb
- spec/services/sign_in/user_code_map_creator_spec.rb
- This PR returns a `device_secret` token when a Sign in Service authentication is performed with a `scope=device_sso` param
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/82120
Authentication
> [82120] Return device_secret when device_sso scope is given for SiS authentication

- modules/vaos/app/services/vaos/v2/appointments_service.rb
- modules/vaos/spec/services/v2/appointment_service_spec.rb
- Appointment cancellations using VPG are current behind `va_online_scheduling_enable_OH_cancellations `and `va_online_scheduling_use_vpg`
PATCH requests to VPG to cancel appointments weren't including the body. The body content was apparently being dropped within Faraday due to a type mismatch.
The solution was to remove the explicit JSON serialization in `appointments_service.rb`. Tests were updated to also match the VCR file using the body to ensure that the valid body content is in the request.
This can be reproduced by attempting to cancel an appointment with feature flags turned on.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/82750
Appointment cancellations
> Update vpg cancellation request body

- config/features.yml
This PR adds a `my_va_enable_new_sip_config` feature flag
**Frontend**
- implementation issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/80036
- implementation PR (wip): https://github.com/department-of-veterans-affairs/vets-website/pull/29641
> My VA - add feature flag for enabling use of new SiP configuration on My VA

- .github/CODEOWNERS
- app/sidekiq/transactional_email_analytics_job.rb
GovDelivery logs a unnecessary messages from the request and response for the CI. Causing hundreds of lines useless log messages. If there is an error the test will fail so there's no need for info logs. 
In order to reduce the log output in CI the request/response messages are suppressed. 
```
I, [2018-05-30T18:18:56.000000 #20]  INFO -- response: Status 200
I, [2018-05-30T18:18:56.000000 #20]  INFO -- response: date: "Wed, 30 May 2018 18:17:56 GMT"
server: "Apache/2.2.15 (CentOS)"
x-frame-options: "SAMEORIGIN"
x-xss-protection: "1; mode=block"
x-content-type-options: "nosniff"
etag: "W/\"6112d22f31b736a3002f590517cb2e81\""
cache-control: "max-age=0, private, must-revalidate"
x-request-id: "82b2f861-4370-4db2-955c-aa0dd56ad102"
x-runtime: "0.026356"
x-served-by: "stg-xactweb3.ep.gdi" …
```
> Suppress Logs from GovDelivery in CI

- app/controllers/v0/benefits_claims_controller.rb
- spec/controllers/v0/benefits_claims_controller_spec.rb
Updating the EVSSClaim records that are already in the DB and correspond to claims that are retrieved via the `#index` or `#show` methods to have their `updated_at` times reflect the time of the latest claim retrieval. This is to prevent 404s that occur whenever the `EVSS::DeleteOldClaims` job runs nightly
- department-of-veterans-affairs/va.gov-team/issues/82790
Added a new spec to ensure that the `updated_at` field gets updated for records that existed before the controller was visited and that are related to claims that are passed to `tap_claims` (used by the #index and #show methods) …
> [CST] Updating EVSSClaim DB records to prevent 404s

- config/features.yml
- Adds mhv_transitional_medical_records_landing_page feature toggle
Closed the following PR since my editor added a newline to the end of `config/features.yml`, thought twice about it, and decided, "I'd rather not."
- https://github.com/department-of-veterans-affairs/vets-api/pull/16640
> Adds mhv_transitional_medical_records_landing_page feature toggle.

- modules/check_in/app/services/travel_claim/client.rb
- *BTSSS API average response time increased between 2 to 2.5 minutes & causing error spike in production; This PR increases the request timeout while calling BTSSS API*
- *https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/79881*
NA
> 79881 Increasing BTSSS API call request timeout

- config/features.yml
- Added feature toggle to be used for appoint a rep frontend. 
- Updated actor type of `representative_status_enabled` toggle
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/73222
> Added feature toggle for appoint a rep

- app/models/form_profiles/va_107959f1.rb
Switches returnUrl from pointing to review-and-submit to the first page of the form per product guidance.
- Team: IVC CHAMPVA
- Flipper: NA
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/81646
*(Describe what parts of the site are …
> Set 10-7959f-1 returnUrl to point to first page of form

- app/sidekiq/terms_of_use/sign_up_service_updater_job.rb
- spec/sidekiq/terms_of_use/sign_up_service_updater_job_spec.rb
- Clean up logging when job fails. 
- log attributes from sidekiq attr_package since it expires 
- move exception message to log payload
- log package key for tracking purposes
- remove job retry limit
- bump `attr_package` expiration to match total possible job retry time (~21 days)
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/82978
- Test the retries_exhausted block functionality:
- In rails console -`rails c`
```ruby
require 'sidekiq/attr_package'
attr_package_key = Sidekiq::AttrPackage.create( icn: 'some-icn', signature_name: 'some-name', version: 'some-version' )
job = { args: [attr_package_key] }.as_json
exception = StandardError.new('some-error')
TermsOfUse::SignUpServiceUpdaterJob.sidekiq_retries_exhausted_block.call(job, exception)
```
You should see a …
> Log SignUpServiceUpdaterJob sidekiq package args

- .github/workflows/deploy-template.yml
Added image tag to the commit message to the manifest repo.  This will make it easier for devs to see if their code was deployed.
> Add image tag to manifest commit message

- app/controllers/v0/terms_of_use_agreements_controller.rb
- app/services/terms_of_use/provisioner.rb
- lib/map/sign_up/service.rb
- spec/controllers/v0/terms_of_use_agreements_controller_spec.rb
- spec/lib/map/sign_up/service_spec.rb
- spec/services/terms_of_use/provisioner_spec.rb
- This PR adds an error case to the Provisioner class for Terms of User Controller that raises an error when the user cannot be provisioned
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/81760
- Terms of Use, Authentication
> [81760] Adding special error case to ToU provisioner response when user cannot be provisioned

- modules/claims_api/lib/claims_api/error/soap_error_handler.rb
- Change a log line that has potential to log PII if an upstream returns it.
- [API-36643](https://jira.devops.va.gov/browse/API-36643)
Mostly claims v1, but some v2 also (just logging, nothing public facing)
> Api 36643 remove fault message

- lib/lighthouse/direct_deposit/client.rb
- lib/lighthouse/service_exception.rb
- modules/mobile/spec/request/payment_information_request_spec.rb
Fixes [this error](https://vagov.ddog-gov.com/apm/error-tracking/issue/a80368e8-f4d2-11ee-ab20-da7ad0900007?query=pod_name%3Avets-api-mobile-%2A&refresh_mode=paused&view=spans&from_ts=1712976884686&to_ts=1713066884686&live=false). I believe the underlying issue is that the lighthouse occasionally experiences timeouts and the lighthouse service exception class isn't really set up to handle timeout requests. `Farady::TimeoutError` has a nil `response`. The exception handler works makes a number of assumptions about how the error is structured that don't work with timeout errors. 
This is not the ideal fix. This is patch in one of the lighthouse clients. The correct approach is to change the lighthouse service exception class to handle all errors in a more robust fashion. I'm reluctant to do …
> 8473 nil response errors

- modules/debts_api/lib/debts_api/v0/fsr_form_transform/asset_calculator.rb
- modules/debts_api/lib/debts_api/v0/fsr_form_transform/utils.rb
- modules/debts_api/spec/lib/debt_api/v0/fsr_form_transform/asset_calculator_spec.rb
This PR is part 2 of an effort to move the FSR transform logic from vets-website to vets-api. 
[81058](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/81058)
Specs added
Eventually it will impact the Financial status Report, currently it effects nothing.
`FsrFormTransform::AssetCalculator.new(...).transform_assets` should generate the `assets` portion of `modules/debts_api/spec/fixtures/pre_submission_fsr/post_transform.json`
> 81058 full transform, assets portion

- config/features.yml
Added `va_online_scheduling_cc_direct_scheduling` feature toggle.
Ticket link: https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/83383
> #83383: Add a new feature flag for CC direct scheduling implementation.

- docs/setup/running_docker.md
- docs/setup/running_natively.md
- spec/spec_helper.rb
The purpose of the PR is to reduce the noise in the CI Run Specs job.   
- By default ignores skipped/pending tests 
- add PENDING environment variable to show skipped/pending tets 
- Allow the CI to skip pending tests
- Pending tests don't prevent PR approval, so they could be skipped to save time. 
- Update documentation to reflect PENDING environment variable changes
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/83150
> Skip Pending Tests 

- modules/claims_api/lib/claims_api/v2/disability_compensation_evss_mapper.rb
- modules/claims_api/spec/lib/claims_api/v2/disability_compensation_evss_mapper_spec.rb
- Adjust EVSS docker mapping logic to accommodate the potential submission of special issues via form submission, in addition to existing handling for PACT special issues.
- Adds tests to exercise mapping logic.
[API-36429](https://jira.devops.va.gov/browse/API-36429)
- Tested locally using Postman to confirm updates do not break existing logic for 526 submissions.
- rspec
Affects EVSS docker container mapping logic for disabilities, specifically handling of special issues.
> Api 36429 special issues form526

- .github/CODEOWNERS
- app/models/accreditation.rb
- app/models/accredited_individual.rb
- app/models/accredited_organization.rb
- spec/factories/accreditations.rb
- spec/factories/accredited_individuals.rb
- spec/factories/accredited_organizations.rb
- spec/models/accreditation_spec.rb
- spec/models/accredited_individual_spec.rb
- spec/models/accredited_organization_spec.rb
- This pr adds a new `Accreditation` model that acts the join between `AccreditedIndividual` and `AccreditedOrganization`
- [78745](https://github.com/department-of-veterans-affairs/va.gov-team/issues/78745)
- Tested creattion with factories in rails console
- Tested destroy with rails console
> [78745] Create accreditation model

- lib/lighthouse/benefits_intake/service.rb
correct options set on PDF Validator
https://github.com/department-of-veterans-affairs/va.gov-team/issues/83487
- invalid options applied to pdf validation
- changed service to correctly send options
- loaded validator in rails console, passing options as in service, viewed validator option attribute
Pension
> Pension 83847 Sidekiq Exhaustion - PDF Size Validation

- modules/claims_api/app/clients/claims_api/bgs_client.rb
- modules/claims_api/app/controllers/claims_api/v2/blueprints/power_of_attorney_request_blueprint.rb
- modules/claims_api/app/controllers/claims_api/v2/power_of_attorney_request/decisions_controller.rb
- modules/claims_api/app/services/claims_api/power_of_attorney_request_service/decide.rb
- modules/claims_api/app/services/claims_api/power_of_attorney_request_service/poa_request.rb
- modules/claims_api/app/services/claims_api/power_of_attorney_request_service/search.rb
- modules/claims_api/app/services/claims_api/power_of_attorney_request_service/search/query.rb
- modules/claims_api/config/routes.rb
- modules/claims_api/spec/requests/v2/power_of_attorney_requests/decline/request_spec.rb
- modules/claims_api/spec/requests/v2/power_of_attorney_requests/index/request_spec.rb
- Redundant composite ID `<participant_id>_<proc_id>` to adapt to BGS API
- `decision` as sub-resource of POA request in response body, mirroring our resourceful routes
> Dash/oren/api 34441/poa request.representation refinements

- modules/ivc_champva/spec/requests/v1/uploads_spec.rb
- stub aws responses for uploads_spec.rb in ivc_champva 
- the aws s3 client was looking for credentials that don't exist and reporting a warning 
- this warning added significant log lines in the Code Check > Run Specs log 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/83563
There's another test causing an additional warning: `Error retrieving instance profile credentials`, that will be addressed in a different PR 
Using `Aws.config.update(stub_responses: true)` in `rspec_helper.rb` caused some failures with a `VCR::Errors::UnusedHTTPInteractionError`
```
Error retrieving instance profile credentials: 
================================================================================
An HTTP request has been made that VCR does not know how to handle:
PUT …
```
> stub AWS responses for ivc_champva uploads_spec

- .github/CODEOWNERS
- app/models/form_profile.rb
- app/models/form_profiles/form_upload_flow.rb
- config/form_profile_mappings/FORM-UPLOAD-FLOW.yml
- config/settings.yml
This PR allows the front end to consume veteran data on the form upload flow from FormProfile.
Associated to https://github.com/department-of-veterans-affairs/vets-website/pull/29878
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/83019
> Add form upload flow to FormProfile list

- app/models/form_profiles/va_526ez.rb
- app/sidekiq/evss/disability_compensation_form/submit_form526.rb
- lib/sidekiq/form526_backup_submission_process/submit.rb
- lib/sidekiq/form526_job_status_tracker/backup_submission.rb
- spec/sidekiq/evss/disability_compensation_form/submit_form526_all_claim_spec.rb
- Follow-on to https://github.com/department-of-veterans-affairs/vets-api/pull/16693
- *This work is behind a feature toggle (flipper): **YES**/~NO~*: `disability_526_toxic_exposure`
- Evaluates Flipper set for current user, assigning boolean value of a `includeToxicExposure` metadata attribute for a newly created in progress form, to be utilized on the frontend in tracking and reporting the inclusion of the toxic exposure section for the form
- A submission whose `submit_endpoint` attribute is set to `'claims_api'` (implemented in [previous PR update](https://github.com/department-of-veterans-affairs/vets-api/pull/16693/files#:~:text=def%20includes_toxic_exposure%3F,end)) is handled similarly to that of a user whose `disability_compensation_lighthouse_submit_migration` Flipper is enabled …
> DBEX: assign toxic exposure submit endpoint & metadata

- lib/data_migrations/form526_submission_submit_endpoint_update.rb
- rakelib/form526_submission_submit_endpoint_update.rake
Modified Rake task to explicitly load module to migrate historic `Form526Submission` data, setting all `submit_endpoint` values to `evss`, corresponding to the service API used for past and current claim submissions. Resolves an error encountered when executing the task in staging environment.
- not directly, but it will be leveraged in conjunction with the `disability_526_toxic_exposure` Flipper
- Modifies https://github.com/department-of-veterans-affairs/vets-api/pull/16693
- Data migration files will be removed following confirmation of deployment to production per [VA Platform guidance](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-database-migrations#vets-apidatabasemigrations-DataMigrations)
- …
> DBEX: explicitly load Form526Submission submit_endpoint data migration module

- modules/debts_api/lib/debts_api/v0/fsr_form_transform/enhanced_expense_calculator.rb
- modules/debts_api/spec/lib/debt_api/v0/fsr_form_transform/asset_calculator_spec.rb
- modules/debts_api/spec/lib/debt_api/v0/fsr_form_transform/expense_calculator_spec.rb
This PR is part 3 of an effort to move the FSR transform logic from vets-website to vets-api.
[81058](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/83577)
Specs added
Eventually it will impact the Financial status Report, currently it effects nothing.
`FsrFormTransform::ExpenseCalculator.build(...).transform_expenses` should generate the `expenses` portion of `modules/debts_api/spec/fixtures/pre_submission_fsr/post_transform.json`
> 81058 backend full transform pt3 expenses

- modules/mobile/spec/request/appointments_vaos_v2_list_request_spec.rb
- modules/vaos/app/services/vaos/v2/appointments_service.rb
- modules/vaos/spec/services/v2/appointment_service_spec.rb
- spec/support/vcr_cassettes/mobile/appointments/VAOS_v2/get_appointment_200_bad_facility_id_vpg.yml
- spec/support/vcr_cassettes/mobile/appointments/VAOS_v2/get_appointment_200_partial_error_vpg.yml
- spec/support/vcr_cassettes/mobile/appointments/VAOS_v2/get_appointment_200_telehealth_onsite_vpg.yml
- spec/support/vcr_cassettes/mobile/appointments/VAOS_v2/get_appointment_200_vpg.yml
- spec/support/vcr_cassettes/mobile/appointments/VAOS_v2/get_appointment_with_ien_200_vpg.yml
- spec/support/vcr_cassettes/mobile/appointments/VAOS_v2/get_appointments_bad_facility_200_vpg.yml
- spec/support/vcr_cassettes/mobile/appointments/VAOS_v2/get_appointments_with_mixed_provider_types_vpg.yml
- spec/support/vcr_cassettes/vaos/v2/appointments/get_appointment_200_CnP_vpg.yml
- spec/support/vcr_cassettes/vaos/v2/appointments/get_appointment_200_booked_cerner_vpg.yml
- spec/support/vcr_cassettes/vaos/v2/appointments/get_appointment_200_non_med_vpg.yml
- spec/support/vcr_cassettes/vaos/v2/appointments/get_appointment_200_with_facility_200_vpg.yml
- spec/support/vcr_cassettes/vaos/v2/appointments/get_appointment_500_vpg.yml
- spec/support/vcr_cassettes/vaos/v2/appointments/get_appointments_200_with_facilities_200_vpg.yml
- Changes are behind `va_online_scheduling_enable_OH_reads` feature flag
- Appointment search requests are now sent to the `vpg` endpoint instead of `vaos`
https://app.zenhub.com/workspaces/appointments-oracle-health-integration-65a6e99ea522640e4d09393b/issues/gh/department-of-veterans-affairs/va.gov-team/83349
These changes impact health appointment creation.
> Appointment search using VPG

- modules/simple_forms_api/app/controllers/simple_forms_api/v1/scanned_form_uploads_controller.rb
This PR adds a missing line so that the metadata validator can work in the scanned form uploads controller.
> Add missing require statement to form upload controller

- db/migrate/20240520191416_drop_accredited_individuals_accredited_organizations.rb
- db/schema.rb
- This is pr drops a join table that is no longer in use. The table should have no data in it and code does not reference it anymore.
- [78745](https://github.com/department-of-veterans-affairs/va.gov-team/issues/78745)
- Not much to test other than the migration succeeding and the test suite passing
No impact as the table was never used. If there was impact, it would be limited to ARM and ARF teams.
> [78745] - Drop unused accredited_individuals_accredited_organizations join table

- config/features.yml
Adds flipper for Search.gov maintenance (outside of their typical maintenance window).
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18206
> VACMS-18206 Add flipper for Search.gov maintenance outages

- app/controllers/concerns/sign_in/authentication.rb
- spec/controllers/sign_in/application_controller_spec.rb
- This PR makes it so the Sign in Service authentication does not send an error to Sentry when the user attempts to authenticate and they send an access token with the string 'undefined'
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/83910
Authentication
> 83910 access token jwt malformed remove error

- config/initializers/active_model_serializers.rb
- spec/controllers/v0/pension_claims_controller_spec.rb
- Unsubscribes from all the `Rendered ActiveModel::Serializer*` logs
- These are pretty useless and just pollute the logs
- `curl localhost:3000/v0/user` and see that the logs are free from `Rendered ActiveModel::Serializer::Null with Hash` 😌 
Logging
> Unsubscribe from ActiveModelSerializers render event

- config/settings/test.yml
- modules/check_in/app/services/travel_claim/client.rb
- modules/check_in/app/services/travel_claim/response.rb
- modules/check_in/app/sidekiq/check_in/travel_claim_submission_worker.rb
- modules/check_in/spec/services/travel_claim/client_spec.rb
- modules/check_in/spec/services/travel_claim/response_spec.rb
- modules/check_in/spec/sidekiq/travel_claim_submission_worker_spec.rb
- *Integrating with new timeout template id for sending SMS when BTSSS api times out*
- *https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/83466*
NA
NA
> 83466 New timeout SMS for BTSSS api timeout

- modules/claims_api/config/schemas/v2/generate_pdf_526.json
- modules/claims_api/spec/requests/v2/veterans/disability_compensation_request_spec.rb
- Adds specialIssues to 526 generate pdf minimum validations schema, so that 526 submissions with specialIssues can be submitted and the resulting pdf doesn't include special issues.
[API-36437](https://jira.devops.va.gov/browse/API-36437)
- Tested locally using Postman, submitting to a 526 form containing special issues to {{uri}}/services/claims/v2/veterans/{{veteran_id}}/526/generatePDF/minimum-validations and confirming the resulting pdf doesn't contain special issues.
- rspec
526 pdf generation with minimum validations.
> Add specialIssues to generate pdf min validations schema

- modules/travel_pay/app/services/travel_pay/client.rb
The BTSSS API was changed to support client-to-server traceability and auditing. It requires a "correlation ID" to all requests made to the API, per request.
Ticket: department-of-veterans-affairs/va.gov-team#83976
> Adds necessary correlation ID to the request(s)

- modules/claims_api/lib/claims_api/v2/disability_compensation_pdf_mapper.rb
- modules/claims_api/spec/lib/claims_api/v2/disability_compensation_pdf_mapper_spec.rb
- Updates mapper to handle nil serviceDates and nil exposureDates (herbicide and additionalExposures)
- Adds tests for scenario
- Adjusts some misplaced tests that were labelled as section 5 (disabilities) but were section 4 (toxic exposure)
- Adjusts mapper so toxicExposures do not default to 'NO' when null is sent in
- [API-36848](https://jira.devops.va.gov/browse/API-36848)
- [API-36866](https://jira.devops.va.gov/browse/API-36866) (not defaulting to 'NO')
- Can also send in a request like below and then check out the PDF.  You should NOT have any errors related to PDF Mapper handling the null values, PDF should get set in S3 and look correct.
* The boxes for YES and NO in `15b` and `15c` should not be checked if `null` is sent in
* You should get a generated PDF even when the dates …
> API-36848 Handle null for Herbicide serviceDates and Additional Exposure exposureDates in Pdf mapper

- modules/claims_api/lib/claims_api/v2/disability_compensation_pdf_mapper.rb
- modules/claims_api/spec/lib/claims_api/v2/disability_compensation_pdf_mapper_spec.rb
* Updates handling in PDF mapper for nil herbicideHazardService and additionalHazardExposure objects
* Adds two RSpec examples one for each object
[API-36848](https://jira.devops.va.gov/browse/API-36848)
* Should be able to send in a request with `nil` `herbicideHazardService` and/or `additionalHazardExposure` and the PDF mapper handles the request with error.  Everything should still be mapped correctly.
Sample request:
```
{
"data":{
"type":"form/526",
"attributes":{
"claimantCertification":true,
"claimProcessType":"STANDARD_CLAIM_PROCESS",
"veteranIdentification":{
"currentVaEmployee":false,
"mailingAddress":{
"addressLine1":"1234 Couch Street",
"city":"Portland",
"country":"USA",
"zipFirstFive":"12345",
"state":"OR"
}
},
"toxicExposure":{
"gulfWarHazardService":{ …
```
> API-36848-fix-for-herbicide-additional-exposures-being-nil

- .github/CODEOWNERS
- app/models/form_profiles/va_10203.rb
- app/models/saved_claim/education_benefits/va_10203.rb
- spec/models/form_profile_spec.rb
- spec/models/saved_claim/education_benefits/va10203_spec.rb
- spec/sidekiq/education_form/process10203_submissions_spec.rb
- spec/support/vcr_cassettes/form_10203/gi_bill_status_200_response.yml
Previous work migrated the GI Bill Status check from a request to EVSS to a request to Lighthouse.  VA form 10203 (Edith Nourse Roberts STEM Scholarship) makes a check to see a veteran's GI Bill Status.  Code in that form was not updated to use the new service and, as a result, continued to send requests to EVSS.  This is undesirable because EVSS is slated for decommissioning in 2024.
This PR updates VA-10203 models to use the previously created `BenefitsEducation::Service`. [Previous PR](https://github.com/department-of-veterans-affairs/vets-api/pull/15642)
This work is not behind a feature toggle.  The new service, `BenefitsEducation::Service` has been active and in-use in production for ~2 months.  We can safely swap out the call to the old service and use the new one.
- [GitHub …
> Update VA Form 10203 models to use BenefitsEducation::Service

- config/features.yml
Create a feature toggle `va_online_scheduling_recent_locations_filter` for displaying the most recent facilities on the Appointments application.
- *Link to ticket created in [va.gov-team repo](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80770) 
n/a
n/a
feature toggle page
expected
> Add new feature flag for the Appointments application

- modules/claims_api/lib/claims_api/v2/disability_compensation_pdf_mapper.rb
- modules/claims_api/spec/lib/claims_api/v2/disability_compensation_pdf_mapper_spec.rb
* Updates the logic so `YES`, `NO` and `null` all mark the boxes, or do not mark the boxes in the case of `null`, as expected
* Cleans out some unused code from gulfWarHazard method in PDF mapper
* Adds RSpec tests
[API-36866](https://jira.devops.va.gov/browse/API-36866)
* Sending in the below request should mark both boxes `YES` on the PDF
```
"toxicExposure":{
"gulfWarHazardService": {
"servedInGulfWarHazardLocations": "YES",
"serviceDates": {
"beginDate": "1972-05",
"endDate": "1980-10"
}
},
"herbicideHazardService": {
"servedInHerbicideHazardLocations": "YES",
"otherLocationsServed": null,
"serviceDates": {}
},
"additionalHazardExposures": null
},
```
* Sending in the below request should mark both boxes 'NO' in the PDF
```
"toxicExposure":{
"gulfWarHazardService": { …
```
> API-36866-fix-response-setting-for-served-in-herbicide

- .github/CODEOWNERS
- app/controllers/v0/backend_statuses_controller.rb
- config/initializers/breakers.rb
- lib/lighthouse/auth/client_credentials/access_token_tracker.rb
- spec/controllers/v1/post911_gi_bill_statuses_controller_spec.rb
- spec/requests/backend_status_request_spec.rb
I am Adam King, I work on the VA-IIR team and we own the GI Bill Status component on `vets-api`.
We have shifted the network call to query GI Bill Status from [EVSS:GiBillStatus::Service](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/evss/gi_bill_status/service.rb) to [BenefitsEducation::Service](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/lighthouse/benefits_education/service.rb).  We need to update the Breakers service to prevent network calls to the upstream (Lighthouse, LTS) service during scheduled downtime.  
This PR adds an entry for the new service in the Breakers configuration, and removes the (now deprecated) EVSS service.  It also updates the backend services controller, which is queried by FE clients who then can …
> Update Breakers to user new GIBS Service

- modules/check_in/app/services/travel_claim/client.rb
- *Reducing the BTSSS api call timeout to 2 minutes for Check-in-experience application*
- *https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/81128*
NA
> 81128 Reducing the timeout to 2 minutes

- config/settings.yml
- lib/periodic_jobs.rb
- modules/ivc_champva/app/jobs/ivc_champva/missing_form_status_job.rb
- modules/ivc_champva/spec/jobs/missing_form_status_job_spec.rb
Add a Sidekiq job that pushes data to DataDog that we can review when missing statuses from PEGA
- Add new Sidekick job `MissingFormStatusJob`
- Update file to add CRON job to run daily art 2am
- Add tests
- Add settings
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/83675
- Rspec 
Given a file successfully sent to s3
When there is not a successfully callback for the file
- Then then the file's ID is sent to DataDog
- and the file ID in the report can be tied to relevant contact information for the applicant
- and the report is created to a location where it can be reviewed (DataDog)
> 83675: Add Sidekiq job to report to DataDog on missing statuses

- config/betamocks/services_config.yml
Quick update to betamocks url that matches changed claims endpoint.
Closes department-of-veterans-affairs/va.gov-team#84113
> updated url to match API updates

- lib/sidekiq/form526_backup_submission_process/submit.rb
- We are simply making an existing error message less alarmist for future generations. This 'failure' is actually just the start of a retry. There are more salient messages and processes in place for capturing real backup failures.
- [ticket](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/84106)
- The class has been instantiated and the method run locally to ensure syntax and logger output
- Form526 Backup path submission
- ~~[ ]  Documentation has been updated (link to documentation)~~ N/A
- ~~[ ]  I added a screenshot of the developed feature~~ N/A
> [DBX-84106] de-intensify 526 backup logging for menial failures

- spec/controllers/v0/post911_gi_bill_statuses_controller_spec.rb
- spec/requests/post911_gi_bill_status_request_spec.rb
- spec/support/schemas/amendment.json
- spec/support/schemas/enrollment.json
- spec/support/schemas/post911_gi_bill_status.json
I'm Adam King, a developer working on the VA-IIR team.  We own this component.  This PR is part of a series of cleanup tickets to remove the old `v0/post_911_gi_bill_status` API endpoint.  We moved to `v1/post_911_gi_bill_status` and are now making a call to Lighthouse in order to retrieve education benefit information (previously EVSS).
Because this removal is a significant chunk of work, I'm breaking it apart into smaller PRs, and also discovering updates that should've been made at the time, like this one: testing that the response returns data in an expected way.  There are some small changes in the data contract - some fields are now nullable, some are also integers where previously they were strings.
There is no production code modified in this PR, only tests.
[GitHub Issue …
> Update request spec to use new GIBS service endpoint

- app/controllers/v0/terms_of_use_agreements_controller.rb
- app/services/terms_of_use/acceptor.rb
- app/services/terms_of_use/decliner.rb
- app/services/terms_of_use/provisioner.rb
- spec/services/terms_of_use/acceptor_spec.rb
- spec/services/terms_of_use/decliner_spec.rb
- spec/services/terms_of_use/provisioner_spec.rb
- This PR prevents Terms of Use Accept/Decline calls from being propagated to the Sign Up Service when a user does not have a sec id. It will instead log that the Sign up Service is not being called and accept the terms for VA.gov, still allowing the user to log in
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/84308
- Authenticated with a normal verified user and confirmed SignUpServiceUpdaterJob was attempted
- Authenticated with a verified user with no sec_id and confirmed SignUpServiceUpdaterJob was not attempted, and log that states the job will not be called was logged
Terms of Use
Authentication
> [84308] Preventing Sign Up Service Terms of Use calls when user does not have a sec id

- modules/covid_vaccine/app/serializers/covid_vaccine/v0/registration_summary_serializer.rb
- modules/covid_vaccine/spec/serializers/covid_vaccines/v0/expanded_registration_serializer_spec.rb
- modules/covid_vaccine/spec/serializers/covid_vaccines/v0/registration_submission_serializer_spec.rb
- modules/covid_vaccine/spec/serializers/covid_vaccines/v0/registration_summary_serializer_spec.rb
- Add more test examples for missing attributes/specs
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/83640
*Note the serializer with 0% coverage is already using jsonapi-serializer
I updated the following serializer because the `object.raw_form_data` keys are strings not symbols
`modules/covid_vaccine/app/serializers/covid_vaccine/v0/registration_summary_serializer.rb`
> Add Unit Tests for Covid Vaccine AMS Serializers

- modules/debts_api/lib/debts_api/v0/fsr_form_transform/personal_identification_calculator.rb
- modules/debts_api/spec/lib/debt_api/v0/fsr_form_transform/personal_identification_calculator_spec.rb
This is part of the larger effort to move the transformation logic for the FSR form from the front end to the back end. This pull request is for part five of this effort addressing many of the miscellaneous transformations, specifically the `personal_identification.` This is only one of the miscellaneous properties to transform and is not enough to close the ticket on its own.
I am on the VA debt team, which owns maintenance of this code. This work is not behind a feature toggle.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/81058
_This has not been added at the time of this pull request._ …
> Full transform on backend, Part 5 [Personal Identification] (81058)

- config/initializers/rack_attack.rb
- spec/middleware/rack/attack_spec.rb
- *(Summarize the changes that have been made to the platform)* Adds rack attack limit configuration for v2 facilities_api controller routes
- *(What is the solution, why is this the solution?)* Some of the excess requests would hopefully have been rejected from recent 403 crisis that overwhelmed Sentry
- Sitewide Facilities
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18237
- Could reach high levels of requests/IP/second
- Run vets-api locally, curl a post to …
> Rack attack limits similar to v1 for v2 facilities_api

- app/controllers/v0/profile/ch33_bank_accounts_controller.rb
- spec/controllers/v0/profile/ch33_bank_accounts_controller_spec.rb
- spec/requests/swagger_spec.rb
EDU direct deposit will be supported by Lighthouse moving forward, so the CH33 controller is being deprecated.
This PR adds a feature flag to disable the controller.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/83731
Added specs for testing the feature flag.
> Deprecate CH33 controller

- modules/claims_api/lib/claims_api/v2/disability_compensation_pdf_mapper.rb
- modules/claims_api/spec/lib/claims_api/v2/disability_compensation_pdf_mapper_spec.rb
- Removes dashes from reserves phone number, and 
- adds a test to the mapper spec
- [API-36890](https://jira.devops.va.gov/browse/API-36890)
- Postman (add a dash tot he reserves phone number
modified:   modules/claims_api/lib/claims_api/v2/disability_compensation_pdf_mapper.rb
modified:   modules/claims_api/spec/lib/claims_api/v2/disability_compensation_pdf_mapper_spec.rb
> API-36890-remove-phone-dash

- modules/ivc_champva/spec/requests/v1/uploads_spec.rb
Just adding one more unit test to the uploads controller. The method for build json unit test was added.
https://github.com/department-of-veterans-affairs/vets-api/pull/16964
> add build json

- .github/CODEOWNERS
- Adds dash to CODEOWNERS for modules/veteran
modified:   .github/CODEOWNERS
> Adds dash to CODEOWNERS for modules/veteran

- .github/CODEOWNERS
- lib/decision_review_v1/utilities/form_4142_processor.rb
- spec/lib/decision_review_v1/processor/form4142_processor_spec.rb
- fix a bug in the 526 backup submission path that was incorrectly setting the 'signed at' date for an ancillary 4142 submission
- [Ticket](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/84377)
- at date set time, `@submission` was nil, incorrectly triggering a failsafe that set 'signed at' dates to the date the processing was ran *INSTEAD* of the date the form submission was created
Form 526 backup submissions with 4142 ancillary documents
- ~~[ ]  Documentation has been updated (link to documentation)~~ N/A
- ~~[ ]  I added a screenshot of the developed feature~~ N/A
> [DBX-83277] patch 526 backup path 4142 sig date

- app/controllers/concerns/sign_in/audience_validator.rb
- app/controllers/v0/sign_in_controller.rb
- app/services/sign_in/client_assertion_validator.rb
- app/services/sign_in/constants/access_token.rb
- app/services/sign_in/constants/auth.rb
- app/services/sign_in/constants/urn.rb
- app/services/sign_in/errors.rb
- app/services/sign_in/session_spawner.rb
- app/services/sign_in/token_exchanger.rb
- app/services/sign_in/token_params_validator.rb
- app/services/sign_in/token_response_generator.rb
- db/seeds/development.rb
- modules/accredited_representative_portal/spec/requests/accredited_representative_portal/application_spec.rb
- spec/controllers/sign_in/audience_validator_spec.rb
- spec/controllers/v0/sign_in_controller_spec.rb
- spec/services/sign_in/client_assertion_validator_spec.rb
- spec/services/sign_in/code_validator_spec.rb
- spec/services/sign_in/session_spawner_spec.rb
- spec/services/sign_in/token_exchanger_spec.rb
- spec/services/sign_in/token_params_validator_spec.rb
- spec/services/sign_in/token_response_generator_spec.rb
- Token exchange for device sso clients
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/82121
- https://github.com/department-of-veterans-affairs/vets-api/pull/16838
- Authenticate with SiS using a client that has api authentication and shared_sessions (`vamobile` will work)
- When you call `/authorize` send `scope=device_sso` param
- Call `/token` normally to get you tokens, you should receive a `device_secret`
- Exchange tokens by calling `/token` with:
```json
{
"grant_type": "urn:ietf:params:oauth:grant-type:token-exchange",
"subject_token": "{access_token}",
"subject_token_type": "urn:ietf:params:oauth:token-type:access_token",
"actor_token": "{device_secret}",
"actor_token_type": "urn:x-oath:params:oauth:token-type:device-secret",
"client_id": "vaweb"
}
```
- …
> Token exchange for device sso clients

- modules/simple_forms_api/app/services/simple_forms_api/confirmation_email.rb
- modules/simple_forms_api/spec/services/confirmation_email_spec.rb
This PR fixes a bug in the Simple Forms API confirmation emailer where an error would be raised if the Flipper was off on a form because an unexpected `nil` was being returned.
> Fix bug where Simple Forms API emailer would fail if Flipper is off

- modules/meb_api/spec/serializers/automation_serializer_spec.rb
- modules/meb_api/spec/serializers/claim_status_serializer_spec.rb
- modules/meb_api/spec/serializers/claimant_serializer_spec.rb
- modules/meb_api/spec/serializers/contact_info_serializer_spec.rb
- modules/meb_api/spec/serializers/eligibility_serializer_spec.rb
- modules/meb_api/spec/serializers/enrollement_serializer_spec.rb
- Add more test examples for missing attributes/specs
- Only for:
- AutomationSerializer, ClaimantSerializer, ClaimStatusSerializer,  EligibilitySerializer, EnrollmentSerializer
- The rest of the serializers will be in a separate PR
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/83642
> Add Unit Tests for MebApi AMS Serializers - Part 1

- app/services/terms_of_use/acceptor.rb
- app/services/terms_of_use/decliner.rb
- app/sidekiq/terms_of_use/sign_up_service_updater_job.rb
- spec/sidekiq/terms_of_use/sign_up_service_updater_job_spec.rb
- Increase AttrPackage expire time
- The current times of retry for 47 hours an package expires in 48 must be too close because the package cant be found when it hits the retry block
- Increase attr_package expire time to 72 hours. This will give us a good buffer and allow us to look up a package if needed.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/84480
- Nothing to really test, I updated unit tests to test retry time and expired time
Terms of use
> Increase SignUpServiceUpdaterJob attr_package expire time

- config/features.yml
Removing the feature toggle for upgrading the webchat. The feature toggle is currently flipped on for all users.
- https://github.com/department-of-veterans-affairs/va-virtual-agent/issues/1267
- https://github.com/department-of-veterans-affairs/vets-website/pull/30151
- vets-website unit testing completed
- Ran vets-website locally and verified behavior
> [#1267] Remove upgraded webchat feature toggle

- config/features.yml
- Added new feature flag `cst_5103_update_enabled` for 5103 changes and removal of Ask for your claim decision
- *Link to ticket created in va.gov-team repo https://github.com/department-of-veterans-affairs/va.gov-team/issues/82537*
- *Link to frontend code change https://github.com/department-of-veterans-affairs/vets-website/pull/30149* 
Claim Status Tool
> [CST] Add feature flag cst_5103_update_enabled for 5103 changes and removal of Ask

- app/services/login/user_verifier.rb
- spec/services/login/user_verifier_spec.rb
- Runs validation on new UserVerification creation, checking for an existing UserVerification with the same CSP type that is locked
- If a locked UserVerification is found the new UserVerification will still be created, but locked as well to prevent successful authentication.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/82599
To test, select the (Login.gov) user you wish to use and locate its corresponding UserAccount. Then delete the existing UserVerification if it exists and create a linked UserVerification that is locked.
```rails
UserCredentialEmail.delete_all
UserVerification.delete_all
UserVerification.new(user_account_id: <account id>, logingov_uuid: SecureRandom.hex, verified_at: Time.now, locked:true).save
```
- During SiS callback the user_verifier …
> [82599] prevents new user verification creation for locked CSPs

- .github/CODEOWNERS
- Gemfile
- Gemfile.lock
- app/controllers/v0/apidocs_controller.rb
- app/controllers/v0/income_and_assets_claims_controller.rb
- app/models/saved_claim/income_and_assets.rb
- app/swagger/swagger/requests/income_and_assets_claims.rb
- config/routes.rb
- spec/factories/income_and_assets_claim.rb
- spec/models/saved_claim/income_and_assets_spec.rb
- spec/requests/income_and_assets_claims_controller_spec.rb
- spec/requests/swagger_spec.rb
Adds boilerplate code for the income and assets (`/v0/form0969`) endpoint. Submissions are successfully posted to the v0/form0969 endpoint, but aren't yet forwarded to VBA. PDF mapping, VBA submission, and logging/metrics are planned in later issues in the epic.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/82554
Income and Assets
> Income and Assets (21P-0969) endpoint boilerplate

- config/features.yml
This PR removes the feature toggle `va_online_scheduling_physical_location` from the features.yml file
- Link to ticket created in va.gov-team [84111](https://github.com/department-of-veterans-affairs/va.gov-team/issues/84111)
n/a
n/a
vaos application
> Remove feature toggle flag for the vaos app

- modules/claims_api/lib/claims_api/v2/disability_compensation_evss_mapper.rb
- modules/claims_api/spec/lib/claims_api/v2/disability_compensation_evss_mapper_spec.rb
* removes `classificationCode` before sending to the Docker container if it is sent in `null`
* Updates tests to check scenario for null value and verifies it gets removed before being sent to the Docker container
[API-36824](https://jira.devops.va.gov/browse/API-36824)
* Submitting a 526 with classificationCode set to `null` for disabilities and secondaryDisabilities should still show the contentions in VBMS when viewing the claim (it previously would not in this scenario)
```
{
"data": {
"type": "form/526",
"claimantCertification": true,
"claimProcessType": "STANDARD_CLAIM_PROCESS",
"veteranIdentification": {
"mailingAddress": {
"addressLine1": "PO Box 501205",
"addressLine2": null,
"addressLine3": null,
"city": "Saipan",
"zipFirstFive": "96950", …
```
> Api 36824 establish claim in vbms correctly

- config/features.yml
Create a feature toggle `appoint_a_representative_enable_pdf` to enable PDF generation of forms `2122` and `2122a`.
-  https://github.com/department-of-veterans-affairs/va.gov-team/issues/84442
n/a
n/a
Feature toggle page
> Add feature flag for Appoint a Rep PDF generation

- config/features.yml
- Removing the deprecated va_online_scheduling_request_flow_update feature toggle
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/64029
- Ensured existing test suite passes.
> Remove va_online_scheduling_request_flow_update feature toggle

- db/migrate/20240605161809_add_case_id_to_ivc_champva_forms.rb
- db/schema.rb
First of a couple of PRs, this one just adds the column to the DB table.
- Generate migration to add `case_id` to IvcChampVaForms table
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/84169
> 84169: Add case_id to IvcChampVAForms table

- modules/travel_pay/app/services/travel_pay/client.rb
- modules/travel_pay/spec/services/client_spec.rb
Fixed assumption about how travel pay claims should be sorted
- department-of-veterans-affairs/va.gov-team#85472
- Previously: Sorted by `modifiedOn`
- Now: Sorts by 'appointmentDateTime`
Travel Pay Status Page only
> Sort by appt date initially

- db/seeds/development.rb
- update development seeds arp logout_redirect_uri to `/representative` from `/representatives`, which reflects the actual app uri
https://github.com/department-of-veterans-affairs/vets-website/pull/30146
> arf.80240 update arp logout_redirect_uri to /representative

- app/models/health_care_application.rb
- spec/requests/health_care_applications_request_spec.rb
- Fixes the preceding implementation to take the current User into account for evaluating whether the Flipper feature flag is enabled, so when we enable it for 25% of logged in users we don't wind up failing to validate API-derived facilities against the stale static JSON.
- *(If bug, how to reproduce)* Enable the feature flag for a % of logged in users, log in, go through the 10-10EZ form, select a Facility not in the static JSON constant, and submit. Produces an error that the (valid) Facility ID is not in the (stale) list.
- *(What is the solution, why is this the solution?)* do the Feature Flag check with the current User, which syncs up the backend validation with the frontend decision of which Facilities UI to show
- *(Which …
> check flag status by user

- modules/mobile/app/controllers/mobile/discovery_controller.rb
- modules/mobile/spec/request/discovery_request_spec.rb
After reviewing which specs are skipping json_api_spec_validation, this was deemed the only actionable change. We expected to skip validation for endpoints that return files, but we currently have several endpoints out of spec that are not returning files.
We cannot change these endpoints without versioning due to json api dictating that 
```
{
data: {}
}
```
must be an object. We have endpoints that are
```
{
data: []
}
```
Changing this would significantly affect front end
https://github.com/department-of-veterans-affairs/va-mobile-app/issues/8530
Existing tests cover these changes
(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the …
> Mobile: Abide to JSON API Spec

- app/sidekiq/evss/disability_compensation_form/submit_form526.rb
- lib/evss/disability_compensation_form/form526_to_lighthouse_transform.rb
- lib/lighthouse/benefits_claims/configuration.rb
- lib/lighthouse/benefits_claims/service.rb
- spec/lib/lighthouse/benefits_claims/service_spec.rb
- spec/sidekiq/evss/disability_compensation_form/submit_form526_all_claim_spec.rb
- spec/support/vcr_cassettes/lighthouse/benefits_claims/submit526/200_synchronous_response.yml
- hooks up SubmitForm526 job to Lighthouse synchronous submit endpoint
- department-of-veterans-affairs/va.gov-team#71773
- as the name and endpoint path suggests, pointing the form526 job to new lighthouse synchronous endpoint
- fixes the "treatmentDate" issue found in department-of-veterans-affairs/va.gov-team#84199
n/a
n/a
> dbex/71773: EVSS Migration - 526 Submit - hook up SubmitForm526 job to Lighthouse synchronous submit endpoint

- .github/workflows/deploy_delay_notifications.yml
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/84577
This pulls the latest status from dev and https://staging-api.va.gov/v0/status and compares the sha to the latest in master. If the time is >30 minutes, it messages the [be-cop notifications channel](https://dsva.slack.com/archives/C039HRTHXDH). It runs every ten minutes.
Originally I had this in Atlas as I thought the logic would be easiest to implement there as there are already models that pull the commits and deploy status but I'd need to figure out how to get a Rails env running in a workflow or create a Sidekiq job. Once I wrote the logic I realized it was very simple to implement in bash.
Example notification [here](https://dsva.slack.com/archives/C039HRTHXDH/p1718122104560309).
> Notify when dev/staging deploys don't succeed

- lib/lighthouse/benefits_education/configuration.rb
- lib/lighthouse/benefits_education/service.rb
I am a member of the VA-IIR team, and we are the owners of this component.
See [slack thread](https://dsva.slack.com/archives/CBU0KDSB1/p1718033925620709)
The `base_path` attribute of the `EducationBenefits::Configuration` object was too generic and it matched the `base_path` of the Forms API.  When the `EducationBenefits` service had a downtime event (this service is flaky, it happens somewhat frequently), the Breakers service blocked access to the Forms API, shutting out thousands of users.
This PR modifies the `base_path` attribute to be the fully qualified URI for the Lighthouse endpoint.  That way, the matcher logic in the Breakers service will not confuse it with any other services.
[GitHub Issue](https://github.com/department-of-veterans-affairs/va-iir/issues/770)
Code is covered …
> update base_path for GIBS service config

- .github/workflows/deploy_delay_notifications.yml
Once an env is out of sync, notifications roll in every 10 mins. 3-4 notifications should be enough. Ideally we just notify when it's triggered and recovered but this is a quick fix so we can stop receiving spam about the dev env.
> fix: Give up notifiying deploy delay after 45 mins

- app/sidekiq/decision_review/submit_upload.rb
This increases the retry count for the SubmitUpload job from 5 to 13, to allow for more time for issues/outages to resolve before a job's retries are exhausted.
No
https://github.com/department-of-veterans-affairs/va.gov-team/issues/84597
Not applicable
Decision Review sidekiq jobs can retry up to 13 times (roughly 17 hours) which can potentially increase the number of jobs in the sidekiq queue
> 84597: Increase retry count for DR evidence upload sidekiq job

- app/models/form526_submission.rb
In the current implementation, an error object lacks sufficient detail. Additional available detail in the response from Lighthouse requires logging. This PR adds the detail description to the error that is returned.
In addition, current `lighthouse_validation_errors` for a `Form526Submission` record with a 422 error response from Lighthouse appear as:
```
[{
"title"=>"Response Status Code '609' - Common::Exceptions::UnprocessableEntity -- /app/lib/lighthouse/service_exception.rb:37:in `send_error'"
}]
```
In the event a call to the Lighthouse service `validate526` returns a 422 error, this update corrects the `form_content_valid?` logic that is responsible for gathering error data that formulates a `lighthouse_validation_response`, to include the correct status code and error …
> [DBEX] add detail to lighthouse validation error response

- config/features.yml
- Removing va_online_scheduling_GA4_migration feature toggle which is now obsolete.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/82973
- Ensure existing test suite passes
> Remove va_online_scheduling_GA4_migration feature toggle

- .github/workflows/deploy_delay_notifications.yml
This allows skipping the repo checkout step which takes 10-15 seconds.
New run speed: https://github.com/department-of-veterans-affairs/vets-api/actions/runs/9471464837/job/26094739260
> fix: Speed up deploy noti check

- app/models/health_care_application.rb
- spec/models/health_care_application_spec.rb
- Updated logic around what `statsD` logs we create when a 10-10 EZ Form submission fails. Previously, we always created a `failed_wont_retry` log for both async and synchronous submission failures. This was confusing since for a synchronous submission failure, it was _never_ going to retry. These changes now log a `failed_wont_retry` when the sidekiq job has run out of retries, and it will log  `sync_submission_failed` for a synchronous form submission that has failed. 
- I also added test coverage around logging _both_ a `failed_wont_retry` and a `failed_wont_retry_short_form` when short forms fail. We want both metrics to be able to more easily aggregate total submissions and total short form submissions. We had the functionality …
> 85478 [10-10 EZ] Add New StatsD logs for async vs sync submission failures

- app/controllers/v0/benefits_claims_controller.rb
- spec/controllers/v0/benefits_claims_controller_spec.rb
- Added the following to claim type logging in `benefits_claims_controller.rb`:
- `attributes.claimPhaseDates.currentPhaseBack`
- `attributes.claimPhaseDates.latestPhaseType`
- `attributes.decisionLetterSent`
- `attributes.developmentLetterSent`
- Updated `benefits_claims_controller_spec.rb`
- [[CST] Expand status logging for claims](https://github.com/department-of-veterans-affairs/va.gov-team/issues/84632)
> [CST] [Backend] Expanded status logging for claims

- app/models/concerns/form526_claim_fast_tracking_concern.rb
- config/features.yml
- spec/models/form526_submission_spec.rb
- spec/support/disability_compensation_form/submissions/only_526_new_disability.json
- This work is behind the feature toggle `disability_526_ep_merge_new_claims`.
- Feature toggle will be removed 30 days after initial launch (ETA late June) -- assuming no unrecoverable errors are seen in the EP Merge API monitor.
- This PR enables 526 submissions with a single NEW contention to be eligible for EP400 Merge.
- I'm on the Employee Experience team, and we work with the Disability Benefits team on this codebase.
- department-of-veterans-affairs/abd-vro#3035
- Old behavior: only 526 claims with a single contention for increase are eligible
- New RSpec added to cover eligibility test for feature toggle on and off
- Testing plan for rollout: Verify eligibility in Staging + VBMS UAT
* No user-facing changes
> Enable single-contention new claims for EP400 Merge

- modules/simple_forms_api/app/models/simple_forms_api/vba_21_4138.rb
- The work adding submission stamp data to form 21-4138, allowed it to be properly stamped upon filling
- [21-4138 Add date / time stamp to upper right hand corner of form](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/1387)
Any
> [SIMPLE_FORMS] fix: 21-4138 - update submission stamps to properly populate pdf

- config/features.yml
Including feature toggle for updated transform. This feature can likely be deprecated 30 days after we swap over to the new endpoint and we have the confidence the new transform and submit endpoint is functioning without an issue
- Link to ticket created in va.gov-team repo
department-of-veterans-affairs/va.gov-team#84473
- Associated `vets-website` PR
department-of-veterans-affairs/vets-website/pull/30334
Manually tested feature flag, and confirmed it appears in:
`http://localhost:3000/flipper/features/fsr_5655_server_side_transform` 
N/A
Feature flag list
(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any …
> [FSR] 84473 - Adding transform feature flag

- modules/claims_api/app/controllers/claims_api/v1/application_controller.rb
- modules/claims_api/spec/requests/v1/power_of_attorney_request_spec.rb
* Creates a check for empty string in headers for birthdate value
* Adds test
[API-37228](https://jira.devops.va.gov/browse/API-37228)
modified:   modules/claims_api/app/controllers/claims_api/v1/application_controller.rb
modified:   modules/claims_api/spec/requests/v1/power_of_attorney_request_spec.rb
> API 37228 fix claim headers for birthdate value

- db/migrate/20240613175759_revert_itf_queue_exhaustions_icn_rename.rb
- db/schema.rb
- This is a partial reversion of a previous migration where we renamed a field on the intent_to_file_queue_exhaustions table. veteran_icn was renamed to user_uuid, but will be reverted back to veteran_icn. This change is necessary because we cannot use a redis store's key (user_uuid) as a reliable source of truth for retrieving user info.
- [*Link to ticket created in va.gov-team repo*](https://github.com/department-of-veterans-affairs/va.gov-team/issues/81536)
- [*Link to previous change of the code*](https://github.com/department-of-veterans-affairs/vets-api/pull/17087)
- [*Link to epic*](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veter …
> Revert renaming veteran_icn to user_uuid

- modules/vaos/app/controllers/vaos/v2/appointments_controller.rb
- modules/vaos/app/services/vaos/v2/appointments_service.rb
- modules/vaos/spec/controllers/v2/appointments_controller_spec.rb
- modules/vaos/spec/services/v2/appointment_service_spec.rb
- As part of the vets-api consolidation work, we want to move the date modification logic from the appointments controller to the appointments service.
- This area is owned and maintained by the Appointments team.
- [ZenHub Ticket](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/zh/327)
- The existing unit tests were moved from the controller to the service
> Move modify_desired_date logic into appointments service

- modules/claims_api/app/swagger/claims_api/v2/dev/swagger.json
- modules/claims_api/config/schemas/v2/poa_request.json
- modules/claims_api/spec/fixtures/v2/veterans/power_of_attorney/request_representative/valid_no_claimant.json
- modules/claims_api/spec/requests/v2/veterans/rswag_power_of_attorney_spec.rb
- modules/claims_api/spec/support/swagger_shared_components/v2.rb
- spec/support/schemas/claims_api/v2/veterans/power_of_attorney/request_representative/submit.json
- This pr adds rwag specs and swagger docs for the POA Request endpoint in lower environments
- [API-34408](https://jira.devops.va.gov/browse/API-34408)
Adds docs to lower environments
> [API-34408] Add swagger docs for poa requests

- config/features.yml
- Adds a toggle for profile privacy policy work
- Also removed a trailing space on one toggle for cleanliness
Timeframe: toggle will be removed within a month of privacy statement being launched in production. Tentative date of removal would be end of August, depending on when final work lands in production. 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/85603
Test locally, just a single toggle being added
No UI changes
Profile
> add toggle for privacy policy

- spec/lib/hca/enrollment_system_spec.rb
- Add specs around the existing TERA logic in the `enrollment_system.rb` as they were not being fully tested. These tests will hopefully allow for future refactors to try to make the `enrollment_system.rb` simpler and easier to understand without introducing any regressions. 
- 1010 Health Apps and it is used by the 1010 EZ and 1010 EZR form
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/85953
- The only code changes are adding tests
1010 EZ and 1010 EZR
> 85953 - 1010 EZ/EZR Add specs around TERA questions in enrollment system

- .github/PULL_REQUEST_TEMPLATE.md
Grafana is deprecated, so we can remove it from the vets-api PR template.
> Remove Grafana from PR template

- bin/dev
- fix syntax issue on on `bin/dev`
- No ticket
> Fix bin/dev Processes Error

- modules/vaos/app/services/vaos/v2/appointments_service.rb
- modules/vaos/spec/services/v2/appointment_service_spec.rb
- spec/support/vcr_cassettes/vaos/v2/appointments/avs-search-error.yml
- This is a quick fix to more gracefully handle responses returned to vets-api from the avs service, checking if the response is a hash before parsing it.
- Tested new logic
- Ran regression tests
> Quick fix avs link safe check

- lib/flipper/views/layout.erb
- Follow-up to  https://github.com/department-of-veterans-affairs/vets-api/pull/17159
During validation, @jennb33 called out the :eye-twitch: misalignment of the navigation. She recommended a negative margin and ✨ that worked!
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/81501
See screenshots
✅ the alignment is consistent even with page re-sizing. 
👎 **Before:**
✨ **After**
Flipper UI
> Align flipper UI nav

- modules/mobile/app/helpers/mobile/appointments_helper.rb
Fixes an issue that was accidentally created in recent work. Only one endpoint uses this code and it is not currently in use. The syntax issue was not found by testing because the method being called is mocked in the specs.
https://github.com/department-of-veterans-affairs/va-mobile-app/issues/8855
None. This endpoint isn't in use. I'm just cleaning up after myself.
> 8855: fix appointments helper syntax error

- .github/workflows/deploy_delay_notifications.yml
Eric built a workflow to notify the backend CoP if a vets-api commit has been merged but dev or staging hasn't deployed within a reasonable time. This PR adds some extra messaging around what to do if this message pops up. This will help Tier 2 support.
- None! I do not know if the formatting will look good or not. 
Current message:
The message in #platform-cop-be-notifications when dev or staging hasn't been deployed after a commit merged. 
What do you think of the spacing? Will the Slack formatting `[text](url)` render properly?? How's the wording?
> Add links to resources in delay notification

- app/services/sign_in/assertion_validator.rb
- spec/controllers/v0/sign_in_controller_spec.rb
- spec/services/sign_in/assertion_validator_spec.rb
- Updates STS assertion validation to cover missing attributes and improve other validations.
- Updated to take a string or array argument, passing an array will result in the first item in the array evaluated as `aud`.
- Updated to return `400` with `Assertion audience is not valid` if attribute is missing.
- Updated to return `400` with `Assertion scopes are not valid` if attribute is missing.
- Will only error if `scopes` param is empty AND the related `ServiceAccountConfig` has populated `scopes` - empty scopes can be passed if the request is tied to a SAC with no saved scopes.
- Updated to return `400` with `Assertion subject is not valid` if attribute is missing.
- Updated to return `400` with `Assertion issuance timestamp is not valid` if attribute is missing or `iat` is set to a …
> [84694] STS validation error handling updates

- app/controllers/v0/intent_to_files_controller.rb
- app/policies/lighthouse_policy.rb
- spec/policies/lighthouse_policy_spec.rb
- spec/requests/intent_to_files_request_spec.rb
We've been seeing a number of 403 errors in our ITF dashboard in Datadog, and they're often due to users lacking an `edipi` or `birls_id` which are required in the current pundit policy used to authorize requests made to the `V0::IntentToFilesController`. I noticed that pundit policy was defined for EVSS, so this PR adds a new policy definition for ITF under the LH policy that checks for participant id, ssn, and name ([Slack thread for reference](https://dsva.slack.com/archives/CE6UEJ6BZ/p1717108841451019?thread_ts=1717100090.559599&cid=CE6UEJ6BZ)) and updates the controller to use that instead of the EVSS policy
https://github.com/department-of-veterans-affairs/va.gov-team/issues/77455
ITF backend (but [errors in ITF API calls no longer block form …
> [DR-77455] Update pundit policy used in ITF controller

- lib/evss/disability_compensation_form/form526_to_lighthouse_transform.rb
- spec/lib/evss/disability_compensation_form/form526_to_lighthouse_transform_spec.rb
This PR populates the `hazard_exposed_to` field with the "specify other hazard" value of the `multipleExposures` array of the Lighthouse request. Previously it had been erroneously populated to `exposure_location`
Disability Benefits Experience Team 1 (DBEX-TREX 🦖 =rawr=)
Toxic Exposure: multipleExposures/exposureDates - Submit …
> Toxic Exposure: populate other hazard description to hazard_exposed_to in multipleExposures array

- config/features.yml
Defaulting `fsr_5655_server_side_transform` to `false` while we work on the endpoint, so FE can merge the following w/o busting up staging
- Using new endpoint PR
department-of-veterans-affairs/vets-website#30400
department-of-veterans-affairs/va.gov-team#84473
- Feature flag implementation:
department-of-veterans-affairs/vets-website#30334
department-of-veterans-affairs/vets-api/pull/17107
Local testing complete. `fsr_5655_server_side_transform` is false by default
N/A
> [FSR] 84473 - Defaulting new feature flag to false instead

- config/features.yml
Three feature flags have been set to `true` by default and there are no longer any in-progress forms that have them set to `false`. This means the flags are safe to remove, and this pull request removes them on the `vets-api` side.
- [Main ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/86012)
- [Initial ticket for the discovery](https://github.com/department-of-veterans-affairs/va.gov-team/issues/81813)
N/A. As long as all the existing tests pass, this is good.
N/A
FSR Forms, specifically in-progress
> [86012] FSR Feature Flag Removal (vets-api)

- lib/lighthouse/benefits_claims/service.rb
- spec/lib/lighthouse/benefits_claims/service_spec.rb
- spec/support/vcr_cassettes/lighthouse/benefits_claims/validate526/200_synchronous_response.yml
Adds tests for the `validate526` method in the Lighthouse `BenefitsClaims::Service` class. The service method is configured to submit the content of a `Form526Submission` to the corresponding Benefits Claims API Disability Compensation Claims `/validate` endpoint, and follows the pattern established by the `submit526` service method. 
A synchronous method, `form_content_valid?`, previously added to the `Form526Submission` model in [16887](https://github.com/department-of-veterans-affairs/vets-api/pull/16887), calls the `validate526` method to confirm if the form content is valid based on the response returned from a submission to the `/validate` endpoint.
- *This work is behind a feature toggle (flipper): ~YES~/**NO*** 
- **Responsible team:** Disability Benefits Experience Team 2 (dBeX …
> [DBEX] add tests & cassette for LH 526 validate endpoint

- config/settings.yml
- modules/va_forms/app/sidekiq/va_forms/form_reloader.rb
- modules/va_forms/spec/sidekiq/form_reloader_spec.rb
This PR adds a new setting, `Settings.va_forms.form_reloader.enabled` that allows us to control whether the `VAForms::FormReloader` job takes any action in a given environment. We will be using this setting to disable the job in the Dev and Sandbox environments.
This PR should not be merged until the corresponding [lower environment settings PR](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2903) and [prod settings PR](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2904) are also merged.
My team (Lighthouse Team Banana Peels) owns the `va_forms` module.
[API-37197](https://jira.devops.va.gov/browse/API-37197)
Tested running the job with the new setting toggled on and off in `config/settings.yml`. Added and …
> API-37197: Add Setting to Toggle `VAForms::FormReloader` Job On/Off Per Environment

- modules/claims_api/app/mailers/claims_api/submission_report_mailer.rb
- modules/claims_api/app/mailers/claims_api/unsuccessful_report_mailer.rb
- modules/claims_api/spec/mailers/report_monthly_submissions_spec.rb
- modules/claims_api/spec/mailers/unsuccessful_report_mailer_spec.rb
_See also: https://github.com/department-of-veterans-affairs/vets-api/pull/17155. Opening a new PR now that I can commit within the repo._
Adds Tyler, a new addition to Team DASH, to email report recipient list and tests.
[API-37195](https://jira.devops.va.gov/browse/API-37195)
Low-risk change. Can verify whether Tyler gets emails or not after merging.
N/A
Benefits Claims API email report recipient list and tests.
N/A
> [API-37195] Add Tyler to Benefits Claims API email reports

- .github/CODEOWNERS
- app/serializers/profile_photo_attachment_serializer.rb
- spec/factories/rated_disabilities.rb
- spec/factories/va_profile/service_histories.rb
- spec/serializers/preferred_name_serializer_spec.rb
- spec/serializers/rated_disabilities_serializer_spec.rb
- spec/serializers/rating_info_serializer_spec.rb
- spec/serializers/saved_claim_serializer_spec.rb
- spec/serializers/search_serializer_spec.rb
- spec/serializers/service_history_serializer_spec.rb
- Removed `ProfilePhotoAttachmentSerializer` 
- I couldn't find where it's used and the controller it was used in previously was deleted
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/83654
> Add Unit Tests for Root AMS Serializers - Part 12

- modules/ask_va_api/app/lib/ask_va_api/announcements/serializer.rb
- modules/ask_va_api/app/lib/ask_va_api/attachments/serializer.rb
- modules/ask_va_api/app/lib/ask_va_api/branch_of_service/serializer.rb
- modules/ask_va_api/app/lib/ask_va_api/categories/serializer.rb
- modules/ask_va_api/app/lib/ask_va_api/correspondences/serializer.rb
- modules/ask_va_api/app/lib/ask_va_api/inquiries/serializer.rb
- modules/ask_va_api/app/lib/ask_va_api/inquiries/status/serializer.rb
- modules/ask_va_api/app/lib/ask_va_api/optionset/serializer.rb
- modules/ask_va_api/app/lib/ask_va_api/profile/serializer.rb
- modules/ask_va_api/app/lib/ask_va_api/states/serializer.rb
- modules/ask_va_api/app/lib/ask_va_api/sub_topics/serializer.rb
- modules/ask_va_api/app/lib/ask_va_api/topics/serializer.rb
- modules/ask_va_api/app/lib/ask_va_api/zipcodes/serializer.rb
- spec/support/serializer_spec_helper.rb
- Replace ActiveModelSerializers (AMS) with JSON:API Serializers in modules/ask_va_api.
- Updated spec/support/serializer_spec_helper.rb to use AMS or JSON:API Serializers
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/84405
> Replace AskVAApi AMS serializers with JSONAPI serializers

- db/migrate/20240621200006_create_form526_submission_remediations.rb
- db/schema.rb
- Create `Form526SubmissionRemediation` model
- Allows for the tracking of remediation efforts, to include context data pertaining to actions taken
- Enables recording multiple remediations for a single submission
- This independent model facilitates providing instances with own state
- Subsequent PRs will implement model validations and methods
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/86438
- [526 State Repair Technical Design Document
](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/untouched_submission_audit/526_state_repair_tdd.md#a-create-a-form52 …
> [DBEX] create Form526SubmissionRemediation model

- modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb
- modules/simple_forms_api/spec/requests/v1/uploads_spec.rb
This PR represents an attempt to avoid `422` errors that are coming back from the Intent to File API. We believe that this before_action here is necessary to properly authorize users. Honestly, I don't entirely understand what calling this method does to the user to make it _not_ raise the error but this Slack thread hopefully sheds more light: https://dsva.slack.com/archives/C02CQP3RFFX/p1717704172086279
> [SIMPLE_FORMS] fix: add before_action to account for 422 errors

- modules/claims_api/app/controllers/claims_api/v1/forms/intent_to_file_controller.rb
- modules/claims_api/app/controllers/claims_api/v1/forms/power_of_attorney_controller.rb
- modules/claims_api/app/controllers/claims_api/v2/veterans/power_of_attorney/base_controller.rb
- modules/claims_api/app/serializers/claims_api/intent_to_file_serializer.rb
- modules/claims_api/app/serializers/claims_api/power_of_attorney_serializer.rb
- modules/claims_api/spec/serializers/intent_to_file_serializer_spec.rb
- modules/claims_api/spec/serializers/power_of_attorney_serializer_spec.rb
This PR is related to https://github.com/department-of-veterans-affairs/vets-api/pull/17210 but should be reviewed first
- Replace ActiveModelSerializers (AMS) with JSON:API Serializers in modules/claims_api.
- `IntentToFileSerializer` and  `PowerOfAttorneySerializer`
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/85753
> Replace ClaimsApi AMS serializers with JSONAPI serializers - Part 2

- .github/workflows/build.yml
Deploy should not be ran until build_and_push finishes to prevent the following error.
> Run deploy workflow after build_and_push

- modules/check_in/app/sidekiq/check_in/travel_claim_base_worker.rb
- modules/check_in/app/sidekiq/check_in/travel_claim_submission_worker.rb
- *Moving send_notification method to base class for using in new sidekiq job to call claim status api*
- *https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/84764*
NA
> 84764 Moving send_notification to travel claim base worker

- modules/vaos/app/services/vaos/v2/appointments_service.rb
- modules/vaos/spec/services/v2/appointment_service_spec.rb
- spec/support/vcr_cassettes/vaos/v2/appointments/get_appointments_200_cc_cancelled.yml
- Quick fix to ensure that provider name info is made available on a cc appt that is cancelled
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/83900
> provider name on cancelled cc appt

- .github/workflows/deploy_delay_notifications.yml
- Follow-up to https://github.com/department-of-veterans-affairs/vets-api/pull/17181. My messages weren't printing! As seen in this recent screenshot:
They were showing up in the [message in the GHA](https://github.com/department-of-veterans-affairs/vets-api/actions/runs/9649791424/job/26614017127), but not printing to Slack. 
- I also added a link to the Build, Push & Deploy actions.
I added this block to run on my branch:
```yaml
on:
push:
branches:
- 'delay_deploy_gha'
```      
And saw the output in the channel. This is what it will look like:
> Add action items to delay deploy workflow (part 2)

- modules/ivc_champva/app/controllers/ivc_champva/v1/uploads_controller.rb
This fixes an issue where all response codes returned form a form submission to IVC module result in either a 200 regardless of whether or not they should, or fail to send back the actual response and thus produce a `204 no content`, which slips through the frontend code check as a false positive (as it's in the 200 range). 
This PR updates the usage of `render` to explicitly include the proper response code, which allows the frontend (platform code) to respond to errors appropriately without needing to be modified.
- Updated usage of `render` in ivc module's `uploads_controller.rb`
Previously, if we got an error on submit, we fell into a catch block that did not explicitly produce an HTTP response object. We just logged to the rails console and returned a 200 later down the line. This …
> update error handling on backend submit to send proper HTTP response codes

- .github/CODEOWNERS
CODEOWNERS has errors. It looks like a team changed their name in GitHub. [github team link](https://github.com/orgs/department-of-veterans-affairs/teams/benefits-accredited-rep-facing-engineers) This team exists: @department-of-veterans-affairs/benefits-accredited-rep-facing-engineers but the @department-of-veterans-affairs/benefits-accredited-rep-facing doesn't
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/75908
This is on my branch:
This is what it looks like in master right now:
> benefits-accredited-rep-facing team name change

- modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb
This is a stopgap measure because we're getting lots of failures on this form. I don't totally understand what's going on with LOA3 vs ICN vs EDIPI etc but I want to send less traffic to the Intent to File API. Hopefully if the user passes the mpi proxy, has an ICN and is LOA3 then there should not be an error at the ITF API.
> Check for LOA3 on 21-0966 to send to ITF API

- app/models/supporting_evidence_attachment.rb
- spec/models/supporting_evidence_attachment_spec.rb
- spec/sidekiq/evss/disability_compensation_form/form526_document_upload_failure_email_spec.rb
In https://github.com/department-of-veterans-affairs/vets-api/commit/dc0971632ad7c542ca4fe66f2e5c7ca30120bdf6, we added a new VA Notify mailer to send to a Veteran when a document they uploaded as evidence to support a Form 526 claim failed when we tried to upload it to EVSS. We needed to obscure a portion of the filename since it could contain PII and the mailer is not the most secure method of communicating with a veteran. Initially this was implemented with asterisks obscuring a portion of the filename.
This PR alters the filename masking  to obfuscate with the letter 'X' instead of an asterisk. It was discovered in testing we cannot obfuscate with special characters such as an asterisk, as these filenames appear in VA Notify Mailers and their templating engine uses markdown. …
> Obfuscate filenames in Form526DocumentUploadFailureEmail with Xs

- .github/CODEOWNERS
- app/models/form526_submission.rb
- app/models/form526_submission_remediation.rb
- spec/models/form526_submission_remediation_spec.rb
- spec/models/form526_submission_spec.rb
- Add `Form526SubmissionRemediation` model with associations and validations
- Add reciprocal association to `Form526Submission` model
- Construct `lifecycle` attribute as an array of hashes with timestamp and context
- Implement `mark_as_unsuccessful` method to update `success` and log context
- Ensure context validation in `add_context_to_lifecycle` method
- Include model validations for `form526_submission_id` and `lifecycle `context
- Subsequent PR will add scopes to `Form526Submission` model
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/86438
- [526 State Repair Technical Design Document …
> [DBEX] create Form526SubmissionRemediation model with lifecycle tracking

- .github/workflows/build.yml
- .github/workflows/deploy.yml
We were mistaken on the workflow run config for the GHA. For the following, on completed will run the build and deploy even if the Code checks fail. We only want these to run if the Code Checks runs are successful. This conditional logic was taken from the [Github docs.
](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#limiting-your-workflow-to-run-based-on-branches)
```  
workflow_run:
workflows: ["Code Checks"]
branches: [master]
types: [completed]
```
> Only trigger build & deploy if code checks pass

- .github/CODEOWNERS
- config/initializers/jsonapi_serializer_blank_id_patch.rb
- modules/covid_vaccine/app/controllers/covid_vaccine/v0/expanded_registration_controller.rb
- modules/covid_vaccine/app/controllers/covid_vaccine/v0/registration_controller.rb
- modules/covid_vaccine/app/serializers/covid_vaccine/v0/expanded_registration_serializer.rb
- modules/covid_vaccine/app/serializers/covid_vaccine/v0/registration_submission_serializer.rb
- modules/covid_vaccine/app/serializers/covid_vaccine/v0/registration_summary_serializer.rb
- modules/covid_vaccine/spec/serializers/covid_vaccines/v0/expanded_registration_serializer_spec.rb
- modules/covid_vaccine/spec/serializers/covid_vaccines/v0/registration_submission_serializer_spec.rb
- modules/covid_vaccine/spec/serializers/covid_vaccines/v0/registration_summary_serializer_spec.rb
- Replace ActiveModelSerializers (AMS) with JSON:API Serializers in modules/covid_vaccine.
- Add `jsonapi_serializer_blank_id_patch.rb`
- the default functionality of jsonapi-serializer doesn't allow for empty strings for id, so I patched FastJsonapi::SerializationCore so it would allow it via `set_id` (e.g. `set_id { '' }`)
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/86384
> Replace COVID Vaccine AMS serializers with JSONAPI serializers

- .github/CODEOWNERS
- config/initializers/jsonapi_serializer_blank_id_patch.rb
- modules/meb_api/app/controllers/meb_api/v0/education_benefits_controller.rb
- modules/meb_api/app/serializers/automation_serializer.rb
- modules/meb_api/app/serializers/claim_status_serializer.rb
- modules/meb_api/app/serializers/claimant_serializer.rb
- modules/meb_api/app/serializers/contact_info_serializer.rb
- modules/meb_api/app/serializers/eligibility_serializer.rb
- modules/meb_api/spec/serializers/automation_serializer_spec.rb
- modules/meb_api/spec/serializers/claim_status_serializer_spec.rb
- modules/meb_api/spec/serializers/claimant_serializer_spec.rb
- modules/meb_api/spec/serializers/contact_info_serializer_spec.rb
- modules/meb_api/spec/serializers/eligibility_serializer_spec.rb
- spec/support/serializer_spec_helper.rb
- Replace ActiveModelSerializers (AMS) with JSON:API Serializers in modules/meb_api.
- `EducationBenefitsController` related serializers 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/85754
> Replace MebApi AMS serializers with JSONAPI serializers - Part 1

- .github/CODEOWNERS
- config/initializers/jsonapi_serializer_blank_id_patch.rb
- modules/meb_api/app/controllers/meb_api/v0/education_benefits_controller.rb
- modules/meb_api/app/controllers/meb_api/v0/forms_controller.rb
- modules/meb_api/app/serializers/enrollment_serializer.rb
- modules/meb_api/app/serializers/exclusion_period_serializer.rb
- modules/meb_api/app/serializers/sponsors_serializer.rb
- modules/meb_api/app/serializers/submission_serializer.rb
- modules/meb_api/app/serializers/submit_enrollment_serializer.rb
- modules/meb_api/app/serializers/toe_claimant_info_serializer.rb
- modules/meb_api/spec/serializers/enrollement_serializer_spec.rb
- modules/meb_api/spec/serializers/exclusion_period_serializer_spec.rb
- modules/meb_api/spec/serializers/sponsors_serializer_spec.rb
- modules/meb_api/spec/serializers/submit_enrollment_serializer_spec.rb
- modules/meb_api/spec/serializers/toe_claimant_info_serializer_spec.rb
- spec/support/serializer_spec_helper.rb
- Replace ActiveModelSerializers (AMS) with JSON:API Serializers in modules/meb_api.
- `FormsController` related serializers 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/85754
> Replace MebApi AMS serializers with JSONAPI serializers - Part 2

- bin/lib/vets-api/setups/base.rb
- bin/lib/vets-api/setups/docker.rb
- bin/lib/vets-api/setups/hybrid.rb
- bin/lib/vets-api/setups/native.rb
- bin/lib/vets-api/setups/rails.rb
- Update the setting changes to keep comments and prevent hyphens from being removed
- n/a
> Fix Settings Updates on bin/setup

- db/migrate/20240625180946_add_backup_submitted_claim_status_to_form526_submission.rb
- db/schema.rb
- Adds `backup_submitted_claim_status` attribute to `Form526Submission`
- This enum will have 3 allowed values – `:accepted`, `:rejected` and `nil` (default)
- A subsequent PR will define the enum within the model
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/86438
- [526 State Repair Technical Design Document
](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/untouched_submission_audit/526_state_repair_tdd.md#b-add-backup_submitted_claim_status-enum-to-the-form526submission-model)
- Nothing to test
Database records will never be created by application code. …
> [DBEX] add backup_submitted_claim_status to Form526Submission

- config/features.yml
- Removing obsolete feature flag
- Part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/55085
- Ensured existing tests pass
> Remove references to va_online_scheduling_status_improvement feature flag

- modules/vaos/app/services/vaos/v2/appointments_service.rb
Saw this message in the rails console: `/app/modules/vaos/app/services/vaos/v2/appointments_service.rb:19: warning: already initialized constant VAOS::V2::AppointmentsService::FACILITY_ERROR_MSG /app/modules/vaos/app/services/vaos/v2/appointments_service.rb:15: warning: previous definition of FACILITY_ERROR_MSG was here`.
2 weeks ago, the FACILITY_ERROR_MSG was added when already defined on line 15.
> Removed extra FACILITY_ERROR_MSG

- modules/appeals_api/config/mailinglists/error_report_daily.yml
- modules/appeals_api/config/mailinglists/error_report_weekly.yml
- modules/appeals_api/config/mailinglists/report_daily.yml
- modules/appeals_api/config/mailinglists/report_weekly.yml
- modules/appeals_api/config/mailinglists/stats_report_monthly.yml
- modules/vba_documents/app/mailers/vba_documents/monthly_report_recipients.yml
- modules/vba_documents/app/mailers/vba_documents/unsuccessful_report_recipients.yml
- This PR updates the recipients lists for the Appeals and Benefits Intake emails reports to add Gia Antoniades and remove Casey Williams. 
- [API-37741](https://jira.devops.va.gov/browse/API-37741)
- Ran a couple of the email generation jobs locally to ensure that the new recipients list was correct.
None
This PR impacts the recipients list for the emails sent in the `vba_documents` and `appeals_api` modules only.
No specific feedback requested.
> API-37741: Add Gia Antoniades to Appeals and Benefits Intake Email Reports

- modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb
- modules/simple_forms_api/spec/requests/v1/uploads_spec.rb
- spec/support/vcr_cassettes/lighthouse/benefits_claims/intent_to_file/422_response.yml
This PR implements a fallback while we continue figuring out why the Intent API is returning `422`s. This will redirect those submissions back to the PDF -> Central Mail route rather than try the Intent API.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/86870
> Implement fallback for when Intent API is down

- app/controllers/v1/sessions_controller.rb
- spec/controllers/v1/sessions_controller_spec.rb
- Followup to https://github.com/department-of-veterans-affairs/vets-api/pull/16979
- Updates the following SSOe auth StatsD entries to use CSP `type` instead of `context`:
- 'api_auth_login_success'
- 'api_auth_login_failure'
- 'api_auth_latency'
- 'api_auth_new_user'
- Rails log `LOGIN_STATUS_FAILURE' is also updated.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/84351
> [84351] updates SSOe login tags to use CSP "type"

- modules/ivc_champva/app/controllers/ivc_champva/v1/pega_controller.rb
- modules/ivc_champva/spec/requests/v1/pega_spec.rb
Update JSON rendering for calls to our endpoint via Pega. Previously it was being lumped into JSON generate and not outputting like a regular status.
- Update JSON renders to actually use their status instead of a defacto 200
- Update test
> Update PegaController JSON render to move status: outside

- modules/ivc_champva/app/controllers/ivc_champva/v1/uploads_controller.rb
- modules/ivc_champva/app/models/ivc_champva/vha_10_10d.rb
- modules/ivc_champva/lib/tasks/forms.rake
- modules/ivc_champva/spec/fixtures/form_json/vha_10_10d.json
- modules/ivc_champva/spec/models/vha_10_10d_spec.rb
Add tags to forms so we can track which applicant type is filling out each form (for 10-10d).
This ticket should split out the signer type ("I’m applying for benefits for myself", "I’m a Veteran applying for benefits for my spouse or dependents", "I’m a representative applying for benefits on behalf of someone else")
- Add `track_user_identity` to model 10-10D (Rest to follow)
- Add new method to forms.rake for new forms
- Update 10-10D Rspec test
- Updated uploads_controller to trigger new method
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/85849
- Have to test DD once on staging
> 85849: Add user tracking for DataDog

- modules/debts_api/lib/debts_api/v0/fsr_form_transform/additional_data_calculator.rb
- modules/debts_api/spec/fixtures/pre_submission_fsr/sw_long/minimal_asset_post_transform.json
- modules/debts_api/spec/lib/debt_api/v0/fsr_form_transform/full_transform_service_spec.rb
Add specs for the FSR full transform and react to them.
[86849](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/86849)
Specs added
It will eventually impact the FSR submission process
The full-transform accurately ports the FE's transform logic
> add specs for streamlined long transform

- lib/map/security_token/service.rb
- spec/lib/map/security_token/service_spec.rb
This PR handles gateway timeouts to the MAP STS service.
https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/gh/department-of-veterans-affairs/va.gov-team/87087
Unit specs.
Not relevant.
Any service that requests MAP STS token.
None.
> 87087 - Handle timeouts for calls to MAP STS

- app/services/sign_in/access_token_jwt_decoder.rb
- app/services/sign_in/service_account_access_token_jwt_decoder.rb
- app/services/sign_in/state_payload_jwt_decoder.rb
- This PR adds the ability for sign in service token decoding, state payload decoding, and service account decoding to utilize a current and deprecated certificate in order to facilitate seamless cert rotation
- https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/zh/397
- Authenticated with Sign in Service, rotated the `Settings.sign_in.jwt_encode_key` cert, confirmed the authentication (and access token) was still valid
Authentication
- Create an access token by authenticating with sign in service
- Update `settings.yml` so that `jwt_encode_key` has a new key, but `jwt_old_encode_key` points to the key that originally created the access token
- Access an authenticated endpoint to confirm the access token is still valid
> [397] Allowing sign in service JWT decoding to use multiple certs when decoding objects

- app/controllers/v1/sessions_controller.rb
- spec/controllers/v1/sessions_controller_spec.rb
- Updates `api_auth_new` StatsD with `type` tag (changed from `context`) to bring in line with previous log & metrics changes.
- https://github.com/department-of-veterans-affairs/vets-api/pull/16979
- https://github.com/department-of-veterans-affairs/vets-api/pull/17278
Perform a new SSOe authentication to see the updated log that has the same tags as the StatsD increment.
```ruby
Rails -- SSO_NEW_KEY, tags: ["type:idme_verified", "version:v1", "client_id:vaweb"]
```
> 84351 api_auth_new StatsD "type" tag update

- modules/representation_management/app/controllers/representation_management/v0/flag_accredited_representatives_controller.rb
- modules/representation_management/app/controllers/representation_management/v0/power_of_attorney_controller.rb
- modules/representation_management/app/serializers/representation_management/flagged_veteran_representative_contact_data_serializer.rb
- modules/representation_management/app/serializers/representation_management/power_of_attorney/base_serializer.rb
- modules/representation_management/app/serializers/representation_management/power_of_attorney/organization_serializer.rb
- modules/representation_management/app/serializers/representation_management/power_of_attorney/representative_serializer.rb
- modules/representation_management/spec/serializers/flagged_veteran_representative_contact_data_serializer_spec.rb
- modules/representation_management/spec/serializers/power_of_attorney/organization_serializer_spec.rb
- modules/representation_management/spec/serializers/power_of_attorney/representative_serializer_spec.rb
- modules/representation_management/spec/serializers/power_of_attorney/shared_base_power_of_attorney.rb
- Replace ActiveModelSerializers (AMS) with JSON:API Serializers in `modules/representation_management`.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/86386
> Replace RepresentationManagement AMS serializers with JSONAPI serializers

- modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb
This PR adds a line of logging whenever the Intent API raises an exception. It will tell us the error itself and the current user's participant_id, which may be `nil`.
> Add logging for 0966 bug

- db/migrate/20240627204058_re_add_index_on_flipper_features.rb
- db/schema.rb
- [PgHero](http://pghero-prod.vfs.va.gov/) listed `index_flipper_features_on_key` as an invalid index and recommended I recreate it. There should be no changes to the schema.
From PgHero:
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/80648
- I ran `rails db:migrate` locally. 
The `flipper_features` table. re-adds the index.
> Fix invalid index `index_flipper_features_on_key`

- db/migrate/20240628161151_re_add_index_on_flipper_gates.rb
- db/schema.rb
- [PgHero](http://pghero-prod.vfs.va.gov/) listed `index_flipper_gates_on_feature_key_and_key_and_value` as an invalid index and recommended I recreate it. There should be no changes to the schema.
From PgHero:
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/80648
- I ran `rails db:migrate` locally. 
The `flipper_gates` table. re-adds the index.
> Fix invalid index `index_flipper_gates_on_feature_key_and_key_and_value`

- .github/CODEOWNERS
-  OCTO-Identity has not maintained TUD for several years and should not be listed as codeowners of TUD code.
> removes octo-identity team from TUD codeowners

- app/services/sign_in/constants/access_token.rb
- app/services/sign_in/user_code_map_creator.rb
- lib/sign_in/logingov/service.rb
- modules/mocked_authentication/spec/lib/credential/service_spec.rb
- spec/factories/sign_in/code_containers.rb
- spec/factories/sign_in/o_auth_sessions.rb
- spec/factories/sign_in/validated_credentials.rb
- spec/lib/sign_in/logingov/service_spec.rb
- spec/services/sign_in/session_refresher_spec.rb
- spec/services/sign_in/session_spawner_spec.rb
- spec/services/sign_in/token_exchanger_spec.rb
- spec/services/sign_in/user_code_map_creator_spec.rb
- spec/support/vcr_cassettes/identity/logingov_200_responses.yml
- Get `all_emails` from logingov user_info.
- Store this attribute in OAuthSessions.user_attributes
- Optionally add to access_token.user_attributes
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/83797
- Sign in with `logingov` using `oauth=true`
- In the rails console find your `OAuthSession.user_attributes`
```ruby
JSON.parse(SignIn::OAuthSession.last.user_attributes)
```
- You should see `all_emails` in `user_attributes`
```ruby
{"email"=>"vets.gov.user+0@gmail.com", "all_emails"=>["vets.gov.user+0@gmail.com"]
```
Sign-in Service, Authentication
> Add Logingov all_email attribute to Sign-in Service

- modules/simple_forms_api/app/models/simple_forms_api/vba_20_10207.rb
This PR will allow the logger to log the `living_situation` and `other_reason` in 20-10207, even if they are `nil`. Currently, we call `.select` on `nil` and that is raising an exception.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/1417
> Log nil if there is no living_situation or other_reason in 20-10207

- modules/avs/app/controllers/avs/v0/avs_controller.rb
- modules/avs/spec/request/v0/avs_request_spec.rb
- During production validation, requests for a new AVS were returning an error for an invalid ID. After validating with the upstream system owner, I learned that the IDs can be of variable length. This PR updates the validation to accept lengths from 30-40 characters.
- https://dsva.slack.com/archives/C04UBETRY8N/p1719591085143669
- AVS module only
> [AVS] update AVS id validation

- db/migrate/20240628173854_drop_index_on_flipper_features.rb
- db/schema.rb
This is a second attempt. First attempt https://github.com/department-of-veterans-affairs/vets-api/pull/17320 resulted in the error when db migrate was run in dev and staging:
```
ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  could not create unique index "index_flipper_features_on_key" (ActiveRecord::RecordNotUnique)
DETAIL:  Key (key)=(drupal_footer) is duplicated.
```
In this PR, we've separated out the commands. 
- [PgHero](http://pghero-prod.vfs.va.gov/) listed `index_flipper_features_on_key` as an invalid index and recommended I recreate it. There should be no changes to the schema.
From PgHero:
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/80648
- I ran `rails db:migrate` locally. 
The …
> DROP INDEX index_flipper_features_on_key

- db/migrate/20240628195735_add_index_on_flipper_features.rb
- db/schema.rb
- Follow-up to #17331 
This is a second attempt. First attempt https://github.com/department-of-veterans-affairs/vets-api/pull/17320 resulted in the error when db migrate was run in dev and staging:
```
ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  could not create unique index "index_flipper_features_on_key" (ActiveRecord::RecordNotUnique)
DETAIL:  Key (key)=(drupal_footer) is duplicated.
```
In this PR, we're only adding in index.  
- [PgHero](http://pghero-prod.vfs.va.gov/) listed `index_flipper_features_on_key` as an invalid index and recommended I recreate it. There should be no changes to the schema.
From PgHero:
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/80648
The `flipper_features` …
> CREATE UNIQUE INDEX flipper_features

- modules/appeals_api/spec/serializers/evidence_submission_serializer_spec.rb
- modules/claims_api/spec/serializers/claim_detail_serializer_spec.rb
- modules/my_health/app/controllers/my_health/v1/all_triage_teams_controller.rb
- modules/my_health/app/controllers/my_health/v1/health_records_controller.rb
- modules/my_health/app/controllers/my_health/v1/messages_controller.rb
- modules/my_health/app/serializers/my_health/v1/all_triage_teams_serializer.rb
- modules/my_health/app/serializers/my_health/v1/category_serializer.rb
- modules/my_health/app/serializers/my_health/v1/eligible_data_classes_serializer.rb
- modules/my_health/spec/serializer/v1/all_triage_teams_serializer_spec.rb
- modules/my_health/spec/serializer/v1/category_serializer_spec.rb
- modules/my_health/spec/serializer/v1/eligible_data_classes_serializer_spec.rb
- spec/support/serializer_spec_helper.rb
- Update serializer options in SerializerSpecHealth
- This required a trivial change to AppealsApi::EvidenceSubmission spec and  ClaimsApi::ClaimDetailSerializer spec
- Replace ActiveModelSerializers (AMS) with JSON:API Serializers in `modules/my_health`.
- `AllTriageTeamsSerializer`, `CategorySerializer`, `EligibleDataClassesSerializer`
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/86385
> Replace MyHealth AMS serializers with JSONAPI serializers - Part 1

- modules/my_health/app/controllers/concerns/my_health/json_api_pagination_links.rb
- modules/my_health/app/controllers/my_health/v1/folders_controller.rb
- modules/my_health/app/controllers/my_health/v1/health_records_controller.rb
- modules/my_health/app/controllers/my_health/v1/triage_teams_controller.rb
- modules/my_health/app/serializers/my_health/v1/extract_status_serializer.rb
- modules/my_health/app/serializers/my_health/v1/folder_serializer.rb
- modules/my_health/app/serializers/my_health/v1/triage_team_serializer.rb
- modules/my_health/spec/request/v1/folders_request_spec.rb
- modules/my_health/spec/serializer/v1/extract_status_serializer_spec.rb
- modules/my_health/spec/serializer/v1/folder_serializer_spec.rb
- modules/my_health/spec/serializer/v1/triage_teams_serializer_spec.rb
**Note**: `modules/my_health/app/controllers/my_health/v1/health_records_controller.rb` has not test coverage via request specs 
**Note**:  It's also unclear based on the specs whether the FoldersController#index call is using `links` or `meta` for pagination. The codeowners should address that in the spec. `links` is require, but pagination in the spec is checked only against `meta`  
- Added `JsonApiPaginationLinks` which is used in creating the "links" object of the response
- Replace ActiveModelSerializers (AMS) with JSON:API Serializers in `modules/my_health`.
- `FoldersController`, `ExtractStatusSerializer`, `TriageTeamSerializer`
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/86385
> Replace MyHealth AMS serializers with JSONAPI serializers - Part 2

- modules/va_forms/app/controllers/va_forms/v0/forms_controller.rb
- modules/va_forms/app/serializers/va_forms/form_detail_serializer.rb
- modules/va_forms/app/serializers/va_forms/form_list_serializer.rb
- Replace ActiveModelSerializers (AMS) with JSON:API Serializers in `modules/va_forms`.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/86388
> Replace VA Forms AMS serializers with JSONAPI serializers

- modules/vba_documents/app/controllers/vba_documents/v1/reports_controller.rb
- modules/vba_documents/app/controllers/vba_documents/v1/uploads_controller.rb
- modules/vba_documents/app/controllers/vba_documents/v2/reports_controller.rb
- modules/vba_documents/app/controllers/vba_documents/v2/uploads_controller.rb
- modules/vba_documents/app/serializers/vba_documents/upload_serializer.rb
- modules/vba_documents/app/serializers/vba_documents/v1/upload_serializer.rb
- modules/vba_documents/app/serializers/vba_documents/v2/upload_serializer.rb
- modules/vba_documents/spec/serializers/shared_upload_serializer.rb
- modules/vba_documents/spec/serializers/v2/upload_serializer_spec.rb
- Replace ActiveModelSerializers (AMS) with JSON:API Serializers in `modules/vba_documents`.
- Refactoring `modules/vba_documents/app/serializers/vba_documents/upload_serializer.rb` to remove the class method block
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/86389
> Replace VBA Documents AMS serializers with JSONAPI serializers

- config/features.yml
- config/settings/test.yml
- lib/decision_review_v1/appeals/supplemental_claim_services.rb
- lib/decision_review_v1/utilities/logging_utils.rb
- spec/requests/v1/supplemental_claims_controller_request_spec.rb
- spec/sidekiq/decision_review/form4142_submit_spec.rb
The current process to upload Form 4142 as part of Supplemental Claim submissions are directly submitted to CMP. With this new feature in place the upload will be done through the Lighthouse Benefits Intake API.
`decision_review_sc_use_lighthouse_api_for_form4142`
https://github.com/department-of-veterans-affairs/va.gov-team/issues/85680
- When the flipper is disabled, Form 4142 submissions for Supplemental Claims are directly submitted to CMP
- When the flipper is enabled, Form 4142 submissions for Supplemental Claims use the Lighthouse Benefits Intake API
- This will be first verified in staging, then the flipper will be enabled in production and monitored for any errors
This impacts Form 4142 submission Sidekiq jobs for …
> 85680: Migrate Supplemental Claims Form 4142 to LH Benefits Intake API

- app/services/terms_of_use/acceptor.rb
- app/services/terms_of_use/decliner.rb
- app/sidekiq/terms_of_use/sign_up_service_updater_job.rb
- spec/services/terms_of_use/acceptor_spec.rb
- spec/services/terms_of_use/decliner_spec.rb
- spec/sidekiq/terms_of_use/sign_up_service_updater_job_spec.rb
- This moves the MPI profile call inside the SignUpServiceUpdaterJob
- Removes use of sidekiq attr package since the args we are passing to sidekiq aren't PII anymore
- https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/zh/369
- Test accepting and declining terms of use
- Confirm TermsOfUseAgreements are being created in rails console
```ruby
TermsOfUseAgreement.last
```
- check that jobs are getting queued in sidekiq:
- Go to http://localhost:3000/sidekiq/queues/default
- You should see `TermsOfUse::SignUpServiceUpdaterJob` being queued up    
Terms of use, authentication
> Move MPI call to SignUpServiceUpdaterJob

- config/features.yml
- modules/claims_api/app/controllers/claims_api/v2/veterans/power_of_attorney/request_controller.rb
- modules/claims_api/spec/requests/v2/veterans/power_of_attorney_new_poa_request_spec.rb
- This pr adds a feature flag to the new poa request controller to skip BGS calls in lower environments
- [API-34409](https://jira.devops.va.gov/browse/API-34409)
- Tested locally in Postman. Manually update the feature flag and compare requests. When `true`, the request should take ~0.5s instead of 20-30s and there should be no activity in the BGS forward proxy terminal.
Impacts POA requests in environments where this flag is set to `true`
> [API-34409] Skip BGS calls in lower environments for POA requests

- modules/vye/app/controllers/vye/v1/user_infos_controller.rb
- modules/vye/app/serializers/vye/address_change_serializer.rb
- modules/vye/app/serializers/vye/pending_document_serializer.rb
- modules/vye/app/serializers/vye/user_info_serializer.rb
- modules/vye/app/serializers/vye/verification_serializer.rb
- Replace ActiveModelSerializers (AMS) with JSON:API Serializers in `modules/vye`.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/87046
> Replace VYE AMS serializers with JSONAPI serializers

- .github/CODEOWNERS
- app/models/form526_submission.rb
- spec/factories/form526_submission_remediations.rb
- spec/factories/form526_submissions.rb
- spec/models/form526_submission_spec.rb
- Adds to `Form526Submission` model (utility described in [526 State Repair Technical Design Document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/untouched_submission_audit/526_state_repair_tdd.md#b-add-backup_submitted_claim_status-enum-to-the-form526submission-model))
- `backup_submitted_claim_status` enum with 3 allowed values: `:accepted`, `:rejected` and `nil` (default)
- instance methods: `remediated?`, `success_type?`, `in_process?`, `failure_type?`, `duplicate?`
- scopes: `success_type`, `in_process`, `failure_type`
- …
> [DBEX] add enum, methods and scopes to Form526Submission

- modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb
- modules/simple_forms_api/spec/requests/v1/uploads_spec.rb
This PR adds a check for `participant_id` before using the Intent to File API. It turns out the `icn` is necessary, too, but insufficient.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/87481
> Check for participant_id for ITF API

- config/features.yml
Adds new flipper for updating the benefit selection page on our team's original claim form.
[Vets-Website Pull Request](https://github.com/department-of-veterans-affairs/vets-website/pull/30644)
Pull Request is just adding the new flag for the frontend enhancement
The feature flag will be used on the my-education-benefits-application on vets-website
> New feature flag for benefit selection page updates

- .github/workflows/audit_service_tags.yml
- .github/workflows/code_checks.yml
- Dockerfile
- docker-compose.test.yml
Use ECR for our Ruby image. We'll need follow-up stories for making sure we're are properly authenticated with AWS, but for now this gets us away from rate limiting on Docker hub.
Sanity check for the images:
```
$ docker pull  public.ecr.aws/docker/library/ruby:3.2-slim-bookworm
3.2-slim-bookworm: Pulling from docker/library/ruby
559a76444520: Already exists 
fe68faa3e9a4: Already exists 
0e01272b679f: Already exists 
2715e4f77bd3: Already exists 
69e9afc1f947: Already exists 
Digest: sha256:de26aa754986a356f0feaeaac37a674a8cb3a5e6617d6a22721b246d41061fb7
Status: Downloaded newer image for public.ecr.aws/docker/library/ruby:3.2-slim-bookworm
public.ecr.aws/docker/library/ruby:3.2-slim-bookworm
$ docker pull  ruby:3.2-slim-bookworm
3.2-slim-bookworm: Pulling from library/ruby
Digest: …
```
> Use ecr for ruby image

- app/controllers/v0/terms_of_use_agreements_controller.rb
- config/routes.rb
- spec/controllers/v0/terms_of_use_agreements_controller_spec.rb
- This PR adds a route to the terms of use agreement controller to allow for an unauthenticated way to see if an ICN has accepted or declined a latest terms of use
- https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/zh/384
Terms of Use
> [384] Adding unauthenticated 'current_status' route for terms of use agreement controller

- .github/CODEOWNERS
- lib/search_typeahead/service.rb
- spec/requests/search_typeahead_request_spec.rb
We are experiencing issues with feature toggles affecting Puma backlog and resulting in 499 errors reported by Traefik. This issue needs a thorough investigation to identify the root cause and implement a solution.
The response errors out and the response body is null when the query is null. When the query is null, the search typeahead should not return an error but an empty string.
- department-of-veterans-affairs/va.gov-team#[87454](https://github.com/department-of-veterans-affairs/va.gov-team/issues/87454)
- [Search Typeahead …
> Render empty string if search query is null when calling SearchTypeahead Service

- app/models/concerns/form526_claim_fast_tracking_concern.rb
- config/settings.yml
- spec/support/vcr_cassettes/virtual_regional_office/multi_contention_classification.yml
- Depends on https://github.com/department-of-veterans-affairs/vets-api/pull/17063
- includes backtrace in logs if ep merge fails
- I experienced similar issue where backtrace info wasn't visible and I think this pattern affects the EE error handling as well (see linked PR)
> Bugfix ee logging failed request

- .rubocop.yml
- lib/map/security_token/configuration.rb
- lib/map/security_token/service.rb
- spec/lib/map/security_token/service_spec.rb
- spec/support/vcr_cassettes/map/security_token_service_200_malformed_response.yml
This PR changes the STS client configuration to send the header for JSON responses. It also modifies the STS client service to remove manual JSON parsing as this is no longer necessary due to the configuration change.
https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/gh/department-of-veterans-affairs/va.gov-team/83081
* Open the mockdata for the token endpoint (`/vets-api-mockdata/map/secure_token_service/token.yml`)
* Modify the response body to return anything that isn't valid JSON.
* Open a rails console.
* Require the STS service.
```ruby
require 'map/security_token/service'
```
* Call the service with a valid application parameter and any value for ICN:
```ruby
MAP::SecurityToken::Service.new.token(application: :sign_up_service, icn: 'bar')
```
* Verify the …
> 83081 - Ensure JSON responses for STS calls

- app/controllers/v0/map_services_controller.rb
- spec/requests/v0/map_services_controller_request_spec.rb
This PR updates the MAP services controller to handle STS timeout errors by sending a bad gateway response.
https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/gh/department-of-veterans-affairs/va.gov-team/87253
- Run the seeds script to add the chatbot service account config.
- Open the Rails console and generate an assertion.
```ruby
private_key = OpenSSL::PKey::RSA.new(
File.read('spec/fixtures/sign_in/sts_client.pem')
)
payload = {
'iss' => 'http://localhost:3978/api/messages',
'sub' => 'vets.gov.user+0@gmail.com',
'aud' => 'http://127.0.0.1:3000/v0/sign_in/token',
'iat' => Time.now.to_i,
'exp' => 10.days.from_now.to_i,
'scopes' => ['http://localhost:3000/v0/map_services/chatbot/token'],
'service_account_id' => '88a6d94a3182fd63279ea5565f26bcb4',
'jti' => …
```
> 87253 - Handle STS timeouts in the MAP services controller

- app/sidekiq/education_form/templates/1990-disclosure/_CH33.erb
- app/sidekiq/education_form/templates/1990-disclosure/_CH33_1606.erb
- app/sidekiq/education_form/templates/1990-disclosure/_CH33_1607.erb
- app/sidekiq/education_form/templates/1990-disclosure/_CH33_30.erb
vfep-1628 - remove 1990 Spool file reqlinquish feature flag
- *This work is behind a feature toggle (flipper): NO (removing feature flag)*
- remove feature flag from 1990 spool file for removing Reliquish language
- remove environment wrapper around the removal of references to Relinquish
- VFEP
- [vfep-1628](https://jira.devops.va.gov/browse/VFEP-1628)
- [vfep-1514](https://jira.devops.va.gov/browse/VFEP-1514)
- [github 17428](https://github.com/department-of-veterans-affairs/vets-api/issues/17428)
- showed relinquish language in 1990 spool file on production
- submit a 1990 form and check the resulting spool file
1990 spool file
> vfep-1628 - remove 1990 Spool file reqlinquish feature flag

- app/controllers/concerns/authentication_and_sso_concerns.rb
This PR removes the environment check that prevents ToU authentication checks in production.
https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/zh/448
The underlying functionality works in lower environments.
Not relevant.
Authentication and ToU.
None.
> Enable ToU authentication check in production

- app/models/form526_submission.rb
- app/sidekiq/evss/disability_compensation_form/submit_form526.rb
- app/sidekiq/form526_status_polling_job.rb
- lib/sidekiq/form526_backup_submission_process/submit.rb
- spec/factories/form526_submissions.rb
- spec/lib/sidekiq/form526_backup_submission_process/submit_spec.rb
- spec/models/form526_submission_spec.rb
- spec/sidekiq/evss/disability_compensation_form/submit_form526_all_claim_spec.rb
- spec/sidekiq/evss/disability_compensation_form/submit_form526_spec.rb
- spec/sidekiq/form526_status_polling_job_spec.rb
- Update Form 526 backup polling
- correctly categorize 'success' responses as 'pending'
- Remove `aasm_state`, value updates and related legacy state machine references
- replaced by `backup_submitted_claim_status` attribute
- Redefine `pending_backup_submissions` scope
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/86438
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/86432
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/86434
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/86441  
- [526 State Repair Technical Design Document …
> [DBEX] refactor response handler & update spec

- app/models/concerns/form526_claim_fast_tracking_concern.rb
- config/features.yml
- spec/models/form526_submission_spec.rb
- This PR adds the feature toggle `disability_526_ep_merge_multi_contention` which enables multi-contention 526 claims to be eligible for EP400 Merge
- I'm on the Employee Experience team; we work with the Disability Benefits team which maintains 526.
- The new feature toggle `disability_526_ep_merge_multi_contention` will be enabled in late July, and removed 30 days after launch assuming no unrecoverable errors are seen in the EP400 Merge dashboard.
- department-of-veterans-affairs/abd-vro#3156
- Old behavior: only single-contention 526 claims are eligible
- New RSpec added to cover eligibility test for feature toggle on and off
- Testing plan for rollout: Verify eligibility in Staging + VBMS UAT
* No user-facing changes
> Expand EP400 Merge eligibility to multi-contention claims

- app/models/form526_submission.rb
- *This work is behind a feature toggle (flipper):NO*
- This change removes a problematic constraint on the new Form526Submission `success_type` scope. When a submission has a `submitted_claim_id`, it is automatically 'success type', and we should not complicated it filtering out submissions that may have also gone to the backup path
- [This document outlines what it means to be success type and why it matters](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/untouched_submission_audit/526_state_repair_tdd.md#key-terms-and-concepts)
- DBeX team 2 / Team Carbs
- [Associated Ticket for backfilling state requires this fix](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52 …
> [DBX-86443] remove backup status check 526 success scope

- config/features.yml
- Removes toggle:  mhv_landing_page_enable_va_gov_health_tools_links
department-of-veterans-affairs/va.gov-team#87133
> Removes toggle:  mhv_landing_page_enable_va_gov_health_tools_links

- modules/ivc_champva/app/services/ivc_champva/file_uploader.rb
- modules/ivc_champva/spec/requests/v1/pega_spec.rb
- modules/ivc_champva/spec/services/attachments_spec.rb
- modules/ivc_champva/spec/services/file_uploader_spec.rb
- modules/ivc_champva/spec/services/pdf_filler_spec.rb
1. When an attachment is uploaded that is not a PDF it's missing when saved in the DB.
2. The file name we send to the S3 bucket is 4171e61a-03b5-49f3-8717-dbf340310473_vha_10_10d1.pdf but saved in the DB like 4171e61a-03b5-49f3-8717-dbf340310473_vha_10_10d-tmp1.pdf. This will certainly cause issues for them when sending the payload.
3. The metadata JSON file is being sent to S3 like vha_10_10d_metadata.json and it needs to include the form_uuid like 4171e61a-03b5-49f3-8717-dbf340310473_vha_10_10d_metadata.json to ensure it's not overwritten.
- Updated meta JSON file to include UUID
- Updated logic to remove tmp to match whats going into S3
- Updates specs
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/87959
> 87959: Minor tweaks to file names

- db/migrate/20240709171552_remove_redundant_indexes.rb
- db/schema.rb
- These are duplicate indexes listed in PgHero. 
This was the message from PgHero:
> **Duplicate Indexes**
These indexes exist, but aren’t needed. Remove themfor faster writes.    
Details
--
On accreditations               
`index_accreditations_on_accredited_individual_id (accredited_individual_id)` is covered by               `index_accreditations_on_indi_and_org_ids (accredited_individual_id, accredited_organization_id)`
On async_transactions
`index_async_transactions_on_transaction_id (transaction_id)` is covered by               `index_async_transactions_on_transaction_id_and_source (transaction_id, source)`
On va_notify_in_progress_reminders_sent            
`index_va_notify_in_progress_reminders_sent_on_user_account_id …
> Remove duplicate indexes

- modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_21_0966.rb
- modules/simple_forms_api/spec/fixtures/form_json/vba_21_0966-prefill.json
- modules/simple_forms_api/spec/requests/v1/uploads_spec.rb
This PR fixes the `id` for 21-0966 so that prefill data can correctly be added to the Intent to File PDF. It also adds a test which, had I written it before, this problem would have been caught yesterday.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/87615
> Fix the form_id and add a test for 21-0966 prefill

- lib/lighthouse/benefits_documents/service.rb
- lib/lighthouse/service_exception.rb
- Fixes broken specs that will be become apparent when bumping to ruby 3.3.3
- checks that `#response` method exists on class before calling it. Not doing so was causing errors, but the way that the specs were capturing errors, the true error was getting ignored
- We'll just re-raise the `CarrierWave::IntegrityError (after logging to Sentry), so that the original error handling/specs work as intended. Mobile Team will address this pattern/how their service is handling various errors in the near future.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/87948
> Check that `respond` method exists in ServiceException

- app/services/sign_in/assertion_validator.rb
- app/services/sign_in/client_assertion_validator.rb
- db/seeds/development.rb
- Currently the assertion validators check for `Settings.hostname`, which is set to `127.0.0.1`, host when validating the JWT payload. All of our examples use `localhost` and I believe this is more commonly used than `127.0.0.1`
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/87954
- Migrate and seed database:
```bash
rails db:migrate
rails db:seed
```
- Start `vets-api` - `rails s`
- Create JWT assertion and make a request in rails console - `rails c`
```ruby
payload = {
sub: 'vets.gov.user+0@gmail.com',
aud: 'http://localhost:3000/v0/sign_in/token',
iat: Time.zone.now.to_i,
exp: Time.zone.now.to_i + 1000,
scopes: [],
service_account_id: 'sample_sts_service_account'
}
key = OpenSSL::PKey::RSA.new(File.read('spec/fixtures/sign_in/sts_cli …
```
> Update SiS assertion validators to validate localhost hostname

- app/models/health_care_application.rb
- spec/models/health_care_application_spec.rb
- Add new statsd value and increment it when a 1010EZ submission failure email is sent
- [*Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses Jira*](https://github.com/department-of-veterans-affairs/va.gov-team/issues/86500)
*10-10EZ
> 10-10EZ - Increment statsd value when submission failure email is sent

- lib/lighthouse/benefits_documents/configuration.rb
- lib/lighthouse/benefits_documents/form526/documents_status_polling_service.rb
- lib/lighthouse/benefits_documents/form526/update_documents_status_service.rb
- lib/lighthouse/benefits_documents/form526/upload_status_updater.rb
- spec/lib/lighthouse/benefits_documents/form526/update_documents_status_service_spec.rb
- spec/lib/lighthouse/benefits_documents/form526/upload_status_updater_spec.rb
**Objective:** Implements a system for periodically polling the Lighthouse [uploads/status](https://dev-developer.va.gov/explore/api/benefits-documents/docs?version=current) endpoint to confirm the status of supplemental documents submitted to Lighthouse as part of a Form 526 Submission. The purpose of this system is to surface successes and failures that happen in the Form 526 process after being forwarded to Lighthouse for processing.
- Create `DocumentsStatusPolling` and `UpdateDocumentsStatus` service classes
- Configure connection and data transmission to Benefits Documents '/uploads/status' endpoint
- Add processing timeout window and failure step logic to `UploadStatusUpdater`
- Subsequent PRs will further implement the interaction with the Lighthouse Benefits Document API client
- …
> [DBEX] create UpdateDocumentsStatus and Polling services

- app/services/claim_fast_tracking/max_rating_annotator.rb
- lib/disability_compensation/providers/rated_disabilities/lighthouse_rated_disabilities_provider.rb
- lib/disability_compensation/responses/rated_disabilities_response.rb
- spec/services/claim_fast_tracking/max_rating_annotator_spec.rb
- spec/support/schemas/rated_disability_base.json
- spec/support/schemas_camelized/rated_disability_base.json
- This PR adds Rails logging of primary and hyphenated diagnostic codes seen in the 526 flow, for visibility in DataDog.
- I'm on the Employee Experience team, and we work closely with the Disability Experience team who maintains 526.
- department-of-veterans-affairs/abd-vro#2865
- Old behavior: no Rails logging of diagnostic codes
- New rspec examples added to cover logging behavior as well as logic for making sense of primary and hyphenated diagnostic codes
- EE team will confirm in DataDog (staging) that diagnostic codes are being logged correctly before adding code to make use of them.
* No user-facing impact
> Log primary and hyphenated diagnostic codes for Max CFI metrics

- app/sidekiq/lighthouse/create_intent_to_file_job.rb
- Added safe nav to all references to the benefits_claims/intent_to_file/monitor.rb class. Also temporarily setting the Lighthouse::CreateIntentToFileJob retries to 0 for testing purposes. We'll be changing that back to the standard 14 once our testing in staging is complete.
- if User info is not present, it will cause the logging and monitoring logic to fail, which would fail to be captured in datadog.
- Adding safe nav will ensure failures are logged and tracked properly in datadog.
- [*Link to ticket created in va.gov-team repo*](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88144)
- [*Link to epic if not included in …
> Add safe nav to user.id calls

- modules/mobile/app/models/mobile/v0/adapters/vaos_v2_appointment.rb
- modules/mobile/spec/models/adapters/appointments_vaos_v2_adapter_spec.rb
Corrects handling of friendly name for cc appointment requests to better match web. 
https://github.com/department-of-veterans-affairs/va-mobile-app/issues/8861
Will test on staging.
> 8861: cc appointment request friendly location name

- modules/simple_forms_api/app/models/simple_forms_api/vba_20_10207.rb
This PR adds a flag to allow optional content in PDFs. Apparently PDFs can be encoded with optional content, which means that the content shows up conditionally (like a CSS media query). By default this causes an error to be thrown in the `combine_pdf` gem. With this `:allow_optional_content` flag, however, it will just display all content regardless when it attaches the documentation to our 20-10207 form (see screenshots).
More info here: https://github.com/boazsegev/combine_pdf/issues/28
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/88181
The left shows the original PDF with the optional content hidden and the right shows what we'd send to the BI API. It seems preferable to just include all …
> Allow optional content for 20-10207 to prevent error raising

- modules/debts_api/lib/debts_api/v0/fsr_form_transform/income_calculator.rb
We found out that `nil` values were slipping through for "total monthly net income" property for the transform. This adds fallback `0.00` values for the instances of it.
- …
> 87408: Add fallback for debt total monthly net income

- lib/va1010_forms/utils.rb
- spec/lib/form1010_ezr/service_spec.rb
- spec/lib/hca/service_spec.rb
- Adds a logger that returns the size of each attachment in the request payload
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/88075
10-10EZ and 10-10EZR forms
> #88075 [10-10EZ] [10-10EZR]: Add logger for individual attachment sizes

- app/models/form526_submission.rb
- spec/factories/form526_submissions.rb
- spec/models/form526_submission_spec.rb
- Refine existing 526 scopes for correctness
- Refine existing 526 scopes for readability
These scopes are part of our greater push to close out Code Yellow 3 by ensuring we have accurate, easily accessible ways to view Form 526 submissions that may require remediation.
Team: DBeX team carbs
- [TDD outlining the purpose of these scopes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/untouched_submission_audit/526_state_repair_tdd.md)
- [Ticket capturing this work](https://github.com/department-of-veterans-affairs/va.gov-team/issues/87964)
- Previously these scopes incorrectly excluded submissions from success states
- All of these scopes have been manually …
> [Dbx-87964] refine 526 scopes

- modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb
- modules/simple_forms_api/spec/requests/v1/uploads_spec.rb
This PR does two things:
1. Check the `participant_id` before getting ITFs from the Benefits Claims API. This should reduce errors.
2. Remove unnecessary line in testing where we supply an `icn`. By logging in in the spec, it's already provided.
> Check pid before getting ITFs (Simple Forms)

- modules/claims_api/lib/bd/bd.rb
- modules/claims_api/spec/lib/claims_api/bd_spec.rb
In Benefits Documents, if the upstream service is down, raise a `GatewayTimeout` exception and log the error. This change handles the case in which the upstream service responds with a non-JSON (i.e., non-hash) object (and we assume the service is down). We do not change any client-facing functionality.
[API-37793](https://jira.devops.va.gov/browse/API-37793)
N/A
Benefits Documents API
Do we want to log the error result from the upstream service?
> [API-37793] Raise a `GatewayTimeout` exception when needed

- modules/claims_api/app/controllers/concerns/claims_api/v2/disability_compensation_validation.rb
- modules/claims_api/spec/requests/v2/veterans/disability_compensation_request_spec.rb
Assume the best if there is any ambiguity when comparing treatment begin date with the first service period begin date. i.e., if the first service begin date is `YYYY-MM-DD`, allow any treatments that begin in `YYYY` or `YYYY-MM`.
Continue to disallow treatment begin dates where there is no ambiguity, i.e., service begin date is `YYYY-MM-DD` and treatment begin date is `YYYY-MM` minus one month.
[API-38039](https://jira.devops.va.gov/browse/API-38039)
N/A
Claims API > Disability Compensation
Could use help testing against live environments while [awaiting AWS access](https://github.com/department-of-veterans-affairs/va.gov-team/issues/87113).
> [API-38039] Relax treatment begin date validation

- app/models/in_progress_form.rb
This PR is a prerequisite for https://github.com/department-of-veterans-affairs/vets-api/pull/17511. Tests on the other PR won't pass until this PR is in.
The purpose of this PR is to ultimately remove the association between `InProgressForm`s and `FormSubmission`s. We never used these, never saved any `FormSubmission`s with associations to `InProgressForm`s and are trying to tighten up the `FormSubmission` model so that it's less misleading about what associations/fields one can expect on it.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/88145
> Remove has_many :form_submissions from InProgressForm

- app/controllers/v0/decision_review_evidences_controller.rb
- config/features.yml
- spec/controllers/v0/decision_review_evidences_controller_spec.rb
This PR is to remove storage of evidence attachment data due to the completion of validating the attachment decryption process.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/87405
Unprocessed (encrypted) versions of the evidence attachments will no longer be stored. Hexapdf will always be used for decrypting PDFs in the DR evidence flow.
This impacts the Decision Review evidence attachment processing
> 87405: Clean up storage of evidence attachments + records used for validation

- app/controllers/concerns/failed_request_loggable.rb
- app/controllers/v1/supplemental_claims_controller.rb
- spec/requests/v1/supplemental_claims_controller_request_spec.rb
We have been seeing a few `stack level too deep` errors that are causing inconsistent issues with form submissions for Supplemental Claims (with a seemingly one-off case for HLR) — this adds some rescuing and logging to see if we can get better visibility into what kind of request/response could be causing the recursive loop. If needed we can add to our other forms, but the majority of errors are from SC
https://github.com/department-of-veterans-affairs/va.gov-team/issues/73584
Decision Reviews backend
> [DR-73584] Add rescue and logging to personal information log create in Supplemental Claims

- .github/workflows/audit_service_tags.yml
- .github/workflows/build-and-publish.yaml
- .github/workflows/build.yml
- .github/workflows/code_checks.yml
- bump docker/build-push-action to v6
- set DOCKER_BUILD_SUMMARY to false
- Seemed to be interfering with a job
- https://github.com/department-of-veterans-affairs/vets-api/pull/17137
> bump docker/build-push-action@v6 and set DOCKER_BUILD_SUMMARY to false

- modules/vaos/app/services/vaos/v2/appointments_reason_code_service.rb
- modules/vaos/spec/services/v2/appointments_reason_code_service_spec.rb
- This is part of the api consolidation effort and moves the logic for extracting additional appointment details (AKA comments) information from the reason code text from the FE to BE. The source logic is [here](https://github.com/department-of-veterans-affairs/vets-website/blob/0bdd33547c4e4eea0c989976a23ce93b42b0c1c6/src/applications/vaos/services/appointment/transformers.js#L240-L245)
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/86917
- The old behavior returns the information as part of the reason code text and additionalAppointmentDetails field is non existent.
N/A
N/A
> Generate additionalAppointmentDetails from appointment request reasoncode.text

- modules/ivc_champva/app/models/ivc_champva/vha_10_7959f_1.rb
- modules/ivc_champva/spec/models/vha_10_7959f_1_spec.rb
Prefix UUID to 10-7959F-1 submissions to avoid overwriting in S3
- The UUId prefix was missing from this form. That means it would be overwritten when any other forms were submitted.
- Updated test
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/88384
> 88384: Fix missing uuid in front of 10-7959F-1 submissions

- config/environments/production.rb
From Rails' docs:
```
config.cache_store = :mem_cache_store, "cache.example.com", { pool: { size: 32, timeout: 1 } }
```
https://edgeguides.rubyonrails.org/caching_with_rails.html#connection-pool-options
> fix: redis pool needs size

- .github/CODEOWNERS
- rakelib/prod/user_credential.rake
- spec/rakelib/user_credential_spec.rb
- Updates `user_credential` Rake task to include `lock_all` and `unlock_all` tasks; these tasks use an ICN to look up the corresponding `UserAccount`, using it to lock or unlock all of that account's `UserVerifications`.
- Each individual lock/unlock action on a UserVerification will now result in a Rails log, as well as a log signifying the start or end of a job.
- Updated all Rails logs to only be written in production environments
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/86453
- To test, confirm you have two `UserVerifications` with the same `user_account_uuid`:
```ruby
UserVerification.all =>
[ #<UserVerification:0x00007078990a0f00
id: 1,
user_account_id: "937b6c00-a8d7-4506-9b7f-7ddacd283c39",
idme_uuid: nil,
logingov_uuid: …
```
> [86435] adds lock_all & unlock_all tasks

- modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb
- modules/simple_forms_api/spec/requests/v1/uploads_spec.rb
Now that Simple Forms is defaulting to allowing only authenticated traffic, it doesn't make sense to allow unauthenticated users to attempt to submit forms. This PR removes our override of `#authenticate` so that if they are not authenticated we will throw an error where previously we let the request through (while logging the request).
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/88328
> Remove Simple Forms API's override of #authenticate

- modules/ivc_champva/app/services/ivc_champva/attachments.rb
This PR fixes the use case where there are more than 7 applicants in one session. This adds robust indexing to the loop.
I've added 7 applicants with 3 attachments in the child support section.
[1f949f9e-ea87-4b5c-8423-14baf41f503b_vha_10_10d-tmp5.pdf](https://github.com/user-attachments/files/16268206/1f949f9e-ea87-4b5c-8423-14baf41f503b_vha_10_10d-tmp5.pdf)
[1f949f9e-ea87-4b5c-8423-14baf41f503b_vha_10_10d-tmp4.pdf](https://github.com/user-attachments/files/16268207/1f949f9e-ea87-4b5c-8423-14baf41f503b_vha_10_10d-tmp4.pdf)
[1f949f9e-ea87-4b5c-8423-14baf41f503b_vha_10_10d-tmp3.pdf](https://github.com/user-attachments/files/16268208/1f949f9e-ea87-4b5c-8423-14baf41f503b_vha_10_10d-tmp3.pdf)
[1f949f9e-ea87-4b5c-8423-14baf41f503b_vha_10_10d_additional_applicants-2-tmp2.pdf](https://github.com/ …
> fix indexing on 3 or more pdfs

- app/controllers/v0/in_progress_forms_controller.rb
- Add a check for participant ID before calling the ITF async job.
- Pension benefit to own this change
- [*Link to ticket created in va.gov-team repo*](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88635) …
> Add check for participant ID

- modules/vaos/app/services/vaos/v2/appointments_reason_code_service.rb
- modules/vaos/spec/services/v2/appointments_reason_code_service_spec.rb
- This is part of the api consolidation effort and moves the logic for extracting reason for appointment information from the reason code text from the FE to BE. The source logic is [here](https://github.com/department-of-veterans-affairs/vets-website/blob/5fc5b4a339e34be9db43e680a4c35798b963ff9b/src/applications/vaos/services/appointment/transformers.js#L233-L239) and [here](https://github.com/department-of-veterans-affairs/vets-website/blob/5fc5b4a339e34be9db43e680a4c35798b963ff9b/src/applications/vaos/services/appointment/transformers.js#L362-L366)
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/86905
- The old behavior returns the information as part of the reason …
> Generate appointment reason from request reasoncode.text

- modules/ivc_champva/app/models/ivc_champva/vha_10_7959c.rb
- modules/ivc_champva/spec/models/vha_10_7959c_spec.rb
In order for PEGA to process 7959c, it needs x-amz-meta-ssn_or_tin embedded in the metadata.
[Uploading 4d7f4aa4-b217-4603-ac01-26d87b194288_vha_10_7959c-tmp.pdf…]()
> add ssn to 7959c

- modules/simple_forms_api/app/services/simple_forms_api/pdf_stamper.rb
This PR is an attempt to resolve some errors we've seen arise around missing files when trying to stamp or delete a PDF.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/88703
> Check if PDF file exists before deleting it while stamping PDFs

- app/controllers/v1/higher_level_reviews_controller.rb
- app/controllers/v1/notice_of_disagreements_controller.rb
- spec/requests/v1/higher_level_reviews_controller_request_spec.rb
- spec/requests/v1/notice_of_disagreements_controller_request_spec.rb
Follow-up to #17497 — I only added the extra logging to Supplemental Claims but (of course) we got the `stack level too deep` errors for both NOD and HLR soon after. This adds the extra logs to those forms as well so we can see if the error we were able to pull from the SC log is the same one causing the stack level error in HLR and NOD.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/73584
Decision Reviews backend
> [DR-73584] Add more logging (NOD + HLR)

- config/features.yml
- Removing va_online_scheduling_clinic_location feature flag
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/88615
Appointments
> Remove va_online_scheduling_clinic_location feature flag
