department-of-veterans-affairs/vets-api

db/migrate/20240628161151_re_add_index_on_flipper_gates.rb, db/schema.rb
Reverts department-of-veterans-affairs/vets-api#17323
=> Revert "Fix invalid index `index_flipper_gates_on_feature_key_and_key_and_value`"

db/migrate/20240627204058_re_add_index_on_flipper_features.rb, db/schema.rb
Reverts department-of-veterans-affairs/vets-api#17320
=> Revert "Fix invalid index `index_flipper_features_on_key`"

modules/simple_forms_api/app/models/simple_forms_api/vba_20_10207.rb, modules/simple_forms_api/lib/simple_forms_api.rb
Scrubs PII from error messages on 20-10207 so that we can now see the errors themselves.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/1417
=> Scrub PII from errors from 20-10207, Simple Forms

modules/mobile/app/services/mobile/v0/lighthouse_health/configuration.rb, modules/mobile/app/services/mobile/v0/lighthouse_health/service.rb, modules/mobile/spec/request/v1/immunizations_request_spec.rb, spec/support/vcr_cassettes/mobile/lighthouse_health/get_immunizations_token_too_many_error.yml
LH Token service for mobile immunizations was assuming the service would return a 200. This raises an error based on what the response is. the example that we saw in datadog was 429 too many requests error. This may be an error we want to pass along to FE but rather then creating this one off mapping, I created this ticket, https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8959, to create one place to map all these types of errors so it can be used across the API.  
https://github.com/department-of-veterans-affairs/va-mobile-app/issues/8522 …
=> add error raise to LH token service

Gemfile.lock
=> Bump sidekiq-ent -> 7.2.4

config/features.yml
Removing unused, duplicate feature flippers
=> delete unused features

config/features.yml
[This FT](https://dsva.slack.com/archives/CBU0KDSB1/p1719840613675229) was removed and needs to be in place for a breaking change
=> Put back necessary feature toggles

app/services/sign_in/constants/access_token.rb, app/services/sign_in/user_code_map_creator.rb, lib/sign_in/logingov/service.rb, modules/mocked_authentication/spec/lib/credential/service_spec.rb, spec/factories/sign_in/code_containers.rb, spec/factories/sign_in/o_auth_sessions.rb, spec/factories/sign_in/validated_credentials.rb, spec/lib/sign_in/logingov/service_spec.rb, spec/services/sign_in/session_refresher_spec.rb, spec/services/sign_in/session_spawner_spec.rb, spec/services/sign_in/token_exchanger_spec.rb, spec/services/sign_in/user_code_map_creator_spec.rb, spec/support/vcr_cassettes/identity/logingov_200_responses.yml
Reverts department-of-veterans-affairs/vets-api#17301
=> Revert "Add Logingov all_email attribute to Sign-in Service"

Gemfile.lock
=> Bump tzinfo-data -> 1.2024.1

config/features.yml
This PR adds form 10-7959f-1 to the features.yml so we can have a flag to toggle it on and off when in production. 
- Adds flipper for form 10-7959f-1
- Success criteria for flipper: gated access to form 10-7959f-1 in a controlled percentage as we begin rolling out to production in the coming weeks/months.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/85561
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggle …
=> 10-7959f-1 Feature Flag

app/controllers/v0/profile/contacts_controller.rb, config/features.yml, spec/controllers/v0/profile/contacts_controller_spec.rb
- **Removes profile_contacts toggle**
department-of-veterans-affairs/va.gov-team#81337
(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything …
=> Removes profile_contacts toggle

db/migrate/20240701192934_add_optimized_index_to_vba_documents_upload_submissions.rb, db/schema.rb
PGHero has identified `vba_documents_upload_submissions` as a slow running query. This PR adds an optimized index to the `vba_documents_upload_submissions` table, targeting the status and created_at columns with a partial condition on s3_deleted. The new index aims to improve query performance for frequently accessed data, potentially reducing response times for related operations.
Current benchmark (prior to migration - via staging env)
```
irb(main):020> model = VBADocuments::UploadSubmission
irb(main):021> 
irb(main):022> query = model.select(:id, :guid, :status, :s3_deleted, :created_at)
irb(main):023>              .where(status: ['pending', 'uploaded', 'received', 'processing', 'success'], s3_deleted: [false, nil])
irb(main):024>              .where('created_at < ?', '2024-07-01') …
```
=> Migration to optimize vba docs table queries

app/controllers/v0/profile/direct_deposits_controller.rb, spec/controllers/v0/profile/direct_deposits_controller_spec.rb
Removed unnecessary logging of control info parameters (and related specs).
=> Remove control info parameters and logging from update

modules/vye/app/controllers/vye/v1/user_infos_controller.rb, modules/vye/app/serializers/vye/address_change_serializer.rb, modules/vye/app/serializers/vye/pending_document_serializer.rb, modules/vye/app/serializers/vye/user_info_serializer.rb, modules/vye/app/serializers/vye/verification_serializer.rb
Reverts department-of-veterans-affairs/vets-api#17371
PR has taken down the Verify Your Enrollment application.
=> Revert "Replace VYE AMS serializers with JSONAPI serializers"

.github/workflows/build.yml
Temp remove these to get an OOB out to kick off the build/deploy manually. We are being rate limited by docker hub
- *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket …
=> temp remove to manually kick things off

modules/debts_api/lib/debts_api/v0/fsr_form_transform/asset_calculator.rb, modules/debts_api/spec/lib/debt_api/v0/fsr_form_transform/asset_calculator_spec.rb
- We found an error out in prod where an attribute we were expecting in a form submission was not there ('questions'). This caused us to 500, we've disabled the feature flag to go back to the old form submission for now so the issue does not happen while we get this fix out.
- *(If bug, how to reproduce)*: I found a way to trigger this by removing 'questions' from the payload
- We are setting a default hash for `questions`
- You can find us at #debt-resolution on slack
- *Link to ticket created in va.gov-team repo …
=> Form 5655 Full Transform - handle nil 'questions'

.github/workflows/build.yml
This reverts commit 68d1765080fcf5351be4721cb0c5c671df596b15.
Putting this back as this was temporary to get the the OOB out
https://dsva.slack.com/archives/C0460N83Y9G/p1719945661418549 …
=> Revert "temp remove to manually kick things off (#17383)"

app/sidekiq/lighthouse/create_intent_to_file_job.rb
- Fixing query on UserAccounts table where it was using the wrong attribute name.
- Updated the find_by statement to use `icn` instead of `veteran_icn`
- [*Link to previous change of the code/bug (if applicable)*](https://github.com/department-of-veterans-affairs/vets-api/pull/17179) …
=> Fix UserAccounts query to use icn instead of veteran_icn

config/features.yml
Created new ProfileInformation Feature Flippers
- department-of-veterans-affairs/va.gov-team#83186
- …
=> Created flipper features for ProfileInformation service

config/features.yml
Adds a flipper to implement the multiple page response (list-loop) pages in the Pensions form.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/82850
- Ran vets-api locally and enabled and disabled the flipper at http://localhost:3000/flipper/features/pension_multiple_page_response
Pension Benefits
=> Add feature toggle

bin/is_ready
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2950
=> Add bin/is_ready for Readiness Probe

bin/is_ready
Sister PR to https://github.com/department-of-veterans-affairs/vets-api/pull/17441
=> feat: is_ready exits 0 on BACKLOG_POD=true

app/services/bgs/dependent_service.rb, app/sidekiq/bgs/submit_form674_job.rb, app/sidekiq/bgs/submit_form686c_job.rb, app/sidekiq/central_mail/submit_central_form686c_job.rb, spec/sidekiq/central_mail/submit_central_form686c_job_spec.rb
- Removing conditionals around a flipper that is now permanent.
- Removed the contents of the else statements
[- *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses Jira*](https://github.com/orgs/department-of-veterans-affairs/projects/1237/views/3?sliceBy%5Bvalue%5D=_noValue&pane=issue&itemId=66038926&sortedBy%5Bdirection%5D=desc&sort …
=> remove dependents central submission check

modules/claims_api/app/sidekiq/claims_api/evidence_waiver_builder_job.rb
- fixes rescue
- [API-37498](https://jira.devops.va.gov/browse/API-37498)
modified:   modules/claims_api/app/sidekiq/claims_api/evidence_waiver_builder_job.rb
=> fixes rescue

lib/debt_management_center/base_service.rb, lib/debt_management_center/debts_service.rb
- We are getting a LOT of timeout errors from our partner DMC. Their timeout threshold is 30 seconds. Seems like when we timeout with them, we trip a breaker and throw a ton of 503 errors. We then overload them with requests every 60 seconds making it hard for them to recover.
- *(If bug, how to reproduce)* Not sure how to reproduce, happy to get ideas
- Our hope is that by extending …
=> 87031 Debts Controller Issues

app/sidekiq/form526_status_polling_job.rb
- This job was timing out when trying to load 10k+ records at once. this small refactor prevents that
- [Ticket](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/87964)
- Flipper: NO
- query manually tested against production database. Rails code tested line by line in production sandbox
Form 526 Submission backup path
=> [DBX-87964] DB performance refactor on 526 backup polling

modules/ivc_champva/app/controllers/ivc_champva/v1/pega_controller.rb
=> Remove service tag

Gemfile.lock, app/models/form_profiles/va_0873.rb, config/form_profile_mappings/0873.yml, spec/fixtures/ask/minimal.json, spec/models/form_profile_spec.rb, spec/requests/swagger_spec.rb
**This pull request includes the following updates:**
1. **va_0873.rb**
- **Added `FormPersonalInformation` class**: This new class encapsulates the personal information logic for better modularity and reusability.
- **Added `FormAvaProfile` class**: This class handles the AVA profile data, improving the code's structure and maintainability.
2. **0873.yml**
- **Revised prefill structure**: The YAML configuration has been updated to reflect a new structure for the prefill process, ensuring data is organized and processed correctly.
3. **Gemfile.lock**
- **Updated `vets-json-schema` to version 24.0.0**: The Gemfile.lock has been modified to include the latest version of the `vets-json-schema` gem, bringing in new schema validations and improvements.
---
1. **va_0873.rb**
- Introduced the …
=> BE | Ask Va API: Updated Form 0873 prefill

modules/vye/lib/vye/batch_transfer/ingress_files.rb
As:
VYE Backend Developer.
I need:
To schedule Sidekiq jobs for staging environment. 
So that: 
I can pull down files from BDN and TIMS on the SFTP server. 
I can upload files to Newman and BDN.  
We need a running SFTP server to download files from. Has to be done after SFTP is working.
Enter the acceptance criteria that will be used to test the user story. 
AC 1: Files could be pulled down from BDN and TIMS utilizing Sidekiq jobs. 
AC 2: Files could be uploaded to Newman and BDN utilizing Sidekiq jobs. 
N/A
N/A 
=> added success and failure counts for injest

bin/lib/vets-api/commands/command.rb, bin/lib/vets-api/setups/native.rb
=> remove require pry

app/swagger/swagger/v1/requests/ivc_champva_forms.rb
Update swagger doc
- Update swagger doc to add `case_id`
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/85715
=> 85715: Update swagger doc

app/models/form_profiles/va_0873.rb, modules/ask_va_api/app/lib/ask_va_api/profile/retriever.rb, modules/ask_va_api/spec/app/lib/ask_va_api/profile/retriever_spec.rb, modules/ask_va_api/spec/requests/v0/inquiries_spec.rb
- updated `Profile::Retriever` error response
- updated `va_0873.rb` error response
- https://github.com/department-of-veterans-affairs/ask-va/issues/1174
=> BE | Ask Va Api:: Update `Profile::Retriever`

modules/ask_va_api/app/services/crm/service.rb
- This is just to point `vets-api` `staging` to `crm dev` environment for testing. Will be changing it to point to `pre-prod` when development work is done. 
=> BE | Ask Va Api: update staging to point to crm dev

modules/claims_api/app/swagger/claims_api/v2/dev/swagger.json, modules/claims_api/app/swagger/claims_api/v2/production/swagger.json, modules/claims_api/config/schemas/v2/526.json, modules/claims_api/config/schemas/v2/generate_pdf_526.json
- Updates 526 v2 schemas for mailing address & change of address attributes. 
- Updates swagger files for docs.
- [API-38040](https://jira.devops.va.gov/browse/API-38040)
- Postman
- rswag/rspec
modified:   modules/claims_api/config/schemas/v2/526.json
modified:   modules/claims_api/config/schemas/v2/generate_pdf_526.json
=> API-38040-526-v2-address-validation

lib/evss/disability_compensation_form/form526_to_lighthouse_transform.rb, spec/lib/evss/disability_compensation_form/form526_to_lighthouse_transform_spec.rb
Trim `addressLine1` of Lighthouse submit request to avoid validation error
Disability Benefits Experience Team 1 - DBEX-TREX - rawr 🦖
[#87716](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/87716) …
=> Trim address line one of mailing address to LH submit request

modules/claims_api/spec/lib/claims_api/bd_spec.rb
- Adds missing variables to failing test.
- hot fix
- rspec
modified:   modules/claims_api/spec/lib/claims_api/bd_spec.rb
=> hot-fix-bd-spec-missing-varaibles

app/controllers/v0/letters_generator_controller.rb
- Refactoring to resolve MethodLength cop on LettersGeneratorController
- N/A
=> Refactoring Disabled MethodLength cop - LettersGeneratorController

modules/debts_api/lib/debts_api/v0/fsr_form_transform/streamlined_calculator.rb
This is part of several back-end transform refactoring tickets. This one is edits specifically to the Streamline calculator.
- *https://github.com/department-of-veterans-affairs/va.gov-team/issues/88278*
Covered by existing tests
VA Debt backend transform
=> 88278: Streamline Calculator Refactor

app/sidekiq/lighthouse/pension_benefit_intake_job.rb, modules/pensions/app/sidekiq/pensions/pension_benefit_intake_job.rb
fix metadata issue preventing pension submissions
https://github.com/department-of-veterans-affairs/va.gov-team/issues/88575
=> Pension 88575 Intake Job Metadata

modules/vye/app/controllers/vye/v1/application_controller.rb, modules/vye/app/models/vye/award.rb, modules/vye/app/models/vye/bdn_clone.rb, modules/vye/app/models/vye/user_info.rb, modules/vye/app/models/vye/user_profile.rb, modules/vye/app/serializers/vye/date_attribute_serializer.rb, modules/vye/app/sidekiq/vye/dawn_dash/activate_bdn.rb, modules/vye/app/sidekiq/vye/midnight_run.rb, modules/vye/app/sidekiq/vye/midnight_run/ingress_bdn.rb, modules/vye/lib/vye/batch_transfer/ingress_files.rb, modules/vye/lib/vye/load_data.rb, modules/vye/spec/factories/vye/bdn_clones.rb, modules/vye/spec/factories/vye/user_profiles.rb, modules/vye/spec/lib/vye/batch_transfer/ingress_files_spec.rb, modules/vye/spec/models/vye/bdn_clone_spec.rb, modules/vye/spec/models/vye/user_profile_spec.rb, modules/vye/spec/sidekiq/vye/dawn_dash/activate_bdn_spec.rb, modules/vye/spec/sidekiq/vye/dawn_dash/egress_updates_spec.rb, modules/vye/spec/sidekiq/vye/dawn_dash_spec.rb, modules/vye/spec/sidekiq/vye/midnight_run/ingress_bdn_spec.rb, modules/vye/spec/sidekiq/vye/midnight_run/ingress_tims_spec.rb, modules/vye/spec/sidekiq/vye/midnight_run_spec.rb, modules/vye/spec/sidekiq/vye/sundown_sweep/clear_deactivated_bdn_spec.rb, modules/vye/spec/sidekiq/vye/sundown_sweep/delete_processed_s3_files_spec.rb, modules/vye/spec/sidekiq/vye/sundown_sweep/purges_stale_verifications_spec.rb, modules/vye/spec/sidekiq/vye/sundown_sweep_spec.rb
=> Updates for ingress

lib/admin/redis_health_checker.rb
Modified attribute that uses Redis class to updating and deleting key.
- [Zenhub Ticket](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/74550)
- Verifying status on lower environments at https://dev-api.va.gov/v0/status
=> Update Redis Check

config/features.yml
Add the feature flag to be consumed by POA upload endpoint.
[API-38233](https://jira.devops.va.gov/browse/API-38233)
N/A
N/A
Feature flags
N/A
=> [API-38233] Add Claims API feature flag for POA benefits docs

config/features.yml
This PR adds a feature flag for form 10-7959c so it can be slow rolled out in production.
- Adds flipper for form 10-7959c
- https://github.com/department-of-veterans-affairs/vets-website/pull/30898
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/87675 …
=> 87675 Add feature flag - form 10-7959c

Gemfile.lock
- Updates the `vets_json_schema` gem
- https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/82212
=> #82212 [10-10 teams]: Update `vets_json_schema` gem to reflect most recent updates

modules/debts_api/lib/debts_api/v0/fsr_form_transform/asset_calculator.rb, modules/debts_api/lib/debts_api/v0/fsr_form_transform/enhanced_expense_calculator.rb, modules/debts_api/lib/debts_api/v0/fsr_form_transform/gmt_calculator.rb, modules/debts_api/lib/debts_api/v0/fsr_form_transform/old_expense_calculator.rb, modules/debts_api/lib/debts_api/v0/fsr_form_transform/utils.rb
This is part of several back-end transform refactoring tickets. This one moves over several non-class-specific methods to the utils module.
- *https://github.com/department-of-veterans-affairs/va.gov-team/issues/88279*
Covered by existing tests
VA Debt backend transform
=> 88279: Backend Transform Utils Refactor

modules/debts_api/lib/debts_api/v0/fsr_form_transform/full_transform_service.rb, modules/debts_api/lib/debts_api/v0/fsr_form_transform/gmt_calculator.rb, modules/debts_api/lib/debts_api/v0/fsr_form_transform/personal_identification_calculator.rb
This is part of several back-end transform refactoring tickets. This one creates more consistency with the outputted data object formats.
- *https://github.com/department-of-veterans-affairs/va.gov-team/issues/88280*
Covered by existing tests
VA Debt backend transform
=> 88280: Update backend transform output consistency

config/features.yml
Add a feature toggle to for pension benefits
- https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/88387
=> Add `pension_introduction_update` to features.yml

modules/debts_api/lib/debts_api/v0/fsr_form_transform/income_calculator.rb
We found out that `nil` values were slipping through for "total monthly net income" property for the transform. [The previous pull request](https://github.com/department-of-veterans-affairs/vets-api/pull/17475) added a fallback `0.00` values for the instances of it. However, this could lead to someone being incorrectly approved for a streamline waiver, so the root cause needs to be addressed differently. This pull request will revert the previous fallback if needed.
- *(Summarize the changes that have …
=> 87408: Revert add fallback for debt total monthly net income

config/features.yml
- *This work is behind a feature toggle (flipper): YES/NO* YES
- added feature toggle for form 1995 to deploy it to prod  …
=> added feature toggle for form 1995

config/features.yml
- We need a new flipper to add to this PR: https://github.com/department-of-veterans-affairs/vets-website/pull/29677 so that the changes can be merged into Main and tested in review instances with the associated PDF work here: https://github.com/department-of-veterans-affairs/vets-api/pull/16852
- Success will be considered when the PDF branch is merged.
- [*Link to ticket created in …
=> add new flipper for FE fields

db/migrate/20240716195104_add_email_sent_to_ivc_champva_forms.rb, db/schema.rb
Update DB table to include email_sent to avoid sending duplicates
- Add migration
- Updated schema
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/88164
=> 88164: Add migrationto add new field with updated schema

app/models/saved_claim.rb, modules/pensions/app/controllers/pensions/v0/pension_claims_controller.rb, modules/pensions/lib/pensions/monitor.rb
- This change updates references to the `itf_datetime` field on the `saved_claims` table to `form_start_date`. This is a prerequisite change before removing the `itf_datetime` field completely.
- [*Link to ticket created in va.gov-team repo*](https://github.com/department-of-veterans-affairs/va.gov-team/issues/87922)
- [*Link to epic*](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/87922)
- *If this work …
=> update references to itf_datetime with form_start_date

config/features.yml
- adds feature flag for displaying new Secure Messaging Edit Contact List page
> Create feature flag for Contact list functionality
> 
> User Story: N/A
> 
> Feature Flag Y/N ? 
> Automated Testing Y/N ? Y-Fazil
> 
> UCD Validation Y/N ? N
> 
> AC1  Feature Flag creation for Contact list functionality is complete
> AC2  
> AC3  
> AC4  
> 
> Links to UCD: 
> FIGMA Link: https://www.figma.com/design/uddjxccqvUyz5FSg1aD5wi/ZFeat---Triage-Group-Selection-Flows?node-id=792-21547&t=1U …
=> adds SM edit contact list feature flag

lib/evss/disability_compensation_form/form526_to_lighthouse_transform.rb, spec/lib/evss/disability_compensation_form/form526_to_lighthouse_transform_spec.rb
This PR expands test coverage for the LH submit request transform class (serviceInformation section). It also fixes a typo that was causing `alternateNames` to not load.
- *This work is behind a feature toggle (flipper): **YES***
[#88844](https://app.zenhub.com/workspaces/disability-benefits-experience-team-1-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-tea …
=> Expand unit tests for LH submit request + fix alternateNames issue

lib/lighthouse/benefits_claims/intent_to_file/monitor.rb
- Refactored the functions in `lib/lighthouse/benefits_claims/intent_to_file/monitor.rb` and updated the error info in the payload for the `track_create_itf_failure` monitor function. If something fails in the ITF endpoint, the previous payload would just return `Unprocessable Entity` as the error message, which was not helpful in identifying the issue. Instead, we've opted to return the entire list of errors given in the response. 
- Pension benefits team to own this change.
- [*Link to ticket created in va.gov-team repo*](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88936)
- [*Link to epic if not included in ticket*](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/departm …
=> Update payload data for track_create_itf_failure monitor log

config/features.yml
Add Pension Benefits feature toggle for content updates
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/88400 …
=> Add feature toggle for pensions update

modules/ivc_champva/app/controllers/ivc_champva/v1/uploads_controller.rb
Add logic to remove an in progress form upon successful submission
- Add known logic to `uploads_controller`
You can see the first call to `InProgressForm` model in the DB shows an application saved and after I submit its destroyed.
=> Add logic to remove an in progress form upon completion

app/controllers/v0/feature_toggles_controller.rb
This makes one round trip to the db instead of two.
Also uses keys better suited for redis.
=> feat: Feature Toggles: Use one query for dolls

config/features.yml, modules/ask_va_api/app/services/crm/service.rb
Added new feature flags to `features.yml`
- ask_va_form_feature
-  ask_va_dashboard_feature
-  ask_va_introduction_page_feature
Updated `Crm::Service` env
- point `vets-api` staging to `crm-api` `preprod`
Here's the PR for FrontEnd adding new feature flags:
- https://github.com/department-of-veterans-affairs/vets-website/pull/30998
- https://github.com/department-of-veterans-affairs/ask-va/issues/1161
- https://github.com/department-of-veterans-affairs/ask-va/issues/1247
=> BE | Ask VA API: Update Feature flags and crm env

Gemfile.lock, db/migrate/20240724183559_add_transaction_id_to_auto_established_claim.rb, db/schema.rb
* Adds migration file
* Updates schema file
[API-38488](https://jira.devops.va.gov/browse/API-38488)
new file:   db/migrate/20240724183559_add_transaction_id_to_auto_established_claim.rb
modified:   db/schema.rb …
=> API-37928-transaction-id-migration

modules/ask_va_api/app/services/crm/service.rb
- updated crm env to qa from preprod
- https://github.com/department-of-veterans-affairs/ask-va/issues/1161
=> BE | Ask VA Api: updated crm env to qa

config/features.yml, lib/debt_management_center/debts_service.rb, spec/lib/debt_management_center/debts_service_spec.rb, spec/lib/debt_management_center/shared_examples/debt_service_examples.rb
- We have an issue with our 3rd party service where they are timing out when we make many requests to them. The vast majority of the time the users do not have records in their system. This adds caching for empty responses from that service
- We are caching in hopes of relieving pressure on the 3rd party service (DMC)
- *(Which team do you work for, …
=> 88497 Cache debts endpoint empty responses

modules/check_in/app/controllers/check_in/v2/appointments_controller.rb, modules/check_in/app/serializers/check_in/vaos/appointment_serializer.rb, modules/check_in/spec/request/v2/appointments_request_spec.rb, modules/check_in/spec/serializers/vaos/appointment_serializer_spec.rb, spec/support/vcr_cassettes/check_in/appointments/get_appointments_without_clinic_200.yml, spec/support/vcr_cassettes/check_in/appointments/get_appointments_without_location_200.yml, spec/support/vcr_cassettes/check_in/clinics/get_clinics_200.yml, spec/support/vcr_cassettes/check_in/clinics/get_clinics_500.yml
- *Implmentation for merging clinic data into vaos upcoming appointments*
- *[https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/71789](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/71789)*
NA
=> 71789 Merging clinic data in vaos upcoming appointments

modules/meb_api/app/controllers/meb_api/v0/forms_controller.rb
- *This work is behind a feature toggle (flipper): `toe_light_house_dgi_direct_deposit`
- No Platform changes but for the Meb_APi module for Toe claim submission controller action
- Aligned  the `submit_claim` method in `FormsController` with the `EducationBenefitsController`
- Replaced the feature flag with `toe_light_house_dgi_direct_deposit`
- Ensured Submissions are enabled in development environment for more thorough testing
- My Education Benefits Team
- [ X] *New code is covered by unit tests*
TOE 1990E submissions
=> Toe submission error handling v2

app/sidekiq/central_mail/submit_central_form686c_job.rb
- *This work is behind a feature toggle (flipper): no*
- This PR adds a line that validates the metadata of the backup submission.
- The solution is to add the validator line prior to the merging of attachment data. This will confirm that the core data being passed along meets the required format. 
-VA Benefits and Claims.
- [*Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses Jira*](https://app.zenhub.com/workspaces/benefits-dependents-experie …
=> Dex 89095 metadata validation

config/features.yml
- This adds a feature toggle to be used in a future implementation of the Complete your profile feature for the Veteran Onboarding app. The corresponding FE change is [here](https://github.com/department-of-veterans-affairs/vets-website/pull/31009).
- I work on the VA.gov IIR team which owns the Veteran Onboarding project.
- While this does introduce a flipper, the success criteria for the feature - which will be implemented at a later date - has not been fully developed yet.
- https://github.com/department-of-veterans-affairs/va-iir/issues/866
- This change only includes adding a new feature toggle.
Feature toggles
(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you …
=> Add Veteran Onboarding Contact Info flow feature toggle

lib/periodic_jobs.rb
Update job to every 15mins
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/88498
=> 88498: Update polling sidekiq job to 15mins

app/models/form_profiles/va_0873.rb, config/settings.yml
- updated `returnUrl` to `/your-personal-information` route
- https://github.com/department-of-veterans-affairs/ask-va/issues/1174
=> BE | Ask VA Api: Update returnUrl for 0873

config/initializers/sidekiq.rb
Prod was failing to hit this healthcheck.
=> Sidekiq Healthcheck should listen on 127.0.0.1

.github/CODEOWNERS, app/uploaders/lighthouse_document_uploader_base.rb
Adding virus scanning via clamAV to lighthouse document uploads. Lighthouse scans uploaded documents for viruses as well before they upload them to VBMS, but the call to Lighthouse happens via a Sidekiq job so it's not possible to let the user know that the upload failed.
- *This work is behind a feature toggle (flipper): YES (benefits_documents_use_lighthouse)*
- department-of-veterans-affairs/va.gov-team/issues/87467
- …
=> [CST] Add virus scanning to lighthouse document uploads

config/locales/en.yml, lib/central_mail/datestamp_pdf.rb, spec/lib/central_mail/datestamp_pdf_spec.rb
Changed date format for date stamp for form 40-10007
https://jira.devops.va.gov/browse/MBMS-71733
Tested by filling out the form locally and submitting to he benefits intake api, using the benefits intake uuid, we downloaded the pdf to confirm that the date was formatted correctly in the MM/DD/YYYY format
- …
=> MBMS-71733 changed date format to MMDDYYY

modules/ivc_champva/spec/services/pdf_filler_spec.rb
HOTFIX to comment on PDF filler spec
=> HOTFIX: Turn off flaky #generate tests

spec/lib/lighthouse/benefits_documents/configuration_spec.rb
DSVA platform reported that the spec spec/lib/lighthouse/benefits_documents/configuration_spec.rb is failing inconsistently. It looks like this is another case of the va online scheduling flipper causing issues. we fixed this in all mobile specs by enabling it for every spec but this spec we worked on is outside of mobile specs so fell through the cracks
https://github.com/department-of-veterans-affairs/va-mobile-app/issues/9226
- *Describe the steps required to verify your changes are working as …
=> enable va online scheduling flipper on benefits config spec

config/features.yml
Add Pension Benefits feature toggle for content updates
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/89520 …
=> Add pensions feature toggle

config/features.yml
Adds a feature toggle for the upcoming work to add new content for medication wording to the pre-check-in application.
department-of-veterans-affairs/va.gov-team#82910
Frontend feature toggle only, no vets-api tests needed.
Pre-check-in application
=> Added feature toggle for medication wording

db/migrate/20240730174253_create_std_institution_facilities.rb, db/schema.rb
Add a table to hold the Institution records imported from the VES Oracle Database, and update the schema accordingly.
10-10 Health Enrollment EZ team
https://github.com/department-of-veterans-affairs/va.gov-team/issues/87005
Confirmed that the new table exists in the database.
=> Create table to store VES DB Institution facility records

modules/vaos/app/services/vaos/v2/appointments_reason_code_service.rb, modules/vaos/spec/factories/v2/appointment_forms.rb, modules/vaos/spec/services/v2/appointments_reason_code_service_spec.rb
Some errors have been popping when parsing the reason code. https://vagov.ddog-gov.com/apm/error-tracking?query=%40issue.age%3A%3C%3D172800000%20env%3Aeks-prod%20resource_name%3AMobile%2A&fromUser=false&issueId=2fa26720-42cd-11ef-be7f-da7ad0900007&refresh_mode=paused&source=all&view=spans&from_ts=1720891010000&to_ts=1721063810000&live=false
It looks like there's some reason codes that have a colon but are missing either a key or value causing the parsing to error out. This change will remove any fields from the reason code hash that does not have a key or value. 
https://github.com/department-of-veterans-affairs/va-mobile-app/issues/9139
- *Describe the steps required to verify your changes are working as expected. Exclusively …
=> Appointments: Anticipate reason codes without key or values

.github/CODEOWNERS, lib/formatters/time_formatter.rb, spec/lib/formatters/time_formatter_spec.rb
add formatter function for human readable time span - quality of life when generating reports against database
https://github.com/department-of-veterans-affairs/va.gov-team/issues/89710
- local testing
none
=> Formatter::TimeFormatter humanize

config/features.yml
- *This work is behind a feature toggle (flipper):NO*
- cleanup unused Flipper  feature flag
- https://jira.devops.va.gov/browse/MHV-59806
- https://github.com/department-of-veterans-affairs/vets-website/pull/31123 …
=> MHV-59806 remove mhv_secure_messaging_to_va_gov_release feature flag

config/initializers/datadog.rb
https://github.com/department-of-veterans-affairs/vets-api/pull/17859
https://docs.datadoghq.com/tracing/trace_collection/custom_instrumentation/ruby/dd-api/#adding-tags-globally-to-all-spans
=> feat: Set kube_deployment & pod_name tags for DD APM

app/controllers/v0/in_progress_forms_controller.rb
- In the track_missing_user_pids monitor method in the InProgressFormsController, we were incorrectly referencing the user_account_id on the user object. It should be user_account_uuid instead. This was causing failures in this monitor method, resulting in some logging messages to be masked.
- Find a user with no participant_id and create a new InProgressForm for pension benefits. This should replicate the bug.
- Pension benefits to own this change.
- [*Link to ticket created in va.gov-team repo*](https://github.com/department-of-veterans-affairs/va.gov-team/issues/88635)
- [*Link to previous change of the code/bug (if applicable)*](https://github.com/department-of-veterans-affairs/vets-api/pull/17603) …
=> Fix reference to user_account_id to user_account_uuid for User object

config/features.yml
Add Pension Benefits feature toggle for content updates
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/89519 …
=> Add pension feature toggle

modules/vye/app/models/vye/bdn_clone.rb, modules/vye/lib/tasks/vye/data/load.rake
this is just a small fix to re-enable loading of users in staging
=> fix to load data in staging

modules/ask_va_api/app/controllers/ask_va_api/v0/static_data_controller.rb, modules/ask_va_api/config/routes.rb
- Add route for `static_data#test_endpoint`
- https://github.com/department-of-veterans-affairs/ask-va/issues/1263
=> BE | Ask VA API: add route for test_endpoint

modules/ask_va_api/app/controllers/ask_va_api/v0/static_data_controller.rb
- revised `StaticData#test_endpoint
- https://github.com/department-of-veterans-affairs/ask-va/issues/1263
=> revised test_endpoint

lib/admin/redis_health_checker.rb
- Quickfix to address a potential race condition in the Redis Health Checker.
=> Memoization Redis Health Refactor

.github/workflows/deploy-template.yml
https://vagov.ddog-gov.com/source-code/setup/apm?env=eks-prod&service=vets-api&version=616404bcf7657ce604bdf491c1faf56a25770f0f
=> feat: Modify DD_GIT_COMMIT_SHA for source code integration

modules/va_notify/README.md
- Updates documentation
- https://app.zenhub.com/workspaces/forms-strike-team-620c2914e703390013c4b414/issues/gh/department-of-veterans-affairs/vanotify-team/1335
- Documentation update only
None
=> VANotify - Update README.md

lib/debt_management_center/debts_service.rb, spec/lib/debt_management_center/shared_examples/debt_service_examples.rb
- This adds Datadog metrics for a caching feature we wrote not too long ago. This also optimizes the caching to only cache empty responses, these are the bulk of the responses we receive and it would seem best to limit what we store.
- *(What is the solution, why is this the solution?)* N/A
- You can find me on #debt-resolution on the Octo Slack
- …
=> 89954 Add Stats for debt request caching

.reek.yml
This PR updates the reek config to play nice with Rails. See the [official reek documentation](https://github.com/troessner/reek?tab=readme-ov-file#working-with-rails) for more info.
Not relevant.
Pull requests. …
=> Update reek config for Rails

.github/CODEOWNERS
Fixing codeowner reviewers. Identity is not able to review their own PRs. PR failing reviews: https://github.com/department-of-veterans-affairs/vets-api/pull/17915/files.
Pull request review output:
```
$ curl 'https://api.github.com/repos/department-of-veterans-affairs/vets-api/pulls/17915/requested_reviewers'
{
"users": [
],
"teams": [
]
}
```
- *Describe …
=> Removing '/' at the end of codeowners path to fix approvals

lib/common/client/base.rb
This should help find common service that are having problems in Datadog.
See https://docs.datadoghq.com/tracing/trace_collection/custom_instrumentation/ruby/dd-api.
=> feat: Tag DD span's with Client service (breakers)

.github/workflows/be_review_prs.yml
The BE Approval job keeps fails when the pull requests has been reviewed and then the job runs again. This will add some knowledge as to what is happening.
Steps to reproduce the error:
1) Pull request is approved
2) More approvals happen and the requested_reviewers disappear, causing this to fail.
A fix is coming out to address this. …
=> Show Github Event name for BE Approval job

modules/ivc_champva/app/services/ivc_champva/pdf_filler.rb, modules/ivc_champva/app/services/ivc_champva/pdf_stamper.rb, modules/ivc_champva/spec/services/pdf_filler_spec.rb
Reverts department-of-veterans-affairs/vets-api#17851
=> Revert "89861: Update how a file copies to hopefully resolve random Rspec fai…"

app/controllers/v0/intent_to_files_controller.rb, app/models/form526_submission.rb, app/sidekiq/evss/disability_compensation_form/submit_form526.rb, config/features.yml, lib/sidekiq/form526_job_status_tracker/backup_submission.rb, spec/lib/sidekiq/form526_job_status_tracker/job_tracker_spec.rb, spec/models/form526_submission_spec.rb, spec/requests/intent_to_files_request_spec.rb, spec/requests/swagger_spec.rb, spec/sidekiq/evss/disability_compensation_form/submit_form526_all_claim_spec.rb, spec/sidekiq/evss/disability_compensation_form/submit_form526_spec.rb
This PR adds two flipper flags to disable various functionality in the 526EZ app in order to facilitate canary production testing.
- *This work is ~~behind~~ a feature toggle (flipper): YES*
Added Flipper flags:
`disability_compensation_production_tester` - disables ITF creation, mail automation (RRD), ancillary form 4142 submission, andbackup path submission
`disability_compensation_fail_submission` - forces a failed submission in order to test the backup submission path
Disability Benefits Experience Team 1 🦖
- *(If introducing a flipper, what is the …
=> Toxic Exposure 1.0: Build feature toggles for production testing

lib/disability_compensation/requests/form526_request_body.rb, lib/evss/disability_compensation_form/form526_to_lighthouse_transform.rb, spec/lib/evss/disability_compensation_form/form526_to_lighthouse_transform_spec.rb
Lighthouse recently added a 3-digit international postal code to match existing EVSS mailing address functionality. This PR updates existing mapping between mailing address inputs so that the 3-digit code is transformed properly for Form 526EZ submission to Lighthouse. 
- *(Summarize the changes that have been made to the platform)* 
- Add international postal code to the right spot in the request to Lighthouse
- *(Which team do you work for, does your team own the maintenance of this component?)* Disability Benefits Team 1 -TREX …
=> [Disability Benefits] Add in Lighthouse international postal code

app/controllers/v0/in_progress_forms_controller.rb
- Veteran ICN is required for ITF logic to work properly. Moved up the ICN check to filter out users that do not have an ICN from hitting the ITF logic.
- Pension benefits to own this change.
- [*Link to ticket created in va.gov-team repo*](https://github.com/department-of-veterans-affairs/va.gov-team/issues/84756)
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Fea …
=> filter out users with no icn from hitting itf logic

modules/claims_api/lib/claims_api/v2/disability_compensation_evss_mapper.rb
- Adds .compact to remove null values from int'l addr
- [API-38974](https://jira.devops.va.gov/browse/API-38974)
Postman
1. hit {{uri}}/services/claims/v2/veterans/{{veteran_id}}/526/synchronous
2. use the following object in the request_body
```
"mailingAddress": {
"addressLine1": "1234 Couch Street",
"addressLine2": "Apt 4",
"city": "Portland",
"zipFirstFive": "",
"zipLastFour": null,
"state": null,
"country": "France",
"internationalPostalCode": "105011"
},
```
3. look for log stating "{"detail":"EVSS DOCKER CONTAINER submit success" 
modified:   modules/claims_api/lib/claims_api/v2/disability_compensation_evss_mapper.rb
(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this …
=> API-38974-intl-addr-nil-values

.github/workflows/code_health_report.yml
Code Health check has been failing randomly from a faraday-retry dependency. Link to [failed test](https://github.com/department-of-veterans-affairs/vets-api/actions/runs/10299927585/job/28660462052?pr=17930). Discussion for pronto issue can be found [here](https://github.com/octokit/octokit.rb/discussions/1486).
N/A
- *If this work is behind a …
=> Added faraday-retry to Code Health check

.github/workflows/be_review_prs.yml
BE Approval check will fail if there are no requested teams for a pull request review. If the pull request has been previously approved, the PR Author is alerted to add their team or backend-review-group as a reviewer.
N/A  …
=> Fail BE approval if requested teams is null

config/features.yml, modules/debts_api/lib/debts_api/v0/financial_status_report_service.rb, modules/debts_api/spec/lib/debt_api/v0/financial_status_report_service_spec.rb
- We are sunsetting the `fsr_confirmation_email` flipper since it's been enabled across environments
- *(Which team do you work for, does your team own the maintenance of this component?)*:
- You can find me at #debt-resolution in Octo Slack
- *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses Jira*:
- https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/87403
- *Link to previous …
=> 87403 Clean up FSR confirmation email feature flag

.github/workflows/audit_service_tags.yml, .github/workflows/be_review_prs.yml, .github/workflows/build-and-publish.yaml, .github/workflows/code_checks.yml, .github/workflows/code_health_report.yml, .github/workflows/codeql-analysis.yml, .github/workflows/danger.yml, .github/workflows/ready_for_review.yml
Cleaned up github actions. I left comments on file changes describing what I did. 
1) Made improvements to run checks faster by putting the labeling jobs as another step.
2) Fixed audit and tests labeling failures by adding permissions: write-all, which is required for adding/removing labels.
- N/A
- 
- *Tests …
=> Cleaned up PR Labels

app/controllers/v0/intent_to_files_controller.rb, app/sidekiq/evss/disability_compensation_form/submit_form526.rb, app/sidekiq/lighthouse/poll_form526_pdf.rb, spec/sidekiq/evss/disability_compensation_form/submit_form526_spec.rb, spec/sidekiq/lighthouse/poll_form526_pdf_spec.rb
This PR fixes issues with `disability_compensation_production_tester` flag:
- stop infinite submit loop when either test flag is enabled
- log user_uuid directly to facilitate production testing
Disability Benefits Experience Team Rawr (1) 🦖
[#90091](https://app.zenhub.com/workspaces/disability-benefits-experience-team-1-63dbdb0a …
=> Toxic Exposure 1.0: Various production tester flag fixes, part 2

modules/simple_forms_api/app/models/simple_forms_api/vba_40_10007.rb
Updating file path in the handle attachments function to use absolute path vs relative path. Change is made to address index out of bounds exceptions on form submission of 40-10007. 
https://jira.devops.va.gov/browse/MBMS-72601 …
=> Added absolute path to handle attachments function

.github/workflows/code_checks.yml
Tests are breaking on "test-passing" labels. This step should be skipped if it's not a PR.
=> fixing failing deploys

config/features.yml
- *This update adds a new feature toggle flag that Enables/disables Secure Messaging Filter Accordion re-design updates on VA.gov*
- *This toggle will be used by the Va.gov Secure Messaging team and will be used for handling the Filter Accordion.*
- *Toggle will be used to successfully hide new filter accordion redesign changes*
- *[MHV-59976](https://jira.devops.va.gov/browse/MHV-59976)*
- *[MHV-57144](https://jira.devops.va.gov/browse/MHV-57144)*
- …
=> [MHV-59976] Add Filter Accordion redesign feature toggle for SM

modules/ivc_champva/app/form_mappings/vha_10_7959c.json.erb
This PR updates the JSON erb file to use the new combined street property so we can stamp street, street2, and street3 in the single "street" box on the form PDF.
- Updates JSON erb mapping to use combined street property
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/90728 …
=> 90728 Use combined street text value - form 10-7959c

modules/debts_api/app/controllers/debts_api/v0/financial_status_reports_controller.rb, modules/debts_api/spec/request/debts_api/v0/financial_status_reports_controller_spec.rb
- This adds Datadog metrics to the new FSR backend transform that has been added, but is currently hidden behind a feature flag. It's being added to the same section where we have the respective logging for it.
- *(What is the solution, why is this the solution?)* N/A
- You can find me on #debt-resolution on the Octo Slack
- …
=> VA-90347: Add Stats for FSR backend transform

config/features.yml
- This work adds a new feature flag for toggling the new confirmation page view
- [Confirmation page Accordion submission details](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/1542)
- Browser tests successful
=> [SIMPLE-FORMS] feat: add feature flag for new confirmation page view

modules/ivc_champva/spec/models/vha_10_7959a_spec.rb
Summary
Adding unit test for 7959A " track_email_usage "
=> track email usage

config/features.yml
Created flipper for the ContactInformation::Service to V2::ContactInformationService upgrade
- department-of-veterans-affairs/va.gov-team#87645
* None, flipper is not on
=> Created va_v3_contact_information_service flipper

app/serializers/dependents_serializer.rb
- Check to confirm that diaries is a hash before trying to access its values. There is an error where diaries is coming in as 'true' and causing an error when it tries to proceed further.
- Bug is happening on the dependents dashboard, cannot be replicated reliably at the moment. This fix should bypass the error if a non hash value comes in.
[- *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses …
=> check for object before accessing

.github/workflows/code_checks.yml
Only attempt to add/remove labels when a pull request kicks off the Code Checks workflow. …
=> Skip pull request labeling when merging a pull request

config/settings.yml
This PR adds the Pager Duty service ID for the newly created `Staging: External: PEGA` service in Pager Duty (per [this doc](https://depo-platform-documentation.scrollhelp.site/developer-docs/downtime-notifications#Downtimenotifications-Configuration)). PEGA is the external service that ingests CHAMPVA forms (10-10d, 10-7959c, 10-7959a, 10-7959f-1, 10-7959f-2) submitted on staging.VA.gov.
- Team: IVC CHAMPVA
- https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/3068
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/90752
- …
=> 90752 Add PEGA pager duty maintenance window service ID - IVC CHAMVPA

lib/disability_compensation/requests/form526_request_body.rb, lib/evss/disability_compensation_form/form526_to_lighthouse_transform.rb, spec/lib/evss/disability_compensation_form/form526_to_lighthouse_transform_spec.rb, spec/support/disability_compensation_form/submissions/with_everything_toxic_exposure.json
Add Claim Notes to the Form526 data being sent to Lighthouse for the overflow page. 
- *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses Jira* https://app.zenhub.com/workspaces/disability-benefits-experience-team-1-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/90902 …
=> Add claim notes to 526 LH transform

modules/simple_forms_api/app/models/simple_forms_api/vba_40_10007.rb
Reverts department-of-veterans-affairs/vets-api#18021, didn't fix failed submissions removing unneccesary code change.
=> Revert "Added absolute path to handle attachments function"

lib/debt_management_center/debts_service.rb, lib/debt_management_center/schemas/debts.json, spec/fixtures/dmc/debt.json, spec/lib/debt_management_center/debts_service_spec.rb, spec/lib/debt_management_center/shared_examples/debt_service_examples.rb, spec/support/schemas/debts.json
- We need a better identifier than what we were using to allow a veteran to view an individual debt. This composite id creates a unique id the frontend can use to display a debt to a vet.
- I spoke with the team that provides the data we're pulling (DMC). They cannot provide a persistent unique identifier since their system does a database update …
=> 90865 Add compositeDebtId to debts response

.github/workflows/audit_service_tags.yml, .github/workflows/be_review_prs.yml, .github/workflows/check_codeowners.yml, .github/workflows/code_checks.yml, .github/workflows/code_health_report.yml, .github/workflows/ready_for_review.yml, .github/workflows/require_backend_label.yml
The ready-for-backend-approval label will be removed after the backend approves a pull request. If there are additional commits pushed to the branch after backend approves the pull request, the ready-for-backend-approval label will be re-added once the checks pass again.
- *Describe the steps required …
=> Cleaned up Pull Request Labels

modules/claims_api/app/sidekiq/claims_api/report_hourly_unsuccessful_submissions.rb, modules/claims_api/app/sidekiq/claims_api/v1/poa_form_builder_job.rb
- Add log line to Prawn error
- Adjust error reporting window -30.minutes
- [API-38432](https://jira.devops.va.gov/browse/API-38432)
- Hit v1 POA submit with an invalid file and got the log line
v1 POA submission
=> Update window and add log line

config/features.yml
Added mhv_integration_medical_records_to_phase_1 feature flag
https://github.com/department-of-veterans-affairs/va.gov-team/issues/88851
N/A
N/A
Feature toggles
=> Added mhv_integration_medical_records_to_phase_1 feature flag

modules/vye/app/models/vye/user_profile.rb, modules/vye/spec/models/vye/user_profile_spec.rb
instrumenting presence of user_info
=> instrumenting presence of user_info

docs/setup/running_binstubs.md
- Add example and best practices for `bin/test`
- n/a
=> Update running_binstubs.md with more test info

config/features.yml
- This removes a feature flag that was used for a front end release. The feature flag has been enabled in production since June 26. 
- There is a PR in vets-website to remove the feature flag from the front-end and is currently in review. 
- [#31323](https://github.com/department-of-veterans-affairs/vets-website/pull/31323)
- [Ticket #539](https://app.zenhub.com/workspaces/contention-classification-640a24db5dcd08457cebbc79/issues/gh/department-of-veterans-affairs/vagov-claim-classification/539)
- …
=> removed feature flag

config/features.yml
Reverts department-of-veterans-affairs/vets-api#17998
This is dependent on front end changes, so need to revert this until those are ready.
=> Revert "removed feature flag"

app/policies/medical_copays_policy.rb, config/features.yml, spec/policies/medical_copays_policy_spec.rb
- We are cleaning up Feature flags that are now the default behavior
- *(Which team do you work for, does your team own the maintenance of this component?)*: You can find me on the Octo Slack at #debt-resolution …
=> Remove un-needed Flippers for debts team

Gemfile.lock
https://github.com/presidentbeef/brakeman/releases
https://github.com/presidentbeef/brakeman/releases/tag/v6.2.1
=> chore: Update brakeman 6.1.2 -> 6.2.1

config/features.yml
…Person::Service Upgrade
Created va_v2_person_service for the upcoming VAProfile::V2::Person::Service Upgrade. Removed unnecessary feature flippers.
- department-of-veterans-affairs/va.gov-team#87645
- [V2::ContactInformation PR](https://github.com/department-of-veterans-affairs/vets-api/pull/18068)
- *Tests …
=> Created va_v2_person_service flipper

config/features.yml
created flipper for SOB updates
=> Added sob_updated_design flipper

Gemfile.lock, modules/ask_va_api/app/controllers/ask_va_api/v0/inquiries_controller.rb, modules/ask_va_api/app/controllers/ask_va_api/v0/static_data_controller.rb, modules/ask_va_api/app/lib/ask_va_api/announcements/retriever.rb, modules/ask_va_api/app/lib/ask_va_api/attachments/retriever.rb, modules/ask_va_api/app/lib/ask_va_api/base_retriever.rb, modules/ask_va_api/app/lib/ask_va_api/correspondences/creator.rb, modules/ask_va_api/app/lib/ask_va_api/correspondences/retriever.rb, modules/ask_va_api/app/lib/ask_va_api/inquiries/creator.rb, modules/ask_va_api/app/lib/ask_va_api/inquiries/retriever.rb, modules/ask_va_api/app/lib/ask_va_api/inquiries/status/retriever.rb, modules/ask_va_api/app/lib/ask_va_api/profile/retriever.rb, modules/ask_va_api/app/services/crm/cache_data.rb, modules/ask_va_api/app/services/log_service.rb, modules/ask_va_api/spec/app/lib/ask_va_api/announcements/retriever_spec.rb, modules/ask_va_api/spec/app/lib/ask_va_api/attachments/retriever_spec.rb, modules/ask_va_api/spec/app/lib/ask_va_api/correspondences/retriever_spec.rb, modules/ask_va_api/spec/requests/v0/inquiries_spec.rb, modules/ask_va_api/spec/requests/v0/static_data_spec.rb, modules/ask_va_api/spec/services/log_service_spec.rb
- **Deprecation Update:** Removed Sentry integration from logging, aligning with its upcoming deprecation.
- **Update Error Message:** Update classes to handle 500 errors.
- **Update Logging Error Message:** Update classes to log all the error response
---
This version provides a clear structure, highlights the reasons behind the changes, and emphasizes the benefits of the updates.
- https://github.com/department-of-veterans-affairs/ask-va/issues/1292
=> BE | Ask Va Api: Update Error Message Response and Logging

modules/claims_api/app/swagger/claims_api/v2/dev/swagger.json, modules/claims_api/app/swagger/claims_api/v2/production/swagger.json, modules/claims_api/config/schemas/v2/526.json, modules/claims_api/spec/requests/v2/veterans/disability_compensation_request_spec.rb
- Updates regex patterns to schema to match https://files.slack.com/files-pri/T1ZD0UBMZ-F072RFM691C/evss_docker_swagger.yaml
1. mailingAddress.city
2. treatment.center.name
- [API-39304](https://jira.devops.va.gov/browse/API-39304)
- Postman 526 V2, with the following request_body:
```
{
"data": {
"type": "form/526",
"claimProcessType": "STANDARD_CLAIM_PROCESS",
"claimNotes": "Some things that are important to know, and are not included in any other place.",
"veteranIdentification": {
"serviceNumber": "123456789",
"veteranNumber": {
"telephone": "5555555555",
"internationalTelephone": "+44 20 1234 5678"
},
"mailingAddress": {
"addressLine1": "1234 Couch St",
"addressLine2": "# 4",
"addressLine3": "Rm 1",
"city": "29-palms",
"state": "OR",
"zipFirstFive": …
```
=> API-39304-update-regex-to-match-EVSS-docker-container

modules/ask_va_api/app/controllers/ask_va_api/application_controller.rb, modules/ask_va_api/app/controllers/ask_va_api/v0/inquiries_controller.rb, modules/ask_va_api/spec/requests/v0/inquiries_spec.rb
- Add `pagination` to `InquiriesController#index` action
- https://github.com/department-of-veterans-affairs/ask-va/issues/1285
=> BE | Ask VA Api: add pagination to InquiriesController#index

spec/support/vcr_cassettes/mobile/profile/v2/delete_email_initial.yml, spec/support/vcr_cassettes/mobile/profile/v2/delete_phone_initial.yml, spec/support/vcr_cassettes/mobile/profile/v2/get_address_status_complete.yml, spec/support/vcr_cassettes/mobile/profile/v2/get_address_status_error.yml, spec/support/vcr_cassettes/mobile/profile/v2/get_address_status_incomplete.yml, spec/support/vcr_cassettes/mobile/profile/v2/get_address_status_incomplete_2.yml, spec/support/vcr_cassettes/mobile/profile/v2/get_address_transaction_status.yml, spec/support/vcr_cassettes/mobile/profile/v2/get_email_status_complete.yml, spec/support/vcr_cassettes/mobile/profile/v2/get_email_status_incomplete.yml, spec/support/vcr_cassettes/mobile/profile/v2/get_phone_status_complete.yml, spec/support/vcr_cassettes/mobile/profile/v2/get_phone_status_incomplete.yml, spec/support/vcr_cassettes/mobile/profile/v2/init_vet360_id_status_400.yml, spec/support/vcr_cassettes/mobile/profile/v2/init_vet360_id_status_complete.yml, spec/support/vcr_cassettes/mobile/profile/v2/init_vet360_id_status_incomplete.yml, spec/support/vcr_cassettes/mobile/profile/v2/init_vet360_id_success.yml, spec/support/vcr_cassettes/mobile/profile/v2/post_address_initial.yml, spec/support/vcr_cassettes/mobile/profile/v2/post_email_initial.yml, spec/support/vcr_cassettes/mobile/profile/v2/post_phone_initial.yml, spec/support/vcr_cassettes/mobile/profile/v2/put_address_initial.yml, spec/support/vcr_cassettes/mobile/profile/v2/put_address_success.yml, spec/support/vcr_cassettes/mobile/profile/v2/put_email_initial.yml, spec/support/vcr_cassettes/mobile/profile/v2/put_phone_initial.yml
The VCR cassettes were created the upgrade of V2::ContactInformation::Service for all mobile requests. Mobile requests will be using the v2 endpoint ContactInformation endpoint
- department-of-veterans-affairs/va.gov-team#87645
- [V2::ContactInformation PR](https://github.com/department-of-veterans-affairs/vets-api/pull/18068) …
=> Created VCR cassettes for the mobile profile upgrade for V2::ContactInformation::Service

modules/simple_forms_api/app/models/simple_forms_api/vba_40_10007.rb
Added unsafe and optional content settings to 40-10007 attachments code …
=> MBMS-72601 added unsafe option and optional content settings

modules/vye/app/models/vye/address_change.rb, modules/vye/app/models/vye/direct_deposit_change.rb, modules/vye/app/models/vye/verification.rb, modules/vye/spec/models/vye/address_change_spec.rb, modules/vye/spec/models/vye/direct_deposit_change_spec.rb, modules/vye/spec/models/vye/verification_spec.rb
reporting queries have to be done in batches
=> batching up reports

modules/simple_forms_api/app/models/simple_forms_api/vba_40_10007.rb
Added a version check to the race string when being created and also added a dup method to the string to make it modifiable.
https://jira.devops.va.gov/browse/MBMS-68369
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/develo …
=> MBMS-68369 Added check on race

app/sidekiq/form526_state_logging_job.rb, spec/sidekiq/form526_state_logging_job_spec.rb
- Replaces logging of every single submission ID in our 526 state log with just counts, which is what we care about
- we still want to log the 'failure_type' submission IDs, as these should never be more than a handful and this is a useful breadcrumb
- This change is necessary because Datadog truncates long logs, which means the original version would not work for building a dashboard
- small clean up to the log body
- nest state log under `state_log` key
- add `start_date` and `end_date` for admin facing clarity
- [Ticket](https://github.com/orgs/department-of-veterans-affairs/projects/1263/views/2?filterQuery=assignee%3ASamStuckey&pane=issue&itemId=71313591)
- [Document about 526 …
=> [DBX-88683] reduce 526 state logs to counts where applicable

config/features.yml
PR to add a feature toggle, `:veteran_onboarding_show_welcome_message_to_new_users`, which will be used to determine whether or not we should display a welcome message when a user first logs in to va.gov.
[github issue](https://github.com/department-of-veterans-affairs/va-iir/issues/1019)
No tests are involved in this PR, just adding a feature toggle
=> VA-IIR 1019: add feature toggle for "Welcome to MyVA"

modules/meb_api/app/controllers/meb_api/v0/forms_controller.rb, modules/meb_api/config/routes.rb
- Refactor controller action and update letters service 
- *Tests need to be written for both the flipper on …
=> refactor forms letter call

modules/va_notify/app/sidekiq/va_notify/email_job.rb, modules/va_notify/app/sidekiq/va_notify/icn_job.rb, modules/va_notify/app/sidekiq/va_notify/user_account_job.rb, modules/va_notify/spec/sidekiq/email_job_spec.rb, modules/va_notify/spec/sidekiq/icn_job_spec.rb, modules/va_notify/spec/sidekiq/user_account_job_spec.rb
- This work is behind a feature toggle (flipper): 
NO
Following the work done in #16932, we want to continue to improve our error notifications in vets-api. In addition to the logging that we added in [#1316](https://github.com/department-of-veterans-affairs/vanotify-team/issues/1316) we also add some statsd increment.
VANotify
[VANotify Zenhub Ticket](https://app.zenhub.com/workspaces/forms-strike-team-620c2914e703390013c4b414/issues/gh/department-of-veterans-affairs/vanotify-team/1321)
- *Describe the steps required to verify your changes are working as expected. Exclusively …
=> Add Statsd increment to error logic for EmailJob IcnJob and AccountIdJob

modules/simple_forms_api/app/models/simple_forms_api/vba_40_10007.rb
- Remapped CMP metadata to account for users relationship to the veteran impacting which data we use for the veterans name.
- https://jira.devops.va.gov/browse/MBMS-73637
- CMP metadata indexing
=> MBMS-73637 Reindexed the CMP meta data mapping

config/features.yml
Adds a feature flag in support of adding a download modal to the Find Forms detail pages.
=> VACMS-18855 Add feature flag for Find Forms modal

config/features.yml
- Feature flag for 5490 maintenance
- Feature flag for 1606/30 split in MEB app
- *Tests need to be written for …
=> add feature flags for meb and 5490

modules/appeals_api/spec/controllers/concerns/appeals_api/status_simulation_spec.rb
Temporary fix to comment out flaky specs before putting in debugging statements in a future PR - https://dsva.slack.com/archives/CBU0KDSB1/p1725563920185959
=> Comment out broken specs until future debugging

config/features.yml
This PR removes the `my_va_enable_new_sip_config` feature flag
- Current ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/82798
- Previous ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/80036
- Previous PR: https://github.com/department-of-veterans-affairs/vets-api/pull/16700
- …
=> My VA - remove my_va_enable_new_sip_config feature flag

modules/travel_pay/app/controllers/travel_pay/v0/claims_controller.rb, modules/travel_pay/app/services/travel_pay/base_client.rb, modules/travel_pay/app/services/travel_pay/claims_client.rb, modules/travel_pay/app/services/travel_pay/claims_service.rb, modules/travel_pay/spec/services/claims_client_spec.rb, modules/travel_pay/spec/services/claims_service_spec.rb
- To set up the refactoring to separate out the API auth, this creates a simple `base_client`, with reusable code and renames all current client and service files and specs to include "claims". 
Travel Pay Team
- …
=> Add Travel Pay base_client for reusable code

config/features.yml
- Simple flipper addition for frontend ticket for adding Datadog's Real User Monitoring to some pages
- https://github.com/department-of-veterans-affairs/vets-website/pull/31820
=> Add New flipper for Real User Monitoring of Disability Benefits Frontends

.github/CODEOWNERS, app/controllers/sts/terms_of_use_controller.rb, app/controllers/v0/terms_of_use_agreements_controller.rb, config/routes.rb, db/seeds/development.rb, spec/controllers/sts/terms_of_use_controller_spec.rb, spec/controllers/v0/terms_of_use_agreements_controller_spec.rb
- Create STS authenticated TOU current_status route `sts/terms_of_use/current_status`
- Remove `current_status` from `terms_of_use_agreements` controller
- https://jira.devops.va.gov/browse/VI-439
- migrate and seed database 
- start server - `rails s`
- Get the ICN of a user account you have locally that has a tou agreement:
```ruby
icn = UserAccount.joins(:terms_of_use_agreements).last.icn
```
- Generate assertion
```ruby
assertion_payload = {
sub: icn, # icn from prev step
aud: 'http://localhost:3000/v0/sign_in/token',
iat: Time.zone.now.to_i,
exp: Time.zone.now.to_i + 1000,
scopes: ['http://localhost:3000/sts/terms_of_use/current_status'],
service_account_id: 'c34b86f2130ff3cd4b1d309bc09d8740',
user_attributes: { …
```
=> [VI-439] Create STS authenticated TOU current_status route

app/controllers/v0/in_progress_forms_controller.rb
- Fix the args passed into CreateIntentToFileAsync job call.
- Pension team to own this work.
- [*Link to ticket created in va.gov-team repo*](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91764) …
=> fix parameters for CreateIntentToFileAsync job call

lib/scopes/form526_submission_state.rb, spec/models/form526_submission_spec.rb
This PR refines an existing scope `:accepted_to_primary_path` on Form 526 Submissions to reflect a successful submission to EVSS or Lighthouse, and adds two new scopes to check for each of those successful submissions: `:accepted_to_evss_primary_path` and `:accepted_to_lighthouse_primary_path`.
- *This work is behind a feature toggle (flipper): YES/NO* Yes
- *(Summarize the changes that have been made to the platform)* Updates scopes on Form526Submissions
- *(Which team do you work for, does your team own the maintenance of this component?)* DBEX/TREX Team 1 …
=> [DBEX- Disability Compensation Team 1] Update Form526Submission scopes to reflect successful submission to either EVSS or LH

modules/meb_api/app/controllers/meb_api/v0/forms_controller.rb
- expect a 200 on the claimant response
=> expect a 200 response

lib/mdot/client.rb, spec/lib/mdot/client_spec.rb, spec/support/vcr_cassettes/mdot/submit_order_missing_body_400.yml
This PR updates the MDOT (supply reordering) client to be more defensive. In particular, we are seeing errors for some responses from the upstream with a missing response body. ([example trace](https://vagov.ddog-gov.com/apm/services/medical-supply-reordering/operations/rack.request/resources?dependencyMap=qson%3A%28data%3A%28telemetrySelection%3Aall_sources%29%2Cversion%3A%210%29&deployments=qson%3A%28data%3A%28hits%3A%28selected%3Aversion_count%29%2Cerrors%3A%28selected%3Aversion_count%29%2Clatency%3A%2195%2CtopN%3A%215%29%2Cversion%3A%210%29&env=eks-prod&errors=qson%3A%28data%3A%28issueSort%3AFIRST_SEEN%29%2Cversion%3A%210%29&fromUser=false&graphType=flamegraph&groupMap …
=> [Supply reordering] handle missing error result

lib/evss/disability_compensation_form/form526_to_lighthouse_transform.rb, spec/lib/evss/disability_compensation_form/form526_to_lighthouse_transform_spec.rb
During the 10% rollout of TE, a few submissions came through with XXs for the month or day (indicating partial days), and failed when trying to parse them into an LH request. The FE seems to effectively validate against this and prevent submission, so the root cause is still a mystery. In the meantime, this BE fix will handle these dates accordingly.
Method that parses incoming TE dates modified to account for XX in date parts
Disability Benefits Experience Team 1 - DBEX TREX 🦖 …
=> Toxic Exposure: Handle dates with XX or month or day

lib/periodic_jobs.rb, modules/vye/app/sidekiq/vye/midnight_run/ingress_bdn.rb
Setting up periodic jobs that does the daily transfers between the systems VYE deals with.
=> setting up periodic jobs

.github/workflows/deploy_missing_notifications.yml
Notify when prod deploy doesn't go out. Pulls holidays from sync_windows in argo repo.
Example here:
- https://github.com/department-of-veterans-affairs/vets-api/actions/runs/10851990905/job/30116995662?pr=18443
- https://dsva.slack.com/archives/C039HRTHXDH/p1726241856893259
=> feat: Notify if prod does not deploy

modules/vye/docs/scheduled-jobs.md
fixed marking for mermaid block so that the diagram gets rendered properly
=> marking mermaid block in markdown

.github/workflows/be_review_prs.yml, .github/workflows/code_checks.yml, .github/workflows/ready_for_review.yml, .github/workflows/require_backend_label.yml
[Label Pull Request Reviewers workflow ](https://github.com/department-of-veterans-affairs/vets-api/blob/master/.github/workflows/require_backend_label.yml)is supposed to omit backend approval when the requested PR team belongs to Mobile, Identity, or Lighthouse. Unfortunately, labels are not correctly working.
When a pull request is in draft mode:
1. "ready-for-backend-review" label is removed
2. "require-backend-review" label is removed
3. "omit-backend-review" is removed
4. Require backend-review-group approval should fail
- …
=> Only label ready to review pull requests

.github/CODEOWNERS, config/initializers/config.rb, docker-compose.review.yml, docker-compose.test.yml, docker-compose.yml, helmCharts/vets-api/templates/deployment.yaml
- Update the config gem configuration to use different environment variables pattern
- Upper case
- Double underscore
Update existing of environment variables in docker-compose and helm chart
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/92961
- Upper case
- Double underscore
=> Update config gem configurations

.github/workflows/be_review_prs.yml
=> Removed 'exit if draft pr' for be approval GHA

modules/simple_forms_api/app/models/simple_forms_api/vba_40_10007.rb
Switch gems from combinePDF to hexaPDF to merge docs
https://jira.devops.va.gov/browse/MBMS-72601
- …
=> MBMS-72601 Changed gems from CombinePDF to hexaPDF

spec/models/va_profile_redis/cache_spec.rb
Fixed breaking test in vets-api [here](https://github.com/department-of-veterans-affairs/vets-api/actions/runs/10923652593/job/30329664987).
-N/A
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles …
=> Fixed Cache Spec for ContactInformationV2

.github/workflows/code_checks.yml
Fixing test-passing and test-failures. If CodeChecks pass, add the test-passing even if the label is already tagged on the PR. If CodeChecks fail, remove the test-failure even if the label is not tagged on the PR. 
- N/A …
=> Fixed test-passing and test-failing labels

config/locales/exceptions.en.yml
- catching attachment scanning exception from `mhv-sm-patient-api` services 
- https://vagov.ddog-gov.com/logs?query=trace_id%3A849601284565888302%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=paused&sort=time&spanID=4221721698232176668&storage=hot&stream_sort=desc&viz=stream&from_ts=1724279404576&to_ts=1724281407816&live=false
- [MHV-53461](https://jira.devops.va.gov/browse/MHV-53461)
- ![image](https://github.com/user-attachments/assets/a54b09b2-322e-40e8-88cc-a75a7ba1fb36)
- *Describe …
=> MHV-53461 SM attachment scan error exception

config/features.yml
- add `mhv_secure_messaging_triage_group_plain_language` feature flag that Disables/Enables Secure Messaging recipients group plain language design
- this feature flag is related to the [MHV SM Plain Triage group naming initiative](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/secure-messaging/product/plain-language-TG-initiative/initiative-brief.md).  Estimated timeline - end 2024 - early 2025
- Primarily expected to be used in `vets-website` for front end …
=> MHV-62185 add mhv_secure_messaging_triage_group_plain_language feature flag

modules/accredited_representative_portal/app/controllers/accredited_representative_portal/application_controller.rb, modules/accredited_representative_portal/app/controllers/accredited_representative_portal/v0/form21a_controller.rb, modules/accredited_representative_portal/app/services/accreditation_service.rb, modules/accredited_representative_portal/config/routes.rb, modules/accredited_representative_portal/spec/requests/accredited_representative_portal/v0/form21a_spec.rb, modules/accredited_representative_portal/spec/services/accreditation_service_spec.rb
Quick PR to clean up a few straggling items before delivering the ARP engine:
https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/93199
specs
ARP
=> arf.93199 clean up ARP engine

modules/mobile/spec/requests/mobile/v0/appointments/vaos_v2_spec.rb
Failing on master branch. https://github.com/department-of-veterans-affairs/vets-api/runs/30590084157. This code was modified yesterday in https://github.com/department-of-veterans-affairs/vets-api/pull/18486.
The test fails intermittently.
=> Skip vaos_v2_spec

modules/simple_forms_api/app/services/simple_forms_api/notification_email.rb, modules/simple_forms_api/spec/services/notification_email_spec.rb
This is a broken-out piece of this PR: https://github.com/department-of-veterans-affairs/vets-api/pull/18591
Trying to reduce line-count so Danger doesn't get mad at me.
=> Begin updating tests for Simple Forms emails

modules/claims_api/spec/lib/claims_api/v2/disability_compensation_evss_mapper_spec.rb
- Refactors disability_compensation_evss_mapper_spec
- [API-40344](https://jira.devops.va.gov/browse/API-40344)
modified:   modules/claims_api/spec/lib/claims_api/v2/disability_compensation_evss_mapper_spec.rb
=> API-40344-refactor-disability_compensation_evss_mapper_spec

app/uploaders/veteran_facing_forms_remediation_uploader.rb, modules/simple_forms_api/app/services/simple_forms_api/s3/submission_archive_builder.rb, modules/simple_forms_api/app/services/simple_forms_api/s3/submission_archive_handler.rb, modules/simple_forms_api/app/services/simple_forms_api/s3/submission_archiver.rb, modules/simple_forms_api/app/services/simple_forms_api/s3/utils.rb, modules/simple_forms_api/lib/tasks/archive_forms_by_uuid.rake, spec/uploaders/veteran_facing_forms_remediation_uploader_spec.rb
- This work updates archive upload/download logic in accordance with manual testing findings
- [Form Submission Remediation - Test remediation process and make updates in accordance with findings](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/1697)
Any
=> [SIMPLE_FORMS] fix: updates to logic in accordance with testing findings

modules/simple_forms_api/spec/services/notification_email_spec.rb
This PR builds off and completes [this one](https://github.com/department-of-veterans-affairs/vets-api/pull/18592) and [this one](https://github.com/department-of-veterans-affairs/vets-api/pull/18614). It's just moving some specs around.
=> Simple Forms - final notifications spec change

.github/CODEOWNERS, .rubocop.yml, .rubocop_todo.yml, app/controllers/concerns/vet360/writeable.rb, app/models/user.rb, app/models/va_profile_redis/contact_information.rb, app/models/va_profile_redis/v2/cache.rb, app/models/va_profile_redis/v2/contact_information.rb, config/redis.yml, lib/va_profile/v2/contact_information/service.rb, spec/factories/va_profile/v2/persons.rb, spec/lib/common/models/concerns/cache_aside_spec.rb, spec/lib/va_profile/v2/contact_information/service_spec.rb, spec/models/async_transaction/va_profile/base_spec.rb, spec/models/async_transaction/vet360/base_spec.rb, spec/models/va_profile_redis/cache_spec.rb, spec/models/va_profile_redis/v2/cache_spec.rb, spec/models/va_profile_redis/v2/contact_information_spec.rb, spec/rails_helper.rb, spec/requests/swagger_spec.rb, spec/requests/v0/profile/email_addresses_spec.rb, spec/requests/v0/profile/transactions_spec.rb, spec/support/va_profile/stub_vaprofile_user.rb, spec/support/va_profile/stub_vet360.rb
VAProfileRedis::V2::ContactInformation needs to be configured for V2::ContactInformation to ensure user's vet360_contact_info is not affected by the upgrade in FormProfile and in mobile requests.
User's `vet360_contact_info` is dependent on VAProfileRedis::ContactInformation. To avoid any issues with mobile and prefill, `vaprofile_contact_info` and `va_profile_v2_email` replaces the exisiting `vet360_contact_info`. This will switch back after the upgrade is complete. 
The rails helper `stub_vaprofile_user` records the new …
=> Configured VAProfileRedis::V2::ContactInformation

app/sidekiq/benefits_intake_remediation_status_job.rb
correct variable used in log
[Remediation Report generalized, cronjob, metrics in DataDog](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91844)
[Pension, Burial | Remediation report updates](https://github.com/department-of-veterans-affairs/va.gov-team/issues/93186)
local check of logs
forms using lighthouse benefitsintake service
=> Pension 93186 remediation report log variable

config/features.yml
- Adding a feature flag for the new Yellow Ribbon section in Comparison Tool
No related issues
No testing required
=> Edm 91 yellow ribbon feature flag

modules/claims_api/spec/requests/v1/forms/rswag_2122_spec.rb, modules/debts_api/lib/debts_api/v0/fsr_form_transform/discretionary_income_calculator.rb, modules/debts_api/lib/debts_api/v0/fsr_form_transform/installment_contracts_other_debts_calculator.rb, modules/debts_api/lib/debts_api/v0/fsr_form_transform/old_expense_calculator.rb, modules/debts_api/lib/debts_api/v0/fsr_form_transform/personal_data_calculator.rb
- This PR fixes a number of flaky specs related to missing lib explicit requires
=> Fixing flaky specs missing lib requires

app/models/user.rb
Removed comments in the user model. 
User's vet360_contact_info is dependent on VAProfileRedis::ContactInformation. To avoid any issues with mobile and prefill, vaprofile_contact_info and va_profile_v2_email replaces the exisiting vet360_contact_info for the new service.
- N/A
- No changes. Just removed comments
(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any …
=> Removed comments in user model

config/features.yml
=> add 10-7959f-2 to feature toggle config

modules/mobile/app/controllers/mobile/v0/appointments_controller.rb, modules/mobile/app/helpers/mobile/appointments_cache_interface.rb
fix for flakey tests 
https://github.com/department-of-veterans-affairs/va-mobile-app/issues/9680
(OPTIONAL)_What should the reviewers know in addition to the above. Is there …
=> move appt error catch

modules/vba_documents/spec/requests/v2/uploads_spec.rb
- Uploads spec that fails sometimes because of uninitialized constant
=> Fixing flaky uploads spec

app/models/user_session_form.rb
- https://dsva.slack.com/archives/CBU0KDSB1/p1727731729824279
- https://github.com/department-of-veterans-affairs/vets-api/pull/18685 …
=> Revert mpi cache invalidate

.github/CODEOWNERS
- Update codeowners spec file from v0 to v1 and update codeowner for swagger file
Post-911 Statement of Benefits
=> EDM/update codeowners for SOB

app/models/saved_claim/veteran_readiness_employment_claim.rb
- This work is behind a feature toggle (flipper): *NO*
- Remove duplicate logic for sending email when submitting VRE form
- Log separately before sending email
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/92651
- Specs run
None
=> Cleanup Email Logic for VRE Form Submission

lib/disability_compensation/providers/document_upload/evss_supplemental_document_upload_provider.rb, spec/lib/disability_compensation/providers/document_upload/evss_supplemental_document_upload_provider_spec.rb, spec/lib/disability_compensation/providers/document_upload/lighthouse_supplemental_document_upload_provider_spec.rb
Adds more robust logging for documenting uploads via the EVSSSupplementalDocumentUploadProvider. This will track all of the important events during an upload and allow us to easily query and make dashboards in DataDog
- *This work is behind a feature toggle (flipper): NO but it will be, this code is unused currently
Benefits Disability
=> Overhaul EVSS API Upload Provider logging

modules/va_notify/app/sidekiq/va_notify/icn_job.rb, modules/va_notify/app/sidekiq/va_notify/user_account_job.rb, modules/va_notify/spec/sidekiq/icn_job_spec.rb, modules/va_notify/spec/sidekiq/user_account_job_spec.rb
- *(Summarize the changes that have been made to the platform): Adding StatsD metric for successful jobs
- *(If bug, how to reproduce)*: NA
- *(What is the solution, why is this the solution?)*: Adding these metrics will allow us to track overall performance in datadog
- *(Which team do you work for, does your team own the maintenance of this component?)*: VA Notify - yes, my team owns this module …
=> VANotify - Add Statsd for successful icn and user account jobs

app/models/form_submission.rb, spec/models/form_submission_spec.rb
This reverts commit c0efed373e682b0d18c5bde5d34e8d8488515d44.
The reverted commit is causing us to lose data on prod.
=> Revert "Handle nil form_data with a sensible default, needed for JSON parsing"

modules/claims_api/app/services/claims_api/slack/failed_submissions_messenger.rb, modules/claims_api/spec/services/failed_submissions_messenger_spec.rb
* Turns va.gov ID's into a link in DD wth last 3 days as the timeframe
* Adjusts test
[API-40975](https://jira.devops.va.gov/browse/API-40975)
* Easiest imo is to make sure you have a claim with the cid for va.gov n your DB then remove the to..from for that query.  Then from the console you can send the job va:
* require 'claims_api/report_hourly_unsuccessful_submissions'
* ClaimsApi::ReportHourlyUnsuccessfulSubmissions.new.perform
* You can dial the test message in by commenting out the other values being sent in
* Specifically lines: 35, 37 - 39 in `failed_submissions_messenger.rb`
* Make sure to change the channel to `channel: '#vaapi-alerts-testing',`
* If you need the test channel credentials let me know and I can send them via keybase
* Alert should show up in the channel
el as a …
=> API-40975-va-gov-errors-slack-alert-dd-link

modules/simple_forms_api/app/services/simple_forms_api/notification_email.rb
This is Part 1 of a (probably) 2-part series of PRs. [The big PR from which this was split is here.](https://github.com/department-of-veterans-affairs/vets-api/pull/18851) It doesn't actually change behavior yet (hence no test changes) but sets up the methods I'll be needing to change behavior in the next PR.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/1731
=> Use form-provided email address instead of Profile email address, Part 1

modules/claims_api/spec/factories/auto_established_claims.rb, modules/claims_api/spec/factories/bgs_response.rb, modules/claims_api/spec/factories/claims_api_base_factory.rb, modules/claims_api/spec/mailers/report_monthly_submissions_spec.rb, modules/claims_api/spec/models/auto_establish_claim_spec.rb, modules/claims_api/spec/requests/v1/forms/526_spec.rb, modules/claims_api/spec/requests/v1/forms/rswag_526_spec.rb, modules/claims_api/spec/requests/v1/rswag_claims_spec.rb, modules/claims_api/spec/requests/v2/veterans/claims_spec.rb, modules/claims_api/spec/serializers/claim_detail_serializer_spec.rb, modules/claims_api/spec/services/disability_compensation/pdf_generation_service_spec.rb, modules/claims_api/spec/shared_reporting_helper.rb, modules/claims_api/spec/sidekiq/claim_uploader_spec.rb, modules/claims_api/spec/sidekiq/flash_updater_spec.rb, modules/claims_api/spec/sidekiq/report_monthly_submissions_spec.rb, modules/claims_api/spec/sidekiq/shared_reporting_examples_spec.rb, modules/claims_api/spec/sidekiq/special_issue_updater_spec.rb
- Separates the bgs factories from 526 factories. 
- Simplifies factories with inheritance from base. 
- Makes the main factory basic, and adds traits to add on. 
- Fixes corresponding tests.
- [API-41053](https://jira.devops.va.gov/browse/API-41053)
modified:   modules/claims_api/spec/factories/auto_established_claims.rb
new file:   modules/claims_api/spec/factories/bgs_response.rb
modified:   modules/claims_api/spec/factories/claims_api_base_factory.rb
modified:   modules/claims_api/spec/mailers/report_monthly_submissions_spec.rb
modified:   modules/claims_api/spec/models/auto_establish_claim_spec.rb
modified:   modules/claims_api/spec/requests/v1/forms/526_spec.rb
modified:   modules/claims_api/spec/requests/v1/forms/rswag_526_spec.rb
modified: …
=> API-41053-526-factory

lib/sidekiq/form526_backup_submission_process/processor.rb
- This work fixes a bug we found with 'undefined method 'icn' for nil' when Form526 submissions were being processed. The bug happened because the Backup Submission class could not find a user account. This fix uses the primary path's way of finding a submission's user account. 
-https://app.zenhub.com/workspaces/disability-benefits-experience-team-1-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/94537 …
=> [Disability Benefits Team 1] Use data we have instead to find icn

db/schema.rb, modules/va_notify/db/migrate/20241014205528_add_metadata_to_va_notify_notifications.rb
- *(Summarize the changes that have been made to the platform)*: Adding an additional db field to an existing table.
- https://app.zenhub.com/workspaces/forms-strike-team-620c2914e703390013c4b414/issues/gh/department-o …
=> VaNotify - Add metadata field to notifications table

Gemfile.lock, app/models/form_profile.rb, lib/flipper/route_authorization_constraint.rb, modules/ivc_champva/app/models/ivc_champva/vha_10_7959a.rb, modules/ivc_champva/app/models/ivc_champva/vha_10_7959c.rb, modules/ivc_champva/spec/services/s3_spec.rb, modules/mobile/app/controllers/mobile/v0/facilities_info_controller.rb, modules/mobile/app/helpers/mobile/facilities_helper.rb, modules/vye/spec/sidekiq/vye/sundown_sweep/clear_deactivated_bdn_spec.rb
- Bump `rubocop` to 1.67.0
- Resolve some cops
- https://github.com/department-of-veterans-affairs/vets-api/pull/18893
=> bump rubocop 1.67.0

db/migrate/20241016171432_drop_upload_submission_status_created_at_index.rb, db/schema.rb
Index added to prevent long query run times. There have been many instances of [PG::QueryCanceled errors](https://vagov.ddog-gov.com/logs?query=env%3Aeks-prod%20service%3Avets-api%20%22PG%3A%3AQueryCanceled%22%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=time%2Casc&viz=stream&from_ts=1726501633000&to_ts=1729093633000&live=true). 
VBADocuments::UploadRemover changed the query parameters in this [PR](https://github.com/department-of-veterans-affairs/vets-api/pu …
=> Removed index_vba_docs_upload_submissions_status_created_at index

modules/simple_forms_api/app/models/simple_forms_api/vba_40_10007.rb
Made updates to the 40-10007 overflow page, to prevent data line breaks
https://jira.devops.va.gov/browse/MBMS-75199
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-Ba …
=> MBMS-75199 Updated overflow page

db/migrate/20240925160219_create_evidence_submissions.rb, db/schema.rb
=> [CST] Added job_class to evidence_submissions table

config/features.yml
- *This work is behind a feature toggle (flipper):* Creating new feature toggle to be used on frontend
- *(Summarize the changes that have been made to the platform)*: There is currently a bug where print page for GI Bill Statement of Benefits will not load. This is do to a null error which is the result of a content-build classname update ([see PR here](https://github.com/department-of-veterans-affairs/content-build/pull/2254)). The component is looking for DOM element with classname ".va-nav-breadcrumbs' which no longer exists. Author of PR Andrew Steele instructed us to change query selector to look for 'va-breadcrums'. We will test this under this feature flag in staging because we cannot test locally.
- *(If bug, how to reproduce)* Log into the app in staging …
=> EDM/Create flipper to test updated SOB print page

Gemfile.lock
- Bump brakeman to 6.2.2
- n/a
=> Bump brakeman 6.2.2

app/controllers/v0/veteran_readiness_employment_claims_controller.rb, spec/sidekiq/vre/submit1900_job_spec.rb
- Change the loa3 attribute in the open struct to loa3? so that it responds to the later loa3? check
[- *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses Jira*](https://github.com/orgs/department-of-veterans-affairs/projects/1237/views/13?pane=issue&itemId=81646616&issue=department-of-veterans-affairs%7Cva.gov-team%7C93953)
- *Link to previous change of the …
=> fix loa3 set in open struct to respond to later loa3? check

modules/simple_forms_api/app/models/simple_forms_api/vba_40_10007.rb
Fix race field on 40-10007 pre need form
https://jira.devops.va.gov/browse/MBMS-75199
- *What is the …
=> MBMS-75199 fixed race field

app/sidekiq/benefits_intake_status_job.rb, modules/meb_api/lib/dgi/forms/service/submission_service.rb, modules/meb_api/lib/dgi/submission/service.rb
- update how we get url from the submitted form_type
=> update type to url conversion

modules/appeals_api/config/mailinglists/report_daily.yml, modules/appeals_api/config/mailinglists/report_weekly.yml
- Updated some mailing lists
- Better to PR a change than to ask someone else to do it!
- Decision Reviews, no
- *No Ticket*
- *This PR _IS_ epic, but not _AN_ epic*
- No unit tests exist for email updates
- Emails were sent to people no longer working here, people that do work here were not getting enough emails and felt left out …
=> [Decision Reviews] Update daily and weekly mailing lists for error reports

modules/simple_forms_api/docs/rfcs/0001-monitoring-s3-pdf-service.md, modules/simple_forms_api/docs/rfcs/README.md
- *This PR introduces an RFC for the monitoring strategy of the S3 PDF management service and a `README.md` for the `docs/rfcs` directory to standardize how RFCs are written, formatted, and stored.*
- *The solution provides a structured approach to monitoring the S3 PDF upload/download service, ensuring performance, reliability, and data privacy are properly managed. The `README.md` outlines guidelines for creating and managing RFCs, promoting consistency and collaboration.*
- *I work for the Veteran Facing Forms team, and this component (the RFC and supporting documentation) will be maintained by the team.*
- *Link to the ticket: [#1624 - Monitoring Plan for S3 PDF Service](https://github.com/department-of-veterans-affairs/va.gov-team-forms/issues/1624)*
- *The old behavior was the …
=> [SIMPLE_FORMS] doc: 1624 - make and implement plan for monitoring pdf download

app/models/health_care_application.rb, spec/models/health_care_application_spec.rb, spec/sidekiq/hca/std_institution_import_job_spec.rb
- Added additional specs for a logic branch in the `HealthCareApplication` model and in the `StdInstitutionImportJob`.
- Deleted an unused method (`form_id`) that was not being tested in `HealthCareApplication`. We already have that value in a const in the model and it is already uppercase. This was the only implementation change. 
10-10EZ Form
I searched for any usages of form_id and am expecting our specs to fail if there is somewhere we are using it. But if anyone knows of somewhere we use it obviously we don't want to remove it.
=> [10-10EZ] Update specs to improve test coverage

modules/meb_api/app/controllers/meb_api/v0/forms_controller.rb
Reverts to direct accessor method for claimaint_ID
Transfer of Entitlement application form
=> Use direct accessor method for claimant_id

app/models/form526_submission.rb, app/sidekiq/evss/disability_compensation_form/submit_form526.rb, lib/sidekiq/form526_job_status_tracker/job_tracker.rb, lib/sidekiq/form526_job_status_tracker/metrics.rb, spec/lib/sidekiq/form526_job_status_tracker/metrics_spec.rb, spec/sidekiq/evss/disability_compensation_form/submit_form526_all_claim_spec.rb
This PR: 
- adds in service provider as a string (either 'lighthouse' or 'evss') to the `system_transaction_id` used in logs internally and for Lighthouse's internal use. 
- adds service_provider to `with_tracking` for Rails logger and DataDog's StatsD metrics. 
- *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses Jira*  https://github.com/department-of-veterans-affairs/va.gov-team …
=> [Disability Benefits Team 1] Track service provider for Form526 Submissions 

.github/workflows/deploy_delay_notifications.yml
- Add some commit/time logging for debugging
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/91838
=> Add logs for debugging

modules/claims_api/config/initializers/okcomputer.rb
* Adds three additional endpoints to the okcomputer initializer
[API-41023](https://jira.devops.va.gov/browse/API-41023)
* Based on what forward proxies are running, navigating to http://localhost:3000/services/claims/v1/upstream_healthcheck (can also v2) should show status as either available or unavailable.
* `available`
* `unavailable` (just PDF generator)
modified:   modules/claims_api/config/initializers/okcomputer.rb
=> API-41023-add-firefly-health-checks

config/features.yml
- Adding a new feature toggle for the podiatry removal work
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/95325
-N/A since this feature will be used in vets-website
N/A
=> Add remove podiatry feature toggle

.rubocop_todo.yml, app/models/lighthouse_document.rb, app/sidekiq/lighthouse/document_upload.rb, lib/lighthouse/benefits_documents/service.rb, spec/sidekiq/evss/document_upload_spec.rb, spec/sidekiq/lighthouse/document_upload_spec.rb
Copying the exhaustion handler from the `EVSS::DocumentUpload` job to the `Lighthouse::DocumentUpload` job to provide the same functionality for both services
- department-of-veterans-affairs/va.gov-team/issues/94406
Added unit tests to ensure that the exhaustion handler is working as intended
- *Describe the steps required to verify your changes are working as …
=> [CST] Adding exhaustion handler to Lighthouse::DocumentUpload job

config/features.yml
This PR updates the `actor_type` for all IVC CHAMPVA + FMP forms from `user` to `cookie_id`. 
This is so that the user experience will be consistent for a user for the duration of a cookie within a singler browser, regardless of their logged in status. (per [this doc](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide))
- Updates actor type for IVC CHAMPVA/FMP form toggles
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/95796
- *Tests need to be written for both the flipper on and …
=> 95796 Update feature toggle actor type - IVC CHAMPVA Forms

modules/meb_api/app/controllers/meb_api/v0/forms_controller.rb
Updates wrong serializer being called in determine serializer method
https://github.com/department-of-veterans-affairs/octo_watchofficer/issues/266
My Education Benefit Transfer of Entitlement Confirmation page results
=> Updates serializer used in determine method

.github/workflows/code_checks.yml
We were seeing timeotus in CI. GitHub made 32 core runners available in the recent past (this year?) so we should go up to it for a faster test run. I'm also only going to 24 processes to make sure we don't run out of memory. This number could be bumped up potentially.
- *(Which team do you work for, does your team own the maintenance of this …
=> chore: Bump Code Checks to 32 core

config/features.yml
> This is the addition of a new feature toggle
> We will be working on new pages and content for our Supplemental Claim form. We plan to do a staged release of the new content
> Once the new content is 100% available in production, and we have validated everything is working and stable, we can remove the toggle
https://github.com/department-of-veterans-affairs/va.gov-team/issues/95167
- …
=> Add Supplemental Claim updates feature toggle

config/features.yml
Added a feature flag for the FSR Wizard
Debt Resolution
[95103](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/95103) …
=> 95103 - Add feature flag for FSR wizard

app/controllers/v0/user/mhv_user_accounts_controller.rb, spec/controllers/v0/user/mhv_user_accounts_controller_spec.rb
- Break MHV user account cache when `v0/user/mhv_user_account` is called
- Update controller to call `MHV::UserAccountCreator` directly
- https://jira.devops.va.gov/browse/VI-688
- login
- navigate to http://localhost:3000/v0/user/mhv_user_account
- You should see a `[MHV][AccountCreation][Service] create_account success` log with `from_cache: false` in the payload everytime you call it
mhv account creation
=> [VI-688] Break MHV user account cache when route called

.github/CODEOWNERS, lib/medical_records/phr_mgr/client.rb, modules/my_health/app/controllers/my_health/v1/medical_records/military_service_controller.rb, modules/my_health/config/routes.rb, spec/lib/medical_records/phr_mgr/client_spec.rb, spec/support/vcr_cassettes/phr_mgr_client/get_military_service.yml
- Created veteran military service record API for Blue Button report
https://jira.devops.va.gov/browse/MHV-63089
> Description
> Implement - Download all-DOD Military Service domain
> 
> NOTE: This story is for getting information from MHV into vets-api
> 
Unit test written for new PHR client method
no UI changes
MHV medical records
AC1  DOD Military Service domain is pulled into Vets-API
=> MHV-63089: Military service record API complete

modules/debts_api/app/sidekiq/debts_api/v0/form5655/vba_submission_job.rb, modules/debts_api/spec/sidekiq/debt_api/v0/vba_submission_job_spec.rb
We are getting Time Out errors when submitting to VBA. This adds in retrying with hopes that we can get submissions flowing through when their system can handle traffic again.
- *(Summarize the changes that have been made to the platform)*: We add retries, just 5. We also spread the retires out so we don't keep hammering their API since there are timeouts happening.
- *(What is the solution, why is this the solution?)*: The idea here is to get the form submitted without the need for manual intervention. Since the API is timing out, I thought it would be helpful to wait sometime to try again rather than the default 'exponential backoff' that Sidekiq does by resubmitting in quick succession at …
=> Debt team - 95944 Add retry for VBA submit

config/features.yml
- `mhv_secure_messaging_recipient_opt_groups` feature flag to toggle optgroups on `/my_health/secure-messages/new-message` recipient dropdown
- https://jira.devops.va.gov/browse/MHV-63946 …
=> MHV-63946 SM - Feature flag for Grouping triage groups by health care system

modules/va_notify/lib/va_notify/service.rb, modules/va_notify/spec/lib/service_spec.rb, spec/support/vcr_cassettes/va_notify/success_email.yml, spec/support/vcr_cassettes/va_notify/success_sms.yml
- *(Summarize the changes that have been made to the platform)*: Updates logic (behind feature flag) to how we are fetching the response data (wasn't a simple hash like we had originally coded for - the response is actually an instance of `Notifications::Client::ResponseNotification`)
- *(If …
=> VaNotify - Update notification creation logic

modules/simple_forms_api/app/services/simple_forms_api/form_remediation/docs/README.md
- Updated and expanded the Form Remediation solution documentation in the README to provide a comprehensive guide for new teams implementing this solution.
- The documentation now includes sections on batch and individual processing, extending functionality, AWS S3 setup, and a new Directory and File Structure section detailing the S3 file organization.
- This update ensures the documentation accurately reflects the current implementation, clarifies configuration options, and provides usage examples.
- My team (Veteran Facing Forms) owns the maintenance of this component.
- [Review and Update Form Remediation Solution Documentation](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/1805)
- The previous …
=> [SIMPLE-FORMS] doc: review and update form remediation solution documentation

spec/lib/va_notify/notification_email/saved_claim_spec.rb
correct unittest timeout, due to settings change
https://dsva.slack.com/archives/C0460N83Y9G/p1730479171710639
- https://github.com/department-of-veterans-affairs/vets-api/pull/19022
CI
=> CI Unittest Settings correction

modules/va_notify/app/services/va_notify/status_update.rb, modules/va_notify/lib/va_notify/service.rb, modules/va_notify/spec/lib/service_spec.rb, modules/va_notify/spec/services/status_update_spec.rb
- *(Summarize the changes that have been made to the platform)*: additional updates to our notification callback logic (behind a feature flag).
- *(Which team do you work for, does your team own the maintenance of this component?)*: VA Notify - yes, my team owns this module
- https://github.com/orgs/department-of-veterans-affairs/projects/1415/v …
=> Vanotify - callback updates

config/features.yml, modules/simple_forms_api/app/services/simple_forms_api/notification_email.rb, modules/simple_forms_api/spec/services/notification_email_spec.rb
Added flipper for 40-10007 error email and fixed first name method. 
https://jira.devops.va.gov/browse/MBMS-78696
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-Backe …
=> MBMS-78696 Added 40-10007 error email flipper to features.yml

app/controllers/v0/users_controller.rb, config/routes.rb, spec/controllers/v0/users_controller_spec.rb
We are adding a route to `users` called `credential_emails` to return all the emails associated with different credentials for a user
Identity Platform
- [Jira Ticket](https://jira.devops.va.gov/browse/VI-684)
```
credential_emails_v0_user GET  /v0/user/credential_emails(.:format) v0/users#credential_emails {:format=>"json"}
```
```
user_account = …
```
=> Add credential emails route to user

modules/mobile/app/controllers/mobile/v0/claims_and_appeals_controller.rb, modules/mobile/app/models/mobile/v0/appeal.rb, modules/mobile/docs/schemas/Appeal.yml, modules/mobile/docs/schemas/AppealIssue.yml
adds some enums not on appeals docs and changes logs to use datadog
https://github.com/department-of-veterans-affairs/va-mobile-app/issues/8145
(OPTIONAL)_What should the reviewers …
=> add appeal model enums and update logging

spec/sidekiq/lighthouse/submit_career_counseling_job_spec.rb, spec/sidekiq/vre/submit1900_job_spec.rb
- Fixed unit tests to move away from "[Time.now.in](http://time.now.in/)_time_zone('Eastern Time (US & Canada)')" to fix an issue where the wrong date was appearing when the unit tests ran on master.
- …
=> fix timezone issue with spec tests causing failures on master

modules/claims_api/app/controllers/concerns/claims_api/disability_compensation_validations.rb, modules/claims_api/spec/requests/v1/forms/526_spec.rb
- Reverts/rolls back https://jira.devops.va.gov/browse/API-41802
=> Reverts previous work

.github/workflows/deploy_delay_notifications.yml
- Still not properly working, and perhaps it's because of the indentation (according to Claude).
=> Fix notification Indentation

.github/workflows/deploy_delay_notifications.yml
- Trying again. It sadly doesn't like the multiline text.
=> Remove Indentation from Deploy Delay workflow

modules/simple_forms_api/app/services/simple_forms_api/notification_email.rb, modules/simple_forms_api/spec/services/notification_email_spec.rb
Updated first name method to add correct first name to email
[
](https://jira.devops.va.gov/browse/MBMS-78696)
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-Backende …
=> MBMS-78696 Updated First name method

modules/mobile/app/controllers/mobile/v0/observations_controller.rb, modules/mobile/app/models/mobile/v0/adapters/observation.rb, modules/mobile/app/models/mobile/v0/observation.rb, modules/mobile/spec/requests/mobile/v0/health/observations_spec.rb
expanded observation to be more strict 
https://github.com/department-of-veterans-affairs/va-mobile-app/issues/8149 …
=> add model to observation on mobile

app/models/concerns/form526_claim_fast_tracking_concern.rb
Related to [this issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/95942) which was that user accounts associated to some submissions were missing an ICN. We put in [this code](https://github.com/department-of-veterans-affairs/vets-api/pull/19230) to fix it at the LH submission call. However, today [some "fast track" submissions](https://vagov.ddog-gov.com/logs?query=%22ICN%20not%20found%20on%20submission%22&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&graphType=flamegraph&messageDisplay=inline&refresh_mode=paused&sort=time&storage=hot&stream_sort=desc&viz=stream&from_ts=1730885520000&to_ts=1730935920000&live=false) came in that pointed to the need to update a precursor LH API call to benefits claims.
- *This work is behind a …
=> Update open_claims call to use new ICN lookup

modules/debts_api/app/sidekiq/debts_api/v0/form5655/vha/sharepoint_submission_job.rb, modules/debts_api/spec/sidekiq/debt_api/v0/vha/sharepoint_submission_job_spec.rb
In an effort to get submission success rates higher for the 5655 form, I am increasing the retry amount and spreading out the retry timing.
Check out the graph below. You will see the sharepoint errors. There are 503's, and connection pool errors. The hope is we get passed these without having to intervene manually.
- *(Summarize the changes that have been made to the platform)*: We are adding retries and spreading them out for the Sharepoint submission job
- *(What is the solution, why is this the solution?)*: I think this is a good solution since this API can be finicky. I'll be adding more PR's like this for our submission jobs to hopefully gain reliability.
- *(Which team do you work …
=> Debt team spread out Sharepoint job retry submissions

modules/debts_api/app/models/debts_api/v0/form5655_submission.rb, modules/debts_api/spec/models/debt_api/v0/form5655_submission_spec.rb, modules/debts_api/spec/sidekiq/debt_api/v0/vha/sharepoint_submission_job_spec.rb, modules/debts_api/spec/sidekiq/debt_api/v0/vha/vbs_submission_job_spec.rb
[OCTO has mandated a convention to log silent errors](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/logging-silent-failures.md). We need to add this to our system to get within guidelines
Link to slack announcement:
https://dsva.slack.com/archives/CPE4AJ6Q0/p1729114032588019
- *(Summarize the changes that have been made to the platform)*: This adds tagging for silent failures
- You can find me on the debts team at #debt-resolution on Slack
- *(If introducing a flipper, …
=> 95376 Add OCTO silent error logging

app/sidekiq/mhv/account_creator_job.rb, spec/sidekiq/mhv/account_creator_job_spec.rb
- Add unique to MHV account creator job
MHV account creation
=> Add unique to MHV account creator job

modules/ask_va_api/app/lib/ask_va_api/inquiries/payload_builder/inquiry_details.rb, modules/ask_va_api/app/lib/ask_va_api/inquiries/payload_builder/inquiry_payload.rb, modules/ask_va_api/app/lib/ask_va_api/inquiries/payload_builder/submitter_profile.rb, modules/ask_va_api/app/lib/ask_va_api/translator.rb, modules/ask_va_api/config/locales/dictionary.yml, modules/ask_va_api/config/locales/en.yml, modules/ask_va_api/config/locales/get_optionset_mock_data.json, modules/ask_va_api/spec/app/lib/ask_va_api/inquiries/payload_builder/inquiry_details_spec.rb, modules/ask_va_api/spec/app/lib/ask_va_api/translator_spec.rb, modules/ask_va_api/spec/support/shared_contexts.rb
Enhance Translation Support for Veteran and Dependent Relationships
This PR introduces key improvements and minor fixes to enhance translation accuracy across the application.
1. New dictionary.yml file:
• Added dictionary.yml to support translations for veteran_relationship and dependent_relationship.
2. Updates to en.yml and optionset_mock_data:
• Synchronized en.yml and optionset_mock_data with new translation entries.
3. Enhancements in Translator.rb:
• Updated Translator.rb to accurately translate all optionsets, ensuring alignment with the latest dictionary.yml.
4. Spec and Submitter Profile Fixes:
• Minor adjustments in specs and submitter_profile to resolve inconsistencies and improve reliability.
Notes:
These changes aim to standardize relationship translations and improve …
=> Ask va api refactor translator

app/controllers/v0/profile/address_validation_controller.rb
Bug fix. @current_user is not authenticated for post requests.
- *Tests need to be written for both the flipper …
=> Removed @current_user from Address Validation

app/sidekiq/lighthouse/submit_career_counseling_job.rb, app/sidekiq/vre/submit1900_job.rb, spec/sidekiq/lighthouse/submit_career_counseling_job_spec.rb, spec/sidekiq/vre/submit1900_job_spec.rb
- Changed date attribute to date_submitted in notify calls for ZSF emails
-VA Benefits and Claims
- *Describe the steps required to verify your changes are working as …
=> change date to date submitted

docker-compose.yml
The latest clamav docker image does not support the `linux/arm64/v8` platform. When developers attempt to pull the latest image tag, they receive the following error, `no matching manifest for linux/arm64/v8 in the manifest list entries`. [Support slack thread](https://dsva.slack.com/archives/CBU0KDSB1/p1731085474624069). …
=> Set clamav image tag to 1.3.0 in docker-compose to support linux/arm64/v8 platform

.github/workflows/backend-pr-labeler.yml
- Apparently you access the PR for `pull_request_review` the same way you would access a `pull_request`, despite what the internet says. But it reduces code so 👍 
- Added some more steps, but nothing that actions on anything yet.
=> Use correct pull_request structure and add in next steps

.github/workflows/backend-pr-labeler.yml
- Pull `get_pr_data` into separate step so job can terminate if job is running `on:push:master`
=> Refactor PR labeler steps

.github/workflows/backend-pr-labeler.yml
- Reference job with correct name
=> Fix get-pr-data variable name

modules/travel_pay/app/services/travel_pay/claim_association_service.rb, modules/travel_pay/spec/services/claims_association_service_spec.rb
- Added an initialize step to association module to get the required `user` object
- Removed unnecessary ['data'] property from appts array
- `@current_user` is not global (oops) and must be passed into the module for the `auth_manager` to do it's thing
- Travel Pay
- [#91972](https://app.zenhub.com/workspaces/beneficiary-travel-btsss-65147e21930cd900223d8e64/issues/gh/department-of-veterans-affairs/va.gov-team/91972)
- *Link to epic if not included in …
=> Travel Pay/Fix association module user bugs

config/features.yml
> YES
> Adding a feature toggle for our Higher-Level Review (HLR) form confirmation page changes
> Once we're released the HLR confirmation page changes to 100% of users we can remove this toggle
> https://github.com/department-of-veterans-affairs/va.gov-team/issues/95199
- *Link to previous change …
=> HLR | Add confirmation update toggle

modules/claims_api/app/controllers/claims_api/v2/veterans/power_of_attorney/request_controller.rb, modules/claims_api/app/swagger/claims_api/v2/dev/swagger.json, modules/claims_api/config/schemas/v2/power_of_attorney_requests/post.json, modules/claims_api/lib/bgs_service/manage_representative_service.rb, modules/claims_api/spec/requests/v2/power_of_attorney_requests/index/rswag_spec.rb
- add pageIndex and pageSize to POA request
- update docs (staging only)
[API-41410](https://jira.devops.va.gov/browse/API-41410)
Sent the following request:
```
curl --location 'http://localhost:3000/services/claims/v2/veterans/power-of-attorney-requests' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer *****' \
--data '{
"data": {
"poaCodes": [
"002",
"003",
"083"
],
"pageIndex": "2",
"pageSize": "2"
}
}
}'
```
Got a successful response. Tried incrementing `pageIndex` and `pageSize` and got expected results.
View POA requests (index)
See below.
=> [API-41410] View POA Requests - Pagination

app/models/saved_claim/dependency_claim.rb, app/models/saved_claim/education_career_counseling_claim.rb, app/models/saved_claim/veteran_readiness_employment_claim.rb, app/sidekiq/benefits_intake_status_job.rb, app/sidekiq/central_mail/submit_central_form686c_job.rb, app/sidekiq/lighthouse/submit_career_counseling_job.rb, app/sidekiq/vre/submit1900_job.rb, spec/sidekiq/central_mail/submit_central_form686c_job_spec.rb
- *This work is behind a feature toggle (flipper): Partially*
-Added failure email calls to the benefits intake status check. Refactored failure email calls into their own methods to be called other places in the app.
[- *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses Jira*](https://github.com/department-of-veterans-affairs/va.gov-team/issues/96802#event-15226529 …
=> Ndbex 96802 post lh failure emails

app/sidekiq/benefits_intake_status_job.rb
=> BenefitsIntakeStatusJob monitor_failure bug

app/controllers/v0/profile/address_validation_controller.rb, lib/va_profile/military_personnel/service.rb, modules/mobile/spec/requests/mobile/v0/user/phones_spec.rb, modules/mobile/spec/services/sync_update_service_spec.rb, modules/veteran/spec/sidekiq/representatives/update_spec.rb, spec/lib/common/models/concerns/cache_aside_spec.rb, spec/lib/debt_management_center/statement_identifier_service_spec.rb, spec/lib/va_profile/v2/contact_information/service_spec.rb, spec/lib/va_profile/v2/contact_information/transaction_response_spec.rb, spec/lib/va_profile/v2/person/service_spec.rb, spec/lib/va_profile/v3/address_validation/service_spec.rb, spec/models/async_transaction/va_profile/base_spec.rb, spec/models/async_transaction/vet360/base_spec.rb, spec/models/va_profile_redis/v2/cache_spec.rb, spec/models/va_profile_redis/v2/contact_information_spec.rb, spec/requests/swagger_spec.rb, spec/requests/v0/profile/addresses_spec.rb, spec/requests/v0/profile/email_addresses_spec.rb, spec/requests/v0/profile/persons_spec.rb, spec/requests/v0/profile/telephones_spec.rb, spec/requests/v0/profile/transactions_spec.rb, spec/support/va_profile/stub_vaprofile_user.rb
Cleaned up spec files due to a comment made in this [PR](https://github.com/department-of-veterans-affairs/vets-api/pull/18729)
- department-of-veterans-affairs/va.gov-team/issues/73776
- No new behavior added. Cleaned up spec tests
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/de …
=> Cleaned up Contact Information Flipper in specs

lib/va_profile/military_personnel/service.rb, modules/mobile/spec/requests/mobile/v0/user/phones_spec.rb, modules/mobile/spec/services/sync_update_service_spec.rb, modules/veteran/spec/sidekiq/representatives/update_spec.rb, spec/lib/common/models/concerns/cache_aside_spec.rb, spec/lib/debt_management_center/statement_identifier_service_spec.rb, spec/lib/va_profile/v2/contact_information/service_spec.rb, spec/lib/va_profile/v2/contact_information/transaction_response_spec.rb, spec/lib/va_profile/v2/person/service_spec.rb, spec/lib/va_profile/v3/address_validation/service_spec.rb, spec/models/async_transaction/va_profile/base_spec.rb, spec/models/async_transaction/vet360/base_spec.rb, spec/models/va_profile_redis/v2/cache_spec.rb, spec/models/va_profile_redis/v2/contact_information_spec.rb, spec/requests/swagger_spec.rb, spec/requests/v0/profile/addresses_spec.rb, spec/requests/v0/profile/email_addresses_spec.rb, spec/requests/v0/profile/persons_spec.rb, spec/requests/v0/profile/telephones_spec.rb, spec/requests/v0/profile/transactions_spec.rb, spec/support/va_profile/stub_vaprofile_user.rb
Reverts department-of-veterans-affairs/vets-api#19336
=> Revert "Cleaned up Contact Information Flipper in specs"

config/features.yml
This PR adds a `my_va_form_submission_pdf_link` feature flag 
- Ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/89250
(OPTIONAL)_What should the …
=> My VA - create feature flag for PDF link

app/sidekiq/benefits_intake_status_job.rb
- fixed submit_failure_email to send_failure_email
- [*Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses Jira*](https://github.com/department-of-veterans-affairs/va.gov-team/issues/97232#event-15314637782)
- *Describe what the old behavior was prior to the …
=> fix submit to send

config/features.yml
> YES
> Adding a feature toggle for our Higher-Level Review (HLR) form confirmation page changes
> Once we're released the Supplemental Claim confirmation page changes to 100% of users we can remove this toggle
> https://github.com/department-of-veterans-affairs/va.gov-team/issues/96883
- *Link to …
=> SC | Add confirmation update toggle

app/controllers/v0/veteran_readiness_employment_claims_controller.rb, spec/models/saved_claim/veteran_readiness_employment_claim_spec.rb
- Add first name to the user struct so that the va notify email can go out properly
- Added the first name and updated the unit tests to catch a similar issue in the future
[- *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses Jira*](https://github.com/department-of-veterans-affairs/va.gov-team/issues/97353) …
=> add first name to user struct, update tests to catch problem

db/migrate/20241119134025_add_index_to_form526_submissions.rb, db/schema.rb
PgHero suggests an index for `backup_submitted_claim_id` on the `form526_submissions ` table. This was noticed while investigating [PgQuery duration times that spike overnight](https://vagov.ddog-gov.com/monitors/199084?eval_ts=1732021756314&from_ts=1731938679391&to_ts=1732021756314). 
https://github.com/orgs/department-of-veterans-affairs/projects/1335/views/1?filterQuery=assignee%3ALindseySaari&pane=issue&itemId=85926689&issue=department-of-veterans-affairs%7Cva.gov-team%7C96409
- *Describe the …
=> Add form 526 submssion index

modules/simple_forms_api/app/services/simple_forms_api/form_remediation/file_utilities.rb
=> [SIMPLE-FORMS] fix: update file processing logic to avoid thread safety concerns

modules/debts_api/app/controllers/debts_api/v0/financial_status_reports_controller.rb
- *(Summarize the changes that have been made to the platform)*: We didn't have some important form parameters defined in our strong parameters. This adds them so that the PDF prints the values
- *(If bug, how to reproduce)*: We submitted the form before and after the change. Data is showing up now 💪🏻 
- *(What is the solution, why is this the solution?)*: Just add the params to the permit method in the controller
- *(Which team do you work for, does your team own the maintenance of this component?)*: Debt Resolution. You can find me on the Octo slack at #debt-resolution
- *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket …
=> Debt team 5655 box3 missing

app/models/prescription.rb, modules/my_health/app/controllers/my_health/v1/prescriptions_controller.rb, modules/my_health/app/helpers/my_health/prescription_helper.rb, modules/my_health/spec/requests/my_health/v1/prescriptions_spec.rb, spec/support/schemas/my_health/prescriptions/v1/prescription_list_filtered.json, spec/support/schemas/my_health/prescriptions/v1/prescription_list_filtered_with_pagination.json, spec/support/schemas/my_health/prescriptions/v1/prescriptions_list.json, spec/support/schemas/my_health/prescriptions/v1/prescriptions_list_paginated.json, spec/support/schemas_camelized/my_health/prescriptions/v1/prescription_list_filtered.json, spec/support/schemas_camelized/my_health/prescriptions/v1/prescriptions_list.json, spec/support/schemas_camelized/my_health/prescriptions/v1/prescriptions_list_paginated.json, spec/support/vcr_cassettes/rx_client/prescriptions/index_with_disp_status_filter.yml
- Adds a count object to the metadata returned from the API
- https://jira.devops.va.gov/browse/MHV-64025
- Added test
N/A
MHV medications app
=> MHV-64025-list-count-per-filter

modules/va_notify/app/sidekiq/va_notify/email_job.rb, modules/va_notify/app/sidekiq/va_notify/user_account_job.rb, modules/va_notify/lib/va_notify/service.rb, modules/va_notify/spec/sidekiq/email_job_spec.rb, modules/va_notify/spec/sidekiq/user_account_job_spec.rb
- *(Summarize the changes that have been made to the platform)*: 
- Updates our email and user account sidekiq jobs to return the response object instead of `true` that came from the incrementing StatsD. This doesn't change the behavior of normal sidekiq invocations (with `perform_async`) but is useful if you are debugging jobs on the command line and calling them manually (with `perform_inline` or `new.perform`)
- Adds another location to skip when looking up the caller location.
- *(If bug, how to …
=> VaNotify - caller location logic

modules/meb_api/app/controllers/meb_api/v0/forms_controller.rb
- form_type was not being properly assigned
=> update form_type assignment

modules/mobile/app/controllers/mobile/v0/maintenance_windows_controller.rb, modules/mobile/docs/openapi.json, modules/mobile/docs/schemas/MaintenanceWindows.yml, modules/mobile/spec/requests/mobile/v0/maintenance_windows_spec.rb
add efolder window 
https://github.com/department-of-veterans-affairs/va-mobile-app/issues/10190
(OPTIONAL)_What should the reviewers know in addition to the above. Is there …
=> add efolder window

app/models/saved_claim/dependency_claim.rb, app/models/saved_claim/education_career_counseling_claim.rb, app/models/saved_claim/veteran_readiness_employment_claim.rb, app/sidekiq/benefits_intake_status_job.rb, app/sidekiq/central_mail/submit_central_form686c_job.rb, app/sidekiq/lighthouse/submit_career_counseling_job.rb, app/sidekiq/vre/submit1900_job.rb, lib/dependents/monitor.rb, lib/pcpg/monitor.rb, lib/vre/monitor.rb, spec/lib/dependents/monitor_spec.rb, spec/lib/pcpg/monitor_spec.rb, spec/lib/vre/monitor_spec.rb, spec/sidekiq/central_mail/submit_central_form686c_job_spec.rb, spec/sidekiq/lighthouse/submit_career_counseling_job_spec.rb, spec/sidekiq/vre/submit1900_job_spec.rb
- Reworked the silent failure calls so that there is a call to silent failure avoided in the exhaustion scenarios in the sidekiq jobs
- Alter the monitor to check for the email and decide which notification to create. pass only the email to the email calls. refactor where necessary.
- [*Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses …
=> Ndbex silent failure updates

modules/va_notify/app/controllers/va_notify/callbacks_controller.rb
- *(Summarize the changes that have been made to the platform)* Removes unnecessary logging
https://github.com/department-of-veterans-affairs/vanotify-team/issues/1411
- *Describe what the old behavior was prior to …
=> VaNotify - Remove logging

config/features.yml
Create initial feature toggle for Dispute Debt.
https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/96916
Features
- [ X ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ X ]  No error nor warning in the console.
- [ X ]  Events are being sent to the appropriate logging solution
- [ X ]  Documentation has been updated (link to documentation)
- [ X ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ X ]  Feature/bug has a monitor built into Datadog (if applicable)
- [ X ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ X ]  I …
=> 96916 - [DD] Create Dispute Debt feature toggle

config/features.yml
- adding `mhv_secure_messaging_recipient_combobox` feature flag
- flag to be used in `vets-website` to enable/disable combobox dropdown on `/my-health/new-message`
- [MHV-62755](https://jira.devops.va.gov/browse/MHV-62755) …
=> MHV-62755 SM combobox feature flag

app/models/form526_submission.rb, app/sidekiq/form526_confirmation_email_job.rb, spec/sidekiq/form526_confirmation_email_job_spec.rb
This PR adds the `date_received` parameter to the Received Email template, which is populated with the current timestamp.
- Disability Benefits Experience Team 1 (DBEX-TREX 🦖)
[#96487](https://github.com/department-of-veterans-affairs/va.gov-team/issues/96487)
- *Link to …
=> Update Received email va-notify template with date_received

lib/periodic_jobs.rb
This moves the KMS job back to the 1am window where it originally was set to run ([PR to adjust to the 5am window](https://github.com/department-of-veterans-affairs/vets-api/pull/19162)). We have mitigated issues with corrupted records and the query duration issues are no longer affected by the KMS rotation job. Again, our monitoring and alerts continue to fire, but it's no longer related to the KMS job.
[This notebook](https://vagov.ddog-gov.com/notebook/15171/postgres-query-duration-investigation) points to the current problem queries. 
I’d like to move …
=> Move KMS job back to 1am window

modules/claims_api/spec/requests/v1/forms/rswag_2122_spec.rb
* Adjustments made to fix failing tests
* [API-28113](https://jira.devops.va.gov/browse/API-28113)
* Introducing PR: [API-42279-find-by-ssn-poa-controller (](https://github.com/department-of-veterans-affairs/vets-api/commit/238bf3a6b6eb01b8adbada9f55e577d8f0fbcf36)https://github.com/department-of-veterans-affairs/vets-api/pull/19520[)](https://github.com/department-of-veterans-affairs/vets-api/commit/238bf3a6b6eb01b8adbada9f55e577d8f0fbcf36)
- Adjusted existing tests so they pass
modules/claims_api/spec/requests/v1/forms/rswag_2122_spec.rb)
=> FIX-api-42279-poa-rswag-tests-failures

config/features.yml, modules/ivc_champva/app/controllers/ivc_champva/v1/uploads_controller.rb, modules/ivc_champva/spec/requests/ivc_champva/v1/forms/uploads_spec.rb
This PR removes the flipper for :
https://github.com/department-of-veterans-affairs/vets-api/pull/19006
https://github.com/department-of-veterans-affairs/vets-api/pull/19006
IVC champva forms only
=> reverse flipper champva_file_recreate

lib/disability_compensation/responses/intake_sites_response.rb
- we were sending an integer for location code
- front end saves as an integer
- saved_claim validation is expecting a string
- 🤕 
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature- …
=> dbex/brd migration: turn separation location code into a string

config/settings.yml, modules/vaos/app/services/eps/appointment_service.rb, modules/vaos/app/services/eps/configuration.rb, modules/vaos/spec/services/eps/appointment_service_spec.rb
- *EPS Get Appointment API integration for Community care referral appointment scheduling*
- *https://github.com/department-of-veterans-affairs/va.gov-team/issues/96411*
NA
=> 96411 EPS Get Appointments Implementation

.github/workflows/ready_for_review.yml
- Add a step ID that was being referenced but didn't exist. oops
=> [VETS-API] Add CI backend step id

modules/travel_pay/app/controllers/travel_pay/application_controller.rb
Masks referer value with scrubbed path to hide potential PII
Closes department-of-veterans-affairs/va.gov-team#93791
Only logging, sometimes, in Travel Pay
=> masks claim ID in referer named_tag

modules/ivc_champva/app/services/ivc_champva/attachments.rb
This PR sorts the list of new file attachment paths by date created. Main goal is to reduce variables that might lead to misaligned file/doctype mappings.
- Sorted list of file paths by date file uploaded
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/96358 …
=> Ensure file path array is sorted by date of upload

app/sidekiq/central_mail/submit_central_form686c_job.rb
- In the backup submission for 686c/674 I added an assignment to the outer layer of the parsed_form hash if the veteran_information hash wasn't present inside of dependents_application.
- This is the solution because in some rare instances there is no veteran_information inside of dependents_application, but there will be a profile populated veteran_information hash in the outer layer.
[- *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses …
=> fix for missing veteran information in some backup jobs

.github/CODEOWNERS, app/controllers/v0/my_va/submission_pdf_urls_controller.rb, app/services/submission_pdf_url_service.rb, config/routes.rb, spec/requests/v0/my_va/submission_pdf_urls_spec.rb
- *This work is behind a feature toggle (flipper)*: YES (`my_va_form_submission_pdf_link`)
- Adds a new endpoint for My VA to support PDF download links on "Form Status Cards"
- New endpoint provided (`/v0/my_va/submission_pdf_urls`) accepts a "Form ID" and "Submission GUID" and returns a new, presigned url to the PDF file on S3.
- Team: Auth Exp
- Endpoint will remain behind a feature toggle until we can test with VFF team to ensure PDF links are functioning as expected on Stage and Prod.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/97541
- This is new functionality for My VA, utilizing work done by VFF team to support PDF backups for forms
- This will need to be tested on Stage with test accounts in coordination with the VFF team.  They will control the …
=> My VA | Adds new endpoint to fetch archived form PDF files from My VA

app/sidekiq/benefits_intake_remediation_status_job.rb
correct recurring error in remediation status job
[PBP | BenefitsIntakeRemediationStatusJob error](https://github.com/department-of-veterans-affairs/va.gov-team/issues/98094)
- job would error if empty saved_claim_id
- ran job locally
any form submitting to BenefitsIntake and using FormSubmission
=> PBP 98094 Remediation Status Job error

lib/form1010_ezr/service.rb, spec/lib/form1010_ezr/service_spec.rb
Adds an incrementor for successful EZR submissions that include at least one attachment.
No bugs
N/A
10-10EZR (10-10 health apps)
- https://github.com/orgs/department-of-veterans-affairs/projects …
=> [#94293][10-10][EZR]: Add StatsD incrementor for successful submissions with at least one attachment

modules/va_notify/lib/va_notify/service.rb, modules/va_notify/spec/lib/service_spec.rb
- *(Summarize the changes that have been made to the platform)* Adds logging to help us track down why metadata isn't being saved like we expect
https://github.com/department-of-veterans-affairs/vanotify-team/issues/1 …
=> VaNotify - Metadata logging

db/migrate/20241204174327_create_power_of_attorney_requests.rb, db/migrate/20241204222335_add_power_of_attorney_id_index_to_claims_api_power_of_attorney_requests.rb, db/schema.rb
Create the Claims API Power of Attorney Requests table.
- [API-43011](https://jira.devops.va.gov/browse/API-43011)
- Ran migration locally.
N/A
Database schema
~~Unsure what column type we want for metadata (using string for now).~~ we want jsonb
=> [API-43011] Create POA requests table

lib/medical_records/bb_internal/client.rb, modules/my_health/docs/openapi.yaml, modules/my_health/docs/openapi_merged.yaml, spec/lib/medical_records/bb_internal/client_spec.rb
- The two controller actions are:
- ImagingController.request_download
- ImagingController.images
- Update URL for imaging APIs to remove PII. We have two API endpoints that take "studyId" as a parameter. Study ID is a universal ID and therefore constitutes PII, so we need to remove it from our URLs.
- on `list_imaging_studies` need to ensure that `studyId` values are transformed to `uuid`, mapped and stored in cache so that `request_study` and `list_images` can do a lookup by uuid in cached map, retrieve a real `studyId` value and send request to the …
=> MHV-64150 MR: Update URL for imaging APIs to remove PII

modules/va_notify/lib/va_notify/service.rb
- *(Summarize the changes that have been made to the platform)* Updates the list of ignored caller locations (for tracking where a notification was triggered from) …
=> VaNotify - Add another ignored file path

config/initializers/flipper.rb, spec/rails_helper.rb
- Added `Rails.application.config.after_initialize` hook for flipper feature values 
- Required should in `rails_helper.rb`
=> bump Rails 7.2.2 - fix flipper feature default values

app/models/concerns/form526_claim_fast_tracking_concern.rb
- use submission.user_uuid for Flipper flag actor checking
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/97336
n/a
=> DBEX/97336: use submission.user_uuid for Flipper flag actor checking

lib/va_profile/configuration.rb, lib/va_profile/models/v3/validation_address.rb, lib/va_profile/v3/address_validation/address_suggestions_response.rb, lib/va_profile/v3/address_validation/service.rb
Can no longer test users Contact Information due to local MVI issues. Adding logs to the new service to help debug in staging. THIS WILL NOT BE LOGGED IN PROD
- department-of-veterans-affairs/va.gov-team/issues/98561 …
=> Added logs for AddressValidationV3

config/features.yml, modules/mobile/app/helpers/mobile/appointments_cache_interface.rb, modules/mobile/spec/requests/mobile/v0/appointments/vaos_v2_spec.rb, modules/vaos/app/services/vaos/v2/appointment_provider_name.rb, spec/support/vcr_cassettes/mobile/appointments/VAOS_v2/get_appointments_with_mixed_provider_types_bad_id.yml
getting error `URI::InvalidURIError: bad URI(is not URI?): "/ppms/v1/providers/1831690858 - Provider not in primary care clinic"`
this logging should help figure out where that is coming from and stop it from raising error on the whole call
https://github.com/department-of-veterans-affairs/va-mobile-app/issues/10316
- *What is the …
=> fix and log provider id issue

lib/va_profile/v3/address_validation/configuration.rb, lib/va_profile/v3/address_validation/service.rb, spec/support/vcr.rb, spec/support/vcr_cassettes/va_profile/v3/address_validation/candidate_multiple_matches.yml, spec/support/vcr_cassettes/va_profile/v3/address_validation/candidate_no_match.yml
Added another log and changed the AddressValidation URL to AddressValidation hostname.
- department-of-veterans-affairs/va.gov-team/issues/98561
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles- …
=> Updated AddressValidation# url with hostname

config/features.yml, modules/ivc_champva/app/controllers/ivc_champva/v1/uploads_controller.rb, modules/ivc_champva/spec/requests/ivc_champva/v1/forms/uploads_spec.rb
Reverts department-of-veterans-affairs/vets-api#19739
There are flaky tests in this PR ([see this issue](https://github.com/department-of-veterans-affairs/vets-api/pull/19830)), so reverting until they can be fixed.
=> Revert "recreate missing files"

.github/CODEOWNERS, app/models/form_profile.rb, app/models/form_profiles/dispute_debt.rb, config/form_profile_mappings/DISPUTE-DEBT.yml, config/settings.yml, spec/models/form_profile_spec.rb
Initial commit for prefill for new form dispute debt
- YES
- New prefill has been added for new app dispute debt
- debt resolution team (#debt-resolution channel on slack)
- Initial ticket (FE focused)
department-of-veterans-affairs/va.gov-team#97002
- BE ticket specifically for prefill (and this PR)
department-of-veterans-affairs/va.gov-team/issues/98021
- Sister PR in vets-website for new app …
=> [DD] Initial prefill for digital dispute

rakelib/post911_sob.rake
Add missing 'puts' to rake task created in https://github.com/department-of-veterans-affairs/vets-api/pull/19582
=> EDM-372/fix-sob-rake-task

config/features.yml
This PR introduces a new feature toggle, `benefits_non_disability_ch31_v2`, for the purpose of separating development on the Veteran Readiness and Employment  (Chapter 31) form.  Updates in …
=> VA-IIR: add feature toggle for VR&E (Ch31) Form

modules/vaos/app/services/eps/appointment_service.rb, modules/vaos/spec/services/eps/appointment_service_spec.rb
- *Create draft appointment implementation*
- *https://github.com/orgs/department-of-veterans-affairs/projects/1323/views/12?pane=issue&itemId=85928973&issue=department-of-veterans-affairs%7Cva.gov-team%7C96413*
NA
=> 96413 EPS create draft appointment implementation

modules/va_notify/lib/va_notify/service.rb, modules/va_notify/spec/lib/service_spec.rb
- *(Summarize the changes that have been made to the platform)* When our `VANotify::Service` class is used directly and symbols are used as keys for `callback_options` it works as expected, however when `callback_options` are passed into a sidekiq job and THEN into the service class the hash keys are converted to strings because sidekiq serializes it's args. This was causing us to not track `callback_options` correctly (because we were looking for symbols and not strings). …
=> VaNotify - Callback options update

Gemfile.lock
- NO
- Getting everything up to date with latest `vets-json-schema`
- ~~*(If bug, how to reproduce)*~~
- ~~*(What is the solution, why is this the solution?)*~~
- debt-resolution, probably not
- ~~*(If introducing a flipper, what is the success criteria being targeted?)*~~
- `vets-json-schema` update
department-of-veterans-affairs/vets-json-schema/pull/966
- `vets-website` update/test branch
department-of-veterans-affairs/vets-website/pull/33495
- *Describe the steps required to verify your changes are working as expected. …
=> Updating to latest vets-json-schema

db/migrate/20241212101623_add_claim_va_notifications_reference_columns.rb, db/schema.rb
db change
[PBP ZSF email webhook generic class](https://github.com/department-of-veterans-affairs/va.gov-team/issues/98508)
ran migration locally
=> PBP 98508 ClaimVANotifiction Reference Columns

modules/claims_api/app/swagger/claims_api/description/v2.md, modules/claims_api/app/swagger/claims_api/v2/dev/swagger.json, modules/claims_api/app/swagger/claims_api/v2/production/swagger.json
- Quick fix for endpoint text.
[API-43264](https://jira.devops.va.gov/browse/API-43264)
- Fixes endpoint text for 526/synchronous to include the text 'synchronous' in the link
Benefits Claims API OAS documentation
=> API-43264 Fix endpoint, add generated swagger

config/features.yml
-Added feature toggle for updated gi design 
As a...
VEBT Developer
I want…
To build the CT homepage redesign initial page
So that…
FE CT redesign work can start
Acceptance Criteria
Header …
=> vebt-889 added feature toggle for updated gi

config/features.yml
-Added feature toggle "show_rudisill_1995" for 1995 rudisill review question
VEBT Business User
I want…
to request a Rudisill review
So that…
I can understand benefits available
Acceptance …
=> vebt-179 rudsill review feature toggle

app/controllers/v1/sessions_controller.rb
- This PR adds a operation value that a user can pass in for a SSOe authentication with mhv test account auth flow
=> Adding MHV test account operation value

lib/source_app_middleware.rb
- Alert: https://dsva.slack.com/archives/C30LCU8S3/p1734930160851979
- [Direct dd link ](https://vagov.ddog-gov.com/monitors/200229?eval_ts=1734930369000&event_id=7896486861057110384&link_source=monitor_notif&from_ts=1734929169000&to_ts=1734930369000)
- This is the `sign-in-changes` app: https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/sign-in-changes
=> Add `sign-in-changes` to source_app_middleware

config/settings.yml, modules/covid_vaccine/app/services/covid_vaccine/v0/enrollment_upload_service.rb, modules/covid_vaccine/spec/services/covid_vaccine/v0/enrollment_upload_service_spec.rb
We are experiencing connection timeouts and failures with SFTP when attempting to connect to the enrollment service from the fwdproxy. The Enrollment Service uses deprecated/unsupported SSH algorithms. Specifically, the server requires older key exchange (KEX) algorithms and host key algorithms, such as diffie-hellman-group1-sha1 and ssh-rsa, which are not included by default in modern SSH configurations. There is also issue with the NLB vs ALB, where NLB (handles raw TCP streams) to an ALB (handles Layer 7 HTTP traffic), which happened during the fwdproxy …
=> Add host and key algorithms for Enrollment Service

README.md
This will be reverted. Reproducing the error found in this [PR](https://github.com/department-of-veterans-affairs/vets-api/pull/20036)
- *If this …
=> Removed spacing in README

spec/uploaders/simple_forms_api/form_remediation/uploader_spec.rb
- Flaky on master/other PRs
- Reproducible locally with `rspec ./spec/uploaders/simple_forms_api/form_remediation/uploader_spec.rb --seed 18109`
=> Skip flaky uploader_spec.rb spec

Gemfile.lock
- Bump brakeman 6.2.2 -> 7.0.0
=> Bump brakeman 6.2.2 -> 7.0.0

config/features.yml
Added feature flag to be used in sob to connect to lighthouse service instead of evss.
https://jira.devops.va.gov/browse/EDM-455
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretog …
=> edm-455 add feature flag for sob

modules/va_notify/app/models/va_notify/notification.rb
- *(Summarize the changes that have been made to the platform)* Add lockbox encryption to the "to" field on notification callbacks
- *(If bug, how to reproduce) N/A
- *(Which team do you work for, does your team own the maintenance of this component?) VA Notify
https://github.com/orgs/department-of-veterans-affairs/projects/1415/views/1?pane=issue&itemId=88343529&issue=depart …
=> #1429: update notificaiton model for encrypted field

modules/va_notify/README.md
Added some clarifying language to modules/va_notify/README.md
- *(What is the solution, why is this the solution?)* Provides clarity in documentation
- *(Which team do you work for, does your team own the maintenance of this component?)* VANotify
N/A; this is in response to a user question …
=> Update VANotify README to clarify callback metadata inclusion with Service

config/features.yml
Add a feature toggle for content updates for Burial Benefits(21P-530)
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/99351
Burial Benefits 21P-530EZ
(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything …
=> Add feature toggle for Burials

spec/uploaders/evss_claim_document_uploader_spec.rb
This PR improves the tests around the `EVSSClaimDocumentUploader` by adding and updating tests to include unique test data through the use of `SecureRandom.uuid` to prevent race conditions and flaky tests. This also adds cleanup of tp files to prevent interference during parallel test runs. 
Since we run tests in CI in parallel using the `parallel_rspec` gem, the test execution order is not guaranteed, which can result in race conditions. This occurs because tests may unintentionally share resources, (such as temporary files in this case) leading to …
=> Update tests with unique data to prevent race conditions

app/controllers/concerns/vet360/writeable.rb, app/models/va_profile_redis/v2/cache.rb, app/models/va_profile_redis/v2/contact_information.rb, lib/va_profile/configuration.rb, lib/va_profile/v2/contact_information/service.rb, modules/mobile/spec/requests/mobile/v0/community_care_providers_spec.rb, spec/models/va_profile_redis/v2/cache_spec.rb, spec/models/va_profile_redis/v2/contact_information_spec.rb, spec/requests/v0/profile/email_addresses_spec.rb
All verified users have an ICN and the ICN is required to make requests to VAProfile::ContactInformation::V2. MPI also uses the user's ICN for cacheing. At the moment, MPI contact info cache is refreshed every 24 hours. In the future CIV2 refactor, the MPI contact info cache will also be updated when users update their contact info. 
From Identity:  User verifies with another credential (for example, [login.gov](http://login.gov/)), logs in for the first time. MPI first creates a new verified record for initial login, and then later (some seconds later), …
=> Cache Contact Information V2 with user's ICN instead of UUID.

app/sidekiq/benefits_intake_status_job.rb, config/settings.yml, lib/va_notify/notification_email/saved_claim.rb
- Added an email trigger for the new Pension application received email template. This email should be triggered when the benefits_intake status changes to `vbms`.
- Pension Burial Benefits team to own this work.
- [*Link to ticket created in va.gov-team repo*](https://github.com/department-of-veterans-affairs/va.gov-team/issues/94112)
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/fea …
=> Added logic to send new application received email for pensions

config/features.yml
… application
- This adds a feature flag to be used at a later time.  This feature flag will be used to monitor and incrementally increase traffic to the migrated contention classification API.  
- The current contention classification application is hosted in VRO and as this service is set to be decommissioned, the application will be migrated to the VA.gov infrastructure.  This feature will be used to route a percentage of user's claims to the new migrated endpoint after the migration is completed. …
=> Adds Feature Flag for Migration of Contention Classifier

modules/debts_api/app/controllers/debts_api/v0/financial_status_reports_controller.rb
- *(Summarize the changes that have been made to the platform)*:
- We are missing the `current_ar` attribute being sent from the frontend. This attribute is used to determine the type of FSR form being submitted.
- *(If bug, how to reproduce)*: Submit form, add a pry and check strong parameters. We can see current_ar is not present. We also check the code that uses current_ar and it is not getting the current_ar data.
- *(What is the solution, why is this the solution?)*: We can see the data coming in with this parameter added.
- *(Which team do you work for, does your team own the maintenance of this component?)*: Debt resolution. You can find me on the Octo slack in the channel #debt-resolution
- *(If introducing a flipper, …
=> 99889 BUG Debt team streamline eligible

app/services/mhv/user_account/errors.rb, spec/controllers/v0/user/mhv_user_accounts_controller_spec.rb, spec/services/mhv/user_account/creator_spec.rb
- Fix MHV user account MHVClientError response body
- https://jira.devops.va.gov/browse/VI-961
MHV account creation
=> [VI-961] fix MHV user account error body

modules/travel_pay/app/controllers/travel_pay/v0/claims_controller.rb, modules/travel_pay/spec/requests/travel_pay/claims_spec.rb
Adds logging and fixes a "not found" edge case
https://github.com/department-of-veterans-affairs/va.gov-team/issues/92256
Travel Pay only
=> Add logging/exception handling to controller

modules/representation_management/app/models/representation_management/form_2122_data.rb, modules/representation_management/lib/representation_management/v0/pdf_constructor/form_2122.rb, modules/representation_management/lib/representation_management/v0/pdf_constructor/form_2122a.rb, modules/representation_management/spec/models/representation_management/form_2122_data_spec.rb
- *(Summarize the changes that have been made to the platform):* This fixes a bug where if all data was supposed to be shared with a representative the PDF would check every box indicating to restrict that information.
- *(If bug, how to reproduce):* Use staging or production (only letting 5% of traffic through) to go through the 2122 form fill experience, check the radio button to share everything with the rep, and download the PDF.  All the restriction checkboxes should be filled.
- *(What is the …
=> 2122 PDF generation only check boxes when specified

modules/accredited_representative_portal/app/models/accredited_representative_portal/power_of_attorney_form.rb, modules/accredited_representative_portal/app/models/accredited_representative_portal/power_of_attorney_request.rb, modules/accredited_representative_portal/app/models/accredited_representative_portal/power_of_attorney_request_decision.rb, modules/accredited_representative_portal/app/models/accredited_representative_portal/power_of_attorney_request_expiration.rb, modules/accredited_representative_portal/app/models/accredited_representative_portal/power_of_attorney_request_resolution.rb, modules/accredited_representative_portal/spec/factories/power_of_attorney_request.rb, modules/accredited_representative_portal/spec/factories/power_of_attorney_request_decision.rb, modules/accredited_representative_portal/spec/factories/power_of_attorney_request_resolution.rb, modules/accredited_representative_portal/spec/models/accredited_representative_portal/power_of_attorney_request_decision_spec.rb, modules/accredited_representative_portal/spec/models/accredited_representative_portal/power_of_attorney_request_spec.rb
This pull request does a minor refactor and improves the logic surrounding the POA (Power of Attorney) representative request feature. Key changes include:
- **Code Refactor:**
- Demodulize references such as AccreditedRepresentativePortal::PowerOfAttorneyRequest
- Encapsulate claimant types inside an ALL array
- Refactor resolution into a Resolving concern inside PowerOfAttorneyRequestResolution
- Update specs and factories accordingly
=> 9: [ART] POA request representative refinement

modules/claims_api/app/controllers/claims_api/v2/blueprints/power_of_attorney_request_blueprint.rb, modules/claims_api/app/controllers/claims_api/v2/veterans/power_of_attorney/request_controller.rb, modules/claims_api/app/services/claims_api/power_of_attorney_request_service/show.rb, modules/claims_api/app/swagger/claims_api/v2/dev/swagger.json, modules/claims_api/config/routes.rb, modules/claims_api/spec/controllers/v2/veterans/power_of_attorney/request_controller_spec.rb, modules/claims_api/spec/factories/power_of_attorney_request.rb, modules/claims_api/spec/requests/v2/power_of_attorney_requests/show/rswag/200.json, modules/claims_api/spec/requests/v2/power_of_attorney_requests/show/rswag/401.json, modules/claims_api/spec/requests/v2/power_of_attorney_requests/show/rswag/404.json, modules/claims_api/spec/requests/v2/power_of_attorney_requests/show/rswag_spec.rb
- Add GET /power_of_attorney_requests/:id endpoint
- Update v2 staging docs
[API-43015](https://jira.devops.va.gov/browse/API-43015)
**Testing steps**
1. Create a PowerOfAttorneyRequest with the following attributes (substitute icn or poa_code as desired):
```
{
"proc_id": "3858547",
"veteran_icn": "1012829932V238054",
"claimant_icn": null,
"poa_code": "003",
}
```
2. Send a GET request where id is the PowerOfAttorneyRequest.id from Step 1:
```
curl --location 'http://localhost:3000/services/claims/v2/veterans/power-of-attorney-requests/:id' \
--header 'Authorization: Bearer *****'
```
3. Observe correct response:
```
{
"data": {
"id": "ced50124-26c9-49f4-ba58-d4d9bd84b40d",
"type": "power-of-attorney-request",
"veteran": {
"firstName": "ANDREA",
"lastName": "MITCHELL", …
```
=> [API-43015] Add power_of_attorney_requests get endpoint

lib/source_app_middleware.rb
Another another missing source app name
- Alert: https://dsva.slack.com/archives/C30LCU8S3/p1736791061966619
- [Logs](https://vagov.ddog-gov.com/logs?query=%22Unrecognized%20value%20for%20HTTP_SOURCE_APP_NAME%20request%20header%22%20service%3Avets-api%20env%3Aeks-prod&agg_m=count&agg_m_source=base&agg_q=%40message_content%2Cservice&agg_q_source=base%2Cbase&agg_t=count&clustering_pattern_field_path=message&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=sliding&sort_m=%2C&sort_m_source=%2C&sort_t=%2C&storage=hot&stream_sort=desc&top_n=10% …
=> Add missing source app name

Dockerfile, Gemfile.lock, spec/lib/medical_records/client_spec.rb
Fixed audit fail and rspec failures
Building docker image locally
=> Fixed docker build and spec failures

modules/claims_api/app/models/claims_api/auto_established_claim.rb, modules/claims_api/app/swagger/claims_api/v1/swagger.json, modules/claims_api/config/schemas/v1/526.json, modules/claims_api/spec/models/auto_established_claim_spec.rb
In v1 526 submissions, remove non-digits from phone numbers and area codes. If the resulting phone number is invalid, add the original phone number to overflow text and delete the invalid phone number from the form data.
This change allows EVSS Docker submissions to proceed without losing any data.  
[API-43472](https://jira.devops.va.gov/browse/API-43472)
Sent request with extra digits and observed correct overflow text (see screenshot) as well as omitting the invalid phone numbers from the form itself. Also tried with valid phone numbers and verified they are present in the proper form items.
To reproduce, try sending a v1 526 POST request and checking the target veteranʼs eFolder for the PDF.
e.g.,
```
{
"data": {
"type": "form/526",
"veteran": { …
```
=> [API-43472] Handle Form526 validation for phone numbers

Gemfile.lock
This reverts commit 7df874d72bac67c51e284550a5d263e8c65191ae.
Revert this PR as it may be causing stats to not send to datadog …
=> Revert "Bump statsd-instrument from 3.9.8 to 3.9.9"

app/controllers/v0/profile/address_validation_controller.rb
Attempting to track down an issue with Address Validation. Created logs for staging to ensure the correct params are being passed. Addresses can be created in the rails console with Address Validation v3 but not in the UI now.
This will be reverted after obtaining the parameters.
N/A at the moment
- *Tests need …
=> Created AddressValidation logs for staging

db/migrate/20250114210637_add_claims_api_processes.rb, db/migrate/20250114223139_add_claims_api_processes_index.rb, db/schema.rb
- Add claims_api_processes table and columns
- Add composite index
- [API-44003](https://jira.devops.va.gov/browse/API-44003)
- Ran migration locally
N/A
db schema
Open to suggestions on table name / column types. Schema decisions made per separate discussion.
=> [API-44003] Add claims_api_processes

Gemfile, Gemfile.lock
This reverts commit ba2768dd837319da94879e45130d3a3f25509203.
Revert again... ipv6 issue …
=> Revert "Bump statsd-instrument from 3.9.8 to 3.9.9 (#20313)"

config/features.yml
We are going to release an autosuggest (combo box) feature for VA health facilities in the Facility Locator. This allows us to isolate our release to Staging for testing.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18911
=> VACMS-18911 Facility Locator autosuggest flag for staging

modules/ivc_champva/app/services/ivc_champva/file_uploader.rb
This PR updates documentation for the `IvcChampva::FileUploader` class.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/100974
- NA
NA
`IvcChampva::FileUploader` class
Any feedback on formatting or content is helpful.
=> 100974 Update documentation in file_uploader.rb - IVC CHAMPVA forms

app/sidekiq/benefits_intake_status_job.rb
=> Remove duplicate line

modules/pensions/lib/pensions/notification_email.rb, modules/pensions/spec/lib/pensions/notification_email_spec.rb
- Added the `date_received` attribute to the pension received email template personalization data hash. This date should reflect the date that lighthouse reportedly received the form submission.
- Pension and Burial Program team to own this work …
=> added date_received attribute to personalization data hash

lib/source_app_middleware.rb
- Remove the too from url and app name
- Rename ask-va-too -> ask-va
- I work on the Ask VA team
- Link to ticket here: https://github.com/orgs/department-of-veterans-affairs/projects/1033/views/11?pane=issue&itemId=88550012&issue=department-of-veterans-affairs%7Cask-va%7C1348
- …
=> AskVA-1348: Configure app url for Ask VA to remove too from name

config/features.yml
Adds a feature flag for upcoming MHV Secure Messaging work to add signature settings to the VA Personal Information page.
> Feature flag for Signature Settings
> 
> Designs not final as of 1/16/25
> 
> https://www.figma.com/design/x9YoKDPekIPiqlDiZdmjci/ZFeat---Changes-to-signature%2Fpreferences?node-id=969-5004&t=2Nx4CTjkoccFb3wa-4
> 
> Feature Flag Y/N ? Y
> 
> Collab Cycle Y/N ? Y
> 
> Platform Approval T/N ?
> 
> DataDog Analytics  Y/N ? N
> 
> 
> 
> 
> UCD Validation …
=> added feature flag for SM Signature Settings

config/features.yml
Removing feature toggles that are no longer being used in vets-website
- department-of-veterans-affairs/va.gov-team/issues/99228
- department-of-veterans-affairs/vets-website/pull/34080
- department-of-veterans-affairs/vets-website/pull/34081
*(Describe what …
=> [CST] Removing feature toggles that are no longer used

app/models/saved_claim/veteran_readiness_employment_claim.rb, spec/models/saved_claim/veteran_readiness_employment_claim_spec.rb
I'm a member of the VA-IIR Team and we are the owners of this project.
When we attempt to submit a claim, we first try to send it to VBMS.  If that action fails, we fall back to Lighthouse.  Previously the `send_to_lighthouse!` function swallowed any exceptions it encountered. This in turn would not trigger a retry (and eventually a failure email message to the user) in the Sidekiq queue.  As a result, this caused a silent failure.
This is a one-line code change, `raise`ing after logging an error.  No feature flag was used.
Ticket: vvvv[101060 …
=> Do not swallow errors in `send_to_lighthouse!` (ZSF)

Gemfile.lock, db/migrate/20250117180318_create_user_action_events.rb, db/migrate/20250117180319_create_user_actions.rb, db/schema.rb
- Creating two new database tables (`user_actions` and `user_action_events`) to support user action auditing
- Identity team owns and will maintain these components
- This is foundational database work for the user action auditing feature
- [VI-863](https://jira.devops.va.gov/browse/VI-863)
- This is a new feature, adding database tables for user action auditing
- Steps to verify:
1. Run migrations locally: `bin/rails db:drop db:create db:schema:load db:migrate`
2. Verify table structure in database matches requirements
3. Test enum type constraints work for status values
4. Verify foreign key relationships between tables
5. Confirm indexes are properly created on status field
- Database schema changes only
- No direct user-facing …
=> Creates user action tracking schema

lib/periodic_jobs.rb
Runs Income Limits import scripts monthly to align with data export cadence.
- [*Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses Jira*](https://github.com/department-of-veterans-affairs/vets-api/pull/20415)
Manual
Income Limits Sidekiq scripts
=> VACMS-18907: Alters cadence of Income Limits import scripts to run monthly.

modules/va_notify/app/models/va_notify/notification.rb
https://github.com/orgs/department-of-veterans-affairs/projects/1415/views/1?pane=issue&itemId=88343529&issue=department-of-veterans-affairs%7Cvanotify-team%7C1429 …
=> #1429: v5: Missing require json_marshal

lib/source_app_middleware.rb
https://github.com/department-of-veterans-affairs/vets-website/pull/34228
https://github.com/department-of-veterans-affairs/content-build/pull/2423 …
=> MBMS-80121 create skeleton of new form 1330M Medallions

modules/claims_api/app/controllers/claims_api/v2/blueprints/power_of_attorney_request_blueprint.rb, modules/claims_api/app/controllers/claims_api/v2/veterans/power_of_attorney/request_controller.rb, modules/claims_api/app/swagger/claims_api/v2/dev/swagger.json, modules/claims_api/spec/requests/v2/veterans/power_of_attorney/power_of_attorney_request_spec.rb, spec/support/schemas/claims_api/v2/veterans/power_of_attorney/request_representative/submit.json
Previously, we omitted null attributes in the power of attorney request create response. Now, return all possible attributes, even if they are null. 
[API-44249](https://jira.devops.va.gov/browse/API-44249)
Create a new power of attorney request (POST `/v2/veterans/:icn/power-of-attorney-request`) and observe null attributes (which were previously omitted):
```
{
"data": {
"id": "1f6d995e-7f09-4702-bd01-0b0b3811cee3",
"type": "power-of-attorney-request",
"veteran": {
"serviceNumber": "123678453",
"serviceBranch": "ARMY",
"address": {
"addressLine1": "2719 Hyperion Ave",
"addressLine2": "Apt 2",
"city": "Los Angeles",
"stateCode": "CA",
"zipCode": "92264",
"zipCodeSuffix": "0200"
},
"phone": {
"areaCode": "555",
"phoneNumber": "5551234"
},
"email": …
```
=> [API-44249] Update PoA Request Create for Static Response

lib/source_app_middleware.rb
https://github.com/department-of-veterans-affairs/vets-website/blob/a5114c4edcd4924575ad92b604c41578f8cc5620/src/applications/accredited-representative-portal/manifest.json#L4
=> [ART] fix ARP source app

spec/lib/sidekiq/form526_backup_submission_process/submit_spec.rb
Re-skip a test [we have been having some problems with](https://github.com/department-of-veterans-affairs/vets-api/pull/20298).
=> Skip a flaky test block

.rubocop_todo.yml, app/sidekiq/education_form/process10203_submissions.rb
- Fixes the following Rubocop offenses:
- `Lint/DuplicateBranch`
- fix single issue in  `app/sidekiq/education_form/process10203_submissions.rb`
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/100982
=> Fix Rubocop Lint/DuplicateBranch

spec/sidekiq/benefits_intake_status_job_spec.rb
Since its difficult to test the VMBS status I added a test to ensure it will get hit if all variables are in place …
=> 94111: Add spec to test email

modules/claims_api/app/sidekiq/claims_api/poa_updater.rb, modules/claims_api/app/sidekiq/claims_api/poa_vbms_updater.rb, modules/claims_api/app/sidekiq/claims_api/v2/poa_form_builder_job.rb, modules/claims_api/app/sidekiq/claims_api/va_notify_accepted_job.rb
Update POA process stepsʼ completed_at attribute on success.
[API-44351](https://jira.devops.va.gov/browse/API-44351)
Run the POA jobs synchronously so that at least one succeeds. Observe filled completedAt field in the GET POA response:
```
{
"data": {
"id": "820bde2f-2196-4cd8-b20c-dcce9a3873e8",
"type": "claimsApiPowerOfAttorneys",
"createdAt": "2024-11-12T23:06:03.892Z",
"representative": {
"serviceOrganization": "",
"representative": {
"type": "attorney"
}
},
"status": null,
"errors": [
{
"title": "BGS Error",
"detail": "BGS Error: update_birls_record failed with code xyz",
"code": "POA_UPDATE"
}
],
"steps": [
{
"type": "PDF_SUBMISSION",
"status": "SUCCESS",
"completedAt": "2025-01-27T17:36:13.225Z",
"nextStep": "POA_UPDATE"
},
{
"type": "POA_UPDATE",
"status": …
```
=> [API-44351] update completedAt when the jobs are done

app/models/form526_submission.rb, app/sidekiq/form526_status_polling_job.rb, app/sidekiq/lighthouse/poll_form526_pdf.rb, config/features.yml, spec/sidekiq/form526_status_polling_job_spec.rb
- add Received Email invocation to Backup Path success
- refactor send_confirmation_email to reside in Form526Submission model
- refactor `send_confirmation_email` -> `send_received_email`
- call `send_received_email` in Primary Path and Backup Path's respective places
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/95908
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer …
=> dbex/95908: add Received Email invocation to Backup Path success

modules/ivc_champva/app/models/ivc_champva/vha_10_10d.rb, modules/ivc_champva/spec/models/vha_10_10d_spec.rb
Reverts department-of-veterans-affairs/vets-api#20465
=> Revert "101565_PEGA-Integration-Include-10-10d-signers-email"

app/models/persistent_attachments/va_form.rb, spec/models/persistent_attachments/va_form_spec.rb
This PR adds two new forms to the Form Upload tool.
=> Add two 21P- forms to Form Upload tool

config/features.yml
Remove unused Facility Locator flippers. All flippers are OFF in staging and production.
| Flipper | Ticket | vets-website PR |
| --- | --- | --- |
|`facility_locator_restore_community_care_pagination` | [#11597](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11597) | https://github.com/department-of-veterans-affairs/vets-website/pull/34246 |
| `show_expandable_vamc_alert` | [#11600](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11600) | https://github.com/department-of-veterans-affairs/vets-website/pull/34247 |
| `facility_locator_show_health_connect_number`| [#11599](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11599) | https://github.com/department-of-veterans-affairs/vets-website/pull/34249 |
| …
=> Remove unused Facility Locator flippers

app/controllers/v0/virtual_agent_claim_letters_controller.rb
- No
- We changed the service tag of our controller from claim-status to virtual-agent.
- We are working to migrate from Sentry to Datadog and along the way we saw that this service tag should be set to virtual-agent, a service our team manages, instead of claim-status, a service managed by another team.
- *(Which team do you work for, does your team …
=> [#1957] Change claim-status service tag to virtual-agent

app/controllers/v0/benefits_claims_controller.rb, lib/lighthouse/benefits_claims/constants.rb, spec/controllers/v0/benefits_claims_controller_spec.rb, spec/lib/lighthouse/benefits_claims/service_spec.rb, spec/support/vcr_cassettes/lighthouse/benefits_claims/index/200_response.yml, spec/support/vcr_cassettes/lighthouse/benefits_claims/show/200_death_claim_response.yml
- Updated `app/controllers/v0/benefits_claims_controller.rb`
- Added unit tests and VCR cassettes:
- `spec/controllers/v0/benefits_claims_controller_spec.rb`
- `spec/support/vcr_cassettes/lighthouse/benefits_claims/index/200_response.yml`
- `spec/support/vcr_cassettes/lighthouse/benefits_claims/show/200_death_claim_response.yml`
- [[CST] Backend changes to rename claims for death benefits](https://github.com/department-of-veterans-affairs/va.gov-team/issues/99951)
=> [CST] [99951] Modified claimType language for death claims in benefits claims controller

app/controllers/v0/profile/preferred_names_controller.rb, modules/mobile/app/controllers/mobile/v0/preferred_names_controller.rb, modules/mobile/spec/requests/mobile/v0/user/preferred_name_spec.rb, spec/requests/v0/profile/preferred_names_spec.rb
This PR adds an `after_action` to `invalidate_mpi_cache` when a user updates `preferred_name`
- When a user updates their preferred_name, the controller should invalidate
- *(If bug, how to reproduce)* When a user updates their preferred_name, it remains unchanged for a short period of time on the FE, even after a reload. This is likely due to mpi cache becoming stale.
- *(What is the solution, why is this the solution?)* Adding `invalid_mpi_cache` as an `after_action`
- *(Which team do you work for, does your team own the maintenance of this component?)* Identity platform, yes.
- [VI-972](https://jira.devops.va.gov/browse/VI-972)
- Log in browser-side, and head to http://localhost:3001/profile/personal-information where you can edit …
=> Invalidate mpi cache for preferred names

config/initializers/filter_parameter_logging.rb, spec/requests/filter_parameter_logging_spec.rb
This PR refactors the parameter filtering logic to improve handling of nested hashes and arrays. It replaces map! with map for arrays and transform_values! with transform_values for hashes to prevent unintended in place modifications. Previously, deeply nested structures weren’t being fully filtered (see images below).
The updated logic properly filters nested structures (see added test), ensuring all sensitive parameters, including those in deeply nested hashes, are filtered. These changes enhance the filtering mechanisms while still properly filtering the …
=> Refactoring filter logic for arrays and hashes

modules/claims_api/app/swagger/claims_api/v2/dev/swagger.json, modules/claims_api/app/swagger/claims_api/v2/production/swagger.json, modules/claims_api/spec/requests/v2/veterans/rswag_power_of_attorney_spec.rb
Update v2 POA endpoint descriptions (staging and prod docs).
[API-44572](https://jira.devops.va.gov/browse/API-44572)
Visual inspection
v2 docs (staging and production)
N/A
=> [API-44572] POA v2 - Update endpoint descriptions

modules/claims_api/app/mailers/claims_api/submission_report_mailer.rb, modules/claims_api/app/mailers/claims_api/unsuccessful_report_mailer.rb, modules/claims_api/spec/mailers/report_monthly_submissions_spec.rb, modules/claims_api/spec/mailers/unsuccessful_report_mailer_spec.rb
Remove Alex and add Drew to nightly and monthly email reports.
[API-44596](https://jira.devops.va.gov/browse/API-44596)
N/A
Email report recipients.
N/A
=> [API-44596] Update email report recipients

config/settings.yml
- *(Summarize the changes that have been made to the platform)* Adds additional section to settings for another callback bearer token
- *(Which team do you work for, does your team own the maintenance of this component?)* VA Notify - yes, my team owns the va_notify module
- https://github.com/department-of-veterans-affairs/vanotify-team/issues/14 …
=> VaNotify - add benefits disability to settings

config/features.yml
- This removes a feature flag definition from the settings. This feature flag was used to rollout out a new feature and the rollout was completed on Jan 16.  
- #20366 removed all references to the feature flag and was merged on 2/4 …
=> Removes feature flag from config

modules/va_notify/lib/va_notify/default_callback.rb, modules/va_notify/spec/lib/default_callback_spec.rb
- *(Summarize the changes that have been made to the platform) update our default callback logic to properly handle temporary failures.
- *(Which team do you work for, does your team own the maintenance of this component?) VA Notify - yes, my team owns this module
- [#1473 - Update Default Callback to properly handle temporary …
=> VaNotify - Update callback logic to include temporary_failure

modules/accredited_representative_portal/app/controllers/accredited_representative_portal/v0/representative_users_controller.rb, modules/accredited_representative_portal/config/initializers/bypass_olive_branch.rb, modules/accredited_representative_portal/spec/factories/representative_user.rb, modules/accredited_representative_portal/spec/requests/accredited_representative_portal/bypass_olive_branch_spec.rb, modules/accredited_representative_portal/spec/requests/accredited_representative_portal/v0/user_spec.rb
=> [ARP - lower camel responses - 4] camel response in ARP users controller

modules/accredited_representative_portal/app/controllers/accredited_representative_portal/v0/in_progress_forms_controller.rb, modules/accredited_representative_portal/app/controllers/accredited_representative_portal/v0/representative_users_controller.rb, modules/accredited_representative_portal/config/initializers/bypass_olive_branch.rb, modules/accredited_representative_portal/spec/factories/representative_user.rb, modules/accredited_representative_portal/spec/requests/accredited_representative_portal/bypass_olive_branch_spec.rb, modules/accredited_representative_portal/spec/requests/accredited_representative_portal/v0/in_progress_forms_spec.rb, modules/accredited_representative_portal/spec/requests/accredited_representative_portal/v0/user_spec.rb
=> [ARP - lower camel responses - 3] handle camel params in ARP IPF controller

config/database.yml, config/locales/exceptions.en.yml, config/settings.yml, lib/mdot/client.rb, spec/models/form_profile/mdot_spec.rb, spec/support/vcr.rb, spec/support/vcr_cassettes/mdot/get_supplies_200.yml, spec/support/vcr_cassettes/mdot/get_supplies_401.yml, spec/support/vcr_cassettes/mdot/get_supplies_500.yml
- Calls to `#handle_client_error` can fail when trying to parse input this way: `error&.body&.fetch('result', nil)`, thus causing an error in a method that is supposed to be handling errors :-/
- Refactors `#handle_client_error`
- Surfaces 401 and 500 responses
- department-of-veterans-affairs/va.gov-team#102066 …
=> Reorder: Fixes error handling for MDOT::Client

modules/accredited_representative_portal/spec/requests/accredited_representative_portal/v0/form21a_spec.rb
Addressing a report of test flakiness. Skipping for now as we aren't actively working on this section at the moment.
=> Fixing a flaky spec

modules/vba_documents/lib/vba_documents/monthly_stats_generator.rb, modules/vba_documents/spec/lib/monthly_stats_generator_spec.rb
- Private method extraction
- Minor method refactoring
- removed @stats in favor or stats method 
- Converted hashes to symbols and deep stringified stats hash
- n/a
=> Refactor - VBA Documents MonthlyStatsGenerator

modules/ask_va_api/app/services/crm/service.rb, modules/ask_va_api/spec/services/crm/service_spec.rb
This PR refactors the Crm::Service#call method to improve readability, maintainability, and request handling. Additionally, it ensures that the organizationName parameter is included in the request params for :put calls.
Key Changes:
•	Refactored Crm::Service#call for better structure and clarity.
•	Added organizationName to the request parameters when making a :put call.
•	Improved URL handling to prevent potential formatting issues.
This update enhances code maintainability while ensuring the correct request structure for PUT requests. 🚀
•	✅ Verified new code in the staging environment …
=> BE | AskVA API: refactor and add in organizationName to params for :put call

config/features.yml
creates feature flag for mhv_medications_display_refill_progress
mhv medications
=> added refill progress feature flag

config/features.yml
Create BE feature flag to correspond with FE side.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/94931
FSR
(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist …
=> FSR - 94931 - Create Corresponding BE Feature Flag

.github/CODEOWNERS, app/models/messaging_signature.rb, config/locales/exceptions.en.yml, lib/sm/client.rb, modules/my_health/app/controllers/my_health/v1/messaging_preferences_controller.rb, modules/my_health/config/routes.rb, modules/my_health/docs/openapi.yaml, modules/my_health/docs/openapi_merged.yaml, modules/my_health/docs/schemas/SecureMessageSignatureUpdateRequest.yml, modules/my_health/spec/requests/my_health/v1/messaging/preferences_spec.rb, spec/lib/sm/client/preferences_spec.rb, spec/support/vcr_cassettes/sm_client/preferences/fetches_the_signature_preferences.yml, spec/support/vcr_cassettes/sm_client/preferences/missing_params_updating_the_signature_preferences.yml, spec/support/vcr_cassettes/sm_client/preferences/sets_the_signature_preferences.yml
- *This work is behind a feature toggle (flipper): *NO*
- adding `POST my_health/v1/messaging/preferences/signature` route, controller and lib methods
- moving `GET my_health/v1/messaging/messages/signature` to `GET my_health/v1/messaging/preferences/signature`, pending cleanup work after all FE migration is done too
- Team: MHV Messages
- https://jira.devops.va.gov/browse/MHV-65858 …
=> MHV-65858 My Health SM post signature api

lib/efolder/service.rb
This service has been causing over 33k 500 errors a day. Datadog error can be found [here](https://vagov.ddog-gov.com/error-tracking?query=service%3Avets-api&fromUser=false&issueId=bd619772-b170-11ef-80c2-da7ad0900007&refresh_mode=sliding&source=all&from_ts=1739912862047&to_ts=1739916462047&live=true). Datadog error logs can be found [here](https://vagov.ddog-gov.com/logs?query=env%3Aeks-prod%20service%3Avets-api%20-%22%5BMHV%5D%5BUserAccount%5D%5BCreator%5D%20%22%20-%22%60block%20in%20bgs_doc_uuids%27%22%20%40payload.controller%3A%22Mobile%3A%3AV0%3A%3AEfol …
=> Fixing efolder errors

db/migrate/20250218222532_add_va_notify_notifications_index.rb, db/schema.rb
=> Created va_notify_notificaitons index

modules/decision_reviews/README.md
Update the transition plan README to reflect current progress. No changes to code.
=> Update module isolation progress

lib/efolder/service.rb
Avoid looping over nil in EFolder service. This is causing many [errors](https://vagov.ddog-gov.com/logs?query=env%3Aeks-prod%20pod_name%3Avets-api-mobile-%2A%20status%3Aerror%20-%40message_content%3A%22%5BMHV%5D%5BUserAccount%5D%5BCreator%5D%20validation%20error%22&agg_m=count&agg_m_source=base&agg_t=count&clustering_pattern_field_path=message&cols=host%2Cservice&event=AwAAAZUfvZduD5G6HwAAABhBWlVmdmJ0cEFBQVZ3czhINnJ4aDhRRVIAAAAkMDE5NTFmYmQtZDc1MC00MWMxLWFjOTAtZGQyYTQ0ZWViZmIzAAApCg&fromUser=true&graphType=flamegraph&messageDisplay=inline&refresh_mode=slidin …
=> Avoid looping over nil in eFolder

config/features.yml
Add corresponding back end components to new flags for upcoming efforts for benefits team.
FE Flag PR: https://github.com/department-of-veterans-affairs/vets-website/pull/34752
https://github.com/department-of-veterans-affairs/va.gov-team/issues/102591
https://github.com/department-of-veterans-affairs/va.gov-team/issues/102648
- *What …
=> 102591 & 102648 - FSR - Create One VA Debt Letter feature flag & VHA Payment History MVP feature flag

config/features.yml
add landing page removal feature flag to features.yml file.
mhv-medications
=> add landing page removal feature flag to features.yml file.

modules/va_notify/README.md
- *(Summarize the changes that have been made to the platform)* Updates to the va_notify readme with two sequence diagrams showing a high level overview of how the systems work (both inside vets-api and outside)
- …
=> VaNotify - update readme

modules/burials/spec/lib/burials/form_profiles/va_21p530ez_spec.rb
- Lint this spec that is causing failures on master
=> Lint va_21p530ez_spec

config/features.yml
Adding new feature flag to manage debt fetching and display generic messaging. 
- FE sister ticket
department-of-veterans-affairs/vets-website/pull/34735
department-of-veterans-affairs/va.gov-team#103043
Manual testing complete to confirm flag was showing up in `http://localhost:3000/flipper/features`
N/A
Feature flags
=> Adding new feature flag

db/audit_migrate/20250129172450_create_audit_logs.rb, db/audit_schema.rb
- Create audit log table
- https://jira.devops.va.gov/browse/VI-870
- Migrate the database
```bash
rails db:migrate
```
-or-
```bash
rails db:migrate:audit
```
audit database
=> [vi-870] Create Audit logs table

config/features.yml, config/settings.yml
- Adds configuration settings for the Enrollment System's eeSummary REST API as well as a flipper toggle.
- https://github.com/orgs/department-of-veterans-affairs/projects/1433/views/35?pane=issue&itemId=98947352&issue=department-of-veterans-affairs% …
=> #103594 [1010 Health Apps] Add config settings and flipper for Enrollment System's eeSummary REST API

config/features.yml
- Add feature toggle to view new GI Comparison Tool homepage that that the VEBT & EDM teams are collaborating on
- [VEBT-1213](https://jira.devops.va.gov/browse/VEBT-1213)
- [VEBT-1214](https://jira.devops.va.gov/browse/VEBT-1214)
=> VEBT-1213 Add CT collab feature toggle

modules/vaos/spec/requests/vaos/v2/locations/clinics_spec.rb
This spec has been frequently failing today. Hopefully, mocking all flippers will prevent false failures.
- [Failing run example](https://github.com/department-of-veterans-affairs/vets-api/runs/37860908358) …
=> Mocked flippers for VAOS::V2::Locations::Clinics specs

config/features.yml
If the folder you changed contains a `manifest.json`, search for its `entryName` in the content-build [registry.json](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/applications/registry.json) (the `entryName` there will match).
If an entry for this folder exists in content-build and you are:
1. **Deleting a folder**:
1. First search `vets-website` for _all_ instances of the `entryName` in your `manifest.json` and remove them in a separate PR. Look particularly for references in …
=> Dependents | 103831: Add flipper for transition banner

db/migrate/20250207083950_create_tooltips.rb, db/schema.rb
Created active record migration file for tooltips and ran rails db:migrate to update the schema with a new table named tooltips
Table will have 8 columns to store information about tooltips:
1. `id` : UUID
2. `user_account_id`: foreign key referencing the user_accounts table that the tooltip belongs to
3. `tooltip_name`
4. `last_signed_in`: timestamp of the last time the user logged in, needed for business logic(this is used to determine unique sessions)
5. `counter`: to keep track of how many times tooltip has been viewed(determination of each count is subject to controller logic)
6. `hidden`: to determine if tooltip should be hidden or not. 
7. standard `created_at` and `updated_at` columns
It also adds a constraint `unique: true` to ensure that each tooltip name is unique within a …
=> [MHV 66349] created tooltip migration, and added table to database schema

modules/vaos/config/initializers/flipper.rb, modules/vaos/spec/config/initializers/flipper_spec.rb
- We're adding Flipper instrumentation to monitor when operations to Appointments tool features are made on Flipper. This will allow us to track feature updates and setup alerts to ensure no critical features are accidentally modified.
- Appointments tool team
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/101922
N/A
Appointments tool
=> Add Flipper instrumentation for appointments features

config/settings.yml, config/settings/development.yml, config/settings/test.yml
Reverts department-of-veterans-affairs/vets-api#21015
=> Revert "remove authn_requests_signed from config settings"

modules/my_health/app/controllers/my_health/v1/messaging_preferences_controller.rb, modules/my_health/spec/requests/my_health/v1/messaging/preferences_spec.rb, spec/support/vcr_cassettes/sm_client/preferences/sets_the_signature_preferences_exclude_name_and_title.yml
- resolving defect for `GET /my_health/v1/messaging/preferences/signature` when `signatureName` and `signatureTitle` are not present
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featur …
=> My Health Messaging Preferences - signature defect

modules/decision_reviews/spec/dr_spec_helper.rb, modules/decision_reviews/spec/requests/v1/supplemental_claims_spec.rb, modules/decision_reviews/spec/sidekiq/form4142_submit_spec.rb
DecisionReviews::V1::SupplementalClaims spec has been flakey and blocking CI. Mocking flippers will allow tests to pass when running specs in parallel. …
=> Attempting to fix flake DecisionReviews::V1::SupplementalClaims spec

modules/decision_reviews/spec/controllers/decision_review_notification_callbacks_controller_spec.rb, modules/decision_reviews/spec/requests/v1/notice_of_disagreements_spec.rb, modules/decision_reviews/spec/sidekiq/delete_saved_claim_records_job_spec.rb, modules/decision_reviews/spec/sidekiq/failure_notification_email_job_spec.rb, modules/decision_reviews/spec/sidekiq/hlr_status_updater_job_spec.rb, modules/decision_reviews/spec/sidekiq/nod_status_updater_job_spec.rb, modules/decision_reviews/spec/sidekiq/sc_status_updater_job_spec.rb, modules/vaos/spec/requests/vaos/v2/appointments_spec.rb
VAOS::V2::Appointments spec has been flakey and blocking CI. Mocking flippers will allow tests to pass when running specs in parallel. Here's an example of failing spec tests.
N/A …
=> Attempting to fix VAOS::V2::Appointments flakey specs

spec/rails_helper.rb
FactoryBot instances were removed from Vets API specs causing many failures. FactoryBot::Syntax::Methods was added to the Rspec configuration to properly run commands like create(:user).
- n/a …
=> Include FactoryBot::Syntax::Methods

modules/decision_reviews/spec/dr_spec_helper.rb
In this [pull request](https://github.com/department-of-veterans-affairs/vets-api/pull/19892), DecisionReviews does not use the rails helper. FactoryBot::Syntax::Methods was added to the spec helper. 
-N/A …
=> Include FactoryBot::Syntax::Methods for decision_review specs

app/controllers/v0/education_benefits_claims_controller.rb
- *(Summarize the changes that have been made to the platform)* Fix method for retrieving PDF files to use Saved Claim ID from form
- *(If bug, how to reproduce)* Right now when you press "Download PDF" after submitting a 10216 form, there is a 500 error when trying to download the PDF.
- *(What is the solution, why is this the solution?)* Use the saved claim ID in the education benefits object instead of just using the education benefits ID returned from the form response. This should return the …
=> VEBT-1243 - Fix 10216 PDF download button

modules/claims_api/spec/rails_helper.rb
Included FactoryBot::Syntax::Methods in modules/claims_api specs to prevent flakey tests.
- N/A
- …
=> Included FactoryBot::Syntax::Methods in modules/claims_api specs

modules/vaos/config/initializers/flipper.rb
- It looks like operations via the Flipper UI sends the instrumentation data as strings (i.e. names) instead of symbols so we need to check both symbols and strings in our code. This should only affect the feature toggle names but I've added the operation names for redundancy as well in case they might be affected.
- Appointments tool team
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/101922
N/A
Appointments tool
=> Handle Flipper UI actions for instrumentation

modules/mobile/spec/requests/mobile/v0/appointments/cancel_spec.rb, modules/mobile/spec/requests/mobile/v0/appointments/create_spec.rb, modules/vaos/spec/services/v2/mobile_facility_service_spec.rb
First go at VAOS flakey tests.
- N/A …
=> Mock flippers for VAOS appointment specs

modules/debts_api/app/models/debts_api/v0/form5655_submission.rb, modules/debts_api/spec/models/debt_api/v0/form5655_submission_spec.rb
- *This work is behind a feature toggle (flipper): YES/NO*: YES
- *(Summarize the changes that have been made to the platform)*: We need to update the data we're sending to VANotify so that we can fire the 5655 silent error mailer.
- *(If bug, how to reproduce)*: I ran our VANotify code and got an error back about the missing parameters this PR adds.
- *(What is the solution, why is this the solution?)*: This gets VANotify the data it needs to successfully send the mailer.
- *(Which team do you work for, does your team own the maintenance of this component?)*: Financial Management. You can find me at #financial-management in Octo Slack.
- *Link to ticket created in va.gov-team repo OR screenshot of Jira …
=> 100844 Silent Error mailer template value update

config/settings.yml
- Fix ivc_forms/s3/region
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/104127
=> Fix s3 bucket for ivc_forms

config/settings.yml
- change from nil to ENVs for parameter store
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/104127
=> Fix accredited_representative_portal/allow_list settings

config/features.yml
This ticket is to remove a feature toggle, `veteran_onboarding_contact_info_flow` - there is no backend code associated with this feature toggle; it is used entirely to alter the functionality of the website.
https://github.com/department-of-veterans-affairs/va-iir/issues/1378
- *(Which team do you work for, does your team own the maintenance of this …
=> Remove feature toggle - veteran_onboarding_contact_info_flow

config/features.yml
- Adding a pair of feature toggles:
- Add `va_online_scheduling_mhv_route_guards`: used for deploying:
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/101531
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/101532
- Add `va_online_scheduling_direct_schedule_appointment_conflict`: used for deploying
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/101218
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/104288
N/A
N/A
=> Add feature toggles for route guards and appointment conflicts

config/features.yml
This PR correlates to the [vets-website PR - #34381](https://github.com/department-of-veterans-affairs/vets-website/pull/34381/files) that refactors the AuthenticatedRoute component in the 10-10EZR application to improve code quality and maintainability. The component is responsible for route guard authentication which is controlled by the ezr_route_guard_enabled feature toggle.
Key improvements include:
- Simplified conditional logic with clearer early returns
- Improved comments explaining the authentication flow
- Maintained all existing functionality while reducing complexity
The feature toggle (ezr_route_guard_enabled) continues to work as before, allowing for dynamic enabling/disabling of authentication requirements for routes in the application.
- *This work is behind a feature …
=> Added feature toggle for ezr route guard

.github/workflows/deploy-template.yml
Fixes error on Build, Push and Deploy GHA action.
https://github.com/department-of-veterans-affairs/vets-api/actions/runs/13701300164/job/38315864673
Resolves the following failure by installing yq via binary
```
10s
Run sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CC86BB64
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CC86BB64
sudo add-apt-repository ppa:rmescandon/yq
sudo apt update
sudo apt install yq -y
shell: /usr/bin/bash -e {0}
env:
AWS_DEFAULT_REGION: us-gov-west-1
AWS_REGION: us-gov-west-1
AWS_ACCESS_KEY_ID: ***
AWS_SECRET_ACCESS_KEY: ***
VA_VSP_BOT_GITHUB_TOKEN: ***
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
Executing: /tmp/apt-key-gpghome.9n76IvJ6cf/gpg.1.sh --keyserver keyserver.ubuntu.com …
```
=> Resolve build error for yq new ubuntu version

modules/appeals_api/.bruno_appeals_api/decision_reviews v2/Docs.bru, modules/appeals_api/.bruno_appeals_api/decision_reviews v2/Healthcheck.bru, modules/appeals_api/.bruno_appeals_api/decision_reviews v2/Upstream Healthcheck.bru, modules/appeals_api/app/controllers/appeals_api/metadata_controller.rb, modules/appeals_api/catalog-info.yaml, modules/appeals_api/config/routes.rb, modules/appeals_api/spec/requests/appeals_api/api_docs_request_spec.rb, modules/appeals_api/spec/requests/appeals_api/metadata_request_spec.rb
This work is behind a feature toggle (flipper): *NO*
This PR modifies the Lighthouse Decision Reviews v2 API to add new routes for the docs, healthcheck, and upstream healthcheck. These new routes better match the Lighthouse API standards and are aligned with the public routes that were recently modified in the Lighthouse API Gateway.
The old routes will continue to be supported until changes have been made in the Lighthouse API Gateway to correctly route the new public routes to the new application routes. I have added TODOs to remind us to remove the old routes.
Additionally, I added our missing Bruno examples for Decision Reviews v2 healthcheck endpoints.
My team (Lighthouse Team Banana Peels) owns the `appeals_api` module.
- [API-45228](https://jira.devops.va.gov/browse/API-45228)
- …
=> API-45228: Update Lighthouse Decision Reviews v2 API Healthcheck and Docs Routes

config/settings.yml
Downcased Kafka producer environment variables to comply with new naming conventions
=> Downcase Kafka producer env vars

spec/sidekiq/education_form/create_daily_spool_files_spec.rb
- Stub Settings in create_daily_spool_files_spec
- Causing other specs to fail
=> Stub Settings in create_daily_spool_files_spec

modules/debts_api/app/controllers/debts_api/v0/one_debt_letters_controller.rb, modules/debts_api/lib/debts_api/v0/one_debt_letter_service.rb, modules/debts_api/spec/lib/debt_api/v0/one_debt_letter_service_spec.rb, modules/debts_api/spec/requests/debts_api/v0/one_debt_letters_spec.rb
- *This work is behind a feature toggle (flipper): YES/NO*: This will be behind a Flipper but currently, it's not and it's not veteran facing
- *(Summarize the changes that have been made to the platform)*: We are rolling out the "One Debt Letter" 🥳 . This adds a header, a save_pdf method that will likely be temporary for testing purposes.
- *(What is the solution, why is this the solution?)*: We need to generate a PDF with debt and copay info, I've looked into Lighthouse, and the forms framework that we have. This doesn't have an OMB number so it seems the right path.
- *(Which team do you work for, does your team own the maintenance of this component?)*: Financial Management you can find me on Octo slack at #financial-management …
=> 102640 Financial Management One Debt Letter Header

config/features.yml
See [this Figma](https://www.figma.com/design/78M7pwgz2mU64WRiCwMVzE/MHV-Figma-Template?node-id=695-15723&t=2dFaw6bZusa80tkn-0) - the URLs in the "Health care" section of My VA must be updated.  This PR is simply to add a feature toggle which will be queried by the `vets-website`
- *(Which team do you work for, does your team own the maintenance of this …
=> Add feature toggle, for consumption by vets-website

config/features.yml
adds feature toggle for IPE work
[Add in production education for filtering FE](https://jira.devops.va.gov/browse/MHV-66597)
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretoggles …
=> [MHV-66597] add feature toggle.

app/models/form_profile.rb, app/models/persistent_attachments/va_form.rb, modules/simple_forms_api/app/services/simple_forms_api/form_upload_notification_email.rb
- This PR activates the Form Upload functionality for VA Forms 21-4192 (Request for Employment Information) and 21-8940 (Veterans Application for Increased Compensation). The changes include backend integration for form uploads, frontend updates to enable users to upload these forms, and email notification configurations for submission statuses.
- There was no prior bug; this is a new feature implementation.
- The solution involves integrating the forms into the backend to handle uploads and metadata submission, enabling the forms in the frontend React component, and ensuring email notifications are triggered correctly. This approach ensures a seamless user experience and compliance with the requirements outlined in the ticket.
- I work for the Veteran Facing Forms Team, which is …
=> [SIMPLE-FORMS] feat: form upload - turn on forms 21-4192 & 21-8940

config/settings.yml, config/settings/development.yml, config/settings/test.yml, modules/ask_va_api/app/services/crm/service.rb
- update pointing vets-api production to crm production
- https://github.com/department-of-veterans-affairs/ask-va/issues/1664
=> BE | Ask VA Api: update crm production env

modules/ask_va_api/app/services/crm/service.rb
- Fix CRM Api prod naming
- https://github.com/department-of-veterans-affairs/ask-va/issues/1664
=> BE | Ask VA Api: update veft-prod to veft

config/features.yml
feature toggle for partial fill work
[Change details page to accept partial fills](https://jira.devops.va.gov/browse/MHV-66372)
mhv-medications
=> add partial fill to features file.

app/models/evidence_submission.rb, spec/sidekiq/lighthouse/evidence_submissions/evidence_submission_document_upload_polling_job_spec.rb
Updated `EvidenceSubmission` model scopes for pending records, so that they only return records with a `request_id`, and related unit test.
- [[CST] [Document Status] Polling job should only poll for evidence submission records with a request_id](https://github.com/department-of-veterans-affairs/va.gov-team/issues/105294)
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggle …
=> [CST] [ZSF] [Document Status] Updated EvidenceSubmission model scopes

app/models/saved_claim/burial.rb, modules/burials/app/models/burials/saved_claim.rb, modules/burials/lib/burials/benefits_intake/submit_claim_job.rb, modules/burials/spec/models/burials/saved_claim_spec.rb
=> Hotfix Burials pdf generation template path

config/features.yml
- YES
- Adding the feature toggles needed for our canary launch
- Staged rollout for new VA.gov experience for legacy Azure app
- [ask-va …
=> adds feature toggles for canary release, et. al.

config/settings.yml
- *(Summarize the changes that have been made to the platform)*: Simple ENV var addition for the 
- *(Which team do you work for, does your team own the maintenance of this component?)*: Financial Management
- *(If introducing a flipper, what is the success criteria being targeted?)*: No plan yet
- *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses Jira*: [Ticket](https://github.com/orgs/department-of-veterans-affairs/projects/1514/views/1?filterQuery=sprint%3A%40current+-status%3A%22Needs+Refinement%22%2C%22Draft+Epic%22%2C%22Super+Epic%22%2CEpic%2C%22Ready+%28Backlog%29%22%2C%22Draft+Super+Epic%2FEpic …
=> 100774 Setting/Environment Variable

config/features.yml
- This change introduces a feature toggle that will be used for testing out work that is in progress for the modularization of Ch31 VR&E code.
- The related vets-website PR can be found [here](https://github.com/department-of-veterans-affairs/vets-website/pull/35234).
- I work on the IIR Product team and we currently own VR&E.
- [1467](https://github.com/department-of-veterans-affairs/va-iir/issues/1467)
- This only introduces the feature toggle that will be used in future changes, so no tests at this time.
This only impacts the list of feature toggles available.
=> Add VR&E Modularization feature toggle

app/controllers/v0/benefits_claims_controller.rb, spec/controllers/v0/benefits_claims_controller_spec.rb, spec/factories/lighthouse/benefits_documents/evidence_submission.rb, spec/lib/lighthouse/benefits_documents/va_notify_email_status_callback_spec.rb
- Update the index endpoint in the vets-api claim `app/controllers/v0/benefits_claims_controller.rb` and added the field hasFailedUploads to the attributes. Put this work behind the ff `cst_show_document_upload_status`.
- Added tests
- Updated the job class in spec/factories/lighthouse/benefits_documents/evidence_submission.rb to be accurate and renamed a factory so `evss` was at the beginning of the name
- Updated spec/lib/lighthouse/benefits_documents/va_notify_email_status_callback_spec.rb with the new factory name
- *Link to ticket created in va.gov-team repo https://github.com/department-of-veterans-affairs/va.gov-team/issues/103612
- [x ] *New code is covered by unit tests* …
=> [CST] - Update index endpoint so that the Claims List returns hasFailedUploads for each claim

modules/simple_forms_api/app/services/simple_forms_api/pdf_stamper.rb
- This work updates a pdf stamping verification to account for file optimizations which appear to be applied during the PDF stamping process
- [Ticket to resolve error messages in DataDog](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/2045)
- [PR to introduce logging](https://github.com/department-of-veterans-affairs/vets-api/pull/21272)
- [Logs detailing what the problem ended up being]()
Any
=> [SIMPLE-FORMS] fix: update verification check to account for optimizations

db/schema.rb, modules/accredited_representative_portal/db/migrate/20250313190720_create_ar_icn_temporary_identifiers.rb
- *This work is behind a feature toggle (flipper): YES/NO* no
Migration for creating `icn_temporary_identifiers` table
- *(If bug, how to reproduce)* feature
- *(What is the solution, why is this the solution?)* https://github.com/department-of-veterans-affairs/va.gov-team/issues/101374
- *(Which team do you work for, does your team own the maintenance of this component?)* ARF
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/101374
- *Link to previous change of the code/bug (if applicable)* -- …
=> Migration for icn_temporary_identifiers (#101374) -- #1

modules/accredited_representative_portal/lib/tasks/seed.rake, modules/accredited_representative_portal/lib/tasks/seed/records.rb, modules/accredited_representative_portal/spec/factories/power_of_attorney_request.rb
- Exit all `rails server` and `rails console` instances
- You will need to drop your existing database so that collisions don't happen with the new data.
```
rails db:drop
rails db:setup
rake db:seed
rake accredited_representative_portal:seed
```
- Start `rails server`
- Next clear all browser cookies
- Sign back into Github and Socks
- Have the TUD page ready https://tud.vfs.va.gov/?page=1 for the temporary code
- Attempt to log in using one of the following:
`vets.gov.user+`  _0,2,4,5,6 or 7_ `@gmail.com` 
- If you get bounced back to ARP login with this error in the console: `Couldn't find AccreditedRepresentativePortal::RepresentativeUserAccount with 'id'= ...`, the only solution seems to be waiting 15-30 minutes and trying again.
- Once signed in, you should have a few dozen PoA …
=> Update ARP dev seed script (#103837)

config/settings.yml, config/settings/development.yml, config/settings/test.yml
- *(Summarize the changes that have been made to the platform)* Adds additional bearer_tokens for the benefits_management_tools service.
- *(Which team do you work for, does your team own the maintenance of this component?)* VA Notify - yes, my team owns the va_notify module
- https://github.com/department-of-veterans-affairs/vanotify-team/issues …
=> VANotify - Add callback token

app/models/form_profiles/va_526ez.rb, lib/evss/disability_compensation_form/data_translation_all_claim.rb, spec/lib/evss/disability_compensation_form/data_translation_all_claim_spec.rb, spec/models/form_profile_spec.rb, spec/models/form_profile_v2_spec.rb
EVSS's PPIU service is gone and the same direct deposit data is coming from Lighthouse. Much of the naming is staying the same (for example, there's a `LighthousePPIUProvider`), but I wanted to make it clearer that PPIU, in its original form, does not exist anymore. 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/103443
- Most work was done in https://github.com/department-of-veterans-affairs/vets-api/pull/20691
These changes are mostly comments and strings. The Policy change does make it slightly more restrictive, but it looks like the policy is more appropriate. 
The new lighthouse policy:
```ruby
def direct_deposit_access?
user.loa3? &&
allowed_providers.include?(user.identity.sign_in[:service_name]) &&
user.icn.present? && user.participant_id.present?
end
``` …
=> Change PPIU wording to LH form 526

Gemfile.lock
vets_json_schema version bump 24.11.1 => 24.11.2
=> vets_json_schema version bump 24.11.1 => 24.11.2

db/audit_migrate/20250324180818_rename_audit_user_identifier_type_enum_login_option.rb, db/audit_schema.rb
- Update `login_uuid` enum value to `logingov_uuid`
- https://jira.devops.va.gov/browse/VI-1102
- Run migrations 
```bash
rails db:migrate
```
Audit log
=> Update audit log enum value

config/identity_settings/environments/test.yml, config/identity_settings/settings.yml
- Add path for localhost mvi url
=> Fix mvi url for dev, mock auth

config/features.yml
This PR removes the `champva_enhanced_monitor_logging` flipper that has been fully enabled in production for some months now.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/104641 …
=> 104641b1 - Remove `champva_enhanced_monitor_logging` from features.yml - IVC CHAMPVA forms

modules/ivc_champva/app/jobs/ivc_champva/missing_form_status_job.rb
This is a follow-on PR to [this one](https://github.com/department-of-veterans-affairs/vets-api/pull/20044). The first PR added the ability to check the PEGA API to verify form statuses after submission. This PR adds an import for the pega client class that is necessary for the job to actually perform the check.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/95912
To test the functionality locally:
- clone this branch and start a local rails console
- Run the following
```ruby
require 'ivc_champva/monitor'
Flipper.enable(:champva_enable_pega_report_check)
Settings.ivc_champva.pega_api.base_path = "<INSERT BASE PATH HERE>"
Settings.ivc_champva.pega_api.api_key = "<INSERT API KEY HERE>"
def demo(form_uuid)
return unless Settings.vsp_environment == "localhost" …
```
=> 95912a - Add PEGA client import to `MissingFormStatusJob` - IVC CHAMPVA forms

.github/CODEOWNERS, app/models/audit/application_record.rb, app/models/audit/log.rb, config/database.yml, spec/factories/audit/logs.rb, spec/models/audit/log_spec.rb
- Creates Audit:Log class
- Connects base class to audit database
- update `audit` database production config.
- add default values so it will boot in envs where there is no audit database (sandbox)
-  run database tasks if the database exists
- https://jira.devops.va.gov/browse/VI-1102
- Test creating `Audit::Log`
Audit Logs, audit DB
=> Create Audit::Log models

spec/models/form_profile/mdot_spec.rb, spec/requests/v0/in_progress_forms_controller_spec.rb, spec/support/vcr_cassettes/mdot/get_supplies_null_addresses_200.yml
Add some MDOT specs
https://github.com/department-of-veterans-affairs/vets-website/pull/35466
https://github.com/department-of-veterans-affairs/va.gov-team/issues/102210
It's all test baby
None because it's just tests
=> 102210 write specs for MDOT IPF

modules/simple_forms_api/docs/form_upload_tool_README.md
This PR fixes some README links.
=> Fix Form Upload README links

spec/lib/pagerduty/maintenance_client_spec.rb
📣 All test runs in master are currently blocking deploys
There are some flaky parallel spec runs and I believe VCR doesn’t allow turning itself off while a cassette is active. I think what's happening is a VCR cassette still "inserted" but the test is trying to turn off VCR (or reset it) without first ejecting that cassette. This is most likely due to parallel runs.
This addresses the issue. 
Example: https://github.com/department-of-veterans-affairs/vets-api/actions/runs/14108101012/job/39519383329 …
=> Update maintenance_client_spec.rb for VCR failures

config/features.yml
> NO
> Removing obsolete feature toggles
> Removing:
> - `hlr_confirmation_update`
> - `sc_confirmation_update `
> - `nod_confirmation_update `
> - https://github.com/department-of-veterans-affairs/va.gov-team/issues/106152 (ticket)
> - https://github.com/department-of-veterans-affairs/vets-website/pull/35516 (to be merged first)
> - https://github.com/department-of-veterans-affairs/vets-website/ …
=> DR | Remove confirmation toggles

docker-compose.review.yml
- set to - `"config/ssoe_idp_sqa_metadata_isam.xml"`
- wrong value in ansible config
=> Add saml_ssoe.idp_metadata to review instance docker-compose

app/models/saved_claim/veteran_readiness_employment_claim.rb
I work for the VA-IIR team and we own this component.  We have had some monitor alerts which seem to indicate that an LOA3 user attempting to submit a form application does not have a social security number.  In order to aid in this investigation, this PR adds logging.
see [1589](https://github.com/department-of-veterans-affairs/va-iir/issues/1556) and [1589](https://github.com/department-of-veterans-affairs/va-iir/issues/1589) …
=> add logging to send_to_lighthouse to aid in job failure investigation

lib/source_app_middleware.rb
- *(Summarize the changes that have been made to the platform)* I added the entryName `representative-21a` to the `SourceAppMiddleware`.
- *(What is the solution, why is this the solution?)* This way the frontend app will send data to datadog.
- *(Which team do you work for, does your team own the maintenance of this component?)* FAR/ARM
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/104244
- *Describe the steps required to verify your changes …
=> Add 21a to SourceAppMiddleware

lib/debt_management_center/sidekiq/va_notify_email_job.rb, modules/debts_api/app/models/debts_api/v0/form5655_submission.rb, spec/lib/debt_management_center/va_notify_email_job_spec.rb
This adds the callback functionality for the 5655 "Financial Status Report" Form. We are using the [Default Callback implementation](https://github.com/department-of-veterans-affairs/vets-api/tree/master/modules/va_notify#how-teams-can-integrate-with-callbacks).
- *This work is behind a feature toggle (flipper): YES/NO*: Yes
- *(Summarize the changes that have been made to the platform)*: Adds VA Notify callback functionality
- *(What is the solution, why is this the solution?)*: This is one of the 2 documented implementations. Seems the most straight forward and simple for our notification
- *(Which team do you work for, does your team own the maintenance of this component?)*: Financial Management. Yes, we own the maintenance. …
=> 100846 Financial Management callback

lib/rx/medications_client.rb
- Adds single log for vagov rx req
N/A
N/A
N/A
N/A
=> Adds log for vagov req for rx

config/features.yml
=> edm feature flag updates

config/features.yml
Added a feature toggle for representative status widget v2 features. 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/105240
=> Added feature toggle for rep status widget v2 features

lib/bpds/README.md
- Adding text into BPDS README file documenting design decisions behind BPDS schema changes made here: https://github.com/department-of-veterans-affairs/vets-api/pull/21205.
- Pension and Burial Programs Team to own this work.
- [*Link to ticket created in va.gov-team repo*](https://github.com/department-of-veterans-affairs/va.gov-team/issues/103350)
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/deve …
=> Add README entry for BPDS submission schema changes

modules/representation_management/spec/services/power_of_attorney_request_service/orchestrate_spec.rb
Removed redundant `record_consent` checks in favor of relying solely on `consent_limits`. Refactored specs to align with new logic, improving clarity and coverage.
- *Link to ticket created …
=> Remove 'record_consent' from #normalized_limitations_of_consent and update specs

db/schema.rb
- These are changes reflected in migrations that were not checked into the schema for whatever reason
=> Fixing inconsistency with checked in schema

modules/ivc_champva/app/controllers/ivc_champva/v1/uploads_controller.rb, modules/ivc_champva/app/models/ivc_champva/ves_request.rb, modules/ivc_champva/app/services/ivc_champva/ves_data_formatter.rb, modules/ivc_champva/lib/ves_api/client.rb, modules/ivc_champva/spec/requests/ivc_champva/v1/forms/uploads_spec.rb, modules/ivc_champva/spec/services/ves_data_formatter_spec.rb
This PR makes some updates to the data validation/processing prior to sending a request from our module to the VES API.
Changes:
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/103459 …
=> Update VES request with new validation requirements

config/features.yml
- Adding `va_online_scheduling_patient_history_future_appts`
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/106475
N/A
N/A
=> Add feature toggle for including future appointments in patient history

Gemfile.lock
Update brakeman to the latest. This is causing master to fail on the brakeman/security check.
- *Tests need to …
=> Update brakeman to 7.0.1

app/controllers/concerns/sign_in/authentication.rb, app/controllers/concerns/sign_in/sso_authorizable.rb, app/controllers/v0/sign_in_controller.rb, app/models/sign_in/client_config.rb, app/models/sign_in/code_container.rb, app/models/sign_in/session_container.rb, app/models/sign_in/validated_credential.rb, app/services/sign_in/auth_sso/session_validator.rb, app/services/sign_in/code_validator.rb, app/services/sign_in/constants/statsd.rb, app/services/sign_in/errors.rb, app/services/sign_in/session_creator.rb, app/services/sign_in/state_payload_jwt_encoder.rb, app/services/sign_in/token_exchanger.rb, app/services/sign_in/token_serializer.rb, app/services/sign_in/user_code_map_creator.rb, config/identity_settings/environments/dev.yml, config/identity_settings/environments/production.yml, config/identity_settings/environments/staging.yml, config/identity_settings/settings.yml, config/routes.rb, db/seeds/development.rb, spec/controllers/sign_in/application_controller_spec.rb, spec/controllers/v0/sign_in_controller_spec.rb, spec/factories/sign_in/validated_credentials.rb, spec/models/sign_in/client_config_spec.rb, spec/models/sign_in/code_container_spec.rb, spec/services/sign_in/auth_sso/session_validator_spec.rb, spec/services/sign_in/session_creator_spec.rb
- Add `v0/sign_in/authorize_sso`
- If there is an existing valid session, it will redirect back to the client with a code they can exchange for a token.
- If there is no session but they  will be redirected to USIP with the parameters they originally passed 
- https://jira.devops.va.gov/browse/VI-1150
- Seed database - `rails db:seed`
- Start `vets-website` and `vets-api`
- Test when there is an existing session
- Login to vets website like normal - http://localhost:3001/?next=loginModal&oauth=true
- make an authorize_sso request with `okta_test` client
```
localhost:3000/v0/sign_in/authorize_sso?client_id=okta_test&code_challenge=FeKw08M4keuw8e9gnsQZQgwg4yDOlMZfvIwzEkSOsiU&code_challenge_method=S256
```
- You should be redirected to `localhost:3002` (you will see a `localhost refused to …
=> Create sign_in authorize_sso

Gemfile, Gemfile.lock, rakelib/connectivity.rake
Reverts recent changes to `statsd-instrument` and its associated rake task to restore the previous stable state. Version 3.9.9 introduced breaking changes, so this rollback ensures compatibility while we reassess the upgrade path.
https://dsva.slack.com/archives/CBU0KDSB1/p1743782089931229 …
=> Replace Statsd gem updates and Rake task

.github/workflows/build.yml, Gemfile.lock
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/105666
Make build workflow run from any branch and deploy run with only main branch
=> [fix]: Build and Deploy Workflow Modification

modules/ask_va_api/app/controllers/ask_va_api/application_controller.rb, modules/ask_va_api/app/controllers/ask_va_api/v0/address_validation_controller.rb, modules/ask_va_api/app/lib/ask_va_api/inquiries/creator.rb, modules/ask_va_api/app/services/log_service.rb, modules/ask_va_api/spec/app/lib/ask_va_api/inquiries/creator_spec.rb, modules/ask_va_api/spec/requests/ask_va_api/v0/inquiries_spec.rb
This PR enhances error visibility and traceability in the Ask VA middleware by enriching exception handling and logging behavior. Specifically, it focuses on logging safe fields from inquiry parameters when an error occurs, aiding debugging while preserving PII boundaries.
⸻
✅ What’s Changed
AskVAApi::Inquiries::Creator
•	Captures a defined whitelist of SAFE_INQUIRY_FIELDS when an exception is raised.
•	Logs each safe field individually as Datadog tags via LogService.
•	Raises a structured InquiriesCreatorError that includes both the original error and …
=> BE | Ask va api: add payload logging to inquiry creator

config/features.yml, modules/accredited_representative_portal/app/controllers/accredited_representative_portal/v0/claimant/power_of_attorney_requests_controller.rb, modules/accredited_representative_portal/spec/requests/accredited_representative_portal/v0/claimant/power_of_attorney_requests_spec.rb
Added feature flag to ARP people search controller actions
- *(If bug, how to reproduce)* --
- *(What is the solution, why is this the solution?)*  added feature flag, is a requirement
- *(Which team do you work for, does your team own the maintenance of this component?)* ARF
https://github.com/department-of-veterans-affairs/va.gov-team/issues/98332
- *Describe what the old behavior was prior to the change* did not have feature toggle
- *Describe the …
=> Add feature flag for ARP people search (#98332)

modules/va_notify/app/controllers/va_notify/callbacks_controller.rb, modules/va_notify/spec/requests/callbacks_spec.rb
I work for the VA-IIR team, and in 2025 we took over the maintenance of three benefit forms.  For the Certificate of Eligibility form, we have discovered that there are a number of [failed requests](https://vagov.ddog-gov.com/logs?query=%40payload.template_id%3Ab2a2baa5-6983-4486-bb51-092442e2a31b%20%40payload.status%3Apermanent-failure&agg_m=count&agg_m_source=base&agg_t=count&clustering_pattern_field_path=message&cols=host%2Cservice&fromUser=true&graphType=flamegraph&messageDisplay=inline&refresh_mode=sliding&sort=time&spanID=4561245301119426529&storage=hot&stream_sort=desc&viz=stream&from_ts=1737994279152&to_ts=1738599079152&live=true) that we would like to investigate.  While we acknowledge that there are probably some upcoming structural changes which we will need to address in the …
=> Add `status_reason` logging to VA Notify

modules/ask_va_api/app/lib/ask_va_api/inquiries/payload_builder/inquiry_payload.rb, modules/ask_va_api/app/lib/ask_va_api/inquiries/payload_builder/shared_helpers.rb, modules/ask_va_api/spec/support/shared_contexts.rb
This PR improves the reliability and clarity of how state and residency information is extracted and built within the inquiry payload logic. These changes aim to prevent nil or empty string issues that could lead to malformed CRM requests or runtime errors.
- **build_residency_state_data**:
- Now properly guards against empty strings and nil values.
- Ensures that fallback values are only used if valid.
- **build_state_data**:
- Refactored logic to use `.presence` for cleaner checks.
- Prevents invalid `StateCode` values when input is blank.
- **File extension normalization**:
- Downcases file extensions before validation.
- Prevents uploads from being rejected due to case-sensitive mismatches (e.g. `.PDF` vs `.pdf`).
- More robust payload generation.
- Reduces risk of `NoMethodError` or …
=> Refactor state and residency handling for robustness and clarity

lib/medical_records/user_eligibility/configuration.rb
- Quick fix to adjust the host for the eligibility check to account for the API Gateway migration
> Update the existing MHV MR endpoints to point to the new API Gateway endpoints. All such instances should be behind a feature flag so they can easily be toggled back and forth.
- Code is covered by existing unit tests
- This will be more fully tested in a live environment in the RI for this PR
=> MHV-68149 Small change missed while upgrading to API Gateway

config/features.yml
This PR adds a flipper for 21-4138's confirmation email.
=> Add flipper for form 21-4138 confirmation email

config/identity_settings/environments/dev.yml
=> Re-enable mvi.mock on dev

modules/ivc_champva/app/services/ivc_champva/attachments.rb
Attempting to address flakiness per [this issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/104787). Per @rmtolmach's testing [notes below](https://github.com/department-of-veterans-affairs/vets-api/pull/21572#discussion_r2029488688), flakiness seems to have been addressed by this change.
The issue seems to be that the PDF filler was being invoked without UUIDs in one place in the actual code (rather than a misconfig of unit tests). By adding the UUID to the invocation the flakiness appears to be addressed.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/104787 …
=> Potential fix for flaky PDF generation test - IVC CHAMPVA

app/sidekiq/hca/health_facilities_import_job.rb, spec/sidekiq/hca/health_facilities_import_job_spec.rb
- The `HCA::HealthFacilitiesImportJob` assumes the `std_states` table is populated since it joins on it to get the `postal_names`. There is a job that is run daily to ensure that table is populated, but that job is not run in review instances or potentially other environments (locally, new environment). 
- This PR adds logic to check if the table is populated, and if it is empty it triggers the job to populate it
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/103519 …
=> [10-10EZ] Ensure StdState table is populated in HealthFacilitiesImportJob

lib/va_profile/v2/contact_information/service.rb
We will be testing VAProfile services in staging as part of the migration from PCIU to VA Profile’s ContactInformationV2 and AddressValidationV3. The model class and the transaction IDs will be logged in staging and given to the VAProfile team to ensure requests are successful.
Transaction id's are not considered PII. 
.  
- department-of-veterans-affairs/va.gov-team/issues/107096
Not changing functionality. 
Not changing functionality.
(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish …
=> Logging transaction_id for VAProfile testing

config/features.yml
- Adding a feature toggle to Ask VA form
- *Describe …
=> Ask VA - Adding flipper for Ask VA

lib/pdf_fill/forms/field_mappings/va1010ez.rb
- Moved the field mappings for the 10-10EZ pdf to a new module to make the va1010ez.rb not so gigantic. 
- I will use the new module in the class in a future PR (separate to keep the diffs smaller)
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/102901
- [Part II](https://github.com/department-of-veterans-affairs/vets-api/pull/21743)
- [] *New code is covered by unit tests*
- No test for this module, but it is tested once it is imported into the other class. 
- *Tests need to be written for both the flipper …
=> [10-10EZ] Move field_mappings for 10-10EZ pdf to new module (Part I)

lib/rx/client.rb, modules/my_health/app/controllers/my_health/rx_controller.rb
- Updates appToken based on how client is initialized for VA.gov
- Work is behind FF
- https://jira.devops.va.gov/browse/MHV-68512
- Behind FF
N/A
VA.gov Rx
=> MHV-68512-fix-aal-issue

lib/pdf_fill/forms/formatters/base.rb, lib/pdf_fill/forms/formatters/va1010ez.rb, lib/pdf_fill/forms/va1010ez.rb, spec/lib/pdf_fill/forms/formatters/base_spec.rb, spec/lib/pdf_fill/forms/formatters/va1010ez_spec.rb
- Added new `formatters` module in `pdf_fill` that can be used for data formatters. I wanted a better way to unit test some of these formatters I was using. 
- Current usages is behind the flipper toggle for the new 10-10EZ pdf generation
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/102901
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature- …
=> [10-10EZ] Create new pdf formatters module and update date formatter for 10-10EZ

config/features.yml
Adds a feature flag for read receipts on Secure Messaging
> Create Feature Flag for Milestone 2 changes (June 4)
> 
> Figma Link: N/A
> 
> DEV:
> 
> Feature Flag Y/N ? N/A
> 
> Collab Cycle Y/N ? N/A
> 
> Platform Approval T/N ? N/A
> 
> UCD:
> 
> DataDog Analytics Y/N ?
> 
> Analytics Tagging Changes needed (Datadog or other)?  Y/N ?
> 
> Testing:
> 
> Manual Testing Y/N ?  N
> 
> 
> 
> UCD Validation Y/N ? N
> 
> 
> AC1 Feature Flag has been created
>  …
=> added SM read receipts feature flag

config/settings.yml, config/settings/development.yml, config/settings/test.yml, modules/accredited_representative_portal/app/models/accredited_representative_portal/power_of_attorney_request_notification.rb, modules/accredited_representative_portal/spec/models/accredited_representative_portal/power_of_attorney_request_notification_spec.rb
- *(Summarize the changes that have been made to the platform)*: This PR adds the expiring and expired VA Notify template ids for the appoint a rep digital experience.
- *(What is the solution, why is this the solution?)*: VA Notify needs these template ids in place to send emails.
- *(Which team do you work for, does your team own the maintenance of this component?)*: FAR/ARM
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/101322
- *Describe what the old behavior was prior to the change*: There is no …
=> Add expiring and expired template ids

config/features.yml
=> 1569 | Renamed feature flag for vet status stage 1

modules/accredited_representative_portal/app/services/accredited_representative_portal/power_of_attorney_request_service/params_schema.rb
add "resolved_at" to the POA Request ParamsSchema allowed list
Minimal addition to an array list …
=> add "resolved_at" to the POA Request ParamsSchema allowed list

lib/pdf_fill/forms/va686c674v2.rb
-Fixed assignment of child_status object to have an error handler in case it is nil.
- Add a condition where {} is assigned if relationship_to_child is not in the params.
[- *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses Jira*](https://github.com/department-of-veterans-affairs/va.gov-team/issues/107902) …
=> fix child_status assignment

lib/va_profile/v2/person/service.rb
Fixed VAProfile::V2::Person::Service to get vaprofile_id/vet360_id for user. Method `encode_url!(icn)` should be a private method. Method `icn_with_aaid` is not needed and should be removed.
- department-of-veterans-affairs/va.gov-team/issues/107096 …
=> Fixed VAProfile::V2::Person::Service init_vet360_id private methods

lib/pdf_fill/forms/va686c674v2.rb, spec/factories/dependency_claim.rb, spec/fixtures/pdf_fill/686C-674-V2/kitchen_sink.json, spec/fixtures/pdf_fill/686C-674-V2/overflow.json, spec/models/bgs_dependents/marriage_history_spec.rb
- Changed the attribute name from reason_marriage_ended_other to other_reason_marriage_ended in two places for the v2 pdf based on the new key coming from the payload.
- The solution is to change the keyname where necessary and update the tests. This only affects v2 in these two spots.
[- *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses Jira*](https://github.com/department-of-veterans-affairs/va.gov-team/issues/107493)
- *Link to …
=> reason marriage ended name change

lib/va_profile/v2/person/service.rb, modules/mobile/app/controllers/mobile/v0/prescriptions_controller.rb, modules/mobile/spec/requests/mobile/v0/health/rx/prescriptions_spec.rb
Updating mobile prescriptions endpoint from get_history_rxs to get_all_rxs
NO
Updated the mobile prescriptions endpoint to use the newer prescription upstream service
The core mobile team
- Issue [#10724](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/10724) …
=> Updating mobile prescriptions endpoint for getting medications

modules/mobile/app/controllers/mobile/v0/prescriptions_controller.rb, modules/mobile/spec/requests/mobile/v0/health/rx/prescriptions_spec.rb
Reverts department-of-veterans-affairs/vets-api#21803
=> Revert "Updating mobile prescriptions endpoint for getting medications"

lib/bgs/form686c.rb, lib/pdf_fill/forms/va686c674v2.rb, spec/factories/686c/form_686c_674.rb, spec/factories/686c/spouse.rb, spec/factories/dependency_claim.rb, spec/fixtures/pdf_fill/686C-674-V2/kitchen_sink.json, spec/fixtures/pdf_fill/686C-674-V2/overflow.json, spec/fixtures/pdf_fill/686C-674-V2/simple.json
- The FE made a change to the attribute name 'type' within current_marriage_information, changing it to 'type_of_marriage'. This PR goes through and modifies the places where 'type' was previously referenced, including unit tests.
- Change 'type' to 'type of marriage' only in the places where v2 could be activated. 
[- *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses Jira*](https://github.com/department-of-veterans-affairs/va.gov-team/i …
=> change to type_of_marriage for v2 scenarios

config/environments/development.rb
- Set log level using environment variable, defaulting to :info.
- Clarify comments for Semantic Logger configurations.
=> refactor: enhance logging and error handling in dev

modules/vaos/config/initializers/flipper.rb, modules/vaos/spec/config/initializers/flipper_spec.rb
- We're updating the DD feature toggle monitoring bahavior to that described in the linked ticket. See checklist in https://github.com/department-of-veterans-affairs/va.gov-team/issues/106095
- Appointments Team
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/106095
N/A
Appointments
=> Update feature toggle monitoring for Appointments on DD

config/features.yml
This PR adds some new feature flags for gating access to the Data Dog Real User Monitoring (RUM) functionality being added in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/36011).
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/106576
- https://github.com/department-of-veterans-affairs/vets-website/pull/36011
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featureto …
=> 106576 - Add new feature flags for IVC real user monitoring - IVC CHAMPVA forms

app/models/form_profiles/va_526ez.rb, app/sidekiq/form0781_state_snapshot_job.rb, config/features.yml, lib/periodic_jobs.rb
- This adds a scheduled job entry for a job made that collects stats for 0781 and sends to datadog from the in progress form records to determine how many of each type of 0781 form are present over time
- 
- This allows for nightly snapshot of stats being able to be sent to DD for a graph.=
- This work is for the Disability team
- Flipper can be removed after 1 month of stat collecting without issue, or at a time it is determined the metric is not needed, this entire job can be disabled
https://github.com/department-of-veterans-affairs/va.gov-team/issues/107511 …
=> Adding scheduled job for 0781 stats (with flipper)

modules/income_and_assets/lib/income_and_assets/pdf_fill/sections/section_06.rb, modules/income_and_assets/lib/income_and_assets/pdf_fill/sections/section_07.rb, modules/income_and_assets/lib/income_and_assets/pdf_fill/va21p0969.rb
Moving Sections 6 and 7 into their own files
- department-of-veterans-affairs/va.gov-team/issues/108357
Tests continue to pass, there are no functional changes introduced in this PR so tests continuing to pass is all that is needed …
=> [Income & Assets] Moving form sections 6 and 7 into their own files

config/features.yml
- adding feature flag for MHV Messaging Milestone 2 AAL
- `mhv_secure_messaging_milestone_2_aal`
- https://jira.devops.va.gov/browse/MHV-70394
- https://github.com/department-of-veterans-affairs/vets-website/pull/36102
- N/A
=> MHV-70394: Add feature flag - MHV SM Milestone 2 AAL 

config/features.yml
I'm adding this flipper so that we cab gate the addition of the MyHealtheVet and MyVA links in the sitewide unauthenticated header expected to release on June 4th, 2025.
Related vets-website PR:
- https://github.com/department-of-veterans-affairs/vets-website/pull/36105
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/4028 …
=> Add mhv header link feature flag

modules/income_and_assets/lib/income_and_assets/pdf_fill/sections/section_05.rb, modules/income_and_assets/lib/income_and_assets/pdf_fill/sections/section_06.rb, modules/income_and_assets/lib/income_and_assets/pdf_fill/va21p0969.rb
Finished moving Section 6 into its own folder (couldn't move all questions out because of LOC changed limit on PRs); Moved Section 5 into its own folder
- department-of-veterans-affairs/va.gov-team/issues/108522
Tests continue to pass, there are no functional changes introduced in this PR so tests continuing to pass is all that is needed
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/f …
=> [Income & Assets] Moving Sections 5 and 6 into separate files

config/features.yml
Adding feature flag `mhv_landing_page_show_share_my_health_data_link`
- department-of-veterans-affairs/va.gov-team#108088
Tested locally
=> [108088] Add feature flag

app/services/bgs/dependent_service.rb, app/sidekiq/bgs/submit_form674_job.rb, app/sidekiq/bgs/submit_form686c_job.rb, config/features.yml, lib/bgs/form674.rb, spec/controllers/v0/dependents_applications_controller_spec.rb, spec/lib/bgs/form674_spec.rb, spec/requests/swagger_spec.rb, spec/services/bgs/dependent_service_spec.rb, spec/sidekiq/bgs/submit_form674_job_spec.rb, spec/sidekiq/bgs/submit_form686c_job_spec.rb
- Removed the :va_dependents_submit674 flipper and references to auto674 that were passed throughout the Dependents process.
- Remove flipper, set everything back to how it was before the flipper was added.
[- *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses Jira*](https://github.com/department-of-veterans-affairs/va.gov-team/issues/108290)
- *Link to epic if not included in …
=> remove auto674 flipper and check

config/features.yml
- Add the `arm_use_datadog_real_user_monitoring feature` feature flag.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/106369
- NA
- NA
Feature flags
=> Add arm_use_datadog_real_user_monitoring feature flag

app/controllers/v0/profile/address_validation_controller.rb, lib/va_profile/v2/contact_information/service.rb, lib/va_profile/v3/address_validation/service.rb, modules/ask_va_api/app/controllers/ask_va_api/v0/address_validation_controller.rb
VAProfile is receiving put/post address requests with address_pou == "RESIDENCE/CHOICE" not "RESIDENCE". Adding logs to determine where the "RESIDENCE/CHOICE" params are coming from.
- department-of-veterans-affairs/va.gov-team/issues/107928 …
=> Added valid_pou logs in staging

lib/va_profile/v2/contact_information/service.rb
This pull request fixes CIV2 logging bugs found in these [logs](https://vagov.ddog-gov.com/logs?query=env%3Aeks-staging%20service%3Avets-api%20status%3Aerror%20%22address_type%22&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=time%2Casc&viz=stream&from_ts=1746025094527&to_ts=1746028694527&live=true).
- [Parent PR](https://github.com/department-of-veterans-affairs/vets-api/pull/21958)
- *Describe what the old behavior was prior to the change* Fixing bugs
- *Describe the steps …
=> Fixed CIV2 logging bugs

app/models/form_profiles/va_686c674v2.rb
…bled
3 months ago, prefill was added to FormProfiles::VA686c674v2. VAProfileRedis::V2::ContactInformation.for_user(user) was added for the mailing address when remove_pciu is enabled. 
- department-of-veterans-affairs/va.gov-team/issues/107928
- …
=> VA686c674v2 - Enable VAProfileRedis::V2::ContactInformation 

modules/income_and_assets/lib/income_and_assets/submissions/monitor.rb, modules/income_and_assets/spec/lib/income_and_assets/benefits_intake/benefit_intake_job_spec.rb, modules/income_and_assets/spec/lib/income_and_assets/submissions/monitor_spec.rb
send 0969 error email
[21P-0969 Action needed email](https://github.com/department-of-veterans-affairs/va.gov-team/issues/106167)
N/A
income and assets
=> PBP 106167 0969 error email

config/settings.yml, config/settings/development.yml, config/settings/test.yml
See https://github.com/department-of-veterans-affairs/checkin-devops/issues/1049
This work is NOT behind a feature toggle.
This removes settings from `settings.yml`, `development.yml`, and `test.yml` that do not appear to be used anymore and have not been used for some time. I am removing them because they are confusing.
I am on the Check-In Experience team, much to their dismay.
Yeah, my team owns this component, but my subteam does not and therefore I need them to double-check my logic. Furthermore I personally disbelieve in the notion of code ownership but rather a loose-knit autonomous collective of like-minded individuals and small cooperative associations freely exchanging code and services with respect for autonomy and freedom basically Proudhon's mutualism but from the safety and …
=> Remove `chip_api` (not `chip_api_v2`) from settings.yml files

lib/va_profile/contact_information/transaction_response.rb, lib/va_profile/v2/contact_information/transaction_response.rb, spec/lib/va_profile/contact_information/transaction_response_spec.rb, spec/lib/va_profile/v2/contact_information/transaction_response_spec.rb
This change redacts sensitive attributes from the message_content field before it is logged. It ensures that PII is removed from application logs to prevent exposure in downstream systems. (Datadog and Sentry)
Example here: https://vagov.ddog-gov.com/logs?query=%22RESIDENCE%2FCHOICE%22&agg_m=count&agg_m_source=base&agg_t=count&clustering_pattern_field_path=message&cols=host%2Cservice&event=AwAAAZaHQtt9LGt9AQAAABhBWmFIUXVnb0FBQUo3OFBLQ25Scl9nSUEAAAAkMDE5Njg3NDMtZjUxZi00NTk0LWJmOWUtOWE4MTdkOWFkMjE2AAiFHg&graphType=service_map&messageDisplay=inline&refresh_mode …
=> Redact logs for VA Profile transaction errors 

lib/va_profile/contact_information/transaction_response.rb, lib/va_profile/v2/contact_information/transaction_response.rb, spec/lib/va_profile/contact_information/transaction_response_spec.rb, spec/lib/va_profile/v2/contact_information/transaction_response_spec.rb
We’re currently focusing on redacting logs specifically where "VAProfile transaction error" appears in the message body. Now that sensitive logs are being properly scrubbed, we want to avoid redacting these safe cases, but we need a reliable way to distinguish them from the truly sensitive logs.
https://github.com/department-of-veterans-affairs/vets-api/pull/21976
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/3948
- *Describe the steps required to verify your changes …
=> Update language for log redaction

app/models/form_profiles/va_0873.rb
Error found while testing for VAProfile. This error is happening when loading certain pages. [Error log](https://vagov.ddog-gov.com/logs?query=%22preferred_name%22%20env%3Aeks-staging&agg_m=count&agg_m_source=base&agg_t=count&clustering_pattern_field_path=message&cols=host%2Cservice&event=AwAAAZaI4GIZXNd7AwAAABhBWmFJNEhUMkFBQUo3OFBLQ2phY2FnQUMAAAAkMDE5Njg5MjQtOWJmOC00MjljLWE2YmEtMmY2MWNjOWFkN2UxAAJ0CQ&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1745502099018&to_ts=1746106899018&live=true). Failsafe should have …
=> BUG: Fixed preferred name bug for va_0873

app/controllers/v0/profile/personal_informations_controller.rb
This PR updates the `PersonalInformationsController` to enhance data sanitization when logging errors related to PII in the MPI response. Specifically, it ensures sensitive fields are redacted from both the `response` and `params` before logging them.
- Added a `sanitize_data` method to redact sensitive fields from the `response` and `params` objects.
- Updated the `log_errors_for` method to use the `sanitize_data` method for sanitizing data before logging to Sentry.
- Ensured that sensitive fields such are excluded from logs to protect PII
This change …
=> redaction: sanitize params and response

app/controllers/v0/profile/personal_informations_controller.rb, lib/va_profile/contact_information/transaction_response.rb, lib/va_profile/v2/contact_information/transaction_response.rb
Additional VA Profile fields have been identified that require redaction from DD logs and Sentry. Redacting these fields aligns with best practices for protecting sensitive data.
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/3948
https://github.com/department-of-veterans-affairs/vets-api/pull/21992
https://github.com/department-of-veterans-affairs/vets-api/pull/21989
https://github.com/department-of-veterans-affairs/vets-api/pull/21976
- *Describe the steps required …
=> Add more redaction fields

config/features.yml
Adding feature flag `mhv_supply_reordering_enabled`
- department-of-veterans-affairs/va.gov-team#102101
Tested locally
=> [102101] Add feature flag mhv_supply_reordering_enabled

modules/income_and_assets/lib/income_and_assets/pdf_fill/sections/section_01.rb, modules/income_and_assets/lib/income_and_assets/pdf_fill/sections/section_02.rb, modules/income_and_assets/lib/income_and_assets/pdf_fill/va21p0969.rb
Moving the last two sections (Sections 1 and 2) into their own files
- department-of-veterans-affairs/va.gov-team/issues/108522
Tests should continue to pass; No new functionality was added here
*(Describe …
=> [Income & Assets] Moving PDF mapping Sections 1 and 2 into separate files

modules/income_and_assets/lib/income_and_assets.rb, modules/income_and_assets/lib/income_and_assets/benefits_intake/submission_handler.rb, modules/income_and_assets/lib/income_and_assets/engine.rb, modules/income_and_assets/spec/lib/income_and_assets/benefits_intake/submission_handler_spec.rb
add received email sending when submission is successful
[21P-0969 Received email](https://github.com/department-of-veterans-affairs/va.gov-team/issues/106166)
N/A
income and assets
=> PBP 106166 0969 received email

Gemfile.lock
Link to `vets-json-schema` PR: https://github.com/department-of-veterans-affairs/vets-json-schema/pull/999
Updates the `vets_json_schema` gem
https://github.com/orgs/department-of-veterans-affairs/projects/1433/views/35?pane=issue&itemId=108646426&issue=department-of-veterans-affairs%7Cva.gov-team%7C108755
- *Link to previous …
=> #108755 [10-10EZR] Updated `vets_json_schema` gem

config/features.yml
vets-website PR: https://github.com/department-of-veterans-affairs/vets-website/pull/36225
=> Create feature toggle for chatbot STS authentication

app/models/va_profile_redis/v2/contact_information.rb, config/features.yml, lib/va_profile/v2/contact_information/service.rb
ContactInformationV2/AddressValidationV3 requires address_pou to be `RESIDENCE` or `CORRESPONDENCE`. 
AddressValidationV3 will throw the error below if RESIDENCE/CHOICE is present in the AddressValidationV3 request.
`lib/va_profile/v3/address_validation/service.rb:62:in 'handle_error': BackendServiceException: {:detail=>{"messages"=>[{"code"=>"ADDRVAL105", "key"=>"InvalidRequestError", "text"=>"The request was invalid. This error cannot be used in conjunction with an address override indicator.", "severity"=>"ERROR"}]}, :code=>"VET360_AV_ERROR"} …
=> Send RESIDENCE/CHOICE to CIV2 when override_address_pou is enabled

config/features.yml
- *This work is behind a feature toggle (flipper): YES/NO* YES
> Adding 2 feature toggles for Intent to File (ITF) changes:
> - Toggle backend API code changes (`pension_itf_enabled`)
> - Toggle frontend Intent to File status alert (`pension_itf_show_alert`)
> Benefits Lifestages/Pension
> Once the ITF API endpoint has been updated & tested, and the frontend has fully released the ITF we will remove the related toggle code and the toggles themselves. …
=> Pension | Add Intent to File toggles

config/settings.yml
env vars are not populated as settings under certain conditions
- https://dsva.slack.com/archives/CBU0KDSB1/p1746213485542429
=> Fix app_token configuration for MHV UHD by applying dump method

app/services/identity/cerner_provisioner.rb, spec/services/identity/cerner_provisioner_spec.rb
- Update cerner provisioner source
=> Update cerner provisioner

app/models/evss_claim_document.rb, app/models/lighthouse_document.rb, lib/lighthouse/benefits_documents/configuration.rb, spec/lib/lighthouse/benefits_documents/configuration_spec.rb, spec/lib/lighthouse/benefits_documents/service_spec.rb, spec/services/evss_claim_service_spec.rb
Reverts department-of-veterans-affairs/vets-api#21918
There were sidekiq errors. I reported them here: https://dsva.slack.com/archives/C04KHCT3ZMY/p1746552735655099
=> Revert "Replace Virtus with Vets::Model - Model Docs"

modules/claims_api/app/sidekiq/claims_api/one_off/poa_v1_bad_box20_render_report_job.rb, modules/claims_api/spec/factories/power_of_attorney.rb, modules/claims_api/spec/sidekiq/one_off/poa_v1_bad_box20_render_report_job_spec.rb
Further discussion had us deciding to broaden the scope of what to report (and eventually regenerate) on.
SEE #22044 for initial commit.
=> API-46261 Fix filtering logic for report job

config/features.yml, config/settings.yml, config/settings/development.yml, config/settings/test.yml, modules/debts_api/app/sidekiq/debts_api/v0/form5655/send_confirmation_email_job.rb, modules/debts_api/lib/debts_api/v0/financial_status_report_service.rb, modules/debts_api/spec/lib/debt_api/v0/financial_status_report_service_spec.rb, modules/debts_api/spec/sidekiq/debt_api/v0/send_confirmation_email_job_spec.rb
- *This work is behind a feature toggle (flipper): YES/NO* YES
- *(Summarize the changes that have been made to the platform)*: As part of the Zero Silent failure initiative we're bringing our in progress email(s) into compliance/consistency with the rest of the forms on the platform.
- *(What is the solution, why is this the solution?)*: The solution here is to queue the email a few min. before the form 
- *Link to ticket created in va.gov-team: https://github.com/department-of-veterans-affairs/va.gov-team/issues/107089
- *Link to previous change of the code/bug (if applicable)*: N/A
- …
=> 107089 Financial Management Zero Silent Error in progress email

lib/mhv/aal/configuration.rb, modules/my_health/app/controllers/my_health/v1/health_records_controller.rb, modules/my_health/docs/openapi.yaml, modules/my_health/docs/openapi_merged.yaml, modules/my_health/spec/requests/my_health/v1/medical_records/health_records_spec.rb, spec/support/vcr_cassettes/mr_client/post_opt_in.yml, spec/support/vcr_cassettes/mr_client/post_opt_in_error.yml, spec/support/vcr_cassettes/mr_client/post_opt_out.yml, spec/support/vcr_cassettes/mr_client/post_opt_out_error.yml
- Added logging for opting in and out of VHIE sharing, including success and error case.
- Fixed an unrelated indentation error with openapi.yml and regenerated the merged file.
> Add Opt In/Out AAL entries for Sharing settings
> 
>  
>  1- Add 2 entries for Opt in/Opt out
> AAL requirement spreadsheet: See lines 33 and 34 - purple highlight
> 
> https://dvagov.sharepoint.com/:x:/r/sites/HealthApartment/_layouts/15/Doc.aspx?sourcedoc=%7B80534FA8-97C2-4726-9E08-20166C9609DF%7D&file=AAL%20work%20to%20be%20done-VHA%20Privacy%20Office%20additions.xlsx&action=default&mobileredirect=true 
> 
> Classic view:   
> 
> Approved content for all MR domains on va.gov is as follows:
> 
> Date/Time = Completion_Time
> 
> Activity Details = Detail_Value
> 
> Activity = Activity_Type
> 
> Action = Action …
=> MHV-69452 Added AAL logs for sharing

db/schema.rb, modules/accredited_representative_portal/app/models/accredited_representative_portal/power_of_attorney_request.rb, modules/accredited_representative_portal/db/migrate/20250430165128_add_redacted_at_to_ar_power_of_attorney_requests.rb, modules/accredited_representative_portal/db/migrate/20250430165129_add_redacted_at_index_to_ar_power_of_attorney_requests.rb
This PR introduces schema changes to the `ar_power_of_attorney_requests` table:
-   Adds a new `redacted_at` column (datetime).
-   Adds a database index on the new `redacted_at` column.
These changes are necessary to support the PII redaction functionality being introduced for Power of Attorney (POA) requests.
-   The `redacted_at` timestamp will track when a request's PII has been removed.
-   The index will allow efficient querying of requests based on their redaction status (e.g., finding records needing redaction or already redacted).
-   **Migration 1:** Adds the `redacted_at` column (`datetime`, nullable).
-   **Migration 2:** Adds an index on `redacted_at` using `algorithm: :concurrently`. This ensures the index is built without locking the table, preventing downtime during …
=> feat(arp): Add redacted_at field and index for POA request redaction

app/models/saved_claim.rb, config/features.yml, spec/models/saved_claim_spec.rb
- Updated `reformatted_schemer_errors` to only return attributes that we know do not have potential to contain pii/phi when returning errors from a `SavedClaim` that has thrown a validation error.  …
=> Filter attributes that are logged when SavedClaim returns validation errors

app/controllers/concerns/vet360/writeable.rb, app/controllers/v0/profile/addresses_controller.rb, lib/va_profile/models/v3/address.rb, lib/va_profile/models/v3/base_address.rb, lib/va_profile/v2/contact_information/service.rb, lib/va_profile/v3/address_validation/address_suggestions_response.rb, modules/ask_va_api/spec/requests/ask_va_api/v0/address_validation_spec.rb, modules/mobile/app/controllers/mobile/v0/addresses_controller.rb, spec/controllers/v0/profile/address_validation_controller_spec.rb, spec/factories/va_profile/v3/addresses.rb, spec/lib/va_profile/v3/address_validation/service_spec.rb, spec/support/vcr_cassettes/va_profile/v2/contact_information/put_address_override.yml, spec/support/vcr_cassettes/va_profile/v2/contact_information/put_address_success.yml
During the VAProfile integration testing, a bug was discovered related to parameter deprecations in ContactInfoV2. Specifically, `validation_key` and `overrideIndicator` were deprecated, and `override_validation_key` is now required for address validation. The parameter handling logic was updated to support `override_validation_key` when ContactInfoV2 is active, including relevant edge cases.
VCR cassettes were updated. Specs were updated.
- *Link to previous …
=> Replaced CIV2 validation_key with override_validation_key

modules/accredited_representative_portal/db/migrate/20250430165129_add_redacted_at_index_to_ar_power_of_attorney_requests.rb
This commit adds an index to the `redacted_at` column of the `ar_power_of_attorney_requests` table.
Adding this index will improve the performance of queries that filter or order by the `redacted_at` column, particularly when retrieving redacted power of attorney requests.
The index is created concurrently to avoid locking the table during the operation. It also includes a check to prevent attempting to add the index if it already exists.
- *(Summarize the changes that have been made to the …
=> Add index to ar_power_of_attorney_requests.redacted_at

lib/bpds/sidekiq/submit_to_bpds_job.rb
- Fixes a bug where `reference_data` was being incorrectly referenced in a `find_or_create_by` call. The field name should be `reference_data_ciphertext`. Also added a short circuit in the job to prevent duplicate submissions to BPDS.
- Running `BPDS::Sidekiq::SubmitToBPDSJob.perform` on a saved claim will cause the error currently on Staging.
- Pension Burial Program team to own this change.
- [*Link to ticket created in va.gov-team repo*](https://github.com/department-of-veterans-affairs/va.gov-team/issues/109137)
- *If …
=> Fixed reference_data column and short circuit for already submitted claims

app/controllers/concerns/vet360/writeable.rb, lib/va_profile/models/v3/address.rb, lib/va_profile/models/v3/base_address.rb, spec/factories/va_profile/v3/addresses.rb, spec/support/vcr_cassettes/va_profile/v2/contact_information/put_address_override.yml, spec/support/vcr_cassettes/va_profile/v2/contact_information/put_address_success.yml
Address Validation key is required for UI logic. 
- *Tests need to be written for both the flipper on and …
=> Added validationKey to V3 address for UI

app/controllers/v0/profile/direct_deposits_controller.rb, app/controllers/v0/profile/email_addresses_controller.rb, app/controllers/v0/profile/payment_history_controller.rb, app/controllers/v0/profile/personal_informations_controller.rb, app/models/adapters/payment_history_adapter.rb
There are many errors in DataDog that are lacking information for further debugging or for efficient investigation.
*Team:* Authenticated Experience/MyVA&Profile
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/108179
- We can look at DataDog to confirm the logs are showing.
=> Improve logging for MyVA and Profile #108179

lib/va_profile/models/v3/address.rb, lib/va_profile/v3/address_validation/address_suggestions_response.rb, modules/ask_va_api/spec/requests/ask_va_api/v0/address_validation_spec.rb, spec/controllers/v0/profile/address_validation_controller_spec.rb, spec/lib/va_profile/v3/address_validation/service_spec.rb
Sending validation_key in the AddressSuggestionResponse to fix UI issues in staging. ContactInfoV1 required validation_key, where as ContactInfoV2 requires override_validation_key. The validation_key param is heavily referenced in the front end and it's best to ensure the VAProfile integration is working before modifying the front end. …
=> Return validation_key in the AddressSuggestionResponse

app/models/adapters/payment_history_adapter.rb
Fixing this [error](https://vagov.ddog-gov.com/apm/traces?query=%40_top_level%3A1%20env%3Aeks-prod%20pod_name%3Avets-api-long-timeout-%2A%20status%3Aerror%20-service%3A%28vets-api-net-http%20OR%20vets-api%29&agg_m=count&agg_m_source=base&agg_q=%40error.message&agg_q_source=base&agg_t=count&cols=service%2Cresource_name%2C%40duration%2C%40http.method%2C%40http.status_code%2C%40_duration.by_service&fromUser=false&graphType=flamegraph&historicalData=true&shouldShowLegend=true&sort=time&spanID=1660946042428000883&spanType=service-entry&spanViewType=errors&storage …
=> Fixiing dig error in AdaptersPayHistory

app/controllers/concerns/vet360/writeable.rb, lib/va_profile/models/v3/address.rb, lib/va_profile/models/v3/base_address.rb
The validation_key issue will be fixed in this [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/109399) after the ContactInformationV2 release. For now, the validation_key will be added to VAProfile::Models::V3::Address' attributes for UI purposes only. 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/109399
- *Describe the steps required to …
=> Added validation_key attribute to VAProfile::V3::Address

lib/bgs/form686c.rb
- The v2/v1 check was not wrapped in parentheses, causing a logic bug that defaulted claims to manual. Fix wraps them in parentheses.
[- *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses Jira*](https://github.com/department-of-veterans-affairs/va.gov-team/issues/109479) …
=> wrap logic in parens to fix bug

app/controllers/concerns/vet360/writeable.rb, lib/va_profile/models/v3/address.rb, lib/va_profile/v2/contact_information/service.rb, spec/support/vcr_cassettes/va_profile/v2/contact_information/put_address_override.yml, spec/support/vcr_cassettes/va_profile/v2/contact_information/put_address_success.yml
Sending override indicator for V2 Contact Information for the VAProfile integration. …
=> Sending override indicator for V2 Contact Information

lib/va_profile/models/v3/address.rb, spec/support/vcr_cassettes/va_profile/v2/contact_information/put_address_override.yml, spec/support/vcr_cassettes/va_profile/v2/contact_information/put_address_success.yml
Trying to target the UI issue. …
=> Attempting to provide validationKey to UI

.github/workflows/settings_checks.yml, config/settings.yml
- Checks a setting's corresponding Parameter based on the ENV 
- Expects a Parameter for each environment
- Adds a `settings-failure` label if missing parameters are found
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/103236
- Example comments in this PR
- [Failing Run Example](https://github.com/department-of-veterans-affairs/vets-api/actions/runs/14597354489/job/40946565691?pr=21794)
- [Passing Run Example](https://github.com/department-of-veterans-affairs/vets-api/actions/runs/14597549016/job/40947219077?pr=21794)
=> Add SSM validation to GHA Settings Check

app/services/medical_copays/vbs/service.rb, config/features.yml, spec/services/medical_copays/vbs/service_spec.rb
- *This work is behind a feature toggle (flipper): YES/NO*: No
- *(Summarize the changes that have been made to the platform)*: We are cleaning up our Flippers to reduce tech debt and make the code easier to reason about. This is one of about 6 Flippers that will be getting removed.
- *(What is the solution, why is this the solution?)*: We have a lot of code, especially specs, that get cumbersome with this and other fllippers. We are at 100% for this and other flippers so we are on a mission to remove them.
- *(Which team do you work for, does your team own the maintenance of this component?)*: Financial Mangagement/"Debt resolution" …
=> 92821 Financial Management - Remove Copay Cache Flipper

config/features.yml
- *This work is behind a feature toggle (flipper): YES/NO* YES `va_dependents_browser_monitoring_enabled`
> Benefits Lifestages / Dependents Management Team
> To toggle Datadog RUM/Logging - indefinite
> https://github.com/department-of-veterans-affairs/va.gov-team/issues/87048
- …
=> Dependents | Add monitor toggle

lib/va_profile/v2/contact_information/transaction_response.rb
This [error](https://vagov.ddog-gov.com/logs?query=env%3Aeks-prod%20service%3Avets-api%20%22undefined%20method%20%60country_code_iso3%27%22&agg_m=count&agg_m_source=base&agg_t=count&clustering_pattern_field_path=message&cols=host%2Cservice%2C%40http.referer%2C%40named_tags.dd.version&graphType=flamegraph&messageDisplay=inline&refresh_mode=sliding&sort=time&spanID=1916012904192703251&storage=hot&stream_sort=time%2Casc&viz=stream&from_ts=1745947312550&to_ts=1747156912550&live=true) started surfacing not long after this …
=> Removed null country_code_iso3 from transaction logs

db/seeds/development.rb
- This PR updates the Chatbot STS configuration seed file on localhost so that it properly matches the configuration behavior Chatbot will need to carry out the STS authentication
=> Update Chatbot seeds

config/settings.yml
- The `bpds.url` setting was previously hardcoded to the `localhost:4000` domain. This setting was updated to point to the environment variables stored in the parameter store.
- Pension and Burial Benefits team to own this work.
- [*Link to ticket created in va.gov-team repo*](https://github.com/department-of-veterans-affairs/va.gov-team/issues/109457)
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/de …
=> update url in settings to point to env variable

lib/va_profile/v2/contact_information/service.rb
VAProfile is reporting double requests for contact information. Email and phone numbers were request logs were added to the ContactInformationV2 service …
=> Log all ContactInformationV2 requests to debug double requests to VAProfile

modules/debts_api/app/models/debts_api/v0/form5655_submission.rb, modules/debts_api/spec/lib/debt_api/v0/financial_status_report_service_spec.rb, modules/debts_api/spec/models/debt_api/v0/form5655_submission_spec.rb, modules/debts_api/spec/sidekiq/debt_api/v0/vba_submission_job_spec.rb, modules/debts_api/spec/sidekiq/debt_api/v0/vha/vbs_submission_job_spec.rb
- *This work is behind a feature toggle (flipper): YES/NO*: No
- *(Summarize the changes that have been made to the platform)*: We are clearing out unneeded flippers. This is for the silent error email for the 5655.
- *(What is the solution, why is this the solution?)*: Simple PR to get rid of conditionals/tech debt
- *(Which team do you work for, does your team own the maintenance of this component?)*: Financial Management
- *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses Jira*: https://github.com/department-of-veterans-affairs/va.gov-team/issues/92821
- *Link to previous change of the code/bug (if applicable)*: N/A
- *Link to …
=> 92821 Financial Management remove failure mailer flipper

lib/va_profile/models/v3/address.rb, spec/support/vcr_cassettes/va_profile/v2/contact_information/put_address_override.yml, spec/support/vcr_cassettes/va_profile/v2/contact_information/put_address_success.yml
The validationKey and overrideIndicator were deprecated in CIV2. These do not need to be added. These parameters were added when debugging UI issues. …
=> Removed validationKey parameter for VAProfile CIV2 requests

modules/ivc_champva/app/controllers/ivc_champva/v1/uploads_controller.rb, modules/ivc_champva/spec/requests/ivc_champva/v1/forms/uploads_spec.rb
- *This work is behind a feature toggle (flipper):NO*
- fix for 'undefined method `uniq` for `nil`'
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/103133 …
=> 103133 uniq nil fix

modules/accredited_representative_portal/app/policies/accredited_representative_portal/claimant_policy.rb
This fixes a bug on the claimant search page where PoA verification was being sent a whole claimant object instead of the expected ICN, so the page was not returning any results.
Log into ARP, Searching for a claimant will not return any results.
This code overrides `ClaimantPolicy` so that the `ValidatePowerOfAttorney` has the correct ICN to submit to Lighthouse for service org verification. (it was previously sending an object that could not be converted)
- *(Which team do you work for, does your team own the maintenance of this component?)* ARF
- *(If introducing a flipper, …
=> Claimant search bugfix - PoA LH verify had wrong object

config/betamocks/services_config.yml, modules/vaos/app/services/eps/appointment_service.rb
- Complete EPS mocks.
- Updated payload to create draft appointment to have the referral number in the correct place. Note this is a just a nice to have as the call works fine, but we want to match the EPS spec.
These code changes go with the updated mocks in https://github.com/department-of-veterans-affairs/vets-api-mockdata/pull/608
https://github.com/department-of-veterans-affairs/va.gov-team/issues/109292
1. Turn on the mocks in `config/settings/development.yml`. You will need to change the mock setting to true for `vaos.ccra.mock` and `vaos.eps.mock`
2. Comment out the following lines in `modules/vaos/app/services/vaos/v2/appointments_service.rb` to bypass the calls for VAOS appointments which have no …
=> Complete VAOS EPS mocks

db/schema.rb, modules/accredited_representative_portal/db/migrate/20250515213037_add_declination_reason_to_ar_power_of_attorney_request_decisions.rb
- This PR adds the `declination_reason` field to `ar_power_of_attorney_request_decisions` table.
- Ticket - https://github.com/department-of-veterans-affairs/va.gov-team/issues/105559
- Follow-on PR - https://github.com/department-of-veterans-affairs/vets-api/pull/21820
- NA (this is a database migration) …
=> Add declination_reason field to ar_power_of_attorney_request_decisions table

config/features.yml
- This PR adds a new feature flag for future use. This feature flag will be used to gate changes that will work to add a special issue to contentions/claims that have claims for MST. 
- https://github.com/department-of-veterans-affairs/abd-vro/issues/4322
- …
=> Adds new feature flag for MST Special Issue

config/features.yml
Just renaming a feature flag so it's more descriptive and accurate
- *This work is behind a feature toggle (flipper): YES/NO* 
- uhhhh no? 
- Renaming a feature flag
- ~~*(If bug, how to reproduce)*~~
- Renaming feature flag to be slightly more specific
- Financial Management  
- *(If introducing a flipper, what is the success criteria being targeted?)* 
- Planning to remove the feature toggle once we're live for a bit and nothing is broken …
=> [CDP] 107662 - Updating one thing per page feature flag name

modules/ivc_champva/app/controllers/ivc_champva/v1/uploads_controller.rb, modules/ivc_champva/spec/requests/ivc_champva/v1/integration/upload_data_transformation_spec.rb
- Integration test for e2e data transformation logic from request json to database
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/108704 …
=> 108704 db data transformation tests

.github/CODEOWNERS, app/controllers/concerns/filterable.rb, app/models/eligible_data_class.rb, app/models/prescription.rb, app/models/prescription_details.rb, app/models/prescription_preference.rb, app/models/tracking.rb, app/services/mhv_account_type_service.rb, lib/bb/client.rb, lib/rx/client.rb, modules/mobile/app/controllers/mobile/v0/prescriptions_controller.rb, modules/mobile/spec/requests/mobile/v0/health/rx/prescriptions_spec.rb, modules/my_health/app/controllers/my_health/v1/prescription_documentation_controller.rb, modules/my_health/app/controllers/my_health/v1/prescriptions_controller.rb, modules/my_health/app/helpers/my_health/prescription_helper.rb, modules/my_health/app/helpers/my_health/rx_grouping_helper.rb, modules/my_health/app/serializers/my_health/v1/prescription_details_serializer.rb, spec/lib/bb/client_spec.rb, spec/lib/rx/client_spec.rb, spec/models/prescription_details_spec.rb
Reverts department-of-veterans-affairs/vets-api#21981
=> Revert "Replace Virtus with Vets::Model - Prescriptions"

app/controllers/concerns/filterable.rb, app/models/all_triage_teams.rb, app/models/attachment.rb, app/models/folder.rb, app/models/message.rb, app/models/message_draft.rb, app/models/message_search.rb, app/models/message_thread.rb, app/models/message_thread_details.rb, app/models/messaging_preference.rb, app/models/messaging_signature.rb, app/models/triage_team.rb, lib/sm/client.rb, modules/mobile/app/controllers/mobile/v0/messages_controller.rb, modules/mobile/app/controllers/mobile/v1/messages_controller.rb, modules/mobile/spec/requests/mobile/v0/messaging/health/folders_spec.rb, modules/mobile/spec/requests/mobile/v1/messaging/health/messages_spec.rb, modules/my_health/app/controllers/my_health/v1/messages_controller.rb, modules/my_health/spec/requests/my_health/v1/messaging/messages_spec.rb, spec/lib/sm/client/folders_spec.rb, spec/lib/sm/client/messages_spec.rb, spec/lib/sm/client/triage_teams_spec.rb, spec/models/folder_spec.rb, spec/models/message_spec.rb, spec/models/triage_team_spec.rb
Reverts department-of-veterans-affairs/vets-api#21991
=> Revert "Replace Virtus with Vets::Model - Messages"

config/settings.yml, config/settings/development.yml, config/settings/test.yml, modules/mobile/app/controllers/mobile/v0/maintenance_windows_controller.rb
- Updated the Mobile maintenance windows controller to include travel_pay in the service graph to return to the FE
- Updated the Settings files to point to the AWS param store for maintenance window IDs based on environment
- Need to also return the maintenance window to the Mobile app FE, so needed to add it to the return
- Also need to be able to test it in Staging, so added a separate Staging ID in Pager Duty and implemented AWS to store the value so `vets-api` can pull it in based on the env
- Travel Pay
- *Link to ticket …
=> Travel pay / Update Mobile service graph & settings values

.github/CODEOWNERS
A number of old team labels were in use (`disability-experience`, `dbex-trex`, `benefits-disability2`, etc.) when ideally there is a uniform team label (`disability-benefits`) that should be used to represent our team. This PR replaces the various old team labels with the [consolidated `disability-benefits` label](https://github.com/orgs/department-of-veterans-affairs/teams/disability-benefits/teams)
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/109118 …
=> 109118 Consolidate old CODEOWNERS team labels with new one

config/initializers/breakers.rb
reverts https://github.com/department-of-veterans-affairs/vets-api/pull/22284
=> remove debugging statement

config/initializers/breakers.rb
fixes staging. reverts https://github.com/department-of-veterans-affairs/vets-api/pull/22250
=> delete debugging block in breakers

rakelib/extract_pdf_fields.rake
- Updating example of rake task description to escape file
- comment update
- comment update
=> [10-10EZ] Update PDF fields rake task example

.github/workflows/require_be_approval.yml
Succeed if backend approval is confirmed workflow is required for all pull requests. Other teams, like Identity, should be able to review their own pull requests. …
=> Fixing required workflow

.github/workflows/ready_for_review.yml
This will ensure that only one run of the "Ready for review" is active per branch, and any in-progress runs will be automatically cancelled when a new one starts on the same branch for the same workflow. Ready for Review workflow is triggered each time another workflow succeeds. This will stop the Ready for Review job until the latest one passes.
- *Describe …
=> Cancel in-progress Ready for Review workflows on the same branch

modules/claims_api/app/sidekiq/claims_api/one_off/poa_v1_pdf_gen_fixup_job.rb, modules/claims_api/spec/sidekiq/one_off/poa_v1_pdf_gen_fixup_job_spec.rb, modules/claims_api/spec/sidekiq/v2/disability_compensation_docker_container_upload_spec.rb
Removes code paths we didn't want & skips lookup of POA codes we know were approved before.
Also, logs on successes so we're not left guessing whether the job completed or failed.
[API-46261](https://jira.devops.va.gov/browse/API-46261)
* Nothing consumer facing.
=> API-46261 Refactor One-off PDF resubmit job

.github/workflows/code_checks.yml
6 months ago, the status output was added to the "test" run. This has been removed due to flakiness.
- *Tests …
=> Removed status output for test failures

config/features.yml
- Mitigating risk of MapBox being impact by 5/31 if contract isn't found to pay for it's usage amongst teams per vfs-all-teams Slack chat
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-Backendexample) …
=> GI CT MapBox mitigation feature flag added

config/settings.yml, config/settings/development.yml, config/settings/test.yml, modules/vaos/app/services/vaos/v2/appointments_service.rb, spec/support/vcr.rb, spec/support/vcr_cassettes/vaos/v2/appointments/get_appointments_200.yml, spec/support/vcr_cassettes/vaos/v2/appointments/get_appointments_200_v2.yml, spec/support/vcr_cassettes/vaos/v2/appointments/get_appointments_200_with_partial_errors.yml, spec/support/vcr_cassettes/vaos/v2/appointments/get_appointments_200_with_partial_errors_v2.yml
- *This work is behind a feature toggle (flipper): YES, FE access blocked by feature flag
- Updates appointments fetch params in appointment draft creation flow to search for appointments over a 2 year range instead of 200, which was the placeholder for testing. 
These appointments are checked to see if the referral number has already been utilized to create an appointment, but it is unclear just how wide a date range we should be checking. 
Note: see the linked issue for details on the error returned by the POST request to `/appointments/draft` on staging, I'm assuming that since it identified only the end date as being invalid I think it means that either the date being sent was too far in the future and not invalid formatting because it does not mention issue with the start date, but …
=> 110479 update appts fetch params

modules/accredited_representative_portal/app/controllers/concerns/accredited_representative_portal/v0/representative_form_upload_concern.rb
Small fix for ARP `RepresentativeFormUploadController` to test a theory that we are getting empty params for claimant info on staging which is overriding veteran info.
=> Small fix for representative form upload

db/migrate/20250523210208_add_unique_index_to_banners_entity_id.rb, db/schema.rb
Index for uniqueness was created.
Rubocop error:
```
app/models/gibs_not_found_user.rb:8:3: C: Rails/UniqueValidationWithoutIndex: Uniqueness validation should have a unique index on the database column.
validates :edipi, presence: true, uniqueness: true
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app/models/invalid_letter_address_edipi.rb:4:3: C: Rails/UniqueValidationWithoutIndex: Uniqueness validation should have a unique index on the database …
```
=> Created AddUniqueIndexToBannersEntityId

modules/mobile/app/controllers/mobile/v0/letters_controller.rb, modules/mobile/spec/requests/mobile/v0/letters_spec.rb
According to [THIS](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/8812) issue, VHA member service has requested two letter types (`Proof of Minimum Essential Coverage Letter` and `Proof of Creditable Prescription Drug Coverage Letter`) be filtered out due to them containing incorrect/outdated data. This change introduces a filter on the mobile letters controller to do just that.
- *This work is behind a feature toggle (flipper): ~~YES~~/NO*
Mobile `Letters#index` call now contains a filter on the types of letters being returned that removes the "offending" letter types.
Sign into app and go to benefits -> letters section. Letter download list should show the problematic …
=> Filter letters with outdated content on Mobile

lib/source_app_middleware.rb
FIXING BREAKING ISSUES IN PROD WHILE ON CALL.
This [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/36868/files) was pushed 5 hours ago causing issues in prod. Monitor [here](https://vagov.ddog-gov.com/monitors/200229?eval_ts=1748894529000&event_id=8130766596175995431&link_source=monitor_notif&from_ts=1748893329000&to_ts=1748894529000). The app name is currently in Vets-API. I dug around and the PR contains `, entryName: …
=> Oncall - Fixing prod - Added Survivor and Dependent Benefits 22-5490

modules/travel_pay/app/controllers/travel_pay/v0/claims_controller.rb
…odError: undefined method []= for nil
- *Link to ticket created in va.gov-team repo OR …
=> Resolved Could not log process_action.action_controller event. 

.github/workflows/audit_service_tags.yml, .github/workflows/code_checks.yml, .github/workflows/codeql-analysis.yml, .github/workflows/ready_for_review.yml, .github/workflows/require_be_approval.yml
The required-be-approval workflow is failing for some pull requests due to detached HEAD states in GitHub Actions or forked PRs. When a pull request is marked "Ready for review," the associated workflows become untraceable because GitHub Actions defaults to checking out the PR as a detached merge commit rather than the actual branch.
As a result:
- The workflow cannot locate runs by PR number, SHA, or branch name.
- This issue is more common with forked PRs, …
=> Resolve remote branch issues in Github Workflows

modules/accredited_representative_portal/app/controllers/accredited_representative_portal/v0/representative_form_upload_controller.rb, modules/accredited_representative_portal/app/controllers/concerns/accredited_representative_portal/v0/representative_form_upload_concern.rb, modules/accredited_representative_portal/config/initializers/bypass_olive_branch.rb
[Datadog log entry](https://vagov.ddog-gov.com/logs?query=trace_id%3A1786331292589492272&agg_m=count&agg_m_source=base&agg_t=count&clustering_pattern_field_path=message&cols=host%2Cservice&event=AwAAAZc31Yx36hbBygAAABhBWmMzMVphS0FBQ3hSOEVuRVNVSE1nQUMAAAAkMDE5NzM3ZDUtYWRjMC00NjliLWFhMzktODkwOTYxN2Y0YjJiAAACbA&fromUser=true&messageDisplay=inline&refresh_mode=paused&storage=hot&stream_sort=desc&viz=stream&from_ts=1748987531551&to_ts=1748988532355&live=false)
=> [ARP] Remove `arp_olive_branch_debugging`

.github/CODEOWNERS
Updated CODEOWNERS file for MBS-selfserv
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guid …
=> Updated CODEOWNERS file for preneed

Gemfile.lock
- Bumping vets-json-schema version
- https://github.com/department-of-veterans-affairs/vets-json-schema/pull/1010
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/26248
_Note: …
=> Bump vets-json-schema

modules/claims_api/app/mailers/claims_api/submission_report_mailer.rb, modules/claims_api/app/mailers/claims_api/unsuccessful_report_mailer.rb, modules/claims_api/spec/mailers/report_monthly_submissions_spec.rb, modules/claims_api/spec/mailers/unsuccessful_report_mailer_spec.rb
- Update e-mail recipients for report
- https://jira.devops.va.gov/browse/API-45822
(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific …
=> [API-45822] Update recipients for benefits claims api report

modules/travel_pay/app/services/travel_pay/claim_association_service.rb, modules/travel_pay/app/services/travel_pay/claims_client.rb, modules/travel_pay/spec/services/claims_association_service_spec.rb, modules/travel_pay/spec/services/claims_client_spec.rb
Reverts department-of-veterans-affairs/vets-api#22689
=> Revert "Travel Pay / update default page size to 50 for claim association logic"

modules/vaos/app/controllers/vaos/v2/referrals_controller.rb, modules/vaos/spec/controllers/v2/referrals_controller_spec.rb, modules/vaos/spec/requests/v2/referrals_spec.rb
- *This work is behind a feature toggle (flipper): YES - behind FE feature flag
Adds metric to the referral details page endpoint.
https://github.com/orgs/department-of-veterans-affairs/projects/1323/views/35?pane=issue&itemId=108440402&issue=department-of-veterans-affairs%7Cva.gov-team%7C108605
=> 108605 CC metrics referral details page

modules/vye/spec/sidekiq/vye/sundown_sweep_spec.rb
A background job has a check for holidays so it doesn't run when no one is working. This holiday check was causing an issue with the specs which started failing on holidays. This PR should fix that. …
=> make sure holiday? check does not interfere with vye spec

config/betamocks/services_config.yml, lib/debt_management_center/base_service.rb, modules/debts_api/app/controllers/debts_api/v0/digital_disputes_controller.rb, modules/debts_api/lib/debts_api/v0/digital_dispute_submission_service.rb, modules/debts_api/lib/debts_api/v0/financial_status_report_service.rb, modules/debts_api/spec/lib/debt_api/v0/digital_dispute_submission_service_spec.rb, spec/requests/swagger_spec.rb
- *This work is behind a feature toggle (flipper):* YES
- *(Summarize the changes that have been made to the platform)*: We are working on releasing our "Digital Dispute" feature 🥳 . This PR adds the request between vets-api and Debt Management Center "DMC". This is an existing integration with a new endpoint.
- *(What is the solution, why is this the solution?)*: This is necessary to transmit the Veteran's information to …
=> 111124 Financial Management API connection to Debt Management Center

config/features.yml
This pull request introduces a new feature flag to the `features.yml` configuration file. The flag enables a spouse confirmation flow for a specific form.
* [`config/features.yml`](diffhunk://#diff-f18a5a886f542bf641d21c158c938069d78f4cb6c367b85289c3667616b7eba2R211-R214): Added `ezr_spouse_confirmation_flow_enabled` feature flag to enable the spouse (V2) confirmation flow in the 10-10EZR form. This flag is enabled in development environments.
- department-of-veterans-affairs/va.gov-team/issues/112609
Tested flipper is available on local.
10-10EZR form eventually.
=> 10-10EZR: Adds feature toggle for spouse confirmation flow.

lib/form1010_ezr/veteran_enrollment_system/associations/reconciler.rb, spec/lib/form1010_ezr/veteran_enrollment_system/associations/reconciler_spec.rb
1. Checks for both `relationType` and `relationship` in the `Reconciler` class. After testing on staging, there are instances where `relationType` can be nil, even though it's a required field for updating and deleting records in the VES Associations API
https://github.com/orgs/department-of-veterans-affairs/projects/1433/views/3 …
=> #112640 [10-10EZR] Add code to `Reconciler` class that accounts for missing `relationType` from VES DB

modules/debts_api/app/controllers/debts_api/v0/digital_disputes_controller.rb, modules/debts_api/lib/debts_api/v0/digital_dispute_submission_service.rb
- *(Summarize the changes that have been made to the platform)*: Found a bug where we were simply missing the Debts config for our request to Debt Management Center (DMC).
- *(If bug, how to reproduce)*: Submitting form via vets-website
- *(What is the solution, why is this the solution?)*: We were getting an error "undefined method 'instance' for nil class". This fixes that error. This adds a config we were missing in our service. We've just now been able to test this end to end using an in progress PR in vets-website.
- *(Which team do you work for, does your team own the maintenance of this component?)*: Financial Management. You can find us at #financial-management on OCTO slack
- *(If introducing a flipper, what is the success …
=> 111124 BUGFIX Digital Dispute connection to DMC

app/models/form526_submission.rb, spec/models/form1010cg/attachment_spec.rb, spec/models/form526_submission_spec.rb, spec/support/disability_compensation_form/submissions/with_duplicate_uploads.json, spec/support/disability_compensation_form/submissions/with_many_duplicate_uploads.json
This change spaces out uploads further apart for each claim. It also spaces apart duplicates, further apart still.
All files are going from `15s` apart, to `60s` apart. Any files that are a duplicate are moving to `N*5m` apart, where `N` is the number duplicate. IE first dupicate is `5m` from the original upload, second duplicate is `10m` away from the original, etc
- *This work is behind a feature toggle (flipper): 
- No
- This change is to spread the load out of uploads to Lighthouse who is resource constrained and having issues
- This aims to reduce the number of time LH documents api hit OOM and dies. 
- *(Which team do you work for, does your team own the maintenance …
=> Increase 526 submission upload delay to reduce impact on LH Benefits Documents API

lib/pdf_fill/forms/va2210215.rb
- *This work is behind a feature toggle (flipper): YES/NO* no
- *(Summarize the changes that have been made to the platform)* Fix decimal issue where it wasnt showing decimal up 
- *(If bug, how to reproduce)* Before, was not showing any decimals
- *(What is the solution, why is this the solution?)* Add lines to keep up to 2 decimals
- *(Which team do you work for, does your team own the maintenance of this component?)* VEBT
- *(If introducing a flipper, what is the success criteria being targeted?)* show 2 decimals
- *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses Jira* https://jira.devops.va.gov/browse/VEBT-2237
- *Link to previous change of the code/bug (if applicable)* https://jira.devops.va.gov/browse/VEBT-2324
- *Link to epic if not …
=> VEBT 2237: Fix decimal in 10215

modules/accredited_representative_portal/app/serializers/accredited_representative_portal/claimant_serializer.rb, modules/accredited_representative_portal/spec/requests/accredited_representative_portal/v0/claimant_request_spec.rb
In ARP claimant search serializer, order PoA requests so that pending results are first, then by date
https://github.com/department-of-veterans-affairs/va.gov-team/issues/107098 …
=> Order PoA requests in claimant search

modules/test_user_dashboard/db/migrate/20250624162553_add_index_to_tud_account_emails.rb
The prod deploy is currently failing with this migration. The issue is around the `disable_ddl_transaction` and the migration failed halfway through.. now it needs to be wrapped in a conditional because when it re-runs, the index exists and fails
Error in db-migrate pod was:
```
-- add_index(:test_user_dashboard_tud_accounts, :email, {:unique=>true, :algorithm=>:concurrently, :name=>"index_test_user_dashboard_tud_accounts_on_email"})
bin/rails aborted!
StandardError: An error has occurred, all later migrations canceled: (StandardError)
PG::DuplicateTable: ERROR:  relation "index_test_user_dashboard_tud_accounts_on_email" already exists
/app/modules/test_user_dashboard/db/migrate/20250624162553_add_index_to_tud_account_emails.rb:5:in `up'
Caused by:
ActiveRecord::StatementInvalid: …
```
=> Add conditionals for failed migration

modules/accredited_representative_portal/app/serializers/accredited_representative_portal/saved_claim_claimant_representative_serializer.rb
Fix display of 'packet' in submissions history 
Submit 21-686c through ARP with at least one supporting attachment. When viewing the claim in submissions history, it currently won't show '21-686c packet' unless two or more attachments are added. 
- *(Which team do you work for, does your team own the maintenance of this component?)* ART/ARF
- *Link …
=> Fix display of 'packet' in submissions history

app/controllers/v0/dependents_applications_controller.rb
- Pass current_user to the va_dependent_v2 flipper in the create method of the controller. This is done below when establishing the service but wasn't done in the create method. Caught this while working on resubmit work.
[- *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if …
=> pass current user to flipper

modules/claims_api/app/services/claims_api/evidence_waiver_document_service.rb, modules/claims_api/app/sidekiq/claims_api/evidence_waiver_builder_job.rb, modules/claims_api/spec/sidekiq/evidence_waiver_builder_job_spec.rb
https://jira.devops.va.gov/browse/API-47468
=> [API-47468] Add more in depth logging to EWS process

app/models/saved_claim/dependency_claim.rb
- add_disabled_child is a new 686 key that used to be add_child. This is needed to process that particular path.
[- *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses Jira*](https://github.com/department-of-veterans-affairs/va.gov-team/issues/113158)
- *Link to epic if not …
=> add add_disabled_child as a 686 flow key

lib/sentry_logging.rb
- Updates sentry warning message.
=> Updates sentry warning message.

modules/debts_api/lib/debts_api/v0/digital_dispute_submission_service.rb, modules/debts_api/spec/lib/debt_api/v0/digital_dispute_submission_service_spec.rb
We got the payload wrong in our initial implementation for our new request to DMC. Turns out it needs camel case. This updates our payload to that.
- *(Summarize the changes that have been made to the platform)*: Small bugfix to fix our payload we're sending to DMC. It's a new endpoint and docs weren't quite ready when we pushed this code originally (we don't have access to lower level env's).
- *(If bug, how to reproduce)*: We are logging errors in prod and did a test with an internal veteran.
- *(Which team do you work for, does your team own the maintenance of this component?)*: Financial Management. You can find us at #financial-management in OCTO slack.
- *(If …
=> 107651 BUGFIX DMC api data contract update

modules/simple_forms_api/app/models/simple_forms_api/vba_21686_c.rb, modules/simple_forms_api/spec/models/vba_21686_c_spec.rb
Fix wrong wording on top date box stamp 21-686c 
Complete 21-686c submission via ARP, check central mail for proper date stamping
Discovered today in meeting
- *(Which team do you work for, does your team own the maintenance of this component?)* ART/ARF
https://github.com/department-of-veterans-affairs/va.gov-team/issues/113003
- *Link to epic if …
=> 21-686c date box stamp copy fix

modules/accredited_representative_portal/spec/requests/accredited_representative_portal/v0/form21a_spec.rb
In https://github.com/department-of-veterans-affairs/vets-api/pull/22844 we un-skipped some tests that were know to be flaky and now those tests are failing. 
Link to slack thread https://dsva.slack.com/archives/C06ABHUNBRS/p1738956153238539
To resolve these flaky tests we re-skipped them.
- *Link to ticket created in va.gov-team repo https://github.com/department-of-veterans-affairs/va.gov-team/issues/113429 …
=> Skip Form21a flaky tests

modules/claims_api/app/controllers/claims_api/v2/veterans/power_of_attorney/request_controller.rb
* No regret refactor for cleaning up local varables in the `decide` method.  Replaces `res` and `service` variables with more specific names to avoid using them multiple times.
* Refactors some of the related logic into extracted methods
* Linting rules forced the change back to the `if` conditional block
[API-47708](https://jira.devops.va.gov/browse/API-47708)
- This is just a refactor, no functionality changes
=> API-47708-prefactor-cleanups-local-vars-in-decide

config/features.yml
Adds a feature flag for the 10-10EZR PDF download feature
- *Describe the steps required to verify your changes are working as expected. Exclusively stating 'Specs run' …
=> #113299 [10-10EZR] Add PDF download feature flag

Gemfile.lock, modules/accredited_representative_portal/spec/requests/accredited_representative_portal/v0/form21a_spec.rb
- ran `vets_json_schema` update following latest merge
https://github.com/department-of-veterans-affairs/vets-json-schema/pull/1020
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/112527
=> Point to latest vets_json_schema version

app/sidekiq/hca/ezr_submission_job.rb, spec/sidekiq/hca/ezr_submission_job_spec.rb
Adds a `PersonalInformationLog` when a submission encounters a parsing error.
- *Link to …
=> #113655 [10-10EZR] Add PIL log to parsing failures

app/controllers/v0/dependents_applications_controller.rb
- There is an edge case where a V1 form is about to submit but the user has been activated as V2, forcing the form down the V2 path which causes an error. This will reinstantiate the V1 dependent service if use_v2 is nil. use_v2 will be nil if the v1 form is submitted even if the flipper has been turned to v2, or if it is a normal v1 path. While this is an extra instantiation of dependents_service, it …
=> go back to v1 service is v2 is nil

Gemfile.lock
- Bump `vets-json-schema` to latest version `25.1.1`
- https://github.com/department-of-veterans-affairs/vets-json-schema/pull/1025
=> rel: `vets-json-schema` Version Bump

app/controllers/v0/profile/addresses_controller.rb, spec/lib/va_profile/contact_information/service_spec.rb, spec/requests/v0/profile/addresses_spec.rb, spec/support/vcr_cassettes/va_profile/contact_information/put_address_override.yml
Permitting country name in the address controller. 
This is a requirement from the VAProfile integration testing in [this slack thread](https://dsva.slack.com/archives/C090VB387SS/p1752179465143359).
- …
=> Permit country name in the V0::Profile::AddressController

app/controllers/v0/test_account_user_emails_controller.rb, spec/requests/v0/test_account_user_emails_spec.rb
- This PR updates the `test_account_user_emails_controller` `create` action to use a SHA256 hash of the email as the Redis key instead of a UUID, ensuring the same key is reused for the same email.
- *(If introducing a flipper, what is the success criteria being …
=> Update TestAccountUserEmail email key generation

app/controllers/v0/profile/address_validation_controller.rb, app/controllers/v0/profile/addresses_controller.rb, modules/ask_va_api/app/controllers/ask_va_api/v0/address_validation_controller.rb, spec/factories/va_profile/v3/validation_address.rb, spec/lib/va_profile/contact_information/service_spec.rb, spec/lib/va_profile/models/v3/validation_address_spec.rb, spec/support/vcr_cassettes/va_profile/contact_information/put_address_override.yml, spec/support/vcr_cassettes/va_profile/v3/address_validation/candidate_multiple_matches.yml
Removing country name from permitted attributes.  …
=> Removed country_name from permitted parameters

modules/mobile/app/schemas/claims_and_appeals_get_claim.json, modules/vaos/app/schemas/appointments_index.json
- *This work is behind a feature toggle (flipper): ~~YES~~/NO*
Due to the recent implementation of a Data Dog monitor that sends warnings to the mobile app alerts channel when schema contract discrepancies have been found, we have noticed discrepancies for the `appointments_index` and the `claims_and_appeals_get_claim` contracts. These json schema contracts have been updated to reflect these changes.
The validation failure logs can be seen [here](https://vagov.ddog-gov.com/logs?query=env%3Aeks-staging%20service%3Avets-api%20%22Schema%20discrepancy%20found%22%20%40message_content%3ASchemaContract%5C%3A%5C%3AValidationJob%2A&agg_m=count&agg_m_source=base&agg_t=count&clustering_pattern_field_path=message&cols=host%2Cservice&ff_di …
=> Address schema contract discrepancies

lib/source_app_middleware.rb, modules/dependents_verification/app/controllers/dependents_verification/v0/claims_controller.rb
- Identifies and remediate mismatches and bugs between the FE form submission config and the BE endpoint to allow a FE form to be received by the BE
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/114105
Dependents Verification
=> Dependents Verification | Accept FE 0538 claims

lib/unified_health_data/service.rb, spec/lib/unified_health_data/service_spec.rb, spec/lib/unified_health_data/service_test_code_logging_spec.rb
Adds test names to analytics logging.
=> Enhance logging in log_test_code_distribution to include test names

config/features.yml
- *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team …
=> adds cerner cookie ff

modules/burials/lib/burials/pdf_fill/va21p530ez.rb, modules/burials/spec/models/burials/saved_claim_spec.rb
- The burials PDF form mapping logic was previously configured to overflow for state, country, and ZIP fields. Country codes are currently always being passed in as a 3-letter code, so the country field was always overflowing with "See add'l Info Page" populated into the field. Since the country field only allows 2 characters, this message was get truncated to "Se" which is the code for Sweden.
- This is …
=> 21P-530EZ - Remove overflow behavior for state, country and zip fields

.github/CODEOWNERS, lib/flipper_utils.rb, lib/mhv_ac/configuration.rb, lib/rx/configuration.rb, lib/sm/configuration.rb, spec/lib/flipper_utils_spec.rb, spec/lib/mhv_ac/configuration_spec.rb, spec/lib/sm/configuration_spec.rb
Reverts department-of-veterans-affairs/vets-api#23104
=> Revert "Revert "Console flipper error""

Gemfile.lock
Updated the vets-json-schema version from 25.1.1 to 25.1.2
The changes are encompassed in this previous pr - https://github.com/department-of-veterans-affairs/vets-json-schema/pull/1027
- _Link to tickets this is regarding https://github.com/department-of-veterans-affairs/va.gov-team/issues/113716 and https://github.com/department-of-veterans-affairs/va.gov-team/issues/113615
- _Link to previous change of the code/bug  - https://github.com/department-of-veterans-affairs/vets-json-schema/pull/1027 …
=> Updated the vets-json-schema version

lib/veteran_enrollment_system/associations/service.rb
Adds `403` response status to the `ERROR_MAP` list as well as a safe operator to a `ERROR_MAP[response.status].new` in case it returns `nil`. …
=> Added 403 to error map and added a safe operator

modules/ivc_champva/app/controllers/ivc_champva/v1/uploads_controller.rb
This PR updates the order in which blank/stamped attachments are appended to the supporting docs array, specifically in the new 10-7959a metadata procedure ([see here for context](https://github.com/department-of-veterans-affairs/vets-api/pull/23083)). Previously, this was adding the attachment after attachment ids were evaluated, which resulted in the new attachment being generated, but not included in the final push to S3.
There is no new code in this PR, the method call was simply moved to a different stage of the document processing flow.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/112033
- *Describe the steps required to verify your changes are working as expected. Exclusively stating 'Specs run' is …
=> Fix order of attachment ID evaluations - IVC CHAMPVA

modules/dependents_verification/app/models/dependents_verification/saved_claim.rb, modules/dependents_verification/lib/dependents_verification/pdf_fill/section.rb, modules/dependents_verification/spec/models/dependents_verification/saved_claim_spec.rb, modules/dependents_verification/spec/swagger/swagger/requests/dependents_verification_claims_spec.rb
- This pull request includes changes to update the `SavedClaim` model with correct data, remove unused and abstract methods from the `Section` class, and clean up outdated test cases. These updates improve the accuracy of the data, simplify the codebase, and ensure the tests align with the current implementation.
- This form isn't yet live
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/114802
Dependents Verification
=> Cleanup and minor changes

app/sidekiq/bgs/job.rb, spec/sidekiq/bgs/job_spec.rb
- *This work is behind a feature toggle (flipper): In dependents V2, currently on for 50% of users*
- Added the keyword 'street' to the address normalizer because FE components changed from using 'address_line' to 'street'
- The solution is to include 'street' in normalizer and write a unit test to confirm behavior
[- *Link to ticket created in va.gov-team …
=> include street as keyword to be normalized

app/sidekiq/hca/ezr_submission_job.rb, app/sidekiq/hca/health_facilities_import_job.rb, app/sidekiq/hca/log_email_diff_job.rb, app/sidekiq/hca/std_institution_import_job.rb, app/sidekiq/hca/submission_job.rb
- Add comments to hca sidekiq jobs that add context to the business logic and design of the jobs. 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/114303
- Only comments added
=> [10-10EZ] Add context in a comment for hca sidekiq jobs

.github/CODEOWNERS
- This PR reverts the updates to the CODEOWNERS for 10-10 health apps to add them to IVC files. 
- We don't want 1010 approval to be a blocker for current work. We may just add 1010 team members to the existing ivc codeowner group so that we are not a requirement. 
none
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-Backendexamp …
=> [10-10] Revert "Add vfs-10-10 to champva-engineering owned codeowners entries"

app/sidekiq/form1010cg/delete_old_uploads_job.rb, app/sidekiq/form1010cg/submission_job.rb
- Add comments to hca sidekiq jobs that add context to the business logic and design of the jobs. 
- Only comments added
=> [10-10CG] Add context in a comment for caregiver sidekiq jobs

app/models/saved_claim/dependency_claim.rb, app/sidekiq/lighthouse/benefits_intake/submit_central_form686c_job.rb, app/sidekiq/lighthouse/benefits_intake/submit_central_form686c_v2_job.rb
- The 674 date stamp was getting put in the wrong place. this moves it back to the box.
- adjust coordinates for the 674 stamper. it now matches the 686c stamper.
[- *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses Jira*](https://github.com/department-of-veterans-affairs/va.gov-team/issues/115152)
- *Link to previous change of the …
=> alter all 686c 674 stampers with updated coordinates

config/features.yml
- *This work is behind a feature toggle (flipper): no. it adds a feature flag.
- Adds a feature flag
https://github.com/department-of-veterans-affairs/va-iir/issues/1887
None. It's a feature flag.
None.
=> 1887: add paperless delivery feature flag

lib/salesforce/configuration.rb
- *(Summarize the changes that have been made to the platform)*: Per this [slack thread](https://dsva.slack.com/archives/CBU0KDSB1/p1753216640838499) with @rmtolmach it was discovered that an update to the breakers gem now requires a service_name argument when defining faraday connection
- *(If bug, how to reproduce)* Feedback tool in prod and staging currently fails on submission. You can try with test user [here](https://staging.va.gov/education/submit-school-feedback/introduction) or check [datadog logs](https://vagov.ddog-gov.com/logs?query=env%3Aeks-prod%20%22Please%20pass%20a%20service_name%20argument%20to%20the%20Breakers%20middleware%20for%20service%3A%22%20status%3Aerror&agg_m=count&agg_m_source=base&agg_q=%40message_content&ag …
=> VEBT-2730/udpate salesforce breakers arg

modules/representation_management/app/controllers/representation_management/v0/accredited_entities_for_appoint_controller.rb, modules/representation_management/app/controllers/representation_management/v0/accredited_individuals_controller.rb, modules/representation_management/app/models/representation_management/accredited_individual_search.rb, modules/representation_management/app/serializers/representation_management/accredited_individuals/individual_serializer.rb, modules/representation_management/spec/requests/representation_management/v0/accredited_entities_for_appoint_spec.rb, modules/representation_management/spec/requests/representation_management/v0/accredited_individuals_spec.rb, modules/representation_management/spec/serializers/accredited_individuals/individual_serializer_spec.rb
With these changes the frontend will be able to work correctly just by changing the endpoints.
- A controller has been changed to use the correct feature flag
- A controller now accepts types from `Veteran::Service::Representative`s and `AccreditedIndividual`s and normalizes them to the `AccreditedIndividual` value.
- `full_name` has been …
=> Adjust Accreditation API endpoints

config/settings.yml, config/settings/development.yml, config/settings/test.yml
- Adds maintenance service to config
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/114955 …
=> Added env var for pagerduty services

Gemfile.lock
Updated vets-json-version version from 25.1.3 to 25.1.4
- *Link to ticket created in va.gov-team - https://github.com/department-of-veterans-affairs/vets-json-schema/pull/1033
- https://github.com/department-of-veterans-affairs/vets-website/pull/37965 …
=> Update the vets-json-schema version to 25.1.4

modules/accredited_representative_portal/app/models/accredited_representative_portal/claimant.rb, modules/accredited_representative_portal/spec/requests/accredited_representative_portal/v0/claimant_request_spec.rb
Return 404 instead of 500 on claimant search when MPI returns no records
Visit ARP claimant search
Search for a bogus user (put a random ssn such as 928475391, do not use 123456789 as this is an MPI record!)
A 500 error will be returned, this PR fixes it to be a 404
After checking Datadog, we are trying to filter out noise
- *(Which team do you work for, does your team own the maintenance of this component?)* ARF
- *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses …
=> Fixes 500 on claimant search when mpi returns no records

modules/accredited_representative_portal/app/models/accredited_representative_portal/power_of_attorney_request_decision.rb, modules/accredited_representative_portal/app/serializers/accredited_representative_portal/power_of_attorney_request_serializer/decision_serializer.rb, modules/accredited_representative_portal/spec/factories/power_of_attorney_request_decision.rb
- Added `accredited_individual` association to PowerOfAttorneyRequestDecision model
- Updated decision serializer to include serialized accredited individual
- Enhanced factory to support accredited individual creation for testing
https://github.com/department-of-veterans-affairs/va.gov-team/issues/111813 …
=> Associate accredited individual with POA request decision

modules/vaos/app/services/eps/provider_service.rb, modules/vaos/spec/services/eps/provider_service_spec.rb
Updates logic utilized in provider search step of Community Care draft appointment creation to bypass address match if only 1 provider is found to match the given specialty. 
We were having an issue with testing on staging where the address match step was preventing draft appt creation, but the logs for each occurrence were indicating that there was only 1 result found to be a "specialty" match. 
The original proposed solution was to remove the address match altogether but, as per the notes from the [ticket for the implementation](https://github.com/department-of-veterans-affairs/va.gov-team/issues/111429), it needs to remain in place for the likely event that a provider is listed under multiple facilities returned by the search …
=> 115381 cc appts skip provider address match

config/settings.yml, config/settings/development.yml, config/settings/test.yml
This is unused in vets-api 
Came out of this support request:
- https://dsva.slack.com/archives/CBU0KDSB1/p1753816678525269
I searched `Settings.notifications` and there were no results.
=> Delete unused notifications setting

modules/claims_api/app/controllers/claims_api/v2/veterans/power_of_attorney/request_controller.rb, modules/claims_api/app/services/claims_api/power_of_attorney_request_service/decision_handler.rb, modules/claims_api/app/sidekiq/claims_api/va_notify_accepted_job.rb, modules/claims_api/spec/controllers/v2/veterans/power_of_attorney/request_controller_spec.rb, modules/claims_api/spec/requests/v2/veterans/rswag_power_of_attorney_spec.rb, modules/claims_api/spec/sidekiq/va_notify_accepted_job_spec.rb
* Validates the return, mapped data
* Builds auth headers for POA
* Saves POA record in DB
* Adds location URL to headers
* Adds logging to help with future debugging
* Adds/updates related tests
* Cleans up VA Notify Accepted job.
* This job was built out as a template before we were accepting accepts for the request so it needed some clean up
[API-43734](https://jira.devops.va.gov/browse/API-43734)
[API-48284](https://jira.devops.va.gov/browse/API-48284) (was able to include this part in this PR)
There are 4 scenarios we have for this submission (accepted path that is). 
- organization (2122)
- organization + dependent
- individual (2122a)
- individual + dependent
The totality of the workflow produces for each:
- Saved POA form in lighthouse (represented below by the IDs that are part …
=> Api 43734 save and auto establish poa

modules/claims_api/app/controllers/claims_api/v2/veterans/power_of_attorney/request_controller.rb
* Staging testing is producing an error I cannot seem to duplicate locally so hoping to add a log to help give some insight into what is happening
- No new code, just an additional log (that may not stay in) to help with some debugging
modified:  modules/claims_api/app/controllers/claims_api/v2/veterans/power_of_attorney/request_controller.rb
=> Adds some logging to help with debugging staging ENV errors

modules/claims_api/lib/claims_api/v2/disability_compensation_fes_openapi.json
- Add FES OpenAPI / Swagger documentation file.
https://jira.devops.va.gov/browse/API-47332
=> 47332 - Add FES Service OpenAPI spec documentation file

config/form_profile_mappings/686C-674-V2.yml, spec/models/form_profile_spec.rb
This reverts commit 221de8b0f8dbff30b3754af9fad44cb86d682ca1.
Reverting https://github.com/department-of-veterans-affairs/vets-api/pull/23378 due to our backend needs the SSN for backup path submissions.
- *(Which team do you work for, does your team own …
=> Revert "DMT | Remove SSN from prefill (#23378)"

modules/accredited_representative_portal/app/controllers/accredited_representative_portal/v0/representative_form_upload_controller.rb, modules/accredited_representative_portal/app/services/accredited_representative_portal/monitoring.rb, modules/accredited_representative_portal/spec/services/accredited_representative_portal/monitoring_spec.rb
Background
To improve observability and troubleshooting of form upload flows in the Accredited Representative Portal, we need to capture detailed spans and contextual metadata around each major step. This includes the initial submission, scanned-form upload, PDF stamping, upload to Benefits Intake, database persistence, and ICN lookup.
⸻
* `Monitoring#trace` — lightweight wrapper around `Datadog::Tracing.trace`
* applies default + custom tags
* flags and re-raises errors so spans are marked `error=true`
* Unit specs covering happy-path and error cases for the new helper
* `RepresentativeFormUploadController`
* wrap `submit`, `handle_attachment_upload`, `authorize_submission`,
`upload_scanned_form`, and `upload_supporting_documents`
in `ar_monitoring.trace`
* set rich span tags (form_id, …
=> Add Datadog tracing to AccreditedRepresentativePortal form upload flows

app/models/saved_claim/veteran_readiness_employment_claim.rb, config/features.yml, config/settings.yml, config/settings/development.yml, config/settings/test.yml, spec/models/saved_claim/veteran_readiness_employment_claim_spec.rb
- *This work is behind a feature toggle (flipper): YES/NO* **YES**
- *(Summarize the changes that have been made to the platform)* This PR is the first part of a multi-part process to implement the VFS Notification library on `vets-api`.  This PR:
- creates feature toggle
- add settings values required by VFS Notification Library
- small refactor and update tests for model
- *(If bug, how to reproduce)* Not a bug
- *(What is the solution, why is this the solution?)* Prevent silent failures when sending email
- *(Which team do you work for, does your team own the maintenance of this component?)* I work on the VA-IIR team
- *(If introducing a flipper, what is the success criteria being targeted?)* identical system behavior to previous, with added monitoring for silent failures
- *Link to …
=> Part 1 of VFS Notifications implementation: settings, config, minor model refactor

lib/form1010_ezr/service.rb, spec/lib/form1010_ezr/service_spec.rb
Added a PIL log to a flipper-controlled method to so we can communicate with the VES team on who's data is being sent and if the changes are being made upstream. The goal is to enable the feature to a very small percentage of the user base and then track the submissions to ensure the functionality is working as intended.
- *(If bug, how to …
=> #116430 [10-10EZR] Added PIL to `handle_associations` method

app/controllers/v0/claim_letters_controller.rb
- adds logging and statsd to better track errors for migration
- 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/116134
*(Describe what parts of the site are impacted and*if*code …
=> bmt1/115629: upgrade metric capturing for vbms to lighthouse claim letters migration

modules/accredited_representative_portal/app/serializers/accredited_representative_portal/saved_claim_claimant_representative_serializer.rb
Small bugfix to add safe nil checks
Ticket: 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/116529
- [ x]  No error nor warning in the console. …
=> bugfix: add safe ref nav

app/models/saved_claim/veteran_readiness_employment_claim.rb, config/settings.yml, config/settings/development.yml, config/settings/test.yml, spec/models/saved_claim/veteran_readiness_employment_claim_spec.rb
At the end of last week, the IIR team merged a series of PRs to implement the VFS Notification library in vets-api.  As a part of this staged rollout, we utilized a feature toggle.  The usage of this feature toggle was incorrect:
https://github.com/department-of-veterans-affairs/vets-api/blob/59b7fbbd535f92c387b92ee92be05abc24f84a64/app/models/saved_claim/veteran_readiness_employment_claim.rb#L304
```
unless Flipper.enabled?(:vre_use_new_vfs_notification_library, user)
```
When passing an object as the second argument (the user), this object must have a `flipper_id` attribute.  Because this user was not a `current_user` like what is found in the controller, but an OpenStruct, this `user` object did not possess a `flipper_id`, causing an exception (timeframe is last 48 hours):
- *This work …
=> BUG (VRE) Don't refer to user when calling feature flag - user is not a real user object

config/betamocks/services_config.yml
Attempted to run vets-api-mockdata locally and ran into a bug. Investigated with @kjduensing and found that the mockdata isnt running due to a bug with vets-api config/betamocks/services_config.yml.
The paths "/veis/api/btsss/travelclaim/api/v2/claims/search-by-appointment-date" is being overridden by the path "/veis/api/btsss/travelclaim/api/v2/claims/*".
Updated `config/betamocks/services_config.yml` so that the path `/veis/api/btsss/travelclaim/api/v2/claims/*` had a regex for the uuid. (updated the path to `"/veis/api/btsss/travelclaim/api/v2/claims/[0-9a-fA-F-]{36}"`. This makes it so that the `search-by-appointment-date` api works. 
Also updated the path `/veis/api/btsss/travelclaim/api/v2/claims/*` so that there is a  `:cache_multiple_responses:` section that looks like this:
``` …
```
=> Bug Fix for running vets-api-mockdata locally

spec/lib/lighthouse/benefits_claims/service_spec.rb, spec/lib/lighthouse/veteran_verification/service_spec.rb
Specs are failing. Trying to reduce the noise. This [PR](https://github.com/department-of-veterans-affairs/vets-api/pull/23423/files) had breaking changes. …
=> Trying to fix some specs

spec/lib/lighthouse/benefits_claims/service_spec.rb, spec/lib/lighthouse/veteran_verification/service_spec.rb
Reverts department-of-veterans-affairs/vets-api#23532
=> Revert "Trying to fix some specs"

modules/simple_forms_api/spec/tasks/send_emails_by_date_range_spec.rb
These are flakey again. This was previously skipped but fixed in https://github.com/department-of-veterans-affairs/vets-api/pull/23552. I saw this in the first four runs here: https://github.com/department-of-veterans-affairs/vets-api/actions/runs/17001072969
specs
=> Skip send_emails_by_date_range_spec.rb

.github/copilot-instructions.md
Trying to get code coverage to pass so I thought pushing another commit might help as a stop-gap measure. 
=> Small update to copilot-instructions.md

.github/workflows/ready_for_review.yml, .github/workflows/require_be_approval.yml
Reverts department-of-veterans-affairs/vets-api#23618
=> Revert "Refactor BE Reviews"

app/sidekiq/va_notify_email_job.rb, modules/va_notify/app/sidekiq/va_notify/email_job.rb, modules/va_notify/spec/sidekiq/email_job_spec.rb
Added a comment to the deprecated va_notify_email_job.rb stating that it's deprecated and the file to use instead.
Added a TODO to remove it and a TODO in the file to use to update the logging logic to use Vets::SharedLogging.
Added an RSpec to cover a branch.
- *(If bug, how to reproduce)* Not a bug
- *(What is the solution, why is this the solution?)* N/A
- *(Which team do you work for, does your team own the maintenance of this component?)* VEBT/No
- *(If introducing a flipper, what is the success criteria being targeted?)* No flipper
[Jira …
=> vebt3133 - add deprecation comment, todos and one test

lib/medical_records/bb_internal/client.rb, spec/lib/medical_records/bb_internal/client_spec.rb
- MHV Medical Records is seeing odd 404 errors around cached UUIDs for image study requests in the datadog logs. This PR adds logging for when the cached study ID doesn't exist to determine the source of the errors.
- Before we can fix the problem the team must diagnose the root cause of the error - is the TTL in the cache not long enough or not set properly? Are the UUIDs not being stored under the correct user key? Is it an edge case where the request comes in _just_ as the cache expires?
- …
=> MHV-MR/116402 UUID caching error logging

spec/simplecov_helper.rb
Master branch is failing because db/migrate files are failing code coverage. `db/migrate` files should not be included in the code coverage report. Also, the track files command was updated because ONLY modules listed should be included in the Code Coverage. 
- …
=> Filtered out more files to improve code coverage.

modules/claims_api/app/mailers/claims_api/submission_report_mailer.rb, modules/claims_api/app/mailers/claims_api/unsuccessful_report_mailer.rb, modules/claims_api/spec/mailers/report_monthly_submissions_spec.rb, modules/claims_api/spec/mailers/unsuccessful_report_mailer_spec.rb
This PR updates the email distribution lists in claimsAPI to match the current team.
NA
NA
```
modules/claims_api/app/mailers/claims_api/submission_report_mailer.rb
modules/claims_api/app/mailers/claims_api/unsuccessful_report_mailer.rb …
```
=> Update email distribution lists

.github/workflows/ready_for_review.yml, .github/workflows/require_be_approval.yml
**Issue:**
If octo-identity is a requested team for a pull request + then a member of octo approves the pull request + the author merges in master/makes changes:
- Requested team that the reviewer was a part of are gone
- All approved reviewers are gone.
This would cause the PR to require backend approval for non exempt teams (which is what we are seeing).
**How to fix:**
- If there are no approved reviews, we can look at the dismissed approvals (meaning they …
=> Refactor be approval

.github/workflows/require_be_approval.yml
Require BE approval should only be triggered when a pull request is reviewed. This was added for testing purposes and needs to be removed. 
- *Describe the steps required to verify your changes are …
=> Removed pull_request triggers

app/uploaders/supporting_evidence_attachment_uploader.rb, spec/uploaders/supporting_evidence_attachment_uploader_spec.rb
NO
This PR removes logging of resulting headers from AWS for an S3 file upload. They include filename, or have started including filename, at some point, which could be PII/PHI so should not be logged.
We cannot log this info, this must be removed. 
Disability Benefits and Claims Core Team
Im not
https://dsva.slack.com/archives/C04KW0B46N5/p1756150341321499
https://dsva.slack.com/archives/CBU0KDSB1/p1756165133234999
- …
=> Removing offending log lines

app/models/bgs_dependents_v2/base.rb, spec/models/bgs_dependents_v2/base_spec.rb
- When an international address, send nil to zip_prefix_nbr
- When we build an address for bgsv2, set a variable called zip_prefix_nbr and pass that to the object.
[- *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses Jira*](https://github.com/department-of-veterans-affairs/va.gov-team/issues/117733)
- *Link to previous change of the …
=> set zip_prefix_nbr to nil when international

Gemfile.lock
I merged [this vets-json-schema PR](https://github.com/department-of-veterans-affairs/vets-json-schema/pull/1042); this PR is to update the version of VJS in the repository.
Local testing was done extensively with this version of VJS in these three PRs:
- https://github.com/department-of-veterans-affairs/vets-json-schema/pull/1042
- https://github.com/department-of-veterans-affairs/vets-website/pull/38318
- …
=> DR 113660: Update vets-json-schema version

lib/sm/client.rb, modules/mobile/app/controllers/mobile/v0/recipients_controller.rb, modules/mobile/docs/schemas/SecureMessagingAllRecipients.yml, modules/mobile/spec/requests/mobile/v0/messaging/health/all_recipients_spec.rb, modules/mobile/spec/support/fixtures/all_triage_teams_with_duplicates.json, spec/support/schemas_camelized/all_triage_teams.json, spec/support/vcr_cassettes/mobile/lighthouse_facilities/200_facilities_977_978_979.yml
care systems info fetch added in sm client so that sm on va.gov can use it too
Currently [va.gov](http://va.gov/) and VAHB are constructing the "Care Systems" list differently. This is causing issues in lower environments for VAHB. This ticket is part of updating the logic in VAHB to match what [va.gov](http://va.gov/) does. 
#[117205](https://github.com/department-of-veterans-affairs/va.gov-team/issues/117205)
- *Describe what the old behavior was prior to …
=> fetching care systems and returning it for mobile

lib/decision_review/utilities/pdf_validation/service.rb
Fixing errors in prod. [Slack thread](https://dsva.slack.com/archives/CBU0KDSB1/p1756229647432859)
- *Describe the steps required to verify your changes are working as expected. Exclusively stating …
=> Revert breaking changes

config/features.yml, lib/va_profile/v3/address_validation/service.rb, spec/lib/va_profile/v3/address_validation/service_spec.rb
- When the address validation service returns a `CandidateAddressNotFound` error (it is still a 200 response), validate the address to allow users to use that address anyways
- Use a rural address to trigger the `CandidateAddressNotFound` error and observe that you can now save the address.
- Validating the address allows the users to save the address they're wanting to save.
- Authenticated Experience Team Authentiknights
- Flipper: profile_validate_address_when_no_candidate_found
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/114832
- Previously the address validation service would return an error for `CandidateAddressNotFound` but now it will return the address with a validation key.
- Attempt to update an …
=> 114832 - validate address when CandidateAddressNotFound is returned

app/services/bgs/people/service.rb
Eliminating some errors causing 429 issues. [Slack thread](https://dsva.slack.com/archives/CBU0KDSB1/p1756229647432859)
- *Describe the steps required to verify your changes are working as expected. …
=> Fix:  VRE::Submit1900Job nil errors

lib/lighthouse/benefits_documents/service.rb, spec/lib/lighthouse/benefits_documents/service_spec.rb
After being notified of leaked PII via the filename of a user-uploaded file, the logger has now been updated to filter out potential PII leaks
Benefits Management Team 2
- …
=> #117791 [BMT 2] Filter out sensitive data from loggers in `BenefitsDocuments::Service`

modules/simple_forms_api/spec/models/vba_40_10007_spec.rb
Increased code coverage for 40-0247 and added test for 40-10007 attachments
https://jira.devops.va.gov/browse/MBMS-102376 …
=> MBMS-102376 Broke out PR 2 NCA Forms

modules/simple_forms_api/spec/models/vba_40_0247_spec.rb, modules/simple_forms_api/spec/models/vba_40_10007_attachment_spec.rb
Increased code coverage for 40-10007 model
https://jira.devops.va.gov/browse/MBMS-102376 …
=> MBMS-102376 Broke up PR NCA Forms

modules/mobile/app/controllers/mobile/v0/users_controller.rb, modules/mobile/app/controllers/mobile/v1/users_controller.rb
- *This work is behind a feature toggle (flipper): ~~YES~~/NO*
Removed the pre-cache after action for certain endpoints in the users controller(s). This way it wont spawn a sidekiq job that attempts to pre-cache claims and appeals data.
Not a bug but we got a request from Platform to determine why we are spawning so many of these jobs (10000+) regularly. The answer is we are creating a job for every user that logs in... and the mobile app sees heavy use.
The solution is to remove the precaching all together. This looks to be an outdated caching attempt and, since the user is now immediately taken to the home screen on the app which makes …
=> Remove precaching for claims and appeals from mobile users controllers

config/features.yml, modules/debts_api/app/controllers/debts_api/v0/digital_disputes_controller.rb, modules/debts_api/app/models/debts_api/v0/digital_dispute_submission.rb, modules/debts_api/lib/debts_api/v0/digital_dispute_dmc_service.rb, modules/debts_api/spec/lib/debt_api/v0/digital_dispute_dmc_service_spec.rb, modules/debts_api/spec/requests/debts_api/v0/digital_disputes_spec.rb, spec/requests/swagger_spec.rb
We are working on moving the Digital Dispute form submission into a sidekiq job. In order to do this, we need(ed) to make some changes/refactors to accomodate the form being in a sidekiq job.
This PR creates a new service that is Feature flagged and moves the record creation into the controller.
- *(Summarize the changes that have been made to the platform)*: No platform changes
- *(What is the solution, why is this the solution?)*: We want to be able to do retries and don't want to pass in controller params like files and fuss with temp files.
- *(Which team do you work for, does your team own the maintenance of this component?)*: Financial Management you can find me on OCTO slack at …
=> 117757 Financial Management Digital Dispute Refactor

spec/requests/v0/profile/telephones_spec.rb, spec/support/vcr_cassettes/va_profile/v2/contact_information/delete_international_telephone_success.yml, spec/support/vcr_cassettes/va_profile/v2/contact_information/delete_telephone_success.yml, spec/support/vcr_cassettes/va_profile/v2/contact_information/post_international_telephone_success.yml, spec/support/vcr_cassettes/va_profile/v2/contact_information/put_international_telephone_success.yml
- *This work is behind a feature toggle (flipper):*
- NO
- This is not a bug.
- VA Profile and VA.gov Profile are rolling out support for international phone numbers. Per [feedback from architecture intent](https://github.com/department-of-veterans-affairs/va.gov-team/issues/105163#issuecomment-3168941753), we want to capture any new request/response combinations specific to …
=> 116836 - Profile - Add VCRs for international phones

modules/dependents_verification/app/controllers/dependents_verification/v0/claims_controller.rb
- There was a typo in the service-tag for Dependents Verification
Dependents Verification
=> Fix typo in Dependents Verification

modules/claims_api/lib/claims_api/pdf_mapper_base.rb, modules/claims_api/lib/claims_api/v1/disability_compensation_pdf_mapper.rb, modules/claims_api/lib/claims_api/v2/disability_compensation_pdf_mapper.rb, modules/claims_api/spec/lib/claims_api/pdf_mapper_base_spec.rb, modules/claims_api/spec/lib/claims_api/v1/disability_compensation_pdf_mapper_spec.rb
* Adds mapping for section 2 - Change of Address
* This whole section is optional in the 526 submission
* Refactors some of the zip and address string building methods to be shared
* The following properties are mapped in this PR:
| V1 526 Property | PDF Mapper Property | 
|---|---|
|veteran.changeOfAddress.endingDate       |        changeOfAddress.effectiveDates.end|
|veteran.changeOfAddress.begnningDate   |         changeOfAddress.effectiveDates.start|
|veteran.changeOfAddress.city         |            changeOfAddress.newAddress.city|
|veteran.changeOfAddress.country         |         changeOfAddress.newAddress.country|
|veteran.changeOfAddress.addressLine1      |       changeOfAddress.newAddress.numberAndStreet|
|veteran.changeOfAddress.addressLine2     | …
=> API-49671-v1-pdf-mapper-section-2

config/betamocks/services_config.yml
EVSS configuration was added back to the Betamocks service config. …
=> fix: Added EVSS configuration to Betamocks Service config.

modules/check_in/app/services/travel_claim/travel_pay_client.rb, modules/check_in/spec/services/travel_claim/travel_pay_client_spec.rb
- *This work is behind a feature toggle (flipper): YES - fe access is behind disabled feature toggle
- updates BTSSS token header key in `TravelClaim::TravelPayClient`
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featu …
=> cie travel claim client headers update

.github/CODEOWNERS, config/settings.yml, config/settings/development.yml, config/settings/test.yml, lib/lighthouse/healthcare_cost_and_coverage/configuration.rb, lib/lighthouse/healthcare_cost_and_coverage/invoice/service.rb, spec/lib/lighthouse/healthcare_cost_and_coverage/configuration_spec.rb, spec/lib/lighthouse/healthcare_cost_and_coverage/invoice/service.rb, spec/lib/lighthouse/healthcare_cost_and_coverage/invoice/service_spec.rb
- *(Summarize the changes that have been made to the platform)*: This is not client/vet facing. This adds the config and Invoice resource for the Lighthouse Healthcare Cost and Coverage API. We will be adding more requests immediately after this one. 
- *(What is the solution, why is this the solution?)*: Our team works with "Debts" and "Copays". The Lighthouse Healthcare Cost and Coverage API retrieves Copay data that is more recent. We will eventually use this API to populate Copay data for the veteran.
- *(Which team do you work for, does your team own the maintenance of this component?)*: Financial Management
- …
=> 114271 Financial Management Lighthouse Healthcare Cost and Coverage

config/features.yml
-  add va dependents v3 flipper 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/119043
-  enable v3 flipper in settings route
=> DMT | VA Dependents v3 flipper

config/features.yml
This flipper was created for the Contact Information V2 integration and no longer is used. This flipper be removed from the rails console after this has been deployed to production.
- department-of-veterans-affairs/va.gov-team/issues/98928
- *If this …
=> Removed override_address_pou flipper

lib/sm/client.rb, lib/sm/middleware/response/sm_parser.rb, spec/lib/sm/client/messages_spec.rb
This pull request improves the handling and parsing of message attachments, especially those stored in AWS S3 and returned as objects with URL metadata. It updates both the client logic and response parsing to support this new format, and adds comprehensive tests to ensure correct behavior for various attachment response scenarios.
Enhancements to attachment handling:
* Updated `get_attachment` in `lib/sm/client.rb` to support responses where attachment …
=> MHV SM: handle updated large attachment response

modules/mobile/app/controllers/mobile/v0/letters_controller.rb, modules/mobile/spec/requests/mobile/v0/letters_spec.rb
- *This work is behind a feature toggle (flipper): YES/~~NO~~*
To prevent breaking backwards compatibility, we are introducing an app version check to enable the COE LGY letter functionality in the letters controller. Due to how the front end code is laid out, we'll need to version it to prevent misleading veterans.
- *Link …
=> [Mobile] Update Letters endpoints to check for app version for COE

app/models/bgs_dependents_v2/relationship.rb, app/models/bgs_dependents_v2/spouse.rb, spec/lib/bgsv2/vnp_relationships_spec.rb, spec/models/bgs_dependents_v2/relationship_spec.rb, spec/models/bgs_dependents_v2/spouse_spec.rb
- RBPS decided not to receive marriage_method_name because handling wasn't finished on their end. This PR removes the calls that pass marriage_method_name
[- *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses …
=> remove marriage method name calls

modules/income_and_assets/app/controllers/income_and_assets/v0/claims_controller.rb, modules/income_and_assets/lib/income_and_assets/benefits_intake/submit_claim_job.rb, modules/income_and_assets/spec/e2e_spec.rb, modules/income_and_assets/spec/factories/income_and_assets/income_and_assets_claim.rb, modules/income_and_assets/spec/lib/income_and_assets/benefits_intake/submit_claim_job_spec.rb
Updating our saved_claim creation to include the user_account_uuid so that it is possible to find saved claims for a specific user (if needed). Also updated usage of `current_user.user_account_uuid` to just use the saved claims `user_account_id` (these are the same)
- department-of-veterans-affairs/va.gov-team/issues/119672
Specs were updated to align with the code changes …
=> Updating saved_claim to include user_account_id

modules/dependents_verification/lib/dependents_verification/pdf_fill/sections/section1.rb, modules/dependents_verification/spec/fixtures/pdf_fill/21-0538/kitchen_sink.json, modules/dependents_verification/spec/fixtures/pdf_fill/21-0538/overflow.json
- Street2 was getting left off of the pdf where it should have been filling in unit number. This PR places it appropriately.
[- *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses Jira*](https://github.com/department-of-veterans-affairs/va.gov-team/issues/119984)
- *Link to epic if …
=> sub in street2 for unit number

modules/claims_api/spec/requests/v2/veterans/rswag_power_of_attorney_spec.rb
* Fixes a few issues existing in our swagger docs
*  When adding the POA request endpoints to the production docs, the flags to not do that (`production: false`) got left in, this removes them to avoid surprises when generating the docs (these are now in prod and this update keeps them there) [892a806](https://github.com/department-of-veterans-affairs/vets-api/pull/24361/commits/892a8068834b673480514edd0214b46a138653bc)
* Fixes mocking in the `decide` endpoints rswag test so that the veteran information is included again. [5145605](https://github.com/department-of-veterans-affairs/vets-api/pull/24361/commits/51456059d729eaac83f99e70a100c0a3d43572cb)
* **_It is worth noting that there was an update to the v2 526.json file that did not get included in the docs and so is appearing new.  The …
=> Api 50173 swagger doc fixes

modules/mobile/app/serializers/mobile/v0/all_triage_teams_serializer.rb, modules/mobile/docs/schemas/SecureMessagingAllRecipients.yml, spec/support/schemas_camelized/all_triage_team.json
Update mobile endpoint to return new piece of data from upstream
https://github.com/department-of-veterans-affairs/va.gov-team/issues/120353 …
=> mobile /allrecipients returns oh flag

app/models/saved_claim.rb, config/identity_settings/environments/staging.yml, lib/dependents/monitor.rb, modules/pensions/lib/pensions/benefits_intake/submit_claim_job.rb, modules/pensions/spec/factories/pension_claim.rb, spec/services/bgs/dependent_service_spec.rb, spec/services/bgs/dependent_v2_service_spec.rb
Setting the `user_account_id` to an ignored column for the `SavedClaim` model. Doing this because strong migrations will not allow us to drop a column that is not in the `ignored_columns` list. This will be followed up by another PR with a DB migration to drop the existing `user_account_id` column and recreate it as a new column with the data type UUID (from BigInt)
- *If this work …
=> Adding user_account_id to ignored_columns

modules/claims_api/app/sidekiq/claims_api/v1/form526_establishment_upload.rb, modules/claims_api/lib/claims_api/v1/disability_compensation_fes_mapper.rb, modules/claims_api/spec/lib/claims_api/v1/disability_compensation_fes_mapper_spec.rb
* Maps disabilities [71dd95d](https://github.com/department-of-veterans-affairs/vets-api/pull/24372/commits/71dd95d3c96a6c99d36438ff3dac4a31fae92287)
* Flattens secondary disabilities into disabilities before mapping
* Updates the wrapper method to include all required values for submission [76dd85f](https://github.com/department-of-veterans-affairs/vets-api/pull/24372/commits/76dd85ff43b35cbca888db453f63b45b2fc36697)
* Adjusts/adds a test for addition method
* Updates the logging text for the job  9853fc9
* **_This will not submit to FES successfully yet because we do not have all the required sections_**
[API-50225](https://jira.devops.va.gov/browse/API-50225)
* Able to handle this here too: [API-50204](https://jira.devops.va.gov/browse/API-50204)
* This submission:
```
{
"data":{ …
```
=> Api 50225 v1 fes mapper section 5 disabilities

config/features.yml
> Adding `dependency_verification_browser_monitoring_enabled` to toggle DataDog RUM & Monitoring in form 21-0538 (Dependency Verification form)
> Benefits Lifestages / Dependents Management Team
https://github.com/department-of-veterans-affairs/va.gov-team/issues/116840
- *Describe the steps required to verify your changes are working as expected. Exclusively …
=> DV | Add DataDog monitoring toggle

.github/CODEOWNERS, lib/lighthouse/healthcare_cost_and_coverage/payment_reconciliation/service.rb, spec/lib/lighthouse/healthcare_cost_and_coverage/payment_reconciliation/service_spec.rb
- *(Summarize the changes that have been made to the platform)*: This is not client/vet facing. This adds the config and Payment Reconciliation resource for the Lighthouse Healthcare Cost and Coverage API. We will be adding more requests immediately after this one. 
- *(What is the solution, why is this the solution?)*: Our team works with "Debts" and "Copays". The Lighthouse Healthcare Cost and Coverage API retrieves Copay data that is more recent. We will eventually use this API to populate Copay data for the veteran.
- *(Which team do you work for, does your team own the maintenance of this component?)*: Financial Management
- *(If introducing a flipper, what is the success criteria being …
=> Lighthouse Payment Reconciliation Resource 2

app/controllers/v0/gi_bill_feedbacks_controller.rb, spec/controllers/v0/gi_bill_feedbacks_controller_spec.rb
This PR adds logging for the gi_bill_feedbacks controller which will allow for us to a) set up monitoring alerts in datadog and b) more easily diagnose and fix failed submissions.
- *Describe what the old behavior was prior …
=> additional logging around gi bill feedback
