department-of-veterans-affairs/vets-api

modules/vaos/app/services/vaos/v2/appointments_reason_code_service.rb, modules/vaos/spec/services/v2/appointments_reason_code_service_spec.rb
- This is part of the api consolidation effort and moves the logic for extracting preferred date information from the reason code text from the FE to BE. The source logic is [here](https://github.com/department-of-veterans-affairs/vets-website/blob/c33b8f64b8d06f67aa0d4af5b9cc4e9b6f9f5f9c/src/applications/vaos/services/appointment/transformers.js#L62-L94)
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/86897
- The old behavior returns the information as part of the reason code text and reasonForAppointment field is non existent.
N/A
N/A
=> Generate preferred dates from request reasoncode.text

db/migrate/20240713000047_drop_decision_review_evidence_attachment_validation.rb, db/schema.rb
This PR is to clean up sensitive data by removing a table that is no longer used. This table is owned by the Decision Reviews team.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/88016
https://github.com/department-of-veterans-affairs/va.gov-team/issues/87405
Ran `rails db:migrate` with no errors
```
== 20240713000047 DropDecisionReviewEvidenceAttachmentValidation: migrating ===
-- remove_index(:decision_review_evidence_attachment_validations, {:column=>:decision_review_evidence_attachment_guid, :name=>"index_dr_evidence_attachment_validation_on_guid"})
-> 0.0031s
-- drop_table(:decision_review_evidence_attachment_validations)
-> 0.0009s
== 20240713000047 DropDecisionReviewEvidenceAttachmentValidation: migrated (0.0060s)
```
This will be a minor impact to the …
=> 88016: Drop DecisionReviewEvidenceAttachmentValidation table

bin/is_ready
This PR does two things:
- Makes is_ready easier to understand by inverting available to unavailable
- Looks for `$AUTOSCALING_TARGET_VALUE` for the allowed unavailable threshold which, once  https://github.com/department-of-veterans-affairs/vets-api/pull/17584 is merged, will combine the two scaling thresholds.
AUTOSCALING_TARGET_VALUE is not set anywhere yet. We should test and deploy this before we start setting it somewhere.
[In our Helm charts](https://github.com/department-of-veterans-affairs/vets-api/blob/parent-helm-charts/chart/templates/hpa-external-metric.yaml), we're calculating an "Unavailability" metric which we use for scaling. When we look at the HPA metric in Datadog, we see the percentage of Puma threads serving requests (which means these pods are unavailable). When we …
=> chore: Use AUTOSCALING_TARGET_VALUE env var in is_ready

config/features.yml
Removed the helpdesk info toggle for the MHV Landing Page. See [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30911) for removing the toggle on the front end.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/87130
N/A
N/A
MHV Landing Page
=> Removed helpdesk info toggle

app/models/form_profiles/va_0873.rb
- This PR is updating the route for the prefill. FE doesn't hit `/topics` anymore.
- Ticket [here](https://app.zenhub.com/workspaces/ask-va-647a476551689d06655cc815/issues/gh/department-of-veterans-affairs/ask-va/755)
- Url was updated to test in dev and staging env. …
=> Ask VA/ Prefill Metadata

.github/CODEOWNERS, app/controllers/claims_base_controller.rb, app/controllers/v0/appointments_controller.rb, app/controllers/v0/burial_claims_controller.rb, app/controllers/v0/messages_controller.rb, app/controllers/v0/preneeds/cemeteries_controller.rb, app/serializers/appointment_serializer.rb, app/serializers/category_serializer.rb, app/serializers/cemetery_serializer.rb, app/serializers/central_mail_submission_serializer.rb, spec/serializers/category_serializer_spec.rb, spec/serializers/cemetery_serializer_spec.rb
- AppointmentSerializer
- CategorySerializer
- CemeterySerializer
- CentralMailSubmissionSerializer
=> Replace Root AMS serializers with JSONAPI serializers - Part 4

app/controllers/v0/profile/ch33_bank_accounts_controller.rb, app/controllers/v0/profile/communication_preferences_controller.rb, app/serializers/ch33_bank_account_serializer.rb, app/serializers/communication_groups_serializer.rb, spec/controllers/v0/profile/ch33_bank_accounts_controller_spec.rb, spec/serializers/ch33_bank_account_serializer_spec.rb, spec/serializers/communication_groups_serializer_spec.rb
- Ch33BankAccountSerializer
- CommunicationGroupsSerializer
Also:
- Refactored CommunicationPreferencesController for readability
=> Replace Root AMS serializers with JSONAPI serializers - Part 5

app/controllers/v0/disability_compensation_forms_controller.rb, app/controllers/v0/education_benefits_claims_controller.rb, app/controllers/v0/profile/direct_deposits/disability_compensations_controller.rb, app/controllers/v0/profile/direct_deposits_controller.rb, app/serializers/disability_compensations_serializer.rb, app/serializers/disability_contention_serializer.rb, app/serializers/education_benefits_claim_serializer.rb, app/serializers/education_stem_claim_status_serializer.rb, spec/factories/disability_compensations.rb, spec/serializers/disability_compensations_serializer_spec.rb
- DisabilityCompensationsSerializer
- DisabilityContentionSerializer
- EducationBenefitsClaimSerializer
- EducationStemClaimStatusSerializer
=> Replace Root AMS serializers with JSONAPI serializers - Part 7

modules/ivc_champva/app/models/ivc_champva/vha_10_7959a.rb, modules/ivc_champva/app/models/ivc_champva/vha_10_7959f_1.rb, modules/ivc_champva/app/models/ivc_champva/vha_10_7959f_2.rb, modules/ivc_champva/spec/models/vha_10_7959a_spec.rb, modules/ivc_champva/spec/models/vha_10_7959f_1_spec.rb, modules/ivc_champva/spec/models/vha_10_7959f_2_spec.rb
As a PEGA user, I need SSN or x-amz-meta-ssn_or_tin for all forms to process in the PEGA workflow.
AC: x-amz-meta-ssn_or_tin is in the metadata for all IVC CHAMPVA forms.
Similar work  for 7959C
(https://github.com/department-of-veterans-affairs/vets-api/pull/17578/files)
Successfully ran unit test for 7959a, 7959f1 and 7959f2.
No pdfs were generated
=> Add ssn to metadata 7959a  7959f1 7959f2

rakelib/prod/user_credential.rake
- Updates logging method to also print to console in production; this makes manual updating of the user_credential lock sheet easier
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/86453
- no functional changes
=> [86453] always puts message to stdout

modules/check_in/app/sidekiq/check_in/travel_claim_status_check_worker.rb, modules/check_in/spec/sidekiq/travel_claim_status_check_worker_spec.rb, spec/support/vcr_cassettes/check_in/btsss/claim_status/claim_status_200.yml, spec/support/vcr_cassettes/check_in/btsss/claim_status/failed_claim_status_200.yml, spec/support/vcr_cassettes/check_in/btsss/claim_status/multiple_claim_status_200.yml, spec/support/vcr_cassettes/check_in/btsss/claim_status/non_matching_claim_status_200.yml
The claim statuses we are getting back from BTSSS claim_status endpoint are in `UpperCamelCase` (or is it `PascalCase`) style. This PR updates our code to handle the statuses.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/85391
*check-in travel claims
=> 85391 update claim statuses

modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb, modules/simple_forms_api/spec/requests/v1/uploads_spec.rb
This reverts commit df17c134f00b60c8bacc4c4f676ec326b3409bf4.
The reverted commit is causing the PMC (40-0247) form to raise errors for unauthenticated users trying to upload supporting documentation.
=> Revert "Remove Simple Forms API's override of #authenticate (#17567)"

bin/is_ready
This queries the `replicas_available` for the appropriate cluster and deployment by using `$DD_ENV` and `$POD_NAME`. If the pod is unhealthy but there are too few of healthy pods in the replica set, the pod will exit 0 forcing it to accumulate a backlog. If all pods are marked as unhealthy, Traefik will drop traffic (503ing). We prefer a line to form (backlog) while new pods spin up rather than just dropping traffic.
To test, start `bin/rails s` and run:
```
AUTOSCALING_TARGET_VALUE=0 bin/is_ready # Force an unhealthy state
echo $? # Run this each time to see exit code
AUTOSCALING_TARGET_VALUE=0 MIN_NOT_READY_PODS=10 bin/is_ready # Force a backlog to accumulate
echo $?
AUTOSCALING_TARGET_VALUE=0 MIN_NOT_READY_PODS=5 bin/is_ready # Play with min not ready to see exit code
echo $?
```
=> feat: is_ready exits 0 when replicaSet unhealthy

modules/debts_api/lib/debts_api/v0/fsr_form_transform/streamlined_calculator.rb
This is a bug fix for the backend transform work. `gmt_threshold` can be `nil`, but this isn't considered in several functions. These functions check if it is higher or lower than other financial metrics. When `gmt_threshold` is `nil`, this makes these functions default to `false` instead of throwing an error.
=> Add nil check for backend transform GMT threshold

modules/simple_forms_api/app/services/simple_forms_api/pdf_filler.rb, modules/simple_forms_api/spec/services/pdf_filler_spec.rb
We've been seeing errors like this one: https://vagov.ddog-gov.com/dashboard/a9w-jhk-den/simple-forms-api?fromUser=false&graphType=flamegraph&refresh_mode=sliding&shouldShowLegend=true&sort=time&spanID=551294370726133741&spanViewType=errors&traceID=594988394759685708&view=spans&from_ts=1721227852516&to_ts=1721400652516&live=true -- `stamped template file does not exist`
After a bit of research, I came across this workaround with `Tempfile`: https://github.com/actions/runner-images/issues/4443#issuecomment-965391736
And I thought it was worth a try!
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/88703
=> Tempfile workaround for Simple Forms PDF filling

config/features.yml
Removed the MHV secondary navigation toggle. 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/87134
N/A
N/A
MHV secondary navigation
=> Removed secondary navigation toggle

modules/claims_api/app/swagger/claims_api/v2/dev/swagger.json, modules/claims_api/app/swagger/claims_api/v2/production/swagger.json, modules/claims_api/config/schemas/v2/526.json, modules/claims_api/spec/requests/v2/veterans/disability_compensation_request_spec.rb
- Implements changes to the 526 schema related to direct deposit information.
- accoutNumber field updated to allow 1000 characters max, allowing digits and dashes.
- routingNumber field updated to allow 1000 characters max, allowing only digits.
- financialInstitutionName field updated to allow 1000 characters max. 
[API-38042](https://jira.devops.va.gov/browse/API-38042)
- Previous validation errored on dashes in accountNumber field, length greater than 14
- Previous validation errored on routingNumber greater than 9 characters.
- Previous validation errored on financialInstitutionName greater than 35 characters.
526 validation for the following endpoints:
POST /veterans/{veteranId}/526/validate
POST /veterans/{veteranId}/526
POST …
=> Api 38042 validation direct deposit

modules/simple_forms_api/app/controllers/simple_forms_api/v1/scanned_form_uploads_controller.rb
- This work allows for the front end to specify the user's ssn, va file number, and their zip code when they're not readily available within the current user's data
- [Form Upload - Support LOA1 to edit SSN & Zip Code](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/1388)
- Browser testing successful
- Only form upload related logic
Any
=> [SIMPLE_FORMS] feat: form-upload - update submit logic to account for extra values

modules/simple_forms_api/app/services/simple_forms_api/pdf_stamper.rb
This adds some logging where I _think_ we're getting a number of exceptions. Unfortunately, it seems like our `verify` method is swallowing some of the stacktrace (maybe because we yield to a passed-in block) so hopefully this will clarify which of our errors come from this method.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/88703
=> Add logging whenever Simple Forms fails to perform multistamp on PDF

spec/sidekiq/lighthouse/form526_document_upload_polling_job_spec.rb
- Tests in this file have suddenly started failing. Skipping them until they can be debugged. 
Some failing specs [on master](https://github.com/department-of-veterans-affairs/vets-api/commits/master/):
- https://github.com/department-of-veterans-affairs/vets-api/actions/runs/10058710384/job/27802392805
- https://github.com/department-of-veterans-affairs/vets-api/actions/runs/10048055875/job/27776345076
- https://github.com/department-of-veterans-affairs/vets-api/actions/runs/10048596527/job/27772903049
spec/sidekiq/lighthouse/form526_document_upload_polling_job_spec.rb
=> Skip failing spec file, form526_document_upload_polling_job_spec.rb

modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb
This PR adds logging whenever we submit a 26-4555 form to the LGY (Loan Guaranty) API endpoint.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/1206
=> Add logging for sending 26-4555 to LGY from Simple Forms

modules/vye/app/models/concerns/vye/needs_enrollment_verification.rb, modules/vye/app/models/vye/user_info.rb, modules/vye/spec/models/vye/user_info_spec.rb
- Updated enrollment verification logic to account for nils we are seeing in prod. The Enrollment Logic handles determining when an enrollment period is ready to be verified by the veteran. The data supplied is run through each of the 11 different cases until one is satisfied and is returned as a period that is ready for verification. If none of the cases are satisfied, then the enrollment period is not ready to be verified. 
- Testing has been handled on local machine manually and with the creation of RSpec tests.
- Award end Date can be NIL and the previous code did not handle for NIL. 
- This code has been tested on local machine and now handles NIL values within the enrollment logic. 
- Peer review of this code was completed as well by walking through each case with another developer …
=> Enrollment verification updates

app/models/lighthouse_document.rb, modules/mobile/spec/request/claims_document_upload_spec.rb
We can check ahead of time whether a lighthouse document upload will fail due to the wrong file extension type. This adds validation at the model level
https://github.com/department-of-veterans-affairs/va-mobile-app/issues/9023
Existing tests cover the changes
=> Check for file extension in lighthouse document model

bin/is_ready
We were getting timeout errors in Argo and the pod was being marked unhealthy.
This adds a two second timeout for DD and puma.
=> feat: is_ready: Timeout if puma/dd slow

spec/sidekiq/lighthouse/form526_document_upload_polling_job_spec.rb
- Converted `lighthouse_document_request_id` values to strings in an effort to address failing, flaky tests
- https://github.com/department-of-veterans-affairs/vets-api/pull/17660
- spec/sidekiq/lighthouse/form526_document_upload_polling_job_spec.rb
=> [DBEX] ID type conversion

config/features.yml
- Added `cst_synchronous_evidence_uploads` feature flag to `vets-api`
- [[CST] Make evidence submission a synchronous task](https://github.com/department-of-veterans-affairs/va.gov-team/issues/76660)
- [[PR] [CST] [Frontend] Added a feature flag for making evidence uploads a synchronous task](https://github.com/department-of-veterans-affairs/vets-website/pull/30975)
=> [CST] [Backend] Added a feature flag for making evidence uploads a synchronous task

config/settings.yml
This PR adds `lgy_sahsha` to the `Settings` object on production. I already populated the three fields in AWS SSM.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/88998
=> Add lgy_sahsha defaults to Settings

db/migrate/20240722150708_add_service_account_configs_array_defaults.rb, db/migrate/20240722150751_add_client_configs_array_defaults.rb, db/schema.rb, db/seeds/development.rb
Add empty array defaults to `SignIn::ServiceAccountConfig.scopes`, `SignIn::ServiceAccountConfig.certificates`, and `SignIn::ClientConfig.certificates`. It is expected to receive an empty array when calling the API and is consistent with other array columns in these tables.
These will be run in all envs 
```ruby
SignIn::ServiceAccountConfig.where(certificates: nil).update(certificates: [])
SignIn::ServiceAccountConfig.where(scopes: nil).update(scopes: [])
SignIn::ClientConfig.where(certificates: nil).update(certificates: [])
```
- Migrate database
```bash
rails db:migrate
```
- Seed database
```bash
rails db:seed
```
Sign-in Service
=> Add array defaults to sign_in_service configs

app/sidekiq/evss/disability_compensation_form/form4142_document_upload_failure_email.rb, spec/sidekiq/evss/disability_compensation_form/form4142_document_upload_failure_email_spec.rb
Implements the `retryable_error_handler` pattern for jobs including the `Sidekiq::Form526JobStatusTracker::JobTracker` concern in the `EVSS::DisabilityCompensationForm::Form4142DocumentUploadFailureEmail` job. This method is meant to catch any errors thrown in the perform block so we can log them in a Form526JobStatus record before we lose the trace and the job falls into the Sidekiq dead queue (that's my understanding based on the documentation in the tracker concern)
- *This work is behind a feature toggle (flipper): NO (the job is already behind a flipper I discovered this issue in testing)
- *(Which team do you work for, does your team own the maintenance of this component?)* Benefits Disability Team, I will be testing, releasing and monitoring the release of this mailer.
- …
=> Add error handler implementation to Form4142DocumentUploadFailureEmail job

app/models/form526_submission.rb, app/sidekiq/form526_status_polling_job.rb, lib/periodic_jobs.rb, spec/factories/form526_submissions.rb, spec/models/form526_submission_spec.rb, spec/sidekiq/form526_status_polling_job_spec.rb
Reverts department-of-veterans-affairs/vets-api#17621
Error seen in ArgoCD dev and staging sidekiq pod logs:
```
undefined local variable or method `args' for main
/app/lib/periodic_jobs.rb:46:in `block in <top (required)>'
```
=> Revert "[DBX-88811] treat LH BI success state as true success"

modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb
This PR uses an alternative to `:authenticate` in the `UploadsController` so that it will allow unauthenticated users to proceed even though there will be no `@current_user` object populated. But it will populate that instance variable in other cases.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/88938
I tested this locally with both unauthed and authenticated users and got expected results from `@current_user`.
=> Replace Simple Forms' authentication override with :load_user

modules/vaos/app/services/vaos/v2/appointments_reason_code_service.rb, modules/vaos/spec/services/v2/appointments_reason_code_service_spec.rb
- This is part of the api consolidation effort and implements a field rename that was decided in a related PR discussion.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/89163
- The old behavior returns the information as part of the reason code text and additionalAppointmentDetails field is non existent.
N/A
N/A
=> VAOS rename additionalAppointmentDetails to patientComments

app/controllers/v0/feature_toggles_controller.rb
`fetch_features_with_gate_keys` collects all the features together and appends information for `add_feature_gate_values`. I removed the cachiing of the sql call as `fetch_features_with_gate_keys` is the only place it is called AND it could cause features to be cached for up to 2 minutes.
Moving the caching here improves response times considerably [compared to the optimizations](https://github.com/department-of-veterans-affairs/vets-api/pull/17679).
Future caching could add russian doll caches based on `MAX updated_at`.
=> feat: Feature Toggles: Cache cpu-intense iterations

app/controllers/v0/feature_toggles_controller.rb
Adds russian-doll-style caching on top of the [CPU-intense caching](https://github.com/department-of-veterans-affairs/vets-api/pull/17693). This makes it so it only checks in once per 24 hours if none of the feature toggles have changed—at the cost of querying the max updated_at once per minute (which is still just one sql query).
=> feat: Feature Toggles: Add russian doll caching

modules/ask_va_api/app/services/crm/service.rb
- Udpated `crm-api` `staging/base_url` in `Parameter Store`
- Updated `Crm::Service` class to use `base_url` from `Settings.yml`
- https://github.com/department-of-veterans-affairs/ask-va/issues/1161
=> BE | Ask VA API: update base_url for staging

app/controllers/v0/gi_bill_feedbacks_controller.rb, app/controllers/v0/health_care_applications_controller.rb, app/controllers/v0/intent_to_files_controller.rb, app/controllers/v0/letters_controller.rb, app/serializers/gi_bill_feedback_serializer.rb, app/serializers/hca_rating_info_serializer.rb, app/serializers/health_care_application_serializer.rb, app/serializers/intent_to_file_serializer.rb, app/serializers/letter_beneficiary_serializer.rb, app/serializers/letters_serializer.rb, spec/serializers/health_care_application_serializer_spec.rb
- GIBillFeedbackSerializer
- HCARatingInfoSerializer
- HealthCareApplicationSerializer
- IntentToFileSerializer
- LetterBeneficiarySerializer
- LetterSerializer
=> Replace Root AMS serializers with JSONAPI serializers - Part 9

app/controllers/v0/in_progress_forms_controller.rb, app/serializers/in_progress_form_serializer.rb, spec/requests/in_progress_forms_request_spec.rb, spec/serializers/in_progress_form_serializer_spec.rb
- My understanding is that metadata shouldn't change case, unless header `X-Key-Inflection` is specified
- The original serializer spec was passing because it was taking into account AMS deep key transformation (to snake case). Those examples were removed: `deeply transformed the keys to snake_case` & `corrupts complicated keys`
- A couple very minor refactorings for readability
- InProgressFormSerializer
- https://github.com/department-of-veterans-affairs/vets-api/pull/5582
=> Replace Root AMS serializers with JSONAPI serializers - InProgressForms

app/models/form526_submission.rb, app/sidekiq/form526_status_polling_job.rb, lib/periodic_jobs.rb, spec/factories/form526_submissions.rb, spec/models/form526_submission_spec.rb, spec/sidekiq/form526_status_polling_job_spec.rb
The first was merged and reverted. this includes a syntax fix for the Sidekick job config. The last version of this attempted to use this syntax incorrectly. I've made two changes here, first is to make `args` into `'args'` which fixes the intial no method error. The second is to forgo using named arguments so my syntax is a 1 to 1 match with the docs.
I've ran through this in a staging command line to confirm there are no syntax errors. However, there is no way (that I know of) to make sure this job will actually receive it's arguments correctly using this syntax until it actually runs. Thankfully, that is perfectly safe. If the job fails on Sunday, we will have a nice error message in Datadog telling us what went wrong and the application will be unaffected.
cc @rmtolmach who caught the …
=> [Dbx 88811] add paranoid success polling for 526

app/models/health_care_application.rb, config/features.yml, spec/models/health_care_application_spec.rb
- Removing Flipper toggle since we no longer need to toggle this feature. We will merge this after we turn the feature on in production. 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/85948
- Previously it would use the old ApplicationMailer if the toggle was off. Now it will _always_ use VANotify to send an email.
1010-EZ
=> [10-10 EZ] 85948 Remove HCA Failure Submission Email Flipper Toggle

lib/statsd_middleware.rb
[This monitor](https://vagov.ddog-gov.com/monitors/200229) keeps telling us about burials-ez. Fixing by adding it to `lib/statsd_middleware.rb`, as explained in the monitor's message.
=> Add burials-ez

modules/ivc_champva/app/controllers/ivc_champva/v1/uploads_controller.rb, modules/ivc_champva/app/models/ivc_champva/vha_10_10d.rb, modules/ivc_champva/app/models/ivc_champva/vha_10_7959a.rb, modules/ivc_champva/app/models/ivc_champva/vha_10_7959c.rb, modules/ivc_champva/app/models/ivc_champva/vha_10_7959f_1.rb
Add logic to track current user LOA
- Add `track_current_user_loa` to a few models
- Add `track_user_identity` to a couple models missing it
- Add new method to `uploads_controller`
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/88263
As a member of the IVC forms team, I want to see metrics for how many users are authenticated versus not authenticated.
If possible, include LOA level.
=> 88263: Add logic for DataDog current user tracking

modules/simple_forms_api/app/services/simple_forms_api/pdf_filler.rb, modules/simple_forms_api/app/services/simple_forms_api/pdf_stamper.rb, modules/simple_forms_api/spec/services/pdf_filler_spec.rb
We've been seeing flaky errors from our PDF Stamper and I have a hunch that these randomly-generated paths are not correct. Based on this Stack Overflow question, I think supplying `Rails.root` might help it. The question is very old but I notice that someone updated it in 2023 saying that in Rails 7, the behavior still works this way so I'm hopeful.
I should note that if this actually resolves the problem fully, I'd be a little surprised since I'd think this would fail 100% of the time. But it only fails 10% of the time. Somehow relative paths work most of the time but not all the time? Seems odd...
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/88703
=> Use complete file path when stamping Simple Forms PDF

modules/representation_management/spec/models/representation_management/accredited_individual_search_spec.rb, modules/representation_management/spec/requests/v0/accredited_individuals_request_spec.rb
- This pr adds the request and search model validation specs for the [controller added here](https://github.com/department-of-veterans-affairs/vets-api/pull/16861).
- [78745](https://github.com/department-of-veterans-affairs/va.gov-team/issues/78745)
- tested controller in postman
Impacts the `representation_management` module
=> 78745 - Add accredited rep request spec

modules/vaos/app/services/vaos/v2/appointments_reason_code_service.rb, modules/vaos/spec/factories/v2/appointment_forms.rb, modules/vaos/spec/services/v2/appointments_reason_code_service_spec.rb
- This is part of the api consolidation effort and moves the logic for extracting additional appointment details and reason for appointment from the reason code text from the FE to BE for Direct Scheduled (DS) appointments. The source logic is [here](https://github.com/department-of-veterans-affairs/vets-website/blob/6e8dc3ca9de43eb9ee11c347d1250043fef9436e/src/applications/vaos/new-appointment/redux/helpers/getReasonCode.js#L49-L52)
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/88692
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/88693
- The old behavior returns the information as part of the reason code text and reasonForAppointment field is …
=> Extract reason code text fields from DS appointments

spec/sidekiq/lighthouse/form526_document_upload_polling_job_spec.rb
- User [VCR's request matching on body](https://benoittgt.github.io/vcr/#/request_matching/body) option in an effort to address failing, flaky tests
- https://github.com/department-of-veterans-affairs/vets-api/pull/17660
- https://github.com/department-of-veterans-affairs/vets-api/pull/17674
- spec/sidekiq/lighthouse/form526_document_upload_polling_job_spec.rb
=> [DBEX] add body request matcher

modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb, modules/simple_forms_api/app/services/simple_forms_api/intent_to_file.rb, modules/simple_forms_api/spec/services/intent_to_file_spec.rb
In preparation for more changes to how to fetch the `participant_id` when handling form 21-0966, I wanted to refactor our controller a little bit. The overriding idea here is to push more 0966-specific logic down to the `IntentToFile` service and out of the controller.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/88757
Tests are still passing. One needed modification to pass.
=> Small refactor of Simple Forms Intent logic

lib/lighthouse/benefits_claims/intent_to_file/monitor.rb
- The previously added change to the logger attempted to call the #errors method on the thrown exception. But this method is only defined within the custom `ClaimsApi::Common::Exceptions::Lighthouse::UnprocessableEntity` exception. Standard Ruby exceptions do not contain this function, so when a standard exception is thrown, the code would error out and not log the true error properly.
- The code should attempt to call the #errors method using a try function to prevent errors from being thrown if the #errors function isn't defined for the thrown exception. If no #error function is defined, then default to the #message function of the thrown exception.
- Pension team to own this change.
- [*Link to ticket created in va.gov-team …
=> added default error message if #errors method does not exist in thrown exception

config/features.yml
This PR add feature toggle `va_online_scheduling_OH_direct_schedule` and `va_online_scheduling_OH_request` for controlling Oracle Health request and direct scheduling workflows.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/89139
N/A
N/A
VAOS
=> Add OH direct schedule and request feature toggles

app/controllers/claims_base_controller.rb, app/controllers/v0/burial_claims_controller.rb, app/controllers/v0/dependents_applications_controller.rb, app/controllers/v0/dependents_verifications_controller.rb, app/controllers/v0/education_career_counseling_claims_controller.rb, app/controllers/v0/pension_claims_controller.rb, app/controllers/v0/veteran_readiness_employment_claims_controller.rb, app/serializers/saved_claim_serializer.rb, modules/pensions/app/controllers/pensions/v0/pension_claims_controller.rb
=> Replace Root AMS serializers with JSONAPI serializers - Part SavedClaim

.github/CODEOWNERS, app/controllers/concerns/json_api_pagination_links.rb, app/controllers/rx_controller.rb, app/controllers/v0/profile/valid_va_file_numbers_controller.rb, app/controllers/v0/trackings_controller.rb, app/controllers/v0/triage_teams_controller.rb, app/controllers/v0/users_controller.rb, app/serializers/tracking_serializer.rb, app/serializers/triage_team_serializer.rb, app/serializers/user_serializer.rb, app/serializers/valid_va_file_number_serializer.rb, spec/serializers/tracking_serializer_spec.rb, spec/serializers/triage_team_serializer_spec.rb, spec/serializers/user_serializer_spec.rb
- TrackingSerializer
- TriageTeamSerializer
- UserSerializer
- ValidVAFileNumberSerializer
TrackingSerializer require pagination, so `JsonApiPaginationLinks` was added as a concern to `RxController`
=> Replace Root AMS serializers with JSONAPI serializers - Part 14

.github/CODEOWNERS, app/controllers/concerns/json_api_pagination_links.rb, app/controllers/sm_controller.rb, app/controllers/v0/folders_controller.rb, app/controllers/v0/message_drafts_controller.rb, app/controllers/v0/messages_controller.rb, app/controllers/v0/messaging_preferences_controller.rb, app/serializers/attachment_serializer.rb, app/serializers/folder_serializer.rb, app/serializers/message_serializer.rb, app/serializers/messages_serializer.rb, app/serializers/messaging_preference_serializer.rb, spec/serializers/attachment_serializer_spec.rb, spec/serializers/message_serializer_spec.rb
- AttachmentSerializer
- FolderSerializer
- MessageSerializer
- MessagesSerializer
- MessagingPreferenceSerializer
Added `JsonApiPaginationLinks` for `FoldersController` and `MessagesController`
=> Replace Root AMS serializers with JSONAPI serializers - Part Message

app/models/form526_submission.rb, spec/factories/form526_submissions.rb, spec/models/form526_submission_spec.rb
- UPdate the `MAX_PENDING_TIME` used to define 526 submissions as 'in process' from 3 days to 2 weeks.
- 3 days was an intial naive guess to get us started. According to the Benefits Intake API docs, submissions can take up to two weeks to receive a pollable status, which is what this window is accounting for
- [Ticket](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/89297)
- [Relevant API docs](https://developer.va.gov/explore/api/benefits-intake/docs?version=current)
- We care specifically about this bit: 
- [Document  about why we care](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability …
=> [DBX] bump max 526 pending time to 2 weeks

config/puma.rb
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/3015 removes the use of PUMA_THREADS.
This is no longer needed.
=> chore: Remove unused puma_threads env var

modules/claims_api/lib/bd/bd.rb, modules/claims_api/spec/lib/claims_api/bd_spec.rb
- Certain `doc_types` (e.g., `L023`) will fail to be identified without an `evss_id`. Fallback to `evss_id` for `claim_id` for `doc_types` that do not have other requirements.
- Fallback to 'supporting' for doc_types not listed.
N/A
N/A
Benefits documents upload
N/A
=> Hotfix: Fallback to `evss_id` for `claim_id`

app/controllers/v0/feature_toggles_controller.rb, config/features.yml, spec/controllers/v0/feature_toggles_controller_spec.rb
New feature toggle logic is working well in production. Clean up old code/feature toggle.
=> chore: Remove use_new_get_all_features feature

app/controllers/v0/in_progress_forms_controller.rb
- Pass in the current user into the Flipper.enabled call to allow percentage of traffic in production.
- [*Link to ticket created in va.gov-team repo*](https://github.com/department-of-veterans-affairs/va.gov-team/issues/81536)
- *What is …
=> Pass user to Flipper logic to allow partially enabled traffic

app/controllers/v0/disability_compensation_forms_controller.rb, app/controllers/v0/preneeds/burial_forms_controller.rb, app/controllers/v0/profile/service_histories_controller.rb, app/controllers/v0/search_controller.rb, app/serializers/rated_disabilities_serializer.rb, app/serializers/rating_info_serializer.rb, app/serializers/receive_application_serializer.rb, app/serializers/search_serializer.rb, app/serializers/service_history_serializer.rb, spec/serializers/receive_application_serializer_spec.rb, spec/serializers/service_history_serializer_spec.rb
- RatedDisabilitiesSerializer
- ReceiveApplicationSerializer
- SearchSerializer
- ServiceHistorySerializer
=> Replace Root AMS serializers with JSONAPI serializers - Part 13

modules/my_health/app/controllers/my_health/v1/messages_controller.rb, modules/my_health/app/controllers/my_health/v1/messaging_preferences_controller.rb, modules/my_health/app/serializers/my_health/v1/message_signature_serializer.rb, modules/my_health/app/serializers/my_health/v1/messaging_preference_serializer.rb, modules/my_health/spec/serializer/v1/message_signature_serializer_spec.rb, modules/my_health/spec/serializer/v1/messaging_preference_serializer_spec.rb
- MessageSignatureSerializer
- MessagingPreferenceSerializer
Note:
- _Per conversation with Oleskii Morgun:_ MessageSignatureSerializer is not using JSON:API serializer and the mhv team will update it and the FE in the future
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/86385
=> Replace MyHealth AMS serializers with JSONAPI serializers - Messages Part 2

modules/mobile/app/controllers/mobile/v0/threads_controller.rb, modules/my_health/app/controllers/my_health/rx_controller.rb, modules/my_health/app/controllers/my_health/v1/threads_controller.rb, modules/my_health/app/controllers/my_health/v1/trackings_controller.rb, modules/my_health/app/serializers/my_health/v1/threads_serializer.rb, modules/my_health/app/serializers/my_health/v1/tracking_serializer.rb, modules/my_health/spec/serializer/v1/thread_serializer_spec.rb, modules/my_health/spec/serializer/v1/tracking_serializer_spec.rb
- ThreadsSerializer
- TrackingSerializer
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/86385
=> Replace MyHealth AMS serializers with JSONAPI serializers - Part 3

app/controllers/v0/dependents_applications_controller.rb, app/serializers/dependents_serializer.rb, spec/serializers/dependents_serializer_spec.rb
- This work is behind a feature toggle (flipper): **NO**
- Adds two extra fields to dependents index api call
- `upcoming_renewal`
- `dependent_benefit_type`
- The fields above are to help veterans understand information about their dependents
- department-of-veterans-affairs/va.gov-team/issues/87272
- Tested through console multiple variations of dependents info to verify the fields are left nil or filled as appropriate
This will impact the dependents page for veterans after the frontend has added the corresponding fields
=> Dependents Card Extra Information

config/sidekiq.yml
This allows setting Sidekiq's concurrency [via our k8s values](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/3034).
When running:
```shell
RAILS_MAX_THREADS=7 bundle exec sidekiq
```
I see the expected threads (sidekiq_alive adds 2):
=> feat: Use RAILS_MAX_THREADS for Sidekiq concurrency

modules/vaos/app/services/vaos/v2/appointments_reason_code_service.rb, modules/vaos/spec/factories/v2/appointment_forms.rb, modules/vaos/spec/services/v2/appointments_reason_code_service_spec.rb
- This is part of the api consolidation effort and solves an issue where the reason code key is `reason code` for appointment requests and `reasonCode` for DS appointments
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/88692
- The old behavior returns the information as part of the reason code text and reasonForAppointment field is non existent.
N/A
N/A
=> VAOS reason code should fallback to reasonCode to support DS appointments

db/migrate/20240722144512_remove_inherited_proof_verified_user_accounts.rb, db/schema.rb
- removes `inherited_proof_verified_user_accounts` table & associations
- Inherited Proofing functionality removed in https://github.com/department-of-veterans-affairs/vets-api/pull/17417
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/65692
- no changes, table is no longer used
- authentication performed
=> [65692] removes inherited_proof_verified_user_accounts

app/models/form526_submission.rb, spec/factories/form526_submissions.rb, spec/models/form526_submission_spec.rb
- Update the 'in process' window for 526 backup path polling from 2 weeks to 3 weeks. This accounts for edge cases, the 24 hour delay in BI polling (it's a nightly job), as well as the 2 days of Sidekiq runtime that may proceed the start of polling
- This is not a user facing change. This unblocks upcoming monitoring work
- [Ticket](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/89297)
- [Document about this work](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/untouched_submission_audit/526_state_repair_tdd.md)
- Nothing to test apart from syntax, which is …
=> [DBX-89297] bump in_process window to 3 weeks for edge cases

app/sidekiq/evss/disability_compensation_form/form4142_document_upload_failure_email.rb, app/sidekiq/evss/disability_compensation_form/form526_document_upload_failure_email.rb, spec/sidekiq/evss/disability_compensation_form/form4142_document_upload_failure_email_spec.rb, spec/sidekiq/evss/disability_compensation_form/form526_document_upload_failure_email_spec.rb
The retry and error logging for these jobs didn't include the actual error message in addition to the class as is done in other jobs; we need this information if we're to debug issues with these mailers
- *This work is behind a feature toggle (flipper): YES the jobs themselves are hidden behind a flipper; only the Form 526 evidence job is on in production but its failing when attempting to send the mailer through VA Notify so I need the additional logging to investigate
- *(Which team do you work for, does your team own the maintenance of this component?)* Disability Benefits
N/A
N/A
N/A this is in a sidekiq mailer job
- [X  Events are being sent to the appropriate logging solution]
While I was able to build tests for the retry logic, there is no automated tests for a catastrophic mailer …
=> Add error message logging to Form526 document failure mailers

modules/claims_api/app/sidekiq/claims_api/poa_vbms_upload_job.rb, modules/claims_api/spec/sidekiq/poa_vbms_upload_job_spec.rb
Add feature flag to the Power of Attorney v1 `put` endpoint. 
* If the feature flag is enabled, upload via Benefits Documents with `doc_type` of L075.
* Otherwise, continue uploading via VBMS as before.
* Add tests.
[API-37989](https://jira.devops.va.gov/browse/API-37989)
N/A
POA v1 `PUT /2122/{id}` endpoint
Could use help testing end-to-end.
=> [API-37989] POA v1 PUT /2122/{id} - Use Benefits Documents API

config/initializers/sidekiq.rb
Fixes issues for people who run Sidekiq locally w/o Sidekiq Enterprise.
=> fix: Sidekiq Health check only runs on Enterprise

app/sidekiq/decision_review/saved_claim_hlr_status_updater_job.rb, app/sidekiq/decision_review/saved_claim_nod_status_updater_job.rb, app/sidekiq/decision_review/saved_claim_sc_status_updater_job.rb, config/features.yml, lib/periodic_jobs.rb, spec/sidekiq/decision_review/saved_claim_hlr_status_updater_job_spec.rb, spec/sidekiq/decision_review/saved_claim_nod_status_updater_job_spec.rb, spec/sidekiq/decision_review/saved_claim_sc_status_updater_job_spec.rb
Adds scheduled jobs to set the `delete_date` of completed DR `SavedClaim` records:
* `SavedClaim::HigherLevelReview`
* `SavedClaim::NoticeOfDisagreement`
* `SavedClaim::SupplementalClaim`
Each job to update a particular class is behind a separate flipper flag:
* `decision_review_saved_claim_hlr_status_updater_job_enabled` - HigherLevelReview
* `decision_review_saved_claim_nod_status_updater_job_enabled` - NoticeOfDisagreement
* `decision_review_saved_claim_sc_status_updater_job_enabled` - SupplementalClaim
Each job is scheduled to run once every hour, with an offset of 10 min between each job (`xx:20`, `xx:30`, `xx:40`)
https://github.com/department-of-veterans-affairs/va.gov-team/issues/84332
This has been tested locally and in rspec. …
=> 84332: Add DR SavedClaim status updater jobs with hourly schedule

modules/ivc_champva/app/controllers/ivc_champva/v1/uploads_controller.rb, modules/ivc_champva/app/models/ivc_champva/vha_10_10d.rb, modules/ivc_champva/app/models/ivc_champva/vha_10_7959a.rb, modules/ivc_champva/app/models/ivc_champva/vha_10_7959c.rb, modules/ivc_champva/app/models/ivc_champva/vha_10_7959f_1.rb
Add DataDog tracking for when an applicant adds an email or not per form
- Add new method to all models
- Add method to uploads_controller
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/88208
- Manual
- I can see percentages for a given time span for the percentage of users who are including at least 1 email* versus leaving email blank
- Since datadog is under our control and we want this metric available at go live, we should plan on including it there
=> 88208: Add tracking for email usage

config/features.yml
- Adds a feature flag for prefilling military history in the Pensions form
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/88432
- Ran vets-api and toggled on http://localhost:3000/flipper/features/pension_military_prefill
Pensions
=> Add military history prefill feature flag

modules/vye/app/controllers/vye/v1/user_infos_controller.rb, modules/vye/app/serializers/vye/address_change_serializer.rb, modules/vye/app/serializers/vye/pending_document_serializer.rb, modules/vye/app/serializers/vye/user_info_serializer.rb, modules/vye/app/serializers/vye/verification_serializer.rb, modules/vye/spec/requests/vye/v1/show_spec.rb, modules/vye/spec/serializers/address_change_serializer_spec.rb, modules/vye/spec/serializers/pending_document_serializer_spec.rb, modules/vye/spec/serializers/user_info_serializer_spec.rb, modules/vye/spec/serializers/verification_serializer_spec.rb
In an effort to remove AMS serializers, this non-JSON:API serializer needs a custom serializer
- Convert AMS serializer to custom serializer
- The response is identical to the AMS serializer response
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/88861
=> Use custom serializer for VYE serializers

app/controllers/v0/disability_compensation_forms_controller.rb, app/serializers/evss_separation_location_serializer.rb, spec/serializers/evss_separation_location_serializer_spec.rb
In an effort to remove AMS serializers, this non-JSON:API serializer needs a custom serializer
- Convert AMS serializer to custom serializer
- The response is identical to the AMS serializer response
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/88861
=> Use custom serializer for EVSSSeparationLocationSerializer

modules/claims_api/app/swagger/claims_api/v2/dev/swagger.json, modules/claims_api/app/swagger/claims_api/v2/production/swagger.json, modules/claims_api/config/schemas/v2/526.json, modules/claims_api/config/schemas/v2/generate_pdf_526.json, modules/claims_api/lib/claims_api/v2/disability_compensation_pdf_mapper.rb, modules/claims_api/spec/fixtures/v2/veterans/disability_compensation/form_526_json_api.json, modules/claims_api/spec/lib/claims_api/v2/disability_compensation_pdf_mapper_spec.rb
- Fix 500 when POSTing with `homeless` without `pointOfContactNumber`.
- Add isCurrentlyHomeless and isAtRiskOfBecomingHomeless to the 'Maximum Request Example'
- Move isAtRiskOfBecomingHomeless to be right above riskOfBecomingHomeless in the schema docs
- [API-38658](https://jira.devops.va.gov/browse/API-38658)
v2 526 submissions (and docs)
=> Update docs and fix phone bug

app/controllers/v0/health_records_controller.rb, app/serializers/eligible_data_classes_serializer.rb, spec/serializers/eligible_data_classes_serializer_spec.rb
- EligibleDataClassesSerializer
=> Replace EligibleDataClassesSerializer AMS with JSONAPI 

config/features.yml
added feature flag to hold off on showing allergies data until medical records app goes into phase 1
[Change content and add link for allergies](https://jira.devops.va.gov/browse/MHV-60168)
manually checked that the flag was displaying on the flipper ui
=> [MHV 60168] added feature flag for allergies.

Gemfile.lock
https://www.ruby-lang.org/en/news/2024/08/01/dos-rexml-cve-2024-41946/
There is a DoS vulnerability in REXML gem. This vulnerability has been assigned the CVE identifier [CVE-2024-41946](https://www.cve.org/CVERecord?id=CVE-2024-41946). We strongly recommend upgrading the REXML gem.
When parsing an XML that has many entity expansions with SAX2 or pull parser API, REXML gem may take long time.
Please update REXML gem to version 3.3.3 or later.
Affected versions:
- REXML gem 3.3.2 or prior
=> fix: Update rexml 3.3.2->3.3.4 for CVE-2024-41946

lib/map/security_token/service.rb, spec/lib/map/security_token/service_spec.rb, spec/support/vcr_cassettes/map/security_token_service_500_response.yml
This PR implements a small change that correct logs server errors for the MAP STS token service. Previously, 5XX errors were logged as "client error."
https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/gh/department-of-veterans-affairs/va.gov-team/88176
- Modify the [mock data file](https://github.com/department-of-veterans-affairs/vets-api-mockdata/blob/master/map/secure_token_service/token.yml) locally to return a 500 status with body `{"error":"server_error"}`
- Load the MAP STS client in a rails console
- Send a request (use `:appointments` for `application` and any value for `icn`)
- Verify the rails logger logs the server error.
Not relevant.
Log entries from MAP STS.
I opted for the simplest solution to avoid incurring additional risk. Another possible …
=> 88176 - Parse MAP STS server errors

app/controllers/v0/feature_toggles_controller.rb
The cache key was based on the last time a feature's gate changed. Unfortunately this won't work for features that are enabled for everyone and then disabled as the key would not bust the cache properly.
This is because Flipper doesn't set the gate to false but DELETEs the gate completely thus making the next `MAX(updated_at)` in line the cache key.
I suppose this could be fixed by touching the feature_toggle when the related gate is deleted. The code change in this PR would not need to be done.  The performance hit here isn't enough for me to go down that path at the moment.
Try this out on master and this branch:
```shell
echo "Restarting Rails Server..."; kill -USR2 $(cat tmp/pids/server.pid); sleep 6
redis-cli flushall; rm tmp/caching-dev.txt 2> /dev/null; rails dev:cache
bin/rails …
```
=> fix: Remove nested caching for feature toggles

.github/workflows/audit_service_tags.yml, .github/workflows/code_checks.yml
The docker-compose command is breaking the Audit Service Tags and Code Checks Test github action. The solution was found in this [discussion](https://github.com/orgs/community/discussions/116610).
[Failing Code Checks](https://github.com/department-of-veterans-affairs/vets-api/actions/workflows/code_checks.yml)
[Failing Audit Service Tag actions](https://github.com/department-of-veterans-affairs/vets-api/actions/workflows/audit_service_tags.yml)
The latest Ubuntu release (ubuntu-latest) in [Ubuntu 22.04 (20240730) Image …
=> Modified docker compose commands due to Ubuntu upgrades

config/betamocks/services_config.yml
- *Setting betamocks config for vaos endpoint*
- *https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/81883*
NA
=> Setting betamocks config for vaos endpoint

lib/search_typeahead/configuration.rb, lib/search_typeahead/service.rb
SearchTypeaheadController is causing site-wide latency for the vets-api-web bulkhead.
For an endpoint like Search Typeahead, the result should be nearly instantaneous and not require a long timeout. Lowering to [a sane value](https://github.com/ankane/the-ultimate-guide-to-ruby-timeouts?tab=readme-ov-file#faraday).
=> fix: Add timeout to search typeahead

.github/workflows/code_health_report.yml, .reek.yml
- Add Code Smell Check to CI 
- Non-blocking 
- Uses Pronto & Reek
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/89902
=> Add Code Smell CI check

db/seeds/development.rb
- This PR updates the seed database for 'identity_dashboard' values for `client_id`, `redirect_uri`, `logout_redirect_uri`, `access_token_audience`.
- https://jira.devops.va.gov/browse/VI-229
Client configurations for SiS.
None
=> VI-229: Update ClientConfig identity_dashboard values

modules/claims_api/app/controllers/concerns/claims_api/poa_verification.rb, spec/support/poa_stub.rb
We currently have duplicate validation logic in BGS and ClaimsApi. Since we are migrating away from BGS, decouple ClaimsApi from BGS validation method. Only use the ClaimsApi validation logic within ClaimsApi.
[API-35496](https://jira.devops.va.gov/browse/API-35496)
N/A
POA Verification
N/A
=> [API-35496] Decouple BGS POA verifier from ClaimsApi

lib/carma/client/mule_soft_auth_token_client.rb, spec/lib/carma/client/mule_soft_auth_token_client_spec.rb
- Return access_token on 200 response instead of 201 since that is what we are getting back from the token server.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/86425
10-10CG
=> [10-10CG] Update handling access_token response 

config/settings.yml, modules/vaos/spec/services/configuration_spec.rb, modules/vaos/spec/services/v1/fhir_configuration_spec.rb
This decreases va_mobile_timeout which is used when connecting to VAOS. The P95 for requests to VAOS is 16s during peak traffic. 25s should be plenty. Previously this value was risen from 15 seconds which is under our P95 so a good percentage would still timeout. Hopefully, this is a good middle ground.
=> chore: Decrease VA Mobile timeout

lib/carma/client/mule_soft_auth_token_client.rb, spec/lib/carma/client/mule_soft_auth_token_client_spec.rb
- The response from okta is a json string. This change parses that string to get the `access_token` to use for the 10-10CG Submission request.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/86425
10-10CG
=> [10-10CG] Correctly parse the access_token

modules/ivc_champva/app/models/ivc_champva/vha_10_7959a.rb
This PR adds the `fileNumber` property to the metadata of form 10-7959a. It is the same value used for the `ssn_or_tin` and `member_number` properties. This form is still in development so some or all of these properties may be combined/removed, but for the time being we need them in place for the metadata validator and the PEGA reception logic.
Not having `fileNumber` was causing the form to throw an error on metadata violation that prevented submitting.
- NA …
=> Add fileNumber property to pass metadata validation - form 10-7959a

modules/simple_forms_api/app/models/simple_forms_api/vba_20_10207.rb, modules/simple_forms_api/app/models/simple_forms_api/vba_40_0247.rb, modules/simple_forms_api/app/models/simple_forms_api/vba_40_10007.rb
We're seeing `index out of range` errors in this spot of code across these three forms. I can't reproduce it locally so this PR is adding some logging to hopefully shed more light on the situation.
=> Simple Forms - Add logging around errors in loading attachments

config/settings.yml, modules/ivc_champva/app/services/ivc_champva/email.rb, modules/ivc_champva/spec/services/email_spec.rb
Update logic to use multiple templates instead of one due to all the differences
- Add new settings for templates
- Update email.rb logic to swap out setting var based on form number
- Remove unused key/value pairs to VANotify
- Update test
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/89144
=> 89144: Update email logic to switch templates by form number

lib/map/sign_up/configuration.rb, lib/map/sign_up/service.rb, spec/lib/map/sign_up/service_spec.rb, spec/support/vcr_cassettes/map/sign_up_service_200_malformed_responses.yml
This PR updates the MAP SuS configuration class to include application/json content type header and update the service to handle parsing errors.
https://jira.devops.va.gov/browse/VI-265
* Start up a Rails console and require the MAP SuS service
```ruby
require 'map/sign_up/service'
```
* Instantiate a client
```ruby
client = MAP::SignUp::Service.new
```
* Make a call to the status endpoint
```ruby
client.status(icn: '1234')
```
* Verify the response is successful
```
2024-08-07 12:54:58.337053 I [54381:12260 service.rb:13] Rails -- [MAP][SignUp][Service] status success, icn: 1234
=> {:agreement_signed=>true, :opt_out=>false, :cerner_provisioned=>false, :bypass_eligible=>false}
```
* Modify the mock data response for the status call …
=> VI-265: Handle malformed responses in MAP SuS service

modules/ivc_champva/app/services/ivc_champva/file_uploader.rb
The file_path was getting too long with the RAils.root.join() update the file_name to match before inserting into S3 and DB
- update `file_uploader`
=> HOTFIX: Make sure file_Name is  orrect before S3/DB insertion

modules/debts_api/app/controllers/debts_api/v0/financial_status_reports_controller.rb
This adds some basic logging to track progress and potential errors with the debt server-side transform.
[Original ticket here.](https://github.com/department-of-veterans-affairs/va.gov-team/issues/89225)
=> [VA-89225] Add server-side transform logging

lib/carma/client/mule_soft_client.rb, spec/lib/carma/client/mule_soft_client_spec.rb
- Since we refactored how we build the mulesoft request, we now need to set the content-type in the request headers when we build it. Right now we are getting a 415 response. 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/86425
10-10CG
=> [10-10CG] Add content-type application/json to mulesoft submission request

app/controllers/sign_in/client_configs_controller.rb, app/controllers/sign_in/service_account_configs_controller.rb, config/routes.rb, spec/controllers/sign_in/client_configs_controller_spec.rb, spec/controllers/sign_in/service_account_configs_controller_spec.rb
- Update `client_configs` and `service_account_configs` routes to accept `client_id` and `service_account_id`. This makes more sense because we pretty much treat these as primary keys. I believe we originally used `:id` so it would work with `ActiveResource` but that is being replaced due to it becoming unmanageable and hacky to make it work with some of our business logic.
- update json errors for consistent parsing and messages
- https://jira.devops.va.gov/browse/VI-223
- https://jira.devops.va.gov/browse/VI-191
- `rails s`
- `rails c`
```ruby
SignIn::ServiceAccountConfig.find_by(service_account_id: …
```
=> [VI-223][VI-191] Sign-in Service - Update config routes params

modules/vaos/app/services/vaos/v2/appointments_reason_code_service.rb, modules/vaos/spec/services/v2/appointments_reason_code_service_spec.rb
- This is part of the api consolidation effort and moves the logic for extracting preferred modality text information from the reason code text from the FE to BE. The source logic is [here](https://github.com/department-of-veterans-affairs/vets-website/blob/d85eec388ea3b822dabb449158132ed35f9aad7a/src/applications/vaos/services/appointment/transformers.js#L28-L40)
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/89773
- The old behavior returns the information as part of the reason code text and reasonForAppointment field is non existent.
N/A
N/A
=> Generate preferred modality from appointment request reasoncode.text

modules/vye/lib/vye/batch_transfer/chunk.rb, modules/vye/lib/vye/batch_transfer/chunking.rb, modules/vye/spec/lib/vye/batch_transfer/chunk_spec.rb, modules/vye/spec/lib/vye/batch_transfer/chunking_spec.rb
- *This is a multipart commit to ingress data from BDN in chunks instead of as one large file
- *(Will break dataset from BDN in multiple parts so that it can be easily consumed by sidekiq)*
- *(I work for VYE we own the maintenance for this component.)*
- Ingress was done as one large file
- The ingress job will now launch multiple chunk jobs
=> multipart commit to ingress data from BDN in chunks instead of as one large file

config/features.yml
This PR adds two new feature flags that will be utilized in upcoming initiatives on the Health Care Application for the 1010 team. The initiatives are linked below.
- department-of-veterans-affairs/va.gov-team#81103
- department-of-veterans-affairs/va.gov-team#87452
=> Add features flags for upcoming HCA initiatives

app/sidekiq/terms_of_use/sign_up_service_updater_job.rb, spec/sidekiq/terms_of_use/sign_up_service_updater_job_spec.rb
- This PR updates the terms of use agreements/decline to Sign up Service to use MPI ICN instead of UserAccount ICN. This is necessary because sometimes the MPI ICN changes and the Sign Up Service update will fail when this happens
- https://jira.devops.va.gov/browse/VI-293
- Authenticated with a user, accepted terms with a mocked SuS failure. 
- Next, changed the user's ICN on the mocked MPI response, then change the mocked SuS failure to a success
- Confirmed the next successful SuS call used the proper updated ICN
Terms of Use
=> [VI-293] Update terms of use calls to sign up service to use ICN off MPI response

config/features.yml
This PR removes the feature toggle flag `va_online_scheduling_status_improvement_canceled`
department-of-veterans-affairs/va.gov-team#89130
n/a
n/a
VAOS feature toggle flag
=> Remove status improvement canceled toggle flag

.github/workflows/audit_service_tags.yml, .github/workflows/code_checks.yml
Because our github actions sometimes run into rate limiting from docker hub and AWS ECR, we want  to retry when this happens.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/89959
=> Add retry logic for docker commands

.reek.yml
- Allow variable names that end in numbers considering all the form related variable names
- Allow `k`,`v`,`i` variable names
- n/a
=> Update Reek Configuration

modules/vaos/app/controllers/vaos/v2/appointments_controller.rb, modules/vaos/spec/request/v2/appointments_request_spec.rb
- This change adds logging for appointment creation time so we can track how regularly pre v2 appointments are being retrieved.
- Appointments (VAOS) team
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/88580
- The new logs are covered up updating existing unit tests
N/A
@cferris32 I'm curious about whether this format of the logs is acceptable and if additional tests should be added.
=> Add VAOS logging for appointment creation time

modules/ivc_champva/app/services/ivc_champva/metadata_validator.rb, modules/ivc_champva/spec/services/metadata_validator_spec.rb
We have a few of forms that don't have a File Number so we don't want to require it
- Add guard clause to method
- Add test
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/90153
=> 90153: Don't make fileNumber a requirement

app/services/claim_fast_tracking/max_rating_annotator.rb, spec/services/claim_fast_tracking/max_rating_annotator_spec.rb
- This PR excludes certain diagnostic codes from displaying a 526 Max Rating notice, based on research specific to digestive system and infectious disease diagnostic codes.
- I'm on the Employee Experience team, which works with the 526 DBEX team that maintains this component.
- department-of-veterans-affairs/abd-vro#3230
- Old behavior: all diagnostic codes were sent to the Max Rating API to determine if the Max Rating notice should be displayed.
- New behavior: infectious disease codes and certain digestive system codes are excluded.
- The DC-specific logic has been broken out into a method that now has its own RSpec tests to cover each scenario.
* User education displayed on 526 Rated Disabilities screen; no user functionality is …
=> Tweak max rating eligibility based on primary diagnostic code

modules/vye/app/models/vye/address_change.rb, modules/vye/app/models/vye/direct_deposit_change.rb, modules/vye/lib/vye/batch_transfer/chunk.rb, modules/vye/lib/vye/batch_transfer/ingress_files/bdn_line_extraction.rb, modules/vye/spec/factories/vye/address_changes.rb, modules/vye/spec/factories/vye/direct_deposit_changes.rb, modules/vye/spec/lib/vye/batch_transfer/bdn_chunk_spec.rb, modules/vye/spec/models/vye/address_change_spec.rb, modules/vye/spec/models/vye/direct_deposit_change_spec.rb
for egressed files to BDN
- all field are never blank, empty field will have a space instead
- we are now left aligning not right aligning
- acct_types are being returned correctly
- phone numbers are being formatted correctly
for ingressed file from BDN
- monthly_rate is now returning the correct value
=> fixes for bugs found during ingress and egress to BDN

modules/check_in/config/locales/exceptions.en.yml
We see quite a few 403 'data has expired' errors from LoROTA, mostly stemming from the fact that the veteran sat on the page too long after logging in. LoROTA expires the entry after some time and returns a 403 in this case. We don't want to log this to sentry as there's no action to be taken on our end.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/89625
=> 89625 add mapping for LoROTA 403 exceptions

db/migrate/20240808215701_add_column_metadata_to_saved_claims.rb, db/schema.rb
- Generate migration to add `metadata` and `metadata_updated_at` to SavedClaim table
https://github.com/department-of-veterans-affairs/va.gov-team/issues/89790
* Migration verified locally
* This impacts the SavedClaim table in vets-api as it adds a new column (nullable string column)
=> 89790: Add metadata columns to saved_claims table

modules/claims_api/lib/bd/bd.rb, modules/claims_api/spec/lib/claims_api/bd_spec.rb
We see a null Associated Claim in VBMS when uploading a POA form via BD. Omit `claimId` from POA requests such that no Associated Claim is present in VBMS.
[API-38801](https://jira.devops.va.gov/browse/API-38801)
Power of Attorney Benefits Document upload
N/A
=> [API-38801] Omit `claimId` when nil from BD upload

modules/mobile/app/models/mobile/v0/adapters/vaos_v2_appointment.rb, modules/mobile/spec/support/fixtures/VAOS_v2_appointments.json, modules/vaos/app/services/vaos/v2/appointments_service.rb
We are relocating another piece of business logic to the appointments service. Web doesn't currently use this field, so the new schema should not affect them
https://github.com/department-of-veterans-affairs/va-mobile-app/issues/9208
Existing tests cover the change
=> Move Appointments minutes duration to service

modules/ivc_champva/spec/fixtures/form_json/vha_10_7959c.json
This PR removes the applicant date of birth test data property from a form 10-7959c mock data file. This property is no longer collected on the frontend (see [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/31333)), so we don't need it in our dummy data.
- https://github.com/department-of-veterans-affairs/vets-website/pull/31333
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/90041 …
=> 90041 Remove date of birth from 10-7959c test data - form 10-7959c

app/sidekiq/decision_review/saved_claim_hlr_status_updater_job.rb, app/sidekiq/decision_review/saved_claim_nod_status_updater_job.rb, app/sidekiq/decision_review/saved_claim_sc_status_updater_job.rb, spec/sidekiq/decision_review/saved_claim_hlr_status_updater_job_spec.rb, spec/sidekiq/decision_review/saved_claim_nod_status_updater_job_spec.rb, spec/sidekiq/decision_review/saved_claim_sc_status_updater_job_spec.rb
Updates scheduled jobs to set the `metadata` and `metadata_updated_at` values for DR `SavedClaim` records:
* `SavedClaim::HigherLevelReview`
* `SavedClaim::NoticeOfDisagreement`
* `SavedClaim::SupplementalClaim`
Adds error handling to better handle temporary issues with GET endpoints
https://github.com/department-of-veterans-affairs/va.gov-team/issues/89790
#17752
This PR impacts the `saved_claims` table and the associated sidekiq jobs run every hour
=> 89790: Populate metadata for DR SavedClaim records

modules/claims_api/app/models/claims_api/auto_established_claim.rb, spec/support/vcr_cassettes/claims_api/disability_comp.yml, spec/support/vcr_cassettes/claims_api/evss/submit.yml
- Fixed typo in AutoEstablishedClaim.to_internal method, misspelling of "disabilities".
- Fixed bugs in disability transformation methods where we weren't returning a value, resulting in nil being set for the form_data disabilities section.
[API-39152](https://jira.devops.va.gov/browse/API-39152)
- Ran rspec tests locally
- Ran local Postman tests on v1 526 endpoints to exercise AutoEstablishedClaim.to_internal logic:{{uri}}/services/claims/v1/forms/526/validate 
{{uri}}/services/claims/v1/forms/526
526 v1 validate and submit
=> Fix typos, fix bugs in disability transformation methods

config/features.yml
Remove unused feature flippers:
- show_events_v2
- injected_header_web_components
- pw_ehr_cta_drupal_source_of_truth
I did an organization-wide search for each of the flippers below and you can see that it's only used in (actual source code) in vets-api.
`show_events_v2`
`injected_header_web_components`
`pw_ehr_cta_drupal_source_of_truth`
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18335
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18864
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11876
=> VACMS-18335-18864-11876 Remove unused flippers

app/models/form526_submission.rb, app/sidekiq/lighthouse/poll_form526_pdf.rb, spec/models/form526_submission_spec.rb, spec/sidekiq/lighthouse/poll_form526_pdf_spec.rb
- checks the correct parameters to call the Poll526Pdf job from the primary submission path
- department-of-veterans-affairs/va.gov-team#90091
- make a form526submission record without `startedFormVersion` in the saved_claim form 
- call `poll_form526_pdf` on the submission record
-- the polling job should _**not be called**_
- make a form526submission record _**with**_ the `startedFormVersion` in the saved_claim form
- call `poll_form526_pdf` on the submission record
-- the polling job **_should_** be called
n/a
=> dbex/90091: beef up, refactor and test PollForm526Pdf

modules/ivc_champva/spec/models/vha_10_10d_spec.rb, modules/ivc_champva/spec/models/vha_10_7959c_spec.rb, modules/ivc_champva/spec/models/vha_10_7959f_1_spec.rb
Add more unit test to 7959C, 1010D, 7959F1 to meet 80% or above code coverage.
7959F2 does not have email tracker
https://github.com/department-of-veterans-affairs/vets-api/pull/18035/files
=> add email tracker test

modules/check_in/app/services/v2/chip/client.rb, modules/check_in/config/locales/exceptions.en.yml, modules/check_in/spec/services/v2/chip/client_spec.rb
Removes sentry logging for CHIP 404s as they are normal error scenarios when the veteran clicks on an old link.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/89776
* check in experience
=> 89776 do not log chip 404s to sentry

modules/travel_pay/app/services/travel_pay/client.rb, modules/travel_pay/spec/services/client_spec.rb
Adding extra headers if environment is production to facilitate load balancing on the Travel Pay API (external).
```mermaid
flowchart
vets-api --> prodCheck{Is Prod?}
prodCheck -->|no| lower[Lower Env Instance]
prodCheck -->|yes| eislb[EIS Load Balancer]
eislb -->|needs subscription key E| tpapi1[Travel Pay API East]
eislb -->|needs subscription key S| tpapi2[Travel Pay API South]
```
closes department-of-veterans-affairs/va.gov-team#90699
=> Btsss add support for dual sub keys

app/sidekiq/decision_review/saved_claim_hlr_status_updater_job.rb, app/sidekiq/decision_review/saved_claim_nod_status_updater_job.rb, app/sidekiq/decision_review/saved_claim_sc_status_updater_job.rb, spec/sidekiq/decision_review/saved_claim_hlr_status_updater_job_spec.rb, spec/sidekiq/decision_review/saved_claim_nod_status_updater_job_spec.rb, spec/sidekiq/decision_review/saved_claim_sc_status_updater_job_spec.rb
This fixes a bug with extracting data from the response object returned from the `DecisionReviewV1::Service` GET methods. 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/89790
#18026
Tested locally and with rspec.
This PR impacts the saved_claims table and the associated sidekiq jobs run every hour
=> 89790: Fix data extraction issue with DR status updater job

modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb, modules/simple_forms_api/spec/requests/v1/uploads_spec.rb
This reverts commit 2847f03795efc4a38c3cfb4b5517964676d09494.
This revert is necessary because I accidentally didn't take into account the distinction between two param keys, `form_number` and `form_id`, which are used depending on which action is being used. I need to think of a better way to do this.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/1573
=> Revert "Only skip authentication if we're on an unauthenticated form (#18040)"

modules/claims_api/app/services/claims_api/disability_compensation/docker_container_service.rb, modules/claims_api/spec/services/disability_compensation/docker_container_service_spec.rb
- Adds raise for errors in docker container service. 
- Adjusts test.
- [API-39187](https://jira.devops.va.gov/browse/API-39187)
- Postman
using this request_body:
```
{
"data": {
"type": "form/526",
"claimProcessType": "STANDARD_CLAIM_PROCESS",
"veteranIdentification": {
"mailingAddress": {
"addressLine1": "1234 Couch Street",
"city": "Portland",
"state": "OR",
"zipFirstFive": "12345"
},
"currentVaEmployee": false
},
"disabilities": [
{
"disabilityActionType": "INCREASE",
"name": "osteoarthritis, right knee with chondromalacia [previously rated as bilateral chondromalacia, diagnostic code 5010]",
"classificationCode": "8997",
"serviceRelevance": "",
"ratedDisabilityId": "1234567",
"diagnosticCode": 5260,
"isRelatedToToxicExposure": null, …
```
=> API-39187-526-sync-raise-e 

modules/claims_api/lib/claims_api/v2/disability_compensation_evss_mapper.rb, modules/claims_api/spec/lib/claims_api/v2/disability_compensation_evss_mapper_spec.rb
Remove bracket stripping in Disability Compensation EVSS mapper. The EVSS Docker now accepts brackets in the disability name and secondary disability name.
[API-39186](https://jira.devops.va.gov/browse/API-39186)
- Manual submission to EVSS Docker with brackets in disabilitiesʼ name and secondaryDisabilitiesʼ name with successful responses.
N/A
Disability compensation EVSS mapper.
N/A
=> [API-39186] Remove bracket stripping from disabilitiesʼ names

modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb, modules/simple_forms_api/spec/requests/v1/uploads_spec.rb
This PR is a second attempt at [this one](https://github.com/department-of-veterans-affairs/vets-api/pull/18040) (which has been reverted because it introduced bugs). Turns out I needed it to be sensitive both to `form_number` and `form_id` in the params.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/1573
=> Only skip authentication if we're on an unauthenticated form, second try

config/features.yml
This PR adds the feature toggle for IVC CHAMPVA form 10-7959a to the backend.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/90029
- https://github.com/department-of-veterans-affairs/vets-website/pull/31466
This form only
NA
=> 90029 Add feature toggle - form 10-7959a

app/sidekiq/decision_review/delete_saved_claim_records_job.rb, app/sidekiq/decision_review/saved_claim_hlr_status_updater_job.rb, app/sidekiq/decision_review/saved_claim_nod_status_updater_job.rb, app/sidekiq/decision_review/saved_claim_sc_status_updater_job.rb, spec/sidekiq/decision_review/delete_saved_claim_records_job_spec.rb, spec/sidekiq/decision_review/saved_claim_hlr_status_updater_job_spec.rb, spec/sidekiq/decision_review/saved_claim_nod_status_updater_job_spec.rb, spec/sidekiq/decision_review/saved_claim_sc_status_updater_job_spec.rb
This PR adds StatsD metrics to specific processing events for the SavedClaim Updater jobs to facilitate the creation of a DD dashboard to monitor the health of this service.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/90103
Local run + spec tests
This impacts StatsD, SavedClaim status updater, and SavedClaim deleter jobs.
=> 90103: Add statsd metrics to DR SavedClaim updater and delete jobs

modules/travel_pay/app/services/travel_pay/client.rb
Logs the `correlation-id` at a DEBUG level for end-to-end tracing.
Closes department-of-veterans-affairs/va.gov-team#90963
=> Add correlation ID to logs for debugging

modules/claims_api/lib/custom_error.rb, modules/claims_api/spec/sidekiq/claim_custom_error_spec.rb
_Warnings_, which do not block claim submission, can confuse consumers. Remove _warnings_ from the `errors` response such that only _errors_ are included.
[API-39194](https://jira.devops.va.gov/browse/API-39194)
N/A
Claims API custom error response.
N/A
=> [API-39194] Remove warnings from errors array

db/migrate/20240821145040_add_benefits_intake_uuid_to_form_submission_attempts.rb, db/schema.rb
We need to do some form resubmissions because they were `expired` by Lighthouse and I realize that we need to separately track the benefits_intake_uuid on each submission attempt. The parent `FormSubmission` record will still have the benefits intake UUID, which is kind of confusing. It would be better to have the parent `FormSubmission` have no UUID and keep it all on each Attempt record but that would mean re-jiggering the data we have already. So let's leave that until later/never.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/820
=> Add benefits_intake_uuid column to form_submission_attempts table

modules/vye/app/models/vye/verification.rb, modules/vye/spec/factories/vye/user_infos.rb, modules/vye/spec/models/vye/verification_spec.rb
Update to report because BDN requires stub_nm field to be left justified.
=> stub_nm needs to be left aligned in BDN report

config/features.yml
Adds a feature toggle for the emergency contacts experience on the 10-10EZR form
`ezr_emergency_contacts_enabled`
`ezr_next_of_kin_enabled`
- [89331](https://github.com/department-of-veterans-affairs/va.gov-team/issues/89331)
Form 10-10 EZR
=> EZR: Feature toggle for emergency contacts and next of kin experience

app/services/sign_in/attribute_validator.rb, lib/mpi/messages/add_person_implicit_search_message.rb, lib/mpi/messages/update_profile_message.rb, spec/lib/mpi/messages/add_person_implicit_search_message_spec.rb, spec/lib/mpi/messages/update_profile_message_spec.rb, spec/lib/mpi/service_spec.rb, spec/services/sign_in/attribute_validator_spec.rb
- This PR removes the check requiring SSN and first_name in a verified credential before allowing auth
- https://jira.devops.va.gov/browse/VI-384
Authentication
=> [VI-384] Removing ssn and first_name requirement from SiS verified authentications

modules/travel_pay/app/services/travel_pay/client.rb
Ruby hash merges are not in place without the `!` notation. This PR makes the merge work property to send all the headers.
Associated with department-of-veterans-affairs/va.gov-team#90699
=> fix header merge

app/models/concerns/kms_encrypted_model_patch.rb
- An `ArgumentError` is raised in development when the app reloads after a code change.
```ruby
Rails -- Exception: ArgumentError: wrong number of arguments (given 1, expected 0)
app/models/concerns/kms_encrypted_model_patch.rb:9:in `has_kms_key'
app/models/concerns/kms_encrypted_model_patch.rb:13:in `has_kms_key'
```
- Add missing arguments to overridden [has_kms_key] method.(https://github.com/ankane/kms_encrypted/blob/master/lib/kms_encrypted/model.rb#L3). 
Reproduce error:
1. Start server
2. navigate to http://localhost:3000
3. make and save a change anywhere in `/app` (add a comment)
4. DON'T restart the server
5. navigate to http://localhost:3000
6. You should get an ArgumentError 
kms_encrypted
=> Fix: Add missing args to has_kms_key override

datadog-service-catalog/datadog-service-catalog.yml, modules/accredited_representative_portal/app/controllers/accredited_representative_portal/application_controller.rb
Updates comment to add ARP to the DataDog service catalog with a link to the relevant entry.
https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/77004
See screenshot of [ARP working in datadog in `env: eks-staging`](https://vagov.ddog-gov.com/apm/services/accredited-representative-portal/operations/rack.request/resources?query=env%3Aeks-prod%20operation_name%3Arack.request%20service%3Aaccredited-representative-portal&dependencyMap=qson%3A%28data%3A%28telemetrySelection%3Aall_sources%29%2Cversion%3A%210%29&deployments=qson%3A%28data%3A%28hits%3A%28selected%3Aversion_count%29%2Cerrors%3A%28selected%3Aversion_count%29%2Clatency%3A%2195%2Ctop …
=> add ARP to DataDog service catalog

modules/mobile/app/models/mobile/v0/adapters/military_information.rb, modules/mobile/app/models/mobile/v0/military_information_history.rb
Create a model for /v0/military-service-history resource
the following endpoint does not use a model, defining the schema of the output in the serializer using Structs. These only specify the top level attributes so any nested objects do not have a defined schema. This has caused issues with schema changing out from under us.
https://github.com/department-of-veterans-affairs/va-mobile-app/issues/8155
Existing tests cover the changes
=> Create MilitaryInformationHistory model

modules/vaos/app/services/vaos/v2/appointments_service.rb, modules/vaos/spec/factories/v2/appointment_forms.rb, modules/vaos/spec/services/v2/appointment_service_spec.rb
- Currently we only extract preferred dates from the reason text for VA appointment requests which comes from the reason code text. This PR adds a fallback for non-VA requests (cc and cerner) which extracts this information from the requested periods field.
- Appointments (VAOS) team
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/90831
=> Extract request preferred dates from requested periods

modules/ivc_champva/app/controllers/ivc_champva/v1/uploads_controller.rb, modules/ivc_champva/app/form_mappings/vha_10_7959a.json.erb, modules/ivc_champva/app/models/ivc_champva/vha_10_7959a.rb, modules/ivc_champva/app/services/ivc_champva/attachments.rb, modules/ivc_champva/app/services/ivc_champva/file_uploader.rb, modules/ivc_champva/app/services/ivc_champva/s3.rb, modules/ivc_champva/spec/fixtures/form_json/vha_10_10d.json, modules/ivc_champva/spec/fixtures/form_json/vha_10_7959a.json, modules/ivc_champva/spec/requests/v1/uploads_spec.rb, modules/ivc_champva/spec/services/attachments_spec.rb, modules/ivc_champva/spec/services/file_uploader_spec.rb
As a 10-7959a applicant I want to include more than 1 claim on the form so that I don't have to keep filling out a separate form for each claim.
- Updated and cleaned up controller to move attachment_ids into @metadata
- Added global vars to 10-7959A to allow multiple PDFs to be created
- Updated other files to use @metadata over another argument to keep some areas a bit cleaner
- Updated tests
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/85683
- manuel
- rspec
Just IVC forms
=> 85683: Allow multiple claims to be created in one submission

config/features.yml
- **Added new toggles:**
- `profile_show_new_benefit_overpayment_debt_notification_setting`
- `profile_show_new_health_care_copay_bill_notification_setting`
- The `New benefit overpayment debt notification` and `New health care copay bill` items were recently added under the Payment notification group, and these new toggles were introduced to control the visibility of these items.
- `profile_show_new_benefit_overpayment_debt_notification_setting`: Controls the `New benefit overpayment debt notification` item.
- `profile_show_new_health_care_copay_bill_notification_setting`: Controls the `New health care copay bill` item.
**Timeframe for toggle**
- Depends on when MHV migrates
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/89359
Test locally
No UI changes
Profile
=> add toggles for new debt team notification items

config/features.yml
- **Added new toggles:**
- `profile_show_mhv_notification_settings_email_appointment_reminders`
- `profile_show_mhv_notification_settings_new_secure_messaging`
- `profile_show_mhv_notification_settings_email_rx_shipment`
- `profile_show_mhv_notification_settings_medical_images`
- **Removed toggles:**
- `profile_show_email_notification_settings`
- `profile_show_mhv_notification_settings`
- The old toggle `profile_show_email_notification_settings` was responsible for displaying the email notification checkbox options for:
- Appointment reminders
- Prescription shipment and tracking updates
- RX refill shipment notifications
- VA Appointment reminders
- Secure messaging alerts
- Medical images and reports available settings
- The old toggle `profile_show_mhv_notification_settings` was …
=> replace mhv notification toggles with new ones

app/sidekiq/decision_review/saved_claim_hlr_status_updater_job.rb, app/sidekiq/decision_review/saved_claim_nod_status_updater_job.rb, app/sidekiq/decision_review/saved_claim_sc_status_updater_job.rb, spec/sidekiq/decision_review/saved_claim_hlr_status_updater_job_spec.rb, spec/sidekiq/decision_review/saved_claim_nod_status_updater_job_spec.rb, spec/sidekiq/decision_review/saved_claim_sc_status_updater_job_spec.rb
This PR adds record status metrics for the SavedClaim Updater jobs for monitoring on our DD dashboard. Dashboard link: https://vagov.ddog-gov.com/dashboard/fps-2wj-ceb
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/90103
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/91327
- #18103
Local run + spec tests
This impacts StatsD and the SavedClaim status updater jobs.
=> 91327: Add record status metrics for DR SavedClaim updater jobs

config/health_care_application/wsdl/voa.wsdl, spec/lib/form1010_ezr/service_spec.rb, spec/support/vcr_cassettes/form1010_ezr/authorized_submit.yml, spec/support/vcr_cassettes/form1010_ezr/authorized_submit_async.yml, spec/support/vcr_cassettes/form1010_ezr/authorized_submit_with_attachments.yml, spec/support/vcr_cassettes/form1010_ezr/authorized_submit_with_es_dev_uri.yml, spec/support/vcr_cassettes/form1010_ezr/authorized_submit_with_mexican_province.yml, spec/support/vcr_cassettes/form1010_ezr/authorized_submit_with_next_of_kin_and_emergency_contact.yml, spec/support/vcr_cassettes/form1010_ezr/authorized_submit_with_non_pdf_attachment.yml, spec/support/vcr_cassettes/form1010_ezr/authorized_submit_with_tera.yml
- Cassettes need to be re-recorded with the updated version of savon (15.1) to confirm SOAP requests are being generated in the same way
- This will ultimately be merged into the branch in [this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/18051), which bumps `savon`, and a few other gems that must be bumped at the same time because of dependencies (`httpi`, `connect_vbms`, and `bgs_ext`).
- When [recording in a Review Instance](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/tutorials/record_vcr.md), I would receive the following error message when sending a request with the newly generated payload:
- `Couldn't create SOAP message due to exception: XML reader error: Duplicate declaration for namespace prefix 'tns'` 
- Sure …
=> Re-record Form1010_ezr cassettes

lib/logging/third_party_transaction.rb
**HIGH PRIORITY** this stops the bleeding on a PII leak
- [Ticket](https://github.com/orgs/department-of-veterans-affairs/projects/1263/views/2?filterQuery=assignee%3ASamStuckey&pane=issue&itemId=76472380)
- Logging of passed args has been leaking PII. an incident has been created, this changes stops the bleeding
=> [DBX-18193] remove passed arg logging from logging wrapper

lib/disability_compensation/factories/api_provider_factory.rb, lib/disability_compensation/providers/document_upload/evss_supplemental_document_upload_provider.rb, lib/disability_compensation/providers/document_upload/lighthouse_supplemental_document_upload_provider.rb, lib/disability_compensation/providers/document_upload/supplemental_document_upload_provider.rb, spec/lib/disability_compensation/providers/document_upload/evss_supplemental_document_upload_provider_spec.rb, spec/lib/disability_compensation/providers/document_upload/lighthouse_supplemental_document_upload_provider_spec.rb, spec/lib/disability_compensation/providers/document_upload/supplemental_document_upload_provider_spec.rb, spec/support/disability_compensation_form/shared_examples/supplemental_document_upload_provider.rb
Makes some changes to the new `Api Provider` infrastructure for Form 526 document uploads to make it easier to work with in the jobs we will be migrating from EVSS uploads to Lighthouse uploads. Also updates the Api Provider to have a feature toggle for the BDD instructions job instead of a generic feature toggle, since all of the jobs will be migrated and tested separately.
TLDR (probably not important to reviewer) decoupling the provider constructor from the document file body allows us to use the logging I built in the `sidekiq_retries_exhausted` block for these jobs, where we don't have access to the file body as we do in the job instance itself. Also tweaks the error logging since we don't have access to an error object in that block, just the error class and message
- *This work is …
=> Refactor Document Upload Api Provider for better flexibility

lib/admin/redis_health_checker.rb
- Remove a reference to `BankName` by swapping it with `Session`, another model using a `redis_key` , so that we can delete the `BankName` class
Session behaves properly:
```
irb(main):006> session = Session.find_or_build('fake token')
=> 
#<Session:0x000000015bf33d40
...
irb(main):007> session
=> 
#<Session:0x000000015bf33d40
@charon_response=nil,
@created_at=2024-08-27 17:32:53.559099 UTC,
@launch=nil,
@persisted=false,
@profile=nil,
@ssoe_transactionid=nil,
@token="fake token",
@uuid=nil>
irb(main):008> session.update(uuid: '1234')
=> true
irb(main):009> session
=> 
#<Session:0x000000015bf33d40
@charon_response=nil,
@created_at=2024-08-27 17:32:53.559099 UTC,
@errors=#<ActiveModel::Errors []>,
@launch=nil,
@persisted=true,
@profile=nil,
@ssoe_transactionid=nil,
@token="fake token", …
```
=> Change BankName model to Session

app/controllers/sign_in/client_configs_controller.rb, spec/controllers/sign_in/client_configs_controller_spec.rb, spec/controllers/sign_in/service_account_configs_controller_spec.rb
- Update ClientConfigsController permitted params to match database columns
- Add tests to `ClientConfigsController` and `ServiceAccountConfigsController` to ensure permitted params match the expected columns
- `rails s`
- `rails c`
```ruby
```
```ruby
assertion_payload = {
sub: 'vets.gov.user+0@gmail.com',
aud: 'http://localhost:3000/v0/sign_in/token',
iat: …
```
=> Sign-in Service Configs: Ensure params match expected attributes  

lib/lighthouse/facilities/facility.rb, spec/lib/lighthouse/facilities/client_spec.rb, spec/requests/v0/health_care_applications_spec.rb, spec/support/vcr_cassettes/lighthouse/facilities.yml
- Adds a `parent` attribute to the Facilities retrieved from Lighthouse.
- This matches the new v1 return value structure, since v0 didn't have the attribute
- We will use this value in the Caregiver signup process to make sure that if a Veteran's main medical facility doesn't have the Caregiver Support service, we assign the Caregiver to a facility that does.
- 10-10EZ/CG Health Enrollment team
- No Flipper is necessary since this is purely additive - we're not taking away or changing anything anyone could rely on.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/90381
- Previously the model ignored the `parent` attribute, even though Lighthouse started sending it in v1.
- Now the model extracts the `parent` …
=> 90381 add Parent attribute to facility

config/features.yml
- Removed `cst_use_claim_details_v2` feature toggle from `features.yml`
- [[CST] [ENG] Remove the feature flag cst_use_claim_details_v2 from vets-api](https://github.com/department-of-veterans-affairs/va.gov-team/issues/87712)
=> [CST] [Backend] Removed cst_use_claim_details_v2 from features.yml

app/sidekiq/decision_review/saved_claim_hlr_status_updater_job.rb, app/sidekiq/decision_review/saved_claim_nod_status_updater_job.rb, app/sidekiq/decision_review/saved_claim_sc_status_updater_job.rb, spec/sidekiq/decision_review/saved_claim_hlr_status_updater_job_spec.rb, spec/sidekiq/decision_review/saved_claim_nod_status_updater_job_spec.rb, spec/sidekiq/decision_review/saved_claim_sc_status_updater_job_spec.rb
Fixes missing tag keys for the new status metrics that were added for #18177. 
#18177
https://github.com/department-of-veterans-affairs/va.gov-team/issues/90103
https://github.com/department-of-veterans-affairs/va.gov-team/issues/91327
Local run + spec tests
This impacts StatsD and the SavedClaim status updater jobs.
=> 91327: Fix metric tag for DR SavedClaim status updater jobs

lib/periodic_jobs.rb
Comments go before a line not after. Confusingly this file had the style intermixed.
=> chore: Rearrange comments in peroidic jobs

modules/health_quest/spec/requests/health_quest/v0/apidocs_spec.rb, modules/health_quest/spec/requests/health_quest/v0/lighthouse_appointments_spec.rb, modules/health_quest/spec/requests/health_quest/v0/locations_spec.rb, modules/health_quest/spec/requests/health_quest/v0/organizations_spec.rb, modules/health_quest/spec/requests/health_quest/v0/patients_spec.rb, modules/health_quest/spec/requests/health_quest/v0/questionnaire_manager_spec.rb, modules/health_quest/spec/requests/health_quest/v0/questionnaire_responses_spec.rb, modules/health_quest/spec/requests/health_quest/v0/questionnaires_spec.rb, modules/income_limits/spec/requests/income_limits/v1/limits_by_zip_code_spec.rb, modules/income_limits/spec/requests/income_limits/v1/validate_zip_code_spec.rb
- Files were renamed to follow convention (detailed at the bottom)
- Top-level example groups were renamed to follow convention
- somes of the changes are from old rubocop disables that have no been resolved
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/91125
=> Reorganize Health Quest & Income Limits Request Specs

modules/ivc_champva/app/models/ivc_champva/vha_10_10d.rb, modules/ivc_champva/spec/models/vha_10_10d_spec.rb
Related to frontend: https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/91216
As a Pega Backend analyst, I need to determine if any applicants in the form are over 65, we can introduce a boolean flag named hasApplicantOver65. This flag will be initialized to false and updated to true if an applicant with an age greater than or equal to 65 is found.
Acceptance Criteria:
The boolean flag will be set to true if one or more applicants in the list loop are 65 years old or older.
This metadata will be added to all 10-10d submissions
=> add hasover65

.github/CODEOWNERS, app/models/saved_claim/coe_claim.rb, app/sidekiq/vbms/submit_dependents_pdf_job.rb, lib/benefits_intake_service/service.rb, lib/common/convert_to_pdf.rb, lib/common/file_helpers.rb, lib/lighthouse/benefits_intake/service.rb, lib/simple_forms_api_submission/service.rb, modules/claims_api/app/services/claims_api/disability_compensation/pdf_generation_service.rb, modules/claims_api/app/sidekiq/claims_api/v2/disability_compensation_pdf_generator.rb, modules/simple_forms_api/spec/requests/v1/scanned_form_uploads_spec.rb, modules/simple_forms_api/spec/requests/v1/uploads_spec.rb, spec/lib/lighthouse/benefits_intake/service_spec.rb, spec/lib/simple_forms_api_submission/service_spec.rb, spec/services/form1010cg/service_spec.rb
The [generate_clamav_temp_file](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/generate_clamav_temp_file) method replaces generate_temp_file when an attachment is being uploaded to vets-api. Generating a temp clamav file creates a temp file in the /clamav_tmp directory. 
This ticket ensures the generate_temp_file/generate_clamav_temp_file is being properly used throughout vets-api.
[Zenhub Ticket](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/90773)
=> ClamAV New File Location

modules/simple_forms_api/app/controllers/simple_forms_api/v1/scanned_form_uploads_controller.rb, modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb, modules/simple_forms_api/app/models/simple_forms_api/vba_20_10206.rb, modules/simple_forms_api/app/models/simple_forms_api/vba_20_10207.rb, modules/simple_forms_api/app/models/simple_forms_api/vba_21_0845.rb, modules/simple_forms_api/app/models/simple_forms_api/vba_21_0966.rb, modules/simple_forms_api/app/models/simple_forms_api/vba_21_0972.rb, modules/simple_forms_api/app/models/simple_forms_api/vba_21_10210.rb, modules/simple_forms_api/app/models/simple_forms_api/vba_21_4138.rb, modules/simple_forms_api/app/models/simple_forms_api/vba_21_4142.rb, modules/simple_forms_api/app/models/simple_forms_api/vba_21p_0847.rb, modules/simple_forms_api/app/models/simple_forms_api/vba_26_4555.rb, modules/simple_forms_api/app/models/simple_forms_api/vba_40_0247.rb, modules/simple_forms_api/app/models/simple_forms_api/vba_40_10007.rb, modules/simple_forms_api/app/services/simple_forms_api/pdf_filler.rb, modules/simple_forms_api/app/services/simple_forms_api/pdf_stamper.rb, modules/simple_forms_api/app/services/simple_forms_api/pdf_uploader.rb, modules/simple_forms_api/lib/tasks/resubmit_forms_by_uuid.rake, modules/simple_forms_api/spec/services/pdf_filler_spec.rb, modules/simple_forms_api/spec/services/pdf_stamper_spec.rb, modules/simple_forms_api/spec/services/pdf_uploader_spec.rb
This is a successor to #18145 and replaces it. The main point of this PR is in the diff for `modules/simple_forms_api/lib/tasks/resubmit_forms_by_uuid.rake`. This PR also uses the recent refactor I did to supply the task with a timestamp override.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/820
Changes to PdfFiller and PdfStamper are tested.
These screenshots are from a form I resubmitted to staging on 8/28 BUT the dates display 8/2. Pretty cool, eh? 😎
=> Add resubmission rake task

modules/mocked_authentication/spec/requests/mocked_authentication/credentials_spec.rb, modules/mocked_authentication/spec/requests/mocked_authentication/mpi/mockdata_request_spec.rb
- Files were renamed to follow convention (detailed at the bottom)
- Top-level example groups were renamed to follow convention
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/91143
=> Reorganize Mocked Authentication Request Specs 91143

config/features.yml, config/settings.yml, modules/meb_api/app/controllers/meb_api/v0/education_benefits_controller.rb, modules/meb_api/app/controllers/meb_api/v0/forms_controller.rb, modules/meb_api/app/workers/meb_api/v0/submit_1990emeb_form_confirmation.rb, modules/meb_api/config/routes.rb, modules/meb_api/spec/requests/meb_api/v0/education_benefits_spec.rb, modules/meb_api/spec/requests/meb_api/v0/forms_spec.rb
- Adds template id settings for form 1990emeb confirmation email templates
- Adds trigger for calling new sidekiq 1990emeb confirmation email job
- Adds sidekiq job for for sending 1990emeb confirmation email based on the status of the claim
- forms_spec and education_benefits_spec are updated with tests ensuring the endpoint properly delegates to the - Submit1990emebFormConfirmation  and Submit1990mebFormConfirmation sidekiq job s
- Tests cover flipper feature being enabled and disabled
- [X ] *New code is covered by unit tests* …
=> Sa 96116 toe notification email trigger

app/sidekiq/bgs/submit_form674_job.rb, app/sidekiq/bgs/submit_form686c_job.rb
- This work is behind a feature toggle (flipper): *NO*
- This fixes the issue we have been seeing in datadog where the error is wrapped in an additional "argument expected to be a string, got (ErrorObject).
- Verified that this error was occurring and is fixed when updating the sentry logging lines
This only impacts logging
=> Fix Error Message Printout in Dependents Jobs

config/features.yml
Add the `cst_include_ddl_sqd_letters` feature flag.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/91429
NA
NA
NA
=> feat: add feature flag for cst_include_ddl_sqd_letters

modules/vaos/app/controllers/vaos/v2/relationships_controller.rb, modules/vaos/app/docs/vaos/v2/vaos_v2.yaml, modules/vaos/app/services/vaos/v2/relationships_service.rb, modules/vaos/config/routes.rb, modules/vaos/spec/request/v2/relationships_request_spec.rb, modules/vaos/spec/services/v2/relationships_service_spec.rb, spec/support/vcr_cassettes/vaos/v2/relationships/get_relationships.yml, spec/support/vcr_cassettes/vaos/v2/relationships/get_relationships_500.yml
- Added a new `/relationships` endpoint to the VAOS module that will be used for future appointment booking work. This uses VPG to pull patient provider relationship information from Oracle Health and VAOS
- https://app.zenhub.com/workspaces/appointments-oracle-health-integration-65a6e99ea522640e4d09393b/issues/gh/department-of-veterans-affairs/va.gov-team/90606
This will have no impact on the site.
=> Add vaos relationships endpoint

modules/claims_api/app/swagger/claims_api/v2/dev/swagger.json, modules/claims_api/app/swagger/claims_api/v2/production/swagger.json, modules/claims_api/config/schemas/v2/526.json, modules/claims_api/spec/requests/v2/veterans/526_spec.rb
- Softens restrictions/regex pattern for toxicExposure.herbicideHazardService.otherLocationsServed, toxicExposure.additionalHazardExposures.specifyOtherExposures, 
toxicExposure.multipleExposures.exposureLocation. 
- Updates v2/dev/swagger.json & v2/production/swagger.json. 
- Updates tests.
- [API-39674](https://jira.devops.va.gov/browse/API-39674)
- Postman v2 526 sync
modified:   modules/claims_api/config/schemas/v2/526.json
modified:   modules/claims_api/spec/requests/v2/veterans/526_spec.rb
Regex suggestions
=> API-39674-update-toxic-exp-regex

modules/claims_api/app/services/claims_api/disability_compensation/docker_container_service.rb, modules/claims_api/app/services/claims_api/disability_compensation/pdf_generation_service.rb, modules/claims_api/app/sidekiq/claims_api/service_base.rb, modules/claims_api/lib/evss_service/base.rb, modules/claims_api/spec/services/disability_compensation/docker_container_service_spec.rb, modules/claims_api/spec/services/disability_compensation/pdf_generation_service_spec.rb, modules/claims_api/spec/sidekiq/service_base_spec.rb
Add `transaction_id` to:
* Docker container service logs
* PDF generation service logs
* EVSS service logs
[API-39196](https://jira.devops.va.gov/browse/API-39196)
N/A
526 synchronous endpoint, including:
* Docker container service
* PDF generation service
* EVSS service
N/A
=> [API-39196] Add `transaction_id` to 526 synchronous logs

modules/ivc_champva/app/models/ivc_champva/vha_10_10d.rb
There was a bug on the stamper for the country code stamp in 1010D. If the veteran or sponsor passes away, the stamp's multi stamp verification wasn't working properly. 
In the certifier section, the country code will now stamp only if this condition is met. 
[df1585d6-64d2-459e-a6ea-993421ee7133_vha_10_10d-tmp.pdf](https://github.com/user-attachments/files/16853322/df1585d6-64d2-459e-a6ea-993421ee7133_vha_10_10d-tmp.pdf)
[6dbef983-1f49-4382-b575-ceb9285fce0c_vha_10_10d-tmp.pdf](https://github.com/user-attachments/files/16853332/6dbef983-1f49-4382-b575-ceb9285fce0c_vha_10_10d-tmp.pdf)
=> multistamp fix

.github/workflows/code_checks.yml
Fix to resolve issue causing CI checks to fail as a result of a recent change to the github action [upload artifact dependency](https://github.com/actions/upload-artifact/commit/b18b1d32f3f31abcdc29dee3f2484801fe7822f4). 
Slack Thread - https://dsva.slack.com/archives/C30LCU8S3/p1725385665978139
=> Bug fix: Include hidden files

config/features.yml
This PR adds a new feature flag that will be utilized in an upcoming initiative on the Health Care Application for the 1010 team. The initiative is linked below.
- department-of-veterans-affairs/va.gov-team#88810
=> Add feature flag for HCA insurance section

config/features.yml
- Removing obsolete feature toggle since the feature has been fully released.
- Appointments (VAOS) team
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/89375
- Ensured existing test suites pass
=> Remove va_online_scheduling_appointment_details_redesign feature toggle

db/migrate/20240903124855_add_lighthouse_updated_at_to_form_submission_attempts.rb, db/schema.rb
This PR should help us debug form submissions a bit better. It adds a new timestamp to our form submission attempts table so we can differentiate between the nightly job we run (when `updated_at` gets set) and the timestamp reported from Lighthouse on when it most recently changed state.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/1613
=> Add lighthouse_updated_at to form_submission_attempts table

app/models/concerns/redis_caching.rb, app/services/medical_copays/vbs/service.rb, config/features.yml, lib/debt_management_center/debts_service.rb, spec/services/medical_copays/vbs/service_spec.rb
This adds caching for empty requests for the VBA copay endpoints to lighten some of their load. It also adds DataDog tracking to monitor how often it is used. This functionality is hidden behind the `debts_cache_vbs_copays_empty_response` feature flag.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/90998
New tests check that the proper functions are called when expected for the caching and that the correct DataDog metrics are tracked.
* VBS Medical Copays
=> VA-90998: Add caching and metrics to VBS copayments

modules/va_forms/app/sidekiq/va_forms/form_builder.rb
This work is NOT behind a feature toggle.
This PR updates the `VAForms::FormBuilder` nightly forms refresh job to change how it handles form URLs that return 403s (Forbidden). It expands upon the work from #18287, which updated the handling for 404s.
All form URLs served up by the VA Forms API need to be publicly available. Therefore, a form URL returning a 403 response (we have one example in Production today) should automatically be marked invalid and does not need to be retried.
A `VAForms::FormBuilder` job is kicked off nightly for each data entry in the forms source database. Therefore, if a form URL is later modified by a form administrator and changed to a publicly available form, it will have a chance to be marked valid again.
My team (Lighthouse Banana Peels) owns the `va_forms` …
=> API-37520: Add 403s to List of Non-Retryable Error Codes for `VAForms::FormBuilder`

db/migrate/20240904184430_add_ciphertext_fields_to_form_submission_attempts.rb, db/schema.rb
This PR (partially) fixes an error I made previously when creating the `form_submission_attempts` table. I didn't append `_ciphertext` to these two fields that are encrypted. Therefore, they don't currently work. I say this only partially fixes the error because I am NOT deleting the `error_message` and `response` fields (which are currently unused and unusable). I've learned that deleting fields is tricky and, strictly speaking, unnecessary right now for me.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/1613
=> Add error_message_ciphertext and response_ciphertext to form_submission_attempts table

app/sidekiq/form526_state_logging_job.rb, spec/sidekiq/form526_state_logging_job_spec.rb
- Update the state logger to also use `StatsD` gauges. this will unblock the desired state visualization. 
- For now we are leaving the logs in place as well for full context, if needed.
- [Ticket](https://github.com/orgs/department-of-veterans-affairs/projects/1263/views/2?filterQuery=assignee%3ASamStuckey&pane=issue&itemId=71313591)
- [Datadog docs](https://www.rubydoc.info/github/DataDog/dogstatsd-ruby/Datadog%2FStatsd:gauge)
- Previously this just wrote logs, but Datadog mapping of a changing payload value is better handled with Gauges
526 state logging
=> [DBX-88683] update 526 state logger with StatsD

modules/claims_api/app/controllers/claims_api/v1/forms/power_of_attorney_controller.rb, modules/claims_api/app/sidekiq/claims_api/poa_vbms_upload_job.rb
* Fixes syntax on optional param sent to job
[API-39286](https://jira.devops.va.gov/browse/API-39286)
* Submissions uploaded still reflect the desired file name. All async workflows ran as expected.
=> Fixes syntax on optional param for sidekiq job

modules/ivc_champva/app/form_mappings/vha_10_7959f_1.json.erb
This PR updates the JSON erb mapping for form 10-7959f-1 so that the concatenation of suffix to lastname works even when suffix isn't provided. Previously, we would get an type error
`no implicit conversion of nil into String`. By switching to use `join()` rather than `+`, nil values are handled gracefully.
- Fixes string concatenation for suffixes in JSON erb
- https://github.com/department-of-veterans-affairs/vets-api/pull/18298 …
=> Update suffix concatenation to handle `nil` values - form 10-7959f-1

lib/bgs/form674.rb
Some inline rubocop disables are unnecessary, so they should be refactored
`# rubocop:disable Metrics/MethodLength`
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/92082
=> Resolve MethodLength Rubocop Disables - Part BGS::Form674

modules/travel_pay/app/services/travel_pay/client.rb
- Remove the last few remaining references to the travel pay ping endpoints 
- (missed a few function defs in the process of removing the endpoints, this is code cleanup)
- *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses Jira* 
- [#91021](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91021)
- #18261 
- Tests already removed
- Travel Pay Module
=> Remove remaining references to the travel pay `ping` endpoints

modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb, modules/simple_forms_api/app/services/simple_forms_api/pdf_filler.rb, modules/simple_forms_api/app/services/simple_forms_api/pdf_uploader.rb, modules/simple_forms_api/spec/services/pdf_filler_spec.rb
This PR adds a random value to every temporarily saved file path. The hope here is to avoid the odd error in prod where a file can't be stamped because that path is not found. My hunch is that this arises from a race condition where one process deletes a file that another process was depending on. We'll see...
=> Use random value in Simple Forms PDF stamping file paths

app/services/bgs/dependency_verification_service.rb, spec/services/bgs/dependency_verification_service_spec.rb
- Changed the call to read_diaries to return a hash with empty values before making the SOAP call if participant_id is nil.
- To reproduce on staging, use user: vets.gov.user+243@gmail.com	 and navigate to https://staging.va.gov/view-change-dependents/view The issue will be confirmed in datadog. The bug was that the sentry error generated from the SOAP attempt returned true, which broke in a previous issue when iterating over diaries.
- The solution is to return a hash with nil/empty values for …
=> skip soap call if participant id is nil

config/features.yml
- Removes a no longer used `pdf_warning_banner` feature flag
- *(What is the solution, why is this the solution?)* N/A
- *(Which team do you work for, does your team own the maintenance of this component?)* Sitewide Team, yes
- [issue](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11520)
- [code removal](https://github.com/department-of-veterans-affairs/vets-website/pull/31708)
- [deprecation](https://github.com/department-of-veterans-affairs/content-build/pull/1426/files)
- [epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10956)
- No changes to behavior. Removed no longer …
=> VACMS-11520: Remove no longer used pdf_warning_banner feature flipper

modules/claims_api/app/controllers/concerns/claims_api/v2/disability_compensation_validation.rb
Add log to debug separation location codes.
[API-39968](https://jira.devops.va.gov/browse/API-39968)
1. Manually submit a separation location code to the `/v2/veterans/:id/526/validate` endpoint;
2. Observe log output:
```
2024-09-09 15:25:03.965299 I [79719:puma srv tp 002] Rails -- ClaimsApi :: separation_location_codes :: {"detail":"Retrieved separation locations","separation_locations":[{"id":24912,"description":"AF Academy"},…
```
N/A
526 disability compensation validation - separation location code
N/A
=> [API-39968] Add log to separation location code validation

app/controllers/v0/benefits_claims_controller.rb, lib/lighthouse/benefits_claims/service.rb, spec/controllers/v0/benefits_claims_controller_spec.rb, spec/support/vcr_cassettes/lighthouse/benefits_claims/submit5103/200_response.yml, spec/support/vcr_cassettes/lighthouse/benefits_claims/submit5103/404_response.yml, spec/support/vcr_cassettes/mobile/lighthouse_claims/request_decision/200_failure_response.yml, spec/support/vcr_cassettes/mobile/lighthouse_claims/request_decision/200_response.yml, spec/support/vcr_cassettes/mobile/lighthouse_claims/request_decision/404_response.yml
Lighthouse has added the ability for us to pass a tracked item ID when making a request to the claims/5103 endpoint. This PR updates the controller method and service to pass the correct JSON body when making the call to Lighthouse
- department-of-veterans-affairs/vets-website/pull/31771
- department-of-veterans-affairs/va.gov-team/issues/91457
Updated specs to account for the fact that we are passing a tracked item ID to the submit5103 method now …
=> [CST] Pass tracked item id to submit5103 method

app/controllers/concerns/form_attachment_create.rb
- Add exception-catching blocks around each of the steps of this action, logging any errors to Sentry
- It's not clear why these 403 errors are coming up, and I hope a more specific understanding of their origin will help.
- Health Enrollment 10-10EZ/CG team
Ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/92139
I ran the app locally and confirmed that the upload process works; since this is a logging change only, there's no testing to add.
- This only affects Sentry logging …
=> add Sentry logging to narrow down failure mode

app/sidekiq/hca/ezr_submission_job.rb, lib/form1010_ezr/service.rb, spec/lib/form1010_ezr/service_spec.rb, spec/sidekiq/hca/ezr_submission_job_spec.rb
- This PR adds code that allows the 10-10 team to differentiate between failures that are still retrying and exhausted failures. It also adds user initials to successful submissions in order to more easily discern when failure retries have finally succeeded.
- I work for the 10-10 health apps team
- https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/91156
- Prior to the change, all submission failures were considered exhausted failures. This code separates failures that are still retrying and exhausted failures.
10-10EZR form
(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer …
=> #91156 [10-10EZR]: Update submission failure notifications and add user initials to successful submissions

app/sidekiq/central_mail/submit_central_form686c_job.rb
As identified in this ticket, we do not need the extra invalid config:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/92135
=> Removed unused sidekiq setting

modules/claims_api/app/controllers/concerns/claims_api/v2/disability_compensation_validation.rb, modules/claims_api/spec/lib/claims_api/v2/disability_compensation_validation_spec.rb
When there is a separation location code among many service periods, we validate all service periodsʼ separation location codes, including periods which might not have a separation location code.
Add a guard to skip service periods that do not have a separation location code.
[API-39901](https://jira.devops.va.gov/browse/API-39901)
N/A
Disability compensation validation > separation location codes
N/A
=> [API-39901] Allow null separation location codes

modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb, modules/simple_forms_api/app/models/simple_forms_api/vba_20_10207.rb, modules/simple_forms_api/spec/fixtures/form_json/vba_20_10207_with_supporting_document.json, modules/simple_forms_api/spec/fixtures/form_json/vba_20_10207_with_supporting_documents.json, modules/simple_forms_api/spec/requests/simple_forms_api/v1/simple_forms_spec.rb
- This work adds logic to separate attachments when submitting form `20-10207`
- This work also adds test coverage around the new logic
- [Error: Form 20-10207 Max Document size exceeded](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/1610)
- Simple Forms API -> form 20-10207
Any
=> [SIMPLE_FORMS] feat: update attachment logic to handle form 20-10207

modules/claims_api/app/controllers/claims_api/v2/veterans/disability_compensation_controller.rb, modules/claims_api/app/controllers/claims_api/v2/veterans/power_of_attorney/base_controller.rb, modules/claims_api/app/controllers/claims_api/v2/veterans/power_of_attorney/request_controller.rb, modules/claims_api/lib/claims_api/common/exceptions/lighthouse/json_form_validation_error.rb, modules/claims_api/lib/claims_api/v2/error/lighthouse_error_handler.rb, modules/claims_api/spec/lib/claims_api/v2/error/lighthouse_error_handler_spec.rb
- Renames error class used for form validation errors to be more generic to reflect use outside of 526
[API-37310](https://jira.devops.va.gov/browse/API-37310)
- Confirmed validation error handling still works as expected for 526 and POA
Disability compensation and POA form validation error handling
=> API-37310 - Rename error class and filename, update refs in code

lib/scopes/form526_submission_state.rb, spec/models/form526_submission_spec.rb
- There is an edge case documented (link below) where a submission would be included in the original `all` scope, but then succeed before the `in_process` scope is considered. This is a side effect of our need to filter the submissions iteratively, instead of finding them in a single query as this was causing PG timeouts.
- [Ticket](https://github.com/orgs/department-of-veterans-affairs/projects/1263/views/2?filterQuery=assignee%3ASamStuckey&pane=issue&itemId=71313591)
- [Updated documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/526_scopes.md#failure_type-edge-case)
- see documentation for problem description
- This has been verified to work in a …
=> [DBX-88683] address last minute 526 success scope case

config/betamocks/services_config.yml, config/features.yml, config/settings/test.yml, modules/check_in/app/services/travel_claim/client.rb, modules/check_in/app/services/travel_claim/redis_client.rb, modules/check_in/spec/services/travel_claim/client_spec.rb, modules/check_in/spec/sidekiq/travel_claim_status_check_worker_spec.rb, modules/check_in/spec/sidekiq/travel_claim_submission_worker_spec.rb
We have been using updated v2 configs (which included new path and api keys) for more than a week now and they are confirmed working in production. This PR removes the older v1 configs to prevent future confusion.
There will be an accompanying PR in the vsp-infra-application-manifests repo.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/92006
check in experience travel claims
=> 92006 remove travel claims v1 configs

modules/accredited_representative_portal/spec/models/accredited_representatiive_portal/representative_user_spec.rb, modules/accredited_representative_portal/spec/requests/accredited_representative_portal/v0/form21a_spec.rb
Makes two small modifications to specs as requested at:
- [User `user_account_id` validation test](https://github.com/department-of-veterans-affairs/vets-api/pull/17805#discussion_r1752526643)
- [Assert IPF empty fetch response after successful 21a submit](https://github.com/department-of-veterans-affairs/vets-api/pull/17805#discussion_r1752528930)
=> Arf/86023/in progress forms.specs

modules/debts_api/lib/debts_api/v0/fsr_form_transform/enhanced_expense_calculator.rb, modules/debts_api/lib/debts_api/v0/fsr_form_transform/gmt_calculator.rb, modules/debts_api/lib/debts_api/v0/fsr_form_transform/streamlined_calculator.rb, modules/debts_api/spec/lib/debt_api/v0/fsr_form_transform/expense_calculator_spec.rb, modules/debts_api/spec/lib/debt_api/v0/fsr_form_transform/streamlined_calculator_spec.rb
This adds additional DataDog tracking for when the full backend transform is released.
* Track whether the expense property with the `financial_status_report_expenses_update` toggle on the front end is used or if it falls back to the old one.
* Track if the form is streamlined (long or short)
- [Original Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/86081)
These tests check that the additional logging is being done properly.
FSR Forms and the full backend transform.
=> [VA-86081] Add extra logging for full backend transform

config/settings.yml, modules/ivc_champva/app/services/ivc_champva/file_uploader.rb, modules/ivc_champva/app/services/ivc_champva/s3.rb, modules/ivc_champva/spec/services/s3_spec.rb
The DOCMP PEGA team removed the requirement for access key ID and access secret key. So instead, we are using Roles for Identity Access Management. This was completed using Terraform.
All IVC CHAMPVA and FMP forms
=> remove access keys for aws ivc

config/settings.yml, db/seeds/development.rb, lib/mhv/account_creation/configuration.rb, lib/mhv/account_creation/service.rb, spec/support/vcr_cassettes/mhv/account_creation/account_creation_service_200_response.yml, spec/support/vcr_cassettes/mhv/account_creation/account_creation_service_400_response.yml, spec/support/vcr_cassettes/mhv/account_creation/account_creation_service_500_response.yml
Update mhv account creation's host, route, and key.
- https://jira.devops.va.gov/browse/VI-466
- https://jira.devops.va.gov/browse/VI-465
- https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/3097
- seed database - `rails db:deed`
- add `conn.request :curl` to the faraday connection: lib/mhv/account_creation/configuration#45
```ruby
def connection
Faraday.new(base_path, headers: base_request_headers, request: request_options) do |conn|
conn.use :breakers
conn.use Faraday::Response::RaiseError
conn.adapter Faraday.default_adapter
conn.request :curl
conn.response :json
conn.response :betamocks if Settings.mhv.account_creation.mock
end
end
````
- start server and a console
- `rails s`
- `rails c`
in the console:
- load service
```ruby
require …
```
=> [VI-466] update mhv account creation's host, add request key

lib/central_mail/service.rb, lib/lighthouse/benefits_intake/service.rb
This PR adds two comments to indicate that teams that submit anything to the Lighthouse Benefits Intake API have a responsibility to monitor those submissions. It also adds a comment discouraging people from using the Central Mail Service in favor of a Lighthouse Service.
https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/1652
=> Add comments to discourage use of the Central Mail Service

modules/simple_forms_api/app/services/simple_forms_api/s3/submission_archive_builder.rb, modules/simple_forms_api/app/services/simple_forms_api/s3/utils.rb, modules/simple_forms_api/spec/services/s3/submission_archive_builder_spec.rb
- This work adds the ability to build a remediation archive based upon a form submission benefits_intake_uuid or a file path where a submitted form submission is being stored locally
- This work also adds RSpec unit test coverage for the "happy path" of this service. More test coverage to come
- [Create PoC for adding filled in PDFs to an S3 bucket](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/1633)
Any
=> [SIMPLE_FORMS] feat: add service to build a remediation archive for a given form submission

.github/CODEOWNERS, app/models/mhv_user_account.rb, spec/models/mhv_user_account_spec.rb
- Create `MHVUserAccount` model. This model will be created from the MHV create_user_account response body:
```json
{
"user_profile_id": "12352",
"champ_va": true,
"patient": true,
"sm_account": true
}
```
- Uses ActiveModel attributes and validations
- Objects will be created and validated in a `MHVUserAccountCreator` service class
- https://jira.devops.va.gov/browse/VI-467
- create various objects in the console and call `.valid?` or `.validate!` on them
- ```ruby
attributes = {
user_profile_id: '12352',
champ_va: true,
patient: true,
sm_account: true
}
account = MHVUserAccount.new(attributes)
account.validate! # true
```
- ```ruby
attributes = {
user_profile_id: nil,
champ_va: true,
patient: true,
sm_account: true
}
account = MHVUserAccount.new(attributes)
account.validate! # …
```
=> [VI-467] Create MHVUserAccount model

modules/mobile/app/controllers/mobile/v0/payment_information_controller.rb, modules/mobile/spec/requests/mobile/v0/payment_information/benefits_spec.rb
- This fixes a 500 error that has been observed in DataDog
- The problem occurs when the direct deposit response lacks control information
- We've talked to the lighthouse team and the team upstream of lighthouse. 
- The upstream team says the only reason this information would be missing is if the user isn't found. 
- The lighthouse team says this isn't possible at all, which is why I've chosen to return unprocessable entity instead of not found. 
https://github.com/department-of-veterans-affairs/va-mobile-app/issues/9140
Specs.
Only impacts the payment information show method.
=> 9140 payment info errors

lib/mpi/responses/profile_parser.rb, spec/lib/mpi/responses/profile_parser_spec.rb
- This PR updates the MPI parsing logic to properly parse the relationships field, and adds a log that states the person types associated with an MPI entry when it is retrieved
- https://jira.devops.va.gov/browse/VI-462
MPI, Authentication
=> [VI-462] Changing parsing logic for MPI relationships fields, and adding log to identify person types when this field is populated

modules/mobile/app/controllers/mobile/v0/appointments_controller.rb, modules/mobile/spec/requests/mobile/v0/appointments/vaos_v2_spec.rb
During a [Frontend bug investigation](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/4762) they discovered the source block of the appts error response is causing a long hang. this remaps the error to not use a source block
https://github.com/department-of-veterans-affairs/va-mobile-app/issues/9510
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guid …
=> remove source hash from mobile appt error

lib/periodic_jobs.rb
- Increase the frequency of our 526 state logging to every night. This provides OCTO admin with a near-real time number to lessen the reliance on Developer production access (other option is run this on an Argo terminal)
- [Ticket](https://github.com/orgs/department-of-veterans-affairs/projects/1263/views/2?filterQuery=assignee%3ASamStuckey&pane=issue&itemId=79465229)
- [Affected dashboard](https://vagov.ddog-gov.com/dashboard/ygg-v6d-nza/benefits---form-526-disability-compensation?fromUser=false&refresh_mode=sliding&from_ts=1723484820226&to_ts=1726076820226&live=true)
- nothing to test
Form 526 State logging
=> [dbx-88683] run 526 state logging nightly

modules/simple_forms_api/app/services/simple_forms_api/s3/submission_builder.rb, modules/simple_forms_api/lib/tasks/archive_download.rake, modules/simple_forms_api/spec/services/s3/submission_builder_spec.rb
- This work adds the ability to build a submission and all its required data for archiving/submission
- This work also adds RSpec unit test coverage
- [Create PoC for adding filled in PDFs to an S3 bucket](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/1633)
Any
=> [SIMPLE_FORMS] feat: build out submission builder service object

modules/claims_api/app/clients/claims_api/bgs_client/definitions.rb, modules/claims_api/lib/bgs_service/local_bgs.rb, modules/claims_api/spec/lib/claims_api/find_definition_spec.rb
- Updates VDC/ManageRepresentativeService in the definitions file, localBGS, and the spec.
- [API-40173](https://jira.devops.va.gov/browse/API-40173)
- rails c
```
@ssl_verify_mode =
if Settings.bgs.ssl_verify_mode == 'none'
OpenSSL::SSL::VERIFY_NONE
else
OpenSSL::SSL::VERIFY_PEER
end
ClaimsApi::LocalBGS.new(external_uid:'a', external_key:'b').fetch_namespace(Faraday::Connection.new(ssl: { verify_mode: @ssl_verify_mode }), 'VDC/ManageRepresentativeService')
```
- Postman: ClaimsApi::V2::Veterans::PowerOfAttorney::RequestController#request_representative
modified:   modules/claims_api/app/clients/claims_api/bgs_client/definitions.rb
modified:   modules/claims_api/lib/bgs_service/local_bgs.rb
modified:   modules/claims_api/spec/lib/claims_api/find_definition_spec.rb
=> APi-40173-vdc-manage-rep-service

modules/vaos/app/services/vaos/v2/appointments_service.rb, modules/vaos/spec/services/v2/appointment_service_spec.rb
- This PR adds some additional error handling and logging for common token errors
- Appointments (VAOS) team
- This is not controlled by a Flipper toggle
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/90026
N/A
=> Handle token related errors in appointments service

.github/CODEOWNERS, app/models/mhv_user_account.rb, app/services/mhv/user_account/creator.rb, app/services/mhv/user_account/errors.rb, lib/mhv/account_creation/service.rb, spec/lib/mhv/account_creation/service_spec.rb, spec/models/mhv_user_account_spec.rb, spec/services/mhv/user_account/creator_spec.rb
- Creates a `MHV::UserAccount::Creator` service object. This class takes in a `user_verification` and optional `cached` args. This class then calls `MHV::AccountCreator::Service.create_account` which makes an external call to MHV then a `MHVUserAccount` is created from the response. 
- `cached` will be added to the external `create_account` call in an upcoming PR
- https://jira.devops.va.gov/browse/VI-469
- in rails console test the class by passing a user_verification you have locally
- a `user_verification.user_account.terms_of_use_agreements` needs to exist
-  This is difficult to test without being on staging but the validations and object creation with a dummy response can be tested.
- in the [mhv_account_creation_response](https://github.com/department-of-veterans-affairs/vets-api/bl …
=> Add MHV::UserAccount::Creator service

app/models/preneeds/address.rb, app/models/preneeds/applicant.rb, app/models/preneeds/burial_form.rb, app/models/preneeds/claimant.rb, app/models/preneeds/currently_buried_person.rb, app/models/preneeds/date_range.rb, app/models/preneeds/full_name.rb, app/models/preneeds/preneed_attachment_hash.rb, app/models/preneeds/race.rb, app/models/preneeds/service_record.rb, app/models/preneeds/veteran.rb, app/models/preneeds/virtus_base.rb
- Rename `Preneeds::Base` to `Preneeds::VirtusBase`
- The intention is remove the `virtus` gem and this is an intermediate PR to help keep PRs small
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/92438
=> Rename Preneeds::Base to Preneeds::VirtusBase

modules/simple_forms_api/app/services/simple_forms_api/s3/submission_archiver.rb, modules/simple_forms_api/spec/services/s3/submission_archiver_spec.rb
- This work creates the submission archiver service object
- This work also adds RSpec unit test coverage
- [Create PoC for adding filled in PDFs to an S3 bucket](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/1633)
Any
=> [SIMPLE_FORMS] feat: build out submission archiver service object

.github/workflows/code_checks.yml
Specs are frequently timing out which sometimes hides the test failures that need to be fixed in order for the tests to pass and not time out. 
https://dsva.slack.com/archives/C0460N83Y9G/p1726685200107339
Ryan M is on BE support and will know if this is having the desired impact. 
The test run part of CI.
=> Don't retry specs

lib/evss/disability_compensation_form/form526_to_lighthouse_transform.rb, spec/lib/evss/disability_compensation_form/form526_to_lighthouse_transform_spec.rb
- ensures toxicExposures.multipleExposures are truly unique from one another
- department-of-veterans-affairs/va.gov-team#93079
- form526 submission requests to LH were failing if the user chose more than one of the same location per exposure event
- now they shouldn't!
n/a
Form526 primary path submission job - less 422s due to this fix :)
=> dbex/93079: uniqify multiple exposures

app/models/form_submission_attempt.rb, modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb, modules/simple_forms_api/app/services/simple_forms_api/notification_email.rb, spec/factories/form_submissions.rb
This PR fixes a couple subtle bugs I found while testing the Simple Forms error emailer: the `form_data` and `form_number` were coming in incorrect.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/1668
=> Fix data format for mailer

.github/CODEOWNERS, app/sidekiq/form526_failure_state_snapshot_job.rb, app/sidekiq/form526_submission_processing_report_job.rb, lib/periodic_jobs.rb, lib/scopes/form526_submission_state.rb, spec/sidekiq/form526_failure_state_snapshot_job_spec.rb, spec/sidekiq/form526_submission_processing_report_job_spec.rb
- break out our 526 state logging job into logical chunks
- `Form526FailureStateSnapshotJob` will run hourly, giving a clear picture of how many submissions require manual intervention
- `Form526SubmissionProcessingReportJob` provides a weekly report on how many submissions were processed, how many succeeded on what path, how many failed, etc
- [Ticket](https://github.com/orgs/department-of-veterans-affairs/projects/1263/views/2?filterQuery=assignee%3ASamStuckey&pane=issue&itemId=79953572)
- [Why we need a state snapshot](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/the-526-failure-saftey-net.md)
- Previously the `Form526StateLoggingJob` was running too frequently for our weekly …
=> Dbx 18456/break out state snapshot

config/features.yml, spec/controllers/v0/profile/direct_deposits_controller_spec.rb
This PR removes the following four toggles that were previously used to control various aspects of the direct deposit single form on the Profile page. Now that we are using the single form for the Direct Deposit page in production, these toggles are no longer needed:
1. **`profile_show_direct_deposit_single_form`:** 
- **Description:** Show/hide the single direct deposit form in profile for all users.
2. **`profile_show_direct_deposit_single_form_uat`:** 
- **Description:** Show/hide the single direct deposit form just for users during UAT only.
3. **`profile_show_direct_deposit_single_form_alert`:** 
- **Description:** Show/hide an alert with information around migrating to a single direct deposit form in profile.
4. **`profile_show_direct_deposit_single_form_edu_downtime`:**
- …
=> 92457-89743: Remove Toggles for Direct Deposit Single Form

app/services/mhv/user_account/creator.rb, lib/mhv/account_creation/service.rb, spec/lib/mhv/account_creation/service_spec.rb, spec/services/mhv/user_account/creator_spec.rb
- Add caching to MHV account creation service
- Add optional params to break cache
- Update `MHV::UserAccount::Creator` to accept and pass break_cache to `MHV::AccountCreator::Service`
- https://jira.devops.va.gov/browse/VI-473
- make sure your dev cache is on:
```bash
rails dev:cache
```
- Test `MHV::AccountCreation::Service` cache:
This is somewhat difficult since calls can only be made on staging and betamocks isn't setup yet
- find a user_verification that has an accepted tou
```ruby
user_verification = UserVerification.joins(user_account: :terms_of_use_agreements).where(terms_of_use_agreements: { response: 'accepted' }).last
```
- Call `create_account`
```ruby
require 'mhv/account_creation/service'
icn = user_verification.user_account.icn
tou_occurred_at = …
```
=> [VI-473] MHV Account Creation Caching

Gemfile.lock
- Bump google-protobuf 4.28.1 -> 4.28.2
- fixes CVE https://github.com/department-of-veterans-affairs/vets-api/security/dependabot/48
=> Bump google-protobuf 4.28.1 -> 4.28.2

modules/simple_forms_api/app/services/simple_forms_api/s3/submission_archive_builder.rb, modules/simple_forms_api/app/services/simple_forms_api/s3/submission_archiver.rb, modules/simple_forms_api/lib/tasks/archive_forms_by_uuid.rake, modules/simple_forms_api/spec/services/s3/submission_archiver_spec.rb
- This work updates the submission archive builder in accordance with VBA direction
- This work also fixes minor bugs with may cause the builder to fail
- [Create Solution for adding Form Submission Remediation Documents to an S3 bucket](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/1633)
- New code is NOT covered by unit tests YET. This is due to flaky tests bringing down the staging environment yesterday. Tests to come!
Any
=> [SIMPLE_FORMS] fix update submission archive builder logic to fix bugs

modules/claims_api/lib/claims_api/v2/error/lighthouse_error_mapper.rb
- Replace 'This job is no longer able to be re-tried' with 'Claim could not be established. Retries will fail.'
- [API-40222](https://jira.devops.va.gov/browse/API-40222)
modified:   modules/claims_api/lib/claims_api/v2/error/lighthouse_error_mapper.rb
=> Updates error message for retries

modules/claims_api/app/sidekiq/claims_api/service_base.rb, modules/claims_api/lib/bd/bd.rb, modules/claims_api/spec/lib/claims_api/bd_spec.rb, modules/claims_api/spec/sidekiq/evidence_waiver_builder_job_spec.rb
- Adds method to service_base for retry_limits_for_notification based on this [DataDog stack trace](https://vagov.ddog-gov.com/logs?query=trace_id%3A3752143384880475127%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AgAAAZIHJZD3uW_8qQAAAAAAAAAYAAAAAEFaSUhKWm5TQUFCUU1oQjAwanlBbndCRwAAACQAAAAAMDE5MjA3MjUtOWFmMC00YzFiLTk3Y2QtNTYwMmU3ZmJlMWFk&fromUser=true&messageDisplay=inline&refresh_mode=paused&storage=hot&stream_sort=desc&viz=stream&from_ts=1726695755447&to_ts=1726697756390&live=false)
- Adds corresponding test. 
- Adds logic to exclude file number in a BD upload if the doc type is 'L705'. 
- Adds corresponding  test.
- [API-40254](https://jira.devops.va.gov/browse/API-40254)
modified:   modules/claims_api/app/sidekiq/claims_api/service_base.rb
modified: …
=> API-40254-5103-bd-upload-errors

modules/claims_api/app/services/claims_api/disability_compensation/pdf_generation_service.rb
* Adds a log out at one of the spots we are seeing failures in an effort to get some insights into why the change to clamav is causing upload failures.
* Checks for existence
* Logs file size
* [API-40293](https://jira.devops.va.gov/browse/API-40293)
* [Slack Support thread](https://lighthouseva.slack.com/archives/CBU0KDSB1/p1726848103765629)
[*(Describe what parts of the site are impacted and*if*code touched other areas)*](modified:   modules/claims_api/app/services/claims_api/disability_compensation/pdf_generation_service.rb)
=> API-40293-add-logger-for-pdf-validate-investigation

modules/pensions/app/sidekiq/pensions/pension_benefit_intake_job.rb, modules/pensions/lib/pensions/monitor.rb, modules/pensions/spec/sidekiq/pensions/pension_benefit_intake_job_spec.rb
no longer raising error if issue during job cleanup
https://github.com/department-of-veterans-affairs/va.gov-team/issues/90726
- local run of job, forcing an error during cleanup
- caught and message logged but no additional error
pension
=> Pension 90726 temp file cleanup monitoring

config/features.yml, lib/carma/models/metadata.rb, lib/carma/models/submission.rb, spec/lib/carma/models/metadata_spec.rb, spec/lib/carma/models/submission_spec.rb
- *This work is behind a feature toggle (flipper): YES*: `caregiver_carma_submitted_at`
- Add `submitted_at` subattribute to submission metadata, set to the claim's `created_at`
- 10-10 Health Enrollment EZ/CG Team
- *(If introducing a flipper, what is the success criteria being targeted?)* enabling the flag sends the expected data
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/93116
- Before: send the same data but without the submitted_at metadata attribute
- After: include the attribute
- locally, I added console output to confirm …
=> send CG claim created_at to CARMA as submitted_at metadata

modules/claims_api/app/swagger/claims_api/v1/swagger.json, modules/claims_api/spec/requests/v1/rswag_claims_spec.rb
- Add 422 spec to and update v1 `/claims/{id}` swagger example.
[API-40228](https://jira.devops.va.gov/browse/API-40228)
- Documentation viewed locally
v1 claim status spec and swagger
N/A
=> [API-40228] Add 422 example to v1 claim status docs

modules/claims_api/app/controllers/claims_api/v1/forms/power_of_attorney_controller.rb, modules/claims_api/app/controllers/claims_api/v2/veterans/power_of_attorney/base_controller.rb, modules/claims_api/app/controllers/claims_api/v2/veterans/power_of_attorney/request_controller.rb, modules/claims_api/app/controllers/concerns/claims_api/v2/power_of_attorney_validation.rb, modules/claims_api/app/services/claims_api/dependent_claimant_verification_service.rb, modules/claims_api/spec/requests/v2/veterans/power_of_attorney/2122_spec.rb, modules/claims_api/spec/requests/v2/veterans/power_of_attorney/2122a_spec.rb, modules/claims_api/spec/requests/v2/veterans/power_of_attorney/power_of_attorney_request_spec.rb, modules/claims_api/spec/services/dependent_claimant_verification_service_spec.rb
Refactor the Dependent Claimant Verification Service to also allow the claimant to provide a participant ID. We prefer the participant ID (retrieved from MPI) over the first/last name matching.
But we only have the claimant’s participant ID in v2 (and even then, it can be hit or miss from MPI). So fallback to the name comparison if the claimant does not provide a participant ID. v1 should still work with the claimant‘s first and last name.
Add the dependent claimant validation to v2.
Add and update tests to reflect the above. This work is behind a feature flag.
[API-38807](https://jira.devops.va.gov/browse/API-38807)
N/A
POA v1 and v2 dependent claimant validation.
Feedback on the design of the service and integration with v1/v2 welcome!
=> [API-38807] Validate claimant is a dependent (POA V2)

chart/templates/postman-test.yaml, chart/values.yaml
- changes to parent helm chart to include a post install/upgrade postman test - confirming basic functionality of vets-api in the cluster.
- [EKS Testing: Reliability; Create a helm test after sync hook](https://app.zenhub.com/workspaces/reliability-team-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/91595)
- https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/3105
- https://github.com/department-of-veterans-affairs/vets-api/pull/18536
- These changes were testing in preview environment deployments, as well as targetting dev, sandbox, staging and production from a local container and a container running in a preview environment
deployment
(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything …
=> Postman tests post install/upgrade

.github/CODEOWNERS, app/controllers/v0/burial_claims_controller.rb, lib/burials/monitor.rb, spec/controllers/v0/burial_claims_controller_spec.rb, spec/lib/burials/monitor_spec.rb
In an effort to remove zero silent errors, we wanted to clone the Pensions::Monitor for Burials.
- Duplicate `Pensions::Monitor` into `Burials::Monitor`
- Update `burial_claims_controller` with monitor logic
- Add Rspec for new monitor
- Update burial controller tests to check for new monitors
- https://github.com/orgs/department-of-veterans-affairs/projects/1278/views/6?pane=issue&itemId=77643998
_Note: Grabbed `SavedClaim::Burial.last.to_pdf` to confirm stamping still accurate on form_
21p-530ex form submissions
=> 91824: Create Burials::Monitor and modify controller

config/initializers/flipper.rb
**This PR makes the following changes:**
- Only send log message about considering removing features if there are any features to consider removing.
- Log when a feature is added. This will hopefully help us figure out what is adding features and where outdated features.yml live.
- Add an extra log in the rescue just to see if we've been hitting errors. 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/87532
There are no unit tests for this work. I will monitor dev and staging logs in [datadog](https://vagov.ddog-gov.com/logs?query=%22consider%20removing%20features%22%20%28env%3Aeks-dev%20%7C%7C%20env%3Aeks-staging%29%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inl …
=> Add and change logging for flipper initializer

.github/CODEOWNERS, app/uploaders/veteran_facing_forms_remediation_uploader.rb, modules/simple_forms_api/app/services/simple_forms_api/s3/submission_archiver.rb, spec/uploaders/veteran_facing_forms_remediation_uploader_spec.rb
- This work updates the submission archiver to properly submit files to S3
- [Create Solution for adding Form Submission Remediation Documents to an S3 bucket](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/1633)
- New code is NOT covered by unit tests YET. This is due to flaky tests bringing down the staging environment the other day. Tests to come!
Any
=> [SIMPLE_FORMS] feat: add logic to properly upload files to S3

modules/simple_forms_api/app/services/simple_forms_api/s3/utils.rb, modules/simple_forms_api/spec/services/s3/submission_archive_builder_spec.rb
- This work updates the submission archive builder in accordance with VBA direction
- [Create Solution for adding Form Submission Remediation Documents to an S3 bucket](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/1633)
Any
=> [SIMPLE_FORMS] feat: updates to submission builder in accordance with new direction

config/settings.yml, modules/simple_forms_api/app/services/simple_forms_api/notification_email.rb
This PR adds the remaining email template id references for Veteran Facing Forms.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/1687
=> Add remaining email template id references

app/models/user.rb, spec/models/user_spec.rb
- add `mhv_user_account` to `User`. Calls `MHV::UserAccount::Creator`
- This will on populate a user has:
- `va_treatment_facility_ids`
- `icn`
- `credential_email`
- `accepted` current `terms_of_use_agreement`
- https://jira.devops.va.gov/browse/VI-468
- add `conn.request :curl` to the mhv account_creation service [connection](https://github.com/department-of-veterans-affairs/vets-api/blob/7bbbff9d456f560a2879c669b31dd707b51cb651/lib/mhv/account_creation/configuration.rb#L45-L53)
```ruby
def connection
Faraday.new(base_path, headers: base_request_headers, request: request_options) do |conn|
conn.use :breakers
conn.use Faraday::Response::RaiseError
conn.adapter Faraday.default_adapter
conn.request :curl
conn.response :json
conn.response :betamocks if Settings.mhv.account_creation.mock
end …
```
=> [VI-468] Add mhv_user_account to User

lib/lighthouse/benefits_documents/configuration.rb
- This PR fixes a class of spec around benefits documents that occurred because of a mocked access token route that was mocking dev instead of sandbox
=> Fixing flaky lighthouse benefits document spec

lib/evss/disability_compensation_form/form526_to_lighthouse_transform.rb, spec/lib/evss/disability_compensation_form/form526_to_lighthouse_transform_spec.rb
This PR adds in text indicating when a condition is caused by toxic exposure. 
- *This work is behind a feature toggle (flipper): YES/NO* Toxic Exposure itself is, this text would only be shown if that feature toggle were on
- *(Summarize the changes that have been made to the platform)* Add text to PDF text for conditions
- *(Which team do you work for, does your team own the maintenance of this component?)* DBEX Team 1
- *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses Jira* https://app.zenhub.com/workspaces/disability-benefits-experience-team-1-63dbdb0a401c4400119d3a44/issues/gh/departm …
=> [Disability Benefits] Add in "toxic exposure" to event exposure text

lib/periodic_jobs.rb, modules/ask_va_api/app/lib/ask_va_api/base_retriever.rb, modules/ask_va_api/app/lib/ask_va_api/optionset/retriever.rb, modules/ask_va_api/app/services/crm/cache_data.rb, modules/ask_va_api/app/sidekiq/crm/optionset_data_job.rb, modules/ask_va_api/app/sidekiq/crm/topics_data_job.rb, modules/ask_va_api/spec/app/lib/ask_va_api/optionset/retriever_spec.rb, modules/ask_va_api/spec/requests/ask_va_api/v0/static_data_spec.rb, modules/ask_va_api/spec/services/crm/cache_data_spec.rb, modules/ask_va_api/spec/sidekiq/crm/optionset_data_job_spec.rb, modules/ask_va_api/spec/sidekiq/crm/topics_data_job_spec.rb
1. **New `OptionsetDataJob` for Cache Hydration**:
- Implemented a background job to refresh the optionset data cache, which ensures that the `Translator` class can efficiently access up-to-date data.
- The job runs every 24 hours to keep data related to inquiry types, authentication levels, and relationships current.
2. **Enhanced `Crm::CacheData` Class**:
- Added granular error handling with the introduction of `CacheStoreError` and `ApiServiceError` for distinguishing between cache and API failures.
- Made cache TTL configurable for greater flexibility via the `initialize` method.
- Improved modularity by separating responsibilities for fetching and storing data, while refining error handling to rescue and re-raise only specific errors.
3. **`TopicDataJob` Alignment**:
- Refactored …
=> Ask va api create background job for optionset and translator class

app/models/preneeds/attachment.rb
- I accidentally left Virtus on Preneeds::Attachment
Original PR: https://github.com/department-of-veterans-affairs/vets-api/pull/18494
=> Remove virtus from Preneeds::Attachment

modules/claims_api/spec/lib/claims_api/v2/disability_compensation_evss_mapper_spec.rb
- Changes 'INCREASE' to 'NEW' in spec
- Adds `isRelatedToToxicExposure` in spec
modified:   modules/claims_api/spec/lib/claims_api/v2/disability_compensation_evss_mapper_spec.rb
=> failing-test-on-master

modules/simple_forms_api/spec/requests/simple_forms_api/v1/simple_forms_spec.rb
This PR removes specs that hinge on a feature flag which has been removed. So they're useless.
=> Remove specs that refer to deleted feature flag

modules/simple_forms_api/spec/services/notification_email_spec.rb
This PR continues [some previous work](https://github.com/department-of-veterans-affairs/vets-api/pull/18592) to refactor specs for the `NotificationEmail`.
=> Continue refactoring notification email specs

app/sidekiq/evss/disability_compensation_form/submit_form526.rb, lib/disability_compensation/providers/generate_pdf/evss_generate_pdf_provider.rb, lib/disability_compensation/providers/generate_pdf/generate_pdf_provider.rb, lib/disability_compensation/providers/generate_pdf/lighthouse_generate_pdf_provider.rb, lib/evss/disability_compensation_form/form526_to_lighthouse_transform.rb, lib/lighthouse/benefits_claims/service.rb, lib/sidekiq/form526_backup_submission_process/processor.rb, spec/lib/disability_compensation/providers/generate_pdf/generate_pdf_provider_spec.rb, spec/lib/lighthouse/benefits_claims/service_spec.rb
- add `meta.transactionId` to LH submit endpoint requests
- department-of-veterans-affairs/va.gov-team#92496
- use _**updated**_ [test harness](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/scripts/526/TREX/DEBUG/form526_submit.rb) to send submit request to LH staging environment or follow this:
1. have a `Form526Submission `on hand as `@submission` (i.e. `@submission = Form526Submission.first`)
2. `@transform_service = EVSS::DisabilityCompensationForm::Form526ToLighthouseTransform.new`
3. `@body = @transform_service.transform(@submission.form['form526'])`
4. `@service = BenefitsClaims::Service.new(@submission.user_account.icn)`
5. this is the new part
```
transaction_id = …
```
=> DBEX/92496: add transactionId to LH Submit request bodies

app/uploaders/veteran_facing_forms_remediation_uploader.rb
- This work updates the file uploader to default to vets-api default credentials
- [Form Submission Remediation - Test remediation process and make updates in accordance with findings](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/1697)
Any
=> [SIMPLE_FORMS] fix: update uploader to default to vets-api account role

modules/ask_va_api/app/controllers/ask_va_api/v0/inquiries_controller.rb, modules/ask_va_api/app/lib/ask_va_api/attachments/uploader.rb, modules/ask_va_api/app/lib/ask_va_api/inquiries/creator.rb, modules/ask_va_api/spec/app/lib/ask_va_api/attachments/uploader_spec.rb, modules/ask_va_api/spec/app/lib/ask_va_api/inquiries/creator_spec.rb, modules/ask_va_api/spec/app/lib/ask_va_api/translator_spec.rb, modules/ask_va_api/spec/requests/ask_va_api/v0/inquiries_spec.rb
- **Feature Toggle (flipper)**: NO
- This pull request introduces several key updates and refactors across the `InquiriesController` and `Inquiries::Creator` to improve maintainability, streamline the payload structure, and delegate responsibilities to relevant classes. The changes impact how inquiry data, including attachments and key conversions, are handled.
1. **InquiriesController Updates**:
- **Attachment Handling**: Removed the ability to upload attachments separately, as they are now included directly in the inquiry payload during the creation process.
- **Key Conversion**: The responsibility for converting keys from `snake_case` to `camelCase` has been moved from the controller to the `Translator` class, improving separation of concerns and enhancing code maintainability.
2. …
=> Ask va api adding profile to submit inquiry

.github/CODEOWNERS, app/controllers/v0/user/mhv_user_accounts_controller.rb, app/models/user.rb, app/serializers/mhv_user_account_serializer.rb, config/routes.rb, spec/controllers/v0/user/mhv_user_accounts_controller_spec.rb, spec/models/user_spec.rb, spec/serializers/mhv_user_account_serializer_spec.rb
- create `V0::User::MHVUserAccountsController` with show action
- route: `v0/user/mhv_user_account`
- returns `404` if the user does not have a MHVUserAccount
- returns `422` if there was an error with creating the MHVUserAccount
- if the user has an mhv_user_account it returns the serialized account
- https://jira.devops.va.gov/browse/VI-470
- betamocks ticket is being worked on so we'll need to mock the response"
in [lib/mhv_account_creation/service.rb](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/mhv/account_creation/service.rb#L14) change `response =` to
```ruby
response = { mhv_userprofileid: '12345678', isPremium: true, isChampVA: true, isPatient: true,
isSMAccountCreated: true, message: 'Existing MHV Account Found for ICN' }.as_json
```
- start …
=> [VI-470] Create MHVUserAccountsController with show action

config/betamocks/services_config.yml
- Adds MHV UserAccount creation request to Betamocks recording
- vets-api-mockdata PR: https://github.com/department-of-veterans-affairs/vets-api-mockdata/pull/540
- https://jira.devops.va.gov/browse/VI-476
- Pull the related `vets-api-mockdata` PR
- Enter a Rails console &  ensure you have a `UserVerification` connected to an account that has accepted ToU. 
- Use your UserVerification to call the MHV UserAccount Creator on localhost - you should fail MHV validation without the changed code, and succeed with it.
```ruby
user_verification = UserVerification.last
mhv_user_account = MHV::UserAccount::Creator.new(user_verification:).perform
mhv_user_account
=> Rails -- [MHV][UserAccount][Creator] client error -- { :error_message => "SSL_connect returned=1 errno=0 peeraddr=192.168.1.1:443 …
```
=> [VI-476] adds MHV UserAccount creation VCR mocking

app/sidekiq/form526_submission_processing_report_job.rb, lib/scopes/form526_submission_state.rb
- refactor our form 526 `accepted_to_primary_path` scope
- fixes a bug caused by `.or` returning extra rows
- shortens DB interaction by processing array join in memory
- remove unused method from Report logging job
- [Ticket](https://github.com/orgs/department-of-veterans-affairs/projects/1263/views/2?filterQuery=assignee%3ASamStuckey&pane=issue&itemId=81066319)
- [Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/526_scopes.md)
- new scope count is correct in production using new logic
526 form submission logging
(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have …
=> [DBX-18617] refactor accepted_to_primary 526 scope

app/models/preneeds/base.rb, app/models/preneeds/race.rb, lib/vets/attributes/value.rb, lib/vets/model.rb, spec/lib/vets/attributes/value_spec.rb, spec/lib/vets/attributes_spec.rb, spec/lib/vets/model_spec.rb
- Rename Rspec dummy classes e.g., `Apartment` -> `FakeApartment`
- Long-term solution will be implemented at a later time
- `Boolean` defined in `Vets::Model` is renamed to `Bool`
- Preneeds classes that used the `Vets::Model` predecessor Boolean was renamed too
- n/a
=> Rename Vets spec dummy classes to prevent naming conflicts

app/models/preneeds/applicant.rb, app/models/preneeds/base.rb, app/models/preneeds/burial_form.rb, app/models/preneeds/claimant.rb, app/models/preneeds/currently_buried_person.rb, app/models/preneeds/full_name.rb, app/models/preneeds/service_record.rb, app/models/preneeds/veteran.rb, lib/vets/attributes/value.rb
- `Preneeds::Base` is now a subclass of `Vets::Model`
- `as_json` was required for `Preneeds::Base` subclasses, so I kept the base class instead of removing it and making the models directly `Vets::Model` subclasses
- Some classes were requiring `Common::Base`, but not using it. So I removed the require
- n/a
=> Convert Preneeds::Base to Vets::Model

modules/simple_forms_api/app/services/simple_forms_api/notification_email.rb, modules/simple_forms_api/spec/services/notification_email_spec.rb
This PR gets the email address from the logged-in Veteran if available instead of relying on form data for the email. It will allow emails to be sent in these cases, since the form data will not contain their email address.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/1684
I've also slightly refactored the tests.
=> Fetch email from logged-in user where available on 21-10210

app/models/user.rb, app/models/user_session_form.rb, app/services/sign_in/user_loader.rb, modules/mobile/spec/support/helpers/sis_session_helper.rb, spec/controllers/sign_in/application_controller_spec.rb, spec/controllers/v0/terms_of_use_agreements_controller_spec.rb, spec/factories/users.rb, spec/services/sign_in/user_loader_spec.rb
- This PR adds a mechanism for the `User` model to store the current session handle/token so that we can tell when a new session is reloading the user. This allows us to invalidate the MPI cache when a user is logging in with a new authenticated session
- https://jira.devops.va.gov/browse/VI-506
Authentication
=> [VI-506] Invalidate MPI cache when user logs in with Sign in Service or SSOe

app/controllers/v1/notice_of_disagreements_controller.rb, app/models/appeal_submission.rb, lib/decision_review/service.rb, lib/decision_review_v1/service.rb, spec/requests/v1/notice_of_disagreements_spec.rb
Since we've released NOD v2 at 100% for a few months now, we want to clean up any logging we used to differentiate between v1 and v2 requests. Basically reverts https://github.com/department-of-veterans-affairs/vets-api/pull/15503/. 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/76676 …
=> [DR-76676] Remove version number logging from NOD requests

.github/CODEOWNERS, lib/pension_21p527ez/pension_military_information.rb, spec/lib/pension21p527ez/pension_military_information_spec.rb
- Removes nil values from the service history branches for Pension prefill. An episode with `{ branch_of_service: 'Unknown' }` in Production set the service_branches to `{ nil: true }`; this will prevent that. 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/93779
- In production terminal, pulled the service history of the user whose prefill failed and manually ran it through both the previous code and the updated code
Pensions
=> Filter invalid service_branches values

app/swagger/swagger/requests/travel_pay.rb, modules/travel_pay/app/services/travel_pay/claims_service.rb, modules/travel_pay/spec/services/claims_service_spec.rb
This is to fix a bug where the GUIDs from the upstream MS Dynamics CRM don't match the expected UUID V4 version. They use a proprietary version.
Relaxed the version to account for any UUID version and relaxed the variant to accept all non-reserved types.
Related to department-of-veterans-affairs/va.gov-team#91011
=> Relaxed parameter matching requirement

modules/claims_api/app/models/claims_api/auto_established_claim.rb, modules/claims_api/spec/models/auto_establish_claim_spec.rb
Remove homelessnessRisk=>otherLivingSituation when otherLivingSituation is nil or empty. Resolves an error with EVSS.
[API-40517](https://jira.devops.va.gov/browse/API-40517)
N/A
AutoEstablishedClaim model
~There is also [another `otherLivingSituation`](https://github.com/department-of-veterans-affairs/vets-api/blob/494076973b6c3f0973baf1d94df6cbc52ebd1fb2/modules/claims_api/app/models/claims_api/auto_established_claim.rb#L192-L195) (under `currentlyHomeless`) that attempts to send an empty space (`' '`) to pass EVSS validation. Should we also delete that key if blank?~ _Never mind, the problem was we were only padding `homelessnessRisk=>otherLivingSituation` when the situation type was `OTHER`. This [change](https://github.com/department-of-veterans-affairs/vets-api/pull/18665/commits/4f5 …
=> [API-40517] Remove `otherLivingSituation` when blank

modules/vye/app/controllers/vye/v1/verifications_controller.rb
- This spec is failing on the master branch
- `VerificationController#matching_awards?` was not matching when it should
- `actual` pending_verifications had a duplicate `id`
Reference:
```
Failures:
1) Vye::V1::VerificationsController#create sets the transact date to the highest act_end of verifications
Failure/Error: subject.create
Vye::V1::VerificationsController::AwardsMismatch:
Vye::V1::VerificationsController::AwardsMismatch
rspec ./modules/vye/spec/controllers/vye/v1/verifications_controller_spec.rb:45 
```
- n/a
=> Fix unique pending_verifications

app/sidekiq/education_form/forms/va_1995.rb, app/sidekiq/education_form/templates/1995.erb, spec/fixtures/education_benefits_claims/1995/ch30_guardian_not_graduated.json, spec/fixtures/education_benefits_claims/1995/ch30_guardian_not_graduated.spl, spec/fixtures/education_benefits_claims/1995/minimal.json, spec/fixtures/education_benefits_claims/1995/minimal.spl
- *This work is behind a feature toggle (flipper)*: No
- *(Summarize the changes that have been made to the platform)*: Show conditional benefit received/applied for 1995 spool file & remove benefit feature flag
- *(What is the solution, why is this the solution?)*: Need to show benefit received when benefitAppliedFor is blank
- *(Which team do you work for, does your team own the maintenance of this component?)*: VEBT
- *(If introducing a flipper, what is the success criteria being targeted?):* N/A
- [VEBT-580](https://jira.devops.va.gov/browse/VEBT-580)
- [Github 18597](https://github.com/department-of-veterans-affairs/vets-api/issues/18597)
- [ x] *New code is covered by unit tests* 
- *Describe what the old behavior was prior to the change* Nothing …
=> VEBT-580: Show conditional benefit received/applied for 1995 spool file & remove benefit feature flag

modules/vaos/app/services/vaos/v2/appointments_reason_code_service.rb, modules/vaos/spec/factories/v2/appointment_forms.rb, modules/vaos/spec/services/v2/appointments_reason_code_service_spec.rb
- Since we allow colons in user comments, we cannot rely on it to be a reliable key-value pair separator and need to modify our tokenization logic to account for them when extracting the comments field from the reason code text.
- Appointments (VAOS) team.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/92704
- The previous logic did not allow for colon in user comments, this change now accounts for this.
N/A
=> Support colon in user comments

app/models/user_session_form.rb, modules/claims_api/spec/requests/v1/claims_spec.rb, modules/vaos/spec/request/v2/relationships_request_spec.rb
- This PR fixes an issue that occurs when invalidating an MPI record on a User object.
- The issue is that the User object needs to be persisted in order to use the `RedisStore` function to destroy an MPI object, so the logic to invalidate the MPI cached record had to be moved to a point after the user object was persisted
- Logged in with `localhost:3000/v1/sessions/idme_verified/new`
- Logged in again with this URL, confirmed I cannot be logged in
- Did the above with the changes in this PR, confirmed I am able to log in the second time the attempt is made
Authentication
- Log in with `localhost:3000/v1/sessions/idme_verified/new`
- Log in again with this URL, confirmed you are able to log in
=> Fixing issue with invalidating an MPI record on a User object when the record is cached

app/models/form526_submission.rb, app/sidekiq/evss/disability_compensation_form/submit_form526.rb, lib/lighthouse/benefits_claims/service.rb, lib/sidekiq/form526_backup_submission_process/processor.rb
- modified what is sent to Lighthouse in the meta.transactionId field for Form526 submission
- department-of-veterans-affairs/va.gov-team#92496
- we were sending a random guid before. now we are sending the submission id for better tracking
n/a
send the form526 submission id for easier tracking in downstream systems
=> dbex/92496: modify transactionId to LH Submit request bodies

modules/simple_forms_api/app/services/simple_forms_api/s3/submission_archive_builder.rb, modules/simple_forms_api/spec/services/s3/submission_archive_builder_spec.rb
- This work updates the attachment handling logic to account for the correct data type
- [Form Submission Remediation - Test remediation process and make updates in accordance with findings](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1956)
Any
=> [SIMPLE_FORMS] fix: update attachment handling to account for path names instead of objects

modules/claims_api/app/swagger/claims_api/v2/dev/swagger.json, modules/claims_api/app/swagger/claims_api/v2/production/swagger.json, modules/claims_api/config/schemas/v2/526.json, modules/claims_api/config/schemas/v2/generate_pdf_526.json, modules/claims_api/config/schemas/v2/request_bodies/disability_compensation/example.json, modules/claims_api/config/schemas/v2/request_bodies/disability_compensation/generate_pdf_example.json, modules/claims_api/spec/fixtures/v2/veterans/disability_compensation/form_526_json_api.json, modules/claims_api/spec/lib/claims_api/v2/disability_compensation_evss_mapper_spec.rb, modules/claims_api/spec/lib/claims_api/v2/disability_compensation_pdf_mapper_spec.rb
- Changes examples of zip code to a real place.
- [API-40530](https://jira.devops.va.gov/browse/API-40530)
- Postman v2 526 using `form_526_json_api.json`
modified:   modules/claims_api/config/schemas/v2/526.json
modified:   modules/claims_api/config/schemas/v2/generate_pdf_526.json
modified:   modules/claims_api/config/schemas/v2/request_bodies/disability_compensation/example.json
modified:   modules/claims_api/config/schemas/v2/request_bodies/disability_compensation/generate_pdf_example.json
modified:   modules/claims_api/spec/fixtures/v2/veterans/disability_compensation/form_526_json_api.json
modified: …
=> API-40530-update-526-docs-valid-zip-codes

lib/mhv/account_creation/service.rb, spec/support/vcr_cassettes/mhv/account_creation/account_creation_service_200_response.yml
- MHV changed some fields in their response body:
-  `mhv_userprofileid` -> `mhv_userProfileId`
- `isChampVA` -> `isChampVABeneficiary`
- https://jira.devops.va.gov/browse/VI-530
- updated specs
- need to test on staging and update betamocks
MHV account creation
=> [VI-530] Update MHV account creation parsing

.github/CODEOWNERS, app/controllers/concerns/form_attachment_create.rb, config/features.yml, spec/concerns/form_attachment_create_spec.rb
- *This work is behind a feature toggle (flipper): YES* (`hca_log_form_attachment_create`)
- Add Sentry info logs before and after the attachment creation process, so we can check whether this actually happens in production.
- We expected the 403 errors to come from this code, but aren't seeing any logs in Sentry. This will affirmatively validate whether that's because something's wrong with the error logging/reporting/retrieval, or if we're actually not seeing errors there and need to look elsewhere.
- Health Enrollment 10-10EZ/CG team
Ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/92139
I ran the app locally and confirmed that the upload process works, and we get the corresponding logs in the console; since this is a logging change only, there's no testing …
=> add conditional logs to confirm attachment functionality

app/models/user.rb, app/models/user_session_form.rb, spec/models/user_spec.rb
- This PR invalidates the MPI cache when a user authenticates, so a fresh MPI record can be called during each authentication
Authentication
=> Invalidating MPI cache when user authenticates

lib/vets/attributes.rb, lib/vets/attributes/value.rb, lib/vets/model.rb, spec/lib/vets/attributes/value_spec.rb, spec/lib/vets/attributes_spec.rb, spec/lib/vets/model_spec.rb
- `Vets::Model` needed a way to reject unknown attributes
- `Vets::Model.attribute_set` includes ancestor's attributes
- Added `DateTime` parser to `Vets::Attributes::Value`
- These three issues were identified from a different ticket that will be linked soon
- n/a
=> Add Attribute Inheritance to Vets::Model

lib/hca/user_attributes.rb
- Remove virtus from HCA::UserAttributes
- Moved `gender` from `attr_reader` to `attr_accessor` because it is in the form
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/93531
=> Remove virtus from HCA::UserAttributes

app/services/sign_in/session_refresher.rb, spec/services/sign_in/session_refresher_spec.rb
- This PR updates the rotated access token during a sign in service session refresh so that it includes the hashed `device_secret`. This is necessary for Sign in Service SSO enabled apps to be able to spawn new sessions even if the original access token has been refreshed
- https://jira.devops.va.gov/browse/VI-534
SSO Authentication
=> [VI-534] Properly passing along hashed_device_secret in refreshed access token for sessions that are device_sso enabled

app/uploaders/veteran_facing_forms_remediation_uploader.rb
- This work increases a file size limitation on the remediation file uploader
- [Form Submission Remediation - Test remediation process and make updates in accordance with findings](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1956)
Any
=> [SIMPLE_FORMS] fix: update size range for uploader

app/models/form_submission_attempt.rb, modules/simple_forms_api/app/services/simple_forms_api/notification_email.rb, modules/simple_forms_api/spec/requests/simple_forms_api/v1/simple_forms_spec.rb, modules/simple_forms_api/spec/services/notification_email_spec.rb, spec/models/form_submission_attempt_spec.rb
This PR is another attempt to handle `UserAccount`s in the `NotificationEmail`s that Simple Forms sends. I desperately want to refactor the `NotificationEmail` class but this needs to get out sooner than later. That tech debt will have to remain until zero silent failures is handled.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/1709
=> Handle user_account in NotificationEmail

spec/lib/carma/client/mule_soft_auth_token_configuration_spec.rb, spec/lib/carma/client/mule_soft_configuration_spec.rb
- Added some new specs to get coverage of two class to 100% per simple-cov gem. 
- This is only updating specs.  No implementation code was changed. 
10-10CG spec coverage. No implementation code was changed.
=> [10-10CG] Update specs to get 100% coverage per simple-cov

lib/source_app_middleware.rb
Add `10-7959f-1-FMP` as a front end app name. Based on my [vets-website search](https://github.com/search?q=repo%3Adepartment-of-veterans-affairs%2Fvets-website%20%2210-7959f-1-FMP%22&type=code), it's a form.
This resolves the monitor, [vets-api source app monitor - un-mapped source app detected](https://vagov.ddog-gov.com/monitors/200229?from_ts=1727885589000&to_ts=1727886789000&event_id=7778315188203486323&source=monitor_notif&eval_ts=1727886789000).
=> Add `10-7959f-1-FMP` to FE app names

app/sidekiq/evss/disability_compensation_form/form0781_document_upload_failure_email.rb, app/sidekiq/evss/disability_compensation_form/form4142_document_upload_failure_email.rb, spec/sidekiq/evss/disability_compensation_form/form0781_document_upload_failure_email_spec.rb, spec/sidekiq/evss/disability_compensation_form/form4142_document_upload_failure_email_spec.rb
The Form0781DocumentUploadFailureEmail and Form4142DocumentUploadFailureEmail jobs are used to send VA Notify emails to Veterans when those respective forms fail to upload to EVSS so they can get instructions on a manual workaround.
These jobs were missing a logging statement for dispatching the email, which we want to use in DataDog to monitor the frequency and success rate of sending these emails
- *This work is behind a feature toggle (flipper): Yes and no, the Form 4142 mailer is live, the Form 0781 mailer will live soon (fixing this logging is required before launch
=> [Disability Benefits] Add missing dispatch logging to Form 526 ancillary document upload failure emails

Gemfile.lock, app/controllers/v0/health_care_applications_controller.rb, app/models/health_care_application.rb, spec/requests/v0/health_care_applications_spec.rb
- Remove 10-10EZ's constant-based check for vaMedicalFacility, since we're getting the data from the Lighthouse API now.
- 10-10 Health Enrollment EZ/CG Team
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/92316
- previously, depending on the feature flag, we would either override the schema's fixed-JSON-list validation with any-string or not
- now we unconditionally use the schema's validation, which allows any string directly
- regardless of the feature flag, confirm that we …
=> 92316 lock in and remove hca_use_facilities_API flag usages

bin/lib/vets-api/setups/native.rb
- Creates Extension if it doesn't exists 
- Validates PostGIS on postgres DB instead of vets-api (which might not be installed)
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/94234
- Deleted vets-api and re-ran bin/setup
=> Update bin/setup native for PostGIS check 

app/controllers/concerns/form_attachment_create.rb, spec/concerns/form_attachment_create_spec.rb
- *This work is behind a feature toggle (flipper): YES* (`hca_log_form_attachment_create`)
- Update the logging so we can actually see the class name
- I didn't realize that naming the extra_context entry `class_name` would cause its contents to be filtered out to `FILTERED-CLIENTSIDE`; renaming to adjust
- Health Enrollment 10-10EZ/CG team
Ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/92139
I ran the app locally and confirmed that the upload process works, and we get the corresponding logs in the console.
- This affects Sentry logging for File Upload creation
=> rename uploaded file class data to avoid filtering

app/services/sign_in/service_account_access_token_jwt_encoder.rb, spec/services/sign_in/service_account_access_token_jwt_encoder_spec.rb
- This PR adds the `nbf` (not before) field to the SiS STS access token. This is essentially the same as the `iat` field, so is just an alias to that field
- https://jira.devops.va.gov/browse/VI-538
STS Authentication
=> Adding nbf field to SiS STS access token which describes the start time the token should be considered valid

modules/simple_forms_api/app/services/simple_forms_api/notification_email.rb, modules/simple_forms_api/spec/services/notification_email_spec.rb
This PR is necessary because, while the nightly job worked fine on staging, I just ran it on prod and it threw an error about calling `first_name` on `nil`. This was happening for a 21-0966 email.
=> Simple Forms NotificationEmail bugfix on getting first_name

app/sidekiq/evss/disability_compensation_form/upload_bdd_instructions.rb, lib/disability_compensation/factories/api_provider_factory.rb, lib/disability_compensation/providers/document_upload/evss_supplemental_document_upload_provider.rb, lib/disability_compensation/providers/document_upload/lighthouse_supplemental_document_upload_provider.rb, spec/lib/disability_compensation/factories/api_provider_factory_spec.rb, spec/lib/disability_compensation/providers/document_upload/evss_supplemental_document_upload_provider_spec.rb, spec/lib/disability_compensation/providers/document_upload/lighthouse_supplemental_document_upload_provider_spec.rb, spec/support/disability_compensation_form/shared_examples/supplemental_document_upload_provider.rb
**NOTE: these changes were originally PRed in https://github.com/department-of-veterans-affairs/vets-api/pull/18695, but had to be extracted from other improvements because of exceeding the line count limit**
Overhauls the shared "API Provider" code we will use to migrate Form 526 ancillary document upload jobs from uploading to EVSS to uploading to Lighthouse instead, and adds behavior to allow us to poll for the status of documents we send to Lighthouse. The purpose of these changes is to better encapsulate logic in the providers so the upload job using them doesn't have to know too much.
Updates the constructor signatures of both the EVSSSupplementalDocumentUploadProvider and LighthouseSupplementalDocumentUploadProviders to make better use of the freely customizable `options` hash …
=> Disability benefits nb refactor document upload provider initialization 1

config/betamocks/services_config.yml
- Updates the betamocks path for MHV Account Creation to correctly point to `/mhv/account_creation/create_account/default`
- https://jira.devops.va.gov/browse/VI-476
- https://github.com/department-of-veterans-affairs/vets-api-mockdata/pull/542
=> [VI-476]  updates mhv account creation betamocks path

config/features.yml
Adding a new feature toggle for sending evidence failures emails for evidence submissions from the Claim Status Tool that fail. Also alphabetized all of the existing feature toggles with the prefix `cst_`
N/A
*(Describe what parts of the site are impacted and*if*code touched …
=> [CST] Adding new feature toggle for evidence failure emails

config/initializers/sidekiq.rb
Each time Sidekiq is initialized, [this checker](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/admin/redis_health_checker.rb#L38-L53) will be run. It logs an error if Sidekiq's Redis is NOT up. We have a Datadog monitor watching for that error: https://vagov.ddog-gov.com/monitors/284651
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/93586
I confirmed the conditional will work. This is prod:
```
irb(main):001> Settings.vsp_environment
=> "production"
```
This is dev:
```
irb(main):001> Settings.vsp_environment
=> "development"
```
Sidekiq initializer
=> Add redis sidekiq health checker to initializer

app/controllers/v0/my_va/submission_statuses_controller.rb, spec/requests/v0/my_va/submission_statuses_spec.rb
The My VA should allow LOA1 and LOA3 users to view their form submission statuses.  The existing authorization policy on the `V0::MyVA::SubmissionStatusesController` was to strict and was not allowing LOA1 users access.  The policy has been removed.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/93723
Updated request spec to use LOA1 user.
=> Remove authorization policy to allow access for LOA1 users

lib/disability_compensation/providers/document_upload/lighthouse_supplemental_document_upload_provider.rb, lib/disability_compensation/providers/document_upload/supplemental_document_upload_provider.rb, spec/lib/disability_compensation/providers/document_upload/evss_supplemental_document_upload_provider_spec.rb, spec/lib/disability_compensation/providers/document_upload/lighthouse_supplemental_document_upload_provider_spec.rb
Adds more robust logging for documenting uploads via the LighthouseSupplementalDocumentUploadProvider. This will track all of the important events during an upload and allow us to easily query and make dashboards in DataDog
- *This work is behind a feature toggle (flipper): NO but it will be, this code is unused currently
Benefits Disability
- [C] *New code is covered by unit tests*
=> Overhaul Lighthouse API Upload Provider logging

modules/travel_pay/app/services/travel_pay/appointments_client.rb
The URI::HTTPS builder was adding unnecessary things to the query path when building. The PR removes that URI::HTTPS.build step and just builds it manually.
- Travel Pay
-  [#92293](https://app.zenhub.com/workspaces/beneficiary-travel-btsss-65147e21930cd900223d8e64/issues/gh/department-of-veterans-affairs/va.gov-team/92293)
- #18548 
- ArgoCD Terminal tests showed …
=> Travel Pay/Update query path builder for appointments client

modules/simple_forms_api/app/services/simple_forms_api/notification_email.rb, modules/simple_forms_api/spec/services/notification_email_spec.rb
This PR fixes a mistake in how we get user profile info from MPI. I had previously thought it looked like this:
```ruby
MPI::Service.new.find_profile_by_identifier returns mpi_profile
mpi_profile = { first_name: 'Joe' }
```
but it is actually like this
```ruby
MPI::Service.new.find_profile_by_identifier returns mpi_response
mpi_response = { profile: { given_names: ['Joe'] } }
```
This PR adds even more defensive programming in case things go wrong so we can run the whole nightly job, even if some things are missing (logging them instead of throwing an exception).
=> Fix how we query MPI Profile for first name

app/models/form_submission_attempt.rb
This PR adds some logging for when a Simple Forms submission fails in Central Mail and we send an email to the user to let them know.
=> Add logging when we're about to send a failure email

app/models/form_submission.rb, spec/models/form_submission_spec.rb
This PR handles when `form_data` is `nil` in a `FormSubmission`. If we allow it to remain `nil`, then it will break in our nightly job when we try to run `JSON.parse(form_data)`. If we can default it to `'{}'` then it won't error out when trying to JSON parse.
=> Handle nil form_data with a sensible default, needed for JSON parsing

modules/claims_api/app/swagger/claims_api/v2/dev/swagger.json, modules/claims_api/app/swagger/claims_api/v2/production/swagger.json, modules/claims_api/spec/requests/v2/veterans/rswag_claims_spec.rb
* Adds an example to the docs for a claim that was accepted but then errored in a background job
* This is for the claims show endpoint n V2.
[API-40626](https://jira.devops.va.gov/browse/API-40626)
- View the docs
* Dropdown
* Errored Claim example
modified:   modules/claims_api/spec/requests/v2/veterans/rswag_claims_spec.rb
We can call these labels whatever we want so let me know if we feel there is a better label to go with.
=> API-40626-errored-claims-show-example

app/models/form_submission_attempt.rb
This PR updates the timezone for sending daily emails about received and errored submissions for Simple Forms forms from UTC to US Eastern.
=> Set timezone to US Eastern for Simple Forms email sends

modules/claims_api/app/controllers/claims_api/v2/veterans/disability_compensation_controller.rb, modules/claims_api/app/services/claims_api/disability_compensation/pdf_generation_service.rb, modules/claims_api/spec/services/disability_compensation/pdf_generation_service_spec.rb
- In v2 526 synchronous submission, if the pdf string is empty, raise an exception and stop processing the claim.
- [API-40614](https://jira.devops.va.gov/browse/API-40614)
N/A
disability compensation v2 controller and pdf generation service
N/A
=> [API-40614] halt v2 526 synchronous submission if pdf empty

modules/check_in/app/services/travel_claim/client.rb, modules/check_in/spec/services/travel_claim/client_spec.rb
We need to use a different BTSSS API client_number when filing travel claims for OH sites, as compared to VistA sites. This PR adds an initialization parameter to the client class, which the service class can use to initialize the client with a different client_number.
This is a backward compatible change and doesn't require a feature flag.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/93074
* check_in experience and Oracle Health travel claims
=> 93074 Update travel claims client to take in client_number as initialization parameter

lib/evss/disability_compensation_form/form526_to_lighthouse_transform.rb, spec/lib/evss/disability_compensation_form/form526_to_lighthouse_transform_spec.rb
- on the frontend, if the user selects a toxic exposure item, moves forward, fills out a date, moves backward, then deselects the toxic exposure item, the date data is left in the in progress form and is later transmitted to vets-api
- this filters the transmittal of the unselected date data in the request body to lighthouse
- department-of-veterans-affairs/va.gov-team#94369
- different client to vets-api objects can be used to test this out.
- the screenshot below shows this snippet of an object tested using the lighthouse pdf generation endpoint:
```
"otherExposures": {
"asbestos": false,
"chemical": false,
"mos": true,
"mustardgas": true,
"radiation": true,
"water": true
},
"otherExposuresDetails": {
"asbestos": {
"startDate": …
```
=> dbex/94369: Remove dates from LH submit request for unselected location/hazard options

app/models/form_submission_attempt.rb, spec/models/form_submission_attempt_spec.rb
This PR handles `nil` form_data in a non-destructive way ([see the revert](https://github.com/department-of-veterans-affairs/vets-api/pull/18773)).
=> Handle nil in form_data properly for Form Submission Attempts

modules/mobile/spec/requests/mobile/v0/appointments/facilities/clinics_spec.rb, modules/vaos/app/services/vaos/v2/systems_service.rb, modules/vaos/spec/requests/vaos/v2/locations/clinics_spec.rb, modules/vaos/spec/services/v2/systems_service_spec.rb, spec/support/vcr_cassettes/mobile/appointments/get_facility_clinics_200_vpg.yml, spec/support/vcr_cassettes/mobile/appointments/get_facility_clinics_bad_facility_id_200_vpg.yml, spec/support/vcr_cassettes/mobile/appointments/get_facility_clinics_bad_service_400_vpg.yml, spec/support/vcr_cassettes/vaos/v2/systems/get_facility_clinics_200_vpg.yml, spec/support/vcr_cassettes/vaos/v2/systems/get_facility_clinics_400_vpg.yml
- Update the `locations/{locationId/clinics` endpoint to route requests to the `vetsapi-patient-gateway` service if the va_online_scheduling_use_vpg feature flag is enabled.
https://app.zenhub.com/workspaces/appointments-oracle-health-integration-65a6e99ea522640e4d09393b/issues/gh/department-of-veterans-affairs/va.gov-team/93475
Clinic searches in the VAOS module will optionally be routed to the `vetsapi-patient-gateway` service, enabling Oracle Health support.
=> Add optional VPG routing to clinic requests

modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb, modules/simple_forms_api/spec/requests/simple_forms_api/v1/simple_forms_spec.rb
This PR checks for `confirmation_code` before sending off a Notification Email for 21-0966 ITF. This can occur if the user already has all requested ITFs on file so no confirmation code is newly created.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/1727
=> Check for confirmation_number before sending a NotificationEmail in ITF 21-0966

lib/evss/disability_compensation_form/form526_to_lighthouse_transform.rb, spec/lib/evss/disability_compensation_form/form526_to_lighthouse_transform_spec.rb
- removes dates from the "other" objects if the user deselected them in the front end
- department-of-veterans-affairs/va.gov-team#94369
- additional hazard dates were being sent to the 526 pdf generation step even if the user removed their free-form text on the front end
1. a user:
2. types in text into the "other" free-form text fields
3. enters in dates for that item
4. clicks BACK
-- but leaves the dates in-tact
5. then they completely delete their "other" free-form text answers
sample data objects in the unit tests
=> dbex/94369: Remove dates from LH submit request for unselected location/hazard options - "other" objects

config/features.yml
- Adds a new feature flag, `va_online_scheduling_vaos_alternate_route`
- https://app.zenhub.com/workspaces/appointments-oracle-health-integration-65a6e99ea522640e4d09393b/issues/gh/department-of-veterans-affairs/va.gov-team/93478
=> Add va_online_scheduling_vaos_alternate_route feature flag

modules/vba_documents/spec/sidekiq/upload_remover_spec.rb
Due to a slow query, we are going to modify the s3_deleted bool column in our vba_documents_upload_submision table to not allow nils.  Before we run the migration, we need to fix a unit test that was attempting to set it to nil.
Team banana peels table, I'm on banana peels
[API-39107](https://jira.devops.va.gov/browse/API-39107)
Benefits Intake unit test
=> s3_deleted will no longer be nilable, fix unit test

modules/simple_forms_api/app/services/simple_forms_api/form_remediation/submission_remediation_data.rb, modules/simple_forms_api/spec/services/form_remediation/submission_remediation_data_spec.rb
=> [SIMPLE_FORMS] feat: form remediation solution streamlining, test coverage, and documentation - PART 2

db/migrate/20241007180915_add_remediation_type_to_form526_submission_remediations.rb, db/schema.rb
- migration to add `remediation_type` value to to `Form526SubmissionRemediation` table
- follow ups
- refactor the model to have an enum that leverages this value providing types
- `manual`
- `ignored_as_duplicate`
- `email_notification`
- migrate  application logic
- update existing `ignored_as_duplicate: true` values to new paradigm
- update Form526Submission state scopes to use new paradigm
- remove `ignored_as_duplicate` value
This will unblock iterations on our 526 Silent Failure work. We will use this new paradigm to automatically 'remediate' submissions when we notify a veteran via email of a failure
- [Ticket for work](https://github.com/orgs/department-of-veterans-affairs/projects/1263/views/2?filterQuery=assignee%3ASamStuckey …
=> [DBX-94128] update 526 remediation model for email era

modules/claims_api/spec/factories/claims_api_base_factory.rb, modules/claims_api/spec/factories/evidence_waiver_submissions.rb, modules/claims_api/spec/factories/power_of_attorney.rb, modules/claims_api/spec/lib/claims_api/bd_spec.rb, modules/claims_api/spec/requests/v1/forms/2122_spec.rb, modules/claims_api/spec/requests/v1/forms/rswag_2122_spec.rb, modules/claims_api/spec/requests/v2/veterans/power_of_attorney/power_of_attorney_spec.rb, modules/claims_api/spec/shared_reporting_helper.rb, modules/claims_api/spec/sidekiq/poa_vbms_upload_job_spec.rb, modules/claims_api/spec/sidekiq/report_monthly_submissions_spec.rb, modules/claims_api/spec/sidekiq/shared_reporting_examples_spec.rb
- Adds base factory, from which other model factories can inherit. 
- Refactors EWS and POA factories. 
- Adjusts tests based on factory changes.
- [API-40905](https://jira.devops.va.gov/browse/API-40905)
new file:   modules/claims_api/spec/factories/claims_api_base_factory.rb
modified:   modules/claims_api/spec/factories/evidence_waiver_submissions.rb
modified:   modules/claims_api/spec/factories/power_of_attorney.rb
modified:   modules/claims_api/spec/lib/claims_api/bd_spec.rb
modified:   modules/claims_api/spec/requests/v1/forms/2122_spec.rb
modified:   modules/claims_api/spec/requests/v1/forms/rswag_2122_spec.rb
modified:   modules/claims_api/spec/requests/v2/veterans/power_of_attorney/power_of_attorney_spec.rb
modified:   modules/claims_api/spec/shared_reporting_helper.rb
modified: …
=> API-40905-main-factory

app/sidekiq/form1010cg/submission_job.rb, spec/sidekiq/form1010cg/submission_job_spec.rb
- After some testing in staging, we found the `failed_ten_retries` metric was not being incremented in the submission job. This was due to the logic in the `RetryMonitoring` middleware that adds a 1 to the `retry_count` when validating the `retry_limits_for_notification` value which determines if it should call the `notify` method. Since we had it set to 10 for the metric, it was passing a params value with a `retry_count` of 9 to the notify, which was then not incrementing due to the check for a 10 and not a 9. 
- `caregiver1010` flipper toggle
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/93615
10-10CG
=> [10-10CG] Update retry_count increment for SubmissionJob

.github/CODEOWNERS, app/uploaders/simple_forms_api/form_remediation/uploader.rb, modules/simple_forms_api/app/services/simple_forms_api/form_remediation/submission_archive.rb, modules/simple_forms_api/spec/services/form_remediation/submission_archive_spec.rb, spec/uploaders/simple_forms_api/form_remediation/uploader_spec.rb
=> [SIMPLE_FORMS] feat: form remediation solution streamlining, test coverage, and documentation - PART 3

modules/vba_documents/app/serializers/vba_documents/upload_serializer.rb, modules/vba_documents/app/serializers/vba_documents/v1/upload_serializer.rb, modules/vba_documents/app/serializers/vba_documents/v2/upload_serializer.rb, modules/vba_documents/spec/serializers/shared_examples_upload_serializer.rb, modules/vba_documents/spec/serializers/upload_serializer_spec.rb, modules/vba_documents/spec/serializers/v1/upload_serializer_spec.rb, modules/vba_documents/spec/serializers/v2/upload_serializer_spec.rb
This work is not behind a feature toggle.
The introduction of #17348, which replaced the JSON serializers, changed a few parts of the Benefits Intake API responses. The first was that `"type": "document_upload"` was changed to `"type": "upload"`. The second was that the order of the fields in the responses changed. We suspect that one or both of these changes may have impacted one of our API consumers, who recently reported an issue with their integration that fetches submission status updates. Setting the responses back to what they were before also allows the example responses in [our API documentation](https://developer.va.gov/explore/api/benefits-intake/docs?version=current) to match the actual responses again.
My team (Lighthouse Banana Peels) owns the `vba_documents` module. …
=> API-40976: Fix Benefits Intake API Responses Modified by JSON Serializer Changes

modules/simple_forms_api/app/services/simple_forms_api/form_remediation/file_utilities.rb, modules/simple_forms_api/app/services/simple_forms_api/form_remediation/s3_client.rb, modules/simple_forms_api/spec/services/form_remediation/s3_client_spec.rb
=> [SIMPLE_FORMS] feat: form remediation solution streamlining, test coverage, and documentation - PART 4

.github/CODEOWNERS, modules/simple_forms_api/app/services/simple_forms_api/form_remediation/jobs/archive_batch_processing_job.rb, modules/simple_forms_api/lib/tasks/archive_forms_by_uuid.rake, modules/simple_forms_api/spec/services/form_remediation/jobs/archive_batch_processing_job_spec.rb, spec/factories/persistent_attachments.rb
=> [SIMPLE_FORMS] feat: form remediation solution streamlining, test coverage, and documentation - PART 5

.github/CODEOWNERS
- the `pensions` GH team was renamed to `pension-and-burials` 
- this change needed to be reflected in the CODEOWNERS file as well
- n/a
=> Rename pensions team to pension-and-burials in CODEOWNERS

modules/check_in/app/services/travel_claim/service.rb
This PR updates the Travel Claims service class to get the client number based on the passed-in facility type. This change allows us to use a different client number for Oracle Health facilities.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/93075
check-in experience Travel Claims
=> update service class to use a different client number

app/sidekiq/evss/disability_compensation_form/upload_bdd_instructions.rb, config/features.yml, lib/disability_compensation/factories/api_provider_factory.rb, spec/sidekiq/evss/disability_compensation_form/upload_bdd_instructions_spec.rb
Updates the `UploadBddInstructions` job to use the new ApiProviders for document uploads.
This will allow us to progressively transition BDD Instruction uploads to the new Lighthouse Documents Benefits API by turning on a flipper for more and more users.
Hides all new behavior behind a killswitch flipper,`disability_compensation_use_api_provider_for_bdd_instructions`, which will only use the API providers if turned on.
If that's enabled, the API Provider Factory itself will decide if we use the Lighthouse or EVSS provider client for the uploads, based on the status of the `disability_compensation_upload_bdd_instructions_to_lighthouse` flipper for the user who the submission belongs to
- *This work is behind a feature toggle (flipper): YES see above
- *(Which team do you work for, does …
=> [Lighthouse Document Upload Migration] Migrate Upload BDD Instructions job

.github/CODEOWNERS
Removes long-covid team as they don't need to be codeowners on this file.
* https://github.com/department-of-veterans-affairs/va.gov-team/issues/83785
* https://github.com/department-of-veterans-affairs/vets-api/pull/18780
=> Removes long-covid team from covid_vaccine_facilities.rb

app/sidekiq/benefits_intake_status_job.rb
This PR increments a statsd metric to count whenever a form submission fails silently, after we've submitted it to Lighthouse. We still need to add another similar incrementing call when we avoid a silent failure by emailing the Veteran.
=> Increment silent_failure statsd count when LH submission fails

lib/decision_review_v1/appeals/supplemental_claim_services.rb, spec/requests/v1/supplemental_claims_spec.rb, spec/sidekiq/decision_review/form4142_submit_spec.rb
Removing a previous Flipper toggle that determined whether 4142 forms submitted with a Supplemental Claim were sent directly to Central Mail (old behavior) or through Lighthouse (new behavior). The new behavior has been in place for months, time to clear out the Flipper.
- [Github issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/94720)
- [X ] *New code is covered by unit tests*
- *Deleted tests for old code path*
- *Updated all existing tests to follow new code path and use correct VCR cassettes*
Only touches the 4142 submission process when that form is included as part of a Supplemental Claim submission
- [X ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured …
=> Decision Reviews| Remove 4142 flipper

modules/representation_management/app/controllers/representation_management/v0/pdf_generator_base_controller.rb, modules/representation_management/app/models/representation_management/form_2122_base.rb, modules/representation_management/spec/models/representation_management/form_2122_base_spec.rb, modules/representation_management/spec/models/representation_management/form_2122a_data_spec.rb, modules/representation_management/spec/requests/representation_management/v0/pdf_generator_2122_spec.rb
- This PR fixes some validation errors that were triggered when submitting the frontend request to generate a PDF of form 2122.  Specifically it converts three character country codes to 2 character codes to pass validation and fixes a zip code suffix validation that wasn't consistently implemented across multiple zip code suffixes.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/94683
- *Describe the steps required to verify your changes are working as expected. Exclusively stating 'Specs run' is NOT acceptable as appropriate testing:* Use the front end in staging to generate a request body and run that against this code to ensure that validation …
=> Fix 2122(a) PDF generation validation errors #94683

modules/mobile/app/controllers/mobile/v0/translations_controller.rb, modules/mobile/docs/openapi.yaml, modules/mobile/spec/requests/mobile/v0/translations_spec.rb
Fixes an issue found when testing the translations download. The previous approach of using the git timestamp doesn't work in deployed environments because the app is mounted within docker. This changes to using the file MD5, which I've already confirmed is accessible in staging. 
https://github.com/department-of-veterans-affairs/va-mobile-app/issues/9622
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesgui …
=> 9622: use translations file md5 instead of timestamp

modules/representation_management/spec/requests/representation_management/v0/pdf_generator_2122_swagger_spec.rb
- *(Summarize the changes that have been made to the platform):* I fixed a bug in a test that was silently failing before but an additional PR made it fail loudly.
- *(If bug, how to reproduce):* Just run the test suite.
- *(What is the solution, why is this the solution?):* The bug was supplying an empty hash when there was supposed to be data.  Previoulsy it didn't crash because the underlying code tested made liberal use of `dig`, which fails gracefully.  Now most of those `dig` calls have been replaced by direct hash access `hash[:key]` style.
- *(Which team do you work for, does your team own the maintenance of this component?):* FAR/ARM
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/94905
- *Describe …
=> Fix swagger docs test for 2122 PDF generation

app/uploaders/simple_forms_api/form_remediation/uploader.rb, lib/simple_forms_api/form_remediation/configuration/base.rb, modules/simple_forms_api/app/services/simple_forms_api/form_remediation/file_utilities.rb, modules/simple_forms_api/app/services/simple_forms_api/form_remediation/jobs/archive_batch_processing_job.rb, modules/simple_forms_api/app/services/simple_forms_api/form_remediation/s3_client.rb, modules/simple_forms_api/app/services/simple_forms_api/form_remediation/submission_archive.rb, modules/simple_forms_api/app/services/simple_forms_api/form_remediation/submission_remediation_data.rb, modules/simple_forms_api/spec/services/form_remediation/file_utilities_spec.rb, modules/simple_forms_api/spec/services/form_remediation/jobs/archive_batch_processing_job_spec.rb, modules/simple_forms_api/spec/services/form_remediation/s3_client_spec.rb, modules/simple_forms_api/spec/services/form_remediation/submission_archive_spec.rb, modules/simple_forms_api/spec/services/form_remediation/submission_remediation_data_spec.rb
=> [SIMPLE_FORMS] feat: form remediation solution streamlining, test coverage, and documentation - PART 8

modules/claims_api/app/services/claims_api/slack/failed_submissions_messenger.rb, modules/claims_api/spec/services/failed_submissions_messenger_spec.rb
* Fixes time range in link
[API-41095](https://jira.devops.va.gov/browse/API-41095)
* If you can access the channel see an example link [here](https://lighthouseva.slack.com/archives/CJYJTRQ1F/p1728915555860939) (claim is under the Va Gov ...  heading)
* Otherwise to send your own you will need an errored claim, switch the channel to `vaapi-alerts-testing` make sure to have the testing key in your settings
* You can trigger the job from the console via `ClaimsApi::ReportHourlyUnsuccessfulSubmissions.perform_async`
* Worth it to preview the message before sending, I always limit every query to 1 just to keep it down depending on your local data you could get a huge output
modified:   modules/claims_api/app/services/claims_api/slack/failed_submissions_messenger.rb
modified: …
=> API-41095-va-gov-errors-slack-alert-fix-dd-timerange

modules/claims_api/spec/requests/v1/claims_spec.rb, modules/claims_api/spec/sidekiq/shared_reporting_examples_spec.rb
- Stabilizes flakey tests. 
- Skips flakey test until pending PR is merged.
modified:   modules/claims_api/spec/requests/v1/claims_spec.rb
modified:   modules/claims_api/spec/sidekiq/shared_reporting_examples_spec.rb
=> fix-flakey-test

modules/simple_forms_api/app/services/simple_forms_api/notification_email.rb, modules/simple_forms_api/spec/requests/simple_forms_api/v1/simple_forms_spec.rb, modules/simple_forms_api/spec/services/notification_email_spec.rb, spec/models/form_submission_attempt_spec.rb, spec/sidekiq/benefits_intake_status_job_spec.rb
Part 2 of [this bigger draft PR](https://github.com/department-of-veterans-affairs/vets-api/pull/18851). [Part 1 is here](https://github.com/department-of-veterans-affairs/vets-api/pull/18852).
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/1731
=> Use form-provided email address instead of Profile email address, Part 2

.github/CODEOWNERS
Shifts ownership of the mobile translations files from the backend team to the content team. 
https://github.com/department-of-veterans-affairs/va-mobile-app/issues/9641
None needed.
=> 9641: make content group owners of mobile translations files

.github/workflows/be_review_prs.yml, .github/workflows/ready_for_review.yml, docs/setup/hybrid.md
Error seen sometimes in CI runs:
```
/home/runner/work/_temp/3711f819-88c3-4533-82f2-1842aa10d536.sh: line 345: unexpected EOF while looking for matching `"'
Error: Process completed with exit code 2.
```
[Example from here](https://github.com/department-of-veterans-affairs/vets-api/actions/runs/11349304416/job/31565085162?pr=18846#annotation:8:357)
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/93566
- Reproduced error locally by using various characters in approval comments, until it was determined that single quotes were causing the action to fail, which matches the case from above and [this one](https://github.com/department-of-veterans-affairs/vets-api/pull/18607#issuecomment-2377288194) from a few weeks ago, though further testing confirmed it was the single, …
=> Use EOF to prevent failures from unexpected characters in GHA's

lib/disability_compensation/providers/document_upload/lighthouse_supplemental_document_upload_provider.rb, spec/lib/disability_compensation/providers/document_upload/lighthouse_supplemental_document_upload_provider_spec.rb, spec/sidekiq/evss/disability_compensation_form/upload_bdd_instructions_spec.rb
As initially implemented, my `LighthouseSupplementalDocumentUploadProvider` service was obtaining a user `participant_id` off of a `User` object which I looked up off of the Form 526 Submission record's `user_uuid`. (`participant_id` is a required field for uploading documents to the Lighthouse Benefits Documents API)
However, I've since learned that user objects are only persisted when the user is logged in, and we need to get this information elsewhere. Fortunately, this ID is persisted in the submission's `auth_headers` hash so we can retrieve it directly from the submission record.
- *This work is behind a feature toggle (flipper): YES this entire migration is behind a flipper and will be tested before it is rolled out in production
=> [Lighthouse Migration] Obtain user participant ID from reliable source

app/models/form526_submission_remediation.rb, spec/models/form526_submission_remediation_spec.rb
- add an enum for `remediation_type` to the `Form526SubmissionRemediation` model. This will replace the `ignored_as_duplicate` boolean in a subsequent PR  & data migration. More details are listed in the ticket
- [Follow up to this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/18779)
- [Ticket](https://github.com/orgs/department-of-veterans-affairs/projects/1263/views/2?filterQuery=assignee%3ASamStuckey&pane=issue&itemId=82453998&issue=department-of-veterans-affairs%7Cvets-api%7C18767)
- To verify functionality, run a rails console in the branch and run `Form526SubmissionRemediation.new.remediation_type`. It will return `manual`
Part of zero silent failure work on the 526 EZ form
=> [DBX-18767] update Form526SubmissionRemediation model with type enum

modules/check_in/app/sidekiq/check_in/travel_claim_submission_worker.rb
Add facility type to TravelClaim::Service instantiation so that it can be used by the service class to use a different claim_number for Oracle Health claims.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/93076
PCI and Oracle Health travel claims
=> 93076 add facility type to service instantiation

lib/mhv/account_creation/service.rb, spec/lib/mhv/account_creation/service_spec.rb
- Adds a log recording a request to the MHV account creation API for a new account; this provides a baseline to measure successes and failures agains.
-  VI-478
- Use the `MHV::AccountCreation::Service` to request a new MHV account, be sure to set `break_cache` to `true` to force the service to attempt to call out to MHV.
- You should see the following log
```ruby
MHV::AccountCreation::Service.new.create_account(icn:, email:, tou_occurred_at:, break_cache: true)
Rails -- [MHV][AccountCreation][Service] create_account request -- { :icn => "1008704012V552302" }
```
=> [VI-478] adds mhv account creation request log

modules/claims_api/app/services/claims_api/dependent_claimant_poa_assignment_service.rb
See title. This work is behind a feature flag - no participant ids were logged in production.
[API-41119](https://jira.devops.va.gov/browse/API-41119)
N/A
N/A
Dependent POA Assignment Service logs
N/A
=> [API-41119] Remove participant id from dependent claimant POA assignment logs

app/models/form_submission_attempt.rb, modules/simple_forms_api/app/services/simple_forms_api/notification_email.rb, spec/models/form_submission_attempt_spec.rb
This PR refactors the `FormSubmissionAttempt` model in light of the fact that teams other than Simple Forms use it. This PR makes the model more explicit about when it sends a Simple Forms email vs other (or no) email.
It doesn't resolve this issue but is related and some pre-work refactoring: https://github.com/orgs/department-of-veterans-affairs/projects/1443/views/3?sliceBy%5Bvalue%5D=Thrillberg&pane=issue&itemId=83509901&issue=department-of-veterans-affairs%7CVA.gov-team-forms%7C1747
=> Refactor FormSubmissionAttempt to check for simple forms earlier before emailing

app/sidekiq/lighthouse/create_intent_to_file_job.rb
- Handles nil values when logging in Lighthouse::CreateIntentToFileJob
- [*Link to ticket created in va.gov-team repo*](https://github.com/department-of-veterans-affairs/va.gov-team/issues/95098)
Pensions
=> CreateIntentToFileJob handle nil logging values

modules/appeals_api/config/mailinglists/report_daily.yml
- *This work is behind a feature toggle (flipper):NO*
This PR simply adds two new recipients to the Daily Decision Reviews Email Report.
My team, Banana Peels, own this module and maintains it.
[Add Maurice DeBeary and Molly Trombley to Daily Decision Review API report (Production)](https://jira.devops.va.gov/browse/API-41196)
Only the Decision Reviews mailer.
=> Add two recipients to daily report email

chart/templates/cron-deployment.yaml, chart/templates/db-migrate-job.yaml, chart/templates/environment-secrets.yaml, chart/templates/server-deployment.yaml, chart/templates/worker-deployment.yaml, chart/values.yaml
- Changes to the vets-api parent helm chart to include parameters store values from values set inside the parent helm chart
- These changes will allow movement toward a consistent helm chart for all environments - allowing environmental consistency and utilization by Preview Environment deployments
- https://app.zenhub.com/workspaces/reliability-team-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/94628
- Isolated test of changes done in a smaller representative helm chart
- Additional testing to be done in DEV environment post merge
vets-api deployments
=> Param store normalization

app/services/sign_in/attribute_validator.rb, spec/services/sign_in/attribute_validator_spec.rb
- This PR reverts a change that preferred MPI lookup by mhv_uuid when a user authenticates with MHV
Authentication
=> Reverting Sign in Service MHV MPI lookup by mhv_uuid

lib/sign_in/idme/configuration.rb, lib/sign_in/idme/service.rb, lib/sign_in/logingov/configuration.rb, lib/sign_in/logingov/service.rb, lib/sign_in/public_jwks.rb, spec/lib/sign_in/idme/service_spec.rb, spec/lib/sign_in/logingov/service_spec.rb, spec/support/vcr_cassettes/identity/idme_jwks_jwt_malformed.yml, spec/support/vcr_cassettes/identity/logingov_jwks_jwt_malformed.yml
- Handle situations where a JWT is is encoded with a new key but is being verified with the old JWK that is cached.
- the `jwt` gem has a built in way of handling this using a `jwks_loader` method (They say lambda but I think a method is cleaner in this case). [`jwks_loader`](https://github.com/jwt/ruby-jwt?tab=readme-ov-file#json-web-key-jwk), [`jwt/jwk/key_finder.rb#L31-L43`](https://github.com/jwt/ruby-jwt/blob/42f905c7fb734d009f311017b17a7645d5ee1e0c/lib/jwt/jwk/key_finder.rb#L31-L43)
- Basically what this does is it first tries to find the JWK in the cache by calling `jwks_loader`, if the JWK is not found - it calls `jwks_loader(kid_not_found: true)`. This will clear the cache and fetch and use the new JWKS.
- https://jira.devops.va.gov/browse/VI-647
- Test SiS login with idme and …
=> [VI-647] Gracefully handle external JWK rotations

Gemfile.lock, config/features.yml
Disable the feature flag, `veteran_onboarding_show_welcome_message_to_new_users` by default in the `dev` environment
=> disable feature flag in dev

app/sidekiq/decision_review/saved_claim_hlr_status_updater_job.rb, app/sidekiq/decision_review/saved_claim_nod_status_updater_job.rb, app/sidekiq/decision_review/saved_claim_sc_status_updater_job.rb, spec/sidekiq/decision_review/saved_claim_hlr_status_updater_job_spec.rb, spec/sidekiq/decision_review/saved_claim_nod_status_updater_job_spec.rb, spec/sidekiq/decision_review/saved_claim_sc_status_updater_job_spec.rb
This update increments the StatsD metric `silent_failure` statsd metric for all of the form and evidence failures that are detected by the SavedClaim status updater jobs. This also updates the existing StatsD metrics to increment only when form or evidence status changes, instead of incrementing every time the statuses are polled.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/94461
Tested locally and spec tests
This impacts statsd and the SavedClaim status updater jobs
=> 94461: Add silent failure metrics and clean up other metrics for DR SavedClaim status updater jobs

db/migrate/20241018163939_create_secondary_appeal_form.rb, db/schema.rb
- Added a migration to create a `secondary_appeal_forms` table
- First step in tracking submission of 4142 forms that are submitted as part of a Supplemental Claim
- Decision Reviews Team
[department-of-veterans-affairs/va.gov-team/issues/95001](https://github.com/department-of-veterans-affairs/va.gov-team/issues/95001)
No tests because this is only the migration and schema change
Adds a table to the DB
=> Add migration for Secondary Appeal Form

config/features.yml
- Adds feature flag to use refactored BD logic for 526 v2 uploads via DisabilityCompensationBenefitsDocumentsUploader.
- This logic is currently sending 526 forms to BD for upload in production, so the new flipper would control sending 526 forms to BD via the refactored logic.
- Success criteria: 526 form uploads sent to BD via 526 submit and 526 synchronous methods succeed without error with flipper enabled.
- Removal expectation: Flipper can be removed once 526 form uploads are confirmed working in production with flipper enabled and we've allowed some bake-in time; say 2 months.
[API-41218](https://jira.devops.va.gov/browse/API-41218)
N/A
Feature flags
=> Add 526 v2 uploads refactor flag to features list

app/models/form526_submission.rb, app/models/form526_submission_remediation.rb, spec/factories/form526_submission_remediations.rb, spec/models/form526_submission_remediation_spec.rb, spec/models/form526_submission_spec.rb
- We used to have 2 types of remediation for silent failures, now we have 3 so we are ditching the `ignored_as_duplicate` boolean in favor of a type enum
- This supports upcomming ZSF email notification work for 526
- [Ticket](https://github.com/orgs/department-of-veterans-affairs/projects/1263/views/2?filterQuery=assignee%3ASamStuckey&pane=issue&itemId=82453998&issue=department-of-veterans-affairs%7Cvets-api%7C18767)
- manual testing in a command line of new methods,
- migrated the data points via a prod command line. All Form526SubmisisonRemediations that have `ignored_as_duplicate: true` now also have a `remediation_type: :ignored_as_duplicate`
526 submission ZSF monitoring
=> [DBX-18767] update 526 remediations to use new duplicate paradigm

config/settings.yml
This PR adds teh Pager Duty service ID for the newly created `Production: External: 10-7959f-1 form` service in Pager Duty. This is so we can schedule maintenance windows/downtimes for the form application.
- Team: IVC CHAMPVA
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/95059 …
=> 95059 - Add FMP1 PagerDuty service to production maintenance block - form 10-7959f-1

modules/veteran/app/sidekiq/veteran/vso_reloader.rb, modules/veteran/spec/sidekiq/veteran/vso_reloader_spec.rb, spec/support/vcr_cassettes/veteran/ogc_vso_rep_data.yml
* Updates VCR to add test user with space at end of last name for import job
* Updates import job to strip trailing white space from last name
* Adds test for scenario
[API-41096](https://jira.devops.va.gov/browse/API-41096)
modified:   modules/veteran/app/sidekiq/veteran/vso_reloader.rb
modified:   modules/veteran/spec/sidekiq/veteran/vso_reloader_spec.rb
modified:   spec/support/vcr_cassettes/veteran/ogc_vso_rep_data.yml
=> API-41096-remove-trailing-spaces-from-name-in-rep-import

.github/CODEOWNERS, app/controllers/v0/health_care_applications_controller.rb, config/features.yml, spec/controllers/v0/health_care_applications_controller_spec.rb, spec/requests/v0/health_care_applications_spec.rb, spec/support/vcr_cassettes/lighthouse/facilities/v1/200_facilities_facility_ids.yml
- When retrieving the Facilities list for a State, if there are none, run the Job that populates the table. (The job takes ~6 seconds at present). This will allow local dev and Review Instance environments, or others with freshly built DBs, to work without having to manually run the Job from the command line.
- 10-10 Health Enrollment Team, EZ/CG
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/95160
- Before this change, trying to fill out the 10-10EZ form on a fresh environment was blocked when entering your preferred Facility. The options are populated by retrieving the State's Facilities from Lighthouse, and then filtering them down to the ones valid downstream with VES. With the cache table empty, the …
=> Populate facilities cache if empty on request

app/sidekiq/decision_review/failure_notification_email_job.rb, config/settings.yml, config/settings/test.yml, spec/sidekiq/decision_review/failure_notification_email_job_spec.rb
This PR updates the `FailureNotificationEmailJob` to increment the `silent_failure_avoided_no_confirmation` metric whenever a send email request to VANotify is completed. The evidence failure emails have also been updated to use a different template than the form emails. Logs have been updated to include the VANotify email notification id and make tag names more consistent.
The job is behind the flipper flag `decision_review_failure_notification_email_job_enabled`.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/94461
https://github.com/department-of-veterans-affairs/va.gov-team/issues/84372
Tested locally and rspec tests
StatsD and Sidekiq
=> 84372: Update FailureNotificationEmailJob with silent failure metrics and use evidence template ids

.github/CODEOWNERS, app/sidekiq/form526_submission_failure_email_job.rb, config/settings.yml, spec/factories/form526_submissions.rb, spec/sidekiq/form526_submission_failure_email_job_spec.rb
- *This work is behind a feature toggle (flipper): NO* (usecase will be)
- Add service for sending failure emails to veterans. unblocks following work:
- leverage service in backup submission exhaustion
- leverage service in backup polling on failure result
- [blocks this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/18937)
- [Ticket ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/94127)
- [Ticket 2](https://github.com/department-of-veterans-affairs/va.gov-team/issues/94128)
- flipper will enable integration testing in staging
- all objects load and functions tested via local command line
=> [DBX-94127/94128] add 526 backup failure email job

config/features.yml
- Remove Flipper directing 4142s to Lighthouse - that is the default code path for all 4142s now
- No ticket, just small code cleanup
- Tests for Flipper cases removed in previous PR, this just removes the flipper from `features.yml`
Removes unused Flipper from list
=> Remove old flipper from features.yml

modules/ask_va_api/app/lib/ask_va_api/inquiries/creator.rb, modules/ask_va_api/app/lib/ask_va_api/inquiries/payload_builder/inquiry_details.rb, modules/ask_va_api/app/lib/ask_va_api/inquiries/payload_builder/shared_helpers.rb, modules/ask_va_api/app/lib/ask_va_api/inquiries/payload_builder/veteran_profile.rb, modules/ask_va_api/app/lib/ask_va_api/translator.rb, modules/ask_va_api/spec/app/lib/ask_va_api/inquiries/creator_spec.rb, modules/ask_va_api/spec/app/lib/ask_va_api/inquiries/payload_builder/inquiry_details_spec.rb, modules/ask_va_api/spec/app/lib/ask_va_api/inquiries/payload_builder/veteran_profile_spec.rb, modules/ask_va_api/spec/app/lib/ask_va_api/translator_spec.rb
Summary
This PR introduces several key improvements to the VeteranProfile, InquiryDetails, and Translator classes to enhance modularity, clarity, and functionality across the codebase.
- VeteranProfile Refactor: The VeteranProfile class has been refactored to improve its structure by separating concerns into base_profile and service_info methods. The introduction of the state_data helper method ensures correct handling of veteran state information. The FieldTranslator is now utilized for translating values, improving readability, and SharedHelpers has been added for shared functionality.
- InquiryDetails Refactor: The InquiryDetails class has been restructured to handle different inquiry types more effectively. New methods such as handle_self_inquiry, handle_others_inquiry, and …
=> Ask va api create veteran profile

config/features.yml
- This work is behind a feature toggle (flipper): NO*
- This change removes the `va_online_scheduling_enable_OH_reads` feature flag from configuration.  All code and tests referencing this flag was removed in #84592.
https://app.zenhub.com/workspaces/appointments-oracle-health-integration-65a6e99ea522640e4d09393b/issues/gh/department-of-veterans-affairs/va.gov-team/94547
https://app.zenhub.com/workspaces/appointments-oracle-health-integration-65a6e99ea522640e4d09393b/issues/gh/department-of-veterans-affairs/va.gov-team/84592
- All tests referencing the removed feature flag were refactored in a previous PR.
- VAOS Appointment module
=> remove unused OH reads feature flag

db/migrate/20241017154903_create_claim_va_notifications.rb, db/schema.rb
We send a confirmation email during the PensionBenefitsIntakeJob. There's no way to 'undo' this step, and we don't have any checks in place to see if the confirmation email was already sent, so this step could get run more than once if the job fails after this step. (It's unlikely the job will fail after this, since all we do afterwards is log the success, but in a worst-case scenario...)
Create a new DB table that holds VA notifications that can be checked before attempted duplicate sends
- Create a new DB table ClaimVANotification
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/86428
=> 86428: Create ClaimVANotification table

config/settings.yml, modules/simple_forms_api/app/services/simple_forms_api/notification_email.rb, modules/simple_forms_api/spec/services/notification_email_spec.rb
This PR adds a template id for the 21-0966 error email to vets-api. The manifests repo has already been updated.
https://github.com/orgs/department-of-veterans-affairs/projects/1443/views/3?sliceBy%5Bvalue%5D=Thrillberg&pane=issue&itemId=83509901&issue=department-of-veterans-affairs%7CVA.gov-team-forms%7C1747
=> Add template id for 21-0966 error email

docs/setup/hybrid.md, docs/setup/native.md, docs/setup/running_natively.md
Binstubs can simplify vets-api setup and testing so we should point people to those docs as an alternative to the traditional setup.
I had an issue getting tests to run without a ton of failures until I ran tests with binstubs. @rjohnson2011 suggested updating docs. 
docs
=> Point to binstubs in setup docs

.github/CODEOWNERS, app/models/secondary_appeal_form.rb, spec/factories/secondary_appeal_forms.rb, spec/models/secondary_appeal_form_spec.rb
- We want to track the status of 4142 forms that are submitted as part of submitting a Supplemental Claim. This PR adds the database table and model that we will use to track them, but does not actually implement the tracking.
- This work belongs to the Decision Reviews Team
- No functionality is added in this PR, so the Flipper is not yet included
[department-of-veterans-affairs/va.gov-team/issues/95001](https://github.com/department-of-veterans-affairs/va.gov-team/issues/95001)
- Create and save an instance of the new model, verify the validations are working
Creates a new table and model, including a factory and tests for that model
=> Add model for tracking 4142 submissions

app/models/form_submission_attempt.rb
This PR fixes the way we log state machine changes in the `FormSubmissionAttempt` model. The old way was always going to the `else` branch so I believe we weren't detecting failures and successes accurately.
=> Fix state machine logging in FormSubmissionAttempt

modules/veteran/app/sidekiq/representatives/update.rb, modules/veteran/spec/sidekiq/representatives/update_spec.rb
- LH's address validation api can struggle with addresses that contain street addresses mixed with P.O. Boxes and will return the geolocation for these as (0, 0). That causes the Find a Rep tool to display some very unexpected distances to users.
- This pr adds some basic retry logic when we get zero coordinate results. The retry uses the additional address line fields as address 1.
- If there are no non-zero coordinate candidates, then we no longer want to update the record.
- [94579](https://github.com/department-of-veterans-affairs/va.gov-team/issues/94579)
Will impact the update job that runs on the Trexler File and eventually FAR and Appoint
=> [94579] Add zero coordinate retry logic to representative address updater

config/features.yml
- *This work is behind a feature toggle (flipper): NO -adds the Flipper*
- Add new Flipper for tracking submission of 4142s
-[department-of-veterans-affairs/va.gov-team/issues/95001](https://github.com/department-of-veterans-affairs/va.gov-team/issues/95001)
- No behavior changes, just the Flipper
- Feature will be tested in staging, then turned on for a percentage of users in prod for a few days, then turned on for everyone. The sooner we deploy the sooner we can automatically notify veterans of 4142 failures
No user-facing changes, no other changes in this PR
=> Add Flipper for tracking 4142s

app/services/login/after_login_actions.rb, app/services/sign_in/user_code_map_creator.rb, config/features.yml, spec/services/login/after_login_actions_spec.rb, spec/services/sign_in/user_code_map_creator_spec.rb
- *We are adding a a feature toggle `mhv_account_creation_api` in the BE to begin the phase rollout for the account creation api.*
- [VI-626](https://jira.devops.va.gov/browse/VI-626) …
=> VI-626 Add mhv_account_creation_api flipper

db/migrate/20241021182334_create_decision_review_notification_audit_log.rb, db/schema.rb
This PR is a migration to create the `decision_review_notification_audit_logs` table.
This table will be used to store VANotify payloads received by the `v1/nod_callbacks` endpoint.
No flipper is needed for this as it is a table migration.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/94148
Migration was run locally
Postgres DB
=> 94148: Migration for DecisionReviewNotificationAuditLog table

app/sidekiq/benefits_intake_status_job.rb
This PR fixes a misunderstanding that I had where I thought on _every_ failed form submission we wanted to increment `silent_failure`. It turns out we only want to increment that on such cases where an email failed to send. This deletes the faulty incrementing but does not yet replace it because I'm not sure how to handle that yet.
=> Stop incrementing silent_failure for Simple Forms

modules/simple_forms_api/app/services/simple_forms_api/notification_email.rb, modules/simple_forms_api/spec/services/notification_email_spec.rb
This PR fixes a Ruby syntax typo and adds a test for that typo.
=> Fix typo in 21-0966 notification email

config/features.yml
- **Added new toggle:**
- `profile_show_no_validation_key_address_alert`
- The `profile_show_no_validation_key_address_alert` toggle was introduced to control the visibility of two new alert messages when no validationKey is returned from the address_validation endpoint
**Timeframe for toggle:**
- Targeted for removal in November.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/93272
Tested locally.
No UI changes.
Profile
=> Add flipper to show/hide address validation alert for no validationKey

modules/debts_api/lib/debts_api/v0/financial_status_report_service.rb, modules/debts_api/lib/debts_api/v0/fsr_form_builder.rb, modules/debts_api/lib/debts_api/v0/fsr_form_transform/personal_data_calculator.rb, modules/debts_api/spec/lib/debt_api/v0/fsr_form_transform/personal_data_calculator_spec.rb
We found out that we are erroring when validating form data that we have mutated. This PR fixes the issue (nil addressLine2 instead of empty string) and allows us to see what the validation issue was in the logs rather than having to guess/look up in progress forms.
[FWIW, we have added a monitor for this issue](https://vagov.ddog-gov.com/monitors/289709)
- *(Summarize the changes that have been made to the platform)*:
- Fixed issue, added better logging, and added monitor for issue (not in this PR)
- *(If bug, how to reproduce)*: I was able to see the issue by running the following:
```
1. Copied payload that was erroring from Staging env
2. Ran IPF through transform
ipf = …
```
=> 95595 Debts team addressLine2 `nill` bug

.github/CODEOWNERS, app/controllers/v1/nod_callbacks_controller.rb, app/models/decision_review_notification_audit_log.rb, config/features.yml, spec/controllers/v1/nod_callbacks_controller_spec.rb, spec/factories/decision_review_notification_audit_logs.rb, spec/models/decision_review_notification_audit_log_spec.rb
This PR updates the NodCallbackController to save all status messages of VANotify notification emails that were sent to Veterans.
This feature is behind the nod_callbacks_endpoint flipper flag.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/94148
The old behavior would only save callbacks in a permanent failure state that would not retry to the `nod_notifications` table. 
The new behavior saves all received callbacks to a new table `decision_review_notification_audit_logs`. This feature will be tested in staging before being enabled in production.
This was tested locally using Postman for POSTing requests to the `v1/nod_callbacks` endpoint.
This impacts the NodCallbackController endpoint and the …
=> 94148: Update NodCallbacksController to save all notifications to DR audit log

app/models/secondary_appeal_form.rb, lib/decision_review_v1/appeals/supplemental_claim_services.rb, spec/factories/secondary_appeal_forms.rb, spec/models/secondary_appeal_form_spec.rb, spec/requests/v1/supplemental_claims_spec.rb
- Save a SecondaryAppealForm object of type '21-4142' when it is successfully submitted to Lighthouse as part of submitting a SupplementalClaim
- Remove schema validation for SecondaryAppealForm because we want to save even malformed form data for audit purposes
- Upcoming: Poll for status and set a delete_date when form is completely successful or failed
- Decision Reviews team, we own this controller and code path
- Success if form information can be saved without error for every 4142 submission
department-of-veterans-affairs/va.gov-team/issues/95001
- Before this change, we logged the status of the request to submit the 4142, but we did not persist information about the form or it's guid in Lighthouse, so we could not poll for its …
=> Save a record of 4142 forms submitted as part of Supplemental Claim

config/application.rb, config/settings.yml
- Add Sign-in Service specific web_origins to sign_in settings. This is for clients that only use the SiS portion of vets-api and helps keep things separated for the eventual split
- https://jira.devops.va.gov/browse/VI-396
- Test SiS and SSOe auth on vets-website
- Test SiS auth on identity-dashboard locally (optional) 
web_origins, sis
=> Add sign-in service specific web_origins

.github/workflows/deploy_delay_notifications.yml
- Looking at commit history, we've tried to get this right a few times. Current logic has it giving the 45 min response as soon as it is deployed because it's backwards. 4th time(?)'s the charm.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/91838
=> Deploy Delay Notification - Flip "-gt" to "-lt"

config/features.yml
- *This work is behind a feature toggle (flipper):* this work _**is**_ a feature toggle :)
- adds disability_526_new_confirmation_page  for future functionality
- only to be consumed on the client
- [*Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses Jira*](https://github.com/department-of-veterans-affairs/va.gov-team/issues/95149)
- disability_526_new_confirmation_page shows up on flipper admin page
=> dbex/95149: add disability_526_new_confirmation_page feature toggle

modules/claims_api/spec/sidekiq/report_hourly_unsuccessful_submissions_spec.rb
- Allows for two scenarios to be true so as to stabilize the test. Ran it upwards of 20x.
report_hourly_unsuccessful_submissions_spec.rb
=> Fix report_hourly_unsuccessful_submissions_spec.rb

.github/CODEOWNERS, app/sidekiq/delete_old_pii_logs_job.rb, spec/sidekiq/delete_old_pii_logs_job_spec.rb
We’ve identified that our PG Query Duration metric has [been spiking between 2:00-4:00 AM ET](https://vagov.ddog-gov.com/monitors/199084?from_ts=1729693621668&to_ts=1729780021668&eval_ts=1729756875247). After adjusting [several VBA jobs](https://vagov.ddog-gov.com/logs?query=%22VBADocuments%3A%3AUploadRemover%22%20status%3Aerror&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=paused&storage=hot&stream_sort=desc&viz=stream&from_ts=1729745071236&to_ts=1729762990337&live=false) that run during this …
=> Batch DeleteOldPiiLogsJob deletions

lib/medical_records/bb_internal/client.rb, modules/my_health/app/controllers/my_health/v1/medical_records/imaging_controller.rb, modules/my_health/config/routes.rb, spec/lib/medical_records/bb_internal/client_spec.rb, spec/support/vcr_cassettes/mr_client/bb_internal/study_status.yml
- Images request status API created for checking the status of a radiology images request job
https://jira.devops.va.gov/browse/MHV-62901
> ### Research/Implement API call to determine if images have been requested
> Description
> Research/Implement API call to determine if images have been requested
> 
> Lexi and Scott have designs. We have a call that does two things: requests images and give you the request status. 
> 
> We want to be able to go to the images page without requesting images and also know the status (have we requested them or not?). 
> 
> Is there an API that will let us know if we have requested them or not. MHV classic does this somehow. 
> 
> Mike, Muazzam can help/know. 
> 
> Goal: find the API call to determine if we have requested images. Implement it on vets-api
> …
=> MHV-62901: Images request status API implemented

modules/debts_api/lib/debts_api/v0/fsr_form_transform/installment_contracts_other_debts_calculator.rb, modules/debts_api/lib/debts_api/v0/fsr_form_transform/personal_data_calculator.rb, modules/debts_api/spec/lib/debt_api/v0/fsr_form_transform/installment_contracts_other_debts_calculator_spec.rb, modules/debts_api/spec/lib/debt_api/v0/fsr_form_transform/personal_data_calculator_spec.rb
We found out that we are erroring when validating form data that we have mutated. This PR fixes the issue (nil `creditorName` and `spouseFullName/last` instead of empty string) and allows us to see what the validation issue was in the logs rather than having to guess/look up in progress forms.
Fixed issue, added better logging, and added monitor for issue (not in this PR)
```
1. Copied payload that was erroring from Staging env
2. Ran IPF through transform
ipf = DebtsApi::V0::FsrFormTransform::FullTransformService.new(full_transform_form)
output = ipf.transform
3. Ran output through validator
schema_path = Rails.root.join('lib', …
```
=> 95727 - Issue with data validation in submission `creditorName` and ` spouseFullName/last` [FSR]

app/controllers/concerns/form_attachment_create.rb, spec/concerns/form_attachment_create_spec.rb
- Switching from the `log_exception_to_sentry` helper to `log_message_to_sentry`, since we can easily do a substring search for the message in the latter to group all relevant logs.
- It was not straightforward to gather multiple exception-style logs together for debugging the 403 errors, this should make it more clear what's happening.
- 10-10 Health Enrollment EZ/CG
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/93581
- previous attempt: …
=> convert sentry logs to messages for ease of tracking

modules/check_in/app/services/travel_claim/service.rb
Fixes [https://github.com/department-of-veterans-affairs/vets-api/security/code-scanning/859](https://github.com/department-of-veterans-affairs/vets-api/security/code-scanning/859)
To fix the problem, we should replace the unsafe `Oj.load` method with a safer alternative that does not allow deserialization of arbitrary objects. The `Oj.safe_load` method is a suitable replacement as it ensures that only basic JSON types are deserialized, thus mitigating the risk of arbitrary code execution.
**Steps to fix:**
1. Replace the `Oj.load` call on line 52 with `Oj.safe_load`.
2. Ensure that the `Oj.safe_load` method is used with appropriate options to handle the expected data format.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Fix code scanning alert no. 859: Deserialization of user-controlled data

app/models/appeal_submission.rb
- *This work is behind a feature toggle (flipper): NO* - model existence is not behind a flipper. All behavior is.
- Previously added a belongs_to to SecondaryAppealForm, needed the has_many on AppealSubmission
- optional, dependent: destroy
https://github.com/department-of-veterans-affairs/va.gov-team/issues/95001
- Could find the AppealSubmission from the SecondaryAppealForm, but not the other way
- Create an AppealSubmission with SecondaryAppealForm in staging, verify in console that lookup works both ways
No user facing changes, just a Rails association
=> Make association two-way

lib/lighthouse/benefits_documents/form526/update_documents_status_service.rb, spec/lib/lighthouse/benefits_documents/form526/update_documents_status_service_spec.rb
No, this job is currently running in production
This corrects a bug in the polling code that parses responses from the Lighthouse `uploads/status` API endpoint. This endpoint takes a batch of ids from documents we have uploaded to Lighthouse and reports their status in processing on their end. We use this to keep track of the document in our system, and whether it was successfully processed asynchronously by Lighthouse.
Currently, a service object for updating a single document in our system is actually memoized, meaning in a loop of batched record statuses, it will keep running the first document update over and over instead of updating all of the documents properly. …
=> Fix status update bug when polling multiple Lighthouse document records

Gemfile.lock
- Original PR: https://github.com/department-of-veterans-affairs/vets-api/pull/19050
- n/a
=> Bump googleauth from 1.11.1 to 1.11.2

modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb, modules/simple_forms_api/spec/requests/simple_forms_api/v1/simple_forms_spec.rb
This PR sends 26-4555s to the SAHSHA API regardless of whether the user has an ICN or not. It should _never_ go down the Benefits Intake API path.
https://github.com/orgs/department-of-veterans-affairs/projects/1443/views/3?sliceBy%5Bvalue%5D=Thrillberg&pane=issue&itemId=84586637&issue=department-of-veterans-affairs%7CVA.gov-team-forms%7C1789
=> Make 26-4555 no longer need an ICN to go to the SAHSHA API

app/sidekiq/form526_submission_failure_email_job.rb, spec/factories/form526_submissions.rb, spec/sidekiq/form526_submission_failure_email_job_spec.rb, spec/support/disability_compensation_form/submissions/with_everything.json
- Acoomodate new Product / Design ask to insert 'None' into email template if Vet-provided files and / or ancillary forms are blank
- Refactor for redability
- add nil check to error logging
- Update shared spec logic
- [Current Ticket for testing](https://github.com/department-of-veterans-affairs/va.gov-team/issues/94173)
- [Initial Ticket 1](https://github.com/department-of-veterans-affairs/va.gov-team/issues/94128)
- [Initial Ticket 2](https://github.com/department-of-veterans-affairs/va.gov-team/issues/94127)
- [Previous PR 1 (where this is used)](https://github.com/department-of-veterans-affairs/vets-api/pull/18937)
- [Previous PR 2 (where this was originally added)](https://github.com/department-of-veterans-affairs/vets-api/pull …
=> [DBX-94173] Cleanup after 526 failure email staging test

db/migrate/20241023222045_create_banners.rb, db/schema.rb
Adds 'banners' table migration.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19450
`bin/rails db:migrate`
An module the Sitewide team is building for Banners.
=> VACMS-19450: Banner model migration

config/features.yml
This PR reverts user types from `cookie_id` back to `user` ([previously, see this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/19055)). This needs to be done because we need access to the ability to whitelist user emails in a flipper (which does not appear to work when `actor_type: cookie_id`.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/95796
- https://github.com/department-of-veterans-affairs/vets-api/pull/19055 …
=> 95796 Reverting change to feature toggle actor type - IVC CHAMPVA Forms

app/uploaders/simple_forms_api/form_remediation/uploader.rb, config/features.yml, modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb, modules/simple_forms_api/app/models/simple_forms_api/vba_20_10207.rb, modules/simple_forms_api/app/services/simple_forms_api/form_remediation/s3_client.rb, modules/simple_forms_api/app/services/simple_forms_api/form_remediation/submission_archive.rb, modules/simple_forms_api/spec/requests/simple_forms_api/v1/simple_forms_spec.rb, modules/simple_forms_api/spec/services/form_remediation/submission_archive_spec.rb
- *This PR introduces logic to archive submissions and upload the resulting PDFs to S3, generating a pre-signed URL that is returned in the confirmation response. It includes updates to existing archival logic, refactoring of tests, and implementation of a feature flag to manage the deployment of the new S3-related functionality.*
- *The solution leverages AWS pre-signed URLs to securely provide access to the uploaded PDFs, allowing users to download the PDFs directly from S3. The implementation also includes setting the `Content-Disposition` header to ensure the correct filename is presented during downloads.*
- *I work for the Veteran Facing Forms team, and our team will maintain this component.*
- *The success criteria for the …
=> [SIMPLE_FORMS] feat: update uploads controller to archive and return presigned_url

app/sidekiq/form1010cg/submission_job.rb, spec/sidekiq/form1010cg/submission_job_spec.rb
- Changing the retries on the form1010cg submission job from 22 to 14. This change makes it the same as our 1010EZ and 1010EZR submission jobs. (It will retry for roughly 1 day, while previously it was roughly 10 days). 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/93823
- Updated documentation [here](https://github.com/department-of-veterans-affairs/va.gov-team/pull/95593)
10-10CG
=> [10-10CG] Update submission job retries from 22 to 14

modules/ivc_champva/app/services/ivc_champva/pdf_filler.rb, modules/ivc_champva/spec/services/pdf_filler_spec.rb
feat: Ensure unique template file names and fix file path issues
- Updated `generate` method to construct `generated_form_path` and `stamped_template_path` using `Rails.root.join` for better path handling.
- Added `create_tempfile` method to create a temporary file for the template, ensuring unique file names by including `SecureRandom.hex`.
- Modified `create_tempfile` method to use `Tempfile` for creating temporary files and copying the template file to the temporary file.
- Ensured that the `template_form_path` is correctly constructed using `TEMPLATE_BASE` and `form_number`.
- Added error handling to raise an exception if the stamped template file does not exist after copying.
https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/simple_forms_api/app/services/s …
=> fix temp file issue

Gemfile.lock
Reverts department-of-veterans-affairs/vets-api#19104
Causing Vets API to boot webrick.
=> Revert "Bump factory_bot_rails from 6.4.3 to 6.4.4"

modules/va_notify/app/sidekiq/va_notify/in_progress_1880_form_reminder.rb, modules/va_notify/spec/sidekiq/in_progress_1880_form_reminder_spec.rb
- *(Summarize the changes that have been made to the platform): Updating Error Logic
- *(If bug, how to reproduce)
- *(What is the solution, why is this the solution?)
- *(Which team do you work for, does your team own the maintenance of this component?): VA Notify - yes, my team owns this module
- https://app.zenhub.com/workspaces/forms-strike-team-620c2914e703390013c4b414/issues/gh/department-of-veterans-affairs/vanotify-team/1 …
=> VaNotify - Update InProgress1880FormReminder error logic

.github/workflows/deploy_delay_notifications.yml
- Fixes issue with incorrect notification (env variable not properly shared between jobs)
- Refactor:
- only runs dev and staging check if commits were found, and in turn only setting summary values in these cases
- if summary values are found, include in notification, otherwise return general error message and link to rub
- couple things for readability and consistency
=> Fix var usage and refactor

app/sidekiq/education_form/send_school_certifying_officials_email.rb, spec/sidekiq/education_form/send_school_certifying_officials_email_spec.rb
- *(Summarize the changes that have been made to the platform)* Fix datadog error within School Certifying Officials email
- *(If bug, how to reproduce)* Check datadog to see if errors go away
- *(What is the solution, why is this the solution?)* To not use Redis with the Sidekiq job
- *(Which team do you work for, does your team own the maintenance of this component?)* VEBT
- *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses Jira* https://jira.devops.va.gov/browse/VEBT-605
- *Link to previous change of the code/bug (if applicable)* N/A
- [ x] *New code is covered by unit tests* Yes …
=> Vebt 605 - Fix datadog error within School Certifying Officials email

app/sidekiq/education_form/create_daily_spool_files.rb, config/initializers/add_local_config.rb, config/initializers/kms_encrypted.rb, modules/claims_api/lib/brd/brd.rb, rakelib/routes_csv.rake, spec/sidekiq/education_form/create_daily_spool_files_spec.rb
- As part of normalizing helm charts and parameter store paths, the environment variables are given a prefix of `SETTINGS` and separator `__`. 
- This converts ENVs from the helm charts to Settings. This allows for the ENVs in the helm charts to be updated without affecting vets-api. 
Additionally, in `modules/claims_api/lib/brd/brd.rb` the ENV and Setting.brd where accessing the same value, so it was simplified (if `Setting.brd.api_key` is nil then so is `ENV['BRD_API_KEY']`) 
There is one exception, `VSP_ENVIRONMENT` is being accessed in an initializer before Settings is reload, so I think it needs to be an ENV. Eventually it can be updated to only use `SETTINGS__VSP_ENVIRONMENT`.
- Part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/95566 …
=> Migrate settings-related ENVs to use Settings directly

modules/ivc_champva/app/services/ivc_champva/pdf_filler.rb, modules/ivc_champva/spec/services/pdf_filler_spec.rb
Reverts department-of-veterans-affairs/vets-api#19060.
Something is causing the final S3 bucket name name the UUID before the form name.
We need the form name to come before the UUID. 
If the UUID comes before the form name, the PEGA system can't process it.
It should be this format: vha_10_7959f_1-cf1b6e07204447096d9bf37837c61df7.pdf
not 0099687f-7e9c-45a9-8865-ac67f0d7ef31_vha_10_7959f_1.pdf
=> Revert "fix temp file issue"

app/sidekiq/lighthouse/poll_form526_pdf.rb
- remove duplicative success metric. since we are using `with_tracking`, job_success is always called once the job is finished
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-togg …
=> remove duplicative success metric for form 526 pdf polling

lib/periodic_jobs.rb
We’ve identified that our PG Query Duration metric has [been spiking between 2:00-4:00 AM ET](https://vagov.ddog-gov.com/monitors/199084?from_ts=1729693621668&to_ts=1729780021668&eval_ts=1729756875247). After adjusting [several VBA jobs](https://vagov.ddog-gov.com/logs?query=%22VBADocuments%3A%3AUploadRemover%22%20status%3Aerror&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=paused&storage=hot&stream_sort=desc&viz=stream&from_ts=1729745071236&to_ts=1729762990337&live=false) that run during this …
=> Adjust window for KMS rotation job

app/sidekiq/form526_status_polling_job.rb, app/sidekiq/form526_submission_failure_email_job.rb, lib/sidekiq/form526_backup_submission_process/submit.rb, spec/lib/sidekiq/form526_backup_submission_process/submit_spec.rb, spec/sidekiq/form526_status_polling_job_spec.rb, spec/sidekiq/form526_submission_failure_email_job_spec.rb
- Pass a timestamp into the 526 failure emailer
- remove a syntax error (named arguments)
- update classname in logs for consistency 
- [Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/94173)
Run a staging test by doing the following
1. paste the new mailer object into a command line
2. update the `my_email` in the following script with yours (or wherever you want to send this)
3. paste the following script into the command line
```ruby
safe_sc_form = {"standardClaim"=>false, "isVaEmployee"=>false, "bankAccountType"=>"Checking", "bankAccountNumber"=>"123234454568", "bankRoutingNumber"=>"123343459", "bankName"=>"FakeUSA", "hasTrainingPay"=>false, "hasSeparationPay"=>false, "isTerminallyIll"=>false, …
```
=> [DBX-94173] add date of failure to 526 failure email

modules/simple_forms_api/docs/rfcs/0002-async-s3-pdf-upload.md
- This PR adds an RFC document proposing the transition of PDF uploads to an asynchronous Sidekiq job rather than the current synchronous method. This RFC outlines the technical requirements, expected benefits, frontend and backend changes, and error-handling strategies to improve user experience and performance.
- Not a bug; this is an RFC to guide future architectural changes.
- Solution: The RFC details the advantages of asynchronous processing, including reduced wait times on the Confirmation page, improved error handling, and resilient handling of S3 outages.
- Team: Veteran-Facing Forms team, responsible for maintaining and implementing this proposal as appropriate.
- [Discovery - Asynchronous PDF Upload to S3 with …
=> [SIMPLE_FORMS] doc: add rfc detailing tradeoffs of async pdf s3 uploads

modules/claims_api/app/sidekiq/claims_api/claim_establisher.rb, modules/claims_api/spec/sidekiq/claim_establisher_spec.rb
- Rescue Lighthouse::BackendServiceException in the Claim Establisher. This rescue does not re-raise the exception, thereby avoiding retries.
- [API-41448](https://jira.devops.va.gov/browse/API-41448)
N/A
- Claim Establisher
N/A
=> [API-41448] Rescue Lighthouse BackendServiceException

app/controllers/v1/nod_callbacks_controller.rb, app/sidekiq/decision_review/failure_notification_email_job.rb, spec/controllers/v1/nod_callbacks_controller_spec.rb, spec/sidekiq/decision_review/failure_notification_email_job_spec.rb
This PR updates the FailureNotificationEmailJob to include details in the `reference` field that is available for VANotify send_email. The callback handler will be able to use the `reference` field to accurately report the service name and function for `silent_failure_avoided` StatsD metrics.
This feature is behind the nod_callbacks_endpoint flipper flag.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/94148
Tested locally and also spec tests
This impacts the FailureNotificationEmailJob, VANotify and the NodCallbacks endpoint
=> 94148: Add reference value to DR failure email job and handling to callback controller

config/settings.yml, modules/ivc_champva/app/jobs/ivc_champva/missing_form_status_job.rb
- This PR adds the ID of a new VA Notify email template
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/95914
- https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/3179
*(Describe what parts of the site …
=> 95914 Add new email template value for form 10-10d failure notifications - IVC CHAMPVA

config/settings.yml, modules/simple_forms_api/app/services/simple_forms_api/notification_email.rb, modules/simple_forms_api/spec/fixtures/form_json/vba_40_10007-min.json, modules/simple_forms_api/spec/services/notification_email_spec.rb
Added error email for NCA form to Notifications email
https://jira.devops.va.gov/browse/MBMS-77352
- …
=> MBMS-77352 Added NCA error emails to email notifications

config/features.yml
- Add feature flag toggles in features.yml file to show and hide access to license, certificates exams and programs pages in comparion tool 
- EDM Team
https://jira.devops.va.gov/browse/EDM-297
=> edm 297 feature flag

.github/CODEOWNERS
- *This work is behind a feature toggle (flipper): YES/NO*: No
- *(Summarize the changes that have been made to the platform)*: Update codeowners separate from PR linked below
- https://github.com/department-of-veterans-affairs/vets-api/pull/19111
- https://jira.devops.va.gov/browse/EDM-213
=> EDM-213/Update codeowners for gids lce

lib/periodic_jobs.rb
After merging [this change yesterday](https://github.com/department-of-veterans-affairs/vets-api/pull/19116), we noticed a [shift in the alert window](https://vagov.ddog-gov.com/monitors/199084). It's split between two windows, but does overlap with the window where the KMS job runs. While [some logs indicate record rotation failures](https://vagov.ddog-gov.com/logs?query=service%3Avets-api%20env%3Aeks-prod%20host%3A%2Avets%5C-api%5C-sidekiq%2A%2A%20status%3Aerror%20%22%2ADecryption%20failed%2A%22&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice …
=> Move periodic job run to 5:10 window

app/sidekiq/central_mail/submit_form4142_job.rb, app/sidekiq/evss/disability_compensation_form/form4142_document_upload_failure_email.rb, spec/sidekiq/central_mail/submit_form4142_job_spec.rb, spec/sidekiq/evss/disability_compensation_form/form4142_document_upload_failure_email_spec.rb
- Logs **resolved** failures, where VA Notify is requested to dispatch an email notifying users of a failure associated with the submission of form 21-4142
- Logs **unresolved** silent failures, when a form 4142 failure email job fails to enqueue
- Logs messages identified as silent failures
- Increments metrics to capture an issue
- Supports logging and metrics requirements set by VA stakeholders
- Disability Benefits Experience Team 2 (dBeX Carbs 🥖), which owns maintenance of all files in …
=> [DBEX] log and monitor form 4142 failure email events

db/migrate/20241029143650_add_failure_notification_sent_at_to_secondary_appeal_form.rb, db/schema.rb
- Add a column to the SecondaryAppealForm table to track when a failure notification has been sent
- Decision Reviews team, yes
https://github.com/department-of-veterans-affairs/va.gov-team/issues/95980
- Migration only, no new code
Only adding a new column to a table for future work
=> Add :failure_notification_sent_at to SecondaryAppealForm

app/models/appeal_submission.rb, app/sidekiq/decision_review/failure_notification_email_job.rb, config/features.yml, spec/sidekiq/decision_review/failure_notification_email_job_spec.rb
- minor method name change for clarity
- *This work is behind a feature toggle (flipper): NO* -adds the Flipper
- Add a new Flipper for sending 4142 failure notification emails
- Minor change to method name `.current_email` -> `.current_email_address`
- Decision Reviews team, yes
https://github.com/department-of-veterans-affairs/va.gov-team/issues/95980
- Method name was slightly ambiguous - no behavior changes
Background job to notify about silent failures - no new behavior yet
=> Add feature flag to notify on 4142 failure

modules/claims_api/app/controllers/concerns/claims_api/claims_user.rb, modules/claims_api/app/controllers/concerns/claims_api/poa_verification.rb, modules/claims_api/app/controllers/concerns/claims_api/token_validation.rb, modules/claims_api/spec/concerns/claims_api/poa_verification_spec.rb, modules/veteran/app/models/veteran/service/representative.rb, modules/veteran/spec/models/veteran/service/representative_spec.rb
- Revert #19017.
- Add `suffix` to `ClaimsUser` (i.e., `@current_user`) attributes.
- Set the `@current_user`ʼs `suffix` to the suffix received from MPI, if any.
- Refactor POA code validation. Include suffix lookup to disambiguate representatives.
- Relax the validation to include the suffix matching _in addition to_ the other matching (e.g., middle name). i.e., increase the chances of a successful POA code validation.
[API-41395](https://jira.devops.va.gov/browse/API-41395)
N/A
- ClaimsUser attributes
- POA verification
- Token validation
Do we want to do any normalization around the suffix (e.g., strip punctuation/spaces)?
=> [API-41395] Add suffix matching to poa code validation

app/models/form526_submission.rb, app/sidekiq/evss/disability_compensation_form/form526_document_upload_failure_email.rb, app/sidekiq/evss/disability_compensation_form/submit_uploads.rb, spec/sidekiq/evss/disability_compensation_form/form526_document_upload_failure_email_spec.rb, spec/sidekiq/evss/disability_compensation_form/submit_uploads_spec.rb
- Logs **resolved** failures, where VA Notify is requested to dispatch an email notifying users of a failure associated with uploaded supplementary evidence
- Logs **unresolved** silent failures, when a failure email job fails to enqueue
- Logs messages identified as failures, which are made known to the user via email notification from VA Notify
- Increments metrics to capture an issue
- Supports logging and metrics requirements set by VA stakeholders
- Disability Benefits Experience Team 2 …
=> [DBEX] log and monitor evidence upload failure email events

app/sidekiq/evss/disability_compensation_form/form0781_document_upload_failure_email.rb
- Removes unnecessary memoization and methods in `Form0781DocumentUploadFailureEmail` (from https://github.com/department-of-veterans-affairs/vets-api/pull/19081) based on feedback received in https://github.com/department-of-veterans-affairs/vets-api/pull/19097
- Logs messages identified as failures, which are made known to the user via email notification from VA Notify
- Increments metrics to capture an issue
- Supports logging and metrics requirements set by VA stakeholders
- Disability …
=> [DBEX] refactor 0781 failure email logging & monitoring

app/models/form_profiles/va_0873.rb, spec/models/form_profile_spec.rb
- Fix `preferred_name` and `ava_profile` method in `0873.rb`
- https://github.com/department-of-veterans-affairs/ask-va/issues/1464
=> BE | Ask VA Api: fix `0873.rb` error handling bug

modules/simple_forms_api/docs/rfcs/0002-async-s3-pdf-upload.md
- This PR adds an RFC document proposing the transition of PDF uploads to an asynchronous Sidekiq job rather than the current synchronous method. This RFC outlines the technical requirements, expected benefits, frontend and backend changes, and error-handling strategies to improve user experience and performance.
- Not a bug; this is an RFC to guide future architectural changes.
- Solution: The RFC details the advantages of asynchronous processing, including reduced wait times on the Confirmation page, improved error handling, and resilient handling of S3 outages.
- Team: Veteran-Facing Forms team, responsible for maintaining and implementing this proposal as appropriate.
- [Part 1 of this …
=> [SIMPLE_FORMS] doc: add rfc detailing tradeoffs of async pdf s3 uploads - PART 2

modules/claims_api/spec/requests/v2/veterans/526_spec.rb, modules/claims_api/spec/requests/v2/veterans/rswag_526_spec.rb
* the anticipated separation date was being pulled directly from the JSON api file and was set for 10-31.  Which is today so it no longer is in the future.  This just dynamically sets it 2 days ahead like the rest of the groups.
[API-41632](https://jira.devops.va.gov/browse/API-41632)
modified:   modules/claims_api/spec/requests/v2/veterans/526_spec.rb
modified:   modules/claims_api/spec/requests/v2/veterans/rswag_526_spec.rb
=> API-30782-hotfix-for-failing-sync-test

config/settings.yml, config/settings/test.yml
This is part 2 of 3-ish
- Remove settings from `config/settings.yml` and `config/settings/test.yml`
- Checked using:
- Dot notation
- Hash access (`[]`, `.dig`, `fetch`)
- Checked parent key
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/95565
=> Remove Unused Settings - Part 2

modules/simple_forms_api/app/services/simple_forms_api/form_remediation/file_utilities.rb, modules/simple_forms_api/app/services/simple_forms_api/form_remediation/s3_client.rb, modules/simple_forms_api/spec/services/form_remediation/s3_client_spec.rb, modules/simple_forms_api/spec/services/form_remediation/submission_archive_spec.rb
- This PR includes updates to the S3 client logic, and added test coverage.
- Fixes a bug
- These updates resolve issues with S3 Client pre-signed url generation
- Team: Veteran Facing Forms team, maintenance of this component is handled by our team.
- No feature toggle introduced
- [Implement S3 PDF Storage and Pre-Signed URL Generation for Successful Submissions](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/1622)
- [Epic: Enable PDF Access, Storage, and Download Functionality for Submitted Forms](https://github.com/department-of-veterans-affairs/VA.gov-team-forms#1620)
- No flipper involved, so flipper testing is not required.
- This impacts the VFF team's S3 client operations. No other areas are …
=> [SIMPLE-FORMS] fix: update s3 client pre-signed url generation logic and add test coverage

config/settings.yml, config/settings/test.yml
This is part 3 of 3-ish
- Remove settings from `config/settings.yml` and `config/settings/test.yml`
- Checked using:
- Dot notation
- Hash access (`[]`, `.dig`, `fetch`)
- Checked parent key
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/95565
=> Remove Unused Settings - Part 3

app/controllers/v1/nod_callbacks_controller.rb, app/controllers/v1/pension_ipf_callbacks_controller.rb, config/settings.yml, modules/appeals_api/app/controllers/appeals_api/appealable_issues/v0/appealable_issues_controller.rb, modules/appeals_api/app/controllers/appeals_api/higher_level_reviews/v0/higher_level_reviews_controller.rb, modules/appeals_api/app/controllers/appeals_api/legacy_appeals/v0/legacy_appeals_controller.rb, modules/appeals_api/app/controllers/appeals_api/notice_of_disagreements/v0/notice_of_disagreements/evidence_submissions_controller.rb, modules/appeals_api/app/controllers/appeals_api/notice_of_disagreements/v0/notice_of_disagreements_controller.rb, modules/appeals_api/app/controllers/appeals_api/supplemental_claims/v0/supplemental_claims/evidence_submissions_controller.rb, modules/appeals_api/app/controllers/appeals_api/supplemental_claims/v0/supplemental_claims_controller.rb, modules/appeals_api/app/controllers/appeals_api/v1/appeals_controller.rb, modules/appeals_api/app/controllers/concerns/appeals_api/openid_auth.rb, modules/covid_vaccine/app/sidekiq/covid_vaccine/scheduled_batch_job.rb
- Most settings are accessed via dot notation (`Settings.parent_key.child_key`)
- Using `.dig` can obscure the use of those keys by making them difficult to find 
- The dot notation makes them easier to find
- If dot notation isn't possible, dig is acceptable 
- n/a
=> Switch Settings.dig to dot notation

modules/simple_forms_api/app/services/simple_forms_api/form_remediation/s3_client.rb, modules/simple_forms_api/spec/services/form_remediation/s3_client_spec.rb
- This PR fixes an issue with the Form Remediation solution's S3 integration where the pre-signed URL returned after a successful file upload referenced a temporary file path instead of the actual S3 storage path. The correction ensures that users can reliably access the uploaded PDF via the provided URL.
- The bug caused a `NoSuchKey` error when accessing the pre-signed URL because it incorrectly pointed to a temporary file path.
- The solution involves modifying the `s3_upload_file_path` method to correctly build the S3 file path using the `File.basename(archive_path)`, which references the file in its final S3 location.
- The Veteran-Facing Forms team implemented and maintains this component.
- [Bug - Fix Pre-signed URL Generation …
=> [SIMPLE-FORMS] fix: update s3 pre-fetched url logic

config/settings.yml, config/settings/development.yml, config/settings/test.yml, lib/flipper/README.md
This is part 4 of 3-ish
- Remove settings from `config/settings.yml` and `config/settings/development.yml`
- Checked using:
- Dot notation
- Hash access (`[]`, `.dig`, `fetch`)
- Checked parent key
- Added comments for difficult to find Settings (willing to remove if undesirable)
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/95565
=> Remove Unused Settings - Part 4

modules/ask_va_api/app/lib/ask_va_api/inquiries/payload_builder/inquiry_payload.rb, modules/ask_va_api/app/lib/ask_va_api/inquiries/payload_builder/veteran_profile.rb, modules/ask_va_api/spec/app/lib/ask_va_api/inquiries/payload_builder/inquiry_payload_spec.rb, modules/ask_va_api/spec/support/shared_contexts.rb
• In InquiryPayload, assigned a default LevelOfAuthentication ID for cases where user is nil. This prevents potential null errors when processing unauthenticated users.
• Fixed a nil handling bug in VeteranProfile by adding a check for veteran_info. This ensures the application gracefully handles cases where veteran_info may be missing.
• Attempt to access the InquiryPayload and VeteranProfile features with a missing user or veteran_info field, which previously resulted in a null pointer exception.
• This fix introduces additional checks to manage nil values for user and veteran_info. Assigning a default LevelOfAuthentication ID provides a fallback to ensure continued functionality without throwing errors.
- https://github.com/department-of-veterans-affairs/ask-va/issues/1463
=> BE | Ask VA Api: Update InquiryPayload and VeteranProfile

datadog-service-catalog/datadog-service-catalog.yml
Resolves https://github.com/orgs/department-of-veterans-affairs/projects/1180/views/5?pane=issue&itemId=81409364&issue=department-of-veterans-affairs%7Cva.gov-team%7C93851
- This PR adds the `representation-management` service to `datadog-service-catalog/datadog-service-catalog.yml`
- https://github.com/orgs/department-of-veterans-affairs/projects/1180/views/5?pane=issue&itemId=81409364&issue=department-of-veterans-affairs%7Cva.gov-team%7C93851
NA
NA
Datadog services catalog
NA
=> Add representation-management to Datadog service catalog

modules/representation_management/app/controllers/representation_management/v0/flag_accredited_representatives_controller.rb
Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/93851
- This PR adds the correct Datadog service tag to `FlagAccreditedRepresentativesController`
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/93851
NA
NA
NA
=> Add correct Datadog service tag to FlagAccreditedRepresentativesController

app/controllers/v0/caregivers_assistance_claims_controller.rb, spec/requests/v0/caregivers_assistance_claims_spec.rb
- Added new log statement for when the caregivers create endpoint raises an exception. It was original set as a debug log, but I realized in production we have `config.log_level = :info` so these logs won't be saved. This changes the log to an error so I can see the results of the logs in production. 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/95897
10-10 CG
=> [10-10CG] Update log from debug to error

app/sidekiq/decision_review/saved_claim_sc_status_updater_job.rb, spec/fixtures/supplemental_claims/SC_4142_show_response_200.json, spec/sidekiq/decision_review/saved_claim_sc_status_updater_job_spec.rb
- use different service and endpoint for checking 4142 vs evidence upload
- slightly different response attributes
- Use BenefitsIntake::Service.get_status to check status of 4142 submissions
- Turn on the `decision_review_track_4142_submissions` Flipper, see that the SavedClaimScStatusUpdaterJob fails with a 404 every time it runs
- Use the correct service and endpoint to query status of 4142s, they are not submitted quite the same way as other evidence documents
Original story: https://github.com/department-of-veterans-affairs/va.gov-team/issues/95001
- Used DecisionReviewV1::Service, now using BenefitsIntake::Service
- Ensure a SecondaryAppealForm exists without a status, run the update job, see that a …
=> Fix bug in polling 4142 status

app/models/secondary_appeal_form.rb, app/sidekiq/decision_review/failure_notification_email_job.rb, config/settings.yml, config/settings/test.yml, spec/sidekiq/decision_review/failure_notification_email_job_spec.rb
- Job that notifies about claims and evidence failures now also notifies about 4142 failures
-  Requires a separate PR to get the email template ids into settings in staging and prod
- Ensure no errors when running job with added behavior, ensure notifications actually go out for all failures
https://github.com/department-of-veterans-affairs/va.gov-team/issues/95980
- Previously: No action was taken for SecondaryAppealForms with an error status
- Submit a 4142, see it fail to process in Lighthouse, allow the status polling job to detect the failure, see that an email is sent
- tests for sending emails
- tests for feature flag
- tests for errors
-  Turn Flipper on in prod, trigger background job, ensure no …
=> Send email notifications for 4142 failures

spec/factories/form_submissions.rb
This PR fixes an omission where I was saving a field as `nil` instead of just omitting it altogether. In a followup PR we'll remove this field from the model/table altogether.
https://github.com/orgs/department-of-veterans-affairs/projects/1443/views/3?sliceBy%5Bvalue%5D=Thrillberg&pane=issue&itemId=83134444&issue=department-of-veterans-affairs%7CVA.gov-team-forms%7C1636
=> Stop saving benefits_intake_uuid to form submission spec factory

app/sidekiq/form526_status_polling_job.rb, app/sidekiq/form526_submission_failure_email_job.rb, lib/sidekiq/form526_backup_submission_process/submit.rb, spec/lib/sidekiq/form526_backup_submission_process/submit_spec.rb, spec/sidekiq/form526_status_polling_job_spec.rb, spec/sidekiq/form526_submission_failure_email_job_spec.rb
-  BUG FIX: Sidekiq converts all incomming arguments to strings. This was an oversight in the previous PR but caught in testing. This PR updates the Job to handle incomming timestamps as strings (or nil)
- [Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/94173)
- Prior to the change, the job  expected a ruby Time object or nil
- After the change, the job expects a timestamp as a string
We were not able to test the built in Sidekiq behavior until this change was actually merged. Previous tests [outlined in this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/19108) only tested the object, not the Sidekiq enqueuing / argument parsing behavior. 
The new code has been validated with step …
=> [DBX-94173] fix timestamp string bug in 526 failure email

modules/appeals_api/app/services/appeals_api/pdf_construction/supplemental_claim/v4/form_fields.rb
Starting to roll out new Supplemental Claims Form.  This code is unreachable.  Future PR will add calling structure\unit test.
Initial data fields to PDF Page Position mappings file.
[API-36674](https://jira.devops.va.gov/browse/API-36674)
Dead code at this point, just the initial data fields to PDF position mappings
Nothing but a uncalled file in github at this point
=> New supp claim forms, initial mappings

modules/claims_api/app/controllers/claims_api/v2/veterans/power_of_attorney/request_controller.rb, modules/claims_api/app/swagger/claims_api/v2/dev/swagger.json, modules/claims_api/config/routes.rb, modules/claims_api/spec/controllers/v2/veterans/power_of_attorney/request_controller_spec.rb, modules/claims_api/spec/requests/v2/veterans/power_of_attorney/power_of_attorney_request_spec.rb, modules/claims_api/spec/requests/v2/veterans/rswag_power_of_attorney_spec.rb, spec/support/schemas/claims_api/v2/veterans/power_of_attorney/request_representative/submit.json
- Add the newly created `procId` returned by BGS to the `/veterans/:id/power-of-attorney-request` response.
- Update docs (staging only) to reflect the above.
- [API-40542](https://jira.devops.va.gov/browse/API-40542)
**Testing steps**
1. Disable the `lighthouse_claims_v2_poa_requests_skip_bgs` feature flag.
1. Connect to BGS and manually send the following request:
```
curl --location 'http://localhost:3000/services/claims/v2/veterans/1012667145V762142/power-of-attorney-request' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer *****' \
--data-raw '{
"data": {
"veteran": {
"serviceNumber": "123678453",
"serviceBranch": "ARMY",
"address": {
"addressLine1": "2719 Hyperion Ave",
"addressLine2": "Apt 2",
"city": "Los Angeles", …
```
=> [API-40542] Create POA Request - Return Proc ID

app/sidekiq/kms_key_rotation/batch_initiator_job.rb
We've removed the code filtering out records with a nil encrypted_kms_key from the query. After investigating in the rails console, we found only one record (out of millions) with encrypted data and nil `encrypted_kms_key`, making this condition effectively a no-op.
```
Model AppealsApi::SupplementalClaim has no records with nil encrypted_kms_key and non-nil encrypted fields.
Model AppealsApi::NoticeOfDisagreement has no records with nil encrypted_kms_key and non-nil encrypted fields.
Model AppealsApi::HigherLevelReview has no records with nil …
```
=> fix: Only include encrypted records with non-null fields for rotation

app/controllers/v1/nod_callbacks_controller.rb, spec/controllers/v1/nod_callbacks_controller_spec.rb
- Add another function type to the callbacks controller so it can parse references from secondary form emails and log silent_failure_avoided for those emails
https://github.com/department-of-veterans-affairs/va.gov-team/issues/95981
- Controller only recognized emails about forms and evidence, now also recognizes emails about secondary forms
- Trigger notification emailed for failed SecondaryAppealForm, see it deliver succesfully, see the callback controller create a record of that success and log it as silent_failure_avoided
Backend handling of VA Notify callbacks about email status
=> #95981 monitor notification status

spec/sidekiq/evss/disability_compensation_form/submit_form0781_spec.rb
This PR is a follow-up to #19186, which is the base PR that will allow us to progressively transition uploading 0781 forms to the new Lighthouse Documents Benefits API. This PR only adds specs to test the multiple conditions of uploading the 0781 and 0781a forms. The submit0781 job processes both forms 0781 and 0781a, if present.
All new behavior is hidden behind a killswitch flipper, `disability_compensation_use_api_provider_for_0781_uploads`, which will only use the API provider if turned on.
If the killswitch is enabled, the API Provider Factory itself will decide if we use the Lighthouse or EVSS provider client for the uploads, based on the status of the `disability_compensation_upload_0781_to_lighthouse` flipper.
- *This work is behind a feature toggle (flipper): YES (described …
=> 83846 disability benefits migrate 0781 a uploads to lighthouse

spec/controllers/v0/profile/direct_deposits_controller_spec.rb, spec/mailers/direct_deposit_mailer_spec.rb, spec/serializers/direct_deposits_serializer_spec.rb
Add `team_owner` and `feature` RSpec tags to direct deposit spec files.
See [this document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/tutorials/testing/rspec_tags.md) for more information.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/95666
Updates direct deposit spec files.
=> Add RSpec tags to direct deposit spec files

config/settings.yml
- This PR adds the ID of a new VA Notify email template
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/95906
- https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/3194
*(Describe what parts of the site …
=> 95906 Add new email template value for form 10-7959f-1 failure notifications - IVC CHAMPVA

spec/sidekiq/evss/disability_compensation_form/submit_form0781_spec.rb
The 0781 job uses shared API provider logging values. This BDD PR https://github.com/department-of-veterans-affairs/vets-api/pull/19217 updated logging to include `submission_id` as well as `submitted_claim_id`. This PR updates the specs to match.
- *This work is behind a feature toggle (flipper): YES 
Disability Benefits team 2, aka Carbs; yes we do own the maintenance of these components
A certain amount of submissions will fail on upload to Lighthouse just as they do to EVSS …
=> Update 0781 specs to log submission_id and submitted_claim_id

config/settings/test.yml, lib/lighthouse/veteran_verification/configuration.rb, lib/lighthouse/veteran_verification/service.rb, spec/lib/lighthouse/veteran_verification/service_spec.rb, spec/support/vcr_cassettes/lighthouse/veteran_verification/status/200_not_confirmed_response.yml, spec/support/vcr_cassettes/lighthouse/veteran_verification/status/200_response.yml, spec/support/vcr_cassettes/lighthouse/veteran_verification/status/400_response.yml, spec/support/vcr_cassettes/lighthouse/veteran_verification/status/401_response.yml, spec/support/vcr_cassettes/lighthouse/veteran_verification/status/403_response.yml, spec/support/vcr_cassettes/lighthouse/veteran_verification/status/413_response.yml, spec/support/vcr_cassettes/lighthouse/veteran_verification/status/429_response.yml, spec/support/vcr_cassettes/lighthouse/veteran_verification/status/500_response.yml, spec/support/vcr_cassettes/lighthouse/veteran_verification/status/502_response.yml, spec/support/vcr_cassettes/lighthouse/veteran_verification/status/503_response.yml, spec/support/vcr_cassettes/lighthouse/veteran_verification/status/504_response.yml
- This work is not behind a feature toggle.
- This change adds a new method to the `VeteranVerification` module in the `lib/lighthouse/veteran_verification/service.rb` file for getting confirmation of veteran status. This method makes a request to the Lighthouse Veteran Service History and Eligibility API /status endpoint. A later PR will put this behind a new vets-api endpoint, which will be ready for vets-website to integrate into the Veteran Proof of Status feature.
- Documentation and further logging will be added in a later PR.
- [1139](https://github.com/department-of-veterans-affairs/va-iir/issues/1139)
- There is no old behavior, as this is a completely new implementation. Testing will be conducted, once the route …
=> Add new Vet Verification Service method for LH API request

modules/claims_api/app/controllers/claims_api/v2/veterans/power_of_attorney/request_controller.rb, modules/claims_api/app/swagger/claims_api/v2/dev/swagger.json, modules/claims_api/config/schemas/v2/power_of_attorney_requests/param/decision/post.json, modules/claims_api/spec/controllers/v2/veterans/power_of_attorney/request_controller_spec.rb, modules/claims_api/spec/requests/v2/power_of_attorney_requests/decisions/create/rswag_spec.rb
- All caps POA `/decide` decision enums.
- Fix typo in docs (staging only) from `approved` → `ACCEPTED`.
[API-40054](https://jira.devops.va.gov/browse/API-40054)
N/A
=> [API-40054] update poa decide enums

lib/medical_records/client.rb, spec/lib/medical_records/client_spec.rb, spec/support/vcr_cassettes/mr_client/get_a_patient_by_identifier_hapi_1363.yml, spec/support/vcr_cassettes/mr_client/get_a_patient_by_identifier_not_found.yml
- MHV backend will no longer throw an error for Patient Not Found. Instead it will return a 202.
- For a time, VA.gov will need to handle both error cases (the 202, plus the original HAPI-1363 error that is being deprecated).
> Update vets-api to handle 202 from MHV when no patient found
> 
> Currently when "No patient found" or "Multiple patient found," MHV is sending back the same 500 error. Muazzam is updating this to split out these errors ([MHV-60266](https://jira.devops.va.gov/browse/MHV-60266)). In the future:
> 
> "Multiple patients found" will continue to return 500
> "No patient found" will now return a 202 with an Observation record
> 
> We need to now update vets-api in two ways:
> 
> When we get that particular 500, return an error to the frontend
> When we get the 202, …
=> MHV-62174 Handle patient not found

modules/claims_api/app/controllers/concerns/claims_api/disability_compensation_validations.rb, modules/claims_api/spec/requests/v1/forms/526_spec.rb
* Adds a validation that is any direct deposit values are present then `bankName` must also be present
* Adds test for this scenario
[API-41445](https://jira.devops.va.gov/browse/API-41445)
* Sending in `directDeposit` information without the bank name should return
```{
"errors": [
{
"title": "Invalid field value",
"detail": "\"\" is not a valid value for \"directDeposit.bankName\"",
"code": "103",
"status": "400"
}
]
}
```
modified:   modules/claims_api/app/controllers/concerns/claims_api/disability_compensation_validations.rb
modified:   modules/claims_api/spec/requests/v1/forms/526_spec.rb
=> API-41445-v1-526-validate-bank-name

app/models/user.rb, app/services/login/after_login_actions.rb, app/services/sign_in/user_loader.rb, app/sidekiq/mhv/account_creator_job.rb, spec/models/user_spec.rb, spec/services/login/after_login_actions_spec.rb, spec/services/sign_in/user_loader_spec.rb
- Only create MHV user account async during SiS auth
- https://jira.devops.va.gov/browse/VI-716
- Login with SiS and make sure a `MHV::AccountCreatorJob` job is enqueued - http://localhost:3000/sidekiq/queues/default
MHV Account creation
=> [VI-716] - Only create MHV account async during SiS auth

modules/claims_api/app/controllers/concerns/claims_api/disability_compensation_validations.rb, modules/claims_api/spec/requests/v1/forms/526_spec.rb
- Adds transformation of empty unitName. 
- Adds a corresponding test.
- [API-41802](https://jira.devops.va.gov/browse/API-41802)
- hit v1 526 and set unitName to an empty string. You should get a 200
modified:   modules/claims_api/app/controllers/concerns/claims_api/disability_compensation_validations.rb
modified:   modules/claims_api/spec/requests/v1/forms/526_spec.rb
=> API-41802-handle-empty-unit-name

.github/CODEOWNERS
While on support and reviewing PRs, I noticed people would sometimes append their codeowners entries to the bottom of the file instead of placing them in alphabetical order. I took these files from the bottom and placed them where they belong. Along the way, I discovered duplicates and sorted a few other lines that I saw out of order. I also added a comment at the bottom to hopefully steer people in the right direction. 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/75910
CODEOWNERS file
=> Alphabetize some CODEOWNERS entries

modules/pensions/lib/pensions/monitor.rb, modules/pensions/spec/lib/pensions/monitor_spec.rb
Now that we have the general classes in place refactor the existing class and functions used in pension (and income-and-assets) to be reusable from other form submission workflows
- Refactor `Pensions::Monitor` to use new generalized method
- Update unit tests
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/95932
=> 95932: Update Pensions monitor

app/controllers/concerns/form_attachment_create.rb, spec/concerns/form_attachment_create_spec.rb
- Expand logging to track whether the file has a password, and its extension.
- To avoid accidentally introducing PII/PHI in the logs, we're only logging the last 5 characters of the extension. Maybe over-prudent, but we're filtering out the filename for a reason.
- 10-10 Health Enrollment EZ/CG team
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/92139
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/93581
- Fill out EZ form, upload a file for e.g. Discharge …
=> expand logs to check for passworded pdfs

app/sidekiq/decision_review/form4142_submit.rb, app/sidekiq/decision_review/submit_upload.rb
This PR updates the Decision Review sidekiq jobs to increase the retries in preparation for a ~39 hour COLA maintenance window.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/96377
This is a job configuration change so it does not have unit tests for the retries.
Decision Review sidekiq jobs related to claims evidence upload and secondary form submissions.
=> 96377: Increase DR Sidekiq jobs retry counts for COLA maintenance

app/models/preneeds/base.rb, lib/vets/model.rb, lib/vets/response.rb, spec/lib/vets/model_spec.rb
- `Vets::Model` was previously a class, but because it can't be used directly, it should be a model 
- `Vets::Model` is a replacement for Virtus gem
- This PR also updates `Preneeds::Base` and `Vets::Response`
- There's no functional difference, this is mostly superficial 
- n/a
=> Convert Vets::Model from a class to a module

postman/Dockerfile
- Since the postman test container is run as a postSync process, if it returns failure then the sync process keep re-trying. Changing so the container always succeeds and will rely on datadog monitors to notify of issues
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/95636
- confirmed newman command
postman test post sync
=> postman-test container always return success

.github/workflows/deploy_delay_notifications.yml
- The failure is preventing the staging step from running. Adding `always()` will allow it to run to, assuming the other condition is true.
=> Run Staging check too

lib/logging/monitor.rb, modules/pensions/lib/pensions/monitor.rb, modules/pensions/spec/lib/pensions/monitor_spec.rb, spec/lib/logging/monitor_spec.rb
refactor Logging::Monitor track_request function
[Trigger Pension and Burial Action Needed email notification](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91426)
[Trigger for downstream failure for Pension and Burial Action Needed email notification](https://github.com/department-of-veterans-affairs/va.gov-team/issues/95293)
Pension
=> PBP 91426 Logging track_request refactor

app/sidekiq/bgs/submit_form674_job.rb, app/sidekiq/bgs/submit_form686c_job.rb, app/sidekiq/central_mail/submit_central_form686c_job.rb, app/sidekiq/evss/disability_compensation_form/form0781_document_upload_failure_email.rb, app/sidekiq/evss/disability_compensation_form/form4142_document_upload_failure_email.rb, app/sidekiq/evss/disability_compensation_form/form526_document_upload_failure_email.rb, app/sidekiq/evss/disability_compensation_form/submit_form526.rb, app/sidekiq/evss/disability_compensation_form/submit_uploads.rb, app/sidekiq/evss/disability_compensation_form/upload_bdd_instructions.rb, app/sidekiq/evss/document_upload.rb, app/sidekiq/evss/request_decision.rb, app/sidekiq/form1010cg/submission_job.rb, app/sidekiq/form526_submission_failure_email_job.rb, app/sidekiq/hca/ezr_submission_job.rb, app/sidekiq/hca/submission_job.rb, app/sidekiq/lighthouse/create_intent_to_file_job.rb, app/sidekiq/lighthouse/document_upload.rb, app/sidekiq/lighthouse/income_and_assets_intake_job.rb, app/sidekiq/lighthouse/submit_benefits_intake_claim.rb, app/sidekiq/lighthouse/submit_career_counseling_job.rb, app/sidekiq/va_notify_dd_email_job.rb, app/sidekiq/va_notify_email_job.rb, app/sidekiq/vbms/submit_dependents_pdf_job.rb, app/sidekiq/vre/create_ch31_submissions_report_job.rb, app/sidekiq/vre/submit1900_job.rb, modules/pensions/app/sidekiq/pensions/pension_benefit_intake_job.rb, spec/sidekiq/form1010cg/submission_job_spec.rb
In response to new standards and the upcoming COLA outage, all sidekiq retries should be set to 16.
retry for  2d 1h 47m 12s
https://github.com/sidekiq/sidekiq/wiki/Error-Handling
https://dsva.slack.com/archives/C053U7BUT27/p1730909263999689?thread_ts=1730731734.405619&cid=C053U7BUT27
- [ X ] *New code is covered by unit tests*
- …
=> Change sidekiq retries to 16

.github/CODEOWNERS, app/controllers/v1/decision_review_notification_callbacks_controller.rb, config/routes.rb, spec/controllers/v1/decision_review_notification_callbacks_controller_spec.rb
This change renames `NodCallbacksController` to `DecisionReviewNotificationCallbacksController` to reflect the real usage of the controller.
#19124
https://github.com/department-of-veterans-affairs/va.gov-team/issues/94148
Tested locally and with `rails routes`
This impacts the `v1/nod_callbacks` route
=> 94148: Rename NodCallbacksController to DecisionReviewNotificationCallbacksController

lib/medical_records/bb_internal/client.rb, modules/my_health/app/controllers/my_health/v1/medical_records/bbmi_notification_controller.rb, modules/my_health/config/routes.rb, spec/lib/medical_records/bb_internal/client_spec.rb, spec/support/vcr_cassettes/mr_client/bb_internal/get_bbmi_notification_setting.yml
New API endpoint created to get bbmi email notification setting
https://jira.devops.va.gov/browse/MHV-62902
> ### Retrieve backend notification settings to determine which content to display for image notification
> Description
> Retrieve backend notification settings to determine which content to display for image notification. 
> 
> Front end will either say, you'll get an email notification or, if you want one, here's where to go to turn that on. 
> 
> Haritha, Elwood Gary might know, start w mike/muazzam. 
> 
> Goal: Find notification setting in MHV API and implement it for vets-api. 
> 
> User Story: As a Medical Images team, we want to determine what the user has set the imaging notification setting to, in order tov display the correct content for retrieving images.
Test created for …
=> MHV-62902: BBMI email notification setting status api created

app/sidekiq/form526_status_polling_job.rb, config/features.yml, lib/sidekiq/form526_backup_submission_process/submit.rb, spec/lib/sidekiq/form526_backup_submission_process/submit_spec.rb, spec/sidekiq/form526_status_polling_job_spec.rb
- Update 526 failure email flipper names to match existing conventions
- add flipper names to config file 
- [Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/94173)
- Nothing else to test
526 submission failure via backup path and polling. Zero silent failures
=> [DBX-95173] Normalize 526 failure email flippers

modules/va_notify/lib/va_notify/service.rb, modules/va_notify/spec/lib/service_spec.rb
- *(Summarize the changes that have been made to the platform)* Updates so that notification creation (behind feature flag) always defaults to a hash.
- https://github.com/department-of-veterans-affairs/vanotify-team/ …
=> VaNotify - Update callback default params

app/controllers/v0/user/mhv_user_accounts_controller.rb, app/services/mhv/user_account/creator.rb, app/services/mhv/user_account/errors.rb, spec/controllers/v0/user/mhv_user_accounts_controller_spec.rb
This passes along the error codes and messages we receive from MHV
```json
{
"errors": [
{
"title": "The server responded with status 400",
"detail": "ICN provided is not the Primary ICN",
"code": "802"
}
]
}
```
- https://jira.devops.va.gov/browse/VI-743
- Difficult to test locally but we can mock a response 
- add this to beginning of lib/mhv/account_creation/service.rb#create_account
```ruby
def create_account(icn:, email:, tou_occurred_at:, break_cache: false)
raise  Common::Client::Errors::ClientError.new("The server responded with status 400", 400, {errorCode: 805, message: "Deactivated Account found in MHV for ICN"} )
...
end
```
- Sign-in
- go to http://localhost:3000/v0/user/mhv_user_account and you should see an error message with the code and message from MHV
```json
{ …
```
=> Add MHV error codes to MHV account error responses

.github/workflows/backend-pr-labeler.yml
- Adding the check-pr-status job from my working branch so that I can test that it works when triggered by Code Checks
- https://github.com/department-of-veterans-affairs/vets-api/pull/19126
=> Add check-pr-status job to BE PR Labeler

.github/workflows/backend-pr-labeler.yml
- The pull request object nested in the workflow run doesn't contain enough info, so this requires making a call to retrieve the whole PR to get the draft status, labels, and teams.
=> Retrieve entire pull_request from workflow_run

app/services/sign_in/session_spawner.rb, spec/services/sign_in/session_spawner_spec.rb, spec/services/sign_in/token_exchanger_spec.rb
- This PR updates the token expirations for a token exchanged session so that it properly expires based off the creation of the new session, not the creation of the original session. This was causing an issue where token expirations were set in the past when an exchanged session happened more than 30 minutes after the creation of the original session
- https://jira.devops.va.gov/browse/VI-739
Authentication - Token Exchange
=> [VI-739] Updating token exchanged session attributes so that exchanged session has proper expiration times

.github/workflows/backend-pr-labeler.yml
- work_flow run was failing because Code Checks runs both on PRs AND pushes to master. Now workflow will exit if there isn't a pull_request, and not throw an error
=> Adjust so worklow_run only performs on PR Code Checks

app/models/saved_claim/burial.rb, spec/models/saved_claim/burial_spec.rb
benefits_claim model function returning nil if last checked value was false
[Trigger Pension and Burial Action Needed email notification](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91426)
burial
=> Burial 91426 SavedClaim::Burial#benefits_claimed returning nil

postman/vets-api.pm-collection.json
As stated by Derek Brown, this endpoint is deprecated and is slated for removal from vets-api.  As such, removing the test from the Postman collection will ensure that no failures occur due to its disuse and eventual removal.
- *This work has been done by the Platform Reliability Team in support of the Product Team*
https://dsva.slack.com/archives/C013VCQKSE7/p1730925246985469
*Nothing user-facing*
=> Remove v0/veteran_confirmation endpoint request and test

config/features.yml
- This PR adds a feature toggle to use to manage traffic to a new endpoint for expanded classification
- The endpoint and logic has not been added, but the feature toggle will be used in future iterations to manage traffic to the endpoint in VRO.
- [#626](https://github.com/orgs/department-of-veterans-affairs/projects/873/views/2?pane=issue&itemId=85258469&issue=department-of-veterans-affairs%7Cvagov-claim-classification%7C626)
*(Describe what parts of the site are impacted and*if*code …
=> adds feature toggle for exanded classification endpoint traffic

modules/claims_api/app/sidekiq/claims_api/report_hourly_unsuccessful_submissions.rb, modules/claims_api/spec/sidekiq/report_hourly_unsuccessful_submissions_spec.rb
* Adjusts error message data type in test, they are saved as an array not a string
* Adjusts test to actually verify the IDs are not included
[API-41807](https://jira.devops.va.gov/browse/API-41807)
modified:   modules/claims_api/app/sidekiq/claims_api/report_hourly_unsuccessful_submissions.rb
modified:   modules/claims_api/spec/sidekiq/report_hourly_unsuccessful_submissions_spec.rb
=> API-41807-adjust-slack-filter-for-correct-error-response

db/migrate/20241112135649_drop_benefits_intake_uuid_index_from_form_submissions.rb, db/migrate/20241112135704_drop_benefits_intake_uuid_from_form_submissions.rb, db/schema.rb
This PR removes the `benefits_intake_uuid` and its index from the `form_submissions` table. This follows up on these two PRs:
1. [Write `benefits_intake_uuid` to `form_submission_attempts` table.](https://github.com/department-of-veterans-affairs/vets-api/pull/19015)
2. [Stop saving `benefits_intake_uuid` to Form Submissions.](https://github.com/department-of-veterans-affairs/vets-api/pull/19169)
https://github.com/orgs/department-of-veterans-affairs/projects/1443/views/3?sliceBy%5Bvalue%5D=Thrillberg&pane=issue&itemId=83134444&issue=department-of-veterans-affairs%7CVA.gov-team-forms%7C1636
=> Drop benefits intake UUID from form submissions

.github/CODEOWNERS, app/controllers/v0/profile/vet_verification_statuses_controller.rb, config/routes.rb, config/settings.yml, lib/lighthouse/veteran_verification/service.rb, spec/controllers/v0/profile/vet_verification_statuses_controller_spec.rb, spec/support/vcr_cassettes/lighthouse/veteran_verification/status/200_person_not_found_response.yml, spec/support/vcr_cassettes/lighthouse/veteran_verification/status/200_show_response.yml
- This work is not behind a feature toggle.
- This change adds a new route and controller to the `V0::Profile` module in the `app/controllers/v0/profile/vet_verification_statuses_controller.rb` file for getting confirmation of a veteran's Title 38 status. This endpoint returns data from the Lighthouse Veteran Service History and Eligibility API `/status` endpoint, which will be used to determine if a veteran is eligible to view their Proof of Status card. A forthcoming vets-website PR will integrate the data returned into the Veteran Proof of Status feature.
- Documentation and further logging will be added in a forthcoming PR.
- [1138](https://github.com/department-of-veterans-affairs/va-iir/issues/1138)
- There is no …
=> Add route and controller for LH API Vet Title 38 Verification

app/sidekiq/decision_review/failure_notification_email_job.rb, app/sidekiq/decision_review/form4142_submit.rb, app/sidekiq/decision_review/submit_upload.rb, lib/decision_review_v1/utilities/constants.rb, spec/sidekiq/decision_review/form4142_submit_spec.rb, spec/sidekiq/decision_review/submit_upload_spec.rb
This adds email notification functionality to the DR jobs when all sidekiq retries are exhausted.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/96419
https://github.com/department-of-veterans-affairs/va.gov-team/issues/94461
Tested locally and via spec test.
`DecisionReview::SubmitUpload` and `DecisionReview::Form4142Submit` jobs, StatsD
=> 96419: Add email notifications for DR jobs sidekiq retries exhausted

app/sidekiq/evss/disability_compensation_form/submit_form0781.rb, app/sidekiq/evss/disability_compensation_form/submit_uploads.rb
- *This work is behind a feature toggle (flipper): 
NO
Ensures the veteran-facing failure mailer we send when a document fails to upload for a Form 526 is the last thing that can raise an exception in an upload job's `sidekiq_retries_exhausted` block. Moves the order of the code in one job and adds a note to two jobs so no new code can get added in this area.
Disability Benefits team 2, we own the maintenance of this component
https://github.com/department-of-veterans-affairs/va.gov-team/issues/96216
=> Prevent Form 526 silent failure logging when failure email is sent

app/controllers/v0/disability_compensation_forms_controller.rb, spec/requests/v0/disability_compensation_form_spec.rb
The PR is a stop-gap fix for a recently encountered [bug](https://github.com/department-of-veterans-affairs/va.gov-team/issues/95368) where somehow users were submitting no NEW or INCREASE disabilities with their 526ez form- even though the frontend explicitly tries to validate against it. Follow up FE fix + investigation ticket for this is [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/96290)
The purpose of this fix is to quickly prevent any such claim from going all the way down the submission path and failing there. The user will still see a very generic error for the time being.
Controller-level code that returns failure before the claim …
=> Raise error if no new or increase disabilities are submitted

app/sidekiq/evss/document_upload.rb, app/sidekiq/lighthouse/document_upload.rb, lib/sentry_logging.rb
The current error message that we get back when there are errors with the request to VANotify don't include any details about why the emails failed. `e.message` only includes the error code and the service name, but doesn't include any further details. The VANotify module does set these things up as extras for Sentry though, so logging the exception to Sentry makes more fine details available to us. I also considered modifying the VANotify module, but that would require making changes to the `Common::Client::Errors::ClientError` class itself which is used across many different modules and may have ramifications that can't be anticipated.
department-of-veterans-affairs/va.gov-team/issues/96884 …
=> [CST] Logging Document upload failure email errors to Sentry

app/sidekiq/central_mail/submit_form4142_job.rb
Ensures the veteran-facing failure mailer we send when a 4142 document fails to upload for a Form 526 is the last thing that can raise an exception in the upload job's `sidekiq_retries_exhausted` block.
(I missed updating this job in [this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/19394), same change)
Disability benefits team 2, yes we own the maintenance
N/A documentation change CI will catch anything
=> Prevent silent failure logging when 4142 mailer is sent

modules/claims_api/app/models/claims_api/auto_established_claim.rb, modules/claims_api/spec/models/auto_establish_claim_spec.rb, modules/claims_api/spec/requests/v1/forms/526_spec.rb
**** [Previous PR](https://github.com/department-of-veterans-affairs/vets-api/pull/19305) *****
- Adds transform method to v1 526 validations to change unitName to be an empty string if it is blank or empty. 
- Adds test for nil and blank unitName.
- [API-41802](https://jira.devops.va.gov/browse/API-41802)
- Postman: v1 526. try sending a blank unitName & a nil unitName
reservesNationalGuardService not provided example:
modified:   modules/claims_api/app/controllers/concerns/claims_api/disability_compensation_validations.rb
modified:   modules/claims_api/spec/requests/v1/forms/526_spec.rb
=> API-41802-unit-name

modules/ivc_champva/app/jobs/ivc_champva/missing_form_status_job.rb
This PR adds a class method to fetch a form object from the DB by UUID. It was previously referenced, but not actually implemented in this class. 
- This work is behind a feature toggle (flipper): **YES**
- Added a class method to get a form from the DB by UUID
- Team: **IVC CHAMPVA**
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/95907
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretoggl …
=> 95907 Add missing class method to failure email logic - IVC CHAMPVA

modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb, modules/simple_forms_api/app/models/simple_forms_api/vba_20_10207.rb, modules/simple_forms_api/app/services/simple_forms_api/form_remediation/submission_archive.rb, modules/simple_forms_api/spec/services/form_remediation/submission_archive_spec.rb
- This PR addresses the issue of document upload errors in the SubmissionArchive service while processing form 20-10207 with attachments.
- Changes include:
- Adding test coverage for file existence checks
- Implementing a guard clause to handle missing files
- Updating the uploads controller to pass the correct attachment file paths instead of UUIDs
- To reproduce the bug, attempt to submit a 20-10207 form with attachments. This should trigger an error during the upload process.
- The solution involves ensuring that the system checks for the existence of the each attachment file before attempting to process it. This prevents errors from occurring when an attachment is missing and provides a clearer error message to the user.
- I work …
=> [SIMPLE-FORMS] fix: submission failures for form 20-10207

modules/simple_forms_api/README.rdoc
- Adds some clarification to the `README` for the `simple_forms_api` module about the setup needed to run the `rails` command locally as well was the path needed by the command to find the appropriate PDF file.
- Ran the `rails` command referenced in the `README` successfully using the new instructions.
It would be nice to be able to run this command using the Docker setup, but that would be a more involved fix.
=> Add note to Simple Forms API README about native setup

app/controllers/v0/health_care_applications_controller.rb, config/features.yml, spec/requests/v0/health_care_applications_spec.rb
- Added a flipper toggle to our `/rating_info` endpoint that allows the endpoint to return a 0 be default instead of calling the underlying BGS service. This will be turned on during a planned BGS outage to prevent calls to the service. Veterans will receive a 0 from this endpoint, but the forms allow them to add their own information later. 
- Flipper toggle `hca_disable_bgs_service`
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/97030
10-10EZ and 10-10EZR
=> [10-10EZ/10-10EZR] Temporarily disable BGS call for the COLA update weekend

.github/workflows/be_review_prs.yml
Sometimes this check runs twice and will be ❌ until you manually re-run it, which is time-consuming and error-prone (sometimes you forget to re-run).
=> remove on pull_request in be_review_prs.yml

app/controllers/v1/sessions_controller.rb, app/models/user.rb
- This PR creates a `UserVerification` object before the `User` object has been persisted on SSOe authentications
- This prevents an issue where a `User` object potentially stored a related (but technically incorrect) `UserVerification` for that authenticated session'
- https://jira.devops.va.gov/browse/VI-762
Authentication
=> [VI-762] Properly managing UserVerification creating during SSOe auth flow

modules/simple_forms_api/app/services/simple_forms_api/form_remediation/file_utilities.rb, modules/simple_forms_api/app/services/simple_forms_api/form_remediation/s3_client.rb, modules/simple_forms_api/app/services/simple_forms_api/form_remediation/submission_archive.rb, modules/simple_forms_api/spec/services/form_remediation/s3_client_spec.rb, modules/simple_forms_api/spec/services/form_remediation/submission_archive_spec.rb
- This pull request updates the S3 client to generate presigned URLs without creating new files or directories, streamlining the file handling and S3 upload logic within the `simple_forms_api` service. It also modifies the date-based file and directory naming conventions to improve efficiency.
- To reproduce the previous behavior, attempt to generate presigned URLs using the existing S3 client, which would create temporary files and directories.
- The solution involves refactoring the S3 client to implement a new method, `retrieve_presigned_url`, which accesses existing archive data directly. This eliminates the need for temporary file generation and consolidates directory naming logic. This approach is chosen for its efficiency and …
=> [SIMPLE-FORMS] fix: updates to S3 presigned URL and directory naming logic

spec/lib/va_profile/demographics/service_spec.rb, spec/lib/va_profile/models/gender_identity_spec.rb, spec/lib/va_profile/models/preferred_name_spec.rb, spec/requests/v0/profile/gender_identities_spec.rb, spec/requests/v0/profile/personal_information_spec.rb, spec/requests/v0/profile/preferred_names_spec.rb
Added `team_owner` and `feature` RSpec tags to the spec files for `personal info`, `preferred name`, `gender identities`, and `service`.
Refer to the [RSpec Tagging Guide](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/tutorials/testing/rspec_tags.md) for more details.
---
- [#96569](https://github.com/department-of-veterans-affairs/va.gov-team/issues/96569)
---
Ran the following command to verify the tags:
```bash
bundle exec rspec spec --tag feature:personal_info
```
Finished in 1.28 seconds
37 examples, 0 failures
=> add team and feature Rspec tags to personal info related files

config/features.yml
Removes the flipper for the search dropdown component that is not longer in use.
[#18336](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18336)
=> VACMS-18336: Remove flipper for search_dropdown_component_enabled

spec/sidekiq/form1010cg/submission_job_spec.rb
- Added `allow(Flipper).to receive(:enabled?).and_call_original`  in a before for the `Form1010cg::SubmissionJob` to ensure any Flipper toggles are stubbed. `SavedClaim::CaregiversAssistanceClaim` was expecting a different flipper toggle to be stubbed and it wasn't, so it was using the stub from the spec that was for a different feature. 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/95897
None
10-10CG Submission Job Spec
=> [10-10CG] Update Form1010cg::SubmissionJob spec to stub all Flipper calls

modules/va_notify/lib/va_notify/service.rb, modules/va_notify/spec/lib/service_spec.rb
> yes
> Before this PR: 
> 
> When creating a VANotify::Notification, if the callback_options Hash included a String value on the key of `metadata`, it would be written to the metadata attribute
>
> example: 
> ```rb
>   # metadata is currently a String datatype
>
>   callback_options = { callback: "String", metadata: "String" }
> ```
>
> After this PR: 
> 
> Since this work is behind a flipper and not in prod yet, we're going to use the new field of
> `callback_metadata` (recently added to the vanotify::notifications table) the intention is to receive a Hash within the callback_options hash (instead of a String) 
> 
> example: 
> ```rb
>   # metadata is currently a …
```
=> Uses new callback_metadata field in VANotify::Notification

modules/simple_forms_api/app/services/simple_forms_api/form_remediation/docs/form_submission_pdf_backups.md
- This PR provides minor changes to the PDF backup documentation which clarify and streamline some of the information.
- I work for the Veteran Facing Forms team, which owns the maintenance of these documents.
- Since this work is not behind a feature toggle, there are no specific success criteria related to a flipper.
- [Improve Documentation Clarity and Organization for PDF Download and Form Remediation](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/1840)
- To verify the changes, reviewers should:
1. Ensure that the PDF download instructions are clearly separated and easy to follow.
2. Confirm that the documentation is accessible and correctly formatted.
- This change impacts the documentation section of …
=> [SIMPLE-FORMS] doc: update form_submission_pdf_backups.md

app/sidekiq/decision_review/saved_claim_status_updater_job.rb, spec/sidekiq/decision_review/hlr_status_updater_job_spec.rb, spec/sidekiq/decision_review/nod_status_updater_job_spec.rb, spec/sidekiq/decision_review/sc_status_updater_job_spec.rb
- Add rescue to status polling job for fetching initial set of records
- Decision Review, yes
https://github.com/department-of-veterans-affairs/va.gov-team/issues/95986
- If fetching the saved claims failed, the entire job would fail and not retry. Now it rescues, logs, and the job will run again in 1 hour
Better error handling for background jobs
=> #95986 rescue db connection error

app/models/user.rb, app/services/users/profile.rb, app/swagger/swagger/schemas/user_internal_services.rb, lib/mpi/models/mvi_profile_identity.rb, lib/mpi/responses/profile_parser.rb, spec/factories/mvi_profiles.rb, spec/factories/users.rb, spec/lib/mpi/responses/profile_parser_spec.rb, spec/models/user_spec.rb, spec/services/users/profile_spec.rb, spec/support/rakelib/users_serialized.json, spec/support/schemas/user_loa1.json, spec/support/schemas/user_loa3.json, spec/support/schemas_camelized/user_loa1.json, spec/support/schemas_camelized/user_loa3.json
- This PR adds the `preferred_name` field to the `/user` serialized response
- This field is sourced from the MPI 'preferred_name' stanza
- https://jira.devops.va.gov/browse/VI-771
Serialized User response
=> [VI-771] Adding preferred name to user serializer, sourced from MPI

modules/claims_api/app/swagger/claims_api/v2/dev/swagger.json, modules/claims_api/config/schemas/v2/power_of_attorney_requests/param/decision/post.json
Add participantId and representativeId to the /decide request body in v2 staging docs. See https://github.com/department-of-veterans-affairs/vets-api/pull/19362 for more.
[API-42062](https://jira.devops.va.gov/browse/API-42062)
Visual inspection.
v2 staging docs.
N/A
=> [API-42062] Update /power-of-attorney-requests/decide docs

lib/lighthouse/veteran_verification/constants.rb, lib/lighthouse/veteran_verification/service.rb, spec/controllers/v0/profile/vet_verification_statuses_controller_spec.rb, spec/lib/lighthouse/veteran_verification/service_spec.rb
- This work is not behind a feature toggle.
- This change adds error message logic to a new route for getting confirmation of a veteran's Title 38 status. This endpoint returns data from the Lighthouse Veteran Service History and Eligibility API `/status` endpoint, which will be used to determine if a veteran is eligible to view their Proof of Status card. If the veteran is found to be ineligible, this change provides more detailed information to display to the user to help them understand why and who to contact to correct it, if they choose.
- Documentation and further logging will be added in a forthcoming PR.
- [1210](https://github.com/department-of-veterans-affairs/va-iir/issues/1210)
- There is no old behavior, as …
=> Add error messaging to Veteran Verification /status endpoint

db/schema.rb, modules/va_notify/db/migrate/20241119031849_applies_modifications_to_va_notify_notifications.rb
> Yes
> Before this PR: 
> - The `va_notify_notifications` table did not have a `callback_klass` field
> - The same table did not have a `template_id` field
> 
> After this PR:
> - The `va_notify_notifications` table will be replacing the `callback` field with the `callback_klass` field to aid in clarity
> - The same table will receive a field of `template_id` as requested to provide additional transparency RE notification statuses
- …
=> Adds new fields to va_notify_notifications

spec/controllers/v0/sign_in_controller_spec.rb
- This PR fixes a flaky spec in the Sign in Controller that was occurring when the spec took a bit longer than expected and the duration field for a log was different than the expected value
=> Fixing flaky spec for sign in controller around duration log

app/models/concerns/form526_claim_fast_tracking_concern.rb, config/settings.yml, lib/virtual_regional_office/client.rb, spec/lib/virtual_regional_office/client_spec.rb, spec/lib/virtual_regional_office/integration/client_spec.rb, spec/sidekiq/evss/disability_compensation_form/submit_form526_all_claim_spec.rb, spec/support/disability_compensation_form/submissions/only_526_mixed_action_disabilities_and_free_text.json, spec/support/vcr_cassettes/virtual_regional_office/expanded_classification.yml
- This adds a new endpoint to the Virtual Regional Office client to perform contention classification using a new method
- The call to the new end point called behind a feature flag that we plan to increase traffic to incrementally to test the response and response time
- https://github.com/orgs/department-of-veterans-affairs/projects/873/views/2?pane=issue&itemId=85258469&issue=department-of-veterans-affairs%7Cvagov-claim-classification%7C626
- Tests are written for the toggle on and off and is based …
=> Implements new endpoint behind feature flag

modules/vye/app/controllers/vye/v1/verifications_controller.rb, modules/vye/spec/controllers/vye/v1/verifications_controller_spec.rb
-  update vye cert_through logic to not include future dates per this logic:
Award August 01 2024 – Dec 15 2024
If the current date is Aug 31 or before Sept 30:
the user should have a cert through date of Aug 31
If the current date is Sept 30 or before Oct 31:
The user should have a cert through date of Sept 30
If the current date is Oct 31 or before Nov 30:
The user should have a cert through date of Oct 31
If the current date is Nov 30 or before Dec 15:
The user should have a cert through date of Nov 30
If the current date is Dec 15 or later
The user should have a cert through date of Dec 15.
The cert through date will always be either the end of a month or during the month, but never in the future. The entire purpose of this …
=> Vebt 674 - VYE update cert_through logic to not include future dates

app/sidekiq/lighthouse/submit_benefits_intake_claim.rb, spec/sidekiq/lighthouse/submit_benefits_intake_claim_spec.rb
This is a change to which date is written to the PDF.  I think we should be writing the created_at date, not now().
I've also cleaned up some code and added comments.
This is **not** behind a flipper.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/97183
=> Change date that is written to the PDF

modules/representation_management/lib/representation_management/v0/pdf_constructor/form_2122a.rb, modules/representation_management/spec/requests/representation_management/v0/pdf_generator_2122a_spec.rb
- *(Summarize the changes that have been made to the platform):* A line that was expecting data was breaking because that data wasn't being sent along yet.  That code now tolerates empty data.
- *(If bug, how to reproduce):* Go through the 2122a appoint a rep flow on staging.
- *(What is the solution, why is this the solution?):* This will allow the 2122a to generate a PDF successfully.
- *(Which team do you work for, does your team own the maintenance of this component?):* FAR/ARM, yes.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/97553
- *Link to epic if not included in …
=> Don't break on empty data

app/controllers/v0/terms_of_use_agreements_controller.rb, app/controllers/v1/sessions_controller.rb, app/services/login/after_login_actions.rb, lib/saml/post_url_service.rb, lib/saml/url_service.rb, spec/controllers/v0/terms_of_use_agreements_controller_spec.rb, spec/controllers/v1/sessions_controller_spec.rb, spec/lib/saml/post_url_service_spec.rb, spec/services/login/after_login_actions_spec.rb
- Skip ssoe after_login MHV account creation for specific clients
- Add skip_mhv_creation_api parameter to ToU redirect for specific clients that  frontend will pass back when accepting ToU
- https://jira.devops.va.gov/browse/VI-740
- https://github.com/department-of-veterans-affairs/vets-website/pull/33008
checkout vi-740 on vets website
- Test logging in with SSOe 
- Change `SKIP_MHV_ACCOUNT_CREATION_CLIENTS` to `[vaweb]`
- Sign In
- It should not have enqueued MHV::AccountCreatorJob http://localhost3000/sidekiq/queues/default 
- Test accepting ToU
- with `SKIP_MHV_ACCOUNT_CREATION_CLIENTS` set to `[vaweb]`
- it should not enqueue a job
ToU, MHV Account Creation,
=> [VI-740] SSOe: add MHV account creation after login

modules/debts_api/lib/debts_api/v0/fsr_form_transform/additional_data_calculator.rb, modules/debts_api/spec/lib/debt_api/v0/fsr_form_transform/additional_data_calculator_spec.rb
[We are seeing "invalid date" errors](https://vagov.ddog-gov.com/error-tracking?query=service%3Afinancial-report&fromUser=false&issueId=89f0ea06-8857-11ef-9c0a-da7ad0900007&refresh_mode=sliding&source=all&from_ts=1731283175451&to_ts=1731887975451&live=true) in our 5655 financial status report form.
This PR captures the error, logs the input and returns a default
- *(Summarize the changes that have been made to the platform)*: This captures the invalid date data, logs the input for investigation, and returns a default value.
- *(If bug, how to reproduce)*: I've added tests that submit a non-parsable piece of data, handles the particular error, and logs the input.
- *(What is the solution, why is this the solution?)*: I've …
=> 97295 Debt team - invalid date

docs/setup/betamocks.md
Removes EVSS::PCIUAddress from Betamocks setup as part of EVSS PCIU migration epic.
[Github Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/79044)
- Passes all specs. 
Betamocks setup cleanup.
=> Remove PCIUAddress from Betamocks setup

app/controllers/v0/my_va/submission_statuses_controller.rb, config/features.yml, spec/requests/swagger_spec.rb, spec/requests/v0/my_va/submission_statuses_spec.rb
This PR removes the `my_va_form_submission_statuses` feature toggle from config list
- ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/94831
- cleanup PR on `vets-website`: https://github.com/department-of-veterans-affairs/vets-website/pull/33081 …
=> remove my_va_form_submission_statuses feature flag

app/sidekiq/decision_review/sc_status_updater_job.rb, lib/decision_review_v1/appeals/supplemental_claim_services.rb, spec/lib/decision_review_v1/service_spec.rb, spec/sidekiq/decision_review/sc_status_updater_job_spec.rb
- was :uuid, now :guid
- to match get_notice_of_disagreement_upload for easier code sharing and shared testing
https://github.com/department-of-veterans-affairs/va.gov-team/issues/96645
- Changed one named argument from :uuid to :guid
DecisionReviewV1::Appeals::SupplementalClaimServices
=> Rename argument in get_supplemental_claim_upload

modules/mobile/app/models/mobile/v0/user_accessible_services.rb, modules/mobile/spec/models/user_accessible_services_spec.rb, modules/mobile/spec/requests/mobile/v0/user/authorized_services_spec.rb
remove authorization of appointments if no facilities
https://github.com/department-of-veterans-affairs/va-mobile-app/issues/9903 …
=> remove authorization of appointments if no facilities

spec/controllers/v0/sign_in_controller_spec.rb
- More spec failures due to 'authentication time' when specs take a while to complete
=> Fixing flaky sign in controller specs (again)

spec/sidekiq/decision_review/hlr_status_updater_job_spec.rb
- Refactor only: Use shared examples in HLR job spec
https://github.com/department-of-veterans-affairs/va.gov-team/issues/96645
-The same setup and behavior tests were duplicated for each of the three subclasses that implements the base job. This applies the shared examples to one (HLR) of three spec files
- Break the job, ensure tests fail as expected
Refactor tests for the `nod_status_update_job.rb`
=> Dr hlr status update use shared examples

app/services/mhv/user_account/creator.rb
- This PR resets the MPI cache when the MHV User Account API is completed
- https://jira.devops.va.gov/browse/VI-694
Authentication
=> [VI-694] Recache MPI when MHV User Account API runs

modules/simple_forms_api/app/models/simple_forms_api/vba_20_10206.rb, modules/simple_forms_api/lib/simple_forms_api.rb
This PR handles scrubbing error messages for 20-10206 so that we can still glean _something_ from the message without it revealing PII.
https://github.com/orgs/department-of-veterans-affairs/projects/1443/views/3?sliceBy%5Bvalue%5D=Thrillberg&pane=issue&itemId=88138715&issue=department-of-veterans-affairs%7CVA.gov-team-forms%7C1874
=> Handle 20-10206 error message scrubbing

.github/workflows/code_checks.yml
When tests run successfully (whether they pass or fail), they finish in 6-8 minutes. But for the past couple months, we've seen tests hit the timeout–not because tests are still running–things just stall out. Ticket to address the root cause is linked below. 
I've never seen the database take much time at all (< a few min). We could decrease the tests more if we want 🤷 
- To actually resolve the issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/97560
code checks in CI
=> Decrease timeouts in code checks

app/models/concerns/form526_claim_fast_tracking_concern.rb
- Fixes conditional on log statement. Current bug is already rescued.
- On submission of 526 form, we attempt to check flashes to see if it includes a particular flash on the claim.
- I'm on the Employee Experience team; we work with the Disability Experience team which maintains Form 526.
- [Ticket](https://github.com/department-of-veterans-affairs/abd-vro/issues/3710)
- bug introduced in this [PR](https://github.com/department-of-veterans-affairs/vets-api/pull/19485)
- Old behavior incorrectly uses `includes?` on array instead of `include?`
* no user functionality is affected
(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you …
=> Fix typo in else

modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb, modules/simple_forms_api/app/services/simple_forms_api/intent_to_file.rb, modules/simple_forms_api/lib/simple_forms_api.rb, modules/simple_forms_api/spec/services/intent_to_file_spec.rb
This PR fixes something which we believed already works (but doesn't). This PR explicitly raises a new exception, `SimpleFormsApi::Exceptions::BenefitsClaimsApiDownError`, when we fail to create an intent to file with the Intent API. Tests are updated a little refactored.
https://github.com/orgs/department-of-veterans-affairs/projects/1443/views/3?sliceBy%5Bvalue%5D=Thrillberg&pane=issue&itemId=88585252&issue=department-of-veterans-affairs%7CVA.gov-team-forms%7C1883
=> Offramp 21-0966 to PDF route when Intent API is down

config/settings/production.yml
- Some settings values in environment helm charts are hardcoded and the same in each environment
- Those values can be moved to `config/settings/production.yml` in vets-api
- production refers to the RAILS_ENV which is "production" in preview environments, dev, staging, sandbox, and production
- This is part 1 of 2
**Note**: these values will still be overridden by settings.local.yml from the environment helm charts until they are removed.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/97711
- Part 2: https://github.com/department-of-veterans-affairs/vets-api/pull/19605
- Original List: https://docs.google.com/spreadsheets/d/1-7PLskyY67b4J1fsk-FADYxnSN1UrmVziFfFIt_1saU/edit?gid=697038896#gid=697038896
Manifest PRs:
- …
=> Move Hardcoded Settings to vets-api - Part 1

config/settings/production.yml
- Some settings values in environment helm charts are hardcoded and the same in each environment
- Those values can be moved to `config/settings/production.yml` in vets-api
- production refers to the RAILS_ENV which is "production" in preview environments, dev, staging, sandbox, and production
- This is part 2 of 2
**Note**: these values will still be overridden by settings.local.yml from the environment helm charts until they are removed. PRs for the environment helm charts have not yet been created
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/97711
- Part 1: https://github.com/department-of-veterans-affairs/vets-api/pull/19604
- Original List: https://docs.google.com/spreadsheets/d/1-7PLskyY67b4J1fsk-FADYxnSN1UrmVziFfFIt_1saU/edit?gid=697038896#gid=697038896
=> Move Hardcoded Settings to vets-api - Part 2

config/features.yml
- Adds a single toggle to enable experimental work for the Authenticated Experience Design Patterns team
- https://github.com/department-of-veterans-affairs/tmf-auth-exp-design-patterns/issues/196
- tested locally. Just adding a single flag
No impact to current site. Adding flag, to this and FE for work that will only live on staging
=> add aedp_VADX feature toggle

config/features.yml
adds feature flag for grouping
[Create feature flag for medication grouping work](https://jira.devops.va.gov/browse/MHV-64023)
none
=> [mhv-64023] added grouping feature to teature.yml file.

app/controllers/v0/disability_compensation_forms_controller.rb
- add missing `separationLocationCode` path
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/97956
=> dbex/97956-separation-location-string: separation location code to string

modules/debts_api/app/controllers/debts_api/v0/financial_status_reports_controller.rb
- *This work is behind a feature toggle (flipper): YES/NO*: No
- *(Summarize the changes that have been made to the platform)*: We have a bug where expected parameters are not getting sent into vets-api due to them not being listed in strong parameters
- *(If bug, how to reproduce)*: We've been submitting forms via vets-website. We confirmed that the values are populating as intended now.
- *(What is the solution, why is this the solution?)*: Params needed to be accepted to move them along to our services.
- *(Which team do you work for, does your team own the maintenance of this component?)*: debt-resolution. You can find me on the Octo slack at #debt-resolution. We own this code.
- *Link to ticket created …
=> 97625 Debt Team FSR missing housing expenses

config/betamocks/services_config.yml, config/settings.yml, lib/gi/search_client.rb, lib/gi/search_configuration.rb
- *(Summarize the changes that have been made to the platform)*: App and betamocks settings updated to enable mock data for `GI::SearchClient` endpoints for comparison tool. `GI::SearchClient` and `GI::SearchConfiguration` updated to only use mocks on a request to `institution_programs` search endpoint when a query parameter of `type == 'FLGT'` is present
- *(What is the solution, why is this the solution?)* Temporarily solution to test new GI Comparison Tool feature until flight program data is made available via WEAMS, which is being worked in parallel. There didn't appear to be a way in betamocks settings to only mock responses if a specific query parameter is passed in, while letting all other …
=> EDM-346/enable gids flight school mocks

modules/ivc_champva/app/controllers/ivc_champva/v1/uploads_controller.rb, modules/ivc_champva/app/services/ivc_champva/attachments.rb, modules/ivc_champva/spec/requests/ivc_champva/v1/forms/uploads_spec.rb
This PR fixes an issue with how attachment metadata is prepared before being sent to Pega for ingestion. Previously, the document types (`attachment_id`, e.g.: 'Birth certificate') were rolled into a list based solely on the order of the front end configuration.
These values were then matched up with the list of attachments in the cache on the backend. However, if a user uploaded files in any order other than the order in which they encounter them, the alignment between attachment_id and the file itself would be thrown off. This caused files to be mis-categorized.
By reorganizing the `attachment_id` array to match with the order files were uploaded, metadata gets matched correctly regardless of how the user uploaded their files.
- Matches supporting docs up to database records and sorts …
=> 96358 Fix for out of order attachment ids - IVC CHAMPVA forms

modules/claims_api/app/swagger/claims_api/v1/swagger.json, modules/claims_api/config/schemas/v1/2122.json, modules/claims_api/config/schemas/v1/526.json
_⚠️ Please do not merge until December 2 or later_
In v1 docs:
- Update state to include province in /2122 and /526 endpoints
- Update country to US (instead of USA) in /2122 endpoint
[API-42380](https://jira.devops.va.gov/browse/API-42380)
- Visual inspection
**526**
**2122**
v1 docs
Do we want to update /2122 serviceOrganization state and country (not listed in ticket)?
=> update state and country v1 docs

modules/debts_api/app/controllers/debts_api/v0/digital_disputes_controller.rb, modules/debts_api/app/models/debts_api/v0/digital_dispute.rb, modules/debts_api/spec/models/debt_api/v0/digital_dispute_spec.rb, modules/debts_api/spec/requests/debts_api/v0/digital_disputes_spec.rb
- *This work is behind a feature toggle (flipper): YES/NO": NO
- *(Summarize the changes that have been made to the platform)*: This connects the DigitalDispute model to the Digital Dispute controller. This feature is not accessible to the user currently, we are waiting on our partner DMC to provide an endpoint for our submissions.
- *(What is the solution, why is this the solution?)*: We are working on getting small timely PR's in in preparation for feature launch. We may end up changing some of this as frontend code settles in.
- *(Which team do you work for, does your team own the maintenance of this component?)*: Debt Resolution. You can find me on Octo Slack at #debt-resolution
- *(If introducing a flipper, what is the success criteria being …
=> 97958 Debt team - connect digital disupte endpoint to model

modules/simple_forms_api/app/services/simple_forms_api/notification_email.rb, modules/simple_forms_api/spec/services/notification_email_spec.rb
This PR catches a few more error cases where we are currently just silently `return`ing out. We should instead be incrementing a `silent_failure` StatsD metric, so this PR does that.
=> Catch more errors in NotificationEmail

config/features.yml, modules/ivc_champva/app/controllers/ivc_champva/v1/pega_controller.rb, modules/ivc_champva/app/services/ivc_champva/file_uploader.rb, modules/ivc_champva/lib/ivc_champva/monitor.rb, modules/ivc_champva/spec/services/monitor_spec.rb
- Adds new logging class based on `ZeroSilentFailures::Monitor`
- Adds logging in two locations
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/96605
Example of the submission log:
IVC CHAMPVA forms
NA
=> 96605 Add new monitoring for form submits and Pega updates - IVC CHAMPVA Forms

modules/simple_forms_api/app/services/simple_forms_api/notification_email.rb, modules/simple_forms_api/spec/services/notification_email_spec.rb
This PR uses the `callback_metadata` key when we send an email from Simple Forms and do NOT have an email from the form data but we do have one from the `user_account`.
=> Use the callback_metadata key when we send an email to a user_account

modules/claims_api/app/mailers/claims_api/submission_report_mailer.rb, modules/claims_api/lib/claims_api/cid_mapper.rb, modules/claims_api/spec/mailers/report_monthly_submissions_spec.rb
- Add recipients to monthly email report
- Add consumer to CID-consumer mapping
- [API-42992](https://jira.devops.va.gov/browse/API-42992)
- [API-43008](https://jira.devops.va.gov/browse/API-43008)
N/A
- Monthly claims API email report recipients
- CID mapper
N/A
=> [API-42992][API-43008] Add recipients and consumer to email report

app/controllers/v0/disability_compensation_forms_controller.rb, app/models/concerns/form526_claim_fast_tracking_concern.rb, app/models/form_profiles/va_526ez.rb, lib/disability_compensation/providers/rated_disabilities/evss_rated_disabilities_provider.rb, lib/disability_compensation/providers/rated_disabilities/lighthouse_rated_disabilities_provider.rb, lib/lighthouse/service_exception.rb, lib/lighthouse/veteran_verification/service.rb
- this adds a way to be able to see where the Lighthouse rated disabilities provider is failing: 526 versus some other invoker. 
- datadog query: `@payload.invoker:*` (or a targeted value)
- can be used by other apps that use the `Lighthouse::ServiceException` class if wanted :)
- [#97336](https://github.com/department-of-veterans-affairs/va.gov-team/issues/97336)
- testing in datadog for the invoker payload
n/a
=> DBEX/97336: `Lighthouse::ServiceException` handler send invoker payload to Rails Logger

config/settings/production.yml
- Unintentionally added `check_in/authentication/max_auth_retry_limit`
- n/a
=> Remove max_auth_retry_limit from production.yml

modules/ivc_champva/app/controllers/ivc_champva/v1/pega_controller.rb
Log ZSF for IVC forms
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/logging-silent-failures.md
Use this log message when your team has identified a silent failure AND has made that failure known to the user via an email notification via VA Notify.
=> add silent failure log

modules/claims_api/app/services/claims_api/power_of_attorney_request_service/create_request.rb, modules/claims_api/app/services/claims_api/power_of_attorney_request_service/terminate_existing_requests.rb
- Parallelize BGS calls (proof of concept)
- Memoize BGS services
```mermaid
sequenceDiagram
CreateRequest->>VnpProcServiceV2: vnp_proc_create
VnpProcServiceV2->>CreateRequest: vnp_proc_id
par
CreateRequest->>VnpProcFormService: vnp_proc_form_create(vnp_proc_id)
VnpProcFormService-->VnpProcFormService: create
and
CreateRequest->>VnpPtcpntService: vnp_ptcpnt_create(vnp_proc_id)
VnpPtcpntService->>CreateRequest: Veteran vnp_ptcpnt_id
end
par create_vonapp_data
CreateRequest->>VnpPersonService: vnp_person_create(vnp_proc_id, vnp_ptcpnt_id)
VnpPersonService-->VnpPersonService: create
and
CreateRequest->>VnpPtcpntAddrsService: vnp_ptcpnt_addrs_create(vnp_proc_id, vnp_ptcpnt_id, 'Mailing')
VnpPtcpntAddrsService-->VnpPtcpntAddrsService: create
and
CreateRequest->>VnpPtcpntAddrsService: …
```
=> [API-37025] Parallelize BGS calls in /power-of-attorney-request creation (POC)

app/sidekiq/lighthouse/poll_form526_pdf.rb
- uses `get_first_name` method on the submission in the polling job to ensure first name is found
- [#97221](https://github.com/department-of-veterans-affairs/va.gov-team/issues/97221)
n/a
*(Describe what parts of the site …
=> dbex/received-email-first-name: use `submission.get_first_name` method

modules/ivc_champva/app/jobs/ivc_champva/missing_form_status_job.rb, modules/ivc_champva/lib/ivc_champva/monitor.rb, modules/ivc_champva/spec/jobs/missing_form_status_job_spec.rb, modules/ivc_champva/spec/services/monitor_spec.rb
This PR updates the logging surrounding Pega status failure notification emails to use the new ZSF monitor class. Logs are also now configured to send to the watchtower [ZSF dashboard](https://vagov.ddog-gov.com/dashboard/n6c-twn-swr/silent-failure-tracker?fromUser=false&refresh_mode=sliding&from_ts=1725290886762&to_ts=1733243286762&live=true).
- Updates logging calls to use the new ZSF monitor class
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/98326 …
=> 98326 Update ZSF logging - IVC CHAMPVA forms

lib/lighthouse/veteran_verification/constants.rb, lib/lighthouse/veteran_verification/service.rb, spec/lib/lighthouse/veteran_verification/service_spec.rb, spec/support/vcr_cassettes/lighthouse/veteran_verification/status/200_error_response.yml, spec/support/vcr_cassettes/lighthouse/veteran_verification/status/200_more_research_required_response.yml
- This change adds new not_confirmed_reason logic in the error messaging generation for the Veteran Verification service. There were new not_confirmed_reasons shared with our team by the Lighthouse API team, so we needed to make sure that we supplied useful messaging to the user when those reasons are returned from the LH API. This work is not behind a feature toggle as the endpoint is brand new and not currently being used by any frontend.
- I am on the IIR Product team and we own the Veteran Status Card feature.
- [1248](https://github.com/department-of-veterans-affairs/va-iir/issues/1248)
- There is no old behavior as this is a brand new endpoint and new logic for the error messaging.
N/A
(OPTIONAL)_What should the …
=> Add new not_confirmed_reason logic to error messaging generation

lib/saml/url_service.rb
- This PR adds 'custom' to the list of terms of use redirected clients that will not trigger the MHV Account creation API
- https://jira.devops.va.gov/browse/VI-740
Authentication
=> [VI-740] Skipping MHV Account Creation API for custom authentication when user must accept terms of use

.github/CODEOWNERS, lib/lighthouse/benefits_education/amendment.rb, spec/factories/gi_bill_status_response.rb, spec/serializers/post911_gi_bill_status_serializer_spec.rb
- *(Summarize the changes that have been made to the platform)*: `v1/post911_gi_bill_status` has been incorrectly serializing nested amendment objects. Key mapping added to transform keys in line with similar key mapping for parent [enrollment object](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/lighthouse/benefits_education/enrollment.rb)
- *(If bug, how to reproduce)* Enrollment history has been removed from SOB frontend. But you can test by logging into staging as vets.gov.user+0@gmail.com, and then in separate window hitting [staging-api](https://staging-api.va.gov/v1/post911_gi_bill_status). Nested amendment object will contain null values except for yellow_ribbon_amount, which has correct key
- …
=> EDM/Fix mismatched amendment keys for Post-911 SOB

modules/banners/spec/sidekiq/banners_update_all_job_spec.rb
- *This work is behind a feature toggle (flipper):* YES, the banner api and it's related jobs are, this PR contains only tests 
- This adds unit tests to cover the `Banners::UpdateAllJob`
- Sitewide team
- Addition of job: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19452
- Issue that prompted this work: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19943
- This new spec covers the `Banners::UpdateAllJob`
Banners related CI testing
=> [VACMS-19943]Add tests to cover the UpdateAll Banners job

app/sidekiq/decision_review/failure_notification_email_job.rb, app/sidekiq/decision_review/saved_claim_status_updater_job.rb, spec/sidekiq/decision_review/failure_notification_email_job_spec.rb, spec/sidekiq/decision_review/shared_examples_for_status_updater_jobs.rb
This removes an incremented `silent_failure` metric from the SavedClaim updater jobs.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/98062
Manually testing and spec tests
This impacts the SavedClaim status updater jobs and StatsD metrics.
=> 98062: Remove silent_failure increment from SavedClaim updater jobs

app/models/appeal_submission.rb, spec/sidekiq/decision_review/failure_notification_email_job_spec.rb, spec/sidekiq/decision_review/form4142_submit_spec.rb, spec/sidekiq/decision_review/submit_upload_spec.rb
This PR removes the usage of `VAProfile::ContactInformation::Service.get_person` to obtain the Veteran's email when sending out failure notification emails as emails are provided as part of the form submission.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/97918
Tested locally and spec tests
Email address is saved in the DR SavedClaim models so that can be used instead of calling `VAProfile::ContactInformation::Service.get_person`.
The impacted parts of the site are sidekiq jobs: FailureNotificationEmailJob, Form4142Submit job, and SubmitUpload job
=> 97918: Update email retrieval for DR email notifications

lib/lighthouse/veteran_verification/constants.rb, lib/lighthouse/veteran_verification/service.rb, spec/lib/lighthouse/veteran_verification/service_spec.rb
- This change adds statsd monitoring and some logging to a brand new endpoint that is not hooked up to any frontend.
- I am on the IIR Product team and we own the Veteran Status Card feature.
- [1254](https://github.com/department-of-veterans-affairs/va-iir/issues/1254)
- No old behavior as this is a new endpoint.
N/A
=> Add Vet Verification Status logging and monitoring capabilities

config/initializers/filter_parameter_logging.rb
-  allow startedFormVersion value in request params
- this is not sensitive data, it merely lets us know which version of the form the user started on
- so we'd like to see the true value of `startedFormVersion`  in the request params
- *Tests need to be written for both the flipper on and …
=> DBEX: allow startedFormVersion value in request params

modules/ivc_champva/app/controllers/ivc_champva/v1/uploads_controller.rb
This PR fixes a bug that was producing an off-by-one count of attached supporting documents in certain IVC forms.
Previously, the logic that checked if an overflow PDF was needed would give incorrect results due to the expectation that every form that contains additional attachments also contains an `applicants` array.
**Fix**
The fix is to make sure that `applicant_rounded_number` is always at least 1 (since we always have one applicant, whether the `applicants` array is present or not).
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/98315
- Manual testing
- Previously, forms that included attachments but did not have an `applicants` array would skip adding the first attachment to the database. After this fix, all files are accounted for in the DB.
- To verify
- …
=> 98315 Fix off-by-one error in supporting file counts - IVC CHAMPVA forms

config/settings.yml
- adds an example of brd settings staging api key to match [infra ](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/3304)
- department-of-veterans-affairs/va.gov-team#98103
_Note: …
=> DBEX/98103: add lighthouse staging api key to settings example

modules/banners/app/models/banner.rb, modules/banners/lib/banners/profile/vamc.rb, modules/banners/spec/models/banner_spec.rb
- This adjusts the `Banner.by_path` scope to be able to find subpages of a banner with more complex path's
- Try to fetch a clinic's banner from the API, you will find with exact path matches things work well, but not when getting into specific paths
- This makes the matching a bit more flexible by working off the root piece of the path to indicate the location being observed by a user
- Also includes an update to the profile mapping to correct typo for subpage inheritance
- Sitewide team (Facilities)
- Issue that lead to finding this work: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19842
- Original ticket introducing `Banner.by_path`: https://github.com/department-of-veterans-affairs/vets-api/pull/19088
- …
=> [VACMS-19842]Fix the ability to find banners via subpage inheritance

db/migrate/20241204221534_add_indexes_to_saved_claims.rb, db/schema.rb
This adds indexes to SavedClaim to help address slow queries and query timeouts for the Decision Review sidekiq jobs.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/98402
Tested locally
This adds new indexes to the `saved_claims` table.
=> 98402: Add indexes to SavedClaim for Decision Review sidekiq job queries

db/migrate/20241204221534_add_indexes_to_saved_claims.rb, db/schema.rb
Reverts department-of-veterans-affairs/vets-api#19758
```
{"host":"db-migrate-x2gnk","application":"vets-api-server","environment":"production","timestamp":"2024-12-09T18:01:16.816662Z","level":"info","level_index":2,"pid":1,"thread":"12280","named_tags":{"dd":{"env":"eks-prod","service":"vets-api","version":"77c9d4e2940998547f03a1b86d3e0c2aeccc31b6","trace_id":"0","span_id":"0"},"ddsource":"ruby"},"name":"ActiveRecord::Base","message":"Migrating to AddIndexesToSavedClaims (20241204221534)"}
== 20241204221534 AddIndexesToSavedClaims: migrating ==========================
-- add_index(:saved_claims, [:metadata, :type], {:where=>"(metadata LIKE '%error%')", :name=>"idx_saved_claims_partial_metadata_like_error_and_type", :algorithm=>:concurrently})
bin/rails aborted!
StandardError: An error …
```
=> Revert "98402: Add indexes to SavedClaim for Decision Review sidekiq job queries"

app/sidekiq/evss/disability_compensation_form/submit_form526.rb, spec/sidekiq/evss/disability_compensation_form/submit_form526_all_claim_spec.rb
- *This work is behind a feature toggle (flipper): YES and NO*
- switching out the legacy error handler with the new lighthouse statuses that we retry on in preparation for 100% lighthouse
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/98283
- errors are categorized by "non-retryable", such as a validation error (422) versus a retryable, such as bad gateway (502)
- now we are handling more retryable situations, such as a service being down, for all service calls during the primary form 526 submission path
n/a
=> DBEX/98283: update retryable error handler for lighthouse requests

modules/claims_api/app/clients/claims_api/bgs_client/definitions.rb, modules/claims_api/spec/lib/claims_api/find_definition_spec.rb
- Removes unneeded methods and tests for standard data web service.
- [API-42924](https://jira.devops.va.gov/browse/API-42924)
modified:   modules/claims_api/app/clients/claims_api/bgs_client/definitions.rb
modified:   modules/claims_api/spec/lib/claims_api/find_definition_spec.rb
=> API-42924-standard-web-service

spec/services/users/services_spec.rb
Removed unnecessary logging. 
https://jira.devops.va.gov/browse/MHV-64980
> ### Back end logging cleanup
none needed
no UI changes
mhv medical records
logging removed
=> MHV-64980: Logging cleanup

config/features.yml
Add the `lighthouse_claims_api_v2_add_person_proxy` feature flag.
[API-42374](https://jira.devops.va.gov/browse/API-42374)
N/A
N/A
Feature flags.
N/A
=> [API-42374] Add add_person_proxy feature flag

app/sidekiq/form1095/new1095_bs_job.rb
The 1095-B background job, which imports 1095-B records from files added by the enrollment system to S3, has been failing for a very long time. The underlying issues are a nil method error and failure to require a method that is required
https://github.com/department-of-veterans-affairs/va-iir/issues/1284
I tested this by modifying the test data and ensuring that this edge case passes. I did not write new tests for this because these are integration tests and it didn't feel appropriate to test every variation of the data model. There is already a test case 'does not save invalid forms from S3 file'. This is effectively covered by that case. 
It only impacts this cron job that runs in the background once per day. There is no broader impact
=> 1284 1095 b job errors

config/features.yml
- Adds a new feature toggle for the front-end confirmation page updates
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/95585
Burials
=> Add confirmation page toggle

.github/CODEOWNERS, app/models/accredited_individual.rb, app/models/form526_submission.rb, app/models/form526_submission_remediation.rb, app/models/schema_contract/validation.rb, app/models/terms_of_use_agreement.rb, modules/debts_api/app/models/debts_api/v0/form5655_submission.rb, modules/representation_management/app/models/representation_management/flagged_veteran_representative_contact_data.rb, modules/vye/app/models/vye/address_change.rb, modules/vye/app/models/vye/award.rb, modules/vye/app/models/vye/verification.rb
- Fixes the following warning: `DEPRECATION WARNING: Defining enums with keyword arguments is deprecated and will be removed in Rails 8.0.`
- more details [here](https://sparkrails.com/rails/2024/02/04/rails-7-adds-new-enum-syntax.html)
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/98790
=> [VETS-API] Fix Rails 8 Deprecation warnings

modules/vaos/app/controllers/vaos/v2/clinics_controller.rb
- We're adding some logging to better track the responses provided by the new recent clinic endpoint
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/98519
- Ensured existing unit tests pass
N/A
=> Add logging for recent clinic details

app/controllers/v0/disability_compensation_in_progress_forms_controller.rb
- *This work is behind a feature toggle (flipper): NO* behind a rescue
- logs form version from the retrieval of IPF and prefill
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/97932 …
=> DBEX/97932: log started form version in show action

app/models/concerns/form526_claim_fast_tracking_concern.rb
- Lighthouse open claims implementation returns everything in a list
- we only filter by certain statuses from the LH Provider 
- `FILTERED_STATUSES = %w[CANCELED ERRORED PENDING].freeze`
- this removes the COMPLETED claims from the "open_claims" list, as those EPs are not "pending" for the "pending_eps?" check
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/97336 …
=> DBEX/97336: filter complete claims from open claims list

modules/claims_api/app/swagger/claims_api/v1/swagger.json, modules/claims_api/config/schemas/v1/2122.json, modules/claims_api/spec/requests/v1/forms/2122_spec.rb
- Update v1 2122 schema to require `zipFirstFive` if and only if `country` is `'US'`. Apply to addresses on:
- `veteran`
- `claimant`
- `serviceOrganization`
- Change 'Zipcode' to 'Zip code' for the above descriptions (including `zipLastFour`).
- Update v1 docs
[API-43040](https://jira.devops.va.gov/browse/API-43040)
- Manual submissions to /v1/forms/2122 with all combinations of `country` and `zipFirstFive`.
v1 2122 schema and docs
N/A
=> [API-43040] POA v1 - Conditionally require zip for US

config/features.yml, modules/ivc_champva/app/controllers/ivc_champva/v1/uploads_controller.rb, modules/ivc_champva/spec/requests/ivc_champva/v1/forms/uploads_spec.rb
*This work is behind a feature toggle (flipper): YES
This PR fixes a bug in our program. In a very small sample of users, an IVC CHAMPVS form user will occasionally get a 500 error message and will not able to submit the complete form. This is caused by the temporary multi-stamp file being deleted in the kubernetes pod before the vets-api pdf filler completes. This PR will allow a retry of the multi stamp creation if the file is missing.
https://github.com/department-of-veterans-affairs/vets-api/pull/19006
https://github.com/department-of-veterans-affairs/vets-api/pull/19662
User story:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/97231
- [x ] *New code is covered by unit tests*
- *If this work is behind a flipper:* YES …
=> recreate missing files

lib/periodic_jobs.rb
Engine migration: start running both the engine version and original version of scheduled jobs. They should behave identically, with no duplication of behavior.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/98352
Only the original version of jobs ran. If this works without errors, the old versions will be removed and only the engine version will run. …
=> Decision Reviews: Add Engine Sidekiq Jobs to Schedule

config/settings.yml, modules/ivc_champva/app/controllers/ivc_champva/v1/pega_controller.rb, modules/ivc_champva/app/jobs/ivc_champva/missing_form_status_job.rb, modules/ivc_champva/app/services/ivc_champva/email.rb, modules/ivc_champva/lib/ivc_champva/monitor.rb, modules/ivc_champva/spec/jobs/missing_form_status_job_spec.rb, modules/ivc_champva/spec/services/email_spec.rb, modules/ivc_champva/spec/services/monitor_spec.rb
This PR adds an email trigger to alert the downstream Pega service when we've fired a ZSF email off to a user. It lets the Pega team keep abreast of any issues to which users have been alerted.
- Adds logic to send Pega an email
- Adds new logging metrics to the `IvcChampva::Monitor` class
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/95915
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Feature …
=> 95915 Add pega notification email workflow - IVC CHAMPVA forms

config/features.yml
- This PR adds a feature toggle for the Veteran Status card feature to use the Lighthouse API instead of the Profile API. This will help our team implement on the frontend and test out this new API integration.
- The success criteria targeted is to make sure that we receive the same access rate or better for known test users when trying to view their Vet Status card.
- The companion vets-website PR is [here](https://github.com/department-of-veterans-affairs/vets-website/pull/33392).
- [1264](https://github.com/department-of-veterans-affairs/va-iir/issues/1264)
- This change only includes adding a new feature toggle.
This change only includes adding a new feature toggle. …
=> Create feature toggle for frontend LH implementation

modules/vaos/app/services/eps/appointment_service.rb, modules/vaos/app/services/eps/base_service.rb, modules/vaos/spec/services/eps/appointment_service_spec.rb
Minor update to use current user's ICN to call EPS methods, rather than requiring a patient_id be passed in as argument.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/96412
=> 96412 use current user's icn for calling EPS methods

db/migrate/20241209231104_add_indexes_to_saved_claims.rb, db/schema.rb
This adds indexes to SavedClaim to help address slow queries and query timeouts for the Decision Review sidekiq jobs.
This PR addresses an issue with an index added in #19758 which blocked production deploys so it was reverted in #19790. The previous index erroneously used a large text field as the column for the index key, and is now using the column id instead.
`PG::ProgramLimitExceeded: ERROR: index row size 3064 exceeds btree version 4 maximum 2704 for index "idx_saved_claims_partial_metadata_like_error_and_type"`
https://github.com/department-of-veterans-affairs/va.gov-team/issues/98402
#19758
#19790
Tested locally and manually in staging
This impacts the `saved_claims` table.
=> 98402: Add partial index and delete_date index to SavedClaim for DR sidekiq job queries

db/migrate/20241209231104_add_indexes_to_saved_claims.rb
- Prevents migration errors caused by duplicate index creation in dev/staging
=> chore: Check for existence of saved_claims indexes before creating

modules/vaos/app/services/vaos/v2/appointments_service.rb, modules/vaos/spec/services/v2/appointment_service_spec.rb
This aligns backend with frontend by adding an extra check on If an appointment is cancellable based on if it's in the past
https://github.com/department-of-veterans-affairs/va-mobile-app/issues/10326
Added extra test to ensure the change flips the boolean
=> Mobile: Add past? as a parameter to if the appointment is cancellable

config/features.yml, modules/mobile/spec/requests/mobile/v0/appointments/vaos_v2_spec.rb, modules/vaos/app/services/vaos/v2/appointment_provider_name.rb
appointments - parse out correct id when bad provider data is given
https://github.com/department-of-veterans-affairs/va-mobile-app/issues/10341
(OPTIONAL)_What should the …
=> appointments - parse out correct id when bad provider data is given

modules/decision_reviews/spec/sidekiq/engine_shared_examples_for_status_updater_jobs.rb, modules/decision_reviews/spec/sidekiq/hlr_status_updater_job_spec.rb, modules/decision_reviews/spec/sidekiq/nod_status_updater_job_spec.rb, modules/decision_reviews/spec/sidekiq/sc_status_updater_job_spec.rb
Fixing flaky tests, no implementation changes
Flaky tests. Run `bundle exec rspec --color spec/sidekiq/decision_review/*  modules/decision_reviews/spec/sidekiq/*` to trigger
- sometimes file load order during test was causing shared examples in the module to overwrite shared examples in the main app, or vice versa. No longer sharing names
No ticket
Shared examples in main app and module had the same names. Rspec doesn't …
=> Differentiate engine version of shared examples

modules/decision_reviews/spec/factories/secondary_appeal_forms.rb, modules/decision_reviews/spec/sidekiq/sc_status_updater_job_spec.rb, spec/sidekiq/decision_review/sc_status_updater_job_spec.rb
Previous refactor accidentally deleted a block of tests. This PR adds them back
No ticket, noticed during another bug fix
Checking status of 4142 forms submitted with Supplemental Claim was not tested
Break 4142 status checks, see tests fail correctly
Test for one Decision Review background job
=> Recover tests lost during refactor

modules/ivc_champva/app/form_mappings/vha_10_7959a.json.erb
This PR updates the JSON erb mapping so that the "Non group" insurance checkbox on form 10-7959a gets checked correctly.
Previously, the mapping was attempting to use the key `non_group`, which did not exist and caused the form to erroneously check the 'other' box. Updating the mapping here fixes the issue of the checkbox not being checked properly.
- https://github.com/department-of-veterans-affairs/vets-website/pull/33552 …
=> Update mapping to properly check `nonGroup` field - form 10-7959a

config/features.yml
Remove two unused feature flippers:
- `facility_locator_ppms_legacy_urgent_care_to_pos_locator`
- `facility_locator_pull_operating_status_from_lighthouse`
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11594
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11595
- [Github-wide search for `facility_locator_ppms_legacy_urgent_care_to_pos_locator`](https://github.com/search?q=org%3Adepartment-of-veterans-affairs+facility_locator_ppms_legacy_urgent_care_to_pos_locator&type=code) shows only one result in vets-api (other than archived/test repos)
- [Github-wide search for `facility_locator_pull_operating_status_from_lighthouse`](https://github.com/search?q=org%3Adepartment-of-veterans-affairs+facility_locator_pull_operating_status_from_lighthouse&type= …
=> VACMS-11595, 11594: remove unused feature flippers

config/features.yml
Adding feature flag `mhv_account_creation_api_consumption`. Targeted end date is sometime in quarter 1 of 2025.
[Related PR](https://github.com/department-of-veterans-affairs/vets-website/pull/33562)
=> 97281 add feature flag

lib/saml/post_url_service.rb
- This PR skips the mhv account creation API during SSOe authentication if `custom` is the type of authentication in the requested SAML attributes
Authentication
=> [VI-740] Skipping mhv account creation during auth custom type in payload attributes

app/sidekiq/hca/log_email_diff_job.rb, spec/factories/in_progress_forms/in_progress_forms.rb, spec/sidekiq/hca/log_email_diff_job_spec.rb
- When refactoring the `HCA::LogEmailDiffJob` to no longer use redis, we discovered it was using an old attribute to validate if the email should be logged as same/different. This attribute was causing it to always return early in the job, thus never actually logging if the email was the same/different between the form and the profile. Removing this check from the job should make the metric start incrementing. 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/94285
10-10 EZ
=> [10-10EZ] Remove view:email_confirmation check from HCA:: LogEmailDiffJob since attribute is no longer used

modules/claims_api/app/services/claims_api/power_of_attorney_request_service/create_request.rb
We parallelized BGS calls in https://github.com/department-of-veterans-affairs/vets-api/pull/19633 but discovered Datadog creates new trace ids for the parallel requests. The result is we cannot see the parallel requests in the Datadog trace view (see ticket [comment](https://jira.devops.va.gov/browse/API-43211?focusedId=3467878&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-3467878) for screenshot).
This PR attempts to continue the same Datadog trace for the parallel requests, allowing us to see all the requests in one waterfall view. See [ddtrace documentation](https://github.com/DataDog/dd-trace-rb/blob/master/docs/UpgradeGuide.md#distributed-tracing) for the approach.
[API-43211](https://jira.devops.va.gov/browse/API-43211)
- Manually submitted a POST …
=> [API-43211] Add distributed tracing to POA request creation

lib/medical_records/bb_internal/client.rb, spec/lib/medical_records/bb_internal/client_spec.rb
- The call to retrieve images was not blocking while the authentication call was completing.
- We needed to update the block condition to check for patient_id, which is required by the images call.
- Old behavior - first time calling radiology or images API would yield a 404
- To verify, start a fresh MR session and see that radiology and images API calls work on the first try
Here's the call. Note that before, the radiology call would have returned a 404 as there was no patient ID.
=> MHV-65081 Check patient_id is present before making calls

modules/decision_reviews/spec/dr_spec_helper.rb, modules/decision_reviews/spec/lib/v1/service_spec.rb, modules/decision_reviews/spec/sidekiq/delete_saved_claim_records_job_spec.rb, modules/decision_reviews/spec/sidekiq/failure_notification_email_job_spec.rb, modules/decision_reviews/spec/sidekiq/form4142_submit_spec.rb, modules/decision_reviews/spec/sidekiq/hlr_status_updater_job_spec.rb, modules/decision_reviews/spec/sidekiq/nod_email_loader_job_spec.rb, modules/decision_reviews/spec/sidekiq/nod_send_email_job_spec.rb, modules/decision_reviews/spec/sidekiq/nod_status_updater_job_spec.rb, modules/decision_reviews/spec/sidekiq/sc_status_updater_job_spec.rb, modules/decision_reviews/spec/sidekiq/submit_upload_spec.rb, modules/decision_reviews/spec/spec_helper.rb, modules/decision_reviews/spec/support/engine_shared_examples_for_status_updater_jobs.rb, modules/decision_reviews/spec/support/pdf_helper.rb, modules/decision_reviews/spec/support/sidekiq_helper.rb, modules/decision_reviews/spec/support/vcr_helper.rb
- don't use the general `rails_helper`
- only require test support and configuration needed by the engine
No ticket
The test in the DR engine were using the main app `rails_helper`. This led to some file loading and namespace collision. The goal is to isolate the engine from the main app as much as possible
Test run without flaky failures or warnings …
=> Isolate DR engine tests from main test context

config/features.yml, modules/ivc_champva/app/controllers/ivc_champva/v1/uploads_controller.rb, modules/ivc_champva/spec/requests/ivc_champva/v1/forms/uploads_spec.rb
This PR fixes a bug in our program. In a very small sample of users, an IVC CHAMPVS form user will occasionally get a 500 error message and will not able to submit the complete form. This is caused by the temporary multi-stamp file being deleted in the kubernetes pod before the vets-api pdf filler completes. This PR will allow a retry of the multi stamp creation if the file is missing.
https://github.com/department-of-veterans-affairs/vets-api/pull/19006
https://github.com/department-of-veterans-affairs/vets-api/pull/19662
User story:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/97231
End to End test on 7959F1 and 1010D
Removed the unit test that enforces handle_uploads to be called twice due to retry logic. 
Excluding the specific unit test involving …
=> Improve-PDF-stamping-resilency

modules/claims_api/app/clients/claims_api/bgs_client/definitions.rb
* Reverts some changes made to the definitions file to avoid Calling for the WSDL when making a request to the 
EBenefitsBnftClaimStatusWebServiceBean/EBenefitsBnftClaimStatusWebService
[API-43374](https://jira.devops.va.gov/browse/API-43374)
* V2 Claims Index hit can be used to test, but anything that uses `find_benefit_claims_status_by_ptcpnt_id` should be good.  Then watch the log out
* What we _do not_ want to see is the WSDL get call in the logout like below
* What we do want to see
modified:   modules/claims_api/app/clients/claims_api/bgs_client/definitions.rb
=> API-42308-prevent-wsdl-call-fix

modules/my_health/app/controllers/my_health/v1/medical_records/military_service_controller.rb
- A user might be missing an EDIPI. If this is the case, return an informative error to the frontend so it can be handled there.
- User without an EDIPI would get a 404 error because the upstream API was called without the URL param.
- To verify, see that a call to the military service API returns an informative 400 or a 200 in normal scenarios.
=> MHV-65160 Handle missing EDIPI

Gemfile, Gemfile.lock
[Ruby's official debugging library](https://github.com/ruby/debug) [added in 3.1](https://www.ruby-lang.org/en/news/2021/12/25/ruby-3-1-0-released/) is excellent. I'd like to use it during the course of development e.g. `binding.b` AKA `binding.break`
=> add debug development & test gem

modules/simple_forms_api/app/services/simple_forms_api/notification_email.rb, modules/simple_forms_api/spec/requests/simple_forms_api/v1/simple_forms_spec.rb, modules/simple_forms_api/spec/services/notification_email_spec.rb
This PR omits the `lighthouse_updated_at` key-value pair if the value is `nil`. I believe this key being `nil` is causing errors to crop up with the library we use to send notifications.
=> Omit nil key-value pair in email personalization

modules/ivc_champva/app/services/ivc_champva/attachments.rb
This PR fixes an issue regarding moving decrypted/unlocked PDFs.
When a user uploads an encrypted PDF, we call a method to unlock it that relies on `Common::FileHelpers::generate_clamav_temp_file` - this method stores the file in a `clamav_tmp` directory. This is fine when developing locally, but on staging that directory is apparently on a different device, which causes our later `File.rename` call to fail as such:
To account for this, rather than using `File.rename`, the code now uses `FileUtils.mv` which should automatically fall back to a copy operation if the move fails due to being on an external device.
- Adds a new `FileUtils.mv` call behind feature toggle
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/98848
- *Describe what the old behavior was prior to …
=> 98848 Use `FileUtils.mv` over `File.rename` to account for external device error - IVC CHAMPVA forms

modules/simple_forms_api/app/controllers/simple_forms_api/v1/scanned_form_uploads_controller.rb, modules/simple_forms_api/app/services/simple_forms_api/pdf_stamper.rb, modules/simple_forms_api/spec/requests/simple_forms_api/v1/scanned_form_uploads_spec.rb, modules/simple_forms_api/spec/services/pdf_stamper_spec.rb
This PR stamps a watermark at the bottom of a PDF uploaded through the Form Upload flow.
https://github.com/orgs/department-of-veterans-affairs/projects/1443/views/3?sliceBy%5Bvalue%5D=Thrillberg&pane=issue&itemId=83134526&issue=department-of-veterans-affairs%7CVA.gov-team-forms%7C1473
=> Stamp watermark on PDF uploaded with Form Upload Flow

modules/vaos/app/services/eps/provider_service.rb, modules/vaos/spec/services/eps/provider_service_spec.rb
This PR adds a method to get the provider slots based on the parameters provided. If nextToken is provided, it is used to fetch the slots. If not, other parameters are passed as is to the underlying wellhive api method, and results are returned.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/96446
=> 96446 add EPS get provider slots method

app/controllers/v0/disability_compensation_forms_controller.rb
- all submissions go through lighthouse
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/97932
=> dbex/97932-claims-api: set claims api only

app/models/form_profiles/va_2122.rb, app/models/form_profiles/va_2122a.rb, config/form_profile_mappings/21-22.yml, config/form_profile_mappings/21-22A.yml
- This pr fixes the default return url for Appoint a Rep prefill
- This pr removes incorrect prefill attributes
- [96836](https://github.com/department-of-veterans-affairs/va.gov-team/issues/96836)
- Prefill with vets-website running locally is working
Appoint a Rep Form 21-22 and 21-22a
=> [96836] Appoint a Rep prefill fixups

app/models/user.rb, spec/models/user_spec.rb
- Enable MHV Account Creation for all users
- https://jira.devops.va.gov/browse/VI-909
- Test sis and ssoe authentication 
MHV Account Creation, authentication
=> VI-909 - Enable MHV Account Creation for all users

modules/simple_forms_api/docs/rfcs/0003-form-submission-purge-plan.md
- This PR introduces a detailed plan for purging `FormSubmission` records from our PostgreSQL database to comply with data retention policies. The plan outlines the process for safely deleting records and associated PDF files after a retention period of 60 days post-approval of the form submission.
- [Develop Data Purge Plan for FormSubmission Records](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/860)
- No previous changes or bugs are directly linked to this implementation.
I would appreciate feedback on the clarity and completeness of the purge plan. Specifically, are there any additional considerations or edge cases that we should account for in the implementation? Additionally, any insights on the …
=> [SIMPLE-FORMS] feat: Develop Data Purge Plan for FormSubmission Records

app/sidekiq/form1010cg/submission_job.rb, spec/sidekiq/form1010cg/submission_job_spec.rb
- Added callbacks to the VANotify implementation for submission failure emails to update statsD metrics with email delivery status information. We are using the default implementation from the VANotify team. Also updated which metrics are incremented when we have a submission that does not have an email or the flipper toggle is turned off.
- Sending the email is still behind the `caregiver_use_va_notify_on_submission_failure` toggle.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/95342
none
10-10CG Submission Job
=> [10-10CG] Add callbacks to VANotify usage in 10-10CG Submission Job

lib/vets/attributes.rb, spec/lib/vets/attributes_spec.rb
- Add filterability by attributes 
- Add filterable attribute list
- Add filterable param list (for use with controllers)
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/98688
=> Add filterable to Vets::Model

.github/CODEOWNERS, app/controllers/v0/test_account_user_emails_controller.rb, config/routes.rb, spec/requests/v0/test_account_user_emails_spec.rb
- This PR adds a route that is callable with an email parameter 
- https://jira.devops.va.gov/browse/VI-910
Test Accounts
=> [VI-910] Adding route to store user-input emails as a prerequisite for accessing MHV test accounts

.github/CODEOWNERS, app/controllers/concerns/exception_handling.rb, app/controllers/v1/sessions_controller.rb, app/models/mhv_user_account.rb, app/models/user.rb, app/models/user_identity.rb, app/services/login/after_login_actions.rb, app/services/login/user_verifier.rb, app/services/sign_in/attribute_validator.rb, app/services/sign_in/user_code_map_creator.rb, lib/saml/user_attributes/ssoe.rb, lib/sign_in/idme/service.rb, modules/mocked_authentication/spec/lib/credential/service_spec.rb, spec/controllers/v1/sessions_controller_spec.rb, spec/factories/mhv_user_accounts.rb, spec/factories/users.rb, spec/lib/saml/ssoe_user_spec.rb, spec/lib/sign_in/idme/service_spec.rb, spec/models/user_spec.rb, spec/requests/swagger_spec.rb, spec/requests/v0/user_spec.rb, spec/services/login/after_login_actions_spec.rb, spec/services/login/user_verifier_spec.rb, spec/services/sign_in/attribute_validator_spec.rb, spec/services/users/profile_spec.rb
- update `mhv_correlation_id` to pull from `mhv_user_account` if it exists otherwise pull from `mpi.active_mhv_ids` if there is only one.
- update `mhv_correlation_id` from the saml and login user attributes to `mhv_credential_uuid`
- don't block users from logging in if they have multiple `mhv_ids`
- https://jira.devops.va.gov/browse/VI-694
- test ssoe and sis login
- test logging in with users that have multiple `mhv_ids` (vets.gov.user+11@gmail.com)
- these should not be blocked
Authentication, mhv_correlation_id
=> [vi-694] update mhv_correlation_id 

app/models/health_care_application.rb, config/features.yml, spec/models/health_care_application_spec.rb
- Added VANotify callbacks to the 10-10EZ Submission Failure email. The callbacks increment relevant statsD metrics and logs for success/failure, and we will be adding monitors in datadog for these metrics. 
- Behind new `hca_zero_silent_failures` toggle
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/93247
- We will validate that the relevant vanotify statsD metrics are incremented with our email tags in staging
10-10EZ
=> [10-10EZ] Add VANotify Callbacks to Failure email

modules/claims_api/spec/lib/claims_api/v2/disability_compensation_validation_spec.rb
- [disability_compensation_validation_spec.rb#L481](https://github.com/department-of-veterans-affairs/vets-api/blame/master/modules/claims_api/spec/lib/claims_api/v2/disability_compensation_validation_spec.rb#L481)
- `anticipatedSeparationDate` must be a future date for the tests to pass
- I made the date dynamic to ensure it always passes
- n/a
=> Fix future date for valid_service_info_for_bdd

modules/simple_forms_api/app/services/simple_forms_api/pdf_stamper.rb
This PR uses `FileUtils.mv` instead of `File.rename` in the Simple Forms PDF Stamper. We were seeing errors on staging stemming from trying to rename files across filesystems. `FileUtils.mv` should be able to handle this.
https://github.com/orgs/department-of-veterans-affairs/projects/1443/views/3?sliceBy%5Bvalue%5D=Thrillberg&pane=issue&itemId=88752628&issue=department-of-veterans-affairs%7CVA.gov-team-forms%7C1892
=> Use FileUtils.mv instead of File.rename to handle cross-filesystem file manipulation

modules/ask_va_api/app/controllers/ask_va_api/v0/health_facilities_controller.rb, modules/ask_va_api/spec/requests/ask_va_api/v0/health_facilities_spec.rb
- Fix bug in HealthFacilitiesController#retrieve_patsr_approved_facilities
- [#1530](https://github.com/department-of-veterans-affairs/ask-va/issues/1530)
=> BE | Ask VA Api: Fix bug in HealthFacilitiesController#retrieve_patsr_approved_facilities

lib/vets/model.rb, lib/vets/model/dirty.rb, spec/lib/vets/model/dirty_spec.rb
- Add methods for use with Vets::Model via Vets::Model::Dirty
- `changed?`: returns an array with the name of the attributes with unsaved changes.
- `changed`: returns true if any of the attributes has unsaved changes, false otherwise.
- `changes`: returns a hash of changed attributes indicating their original and new values
- The changes track only the original value and the current value
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/98688
=> Add dirty module to Vets::Model

lib/vets/collection.rb, spec/lib/vets/collection_spec.rb
Note: there's a linting failure for a rails upgrade... that will be addressed in sjc-vets-collection
- This requires Vets::Models be Sortable, but these files will be merged in a different PR
-  So it's blocked until Sortable is merged 
- Issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/99123
- Blocking PR: https://github.com/department-of-veterans-affairs/vets-api/pull/19827
=> Add sortability to Vets::Collection

modules/vaos/app/services/vaos/v2/appointments_service.rb, modules/vaos/spec/services/v2/appointment_service_spec.rb
- Hotfix for large number of modality errors, see [conversation on Slack](https://dsva.slack.com/archives/CMNQT72LX/p1734727335423249)
- N/A
N/A
=> Reduce modality error log to info

modules/vaos/app/services/eps/appointment_service.rb, modules/vaos/spec/services/eps/appointment_service_spec.rb
Implements a new method to submit appointments to the EPS API using the  /appointments/{appointmentId}/submit endpoint. The method:
- Validates appointment_id and required parameters (network_id, provider_service_id, 
slot_ids, referral_number)
- Supports optional additional_patient_attributes
- Returns API response wrapped in OpenStruct
https://github.com/department-of-veterans-affairs/va.gov-team/issues/96414
VAOS appointments, community care referrals
=> 96414 Add submit_appointment method to EPS AppointmentService

.github/CODEOWNERS
This PR updates CODEOWNERS for the `transactional_email_analytics_job` and spec. This job processes analytics data for transactional emails sent through GovDelivery. It tracks [four specific mailers](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/sidekiq/transactional_email_analytics_job.rb#L41-L48) so I've assigned the ownership of this job to the owning teams. 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/98414
N/A
CODEOWNERS
=> Update codeowners for transactional_email_analytics_job

modules/ivc_champva/app/controllers/ivc_champva/v1/uploads_controller.rb, modules/ivc_champva/spec/requests/ivc_champva/v1/forms/uploads_spec.rb
This PR improves flexibility and maintainability by using a list to manage error conditions, making it easier to add or modify error messages in the future. Additionally, it handles a broader range of error messages and provides a clearer return message when no retries are needed.
Comparison:
Error Conditions:
Old Code: Checks for specific error messages directly within the if statement.
New Code: Uses a list (error_conditions) to store multiple error messages and checks if any of these conditions are met.
Flexibility:
Old Code: Hardcoded error messages make it less flexible and harder to maintain.
New Code: More flexible and maintainable by using a list to manage error conditions.
Error Messages:
Old Code: Handles fewer specific error messages.
New Code: Handles a broader range of error …
=> optimize error handling

app/controllers/v1/post911_gi_bill_statuses_controller.rb, spec/controllers/v1/post911_gi_bill_statuses_controller_spec.rb
- *(Summarize the changes that have been made to the platform)* Updated the statsd prefix in preparation for integration of Post-911 Statement of Benefits tool with DGIB data. Tool no longer exclusively serves data from Light House.
- *(What is the solution, why is this the solution?)* I removed reference to Lighthouse from statsd prefix because tool will no longer exclusively serve lighthouse data
- *(Which team do you work for, does your team own the maintenance of this component?)* Education Data Migration (EDM)
- https://jira.devops.va.gov/browse/EDM-269
- *Describe …
=> EDM-269/update post911 sob statsd prefix

config/features.yml
This PR adds a feature toggle to control the Data Dog Real User Monitoring (RUM) for form 10-10d.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/98828
- https://github.com/department-of-veterans-affairs/vets-website/pull/33772
NA
IVC CHAMPVA form 10-10d …
=> 98828 Add feature toggle for RUM - form 10-10d

.github/workflows/build.yml, .github/workflows/deploy-template.yml
The workflow prevents deploying failed commits by modifying `gitHub.sha` to `github.event.workflow_run.head_commit.id`. See [thread](https://oddball.slack.com/archives/C045LCF8WU8/p1735237544597019) for more details.
PR output:
```
Echo PR before push:
Run echo “github.sha: 17f0c2bc1de44575714094f32492750596ed4e16”
github.sha: 17f0c2bc1de44575714094f32492750596ed4e16
github.event.push.head_commit.id:
github.event.pull_request.merge_commit_sha: 413c1608c7272b1bdaa1c46a38e30adcfff15a01
github.event.head_commit.id:
Echo PR code checks after push:
Run echo “github.sha: 781541c1b366fc5549896ae961bf9d6faeb40b75"
github.sha: 781541c1b366fc5549896ae961bf9d6faeb40b75
github.event.push.head_commit.id:
github.event.pull_request.merge_commit_sha:
github.event.head_commit.id: …
```
=> Add Commit Status Verification to deploy-template

app/sidekiq/education_form/send_school_certifying_officials_email.rb
- VEBT-894 - handle 404 error for 22-10203 SCO email
-  add error handling
- VEBT
- [vebt-894](https://jira.devops.va.gov/browse/VEBT-894)
From ticket:
Description
Fixing a school certifying officials email datadog error.  The error is /app/lib/common/client/base.rb:115:in `rescue in request': BackendServiceException: {:status=>404, :detail=>"Record not found", :code=>"GI404", :source=>"Record not found"} (GI::ServiceException)
- 404 error thrown for SCO email when facility code is not an approved institution
- submit a 10203 form
submission of 10203 form SCO email
=> VEBT-894 - handle 404 error for 22-10203 SCO email

config/redis.yml
While working on a ticket to find out if there were any duplicated redis namespaces in vets-api, I found `okta-response` existed twice in the redis config. Duplicated redis namespaces are bad because data can be overwritten if namespaces are created with the same keys. I did more searching in the codebase and couldn't find anywhere this namespace was being called. I even searched the entire VA org and didn’t see any references. So Lindsey and I determined these keys could be deleted. See Testing section for more investigation.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/97502
In a prod vets-api pod:
```
vets-api(prod)> namespace = 'okta-response'
=> "okta-response"
vets-api(prod)> redis = $redis
=> #<Redis client v5.3.0...
vets-api(prod)> count = 0
=> 0 …
```
=> Delete `okta-response` keys in redis config

app/models/persistent_attachments/va_form.rb, spec/models/persistent_attachments/va_form_spec.rb
This PR adds the min and max page count for 21-509 to the `VAForm` Persistent attachment class. This will enable the FE to display warnings if the user uploads a doc with too few or too many pages.
=> Add 21-509 min and max pages to Form Upload flow

modules/simple_forms_api/app/controllers/simple_forms_api/v1/scanned_form_uploads_controller.rb
This PR logs the form number and file size for form upload submissions. I think the ultimate goal is to maybe make a pie chart divided by form number. (Currently this only works for two form numbers)
https://github.com/orgs/department-of-veterans-affairs/projects/1443/views/3?sliceBy%5Bvalue%5D=Thrillberg&filterQuery=-status%3AIcebox%2CEpic%2C%22Collab+Cycle%22&pane=issue&itemId=83134568&issue=department-of-veterans-affairs%7CVA.gov-team-forms%7C1278
=> Log form number and file size for form upload submissions

modules/decision_reviews/spec/controllers/decision_review_evidences_controller_spec.rb, modules/decision_reviews/spec/controllers/decision_review_notification_callbacks_controller_spec.rb, modules/decision_reviews/spec/dr_spec_helper.rb, modules/decision_reviews/spec/requests/v1/higher_level_reviews/contestable_issues_spec.rb, modules/decision_reviews/spec/requests/v1/higher_level_reviews_spec.rb, modules/decision_reviews/spec/requests/v1/notice_of_disagreements/contestable_issues_spec.rb, modules/decision_reviews/spec/requests/v1/notice_of_disagreements_spec.rb, modules/decision_reviews/spec/requests/v1/supplemental_claims/contestable_issues_spec.rb, modules/decision_reviews/spec/requests/v1/supplemental_claims_spec.rb, modules/decision_reviews/spec/requests/v2/higher_level_reviews_spec.rb
Use engine test helpers instead of main app test helpers. Already done for sidekiq and lib specs.
No ticket
Was using main app `rails_helper`, now using engine specific test setup
Run test in isolation from main app, ensure tests still pass
Decision Review engine specs
=> Use engine only test helpers

modules/vaos/app/controllers/vaos/v2/clinics_controller.rb, modules/vaos/app/docs/vaos/v2/vaos_v2.yaml, modules/vaos/spec/requests/vaos/v2/locations/clinics_spec.rb, spec/support/vcr_cassettes/vaos/v2/systems/get_recent_facilities_200.yml
- This work is behind a feature toggle (flipper): YES - `va_online_scheduling_recent_locations_filter`
- This is part of ongoing development for the new recent locations feature. This PR adds an optional url param `clinical_service_id` that allows recent facilities endpoint to filter returned facilities to only those that supports the specified service.
- Appointment (VAOS) Team
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/99311
- Added new unit tests to cover the added filter capability and ensured existing tests pass
N/A
=> Recent facilities endpoint enhancements - Filter by type of care

Gemfile.lock
- Bump carrierwave 3.0.7 -> 3.1.0
=> Bump carrierwave 3.0.7 -> 3.1.0

lib/pdf_fill/forms/va210781v2.rb, spec/fixtures/pdf_fill/21-0781V2/kitchen_sink.json, spec/fixtures/pdf_fill/21-0781V2/overflow.json, spec/support/disability_compensation_form/all_claims_with_0781v2_fe_submission.json, spec/support/disability_compensation_form/form_0781v2.json, spec/support/disability_compensation_form/submissions/with_0781v2.json
- Eventually will be gated by [disability_compensation_sync_modern_0781_flow](https://github.com/department-of-veterans-affairs/vets-api/blame/4e69360695d020fe9a3c915fc787cefc101e5cc6/config/features.yml#L570)
- Sets the `optionIndicator` object based on a string value being submitted, rather than a hash of attributes with true/false values
- Expects 1 of 4 valid options
- *(If bug, how to reproduce)* **N/A**
- The current 21-0781 form generated as a result of completing the online form 21-526EZ process is outdated (expired 7/21/2020) and requires an upgrade to be in sync with the current paper form (released …
=> [DBEX] set indicator object from submitted string value

modules/representation_management/app/serializers/representation_management/power_of_attorney/representative_serializer.rb, modules/representation_management/app/swagger/v0/swagger.json, modules/representation_management/spec/requests/representation_management/v0/power_of_attorney_swagger_spec.rb, modules/representation_management/spec/serializers/power_of_attorney/representative_serializer_spec.rb, modules/representation_management/spec/support/rswag_config.rb
- This pr adds the individual type attribute to the current power of attorney API response so that the front end can distinguish between attorneys and claims agents.
- [96901](https://github.com/department-of-veterans-affairs/va.gov-team/issues/96901)
- Appoint a Rep Form 21-22 and 21-22a
=> [96901] Add Individual Type to current rep API response

spec/sidekiq/evss/disability_compensation_form/submit_form0781_spec.rb
- Added test coverage to ensure the `get_docs` method works as expected and correctly distinguishes between different form types `form0781` and `form0781a`
https://github.com/department-of-veterans-affairs/vets-api/pull/19624
- Impacts the processing of disability compensation forms, specifically the generation of PDF documents for `form0781` and `form0781a`
=> Add test coverage to verify correct argument is passed to process_0781

app/controllers/v1/sessions_controller.rb, app/services/login/user_verifier.rb, app/services/sign_in/user_code_map_creator.rb, spec/controllers/v0/sign_in_controller_spec.rb, spec/models/user_spec.rb, spec/services/login/user_verifier_spec.rb
- This PR updates UserVerifier functionality so that MHV accounts will properly propagate the MHV UUID when the `UserVerifier` is called during an MHV SSOe auth
- https://jira.devops.va.gov/browse/VI-918
Authentication
=> [VI-918] Updating UserVerifier to take distinct attributes, and to properly propagate mhv uuid

app/models/user.rb, spec/models/user_spec.rb
- This PR makes it so the MHV Correlation ID attribute on the user model is only available if the user is verified and has properly accepted terms of use
https://jira.devops.va.gov/browse/VI-918
MHV attributes
=> [VI-917] MHV Correlation ID attribute only for verified users

modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb, modules/simple_forms_api/app/services/simple_forms_api/notification_email.rb, modules/simple_forms_api/spec/requests/simple_forms_api/v1/simple_forms_spec.rb, modules/simple_forms_api/spec/services/notification_email_spec.rb, modules/va_notify/lib/va_notify/service.rb
This PR allows certain SAHSHA (26-4555) emails to be sent (REJECTED and DUPLICATE ones) without a reference_number. Currently we're seeing an error every time one of these types of emails is attempted to be sent because of this bug.
https://github.com/orgs/department-of-veterans-affairs/projects/1443/views/3?sliceBy%5Bvalue%5D=Thrillberg&filterQuery=-status%3AIcebox%2CEpic%2C%22Collab+Cycle%22&pane=issue&itemId=92389103&issue=department-of-veterans-affairs%7CVA.gov-team-forms%7C1946
=> Allow SAHSHA emails to be sent without reference_numbers

modules/claims_api/app/controllers/concerns/claims_api/disability_compensation_validations.rb, modules/claims_api/spec/requests/v1/forms/526_spec.rb
In v1 526 validation, check the disabilitiesʼ classification code expiration dates. If the code is expired, raise an exception.
[API-43131](https://jira.devops.va.gov/browse/API-43131)
N/A
v1 526 submission validation
N/A
=> [API-43131] Validate 526 v1 disabilitiesʼ classification code end date

app/sidekiq/lighthouse/submit_benefits_intake_claim.rb, spec/sidekiq/lighthouse/submit_benefits_intake_claim_spec.rb
- The import of BenefitsIntake::Metadata in SubmitBenefitsIntakeClaim broke after a namespace change was released last week, causing submissions to fail. This repairs the import. 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/100034
-  Confirmed that the test change caused test failure prior to fix
Before:
After:
Burials, SubmitBenefitsIntakeClaim
=> Fix SubmitBenefitsIntakeClaim import error

modules/va_notify/app/controllers/va_notify/callbacks_controller.rb, modules/va_notify/spec/requests/callbacks_spec.rb
- *(Summarize the changes that have been made to the platform)* Adds additional logging to help determine which notifications still need to have metadata provided (for properly tracking silent failures) …
=> VaNotify - Update callback logging

lib/periodic_jobs.rb
- *This work is behind a feature toggle (flipper): YES* The Realtime banners are behind a feature flag as well as the job that is updating via a separate flag
- This will have real time banners update jobs running every 5 minutes instead of 10, bringing down the expected update time for Editors from 20minutes to 10.
- Sitewide team built and owned
- Issue: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20093
- Previously this job would be run every 10minutes, with the update only adjusting to run this every 5
Real-time banners DB updating
=> [VACMS-20093]Update real-time banners every 5 minutes instead of waiting 10

Gemfile.lock, modules/vye/app/models/vye/user_profile.rb, modules/vye/lib/vye/load_data.rb, modules/vye/spec/lib/vye/load_data_spec.rb, modules/vye/spec/models/vye/user_profile_spec.rb
- Refined criteria for processing TIMS ingest errors
- Not sure if this would be classified as a bug so much as incorrect criteria?
- Removed logic that incorrectly checked for a conflict and changed logic for loading user profile
- vebt
- N/A
- Jira ticket attached in word document
- [x ] *New code is covered by unit tests*
TIMS ingest records were incorrectly being identified as having errors when they should not have.
Run a TIMS ingest job (LoadData rake task) and confirm errors are not being flagged that shouldn't be. These …
=> vebt-830 code tims fix and tests
