config/application.rb

we're using rspec and don't need test unit

remove test unit

---

.gitmodules
.travis.yml

add vets json schema submodule

---

.travis.yml
Gemfile
Gemfile.lock
config/application.rb
config/database.yml

add postgres

---

.travis.yml
config/application.yml.example

Removing an unused variable from Travis and the example application.yml file.

Remove unused variable

---

Gemfile
Gemfile.lock
README.md
config/application.rb
config/initializers/active_model_serializers.rb
spec/controllers/v0/education_benefits_claims_controller_spec.rb
spec/request/education_benefits_claims_request_spec.rb
spec/request/prescriptions_request_spec.rb
spec/serializers/tracking_serializer_spec.rb
spec/serializers/triage_team_serializer_spec.rb
spec/support/schemas/prescription.json
spec/support/schemas/prescriptions.json
spec/support/schemas/prescriptions_filtered.json
spec/support/schemas/tracking.json
spec/support/schemas/trackings.json
spec/support/schemas/triage_team.json
spec/support/schemas/triage_teams.json

Convert case middleware

---

app/models/user.rb

EVSS isn't working for me right now. I thought it might have something to do with us not including this header, so I added it in. That doesn't seem to actually be the issue, but we may as well merge this in.

VAAFI headers: Build the JSON magic header

---

app/jobs/education_form/templates/22-1990.erb
spec/factories/education_benefits_claim.rb

some of my tests on #59 need the newer json schema

Update vets json schema

---

docs/sm-api.md

@Kam @ayaleloehr This is the format I'd like to follow. Please review, and if acceptable, I will have the rest up tonight.

First draft for sm api doc

---

app/controllers/v0/claims_controller.rb
app/controllers/v0/documents_controller.rb
app/models/claim.rb
app/models/user.rb
lib/evss/base_service.rb
lib/evss/claims_service.rb
lib/evss/documents_service.rb
spec/lib/evss/claims_service_spec.rb
spec/lib/evss/documents_service_spec.rb

It didn't really make sense as a user responsibility, so let's make it the job of the EVSS base client.

Move VAAFI header creation into the EVSS client

---

Gemfile
Gemfile.lock
app/jobs/education_form/create_daily_spool_files.rb
config/application.rb
config/initializers/sidekiq.rb
spec/jobs/education_form/create_daily_spool_files_spec.rb
spec/rails_helper.rb

Add sidekiq

---

lib/evss/error_middleware.rb

AFAICT, the code did not work as originally written. Let me know if there is some more elegant way of writing this.

EVSS middleware: fix bug when success: false is returned

---

app/jobs/education_form/education_facility.rb
app/models/education_benefits_claim.rb
app/serializers/education_benefits_claim_serializer.rb
spec/jobs/education_form/create_daily_spool_files_spec.rb
spec/jobs/education_form/education_facility_spec.rb
spec/models/education_benefits_claim_spec.rb
spec/serializers/education_benefits_claim_serializer_spec.rb

Output the regional office address

---

Gemfile
Gemfile.lock

Bundler added the `1.13.1` change, let me know if it's a problem and I'll revert that bit

Adding `oj` to override system `json` gem

---

app/models/folder.rb
spec/models/folder_spec.rb

Alex I'm assigning this one to you and tagging @webinista for awareness regarding conversation on https://github.com/department-of-veterans-affairs/messaging-fe/issues/67

adding length check on folder

---

app/controllers/v0/messages_controller.rb
app/models/message.rb
app/models/message_draft.rb
spec/models/message_spec.rb
spec/request/messages_request_spec.rb
spec/support/vcr_cassettes/sm/messages/10616687/create_no_subject.yml

Added validation to message model
Test validation in message model spec
Test exception in message request spec
Test default subject line in message request spec

Added validation to message model

---

app/controllers/v0/message_drafts_controller.rb
config/routes.rb
docs/api/sm-api.md
lib/sm/api/message_drafts.rb
lib/sm/api/messages.rb
lib/sm/client.rb
spec/factories/healthcare_messaging_message_draft.rb
spec/lib/sm/api/message_drafts_spec.rb
spec/request/message_drafts_request_spec.rb
spec/support/schemas/message.json
spec/support/vcr_cassettes/sm/message_drafts/10616687/create.yml
spec/support/vcr_cassettes/sm/message_drafts/10616687/update.yml

Added message drafts controller: create and update
Added message drafts api
Added api/request specs

Drafts api

---

app/controllers/v0/messages_controller.rb
config/routes.rb
docs/api/sm-api.md
spec/request/messages_request_spec.rb
spec/support/vcr_cassettes/sm/messages/10616687/create_reply_bad_id.yml

Added message replies

---

config/environments/production.rb
config/mvi_schema/mock_mvi_responses.yml.example

Once id.me loads our test users into their system we can switch this back to the real mvi service.

Use mock mvi service in prod

---

app/models/disability_claim.rb
app/serializers/disability_claim_base_serializer.rb
app/services/disability_claim_service.rb
db/migrate/20161005170638_add_user_uuid_index_to_disability_claims.rb
db/schema.rb
spec/serializers/disability_claim_detail_serializer_spec.rb
spec/services/disability_claim_service_spec.rb
spec/support/schemas/disability_claim.json
spec/support/schemas/disability_claims.json

Adds two fields to a disability claim
- Development letter sent boolean
- Sync failed boolean
Sync failed will be `null` if the sync was successful

Claim dev letter sent

---

app/models/message.rb
spec/models/message_spec.rb

- adding additional check for number of files uploaded
- cleaning up calculation of file sizes
- adding specs

Message upload validation cleanup

---

README.md
app/uploaders/disability_claim_document_uploader.rb
config/initializers/evss_aws_access_creds.rb
spec/uploaders/disability_claim_document_uploader_spec.rb

ENV var naming was incorrect
https://github.com/department-of-veterans-affairs/devops/pull/843/files

Fix env var naming

---

config/mvi_schema/mock_mvi_responses.yml.example

I got this info from EVSS's mock login. I would like to add it to our YAML file to see if it lets people log in to EVSS.

MVI mock overrides: Add info from EVSS stage1a

---

config/initializers/breakers.rb
lib/evss/base_service.rb
lib/evss/common_service.rb
spec/lib/evss/base_service_spec.rb
spec/services/disability_claim_service_spec.rb

Increase EVSS timeout to 15 seconds
Temporarily remove breakers from EVSS requests

Increase evss timeout

---

app/controllers/v0/disability_claims_controller.rb
app/services/disability_claim_service.rb
app/workers/disability_claim/request_decision.rb
spec/jobs/disability_claim/request_decision_spec.rb
spec/lib/evss/claims_service_spec.rb
spec/request/disability_claims_spec.rb

Fixes https://github.com/department-of-veterans-affairs/sunsets-team/issues/158

EVSS: Queue requests for decision

---

config/mvi_schema/mock_mvi_responses.yml.example

To let us do testing on dev as a backup plan to stage1a.

Adding MHV accounts for some mock users

---

app/serializers/disability_claim_detail_serializer.rb
spec/fixtures/disability_claim/claim-with-documents.json
spec/serializers/disability_claim_detail_serializer_spec.rb

Refs https://github.com/department-of-veterans-affairs/sunsets-team/issues/197

EVSS: Add other documents to events timeline

---

app/workers/education_form/create_daily_spool_files.rb
spec/jobs/education_form/create_daily_spool_files_spec.rb

shay wants the spool files to be `RPO_MMDDYYYY_vetsgov.spl`

change spool filenames

---

app/controllers/v0/disability_claims_controller.rb
app/serializers/disability_claim_base_serializer.rb
app/workers/disability_claim/request_decision.rb
db/migrate/20161104193741_add_requested_decision_to_disability_claim.rb
db/schema.rb
lib/evss/claims_service.rb
spec/jobs/disability_claim/request_decision_spec.rb
spec/lib/evss/claims_service_spec.rb
spec/request/disability_claims_spec.rb

Solves an issue where the job might not be processed for a while.
Closes https://github.com/department-of-veterans-affairs/sunsets-team/issues/187

EVSS: Set a flag when a user requests a decision

---

app/controllers/concerns/mhv_controller_concerns.rb
app/controllers/v0/sessions_controller.rb
app/models/user.rb
app/services/mhv_logging_service.rb
config/redis.yml
spec/factories/users.rb
spec/services/mhv_logging_service_spec.rb

MHV Login/Logout facility Integration

---

config/initializers/breakers.rb
lib/evss/base_service.rb
lib/evss/common_service.rb
spec/lib/evss/base_service_spec.rb
spec/services/disability_claim_service_spec.rb

Enable breakers for EVSS services

---

app/controllers/facilities_controller.rb

Found via [Sentry](http://sentry.vetsgov-internal/vets-gov/platform-api-development/issues/90/)

handle a missing bbox parameter

---

app/serializers/disability_claim_base_serializer.rb
spec/support/schemas/disability_claim.json
spec/support/schemas/disability_claims.json

Refs https://github.com/department-of-veterans-affairs/sunsets-team/issues/219

EVSS: Add phase back attributes to response

---

app/controllers/v0/disability_claims_controller.rb
app/controllers/v0/documents_controller.rb
spec/request/disability_claims_spec.rb

#Found via [Sentry](http://sentry.vetsgov-internal/vets-gov/platform-api-staging/issues/85/)

Handle missing claims

---

app/workers/education_form/create_daily_spool_files.rb

If there's a problem, we either expect it to resolve quickly, or want to wait until tomorrow.

Retry EDU job just 5 times

---

config/mvi_schema/mock_mvi_responses.yml.example

I got sick of users not matching up in dev and staging, so just decided to add them to the mock service. Please let me know if any of my formatting is off @kreek !

Adding mock users

---

docs/api/disability-benefits.md

Fixes https://github.com/department-of-veterans-affairs/sunsets-team/issues/232

EVSS: Update API docs

---

app/workers/education_form/create_daily_year_to_date_report.rb
spec/jobs/education_form/create_daily_year_to_date_report_spec.rb

closes department-of-veterans-affairs/edu-benefits-team/issues/108

Daily report show date range

---

app/models/mvi.rb
docs/api/user.md
lib/mvi/errors/errors.rb
lib/mvi/middleware/request/soap.rb
lib/mvi/middleware/response/soap.rb
lib/mvi/mock_service.rb
lib/mvi/responses/base.rb
lib/mvi/responses/find_candidate.rb
lib/mvi/service.rb
spec/lib/mvi/middleware/request/soap_spec.rb
spec/lib/mvi/middleware/response/soap_spec.rb
spec/lib/mvi/mock_service_spec.rb
spec/lib/mvi/responses/base_spec.rb
spec/lib/mvi/responses/find_candidate_spec.rb
spec/lib/mvi/service_spec.rb
spec/models/mvi_spec.rb
spec/support/schemas/profile.json

release-20161128a

---

app/controllers/application_controller.rb

For some exception types, there's no point in sending the data to Sentry because the exceptions do not indicate any actionable event. This adds a filter for ignoring them.
For reviewers, do you think we should also stop logging the errors as well?

skip Sentry for some exception types

---

docs/api/login.md

Doc has been updated for accuracy.

Update login doc

---

docs/api/login.md

release-20161201a

---

app/controllers/application_controller.rb
config/routes.rb

This reverts commit 445b8251f05968de2f25469f65d20b2405f4447a.

Revert "temporarily add endpoint that triggers a 500 error (#578)"

---

app/controllers/application_controller.rb
config/routes.rb

Today's Production Release - Jenkins problems require recreating #592

Release 20161205a

---

app/serializers/disability_claim_detail_serializer.rb

EVSS: Quickie fix for phase dates

---

app/controllers/v0/sessions_controller.rb
app/serializers/disability_claim_detail_serializer.rb

release-20161207b

---

app/services/mhv_logging_service.rb

Fixes: http://sentry.vetsgov-internal/vets-gov/platform-api-production/issues/293/
The logic for logout service was wrong, this simplifies and fixes, makes more readable.

Fix MHVLogoutService

---

spec/serializers/disability_claim_detail_serializer_spec.rb

release-20161209b

---

app/controllers/v0/sessions_controller.rb
app/models/vba_facility_adapter.rb
app/models/vha_facility_adapter.rb

release-20161212a

---

app/workers/education_form/create_daily_spool_files.rb
app/workers/education_form/delete_old_applications.rb
config/environments/production.rb
spec/jobs/education_form/delete_old_applications_spec.rb

release-20161216a

---

app/workers/education_form/delete_old_applications.rb
spec/jobs/education_form/delete_old_applications_spec.rb

release-20161215c

---

spec/lib/evss/auth_headers_spec.rb

Add a test to make sure the LoA still gets set properly even if there's a refactor of some kind.

EVSS: Add a test for LoA

---

app/models/vha_facility_adapter.rb
spec/lib/evss/auth_headers_spec.rb

release-20161219a

---

lib/evss/error_middleware.rb
spec/lib/evss/error_middleware_spec.rb
spec/support/vcr_cassettes/evss/claims/claim_with_errors.yml

Fixes https://github.com/department-of-veterans-affairs/sunsets-team/issues/282

EVSS: Reject responses with FATAL or ERROR severity

---

lib/evss/error_middleware.rb
spec/lib/evss/error_middleware_spec.rb
spec/support/vcr_cassettes/evss/claims/claim_with_errors.yml

release-20161220a

---

app/models/vha_facility_adapter.rb
spec/factories/vha_gis_records.rb
spec/models/vha_facility_adapter_spec.rb

Needed to fix breakage in production caused by GIS data changes.

Pv fl data changes

---

app/models/vha_facility_adapter.rb
spec/factories/vha_gis_records.rb
spec/models/vha_facility_adapter_spec.rb

* Needed to fix facility locator production issue.

release-20161221b

---

Gemfile
Gemfile.lock
app/workers/education_form/create_daily_spool_files.rb
config/sidekiq_scheduler.yml
spec/jobs/education_form/create_daily_spool_files_spec.rb

Per Shay, we should only send Spool Files on weekdays that do not have observed federal holidays on them

Only run CreateDailySpoolFiles on weekdays

---

Jenkinsfile
Jenkinsfile.branch_deploy

Also updating normal Jenkinsfile

Adding branch deploy Jenkinsfile

---

README.md
docs/setup/authentication_with_idme.md
docs/setup/edu_benefits.md
docs/setup/evss.md
docs/setup/facilities_locator.md
docs/setup/mhv.md
docs/setup/mvi.md

- Corrections for accuracy
- Moved all feature-specific info into separate .md files in `/docs/setup/`
- Make the README a bit shorter and easier to read

README.md Cleanup

---

docs/api/gi-api.md

First comprehensive draft of the API documentation.
What am I missing? Is anything unclear?
Closes department-of-veterans-affairs/vets.gov-team#951

GI API documentation

---

docs/api/gi-api.md

Production Release 20170202a

---

app/serializers/evss_claim_detail_serializer.rb
spec/fixtures/evss_claim/claim-with-documents.json
spec/serializers/evss_claim_detail_serializer_spec.rb

Related to https://github.com/department-of-veterans-affairs/sunsets-team/issues/303

Use upload date when present

---

app/controllers/v0/health_care_applications_controller.rb
lib/hca/enrollment_system.rb
lib/hca/service.rb
spec/lib/hca/enrollment_system_spec.rb

revert until the charter for hca login is signed

Revert "Hca login form changes"

---

app/workers/education_form/create_daily_year_to_date_report.rb
spec/jobs/education_form/create_daily_year_to_date_report_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/1082

Report header update

---

Jenkinsfile

Fixes builds failing due to deploy step

Fix job name

---

app/controllers/application_controller.rb
app/models/session.rb
lib/common/models/redis_store.rb
spec/lib/common/models/redis_store_spec.rb
spec/models/session_spec.rb

Reverts department-of-veterans-affairs/vets-api#801

Revert "Session Extension v2"

---

.overcommit.yml
app/workers/education_form/forms/base.rb
app/workers/education_form/forms/va1990.rb
app/workers/education_form/forms/va1995.rb
app/workers/education_form/templates/1995.erb
lib/tasks/edu.rake
spec/fixtures/education_benefits_claims/1995/kitchen_sink.json
spec/fixtures/education_benefits_claims/1995/kitchen_sink.spl
spec/fixtures/education_benefits_claims/1995/minimal.json
spec/fixtures/education_benefits_claims/1995/minimal.spl

We have a tentative 👍 on unifying the style of the EDU forms output for the backend systems. This is the bulk of the work to change the 1995 to look more like the 1990. The 22-1995 is not live right now, and this would be used in staging to generate additional samples and refinements.

22-1995 Output Restructuring (Spool Files)

---

app/controllers/application_controller.rb
app/controllers/v0/education_benefits_claims_controller.rb
app/controllers/v0/health_care_applications_controller.rb
app/controllers/v0/sessions_controller.rb
config/initializers/raven.rb
config/routes.rb
lib/common/exceptions/external/backend_service_exception.rb
lib/sentry_logging.rb
spec/controllers/application_controller_spec.rb
spec/lib/sentry_logging_spec.rb
spec/lib/sentry_logging_spec_helper.rb
spec/request/education_benefits_claims_request_spec.rb
spec/request/health_care_applications_request_spec.rb

**Problem**
Each piece of code was calling `Raven` in their own way.
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/1401
**This PR**
Put `Raven` calls into a module and include it as a mixin to the `ApplicationController`.

Sentry Logging Module

---

lib/tasks/connectivity.rake

Accompanies changes to SFTP connection from https://github.com/department-of-veterans-affairs/vets-api/pull/865

Adds EDU SFTP port to connectivity test

---

db/migrate/20170329210115_submission_changes_for1995.rb

This _should_ help fix the deploy failure on staging where it's unable to find the transferOfEntitlement attribute

Fix a migration failure in staging

---

app/workers/education_form/forms/base.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/1931

use constantize for edu form base

---

Gemfile
Gemfile.lock
app/mailers/failed_claims_report_mailer.rb
app/workers/evss/failed_claims_report.rb
config/sidekiq_scheduler.yml
spec/jobs/evss/failed_claims_report_spec.rb
spec/mailers/failed_claims_report_mailer_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/2052
i tested it in staging rails console and it works

Evss failed upload job

---

docs/api/edu-benefits.md

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/2051

Update edu benefits api documentation

---

app/controllers/v0/apidocs_controller.rb
app/swagger/requests/education_benefits_claims.rb
app/swagger/requests/health_care_applications.rb
app/swagger/responses/backend_service_error.rb
app/swagger/responses/validation_error.rb
spec/request/swagger_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/2294

Rainbows swagger documentation

---

Gemfile.lock
app/workers/education_form/templates/5495.erb
spec/fixtures/education_benefits_claims/5495/kitchen_sink.json
spec/fixtures/education_benefits_claims/5495/kitchen_sink.spl
spec/fixtures/education_benefits_claims/5495/simple.spl

For https://github.com/department-of-veterans-affairs/vets.gov-team/issues/2733

Add relativeVaFileNumber to 22-5495 output

---

app/serializers/education_benefits_claim_serializer.rb
app/workers/education_form/templates/5495.erb
spec/fixtures/education_benefits_claims/5495/kitchen_sink.spl
spec/fixtures/education_benefits_claims/5495/simple.spl

I know that these fields are in the json-schema, but they aren't in the vets-website form, and I'm confirmed that's intention.

Remove unused 22-5495 Fields

---

app/controllers/v0/messaging_preferences_controller.rb
app/controllers/v0/prescription_preferences_controller.rb
app/models/messaging_preference.rb
app/models/prescription_preference.rb
app/serializers/messaging_preference_serializer.rb
app/serializers/prescription_preference_serializer.rb
lib/rx/client.rb
lib/sm/client.rb
spec/lib/sm/client/preferences_spec.rb
spec/request/messaging_preferences_spec.rb
spec/request/prescriptions_request_spec.rb
spec/support/vcr_cassettes/sm_client/session.yml

Connected to https://github.com/department-of-veterans-affairs/vets.gov-team/issues/2685

Improvements for MHV notification preferences edge cases

---

app/models/messaging_preference.rb
app/models/prescription_preference.rb
config/locales/exceptions.en.yml
lib/common/exceptions/external/backend_service_exception.rb
lib/rx/client.rb
lib/sm/client.rb
spec/lib/rx/client_spec.rb
spec/lib/sm/client/preferences_spec.rb
spec/request/messaging_preferences_spec.rb
spec/request/prescriptions_request_spec.rb
spec/support/vcr_cassettes/rx_client/preferences/raises_a_backend_service_exception_when_email_includes_spaces.yml
spec/support/vcr_cassettes/sm_client/preferences/raises_a_backend_service_exception_when_email_includes_spaces.yml

Connects to https://github.com/department-of-veterans-affairs/vets.gov-team/issues/2767
Connects to: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/2768

Mhv preferences errors 2767 2768

---

app/controllers/v0/terms_and_conditions_controller.rb
app/models/terms_and_conditions.rb
db/migrate/20170519153047_create_mhv_ac_terms.rb
db/schema.rb

This creates the default terms for mhvac, clarifies the 404 a little bit, and fixes up an association.

Some tweaks for the terms and conditions

---

app/models/mhv_account.rb
config/mvi_schema/mock_mvi_responses.yml.example
config/settings.yml
spec/models/mhv_account_spec.rb

The logic is right, and the tests are pretty comprehensive, but not attached to either. In particular:
- initializing constant from settings seems off
- test cases could definitely be DRYer 
Open to suggestions for how, otherwise I'll look at this with fresh eyes tomorrow morning.

MhvAccount va_patient method

---

app/controllers/v0/in_progress_forms_controller.rb
spec/request/in_progress_forms_request_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/3023

in progress forms first or initialize bug

---

app/models/in_progress_form.rb
spec/models/in_progress_form_spec.rb
spec/request/in_progress_forms_request_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/3046

In progress forms serialize as json

---

app/controllers/concerns/mhv_controller_concerns.rb
app/controllers/v0/health_beta_registrations_controller.rb
app/models/health_beta_registration.rb
app/models/mhv_account.rb
app/serializers/user_serializer.rb
config/routes.rb
db/migrate/20170607043549_add_health_account_beta.rb
db/schema.rb
lib/health_beta.rb
spec/models/mhv_account_spec.rb
spec/request/prescriptions_request_spec.rb
spec/spec_helper.rb
spec/support/schemas/user_loa1.json
spec/support/schemas/user_loa3.json

Add a controller/model to record users being active in the feature beta.
Change the logic for the user serializer and controller auth methods based on whether user is active in beta. 
Beta-conditional code is on backend only.

Pv terms beta

---

config/evss/mock_gi_bill_status_response.yml.example

Connects to https://github.com/department-of-veterans-affairs/vets.gov-team/issues/3189

Add data to gibs mock response

---

spec/request/terms_and_conditions_request_spec.rb

Tested with `--seed 42804` on `da84be`

Fix another randomly failing spec

---

config/mvi_schema/mock_mvi_responses.yml.example

Adds 3 `CI EVSS  users:
- Gary Todd
- Jean Picard
- Srikanth Vanapalli
Source:
https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/EVSS%20Integration/Engineering%20Assets.md#ci
Note: Sublime Text removed lots of trailing white space

Add CI users to mock mvi data

---

config/mvi_schema/mock_mvi_responses.yml.example

The [newly added CI users](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/EVSS%20Integration/Engineering%20Assets.md#ci) were added using improper formatting.  This PR corrects that formatting

Mock MVI data wasnt formatted properly

---

lib/common/client/middleware/response/mhv_xml_html_errors.rb
spec/lib/common/client/middleware/response/response_middleware_spec.rb

Connects to: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/3443

Fixing MHVXmlHtmlErrors Middleware

---

config/evss/mock_letters_response.yml.example
lib/evss/letters/mock_service.rb
spec/controllers/v0/letters_controller_spec.rb
spec/lib/evss/letters/mock_service_spec.rb
spec/support/evss/mock_letters_response.yml

- adds all CI/INT users to mock data yaml
- data now listed by ssn then service method
- added error message if ssn or method keys are missing from yaml

added all CI/INT users to letters mock data

---

app/models/mhv_account.rb
spec/models/mhv_account_spec.rb

Fixes https://github.com/department-of-veterans-affairs/vets.gov-team/issues/3500

Default address if not present in MVI

---

app/models/mhv_account.rb
config/settings.yml
spec/models/mhv_account_spec.rb

Allows for testing in staging. Will have a devops PR to set the range accordingly in staging.

Make VHA facility range configurable

---

config/evss/mock_letters_response.yml.example
lib/evss/letters/letter.rb
spec/support/schemas/letter_base.json

Connects:
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/3687

Add certificate_of_eligibility to enum

---

app/models/mhv_account.rb
spec/models/mhv_account_spec.rb

Fixes https://github.com/department-of-veterans-affairs/vets.gov-team/issues/3748

Populate MHV is_veteran from user.veteran? indicator

---

app/serializers/post911_gi_bill_status_serializer.rb
app/swagger/requests/post911_gi_bill_statuses.rb
config/evss/mock_gi_bill_status_response.yml.example
lib/evss/base_service.rb
lib/evss/gi_bill_status/gi_bill_status_response.rb
spec/controllers/v0/post_911_gi_bill_statuses_controller_spec.rb
spec/lib/evss/gi_bill_status/service_spec.rb
spec/request/post911_gi_bill_status_request_spec.rb
spec/support/schemas/post911_gi_bill_status.json

connects: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/3803

Add active_duty and veteran_is_eligible to GIBS Response

---

app/swagger/requests/post911_gi_bill_statuses.rb
config/evss/mock_gi_bill_status_response.yml.example
lib/evss/gi_bill_status/entitlement.rb
lib/evss/gi_bill_status/gi_bill_status_response.rb
spec/lib/evss/gi_bill_status/service_spec.rb
spec/request/swagger_spec.rb
spec/support/schemas/entitlement.json
spec/support/schemas/post911_gi_bill_status.json
spec/support/vcr_cassettes/evss/gi_bill_status/gi_bill_status.yml

Connected Issue: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/3857
Before:
```
{
originalEntitlement: 75,
usedEntitlement: 40,
remainingEntitlement: 35
}
```
After:
```
{
originalEntitlement: {days: 3, months 3},
usedEntitlement: {days: 0, months: 2},
remainingEntitlement: (days: 3, months: 1)
}
```

Changed entitlement from an integer to an object with months and days

---

app/controllers/application_controller.rb
app/controllers/claims_base_controller.rb
app/controllers/v0/education_benefits_claims_controller.rb
app/controllers/v0/health_care_applications_controller.rb
spec/controllers/application_controller_spec.rb
spec/controllers/v0/burial_claims_controller_spec.rb
spec/rails_helper.rb
spec/request/education_benefits_claims_request_spec.rb
spec/request/health_care_applications_request_spec.rb
spec/support/model_helpers.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/3303

Ensure the form isn't saved after submitted

---

config/initializers/breakers.rb
lib/common/client/configuration/base.rb
lib/emis/military_information_configuration.rb
lib/emis/payment_configuration.rb
lib/emis/veteran_status_configuration.rb
lib/preneeds/configuration.rb

Add breakers for all services that use it

---

app/serializers/user_serializer.rb
spec/serializers/user_serializer_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/4050

Add expiration date to saved form profile info

---

lib/common/client/middleware/response/soap_parser.rb
spec/lib/common/client/middleware/response/soap_response_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/4197

log soap errors to sentry

---

app/controllers/claims_base_controller.rb
app/models/persistent_attachment.rb
app/models/persistent_attachment/pension_burial.rb
app/uploaders/claim_documentation/pension_burial/workflow.rb
config/locales/en.yml
db/migrate/20170807203358_remove_user_submitted_at_from_saved_claims.rb
db/schema.rb
spec/factories/burial_claim.rb
spec/factories/pension_claim.rb
spec/lib/workflow/task/shared/datestamp_pdf_task_spec.rb
spec/models/persistent_attachment/pension_burial_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/4246

remove timestamp from pdf

---

app/controllers/v0/in_progress_forms_controller.rb
spec/request/in_progress_forms_request_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/4270

save in progress error

---

app/models/in_progress_form.rb

Tanel did a look at their data and confirmed that these are the only lengths we should expect.

Allow more uuid lengths

---

spec/factories/mvi_profiles.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/4425

use state abbr in mvi profile

---

lib/pdf_fill/hash_converter.rb
spec/fixtures/pdf_fill/21P-530/simple.json

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/4439

530 pdf conversion error

---

Jenkinsfile.branch_deploy
Jenkinsfile.deploy

adds fix for [#4505](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/4505) for this repo

add pip upgrade to jenkinsfiles

---

lib/evss/claims_service.rb

@wyattwalter this removes the use of BenchmarkRequest for now.
Addresses department-of-veterans-affairs/vets.gov-team#4714

Remove use of BenchmarkRequest

---

app/controllers/application_controller.rb
app/controllers/v0/sessions_controller.rb
app/models/user.rb
app/serializers/user_serializer.rb
config/routes.rb
lib/saml/user.rb
lib/saml/user_attributes/dslogon.rb
lib/saml/user_attributes/id_me.rb
lib/saml/user_attributes/mhv.rb
spec/controllers/v0/sessions_controller_spec.rb
spec/lib/saml/dslogon_user_spec.rb
spec/models/mhv_account_spec.rb
spec/spec_helper.rb
spec/support/schemas/user_loa1.json
spec/support/schemas/user_loa3.json

Reverts department-of-veterans-affairs/vets-api#1363 again, so basically putting changes back.

Revert "Revert "basic changes to support identity improvement with backward c…"

---

lib/evss/letters/configuration.rb
lib/evss/pciu_address/configuration.rb

Addresses https://github.com/department-of-veterans-affairs/vets.gov-team/issues/4943

rename letters and pciuaddress services to be valid for statsd

---

app/models/form_profile.rb
app/models/user.rb
config/routes.rb
spec/models/user_spec.rb
spec/request/beta_registration_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/4993

Emis beta enrollment

---

app/controllers/v0/sessions_controller.rb
lib/benchmark/timer.rb
spec/controllers/v0/sessions_controller_spec.rb
spec/lib/benchmark/timer_spec.rb

Adding metrics for authentication. New users and login/logout timers.

Auth Metrics

---

app/controllers/v0/sessions_controller.rb
spec/controllers/v0/sessions_controller_spec.rb
spec/support/saml/saml_response_dslogon.xml

Statsd on per-context basis

---

app/controllers/v0/sessions_controller.rb

assuming your local test was successful, here is the patch.

use decorated version of saml_user

---

app/models/emis_redis/model.rb
app/models/emis_redis/veteran_status.rb
app/serializers/user_serializer.rb
spec/models/emis_redis/model_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/5051

handle emis empty responses better

---

app/controllers/v0/sessions_controller.rb

Also add additional tags for better metrics

Add Metrics To New Auth Endpoint

---

lib/data_migrations/education_program.rb
spec/lib/data_migrations/education_program_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/5125

bug in education program migration

---

app/controllers/v0/id_card_attributes_controller.rb
config/routes.rb
lib/vic/url_helper.rb
spec/request/id_card_attributes_request_spec.rb

Refactoring frontend to do a POST submission, so changing the API to return a JSON dict of URL + traits. Changed route/controller name to be more accurate.

Update to return url and traits separately for form submission by frontend

---

app/workers/education_form/create_spool_submissions_report.rb
config/sidekiq_scheduler.yml
spec/jobs/education_form/create_spool_submissions_report_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/5172

Spool report fix

---

app/controllers/v0/sessions_controller.rb
lib/saml/user.rb

Let's hold off on this until we debug locally in case any other changes needed, but I think this corrects the authn_context and connect params without breaking anything else.

mhv policy name update

---

config/sidekiq_scheduler.yml

Switch the currently running report `CreateDailyYearToDateReport` over to the requested `CreateDailyFiscalYearToDateReport`.

Switch daily report to fiscal year-to-date

---

Gemfile
Gemfile.lock
db/migrate/20170815232409_clean_up_education_benefits_data_transfer.rb

* rm zero downtime migrations
* migrate leftovers

Production Release 20171012c

---

app/controllers/v0/in_progress_forms_controller.rb
spec/request/in_progress_forms_request_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/5405

Error when attempting to delete saved form

---

app/models/emis_redis/model.rb
spec/models/emis_redis/model_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/5436

Emis prefill bug

---

app/workers/education_form/forms/va1990.rb
lib/data_migrations/education_program_remove_school.rb
rakelib/edu.rake
spec/fixtures/education_benefits_claims/1990/kitchen_sink.json
spec/fixtures/education_benefits_claims/1990/simple_ch33.json
spec/lib/data_migrations/education_program_remove_school_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/5261

Remove school field

---

app/uploaders/evss_claim_document_uploader.rb
spec/uploaders/evss_claim_document_uploader_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/5522

Evss doc upload bug

---

app/mailers/failed_claims_report_mailer.rb
app/mailers/spool_submissions_report_mailer.rb
app/mailers/year_to_date_report_mailer.rb
spec/mailers/failed_claims_report_mailer_spec.rb
spec/mailers/spool_submissions_report_mailer_spec.rb
spec/mailers/year_to_date_report_mailer_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/5558

remove josh from emails

---

lib/sftp_writer/remote.rb
spec/lib/sftp_writer/remote_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/5623

fix sftp close method

---

lib/pension_burial/service.rb
lib/workflow/task/pension_burial/upload.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/5673

Pension burial upload fix

---

app/controllers/v0/preneeds/burial_forms_controller.rb
app/models/preneeds/preneed_submission.rb
db/migrate/20171103140150_create_preneed_submissions.rb
db/schema.rb
spec/factories/preneeds/preneed_submissions.rb
spec/models/preneeds/preneed_submission_spec.rb
spec/request/preneeds/burial_forms_request_spec.rb

Persists successful Preneeds submissions. Will be following up non-successful submissions in next PR.

Added logging of successful submissions

---

app/services/evss_claim_service.rb
app/uploaders/evss_claim_document_uploader.rb
spec/uploaders/evss_claim_document_uploader_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/5793
i tested on dev and it works

document upload bug

---

app/models/persistent_attachments/pension_burial.rb
app/models/saved_claim/burial.rb
app/models/saved_claim/pension.rb
lib/workflow/task/pension_burial/upload.rb
spec/factories/burial_claim.rb
spec/factories/pension_claim.rb
spec/lib/workflow/task/pension_burial/upload_spec.rb
spec/models/persistent_attachments/pension_burial_spec.rb
spec/models/saved_claims/burial_spec.rb
spec/models/saved_claims/pension_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/5742
i tested in dev, with the right email it uploaded to the api http://sentry.vetsgov-internal/vets-gov/platform-api-development/issues/23279/
with a blank email it got sent to the sftp
http://sentry.vetsgov-internal/vets-gov/platform-api-development/issues/23280/

Pension api email

---

lib/data_migrations/uuid_unique_index.rb
rakelib/saved_forms_unique_index.rake
spec/lib/data_migrations/uuid_unique_index_spec.rb
spec/rails_helper.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/5730

Uuid change data migration

---

Jenkinsfile.deploy

Reflecting current jenkins configuration

Avoid purpose-specific jenkins labels

---

README.md
config/settings.yml
config/settings/development.yml
docs/setup/betamocks.md

Changes to turn MVI mocking on by default locally and updated docs.

Update mvi development settings

---

app/workers/education_form/generate_spool_files.rb
rakelib/jobs.rake
spec/jobs/education_form/generate_spool_files_spec.rb

shay requested we give names and SSNs of the spool files to be prioritized, she wanted us to also resubmit the eastern region spool file for that day.

Update spool resubmission job

---

app/workers/education_form/generate_spool_files.rb
rakelib/jobs.rake
spec/jobs/education_form/generate_spool_files_spec.rb

* update rake task
* separate files for each region

Production Deploy 2017113b

---

lib/saml/user_attributes/dslogon.rb
spec/lib/saml/dslogon_user_spec.rb

Links to https://github.com/department-of-veterans-affairs/vets.gov-team/issues/6001

DS Logon Bug Fix - set gender to nil if it is anything other than M / F

---

app/controllers/application_controller.rb
app/controllers/concerns/mhv_controller_concerns.rb
app/controllers/v0/post911_gi_bill_statuses_controller.rb
app/models/emis_redis/military_information.rb
app/models/form_profile.rb
app/models/form_profile/va1010ez.rb
app/models/gibs_not_found_user.rb
app/models/mhv_account.rb
app/workers/education_form/generate_spool_files.rb
db/migrate/20171107181828_create_gibs_not_found_users.rb
db/migrate/20171107183613_index_gibs_not_found_users_on_edipi.rb
db/schema.rb
lib/saml/settings_service.rb
rakelib/evss.rake
rakelib/jobs.rake
spec/jobs/education_form/generate_spool_files_spec.rb
spec/models/form_profile_spec.rb
spec/models/mhv_account_spec.rb
spec/request/attachments_request_spec.rb
spec/request/breakers_integration_spec.rb
spec/request/folders_request_spec.rb
spec/request/health_records_request_spec.rb
spec/request/message_drafts_request_spec.rb
spec/request/messages_request_spec.rb
spec/request/messaging_preferences_spec.rb
spec/request/post911_gi_bill_status_request_spec.rb
spec/request/prescriptions_request_spec.rb
spec/request/statsd_middleware_spec.rb
spec/request/swagger_spec.rb
spec/request/triage_teams_request_spec.rb

Resolves department-of-veterans-affairs/vets.gov-team#5892.

Only create and upgrade if user does not have preexisting MHV account.

---

app/controllers/v0/preneeds/burial_forms_controller.rb
app/models/preneeds/currently_buried_person.rb
spec/models/preneeds/currently_buried_person_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/6017

Sending nil cemeteryNumber to pre-need api

---

Gemfile.lock

Update vets-json-schema to v3.10.4 to support https://github.com/department-of-veterans-affairs/vets-json-schema/pull/167

Update vets-json-schema to v3.10.4

---

app/models/preneeds/applicant.rb
app/models/preneeds/attachment.rb
app/models/preneeds/burial_form.rb
app/models/preneeds/currently_buried_person.rb
lib/common/hash_helpers.rb
lib/preneeds/service.rb
spec/lib/common/hash_helpers_spec.rb
spec/lib/preneeds/service_spec.rb
spec/models/preneeds/currently_buried_person_spec.rb
spec/support/vcr_cassettes/preneeds/burial_forms/burial_form_with_attachments.yml

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/6244

Preneeds bugs

---

app/models/user.rb
spec/request/id_card_attributes_request_spec.rb

Production Release 20171128c

---

rakelib/pension_burial.rake

this was already added and run in production, adding it here in case we need to run it again

fix pension burial task

---

app/models/emis_redis/military_information.rb
spec/lib/emis/military_information_service_spec.rb
spec/models/emis_redis/military_information_spec.rb
spec/support/vcr_cassettes/emis/get_military_service_episodes/valid_no_end_date.yml

Treat as ending in the future for sorting purposes.
See https://github.com/department-of-veterans-affairs/vets.gov-team/issues/6297

Military service episodes may have a nil end date. 

---

app/models/emis_redis/military_information.rb
spec/lib/emis/military_information_service_spec.rb
spec/models/emis_redis/military_information_spec.rb
spec/support/vcr_cassettes/emis/get_military_service_episodes/valid_no_end_date.yml

Production Release 20171129b

---

app/models/id_card_announcement_subscription.rb
spec/models/id_card_announcement_subscription_spec.rb

* VIC announcement subscription email length limit
* Fix rubocop warning

Production Release 20171203hf2

---

rakelib/pension_burial.rake

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/6431
job ids scraped from sentry

Pension burial rerun jobs

---

lib/evss/configuration.rb
lib/evss/letters/configuration.rb
lib/evss/letters/download_configuration.rb
lib/evss/pciu_address/configuration.rb
rakelib/pension_burial.rake

Apologies for the delay getting this out today.

Production Release 20171204a

---

app/controllers/v0/post911_gi_bill_statuses_controller.rb
app/models/gibs_not_found_user.rb
spec/request/post911_gi_bill_status_request_spec.rb

Connects:
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/4139
Entire removal of table & model will happen once list has been gathered and sent to EVSS.

stop logging vet_not_found responses

---

config/betamocks/services_config.yml

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/6196

add emis services to config

---

Jenkinsfile

Enable deployment of staging via new model now:
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/5490

enable builds in staging

---

app/models/id_card_announcement_subscription.rb
rakelib/id_card_announcement_subscriptions.rake
spec/models/id_card_announcement_subscription_spec.rb

Includes total count of emails recorded and count of emails on the VA domain (va.gov). https://dsva.slack.com/archives/C7N19LS31/p1512621548000030
Also includes export tasks for VA and non-VA emails with offset and limit parameters.

VIC ID card announcement export features

---

rakelib/evss.rake

Adds the `created_at` value to the CSV dump of `GibsNotFoundUser` table.
The output takes the following form:
```
edipi,first_name,last_name,ssn,dob,created_at
1111122222,BILL,RYAN,123456789,1937-03-07,08 Dec 2017 22:03:42 UTC +0000
3333344444,GEORGE,WASHINGTON,123456789,1947-09-25,08 Dec 2017 22:21:27 UTC +0000
```

add timestamp to the csv dump

---

app/models/user.rb
spec/models/user_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/6718

Emis prefill edipi

---

app/models/emis_redis/military_information.rb
spec/models/emis_redis/military_information_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/6749

handle nil values in is_va_service_connected

---

Gemfile.lock
spec/factories/va1990.rb
spec/fixtures/education_benefits_claims/1990/kitchen_sink_active_duty.json
spec/fixtures/education_benefits_claims/1990/kitchen_sink_edu_prog.json
spec/jobs/education_form/create_daily_spool_files_spec.rb
spec/jobs/education_form/education_facility_spec.rb

Update vets-json-schema to include:
* Navy service branch for Preneeds
* Removal of school for 22-1990

Update vets-json-schema to v3.13.2

---

app/mailers/feedback_submission_mailer.rb
spec/mailers/feedback_submission_mailer_spec.rb

Speak now if you dont want to be on this emailing list.

add ppl to receive staging feedback emails

---

app/controllers/v0/apidocs_controller.rb
app/swagger/requests/maintenance_windows.rb
app/swagger/schemas/maintenance_windows.rb
spec/request/swagger_spec.rb

Also add swagger definition for maintenance windows API.

add swagger definition for maintenance_windows api

---

app/workers/maintenance/poll_pagerduty.rb
config/settings.yml
config/sidekiq_scheduler.yml
lib/pagerduty/configuration.rb
lib/pagerduty/maintenance_client.rb
spec/factories/maintenance_windows.rb
spec/jobs/maintenance/poll_pagerduty_spec.rb
spec/lib/pagerduty/client_spec.rb
spec/rails_helper.rb
spec/support/pagerduty/maintenance_windows_page_1.json
spec/support/pagerduty/maintenance_windows_page_2.json
spec/support/pagerduty/maintenance_windows_simple.json

Replaces #1622, rebased on top of Wyatt's changes.

Pv maintenance worker

---

app/controllers/application_controller.rb
app/controllers/v0/sessions_controller.rb
lib/mvi/service.rb
lib/sentry_logging.rb
spec/controllers/application_controller_spec.rb
spec/controllers/v0/sessions_controller_spec.rb
spec/lib/mvi/service_spec.rb
spec/request/burial_claims_spec.rb
spec/request/education_benefits_claims_request_spec.rb
spec/request/health_care_applications_request_spec.rb
spec/request/pension_claims_controller_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/8280

improving sentry searchability

---

config/sidekiq_scheduler.yml

Increase polling frequency for testing.

increase frequency of PD polling

---

lib/mvi/models/mvi_profile.rb
lib/mvi/responses/id_parser.rb
lib/mvi/responses/profile_parser.rb
spec/factories/mvi_profiles.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/8557

add sec id to mvi id parser 

---

app/controllers/v0/vic/vic_submissions_controller.rb
spec/controllers/v0/vic/vic_submissions_controller_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/8608

fix user auth for vic

---

lib/vic/service.rb
spec/lib/vic/service_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/8618

dont send help text in title 38

---

app/uploaders/profile_photo_attachment_uploader.rb
app/uploaders/supporting_documentation_attachment_uploader.rb
app/uploaders/uploader_virus_scan.rb
lib/common/virus_scan.rb
lib/shrine/plugins/validate_virus_free.rb
spec/uploaders/uploader_virus_scan_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/8628

Vic virus scan

---

lib/vic/service.rb
spec/lib/vic/service_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/8647

Pass case number back to front end in response

---

spec/lib/hca/validations_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/8684

fix rspec timing error in hca test

---

app/controllers/v0/vic/vic_submissions_controller.rb
spec/controllers/v0/vic/vic_submissions_controller_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/8787

clear saved form after submission

---

app/uploaders/reencode_images.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/8635

Strip EXIF data from VIC image uploads

---

app/models/form_attachment.rb
app/workers/vic/submission_job.rb
spec/jobs/vic/submission_job_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/8856
Wasn't sure if we wanted to be deleting attachments along with the files themselves, so I included that. Let me know if it needs to be taken out

Delete uploads from s3

---

Jenkinsfile

Need this to cleanup the builds of long-lived branches (primarily master at this point) in Jenkins for the multi-branch pipeline jobs.

add cleanup to pipeline config

---

lib/saml/user_attributes/id_me.rb
spec/lib/saml/idme_user_spec.rb

This is attempting to fix / resolve this issue which happens sporadically in production:
http://sentry.vetsgov-internal/vets-gov/platform-api-production/issues/28821/

Fixing issue in idme saml response

---

app/workers/vic/submission_job.rb
lib/vic/service.rb
spec/lib/vic/service_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/8824

Vic filename change

---

app/controllers/v0/vic/profile_photo_attachments_controller.rb
spec/controllers/v0/vic/profile_photo_attachments_controller_spec.rb

Send a 404 when the guid can't be found

VIC Photo download 404 when matching GUID can't be found

---

app/workers/vic/submission_job.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/8927

vic submission job bug

---

lib/vic/service.rb
spec/lib/vic/service_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/8947

vic handle mvi not found and emis not found

---

app/uploaders/log_metrics.rb
app/uploaders/profile_photo_attachment_uploader.rb
app/uploaders/supporting_documentation_attachment_uploader.rb
spec/uploaders/log_metrics_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/8958

Vic metrics

---

lib/vic/service.rb
spec/lib/vic/service_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/8965

vic - use random filename for tmp file

---

Gemfile.lock

http://jenkins.vetsgov-internal/blue/organizations/jenkins/testing%2Fvets-api/detail/vic-prod-config/3/pipeline
security vulnerability in current version

update ruby saml

---

app/controllers/v0/vic/base_controller.rb
app/controllers/v0/vic/profile_photo_attachments_controller.rb
app/controllers/v0/vic/supporting_documentation_attachments_controller.rb
app/controllers/v0/vic/vic_submissions_controller.rb
app/workers/vic/attachment_upload_job.rb
app/workers/vic/submission_job.rb
lib/vic/tag_sentry.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/8996

vic sentry tagging

---

lib/vic/service.rb

Reverts department-of-veterans-affairs/vets-api#1741

Revert "change salesforce host"

---

app/models/session.rb
spec/models/session_spec.rb

Related to : https://github.com/department-of-veterans-affairs/vets-api/pull/1699
The above PR contains a fairly high amount of complexity.  This PR is to help determine if that complexity is worth it.

Sentry monitoring to see number of Sessions that reach max session duration

---

lib/vic/service.rb
spec/lib/vic/service_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/9158

vic submission error

---

rakelib/redis.rake

Facilitates load testing of an authenticated API endpoint - requires an input file containing one or more JSON dicts of all of the Redis data for a user (or a simulacrum thereof). Eventually want to write a script that pulls this from vets-api-mockdata directly.

 Rake task to synthesize authenticated sessions from a file 

---

lib/saml/user.rb
spec/lib/saml/idme_user_spec.rb

I'm trying to debug this issue which started happening a lot more as of February 27:
http://sentry.vetsgov-internal/vets-gov/platform-api-production/issues/33842/

adding additional context to debug an issue in saml parsing

---

app/workers/submit_saved_claim_job.rb
spec/jobs/submit_saved_claim_job_spec.rb

Change vets.gov to Vets.gov in pension/burial upload metadata

---

lib/pension_burial/service.rb

This will allow us to capture the full metadata of the submissions for correlation with the central mail api team.

Log Pension/Burial request metadata

---

config/form_profile_mappings/22-1990E.yml
config/form_profile_mappings/22-5490.yml
config/form_profile_mappings/22-5495.yml
spec/models/form_profile_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/9334

Education form prefill changes

---

app/models/base_facility.rb
spec/models/base_facility_spec.rb

It bothers me a bit that order matters, but I'd like to match old behavior as much as possible so that we limit any impact. Let me know what you think about this approach.

order hours by weekday for show

---

app/controllers/application_controller.rb
app/controllers/preneeds_controller.rb
app/controllers/v0/education_benefits_claims_controller.rb
app/controllers/v0/evss_claims_controller.rb
app/controllers/v0/health_care_applications_controller.rb
app/controllers/v0/in_progress_forms_controller.rb
app/workers/education_form/create_daily_fiscal_year_to_date_report.rb
app/workers/education_form/create_daily_spool_files.rb
app/workers/education_form/create_daily_year_to_date_report.rb
app/workers/education_form/create_spool_submissions_report.rb
app/workers/education_form/delete_old_applications.rb
app/workers/evss/create_user_account_job.rb
app/workers/evss/delete_old_claims.rb
app/workers/evss/document_upload.rb
app/workers/evss/failed_claims_report.rb
app/workers/evss/request_decision.rb
app/workers/in_progress_form_cleaner.rb
app/workers/process_file_job.rb
lib/pension_burial/tag_sentry.rb
lib/sentry/tag_rainbows.rb
lib/vic/tag_sentry.rb
spec/request/education_benefits_claims_request_spec.rb
spec/request/health_care_applications_request_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/9466

tag all rainbows sentry errors

---

lib/hca/validations.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/9494

Extend Future Discharge Date from 180 days to 2 years

---

app/policies/emis_policy.rb
spec/models/user_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/9574

user must have edipi for emis

---

lib/common/client/base.rb
spec/lib/evss/letters/service_spec.rb
spec/lib/mvi/service_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/9577

don't log timeout errors twice

---

lib/common/client/middleware/response/soap_parser.rb
spec/lib/common/client/middleware/response/soap_response_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/9502

use Raven.extra_context for soap errors

---

app/controllers/v0/apidocs_controller.rb
app/swagger/requests/address.rb
app/swagger/requests/appeals.rb
app/swagger/requests/backend_statuses.rb
app/swagger/requests/bb/health_records.rb
app/swagger/requests/burial_claims.rb
app/swagger/requests/education_benefits_claims.rb
app/swagger/requests/feedbacks.rb
app/swagger/requests/gibct/calculator_constants.rb
app/swagger/requests/gibct/institutions.rb
app/swagger/requests/health_care_applications.rb
app/swagger/requests/in_progress_forms.rb
app/swagger/requests/letters.rb
app/swagger/requests/maintenance_windows.rb
app/swagger/requests/messages/folders.rb
app/swagger/requests/messages/message_drafts.rb
app/swagger/requests/messages/messages.rb
app/swagger/requests/messages/triage_teams.rb
app/swagger/requests/pension_claims.rb
app/swagger/requests/post911_gi_bill_statuses.rb
app/swagger/requests/prescriptions/trackings.rb

Needs more work to categorize some of the remaining endpoints but wanted to put this up for reference. @jkassemi feel free to push to this branch as well if you do any cleanup.

First pass at some swagger endpoint organization

---

app/controllers/v0/health_care_applications_controller.rb
lib/common/client/base.rb
lib/hca/service.rb
lib/sentry_logging.rb
spec/jobs/education_form/create_daily_spool_files_spec.rb
spec/jobs/facilities/access_data_download_spec.rb
spec/jobs/maintenance/poll_pagerduty_spec.rb
spec/lib/bb/client_spec.rb
spec/lib/hca/service_spec.rb
spec/lib/mvi/responses/profile_parser_spec.rb
spec/lib/sentry_logging_spec_helper.rb
spec/request/health_care_applications_request_spec.rb
spec/services/mhv_account_type_service_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/8607

Improve Sentry logging for HCA errors

---

config/initializers/raven.rb
lib/evss/claims_service.rb
lib/evss/documents_service.rb
lib/sentry/ignored_error.rb
lib/sentry/rescue_evss_errors.rb
rakelib/connectivity.rake
spec/lib/evss/claims_service_spec.rb
spec/lib/evss/documents_service_spec.rb
spec/support/vcr_cassettes/evss/claims/claims_with_errors.yml
spec/support/vcr_cassettes/evss/documents/upload_with_errors.yml

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/9659

Sentry ignored error

---

app/controllers/claims_base_controller.rb
app/models/central_mail_claim.rb
app/models/central_mail_submission.rb
app/models/saved_claim/burial.rb
app/models/saved_claim/pension.rb
app/serializers/central_mail_submission_serializer.rb
app/workers/submit_saved_claim_job.rb
config/routes.rb
db/migrate/20180404214912_add_state_to_saved_claims.rb
db/migrate/20180404230656_add_guid_index_to_saved_claims.rb
db/schema.rb
lib/pension_burial/service.rb
spec/controllers/v0/burial_claims_controller_spec.rb
spec/jobs/submit_saved_claim_job_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/9702

Pension submission change

---

lib/evss/claims_service.rb
lib/evss/documents_service.rb
lib/evss/error_middleware.rb
lib/sentry/rescue_evss_errors.rb

department-of-veterans-affairs/vets.gov-team#9659

refactor RescueEVSSErrors

---

app/models/saved_claim.rb
app/models/saved_claim/burial.rb
app/models/saved_claim/pension.rb
spec/lib/saved_claims_spec_helper.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/9937

change saved claim confirmation code to just be the uuid

---

app/models/saved_claim.rb
app/models/saved_claim/burial.rb
app/models/saved_claim/education_benefits/va1990.rb
app/models/saved_claim/education_benefits/va1990e.rb
app/models/saved_claim/education_benefits/va1990n.rb
app/models/saved_claim/education_benefits/va1995.rb
app/models/saved_claim/education_benefits/va5490.rb
app/models/saved_claim/education_benefits/va5495.rb
app/models/saved_claim/pension.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/9966

remove unused saved_claim code

---

db/migrate/20180414001259_persistent_attachment_indexes.rb
db/schema.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/9965

add missing indexes to persistent_attachments

---

app/controllers/v0/profile/personal_informations_controller.rb

Getting these Sentry log errors:  
```
NoMethodErrorapp/serializers/personal_information_serializer.rb in gender at line 7
```
http://sentry.vetsgov-internal/vets-gov/platform-api-staging/issues/36483/events/887204/
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/10023

Adds sentry logging to debug controller issue

---

lib/pension_burial/service.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/10080

remove pension burial testing logging

---

app/controllers/v0/profile/personal_informations_controller.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/10023
After testing users in staging, sentry revealed no issues.

Removing sentry debugging

---

lib/sentry/processor/pii_sanitizer.rb
spec/lib/sentry/processor/pii_sanitizer_processor_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/10148

filter pii from pension burial sentry logs

---

lib/vic/service.rb
spec/lib/vic/service_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/10099

combine all discharge documentation uploads into a single pdf

---

app/workers/central_mail/submit_saved_claim_job.rb
spec/jobs/central_mail/submit_saved_claim_job_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/10241

pension burial invalid zipcode

---

app/workers/education_form/create_daily_fiscal_year_to_date_report.rb
app/workers/education_form/create_daily_spool_files.rb
config/initializers/sidekiq.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/10247

CreateDailySpoolFiles being created twice

---

lib/common/hash_helpers.rb
spec/lib/common/hash_helpers_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/10234

Preneed Submission Error when someone is buried under the sponsor's eligibility

---

lib/hca/enrollment_system.rb

remove `zipcode` references from hca/enrollment_system

---

app/controllers/concerns/vet360/writeable.rb
app/controllers/v0/addresses_controller.rb
app/controllers/v0/profile/alternate_phones_controller.rb
app/controllers/v0/profile/emails_controller.rb
app/controllers/v0/profile/full_names_controller.rb
app/controllers/v0/profile/primary_phones_controller.rb
app/controllers/v0/profile/service_histories_controller.rb
app/policies/evss_policy.rb
spec/spec_helper.rb

Reverts department-of-veterans-affairs/vets-api#1921

Revert "Adds temporary logging to debug Profile UAT issues in prod"

---

app/controllers/v0/health_care_applications_controller.rb
app/workers/hca/submission_job.rb
lib/hca/soap_parser.rb
spec/jobs/hca/submission_job_spec.rb
spec/lib/hca/soap_parser_spec.rb
spec/request/health_care_applications_request_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/10286

stop hca submission job if validation error detected

---

lib/hca/enrollment_system.rb
spec/lib/hca/enrollment_system_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/10415

Hca zipcode bug

---

app/controllers/v0/health_care_applications_controller.rb
spec/request/health_care_applications_request_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/10430

hca save in progress form not cleared after submission

---

app/controllers/concerns/vet360/writeable.rb
app/controllers/v0/addresses_controller.rb
app/controllers/v0/profile/alternate_phones_controller.rb
app/controllers/v0/profile/emails_controller.rb
app/controllers/v0/profile/full_names_controller.rb
app/controllers/v0/profile/primary_phones_controller.rb
app/controllers/v0/profile/service_histories_controller.rb
app/policies/evss_policy.rb
spec/spec_helper.rb

Reverts department-of-veterans-affairs/vets-api#1925

"Adds temporary logging to debug Profile UAT issues in prod"

---

modules/vba_documents/app/workers/vba_documents/upload_processor.rb
modules/vba_documents/spec/jobs/upload_processor_spec.rb

Fixes https://github.com/department-of-veterans-affairs/vets-contrib/issues/140
Added vanity metric logging for number of pdfs (content + attachments)

VBADocuments: Set timestamp based on initial upload time

---

modules/vba_documents/app/controllers/vba_documents/v0/uploads_controller.rb
modules/vba_documents/app/models/vba_documents/upload_submission.rb
modules/vba_documents/app/workers/vba_documents/upload_processor.rb
modules/vba_documents/spec/jobs/upload_processor_spec.rb
modules/vba_documents/spec/models/upload_submission_spec.rb
modules/vba_documents/spec/request/uploads_request_spec.rb

…ssions
Resolves department-of-veterans-affairs/vets-contrib#142

VBADocuments: Propagate X-Consumer-Username header to source field in submisssion

---

app/workers/preneeds/delete_old_uploads.rb
config/sidekiq_scheduler.yml
spec/jobs/preneeds/delete_old_uploads_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/10476

delete old attachment uploads for preneeds

---

lib/common/client/middleware/response/facility_parser.rb
spec/factories/vha_facilities.rb
spec/request/va_facilities_request_spec.rb

Add audiology and optometry to the services we can indicate from wait time data

indicate audiology and optometry via wait time data

---

app/uploaders/preneed_attachment_uploader.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/3767

add virus scan to preneed uploads

---

spec/rakelib/vet360_spec.rb

Suppress rake tasks printing to stdout during test runs.

Suppress rake stdout during tests

---

config/initializers/breakers.rb
lib/vet360/contact_information/configuration.rb
lib/vet360/service.rb

Closes [#10719](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/10719)

Configure breakers for vet360

---

app/controllers/v0/id_card_attributes_controller.rb
lib/vic/id_card_attribute_error.rb
spec/request/id_card_attributes_request_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/10704

Change error codes for new VIC error messages

---

modules/vba_documents/README.yml
modules/vba_documents/app/workers/vba_documents/upload_processor.rb
modules/vba_documents/spec/jobs/upload_processor_spec.rb

Ref https://github.com/department-of-veterans-affairs/vets-contrib/issues/166

VBADocuments: Add validation of fileNumber according to CMAPI reqs

---

app/controllers/v0/mhv_accounts_controller.rb
config/routes.rb
spec/request/mhv_accounts_request_spec.rb

Just trying this out and seeing if you think this makes sense. I've got a working local test with the F/E using the separate actions.

Split MHV create and upgrade actions.

---

app/workers/hca/submission_job.rb

remove line to force failure of HCA application for oddball/adhocteam/va addresses

remove HCA force failure

---

Gemfile.lock

upgrade sprockets

---

config/locales/exceptions.en.yml
spec/lib/common/exceptions/sentry_ignored_gateway_timeout_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/11061

SentryIgnoredGatewayTimeout bug

---

config/locales/exceptions.en.yml

Closes [11070](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/11070)

Map missing vet360 error codes 305 & 307

---

app/swagger/schemas/vet360/contact_information.rb
spec/serializers/user_serializer_spec.rb
spec/support/vet360/stub_vet360.rb

Small bug snuck in that makes the user object render in an error state. This fixes it. The frontend team has been using an older version which renders correctly, this is just a patch so it doesn't come up in the future.

Vet360 Swagger Doc Fix

---

app/models/form_profiles/va1990.rb
lib/vet360/models/address.rb
lib/vet360/models/telephone.rb
spec/factories/vet360/addresses.rb
spec/lib/vet360/models/address_spec.rb
spec/lib/vet360/models/telephone_spec.rb
spec/models/form_profile_spec.rb
spec/support/vcr_cassettes/vet360/contact_information/delete_address_success.yml
spec/support/vcr_cassettes/vet360/contact_information/post_address_success.yml
spec/support/vcr_cassettes/vet360/contact_information/post_address_w_id_error.yml
spec/support/vcr_cassettes/vet360/contact_information/put_address_ignore_eed.yml
spec/support/vcr_cassettes/vet360/contact_information/put_address_success.yml

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/11148

Vets360 1990

---

app/controllers/v0/mhv_accounts_controller.rb
app/models/mhv_account.rb
app/models/user.rb
app/policies/mhv_account_creation_policy.rb
app/policies/mhv_prescriptions_policy.rb
app/serializers/mhv_account_serializer.rb
app/services/mhv_account_type_service.rb
app/services/mhv_accounts_service.rb
config/routes.rb
config/settings.yml
lib/mvi/models/mvi_profile.rb
lib/mvi/responses/profile_parser.rb
spec/factories/mhv_accounts.rb
spec/factories/mvi_profiles.rb
spec/lib/mvi/responses/profile_parser_spec.rb
spec/models/mhv_account_spec.rb
spec/models/user_spec.rb
spec/request/mhv_accounts_request_spec.rb
spec/request/user_request_spec.rb
spec/services/mhv_account_type_service_spec.rb
spec/services/mhv_accounts_service_spec.rb
spec/support/mvi/find_candidate_multiple_mhv_response.xml

This reverts commit 1f5b15265696577e77b2a4d52fbc587fa52ff000.

Revert "Mhv account creation cleanup (#1899)"

---

lib/mvi/models/mvi_profile.rb
lib/mvi/models/mvi_profile_address.rb

Should remove the need to run `bin/spring stop` as much between specs

extract MviProfileAddress from MviProfile

---

app/models/form_profile.rb
app/models/form_profiles/va1990.rb
config/routes.rb
spec/models/form_profile_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/11374

use beta registration for v360 prefill

---

config/locales/exceptions.en.yml

Closes [#11368](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/11368)
Added additional ADDRVAL error codes which are passed through from Spectrum.

Map Spectrum error codes

---

app/models/form_profile.rb
app/models/form_profiles/va1990.rb
config/routes.rb
spec/models/form_profile_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/11465
removes beta registration for vets360 prefill, UAT already done in production and ready to go live

remove beta registration for vets360 prefill

---

app/models/emis_redis/military_information.rb
app/models/form_profiles/va526ez.rb
lib/evss/disability_compensation_form/data_translation.rb
spec/models/emis_redis/military_information_spec.rb

moves 'fixing' the plural service branch name to the data translator, temporary disability strips chars fix for user testing.

526 update service name and disability name

---

lib/evss/disability_compensation_form/data_translation.rb
spec/lib/evss/disability_compensation_form/data_translation_spec.rb
spec/support/disability_compensation_form/evss_submission.json

Changing `National Oceanic &amp; Atmospheric Administration` to `National Oceanic & Atmospheric Administration` per EVSS

Update data translation

---

app/models/form_profile.rb
spec/factories/mvi_profiles.rb
spec/models/form_profile_spec.rb

fix form_profile_spec specs

---

app/controllers/v0/mhv_accounts_controller.rb
app/models/mhv_account.rb
app/models/user.rb
app/policies/mhv_account_creation_policy.rb
app/policies/mhv_prescriptions_policy.rb
app/serializers/mhv_account_serializer.rb
app/serializers/user_serializer.rb
app/services/mhv_account_type_service.rb
app/services/mhv_accounts_service.rb
config/routes.rb
config/settings.yml
lib/mvi/models/mvi_profile.rb
lib/mvi/responses/profile_parser.rb
spec/factories/mhv_accounts.rb
spec/factories/mvi_profiles.rb
spec/lib/mvi/responses/profile_parser_spec.rb
spec/models/mhv_account_spec.rb
spec/models/user_spec.rb
spec/request/mhv_accounts_request_spec.rb
spec/request/user_request_spec.rb
spec/serializers/user_serializer_spec.rb
spec/services/mhv_account_type_service_spec.rb
spec/services/mhv_accounts_service_spec.rb
spec/support/mvi/find_candidate_multiple_mhv_response.xml
spec/support/schemas/user_loa1.json
spec/support/schemas/user_loa3.json
spec/support/vcr_cassettes/complex_interaction/internal_interactions.yml

Reverts department-of-veterans-affairs/vets-api#2178

Revert "Mhv upgrade launch"

---

app/models/base_facility.rb

Fixes #12043
Dental Services was missed in the initial list of services. We have the data but were unable to search for it specifically.

adding dental services to health

---

lib/gibft/service.rb

fix gibft username

---

Gemfile.lock

update json schema

---

app/models/mhv_account.rb
app/workers/mhv/account_statistics_job.rb

We added metrics for MhvAccount creation but were missing some numbers and have tracked down the scenario covered in this PR

adding a scope and stat for a scenario we discovered via data

---

app/models/form_profiles/complaint_tool.rb

Feedback Tool returnUrl change
automated
verify frontend forms are prefilled

update Feedback Tool returnURL

---

lib/gibft/service.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/12559
add prod and uat salesforce usernames

Salesforce username fix

---

config/settings.yml

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/11955
update cert paths in settings.yml to match the paths in readme.md
tested `File.read(Settings.saml.cert_path)`

update settings yml to match saml certificate setup instructions

---

config/routes.rb

Adds `claim-increase` to the available beta services defined in routes

add claim-increase beta route

---

app/models/async_transaction/evss/va526ez_submit_transaction.rb

Using `scope` declarations in models will return `all` rows if the results would have been `nil` instead. The find/where checks have now been moved their respective class methods.
spec tests and local console testing.
Testing via staging.

Remove scope  declarations

---

app/workers/evss/disability_compensation_form/submit_form526.rb

We want to extend the retry time from ~8 hours to ~24 hours. According to this https://github.com/mperham/sidekiq/issues/2168 retries need to be set to 13 to get about a days worth of retrying from the job (about 25 hours). 
spec tests.
Staging, possibly.

Increase retry count

---

lib/gibft/service.rb

update gibft settings to work in dev

update gibft settings to work in dev

---

Gemfile.lock
app/models/gi_bill_feedback.rb
spec/factories/gi_bill_feedback.rb
spec/fixtures/gibft/transform_form.json

use the last four digits of ssn from form in the profile data ssn field
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/13464
test in dev

last four digits of ssn support for gibft backend

---

Gemfile.lock

A front end deploy requires the json schema version in the api to be bumped up to current.
None.
None.

Update json schema version for deploy

---

Gemfile.lock

Yet another json schema version bump.
None.
None.

Update json schema version

---

app/models/form_profiles/va21686c.rb

These changes update the 686 form return URL.

Update 686 form return URL

---

app/workers/evss/disability_compensation_form/submit_uploads.rb
spec/jobs/evss/disability_compensation_form/submit_uploads_spec.rb

Updated setting of file_body
Unit tests
Staging integration tests

Submit 526 uploads update file body

---

Gemfile.lock
app/models/gi_bill_feedback.rb
spec/factories/gi_bill_feedback.rb
spec/fixtures/gibft/transform_form.json
spec/fixtures/gibft/transform_form_no_user.json
spec/models/gi_bill_feedback_spec.rb

fix gi bill feedback submission errors
tested on staging
test on staging/dev on website

Feedback submission errors

---

Gemfile.lock
app/models/gi_bill_feedback.rb
spec/factories/gi_bill_feedback.rb
spec/fixtures/gibft/transform_form.json
spec/fixtures/gibft/transform_form_no_user.json

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/13880
send facility code to salesforce
tested on dev in console
test on website

feedback tool facility code backend 

---

app/controllers/v0/sessions_controller.rb
spec/controllers/v0/sessions_controller_spec.rb

fix this error http://sentry.vetsgov-internal/vets-gov/platform-api-production/issues/43730/
don't create account if current_user is nil

handle nil current_user in async_create_evss_account

---

config/settings.yml
lib/saml/url_service.rb

Fixes: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/13806
Tested with MHV user: petetwelve
Tested with DS Logon user: bragan.b.christesen
Tested with ID.me user: personal account
Test again on staging.vets.gov and staging.va.gov

Support white-label for identity verification and mfa flows

---

bin/setup-osx
config/environment.rb
db/schema.rb
docker-compose.test.yml
docker-compose.yml
docs/setup/native.md
modules/va_facilities/db/migrate/20181017120746_enable_post_gis_extension.rb

Separate it out to address concerns in department-of-veterans-affairs/vets-api#2363
Successfully migrates
None

Add migration to enable postgis extension

---

config/locales/exceptions.en.yml

Stems from Sentry logs in production:
http://sentry.vetsgov-internal/vets-gov/platform-api-production/issues/48642/

Adds new Vet360 error code

---

config/settings.yml
lib/mvi/service.rb
spec/lib/mvi/service_spec.rb

We are turning off the direct edipi search in favor of the attribute search to leverage mvi orchestration. We are putting it behind a toggle so we can continue to test on staging.
spec coverage

adding an mvi setting for edipi search

---

app/controllers/application_controller.rb
spec/request/example_root_spec.rb

example controller gets tested by deploy script using aws instance ipaddress, no virtual host
local specs
the build should just build

Fix broken build

---

lib/saml/url_service.rb
spec/request/connected_applications_request_spec.rb

fix mapping for api.va.gov

---

spec/request/swagger_spec.rb

Fixes a broken spec on master
local unit tests

fix profile/connected_applications swagger spec

---

Gemfile.lock

Updates `rack-protection`.
Command I ran:
```
bundle update --conservative rack-protection
```
Local rspec.
None.

Updates rack-protection

---

app/controllers/v0/sessions_controller.rb
config/routes.rb
lib/saml/url_service.rb
spec/controllers/v0/sessions_controller_spec.rb
spec/lib/saml/url_service_spec.rb

gets rid of the `sessions/logout`, handles everything in `sessions/slo/new`
1 less redirect, and we can destroy everything in a get request so no worry about Set-Cookie not working.
Just specs, need to verify on staging. For both va and vets
Verify on staging before shipping to production.

Fix sso cookie not getting deleted

---

Gemfile.lock
app/controllers/application_controller.rb
app/controllers/v0/sessions_controller.rb

Adding Logging to SSO

---

lib/gibft/service.rb
spec/lib/gibft/service_spec.rb

update gibft username to use the rdtcdsit username
tested in staging

Gibft dev username change

---

lib/mvi/responses/profile_parser.rb
spec/lib/mvi/responses/profile_parser_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15086
make edipi nil when invalid, when is blank string edipi wanted?

make edipi nil when invalid

---

lib/central_mail/configuration.rb
lib/common/client/base.rb
lib/emis/configuration.rb
lib/preneeds/configuration.rb
lib/preneeds/logged_configuration.rb

fix breakers middleware order in rainbows services

rainbows breakers changes

---

lib/evss/disability_compensation_form/data_translation_all_claim.rb
spec/lib/evss/disability_compensation_form/data_translation_all_claim_spec.rb
spec/support/disability_compensation_form/all_claims_evss_submission.json
spec/support/disability_compensation_form/all_claims_fe_submission.json

FE changes have been made to pass the `treatedDisabilityNames` field form form 526 submissions. The data translator has been updated to handle this appropriately.
spec
staging e2e.

Form526 parse treament center disabilities

---

app/models/saved_claim/disability_compensation.rb
rakelib/form526.rake

The `update_types` rake task didnt work correctly when using `.save` on the row. Most likely the save would revert the `type` assignment back to the base class since thats what the model the claim is working off of. To circumvent this `update_all` is used which will bypass the validations.
local/staging
staging

Update 526 migration rake task

---

lib/gibft/service.rb

the gibft team said this was the correct username for production

change prod gibft username

---

lib/evss/disability_compensation_form/data_translation_all_claim.rb
spec/lib/evss/disability_compensation_form/data_translation_all_claim_spec.rb
spec/support/disability_compensation_form/all_claims_evss_submission.json
spec/support/disability_compensation_form/all_claims_fe_submission.json

Various small changes to the data translator for form 526 all claims. These changes came about due to vets json schema changes and/or necessitated due to front end changes.
spec tests.
staging e2e testing

Form526 submission payload fixes

---

Gemfile.lock
lib/evss/disability_compensation_form/data_translation_all_claim.rb
spec/lib/evss/disability_compensation_form/data_translation_all_claim_spec.rb
spec/support/disability_compensation_form/all_claims_fe_submission.json

Gemfile updated for the latest revision of vets-json-schema. There are some schema validation errors seen on staging for 4142 and this merge would fix the error for `providerFacilityAddress` 
Local build and testing

Gemfile updated for latest revision of vets-json-schema

---

app/controllers/concerns/authentication_and_sso_concerns.rb
spec/controllers/v0/sessions_controller_spec.rb

Adding duplicated key to the cookie to support what MHV is expecting for their release, but we will want to switch this out in future iteration.
specs only
testing on staging

mhv is using credential used, snakecase

---

app/controllers/concerns/authentication_and_sso_concerns.rb
spec/controllers/v0/sessions_controller_spec.rb

sso 'testing; is enabled on staging, but disabled in other environments, this will be convenient to support future changes that need to be tested in staging without shipping to production.
specs should suffice.
verify on production with a prod account that it works correctly.

remove the feature toggling mechanism for AAL changes for MHV

---

Gemfile.lock

Gemfile updated for the latest revision of vets-json-schema. 
Local build and testing

Updated to point to the latest vets_json_schema version

---

app/models/user_preference.rb
db/migrate/20181219215248_remove_user_preference_choice_index.rb
db/migrate/20181219215343_add_non_unique_preference_choice_index.rb
db/schema.rb
spec/models/user_preference_spec.rb

Bug description:
**Steps to Reproduce**
url: https://staging.va.gov/my-va/find-benefits
user: vets.gov.user+0@gmail.com, vets.gov.user+226@gmail.com, etc
**What happened:**
https://dsva.slack.com/files/U8CQ2FSKD/FEZLYHY22/recs_bug.mov
**Desired behavior:**
User should be able to save any combination of selections
**Add'l Notes:**
- Engineers have not been able to reproduce this bug on their local machines, only in staging.
Local testing and specs
Testing in staging

Fixes bug - Unable to save any selections in staging

---

app/controllers/v0/apidocs_controller.rb
app/controllers/v0/hca_dd214_attachments_controller.rb
app/models/hca_dd214_attachment.rb
app/serializers/hca_dd214_attachment_serializer.rb
app/swagger/requests/hca_dd214_attachments.rb
app/uploaders/hca_dd214_uploader.rb
config/routes.rb
spec/controllers/v0/hca_dd214_attachments_controller_spec.rb
spec/request/swagger_spec.rb

api for uploading a dd214 to send to ES
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16033
test on staging after frontend implemented

Send DD-214 to ESR w/ health care application

---

app/controllers/v0/apidocs_controller.rb

Update swagger endpoint to not reference vets.gov

---

lib/evss/disability_compensation_auth_headers.rb

Removing no longer needed info logs https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16416
specs
staging integration testing

removing evss sentry info logs

---

modules/vba_documents/README.yml

Fix typo in swagger docs.

---

modules/claims_api/EVSS_CLAIMS.yml

This is a change to fix a typo in the claims api documentation

fix typo in documentation

---

db/migrate/20190201211123_add_vettec_to_education_benefits_submissions.rb
db/schema.rb

Fix to add column via change method

---

app/models/okta_redis/profile.rb

I missed an S in the code so it's not raising the right exception

Error in typing -> Not found

---

app/workers/education_form/forms/va0994.rb
app/workers/education_form/templates/0994.erb
spec/fixtures/education_benefits_claims/0994/kitchen_sink.spl
spec/fixtures/education_benefits_claims/0994/prefill.spl
spec/fixtures/education_benefits_claims/0994/simple.spl

Updated 0994 template language to match vets-website changes
Unit tests updated.  Tested locally.
QA review

[VET TEC] Update 0994 template language

---

app/controllers/application_controller.rb
app/controllers/v0/preneeds/burial_forms_controller.rb
lib/common/hash_helpers.rb

move deep transform parameters out of app controller

rails 5 deep transform change

---

app/workers/education_form/forms/va0994.rb

[VET TEC] Small update to 0994 spool file template

---

app/models/health_care_application.rb

disable mvi hca rate limiting on dev
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/17170
test on dev

skip mvi hca rate limiting based on settings

---

app/models/form526_submission.rb

Reverts department-of-veterans-affairs/vets-api#2850

Revert "Move workflow complete handler to ancillary job Batch"

---

lib/gibft/service.rb

update gibft username as requested by the gibft team
test on dev

update gibft username

---

app/controllers/v0/sessions_controller.rb
spec/controllers/v0/sessions_controller_spec.rb

Removing logic that checks for session cookie being enabled or not.
None
None

session cookie is here to stay, lets reflect that

---

modules/veteran_verification/DISABILITY_RATING.yml

fixes https://github.com/department-of-veterans-affairs/vets-contrib/issues/1613
verified rendering with editor.swagger.io, no broken tests
verify in lower environments
a sample response for 200 is rendered in swagger

fix small typo in disability rating documentation

---

config/sidekiq_scheduler.yml

This bug is occurring each time cron job is called:
http://sentry.vetsgov-internal/vets-gov/platform-api-production/issues/59123/events/2246858/
This feature is not in use in production yet.  Removing the cron job while we debug the issue.  Will put the cron job back in place once the issue is resolved.

Hotfix - Removes non-critical cron job associated with a bug

---

.yardopts
Gemfile
Gemfile.lock

Adds yard gem to dev group and .yardopts file
N/A
N/A
Adds yard gem and yard options file to define how docs are generated

yard gem and yardopts

---

app/models/gi_bill_feedback.rb
spec/models/gi_bill_feedback_spec.rb

fix bug in school feedback form where non camelcase hash keys are transformed into camelcase
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/17611

Bug in School Feedback Form Submissions

---

lib/hca/enrollment_eligibility/status_matcher.rb
spec/lib/hca/enrollment_eligibility/status_matcher_spec.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/17725
return none of the above if a user has a blank enrollment_status
test on dev

HCA handle nil enrollment_status for loa3 users

---

Jenkinsfile

Rails upgrade testing is complete on dev, setting staging to be the `rails-5.0.7.1` branch and dev back to `master`
N/A
Upgrade smoke test on staging

staging to rails-5.0.7.1 branch and dev back to master

---

lib/appeals/configuration.rb
lib/appeals/middleware/errors.rb
lib/appeals/responses/appeals.rb
lib/appeals/service.rb

Adds yard docs for appeals
N/A
N/A

17780 appeals docs

---

rakelib/redis.rake

This PR amends the redis rake namespace to include a task to clean account data out

Add task to flush RedisStore Account data

---

Jenkinsfile

This PR revert [this change](https://github.com/department-of-veterans-affairs/vets-api/pull/2922) to the `Jenkinsfile` such that we can merge `rails-5.0.7.1` branch into `master` again in preparation for production deploy.

Modify Jenkinsfile to deploy staging from master

---

Gemfile.lock
modules/appeals_api/appeals_api.gemspec
modules/claims_api/claims_api.gemspec
modules/openid_auth/openid_auth.gemspec
modules/va_facilities/va_facilities.gemspec
modules/vba_documents/vba_documents.gemspec
modules/veteran/veteran.gemspec
modules/veteran_verification/veteran_verification.gemspec

In the Rails upgrade the module versions weren't all correctly upticked.
`bundle install` on a fresh gemset and running the app
CI build

Uptick module versions

---

rakelib/evss.rake

Updates the GIBS not found rake task so that it can be run from Jenkins
Tested against local db
Staging testing

update gibs not found rake task

---

rakelib/evss.rake

Fixes GIBS rake task to parse json correctly
local
staging

fix GIBS rake task

---

app/mailers/spool_submissions_report_mailer.rb
spec/mailers/spool_submissions_report_mailer_spec.rb

The following email has been added to the distro for the 0994 daily YTD report in production: Ricardo.DaSilva@va.gov
Unit testing
Verify with client emails are being received after changes go live.

VET TEC: Update YTD Report Email Distribution #17980

---

modules/claims_api/config/routes.rb

Testing claims v1, we got 404s on claims v1 cors
No ticket
none
- Testing in dev once deployed

Add claims v1 cors preflight check

---

Jenkinsfile

This PR updates the Jenkinsfile to deploy the `rails-5.1` branch to development.

Modify Jenkinsfile to deploy Rails 5.1 to dev from master

---

config/routes.rb

Getting ready for UAT of changes to the HCA. Adding a new beta-app ID to facilitate that.

Add `hca2` beta-app ID

---

lib/evss/reference_data/configuration.rb
lib/evss/reference_data/service.rb

Adding documentation to Reference Data (one of the EVSS services)
Documentation is added

add reference data documentation

---

lib/evss/vso_search/configuration.rb
lib/evss/vso_search/service.rb

Adding documentation to VSO Search (one of the EVSS services)
Documentation is added

add vso search documentation

---

rakelib/connectivity.rake

Fixing a couple of the connectivity tasks.
ref: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16410

fix some connectivity tasks

---

modules/va_facilities/README.yml
rakelib/connectivity.rake

Updating the Open API Spec for Facilities API. This includes changes made in the following pull requests:
- https://github.com/department-of-veterans-affairs/vets-api/pull/2987
- https://github.com/department-of-veterans-affairs/vets-api/pull/2992
- https://github.com/department-of-veterans-affairs/vets-api/pull/3006
Part of https://github.com/department-of-veterans-affairs/vets-contrib/issues/1894.

Update Facilities API spec

---

lib/evss/pciu/configuration.rb
lib/evss/pciu/email_address.rb
lib/evss/pciu/email_address_response.rb
lib/evss/pciu/phone_number.rb
lib/evss/pciu/phone_number_response.rb

Adding documentation to PCIU (one of the EVSS services)
Documentation is added

add pciu yard docs

---

config/sidekiq_scheduler.yml

geoBISL has shutdown the arcGIS endpoints we use to get this data. I'm shutting down the jobs while this gets sorted out on the VA side

disabling facility location data jobs

---

lib/hca/enrollment_eligibility/service.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18544
add monitoring to hca ee api

add monitoring to hca ee api

---

modules/va_facilities/README.v1.yml

Fix parameter name in `/nearby` path description from `address_1` to `street_address`.

Update param name in description

---

Jenkinsfile

This PR will update Jenkinsfile to deploy the `rails-5.2` branch to development. #2933 
n\a 
n\a 
~- [ ] Appropriate logging~
~- [ ] Swagger docs have been updated, if applicable~
~- [ ] Provide link to originating GitHub issue, or connected to it via ZenHub~
~- [ ] Does not contain any sensitive information (i.e. PII/credentials/internal URLs/etc., in logging, hardcoded, or in specs)~
~- [ ] Provide which alerts would indicate a problem with this functionality (if applicable)~

Deploy dev from rails-5.2 branch

---

Jenkinsfile

Revert the Jenkinsfile change so staging deploys from master

Send staging back to master

---

README.md

I had to stand up a new dev environment recently and looked here for the links to the certificate and key only to find they were broken. This updates those links

Update certificate links

---

app/workers/evss/disability_compensation_form/submit_form526.rb

EVSS has confirmed that ~75% of the `PIF in use` errors that we have been are resolved within a 24 hour period and can therefore be retried. This retry logic has been added into the submission job.
staging e2e test

Add 'PIF_in_use' error to 526 submit job retry logic

---

app/mailers/preneeds_submissions_report_mailer.rb
spec/mailers/preneeds_submissions_report_mailer_spec.rb

Update PreNeeds submissions report mailer recipients
specs
N/A

Update PreNeeds submissions report mailer recipients

---

config/settings.yml
spec/support/vcr_cassettes/central_mail/status_multiple_uuids.yml
spec/support/vcr_cassettes/central_mail/status_one_uuid.yml
spec/support/vcr_cassettes/central_mail/submit_4142.yml
spec/support/vcr_cassettes/central_mail/submit_4142_400.yml
spec/support/vcr_cassettes/central_mail/upload.yml
spec/support/vcr_cassettes/vso_appointments/upload.yml

* See https://github.com/department-of-veterans-affairs/devops/pull/4978

Update central mail test server

---

Gemfile
Gemfile.lock

This PR bumps the Sentry client version to the latest, as we have upgraded to the latest server

Bump Sentry client version as we on are the latest server

---

modules/claims_api/app/controllers/claims_api/v1/forms/disability_compensation_controller.rb

Wrapping up for ticket https://github.com/department-of-veterans-affairs/vets-contrib/issues/2105
- Rspec testing still returns original content.
- Will test this in dev-api.va.gov
- Make sure a proper response is returned in V1 similar to V0.

Trying to wrap up responses

---

modules/vba_documents/app/models/vba_documents/upload_submission.rb

We found out the new status is formatted this way through connecting and doing an end to end test.
- dev server calls

VBA Documents new vbms status update

---

modules/claims_api/app/swagger/claims_api/claims_v0_swagger.rb

shout out to @mjlumetta for finding this on the developer portal

Base path is wrong is the swagger docs

---

Gemfile.lock

Bump version of `yard` to eliminate security vulnerability.  [Source](https://github.com/rubysec/ruby-advisory-db/commit/c668902e7da0caea64a536b0b1ead59eb537c4ea#diff-ade4faa3f7aaec38fa507da6f1e10050)
specs
N/A
(Yard is just used for generating documentation)
- ~~[ ] Appropriate logging~~
- ~~[ ] Swagger docs have been updated, if applicable~~
- ~~[ ] Provide which alerts would indicate a problem with this functionality (if applicable)~~

bump `yard` gem version

---

modules/vba_documents/app/swagger/vba_documents/v0/description.md
modules/vba_documents/app/swagger/vba_documents/v1/description.md

Updating swagger docs with new FAQs + new caching header
resolves https://github.com/department-of-veterans-affairs/vets-contrib/issues/2707

FAQs + new caching header

---

modules/vba_documents/app/swagger/vba_documents/v0/description.md
modules/vba_documents/app/swagger/vba_documents/v1/description.md

Minor last minute changes to documentation

---

modules/claims_api/app/controllers/claims_api/v1/forms/disability_compensation_controller.rb

Minor fix to the validation end point.
- Make sure validation end point sends the right payload

Fixing validation end point to process real payload

---

modules/claims_api/app/models/claims_api/veteran.rb

there is a bug with how this error is raised, it would 500 rather than throwing the proper error because of formatting it thought this was a function to be called rather than an error to be raised
- local calls

Fix error raising

---

modules/claims_api/app/controllers/claims_api/v0/forms/disability_compensation_controller.rb
modules/claims_api/app/controllers/claims_api/v1/forms/disability_compensation_controller.rb

Adding validation fix to v0 per https://github.com/department-of-veterans-affairs/vets-api-clients/pull/82
- Fixing Validation bug

Adding Validation Fix to V0

---

README.md

Updating the link to the Sidekiq license key since the vets.gov-team repo has been reorganized

Update SideKiq Link in README

---

Gemfile
Gemfile.lock

ci found  a security vulnerability, lets get that fixed

Update nokogiri for security vulnerability

---

modules/vba_documents/app/swagger/vba_documents/document_upload/metadata_swagger.rb

Spelling mistake in swagger docs
resolves https://github.com/department-of-veterans-affairs/vets-contrib/issues/2931

Fix spelling mistake

---

app/mailers/year_to_date_report_mailer.rb
spec/mailers/year_to_date_report_mailer_spec.rb

https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets.gov-team/19516
Unit testing.
Once in staging, we will reach out to Lucas Tickner to confirm that he is receiving YTD reports.
- Lucas.Tickner@va.gov
- Lucas.Tickner@va.gov

add new staging recipient for year to date report

---

modules/claims_api/app/models/claims_api/veteran.rb
modules/claims_api/spec/models/veteran_spec.rb

This is what actually ended up working on staging to call EDIPI properly ticket https://github.com/department-of-veterans-affairs/vets-contrib/issues/2859
- Properly call EDIPI for Veteran model

Quick fix for calling edipi

---

app/mailers/views/direct_deposit.html.erb

Updates the text contained in the Direct Deposit email
specs
manual generation of email

Update Direct Deposit email text

---

config/settings.yml
lib/evss/ppiu/configuration.rb

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19551
increase the ppiu read timeout to reduce timeout errors
tested new timeout value with the load test script

increase ppiu timeout based on load test results

---

modules/va_facilities/README.yml

Follow-up to #3251. We need to show an actual link instead of just the link text.

Update Access To Care wait times FAQ link to Facilities v0 docs

---

Gemfile.lock

Fixes a bug in simplecov related to parallel_tests in simplecov https://github.com/colszowka/simplecov/pull/706
ran specs on jenkins

Update simeplecov gem to fix parallel_test coverage bug

---

Gemfile
Gemfile.lock

Bundler supports checking a Ruby version so `bundle install` fails fast on the wrong Ruby version.
Feature was added in https://bundler.io/v1.12/gemfile_ruby.html
Added the line, bundled, then changed my ruby and system ruby with rvm. If versions didn't match, `bundle` failed.
Checking deploy on staging. Not sure exaclty how that pipeline works
Verify it works with whatever ruby manager is on staging/production

Add ruby version to Gemfile

---

db/schema.rb
modules/claims_api/db/migrate/20190904156435_create_power_of_attorney.rb

This is a separate migration PR for https://github.com/department-of-veterans-affairs/vets-api/pull/3261
- Setup necessary power of attorney tables in migration

Adding migration for Power of Attorney First

---

spec/lib/sentry/processor/filter_request_body_spec.rb

The specs now are each independent with clearer setup, exercise, and verification phases.
Refactors specs so continuing to pass is the only real test
None.

Refactor the specs for clarity

---

.rubocop.yml
app/models/preneeds/receive_application.rb

Refactor for Rubocop.
Note: this is a PR for a feature branch, not `master`.  PR #3330

rubocop offenses

---

modules/claims_api/app/controllers/claims_api/application_controller.rb
modules/claims_api/app/swagger/claims_api/claims_model_swagger.rb
modules/claims_api/app/swagger/claims_api/claims_v0_controller_swagger.rb
modules/claims_api/app/swagger/claims_api/claims_v0_swagger.rb
modules/claims_api/app/swagger/claims_api/claims_v1_controller_swagger.rb
modules/claims_api/app/swagger/claims_api/claims_v1_swagger.rb
modules/claims_api/app/swagger/claims_api/form_0966_v0_controller_swagger.rb
modules/claims_api/app/swagger/claims_api/form_2122_v0_controller_swagger.rb
modules/claims_api/app/swagger/claims_api/form_2122_v1_controller_swagger.rb
modules/claims_api/app/swagger/claims_api/form_526_v0_controller_swagger.rb
modules/claims_api/app/swagger/claims_api/form_526_v1_controller_swagger.rb

Major changes that needed to be made to the Claims API documentation. Ticket https://github.com/department-of-veterans-affairs/vets-contrib/issues/3096
- Checked against developer portal ran locally
- Checking on developer.va.gov when deployed.
- Minor changes to Claims API documentation

Major corrections and changes to Claims API documentation

---

.rubocop.yml
.rubocop_todo.yml
modules/va_facilities/spec/validators/param_validators_spec.rb
modules/vba_documents/spec/lib/multipart_parser_spec.rb
modules/vba_documents/spec/models/upload_submission_spec.rb
spec/lib/common/client/monitoring_spec.rb
spec/lib/facilities/nca_facility_spec.rb
spec/lib/facilities/vba_facility_spec.rb
spec/lib/facilities/vc_facility_spec.rb
spec/lib/facilities/vha_facility_spec.rb
spec/models/async_transaction/base_spec.rb
spec/request/beta_registration_spec.rb
spec/request/id_card_attributes_request_spec.rb
spec/request/swagger_spec.rb
spec/serializers/message_serializer_spec.rb

Continuation of fixing Rubocop Rspec offenses.

Rubocop rspec fixes round 11

---

modules/va_facilities/README.v1.yml
modules/va_facilities/README.yml

Curl generation testing was breaking which led to finding this misalignment of the secrutiy schema.
- developer portal curl generation

Line up the security schema -- facilities swagger

---

modules/claims_api/app/controllers/claims_api/application_controller.rb
modules/claims_api/app/controllers/claims_api/concerns/mvi_verification.rb

Logging MVI errors so that we can get an idea why it's failing, ticket https://github.com/department-of-veterans-affairs/vets-contrib/issues/3332
- Adding Error Logging to MVI check

MVI Error logging in Claims

---

modules/vba_documents/app/mailers/vba_documents/unsuccessful_report_mailer.rb
modules/vba_documents/spec/mailers/unsuccessful_report_mailer_spec.rb

A request was made to have Valerie added to the recipient list.
- rspec

Add additional recipient to the report

---

modules/vba_documents/app/mailers/vba_documents/unsuccessful_report_mailer.rb
modules/vba_documents/spec/mailers/unsuccessful_report_mailer_spec.rb

@ryanlink requested to be added to the report
- rspec

Add Ryan Link to report recipients

---

config/sidekiq_scheduler.yml
modules/vba_documents/app/mailers/vba_documents/views/unsuccessful_report.erb

Two bugs
- scheduler was sending every hour #cronsytanx
- All the results were on one row

Art.fix report

---

app/workers/facilities/pssg_download.rb
config/initializers/rgeo.rb
lib/facilities/drivetime_band_client.rb
lib/facilities/drivetime_band_configuration.rb
spec/jobs/facilities/pssg_download_spec.rb
spec/lib/facilities/drivetime_band_client_spec.rb

This PR adds updates to the PSSG Download Job that should prevent errors and speed up overall download time. 
https://github.com/department-of-veterans-affairs/vets-contrib/issues/3448

Rt kr/pssg job updates

---

config/betamocks/services_config.yml
lib/evss/vso_search/configuration.rb
spec/lib/evss/vso_search/configuration_spec.rb

in order to not have mismatches in the future use settings / api version
resolves https://github.com/department-of-veterans-affairs/vets-contrib/issues/3474
- rspec

Version Settings for VSO search

---

docs/setup/native.md

Update the installation instructions for manually installing the app
[ ] Re-run all commands step-by-step on local machine
[ ] Run through final instructions on another machine
[ ] Check on Ubuntu
Another machine can be boostrapped using these instructions

Update installation instructions

---

.gitignore
docs/setup/evss.md
docs/setup/mvi.md

There are some old exclusions in `.gitignore` for mock files that
likely predate `betamocks`. Reviewing those led to finding some related docs
that are also out-of-date. The old info is removed in this PR.

Remove old docs and gitconfig support for EVSS and MVI mocks

---

modules/vba_documents/lib/vba_documents/multipart_parser.rb

Patching an error that seems to be occuring in staging.
- Remove .path from what is essentially a string

Causing upload errors to GDIT

---

modules/vaos/app/services/vaos/appointment_service.rb
modules/vaos/app/services/vaos/systems_service.rb

Fixes triggering the perform arg footgun for VAOS calls 🤦‍♂   
unit tests

fix headers arg location in vaos perform calls

---

modules/vaos/app/controllers/vaos/application_controller.rb
modules/vaos/app/services/vaos/appointment_requests_service.rb
modules/vaos/app/services/vaos/appointment_service.rb
modules/vaos/spec/request/appointments_request_spec.rb
spec/support/vcr_cassettes/vaos/appointments/get_cc_appointments.yml
spec/support/vcr_cassettes/vaos/appointments/get_cc_appointments_500.yml
spec/support/vcr_cassettes/vaos/appointments/get_cc_appointments_empty.yml

Fixes route for CC appointments.
Introduces improved 403 Forbidden handling for when ICN is unavailable.
Specs only
Manual regression
See description.

Fix cc appointments endpoint and handle no icn

---

config/features.yml
config/settings.yml

This adds the VAOS feature flags that we're going to need over the next month in order to roll out the application. It also adds users that can access the UI to change the flags.
None
Verify the flags in staging

Add VAOS feature flags

---

modules/vaos/app/controllers/vaos/clinics_controller.rb
modules/vaos/app/serializers/vaos/clinic_serializer.rb
modules/vaos/spec/request/facilities_request_spec.rb
modules/vaos/spec/services/systems_service_spec.rb
spec/support/schemas/vaos/facility_clinics.json
spec/support/vcr_cassettes/vaos/systems/get_facility_clinics.yml

Fixes https://github.com/department-of-veterans-affairs/va.gov-team/issues/3409
Adds in missing facility clinic fields
unit tests

VAOS missing clinic fields

---

config/settings.yml

As requested by @annaswims I'm adding myself as a Flipper UI admin specifically so I can work with the `profileShowDirectDeposit` feature flag that controls the Profile Direct Deposit feature

Add Erik Hansen as a Flipper UI user

---

modules/va_forms/app/controllers/va_forms/v0/forms_controller.rb
modules/va_forms/app/swagger/va_forms/forms/form_swagger.rb
modules/va_forms/app/swagger/va_forms/v0/controller_swagger.rb
modules/va_forms/app/swagger/va_forms/v0/description.md
modules/va_forms/spec/requests/v0/forms_request_spec.rb

Add a new query param for searching functionality
resolves https://github.com/department-of-veterans-affairs/vets-contrib/issues/3648
- rspec
nique to your PR_

VA Forms Search

---

spec/lib/emis/responses/get_combat_pay_response_spec.rb
spec/lib/emis/responses/get_deployment_response_spec.rb
spec/lib/emis/responses/get_guard_reserve_service_periods_response_spec.rb
spec/lib/emis/responses/get_pay_grade_history_response_spec.rb
spec/lib/mvi/models/mvi_profile_spec.rb
spec/request/backend_status_request_spec.rb

Adding in data type checks to specs on some Virtus models

Adding data type checks to some specs

---

config/puma.rb

This is a revert of https://github.com/department-of-veterans-affairs/vets-api/pull/3727 which was not intended to go out today.

undo changes

---

app/controllers/concerns/form_attachment_create.rb
app/swagger/requests/hca_attachments.rb
app/swagger/requests/upload_supporting_evidence.rb
spec/controllers/v0/hca_attachments_controller_spec.rb
spec/request/swagger_spec.rb
spec/request/upload_supporting_evidence_spec.rb

revert both https://github.com/department-of-veterans-affairs/vets-api/pull/3746 and
https://github.com/department-of-veterans-affairs/vets-api/pull/3721
https://dsva.slack.com/archives/C30LCU8S3/p1578516985009900

Revert file upload

---

modules/claims_api/config/schemas/526.json

Quick validation update that we're seeing in production getting by us

Add zip last four validation

---

modules/vba_documents/app/mailers/vba_documents/unsuccessful_report_mailer.rb
modules/vba_documents/app/views/vba_documents/unsuccessful_report_mailer/_submission_table.html.erb
modules/vba_documents/app/views/vba_documents/unsuccessful_report_mailer/unsuccessful_report.html.erb
modules/vba_documents/app/workers/vba_documents/report_unsuccessful_submissions.rb
modules/vba_documents/spec/jobs/report_unsuccessful_submissions_spec.rb
modules/vba_documents/spec/mailers/unsuccessful_report_mailer_spec.rb

move views to proper location
refactor table into partial
resolves https://github.com/department-of-veterans-affairs/vets-contrib/issues/4032
- rspec
- monitor tomorrows email

Add stuck submissions to mailer

---

modules/vba_documents/app/mailers/vba_documents/unsuccessful_report_mailer.rb
modules/vba_documents/spec/mailers/unsuccessful_report_mailer_spec.rb

Resolves https://github.com/department-of-veterans-affairs/vets-contrib/issues/4112
- Remove Aubrey from daily and weekly reports
- Add Kelly, Ed and Em to daily and weekly reports

Changing error report emails

---

modules/veteran_confirmation/VETERAN_CONFIRMATION.yml

This PR addresses [#4114](https://github.com/department-of-veterans-affairs/vets-contrib/issues/4114). It updates the Open API Spec for the Lighthouse Veteran Confirmation API to include information about Test Users. That information is needed for an API consumer to get a successful `"confirmed"` response from the API in lower environments.
- Validated the yaml for the Open API Spec

Veteran Confirmation API Documentation Updates

---

Dockerfile

Fixes logic error in Dockerfile. This check should be looking for the presence of .pem files to rename, not .crt. It works, but only because we happen to have both that get added by Ansible.
Part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/5239
Tested locally with `make ci-build` in scenarios with .crt and with .pem files.

wrong file path check in dockerfile

---

app/controllers/v0/burial_claims_controller.rb

Adds tag for relationship types to statsD metrics for claimant relationship type
Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/5665
local testing
staging

Tag burial claims metrics with claimant relationship type

---

Gemfile
Gemfile.lock
config/newrelic.yml

The BE Tools team is evaluating NewRelic as a performance monitoring tool for digging into thorny issues
around CPU, memory, and database usage. This PR is the minimal configuration, with a devops PR forthcoming
to handle separating environment names on AWS

Add NewRelic gem and config

---

lib/sentry/processor/pii_sanitizer.rb
spec/lib/sentry/processor/pii_sanitizer_processor_spec.rb

https://github.com/department-of-veterans-affairs/va.gov-team/issues/5736

filter vet360 address fields in PII sanitizer

---

rakelib/github_stats.rake

Updates the metric name and the way we're calculating duration :D 
Tested on the dev server

Update duration calculation to use floats and rename metric

---

Gemfile.lock

Update minor versions of some recently updated gems in the test group
Updated
* database_cleaner
* faker
* webmock
Also update `brakeman` and remove obsolete ignored warning.

Update some recently bumped test gems

---

config/features.yml

add new profile_schema_forms feature flag

---

config/features.yml

Adding a feature flag to suppress the ability to search for pharmacies in the facility locator

Adding a feature flag to suppress pharmacies in the facility locator

---

config/features.yml

This flag is no longer used. Between this massive PR https://github.com/department-of-veterans-affairs/vets-website/pull/11870 and this new one https://github.com/department-of-veterans-affairs/vets-website/pull/11929/ all traces of the feature flag have been removed from the FE

delete unused profile_schema_forms flag

---

app/policies/evss_policy.rb
app/services/users/services.rb
lib/backend_services.rb
spec/policies/evss_policy_spec.rb

We are doing a slow roll out of the original claims functionality for the form 526 workflow. This is a bit more complicated because this is not a brand new form but, rather, new functionality for the current form. MVI requires us to do SQA testing (testing on their staging platform) by doing full end-to-end tests. Therefore, we require the front end to make original claims accessible on the staging branch but NOT the production platform. We decided to include whether the current user is capable of doing an original claim in the users services list and then let the FE implement gating on this on the correct platform (staging in this case).
Once this passes as SQA and is approved for production we will revamp the current form 526 policy currently in place and remove this temporary original …

6678 add original claims to service list

---

config/features.yml

add two new feature flags

---

app/serializers/provider_serializer.rb
config/features.yml
lib/facilities/ppms/client.rb
spec/lib/facilities/ppms/client_spec.rb
spec/serializers/provider_serializer_spec.rb

- facilities_ppms_response_trim
- facilities_ppms_caresite_name
- facility_locator_dedup_community_care_services
department-of-veterans-affairs/va.gov-team#6067
department-of-veterans-affairs/va.gov-team#6066
Removing the feature flags and associated logic
The feature flags should no longer change its behavior

Removing three facility feature flags

---

config/settings.yml

Adds Patrick to flipper admins in preparation for SSOe rollout management.

Adds Patrick to flipper admin list

---

lib/sidekiq/semantic_logging.rb

Calling super with the new number of arguments
Rspec passed

Fixing rspec failures around semantic_logging

---

config/settings.yml

my account has been verified in LOA3

adding eric.buckley@adhocteam.us to flipper admin users

---

spec/factories/saml_attributes.rb

Captured by signing in via AccessVA and navigating to VA.gov and triggering a SAML reassertion from SSOe. 
No new test cases at this point, mainly pushing for reference by @ericbuckley

Adds representative SAML factories for inbound SSO

---

Gemfile.lock

update vets-json-schema revision with the new hash.

update vets-json-schema revision with new hash

---

lib/vet360/models/address.rb
spec/lib/vet360/contact_information/service_spec.rb
spec/support/vcr_cassettes/vet360/contact_information/person_intl_addr.yml

https://github.com/department-of-veterans-affairs/va.gov-team/issues/7524

fix vet360 address not reading province from get person response

---

Gemfile.lock

Gem update. Nothing fancy here.

Update new relic gem

---

config/features.yml

As a developer, I need to create a feature flag that can be used for the Section 103 UI update effort, so that the development is only available in lower environments until it is ready to be delivered to production.
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/7773
frontend pr: https://github.com/department-of-veterans-affairs/vets-website/pull/12168
new feature is listed here http://localhost:3000/flipper/features

Added estimate your benefits sec103 feature flag

---

config/features.yml

https://github.com/department-of-veterans-affairs/va.gov-team/issues/7780
vets-website: https://github.com/department-of-veterans-affairs/vets-website/pull/12203

EYB: Create Feature Flag Toggle for Estimate Your Benefits Effort #7780

---

Gemfile.lock

We need to update the vets-json-schema version to be the one that contains the updates for the 10203 form.

update vets-json-schema version

---

Gemfile.lock

Updating the vets-json-schema version so we can work with the latest schema changes for the edu 10203 form.

update vets-json-schema to latest version

---

config/environments/production.rb

Temporarily log CSRF token value to assist in troubleshooting of seemingly erroneous occurrences of CSRF violations.

Log CSRF token for troubleshooting

---

modules/vaos/app/controllers/vaos/messages_controller.rb

There are two `MessagesSerializer` classes in the application. During work
on CircleCi, which led to some changes in how RSpec loading was handled,
two specs were reliably breaking under certain conditions. In a nutshell:
Things that work:
```
$ bundle exec rspec ./modules/vaos/spec/request/messages_request_spec.rb:83
$ bundle exec rspec --pattern modules/*/spec/**/*_spec.rb --format progress ./modules/vaos/spec/request/messages_request_spec.rb:83
```
Things that fail — including the spec dir first:
```
$ bundle exec rspec --pattern spec/**/*_spec.rb --format progress ./modules/vaos/spec/request/messages_request_spec.rb:83
```
and the failure is
```
{\"errors\":[{\"title\":\"Internal server error\",\"detail\":\"Internal server error\",\"code\":\"500\",\"status\":\"500\",\"meta\":{\"excepti …
```

Add module scope to VAOS MessagesSerializer

---

config/features.yml
config/settings.yml

Add Robin Garrison to the flipper admin user white list in the settings file.
Add Original Claims to the flipper feature file to allow for original claims users.

Add original claims to flipper feature

---

config/settings.yml

Add dev for COVID19 chatbot to flipper
Add dev from VSP/BE-Tools to flipper
We keep all the admins for flipper in the `settings.yml` file. Just adding a few.

Add admins to Flipper

---

spec/controllers/v0/coronavirus_chatbot/tokens_controller_spec.rb

Linting fix for previous PR around [Adding COVID19 Chatbot Token service to vets API ](https://github.com/department-of-veterans-affairs/vets-api/pull/4146)
[Failing Jenkins build](http://jenkins.vfs.va.gov/blue/organizations/jenkins/testing%2Fvets-api/detail/master/2536/pipeline)
department-of-veterans-affairs/covid19-chatbot/issues/91
Just updating the content description for when the service is not healthy.

[#91] Fixes linting error caught for duplicate content descriptions

---

spec/lib/mvi/service_spec.rb

We want to monitor metrics for the new add person call to MVI. This has already been implemented but there was a lack of testing. I wanted to rectify and add a few tests to make sure the increments are gathered correctly.
Nothing.

Add monitoring tests for add_person call

---

Gemfile.lock

Minor gem update for test environment
Ongoing maintenance

Update byebug gem

---

docker-compose.test.yml

Production is being upgraded to Redis 5.0 (from Redis 3.2). As part of the prep for the upgrade, this PR ensures both Docker-based development and all testing is using a Redis 5.0 instance.
The expectation 
department-of-veterans-affairs/va.gov-team#8150
Ran tests locally in docker and on CI to verify everything works with the version change.

Use redis 5.0 for docker tests

---

lib/appeals/middleware/errors.rb
lib/evss/power_of_attorney_verifier.rb
spec/jobs/evss/disability_compensation_form/submit_form526_increase_only_spec.rb
spec/lib/carma/models/submission_spec.rb
spec/lib/central_mail/datestamp_pdf_spec.rb
spec/lib/decision_review/service_spec.rb
spec/lib/evss/power_of_attorney_verifier_spec.rb
spec/models/folder_spec.rb
spec/models/message_spec.rb
spec/models/okta_redis/grants_spec.rb
spec/models/personal_information_log_spec.rb
spec/models/session_spec.rb
spec/request/caregivers_assistance_claims_request_spec.rb
spec/request/csrf_request_spec.rb
spec/request/evss_claims_async_spec.rb
spec/request/flipper_request_spec.rb
spec/request/swagger_spec.rb
spec/request/user_preferences_request_spec.rb
spec/request/user_request_spec.rb
spec/serializers/message_serializer_spec.rb

Fix typos in test specs and error message

---

config/environments/development.rb

department-of-veterans-affairs/va.gov-team#6767

Add `config.hosts` setting for `development` env

---

docker-compose.review.yml
docker-compose.yml

As we prepare for production to finally join the rest of our Redis Elasticache instances running v5.0, its time to get the last few Docker containers migrated as well. Thus this PR 😄 
department-of-veterans-affairs/va.gov-team#8141
Checked that the docker container works for local dev. Don't expect anything else surprising.

Update Redis version in Docker containers

---

Gemfile.lock

Update factory_bot* gems
Update bye bug
NA Ongoing support

Minor update to some test gems

---

config/settings.yml

LOA3 Verification (for staging, also verified in prod more recently):

Add dan.hinze@adhocteam.us to flipper admin list

---

app/swagger/schemas/vet360/address.rb
lib/vet360/models/base_address.rb
spec/lib/vet360/models/address_spec.rb

change address length limits for vet360 address model
https://github.com/department-of-veterans-affairs/va.gov-team/issues/8046
swagger docs have been updated

change address length limits for vet360 address model

---

config/settings.yml

Add BAH Team emails for enabling/disabling feature flags

Add BAH Team emails to flipper.admin_user_emails

---

modules/claims_api/spec/requests/v0/disability_compensation_request_spec.rb
modules/claims_api/spec/requests/v1/disability_compensation_request_spec.rb

Just needed to confirm using our tests that there is nothing broken with uploading multiple attachments.
https://vasdvp.atlassian.net/browse/DASH-187

Confirming multiple attachments do get uploaded

---

config/settings.yml

Add user to list of Flipper admins.

Add Flipper Admin

---

config/settings.yml

accounts were made with lowercase

Fix casing of BAH flipper feature admin emails

---

modules/vba_documents/app/swagger/vba_documents/document_upload/status_description.md
modules/vba_documents/app/swagger/vba_documents/document_upload/v1/status_description.md
modules/vba_documents/app/swagger/vba_documents/v1/description.md

Benefits Intake API documentation updates

---

config/features.yml

Use actor_type for 10-10cg feature toggles.
Patch for https://github.com/department-of-veterans-affairs/va.gov-team/issues/6321
This feature is not launched yet and will not affect va.gov users.

change actor_type for 10-10cg feature toggles

---

config/features.yml

Tracked in this issue [department-of-veterans-affairs/covid19-chatbot#142]
Since the COVID-19 chatbot is now live in production, we no longer need these feature flags. **These code changes remove the flags for the FAQ and Facility Locator pages.**
Need to remove usage of these feature flags in vets-website as well: [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/12589)
[department-of-veterans-affairs/covid19-chatbot#121]
[Previous PR](https://github.com/department-of-veterans-affairs/vets-api/pull/4165) that added the feature flags

Removes chatbot feature flags for FAQ and Facility Locator pages

---

modules/vaos/app/services/vaos/systems_service.rb
spec/support/vcr_cassettes/vaos/systems/get_institutions.yml
spec/support/vcr_cassettes/vaos/systems/get_institutions_single.yml

CDW Service V2 is being sunset in favor of the V3. 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/8894
Only changes are to specs and a base URI for the host for a specific set of services.
Will verify on staging.

CDW service V2 is being sunset in favor of V3

---

app/mailers/spool_submissions_report_mailer.rb
app/mailers/year_to_date_report_mailer.rb
spec/mailers/spool_submissions_report_mailer_spec.rb
spec/mailers/year_to_date_report_mailer_spec.rb

Add new user to mailers due to personnel change
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/8949
N/A

add new user to report mailers

---

Gemfile.lock
config/brakeman.ignore

Minor upgrade, nothing fancy here.

Upgrade brakeman gem

---

Gemfile.lock

No major changes that seem to need extra attention, but laying groundwork
for Ruby 2.7

Update pg gem

---

Gemfile.lock

Nothing major, just updating dev dependency in the gem
https://github.com/ddollar/foreman/blob/master/Changelog.md#0871-2020-04-02

Update foreman gem

---

Dangerfile

Updates our ruby-danger configuration:
- now **fails** instead of **warns** when files are changed in `/app` & `/db` within the same PR
- Places the file summary of each check into a collapsable element
- Some wording changes
- adds a few links on migration and deployment best practices
How the comment looks... [before](https://github.com/department-of-veterans-affairs/vets-api/pull/4238#issuecomment-626061940) & [after](https://github.com/department-of-veterans-affairs/vets-api/pull/4272#issuecomment-628694668)
https://github.com/department-of-veterans-affairs/va.gov-team/issues/9043
ruby-danger is not required to pass for a PR to be able to merge... so even though a PR might fail because it creates migrations and app changes together, the PR author is will able to merge to PR - a …

shorten dangerbot error messages

---

Gemfile
Gemfile.lock

Update rspec-rails to v4.0

---

config/initializers/raven.rb

Allow 'ActionController::InvalidAuthenticityToken' exceptions in Sentry
department-of-veterans-affairs/va.gov-team-sensitive#44
department-of-veterans-affairs/va.gov-team-sensitive#42
department-of-veterans-affairs/va.gov-team-sensitive#61

Allow 'ActionController::InvalidAuthenticityToken' exceptions in Sentry

---

Gemfile.lock

Update rspec-rails gem

---

config/features.yml

This adds some new feature toggles for the VAOS EAS/VSP work
department-of-veterans-affairs/va.gov-team#9042

Add new feature toggles for VAOS FHIR work

---

README.md
app/controllers/application_controller.rb
config/settings.yml
docs/setup/native.md
modules/vba_documents/app/controllers/vba_documents/internal/v0/upload_complete_controller.rb
modules/vba_documents/spec/request/v0/upload_complete_request_spec.rb

This PR fixes an issues where VBA Documents musts work with both VAGOV and VETSGOV SNS topic names.

bam: Correctly accept more than one topic arn

---

lib/facilities/ppms/client.rb
spec/request/v0/facilities/ccp_request_spec.rb
spec/request/v0/facilities/va_request_spec.rb
spec/support/vcr_cassettes/facilities/va/ppms.yml

Rounding radius to an Integer since PPMS's new version can't handle a decimal.
Rounding the radius
This needs to be tested in a review instance and needs to go to prod asap.

PPMS needs radius to be an integer

---

Gemfile.lock

restoring accidentally removed gems

restore sidekiq ent and pro gems to gemfile.lock

---

app/policies/evss_policy.rb

no functional change, simply for readability

refactor evss policy for readability

---

.github/CODEOWNERS

Add vfs-vaos to CODEOWNERS with responsibility for their module
department-of-veterans-affairs/va.gov-team#9579
Have to try this with real PRs

Revise CODEOWNER assignments

---

rakelib/form526.rake

the regex in `form526.rake` was using `\\` to escape characters instead of `\`, so nothing matched.  Therefore, most errors weren't being included in this report. 
And, while I was in the neighborhood I got rid of all single-letter variables.
this is a rake task that is occasionally run by developers to report on errors.  It does not change data.

fix regex in rake form526:errors

---

config/features.yml

As a developer, I need to create a toggle for the Estimate Your Benefits Bottom Sheet, so that it can be enabled / disabled without requiring a deployment.
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/9403
local testing at `http://localhost:3000/flipper/features/gibct_eyb_bottom_sheet`
Adding Estimate your benefits bottom sheet feature flag

Estimate your benefits bottom sheet feature flag backend

---

app/services/form1010cg/service.rb
lib/carma/README.md
spec/services/form1010cg/service_spec.rb

Fix bug where caregiver ICNs are not passed to CARMA on 10-10CG Submission

Fix issue where Caregiver ICN is not passed to CARMA

---

config/settings.yml

Adding Dustin Hughes's email account to the feature flag admin list. 
Adding hughes_dustin@bah.com to feature flag flipper admin list.

adding a feature flag admin

---

modules/claims_api/app/controllers/claims_api/v0/forms/disability_compensation_controller.rb
modules/claims_api/app/controllers/claims_api/v1/forms/disability_compensation_controller.rb
modules/claims_api/spec/requests/v0/disability_compensation_request_spec.rb
modules/claims_api/spec/requests/v1/disability_compensation_request_spec.rb

Reverts department-of-veterans-affairs/vets-api#4317

Revert "Send evss source in claims"

---

app/serializers/personal_information_serializer.rb
spec/serializers/personal_information_serializer_spec.rb

fix NoMethodError bug in personal information serializer
https://github.com/department-of-veterans-affairs/va.gov-team/issues/9132
tested with automated tests

NoMethodError in personal information serializer

---

rakelib/form526.rake

- updated `form526:submission` rake so that it could accept either a submission id or a job id as an argument
- got rid of all single-letter variables and did some light refactoring
- stripped the GUID from error messages so that they will all be grouped together.
this is an occasionally-used rake task that was difficult to test locally without a lot of test data. I will validate this in staging.

Update form 526 rake tasks

---

Gemfile.lock
spec/services/form1010cg/service_spec.rb

Needed to implement HLR work for https://github.com/department-of-veterans-affairs/vets-json-schema/pull/429
Requested for https://github.com/department-of-veterans-affairs/vets-website/pull/12880
department-of-veterans-affairs/va.gov-team#7154

Update vets-json-schema v6.0.1

---

config/features.yml

Creating a feature flag to tell the front end to use the facility locator API V1
department-of-veterans-affairs/va.gov-team#7658
This just creates a feature flag for the front end.

Adding a feature flag so the front end can use V1

---

Gemfile.lock

Upgrading to latest VCR gem.
Only relevant major changes
* sets the stage for an upgrade to Faraday 1.0
* supports ruby 2.7
https://github.com/vcr/vcr/blob/master/CHANGELOG.md for more
Spec using VCR successfully pass.

Update vcr gem

---

modules/veteran_confirmation/VETERAN_CONFIRMATION.yml

Added short description in the swagger configuration for the VETERAN_CONFIRMATION api to explain how MVI differs in the Production and Sandbox environments.
https://vajira.max.gov/browse/API-644
My original PR was https://github.com/department-of-veterans-affairs/vets-api/pull/4403, but I had some issues rebasing the branch.

API 644 Improve MVI Documentation

---

config/initializers/rack-CVE-2020-8184.rb
lib/rack-CVE-2020-8184.rb

Applied the workaround from https://groups.google.com/forum/#!topic/ruby-security-ann/zKaG37spQao as a temporary fix for the security issue.
department-of-veterans-affairs/va.gov-team#10272
Verified Rails logger message is received on local development. Will check on staging/production as it launches.

Workaround for CVE-2020 8184

---

config/settings.yml

Adding myself to be a flipper admin.

added email for mdewey

---

modules/appeals_api/app/swagger/appeals_api/v1/api_description.md

Adding an h2 heading to match claims style and meet 508 compliance on the appeals decision review page

Add an h2 for appeals description for 508 compliance

---

modules/claims_api/app/swagger/claims_api/v1/form_2122_controller_swagger.rb

This PR fixes a type in the 2122 Power of Attorney Swagger Docs

fixing typo in the 2122 swagger docs

---

modules/claims_api/app/swagger/claims_api/v0/form_2122_controller_swagger.rb
modules/claims_api/app/swagger/claims_api/v0/form_526_controller_swagger.rb
modules/claims_api/app/swagger/claims_api/v1/form_2122_controller_swagger.rb
modules/claims_api/app/swagger/claims_api/v1/form_526_controller_swagger.rb

Needed to include examples of the base64 payloads in attachments for the curl generation.
https://vajira.max.gov/browse/API-1190

Final example demonstrations for base64 Claims representation

---

modules/claims_api/lib/claims_api/health_checker.rb

This PR adds back in the healthcheck endpoints for VBMS and BGS since they are now available in production

adding back in vbms and bgs healchecks

---

app/swagger/swagger/schemas/appeals/contestable_issues.rb
config/locales/exceptions.en.yml
lib/decision_review/schemas/contestable_issues.json
lib/decision_review/service.rb
spec/lib/decision_review/service_spec.rb
spec/rails_helper.rb
spec/request/appeals_request_spec.rb
spec/support/schemas/contestable_issues.json
spec/support/vcr_cassettes/decision_review/200_contestable_issues.yml
spec/support/vcr_cassettes/decision_review/400_contestable_issues.yml
spec/support/vcr_cassettes/decision_review/404_contestable_issues.yml
spec/support/vcr_cassettes/decision_review/422_contestable_issues.yml
spec/support/vcr_cassettes/decision_review/502_contestable_issues.yml

since we wrote the code to make a call to Lighthouse (https://sandbox-api.va.gov/services/appeals/v1/decision_reviews/contestable_issues) some headers and attribute names have changed. This updates the schema and the specs.
The 200-response spec now includes a real recorded response.
department-of-veterans-affairs/va.gov-team#9817
cc: @Mottie

update decision review

---

modules/vaos/spec/services/middleware/vaos_logging_integration_spec.rb
modules/vaos/vaos.gemspec

Updates VOAS gemspec load path to match other engines
N/A

Vaos update gemspec

---

app/controllers/v0/caregivers_assistance_claims_controller.rb
app/services/form1010cg/service.rb
spec/controllers/v0/caregivers_assistance_claims_controller_spec.rb
spec/services/form1010cg/service_spec.rb

Fixes: https://github.com/department-of-veterans-affairs/va.gov-team/issues/10583

Render "Backend Service Outage" on invalid veteran status for 10-10CG submissions

---

config/features.yml

Adding a feature flag for the Higher-Level Review form 20-0996 in anticipation of launch.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/10709

Add HLR feature flag

---

config/features.yml

This adds new feature toggles for the express care work upcoming for VAOS.
department-of-veterans-affairs/va.gov-team#11066

Add express care feature toggles for VAOS

---

app/controllers/v1/sessions_controller.rb

Adding the `type` value to the SAML Request/Response log entries, so we can better distinguish the responses we are sending/receiving from SSOe.

adding type values to SAML Request/Response logs to help with debugging

---

app/mailers/spool_submissions_report_mailer.rb
spec/mailers/spool_submissions_report_mailer_spec.rb

Add Product Owner and Tech Lead of BAH Team to staging spool report email list

add BAH Product Owner and Tech Lead to staging spool reports

---

Gemfile.lock
modules/claims_api/lib/claims_api/health_checker.rb

Updating BGS gem with necessary per service healthchecks for Claims
https://vajira.max.gov/browse/API-1395

Updating BGS Healthchecks per service

---

app/mailers/spool_submissions_report_mailer.rb
app/workers/education_form/create_daily_spool_files.rb
spec/factories/education_benefits_claims.rb
spec/jobs/education_form/create_daily_spool_files_spec.rb
spec/mailers/spool_submissions_report_mailer_spec.rb

https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/10805
Adds 10203 spool submissions to the daily report. 
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/10805

add 10203 to spool submission report

---

app/mailers/year_to_date_report_mailer.rb
spec/mailers/year_to_date_report_mailer_spec.rb

As an Education Services Team member, I need the 10203 submissions included in the daily YTD report so I can perform my duties with accurate and up to date information once the 10203 has launched.
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/10808
3 New columns are included in the YTD reports:
a. Fiscal Year Submissions (Ex. Header: 2018-10-01..2019-08-08 23:59:59 UTC)
b. Submitted (Ex. Header: Submitted)
c. Daily Submissions Sent to Spool File (Ex. Header: 2019-08-08 00:00:00 UTC..2019-08-08 23:59:59 UTC | Sent to Spool File)
a. Adam Sonntag - Sonntag_Adam@bah.com
b. Desiree Turner - Turner_Desiree@bah.com
c. Darrell Neel - Neel_Darrell@bah.com

Updated staging email list for 10203

---

modules/vba_documents/app/swagger/vba_documents/document_upload/metadata_swagger.rb
modules/vba_documents/app/swagger/vba_documents/document_upload/status_attributes_swagger.rb
modules/vba_documents/app/swagger/vba_documents/document_upload/v1/status_attributes_swagger.rb
modules/vba_documents/app/swagger/vba_documents/v0/controller_swagger.rb
modules/vba_documents/app/swagger/vba_documents/v1/controller_swagger.rb

resolves https://vajira.max.gov/browse/API-1425

Benefits Intake API - Fix Swagger Errors

---

modules/claims_api/lib/claims_api/health_checker.rb

This PR fixes the BGS healthcheck

fix BGS healthcheck

---

config/betamocks/services_config.yml
config/settings.yml
lib/debts/configuration.rb

add betamocks configuration for debts api index call
https://github.com/department-of-veterans-affairs/va.gov-team/issues/10614
tested locally

debts api betamocks

---

app/controllers/v0/caregivers_assistance_claims_controller.rb
app/services/form1010cg/service.rb
config/initializers/statsd.rb
spec/controllers/v0/caregivers_assistance_claims_controller_spec.rb

Fixes: https://github.com/department-of-veterans-affairs/va.gov-team/issues/5672
Add StatsD increments for Form 10-10cg Submissions.

Add StatsD events to Form1010cg Submissions

---

app/mailers/spool_submissions_report_mailer.rb
app/mailers/year_to_date_report_mailer.rb
spec/mailers/spool_submissions_report_mailer_spec.rb
spec/mailers/year_to_date_report_mailer_spec.rb

As an Education Services Team Member, I need to receive the daily spool and YTD reports out of the staging environment during UAT so that I can confirm that everything is working correctly with the 10203 prior to launch.
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/10942
Following emails updated
1. The following email addresses are included in the staging distribution for the daily spool report:
a. Luke Tickner - Lucas.Tickner@va.gov
b. Brian.Grubb - Brian.Grubb@va.gov
c. Tammy Hurley - tammy.hurley1@va.gov
d. Joe Preisser - Joseph.Preisser@va.gov
e. Joseph Welton - Joseph.Welton@va.gov
2. The following email addresses are included in the staging distribution for the YTD report:
a. Luke Tickner - Lucas.Tickner@va.gov
b. …

updated edu emails

---

bin/fake_clamdscan
config/settings.local.yml.example
docs/setup/native.md

Add a fake ClamAV file and configuration example for local development to avoid the complexity of installation and configuration required by ClamAV for native OSX and Linux/Ubuntu installations. 
department-of-veterans-affairs/va.gov-team#11176
* New docs in the native install about running the fake scanner
* Tested using local installs of vets-website and vets-api with user `vets.gov.user+17@gmail.com` completing form at http://localhost:3001/pension/application/527EZ/introduction and uploading _multiple_ files.

Add a fake clamav scanner for local development

---

config/features.yml

As a developer, I need to create a feature flag that can be used to turn on and off CT filter enhancements so that it can be delivered to production in a timely manner.
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/11344

added gibct filter enhancement flag

---

lib/flipper/views/feature.erb
lib/flipper/views/features.erb

Fix typos: feagure -> feature

---

config/settings.yml

We need to be able to turn on Profile 2.0 for specific Veterans during UAT sessions so we are adding Samara, Matt Shea, and Tressa Furner to the list of Flipper admins so that an engineer does not need to observe every UAT session.

Allow Samara Strauss to edit feature flags

---

modules/appeals_api/app/workers/appeals_api/higher_level_review_pdf_submit_job.rb
modules/appeals_api/spec/workers/higher_level_review_pdf_submit_job_spec.rb

Corrections and missing pieces for properly uploading documents to GDIT discovered during testing.
https://vajira.max.gov/browse/API-1334

Fixing HLR GDIT upload

---

modules/va_forms/app/serializers/va_forms/form_detail_serializer.rb

Getting out a fix making sure we don't crap out due to bad data from the new data source
https://vajira.max.gov/browse/API-1629

Fix for failing show end point for forms

---

config/features.yml

As a developer, I need to create a feature flag that can be used to turn on and off CT post-9/11 gi bill benefit rate updates so that it can be delivered to production in a timely manner.
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/11534
Frontend PR: https://github.com/department-of-veterans-affairs/vets-website/pull/13569

added chp33 feature flag to backend

---

config/features.yml

Add featureflip for UAT/PROD testing of Debt letters application 
department-of-veterans-affairs/va.gov-team#11517

bradl3yC - 11517  - Add FF for debt letters

---

.gitignore

Update .gitignore to ignore files created by Intellij IDE

---

app/models/bgs_dependents/child_marriage.rb
app/models/bgs_dependents/child_stopped_attending_school.rb
app/models/bgs_dependents/death.rb
app/models/bgs_dependents/step_child.rb
spec/models/bgs_dependents/child_marriage_spec.rb
spec/models/bgs_dependents/child_stopped_attending_school_spec.rb
spec/models/bgs_dependents/death_spec.rb
spec/models/bgs_dependents/step_child_spec.rb

This PR is a chunk broken off of [this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/4546). It was advised that we break that large PR into smaller more easily reviewable chunks of code to expedite the review process.
This PR is one of a few that are adding models for the 686c form submission. These models will be mostly responsible for serializing data that we are sending/receiving to/from BGS.
department-of-veterans-affairs/va.gov-team#11260

[686] Dependents application models 3

---

modules/vba_documents/app/mailers/vba_documents/unsuccessful_report_mailer.rb
modules/vba_documents/spec/mailers/unsuccessful_report_mailer_spec.rb

Adding Mark Greenburg to Benefits Intake Report

---

modules/claims_api/app/controllers/claims_api/v1/forms/power_of_attorney_controller.rb
modules/claims_api/app/swagger/claims_api/v1/form_2122_controller_swagger.rb

resolves https://vajira.max.gov/browse/API-1581

Claims API v1 - Improve Error Handling for Missing POA (2122 Controller)

---

modules/vaos/app/controllers/vaos/v1/appointments_controller.rb
modules/vaos/app/services/vaos/v1/fhir_service.rb
modules/vaos/config/routes.rb
modules/vaos/spec/request/v1/appointments_request_spec.rb
spec/fixtures/fhir/dstu2/appointment_create.yml
spec/fixtures/fhir/dstu2/invalid_appointment_create.yml
spec/support/vcr_cassettes/vaos/fhir/appointment/post_appointment_create_request_201.yml
spec/support/vcr_cassettes/vaos/fhir/appointment/post_appointment_invalid_request_400.yml

VAOS + FHIR - Create Appointment Resource
[VFT Zenhub issue #9557](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/9557)
Add Appointment post Rails route, Appointment Controller create method and rspec test for Appointment creation.

9557 vaos fhir create appointment resource

---

modules/appeals_api/app/swagger/appeals_api/v1/api_description.md
modules/appeals_api/app/swagger/appeals_api/v1/swagger_root.rb
modules/appeals_api/app/swagger/v0/appeals.yml

This PR updates the Appeals documentation per jira ticket api-1610.

update the appeals api docs

---

lib/carma/models/metadata.rb
lib/carma/models/submission.rb
spec/lib/carma/models/metadata_spec.rb
spec/lib/carma/models/submission_spec.rb

Fixes: https://github.com/department-of-veterans-affairs/va.gov-team/issues/11204

Send the claim's guid to CARMA on 10-10CG submissions

---

Gemfile.lock

Our frontend team requested I bump the version up for changes they have added in schema.
Related PR: https://github.com/department-of-veterans-affairs/vets-json-schema/pull/465

Bump JSON schema version

---

modules/appeals_api/app/models/appeals_api/higher_level_review.rb
modules/appeals_api/app/swagger/appeals_api/v1/swagger_root.rb
modules/appeals_api/app/workers/appeals_api/higher_level_review_pdf_submit_job.rb
modules/appeals_api/app/workers/appeals_api/higher_level_review_upload_status_batch.rb

resolves https://vajira.max.gov/browse/API-1669

Fix Data Race Between PDF-Submit-Job and Clean-Up-PII-Job

---

modules/claims_api/app/workers/claims_api/poa_updater.rb

One discovered bug led to another
https://vajira.max.gov/browse/API-1805

Fixing location of PoA code in payload sent to BGS

---

config/features.yml

Creating a feature flag to tell the front end to hide community care search
FE support: https://github.com/department-of-veterans-affairs/vets-website/pull/13638
department-of-veterans-affairs/va.gov-team#10698
This just creates a feature flag for the front end.

Add flag to supress ccp search

---

config/features.yml

This PR adds the BDD feature flag for allowing users access the BDD form flow within the 526 form.

Add BDD Feature Flag for Form 526

---

config/features.yml

We are beginning to build a replacement for the existing [IRIS Ask a Question form](https://iris.custhelp.va.gov/app/ask) on VA.gov. This feature toggle will hide/disable the form while we're still developing.
department-of-veterans-affairs/covid19-chatbot#302
department-of-veterans-affairs/covid19-chatbot#305
Adds a new feature flag, `get_help_ask_form`. Nothing tied to this feature flag yet.

Adds feature toggle for Ask a Question form

---

config/sidekiq_scheduler.yml
modules/appeals_api/app/models/appeals_api/higher_level_review.rb
modules/appeals_api/app/workers/appeals_api/higher_level_review_clean_up_week_old_pii.rb
modules/appeals_api/spec/factories/higher_level_reviews.rb
modules/appeals_api/spec/models/higher_level_review_spec.rb
modules/appeals_api/spec/workers/higher_level_review_clean_up_week_old_pii_spec.rb

resolves https://vajira.max.gov/browse/API-1843

Appeals API - Clean up Complete HLRs Once They're a Week Old

---

README.md
docs/setup/docker.md
docs/setup/native.md
docs/setup/running_docker.md
docs/setup/running_natively.md

I've updated the setup instructions to better reflect that native install is an equally valid choice for developers

update native setup instructions

---

app/controllers/v0/education_benefits_claims_controller.rb
app/models/saved_claim/education_benefits/va10203.rb
spec/models/saved_claim/education_benefits/va10203_spec.rb

department-of-veterans-affairs/va.gov-team#12163

STEM - 10203 Submission fails when not signed in

---

config/settings.yml

Add myself and bconley@governmentcio.com to `admin_user_emails`.
Slack support request: https://dsva.slack.com/archives/CBU0KDSB1/p1596742135175600?thread_ts=1596645903.086500&cid=CBU0KDSB1
It involves a change to `settings.yml`.

add myself, bconley@governmentcio.com to admin_user_emails

---

app/models/saved_claim.rb
app/models/saved_claim/education_benefits/va10203.rb
app/workers/education_form/send_sco_email.rb
spec/fixtures/education_benefits_claims/10203/minimal.json
spec/fixtures/education_benefits_claims/10203/minimal.spl

Make sure value is always "No" or "Yes" at https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/workers/education_form/templates/10203.erb#L58
department-of-veterans-affairs/va.gov-team#12205

STEM: Update 'Auto Email Sent to SCO:' in Spool File #12205

---

config/features.yml

Found out that capital letters are invalid. This will fix that.

fix 1990n feature name

---

config/features.yml

Found out that capital letters are invalid. This will fix that.

fix 1990e feature name

---

spec/request/v0/facilities/va_request_spec.rb
spec/support/schemas_camelized/suggested_facilities.json

creates a camel-inflected version of 'suggested_facilities' and compares it to results in the v0 va_request_spec

11585 add camel inflected schemas to va request spec

---

spec/request/appointments_request_spec.rb
spec/support/schemas_camelized/appointments_response.json

`appointments_request_spec`, now supporting inflected responses

11585 add camel inflected schemas to appointments request

---

.github/CODEOWNERS

Add the vfs-ebenefits team to CODEOWNERS file
department-of-veterans-affairs/va.gov-team#12309
Team will test - no impact on code or performance.

Add vfs-ebenefits team to CODEOWNERS

---

spec/request/backend_status_request_spec.rb
spec/support/schemas_camelized/backend_statuses.json

Add camelCase version of schema for backend_statuses

camelized response spec for backend_status

---

spec/request/email_request_spec.rb
spec/support/schemas_camelized/email_address_response.json

Add tests for email_address_response and errors in email_request_spec

11585 add camel inflected schemas to email request

---

spec/request/evss_claims_async_spec.rb
spec/support/schemas_camelized/evss_claim_async.json
spec/support/schemas_camelized/evss_claims_async.json

camel-inflected schema tests for evss claims

11585 add camel inflected schemas to evss claims async

---

spec/request/evss_claims_spec.rb
spec/support/schemas_camelized/evss_claim.json
spec/support/schemas_camelized/evss_claims.json

camel-inflected tests for evss_claims request spec

11585 add camel inflected schemas to evss claims

---

spec/request/folders_request_spec.rb
spec/support/schemas_camelized/folder.json
spec/support/schemas_camelized/folders.json
spec/support/schemas_camelized/messages.json

tests for camelCase in folders_request_spec

11585 add camel inflected schemas to folders request spec

---

app/services/form1010cg/service.rb
spec/request/caregivers_assistance_claims_request_spec.rb
spec/services/form1010cg/service_spec.rb

Resolves: https://github.com/department-of-veterans-affairs/va.gov-team/issues/12413

Remove veteran status search on 10-10cg submissions

---

spec/request/letters_request_spec.rb
spec/support/schemas_camelized/letter_base.json
spec/support/schemas_camelized/letter_beneficiary.json
spec/support/schemas_camelized/letter_beneficiary_benefit_information_dependent.json
spec/support/schemas_camelized/letter_beneficiary_benefit_information_veteran.json
spec/support/schemas_camelized/letters.json

camelCase schemas add for letters spec

11585 add camel inflected schemas to letters

---

spec/request/message_drafts_request_spec.rb
spec/request/messages_request_spec.rb
spec/support/schemas_camelized/category.json
spec/support/schemas_camelized/message.json
spec/support/schemas_camelized/message_with_attachment.json
spec/support/schemas_camelized/messages_thread.json

camelCase schema tests for `message_drafts_request_spec` and `messages_request_spec`

11585 add camel inflected schemas to message drafts and messages

---

spec/request/prescriptions_request_spec.rb
spec/support/schemas_camelized/prescription.json
spec/support/schemas_camelized/prescription_base.json
spec/support/schemas_camelized/prescriptions.json
spec/support/schemas_camelized/prescriptions_filtered.json
spec/support/schemas_camelized/trackings.json

new camelCase schema tests for `v0/prescriptions`

11585 add camel inflected schemas to prescriptions

---

spec/request/service_history_request_spec.rb
spec/support/schemas_camelized/service_history_response.json

camelCase schema tests for /v0/profile/service_history

11585 add camel inflected schemas to service history

---

spec/request/rating_info_request_spec.rb
spec/request/search_request_spec.rb
spec/support/schemas_camelized/search.json

add test for camelCase schema of /v0/disability_compensation_form/rating_info
add test for camelCase schema and errors of v0/search

11585 add camel inflected schemas to disability rating info and search

---

spec/request/terms_and_conditions_request_spec.rb
spec/support/schemas_camelized/terms_and_conditions.json
spec/support/schemas_camelized/terms_and_conditions_acceptance.json
spec/support/schemas_camelized/terms_and_conditions_mini.json
spec/support/schemas_camelized/terms_and_conditions_single.json

add camelCase tests for terms_and_conditions_acceptance, terms_and_conditions_single, and terms_and_conditions schemas to v0/terms_and_conditions

11585 add camel inflected schemas terms and conditions

---

spec/request/triage_teams_request_spec.rb
spec/support/schemas_camelized/triage_team.json
spec/support/schemas_camelized/triage_teams.json

add the camelCase schema for triage_teams_request_spec

add camelCase schemas for triage_teams for v0/messaging/health/recipients

---

spec/request/gids/calculator_constants_request_spec.rb
spec/request/gids/institution_programs_request_spec.rb
spec/request/gids/institutions_request_spec.rb
spec/request/gids/zipcode_rates_request_spec.rb
spec/support/schemas_camelized/gi/autocomplete.json
spec/support/schemas_camelized/gi/calculator_constants.json
spec/support/schemas_camelized/gi/institution.json
spec/support/schemas_camelized/gi/institution_children.json
spec/support/schemas_camelized/gi/institutions.json
spec/support/schemas_camelized/gi/zipcode_rate.json

add camelCase schemas from the `spec/support/schemas/gi` used for the gids request specs

11585 add camel inflected schemas for gids

---

spec/request/notifications_request_spec.rb
spec/support/schemas_camelized/notification.json

added camelCase schema for `notification` for v0/notifications specs

add camelCase schemas for v0/notifications

---

Gemfile.lock
modules/claims_api/app/controllers/claims_api/base_form_controller.rb

This PR removes sending of signature_indicated for the intent to file bgs call

Dont send signature indicator

---

config/features.yml

Added feature flag for the new Questionaire service. 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/12402
Feature flag for controlling whether or not the questionnaire form is shown in the front end

Added toggle for healthcare clipboard experience

---

app/controllers/facilities_controller.rb
app/controllers/v1/facilities/ccp_controller.rb
app/controllers/v1/facilities/va_ccp_controller.rb
app/models/ppms/provider_facility.rb
app/serializers/ppms/provider_facility_serializer.rb
config/routes.rb
spec/request/v1/facilities/ccp_request_spec.rb
spec/request/v1/facilities/va_ccp_request_spec.rb
spec/support/vcr_cassettes/facilities/va/ppms_and_lighthouse.yml

this will make requests to both lighthouse and PPMS and merge the results
Creating a new endpoint that will combine the urgent care results from PPMS and Lighthouse
department-of-veterans-affairs/va.gov-team#10318

Urgent Care Mashup

---

modules/claims_api/app/controllers/claims_api/base_form_controller.rb
modules/claims_api/app/controllers/claims_api/v0/forms/intent_to_file_controller.rb
modules/claims_api/app/controllers/claims_api/v1/forms/intent_to_file_controller.rb

recover from situation where ITF doesnt exist for a veteran with a given  compensation type

Recover intent to file empty

---

spec/request/vet360/address_request_spec.rb
spec/request/vet360/email_address_request_spec.rb
spec/request/vet360/permission_request_spec.rb
spec/request/vet360/person_request_spec.rb
spec/request/vet360/telephone_request_spec.rb
spec/support/schemas_camelized/vet360/transaction_response.json

camelCase schema tests for `requests/vet360`

11585 add camel inflected schemas to vet360

---

app/mailers/views/school_certifying_officials.html.erb

https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/12156
Updating the 10203 form url in the mailer form.

update 10203 form url

---

modules/veteran_confirmation/VETERAN_CONFIRMATION.yml

Changed required information and optional information headers from h4 to h3.
Headers should follow natural descending order in API descriptions.

Correct Vetaran Confirmation Header Order

---

config/features.yml

This PR adds feature toggles for the new unauth + auth content on the following pages:
https://www.va.gov/health-care/refill-track-prescriptions
https://www.va.gov/health-care/secure-messaging
https://www.va.gov/health-care/schedule-view-va-appointments
https://www.va.gov/health-care/view-test-and-lab-results
https://www.va.gov/health-care/get-medical-records/
https://github.com/department-of-veterans-affairs/va.gov-team/issues/11153

Add feature toggles for health care manage benefit pages

---

Gemfile.lock

We need the new read poa request by ptcpnt id in production so I can test my data against BGS to see if we have access. 
https://vajira.max.gov/browse/API-1830

updating bgs_ext

---

config/features.yml

`acto` should have been `actor`
- https://github.com/department-of-veterans-affairs/vets-api/pull/4737
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/10966
Oopsie

[Development] Fix typo in feature toggle

---

rakelib/form526.rake

Update Form526 rake task
* remove code related to deprecated v1 increase form
* differentiate BDD submissions
* show data, both before and after data translation
* make clear which errors come from the main submission or ancillary jobs
https://github.com/department-of-veterans-affairs/va.gov-team/issues/10675

Update form526 rake task

---

app/controllers/v1/sessions_controller.rb
config/initializers/statsd.rb
spec/controllers/v1/sessions_controller_spec.rb

updating/adding SAML request/response tracks to track both type and authn context
closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/12488

add ssoe statsd type context

---

README.md
docs/setup/mailer.md

Adding documentation around Mailers and previews location and access url

ActionMailer Documentation

---

rakelib/form526.rake

I made a mistake and missed a renaming of a method without test coverage of a rake task.

fix form526.rake method fix

---

modules/covid_research/app/services/covid_research/volunteer/genisis_service.rb
modules/covid_research/spec/serializers/covid_research/genisis_serializer_spec.rb

This fixes the `post` call to Faraday 🤦 
No big changes here just ensuring the payload is including the proper headers

Fix the `post` call to Faraday

---

app/models/saved_claim.rb
app/services/form1010cg/service.rb
lib/mvi/service.rb
spec/lib/mvi/service_spec.rb

`Form1010cg::Service` has more dependencies that were listed in this base branch. I've added those and also added those dependencies' dependencies, until the request spec for submitting a VA Form 10-10cg would pass.

add dependency loading for form1010cg requests and services

---

config/features.yml

Add featureflip for FE work surrounding V2 of debt letters

bradl3yC Add v2 feature flip for debt letters

---

app/controllers/v0/sessions_controller.rb
app/controllers/v1/sessions_controller.rb

In order to track down our proper SSOe statistics, we need to compare logs vs statsd information to make sure our numbers are true. This PR will add those logging statements to both controllers.
department-of-veterans-affairs/va.gov-team#12487
```bash
be rspec spec/controllers/v0/sessions_controller_spec.rb spec/controllers/v1/sessions_controller_spec.rb
```

va.gov-team#12487: First pass at adding logging statements

---

config/features.yml

A GIBCT feature flag for enhancements to the institution filter results 
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/13041
Confirmed that the new feature flag exists in the flipper flag UI.

create benefit question enhancements feature flag

---

config/features.yml

This PR fixes a spelling error that was caught thankfully by @erluti! 🙏

Fix spelling

---

lib/lighthouse/facilities/response.rb

Should resolve this error http://sentry.vfs.va.gov/vets-gov/platform-api-staging/issues/197187/

add require to facilities response

---

modules/appeals_api/lib/appeals_api/health_checker.rb
modules/claims_api/lib/claims_api/health_checker.rb

These two health checks require services that weren't included in their HealthCheckers

Fix healthcheck requires

---

app/controllers/openid_application_controller.rb
modules/openid_auth/app/controllers/openid_auth/v0/mvi_users_controller.rb
modules/openid_auth/app/controllers/openid_auth/v0/okta_controller.rb

fixes related to this sentry error http://sentry.vfs.va.gov/vets-gov/platform-api-sandbox/issues/197991

Missing requires for openidauth

---

Gemfile.lock

This pull request updates the gemfile.lock entry for vets-json-schema to remain consistent with this PR - https://github.com/department-of-veterans-affairs/vets-json-schema/pull/500
department-of-veterans-affairs/va.gov-team#13172

update gemfile entry

---

Gemfile
Gemfile.lock

https://github.com/department-of-veterans-affairs/vets-json-schema/pull/507
department-of-veterans-affairs/va.gov-team#13414

Remove 1995S Schema

---

config/initializers/app_info.rb
config/initializers/raven.rb
config/settings.yml
config/settings/test.yml

Update Sentry configuration to include environment

---

config/initializers/raven.rb

Something is causing the deployment of vets-api-server to cycle in staging (and dev I think). Found a mention of an undefined method "environment". The suggestion that came with that error asks if the user meant "environments". Could be way off here, but just trying to connect the dots. Forgive me if this is not what is causing the issue being observed.

hotfix syntax

---

config/features.yml

This pull request adds an entry for PCPG chapter 36 in `features.yml`. It corresponds with this pull request into vets-website - https://github.com/department-of-veterans-affairs/vets-website/pull/14234/files
department-of-veterans-affairs/va.gov-team#13129

add feature toggle to vets-api

---

modules/vaos/app/controllers/vaos/v0/appointment_requests_controller.rb
modules/vaos/spec/request/appointment_requests_request_spec.rb

Logging AppointmentRequest creation and cancellation.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/13504
Nope

13504 - add logging of appointment request ids

---

app/controllers/v0/efolder_controller.rb
spec/support/stub_efolder_documents.rb

prep work for https://github.com/department-of-veterans-affairs/vets-api/pull/4897/files
discovered a service being used without being required

add missing requires for Efolder service

---

app/models/in_progress_form.rb
spec/models/in_progress_form_spec.rb
spec/request/in_progress_forms_request_spec.rb

we'd like to add the SIP id to the form metadata so we can better troubleshoot http://sentry.vfs.va.gov/vets-gov/website-production/issues/12188/

Add SaveInProgress id to metadata

---

app/models/form_profile.rb
app/models/form_profiles/va526ez.rb
app/workers/evss/disability_compensation_form/submit_form526_cleanup.rb
lib/evss/disability_compensation_form/data_translation_all_claim.rb
spec/models/form_profile_spec.rb
spec/models/saved_claim/disability_compensation/form526_all_claim_bdd_spec.rb

we decided that form526 bdd is one form (same as 526) after all so I'm reverting the changes made in  #4382 and #4491
department-of-veterans-affairs/va.gov-team#11260

Undo BDD changes

---

modules/covid_research/README.md

Adds some documentation for the `covid_research` module
Just a `README` for whomever comes next...

Covid research/doc

---

config/features.yml

This flag should have been turned on as part of https://github.com/department-of-veterans-affairs/vets-api/pull/4277

Turn `profile_show_profile_2.0` on by default

---

modules/covid_research/app/mailers/covid_research/volunteer/submission_mailer.rb

Please see commit. Changing subject in automated confirmation email.
None.

Update subject for covid research email

---

config/features.yml

Now that features are off by default in dev, we need to set which VAOS flags we do want on by default. This makes those updates.

Update features.yml with better VAOS dev defaults

---

modules/vaos/app/controllers/vaos/v0/appointment_requests_controller.rb
modules/vaos/spec/request/appointment_requests_request_spec.rb

Updated appointment request controller to log type_of_care_id
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/13760
Respective unit tests were updated to reflect this change

added logging for type_of_care in appointment_requests_controller

---

docs/setup/native.md

fix jump link

---

Gemfile.lock

Implements this change https://github.com/department-of-veterans-affairs/vets-json-schema/pull/516.

Bump schema version for covid research form

---

modules/veteran_confirmation/VETERAN_CONFIRMATION.yml

Update documentation to match implementation for Veteran Confirmation response.
https://vajira.max.gov/browse/API-2402
This is documentation only to match implementation.

Corrected Veteran Confirmation documentation to match actual response.

---

config/initializers/staccato.rb
config/settings.yml
spec/config/initializers/staccato_spec.rb
spec/support/vcr_cassettes/govdelivery_emails.yml
spec/support/vcr_cassettes/staccato/event.yml

modify staccato library to send requests through the google analytics forward proxy instead of directly to google analytics
https://github.com/department-of-veterans-affairs/va.gov-team/issues/13856
tested in staging

modify staccato to use google analytics forward proxy

---

spec/lib/evss/disability_compensation_form/data_translation_all_claim_spec.rb
spec/support/disability_compensation_form/bdd_evss_submission.json
spec/support/disability_compensation_form/bdd_large_fe_submission.json

Adding BDD form test.
department-of-veterans-affairs/va.gov-team#10368

More BDD specs

---

app/models/ppms/provider_facility.rb
lib/facilities/ppms/client.rb

resolves issue discovered here https://dsva.slack.com/archives/CBU0KDSB1/p1601328320190800

add missing requires for PPMS::ProviderFacility

---

.rubocop.yml
app/controllers/v1/apidocs_controller.rb
app/swagger/swagger/v1/requests/facilities.rb
app/swagger/swagger/v1/schemas/errors.rb
app/swagger/swagger/v1/schemas/facilities.rb
config/routes.rb
spec/lib/lighthouse/facilities/client_spec.rb
spec/request/v0/facilities/va_request_spec.rb
spec/request/v1/apidoc/apidoc_spec.rb
spec/request/v1/apidoc/shared_examples/facility_locator_spec.rb
spec/request/v1/facilities/va_request_spec.rb
spec/support/vcr_cassettes/lighthouse/facilities.yml

Adding swagger docs for the V1 api
department-of-veterans-affairs/va.gov-team#11603
* There weren't any v1 swagger docs before this
* I broke the testing up into smaller pieces, its something I think we should do to the V0 apivore tests.
Minimal rspec testing

11603 v1 facilities swagger

---

Gemfile
Gemfile.lock
modules/health_quest/app/policies/health_quest_policy.rb
modules/health_quest/app/services/health_quest/pgd_service.rb
modules/health_quest/spec/request/appointment_request_by_id_spec.rb
modules/health_quest/spec/request/appointments_request_spec.rb
modules/health_quest/spec/services/pgd_service_spec.rb

For the health quest module - this adds a PGD (patient generated data) service. The service is not actually functional but our front end developer wanted to see the endpoints.

PR1 for PGD service, PGD service here is dummied up a bit

---

config/settings.yml

Adding myself as admin so I can own caregivers 1010CG feature flips
Adding user to feature flip admin list as described in [docs](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/)

Add Justin Linn to admin list

---

modules/covid_research/app/views/covid_research/volunteer/signup_confirmation.html.erb

zap pesky slash

---

config/features.yml

department-of-veterans-affairs/va.gov-team#14064
https://github.com/department-of-veterans-affairs/vets-website/pull/14437

EDU: Create feature flag for education form updates #14064

---

Gemfile.lock

As an applicant, I need the completion and review of my Personal Information to be seamless and flow from start to finish so I do not have to review previously answered questions based on questions that follow.
[Originating Issue](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/13784)
Associated `vets-website` [pull request](https://github.com/department-of-veterans-affairs/vets-website/pull/14405)
Updated unit tests, passing locally.
a. What's the best way for us to contact you?
b. Country
c. Street address
d. Line 2
e. City
f. State
g. Postal code
h. Email address
i. Re-enter email address
j. Home phone number
k. Mobile phone number
l. I would like to receive text messages from VA about my GI Bill benefits
Note: Text …

13784: Update schema hash

---

config/features.yml

Remove the feature flip for V2.  The MVP will not be released and V2 is now the release version.

bradl3yC - debt letters - Remove v2 feature flip

---

Gemfile.lock

This pull request updates vets-api to the latest changes in this pull request - https://github.com/department-of-veterans-affairs/vets-json-schema/pull/524
department-of-veterans-affairs/va.gov-team#12420

Update vets-api to latest vets-json-schema

---

config/features.yml

Added the `gibct_school_ratings` feature flag.
department-of-veterans-affairs/va.gov-team#13620
- This was accidentally removed in https://github.com/department-of-veterans-affairs/vets-api/pull/4884

Add gibct_school_ratings feature flag

---

Gemfile
Gemfile.lock

Vets-json-schema update for https://github.com/department-of-veterans-affairs/vets-json-schema/pull/526

add mobile as preferred contact method in definitions

---

app/controllers/v0/debt_letters_controller.rb
lib/debts/letter_downloader.rb

Fixes uninitialized constant here in the debt_letters controller by pulling in the debt letters lib code.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/14144
tested locally

[14144] Require letter_downloader - fix uninitialized constant error for debt_letters

---

app/workers/education_form/templates/phone_numbers.erb
config/features.yml
spec/fixtures/education_benefits_claims/1990/kitchen_sink.spl
spec/fixtures/education_benefits_claims/1990/kitchen_sink_active_duty.spl
spec/fixtures/education_benefits_claims/1990/kitchen_sink_edu_prog.spl
spec/fixtures/education_benefits_claims/1990/simple_ch33.spl
spec/fixtures/education_benefits_claims/1990e/kitchen_sink.spl
spec/fixtures/education_benefits_claims/1990e/simple.spl
spec/fixtures/education_benefits_claims/1990n/kitchen_sink.spl
spec/fixtures/education_benefits_claims/1990n/simple.spl
spec/fixtures/education_benefits_claims/1995/kitchen_sink.spl
spec/fixtures/education_benefits_claims/1995/minimal.spl
spec/fixtures/education_benefits_claims/5490/kitchen_sink_chapter_33_spouse.spl
spec/fixtures/education_benefits_claims/5490/kitchen_sink_chapter_35_child.spl
spec/fixtures/education_benefits_claims/5490/kitchen_sink_chapter_35_spouse.spl
spec/fixtures/education_benefits_claims/5490/simple_chapter_33_child.spl
spec/fixtures/education_benefits_claims/5495/kitchen_sink.spl
spec/fixtures/education_benefits_claims/5495/simple.spl

Update spool file phone number labels to match what is displayed in frontend
https://github.com/department-of-veterans-affairs/vets-website/pull/14471
department-of-veterans-affairs/va.gov-team#14467

Update spool file phone number labels

---

Gemfile.lock
spec/fixtures/ask/minimal.json

Updated our ask controller test to prepare it to work with schema updates
https://github.com/department-of-veterans-affairs/vets-json-schema/pull/525/
department-of-veterans-affairs/orchid#31
department-of-veterans-affairs/orchid#89

Updates vets-json-schema to 16.0.0

---

modules/health_quest/app/controllers/health_quest/v0/apidocs_controller.rb
modules/health_quest/app/docs/health_quest/v0/health_quest.yaml
modules/health_quest/config/routes.rb
modules/health_quest/spec/request/apidocs_request_spec.rb

Initial swagger for health quest service
https://github.com/department-of-veterans-affairs/va.gov-team/issues/14625

initial health quest swagger

---

app/controllers/v0/ask/asks_controller.rb
spec/controllers/v0/ask/asks_controller_spec.rb

Updates ask controller to return a (currently fake) confirmation number and submission date in the response, for valid requests.
department-of-veteran-affairs/orchid#76

Contact Us form - return confirmation number and date 

---

app/controllers/v0/claim_documents_controller.rb
spec/request/claim_documents_spec.rb

I found a missing require when I ran `spec/request/claim_documents_spec.rb` in isolation.

Add missing require

---

Gemfile.lock

This pull request updates the Gemfile.lock entry for vets-json-schema
department-of-veterans-affairs/va.gov-team#14301

update dependency for vets-json-schema

---

modules/vba_documents/app/mailers/vba_documents/unsuccessful_report_mailer.rb
modules/vba_documents/spec/mailers/unsuccessful_report_mailer_spec.rb

Updating list of emails for Benefits Team 2 needing to get Benefits Intake Emails.

Updating list of folks receiving Benefits Intake Emails

---

config/features.yml

Remove the gibct_filter_enhancement flag. 
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/13363

remove gibct_filter_enhancement feature flag

---

app/models/ppms/provider.rb
config/initializers/breakers.rb
lib/facilities/ppms/do_not_encoder.rb
lib/facilities/ppms/v0/configuration.rb
lib/facilities/ppms/v1/client.rb
lib/facilities/ppms/v1/configuration.rb
lib/facilities/ppms/v1/response.rb
spec/lib/facilities/ppms/do_not_encoder_spec.rb
spec/lib/facilities/ppms/v0/client_spec.rb
spec/lib/facilities/ppms/v1/client_spec.rb
spec/lib/facilities/ppms/v1/response_spec.rb
spec/request/v1/apidoc/shared_examples/facility_locator_spec.rb

Adding in the V1 client with the minimal number of params.
department-of-veterans-affairs/va.gov-team#7782
* Refactored the DoNotEncoder
* Added a V1 Client/Configuration/Response

7782 changes to ppms queries pt3 ppms client v1

---

modules/covid_research/app/views/covid_research/volunteer/signup_confirmation.html.erb

feedback@va.gov --> research@va.gov email change

---

modules/veteran/app/models/veteran/user.rb

The user data I was testing with changed because the application changed and I didn't catch the change.
https://vajira.max.gov/browse/API-3036

Representative Oauth 500 fix due to user data error

---

app/models/bgs_dependents/vnp_benefit_claim.rb
spec/models/bgs_dependents/vnp_benefit_claim_spec.rb

Hello! Thank you for your time in reviewing this. This is a small PR that we are submitting after testing 686 form submissions with BGS. Our goal in testing is to get a claim through and processed automatically by RBPS. We were told the that we need to submit the parameters this PR introduces in order to get past RBPS.
department-of-veterans-affairs/va.gov-team#14624
Negative
This feature is feature flagged. This PR does not introduce changes to the feature flag
This PR does not add Sentry code
Negative
* Are …

Adds vet_participant_id to [686] form submission

---

config/features.yml

Added the `education_reports_cleanup` feature flag
department-of-veterans-affairs/va.gov-team#13859
- This feature will be used in https://github.com/department-of-veterans-affairs/vets-api/pull/5097

Education FYTD cleanup feature flag

---

modules/claims_api/app/controllers/claims_api/application_controller.rb
modules/claims_api/app/controllers/claims_api/concerns/mpi_verification.rb

This PR updates mvi_verification to become mpi_verification and updates a require with the new rename
department-of-veterans-affairs/va.gov-team#14790

Update mvi verification to MPI

---

config/settings.yml

add myself to flipper admin users so i can change ch33 direct deposit flipper settings

add lihan to flipper admin users

---

config/redis.yml

reduce vet360 contact info cache to 1 hour so that upstream changes can be detected sooner
https://github.com/department-of-veterans-affairs/va.gov-team/issues/14626

reduce vet360 contact info cache to 1 hour

---

config/features.yml

Re-Adding the feature flag for the front end
department-of-veterans-affairs/va.gov-team#14154
* Feature Flag `facilities_ppms_suppress_pharmacies`

Re adding a feature flag used by the front end

---

app/serializers/vet_payment_history_serializer.rb

Small PR for the View Payments feature to return a null value if both check address and address eft info is not available.
department-of-veterans-affairs/va.gov-team#14973

Update Payment Method for View Payments

---

config/features.yml

And also remove the Profile 2.0 flag we stopped used a couple of weeks ago
[This FE PR](https://github.com/department-of-veterans-affairs/vets-website/pull/14664) will fetch the value of this new feature flag.

Add feature flag for new My VA Dashboard

---

config/betamocks/services_config.yml
config/settings.yml

department-of-veterans-affairs/va.gov-team#10276

configure mockdata for separation location

---

config/features.yml

Remove the `gibct_search_enhancements`feature flag.
department-of-veterans-affairs/va.gov-team#10810

Remove gibct_search_enhancements flag

---

app/models/mpi_data.rb
app/services/form1010cg/service.rb

This PR updates the MPI model and form1010cg service mvi_service method to be consistent with the MPI rename
department-of-veterans-affairs/va.gov-team#14782

update mvi_service to mpi_service

---

lib/mvi/messages/find_profile_message.rb
spec/lib/mvi/messages/find_profile_message_spec.rb

We are seeing errors in [Sentry](http://sentry10.vfs.va.gov/organizations/vsp/issues/3223/?environment=production&project=3&query=is%3Aunresolved+assigned%3A%23vsp-identity&sort=freq&statsPeriod=14d) that we are sending an invalid `find profile` response. We were only checking that the keys were present, and not that the values were nil or an empty string. This PR adds those specs as well as the code to validate this.
department-of-veterans-affairs/va.gov-team#15180

va.gov-team#15180: Raise proper error for missing keys and values

---

db/schema.rb
modules/apps_api/db/migrate/20201002143151_create_directory_applications.rb

Baseline migration files for apps_api module. This PR has been created to seperate db and app changes from #5075.
No changes other than migrations.

migration files for apps_api module

---

spec/service_consumers/provider_states_for/contact_us.rb

Creates provider state for contact us pact
department-of-veterans-affairs/orchid#149

Creates provider state for contact us pact

---

modules/claims_api/app/models/claims_api/veteran.rb

Reverting one minor change from my last PR https://github.com/department-of-veterans-affairs/vets-api/pull/5168 around calling from_identity
https://vajira.max.gov/browse/API-3036

Reverting from identity change

---

Gemfile.lock

Updates vets-json-schema 17.2.0
[department-of-veterans-affairs/orchid#152]

Updates vets-json-schema to 17.2.0

---

app/uploaders/evss_claim_document_uploader.rb
app/uploaders/hca_attachment_uploader.rb
app/uploaders/preneed_attachment_uploader.rb
app/uploaders/profile_photo_attachment_uploader.rb
app/uploaders/set_aws_config.rb
app/uploaders/supporting_documentation_attachment_uploader.rb
app/uploaders/supporting_evidence_attachment_uploader.rb
app/uploaders/vic/processing_uploader.rb
modules/claims_api/app/uploaders/claims_api/base_uploader.rb

This PR updates SetAwsConfig to become SetAWSConfig to match the existing inflection
department-of-veterans-affairs/va.gov-team#15529

Use AWS inflection

---

app/models/saved_claim/dependency_claim.rb
config/initializers/inflections.rb
modules/claims_api/app/controllers/claims_api/v0/forms/power_of_attorney_controller.rb
modules/claims_api/app/controllers/claims_api/v1/forms/power_of_attorney_controller.rb
modules/claims_api/app/workers/claims_api/poa_form_builder_job.rb
modules/claims_api/app/workers/claims_api/vbms_upload_job.rb
modules/claims_api/lib/claims_api/vbms_sidekiq.rb
modules/claims_api/lib/claims_api/vbms_uploader.rb
modules/claims_api/spec/lib/vbms_uploader_spec.rb
modules/claims_api/spec/support/fake_vbms.rb
modules/claims_api/spec/workers/vbms_upload_job_spec.rb
spec/lib/debts/letter_downloader_spec.rb
spec/lib/efolder/service_spec.rb
spec/models/saved_claim/dependency_claim_spec.rb

Some VBMS classes have been added in the last few months and we need an inflection for those and consistent naming. This PR adds the inflection and updates vbms in the codebase
department-of-veterans-affairs/va.gov-team#15530

Add VBMS inflection

---

app/controllers/v0/ask/asks_controller.rb
spec/controllers/v0/ask/asks_controller_spec.rb

Updates v0/ask/asks to return status 201 on successful submission of form
department-of-veterans-affairs/orchid#163

Contact us returns 201 on form submission

---

config/settings.yml

Updating admin user email for access to flipper feature toggles on staging
department-of-veterans-affairs/orchid#139

Updating admin user email for access to flipper feature toggles on staging

---

modules/health_quest/app/services/health_quest/jwt_wrapper.rb

- Modifying the jwt wrapper ISS to `gov.va.clipboard`
Configuration change. If the value is incorrect we will not be able to obtain a JWT token from MAP.

jwt iss to gov.va.clipboard

---

modules/health_quest/spec/services/configuration_spec.rb
modules/health_quest/spec/services/session_service_spec.rb

- Adding specs for session_service which had zero percent test coverage. This is necessary for the stories that will be worked on in the upcoming sprint.
Specs for session_service: /Users/dilloraju/Development/source/vets-api/session_service_spec.rb

14991 session service specs and cleanup

---

spec/ask.rb

We seem to have added this file twice. The correct one is `spec/factories/ask.rb`; removing the one that's in the wrong place.
n/a

Removes duplicate factory file for 0873 form

---

config/settings.yml
modules/claims_api/app/mailers/claims_api/unsuccessful_report_mailer.rb
modules/claims_api/app/views/claims_api/unsuccessful_report_mailer/unsuccessful_report.html.erb
modules/claims_api/app/workers/claims_api/report_unsuccessful_submissions.rb
modules/claims_api/spec/mailers/unsuccessful_report_mailer_spec.rb
modules/claims_api/spec/workers/report_unsuccessful_submissions_spec.rb
modules/vba_documents/app/mailers/vba_documents/unsuccessful_report_mailer.rb
modules/vba_documents/app/views/vba_documents/unsuccessful_report_mailer/unsuccessful_report.html.erb
modules/vba_documents/app/workers/vba_documents/report_unsuccessful_submissions.rb
modules/vba_documents/spec/jobs/report_unsuccessful_submissions_spec.rb
modules/vba_documents/spec/mailers/unsuccessful_report_mailer_spec.rb

Turning reports on for both claims and benefits intake from making changes to devops branch https://github.com/department-of-veterans-affairs/devops/pull/7927
https://vajira.max.gov/browse/API-2847

Updating report based on devops changes

---

spec/controllers/application_controller_spec.rb

I wanted to introduce spec changes independent of my open PR: https://github.com/department-of-veterans-affairs/vets-api/pull/5165
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/15012
Just more comprehensive specs for the exceptions in ExceptionHandling mixin.

adding just the specs

---

db/migrate/20201027024317_create_notice_of_disagreements.rb
db/schema.rb

This is the migration for #5164. 
[Make JSON Schema for NOD](https://vajira.max.gov/browse/API-2993)

Migration for creating AppealsApi::NoticeOfDisagreement class

---

app/controllers/v0/ask/asks_controller.rb
app/swagger/swagger/requests/asks.rb
spec/controllers/v0/ask/asks_controller_spec.rb
spec/request/swagger_spec.rb

Changes 503 to 501 status code. Adds to Swagger docs and tests for new 501
department-of-veterans-affairs/orchid#162
Adds test to swagger for 501 case

Changes status code service unavailable and updates Swagger

---

.rubocop.yml
spec/services/form1010cg/service_spec.rb
spec/support/form1010cg_helpers/build_claim_data_for.rb

Move the helper to build a 10-10CG's data to it's own spec helper for use in other (and future) specs.

Create a spec helper for building a 10-10CG subject's data.

---

modules/claims_api/app/mailers/claims_api/unsuccessful_report_mailer.rb
modules/claims_api/spec/mailers/unsuccessful_report_mailer_spec.rb
modules/vba_documents/app/mailers/vba_documents/unsuccessful_report_mailer.rb
modules/vba_documents/spec/mailers/unsuccessful_report_mailer_spec.rb

Just adding Dave to the reports.

Getting Dave Mazik in the daily reports

---

spec/lib/bgs/vnp_veteran_spec.rb
spec/lib/evss/disability_compensation_form/data_translation_all_claim_spec.rb

vets-api deployment failed due to these tests failing. This is a hotfix for those tests.

Add missing claim_type argument to specs

---

Gemfile.lock

Updates the Gemfile.lock entry for vets-json-schema per [this pull request](https://github.com/department-of-veterans-affairs/vets-json-schema/pull/546)
department-of-veterans-affairs/va.gov-team#15796

15796 Update Gemfile.lock entry for vets-json-schema

---

config/features.yml

Adds a new feature toggle for upcoming VAOS work. I've also updated our previous feature toggle to be on in development, now that it's on in production.
Front end PR: https://github.com/department-of-veterans-affairs/vets-website/pull/14934
department-of-veterans-affairs/va.gov-team#15869

Add new feature toggle for VAOS community care provider selection

---

config/settings.yml

My email address was recently changed. I'm updating the list to reflect the change.
I also sorted the section of the list that didn't have remove tags

Updating flipper admin email address

---

config/settings.yml
modules/claims_api/app/controllers/claims_api/application_controller.rb
modules/claims_api/app/controllers/claims_api/v1/claims_controller.rb

Overrides the `fetch_aud` method to prepare claims v1 endpoints for the OAuth authorization server isolation effort. Dependent on  department-of-veterans-affairs/devops#7967
https://vajira.max.gov/browse/API-2415

Add fetch_aud override for claims

---

app/models/in_progress_form.rb
rakelib/form526.rake
rakelib/in_progress_forms.rake
spec/models/in_progress_form_spec.rb

I'm trying to answer the question "why did a veteran get stuck on form 526, but I think these jobs could be useful for all forms. 
as of https://github.com/department-of-veterans-affairs/vets-website/pull/14807 vets-website sends more info in the metadata
department-of-veterans-affairs/va.gov-team#15689

Rake tasks for troubleshooting InProgressForms

---

modules/mobile/app/serializers/mobile/v0/military_information_serializer.rb
modules/mobile/spec/request/military_information_request_spec.rb

Added safe check to end date for military info
No issue, hotfix
Added test case for no end date

fix no end date issue, added test for it

---

modules/claims_api/app/swagger/claims_api/description/v0.md

v0 documentation updated around allowing 2122 form
https://vajira.max.gov/browse/API-3546
Swagger documentation changed around claims v0

API-3546: Update Claims V0 documentation to show 2122 support now (Release Notes)

---

config/locales/en.yml

content updates for error text
department-of-veterans-affairs/va.gov-team#14752x

content updates

---

Gemfile
spec/request/education_benefits_claims_request_spec.rb
spec/request/in_progress_forms_request_spec.rb

[This gem](https://github.com/futurechimp/awrence) appears to only be used in two places, is for testing only, and there's an alternative using rails alone.

remove use of awrence gem

---

Gemfile.lock

This PR didn't have an updated Gemfile.lock https://github.com/department-of-veterans-affairs/vets-api/pull/5322

lock file without awrence

---

spec/service_consumers/provider_states_for/contact_us.rb

Renames provider state for Contact Us pact test
To be merged after vets-website PR with the consumer-side updates: https://github.com/department-of-veterans-affairs/vets-website/pull/14825
[department-of-veterans-affairs/orchid#151]

Rename provider state for Contact Us Pact test

---

modules/claims_api/app/models/claims_api/auto_established_claim.rb
modules/claims_api/app/workers/claims_api/claim_establisher.rb
modules/claims_api/spec/models/auto_establish_claim_spec.rb

Write flashes for a claim to log on claim creation.
https://vajira.max.gov/browse/API-3257
Existing specs

API-3257: Flashes - Set up logging to capture what we need

---

modules/apps_api/lib/apps_api/directory_application_creator.rb

Small hotfix to correct `app_url` to actual ibluebutton site.

fixed iBlueButton url

---

modules/veteran_verification/app/models/veteran_verification/service_history_episode.rb
modules/veteran_verification/app/services/emis/mock_military_information_configuration_v2.rb

Adds logging and one addition require update to debug issue in dev with mock-emis functionality for the Veteran Verification API module in vets-api.
Adds logging and one addition require update to debug issue in dev with mock-emis functionality for the Veteran Verification API module in vets-api.
https://vajira.max.gov/browse/API-3058

Added logging and require update for mock emis.

---

modules/health_quest/app/controllers/health_quest/v0/questionnaire_responses_controller.rb
modules/health_quest/app/services/health_quest/patient_generated_data/questionnaire_response/factory.rb
modules/health_quest/app/services/health_quest/patient_generated_data/questionnaire_response/map_query.rb
modules/health_quest/spec/request/questionnaire_responses_request_spec.rb
modules/health_quest/spec/services/patient_generated_data/questionnaire_response/factory_spec.rb
modules/health_quest/spec/services/patient_generated_data/questionnaire_response/map_query_spec.rb

- Get QuestionniareResponse resource by id
- The Factory class is still being used as per the discussion in this PR comment: https://github.com/department-of-veterans-affairs/vets-api/pull/5330#discussion_r526341365
- We will begin thinking about the abstraction and refactoring once we're drawing towards the end of fetching all of the resources we need from the PGD.
department-of-veterans-affairs/va.gov-team#16379
- Tested by visiting: `/health_quest/v0/questionnaire_responses/<questionnaire_response_id>/`
- Tested by writing specs

16379 questionnaire response by

---

db/schema.rb
modules/claims_api/db/migrate/20201117200716_add_bgs_responses_column_to_auto_established_claims.rb

Adds columns required for API-3261 work.
https://vajira.max.gov/browse/API-3261
Will require migrations to be run within environment.
Specs within application work utilizing this database migration:
https://github.com/department-of-veterans-affairs/vets-api/pull/5334

API-3261: Database migration

---

config/features.yml

[Original Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16302)
This PR is to add the feature to features.yml for the flipper component on view payment history

16302 flipper toggle

---

config/settings.yml
config/settings/test.yml
lib/vre/ch31_form.rb
lib/vre/configuration.rb
lib/vre/errors/ch31_error.rb
lib/vre/service.rb
spec/lib/vre/ch31_form_spec.rb
spec/support/vcr_cassettes/veteran_readiness_employment/failed_send_to_vre.yml

[WIP DO NOT REVIEW] Temp pair 15801 ch 31 model

---

config/settings.yml

ssuddath@governmentcio.com added to admin list to toggle feature flags
department-of-veterans-affairs/va.gov-team#14452
This adds ssuddath@governmentcio.com to the admin user list to be able to toggle feature flags

Add srsuddath to flipper admin list

---

modules/claims_api/db/migrate/20201117200716_add_bgs_responses_column_to_auto_established_claims.rb

Fixes master CI. 
I suspect that [recent changes to how PR's lint only changes files](https://github.com/department-of-veterans-affairs/vets-api/pull/4036) had something to do w/ how this linting error was able to pass CI and make it into the `master` branch.
Related slack convo - https://dsva.slack.com/archives/C0MQ281DJ/p1606158027213800
None

fixing master CI lint

---

db/migrate/20201123000822_add_upload_metadata_to_vba_documents_upload_submission.rb
db/schema.rb

This is the migration needed for API-3044:
https://vajira.max.gov/browse/API-3044
https://vajira.max.gov/browse/API-3044
Just a migration to support the following upcoming pull request:
https://github.com/department-of-veterans-affairs/vets-api/pull/5303

Adding in migration for uploaded_pdf

---

modules/apps_api/lib/apps_api/directory_application_creator.rb

Per feedback from Andy Parcel, the casing for IOS apps on the directory has been corrected to iOS.

changed IOS to iOS in application descriptions

---

modules/claims_api/app/mailers/claims_api/unsuccessful_report_mailer.rb
modules/claims_api/app/views/claims_api/unsuccessful_report_mailer/unsuccessful_report.html.erb
modules/claims_api/app/workers/claims_api/report_unsuccessful_submissions.rb
modules/claims_api/spec/mailers/unsuccessful_report_mailer_spec.rb
modules/claims_api/spec/workers/report_unsuccessful_submissions_spec.rb
spec/mailers/previews/claims_api_unsuccessful_report_mailer_preview.rb

Adds flash information to existing claims report.
https://vajira.max.gov/browse/API-3259
Updated specs and tested template through ActionMailer preview.

API-3259: Flashes - Figure out what we want to capture and report on

---

app/models/in_progress_disability_compensation_form.rb

Removing an unused class.
This PR removed the only place it was in use https://github.com/department-of-veterans-affairs/vets-api/pull/2150

InProgressDisabilityCompensationForm is not used

---

db/schema.rb
modules/appeals_api/db/migrate/20201127195258_add_status_to_notice_of_disagreements.rb

Need to add status to notice of disagreements table
https://vajira.max.gov/browse/API-3828
Two migration files added

API-3828 Add status to notice of disagreement

---

README.md
docs/deployment/information.md

Added some basic information around deployments of this project. Primarily around the manual work involved with database migrations.
Discovered missing documentation when working on this ticket https://vajira.max.gov/browse/API-3261
Reviewed markdown in github

some basic deployment documentation

---

modules/appeals_api/db/migrate/20201127195258_add_status_to_notice_of_disagreements.rb

Master build is failing because of a linting issue.
None
Tested with rubocop locally.

Fix lint issue in master

---

modules/mobile/app/controllers/mobile/v0/claims_and_appeals_controller.rb
modules/mobile/spec/request/claims_and_appeals_overview_request_spec.rb

Changed sort of claims overview values from filed date to updated date
N/A
Small change to tests to match sorting change

changed value sorted by

---

modules/claims_api/app/swagger/claims_api/forms/form_526_response_swagger.rb
modules/claims_api/config/schemas/526.json

This adds missing values for the `flashes` enum in 526 schema and swagger
https://vajira.max.gov/browse/API-3254
there's a handful of values with unresolved questions. That's described in the [issue](https://vajira.max.gov/browse/API-3254).

Update list of enum values for flashes in swagger and 526 schema

---

modules/health_quest/app/services/health_quest/patient_generated_data/patient/factory.rb
modules/health_quest/app/services/health_quest/patient_generated_data/patient/map_query.rb
modules/health_quest/app/services/health_quest/patient_generated_data/patient/resource.rb
modules/health_quest/spec/services/patient_generated_data/patient/factory_spec.rb
modules/health_quest/spec/services/patient_generated_data/patient/map_query_spec.rb
modules/health_quest/spec/services/patient_generated_data/patient/resource_spec.rb

- Provide the ability for the health quest module to create a FHIR Patient resource on the sandbox PGD.
department-of-veterans-affairs/va.gov-team#16089
- RSpec tests written and run.
- Manually verified code locally.

16089 post patient pgd

---

modules/apps_api/app/controllers/apps_api/docs/v0/api_controller.rb
modules/apps_api/app/swagger/apps_api/v0/apps/apps_swagger.rb

Related: https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/15899

Name AppsSwagger after its filename

---

modules/health_quest/app/services/health_quest/pgd_service.rb
modules/health_quest/spec/services/pgd_service_spec.rb

Related: https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/15893

Rename PGDService to PatientGeneratedDataService for Zeitwerk

---

modules/appeals_api/bin/rails

Came upon this path while working on an unrelated ticket. It appears to be incorrect. Please check fix.

Fix incorrect path in bin/rails

---

Gemfile
Gemfile.lock
config/initializers/strong_migrations.rb

remove [zero_downtime_migrations](https://github.com/LendingHome/zero_downtime_migrations) (support for which has stagnated) and install [strong_migrations](https://github.com/ankane/strong_migrations)
department-of-veterans-affairs/va.gov-team#9156

use strong_migrations

---

db/schema.rb
modules/appeals_api/db/migrate/20201204151107_add_code_to_notice_of_disagreement.rb
modules/appeals_api/db/migrate/20201204151120_add_detail_to_notice_of_disagreement.rb

Implementing central mail service for notice of disagreement. The model requires two new attributes in order to capture and surface errors
https://vajira.max.gov/browse/API-3927
Two migrations
Testing to follow in related https://vajira.max.gov/browse/API-3623

Add NOD error attrs code and detail migration

---

README.md
docs/setup/docker.md
docs/setup/native.md
docs/setup/running_docker.md

Update Docker docs
https://github.com/department-of-veterans-affairs/va.gov-team/issues/16937
- fix missing code fence
- comply to markdownlint

Consolidate setup docs and Docker docs

---

app/controllers/v1/sessions_controller.rb

Adds a check for an error code in `login_stats` and substitutes a default code if none is found to prevent unexpected exceptions without an error code from generating more errors.
department-of-veterans-affairs/va.gov-team#15883
manual testing with breakpoints of `login_stats` method with no exceptions and exceptions without error codes

adds handling for internally generated errors in login_stats method

---

config/features.yml
db/schema.rb

Add a new `ch33_dd_profile` feature flag so we can gate the new Direct Deposit For Education Benefits in the front end.
Corresponding FE PR is at https://github.com/department-of-veterans-affairs/vets-website/pull/15229

add ch33_dd_profile feature flag

---

.github/CODEOWNERS

Defines CODEOWNERS for covid_vaccine module and spec directories, assigning to cto-health-care-products team. This aligns with ownership of the corresponding frontend app.

Defines CODEOWNERS for covid_vaccine module

---

config/features.yml

Removed `form_1995_edu_updates` feature flag
department-of-veterans-affairs/va.gov-team#14243

Remove form_1995_edu_updates feature

---

config/settings.yml

This PR adds @stephenBarrs into our Flipper admin group.
Related to FE app rollout https://github.com/department-of-veterans-affairs/vets-website/pull/15286

Add a new member to Flipper admins

---

modules/covid_vaccine/app/services/covid_vaccine/v0/registration_service.rb

Adds audit logging of submissions; sensitive fields are not logged, just the boolean presence/absence of them is logged.

Adds some audit logging of covid vaccine submission

---

modules/vba_documents/app/controllers/vba_documents/internal/v0/upload_complete_controller.rb
modules/vba_documents/spec/request/v0/upload_complete_request_spec.rb
modules/vba_documents/spec/request/v0/uploads_request_spec.rb

Eliminating the last upload call for the gdit to gov cio transition.

Commenting out last async call.

---

modules/apps_api/lib/apps_api/directory_application_creator.rb

Added Coral Health to DirectoryApplication records to be displayed in the Application Directory on https://www.va.gov/resources/find-apps-you-can-use/
https://lighthouseva.slack.com/archives/CMT4MFPS6/p1594217990164600
No other changes!

Add Coral Health to Application Directory

---

app/models/form526_submission.rb
app/models/saved_claim.rb
modules/vba_documents/spec/request/v0/uploads_request_spec.rb
spec/jobs/structured_data/process_data_job_spec.rb
spec/lib/saved_claims_spec_helper.rb
spec/models/form526_submission_spec.rb
spec/models/saved_claim/pension_spec.rb

Reverts department-of-veterans-affairs/vets-api#5475

Revert "Turning off GDIT submissions for GCIO transition for va.gov code"

---

modules/claims_api/app/views/claims_api/unsuccessful_report_mailer/_submission_table.html.erb
modules/claims_api/app/views/claims_api/unsuccessful_report_mailer/unsuccessful_report.html.erb
modules/claims_api/app/workers/claims_api/report_unsuccessful_submissions.rb

Add small styling to improve error readability.
"Uniqify" EVSS responses for errors table.
https://vajira.max.gov/browse/API-3812

API-3812: Improve unsuccessful claims report

---

modules/health_quest/config/mock/appointment.yml

- Adding phone numbers to both facility and clinic objects in the appointment.yml file

add phone numbers to mock appointment

---

modules/covid_vaccine/app/jobs/covid_vaccine/registration_email_job.rb
modules/covid_vaccine/spec/jobs/covid_vaccine/registration_email_job_spec.rb

Changes needed to get the mailer to work. Was expecting the wrong object to be returned. Causing Sidekiq worker to fail.

remove the logger line thats causing mailer to fail

---

app/controllers/appeals_base_controller.rb
modules/claims_api/app/swagger/claims_api/description/v0.md
modules/claims_api/app/swagger/claims_api/description/v1.md
modules/claims_api/app/swagger/claims_api/forms/form_526_response_swagger.rb

Needed to update Flashes information.
https://vajira.max.gov/browse/API-3253

Updating Flashes documentation

---

lib/mpi/service.rb

Update to #5340 to log invalid `find_user` MVI requests as `extra_content` instead of as a `tag` in order to properly debug Invalid Request exceptions.
Sentry Example: http://sentry.vfs.va.gov/organizations/vsp/issues/10852/?environment=production&project=3&query=is%3Aunresolved+message%3A%22MPI%3A%3AErrors%3A%3AInvalidRequestError%22&statsPeriod=14d
department-of-veterans-affairs/va.gov-team#15180

MVI Invalid Request Exception logging update

---

config/features.yml

Continuation of [this pr](https://github.com/department-of-veterans-affairs/vets-api/pull/5540) to add feature name to the config registery.
department-of-veterans-affairs/va.gov-team#10758
There is a new feature name.

DT-10758 - Added Find a forms feature name for Flipper.

---

app/models/account.rb
spec/models/account_spec.rb

[This PR](https://github.com/department-of-veterans-affairs/vets-api/pull/5529) was rolled out in an emergency and this adds some tests

account scopes use none
