- config/features.yml
- Created a feature flag `cst_send_evidence_submission_failure_emails` 
- *Link to ticket created in va.gov-team repo https://github.com/department-of-veterans-affairs/va.gov-team/issues/100037
- Ran locally and I see feature flag
Images of new feature flag 
CST
> [CST] - Add feature flag `cst_send_evidence_submission_failure_emails`

- Gemfile.lock
- modules/simple_forms_api/app/models/simple_forms_api/vba_21_4140.rb
- modules/simple_forms_api/spec/models/vba_20_10207_spec.rb
- modules/simple_forms_api/spec/models/vba_21_0845_spec.rb
- modules/simple_forms_api/spec/models/vba_21_0966_spec.rb
- modules/simple_forms_api/spec/models/vba_21_4140_spec.rb
- modules/simple_forms_api/spec/models/vba_40_0247_spec.rb
- modules/simple_forms_api/spec/requests/simple_forms_api/v1/simple_forms_spec.rb
- modules/simple_forms_api/spec/support/shared_examples_for_base_form.rb
- Adds `#zip_code_is_us_based` to the `VBA214140` model.
- Refactors model specs to use a shared spec that takes in the address keys as params.
- Fixes a bug with the simple forms specs where only the last called form was being used to run the shared examples.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/93461
- Added new shared example spec that tests this method on every applicable simple form.
- Fixed bug with existing spec.
At the moment, none. It will ultimately impact the Simple Forms API, adding support for the 21-4140 form.
This was originally part of a larger PR but had to be broken out because too many lines of code were being altered. Let me know if there is a better way to deal with the LOC limit …
> 93461: Add #zip_code_is_us_based to VBA214140

- app/models/application_record.rb
- lib/common/client/concerns/monitoring.rb
- modules/accredited_representative_portal/app/policies/accredited_representative_portal/application_policy.rb
- modules/va_notify/lib/va_notify/service.rb
Updated instances of `caller_locations` to use `base_label` instead of `label`, reflecting changes in Ruby 3.4 where `label` includes the class name and `base_label` includes only the method name. This ensures correct behavior as we are expecting only the method name.
https://stackoverflow.com/questions/5100299/how-to-get-the-name-of-the-calling-method#comment139868411_15098459
> fix: update caller location handling for Ruby 3.4 compatibility

- Gemfile.lock
- Bump argon2-kdf from 0.2.0 to 0.3.0 to include fiddle as a dependency.
- Resolves deprecation warning for `fiddle` not being part of default gems in Ruby 3.5+.
Warning:
```
.bundle/bundle/ruby/3.4.0/gems/argon2-kdf-0.2.0/lib/argon2/kdf.rb:2: warning:
~/.local/share/mise/installs/ruby/3.4.1/lib/ruby/3.4.0/fiddle/import.rb is found in
fiddle, which will no longer be part of the default gems starting from Ruby 3.5.0.
```
> fix: update argon2-kdf gem to address fiddle deprecation warning

- modules/ivc_champva/app/services/ivc_champva/pdf_filler.rb
- modules/ivc_champva/spec/services/pdf_filler_spec.rb
Fix: Prevent race conditions causing "No such file or directory" errors
This PR addresses a recurring issue where file processing operations (e.g., PDF generation, uploads) were failing with "No such file or directory" errors. This was caused by race conditions where operations were attempted on files before they were fully written to disk.
Key changes:
*   Modified `create_tempfile` to explicitly flush and close temporary files.
*   Added unit tests to verify file completion.
This change improves the reliability of file processing and prevents intermittent errors.
https://github.com/department-of-veterans-affairs/vets-api/pull/19930
https://github.com/orgs/department-of-veterans-affairs/projects/1533/views/1?pane=issue&itemId=89440653 …
> add flush statement

- app/models/form_profiles/va_21686c.rb
- app/models/form_profiles/va_526ez.rb
- modules/ask_va_api/app/controllers/ask_va_api/v0/address_validation_controller.rb
- spec/models/form_profile_spec.rb
- spec/models/form_profile_v2_spec.rb
The 21686c and va_526 form profiles were using the wrong policy for user authorization when initializing veteran information. The evss access policy requires a user to have an edipi, ssn.present, and participant_id. ICN is the only thing needed to initialize contact information for V2 and the va_profile access_to_v2 only requires an ICN, which is only present for verified users.
The va_526 initialize_veteran_contact_information method was reformatted due to rubocop linting errors.
The `country_name` parameter was added to the …
> Corrected Contact Info V2 authorization policies and added country_name to the AskVA AddressValidation Controller params

- lib/medical_records/bb_internal/client.rb
- spec/lib/medical_records/bb_internal/client_spec.rb
- Quick fix to escape spaces in the last name to avoid `InvalidURIError`
> We need to escape the "last name" param in the URL, as spaces in the name cause a failure with InvalidURIError.
> 
> Slack thread: https://dsva.slack.com/archives/C04ER7MHX5E/p1735843276066719
> 
> Example DD trace: https://vagov.ddog-gov.com/apm/trace/1288248410188108306?timeHint=1735840358996.1582
- Previously, call to generate the CCD returned a `InvalidURIError`
- To validate, generate the CCD for a user with a space in the last name
> MHV-65628 Escape spaces in name for generate_ccd

- config/features.yml
- Added new feature toggle to features.yml called `appoint_a_representative_enable_2.0_features`
- https://github.com/orgs/department-of-veterans-affairs/projects/1180/views/5?pane=issue&itemId=92511144&issue=department-of-veterans-affairs%7Cva.gov-team%7C99977
> Added feature toggle for appoint a rep v2 features

- app/controllers/v0/users_controller.rb
- spec/controllers/v0/users_controller_spec.rb
- This PR fixes a bug in the credential email route that occurs when a user's `UserVerification` does not have a `UserCredentialEmail`
Interstitial Authentication
> Fix bug in credential email route with missing credential email

- modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb
- This PR enhances the API responses for both synchronous and asynchronous submissions by adding a `submissionApi` field. This field indicates whether the submission originates from the benefits intake API (central mail) or the benefits claim API, allowing the frontend to differentiate between the two types of submissions.
- The previous responses did not include this field, which could lead to confusion on the frontend regarding the type of submission being processed.
- The solution involves modifying the response generation logic in the relevant API controllers to include the `submissionApi` field based on the context of the submission (intake vs. claim vs. SAHSHA). This change is necessary to improve the clarity and usability of the …
> [SIMPLE-FORMS] feat: add submission api to submit return json

- modules/accredited_representative_portal/spec/requests/accredited_representative_portal/v0/power_of_attorney_requests_spec.rb
This PR temporarily skips some request specs that will fail due to a migration that will be introduced in a subsequent PR that introduces migration changes.
The skipped specs in this PR will be fixed and unskipped after the new migrations have been merged in.
> 6: [ART] Skip spec for POA request representatives migration

- config/settings.yml
- lib/lighthouse/benefits_documents/configuration.rb
Related to previous timeout PRs
https://github.com/department-of-veterans-affairs/vets-api/pull/20174
https://github.com/department-of-veterans-affairs/vets-api/pull/20173
We need to actually make this higher than the lighthouse side timeout otherwise we are in the same situation potentially. 
Lighthouse timeout is 60s, if we set ours to 55s, any requests that complete in 55-60s still leave us in the same potential situation of not knowing if lighthouse actually got/sent the file or not. 
If we set to higher than their timeout, we rely on them to tell us if they timed out or not by their timeout and therefore eliminate uncertainty and eliminate this risk.
> Bumping to OVER lighthouse limit

- Gemfile
- Gemfile.lock
- lib/sidekiq/semantic_logging.rb
Update Sidekiq from 7.2 to 7.3.
- The Gemfile has also been updated to remove the version constraint for `sidekiq`.
- `sidekiq-ent` and `sidekiq-pro` have also been upgraded to 7.3.x
> chore: Update Sidekiq gem to 7.3.4

- lib/vets/collection.rb
- lib/vets/collections/finder.rb
- spec/lib/vets/collection_spec.rb
- spec/lib/vets/collections/finder_spec.rb
**_Mergers to a feature branch_**
- Add new `where` and `find_by` method to collection class
- Create a new class `Finder` to handle "filtering" for records
- main PR: https://github.com/department-of-veterans-affairs/vets-api/pull/19895
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/99123
`Common::Collection` uses `find_by` to find all "matching" records and `find_first_by` to find the first. I believe these are bad choices because `find_by` is used by ActiveRecord to get a single object. So I chose to rename the find all and find first method names to mimic the most similar query methods... `where` and `find_by` for Vets::Collection.
I'm open to other suggestions, but I think `find_by` and `find_first_by` should be renamed
> Add filtering info to Vets::Collection

- modules/simple_forms_api/app/form_mappings/vba_21_4140.json.erb
- modules/simple_forms_api/app/models/form_engine/address.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_21_4140.rb
- modules/simple_forms_api/spec/models/vba_21_4140_spec.rb
- modules/simple_forms_api/spec/support/shared_examples_for_base_form.rb
- This is the 4th PR (after https://github.com/department-of-veterans-affairs/vets-api/pull/20156) sprung from https://github.com/department-of-veterans-affairs/va.gov-team/issues/93461 due to LOC limitations. There will be at least one more after this.
- Adds an `#address` instance method to `VBA214140`. Maps all relevant attributes to the associated PDF template.
- Creates a `FormEngine::Address` class to properly format Form Engine addresses.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/93461
- Unit tests for `#address` instance method and a spec to ensure ISO 2 conversion works.
At the moment, none. It will ultimately impact the Simple Forms API, adding support for the 21-4140 form.
If anyone has strong …
> 93461: Add #address to VBA214140

- lib/medical_records/bb_internal/client.rb
- modules/my_health/spec/requests/my_health/v1/medical_records/imaging_spec.rb
- modules/my_health/spec/requests/my_health/v1/medical_records/radiology_spec.rb
- spec/lib/medical_records/bb_internal/client_spec.rb
- There is currently a very small window during which requests can be made while the ICN is not set in session (`session.ICN` is briefly deleted while calling a super method and then restored).
- This is a small fix to ensure that ICN is present when making requests.
> The request_download action is failing just about 1% of the time with a 404. This appears to be because the ICN is not being included in the backend request. You can see a list of these errors [here](https://vagov.ddog-gov.com/logs?query=bluebutton%20studyjob%20icn%20studyid%20status%3Awarn&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1736271128595&to_ts=1736443928595&live=true).
- As this is only an …
> MHV-65985 Added a check to block BBInternal client init threads if ICN is not set

- modules/ivc_champva/app/jobs/ivc_champva/missing_form_status_job.rb
Per this [discussion](https://dsva.slack.com/archives/C010R6AUPHT/p1736529002758789?thread_ts=1735681070.281949&cid=C010R6AUPHT), the VA Notify callback is breaking because our `statsd_tags` were configured as a string rather than a hash with values `service` and `function`.
This PR updates that, which should hopefully allow the callback to work as expected. This is part of ongoing work and requires testing in staging. 
This work is behind a feature flag.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/98603
- *Tests …
> 98603 Update metadata to match what VANotify expects - IVC CHAMPVA forms

- app/models/accredited_individual.rb
- app/models/accredited_organization.rb
- modules/accredited_representative_portal/app/controllers/accredited_representative_portal/v0/power_of_attorney_requests_controller.rb
- modules/accredited_representative_portal/app/models/accredited_representative_portal/power_of_attorney_request.rb
- modules/accredited_representative_portal/app/serializers/accredited_representative_portal/power_of_attorney_request_serializer.rb
- modules/accredited_representative_portal/app/serializers/accredited_representative_portal/power_of_attorney_request_serializer/accredited_individual_serializer.rb
- modules/accredited_representative_portal/app/serializers/accredited_representative_portal/power_of_attorney_request_serializer/power_of_attorney_holder_serializer.rb
- modules/accredited_representative_portal/spec/factories/power_of_attorney_request.rb
- modules/accredited_representative_portal/spec/requests/accredited_representative_portal/v0/power_of_attorney_requests_spec.rb
**Add Power of Attorney Representative Support to Accredited Representative Portal**
Description:
This PR introduces enhancements to the Accredited Representative Portal to support Power of Attorney (POA) request representatives (accredited individuals and organizations). The key changes include:
Key Changes:
1.	Model Changes:
•	Added new references and associations for power_of_attorney_requests to support representatives (accredited_individuals and accredited_organizations).
•	Updated the PowerOfAttorneyRequest model with new relationships (belongs_to and has_one) and validations for claimant data.
•	Added a mechanism to handle the claimant type (dependent or veteran) during record creation.
2.	Controllers
•	Minor modification to how querying is handled in the POA requests controller. …
> 8: [ART] POA request representative

- config/form_profile_mappings/10182.yml
- config/form_profile_mappings/20-0996.yml
- spec/models/form_profile_spec.rb
- spec/models/form_profile_v2_spec.rb
> NO
> We're removing prefill data that isn't being used by our Decision Review forms.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/99077
N/A
N/A
Decision Reviews forms: Higher-Level Review (0996) and Notice of Disagreement (10182)
(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you …
> DR | Remove unused prefills

- modules/ivc_champva/app/jobs/ivc_champva/missing_form_status_job.rb
Per this [discussion](https://dsva.slack.com/archives/C010R6AUPHT/p1736539531619509?thread_ts=1735681070.281949&cid=C010R6AUPHT), the VA Notify callback is breaking because our `statsd_tags` were configured as a string rather than a hash with values `service` and `function`.
This PR updates that, which should hopefully allow the callback to work as expected. This is part of ongoing work and requires testing in staging. 
This work is behind a feature flag.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/98603
- *Tests …
> Replace `statsd_tag` with proper `statsd_tags` in VA Notify callback metadata hash - IVC CHAMPVA forms

- .github/CODEOWNERS
- app/controllers/v0/user/mhv_user_accounts_controller.rb
- app/models/user.rb
- app/policies/mhv_user_account_policy.rb
- spec/controllers/v0/user/mhv_user_accounts_controller_spec.rb
- spec/policies/mhv_user_account_policy_spec.rb
- Add policy to check if user can create a MhvUserAccount 
- https://jira.devops.va.gov/browse/VI-957
- Test`/v0/user/mhv_user_account` with loa1 user
- You should get a 403
- Test`/v0/user/mhv_user_account` with loa3 user
- You should get a 200
MHV User Accounts
> [VI-957] Add MHVUserAccountPolicy

- modules/accredited_representative_portal/app/models/accredited_representative_portal/power_of_attorney_request_resolution.rb
- modules/accredited_representative_portal/spec/models/accredited_representative_portal/power_of_attorney_request_resolution_spec.rb
This pull request introduces a uniqueness constraint for `power_of_attorney_request` in the `PowerOfAttorneyRequestResolution` model to ensure that each POA request can only be resolved once.  
- **Model Validation:**  
- Added a `validates :power_of_attorney_request, uniqueness: true` constraint to enforce uniqueness for POA requests.  
- **Test Coverage:**  
- Created a new RSpec test suite for `PowerOfAttorneyRequestResolution` to verify the uniqueness validation.  
- The test ensures an appropriate error message is displayed when a duplicate POA resolution is attempted.
> 10: [ART] POA request resolution validates unique POA request

- modules/claims_api/app/sidekiq/claims_api/poa_assign_dependent_claimant_job.rb
* Makes argument optional so v1 calls to `PoaAssignDependentClaimantJob` still succeed
[API-43896](https://jira.devops.va.gov/browse/API-43896)
- *Describe what the old behavior was prior to the change* - No changes to existing behavior, this is jsut a fix since this job was being called from two places and only one is sending in the added argument
modified:   modules/claims_api/app/sidekiq/claims_api/poa_assign_dependent_claimant_job.rb
> API-43896-v1-poa-dependent-job-arguments

- app/models/form_profiles/va_526ez.rb
- app/services/claim_fast_tracking/max_rating_annotator.rb
- config/features.yml
- spec/services/claim_fast_tracking/max_rating_annotator_spec.rb
- This PR introduces the **`disability_526_max_cfi_service_switch`** feature flag to control the switch between the Virtual Regional Office (VRO) client and a new Max Ratings service for fetching disability max ratings.
- No bugs were fixed in this PR, only the addition of the new feature flag and corresponding logic.
- The solution introduces a feature flag to control which service is used. When the feature flag is **enabled**, it will use the new service logic (to be implemented); when **disabled**, it will default to the VRO client.
- I am part of the **Employee Experience team (EE)**
- [#3947](https://github.com/department-of-veterans-affairs/abd-vro/issues/3947)
- The old behavior was to use the VRO client by default for …
> Add feature flag for Max CFI service switch and tests

- config/features.yml
- Renamed feature toggle to avoid the `.` character
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/99977
> Renaming feature toggle to remove . character

- app/models/user.rb
- app/services/mhv/user_account/creator.rb
- lib/mhv/account_creation/service.rb
- spec/controllers/v0/user/mhv_user_accounts_controller_spec.rb
- spec/lib/mhv/account_creation/service_spec.rb
- spec/models/user_spec.rb
- spec/services/mhv/user_account/creator_spec.rb
- `User#mhv_user_account` will always use the cached version. If there is no cached version, it will return nil.
- https://jira.devops.va.gov/browse/VI-968
- make sure your local cache is enabled `rails dev:cache`
- Cache the mhv_user_account request for the user you will login with
- start a rails server - `rails s`
- in rails console - `rails c`:
```ruby
icn = 1012667122V019349 # change to the icn of the user you will login with (they need to have accepted TOU)
user_account = User.find_by(icn:)
user_verification = user_account.user_verifications.idme.first 
MHV::UserAccount::Creator.new(user_verification:).perform
```
- Check to make sure the response was cached
```ruby
cache_key = "mhv_account_creation_#{icn}"
Rails.cache.read(cache_key)
```
- Start vets-website and login
- go to …
> Always use mhv_user_account cached response on User

- modules/simple_forms_api/app/services/simple_forms_api/notification_email.rb
This PR adds a fallback where we do not rely on form data for a veteran's first name but instead we rely on their logged-in user's first name. This is for sending emails after receipt of submissions.
https://github.com/orgs/department-of-veterans-affairs/projects/1443/views/3?sliceBy%5Bvalue%5D=Thrillberg&pane=issue&itemId=93326260&issue=department-of-veterans-affairs%7CVA.gov-team-forms%7C1967
> Fallback to current user's first name in 21-0966

- modules/simple_forms_api/app/form_mappings/vba_21_4140.json.erb
- modules/simple_forms_api/app/models/form_engine/employment_history.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_21_4140.rb
- modules/simple_forms_api/spec/fixtures/form_json/vba_21_4140-min.json
- modules/simple_forms_api/spec/fixtures/form_json/vba_21_4140.json
- modules/simple_forms_api/spec/models/form_engine/employment_history_spec.rb
- modules/simple_forms_api/spec/models/vba_21_4140_spec.rb
- This should be the penultimate PR spawned from https://github.com/department-of-veterans-affairs/va.gov-team/issues/93461 due to LOC limitations. There should be one more PR after this.
- Adds `#employment_history` and `#employed?` to `VBA214140`.
- Maps employment history submission data to the 21-4140 PDF template.
- Creates a `FormEngine::EmploymentHistory` class to handle employment history data.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/93461
- Unit tests for the new `FormEngine::EmploymentHistory` class
- Unit tests for the `#employment_history` and `#employed?` instance methods
At the moment, none. It will ultimately impact the Simple Forms API, adding support for the 21-4140 form.
(OPTIONAL)_What …
> 93461: Add #employment_history to VBA214140

- modules/vaos/app/services/vaos/v2/appointments_service.rb
- This PR adds additional diagnostic logs to help us determine the large number of modality parsing failures
- Discussion regarding this issue is in [this slack thread](https://dsva.slack.com/archives/CMNQT72LX/p1734727335423249)
- N/A
- Tested locally but the sampling mechanism is not amenable unit testing
N/A
> Add diagnostics for VAOS modality error

- app/services/mhv/user_account/creator.rb
- spec/controllers/v0/user/mhv_user_accounts_controller_spec.rb
- spec/models/user_spec.rb
- spec/services/mhv/user_account/creator_spec.rb
- This PR removes the email requirement to call the MHV Account Creator API. Some MHV Users don't have an email, so this allows them to successfully call the MHV Account Creation API
- https://jira.devops.va.gov/browse/VI-976
- Logged in locally and confirmed a user with a 'nil' value for `UserVerification.user_credential_email` was able to call the MHV Account creation API
MHV Account Creation API
> [VI-976] Removing email requirement to call MHV Account Creator API

- config/environments/development.rb
- config/environments/test.rb
- modules/ask_va_api/app/controllers/ask_va_api/v0/inquiries_controller.rb
- modules/check_in/app/controllers/check_in/v0/travel_claims_controller.rb
- modules/claims_api/app/controllers/claims_api/v1/application_controller.rb
- modules/claims_api/app/controllers/claims_api/v2/application_controller.rb
- modules/covid_vaccine/app/controllers/covid_vaccine/application_controller.rb
- modules/covid_vaccine/app/controllers/covid_vaccine/v0/registration_controller.rb
- modules/mobile/app/controllers/mobile/concerns/sso_logging.rb
- modules/mobile/app/controllers/mobile/v0/addresses_controller.rb
- modules/mobile/app/controllers/mobile/v0/profile_base_controller.rb
- in Rails 7.1, the config option `raise_on_missing_callback_actions` was introduced. When enabled, errors are raised if a callback (`before_action`, `after_action`, etc) specifies an action or method (via `:only`/`:except`) that isn't explicitly defined in the controller (or a controller it inherits from).
- In Rails 8, The default configuration is to set `raise_on_missing_callback_actions` to `true` in both `test` and `development`.
- There are several instances in vets-api where a team has defined these callbacks in a base controller with the intent to define the callbacks in the derived/child controllers. In most of these cases, I used some logic that uses the `action_name` to determine if the callback should be executed, which effectively gives the same behavior. I one case case I …
> set raise_on_missing_callback_actions to true

- config/features.yml
> NO - toggle removed from the frontend
> Removing `hlr_updateed_contnet` (typo expected) as it's no longer being used, but not yet deployed to production
https://github.com/department-of-veterans-affairs/va.gov-team/issues/100041
N/A
N/A
Higher-Level Review form
(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. …
> HLR | Remove content toggle

- app/controllers/v1/sessions_controller.rb
- lib/saml/url_service.rb
- spec/controllers/v1/sessions_controller_spec.rb
- This PR adds the 'operation' param to SSOe authentication callback. It should now populate in logs to show which users successfully authenticated based on the 'operation' that was used during authentication
- https://jira.devops.va.gov/browse/VI-977
Authentication
> [VI-977] Add operation param to SSOe auth callback

- app/sidekiq/lighthouse/submit_benefits_intake_claim.rb
- Adds the form_id to the logs in Lighthouse::SubmitBenefitsIntakeClaim to allow teams to limit their monitors to their own form(s). 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/100836
Burials, Education Career Counseling, VRE, and users of SavedClaim.
> Log form id in SubmitBenefitsIntakeClaim

- app/sidekiq/hca/log_email_diff_job.rb
- config/features.yml
- spec/sidekiq/hca/log_email_diff_job_spec.rb
- Removing `hca_log_email_diff_in_progress_form` flipper toggle and corresponding usage. We have had this toggle turned on and now that logic will be the default. This PR removes the other logic flow that used a redis key and now only uses the database table.
- I will delete the toggle from all environment databases once this is merged in and deployed.
- Deleting the `hca_log_email_diff_in_progress_form` toggle
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/99303 …
> [10-10EZ] Remove log email diff toggle

- lib/periodic_jobs.rb
- Addendum to https://github.com/department-of-veterans-affairs/vets-api/pull/20080
- https://jira.devops.va.gov/browse/VI-912
> [VI-912] removes covid_vaccine periodic jobs

- app/controllers/v0/claim_documents_controller.rb
- The conditional that checks for pension and burial applications for the updated validation process for document uploads was checking for the incorrect burials form_id. It should've been `21P-530EZ` but was instead checking for `21P-530`. This PR rectifies this issue.
- Go to burial application and attempt to upload invalid documents on the "Additional Information" page. The validations should block uploads of invalid files, but uploads succeed due to the incorrect form_id being checked.
- Pension & Burial Program (PBP) team to own this work.
- [*Link to ticket created in va.gov-team repo*](https://github.com/department-of-veterans-affairs/va.gov-team/issues/101121)
- [*Link to previous change of the …
> updated expected form id for burial applications

- app/controllers/appeals_base_controller_v1.rb
- app/controllers/v1/decision_review_evidences_controller.rb
- app/controllers/v1/decision_review_notification_callbacks_controller.rb
- app/controllers/v1/higher_level_reviews/contestable_issues_controller.rb
- app/controllers/v1/higher_level_reviews_controller.rb
- app/controllers/v1/notice_of_disagreements/contestable_issues_controller.rb
- app/controllers/v1/notice_of_disagreements_controller.rb
- app/controllers/v1/supplemental_claims/contestable_issues_controller.rb
- app/controllers/v1/supplemental_claims_controller.rb
- app/controllers/v2/higher_level_reviews_controller.rb
- spec/controllers/v1/decision_review_evidences_controller_spec.rb
- spec/controllers/v1/decision_review_notification_callbacks_controller_spec.rb
- spec/requests/v1/higher_level_reviews/contestable_issues_spec.rb
- spec/requests/v1/higher_level_reviews_spec.rb
- spec/requests/v1/notice_of_disagreements/contestable_issues_spec.rb
- spec/requests/v1/notice_of_disagreements_spec.rb
- spec/requests/v1/supplemental_claims/contestable_issues_spec.rb
- spec/requests/v1/supplemental_claims_spec.rb
- spec/requests/v2/higher_level_reviews_spec.rb
Add logging to all non-module DR controllers, in preparation for switching to use the module versions. Intent is to be able to track any other code paths using the non-module DR controllers after we switch
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/98907
No logging when old controller methods were called
Call the old endpoints, …
> Add logging to non-module Decision Review controllers

- spec/lib/sidekiq/form526_backup_submission_process/submit_spec.rb
- This spec has been known to fail intermittently with a `pdftk` error. Here's an [example run](https://github.com/department-of-veterans-affairs/vets-api/actions/runs/12794287583/job/35669085970?pr=20278).
```
Failures:
1) V1::SupplementalClaims #create with 4142 when tracking 4142 is enabled creates a supplemental claim and queues and saves a 4142 form when 4142 info is provided
Failure/Error: PDFUtilities::PDFTK.stamp(file_path, stamp_path, stamped_pdf)
PdfForms::PdftkError:
pdftk failed with command
/usr/bin/pdftk tmp/pdfs/21-4142_.pdf stamp tmp/a5c3a552c1528d5915afaa7a4c4b507a output tmp/8b5cf1adcd36d23aa66468bca3fec196.pdf
command output was:
Error: Invalid PDF: trailer not found.
Error: Failed to open input PDF file: 
tmp/pdfs/21-4142_.pdf
Errors encountered.  No output created. …
```
> Skip flaky test block

- app/services/claim_fast_tracking/max_rating_annotator.rb
- spec/services/claim_fast_tracking/max_rating_annotator_spec.rb
- Replaced `Rails.logger.info` calls in `log_hyphenated_diagnostic_codes` with `StatsD.increment` to avoid logging sensitive diagnostic codes. The new metrics include diagnostic code, diagnostic code type, and hyphenated diagnostic code as tags.
- This change improves privacy by preventing potential de-anonymization of veterans based on logged diagnostic codes.
- [#3941](https://github.com/department-of-veterans-affairs/abd-vro/issues/3941)
- Previously, diagnostic codes were logged using `Rails.logger.info`.
- Verified that `StatsD.increment` is now used to record metrics, and updated tests to ensure that the correct metrics and tags are being sent.
- This change impacts the `log_hyphenated_diagnostic_codes` method in the …
> replace Rails logging with StatsD metrics for diagnostic codes 

- modules/accredited_representative_portal/Rakefile
- modules/accredited_representative_portal/app/models/accredited_representative_portal/power_of_attorney_form.rb
- modules/accredited_representative_portal/app/models/accredited_representative_portal/power_of_attorney_request.rb
- modules/accredited_representative_portal/app/models/accredited_representative_portal/power_of_attorney_request_resolution.rb
- modules/accredited_representative_portal/lib/tasks/seed.rake
- modules/accredited_representative_portal/lib/tasks/seed/records.rb
- modules/accredited_representative_portal/spec/factories/power_of_attorney_form.rb
- modules/accredited_representative_portal/spec/models/accredited_representative_portal/power_of_attorney_request_decision_spec.rb
- modules/accredited_representative_portal/spec/models/accredited_representative_portal/power_of_attorney_request_resolution_spec.rb
- modules/accredited_representative_portal/spec/models/accredited_representative_portal/power_of_attorney_request_spec.rb
- spec/factories/accredited_individuals.rb
This PR introduces a rake task for seeding POA requests for Dev and Staging use.
```
bin/rails accredited_representative_portal:seed
```
Seeds 123 POA requests associated with the [staging seed data for representatives](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/accredited-representation-management/accredited-entities-test-data.md) introduced by ARM (but locally).
> 11: [ART] POA request seed task for dev

- .github/CODEOWNERS
- spec/simplecov_helper.rb
- spec/spec_helper.rb
- spec/support/codeowners_parser.rb
- Creates a `CodeownersParser` support class - this class takes a team name and returns all `.github/CODEOWNERS` line entries that match the name.
- Invokes the support class in `spec/spec_helpers` `SimpleCov` configuration for the `octo-identity` team.
- Updates `.github/CODEOWNERS` to add Identity team coverage to new files.
- https://jira.devops.va.gov/browse/VI-962
```ruby
require('./spec/support/codeowners_parser')
codeowners_parser = CodeownersParser.new
octo_identity_files = codeowners_parser.perform('octo-identity')
=> ["app/controllers/concerns/accountable.rb",
...]
```
- run the full test suite: `bundle exec rake parallel:spec`
- navigate to the `vets-api/coverage/index.html` file in your browser
- `OctoIdentity` should appear as a group
`spec_helper`, SimpleCov
> [VI-962] adds CodeownersParser & octo-identity test coverage group

- db/migrate/20250109172425_remove_covid_vaccine_registration_submissions.rb
- db/schema.rb
- Tech debt PR to remove deprecated `covid_vaccine` module database tables.
- https://jira.devops.va.gov/browse/VI-912
- https://github.com/department-of-veterans-affairs/vets-api/pull/20080
- https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/3351
- https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/3352
- Successful app launch & authentication following migration & re-seeding of DB.
None, code is already deprecated.
> [VI-912] removes covid_vaccine registration submission tables

- db/migrate/20250116192421_add_can_accept_digital_poa_requests_to_veteran_organizations.rb
- db/schema.rb
- This pr adds a boolean column to `veteran_organizations` that is intended to enable/disable the ability for organizations to receive digital poa requests that can be acted upon in the accredited rep portal.
- This is the short term, low lift solution for our pilot program. The implementation and source of truth will be revisited post-pilot.
- [99972](https://github.com/department-of-veterans-affairs/va.gov-team/issues/99972)
- Ran the migration locally. Unit tests are not applicable.
This will be used in Appoint a Rep Form 21-22 and 21-22a and the Accredited Representative Portal. No immediate impact.
> [99972] Add org level poa submission indicator

- modules/representation_management/lib/representation_management/v0/pdf_constructor/form_2122a.rb
- modules/representation_management/spec/lib/representation_management/v0/pdf_constructor/form_2122a_spec.rb
- *(Summarize the changes that have been made to the platform):* A missing representative phone number will no longer crash the 2122a PDF generation.
- *(If bug, how to reproduce):* 
- *(What is the solution, why is this the solution?):* This ensures the PDF generation won't crash due to data inconsistencies we don't have control over.
- *(Which team do you work for, does your team own the maintenance of this component?):* FAR/ARM, yes we own the maintenance.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/101149 …
> 2122a PDF generation missing rep phone fix

- lib/periodic_jobs.rb
This PR changes the frequency and offset of the SavedClaim status updater jobs to reduce the number of requests to the LH API.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/99356
Tested locally.
The old behavior was to run all status updater jobs hourly - this decreases the frequency of each job to 6 times a day.
Sidekiq jobs to update the SavedClaim table
> 99356: Reduce frequency of DR SavedClaim status updater jobs

- .rubocop_todo.yml
- lib/common/exceptions/backend_service_exception.rb
- Fixes the following Rubocop offenses:
- `Rails/StripHeredoc`
- Use squiggly heredoc (<<~) instead of strip_heredoc
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/100982
> Fix Rubocop/Rails 3

- config/features.yml
- modules/ivc_champva/app/services/ivc_champva/file_uploader.rb
- modules/ivc_champva/lib/ivc_champva/monitor.rb
- modules/ivc_champva/spec/services/file_uploader_spec.rb
This PR updates the way the IVC CHAMPVA module handles missing uploads when some fail to make it to S3. Previously, the user's submission was allowed to continue if some files failed to make it through. Then steps were taken to manually interpret the submission and determine if enough information made it through. 
This created a lot of manual work and room for error. This PR updates the backend so that rather than letting incomplete submissions through, we fail the submission and throw an error that bubbles up to the user. This will prevent users from having a false impression that their submission was acceptable and provides breathing room until the file transmission issue can be worked out.
For more background and context, see this …
> 100496 Throw 500 if any files fail to make it to S3 - IVC CHAMPVA forms

- config/features.yml
- config/settings.yml
- modules/pensions/app/sidekiq/pensions/pension_benefit_intake_job.rb
- modules/pensions/lib/pensions/monitor.rb
- modules/pensions/spec/lib/pensions/monitor_spec.rb
- modules/pensions/spec/sidekiq/pensions/pension_benefit_intake_job_spec.rb
- Send an email notifying applicants that their Pension application was submitted on VA.gov, replacing the current confirmation email.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/94104
Pensions
> Pension submitted email

- app/controllers/v0/apidocs_controller.rb
- Updates Swagger documentation for the new Realtime Banners API to matchup keys
- Original work was recently created here https://github.com/department-of-veterans-affairs/vets-api/pull/20234
- Sitewide Team owns and maintains the Banners Controller API and its related docs
- Issue: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19908
- Epic: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19302
- OG PR: https://github.com/department-of-veterans-affairs/vets-api/pull/20234
- AFAIK there is no way to test our Swagger documentation locally. This documentation update will need to be verified on https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/ once …
> [VACMS-19908]Swagger API docs, lower case "b" for banners keys to lineup

- modules/ivc_champva/app/controllers/ivc_champva/v1/pega_controller.rb
Due to a change introduced in [this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/20015/files#diff-d3a5e685973696a7a8571bda0dd7281b6539cce3f5c58934f6e8374fd6126ee5), the `date_submitted` property was not being passed in the VA Notify personalization block for IVC CHAMPVA form confirmation emails. This caused the emails to not trigger.
This PR adds the `date_submitted` property into the form data object so that VA Notify successfully triggers an email job.
1. Open an [Argo staging terminal](https://argocd.vfs.va.gov/applications/vets-api-staging?view=tree&resource=) for vets-api web and run `bundle exec rails c` 
2. Paste in the updated `send_email` method, the `get_forms_by_uuid` dependency method, and the helper script:
```ruby
def send_email(form_uuid, form)
return …
```
> Fix confirmation email personalization bug - IVC CHAMPVA forms

- modules/vye/lib/vye/batch_transfer/egress_files.rb
- modules/vye/spec/lib/vye/batch_transfer/egress_files_spec.rb
- *This work is behind a feature toggle (flipper): YES/NO* no
- *(Summarize the changes that have been made to the platform)* Standardized the naming of the vawave file so that it always ends in 3 digits
- *(If bug, how to reproduce)* n/a
- *(What is the solution, why is this the solution?)* Change string formatting
- *(Which team do you work for, does your team own the maintenance of this component?)* VEBT
- *(If introducing a flipper, what is the success criteria being targeted?)* n/a
- *Link to ticket created in va.gov-team repo OR screenshot of Jira …
> VEBT 1091 - Rename vawave files to end in 3 digit numbers

- modules/vaos/app/services/vaos/v2/appointments_service.rb
- modules/vaos/spec/services/v2/appointment_service_spec.rb
- As part of the investigations into the appointments modality resolution failures, we identified three appointment variations that were unaccounted for:
1. {""kind"":""telehealth",""vvs_kind"":null}
1. {""kind"":""telehealth",""vvs_kind"":""ADHOC""}
1. {""kind"":""telehealth",""vvs_kind"":""MOBILE_ANY""}
- The appointment modality resolution logic has been updated to account for these variations
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/101054
- Unit tests are added to account for the appointment variations that caused failures for the previous implementation.
N/A
> Update telehealth appointment modality resolution logic

- lib/sidekiq/retry_monitoring.rb
- A message, `NameError: uninitialized constant Sidekiq::MonitoredWorker`, occasionally appears in the logs when a Sidekiq job fails/retries. It appears that this comes from a missing import in `lib/sidekiq/retry_monitoring.rb`, and that requiring 'sidekiq/retry_monitoring' should fix it. 
- Ran code which triggered a Sidekiq retry and no longer saw the error message locally 
Sidekiq monitored workers
> Handle uninitialized constant

- modules/ask_va_api/app/lib/ask_va_api/inquiries/payload_builder/inquiry_details.rb
- modules/ask_va_api/config/locales/en.yml
- modules/ask_va_api/spec/app/lib/ask_va_api/inquiries/payload_builder/inquiry_details_spec.rb
- Fixed a bug in the InquiryDetails component where the who_is_your_question_about field was nil, causing an error that prevented the creation of an inquiry.
> BE | Ask VA Api: Fix bug in inquiry details when who_is_your_question_about is nil

- modules/claims_api/app/swagger/claims_api/v2/dev/swagger.json
- modules/claims_api/spec/requests/v2/veterans/rswag_power_of_attorney_spec.rb
* moves the /power-of-attorney-request endpoint up to be under the /power-of-attorney endpoints entry
[API-44208](https://jira.devops.va.gov/browse/API-44208)
modified: …
> API-44208-reorder-poa-docs-1

- config/betamocks/services_config.yml
- config/settings.yml
- modules/claims_api/app/services/claims_api/power_of_attorney_request_service/index.rb
- modules/claims_api/lib/bgs_service/local_bgs.rb
- modules/claims_api/lib/bgs_service/manage_representative_service.rb
* Adds optional param to local BGS call so we can ensure to mock _**only**_ where we want to
* Adds BGS for mocking in the betamocks service config
* Adds new setting under the `claims_api` namespace for enabling mocking of these BGS calls
* Threads optional param through from `read_poa_request` which is the BGS call used in the workflow for this ticket specifically
[API-34449](https://jira.devops.va.gov/browse/API-34449)
*  **_You will need the matching PR from the mock data repo to properly test this out._**
* In the mockdata repo pull down the latest and switch to branch `API-34449-mock-poa-request-responses`
* In settings local add these settings right under claims api (can be anywhere other included to show indenting):
```
claims_api:
...
bgs: <--- new
mock_responses: true <------- …
```
> API-34449-poa-requests-mock

- app/controllers/v0/claim_documents_controller.rb
- Refactor `stamped_pdf_valid?` to fix  Metrics/MethodLength cop
- n/a
> Refactor Metrics/MethodLength disable on V0::ClaimDocumentsController

- modules/accredited_representative_portal/app/controllers/accredited_representative_portal/v0/power_of_attorney_requests_controller.rb
- modules/accredited_representative_portal/app/controllers/concerns/accredited_representative_portal/power_of_attorney_requests.rb
- modules/accredited_representative_portal/app/models/accredited_representative_portal/power_of_attorney_request.rb
- modules/accredited_representative_portal/spec/requests/accredited_representative_portal/v0/power_of_attorney_requests_spec.rb
- *This work is behind a feature toggle (flipper):* YES
- *Description* Allow sending of `status=Pending` or `status=Completed` param to the power_of_attorney_requests endpoint to filter the list
- *(If bug, how to reproduce)* feature
- *(What is the solution, why is this the solution?)* https://github.com/department-of-veterans-affairs/va.gov-team/issues/98714
- *(Which team do you work for, does your team own the maintenance of this component?)* ART, yes
- *(If introducing a flipper, what is the success criteria being targeted?)* ??
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/98714
- *Link to epic if not …
> [16] ART: Filter PoA results list

- modules/representation_management/app/serializers/representation_management/original_entities/organization_serializer.rb
- modules/representation_management/app/swagger/v0/swagger.json
- modules/representation_management/spec/serializers/original_entities/organization_serializer_spec.rb
- modules/representation_management/spec/support/rswag_config.rb
- This pr adds the new column `can_accept_digital_poa_requests` to the organization serializer used in the original entities controller. This attribute is needed in the front end to determine organization level eligibility for creating a digital poa request.
- [99972](https://github.com/department-of-veterans-affairs/va.gov-team/issues/99972)
- Old behavior: the api response did not include the attribute
- New behavior: the api response includes the attribute
- Tested locally with postman and pointing the front end experience to local
Appoint a Rep Form 21-22 and 21-22a
> [99972] Appoint a Rep add can_accept_digital_poa_requests to serializer

- modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb
- modules/simple_forms_api/app/services/simple_forms_api/notification_email.rb
- modules/simple_forms_api/spec/requests/simple_forms_api/v1/simple_forms_spec.rb
- modules/simple_forms_api/spec/services/notification_email_spec.rb
This PR simplifies the logic involved in knowing whether the `confirmation_number` is required for an email template. There is only one case in which it is NOT necessary and that is a 26-4555 `:duplicate` email.
https://github.com/orgs/department-of-veterans-affairs/projects/1443/views/3?sliceBy%5Bvalue%5D=Thrillberg&pane=issue&itemId=88758986&issue=department-of-veterans-affairs%7CVA.gov-team-forms%7C1897
> Clarify 26-4555 email template logic around confirmation_number

- lib/lighthouse/veteran_verification/service.rb
- spec/lib/lighthouse/veteran_verification/service_spec.rb
- This change adds additional logging to a Proof of Status card endpoint to capture "confirmed" veteran status in addition to "not confirmed". This will allow us to better track the ratio of confirmed to not confirmed veteran statuses and provide more detailed information for reporting.
- [1392](https://github.com/department-of-veterans-affairs/va-iir/issues/1392)
- There is no old behavior as this just adds new logging. 
This only impacts the Proof of Status card endpoint and DataDog logs.
(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with …
> Add logging of 'confirmed' vet status to Proof of Status

- config/features.yml
- modules/mobile/app/models/mobile/v0/adapters/vaos_v2_appointment.rb
- modules/mobile/app/models/mobile/v0/adapters/vaos_v2_appointments.rb
- modules/mobile/app/services/mobile/v2/appointments/proxy.rb
- modules/mobile/spec/models/adapters/appointments_vaos_v2_adapter_spec.rb
- modules/mobile/spec/requests/mobile/v0/facilities_info_spec.rb
- modules/mobile/spec/support/fixtures/VAOS_v2_appointments.json
- This work is behind a feature toggle (flipper): YES - `va_online_scheduling_appointment_type_consolidation`
- We noticed a issue that causes 502 errors in production for mobile appointments and we are fixing it in this PR.
- The bug was introduced in https://github.com/department-of-veterans-affairs/vets-api/pull/18879 where `REQUEST` appointment types were not handled correctly via the model adapters. 
- The fix is to update the appointment type resolution logic for `REQUEST` appointment types returned by the vets-api appointments service which should be resolved to `VA` for mobile appointments.
- We'll remove the toggle once the issue has been validated to be fixed in production.
- The discussion for this production issue is tracked in Slack …
> Fix production error, parse va appointment requests as va appointments in mobile module

- modules/claims_api/app/controllers/claims_api/v2/blueprints/power_of_attorney_request_blueprint.rb
- modules/claims_api/app/swagger/claims_api/v2/dev/swagger.json
- modules/claims_api/spec/requests/v2/veterans/rswag/index/200.json
- modules/claims_api/spec/requests/v2/veterans/rswag/show/200.json
In the power-of-attorney-request index and show endpoints, update:
- changeAddressAuthorization → consentAddressChange
- healthInfoAuthorization → recordConsent
- 'Y' / 'N' → true / false
Update v2 docs (staging only).
[API-44247](https://jira.devops.va.gov/browse/API-44247)
Send a request to GET `/veterans/power-of-attorney-requests/:id` or POST `/veterans/power-of-attorney-requests` and observe correct response.
**Index**
**Show**
Power of attorney request index and show. v2 staging docs.
N/A
> [API-44247] update poa request attributes

- modules/my_health/spec/requests/my_health/v1/medical_records/imaging_spec.rb
- Fixes a flaky spec. Make sure to eject VCR cassettes after specs are run or they can cause spec issues.
> Fix flaky my health spec

- spec/controllers/sign_in/client_configs_controller_spec.rb
- This spec makes it so changes to the `SignIn::ClientConfig` cannot be made without both code and migration happening in the same PR
- https://jira.devops.va.gov/browse/VI-1014
> [VI-1014] Remove permitted param spec from client config controller

- app/services/sign_in/assertion_validator.rb
- This PR changes the validations in Sign in Service STS so that the 'staging' hostname is compared against the STS token instead of the randomly generated review instance hostname
- https://jira.devops.va.gov/browse/VI-1032
Sign in Service STS
> [VI-1032] Adding special case for Sign in Service STS on review instances to allow for special exception in audience validation

- config/features.yml
Feature flag for enabling the new eligibility check has been enabled in development which includes review instances. 
https://jira.devops.va.gov/browse/MHV-66713
> ### Infinite spinner for users with initial FHIR population
> Description
> We are seeing complaints from users who are waiting indefinitely for the "2 minute" spinner to finish, but it apparently never does. This is the spinner that pops up while waiting for the initial FHIR population to happen.
> 
> We need to check the logic here and see if there's an issue.
> 
> See [Slack thread](https://dsva.slack.com/archives/C03Q2UQL1AS/p1737646550870249) for more info.
No new tests needed
No UI changes. 
MHV medical records
(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the …
> MHV-66713: Review instance feature flag fix

- config/features.yml
added pending meds feature flag
[Adding pending meds to a users list](https://jira.devops.va.gov/browse/MHV-65291)
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-Back …
> [MHV-65291] added pending meds to features.yml.

- app/controllers/v0/profile/address_validation_controller.rb
- Pre-need-integration is hitting unathorized errors when attempting to validate addresses without a user being signed in
- This change fixes that
- Jira Link: https://jira.devops.va.gov/browse/MBMS-71996
- Front End PR 1: https://github.com/department-of-veterans-affairs/vets-website/pull/34127
- Address validation controller 
- With that being said, everyone but pre-need-integration that uses this controller requires users to sign in before attempting address validation so the only form affected by this change will be pre-need-integration
> Skip user authentication for address validation

- modules/ask_va_api/app/lib/ask_va_api/base_retriever.rb
- modules/ask_va_api/app/lib/ask_va_api/correspondences/retriever.rb
• Impact: The method performs redundant calls to fetch_data, which could lead to repeated I/O operations or processing overhead, especially if fetch_data involves expensive operations like file reading or API calls.
• Solution: Store the result of fetch_data in a variable and reuse it.
> Refactor BaseRetriever

- spec/sidekiq/decision_review/form4142_submit_spec.rb
- This spec has been regularly failing in CI with the following PDFTK error message:
```
PdfForms::PdftkError:
pdftk failed with command
/usr/bin/pdftk tmp/pdfs/21-4142_.pdf stamp tmp/5968fde7587b1bdef0d3d4ee780e3862 output tmp/b4890f926eb61dfc491dc04bf8fcdfc4.pdf
command output was:
Error: Invalid PDF: trailer not found.
Error: Failed to open input PDF file: 
tmp/pdfs/21-4142_.pdf
Errors encountered.  No output created.
Done.  Input errors, so no output created.
```
Here's an [example run](https://github.com/department-of-veterans-affairs/vets-api/actions/runs/13015004820/job/36306060406?pr=20308#step:10:913)
> Skip flaky form4142 spec example

- .rubocop_todo.yml
- modules/appeals_api/spec/controllers/application_controller_spec.rb
- modules/appeals_api/spec/services/appeals_api/pdf_construction/generator_spec.rb
- modules/appeals_api/spec/sidekiq/appeals_api/add_icn_updater_spec.rb
- modules/claims_api/spec/lib/claims_api/evidence_waiver_pdf_constructor/pdf_spec.rb
- modules/vba_documents/spec/sidekiq/report_unsuccessful_submissions_spec.rb
- spec/lib/bb/generate_report_request_form_spec.rb
- spec/lib/bgs/vnp_relationships_spec.rb
- spec/lib/saml/ssoe_user_spec.rb
- spec/requests/authentication/standard_authentication_spec.rb
- spec/requests/breakers_integration_spec.rb
- Fixes the following Rubocop offenses:
- `RSpec/PendingWithoutReason`
- replaced `xit` with `skip: "some reason (if known)"`
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/100982
> Fix RSpec/PendingWithoutReason

- db/migrate/20250123220146_add_json_api_compatibility_to_client_configs.rb
- db/schema.rb
- This PR adds the schema changes necessary to separate Sign in Service clients from either JSON API compatible or OAuth RFC compatible clients
- https://jira.devops.va.gov/browse/VI-1014
Authentication
> [VI-1014] Schema changes to add Oauth compatibility functionality for sign in service token route

- app/controllers/v0/caregivers_assistance_claims_controller.rb
- spec/requests/v0/caregivers_assistance_claims_spec.rb
- This work is behind a feature toggle (flipper): NO, but the front end code that calls it is behind a toggle. 
- When looking into why invalid facility ids were being passed with 10-10CG Submissions with the new facility search functionality, we discovered that when `vets-website` was making the request to find the parent facility, the request was being made with `facilityIds` as the parameter key name. In the rails controller that was converted to snake case, which was then being passed to the Lighthouse Facilities api which expected it in camel case. Since it was being passed incorrectly, the facilities results were just returning the first 5 results.
- This PR converts the param key name to the valid camel case for the Lighthouse api
- Behind the …
> [10-10CG] Update facility_ids param in facilities endpoint

- config/features.yml
We need a feature flipper to show new Facility Locator mobile map features for our research sessions.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18444
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20153
> VACMS-18444 Add new flipper for Facility Locator mobile map research

- app/controllers/v0/profile/address_validation_controller.rb
Reverts department-of-veterans-affairs/vets-api#20448
Per Identity Team: 
We shouldn't be skipping CSRF for POST routes that are exposed to the [VA.gov](http://va.gov/) frontend
> Revert "Skip user authentication for address validation"

- .github/workflows/gh-env-cleanup.yml
https://github.com/department-of-veterans-affairs/va.gov-team/issues/100722
This workflow deletes old, non-protected environments from the Vets API repo on GitHub. It also deletes environments attached to PRs on PR close/merge.
I initially wrote this to use bash but decided to convert to ruby for readability. Speaking of, GitHub doesn't syntax highlight bash (or ruby) embedded in YAML, so here's the ruby script:
```ruby
require 'bundler/inline'
gemfile { source 'https://rubygems.org'; gem 'octokit' }
CURRENT_TIME = Time.now.to_i
THRESHOLD_SECONDS = 90 * 24 * 60 * 60 # 90 days in seconds
REPO = ENV['GITHUB_REPOSITORY']
CLIENT = Octokit::Client.new access_token: ENV['VA_VSP_BOT_GITHUB_TOKEN']
def old_and_unprotected? env
env[:protection_rules].empty? && CURRENT_TIME - env[:created_at].to_i …
```
> feat: Cleanup old GH env via Actions

- modules/ivc_champva/app/models/ivc_champva/vha_10_10d.rb
- modules/ivc_champva/spec/models/vha_10_10d_spec.rb
Updated the line to directly access the applicantEmailAddress from the first element of the applicants array.
Removed unnecessary type checks and ensured the correct key is used.
Unit Test.
Only 1010D in IVC CHAMPVA forms
> 101565_PEGA-Integration-Include-10-10d-signers-email

- config/features.yml
Follow-on to EP merge functionality removal. See description in that PR:
https://github.com/department-of-veterans-affairs/vets-api/pull/20433
Once this is merged, will need to do the below:
```bash
Flipper.remove(:disability_526_ep_merge_api)
```
> EP Merge feature flag removal

- modules/decision_reviews/app/controllers/decision_reviews/application_controller.rb
DecisionReviews module is using an isolated ApplicationController, pulling in helpers from the main app
https://github.com/department-of-veterans-affairs/va.gov-team/issues/101843
https://github.com/department-of-veterans-affairs/va.gov-team/issues/102061
- Module controllers inherited from main app ApplicationController
- Test module endpoints in …
> Isolated ApplicationController for DR Module

- modules/decision_reviews/app/sidekiq/decision_reviews/hlr_status_updater_job.rb
- modules/decision_reviews/app/sidekiq/decision_reviews/nod_status_updater_job.rb
- modules/decision_reviews/app/sidekiq/decision_reviews/sc_status_updater_job.rb
This fixes a memoization issue for the SavedClaim status updater jobs. This is intended to address an intermittent query timeout issue by reducing the number of DB queries to the SavedClaim table.
No
https://github.com/department-of-veterans-affairs/va.gov-team/issues/101553
Tested locally and passes existing tests
The previous memoized values in the status updater jobs were ActiveRecord relation objects, so the same queries would be executed multiple times. 
Sidekiq jobs and vets-api postgres db
> 101553: Update DR SavedClaim queries to memoize array instead of ActiveRecord relation

- config/features.yml
- There is a typo for the `search_use_v2_gsa` feature flipper, this corrects `enabled_in_development` to the correct `enable_in_development`
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18736
- 
- *This did not cause any bugs or direct issues before, but kept the flag from being enabled by default in local development.
- The `search_use_v2_gsa` flipper will now be enabled by default in local development environments
Flipper flag related to v2 search which is currently on hold.
> [VACMS-18736]Correct spelling for search v2 'enable_in_development'

- modules/vaos/app/controllers/vaos/v2/appointments_controller.rb
- updates AppointmentsController#fetch_drive_times method to utilize lat/long from user's vet360 data
- previous implementation assumed the user's residential lat/long would be available from their `address` attribute, but that data is obtained from the MPI service and does not include lat/long. Instead we can obtain the lat/long from the user's `vet360_contact_info` data if available.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/101426
As per John W, return an empty string if the user's lat/long are not available.
> 101426 update AppointmentsController#fetch_drive_times

- modules/ask_va_api/app/controllers/ask_va_api/v0/health_facilities_controller.rb
- modules/ask_va_api/spec/requests/ask_va_api/v0/health_facilities_spec.rb
- modules/facilities_api/app/controllers/facilities_api/v2/va_controller.rb
- modules/facilities_api/spec/requests/facilities_api/v2/va_spec.rb
Remove dead code related to the `facilities_locator_mobile_covid_online_scheduling` flipper that has already been removed from `vets-api`.
Sanity check: this flipper is only still used in `vets-api` in the files I've edited: https://github.com/search?q=org%3Adepartment-of-veterans-affairs%20facilities_locator_mobile_covid_online_scheduling&type=code
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13484
Checked Staging and Production Flipper Admins for this flipper; it is already gone:
> VACMS-13484 Remove unused Facilities flipper

- modules/simple_forms_api/app/models/simple_forms_api/base_form.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_20_10206.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_20_10207.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_21_0845.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_21_0966.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_21_0972.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_21_10210.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_21_4142.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_21p_0847.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_26_4555.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_40_0247.rb
- modules/simple_forms_api/app/models/simple_forms_api/vba_40_10007.rb
- modules/simple_forms_api/spec/models/base_form_spec.rb
- modules/simple_forms_api/spec/models/vba_20_10206_spec.rb
- modules/simple_forms_api/spec/models/vba_20_10207_spec.rb
- modules/simple_forms_api/spec/models/vba_21_0845_spec.rb
- modules/simple_forms_api/spec/models/vba_21_0966_spec.rb
- modules/simple_forms_api/spec/models/vba_21_0972_spec.rb
- modules/simple_forms_api/spec/models/vba_21_10210_spec.rb
- modules/simple_forms_api/spec/models/vba_21_4142_spec.rb
- modules/simple_forms_api/spec/models/vba_21p_0847_spec.rb
- modules/simple_forms_api/spec/models/vba_26_4555_spec.rb
- modules/simple_forms_api/spec/models/vba_40_0247_spec.rb
- modules/simple_forms_api/spec/models/vba_40_10007_spec.rb
This is the second part, beginning with [this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/20376) of a big refactor of Simple Forms emails. This one implements a method across all our forms, `notification_email_address`, so we can remove that logic from the `NotificationEmail` service later on.
> Implement simple forms notification_email_address

- .github/CODEOWNERS
- app/controllers/concerns/headers.rb
- config/application.rb
Adding the `Timing-Allow-Origin` header to the headers sent on API responses. This is to allow DataDog Real User Monitoring to collect timing metrics on requests to vets-api made by vets-website. I set it to `Settings.web_origin` so that it will only allow timing info for vets-website. I'm not sure if I need to add `Timing-Allow-Origin` to the list of headers in rack-cors though. It seemed to work without it so I left it out.
[DataDog recommendations](https://docs.datadoghq.com/real_user_monitoring/browser/monitoring_resource_performance/#resource-timing-and-cors)
[MDN Article on Timing-Allow-Origin](https://developer.mozilla.org/en-US/docs/Web/API/Performance_API/Resource_timing#cross-origin_timing_information)
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/101997 …
> Adding header needed for DataDog RUM

- modules/veteran/app/sidekiq/representatives/queue_updates.rb
- modules/veteran/app/sidekiq/representatives/update.rb
- modules/veteran/app/sidekiq/veteran/vso_reloader.rb
- modules/veteran/spec/sidekiq/representatives/queue_updates_spec.rb
- modules/veteran/spec/sidekiq/representatives/update_spec.rb
- modules/veteran/spec/sidekiq/veteran/vso_reloader_spec.rb
- *(Summarize the changes that have been made to the platform):* The sidekiq jobs in `modules/veteran/app/sidekiq/representatives` were logging to Sentry and Slack in all ENVs.  Now they log to Datadog instead of Sentry and only log to Slack in `production`.  This should cut down on sidekiq retries in `dev` and `sandbox` where there is no slack webhook url configured.
- *(What is the solution, why is this the solution?):* We made changes recently to these jobs to make logging more verbose so we could see what was happening and we went too far.
- *(Which team do you work for, does your team own the maintenance of this component?):* FAR/ARM, we own the maintenance.
- *(If introducing a flipper, what is the …
> Only log to slack in prod and convert sentry logging to datadog for Representatives sidekiq jobs in the Veteran module

- modules/claims_api/app/sidekiq/claims_api/claim_establisher.rb
- modules/claims_api/spec/sidekiq/claim_establisher_spec.rb
In ClaimEstablisherJob (only used in v1 526), raise an error when the EVSS Docker container fails with 417 Expectation Failed (thereby retrying the job where previously we did not).
[API-44352](https://jira.devops.va.gov/browse/API-44352)
N/A
ClaimEstablisherJob (v1 526)
N/A
> [API-44352] 526 v1 - Retry [417] error

- modules/claims_api/app/services/claims_api/power_of_attorney_request_service/create_request.rb
- Updates the alphabetic case of the VDC_STATUS value used in calls to BGS createVeteranRepresentative, so that the resulting request is correctly populated and appears as expected in the VNP_PROC_LC_STATUS Corp DB table.
- [API-44520](https://jira.devops.va.gov/browse/API-44520)
- Testing done in concert with Michael Harlow to confirm that our POA requests are being correctly populated in BGS and the Corporate DB table VNP_PROC_LC_STATUS.
Calls to POA endpoint POST veterans/{{veteranId}}/power-of-attorney-request
> API-44520 - Update VDC_STATUS value to uppercase for call to BGS

- modules/accredited_representative_portal/app/controllers/accredited_representative_portal/v0/power_of_attorney_requests_controller.rb
- modules/accredited_representative_portal/app/serializers/accredited_representative_portal/power_of_attorney_request_serializer.rb
- Renames the `COMPLETED` status to `PROCESSED` in the AccreditedRepresentativePortal statuses
- Updates corresponding case statement to use the new `PROCESSED` status
- Refactors the power of attorney request serializer to handle claimant type form field cleanup more consistently removing the "over-deletion" on dependent type.
This change improves code consistency by:
1. Using more accurate terminology (PROCESSED instead of COMPLETED)
2. Cleaning up redundunt logic
> Rename COMPLETED status to PROCESSED and refactor claimant type handling

- modules/vaos/app/services/eps/appointment_service.rb
- modules/vaos/spec/services/eps/appointment_service_spec.rb
This PR adds a get_appointment method to EPSService which calls the EPS endpoint to get details of a specific appointment.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/101978
VAOS EPS code
> 101978 add EPS get_appointment method

- modules/claims_api/app/controllers/concerns/claims_api/disability_compensation_validations.rb
- modules/claims_api/app/swagger/claims_api/v1/swagger.json
- modules/claims_api/app/swagger/claims_api/v2/dev/swagger.json
- modules/claims_api/app/swagger/claims_api/v2/production/swagger.json
- modules/claims_api/config/schemas/v1/526.json
- modules/claims_api/config/schemas/v2/526.json
- modules/claims_api/spec/requests/v1/forms/526_spec.rb
In v1 526, validate that at least one service period activeDutyEndDate is within 180 days from the current date.
Update v1 and v2 docs to include requirement:
> Date Completed Active Duty. If in the future, 'separationLocationCode' is required. Cannot be more than 180 days in the future, unless past service is also included.
[API-43688](https://jira.devops.va.gov/browse/API-43688)
**v1**
**v2**
526 v1 submission validation. v1 and v2 docs.
N/A
> [API-43688] 526 - Validation for activeDutyEndDate beyond 180 days

- modules/claims_api/app/swagger/claims_api/v2/dev/swagger.json
- modules/claims_api/app/swagger/claims_api/v2/production/swagger.json
- modules/claims_api/config/schemas/v2/526.json
- modules/claims_api/config/schemas/v2/generate_pdf_526.json
- Updates json schemas and adds generated swagger documentation for change to update treatments documentation to reflect true max number of characters allowed.
[API-42638](https://jira.devops.va.gov/browse/API-42638)
- Previewed documentation locally to ensure documentation updates are present and correct.
526 documentation for synchronous, validate, and generatePDF/minimum-validations.
> API-42638 - 526 v2 - Update docs for treatment info validations

- modules/decision_reviews/app/controllers/decision_reviews/application_controller.rb
- NO
Add additional logging context to controllers in the DecisionReviews module. This context used to be inherited from the shared ApplicationController, but now needs to be explicitly included in the module.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/102061
- Logs from DR module controllers did not include context like source …
> recover logging tags for DR module controllers

- modules/claims_api/app/sidekiq/claims_api/poa_assign_dependent_claimant_job.rb
- modules/claims_api/app/sidekiq/claims_api/poa_vbms_updater.rb
- modules/claims_api/app/sidekiq/claims_api/service_base.rb
- modules/claims_api/spec/sidekiq/poa_assign_dependent_claimant_job_spec.rb
- modules/claims_api/spec/sidekiq/poa_vbms_updater_spec.rb
* Adds consent information log outs to `poa_vbms_updater` and `poa_assign_dependent_claimant_job`
* Adds tests for logger detail message
* Refactors:
* Refactors some shared methods into the service_base file
* removes a method that was duplicating logic
[API-44223](https://jira.devops.va.gov/browse/API-44223)
* Manually running the jobs you should see logouts in line with images below for each scenario
* with `"recordConsent": true,` (obviously details will match your rep and all that)
```
Rails --  ClaimsApi :: poa_vbms_updater :: {... "detail":"Updating Access. recordConsent: true for representative 045","poa_code":"045","allow_poa_access":true,"allow_poa_c_add":null} :: Location:...
```
* with `      "recordConsent": false, "consentLimits": ["HIV"],`
```
Rails -- ClaimsApi :: …
```
> API-44223-consent-limit-logging

- db/schema.rb
- modules/accredited_representative_portal/db/migrate/20250204175216_create_ar_user_account_accredited_individuals.rb
- modules/accredited_representative_portal/db/migrate/20250204175217_add_index_to_ar_user_account_accredited_individuals.rb
- modules/accredited_representative_portal/db/migrate/20250204175218_add_replication_index_to_accredited_individuals.rb
- modules/accredited_representative_portal/db/migrate/20250204175219_add_power_of_attorney_holder_type_constraint.rb
This PR sets up the database structure to maintain an allow-list of accredited VA representatives who can handle Power of Attorney requests.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/99863
1. Creates new allow-list table `ar_user_account_accredited_individuals` to track authorized VSO representatives
- Stores registration numbers, POA holder types, and user account info
- Uses UUID for primary key
2. Adds indexes to support:
- Unique registration numbers
- CSV-based allow-list synchronization (composite unique index)
- POA holder type constraints per email
- Maintains authoritative allow-list of accredited VSO representatives
- Supports automated synchronization with source CSV allow-list
- Ensures data integrity through uniqueness constraints
- Provides …
> [ARP allowlist] Create VA accredited individuals allow-list table

- lib/vets/type/primitive.rb
- spec/lib/vets/type/base_spec.rb
- Two specs where failing locally because of a loading issue 
- spec/lib/vets/type/base_spec.rb
- spec/lib/vets/attributes_spec.rb
- n/a
> Fix class loading issue for lib/vets

- .github/CODEOWNERS
- config/initializers/filter_parameter_logging.rb
- spec/fixtures/files/test_file_with_pii.txt
- spec/requests/filter_parameter_logging_spec.rb
This PR changes the `filter_parameter_logging.rb` initializer to improve PII filtering beyond just strings. Prior to this, only string based parameters were being filtered, leaving potential PII exposure in `ActionDispatch::Http::UploadedFile` objects, Hashes and Arrays. This update ensures that uploaded files and structured data containing sensitive info are properly filtered. The filter parameter method uses recursion to iterate over both arrays and hashes, allowing it to filter `ActionDispatch::Http::UploadedFile` objects and strings effectively, with …
> Filtering Sensitive Parameters from Vets API Logs

- .github/CODEOWNERS
- config/settings.yml
- config/settings/test.yml
- lib/bpds/jwt_encoder.rb
- spec/lib/bpds/jwt_encoder_spec.rb
- Adds a class to encode the JWT for the new BPDS service
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/99544
- Add `bpds.jwt_secret` to settings.local
- Run `bundle exec rails c` and in the terminal:
```
require 'bpds/jwt_encoder'
BPDS::JwtEncoder.new.get_token
```
- Follow the directions [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/engineering/mhv-api-tunnel-setup.md) but instead of making a tunnel, just SSH into a fwdproxy instance
- Send a request from the fwdproxy instance using the token from earlier: `curl -X GET "https://bpds-dev.dev.bip.va.gov/api/v1/bpd/1" -H "accept: application/json" -H "Authorization: Bearer …
> Encode BPDS JWT

- app/controllers/v0/form1095_bs_controller.rb
- app/models/form1095_b.rb
- lib/form1095_b/templates/txts/1095b-2024.txt
- spec/models/form1095_b_spec.rb
- spec/requests/v0/form1095_bs_spec.rb
- This work is behind a feature toggle (flipper): It is feature flagged on the front end. The endpoint is not currently in use.
- Adds new 2024 1095b text file
- Programmatically adds VA contact info to 1095b form
- limits available forms endpoint to only return most recent tax year
https://github.com/department-of-veterans-affairs/va-iir/issues/1387
Specs.
Only impacts 1095b endpoints, which are not currently in use.
> 1387 update 1095b

- config/initializers/filter_parameter_logging.rb
- spec/fixtures/files/test_file_with_pii.txt
- spec/requests/filter_parameter_logging_spec.rb
This PR updates the filter parameter logging file to allow `tempfile` and `content_type` through the filtering.
`tempfile` is an automatically generated temporary file object that is created when a user uploads a file. It does not display sensitive information, and is useful for logging/diagnosing issues. Similarly, `content_type` is just the type of media (e.g., `application/pdf`).
- Updates `filter_parameter_logging` to allow `tempfile` and `content_type` to pass unfiltered in logs
- [DSVA Slack thread](https://dsva.slack.com/archives/C0460N83Y9G/p1738769353034689?thread_ts=1734544550.087249&cid=C0460N83Y9G) where this has been discussed
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/102541
- *Describe …
> Add `tempfile` and `content_type` to list of allowed keynames in filter process

- modules/vye/spec/serializers/claimant_verification_serializer_spec.rb
- The class wasn't loading on local test runs
- This spec doesn't test the class it only tests the fixture 
- n/a
> Fix broken ClaimantVerificationSerializer spec

- modules/ivc_champva/app/models/ivc_champva/vha_10_10d.rb
- modules/ivc_champva/app/models/ivc_champva/vha_10_7959a.rb
- modules/ivc_champva/app/models/ivc_champva/vha_10_7959c.rb
- modules/ivc_champva/app/models/ivc_champva/vha_10_7959f_1.rb
- modules/ivc_champva/app/models/ivc_champva/vha_10_7959f_2.rb
- modules/ivc_champva/spec/models/vha_10_10d_spec.rb
- modules/ivc_champva/spec/models/vha_10_7959a_spec.rb
- modules/ivc_champva/spec/models/vha_10_7959c_spec.rb
- modules/ivc_champva/spec/models/vha_10_7959f_1_spec.rb
- modules/ivc_champva/spec/models/vha_10_7959f_2_spec.rb
This PR updates the metadata for all IVC forms to include the `primaryContactEmail` property so that submitted attachments will contain an email address embedded in the file metadata upon submission to S3.
- Update all IVC form metadata constructors to include new email prop
- Update relevant test data in spec files
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/101565
- Old behavior: metadata did not include this email prop
- To verify behavior, file was submitted to a development S3 bucket and the metadata was confirmed to contain the email property
|S3 metadata|
|-|
|<img width="959" alt="Screenshot 2025-02-05 at 14 55 17" src="https://github.com/user-attachments/assets/1d604e25-f6f7-428e-9393-a97570c6305c" />| …
> 101565 Update metadata for each IVC forms with primary contact email - IVC CHAMPVA forms

- config/features.yml
- modules/mobile/app/models/mobile/v0/adapters/vaos_v2_appointment.rb
- modules/mobile/app/models/mobile/v0/adapters/vaos_v2_appointments.rb
- modules/mobile/app/services/mobile/v2/appointments/proxy.rb
- modules/mobile/spec/models/adapters/appointments_vaos_v2_adapter_spec.rb
- modules/mobile/spec/requests/mobile/v0/facilities_info_spec.rb
- The production fix made in https://github.com/department-of-veterans-affairs/vets-api/pull/20427 has been fully deployed and verified in production. This PR removes the temporary feature toggle introduced for the deployment of the fix.
- Appointments (VAOS) Team is making the change but the ownership of the code is with the Mobile team
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/101846
N/A
Mobile
> Remove remove-va_online_scheduling_appointment_type_consolidation feature toggle

- config/features.yml
- modules/ivc_champva/app/services/ivc_champva/s3.rb
- modules/ivc_champva/spec/requests/ivc_champva/v1/forms/uploads_spec.rb
- modules/ivc_champva/spec/services/s3_spec.rb
- Added `require 'ivc_champva/monitor'` to integrate the `IvcChampva::Monitor` class.
- Introduced a `monitor` method to initialize an instance of `IvcChampva::Monitor` for tracking successful S3 uploads.
- Enhanced `put_object` method:
- Added explicit error handling using a `begin/rescue` block.
- Improved response handling by introducing `handle_put_object_response` and `handle_put_object_error` methods.
- Introduced Flipper-based conditional logging for S3 uploads.
- Introduced `handle_put_object_response`:
- Logs failures and tracks successful S3 uploads via `monitor.track_all_successful_s3_uploads(key)`.
- Introduced `handle_put_object_error`:
- Logs unexpected errors encountered during S3 PutObject operations.
- Updated …
> Refactor S3 PutObject response and error handling

- modules/simple_forms_api/app/services/simple_forms_api/form_upload_notification_email.rb
- modules/simple_forms_api/spec/services/form_upload_notification_email_spec.rb
This is a small bugfix to correct the path to find a Veteran's email address in the Form Upload tool.
> Fix path for email in Form Upload email

- .github/workflows/require_be_approval.yml
Developers are bypasing the backend approval requirement.  Require backend-review-group approval will fail if the pull request is in draft mode. Just as before, if the requested team belongs to Identity, the Require backend-review-group approval workflow will be skipped after verifying the pull request is not in draft mode.
Draft pull requests cannot be approved.
- N/A
Tested approving pull request in draft mode.
Tested approving pull request not in draft mode. …
> Deny approvals for draft pull requests.

- .github/CODEOWNERS
- app/models/form526_submission.rb
- app/sidekiq/evss/disability_compensation_form/submit_form526.rb
- app/sidekiq/form526_submitted_email_job.rb
- config/features.yml
- config/settings.yml
- lib/sidekiq/form526_job_status_tracker/backup_submission.rb
- spec/sidekiq/evss/disability_compensation_form/submit_form526_all_claim_spec.rb
- feature flag: `disability_526_send_form526_submitted_email`
- `Form526Submission#send_submitted_email`
- call submitted email in two places: primary success, backup path start
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/94200 …
> dbex/94200: add Form526SubmittedEmailJob

- app/controllers/v0/caregivers_assistance_claims_controller.rb
- This work is behind a feature toggle (flipper): NO, but the  `vets-website` code that calls this endpoint currently is
- Small refactor to improve readability and efficiency when reformatting the `facility_ids` to `facilityIds` param for the Lighthouse API call per @stevenjcumming's suggestion. 
- 1010 Health Apps 
- `vets-website` call is `caregiver_use_facilities_API`
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/101907
> [10-10CG] Refactor facilityIds param formatting

- modules/debts_api/app/models/debts_api/v0/form5655_submission.rb
- modules/debts_api/spec/models/debt_api/v0/form5655_submission_spec.rb
- *This work is behind a feature toggle (flipper): YES/NO*: Sort of. We have a feature flag that enables a different error class that would effectively fire/not fire this conditional.
- *(Summarize the changes that have been made to the platform)*: We've been alerting Watchtower about Sharepoint errors we're getting. It's not great that we're erroring but also, it's not _really_ a silent error. The Veteran's data gets where it needs to go even if sharepoint errors. We enabled a new error class(es) via Flipper and confirmed this is working as expected. Now, we're adding this to not fire silent errors when there's a sharepoint error.
- *(What is the solution, why is this the solution?)*: This will get our alerts to watchtower so we can be alerted to a …
> 100832 Financial Management: Do not register Silent Errors for Sharepoint errors

- lib/source_app_middleware.rb
Datadog alert: [vets-api source app monitor - un-mapped source app detected](https://dsva.slack.com/archives/C30LCU8S3/p1738949981312379)
The logs in the alert show 
```
Unrecognized value for HTTP_SOURCE_APP_NAME request header... [welcome-va-setup-review-information]
```
Noticed while on support.
> Add welcome-va-setup-review-information to source_app_middleware.rb

- modules/accredited_representative_portal/config/initializers/bypass_olive_branch.rb
- modules/accredited_representative_portal/spec/requests/accredited_representative_portal/bypass_olive_branch_spec.rb
See head of PR stack: #20621
> `olive_branch` transforms (a) request and (b) response payloads.
>
> (a) It deeply transforms request and query param keys.
At times it is convenient for params to act as snake-cased setters at a Ruby interface, but not always. Form resources are a possible example where not.
>
> For now, let's wait to encounter the cases where we really want this convenience. If we do encounter some, we may discover that we want a more explicit and collocated way to opt in.
>
> (b) It reloads the response from JSON, deeply transforms keys, and dumps back to JSON.
This is superfluous because our serialization layer `jsonapi-serializer` already has a configuration option for key casing. This realizes our desired casing the one and only time it is visiting an object during …
> [ARP - lower camel responses - 5] bypass olive branch

- modules/simple_forms_api/app/services/simple_forms_api/form_upload_notification_email.rb
- modules/simple_forms_api/app/services/simple_forms_api/notification_email.rb
- modules/simple_forms_api/spec/services/form_upload_notification_email_spec.rb
- modules/simple_forms_api/spec/services/notification_email_spec.rb
This PR tracks `confirmation_number` with the `callback_metadata` that we send back to VANotify. This should help us tie specific Notifications to the corresponding submission attempt.
- https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/2008
> Add confirmation_number to callback_metadata for simple forms

- .github/CODEOWNERS
The Employee Experience team is embarking on a redesign of the PDF generator overflow page, to be rolled out on a form-by-form basis in collaboration with teams maintaining each form. This effort will touch `lib/pdf_fill` many times, which currently has a handful of form-specific teams tagged as codeowner.
I reached out to each of those teams on Slack for guidance; debt resolution and 1095b prefer to be untagged, and 10-10 preferred to stay codeowner.
#20628 is the PR that brought this to my attention.
> Update codeowners for top-level lib/pdf_fill

- modules/claims_api/app/controllers/claims_api/v1/forms/disability_compensation_controller.rb
- modules/claims_api/app/sidekiq/claims_api/claim_uploader.rb
- modules/claims_api/lib/claims_api/v2/disability_compensation_documents.rb
- modules/claims_api/spec/sidekiq/claim_uploader_spec.rb
* Adds claim status check before rescheduling claim uploader job
* add log when claim is errored and uploader does not reschedule
* adds slack alert when the claim is errored and the uploader decides tonot reschedule
* adds param to help with support
* updates related tests
[API-44372](https://jira.devops.va.gov/browse/API-44372)
- …
> API-44372-claim-uploader-schedule-fix

- .github/CODEOWNERS
- .github/workflows/code_checks.yml
- .rubocop.yml
- config/database.yml
- config/settings.yml
- db/audit_schema.rb
- docker-compose.review.yml
- docker-compose.test.yml
- docker-compose.yml
- This adds the audit database config and connection using rails standard for multiple databases
- Updates docker compose files
- the production audit database has `database_tasks: false`. This will skip migrations in the deployed envs until the database is set up
- In development, Rails database commands with no suffix will run tasks for both databases (`rails db:migrate`) or you can add a suffix (`rails db:migrate:primary`, `rails db:migrate:audit`) to run tasks on the specified database only.
- clean up code_checks pipeline
- https://jira.devops.va.gov/browse/VI-869
- create the databases (`development`, `test`)
- `rails db:create`
-  or `rails db:create:audit`
- Load schema (⚠️ Only do this on the `audit` db or you will loose all your data in `primary`)
- `rails db:load_schema:audit` …
> [VI-869] Add audit_db config and connection

- lib/pdf_fill/forms/va1010cg.rb
- spec/fixtures/pdf_fill/10-10CG/merge_fields.json
- spec/lib/pdf_fill/forms/va1010cg_spec.rb
- When a 10-10CG form is submitted, a pdf version of the form is also filled out and sent with the form data payload (The same pdf is also available for the Veteran to download upon submission). In this pdf, we have a helper that fills the selected facility input with the `ID - Name of Facility` and not just the facility id like we send in the payload. Finding the name is performed by looking up the list of caregiver facilities in `vets-json-schema`, and matches the id with the object that has that id. If the id is not found, it sets the input to empty. 
- This change ensures that we at least always pass the facility id, since we know we have that because we passed the schema validation and it is required. If we find the name we set it, …
> [10-10CG] Display facility Id in pdf if name is not found in vets-json-schema

- db/migrate/20250210175014_add_bpd_uuid_to_saved_claims.rb
- db/schema.rb
- Migration to add a new `bpd_uuid` field to the saved_claims table. This field will be used to record UUIDs generated from submitting data to BPDS endpoint.
- Pension Burial Program team to own this change
- [*Link to ticket created in va.gov-team repo*](https://github.com/department-of-veterans-affairs/va.gov-team/issues/99548)
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-to …
> Migration to add bpds_uuid to saved_claims

- modules/simple_forms_api/app/controllers/simple_forms_api/v1/scanned_form_uploads_controller.rb
- modules/simple_forms_api/spec/fixtures/form_json/form_upload_flow_21_0779.json
- modules/simple_forms_api/spec/requests/simple_forms_api/v1/scanned_form_uploads_spec.rb
This PR supplies the `form_data` to the `FormSubmission` in the Form Upload tool. We're already supplying this data in other cases but it was originally omitted for Form Upload because I (mistakenly) thought it wouldn't be necessary. This was before we knew we wanted to be sending emails on form submission status. We'll definitely need the form data to be saved so that we can at least fetch the email later, on form submission status updates.
- https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/1968
> Pass form_data to FormSubmission in Form Upload tool

- modules/accredited_representative_portal/app/controllers/accredited_representative_portal/v0/in_progress_forms_controller.rb
- modules/accredited_representative_portal/app/controllers/accredited_representative_portal/v0/representative_users_controller.rb
- modules/accredited_representative_portal/app/models/accredited_representative_portal/power_of_attorney_form.rb
- modules/accredited_representative_portal/app/serializers/accredited_representative_portal/application_serializer.rb
- modules/accredited_representative_portal/config/initializers/bypass_olive_branch.rb
- modules/accredited_representative_portal/spec/factories/power_of_attorney_form.rb
- modules/accredited_representative_portal/spec/factories/representative_user.rb
- modules/accredited_representative_portal/spec/requests/accredited_representative_portal/bypass_olive_branch_spec.rb
- modules/accredited_representative_portal/spec/requests/accredited_representative_portal/v0/in_progress_forms_spec.rb
- modules/accredited_representative_portal/spec/requests/accredited_representative_portal/v0/power_of_attorney_requests_spec.rb
- modules/accredited_representative_portal/spec/requests/accredited_representative_portal/v0/power_of_attorney_requests_spec/responses/dependent_claimant_power_of_attorney_form.json
- modules/accredited_representative_portal/spec/requests/accredited_representative_portal/v0/power_of_attorney_requests_spec/responses/veteran_claimant_power_of_attorney_form.json
- modules/accredited_representative_portal/spec/requests/accredited_representative_portal/v0/user_spec.rb
- modules/accredited_representative_portal/spec/serializers/accredited_representative_portal/power_of_attorney_request_serializer_spec.rb
This is the head of a PR stack that switches all existing ARP endpoints to input and output camel cased request and response payloads explicitly and in particular bypasses `olive_branch` middleware. The PRs sequence the work like `1 <- 2 <- 3 <- 4 <- 5` and can each be approved one at a time in that order. Then that whole chain can get merged into this head PR and platform can re-approve a final time to go into `master`. 
⚠️ _Please feel free to visit the 5 minimal diffs in quick succession!_ ⚠️
The PR titles and minimal diffs are self explanatory:
- #20621
- #20622
- #20623
- #20624
- #20625
It is worth reiterating the code comment that exists in the final PR of the PR stack that bypasses `olive_branch` for ARP endpoints:
> `olive_branch` transforms (a) request and (b) response payloads. …
> [ARP - lower camel responses - 1] `set_key_transform :camel_lower`

- lib/lighthouse/benefits_intake/sidekiq/submission_status_job.rb
This PR fixes a small bug where we would update state on a `FormSubmissionAttempt` (triggering an email to send) before populating the `lighthouse_updated_at` field. The emails, without this field set, would fail. Currently this whole Job is behind a feature flag (`:benefits_intake_submission_status_job`) which is OFF. Once we fix this, I believe we are safe to turn the feature flag back on.
> Submission Status Job: Assign lighthouse_updated_at before running callbacks upon state change

- app/controllers/v0/health_care_applications_controller.rb
- config/features.yml
- spec/controllers/v0/health_care_applications_controller_spec.rb
- spec/requests/v0/health_care_applications_spec.rb
- Update the Health Care Applications backend to use the new Lighthouse Facilities Client V2, since V1 is being deprecated.
- 10-10 Health Enrollment Team EZ/CG
- `hca_ez_use_facilities_v2` flipper toggle
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/99214
- Old behavior: use the V1 Client to retrieve Facilities from Lighthouse.
- New behavior: uses V2 instead.
- To verify, start a 10-10EZ application, and proceed to the VA Facility page. Choose a `State`, and confirm that the `Center or clinic` dropdown populates with facilities.
* 10-10EZ Health Care Application form
(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you …
> Use the new Facilities V2 Client for EZ Lighthouse queries

- config/features.yml
We are combining two flippers together:
- `facilities_ppms_suppress_all`
- `facilities_ppms_suppress_pharmacies`
The code for these two flippers will all be used under the `facilities_ppms_suppress_all` flipper, so we can remove the pharmacies-specific flipper.
vets-website PR for removal of the flipper code for pharmacies: https://github.com/department-of-veterans-affairs/vets-website/pull/34567
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11589
> VACMS-11589 Remove unused flipper

- .github/CODEOWNERS
- config/settings.yml
- config/settings/test.yml
- modules/accredited_representative_portal/app/models/accredited_representative_portal/user_account_accredited_individual.rb
- modules/accredited_representative_portal/app/sidekiq/accredited_representative_portal/allow_list_sync_job.rb
- modules/accredited_representative_portal/spec/models/accredited_representative_portal/user_account_accredited_individual_spec.rb
- modules/accredited_representative_portal/spec/sidekiq/accredited_representative_portal/allow_list_sync_job_spec.rb
- modules/accredited_representative_portal/spec/spec_helper.rb
- spec/support/vcr.rb
- spec/support/vcr_cassettes/accredited_representative_portal/sidekiq/accredited_representative_portal/allow_list_sync_job_spec/insertions_and_deletions.yml
This PR introduces key improvements and new features to the Accredited Representative Portal, automating allow list management via GitHub and enhancing overall system integrity and test coverage.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/99863
---
- Added ownership for `spec/support/vcr_cassettes/accredited_representative_portal` to ensure proper code review for the new module.
- **Settings (`config/settings.yml`):** Added a new `allow_list` configuration for GitHub integration, specifying access token, repository, and CSV path.
- **Model (`UserAccountAccreditedIndividual`):**
- Tracks accredited representatives with key validations:
- Presence of registration number and email.
- Email format validation.
- Defined `power_of_attorney_holder_type` using an enum.
- …
> [ARP][PR stack #2] Add accredited individuals allow-list syncing system

- db/schema.rb
- modules/accredited_representative_portal/db/migrate/20250128162530_create_ar_power_of_attorney_form_submissions.rb
This is PR No. 1 of a stack concerning ticket #101919
- *(Summarize the changes that have been made to the platform)* Added migration to record PoA form submissions to Lighthouse
- *(If bug, how to reproduce)* feature
- *(What is the solution, why is this the solution?)* https://github.com/department-of-veterans-affairs/va.gov-team/issues/101919
- *(Which team do you work for, does your team own the maintenance of this component?)* ARF/ART
- *(If introducing a flipper, what is the success criteria being targeted?)* -
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/101919
- *Link to previous change of the …
> [ARP POA submission] (#1) Create migration for PoA form submissions (#101919)

- spec/lib/github_authentication/sidekiq_web_spec.rb
Prepare for a future Rack 3.x upgrade by updating the Sidekiq Web session secret  in our sidekiq spec to meet the new minimum length requirement (64 characters). In Rack 3.0, session  secrets shorter than 64 characters result in an `ArgumentError`, preventing tests from passing.
This change allows Sidekiq Web authentication tests to pass consistently in both current and future Rack versions.
> fix(tests): ensure Rack session secret meets minimum length requirement

- modules/ivc_champva/app/services/ivc_champva/email.rb
- modules/ivc_champva/spec/services/email_spec.rb
This PR is a follow-up to this [previous bugfix](https://github.com/department-of-veterans-affairs/vets-api/pull/20382). This PR configures the VA Notify email params to have default `nil` values so that the unit test can more accurately catch when properties are missing/misconfigured. It also updates the associated unit test `data` object with the current list of necessary keys.
This will help prevent future misconfigurations to the parameter list in `IvcChampva::Email::send_email` from going unnoticed (as was the case when the [bug referenced here](https://github.com/department-of-veterans-affairs/vets-api/pull/20382) was introduced).
- This work is not behind a feature toggle
- Team: IVC CHAMPVA
- [Original bugfix](https://github.com/department-of-veterans-affairs/vets-api/pull/20382) …
> 20382 refactor IVC email VA Notify param logic + associated test - IVC CHAMPVA forms

- config/features.yml
> YES
> Removing obsolete feature toggles for Decision Review new API endpoints
> - `decision_review_hlr_new_api`
> - `decision_review_nod_new_api`
> - `decision_review_sc_new_api`
>
> Dependent on these 2 PRs being merged  - DO NOT MERGE BEFORE:
> - https://github.com/department-of-veterans-affairs/vets-website/pull/34544
> - https://github.com/department-of-veterans-affairs/vets-website/pull/34546
- *(If introducing a flipper, what is the success criteria being …
> Remove DR new API toggles

- modules/accredited_representative_portal/lib/tasks/seed/staging_seed.rb
- modules/accredited_representative_portal/lib/tasks/seed/staging_seed/constants.rb
- modules/accredited_representative_portal/lib/tasks/seed/staging_seed/methods.rb
- modules/accredited_representative_portal/lib/tasks/staging_seed.rake
- modules/accredited_representative_portal/spec/lib/tasks/staging_seed_spec.rb
Fixes seed data to comply with camel casing expectation of POA form schema. 
Also, use of rand + assertion on existence of resolved and unresolved failed w/ seed:
`bundle exec rspec --seed 41240 modules/accredited_representative_portal/spec/`
Is switching to have every other one be resolved / unresolved acceptable for our staging seed approach @chumpy ?
> [ARP][PR stack #1] fix seed spec

- modules/mocked_authentication/app/views/mocked_authentication/credential/index.html.erb
Just fixing the link to the docs page on the Mocked Authentication page :-)
> Update mocked auth docs link

- modules/debts_api/lib/debts_api/v0/financial_status_report_service.rb
- modules/debts_api/spec/lib/debt_api/v0/financial_status_report_service_spec.rb
- Refactored FinancialStatusReportService to use timiing
- Ensures StatsD captures request start time and end time of request metrics for VBA,VBS, and VHA FSR Submissions
[102406](https://github.com/department-of-veterans-affairs/va.gov-team/issues/102406)
> 102406 - Add Statsd metrics to report latency for our partner requests

- config/features.yml
- Adding a feature toggle for VaDate/VaDateField adoption
- No exact target date for removal since it will depend on the deployment of the feature which has no explicit deadline. However, the engineering work will likely start next sprint and deployment will begin immediately after. Deployment and removal will likely be in Q1 2025.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/103076
N/A
N/A
> Add feature flag for VADate/VaDateField adoption

- modules/claims_api/spec/controllers/v2/veterans/power_of_attorney/request_controller_spec.rb
- modules/claims_api/spec/requests/v1/forms/0966_spec.rb
- modules/claims_api/spec/requests/v1/forms/2122_spec.rb
- modules/claims_api/spec/requests/v1/forms/526_spec.rb
- modules/claims_api/spec/requests/v2/veterans/claims/5103_spec.rb
- modules/claims_api/spec/requests/v2/veterans/intent_to_files_spec.rb
- modules/claims_api/spec/requests/v2/veterans/power_of_attorney/2122_spec.rb
- modules/claims_api/spec/requests/v2/veterans/power_of_attorney/2122a_spec.rb
- modules/claims_api/spec/requests/v2/veterans/power_of_attorney/power_of_attorney_request_spec.rb
- modules/claims_api/spec/support/auth_helper.rb
- modules/my_health/spec/requests/my_health/v1/prescriptions_spec.rb
Prepare specs for Rack 3.x by setting the `Content-Type: application/json` header in JSON requests. This is a backwards compatible change that prevents issues where Rails does not parse the request body correctly, which would lead to unexpected 422 errors after the upgrade.
> fix(tests): ensure compatibility with Rack 3.x by adding Content-Type header

- modules/vye/spec/sidekiq/vye/midnight_run/ingress_bdn_spec.rb
- bdn_ingress test was failing because today is a holiday
- failing test
- fix logging for when test is run on a holiday
- VEBT
- *(If introducing a flipper, what is the success criteria being targeted?)*  N/A
- *Link to slack thread where issue with test identified, blocking another team
https://dsva.slack.com/archives/CBU0KDSB1/p1739814769793249
- bdn_ingress test failed
- check that all tests pass
VYE tests
> VEBT: fix failing VYE bdn_ingress test on holidays

- app/sidekiq/benefits_intake_status_job.rb
- spec/sidekiq/benefits_intake_status_job_spec.rb
This PR removes a conditional around a feature flag that we don't anticipate using. There are no plans currently to replace this job (`BenefitsIntakeStatusJob`) with another job.
> Remove :benefits_intake_submission_status_job from BenefitsIntakeStatusJob

- config/features.yml
- Removes `mhv_account_creation_api_consumption` feature toggle
- department-of-veterans-affairs/va.gov-team#99638 …
> Removes mhv_account_creation_api_consumption

- config/database.yml
- config/settings.yml
- docker-compose.review.yml
- docker-compose.test.yml
- docker-compose.yml
- Since developers have a variety of configurations use the existing `database_url` and `test_database_url` scheme and host when constructing the audit database url
- setup databases, you should see that they are already created
```bash
rails db:setup
```
Database config
> Use existing database_url for development and test audit_db

- modules/travel_pay/app/services/travel_pay/appointments_client.rb
- modules/travel_pay/app/services/travel_pay/base_client.rb
- modules/travel_pay/app/services/travel_pay/claims_client.rb
- modules/travel_pay/app/services/travel_pay/expenses_client.rb
- modules/travel_pay/app/services/travel_pay/token_client.rb
- modules/travel_pay/spec/services/appointments_client_spec.rb
- modules/travel_pay/spec/services/claims_client_spec.rb
- modules/travel_pay/spec/services/expenses_client_spec.rb
- modules/travel_pay/spec/services/token_client_spec.rb
- Adding `statsd` logging to our external API calls to measure response time
- We need a way to measure how long it takes for each response individually to track latency when calling the external API. 
- We are currently only tracking the latency for the entire process, not each step individually (i.e. getting tokens, then getting the claims takes `a` ms vs. getting the first token takes `x` ms, the second token takes `y` ms and actually getting the claims response takes `z` ms)
- Travel Pay …
> Travel Pay / Add `statsd` logging

- spec/rails_helper.rb
- The CI logs have 26 instances of VCR errors for:
- unhandled requests to datadog trace and ec2 metadata
- This adds over 550 log lines which is roughly 40% of the total lines
- They should be ignored by VCR
- n/a
> VCR ignore datadog trace and EC2 metadata uris

- modules/vaos/app/docs/vaos/v2/vaos_v2.yaml
- modules/vaos/app/services/vaos/v2/appointments_service.rb
- modules/vaos/spec/services/v2/appointment_service_spec.rb
- We no longer differentiate between GFE and non-GFE video appointments on the front end so this PR removes the logic that makes this distinction.
- Appointments tool team
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/101540
- Updated unit tests to account for the new behavior
N/A
Appointments tool
> Remove GFE appointment modality

- config/features.yml
- Adding a feature toggle for modifying the date range selection on the Past appointments page
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/103201
N/A
N/A
> Add feature flag for past appointment date range selection

- app/sidekiq/form1095/new1095_bs_job.rb
- spec/sidekiq/form1095/new1095_bs_job_spec.rb
- *This work is behind a feature toggle (flipper): No. This work impacts non-client facing data ingestion code. 
- This changes the 1095b data ingestion job–which ingests data placed on an s3 bucket by the enrollment team–to no longer retain the data file if a veteran's icn is missing in the data. That is expected behavior and should not be considered a failure. We should just skip that record and delete the data ingestion file. 
https://github.com/department-of-veterans-affairs/va-iir/issues/1429
- *Describe what the old behavior was prior to the change* 
The data ingestion job raised an error when the veteran's icn was missing from the data. It also did not delete the data file.
- *Describe the steps required to verify your changes are working as expected. Exclusively stating 'Specs …
> 1429 1095b missing icn

- lib/periodic_jobs.rb
@stevenjcumming This will cron up that allowlist sync job!
FYI, we might intentionally get the cron going before we update parameter store with some values (this will cause the job to error but we can just look at the errors in DD and that would be pretty neat).
Then after parameter store values are set we'll merge in the final piece of code that bases our authorization on this allowlist and the sidekiq pods would at that point get new'd with the necessary env vars.
> [ARP] Register cron for ARP allowlist sync

- .github/CODEOWNERS
- app/controllers/sign_in/user_info_controller.rb
- app/policies/sign_in/user_info_policy.rb
- config/routes.rb
- config/settings.yml
- spec/controllers/sign_in/user_info_controller_spec.rb
- spec/policies/sign_in/user_info_policy_spec.rb
- Creat a user info endpoint that returns `credential_uuid`, `email`, `first_name`, `last_name`, `icn`, `sec_id`
- Restrict access to specific SiS clients
- route not available in production
- https://jira.devops.va.gov/browse/VI-1066
- Add `vaweb` to `Settings.sign_in.user_info_clients`
- Sign in
- go to http://localhost:3000/sign_in/user_info
- you should see a response like:
```json
{
"credential_uuid": "ba8028fc-bb4d-47aa-8fee-46f740cc3bb4",
"icn": "112345678V54321",
"sec_id": "0000012345",
"first_name": "First",
"last_name": "Last",
"email": "user@gmail.com"
}
```
- remove `vaweb` from settings
- sign in
- go to http://localhost:3000/sign_in/user_info
- you should get a `403`
Sign-in service
> [VI-1066] - createUserInfo endpoint

- modules/ivc_champva/app/models/ivc_champva/vha_10_7959c.rb
- modules/ivc_champva/spec/fixtures/form_json/vha_10_7959c.json
- modules/ivc_champva/spec/models/vha_10_7959c_spec.rb
This PR updates the metadata for IVC CHAMPVA form 10-7959c to include the `applicantEmail` property. This is so that submitted attachments will contain the the applicant's email address embedded in the file metadata upon submission to S3. 
- Updates IVC form 10-7959c metadata constructor to include new email prop
- Update relevant test data in spec files
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/102728
NA
IVC CHAMPVA form 10-7959c
NA
> Add optional `applicant_email` to PDF metadata - IVC CHAMPVA forms

- app/services/sign_in/user_loader.rb
- spec/services/sign_in/user_loader_spec.rb
- If a user has a verified `mhv` or `dslogon` account with a `backing_idme_uuid` and an unverified `idme` account with the same `idme_uuid` it will find the unverified `UserVerification` in `User`. 
- This happens if a user has a verified mhv/dslogon account that shares the same email with an unverified `idme`
- Pass the `user_verification_id` in the `UserLoader` to make sure the correct one is set
- https://jira.devops.va.gov/browse/VI-1078
- Test Sign In service auth
- will need to test MHV on staging
Sign In service
x- [x]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
> [VI-1078] Pass user_verification_id in UserLoader

- lib/efolder/service.rb
- spec/uploaders/evss_claim_document_uploader_spec.rb
This service has been causing over 33k 500 errors a day. Datadog error can be found [here](https://vagov.ddog-gov.com/error-tracking?query=service%3Avets-api&fromUser=false&issueId=bd619772-b170-11ef-80c2-da7ad0900007&refresh_mode=sliding&source=all&from_ts=1739912862047&to_ts=1739916462047&live=true). Datadog error logs can be found [here](https://vagov.ddog-gov.com/logs?query=env%3Aeks-prod%20service%3Avets-api%20-%22%5BMHV%5D%5BUserAccount%5D%5BCreator%5D%20%22%20-%22%60block%20in%20bgs_doc_uuids%27%22%20%40payload.controller%3A%22Mobile%3A%3AV0%3A%3AEfol …
> Check if uploaded docs are a hash or have a key

- modules/va_notify/lib/va_notify/default_callback.rb
- modules/va_notify/spec/lib/default_callback_spec.rb
- This PR removes the logic using the `va_notify_metadata_statsd_tags ` toggle introduced in https://github.com/department-of-veterans-affairs/vets-api/pull/20235. The toggle has been on in production for a while and we no longer need to be able to turn it off. 
- [This PR was created to delete the actual toggle from the feature file](https://github.com/department-of-veterans-affairs/vets-api/pull/20729)
- https://github.com/department-of-veterans-affairs/vets-api/pull/20235
- *If this work is behind a …
> [VANotify] Remove va_notify_metadata_statsd_tags flipper toggle logic

- app/models/form_profile.rb
- config/features.yml
- modules/burials/app/models/burials/form_profiles/va_21p530ez.rb
- modules/burials/spec/lib/burials/form_profiles/va_21p530ez_spec.rb
- spec/models/form_profile_spec.rb
Migrate the form_profile (prefill) logic for Burials 21P-530EZ over to the module space.
- Updated FormProfile so that people can easily switch to a module version of their form profile
- Added `burial_form_profile_module_enabled` flipper
- Added tests for 100% coverage
- Ported over form profile files for Burial
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/99558
Burial Module and FormProfile
> 99558: Migrate burial form profile logic to module

- config/features.yml
This PR removes expired feature toggles from the feature flag registry. The toggles were utilized for rolled out features and have been scrapped from any conditionals in 10-10 applications, thus there are no longer necessary.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/103520
> Remove expired 10-10 feature toggles

- app/controllers/sign_in/user_info_controller.rb
- spec/controllers/sign_in/user_info_controller_spec.rb
- Add `sub` to user info response. This should match the `sub` in the access token which is currently `csp_uuid`
- https://jira.devops.va.gov/browse/VI-1089
- Add `vaweb` to `Settings.sign_in.user_info_clients`
- Sign in
- go to http://localhost:3000/sign_in/user_info
- you should see a response like:
```json
{
"sub": "ba8028fc-bb4d-47aa-8fee-46f740cc3bb4",
"credential_uuid": "ba8028fc-bb4d-47aa-8fee-46f740cc3bb4",
"icn": "112345678V54321",
"sec_id": "0000012345",
"first_name": "First",
"last_name": "Last",
"email": "user@gmail.com"
}
```
Sign-in service
> [VI-1089] - Add sub to user_info response

- lib/shrine/plugins/validate_correct_form.rb
This PR allows `png`s and `jpeg`s to be validated in the Form Upload tool. Currently, we're only validating `pdf`s but this allows other file types to pass through and not warn the Veteran that they may be uploading the wrong file. I had expected more modifications to be necessary but I tested this locally (both for pngs and jpegs that should have passed and failed validation) and it all works great!
https://github.com/orgs/department-of-veterans-affairs/projects/1443/views/3?sliceBy%5Bvalue%5D=Thrillberg&pane=issue&itemId=98818140&issue=department-of-veterans-affairs%7CVA.gov-team-forms%7C2030
> Form Upload - allow png and jpeg to be validated

- .github/workflows/audit_service_tags.yml
- .github/workflows/build.yml
- .github/workflows/code_checks.yml
- .github/workflows/deploy-template.yml
- docker-compose.test.yml
Issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/90369
As the developers and engineers on the VA Platform,
We need to pull images for gh-actions from a private ECR repo.
So that we can avoid failed gh-actions due to rate limiting.
> chore: Use private ECR for GHA docker images

- modules/accredited_representative_portal/app/services/accredited_representative_portal/power_of_attorney_request_service/create/form_data_adapter.rb
- modules/accredited_representative_portal/spec/services/accredited_representative_portal/power_of_attorney_request_service/create/form_data_adapter_spec.rb
- modules/representation_management/app/controllers/representation_management/v0/power_of_attorney_requests_controller.rb
- modules/representation_management/app/serializers/representation_management/power_of_attorney_request_serializer.rb
- modules/representation_management/app/services/representation_management/power_of_attorney_request_service/orchestrate.rb
- modules/representation_management/spec/requests/representation_management/v0/power_of_attorney_requests_controller_spec.rb
- modules/representation_management/spec/serializers/power_of_attorney_request_serializer_spec.rb
- modules/representation_management/spec/services/power_of_attorney_request_service/orchestrate_spec.rb
- This pr creates an orchestration service for Power of Attorney request creation
- adapt the form data
- make the request and form records
- delete form in progress if applicable
- This pr calls the orchestration service in ARM's poa request controller
- This pr fixes a data transformation issue in the adapter 
- [99974](https://github.com/department-of-veterans-affairs/va.gov-team/issues/99974)
- Went through the Appoint a Rep flow locally with authed user and hit the endpoint to make sure records were created
This impacts ARP and Appoint a Rep 21-22 once the feature flag is enabled
> [99974] Create poa request orchestration service - part 2 

- .github/workflows/audit_service_tags.yml
- .github/workflows/code_checks.yml
- docker-compose.test.yml
The trailing slash allows the use of docker-compose.test.yml locally with Docker Hub.
I also confirmed it was actually pulling by checking the digests. They differ between docker hub and our private ecr. I ran this script in GHA (which should have failed if it hadn't pulled the image yet) and the digest matched with ECR:
```yaml
- name: Check ECR_REGISTRY
run: |
docker inspect --format='{{index .RepoDigests 0}}' 008577686731.dkr.ecr.us-gov-west-1.amazonaws.com/redis:6.2-alpine
```
> chore: pull ECR registry from ENV var

- lib/source_app_middleware.rb
This fixes https://vagov.ddog-gov.com/monitors/200229, which alerted [the oncall channel](https://dsva.slack.com/archives/C30LCU8S3/p1740504820935559).
None. Saw while I was covering for support. 
Once deployed (tomorrow at 1pm ET), the monitor will resolve. 
**vets-api source app monitor - un-mapped source app detected** monitor
> Update source_app_middleware.rb with 10-7959C

- modules/ivc_champva/app/controllers/ivc_champva/v1/uploads_controller.rb
During the refactoring of [this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/20727/), we removed a data dog trace that was useful in our dashboard. This PR adds it back.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/102270
|Form …
> Add back previously removed Data Dog trace for submitted forms - IVC CHAMPVA forms

- config/features.yml
This PR updates the actor type on the `form107959c` feature toggle to be `cookie_id` so that users will have a consistent flipper experience across both the static entry page and the actual form intro page (rather than having the flipper re-roll the dice in those two locations and potentially giving users confusing results).
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/103567
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/develop …
> 103567 - Update OHI form feature toggle actor type to be `cookie_id` - form 10-7959c

- app/controllers/v0/form1095_bs_controller.rb
- app/models/form1095_b.rb
- app/sidekiq/form1095/new1095_bs_job.rb
- spec/models/form1095_b_spec.rb
- spec/requests/swagger_spec.rb
- spec/requests/v0/form1095_bs_spec.rb
- spec/sidekiq/form1095/new1095_bs_job_spec.rb
- This change modifies a job that ingests files placed on S3 by the enrollment team. The job is being changed to not process records for tax years prior to the current tax year.
- I work for the IIR team and we will maintain this code. 
https://github.com/department-of-veterans-affairs/va-iir/issues/1430
Because this is being done in a job that relies on s3, local tests are the best we can do.
Only touches 1095b code.
> 1430 do not save 1095b data prior to current tax year

- config/settings.yml
- config/settings/test.yml
- spec/lib/debt_management_center/vbs/request_spec.rb
- spec/services/medical_copays/request_spec.rb
- spec/support/vcr_cassettes/debts/get_letters.yml
- spec/support/vcr_cassettes/debts/get_letters_empty_response.yml
- spec/support/vcr_cassettes/debts/get_letters_empty_ssn.yml
- spec/support/vcr_cassettes/debts/person_data_and_letters.yml
- spec/support/vcr_cassettes/dmc/download_pdf.yml
- spec/support/vcr_cassettes/dmc/submit_fsr.yml
- spec/support/vcr_cassettes/dmc/submit_fsr_error.yml
- spec/support/vcr_cassettes/dmc/submit_to_vbs.yml
- spec/support/vcr_cassettes/govdelivery_emails.yml
- spec/support/vcr_cassettes/mdot/get_supplies_403.yml
- spec/support/vcr_cassettes/mdot/get_supplies_422.yml
- spec/support/vcr_cassettes/mdot/get_supplies_502.yml
- spec/support/vcr_cassettes/mdot/get_supplies_503.yml
- spec/support/vcr_cassettes/mdot/get_supplies_no_perm_address_200.yml
- spec/support/vcr_cassettes/mdot/get_supplies_no_temp_address_200.yml
- spec/support/vcr_cassettes/mdot/get_supplies_null_perm_address_200.yml
- spec/support/vcr_cassettes/mdot/get_supplies_null_temp_address_200.yml
- spec/support/vcr_cassettes/mdot/submit_order.yml
- spec/support/vcr_cassettes/mdot/submit_order_400.yml
- spec/support/vcr_cassettes/mdot/submit_order_502.yml
- spec/support/vcr_cassettes/mdot/submit_order_missing_body_400.yml
- spec/support/vcr_cassettes/staccato/event.yml
This PR replaces the old fwdproxy URL with the new one. But only in the non-spec files. Some tests and cassettes still refer to the old URL but I don't think we need to change those.
These changes are required to correct issues seen in our Review Instances where the build picks up on these configurations that still point to our old fwdproxy URLs. I tried getting away with _not_ updating the VCR cassettes, but tests were failing without the url update.
Working with Hector on this.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/101001
- I confirmed that these were the URLs in AWS. 
- Hector [discovered](https://github.com/department-of-veterans-affairs/va.gov-team/issues/101001#issuecomment-2674718409) that these are showing up in Review Instances. 
Nothing, really. …
> Update fwdproxy URLs

- config/features.yml
This adds a new feature toggle for form 21-0966 to enable/disable the new confirmation page.
department-of-veterans-affairs/va.gov-team-forms#2031
> Add new form 21-0966 confirmation page feature toggle

- app/controllers/v1/sessions_controller.rb
- spec/controllers/v1/sessions_controller_spec.rb
- Accept `operation=mhv_exception` param in Sessions#new
- https://jira.devops.va.gov/browse/VI-1097
- https://github.com/department-of-veterans-affairs/vets-website/pull/34938
- Check out vets-website branch - https://github.com/department-of-veterans-affairs/vets-website/pull/34938
- start website and api
- got to http://localhost:3001/sign-in/mhv
- Click MHV button
- you should be redirected to http://localhost:3000/v1/sessions/mhv/new?operation=mhv_exception
Sessions
> [VI-1097] - Add mhv_exception operation type to sessions#new

- modules/accredited_representative_portal/app/serializers/accredited_representative_portal/power_of_attorney_request_serializer.rb
- modules/accredited_representative_portal/spec/requests/accredited_representative_portal/v0/power_of_attorney_requests_spec/responses/dependent_claimant_power_of_attorney_form.json
- modules/accredited_representative_portal/spec/requests/accredited_representative_portal/v0/power_of_attorney_requests_spec/responses/veteran_claimant_power_of_attorney_form.json
- modules/accredited_representative_portal/spec/serializers/accredited_representative_portal/power_of_attorney_request_serializer_spec.rb
https://github.com/department-of-veterans-affairs/va.gov-team/issues/102923
This PR enhances the `PowerOfAttorneyRequestSerializer` by implementing **sensitive data redaction** for **SSN and VA file numbers**, ensuring that only the last four digits are exposed while the rest are masked.
- **Added a `TO_BE_REDACTED` constant** to define fields requiring redaction (`ssn`, `vaFileNumber`).
- **Implemented `redact_except_last_four_digits` method** to replace all but the last four characters with `'X'`.
- **Updated `power_of_attorney_form` processing** to apply redaction for `claimant`, `veteran`, and `dependent`.
- **Modified test fixture JSON responses** to reflect the redacted format (`XXXXX6789`).
- **Added unit tests in RSpec** to verify redaction logic for various input cases.
> Redact SSN and VA file number except last four digits in POA serializer

- modules/decision_reviews/config/routes.rb
DecisionReviews module endpoint for VA Notify callbacks renamed to better reflect the behavior.  Va Notify is not using this endpoint yet, about to switch.
- (https://github.com/department-of-veterans-affairs/va.gov-team/issues/101385)
URL was `nod_callbacks` because originally that was the only purpose of the endpoint. It is now used for notification callbacks for all DR submission errors …
> Rename DR Notification Callbacks Endpoint

- modules/representation_management/app/swagger/v0/swagger.json
- modules/representation_management/spec/requests/representation_management/v0/power_of_attorney_requests_swagger_spec.rb
- modules/representation_management/spec/support/rswag_config.rb
- modules/representation_management/spec/support/swagger_shared_components/v0.rb
- This pr adds swagger docs for the new POA Request digital submission endpoint
- [101855](https://github.com/department-of-veterans-affairs/va.gov-team/issues/101855)
- looked at generated swagger doc locally
Representation Management swagger docs
> [101855] Add poa request submission swagger docs

- modules/accredited_representative_portal/app/models/accredited_representative_portal/power_of_attorney_request.rb
- modules/accredited_representative_portal/app/services/accredited_representative_portal/power_of_attorney_request_service/create.rb
- modules/accredited_representative_portal/spec/models/accredited_representative_portal/power_of_attorney_request_spec.rb
- modules/accredited_representative_portal/spec/services/accredited_representative_portal/power_of_attorney_request_service/create_spec.rb
- This pr updates the POA Request Create service to use the poa holder type constant instead of hard coding the type as `AccreditedOrganization`
- This pr adds model validation to the POA Request to check the holder type against the allowed list
- [103953](https://github.com/department-of-veterans-affairs/va.gov-team/issues/103953)
- Created new poa requests locally running through the appoint front end
Appoint a Rep Form 21-22 and ARP
> [103953] Update POA Request creation to use poa holder types

- config/settings.yml
- config/settings/development.yml
- config/settings/test.yml
- authn_requests_signed is only used for machine specific development
- n/a
> remove authn_requests_signed from config settings

- app/models/saved_claim/higher_level_review.rb
- app/models/saved_claim/notice_of_disagreement.rb
- app/models/saved_claim/supplemental_claim.rb
- spec/models/saved_claim/higher_level_review_spec.rb
- spec/models/saved_claim/notice_of_disagreement_spec.rb
- spec/models/saved_claim/supplemental_claim_spec.rb
- No
This PR adds error handling and logging for JSON schema read errors related to the DR SavedClaim child models (`SavedClaim::HigherLevelReview`, `SavedClaim::NoticeOfDisagreement`, and `SavedClaim::SupplementalClaim`). The errors are related to the JSON schema gem being used for validation and is not an underlying schema issue, resulting in occasional submission failures. These exceptions can be ignored as the schema validation step for these SavedClaim models occurs after a different schema validation step has already succeeded.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/103415
The SavedClaim models would occasionally error out with a schema read …
> 103415: Handle schema read errors for DR SavedClaim models

- rakelib/extract_pdf_fields.rake
- New rake task to use PdfForms to get all form fields in a pdf and write to a file with the metadata that is needed when adding a new pdf form to the `PdfFill:Filler` module. This rake task can be used by engineers to more easily add new forms to the fill module. 
- If this is valuable, where is the best place to document that it exists and you can use it? Maybe a comment in the `PdfFill:Filler` module? 
-  Example:  `bundle exec rake pdf:extract_fields[lib/pdf_fill/forms/pdfs/10-10EZ.pdf]` and a file will be added in `lib/pdf_fill/forms/10-10EZ_field_data.json` will the field metadata.
- This work was added since I used it when working on https://github.com/department-of-veterans-affairs/va.gov-team/issues/60909
- …
> [1010 Health Apps] Add rake task to generate pdf form field metadata when adding new pdf fill class

- modules/ivc_champva/app/jobs/ivc_champva/missing_form_status_job.rb
- modules/ivc_champva/spec/jobs/missing_form_status_job_spec.rb
This PR adds new unit tests to the `MissingFormStatusJob` and updates the job to ignore form submissions that are < 1 minute old when determining if alerts should be sent.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/104036
NA
`MissingFormStatusJob` …
> 104036 - Update unit tests for Missing Form Status Job - IVC CHAMPVA forms

- config/features.yml
- New `hca_download_completed_pdf` toggle to be used to expose download pdf link in `vets-website` for the 10-10EZ form.
- `hca_download_completed_pdf`
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/102899 …
> [10-10EZ] Add new hca_download_completed_pdf toggle

- Gemfile.lock
From the following Backend Support issue -> https://dsva.slack.com/archives/CBU0KDSB1/p1741023083130489
Run bundle-audit CI check is failing on all PRs with the following message
```
Run bundle exec bundle-audit check --update --ignore CVE-2024-27456
Download ruby-advisory-db ...
Cloning into '/home/runner/.local/share/ruby-advisory-db'...
ruby-advisory-db:
advisories:	963 advisories
last updated:	2025-03-03 08:44:49 -0800
commit:	4b6766fe26a9f2590732bca3b563bf37d3aeacc9
Name: uri
Version: 1.0.2
CVE: CVE-2025-27221
Criticality: Unknown
URL: https://www.cve.org/CVERecord?id=CVE-2025-27221
Title: CVE-2025-27221 - userinfo leakage in URI#join, URI#merge and URI#+.
Solution: update to '~> 0.11.3', '~> 0.12.4', '~> 0.13.2', '>= 1.0.3'
Vulnerabilities found!
Error: Process completed with exit …
```
> Resolve bundle audit error - URI gem update

- app/models/health_care_application.rb
- spec/models/health_care_application_spec.rb
- Remove usage and logic for `retry_form_validation` toggle. It is currently on and we always want it on going forward.
- Future PR to remove the toggle itself and delete the toggles from the environment DBs
- Functionality added [in this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/20442).
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-to …
> [10-10EZ] Remove retry_form_validation toggle logic

- .github/workflows/build.yml
- .github/workflows/deploy-template.yml
- .github/workflows/labeler.yml
- Scheduled brownout today for Ubuntu 20.04 Actions runner image
- Bump to 22.04
- Source: https://github.com/actions/runner-images/issues/11101 
- n/a
> Bump gha runner image to ubuntu-22.04

- spec/serializers/intent_to_file_serializer_spec.rb
The uninitialized constant error was due to missing the require statement for `IntentToFilesResponse`. Adding this resolves the issue in the serializer spec.
When running `rspec spec/serializers/intent_to_file_serializer_spec.rb` alone, this error occured:
```
uninitialized constant EVSS::IntentToFile::IntentToFilesResponse
```
> fix: require IntentToFilesResponse to resolve error

- app/sidekiq/evss/document_upload.rb
- app/sidekiq/lighthouse/evidence_submissions/document_upload.rb
- spec/sidekiq/evss/document_upload_spec.rb
- spec/sidekiq/lighthouse/evidence_submissions/document_upload_spec.rb
While turning on `cst_send_evidence_submission_failure_emails` on 3/4/25 we noticed that a possible bug was present in the instance where...
- A document was uploaded and queued to upload in the service code with sidekiq (evss_claim_service.rb and service.rb) but the document_upload code (document_upload.rb) was not ran yet. When we turned on the ff `cst_send_evidence_submission_failure_emails` the document upload code was then ran for some document uploads and an error occurred because the code that runs in document_upload.rb expected an evidence_submission record to exist, but no record existed since the service code had not been ran with the ff enabled.
- We updated `app/sidekiq/evss/document_upload.rb` and `app/sidekiq/lighthouse/evidence_submissions/document_upload.rb` to account for …
> [CST] [ZSF] Resolved edge case bug with turning on ff cst_send_evidence_submission_failure_emails

- db/schema.rb
- modules/accredited_representative_portal/db/migrate/20250227192104_create_ar_power_of_attorney_request_withdrawals.rb
- This is part 1 of work to introduce a new concept for POA Request Resolutions - Withdrawals
- for example, replacing an active request with a new one to enforce the business rule that a claimant can only have one active poa request
- This pr is the migration to create the new resolution type table
- [104070](https://github.com/department-of-veterans-affairs/va.gov-team/issues/104070)
- No unit tests because it's only a migration
- Ran migration locally
Will impact Appoint a Rep 21-22 and ARP once the table is in use
> [104070] Migration for new poa withdrawals - Part 1

- app/models/form_profiles/va_526ez.rb
- app/services/claim_fast_tracking/max_rating_annotator.rb
- spec/models/form_profile_spec.rb
- spec/models/form_profile_v2_spec.rb
- spec/requests/v0/disability_compensation_in_progress_forms_controller_spec.rb
- spec/services/claim_fast_tracking/max_rating_annotator_spec.rb
Removes the feature flag `disability_526_max_cfi_service_switch`. 
- https://github.com/department-of-veterans-affairs/abd-vro/issues/4164
Follow On Ticket to Remove the Feature Flag from features.yml:
- https://github.com/department-of-veterans-affairs/vets-api/pull/21080
- unit tests were updated 
- old behavior: feature flag indicated where to send traffic `max-cfi-api` within VRO **OR** to `disability-max-ratings-api`
- new behavior: API in VRO is being turned off, all traffic needs to always point to `disability-max-ratings-api`
N/A
> Remove max ratings api switch ff

- modules/claims_api/app/sidekiq/claims_api/va_notify_accepted_job.rb
- modules/claims_api/app/sidekiq/claims_api/va_notify_declined_job.rb
- modules/claims_api/app/sidekiq/claims_api/va_notify_follow_up_job.rb
What it says on the tin. Make sure to log _before_ trying to reach out to a 3rd party for error alerting. That way if its call errors, we'll at least still have our log to fall back on.
[API-40902](https://jira.devops.va.gov/browse/API-40902)
- Ran existing specs w/ no failures.
Background job processing w/in ClaimsAPI - nothing consume facing.
> Write to log before sending to slack

- app/sidekiq/form1095/new1095_bs_job.rb
- Changes the 1095b ingestion job to not retry. Based on logs, it looks as though it spawns two or occasionally three retry processes simultaneously, which results in a race condition wherein both jobs attempt to create the same record at once, which kills the job and forces more retries. Given the sheer number of records per ingestion file, this is extremely inefficient. There is no need to retry this job.
https://github.com/department-of-veterans-affairs/va-iir/issues/1492
No testing needed because it just changes the sidekiq options for the job. 
1095b ingestion job
> 1492: do not retry 1095b ingestion job

- app/sidekiq/lighthouse/evidence_submissions/delete_evidence_submission_records_job.rb
- spec/sidekiq/lighthouse/evidence_submissions/delete_evidence_submission_records_job_spec.rb
This reverses this PR, which was incorrect: https://github.com/department-of-veterans-affairs/vets-api/commit/8e6c548f45e69d727310c49ad05e05e8817c2a74
- Restores the second parameter in `StatsD.increment` used for tracking amount of records deleted
- After speaking with Molly Trombley-McCann and Derek Fong, it was confirmed that the StatsD gem we use does implement that second parameter to store counts (unlike the official docs on DataDog's website say)
- https://github.com/department-of-veterans-affairs/vets-api/commit/8e6c548f45e69d727310c49ad05e05e8817c2a74 …
> Restored the count parameter used for logging to statsd which records got deleted

- spec/sidekiq/education_form/create_daily_spool_files_spec.rb
- Flaky spec causing other specs to fil
- Stub `Setting.hostname` so it doesn't affect other specs.
> Stub setting so it doesn't affect other specs

- modules/accredited_representative_portal/app/models/accredited_representative_portal/power_of_attorney_request.rb
- modules/accredited_representative_portal/app/models/accredited_representative_portal/power_of_attorney_request_resolution.rb
- modules/accredited_representative_portal/app/models/accredited_representative_portal/power_of_attorney_request_withdrawal.rb
- modules/accredited_representative_portal/app/services/accredited_representative_portal/power_of_attorney_request_service/create.rb
- modules/accredited_representative_portal/spec/factories/power_of_attorney_request.rb
- modules/accredited_representative_portal/spec/factories/power_of_attorney_request_resolution.rb
- modules/accredited_representative_portal/spec/factories/power_of_attorney_request_withdrawal.rb
- modules/accredited_representative_portal/spec/models/accredited_representative_portal/power_of_attorney_request_withdrawal_spec.rb
- modules/accredited_representative_portal/spec/services/accredited_representative_portal/power_of_attorney_request_service/create_spec.rb
- This pr introduces a new `PowerOfAttorneyRequestResolution` type of `Withdrawal`
- This pr withdraws, as a replacement, all unresolved poa requests when creating a new request
- [104070](https://github.com/department-of-veterans-affairs/va.gov-team/issues/104070)
- Went through the Appoint a Rep flow locally and confirmed previous active requests were withdrawn
Appoint a Rep and Accredited Representative Portal
> [104070] Enforce only one active poa request

- app/models/form_submission_attempt.rb
- app/sidekiq/simple_forms_api/notification/send_notification_email_job.rb
- spec/models/form_submission_attempt_spec.rb
- spec/sidekiq/simple_forms_api/notification/send_notification_email_job_spec.rb
- This work refactors the SendNotificationEmailJob to use a simplified parameter scheme in order to avoid any Sidekiq related state/data drops.
- This work also updates the FormSubmissionAttempt to call this job in the proper way
- This work also updates code coverage around the updated logic to be more streamlined and ensure full test coverage is met.
- I work on the Veteran Facing Forms team which owns this logic.
- [[Zero Silent Failures] - Failure email notification job is failing to queue](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/2062)
Any
> [SIMPLE-FORMS] fix: update send notification email job to account for perform_async args

- modules/simple_forms_api/app/services/simple_forms_api/notification/email.rb
- modules/simple_forms_api/app/services/simple_forms_api/notification_email.rb
- modules/simple_forms_api/spec/fixtures/form_json/vba_20_10207-third-party-non-veteran.json
- modules/simple_forms_api/spec/fixtures/form_json/vba_20_10207-third-party-veteran.json
- modules/simple_forms_api/spec/services/notification/email_spec.rb
- This work adds logic which properly uses the user's email address when sending a notification email
- This work also refactors the existing logic for determining form 20-10207's first name and email
- This work also refines and extends the existing RSpec coverage
- The logic is currently being duplicated because a separate refactor is still underway which will move this logic to a new location within the codebase.
- I'm on the Veteran Facing Forms team who own this code.
- [[Bug] 10207 emails are reverting to email address in Profile](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/2036)
Any
> [SIMPLE-FORMS] fix: add logic and supporting tests for user email support

- .github/CODEOWNERS
- .gitignore
- config/identity_settings/environments/dev.yml
- config/identity_settings/environments/localhost.yml
- config/identity_settings/environments/production.yml
- config/identity_settings/environments/staging.yml
- config/identity_settings/settings.yml
- config/initializers/identity_config.rb
- Create `IdentitySettings` for identity owned config. 
- `settings.yml` contains defaults
- each environment overrides or uses the default value
- a `~` is a secret value that will be injected from parameter store
- https://jira.devops.va.gov/browse/VI-1119
- Check `IdentitySettings` in console
Settings
> [VI-1119] - Create IdentitySettings

- modules/accredited_representative_portal/config/routes.rb
While these endpoints are still under development, they should be inaccessible in production. For now, this check is extra stringent, and makes these endpoints inaccessible anywhere outside development and test. But once development on these features picks back up, we want them to be accessible in staging too.
TODO: Carry out this per-environment guard of these endpoints by using Flipper feature toggling and controller before actions instead.
> [ARP] Disable non-POA request routes outside development and test

- modules/accredited_representative_portal/app/models/accredited_representative_portal/representative_user_account.rb
- modules/accredited_representative_portal/app/services/accredited_representative_portal/power_of_attorney_request_service/accept.rb
- modules/accredited_representative_portal/spec/models/accredited_representative_portal/representative_user_account_spec.rb
- modules/accredited_representative_portal/spec/requests/accredited_representative_portal/v0/power_of_attorney_request_decisions_spec.rb
Use the signature of the accepting representative rather than the requested representative on the POA form.
> [ARP] Fix POA signature

- modules/claims_api/app/controllers/claims_api/v2/veterans/power_of_attorney/request_controller.rb
- modules/claims_api/spec/controllers/v2/veterans/power_of_attorney/request_controller_spec.rb
* When params are sent to the power-of-attorney-requests endpoint we want a 400 status returned not a 422
* Adjusts the error status returned and adjusts the related tests
[API-45550](https://jira.devops.va.gov/browse/API-45550)
[API-45362](https://jira.devops.va.gov/browse/API-45362)
modified:   modules/claims_api/spec/controllers/v2/veterans/power_of_attorney/request_controller_spec.rb
> API-45550-changes-422-to-400-bad-request

- config/initializers/identity_config.rb
- spec/support/vcr_cassettes/identity/idme_200_responses.yml
- spec/support/vcr_cassettes/identity/idme_jwks_jwt_malformed.yml
- spec/support/vcr_cassettes/identity/idme_jwks_malformed.yml
- spec/support/vcr_cassettes/identity/idme_jwks_mismatched_kid.yml
- spec/support/vcr_cassettes/identity/idme_jwks_mismatched_signature.yml
- Load Identity secrets into `IdentitySettings` from the `ENV`
- Secrets are stored in parameter store with the format: 
```bash
/dsva-vagov/vets-api/{env}/env_vars/identity_settings/{key1}/{key2}/{key*n*}
```
e.g.
```bash
/dsva-vagov/vets-api/dev/env_vars/identity_settings/idme/client_secret
```
- Secrets get loaded into the `ENV` replacing each `/` after `env_vars/` with `__`. The above path would be loaded as
```ruby
ENV['IDENTITY_SETTINGS__IDME__CLIENT_SECRET']
```
- https://jira.devops.va.gov/browse/VI-1120
- Start rails console with env var `IDENTITY_SETTINGS__IDME__CLIENT_SECRET=some-secret`
```bash
IDENTITY_SETTINGS__IDME__CLIENT_SECRET=some-secret rails c
```
- Check setting
```ruby
IdentitySettings.idme.client_secret
```
ℹ️: `prod` may not be updated with `IDENTITY_SETTINGS` env …
> [VI-1120] Load IdentitySettings secrets

- app/controllers/v0/form1095_bs_controller.rb
- *This work is behind a feature toggle (flipper): NO (but these endpoints are not currently in use)
- Adds a service tag for use on datadog. AFAIK no additional steps are necessary to make this service appear on DD.
https://github.com/department-of-veterans-affairs/va-iir/issues/1424
I don't think this needs to be tested, but I'm open to suggestion if anyone has ideas.
It should create a new service on DD that can be used for monitoring this feature.
> 1421: add form-1095b service tag for datadog monitoring

- config/settings.yml
Adds two more IVC failure email template values to the settings file. 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/104386
NA
IVC forms 10-7959a/c
NA
> Added more failure email template params - IVC CHAMPVA forms

- modules/claims_api/app/services/claims_api/slack/failed_submissions_messenger.rb
- modules/claims_api/app/sidekiq/claims_api/report_hourly_unsuccessful_submissions.rb
- modules/claims_api/spec/services/failed_submissions_messenger_spec.rb
- modules/claims_api/spec/sidekiq/report_hourly_unsuccessful_submissions_spec.rb
Workflow from taking a claim ID datadog link, copying a transaction id from the detail, then pasting it back into the search felt not-great. In the cases of va.gov autoestablish claim errors, add a link to the transaction id log search directly to ease some suffering.
- [API-44632](https://jira.devops.va.gov/browse/API-44632)
Before, only the claim ID would have a link to datadog. 
Now, both the claim ID and its associated Transaction ID both have links to datadog.
Claims API slack alerting. Nothing consumer-facing.
> Add Transaction ID datadog link to va.gov-specific alerts

- modules/ivc_champva/app/services/ivc_champva/ves_data_validator.rb
- modules/ivc_champva/spec/services/ves_data_validator_spec.rb
This PR adds the first pass at our VES data validator. IVC CHAMPVA form 10-10d will soon be submitting to the new VES CHAMPVA API, so we need to make sure we can appropriately validate our data before sending it to VES.
- Adds new data validator class
- Adds some initial unit tests (more to come in a follow-on PR)
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/103453
NA
None yet; this is not in use anywhere. We're prepping this module for an integration in a coming sprint.
NA
> 103453 - Add validation for VES data - IVC CHAMPVA

- .github/CODEOWNERS
- app/controllers/v0/disability_compensation_forms_controller.rb
- lib/lighthouse/benefits_reference_data/response_strategy.rb
This PR renames and moves `lib/evss/reference_data/response_strategy.rb` to an appropriate location in the Lighthouse directory.
**Related issue**: https://github.com/department-of-veterans-affairs/va.gov-team/issues/104912
> chore: Rename EVSS::ReferenceData::ResponseStrategy class

- Gemfile.lock
Resolves CVE
```
Name: rack
Version: 2.2.12
CVE: CVE-2025-27610
GHSA: GHSA-7wqh-767x-r66v
Criticality: High
URL: https://github.com/rack/rack/security/advisories/GHSA-7wqh-767x-r66v
Title: Local File Inclusion in Rack::Static
Solution: update to '~> 2.2.13', '~> 3.0.14', '>= 3.1.12'
```
> chore: Update Rack to 2.2.13

- modules/accredited_representative_portal/app/controllers/accredited_representative_portal/v0/power_of_attorney_requests_controller.rb
- modules/accredited_representative_portal/app/models/accredited_representative_portal/power_of_attorney_request.rb
- modules/accredited_representative_portal/spec/requests/accredited_representative_portal/v0/power_of_attorney_requests_spec.rb
Bugfix for fixing processed POA requests 500 in API overlapped w/ excluding "withdrawn" POA requests from search results. (In fact logic changed to "return resolved that are decisioned", previously was "return resolved that are not expired").
Also threw in pending sort order fix because it just involved changing 2 characters.
> [ARP] pending sort order & processed only shows decisioned

- modules/simple_forms_api/lib/tasks/send_emails_by_date_range.rake
- modules/simple_forms_api/spec/tasks/send_emails_by_date_range_spec.rb
This PR introduces a rake task whose goal is to send `:received` and `:error` emails for form submissions that advanced to their final status but emails failed.
https://github.com/orgs/department-of-veterans-affairs/projects/1443/views/3?sliceBy%5Bvalue%5D=Thrillberg&visibleFields=%5B%22Title%22%2C%22Assignees%22%2C%22Status%22%2C%22Labels%22%2C139765646%5D&pane=issue&itemId=100860483&issue=department-of-veterans-affairs%7CVA.gov-team-forms%7C2070
> Simple forms send emails by date range rake task

- config/features.yml
- Removing some of the obsolete feature toggles for features that have been fully released.
- Appointments tools team
- This PR can only be merged after https://github.com/department-of-veterans-affairs/vets-website/pull/35081 is merged.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/103882
N/A
Appointments tools
> Remove unused appointments feature toggles - 5

- config/features.yml
- modules/vaos/config/initializers/flipper.rb
- Removing some of the obsolete feature toggles for features that have been fully released.
- Appointments tools team
- This PR should be merged after https://github.com/department-of-veterans-affairs/vets-website/pull/35106 is merged.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/103685
N/A
Appointments tools
> Remove unused appointments feature toggles - 2

- modules/ask_va_api/app/lib/ask_va_api/base_retriever.rb
- modules/ask_va_api/app/lib/ask_va_api/inquiries/payload_builder/inquiry_details.rb
- modules/ask_va_api/app/lib/ask_va_api/inquiries/payload_builder/inquiry_payload.rb
- modules/ask_va_api/app/lib/ask_va_api/inquiries/payload_builder/profile_builder_base.rb
- modules/ask_va_api/app/lib/ask_va_api/inquiries/payload_builder/submitter_profile.rb
- modules/ask_va_api/app/lib/ask_va_api/inquiries/payload_builder/veteran_profile.rb
- modules/ask_va_api/config/locales/en.yml
- modules/ask_va_api/spec/app/lib/ask_va_api/inquiries/payload_builder/submitter_profile_spec.rb
- modules/ask_va_api/spec/app/lib/ask_va_api/inquiries/payload_builder/veteran_profile_spec.rb
- modules/ask_va_api/spec/requests/ask_va_api/v0/inquiries_spec.rb
- modules/ask_va_api/spec/support/shared_contexts.rb
This PR introduces several improvements across multiple components, focusing on profile duplication, address handling, inquiry retrieval, and localization updates.
Key Changes
• VeteranProfile & Profile Duplication
• Updated VeteranProfile to check “I’m the Veteran”, ensuring it correctly duplicates VeteranProfile with SubmitterProfile.
• Expanded SharedContext with additional payload data for improved handling.
• Added new translation keys to en.yml for better localization support.
• Profile & Address Handling
• Enhanced InquiryPayload, ProfileBuilderBase, and SubmitterProfile to properly handle StateOfProperty, ZipCodeOfResidency, and other address-related data.
• Ensured consistent processing and integration of these fields across the system.
• Inquiry Retrieval Improvements
• Updated …
> Ask va api fix veteran profile dup bug

- config/features.yml
- Adding 4 new feature toggles:
- `va_online_scheduling_fe_source_of_truth_va`
- `va_online_scheduling_fe_source_of_truth_cc`
- `va_online_scheduling_fe_source_of_truth_modality`
- `va_online_scheduling_fe_source_of_truth_telehealth`
- Updating description of the existing feature toggle `va_online_scheduling_fe_source_of_truth`
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/104288
N/A
N/A
> Add additional feature toggles for source of truth updates

- app/sidekiq/evss/document_upload.rb
- app/sidekiq/lighthouse/evidence_submissions/delete_evidence_submission_records_job.rb
- app/sidekiq/lighthouse/evidence_submissions/document_upload.rb
- app/sidekiq/lighthouse/evidence_submissions/failure_notification_email_job.rb
- lib/lighthouse/benefits_documents/upload_status_updater.rb
- spec/lib/lighthouse/benefits_documents/service_spec.rb
- spec/lib/lighthouse/benefits_documents/upload_status_updater_spec.rb
- spec/services/evss_claim_service_spec.rb
- spec/sidekiq/evss/document_upload_spec.rb
- spec/sidekiq/lighthouse/evidence_submissions/document_upload_spec.rb
- spec/sidekiq/lighthouse/evidence_submissions/evidence_submission_document_upload_polling_job_spec.rb
- spec/sidekiq/lighthouse/evidence_submissions/failure_notification_email_job_spec.rb
- Found that we were setting `.utc` to the evidence submission date fields and we didn't need to since the date fields are saved as utc when saved to the database
- Also found that in the evidence submission code and tests we are using `DateTime.now` or `Time.now` when we should use `DateTime.current` or `Time.current` which uses what the Rails environment is set to. If it's not set, then .current will be same as .now and use the servers timezone.
Updated the following files: 
- app/sidekiq/evss/document_upload.rb
- app/sidekiq/lighthouse/evidence_submissions/delete_evidence_submission_records_job.rb
- app/sidekiq/lighthouse/evidence_submissions/document_upload.rb
- app/sidekiq/lighthouse/evidence_submissions/failure_notification_email_job.rb
- …
> [CST] - Updated code to no longer use `.utc` and to use `DateTime.current `

- app/models/form_submission_attempt.rb
- app/sidekiq/simple_forms_api/notification/send_notification_email_job.rb
- modules/simple_forms_api/app/controllers/simple_forms_api/v1/scanned_form_uploads_controller.rb
- modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb
- modules/simple_forms_api/app/services/simple_forms_api/notification/email.rb
- modules/simple_forms_api/app/services/simple_forms_api/notification/template_ids.yml
- spec/lib/lighthouse/benefits_intake/sidekiq/submission_status_job_spec.rb
- spec/models/form_submission_attempt_spec.rb
- spec/sidekiq/benefits_intake_status_job_spec.rb
- spec/sidekiq/simple_forms_api/notification/send_notification_email_job_spec.rb
This PR continues the work begun in these [two](https://github.com/department-of-veterans-affairs/vets-api/pull/20923) [PRs](https://github.com/department-of-veterans-affairs/vets-api/pull/20926). In the prior PRs we created new files in the right directory structure and this PR uses these new files.
This PR also makes use of a YAML file for template_ids, instead of having them inline in the code.
> Simple Forms Notification Email refactor

- Gemfile.lock
- Bump ruby-saml to 1.18.0
```
Name: ruby-saml
Version: 1.17.0
CVE: CVE-2025-25292
GHSA: GHSA-754f-8gm6-c4r2
Criticality: Unknown
URL: https://github.com/SAML-Toolkits/ruby-saml/security/advisories/GHSA-754f-8gm6-c4r2
Title: Ruby SAML allows a SAML authentication bypass due to namespace handling (parser differential)
Solution: update to '~> 1.12.4', '>= 1.18.0'
```
- n/a
> Bump ruby-saml to 1.18.0

- lib/periodic_jobs.rb
- Increases the frequency of running the 1095b deletion script because there are millions of records that need to be removed and it would take 6 months at 100k per day
- https://github.com/department-of-veterans-affairs/va-iir/issues/1430
None needed.
Deletion of old 1095b records
> 1430: run 1095b cron more frequently

- modules/simple_forms_api/lib/tasks/send_emails_by_date_range.rake
- modules/simple_forms_api/spec/tasks/send_emails_by_date_range_spec.rb
This PR makes two improvements to [the previously-merged rake task](https://github.com/department-of-veterans-affairs/vets-api/pull/21177):
1. Don't `raise` in case of error. Instead we will keep processing emails and output all errors at the end for further remediation. We also will keep extra track of error notifications to be sure all of those get sent.
2. Only send emails for Simple Forms. Other forms handle their own emails.
https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/2070
> Revise Simple Forms email rake task

- modules/claims_api/app/controllers/concerns/claims_api/target_veteran.rb
- modules/claims_api/spec/requests/v2/veterans/claims_spec.rb
* Updates target veteran `add_person_proxy` check to log out response when it fails.
* updates a related to test
[API-45585](https://jira.devops.va.gov/browse/API-45585)
modified:   modules/claims_api/app/controllers/concerns/claims_api/target_veteran.rb
modified:   modules/claims_api/spec/requests/v2/veterans/claims_spec.rb
> API-45585-add-logging-to-add-person-proxy-response-on-failure

- spec/factories/form526_submissions.rb
- spec/lib/sidekiq/form526_backup_submission_process/processor_spec.rb
- add unit test for generating 0781 and 0781a pdfs
- add unit test for generating 0781v2 pdf
- adds 2 unit tests checking the correct 0781 pdf is generated with the expected dataset in the Form526Submission record
- [#103148](https://github.com/department-of-veterans-affairs/va.gov-team/issues/103148)
n/a
> dbex/103148: [0781 PS] Spike - Test the Backup path for new 0781

- modules/appeals_api/spec/requests/appeals_api/v1/notice_of_disagreements_spec.rb
- modules/appeals_api/spec/requests/appeals_api/v2/decision_reviews/higher_level_reviews_spec.rb
- modules/appeals_api/spec/requests/appeals_api/v2/decision_reviews/supplemental_claims_spec.rb
This work is behind a feature toggle (flipper): *NO*
On 2/21, our team was notified by the Platform Team that a few of our `AppealsAPI` specs had been temporarily disabled in #20902 due to reported flakiness. However, on closer look at that PR, its description, and the failed job runs linked from it, we couldn't find any evidence that these specs were the ones causing a problem. (The description mentioned instance doubles for `OpenSSL::X509::Certificate`, which these specs don't utilize, and the failed Test job runs from the linked PR showed failed `V0::SignInController` specs but no failed `AppealsApi` specs.)
I also attempted to reproduce the flakiness locally by running the specs in parallel using the exact command we use in CI, but was not able to reproduce any failures after half a …
> API-45558: Reenable Decision Reviews Specs After Testing for Flakiness

- modules/vaos/app/controllers/vaos/v2/referrals_controller.rb
- modules/vaos/app/serializers/ccra/referral_detail_serializer.rb
- modules/vaos/app/serializers/ccra/referral_list_serializer.rb
- modules/vaos/config/routes.rb
- modules/vaos/spec/controllers/v2/referrals_controller_spec.rb
- modules/vaos/spec/factories/ccra/referrals.rb
- modules/vaos/spec/requests/v2/referrals_spec.rb
- modules/vaos/spec/serializers/ccra/referral_detail_serializer_spec.rb
- modules/vaos/spec/serializers/ccra/referral_list_serializer_spec.rb
- *This work is behind a feature toggle (flipper): NO* - This adds a new controller that is not currently used.
- Implement VAOS referral controller that uses the CCRA referral service.
- Team and owned by: UAE Check-in team
Tasks outstanding:
1. Betamocks - separate PR not yet opened
2. Swagger updates - separate ticket
https://github.com/department-of-veterans-affairs/va.gov-team/issues/98256
No Betamocks yet. That is a separate PR as mocks reside in `vets-api-mockdata`
N/A
N/A - not integrated yet
> Implement VAOS referral controller

- lib/search_typeahead/service.rb
- spec/lib/search_typeahead/service_spec.rb
- spec/requests/v0/search_typeahead_spec.rb
This is to address `NoMethodError`s we see when search.gov is slow.
> NoMethodError: undefined method `body' for an instance of Faraday::TimeoutError
https://dsva.slack.com/archives/C0460N83Y9G/p1741889358811859
> feat: SearchTypehead: Handle 500, 502, & 504

- config/initializers/sidekiq.rb
- config/puma.rb
Adding missing require statements for safely closing down Kafka producer instance when the Puma and Sidekiq processes shut down.
> Add missing require statements to initializers

- config/initializers/sidekiq.rb
- config/puma.rb
Emergency fix to a broken require statement that could prevent Puma from starting.
> Removing Kafka shutdown behavior b/c of broken require statements

- modules/simple_forms_api/app/services/simple_forms_api/notification/form_upload_email.rb
- modules/simple_forms_api/docs/form_upload_tool_README.md
- *Updated `SUPPORTED_FORMS` in Simple Forms API notification service to include additional form IDs.*
- *Updated documentation (`form_upload_tool_README.md`) with changes to form support and updated links.*
- *Which team do you work for, does your team own the maintenance of this component?* **Veteran Facing Forms Team**
- *No new flipper introduced.*
- Unit and E2E tests pass
Any
> [SIMPLE-FORMS] fix: add new form upload forms to the form upload flow notification email configuration

- config/initializers/sidekiq.rb
- config/puma.rb
Re-adding Kafka shutdown behavior with correct require statements. In the `config/initializer/sidekiq.rb` file, the path to `kafka/producer_manager` can be found. In `config/puma.rb`, the `$LOAD_PATH` does not contain the lib directory in local environments, but does contain it in VSP environments. I added the `require` statement to the `on_worker_shutdown` hook that won't run locally anyway:
> Warning: You specified code to run in a `on_worker_shutdown` block, but Puma is not configured to run in cluster mode (worker count > 0), so your `on_worker_shutdown` block will not run
> Re-add Kafka producer shutdown

- config/features.yml
- Adding `va_online_scheduling_display_past_cancelled_appointments`
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/105404
N/A
N/A
> Add feature toggles for displaying past cancelled appointments

- lib/va_profile/configuration.rb
- Cannot determine the nature of the issue with local testing and data needed for prefill
- Switch back to local & test using `Settings.vet360` and deployed env using `Settings.va_profile`
- Settings for va_profile didn't exist in local development or test
- n/a
> Switch VA Profile Settings back to Settings.vet360 for local and test 

- modules/simple_forms_api/app/services/simple_forms_api/notification/email.rb
- modules/simple_forms_api/spec/services/notification/email_spec.rb
This PR does not affect behavior except to add some logging when we send Simple Forms emails. This is part of an effort to debug 26-4555 emails not sending.
https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/2077
> Add logging for Simple Forms emails

- config/features.yml
- New feature toggle for linking to our react apps for forms 10215 and 10216 when we release them instead of the paper form download links
- [VEBT-1250](https://jira.devops.va.gov/browse/VEBT-1250)
- [VEBT-1251](https://jira.devops.va.gov/browse/VEBT-1251) …
> VEBT Add feature toggle for forms 10215, 10216 release

- modules/ask_va_api/app/lib/ask_va_api/inquiries/payload_builder/inquiry_payload.rb
- modules/ask_va_api/spec/app/lib/ask_va_api/inquiries/payload_builder/inquiry_payload_spec.rb
- Update InquiryPayload#medical_center_guid_lookup to handle `nil`
-
> BE | Ask VA API: Fix medicalCenter bug

- config/identity_settings/environments/production.yml
- config/identity_settings/environments/sandbox.yml
- config/identity_settings/environments/staging.yml
- config/identity_settings/settings.yml
- Update environment specific values after audit
- update `mvi.mock` default to `true` for consistency across other settings
- https://jira.devops.va.gov/browse/VI-1121
- Will re-confirm in all envs  once deployed
IdentitySettings
> Update IdentitySettings values

- config/settings.yml
`kafka_producer` was misspelled in settings.yml file
> Fix settings typo

- modules/accredited_representative_portal/app/sidekiq/accredited_representative_portal/power_of_attorney_request_email_job.rb
- modules/accredited_representative_portal/spec/sidekiq/accredited_representative_portal/power_of_attorney_request_email_job_spec.rb
The VA Notify team pointed out to us that the response is a ruby object, not a hash.  The hash code here was causing the email job to error and retry, resending the email every time.
- *(Summarize the changes that have been made to the platform)*: This PR just changes the method of accessing the response object from a hash to an object.  `.id` vs `['id']`.
- *(If bug, how to reproduce)* Triggering the digital submit confirmation or declination email now will cause the email job to get stuck in a retry loop.
- *(What is the solution, why is this the solution?)*: We were advised by the VA Notify team that the response will be a ruby object.  I had previously thought it was a hash, but I couldn't find the documentation that caused me to …
> Fix retry loop in AccreditedRepresentativePortal::PowerOfAttorneyRequestEmailJob

- app/sidekiq/form1095/delete_old1095_bs_job.rb
- app/sidekiq/form1095/new1095_bs_job.rb
- spec/sidekiq/form1095/delete_old1095_bs_job_spec.rb
- spec/sidekiq/form1095/new1095_bs_job_spec.rb
- Adds a prefix to 1095b logging to simplify log monitoring
- https://github.com/department-of-veterans-affairs/va-iir/issues/1424
- specs
1095b ingestion and deletion logs
> 1421 enable 1095b log monitoring

- config/features.yml
Switching show_yellow_ribbon_table from user to cookie_id, the comparison tool is not an authenticated service.
> cookie_id for show_yellow_ribbon_table

- .github/workflows/build_atlas_codeowners.yml
Due to a CVE issue, `tj-actions/changed-files@v46` was found to have a supply chain vulnerability that could lead to information disclosure of sensitive secrets. This includes, but is not limited to, valid access keys, GitHub Personal Access Tokens (PATs), npm tokens, and private RSA keys.
The vulnerability affected the Action's ability to detect file changes in pull requests and commits, potentially exposing secrets during execution.
🔹 This issue has been patched in v46.0.1. [Upgrading to this version is strongly recommended to mitigate the …
> CVE-2025-30066:  tj-actions/changed-files bump to patched version

- config/features.yml
Adding a feature toggle for using new notification callback custom class
Callback handler is correctly invoked and logging and metrics appear in DD
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/104037
- https://github.com/department-of-veterans-affairs/vets-api/pull/21214
No feature toggle in place
New feature toggle for a …
> Add feature flag for DR notification callbacks

- app/models/mpi_data.rb
- Add person proxy MPI call requires an MPI orchestrated 'search by attributes', returning a search token, before it can update the record. This search by attributes is incorrectly searching with the first and last given names, instead of family name
MPI integration
> Fixing add_person_proxy bug that doesn't properly search with a family name

- db/audit_migrate/20250320151836_rename_audit_user_identifier_type_enum_option.rb
- db/audit_schema.rb
- Fix audit log enum `audit_user_identifier_types`. `system_hostmame` -> `system_hostname`
- Run migrations:
```bash
rails db:migrate:audit
```
Audit Log
> Fix audit_log enum value

- app/services/bgs/uploaded_document_service.rb
Attempting to fix the high yielding[ efolder error](https://vagov.ddog-gov.com/error-tracking?query=service%3Avets-api%20env%3Aeks-prod&fromUser=true&issueId=bd619772-b170-11ef-80c2-da7ad0900007&refresh_mode=sliding&source=all&from_ts=1741880342338&to_ts=1742485142338&live=true). Return empty array when BGS uploaded_document is null. [Slack thread](https://dsva.slack.com/archives/C07VBGW29CZ/p1741963709097769)
- department-of-veterans-affairs/octo_watchofficer/issues/461
Behavir
This does not impact Vets API. This will return an empty array …
> Return empty array when BGS uploaded_document is null

- .gitignore
- The public directory was but is not currently ignored
- CarrierWave likes to store uploads in the public folder when it isn't using s3 (Local development)
- All CarrierWave store_dir values are added to .gitignore
- n/a
> Add CarrierWave upload directories to gitignore

- config/features.yml
- modules/ivc_champva/app/controllers/ivc_champva/v1/pega_controller.rb
- modules/ivc_champva/spec/requests/ivc_champva/v1/forms/status_updates_spec.rb
This PR removes the `champva_confirmation_email_bugfix` flipper that has been fully enabled in production for some months now.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/104641 …
> 104641a - Remove `champva_confirmation_email_bugfix` flipper - IVC CHAMPVA forms

- config/features.yml
Adding two feature flags to use the new notification callback custom class 
Benefits Decision Reviews, yes
Callback handler is used and correctly logs + emits metrics to Datadog
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/104037
- #21265 
Feature flags were not present
This will impact the Decision Review emails that are using VA Notify in the event of a downstream failure
(OPTIONAL)_What should the reviewers know in addition …
> 104037: Add feature flags for DR notification callbacks

- lib/pdf_fill/extras_generator.rb
- lib/pdf_fill/extras_generator_v2.rb
- lib/pdf_fill/filler.rb
- lib/pdf_fill/hash_converter.rb
- spec/lib/pdf_fill/extras_generator_spec.rb
- spec/lib/pdf_fill/extras_generator_v2_spec.rb
- *This work is behind a feature toggle (flipper): NO* -- this work is not hooked up to live code paths; when it is, it will be behind a feature toggle.
This PR is a refactor that moves all PDF overflow redesign code in ExtrasGenerator into a new subclass ExtrasGeneratorV2. This effectively reverts ExtrasGenerator to the existing overflow code using the `prawn` PDF renderer, while allowing ExtrasGeneratorV2 to switch to the extended renderer `prawn-markup`. No change to behavior or underlying renderer is introduced here.
I am on the Employee Experience team. The PdfFill codebase is shared library code maintained by Platform.
The diff is pretty big, but most of it is moving code from ExtrasGenerator to ExtrasGeneratorV2, and the corresponding move in RSpecs. The resulting ExtrasGenerator …
> Refactor ExtrasGenerator redesign code into ExtrasGeneratorV2

- modules/vaos/app/services/vaos/v2/appointments_presentation_filter.rb
- modules/vaos/app/services/vaos/v2/appointments_service.rb
- modules/vaos/spec/requests/vaos/v2/appointments_spec.rb
- modules/vaos/spec/services/v2/appointment_service_spec.rb
- modules/vaos/spec/services/v2/appointments_presentation_filter_spec.rb
- This updates the determination of future appointments by allowing a grace period of 240 minutes for telehealth appointments and 60 minutes for all other appointments. This ensures that for valid appointments exactly one of `past` or `future` is set to true.
- We are also updating the presentation filter to allow all past cancelled appointments to be retrieved.
- Appointments tool team
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/105466
N/A
Appointments tool
> Include cancelled past appointments in fetch results

- app/controllers/v1/gids/lcpe_controller.rb
- app/models/lcpe_redis.rb
- lib/gi/lcpe/configuration.rb
- lib/gi/lcpe/response.rb
- spec/lib/gi/lcpe/client_spec.rb
- spec/requests/v1/gi/lcpe/exams_spec.rb
- spec/requests/v1/gi/lcpe/lacs_spec.rb
- spec/support/vcr_cassettes/gi/lcpe/get_exam_details.yml
- spec/support/vcr_cassettes/gi/lcpe/get_exams_cache_fresh.yml
- spec/support/vcr_cassettes/gi/lcpe/get_exams_cache_nil.yml
- spec/support/vcr_cassettes/gi/lcpe/get_exams_cache_stale.yml
- spec/support/vcr_cassettes/gi/lcpe/get_lac_details.yml
- spec/support/vcr_cassettes/gi/lcpe/get_lacs_cache_fresh.yml
- spec/support/vcr_cassettes/gi/lcpe/get_lacs_cache_nil.yml
- spec/support/vcr_cassettes/gi/lcpe/get_lacs_cache_stale.yml
- *(Summarize the changes that have been made to the platform)* Staging review required removing '@' delimiter from enriched id for lcpe lacs and exams. Replacing with a 'v' for version. Also updating ETAG to use double instead of single quotes.
- *(What is the solution, why is this the solution?)* Replace special character with accepted character
- *(Which team do you work for, does your team own the maintenance of this component?)* Education Data Migration (EDM), yes
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/105704
- https://jira.devops.va.gov/browse/EDM-852 …
> EDM-852/update LCPE characters for etag and enriched id

- lib/decision_review_v1/utilities/form_4142_processor.rb
- modules/decision_reviews/lib/decision_reviews/v1/supplemental_claim_services.rb
- modules/decision_reviews/spec/requests/v1/supplemental_claims_spec.rb
- spec/lib/decision_review_v1/processor/form4142_processor_spec.rb
- spec/support/disability_compensation_form/submissions/with_4142.json
- Used `vets-json-schema` to add JSON Schema validation to Supplemental Claim (0995) Form 4142 submission processing. This allows us to detect `form4142` payload issues (e.g. missing fields, incorrect format for dates/state codes) before PDF generation is attempted, similar to how `SupplementalClaimsController#handle_saved_claim` currently uses the `SC-CREATE-REQUEST-BODY_V1` JSON schema.
- https://github.com/department-of-veterans-affairs/vets-json-schema/pull/981
- https://github.com/department-of-veterans-affairs/vets-website/pull/34995
- Impacts the processing and PDF template fill of in-0995 VA Form 21-4142 submissions
- Consider a follow-up PR to vets-website that uses the updated vets-json-schema definition to ensure alignment …
> Add JSON Schema validation to in-0995 form 4142

- app/swagger/swagger/v1/requests/appeals/appeals.rb
Update the urls for decision review endpoints in the swagger docs, to reflect the new module prefix
Decision Reviews, we own the urls being documented
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/105843
Swagger docs still showed the old urls without the `decision_reviews` prefix
Check swagger docs page
Swagger docs
> Update swagger docs for decision review endpoints

- app/controllers/v0/form1095_bs_controller.rb
- spec/requests/v0/form1095_bs_spec.rb
- *This work is behind a feature toggle (flipper): YES (on front end)
- adds statsd increment when user does not have a current 1095b for download. This is intended to help us better understand the user experience. 
https://github.com/department-of-veterans-affairs/va-iir/issues/1529
It only increments a counter when the user requests whether they have 1095b forms and they don't have any. It's just a metrics change.
> 1529 1095b statsd

- modules/accredited_representative_portal/app/controllers/accredited_representative_portal/v0/power_of_attorney_requests_controller.rb
- modules/accredited_representative_portal/app/services/accredited_representative_portal/power_of_attorney_request_service/params_schema.rb
- modules/accredited_representative_portal/spec/requests/accredited_representative_portal/v0/power_of_attorney_requests_spec.rb
- modules/accredited_representative_portal/spec/services/accredited_representative_portal/power_of_attorney_request_service/params_schema_spec.rb
This PR implements pagination for the Power of Attorney Requests index endpoint to address scaling issues as the number of requests grows. The implementation follows standard JSON API practices with page-based pagination.
- Added a new `ParamsSchema` module for validating and normalizing pagination parameters
- Updated the POA Requests controller to use pagination instead of a hard limit of 100 records
- Modified the JSON response format to include pagination metadata
- Updated tests to verify pagination functionality works correctly
- Page size defaults to 10 items per page with configurable min (10) and max (100) limits
- Parameters follow the JSON:API format: `page[number]` and `page[size]`
- Invalid pagination parameters return a 400 Bad Request response with descriptive error …
> Add Pagination to ARP Power of Attorney Requests List

- modules/mobile/app/models/mobile/v0/adapters/legacy_allergy_intolerance.rb
- modules/mobile/spec/requests/mobile/v0/health/allergy_intolerance_spec.rb
- spec/support/vcr_cassettes/rrd/lighthouse_allergy_intolerances_empty_fields.yml
We are seeing some allergy requests fail with `adapters/legacy_allergy_intolerance.rb:65:in 'recorder': undefined method '[]' for nil (NoMethodError)` ([datadog link](https://vagov.ddog-gov.com/logs?query=service%3Avets-api%20env%3Aeks-prod%20%40payload.controller%3A%28%22Mobile%3A%3AV0%3A%3AAllergyIntolerancesController%22%29%20%40http.status_code%3A500&agg_m=count&agg_m_source=base&agg_t=count&clustering_pattern_field_path=message&cols=host%2Cservice&fromUser=true&graphType=flamegraph&messageDisplay=inline&refresh_mode=sliding&sort=time&spanID=3507310816979748981&storage=hot&stream_sort=desc&viz=stream&from_ts=1742916718354&to_ts=1742931118354&live=true))
We investigated with @stephenBarrs and he was able to confirm that some results are returned from Lighthouse with a missing …
> Handle missing allergy fields gracefully

- lib/lighthouse/benefits_claims/service.rb
- spec/support/vcr_cassettes/lighthouse/benefits_claims/show/200_response.yml
Iteration on https://github.com/department-of-veterans-affairs/vets-api/pull/21009
The Evidence Request with the _actual_ display name `Employment info needed` was listed in Figma as `Employment information needed` and so our friendly-language override did not catch it. This remedies the problem.
> [CST] Changes display_name key for employment info Request

- lib/iam_ssoe_oauth/configuration.rb
- spec/lib/iam_ssoe_oauth/service_spec.rb
- Don't memoize `connection`. This only gets called once per instance so there is no benefit. The cert and key are loaded in the `connection.ssl` and leaked across tests causing intermittent failures: 
- <img width="828" alt="Screenshot 2025-03-27 at 9 02 44 AM" src="https://github.com/user-attachments/assets/a72d738b-abeb-4726-af0c-7f7daf92aa37" />
> Update iam_ssoe_oauth/service spec

- Gemfile.lock
- app/models/form_profiles/va_0873.rb
- config/form_profile_mappings/0873.yml
- modules/ask_va_api/app/lib/ask_va_api/base_retriever.rb
- modules/ask_va_api/app/lib/ask_va_api/inquiries/payload_builder/inquiry_payload.rb
- modules/ask_va_api/spec/app/lib/ask_va_api/inquiries/payload_builder/inquiry_payload_spec.rb
- modules/ask_va_api/spec/requests/ask_va_api/v0/inquiries_spec.rb
- spec/fixtures/pdf_fill/21P-0969/merge_fields.json
- spec/models/form_profile_spec.rb
- spec/models/form_profile_v2_spec.rb
This PR includes the following enhancements and updates:
• InquiryPayload Update
• Added your_location_of_residency to the SubmitterZipCodeOfResidency section to support more accurate residency mapping.
• BaseRetriever Error Handling
• Improved error handling logic in BaseRetriever for more consistent and resilient responses across retriever classes.
• VA0873 Personal Information Enhancement
• Added work_phone to the personal information payload.
• Pulled and normalized work_phone data using vet360_contact_info.
- [Ask VA Api: Fix Inquiries retriever bug](https://github.com/department-of-veterans-affairs/ask-va/issues/1707)
> BE | Ask va api: fix inquiries retriever bug

- modules/ivc_champva/app/models/ivc_champva/vha_10_10d.rb
- modules/ivc_champva/spec/models/vha_10_10d_spec.rb
This PR adds new properties to the 10-10d metadata object. For all applicant objects in the applicants array, we create a new `applicant_x` property that maps to a subset of applicant information. This is so that PEGA can use these metadata values to improve their search functionality after ingesting 10-10d submissions.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/105513
- Prior to this change we didn't include all applicants in the metadata
- To verify this change, run vets-api locally, add a byebug after this [line](https://github.com/department-of-veterans-affairs/vets-api/blob/8a338a0380c2893a8a6f96ef61703f6e26591799/modules/ivc_champva/app/controllers/ivc_champva/v1/uploads_controller.rb#L240), and submit a form with one attachment. When the breakpoint is …
> 105513 Add applicants to metadata - form 10-10d

- lib/kafka/schema_registry/service.rb
- spec/lib/kafka/schema_registry/service_spec.rb
- spec/support/vcr_cassettes/kafka/topics.yml
- spec/support/vcr_cassettes/kafka/topics404.yml
the base path in AWS url parameter had part of the path in it causing errors in dev environment. This corrects that. AWS parameter has already been updated.
https://github.com/orgs/department-of-veterans-affairs/projects/1509/views/5?pane=issue&itemId=102380453&issue=department-of-veterans-affairs%7CVES%7C4567 …
> fix pathing on kafka schema registry

- lib/periodic_jobs.rb
https://github.com/department-of-veterans-affairs/va.gov-team/issues/103173
This job needs to be reworked to not use a seqscan when checking for records that need rotating. Since another large-impact job collides with this KMS job, we're moving it 40 minutes forward to not overlap.
This alleviates pressure on our Postgres DB which was causing high latency query times.
> chore: Move KmsKeyRotation Job 40 minutes out

- lib/decision_review_v1/utilities/form_4142_processor.rb
This PR is an attempt to fix flakey pdf specs across vets-api. I saw in our [flakey specs doc](https://vfs.atlassian.net/wiki/spaces/BCP/pages/3797057551/Vets-API+Flakey+Specs) that some flakey tests were in the `modules/decision_reviews` directory, so I ran: `bin/test modules/decision_reviews  --parallel` and got a pdf error! When I took off the --parallel flag, all tests pass. This failed 4/9 times when I ran the test in parallel, but passed 10/10 times with this fix.
**Why?** 
In `lib/decision_review_v1/utilities/form_4142_processor.rb`, we had this code: 
```ruby
def initialize(form_data:, submission_id: nil)
...
@pdf_path = generate_stamp_pdf  # this method was using uuid before it was instantiated.
@uuid = SecureRandom.uuid
... …
```
> Pre-initialize and memoize UUID for form 4142 PDF naming

- config/features.yml
This PR removes the `champva_pdf_decrypt` flipper from features.yml. It is a follow-on to this [PR](https://github.com/department-of-veterans-affairs/vets-api/pull/21325) that removed all logic dependent on the flipper's presence.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/104641 …
> 104641d2 - Remove champva_pdf_decrypt flipper from features.yml - IVC CHAMPVA forms

- config/features.yml
- modules/accredited_representative_portal/app/controllers/accredited_representative_portal/application_controller.rb
- modules/accredited_representative_portal/app/controllers/accredited_representative_portal/v0/intent_to_file_controller.rb
- modules/accredited_representative_portal/app/policies/accredited_representative_portal/intent_to_file_policy.rb
- modules/accredited_representative_portal/config/routes.rb
- modules/accredited_representative_portal/spec/policies/accredited_representative_portal/intent_to_file_policy_spec.rb
- modules/accredited_representative_portal/spec/requests/accredited_representative_portal/v0/intent_to_file_spec.rb
- spec/support/vcr_cassettes/lighthouse/benefits_claims/intent_to_file/create_compensation_422_response.yml
- spec/support/vcr_cassettes/lighthouse/benefits_claims/intent_to_file/create_compensation_503_response.yml
- *This work is behind a feature toggle (flipper): YES/NO* Yes
Added endpoints to ARP portal to view and submit Intent to File requests
- *(If bug, how to reproduce)* feature
- *(What is the solution, why is this the solution?)* So that authorized reps can submit an intent to file on behalf of the vet/claimant
- *(Which team do you work for, does your team own the maintenance of this component?)* ARF/ART
- *(If introducing a flipper, what is the success criteria being targeted?)* existing flipper
- [101321](https://github.com/department-of-veterans-affairs/va.gov-team/issues/101321) …
> [ARP ITF] Intent to file (#103121)

- modules/mobile/app/controllers/mobile/v0/vet_verification_statuses_controller.rb
- modules/mobile/app/services/mobile/v0/veteran_verification/service.rb
Add mobile VetVerification Service:
- differentiates statsd + logging for tracking purposes
- load the new service in the mobile controller
- https://github.com/department-of-veterans-affairs/va-mobile-feature-support/issues/343
- https://github.com/department-of-veterans-affairs/va-mobile-feature-support/issues/344
- Prior to this change all logging was shared amongst the mobile + web apis
- Logs should now properly separate themselves to be more granular in datadog tracking
- Once deployed to staging we'll validate in the datadog logs there
None. This feature is still in the development stage for mobile and is completely quarantined off.
- DD Dashboards are WIP for this mobile feature
(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish …
> MFS: VetVerification Logging Differientiation 

- modules/representation_management/app/controllers/representation_management/v0/power_of_attorney_requests_controller.rb
- modules/representation_management/spec/services/power_of_attorney_request_service/orchestrate_spec.rb
What Changed
•	Removed the record_consent parameter from PowerOfAttorneyRequestsController.
•	Removed associated record_consent test data from orchestrate_spec.rb.
Why
•	record_consent is no longer used in the POA request flow and has been removed for clarity and maintainability.
•	Updated tests to reflect the change and ensure accurate validation coverage for existing fields like consent_limits.
Impact
•	No functional change in the current behavior.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/105522
https://github.com/department-of-veterans-affairs/vets-api/pull/21426 …
> ARM: Remove unused `record_consent` field from POA request handling

- .github/workflows/build.yml
The current process for tagging the vets-api image uses the commit sha for docker image builds and tagging for deployments. To allow more robust versioning, better ECR repo purge policies, and better awareness of code versions, we need to add semvers to the versioning pattern.
This PR adds the semver tag on the vets-api docker image when created and pushed to AWS ECR. 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/105668
> [!Note]
> Kickoff build.yaml workflow and ensure both tags are on the newly created image
> [!Note]
> Add screenshot here
Vets-api image creation and deployment
> chore(PE): Add semver tag to vets-api docker image

- modules/simple_forms_api/app/models/simple_forms_api/vba_21_4138.rb
- This work adds a name and email accessor for form 21-4138. This enables email delivery to the expected recipient email, specified by the user during the form submission process.
- To reproduce the bug, complete form 21-4138 and submit normally. The notification emails will always be delivered to the user's account email, regardless of what's specified in the form itself.
- I work for the Veteran Facing Forms team who owns this form
- [[Bug] 21-4138 emails are reverting to email address in Profile](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/2104)
- This work only affects form 21-4138 email deliveries
Any
> [SIMPLE-FORMS] fix: add name and email accessors for 4138

- spec/lib/sidekiq/form526_backup_submission_process/submit_spec.rb
- spec/support/disability_compensation_form/submissions/with_everything.json
- spec/support/disability_compensation_form/submissions/with_everything_toxic_exposure.json
va-gov-team issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/102017
Nests another cassette to handle the Form 526 generation.
Changes date formatting in the test data to comply with the schema validation.
> [CST]: Un-skip previously flaky test

- app/controllers/v0/disability_compensation_forms_controller.rb
- app/models/form526_submission.rb
- config/features.yml
- spec/requests/v0/disability_compensation_form_spec.rb
- add flipper flag `disability_compensation_temp_toxic_exposure_optional_dates_fix`
- add functionality to remove botched dates from SavedClaim creation in optional Toxic Exposure section
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/106340
- *Describe what the old behavior was prior to the change*: users would back out of Toxic Exposure sections with bad dates, thus failing the final transmission submission on SavedClaim creation - not passing validation
0. don't turn on the flipper flag yet
1. start a new form 526 submission
2. have at least 1 new …
> dbex/106340: [Toxic Exposure] Users are failing SavedClaim creation when exposure dates are incomplete, i.e. "XXXX-01-XX"

- app/controllers/concerns/exception_handling.rb
- app/models/form_attachment.rb
- lib/sentry_logging.rb
- lib/vets/shared_logging.rb
- modules/decision_reviews/app/controllers/decision_reviews/application_controller.rb
- modules/decision_reviews/spec/requests/v1/notice_of_disagreements_spec.rb
- modules/decision_reviews/spec/requests/v1/supplemental_claims_spec.rb
- modules/decision_reviews/spec/requests/v2/higher_level_reviews_spec.rb
- spec/controllers/application_controller_spec.rb
- spec/models/form_attachment_spec.rb
This is a spike showing one option for separating logging to Sentry and Rails in `vets-api`. A new module inside the `vets` folder has different methods for logging to Sentry and Rails, and an example of the new usage is shown in `form_attachment.rb`. If this path is chosen, `Vets::SharedLogging` would replace `SentryLogging` entirely.
Created a new module Vets::SharedLogging to replace SentryLogging. Using it only in ExceptionHandling, and as an example in `form_attachment.rb`
Decision Reviews. We own some of this code, but most is shared across teams.
- …
> Vets::SharedLogging example

- modules/claims_api/lib/claims_api/v1/poa_pdf_constructor/base.rb
- modules/claims_api/lib/claims_api/v2/poa_pdf_constructor/base.rb
- modules/claims_api/spec/lib/claims_api/shared_pdf_constructor_base_examples_spec.rb
Fixes consent checkboxes so that when no grants are put into the form data, NONE of the checkboxes in box 20 are filled. This will allow the widest range of disclosures possible rather than the buggy behavior of allowing next to no disclosure.
Behavior when a subset of grants are provided remains unchanged.
[API-45838](https://jira.devops.va.gov/browse/API-45838)
Power of Attorney form 21-22 (not 21-22a) pdf generation
> API-45838 Fix consent exemptions to check nothing when grants are blank

- modules/ivc_champva/app/form_mappings/vha_10_7959f_2.json.erb
This PR updates the JSON ERB mapping for form 10-7959f-2 so that it properly checks the payment selection box. Previously, the checkbox always defaulted to "provider" because the logic didn't actually compare the value properly.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/106517
- Old behavior: payment checkbox was always set to "provider" regardless of user input
- To verify locally, run vets-api/vets-website and submit a 10-7959f-2 form. Verify the resulting PDF has the proper payment checkbox selected.
| |Form input| PDF output|
|-|-|-|
|Payment to veteran|![Screenshot 2025-04-01 at 11 50 36](https://github.com/user-attachments/assets/71d53302-0a5e-471a-b6b5-c40b8200be58)|![Screenshot 2025-04-01 at 11 51 …
> 106517 - Update mapping to properly check payment box - form 10-7959f-2

- Gemfile
- Gemfile.lock
- rakelib/connectivity.rake
- Removes version on StatsD gem. 
- [PRs from vsp-infra-application-manifests](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pulls/stiehlrod)
- [Updates AWS param store](https://console.amazonaws-us-gov.com/systems-manager/parameters/%252Fdsva-vagov%252Fvets-api%252Fprod%252Fstatsd%252Fhost/description?region=us-gov-west-1&tab=Table#list_parameter_filters=Name:Contains:statsd)
- Alerted in #sign-in-experience channel: https://dsva.slack.com/archives/C078GBPDMGB/p1743616088961279
- [issue: 101229](https://github.com/department-of-veterans-affairs/va.gov-team/issues/101229)
modified:   Gemfile
modified:   Gemfile.lock
modified:   rakelib/connectivity.rake
> SRE-101229-update-statsD

- modules/ivc_champva/app/models/ivc_champva/ves_request.rb
- modules/ivc_champva/spec/services/ves_data_formatter_spec.rb
This PR changes the custom `to_hash` functions used inside the IVC CHAMPVA VES request class so that rather than requiring manual mapping of properties, we automatically create hashes that include all instance variables (which was the original intent).
- Adds new helper function to gather instance variables and convert to a hash (with keyname modifications)
- Sets all custom `to_hash` methods to use the new helper
- Updates relevant unit test
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/103456
- Prior to this change the hashes were created via a manual mapping, which was error prone. Now, we ensure that the hash accurately represents all instance variables in the sponsor, certifier, and beneficiary classes.
NA
The IVC CHAMPVA VES data formatter class
NA
> Update hashing method for ves request class - IVC CHAMPVA forms

- app/controllers/v0/caregivers_assistance_claims_controller.rb
- config/features.yml
- modules/facilities_api/app/services/facilities_api/v2/lighthouse/client.rb
- modules/facilities_api/spec/services/facilities_api/v2/lighthouse/client_spec.rb
- spec/requests/swagger_spec.rb
- spec/requests/v0/caregivers_assistance_claims_spec.rb
- When the facilities endpoint for the 10-10CG was added it used a V1 module to call the Lighthouse Facilities API, and since then we have learned a better one to use is the V2 module. They call the same Lighthouse Facilitiies API so the responses are pretty much the same.
- Added behind `caregiver_use_facilities_API_V2` toggle
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/101118
- *Describe the steps …
> [10-10CG] Update caregiver facilities endpoint to use v2 module

- lib/medical_records/client.rb
- spec/support/vcr_cassettes/mr_client/get_a_list_of_clinical_notes.yml
- The `type` param will no longer be supported for FHIR DocumentReference in MHV. Instead, we should be using the `category` param to get Notes.
> The CS&N endpoint has been modified to no longer accept the "type" parameter. Pass the "category" parameter instead.
> 
> Slack thread: https://dsva.slack.com/archives/C03Q2UQL1AS/p1743776062702289
> 
- Updated spec tests to account for the modified parameter list.
- Local testing to verify that Notes didn't work before the change, and did work after the change. This was verified at the level of the backend endpoint and at the application level
> MHV-69244 Switch Notes FHIR call to 'category' from 'type'

- config/features.yml
- modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb
- modules/simple_forms_api/spec/requests/simple_forms_api/v1/simple_forms_spec.rb
This PR removes two feature flags `simple_forms_email_confirmations` and `submission_pdf_s3_upload`, both of which are ENABLED in prod and staging. I believe we have no plans to disable to tweak them at all, at this point. One of them (probably the S3 one) was causing some test flakiness. I think just removing them outright is the cleanest solution.
https://dsva.slack.com/archives/C044AGZFG2W/p1743454383697389
> Remove two feature flags to make tests less flakey

- lib/periodic_jobs.rb
- Changes the frequency of 1095b form deletion to only happen once per day. This is being done because the old records have already been deleted. We can increase the rate again later if needed. Leaving as once per day for now.
https://github.com/department-of-veterans-affairs/va-iir/issues/1501
No testing needed for schedule frequency change.
How frequently this cron job runs.
> 1501: decrease frequency of 1095b form record deletion

- config/settings.yml
- config/settings/development.yml
- config/settings/test.yml
- modules/vaos/app/services/ccra/base_service.rb
- modules/vaos/spec/requests/vaos/v2/eps_appointments_spec.rb
- modules/vaos/spec/services/ccra/base_service_spec.rb
- modules/vaos/spec/services/ccra/referral_service_spec.rb
- modules/vaos/spec/services/concerns/token_authentication_spec.rb
- spec/support/vcr.rb
- spec/support/vcr_cassettes/vaos/concerns/token/token_200.yml
- spec/support/vcr_cassettes/vaos/concerns/token/token_400.yml
- Things have changes and the CCRA service needs to get a session token instead of the token authentication used by EPS.
- Refactored the code to use the SessionService for the CCRA session.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/106407
N/A
None. This service is still not being used.
> Use VAOS SessionService instead of Token Authenticator for CCRA service

- modules/ivc_champva/app/services/ivc_champva/ves_data_formatter.rb
- modules/ivc_champva/spec/services/ves_data_formatter_spec.rb
This PR updates the VES data formatter to ensure the sponsor `date_of_marriage` field is properly formatted for VES ingestion. Previously, this date field was in the format `MM-DD-YYYY`. After this change it will be in the form `YYYY-MM-DD`, as per VES requirements.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/106951
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-Backendexa …
> 106951 - Update date format for `date_of_marriage` field - form 10-10d

- Gemfile
- Gemfile.lock
This PR removes the pinned `statsd-instrument (= 3.9.8)` version from the Gemfile. Although the Gemfile was still pinned to 3.9.8, the lockfile had already been updated to 3.9.9 [from this manual change](https://github.com/department-of-veterans-affairs/vets-api/pull/21568). Removing the outdated pin ensures consistency between the Gemfile and lockfile going forward.
All Dependabot PRs were attempting to downgrade statsd-instrument back to 3.9.8 due to the pinned version in the Gemfile, despite the lockfile being on 3.9.9. This change resolves that …
> Update statsd-instrument pinned version

- .github/workflows/build.yml
The deployment conditional was using mixed syntax styles which can cause unexpected behavior.
Changed to use consistent expression format for the entire condition.
> fix(actions): Workflow condition syntax for deployment

- bin/prod
- config/environments/production.rb
This change adds support for running the Vets API in production mode locally:
1. Create `bin/prod` script to simplify running in production mode with all necessary    environment variables pre-configured
2. Modify production.rb to conditionally use local ActiveStorage when running locally    instead of requiring AWS S3 configuration
The `bin/prod` script provides a convenient way to start the server, console, or run commands in production mode while automatically setting all required environment variables, making it much easier to test and debug production-specific behavior.
Related
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/105950
- 📘 [Running Vets API in Production Mode Locally - Confluence](https://vfs.atlassian.net/wiki/spaces/PPT/pages/4013752339/Running+Ve …
> feat: enable running API in production mode locally

- modules/accredited_representative_portal/app/controllers/accredited_representative_portal/v0/power_of_attorney_requests_controller.rb
- modules/accredited_representative_portal/app/models/accredited_representative_portal/power_of_attorney_request.rb
- modules/accredited_representative_portal/app/services/accredited_representative_portal/power_of_attorney_request_service/params_schema.rb
- modules/accredited_representative_portal/spec/models/accredited_representative_portal/power_of_attorney_request_spec.rb
- modules/accredited_representative_portal/spec/requests/accredited_representative_portal/v0/power_of_attorney_requests_spec.rb
- modules/accredited_representative_portal/spec/services/accredited_representative_portal/power_of_attorney_request_service/params_schema_spec.rb
**Enhancements**
•	Introduced support for sorting PowerOfAttorneyRequest records via created_at and resolved_at.
•	Sorting supports both asc and desc orders with default fallback behavior.
•	Moved Statuses enum to the ParamsSchema module for better encapsulation and reuse.
**Controller Changes**
•	Refactored parameter validation and normalization to use ParamsSchema.
•	Applied sorting logic within poa_requests, falling back to default ordering when no sort param is provided.
•	Updated status filtering to reference ParamsSchema::Statuses.
**Model Updates**
•	Added .sorted_by scope to PowerOfAttorneyRequest with support for created_at and resolved_at sorting.
•	Improved decisioned scope to use a left outer join for broader resolution coverage.
**Specs**
•	Added model and request specs …
> Add Sorting and Status Filtering to PowerOfAttorneyRequestsController

- app/policies/mhv_messaging_policy.rb
- `mhv_messaging_policy.rb` was not checking for associations to VA treatment facilities before invoking SM Patient API `session` request. This resulted in mhv-sm-patient-api returning an error `code:105 - User was not found`
- adding a check for `user.va_patient?` before invoking a session since we know it will result in an error
- [MHV-69292](https://jira.devops.va.gov/browse/MHV-69292)
- https://dsva.slack.com/archives/C044WNQT4P9/p1743103113313749 …
> MHV-69292 SM: check for treatment facilities before invoking session request

- rakelib/prod/backfill_user_account_for_appeal_submissions.rake
- creates `rakelib/prod/backfill_user_account_for_appeal_submissions` Raketask; this task queries `AppealSubmission` records that do not have a `UserAccount` relation & uses their user_uuid to look up their ICN from `UserVerification` and `Account` records. Records that have ICNs that lead to a `UserAccount` have that account added to their submission record.
- https://jira.devops.va.gov/browse/VI-1104
- refactor PR https://github.com/department-of-veterans-affairs/vets-api/pull/21427
- Testing can be performed in a Rails console. To begin, monkey-patch the `spec/factories/appeal_submissions.rb` factory to disable the `stub_mpi` functionality:
```ruby
FactoryBot.define do
factory :appeal_submission do
user_uuid do
user = create(:user, :loa3, ssn: '212222112', stub_mpi: false)
user.uuid …
```
> [VI-1104] adds AppealSubmission user_account_id backfill raketask

- Dangerfile
Although the Dangerfile line length warning says that it ignores whitespace, it currently includes lines with whitespace-only changes in the count if the file has any non-whitespace line changes. That's because the filter to ignore whitespace changes is only applied to the `git diff` for the list of files, and not to the one for the file contents. This PR removes whitespace-only lines from the count.
- Manual runs of lines from the Dangerfile and the changed lines to confirm only desired lines are included in count
Example of issue from current PR https://github.com/department-of-veterans-affairs/vets-api/pull/21586
Actual non-whitespace diff of modules/income_and_assets/lib/income_and_assets/pdf_fill/forms/va21p0969.rb
CI
> Ignore whitespace in line count

- .github/workflows/build.yml
Resolves https://github.com/department-of-veterans-affairs/vets-api/security/code-scanning/894
Related: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/2342
> fix: remove vulnerable github.event.workflow_run.head_branch references

- config/identity_settings/environments/dev.yml
- temporarily turn off dev `mpi` mocking for `add_person_proxy` testing
> Temporarily turn off dev mpi mocking

- modules/ask_va_api/app/controllers/ask_va_api/application_controller.rb
- modules/ask_va_api/app/lib/ask_va_api/inquiries/creator.rb
- modules/ask_va_api/app/services/crm/service.rb
- modules/ask_va_api/spec/requests/ask_va_api/v0/inquiries_spec.rb
- `ApplicationController#handle_exceptions` now set status for "No Inquiries Found" to `:not_found`
- `ApplicationController#log_error` now logs user idme_uuid and logingov_uuid
- removed unused method from Inquiries::Creator
- update inquiries_spec for `:not_found` status
- Update Crm::Service#call rescue block for instance where original_body is not valid.
> BE | Ask VA Api: Update ApplicationController

- app/controllers/v0/dependents_applications_controller.rb
- Track the InProgressForm.created_at as form_start_date in order to track total time to submission for forms. 
- See [Burials](https://github.com/department-of-veterans-affairs/vets-api/blob/a530cc2b0a55e696a8be3ea4deb6a26f6bd1fce7/modules/burials/app/controllers/burials/v0/claims_controller.rb#L47) for an existing implementation of this pattern.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/107046
Dependents
> [Dependents] Populate the form_start_date

- config/features.yml
remove unused flippers
[PBP | Remove 'burialLocationOfDeath' feature toggle](https://github.com/department-of-veterans-affairs/va.gov-team/issues/104955)
[PBP | Remove 'pension_confirmation_update' feature toggle](https://github.com/department-of-veterans-affairs/va.gov-team/issues/105422)
[PBP | Remove 'burial_document_upload_update' feature toggle](https://github.com/department-of-veterans-affairs/va.gov-team/issues/105974)
https://github.com/department-of-veterans-affairs/vets-website/pull/35803
NA
pension and burial
> PBP Remove Unused Flippers

- rakelib/prod/backfill_user_account_for_appeal_submissions.rake
Fixes  a bug in the `UserAccount` creation process for `AppealSubmission` backfill raketask
- Original PR: https://github.com/department-of-veterans-affairs/vets-api/pull/21578
- https://jira.devops.va.gov/browse/VI-1104
- Testing can be performed in a Rails console. To begin, monkey-patch the `spec/factories/appeal_submissions.rb` factory to disable the `stub_mpi` functionality:
```ruby
FactoryBot.define do
factory :appeal_submission do
user_uuid do
user = create(:user, :loa3, ssn: '212222112', stub_mpi: false)
user.uuid
end
```
- Open a Rails console & create an appeal submission with a `user_uuid` that won't connect  to a `UserVerification`
```ruby
include FactoryBot::Syntax::Methods
appeal_submission = create(:appeal_submission)
user_uuid = appeal_submission.user_uuid
account = …
```
> [VI-1104] udpates AppealSubmission user_account backfill raketask

- modules/ask_va_api/app/controllers/ask_va_api/v0/inquiries_controller.rb
- modules/ask_va_api/app/lib/ask_va_api/attachments/retriever.rb
- modules/ask_va_api/app/lib/ask_va_api/inquiries/retriever.rb
- modules/ask_va_api/app/services/crm/service.rb
- modules/ask_va_api/spec/app/lib/ask_va_api/attachments/retriever_spec.rb
- modules/ask_va_api/spec/app/lib/ask_va_api/inquiries/retriever_spec.rb
- modules/ask_va_api/spec/services/crm/service_spec.rb
CRM Integration Enhancement: ICN Header Support + Retriever Improvements
This PR enhances how ICN (Integration Control Number) is handled across AskVA API requests to CRM. It ensures that all service calls include the `X-VA-ICN` header and improves the consistency and reliability of inquiry-related data retrieval.
- **CRM Service**: Adds `X-VA-ICN` to all outgoing headers for user identification in CRM logs and filtering.
- **InquiriesController**: Updated to pass ICN from the authenticated user into the retriever logic.
- **Inquiries::Retriever**: …
> BE | Ask VA Api: CRM Integration Enhancement: ICN Header Support + Retriever Improvements

- config/environments/development.rb
Redirects logs to STDOUT to prevent Foreman from eating request logs.
I also removed tagging (just in dev) which wasn't useful as it would display 'request_id' instead of the actual request ID value (same issue with correlation_id).
> fix: enable STDOUT logging for development environment

- app/mailers/direct_deposit_mailer.rb
- app/sidekiq/va_notify_dd_email_job.rb
- config/features.yml
- config/settings.yml
- config/settings/development.yml
- config/settings/test.yml
- spec/mailers/direct_deposit_mailer_spec.rb
- spec/sidekiq/va_notify_dd_email_job_spec.rb
- This work is behind a feature toggle (flipper): `only_use_direct_deposit_email_template`
We want to remove the EDU and C&P email templates. EDU template has had no triggers in the last 30 days and is safe to remove alongside all remaining mentions of the template. 
However, the C&P template is _still_ being triggered in VA Notify Production. We have decided to take the feature flag approach to smoothly ensure complete removal of the template and remaining mentions.
Team: Authenticated Experience
**Success criteria being targeted:**
When the flag is on, …
> Add feature flag to begin removal of EDU and C&P email templates #92636

- lib/evss/disability_compensation_form/form0781.rb
This change fixes a bug where the submission will error if data is not present, which happens in certain states of submission.
> Adding protection for nil vals

- modules/ask_va_api/app/lib/ask_va_api/inquiries/payload_builder/inquiry_payload.rb
- modules/ask_va_api/spec/app/lib/ask_va_api/inquiries/payload_builder/inquiry_payload_spec.rb
This PR updates `Inquiries::PayloadBuilder::InquiryPayload` to improve clarity around a reused ID and correct a small but critical typo affecting counselor data.
- 📝 **Added a comment** explaining why `UNAUTHENTICATE_ID` and `INQUIRY_SOURCE_AVA_ID` share the same value (`'722310000'`). This reflects intentional ID reuse from the upstream API, which assigns overlapping IDs across different fields.
- ✏️ **Fixed a typo** in the `counselor_info` method:
- Corrected `:their_vre_couselor` and `:your_vre_couselor` → `:their_vre_counselor` and `:your_vre_counselor`
- Ensures the correct keys are used when building the inquiry payload
- Prevents counselor data from being omitted or incorrectly mapped due to a misspelled key
- Improves code clarity around shared constant usage tied to external API …
> BE | Ask VA Api: Add note for shared constant IDs and fix counselor field fallback

- config/features.yml
- This change introduces a feature toggle that will be used for testing out FE Datadog logging of PDF generation events for the Veteran Status Card app.
- I work on the IIR Product team and we currently own Veteran Status Card.
- [1598](https://github.com/department-of-veterans-affairs/va-iir/issues/1598)
- This only introduces the feature toggle that will be used in future changes, so no tests at this time.
This only impacts the list of feature toggles available.
> Add feature toggle for logging Vet Status Card pdf download events

- modules/ask_va_api/app/controllers/ask_va_api/v0/inquiries_controller.rb
The following endpoints are temporarily shutdown for `production`:
- `GET /inquiries/:id` (`#show`)
- `GET /download_attachment` (`#download_attachment`)
To reduce exposure risk in production, especially related to potential IDOR and attachment handling vulnerabilities, access to these endpoints is now **restricted to lower environments only**.
- Added environment guards (`Settings.vsp_environment`) to both the `#show` and `#download_attachment` actions in `InquiriesController`
- Both endpoints will return a `403 Forbidden` response in production
- Remain accessible in **non-production environments** (e.g., dev, staging, sandbox)
When accessed in production, the following response is returned:
```json
{
"error": "This endpoint is not available in production."
}
```
**Low** – These changes …
> BE | Ask VA Api: Restrict /inquiries/:id and download_attachment endpoints to lower env

- app/controllers/v0/debts_controller.rb
- app/swagger/swagger/requests/debts.rb
- config/betamocks/services_config.yml
- lib/debt_management_center/debts_service.rb
- spec/lib/debt_management_center/debts_service_spec.rb
- spec/lib/debt_management_center/shared_examples/debt_service_examples.rb
- spec/support/vcr.rb
- spec/support/vcr_cassettes/debts/get_letters_count_only.yml
- *(Summarize the changes that have been made to the platform)*: Added an optional locator to the betamocks config for mocking responses for the new DMC count only query response
- *(What is the solution, why is this the solution?)* This allows for count_only in a way that doesn't call debt fetching functions on initialization.  Lazy loading debts when needed will decrease load on DMC servers.  Additionally we removed unused flipper logic,  and unused code.  This change is backwards compatible, so any functions referencing get_debts should not require updating.
- *(Which team do you work for, does your team own the maintenance of this component?)* Financial Management, we own this component
- *(If …
> 105866 debt request count only param

- lib/mdot/client.rb
- spec/lib/mdot/client_spec.rb
- spec/support/mdot_helpers.rb
We want to generate a new MDOT token if the current token expires instead of erroring out.
[106833](https://github.com/department-of-veterans-affairs/va.gov-team/issues/106833)
specs added
Supply Reorder Application, MDOT
When trying to submit a supply reorder with a dead token, attempt to generate a new token by getting supplies before throwing error.
> 106833 detect dead MDOT token and pull a new one

- app/models/form526_submission.rb
- rakelib/form526.rake
- spec/factories/form526_submissions.rb
- spec/lib/sidekiq/form526_backup_submission_process/processor_spec.rb
- spec/lib/sidekiq/form526_backup_submission_process/submit_spec.rb
- spec/lib/sidekiq/form526_job_status_tracker/job_tracker_spec.rb
- spec/models/form526_submission_spec.rb
- spec/requests/v0/disability_compensation_form_spec.rb
- spec/sidekiq/central_mail/submit_form4142_job_spec.rb
- spec/sidekiq/evss/disability_compensation_form/submit_form0781_spec.rb
- spec/sidekiq/evss/disability_compensation_form/submit_form526_all_claim_spec.rb
- spec/sidekiq/evss/disability_compensation_form/submit_uploads_spec.rb
- spec/support/vcr_cassettes/lighthouse/veteran_verification/disability_rating/200_Not_Connected_response.yml
- Updates `Form526Submission` model's `account` methods backup lookup behavior
- Past behavior for backup querying when `UserAccount` sourced ICN failed:
1. Use past submissions to find alternative `UserAccount` with an ICN
2. `user_uuid` lookups of `UserVerification` & `Account` records to find  an ICN
- Updated backup query behavior calls MPI for a profile with an ICN
1. first query made using EDIPI -  `auth_headers['va_eauth_dodedipnid']`
2. second query made using user name/DOB/SSN  as saved in submission auth_headers
- enforces a `UserAccount` association on `Form526Submission` records in validations
- updates `form526.rake` to rely on `UserAccount` over `Account` for ICN sourcing & adds similar MPI backup querying for ICN values
- https://jira.devops.va.gov/browse/VI-1104
- …
> [VI-1104] updates Form526 user_account lookup

- app/models/accredited_individual.rb
- app/models/accredited_organization.rb
- config/initializers/inflections.rb
- modules/representation_management/app/services/representation_management/gclaws/client.rb
- modules/representation_management/app/services/representation_management/gclaws/configuration.rb
- modules/representation_management/spec/models/representation_management/form_2122_digital_submission_spec.rb
- modules/representation_management/spec/services/representation_management/gclaws/client_spec.rb
- modules/representation_management/spec/services/representation_management/gclaws/configuration_spec.rb
- This pr adds a client and configuration for a GCLAWS integration
- the integration will be used in daily sidekiq jobs to fetch data on accredited entities and update records in the `accredited_individuals` and `accredited_organizations` tables
- This will allow us to start moving away from the daily and supplemental weekly excel file processing jobs
- This will allow the accredited representation teams to move away from the legacy `veteran_representatives` and `veteran_organizations` tables which are owned by LH and could block future LHDI migration
- This pr fixes some typos in the accredited rep space
- [105455](https://github.com/department-of-veterans-affairs/va.gov-team/issues/105455)
- A local connection to GCLAWS is not supported
- I used the ArgoCD staging rails console to make …
> 105455 add gclaws client

- rakelib/prod/backfill_user_account_for_async_transactions.rake
- creates `rakelib/prod/backfill_user_account_for_async_transactions` Raketask; this task queries `AsyncTransaction::Base` records that do not have a `UserAccount` relation & uses their user_uuid to look up their ICN via 
1. `UserVerification` records
2. `Account` records
3. MPI lookups
- Records that have connected `UserAccount`s will have them added as a relation; records that have an ICN but no `UserAccount` will have a new `UserAccount` created & added as a relation.
- https://jira.devops.va.gov/browse/VI-1105
- Testing can be performed in a Rails console
```ruby
include FactoryBot::Syntax::Methods
async_transaction = create(:async_transaction)
user_uuid = async_transaction.user_uuid
user_verification = UserVerification.find_by(idme_uuid: user_uuid) || create(:user_verification, …
```
> [VI-1105] adds user_account backfill raketask for AsyncTransaction::Base

- docker-compose.test.yml
This PR removes the `target: development` line from `docker-compose.test.yml`.
The `Dockerfile` does not define a build stage named `development`, which causes the following error when building locally:
```
failed to solve: target stage "development" could not be found
```
This issue only affects **local development**, where we rely on `docker compose`. Our GitHub Actions CI uses `docker/build-push-action` to build the image directly, without referencing the Compose file, so it doesn’t trigger this error.
Removing the target allows Docker to default to the final stage defined in the `Dockerfile`, which is sufficient for our test environment.
Run the following command:
```bash
docker compose -f docker-compose.test.yml build
```
The build should complete without errors where (a fresh build) …
> fix(docker): Compose test had undefined developemnt stage

- app/services/user_audit/appenders/audit_log_appender.rb
- spec/services/user_audit/appenders/audit_log_appender_spec.rb
- Fix typo in `AuditLogAppender`
- login with login.gov user and check if `Audit::Log` was created
`- or -`
- call UserAudit logger with a login.gov user_verification and check if `Audit::Log` was created
```ruby
user_verification = UserVerification.where.not(logingov_uuid: nil).last
UserAudit.logger.success(event: :sign_in, user_verification:)
```
UserAudit logger
> Fix audit_log_appender

- modules/ask_va_api/app/controllers/ask_va_api/application_controller.rb
- modules/ask_va_api/app/controllers/ask_va_api/v0/inquiries_controller.rb
- modules/ask_va_api/spec/requests/ask_va_api/v0/inquiries_spec.rb
This PR adds a `require_loa3!` before_action to ensure that only users with Level of Assurance 3 (LOA3) can access endpoints that rely on `current_user.icn`. This helps maintain strict access control and prevents LOA1 users from interacting with inquiries tied to sensitive identity data.
- Added `require_loa3!` to `InquiriesController`, excluding `unauth_create` and `status`
- Returns `401 Unauthorized` for users who are not LOA3
- Introduced `loa3_valid?` helper method for readability and reuse
- Created shared example to validate LOA3 protection across applicable endpoints
- [Validate that current_user is LOA3 before processing inquiries](https://github.com/department-of-veterans-affairs/ask-va/issues/1757)
> BE | Ask VA APi: add LOA3 validation for authenticated inquiry endpoints

- .github/CODEOWNERS
- config/initializers/console_filter_toggles.rb
This commit introduces a reveal! and conceal! mechanism within the Rails console.
It allows developers to temporarily remove and later restore filtered attributes
(e.g., passwords, tokens) for debugging purposes without permanently altering the
global configuration.
Related convo: https://dsva.slack.com/archives/CBU0KDSB1/p1734037958582009?thread_ts=1734029085.406129&cid=CBU0KDSB1
Old PR: https://github.com/department-of-veterans-affairs/vets-api/pull/19866
> feat(console): add commands to reveal/conceal attribute filters in console

- modules/ivc_champva/app/jobs/ivc_champva/ves_retry_failures_job.rb
- modules/ivc_champva/spec/jobs/ves_retry_failures_job_spec.rb
- Add nil filtering on database query, and nil check on processing db records
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/103461
- new unreleased feature
- CHAMPVA VES submissions for 10-10D
> add nil check to db query for failed ves records

- modules/vaos/app/services/vaos/v2/appointments_service.rb
- modules/vaos/spec/services/v2/appointment_service_spec.rb
- spec/support/vcr_cassettes/vaos/v2/mobile_facility_service/get_facilities_200_sort_by_recent_locations.yml
- This work is behind a feature toggle (flipper): YES, controlled by requests from vets-website gated by va_online_scheduling_recent_locations_filter
- We met with stakeholders and decided that for performance reasons, we are going to limit the past history to only appointments within the past year.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/106715
N/A
Appointments
> Update recent facilities look back logic

- modules/vaos/app/services/vaos/v2/appointments_service.rb
- modules/vaos/spec/services/v2/appointment_service_spec.rb
- This work is behind a feature toggle (flipper): YES, controlled by requests from vets-website gated by va_online_scheduling_fe_source_of_truth_modality
- Updating vets-api logic to match the logic in vets-website
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/107827
N/A
Appointments
> Update telehealth modality for vvskind nil

- config/settings.yml
- config/settings/development.yml
- Change CCRA to not be mocked in development.yml
N/A - this is to be able to run in review instances
N/A
N/A
N/A
> Change CCRA to not be mocked in development.yml

- config/features.yml
- lib/lighthouse/benefits_claims/constants.rb
- lib/lighthouse/benefits_claims/service.rb
- spec/controllers/v0/benefits_claims_controller_spec.rb
- spec/support/vcr_cassettes/lighthouse/benefits_claims/show/200_response.yml
Iterating on this one: https://github.com/department-of-veterans-affairs/vets-api/pull/21665
Changes include:
* One feature flipper, not two
* `friendlyDescription` is now `activityDescription`
* adds `shortDescription`
* override Proof Of Service to be 3rd party
- This work is behind a feature toggle (flipper): **YES**
- I am on **Benefits Management 2**
- The `: cst_friendly_evidence_requests ` flipper is back, consolidating the old `first-` and `third-` party flippers.
- [va.gov-team ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/106930)
> [CST] Friendly language consolidation & iteration

- .rubocop.yml
- modules/debts_api/lib/debts_api/v0/one_debt_letter_service.rb
- modules/vye/.rubocop.yml
- spec/sidekiq/education_form/create_daily_spool_files_spec.rb
- Switched from `require:` to `plugins:` in `.rubocop.yml` as per the plugin migration guide
- Updated deprecated cop namespaces:
- Metrics/LineLength → Layout/LineLength
- Rspec/NoExpectationExample → RSpec/NoExpectationExample
> chore(rubocop): migrate to plugin-based config and update deprecated cop names

- config/settings.yml
- config/settings/development.yml
- config/settings/test.yml
- modules/vaos/app/controllers/vaos/v2/eps_appointments_controller.rb
- modules/vaos/app/controllers/vaos/v2/referrals_controller.rb
- modules/vaos/app/services/ccra/referral_service.rb
- modules/vaos/spec/controllers/v2/referrals_controller_spec.rb
- modules/vaos/spec/requests/v2/referrals_spec.rb
- modules/vaos/spec/requests/vaos/v2/eps_appointments_spec.rb
- modules/vaos/spec/services/ccra/referral_service_spec.rb
- spec/support/vcr_cassettes/vaos/ccra/post_get_referral_error.yml
- spec/support/vcr_cassettes/vaos/ccra/post_get_referral_not_found.yml
- spec/support/vcr_cassettes/vaos/ccra/post_get_referral_success.yml
- spec/support/vcr_cassettes/vaos/ccra/post_get_referral_with_phone.yml
- spec/support/vcr_cassettes/vaos/ccra/post_referral_list_empty.yml
- spec/support/vcr_cassettes/vaos/ccra/post_referral_list_error.yml
- spec/support/vcr_cassettes/vaos/ccra/post_referral_list_success.yml
- **This work is behind a feature toggle (flipper):** YES
- **Summary of changes:** 
- Updated the `base_path` configuration for VAOS-related settings to use `/vaos/v1/patients` instead of `csp/healthshare/ccraint/rest`.
- Modified methods in the `ReferralService` to include the user's ICN in API requests.
- Updated controller actions to pass the `current_user.icn` when calling referral-related services.
- Refactored request specs and VCR cassettes to align with the new `base_path` and ICN requirements.
- **If bug, how to reproduce:** Not a bug; this is a feature enhancement.
- **What is the solution, why is this the solution?**
- This solution centralizes and simplifies the API paths while integrating user-specific data (ICN) into API calls for more personalized and accurate responses.
- …
> 108137 fix ccra config endpoints

- db/migrate/20250422190711_add_index_on_needs_kms_rotation_to_encrypted_models.rb
- db/schema.rb
This PR adds an index on `needs_kms_rotation`, which was added as a column in https://github.com/department-of-veterans-affairs/vets-api/pull/21806. Splitting this into it's own PR based on the recommendations in [the docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-database-migrations#vets-apidatabasemigrations-Indexes). 
- Previous PR: https://github.com/department-of-veterans-affairs/vets-api/pull/21806
- Issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/106336
Migration ran successfully locally.
```
== 20250422190711 AddIndexOnNeedsKmsRotationToEncryptedModels: migrated (2.4646s) 
```
There are 36 indexes being added, which matches the 36 tables getting that column in the last PR
`t.index ["needs_kms_rotation"]` 
I ran these …
> Add index on `needs_kms_rotation`

- lib/source_app_middleware.rb
This will fix the alerting monitor: [vets-api source app monitor - un-mapped source app detected](https://vagov.ddog-gov.com/monitors/200229?event_id=8073461996306547886&link_source=monitor_notif&live=1w)
Error:
```
Unrecognized value for HTTP_SOURCE_APP_NAME request header... [10-7959a]
```
Message in [#oncall](https://dsva.slack.com/archives/C30LCU8S3/p1745478700909819)
> Add 10-7959a to source_app_middleware

- app/controllers/v0/profile/direct_deposits_controller.rb
- spec/controllers/v0/profile/direct_deposits_controller_spec.rb
- spec/support/vcr_cassettes/lighthouse/direct_deposit/show/errors/502_update_response.yml
- We are adding explicit error logging in Direct Deposit for improved visibility and debugging in DataDog. These changes will allow DataDog to classify the log as an error instead of info - as it currently does
- MyVA & Profile Team
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/106004
N/A
- Before this change, all errors from our Direct Deposit endpoints would be logged/classified as info by DataDog
- We will be able to confirm these changes work as expected when exploring DataDog logs for Direct Deposit and there is a count greater than 0 for Errors category. Additionally, we will not see any red/error status codes under the info category.
None …
> 106004 Add error logging for direct deposit

- app/controllers/concerns/vet360/writeable.rb
- Bugfix PR for #21613 , correcting mismatch between String `type` passed in as an argument and the Symbol keys of the `PROFILE_AUDIT_LOG_TYPES` constant.
- https://jira.devops.va.gov/browse/VI-1136
- Testing of the `type` comparison can be done in a Rails console
```ruby
PROFILE_AUDIT_LOG_TYPES = { email: :update_email_address, address: :update_mailing_address, telephone: :update_phone_number }.with_indifferent_access.freeze
=> {"email"=>:update_email_address, "address"=>:update_mailing_address, "telephone"=>:update_phone_number}
type = 'email'
=> "email" 
PROFILE_AUDIT_LOG_TYPES[type].present?
=> true 
```
> [VI-1136] fixes string to symbol typo

- .github/CODEOWNERS
- app/models/form_profile.rb
- app/models/form_profiles/va_686c674.rb
- app/models/form_profiles/va_686c674v2.rb
- lib/pension_21p527ez/pension_military_information.rb
- modules/pensions/app/models/pensions/form_military_information.rb
- spec/models/form_profile_spec.rb
- spec/models/form_profile_v2_spec.rb
- spec/models/form_profiles/mdot_spec.rb
- Subsequent PR will update the other FormProfile related model
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/92440
Note: Some test required updates because of difference in hash keys (strings & symbols)
> Replace Virtus with Vets::Model - FormProfile

- spec/services/sign_in/token_response_generator_spec.rb
Since yesterday afternoon, this has been failing on `master` and on PRs with high frequency (~75% of the time). Identity is working on a fix, but this PR skips the tests until there is a fix. This will unblock developers.
https://dsva.slack.com/archives/CSFV4QTKN/p1745523620361109
Tests are being skipped on this branch:
```
rebeccatolmach ~/git/vets-api be rspec spec/services/sign_in/token_response_generator_spec.rb
.....
Finished in 0.62441 seconds (files took 16.55 seconds to load)
7 examples, 0 failures
```
On `master`:
```
9 examples, 0 failures
```
`spec/services/sign_in/token_response_generator_spec.rb`
> Skip flakey tests in token_response_generator_spec.rb

- db/migrate/20250312085108_create_bpds_submissions.rb
- db/migrate/20250312085126_create_bpds_submission_attempts.rb
- db/migrate/20250409194833_add_kms_encryption_key_to_submission_tables.rb
- db/migrate/20250409194908_add_failure_to_bpds_submission_status_enum.rb
- db/migrate/20250410151321_make_saved_claim_id_nullable_on_submissions.rb
- db/schema.rb
Reverts department-of-veterans-affairs/vets-api#21894
Eric and I figured out a fix, so we're applying it here.
error:
```
NameError: uninitialized constant AddFailureToBPDSSubmissionStatusEnum (NameError)
Object.const_get(camel_cased_word)
^^^^^^^^^^
Did you mean?  AddFailureToBpdsSubmissionStatusEnum
Caused by:
NameError: uninitialized constant AddFailureToBPDSSubmissionStatusEnum (NameError)
Object.const_get(camel_cased_word)
^^^^^^^^^^
Did you mean?  AddFailureToBpdsSubmissionStatusEnum
```
> Revert "Revert "added encrypted_kms_key to submission tables and added failure enum""

- app/models/form_profile.rb
Disabling PCIU calls to fill in phone numbers and email should be disabled when enabled the [remove_pciu](https://api.va.gov/flipper/features/remove_pciu) flipper. Previously, disabling PCIU calls were behind another flipper, remove_pciu_2. This was overlooked and PCIU calls should not be made when remove_pciu is enabled.
The `pciu_disabled?` private method eliminates the repetitive `Flipper.enabled?(:remove_pciu, user)` calls in FormProfile.
```
def pciu_disabled?
Flipper.enabled?(:remove_pciu, user)
end
```
FormProfile, #L351, `opt[:address] ||= …
> Disabled PCIU in form profile when remove_pciu is enabled

- config/features.yml
Adding feature flag `mhv_milestone_2_changes_enabled`
- department-of-veterans-affairs/va.gov-team#108087
Tested locally
> [108087] Add feature flag

- spec/requests/filter_parameter_logging_spec.rb
- spec/services/sign_in/token_response_generator_spec.rb
When these tests, specifically the line in the `before do` block:
```ruby
SemanticLogger.appenders.each { |appender| SemanticLogger.remove_appender(appender) }
```
runs before some other tests (`spec/services/sign_in/token_response_generator_spec.rb` and `spec/controllers/v1/sessions_controller_spec.rb`), it makes them fail with an error like this:
```
1) V1::SessionsController POST #saml_callback when user has level of assurance 1 after redirecting the client behaves like a successful UserAudit log creates a user action
Failure/Error: expect { call_endpoint }.to change(UserAction, :count).by(1)
expected `UserAction.count` to have changed by 1, but was changed by 0
Shared Example Group: "a successful UserAudit log" called from ./spec/controllers/v1/sessions_controller_spec.rb:719
```
This …
> skip entire filter_parameter_logging_spec

- modules/vaos/app/services/vaos/v2/appointments_service.rb
- modules/vaos/spec/requests/vaos/v2/appointments_spec.rb
- The VAOS service uses the required fallback logic for serviceName so friendly name is no longer required
- Appointments Team
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/108275
N/A
Appointments
> Remove clinic friendlyName field

- config/features.yml
- Removing a fully released feature toggle
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/105164
- N/A
N/A
Appointments
> Remove released feature va_online_scheduling_past_appt_date_range

- db/schema.rb
- The schema is out of date. Run migrations to fix schema. Reproducible on staging:
- schema on staging before migrations 
```ruby
create_table "bpds_submission_attempts", force: :cascade do |t|
t.datetime "created_at", null: false
t.datetime "updated_at", null: false
t.bigint "bpds_submission_id", null: false
t.jsonb "metadata_ciphertext", comment: "encrypted metadata sent with the submission"
t.jsonb "error_message_ciphertext", comment: "encrypted error message from the bpds submission"
t.jsonb "response_ciphertext", comment: "encrypted response from the bpds submission"
t.datetime "bpds_updated_at", comment: "timestamp of the last update from bpds"
t.string "bpds_id", comment: "ID of the submission in BPDS"
t.enum "status", default: "pending", enum_type: "bpds_submission_status"
t.text …
```
> Update out-of-date schema

- lib/vets/attributes.rb
- spec/lib/vets/attributes_spec.rb
- When an attribute is a Bool without a default, a false value will failed to be assigned and uses the default of nil
- This bug doesn't affect any existing attribute because all existing Bool attributes have a default value. 
- n/a
I don't love the way I fixed it, might refactor later
> Fix: Vets::Attribute Bool bug

- Gemfile.lock
- The backend updates the vets-json-schema version. The schema change is for pre-need-integration to remove the `na` option for sex
- https://github.com/department-of-veterans-affairs/vets-json-schema/pull/995
- https://github.com/department-of-veterans-affairs/vets-website/pull/35942
> MBMS-88525 Updated vets-api with new vets-json-schema version

- spec/requests/filter_parameter_logging_spec.rb
- Use `SemanticLogger::Test::CaptureLogEvents` to capture log output
> Fix filter_parameter_logging_spec

- rakelib/prod/backfill_user_account_for_form_email_matches_profile_logs.rake
- Backfill PR to enable [`user_uuid` refactor](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Products/user_uuid%20Refactor/user_uuid_refactor_faq.md).
- similar to earlier [`user_account` backfill PRs](https://github.com/department-of-veterans-affairs/vets-api/pull/21756)
- https://github.com/department-of-veterans-affairs/identity-documentation/issues/58
- Testing can be performed in a Rails console
```ruby
include FactoryBot::Syntax::Methods
user_uuid = UserVerification.last.idme_uuid || UserVerification.last.logingov_uuid
in_progress_form = create(:in_progress_form, user_uuid:)
form_email_log = FormEmailMatchesProfileLog.new(user_uuid:, in_progress_form_id: in_progress_form.id)
form_email_log.save! …
```
> [VI-1105] FormEmailMatchesProfileLog user_account_id backfill PR

- config/features.yml
- Removing fully released feature toggles
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/103684
- N/A
N/A
Appointments
> Remove unused appointments feature toggles - 1

- .github/workflows/yardoc.yml
Removing the `fetch-depth` option (default is 1) to avoid pulling all tags and branches every time the action runs. This should improve the speed of the `checkout` action and lead to a smaller system resource footprint for the runners
- department-of-veterans-affairs/va.gov-team/issues/108424
> Updating yardoc GHA to use a fetch-depth of 1

- app/services/form1010cg/auditor.rb
- app/services/form1010cg/service.rb
- app/sidekiq/form1010cg/submission_job.rb
- config/features.yml
- spec/services/form1010cg/auditor_spec.rb
- spec/services/form1010cg/service_spec.rb
- spec/sidekiq/form1010cg/submission_job_spec.rb
- *This work is behind a feature toggle (flipper): YES*: `hca_cg_request_duration_monitoring`
- Add StatsD duration measure metrics to 10-10CG calls from the frontend, and between the backend and CARMA/Mulesoft
- Health Enrollment 10-10EZ/CG
- criteria: no performance degradation or errors
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/101080
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featur …
> add statsd logging for CG query durations

- .github/CODEOWNERS
All form profiles are [not owned by govcio-vfep](https://github.com/department-of-veterans-affairs/vets-api/pull/21877#issuecomment-2840059855). I reached out to Holden and he said his team owns 2122.
none. found while on support.
> update form ownership for 2122

- db/migrate/20250428154055_create_sign_in_certificates.rb
- db/migrate/20250429014133_create_sign_in_config_certificates.rb
- db/schema.rb
- Create table for `SignIn::Certificate`
- https://github.com/department-of-veterans-affairs/identity-documentation/issues/103
- run migrations - `rails db:migrate`
Database
> [ID-103] - Add migration for creating sign_in_certificates table

- app/models/form_profiles/va_0873.rb
- app/models/form_profiles/va_0994.rb
- app/models/form_profiles/va_10203.rb
- app/models/form_profiles/va_1990s.rb
- app/models/form_profiles/va_686c674.rb
- app/models/form_profiles/va_686c674v2.rb
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/92440
Note: Some test required updates because of difference in hash keys (strings & symbols)
> Replace Virtus with Vets::Model - Form Profile 2

- app/controllers/v0/disability_compensation_in_progress_forms_controller.rb
- app/models/form_profiles/va_526ez.rb
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/92440
Note: Some test required updates because of difference in hash keys (strings & symbols)
> Replace Virtus with Vets::Model - Form Profile 526ez

- modules/my_health/app/controllers/my_health/v1/medical_records/self_entered_controller.rb
- modules/my_health/spec/requests/my_health/v1/medical_records/self_entered_spec.rb
- Made `SelfEnteredController` a direct child of `ApplicationController`, skipping `MrController` in the middle.
- A full policy for this behavior is not necessary; we instead just check for the necessary parameters and return `403` if they are not present.
- Users can have self-entered information _without_ an MHV Premium account, so we don't check for that.
> Acceptance criteria:
> 
> - AC1: A new policy is created for users who have a premium MHV account (double-check this) but do NOT have a VA treatment facility
> - AC2: SEI actions are moved to a controller that uses the new policy
> - AC3: If necessary, move SEI functions to a new client. Determine if the intended user will ALSO have an ICN. If so, no new client is necessary.
- The only functional change here is that the self …
> MHV-69698 Decouple SelfEnteredController from MrController

- modules/accredited_representative_portal/app/controllers/accredited_representative_portal/v0/power_of_attorney_requests_controller.rb
- modules/accredited_representative_portal/app/models/accredited_representative_portal/power_of_attorney_request.rb
- modules/accredited_representative_portal/lib/tasks/seed/staging_seed/methods.rb
- modules/accredited_representative_portal/spec/factories/power_of_attorney_request.rb
- modules/accredited_representative_portal/spec/requests/accredited_representative_portal/v0/power_of_attorney_requests_spec.rb
This PR addresses several issues identified in the Accredited Representative Portal's Power of Attorney (POA) requests endpoint and its corresponding RSpec tests:
1.  **Resolves Intermittent Spec Failures (`RecordNotUnique`):** Fixes intermittent `ActiveRecord::RecordNotUnique` errors related to the `veteran_organizations` table's unique `poa` index. The underlying cause appeared to be a conflict between explicit organization creation in the spec setup (`let(:other_vso)`) and implicit creation logic within the `:power_of_attorney_request` factory when called with a specific `poa_code`.
2.  **Fixes Spec Order Dependency Failure:** Corrects a test failure in the 'variety of poa request configurations' example. The test was previously failing because it used `eq` to assert a specific order …
> fix: Improve POA request spec stability and API consistency

- app/models/saved_claim.rb
- modules/burials/spec/models/burials/saved_claim_spec.rb
- spec/lib/lighthouse/benefits_documents/form526/upload_status_updater_spec.rb
- spec/models/saved_claim_spec.rb
- The overflow tracking method is producing errors for a large number of forms. Instead, we want to skip tracking when the form filler isn't implemented for a form. Since failures in tracking aren't significant errors, we also want to downgrade the logging to a warning. 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/108401
Saved Claims
> Skip tracking overflow for unregistered forms

- app/models/bgs_dependents/adult_child_attending_school.rb
- app/models/bgs_dependents/base.rb
- app/models/bgs_dependents/child.rb
- app/models/bgs_dependents/child_school.rb
- app/models/bgs_dependents/child_student.rb
- app/models/bgs_dependents/spouse.rb
- app/models/bgs_dependents/veteran.rb
- lib/bgs/children.rb
- Some changes from hash notation to dot notation were required
In this case, attributes where assigned via `self.attributes`, but that won't work correct with `Vets::Model` because it by-passes the code that deletes "Unknown Attributes" aka attributes not set up for the class.  
- https://github.com/department-of-veterans-affairs/va.gov-team/i …
> Replace Virtus with Vets::Model - BGS Dependents

- modules/simple_forms_api/spec/requests/simple_forms_api/v1/simple_forms_spec.rb
- spec/uploaders/evss_claim_document_uploader_spec.rb
In `simple_forms_spec.rb`: Skipping the tests in the `before do` block was creating lots of output when running the tests locally and in CI. Skipping this way removes the output. 
In `evss_claim_document_uploader_spec.rb`: We've seen a lot of this test failing since February (as noted in our flakey spec doc) and especially today, for some reason. 
```
1) EVSSClaimDocumentUploader#final_filename returns the right filename
Failure/Error: expect(uploader.final_filename).to eq('converted_image_TIF.jpg')
Expected "converted_image.TIF" to eq "converted_image_TIF.jpg".
```
I also changed the formatting of some skipped tests so we can easily find skipped tests in the future. 
None. Saw while on support. 
ran the tests locally and observed the spammy output was gone. 
specs
> Skip converted_image_TIF test and reformat other skipped tests

- modules/my_health/app/controllers/my_health/v1/medical_records/military_service_controller.rb
- modules/my_health/spec/requests/my_health/v1/medical_records/military_service_spec.rb
- Made `MilitaryServiceController` a direct child of `ApplicationController` bypassing `MrController` in the middle. Done to support work for the cartography team.
- A full policy is not needed here. Just return errors if the required parameters are not present.
> Acceptance criteria:
> 
> AC1: A new policy is created for users who have a premium MHV account (double-check this) but do NOT have a VA treatment facility – Work shared with [MHV-69698](https://jira.devops.va.gov/browse/MHV-69698)
> AC2: DoD history action is moved to a controller that uses the new policy
> AC3: Confirm that the intended users will have an EDIPI, as that's what we use to get DoD history
- The only functional change here is that the military service endpoint no longer requires the user to have a VA Treatment …
> MHV-69701 Decouple MilitaryServiceController from MrController

- app/sidekiq/evss/disability_compensation_form/submit_form0781.rb
Small logging improvement adding the submitted claim id (VBMS ID) to the log messages for 0781 generated PDFs
Related ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/108837
> Adding VBMS to 0781  log

- config/features.yml
- config/form_profile_mappings/10-10EZR.yml
- lib/hca/enrollment_eligibility/service.rb
- spec/fixtures/form1010_ezr/veteran_data.json
- spec/lib/hca/enrollment_eligibility/service_spec.rb
- spec/models/form_profile_spec.rb
Form 10-10EZR
Adds prefill data for a Veteran's contacts: Emergency Contact(s) and Next Of Kin(s)
- *This work is behind a feature toggle (flipper): YES* `ezr_prefill_contacts`
1. Adds Veteran contacts to `get_ezr_data` method
2. Adds `veteranContacts` to the 10-10EZR `FormProfile`:
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/104969
- Tests are written for when the flag is enabled and disabled
- QA will be performed in the staging environment
10-10EZR form
> EZR: Prefill Veteran contacts

- config/settings.yml
This PR updates the CRM API `auth_url` configuration for Ask VA to pull from an environment variable (`ask_va_api_crm_api_auth_url`) instead of hardcoding `https://login.microsoftonline.us`. 
By doing this, the `auth_url` is now managed via Parameter Store, allowing environment-specific configuration (e.g., staging/prod can each use the correct fwdproxy port). This improves flexibility and aligns with platform best practices for external service integrations.
- https://github.com/department-of-veterans-affairs/ask-va/issues/1809
- just update settings
> BE | Ask VA Api: link auth_url to parameter store

- .github/CODEOWNERS
- app/models/schema_contract/validation.rb
- app/models/schema_contract/validation_initiator.rb
- modules/vaos/spec/factories/vaos_users.rb
- spec/factories/schema_contract/validations.rb
- spec/models/schema_contract/validation_initiator_spec.rb
- updates `SchemaContract::Validation` to include a `user_account_id`
- part of the [`user_uuid` refactor](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Products/user_uuid%20Refactor/user_uuid_refactor_faq.md)
- followup PR to https://github.com/department-of-veterans-affairs/vets-api/pull/21936
- https://github.com/department-of-veterans-affairs/identity-documentation/issues/58
> [VI-1105] updates SchemaContract::Validation to use user_account_id

- modules/burials/app/models/burials/saved_claim.rb
- modules/burials/lib/burials/notification_email.rb
- modules/burials/spec/models/burials/saved_claim_spec.rb
- modules/income_and_assets/app/models/income_and_assets/saved_claim.rb
- modules/income_and_assets/spec/factories/income_and_assets/income_and_assets_claim.rb
- modules/income_and_assets/spec/models/income_and_assets/saved_claim_spec.rb
0969 was missing some key methods when it came to saved claims
- Update 0969 SavedClaim to add missing methods
- Update related spec file
- Found and fixed typo in `claimant` for Burial
- Updated tests as well
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/108753
> 108753: Fix up saved_claim.rb; fix typo in Burial

- app/controllers/v0/dependents_applications_controller.rb
- app/sidekiq/bgs/submit_form674_job.rb
- app/sidekiq/bgs/submit_form686c_job.rb
- app/sidekiq/lighthouse/benefits_intake/submit_central_form686c_job.rb
- spec/controllers/v0/dependents_applications_controller_spec.rb
- spec/sidekiq/bgs/submit_form674_job_spec.rb
- spec/sidekiq/bgs/submit_form686c_job_spec.rb
- spec/sidekiq/lighthouse/benefits_intake/submit_central_form686c_job_spec.rb
- This work sets up the code needed to implement submitted emails for Dependents and update received emails for Dependents. It's not yet called in the code - see https://github.com/department-of-veterans-affairs/vets-api/pull/22005 for full implementation. 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/97892
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/86710
For manual testing, turn on `dependents_separate_confirmation_email` and `dependents_submitted_email` flippers
Dependents
> Dependents Notification Emails

- config/features.yml
Removes the ```mhv_interstitial_enabled``` feature toggles as it is no longer being used
[Ticket](https://github.com/department-of-veterans-affairs/identity-documentation/issues/28)
> removes mhv interstital feature toggle

- app/models/sign_in/certificate.rb
- app/models/sign_in/client_config.rb
- app/models/sign_in/config_certificate.rb
- app/models/sign_in/service_account_config.rb
- spec/factories/sign_in/certificates.rb
- spec/factories/sign_in/client_configs.rb
- spec/factories/sign_in/config_certificates.rb
- spec/factories/sign_in/service_account_configs.rb
- spec/models/sign_in/certificate_spec.rb
- spec/models/sign_in/client_config_spec.rb
- spec/models/sign_in/config_certificate_spec.rb
- spec/models/sign_in/service_account_config_spec.rb
- Create models for tables: `sign_in_certificates` and `sign_in_config_certificates` and add associations to `SignIn::ClientConfig` and `SignIn::ServiceAccountConfig`
- Delegate attributes from `OpenSSL::X509::Certificate`
- After this is merged:
-  existing certificates will be backfilled
- PR with migrations to remove `certificates` columns from `ClientConfig` and `ServiceAccountConfig`
- PR to change `SignIn::Certificate#certs` association to `certificates`
- department-of-veterans-affairs/identity-documentation#103
- in rails console
```ruby
pem = File.read('spec/fixtures/sign_in/sample_client.crt')
config = SignIn::ClientConfig.last
certificate = config.certs.create(pem:)
certificate.not_before # => 2024-05-14 17:25:14 UTC
certificate.not_after  # => 2051-09-30 17:25:14 UTC …
```
> [ID-103] - Create and update models for sign-in certificates

- app/models/lighthouse_document.rb
- lib/lighthouse/benefits_documents/service.rb
- While investigating validation errors, I found that some of the uploads were failing because the filenames were uppercase, and our validation method was only looking for lowercase characters ([here](https://vagov.ddog-gov.com/apm/traces?query=env%3Aeks-prod%20operation_name%3Arack.request%20resource_name%3A%22Mobile%3A%3AV0%3A%3AClaimsAndAppealsController%23upload_document%22%20service%3Amobile-app&agg_m=count&agg_m_source=base&agg_t=count&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&fromUser=false&graphTyp …
> Downcase file extensions for validation

- app/models/evss_claim_document.rb
- app/models/lighthouse_document.rb
- lib/lighthouse/benefits_documents/configuration.rb
- spec/lib/lighthouse/benefits_documents/configuration_spec.rb
- spec/lib/lighthouse/benefits_documents/service_spec.rb
- spec/services/evss_claim_service_spec.rb
- Some changes from hash notation to dot notation were required
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/92439
> Replace Virtus with Vets::Model - Model Docs

- app/models/saved_claim.rb
- spec/models/saved_claim_spec.rb
- Cleanup from previous PRs to add new gem for validating json schemas for `SavedClaim`. We previously were passing a `clear_cache` flag to validate method for the old gem, and we no longer need to set it since we are not doing anything with the value in the new gem.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/109094 …
> [10-10CG] Remove clear_cache flag since new gem does not use it

- app/controllers/v0/terms_of_use_agreements_controller.rb
- app/models/user.rb
- app/services/identity/cerner_provisioner.rb
- app/services/login/after_login_actions.rb
- app/services/sign_in/user_loader.rb
- app/sidekiq/identity/cerner_provisioner_job.rb
- spec/controllers/v0/terms_of_use_agreements_controller_spec.rb
- spec/models/user_spec.rb
- spec/services/identity/cerner_provisioner_spec.rb
- spec/services/login/after_login_actions_spec.rb
- spec/services/sign_in/user_loader_spec.rb
- spec/sidekiq/identity/cerner_provisioner_job_spec.rb
- Create `Identity::CernerProvisionerJob` that is called during authentication
- https://github.com/department-of-veterans-affairs/identity-documentation/issues/16
- https://github.com/department-of-veterans-affairs/identity-documentation/issues/14
- https://github.com/department-of-veterans-affairs/vets-api/pull/21943 <- ⚠️ MERGE FIRST
- Login with SiS and SSOe and make sure a `Identity::CernerProvisionerJob` job is enqueued - http://localhost:3000/sidekiq/queues/default
Authentication, Cerner provisioning
> [ID-16] - Create cerner provisioner job and call during authentication

- modules/ivc_champva/lib/ves_api/client.rb
- modules/ivc_champva/spec/lib/ves_api_client_spec.rb
This PR updates the `submit_1010d` method of the `IvcChampva::VesApi::Client` class to return the http response from VES after submitting a successful request (previously just returned `nil` in the event of success)
- This work is behind a feature toggle
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/107624
- …
> Updated return value for `submit_1010d` to return http response on success - IVC CHAMPVA

- .devcontainer/devcontainer.json
- .devcontainer/on-create.sh
- .devcontainer/post-start.sh
----
There are 2 Problems in the current DevContainer Configurations that enable development on Github Codespaces and/or Local Macs (with Apple Silicon)
1. When creating a Codespace on Github, it doesn't clone the `vets-api-mockdata` repository due to permissions issue when the image is being built (bug)
2. The current way of installing Redis through linuxbrew doesn't work on Macs with ARM based CPUs. This fix will (hopefully) speed up the onboarding process for new developers.
---------
1. Remove Dependency on Homebrew which is not supported on ARM architectures. Instead install Redis via `apt` package manager.
2. Ensure that the `vets-api-mockdata` repository is properly cloned. 
- *This work is behind a feature toggle (flipper): YES/NO* : *
--*NO**
- *(Summarize the changes that have …
> Fix DevContainer Configuration for Apple Silicon Macs and Github Codespaces

- modules/claims_api/app/sidekiq/claims_api/one_off/poa_v1_bad_box20_render_report_job.rb
- modules/claims_api/spec/factories/claims_api_base_factory.rb
- modules/claims_api/spec/factories/power_of_attorney.rb
- modules/claims_api/spec/sidekiq/one_off/poa_v1_bad_box20_render_report_job_spec.rb
Will be manually run as a one-off job to report on the records that were generated incorrectly thanks to a 21-22 rendering bug that existed at the time.
- [API-46261](https://jira.devops.va.gov/browse/API-46261)
- [Discussion w/ Platform](https://dsva.slack.com/archives/CBU0KDSB1/p1746123587754949) on best approach to run this report
- Will roll out onto staging to run there as a test, then when confirmed will run on production.
* None - this is a backround job that builds an email report
> API-46261 Add one-off job to report bugged POA records

- config/settings.yml
- config/settings/development.yml
- config/settings/test.yml
- Adding the config value for pager duty integration for the travel pay application 
- N/A
- N/A, config value addition 
Maintenance windows
> Add travel_pay setting to maintenance services in settings.yml

- config/initializers/filter_parameter_logging.rb
- This PR adds `grant_type` to parameter allowlist, allowing us to group logs by this non-sensitive parameter value
> Adding grant_type to parameter allowlist

- lib/vets/collection.rb
- lib/vets/collections/cacheable.rb
- spec/lib/vets/collection_spec.rb
- spec/lib/vets/collections/cacheable_spec.rb
- spec/lib/vets/collections/finder_spec.rb
- Add Caching functionality to `Vets::Collection` via Cacheable concern
- Mimics `Common::Collection`
- There are differences between `Vets::Collection` and `Common::Collection`. Most are related to method naming. 
- Some alias are added to provided a better bridge between the two
- errors were added to `Vets::Collection`
- Vets::Collection _**does work**_ with Common::Models 
- removed .from_hashes because that's covered by the init method
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/102951
> Vets::Collection Caching

- config/features.yml
- Remove two feature toggles:
- `va_online_scheduling_clinic_filter `
- `va_online_scheduling_patient_history_future_appts `
- Appointments Team
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/104918
- N/A
N/A
Appointments
> Cleanup VAOS feature toggles

- lib/logging/base_monitor.rb
- lib/logging/benefits_intake/monitor.rb
- lib/logging/controller/monitor.rb
- spec/lib/logging/base_monitor_spec.rb
Add monitoring modules that make it easier for form modules to set up monitoring for claims and LightHouse sidekiq jobs
- Add controller monitor 
- Add benefits intake monitor
- Add base_monitor to include the other two and can be inherited in form modules
- Add spec
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/105776
Not used by anything yet
- https://github.com/department-of-veterans-affairs/vets-api/pull/21848 will be the first for module to use it
> 105776: Add new platform monitoring logic

- modules/mobile/app/controllers/mobile/v1/labs_and_tests_controller.rb
- modules/mobile/spec/requests/mobile/v1/health/labs_and_tests_spec.rb
Just a small update to wrap response with `data:` per JSON:API spec
- existing tests were updated as needed 
- response from the `GET /mobile/v1/health/labs-and-tests` endpoint would be an array of data, now the response is like: `{data:[<data objects>]`
- *Describe the steps required to verify your changes are working as expected. 
- Mobile API endpoint for labs and tests
> restructure mobile labs and tests response format to include data object wrapper

- modules/pensions/lib/pensions/pdf_fill/constants.rb
- modules/pensions/lib/pensions/pdf_fill/va21p527ez.rb
Moving constants defined in the `va21p527ez.rb` pdf mapping file into their own file to improve the organization of the module
- department-of-veterans-affairs/va.gov-team/issues/109164
There aren't any functional changes, as long as tests continue to pass all is well
- *What is …
> [Pensions] Moving constants into a separate file

- app/sidekiq/lighthouse/evidence_submissions/document_upload.rb
- Lighthouse::EvidenceSubmissions::DocumentUpload retry job still have bad arguments from a previous PR
- file_obj needs to be deleted for the job to run correctly because file_obj doesn't work with serialization
[Slack thread](https://dsva.slack.com/archives/C04KHCT3ZMY/p1746713446248649?thread_ts=1746552735.655099&cid=C04KHCT3ZMY)
> remove file_obj from doc hash in doc upload job

- config/betamocks/services_config.yml
- modules/vaos/app/exceptions/vaos/exceptions/configuration_error.rb
- modules/vaos/app/services/ccra/referral_service.rb
- modules/vaos/app/services/common/jwt_wrapper.rb
- modules/vaos/app/services/vaos/referral_encryption_service.rb
- modules/vaos/spec/services/common/jwt_wrapper_spec.rb
- modules/vaos/spec/services/vaos/referral_encryption_service_spec.rb
- Hide VAOS referral controller encryption exception from response. The exception is still logged. Also update betamocks.
New sample response:
```
{
"errors": [
{
"title": "Service Configuration Error",
"detail": "The VAOS service is unavailable due to a configuration issue",
"code": "VAOS_CONFIG_ERROR",
"source": "VAOS",
"status": "503"
}
]
}
```
https://github.com/department-of-veterans-affairs/va.gov-team/issues/107224 …
> Hide VAOS referral controller encryption exception from response

- db/migrate/20250506172106_add_needs_kms_rotation_fields_to_submissions_tables.rb
- db/migrate/20250507151848_add_needs_kms_rotation_indices_to_submission_tables.rb
- db/schema.rb
- This schema change is a follow up PR that re-adds the encryption rotation fields back to the new submissions and attempts tables. The migrations for this schema change already exist here: `20250421190417_add_needs_kms_rotation_to_encrypted_models.rb` and `20250422190711_add_index_on_needs_kms_rotation_to_encrypted_models.rb`.
- Pension and Burial program team to own this change.
- [*Link to ticket created in va.gov-team repo*](https://github.com/department-of-veterans-affairs/va.gov-team/issues/105115)
- *Link to previous change of the code/bug (if applicable)*: https://github.com/department-of-veterans-affairs/vets-api/pull/21655
- *Describe the steps required to verify …
> Add encryption rotation fields and indices to submission and attempt tables

- config/features.yml
This PR adds two new feature flags as part of the DS Logon credential deprecation work
- `dslogon_interstitial_redirect` - Controls when DS Logon users are redirected to interstitial page
- `dslogon_button_disabled` - Controls when the DS Logon button is displayed on sign-in pages
- https://github.com/department-of-veterans-affairs/identity-documentation#143
Manual testing
n/a
This will only impact the Flipper and feature_toggles endpoint
> adds dslogon deprecation feature flags

- config/features.yml
- lib/mail_automation/client.rb
- spec/lib/mail_automation/client_spec.rb
- This fixes a long-standing bug that omitted 526 uploads when notifying MAS of new 526 submissions. Motivated by this fix, we now also include 526 ancillary forms (4142 and 0781) in the MAS notification.
- I am part of the Employee Experience team working with DBEX team
- Success criteria for Flipper flag: confirmation from MAS team that they're receiving 526 uploads and ancillaries.
- https://github.com/department-of-veterans-affairs/abd-vro/issues/4285
- Old behavior: only 526 form data was included in MAS call
- New behavior: 526 uploads, and ancillary 4142 and 0781 forms, are included in MAS call
- Testing plan for rolling out the feature: Work with MAS team to confirm that they're receiving …
> Fix and expand sending Form 526 ancillary data to MAS API

- app/models/health_care_application.rb
- lib/kafka/concerns/kafka.rb
- spec/lib/kafka/concerns/kafka_spec.rb
Some clean up of the kafka code. Removes redaction of icn on non prod env and rescue all icn lookup errors not just validation errors
https://github.com/orgs/department-of-veterans-affairs/projects/1509/views/1?pane=issue&itemId=108934925&issue=department-of-veterans-affairs%7CVES%7C4827 …
> Kafka - don't redact icn on staging and rescue all icn lookup errors

- app/controllers/concerns/vet360/writeable.rb
- lib/va_profile/models/v3/address.rb
- lib/va_profile/models/v3/base_address.rb
- spec/factories/va_profile/v3/addresses.rb
- spec/support/vcr_cassettes/va_profile/v2/contact_information/put_address_override.yml
- spec/support/vcr_cassettes/va_profile/v2/contact_information/put_address_success.yml
Removed validation_key attribute from VAProfile::Models::V3::Address. The validation_key does not need to be saved to the address object, the validation_key only needs to be returned in the AddressResponse for UI purposes. This [ticket](department-of-veterans-affairs/va.gov-team/issues/109399) was created to fix this in the UI after ContactInformationV2.
- department-of-veterans-affairs/va.gov-team/issues/109399
- *Describe what the old behavior was prior to the change* Returning validation_key in the V3 …
> Removed validation_key attribute from VAProfile::Models::V3::Address

- modules/my_health/app/controllers/my_health/apidocs_controller.rb
- My Health apidocs controller fix
- `apidocs_controller.rb` was throwing the following error: `"exception":"Tried to load unspecified class: Time","backtrace"`. It occurred probably because YAML.safe_load was used to load the YAML file, and it did not allow deserialization of `Time` by default. Explicitly permitting the Time class when calling `YAML.safe_load`.
- 
- ![image](https://github.com/user-attachments/assets/ab820b80-ff1f-4990-86cb-b4ab7d39cba0)
- [MHV-71249](https://jira.devops.va.gov/browse/MHV-71249)
- tested by calling …
> MHV-71249: My Health apidocs controller fix

- app/sidekiq/lighthouse/evidence_submissions/document_upload.rb
- app/sidekiq/lighthouse/evidence_submissions/failure_notification_email_job.rb
- spec/sidekiq/lighthouse/evidence_submissions/document_upload_spec.rb
- spec/sidekiq/lighthouse/evidence_submissions/failure_notification_email_job_spec.rb
- This work is behind a feature toggle (flipper): **NO**
- The metric `silent_failure_avoided_no_confirmation` is no longer necessary since CST now uses a VA Notify callback for confirmation of failure notification email delivery. [This callback](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/sidekiq/lighthouse/evidence_submissions/va_notify_email_status_callback.rb#L40) increments `silent_failure_avoided` / `silent_failure` according to the email delivery status. 
- Team: Benefits Management Tools
This removes a superfluous Datadog metric from …
> Remove silent_failure_avoided_no_confirmation for failed CST uploads

- modules/claims_api/app/sidekiq/claims_api/one_off/poa_v1_bad_box20_render_report_job.rb
- modules/claims_api/spec/sidekiq/one_off/poa_v1_bad_box20_render_report_job_spec.rb
Support suggested I try using the builder class to do the email delivery instead of invoking ApplicationMailer directly. With nothing else to go on for why this particular email isn't sending out, it can't hurt to try!
- #22044
- [Support thread](https://dsva.slack.com/archives/CBU0KDSB1/p1746813703362399)
Async one-off job. Nothing veteran facing.
> API-46261 Use more standard Mailer class for report

- modules/my_health/app/controllers/concerns/my_health/aal_client_concerns.rb
- modules/my_health/app/controllers/my_health/v1/health_records_controller.rb
- modules/my_health/app/controllers/my_health/v1/medical_records/self_entered_controller.rb
- modules/my_health/spec/requests/my_health/v1/medical_records/self_entered_spec.rb
- Added AAL logging to Self-Entered (only to the unified call)
- Refactored some common code into `AALClientConcerns`
> Implement required AAL entry for Self-entered download
> 
> 
> 
> 
> AAL work to be done spreadsheet link below (See Medical Records tab-line 43- dark tan highlight)
> 
> https://dvagov.sharepoint.com/:x:/r/sites/HealthApartment/_layouts/15/Doc.aspx?sourcedoc=%7B80534FA8-97C2-4726-9E08-20166C9609DF%7D&file=AAL%20work%20to%20be%20done-VHA%20Privacy%20Office%20additions.xlsx&action=default&mobileredirect=true 
> 
> Approved content for all MR domains on va.gov is as follows:
> 
> Date/Time = Completion_Time
> 
> Activity Details = Detail_Value
> 
> Activity = Activity_Type
> 
> Action = Action
> 
> Performer Type = Performer_Type
> 
> Results = Status
> 
> Figma Link: N/A …
> MHV-69302 Added AAL to SEI action; refactored AAL code

- app/controllers/concerns/authentication_and_sso_concerns.rb
- app/controllers/v1/sessions_controller.rb
- app/models/user.rb
- spec/controllers/v1/sessions_controller_spec.rb
- spec/models/user_spec.rb
- After a user logs in with ssoe check if they are cerner eligible and set `true` or `false`
- When a user starts the ssoe login flow it will check if that cookie exists:
- doesn't exist - log `unknown`
- exists - log cookie value (`true` or `false`)
- https://github.com/department-of-veterans-affairs/identity-documentation/issues/118
- Log in with ssoe with a `loa3` user that has a `cerner_id` (`user+81`)
- initially you should see a log like:
```ruby
[SessionsController] Cerner Eligibility -- { :eligible => :unknown, :cookie_action => :not_found }
```
- after you login you should see a log like:
```ruby
[SessionsController] Cerner Eligibility -- { :eligible => true, :cookie_action => :set, icn: <icn> }
```
- You should also have a `CERNER_ELIGIBILTY` cookie set.
- Log out
- Start ssoe …
> [ID-118] - Create and check cerner eligibility cookie

- lib/vets/attributes.rb
- lib/vets/collection.rb
- lib/vets/collections/cacheable.rb
- lib/vets/collections/finder.rb
- lib/vets/collections/pagination.rb
- lib/vets/type/utc_time.rb
- spec/lib/vets/collection_spec.rb
- spec/lib/vets/collections/finder_spec.rb
- spec/lib/vets/collections/pagination_spec.rb
- This PR allows Common::Collection and Vets::Collection to be used more interchangeable 
- This PR also helps reduce the size of https://github.com/department-of-veterans-affairs/vets-api/pull/21991
- Updates include:
- Aliasing methods
- Matching sorting metadata output
- Pagination errors
- Edge case String coercion 
- n/a
> Vets::Collection updates to match Common::Collection

- config/settings.yml
- config/settings/development.yml
- config/settings/test.yml
- The GCLAWS team added a `Origin` header requirement to their api key provisioning. We need to add that to the client class Faraday request headers to get working api calls. This pr adds the expected origin as a secret.
- [105455](https://github.com/department-of-veterans-affairs/va.gov-team/issues/105455)
> [105455] Add gclaws origin secret

- bin/local-openresty
- docs/setup/local-openresty.md
- docs/setup/local-traefik.md
Adds a new bin/local-openresty script and documentation for running OpenResty as a reverse proxy for the Vets API. This allows developers to test using OpenResty either directly to the API or as part of a multi-tier proxy setup with Traefik.
- Create bin/local-openresty script with support for auto-detecting Traefik
- Add comprehensive docs at docs/setup/local-openresty.md with examples and configuration details
- Update local-traefik.md with guidance on using Traefik and OpenResty together
- Default to using port 8081 for Traefik when running both proxies together
This setup helps debug issues only occurring in prod.
> feat(dev): add local-openresty script for reverse proxy setup

- app/services/bgs/payment_service.rb
Iteration on this previous PR: https://github.com/department-of-veterans-affairs/vets-api/pull/21906
This fixes an issue caught in Sentry.
Slack discussion here: https://dsva.slack.com/archives/CBU0KDSB1/p1746810044798179
Sentry here: https://sentry.vfs.va.gov/organizations/vsp/issues/334865/?environment=production&project=3&query=is%3Aunresolved&statsPeriod=14d
I have since disabled the two feature flippers, so the error is no longer happening. I will re-enable them when this PR goes out.
The actual fix is simple, `Array.wrap` the provided response before performing `.select` and `.each` on it in a manner that assumes it is an array. [The payment history adapter](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/adapters/payment_history_adapter.rb#L14) …
> [Payments] Payment data may not be an array, so wrap before iterating

- app/models/in_progress_form.rb
- app/sidekiq/hca/log_email_diff_job.rb
- spec/factories/in_progress_forms/in_progress_forms.rb
- spec/lib/lighthouse/benefits_claims/intent_to_file/monitor_spec.rb
- spec/requests/v0/in_progress_forms_controller_spec.rb
- spec/sidekiq/hca/log_email_diff_job_spec.rb
- updates `InProgressForm` `log_hca_email_diff` method to include the form's `user_account_id`, this is then passed to the saved `FormEmailMatchesProfileLog` record created as part of the `HCA::LogEmailDiffJob`
- https://github.com/department-of-veterans-affairs/identity-documentation/issues/58
-[ Backfill rake task](https://github.com/department-of-veterans-affairs/vets-api/pull/21875) for `FormEmailoMatchesProfileLog` records that don't have a `user_account_id`
- Make an (authenticated) request to create/update a 1010ez `InProgressForm`
```curl
curl --location --request PUT 'http://localhost:3000/v0/in_progress_forms/1010ez' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer ....'
--data '{ "form_data": { "some-form-key": "some-form-data" } }'
```
- A …
> [VI-1105] adds user_account_id to FormEmailMatchesProfileLog

- modules/claims_api/app/sidekiq/claims_api/one_off/poa_v1_bad_box20_render_report_job.rb
- modules/claims_api/spec/sidekiq/one_off/poa_v1_bad_box20_render_report_job_spec.rb
It's suspected that the original email of all 2077 records was too large to send through the mail system. Manual testing showed that ~100 made it through fine, so this will send an email for each week of records in the date range.
See #22044 
> Would try to send one big email at the end of filtering through the records
- How to test
> `ClaimsApi::OneOff::PoaV1BadBox20RenderReportJob.perform_async('<consumer_id>', %w[<va emails>], '<start date in YYYY-MM-DD format>', '<finish date in YYYY-MM-DD format>').`
Reporting job. Nothing veteran facing or modifying of data.
> API-46261 Send emails in batches too

- app/policies/lighthouse_policy.rb
- spec/policies/lighthouse_policy_spec.rb
- This change removes the check for `participant_id` from the endpoint policy. This is being done after doing some research and logging for about 3 weeks any failure of the policy, which showed out of 4,250 failures, all of them were missing a participant_id. participant_id is not needed for the data retrieval and there does not seem to be any reason to keep the check.
- I work on the IIR Product team and we currently own Veteran Status Card.
- [1655](https://github.com/department-of-veterans-affairs/va-iir/issues/1655)
- Prior to the change, the policy checked for both ICN and participant_id. Now it just checks for ICN.
This only impacts the auth policy for the Vet Verification Status endpoint which is only used by …
> Remove participant_id from auth policy

- config/settings.yml
- config/settings/development.yml
- config/settings/test.yml
- Adds settings entries for VANotify poller to production configuration file.
- Note that corresponding entries have been made in AWS parameter store to populate the values for the added settings:
/dsva-vagov/vets-api/prod/env_vars/claims_api/vanotify/services/lighthouse/notify_service_id
/dsva-vagov/vets-api/prod/env_vars/claims_api/vanotify/services/lighthouse/notification_client_secret
[API-45733](https://jira.devops.va.gov/browse/API-45733)
- VANotify polling is currently failing with auth errors in production, so once these settings are deployed we should no longer see these errors.
VANotifyFollowUpJob configuration
> API-45733 Add-VANotify-settings

- .github/workflows/settings_checks.yml
- Settings Check runs on master, but only work when there's a code difference between master
- It would be inefficient to re-check all parameters on all PRs so instead we're option to not run on master
- The bug is not blocking merging or deploying
- n/a
> Bug: Remove master branch from Settings Check runs

- config/features.yml
- Removes a feature flag that is no longer needed. References to it have already been removed from the front end. 
https://github.com/department-of-veterans-affairs/va-iir/issues/1588
Specs still pass.
Removes a feature flag that is no longer in use on the front end. It's also not used on the back end.
> 1588: remove show_digital_form_1095b feature flag

- modules/claims_api/app/services/claims_api/slack/failed_submissions_messenger.rb
- modules/claims_api/spec/services/failed_submissions_messenger_spec.rb
TIDs could be filled with things not very ID-like, so this whitelists what we link to in DataDog.
* [API-44632](https://jira.devops.va.gov/browse/API-44632)
* #21094
* ClaimsAPI alerting, nothing consumer/veteran facing.
> Only show TIDs if whitelisted

- modules/claims_api/app/sidekiq/claims_api/va_notify_accepted_job.rb
- modules/claims_api/app/sidekiq/claims_api/va_notify_follow_up_job.rb
- modules/claims_api/spec/sidekiq/va_notify_accepted_job_spec.rb
- modules/claims_api/spec/sidekiq/va_notify_follow_up_job_spec.rb
- Updates VANotifyFollowUpJob so that it sets the status of the CLAIMANT_NOTIFICATION step of POA submissions.
[API-45553](https://jira.devops.va.gov/browse/API-45553)
- Formerly the VANotifyAcceptedJob set the status of the CLAIMANT_NOTIFICATION to "SUCCESS" after kicking of the asynchronous call to send the VANotify email.
- VANotifyAcceptedJob now sets the step status to "IN_PROGRESS", and the VANotifyFollowUpJob sets the step status to the correct mapped status value based on the status returned from VANotify for the email job.
- POA v2 submissions notification step.
- VANotifyFollowUpJob
> API-45553 - POA v2 - Update CLAIMANT_NOTIFICATION status

- .github/workflows/code_checks.yml
When the `pdf-forms` gem encounters an error filling a form PDF via `pdftk`, it saves the failed form data in an FDF file in the system temp directory (OS/System dependent, but for the Github runners it defaults to `/tmp`). It's not currently possible to configure `pdf-forms` to tell it where to save the FDF files, so I am setting the `TMPDIR` environment variable to `tmp/systmp` so that I can save the files there (rubys Tempfile library uses `TMPDIR` to determine which directory to store files in). These files are then uploaded as artifacts when there is a spec failure …
> Testing uploading new artifacts

- modules/my_health/app/controllers/my_health/v1/medical_records/military_service_controller.rb
- modules/my_health/spec/requests/my_health/v1/medical_records/military_service_spec.rb
- Added an AAL entry for accessing military service
- Added a `bb` param to indicate that this is being pulled as part of a Blue Button report, in which case we do NOT create an AAL entry
- Corresponding FE PR: https://github.com/department-of-veterans-affairs/vets-website/pull/36494
> Implement DOD report AAL entry-pass a parameter to the BackEnd that indicates AAL needed 
> 
> This is a new report being implemented.  Once the report functionality is complete, this AAL will need to be added.
> 
> AAL work to be done spreadsheet link below (See Medical Records tab-line 42, red highlighted line item)
> 
> https://dvagov.sharepoint.com/:x:/r/sites/HealthApartment/_layouts/15/Doc.aspx?sourcedoc=%7B80534FA8-97C2-4726-9E08-20166C9609DF%7D&file=AAL%20work%20to%20be%20done-VHA%20Privacy%20Office% …
> MHV-71086 Added AAL logging for military service

- docs/setup/docker.md
- docs/setup/running_docker.md
- Move some clamav config to docker setup 
- Updated clamav code sample
- Did not include any binstub info on base setup
Corresponding confluence page (to become the only developer doc related in setup:
https://vfs.atlassian.net/wiki/spaces/PWD/pages/4091052094/Copy+of+Developer+Setup
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/101709
> Setup Doc Consolidation

- modules/accredited_representative_portal/app/controllers/accredited_representative_portal/v0/representative_users_controller.rb
- modules/accredited_representative_portal/spec/requests/accredited_representative_portal/v0/user_spec.rb
This commit updates the `RepresentativeUsersController` within the Accredited Representative Portal to include the current user's Level of Assurance (LOA) in the API response.
The `loa` attribute is now part of the user object returned by the `/accredited_representative_portal/v0/user` endpoint.
The corresponding request specs in `user_spec.rb` have been updated to reflect this change and ensure the `loa` attribute is correctly serialized.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/107802
- *Describe what the old behavior was prior …
> feat(AccreditedRepresentativePortal): Expose user LOA in API response

- app/controllers/v0/preneeds/cemeteries_controller.rb
- lib/preneeds/service.rb
- modules/mobile/app/controllers/mobile/v0/cemeteries_controller.rb
- modules/mobile/app/serializers/mobile/v0/cemeteries_serializer.rb
- spec/lib/preneeds/service_spec.rb
- This PR updates Common::Collection with Vets::Collection
- Vets::Collection is a near match with Common::Collection 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/92439
> Replace Common::Collection with Vets::Collection - Preneeds Service

- app/services/sign_in/constants/service_account_access_token.rb
- This PR adds the `participant_id` constant to the allowed list of user attributes when authenticating with a Sign in Service STS token
- https://github.com/department-of-veterans-affairs/identity-documentation/issues/257
> [257] Adding participant_id to allowed user_attribute types for Sign in STS

- app/controllers/concerns/authentication_and_sso_concerns.rb
- spec/controllers/v1/sessions_controller_spec.rb
- Currently the cookie is being set with api.va.gov, change to .va.gov so frontend can read it
- login with ssoe and you should see the CERNER_ELIGIBLE cookie with `localhost` domain 
Authentication
> Update Cerner eligible cookie domain

- modules/vaos/app/services/vaos/v2/appointments_service.rb
- modules/vaos/spec/services/v2/appointment_service_spec.rb
- We're adding `partialErrorMessage` to the API response to ensure messaging consistency across web and mobile FE
- Appointments Team
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/107947
N/A
Appointments
> Add partialErrorMessage field to support unified error messaging

- app/sidekiq/lighthouse/evidence_submissions/document_upload.rb
- app/sidekiq/lighthouse/failure_notification.rb
- spec/sidekiq/lighthouse/evidence_submissions/document_upload_spec.rb
- spec/sidekiq/lighthouse/failure_notification_spec.rb
- This work is behind a feature toggle (flipper): **NO**
- The `Lighthouse::FailureNotification` job now uses a [callback](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/sidekiq/lighthouse/evidence_submissions/va_notify_email_status_callback.rb#L40) from VA Notify to increment `silent_failure_avoided` / `silent_failure` according to the email delivery status, thus `silent_failure_avoided_no_confirmation` is removed. In addition, the `silent_failure` metric is now emitted when job retries are exhausted.
- Team: Benefits Management Tools
-
> Clean up failure metrics for Lighthouse::FailureNotification job

- config/features.yml
This PR removes the feature toggle flag,  `va_online_scheduling_static_landing_page`
- Link to ticket created in va.gov-team repo [#103686](https://github.com/department-of-veterans-affairs/va.gov-team/issues/103686) 
n/a
n/a
feature.yml
> Remove static landing toggle flag

- .github/CODEOWNERS
- app/models/mhv/mr/fhir_record.rb
- app/models/mhv/mr/health_condition.rb
- app/models/mhv/mr/vaccine.rb
- config/initializers/inflections.rb
- modules/my_health/app/controllers/my_health/mr_controller.rb
- modules/my_health/app/controllers/my_health/v1/allergies_controller.rb
- modules/my_health/app/controllers/my_health/v1/clinical_notes_controller.rb
- modules/my_health/app/controllers/my_health/v1/conditions_controller.rb
- modules/my_health/app/controllers/my_health/v1/labs_and_tests_controller.rb
- modules/my_health/app/controllers/my_health/v1/medical_records/bbmi_notification_controller.rb
- modules/my_health/app/controllers/my_health/v1/medical_records/ccd_controller.rb
- modules/my_health/app/controllers/my_health/v1/medical_records/imaging_controller.rb
- modules/my_health/app/controllers/my_health/v1/medical_records/mr_session_controller.rb
- modules/my_health/app/controllers/my_health/v1/medical_records/patient_controller.rb
- modules/my_health/app/controllers/my_health/v1/medical_records/radiology_controller.rb
- modules/my_health/app/controllers/my_health/v1/vaccines_controller.rb
- modules/my_health/app/controllers/my_health/v1/vitals_controller.rb
- spec/models/mhv/mr/health_condition_spec.rb
- spec/models/mhv/mr/vaccine_spec.rb
- Added models to convert backend FHIR results into simpler objects for eventual use in the frontend
- Renamed some controllers with capital "MR"
> Add backend models for all our FHIR objects. They should be able to build themselves from a returned FHIR resource.
- This is prep-work for moving functionality to the backend in the future. Should have no impact on current functionality.
- Not behind a feature flag (yet)
> MHV-71298 Added models for vaccine and health condition

- app/services/form1010cg/service.rb
- app/sidekiq/form1010cg/submission_job.rb
- config/features.yml
- spec/services/form1010cg/service_spec.rb
- spec/sidekiq/form1010cg/submission_job_spec.rb
- *This work is behind a feature toggle (flipper): YES* `:caregiver_use_rails_logging_over_sentry`
- Use Rails logger instead of Sentry to handle errors in Caregiver backend
- In the interests of shifting away from using Sentry, this disentangles the CG backend from that logger in favor of the standard Rails logger
- Health Enrollment 10-10CG
- Feature flag can be removed if we see no performance degradation, or unexpectedly sensitive data in the logs
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/108604
- Before the change, the errors would be logged to Sentry. After, they go to the Rails logs
- Verify by submitting in a context where the request will fail:
- Testing plan: Enable in environment, confirm the errors we get in …
> replace Sentry logging with Rails in CG

- modules/travel_pay/app/services/travel_pay/documents_service.rb
Due to a discrepancy in the swagger docs for the external API, I assumed the response from the API would be in json format. It's not. Only the binary data comes back as a string (with headers and response metadata of course). 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/104858
Travel Pay
> Fix parsing body by not parsing body

- app/models/form_submission_attempt.rb
We notice in the logs as seen in the screenshot below that we are missing claim_id from this payload. It is difficult to locate when this occurs.
- Add `claim_id` to the log hash
> Add claim_id to form submission attempt logs

- lib/lighthouse/benefits_documents/configuration.rb
- lib/lighthouse/benefits_documents/service.rb
- spec/lib/lighthouse/benefits_documents/service_spec.rb
- *This work is behind a feature toggle (flipper): NO* but it is not used anywhere. This simply adds the service for further use
- add lighthouse service and configuration to call:
- claims-letters/search
- claims-letters/download
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/102839 …
> BMT1/102839: [CST] Migrate from connect_VBMS to LH document service for claim letters

- config/initializers/breakers.rb
- Adds logs to breakers initializer 
- temporary in order to debug an issue - this will be REMOVED next week
- [issues/108975](https://github.com/department-of-veterans-affairs/va.gov-team/issues/108975)
breakers init in vets-api
> Adds logs to breakers initializer

- lib/pdf_fill/filler.rb
Somehow this didn't fail during PR, but failed after merge into master. A couple more lines were added to this method in https://github.com/department-of-veterans-affairs/vets-api/pull/22224 causing this error:
```
lib/pdf_fill/filler.rb:145:5: C: Metrics/MethodLength: Method has too many lines. [22/20]
def process_form(form_id, form_data, form_class, file_name_extension, fill_options = {}) ...
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6232 files inspected, 1 offense detected
```
This should be fixed correctly (refactor the method), but since this is blocking deploys to dev and staging, this is a quick fix. 
none. saw while trying to deploy something to staging. 
```
rebeccatolmach ~/git/vets-api be rubocop
6232 files inspected, no offenses …
```
> Temporary fix for linting failure in master

- config/initializers/breakers.rb
There was an error in db-migrate in staging because `client` hadn't been created yet by the time we were calling it in https://github.com/department-of-veterans-affairs/vets-api/pull/22250. This should fix the error. 
```
NoMethodError: undefined method `redis_connection' for nil (NoMethodError)
data = Breakers.client.redis_connection.zrange(outages_key(service: service), -1, -1)[0]
^^^^^^^^^^^^^^^^^
/app/config/initializers/breakers.rb:116:in `block (2 levels) in <top (required)>'
/app/config/initializers/breakers.rb:114:in `each'
/app/config/initializers/breakers.rb:114:in `block in <top (required)>'
/app/config/environment.rb:7:in `<top (required)>'
```
- https://github.com/department-of-veterans-affairs/vets-api/pull/22250
Will watch staging deploy post-merge. 
this is only for …
> move debug statement later

- modules/claims_api/app/swagger/claims_api/v2/dev/swagger.json
- modules/claims_api/spec/requests/v2/veterans/rswag_power_of_attorney_spec.rb
* Updates `veterans/power-of-attorney-requests` endpoint to include page size and number params in docs
[API-45363](https://jira.devops.va.gov/browse/API-45363)
- This is just a documentation update, only real testing is visual testing of the changes
modified:   modules/claims_api/spec/requests/v2/veterans/rswag_power_of_attorney_spec.rb
> API-45363-requests-endpoint-documentation-updates

- db/migrate/20250519141104_add_enums_to_lighthouse_submission_status.rb
- db/schema.rb
- This migration adds new values to the `lighthouse_submission_status` enum defined in the database.
- Pension and Burial Benefits team to own this work.
- [*Link to ticket created in va.gov-team repo*](https://github.com/department-of-veterans-affairs/va.gov-team/issues/103351)
- …
> Migration for adding new enums to lighthouse_submission_status

- spec/lib/breakers/statsd_plugin_spec.rb
This work is a direct result of [this conversation
](https://dsva.slack.com/archives/C0581MN69TJ/p1747662757480529)
spec/lib/mdot/client_spec specs are flaky because of global state set in an unrelated spec
[110096](https://github.com/department-of-veterans-affairs/va.gov-team/issues/110096)
specs green
specs
> 110096 ensure that global state doesnt step on the toes of other specs when run in parallel

- lib/vets/collection.rb
- spec/lib/vets/collection_spec.rb
- 2 PRs needed to be reverted to fix a live issue in production
- https://github.com/department-of-veterans-affairs/vets-api/pull/22274
- https://github.com/department-of-veterans-affairs/vets-api/pull/22265
- This PR fixes the bug that was caused when records are empty.
- Instead of validating the attribute to be ordered by the record, this uses the class method `attribute_set`
- Since it's a class method, it avoids the empty record bug
- Also added a guard statement to ensure that the bug is avoided even when the model_class is not set
- n/a
without guard statement:
```ruby
{"errors"=>[{"title"=>"Invalid sort criteria", "detail"=>"\"prescription_name\" is not a valid sort criteria for \"PrescriptionDetails\"", "code"=>"106", "status"=>"400"}]}
```
with guard statement:
```ruby …
```
> Fix Vets::Collection Empty Records Ordering Bug

- spec/support/vcr_cassettes/vaos/eps/draft_appointment/200.yml
- spec/support/vcr_cassettes/vaos/eps/draft_appointment/400_invalid_patientid.yml
- spec/support/vcr_cassettes/vaos/eps/get_appointment/404.yml
- spec/support/vcr_cassettes/vaos/eps/get_appointment/500.yml
- spec/support/vcr_cassettes/vaos/eps/get_appointment/booked_200.yml
- spec/support/vcr_cassettes/vaos/eps/get_appointment/draft_200.yml
- spec/support/vcr_cassettes/vaos/eps/get_appointments/500_error.yml
- spec/support/vcr_cassettes/vaos/eps/get_appointments_200_empty_start_date.yml
- spec/support/vcr_cassettes/vaos/eps/get_appointments_empty_data.yml
- spec/support/vcr_cassettes/vaos/eps/get_drive_times/200.yml
- spec/support/vcr_cassettes/vaos/eps/get_drive_times/400_invalid_coords.yml
- spec/support/vcr_cassettes/vaos/eps/get_eps_appointments_200.yml
- spec/support/vcr_cassettes/vaos/eps/get_provider_service/200.yml
- spec/support/vcr_cassettes/vaos/eps/get_provider_service/404_unknown_provider.yml
- spec/support/vcr_cassettes/vaos/eps/get_provider_service/get_multiple_providers_200.yml
- spec/support/vcr_cassettes/vaos/eps/get_provider_service/get_multiple_providers_200_v2.yml
- spec/support/vcr_cassettes/vaos/eps/get_provider_slots/200.yml
- spec/support/vcr_cassettes/vaos/eps/get_provider_slots/200_no_slots.yml
- spec/support/vcr_cassettes/vaos/eps/get_vaos_appointments_200_with_merge.yml
- spec/support/vcr_cassettes/vaos/eps/providers/data_200.yml
- spec/support/vcr_cassettes/vaos/eps/providers/data_401.yml
- spec/support/vcr_cassettes/vaos/eps/providers/data_500.yml
- spec/support/vcr_cassettes/vaos/eps/providers/data_Aq7wgAux_200.yml
- spec/support/vcr_cassettes/vaos/eps/search_provider_services/200.yml
- spec/support/vcr_cassettes/vaos/eps/search_provider_services/empty_200.yml
- Updated VCR URLs for EPS and CCRA tests to use settings. This makes it so we do not hard code URLs in the VCR cassettes.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/104226
Existing unit tests cover this change.
N/A
N/A
> Updated VCR URLs for EPS and CCRA tests to use settings

- app/controllers/v0/intent_to_files_controller.rb
- lib/lighthouse/benefits_claims/intent_to_file/monitor.rb
- spec/lib/lighthouse/benefits_claims/intent_to_file/monitor_spec.rb
- spec/requests/v0/intent_to_file_spec.rb
- This adds validation, logging, and statsd metrics to the `V0::IntentToFilesController` similar to the checks and logging already in place for `InProgressController` and `CreateIntentToFileJob`
- To be owned by Pension Benefits team
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/108930
- Tested locally and ran spec tests
> 108930: Add validation, logging, and metrics to V0 ITF controller

- .github/CODEOWNERS
- app/serializers/rating_info_serializer.rb
- lib/evss/dependents/retrieved_info.rb
- lib/evss/disability_compensation_form/rated_disabilities_response.rb
- lib/evss/letters/beneficiary_response.rb
- lib/evss/letters/letters_response.rb
- lib/evss/pciu_address/address_response.rb
- lib/evss/pciu_address/countries_response.rb
- lib/evss/pciu_address/states_response.rb
- lib/evss/ppiu/payment_information_response.rb
- lib/evss/response.rb
- modules/mobile/app/models/mobile/v0/adapters/legacy_rating.rb
- spec/lib/evss/pciu/service_spec.rb
- spec/serializers/rating_info_serializer_spec.rb
- Virtus is being replace with `Vets::Model`. Differences include:
- There's no hash access for attributes `form[:attribute]` only dot notation `form.attribute`
- Syntax change for Array attributes
- Sorting uses a class method: `default_sort_by`
- booleans are temporarily `Bool`, until Virtus is completely gone
- This PR replaces `Virtus.model` with `Vets::Model` and updates the _attributes_ and _implementation_ accordingly. 
- This change should not affect any functionality.
Part 1: https://github.com/department-of-veterans-affairs/vets-api/pull/22239
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/92441
> Replace Common::Base with Vets::Model - EVSS::Response

- app/sidekiq/hca/std_institution_import_job.rb
- spec/sidekiq/hca/std_institution_import_job_spec.rb
- Reduce logging noise. Currently we log one line for every Institution as we process them, whether they're new or already exist. This was useful for initial debug and rollout, but now that it's confirmed stable it's ~4000 lines of unnecessary noise a day. This reduces that output to a single line.
- Health Enrollment 10-10EZ/CG
- Cleanup / followup to https://github.com/department-of-veterans-affairs/va.gov-team/issues/87005
- Functionality is unchanged, only logging is reduced.
- Run `HCA::StdInstitutionImportJob.new.perform` in a console, and see that it only outputs a few summary lines instead of thousands of individual facility lines.
Facility selectors used in Health Enrollment (10-10EZ) and Caregiver (10-10CG) forms.
> make facility import job logging more concise

- app/models/concerns/form526_claim_fast_tracking_concern.rb
- app/models/form_profiles/va_526ez.rb
- lib/disability_compensation/requests/form526_request_body.rb
- lib/disability_compensation/responses/claims_service_response.rb
- lib/disability_compensation/responses/intake_sites_response.rb
- lib/disability_compensation/responses/intent_to_files_response.rb
- lib/disability_compensation/responses/payment_information_response.rb
- lib/disability_compensation/responses/rated_disabilities_response.rb
- lib/vets/attributes.rb
- spec/lib/disability_compensation/providers/claims_service/lighthouse_claims_service_provider_spec.rb
- spec/lib/disability_compensation/providers/intent_to_file/lighthouse_intent_to_file_provider_spec.rb
- spec/lib/disability_compensation/providers/rated_disabilities/lighthouse_rated_disabilities_provider_spec.rb
- spec/lib/evss/disability_compensation_form/form526_to_lighthouse_transform_spec.rb
- Virtus is being replace with `Vets::Model`. Differences include:
- There's no hash access for attributes `form[:attribute]` only dot notation `form.attribute`
- Syntax change for Array attributes
- Sorting uses a class method: `default_sort_by`
- booleans are temporarily `Bool`, until Virtus is completely gone
- This PR replaces `Virtus.model` with `Vets::Model` and updates the _attributes_ and _implementation_ accordingly. 
- This change should not affect any functionality.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/92441
> Replace Virtus with Vets::Model - Disability Compensation

- .github/workflows/check_codeowners.yml
- app/controllers/v0/test/test.rb
breaking change in an action we use: https://github.com/thollander/actions-comment-pull-request/blob/main/MIGRATION_GUIDE.md
Updated in https://github.com/department-of-veterans-affairs/vets-api/pull/22310 and the comments came through in the PR when this change was made:
https://github.com/department-of-veterans-affairs/vets-api/pull/22319#issuecomment-2897994270 (below)
Codeowners Github action
> update GITHUB_TOKEN to github-token in GHA

- config/features.yml
- *This work IS a feature toggle (flipper):* `my_va_auth_exp_redesign_enabled`
- To begin the work for our MyVA Redesign we are adding the toggle that will show/hide the new design
- MyVA & Profile/Authenticated Experience Team
- When this toggle is enabled and changes are wrapped with this new toggle, the user will be able to experience the MyVA redesign
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/109868
- Only adding the feature toggle itself so no changes to be tested
- The toggle was nor visible in Flipper UI 
- To see the new toggle:
1️⃣  Checkout this branch
2️⃣  start your rails server `rails s`
3️⃣  Navigate to `http://localhost:3000/flipper/features`
4️⃣  Cmd + F for …
> Add toggle for MyVA new design #109868

- app/models/saved_claim.rb
- app/models/saved_claim/dependency_claim.rb
- app/sidekiq/benefits_intake_status_job.rb
- app/sidekiq/lighthouse/benefits_intake/submit_central_form686c_job.rb
- lib/dependents/monitor.rb
- lib/dependents/notification_callback.rb
- lib/pdf_fill/forms/va21674.rb
- lib/pdf_fill/forms/va21674v2.rb
- spec/factories/dependency_claim.rb
- spec/lib/dependents/monitor_spec.rb
- spec/models/saved_claim/dependency_claim_spec.rb
- spec/sidekiq/lighthouse/benefits_intake/submit_central_form686c_job_spec.rb
- *This work is behind a feature toggle (flipper): Partially*
The primary purpose of this PR is to add overflow PDF tracking for the 686c-674 form (v1 and v2), but this involved resolving a significant number of related bugs and issues.
- The Dependents monitor needed to be updated to differentiate between v1 and v2 claims
- Updates to locations using the monitor to pass new v2 flag
- The V2 flag wasn't getting set correctly in tests, so tests needed to be updated
- Once the V2 flag was set, V2 tests began failing. I discovered that `SavedClaim.form_data` was getting overwritten with each call to `to_pdf` for 21-674-V2, causing errors on all calls after the first. This has been fixed. 
- As part of debugging, I added an additional monitoring call to `to_pdf`.
- One test broke for v1 when …
> Enable 686c-674 PDF overflow tracking

- .github/CODEOWNERS
- app/models/persistent_attachments/va_form_attachment.rb
- modules/accredited_representative_portal/app/models/accredited_representative_portal/saved_claim/benefits_intake.rb
- modules/accredited_representative_portal/docs/BENEFITS_INTAKE_CLAIMS.md
- modules/accredited_representative_portal/spec/models/accredited_representative_portal/saved_claim/benefits_intake_spec.rb
Here is a PR (first in a stack) that introduces the core of the data model that would give us a generic benefits intake claim submission that interoperates w/ platform's code for doing this generically too.
Goal is being small, nonintrusive, and leading the way towards any areas where platform code gets inappropriately specific. If/when we reach any instances of that, we'd be bold about putting workarounds in platform code rather than duplicate the entire system (which has happened multiple times already in vets-api) .
Service classes that wrap interactions w/ this data model forthcoming now that the hard part is "figured out".
The key features of our solution include:
- Interoperating w/ existing `SubmitBenefitsIntakeClaim` asynchronous BI API integration
- Form data will map to BI API …
> Arp/form upload/1

- modules/vaos/app/serializers/ccra/referral_detail_serializer.rb
- modules/vaos/spec/serializers/ccra/referral_detail_serializer_spec.rb
- Added facility name to VAOS referral detail response
https://github.com/department-of-veterans-affairs/va.gov-team/issues/110189
N/A
N/A
> Added facility name to VAOS referral detail response

- modules/vaos/app/controllers/vaos/v2/referrals_controller.rb
- modules/vaos/spec/controllers/v2/referrals_controller_spec.rb
- Updated search parameters for VAOS referral list to include sent referrals.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/110461
N/A
N/A
> Updated search parameters for VAOS referral list

- app/models/saved_claim/dependency_claim.rb
- lib/dependents/monitor.rb
- lib/pdf_fill/forms/va21674.rb
- lib/pdf_fill/forms/va21674v2.rb
- lib/pdf_fill/forms/va686c674.rb
- lib/pdf_fill/forms/va686c674v2.rb
- Sometimes `veteran_information` is undefined in form_data at the top level, but is present in dependents_application. While this is handled elsewhere in the code, to track PDF overflow it needs to be managed earlier in the process, during a PDF mapping of unprocessed data. 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/108402
Dependents
> Handle nil veteran info

- app/models/saved_claim/dependency_claim.rb
- app/sidekiq/lighthouse/benefits_intake/submit_central_form686c_job.rb
- lib/dependents/monitor.rb
- spec/lib/dependents/monitor_spec.rb
- spec/sidekiq/lighthouse/benefits_intake/submit_central_form686c_job_spec.rb
- First piece of https://github.com/department-of-veterans-affairs/va.gov-team/issues/110120
- Updates the Dependents::Monitor to take saved_claim_id as a parameter at creation (instead of v2) to allow safer and more consistent calculation of whether a claim is v2 for monitoring purposes. This will also make removing v2 from the monitors after full release simpler. 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/110120
Dependents
> Use saved_claim_id to initialize Dependents:Monitor

- Gemfile.lock
Reverts department-of-veterans-affairs/vets-api#22342
https://dsva.slack.com/archives/C30LCU8S3/p1747999195998519
Added in 2.16:
> Add warning when `on_error` handler is not a Proc ([#4611](https://github.com/DataDog/dd-trace-rb/pull/4611))
Causing lots of vets-api errors:
```
W, [2025-05-23T13:24:19.916260 #103]  WARN -- datadog: [datadog] on_error argument to SpanOperation ignored because is not a Proc: #<Method: Net::HTTP(Datadog::Tracing::Contrib::HTTP::Instrumentation::InstanceMethods)#annotate_span_with_error!(span, error) /usr/local/bundle/cache/ruby/3.3.0/gems/datadog-2.16.0/lib/datadog/tracing/contrib/http/instrumentation.rb:115>
```
> Revert "Bump datadog from 2.15.0 to 2.16.0"

- modules/vaos/app/services/ccra/referral_service.rb
- Removed debug logging from referral service
https://github.com/department-of-veterans-affairs/va.gov-team/issues/109247
N/A
N/A
N/A
> Removed debug logging from referral service

- modules/vaos/app/models/ccra/referral_list_entry.rb
- modules/vaos/app/serializers/ccra/referral_list_serializer.rb
- modules/vaos/spec/serializers/ccra/referral_list_serializer_spec.rb
- Added station ID to VAOS referral list
https://github.com/department-of-veterans-affairs/va.gov-team/issues/110489
N/A
N/A
> Added station ID to VAOS referral list

- modules/vaos/app/controllers/vaos/v2/appointments_controller.rb
- Removed pagination from VAOS check referral usage method call. This was causing an exception since the pagination object as missing data. We don't need this.
- Formatted dates as needed by API
https://github.com/department-of-veterans-affairs/va.gov-team/issues/106405
N/A
N/A
> Removed pagination from VAOS check referral usage method call

- app/controllers/v0/event_bus_gateway_controller.rb
- app/sidekiq/event_bus_gateway/letter_ready_email_job.rb
- spec/controllers/v0/event_bus_gateway_controller_spec.rb
- spec/sidekiq/event_bus_gateway/letter_ready_email_job_spec.rb
The Gateway will actually **not** ever send over additional `personalisation` parameters, so we do not need to care about them in vets-api. Put another way, all the `personalisation` params being sent to VA Notify will be found or calculated within vets-api.
> [Event Bus] Removes personalisation from gateway controller params

- app/sidekiq/event_bus_gateway/letter_ready_email_job.rb
In the email being sent via VA Notify, there are links. But those links should refer to the non-api host, not the api host. So this does that. I could do this with a regexp but I find the hash to be more direct.
For environments that aren't in the mapping (local), we don't need to alter it.
> [Event Bus]: Adds mapping for hostname to remove api prefix

- .github/workflows/ready_for_review.yml
Multiple PRs are unable to be merged as a result of this CI check failure, even after backend review and all tests passing. Temporarily disabling the failures detected portion until this can be investigated further. 
https://dsva.slack.com/archives/CBU0KDSB1/p1748538329086439
Another PR -> https://github.com/department-of-veterans-affairs/vets-api/pull/22047
Another PR -> https://github.com/department-of-veterans-affairs/vets-api/pull/22439
> Temp modify failing CI check

- modules/vaos/app/controllers/vaos/v2/appointments_controller.rb
- modules/vaos/spec/requests/vaos/v2/appointments_spec.rb
- Added referral consult ID to create draft. This is due to the change that a referral can only be fetched using the consult ID.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/110832
N/A
N/A
> Added referral consult ID to create draft

- modules/claims_api/app/controllers/claims_api/v1/application_controller.rb
- modules/claims_api/app/controllers/claims_api/v1/forms/disability_compensation_controller.rb
- modules/claims_api/app/controllers/claims_api/v2/veterans/power_of_attorney/base_controller.rb
- modules/claims_api/app/services/claims_api/unsynchronized_evss_claim_service.rb
- modules/claims_api/app/sidekiq/claims_api/flash_updater.rb
- modules/claims_api/app/sidekiq/claims_api/service_base.rb
- modules/claims_api/app/sidekiq/claims_api/special_issue_updater.rb
- modules/claims_api/app/sidekiq/claims_api/updater_service.rb
- modules/claims_api/app/sidekiq/claims_api/v2/disability_compensation_benefits_documents_uploader.rb
- modules/claims_api/app/sidekiq/claims_api/v2/disability_compensation_docker_container_upload.rb
- modules/claims_api/app/sidekiq/claims_api/v2/disability_compensation_pdf_generator.rb
- modules/claims_api/lib/claims_api/poa_vbms_sidekiq.rb
- modules/claims_api/lib/claims_api/vbms_uploader.rb
- modules/claims_api/spec/sidekiq/poa_vbms_sidekiq_spec.rb
Retired the use of SentryLogging in the `claims_api` module. Removed where logging was already in place, replaced with Vets::SharedLogging's `log_exception_to_rails`, or replaced with `ClaimsApi::Logger` where appropriate.
Also a bit of logging cleanup for a "temporary" feature test that was introduced in 2021 and hasn't logged anything in production for the last 90 days.
[API-45155](https://jira.devops.va.gov/browse/API-45155)
Various logging items around Claims APIs. Should be transparent to end users.
> API-45155 Retire SentryLogger

- lib/va_profile/v2/contact_information/service.rb
The vet360_id is required for `/GET` person VAProfile requests.
This is behind the `remove_pciu` flipper, which is on in staging and off in prod.
- https://dsva.slack.com/archives/C06JM7UUHE3/p1748455143817789
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/101375 …
> Require the  vet360_id for GET Person VAProfile requests

- app/models/persistent_attachments/va_form_attachment.rb
- modules/accredited_representative_portal/app/models/accredited_representative_portal/saved_claim/benefits_intake.rb
- modules/accredited_representative_portal/app/services/accredited_representative_portal/saved_claim_service/attach.rb
- modules/accredited_representative_portal/spec/services/accredited_representative_portal/saved_claim_service/attach_spec.rb
- spec/fixtures/files/accredited_representative_portal/invalid.pdf
Introduces a service, `SavedClaimService::Attach`, for creating attachments that can later be specified by ID as attachments to a Benefits Intake saved claim, `SavedClaim::BenefitsIntake`, upon submission. This mirrors the client-server relationship from Simple Forms products that we forked.
This has no callers yet.
Attachments have an attribute determining whether or not they are for the main form or for other documents, which in turn determines which attachment validations they receive:
- `VAForm` => `FormUpload::Uploader::Attachment`
- `VAFormAttachment` (later PR renames to `VAFormDocumentation`) => `ClaimDocumentation::Uploader::Attachment`
The service exercises two sets of validations of the attached file:
- `vets-api`'s local validations of `PersistentAttachment` subtypes
- …
> Arp/form upload/2

- .github/copilot-instructions.md
I followed [these instructions](https://docs.github.com/en/copilot/customizing-copilot/adding-repository-custom-instructions-for-github-copilot) for creating `copilot-instructions.md` for providing additional context for _Copilot chats_. 
> The instructions you add to the `.github/copilot-instructions.md` file should be short, self-contained statements that add context or relevant information to supplement users' chat questions.
I asked Copilot for advice in writing and formatting this file and it suggested these different sections. I made some of my own updates as well. Please review for accuracy!
Note: these instructions don't impact the code reviews that Copilot can do in a PR. For that, I've added some "guidelines" directly in the UI …
> add instructions for Copilot chat

- config/features.yml
- This change introduces a feature toggle that will be used for controlling the display of a cut over notice for a new version of the VR&E (Ch 31) form.
- I work on the IIR Product team and we currently own VR&E (Ch 31).
- [1743](https://github.com/department-of-veterans-affairs/va-iir/issues/1743)
- This change only introduces a new feature toggle to be used by vets-website.
List of feature toggles available.
> Add VR&E cutover notice feature toggle

- modules/vaos/app/controllers/vaos/v2/eps_appointments_controller.rb
- modules/vaos/app/models/vaos/v2/eps_appointment.rb
- modules/vaos/spec/requests/vaos/v2/eps_appointments_spec.rb
- EPS draft appointments don't 404. We were returning a 404 when an appointment had a state of draft, but this is not really a 404 as the appointment was found. We now just return the data.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/110958
N/A
N/A
> EPS draft appointments don't 404

- app/controllers/sign_in/webhooks/logingov_controller.rb
- app/services/sign_in/errors.rb
- app/services/sign_in/logingov/risc_event_handler.rb
- lib/sign_in/logingov/risc_event.rb
- spec/controllers/sign_in/webhooks/logingov_controller_spec.rb
- spec/factories/sign_in/logingov_risc_event_payloads.rb
- spec/lib/sign_in/logingov/risc_event_spec.rb
- spec/services/sign_in/logingov/risc_event_handler_spec.rb
- Create logingov risc event handler and class.
- The class will parse the event
- The handler receives a decoded jwt, creates a risc event, and currently logs the event. (other functionality such as flagging an account could be added to the handler in the future)
- Create a factory for example RISC payloads. These can also be encoded witht the oauth_test private key
- [Login.gov Docs](https://developers.login.gov/security-events/#receiving-a-security-event-token-set)
- https://github.com/department-of-veterans-affairs/identity-documentation/issues/221
- Create some test payloads and call the handler and create RiscEvents in rails console'
```ruby
include FactoryBot::Syntax::Methods
payload = build(:logingov_risc_event_payload)
SignIn::Logingov::RiscEventHandler.new(payload:).perform
``` …
> [ID-221] Create logingov risc event object and handler

- modules/accredited_representative_portal/app/controllers/accredited_representative_portal/v0/representative_form_upload_controller.rb
- modules/accredited_representative_portal/app/controllers/concerns/accredited_representative_portal/v0/representative_form_upload_concern.rb
This PR is to troubleshoot an error that as the ARF team we are only encountering on staging -- when using the same exact params to search users on MPI (first & last name, dob, ssn), it works on local dev environments but when on staging, it _appears_ that these parameters are blanked out. This change allows us to print the length of each param, without defying the masking used in logging.
> [ARP] Debug log shape of values in claim submission code path

- modules/mobile/app/models/mobile/v0/adapters/claim_letter_documents.rb
- modules/mobile/spec/requests/mobile/v0/claims_and_appeals_spec.rb
It has been verified that the GET `claim-letters/search` endpoint from the LH Benefits Documents Service will return an empty data object (ie `{ "data" => {} }` when the user has no documents to return. This was not being checked for originally (it was assumed, according to their docs that either nothing is returned or an empty "documents" list is returned). This change fixes that check.
- *This work is behind a feature toggle (flipper): ~~YES~~/NO*
Update Mobile Claim Letter Documents adapter to account for empty data object.
Make a request on staging to the mobile GET `claim-letters/documents` endpoint with a user with no documents. It will currently return a 500
- *(What is the solution, why …
> BUG - Update Claim Letters Documents adapter to check for empty data object

- app/models/saved_claim/dependency_claim.rb
- VBMS upload isn't configured for local development, which causes a 500 error on local Dependents submissions. Skip upload attempt in development.
Dependents
> Skip VBMS upload in development

- .github/CODEOWNERS
Backend Platform is looking to replace [mbs-core-team](https://github.com/orgs/department-of-veterans-affairs/teams/mbs-core-team) as code owners since they don't appear to be a team of vets-api developers. We got most of the way there with https://github.com/department-of-veterans-affairs/vets-api/pull/22540 and this PR handles the remaining ones. 
This is something we brought up in the Backend CoP.
https://dsva.slack.com/archives/C0547Q0K0LF/p1749067588868699
CODEOWNERS
> CODEOWNERS: Replace mbs-core-team with pensions-and-burials

- app/sidekiq/event_bus_gateway/letter_ready_email_job.rb
- spec/sidekiq/event_bus_gateway/letter_ready_email_job_spec.rb
Prior to this change, if BGS could not find a user for a given Participant ID, the job would continue to execute and we'd get an error from VA Notify.
This change makes the BGS fail-to-find raise an error so that **that** stops execution of the code and the error is caught and logged earlier.
> [Event Bus] BGS fail to find now raises exception so VA Notify is not hit

- config/features.yml
- This change adds the `profile_contact_info_page_ui_refresh` ahead of UI updates to the Profile Contact Info page in vets-website. This flipper will be removed once the UI updates are complete and have been validated by our team.
- Team: Authenticated Experience
https://github.com/department-of-veterans-affairs/va.gov-team/issues/111396
Verified the flag shows in features/flipper in my local environment …
> Add profile_contact_info_page_ui_refresh flag to features.yml

- modules/accredited_representative_portal/app/models/accredited_representative_portal/claimant_representative.rb
- modules/accredited_representative_portal/spec/models/accredited_representative_portal/claimant_representative_spec.rb
Introduces `ClaimantRepresentative` for encapsulating checking for and returning a POA holder relationship involving a claimant and representative.
(In near future state, representative's POA holders are sourced from OGC data while claimant's current general POA is sourced from CorpDB via BGS via Lighthouse)
**Note:** This is knowingly duplicative of some existing code, and can motivate consolidation into some module if we can find the consolidation.
> Arp/form upload/7

- db/schema.rb
- modules/accredited_representative_portal/db/migrate/20250527050638_create_ar_saved_claim_claimant_representatives.rb
Migration for `SavedClaimClaimantRepresentative` which associates a claim submitted in our tool to 3x relationship members:
```
claimant <==> poa_holder <==> representative
```
> Arp/form upload/8

- modules/claims_api/app/controllers/claims_api/v1/forms/power_of_attorney_controller.rb
- modules/claims_api/app/controllers/concerns/claims_api/poa_verification.rb
- modules/claims_api/spec/concerns/claims_api/poa_verification_spec.rb
- modules/claims_api/spec/requests/v1/forms/2122_spec.rb
- modules/claims_api/spec/requests/v1/forms/rswag_2122_spec.rb
- modules/claims_api/spec/support/auth_helper.rb
Expands searching for representatives in cases where the Representative's name in OGC is different than what's stored in the login or MPI. It's the same search logic vetted in other existing endpoints, now added to the `active` POA v1 endpoint.
* Marmoset originating ticket: [API-46858](https://jira.devops.va.gov/browse/API-46858)
* Subtask: [API-47081](https://jira.devops.va.gov/browse/API-47081)
Representatives looking to see a veteran's active POA will have a better chance of being recognized by the system as a valid viewer of that information.
> API-46858 POA v1 active endpoint lookup expansion

- app/models/user.rb
- app/serializers/user_serializer.rb
- app/services/users/profile.rb
- app/services/users/scaffold.rb
- spec/serializers/user_serializer_spec.rb
- spec/support/schemas/user_loa1.json
- spec/support/schemas/user_loa3.json
- spec/support/schemas_camelized/user_loa1.json
- spec/support/schemas_camelized/user_loa3.json
- Updates to `Account` removal PR: https://github.com/department-of-veterans-affairs/vets-api/pull/21979.
- restores user profile `account` serialization, this will be removed after a `vets-website` update.
- restores user `flipper_id` function to also include `UserAccount` id.
- https://github.com/department-of-veterans-affairs/identity-documentation/issues/393
- Confirm user serialization change - both `account` and `user_account` should be present with an identical uuid
> [393] restores user profile account serialization format & flipper check

- lib/unified_health_data/service.rb
- spec/lib/unified_health_data/service_spec.rb
This PR adds support for displaying comparator values (e.g., "<", ">", "<=") in lab results. Previously, lab results with comparators would only show the value and unit (e.g., "50 mmol/L"). Now, if a comparator is present in the data, it will be displayed correctly (e.g., "<50 mmol/L").
- Updated `fetch_observation_value` method to include comparators when present
- Extracted a helper method `format_quantity_value` to handle formatting of quantity values
- …
> Add Support for Lab Result Comparators

- app/controllers/v1/sessions_controller.rb
- app/services/sign_in/constants/auth.rb
- spec/controllers/v0/sign_in_controller_spec.rb
- We are adding 3 operation param types to `operationType`: `VERIFY_CTA_AUTHENTICATED`, `VERIFY_PAGE_AUTHENTICATED` and `VERIFY_PAGE_UNAUTHENTICATED`
- *(If bug, how to reproduce)* not a bug
- *(What is the solution, why is this the solution?)* Adding more operation types for FE use
- *(Which team do you work for, does your team own the maintenance of this component?)* Identity …
> Add page auth, page unauth and cta auth param to operation type

- .github/copilot-instructions.md
Adds info on how to enable test logging to the copilot instructions.
> Add info on how to enable test logging to the copilot instructions

- spec/requests/swagger_spec.rb
- spec/sidekiq/form1010cg/delete_old_uploads_job_spec.rb
Skip flakey specs while the root cause is investigated. They are both using the cassette, `3/object/put/834d9f51-d0c7-4dc2-9f2e-9b722db98069/doctors-note.pdf`, which seems to be causing problems all of a sudden. Errors: 
```
Failures:
1) Form1010cg::DeleteOldUploadsJob#perform integration deletes attachments created more than 30 days ago
Failure/Error: 
VCR.use_cassette(cassette, vcr_options) do
block.call
end
VCR::Errors::UnusedHTTPInteractionError:
There are unused HTTP interactions left in the cassette:
- [put https://my-bucket.s3.us-gov-west-1.amazonaws.com/uploads/tmp/1619206365-340201329057824-0002-6154/doctors-note.jpg] => [200 ""]
- [head https://my-bucket.s3.us-gov-west-1.amazonaws.com/uploads/tmp/1619206365-340201329057824-0002-6154/doctors-note.jpg] => [200 ""]
- [put …
```
> skip 1010 VCR flakey specs

- app/sidekiq/event_bus_gateway/va_notify_email_status_callback.rb
- spec/sidekiq/event_bus_gateway/va_notify_email_status_callback_spec.rb
These particular emails are not prompted by any action taken by the user, they are not Silent Failures. Do not log them as such.
> [Event Bus Gateway]: VA Notify callback failures are not silent

- modules/accredited_representative_portal/app/controllers/concerns/accredited_representative_portal/v0/representative_form_upload_concern.rb
- modules/accredited_representative_portal/spec/requests/accredited_representative_portal/v0/representative_form_uploads_spec.rb
- We are now submitting supporting evidence with a VA Form. Our service needs to find all associated attachments based on confirmation codes. This change handles multi attachment submissions
- Front-end pr - https://github.com/department-of-veterans-affairs/vets-website/pull/37170
/representative/representative-form-upload
> RepresentativeFormUploadConcern::attachment_guids multiform compliant

- lib/bpds/service.rb
- spec/lib/bpds/service_spec.rb
- *This work is behind a feature toggle (flipper): YES* `bpds_service_enabled`
- This updates the POST request body being sent to BPDS being incorrectly generated
- The bugs were that participant id and file number were added at the root level instead of in the `bpd` element, and the `.merge` calls were not changing the payload in-place so the final submitted payload wasn't including any identifier fields
- Owned by Pension Benefits team
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/112573
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/109911
- Tested manually locally and on staging
* Requests to BPDS from the Pension ClaimsController
> 112573: Fix incorrectly formulated BPDS request body for pension claims

- config/features.yml
- Added feature toggle to call DGIB ONLY without calling BDN.
https://jira.devops.va.gov/browse/VEBT-1357
> VEBT-1357: VYE: adding feature toggle for dgib endpoint only

- db/schema.rb
- modules/test_user_dashboard/db/migrate/20250624162553_add_index_to_tud_account_emails.rb
- adds `email` index to `test_user_dashboard_tud_accounts` table.
- necessary for TUD `email` uniqueness validation to be Rubocop-compliant.
- TUD rubocop update: https://github.com/department-of-veterans-affairs/vets-api/pull/22842
- https://github.com/orgs/department-of-veterans-affairs/projects/1646/views/2?filterQuery=label%3Abackend+-status%3AINTAKE%2CDiscovery%2C%22Shape+Work+%26+Prioritize%22%2CDesign%2C%22Active+Research%22%2C%22Super+Epics%22%2CEpics%2C%22Launch+%26+Monitor%22%2C%22Discover+%26+Define%22%2C%22Deliver%21+Iterate%21%22+type%3ATask+assignee%3A%40me&pane=issue&itemId=115002077&issue=department-of-veterans-affairs%7Cva.gov-team%7C111946
> [111946] adds email index to tud_accounts

- modules/vaos/app/controllers/vaos/v2/appointments_controller.rb
- modules/vaos/app/models/ccra/referral_detail.rb
- modules/vaos/spec/requests/vaos/v2/appointments_spec.rb
- modules/vaos/spec/services/ccra/redis_client_spec.rb
- The appointment type was originally hard coded to `ov` per instructions received, but it turns out that we need to get the appointment type from the provider's data itself and send it to the the slots search.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/112860
N/A
Unreleased VAOS referral appointments
> VAOS Referral appointments uses provider's appointment types

- app/serializers/user_serializer.rb
- app/services/users/profile.rb
- app/services/users/scaffold.rb
- spec/support/schemas/user_loa1.json
- spec/support/schemas/user_loa3.json
- spec/support/schemas_camelized/user_loa1.json
- spec/support/schemas_camelized/user_loa3.json
- Removes `account` from User serialization.
- https://github.com/department-of-veterans-affairs/identity-documentation/issues/324
- https://github.com/department-of-veterans-affairs/identity-documentation/issues/393
- Verify `account` attribute is no longer present at `localhost:3000/v0/user`
> [324] removes account from user serialization

- modules/ask_va_api/app/lib/ask_va_api/inquiries/payload_builder/inquiry_payload.rb
Datadog Stack Trace shows that the error is happening because the file structure may be nil or empty. This puts defensive checks to ensure the inquiry can proceed if there are no file attachments. This may have been preventing Inquiries from being submitted.
`AskVAApi::Inquiries::InquiriesCreatorError: InquiriesCreatorError: undefined method `[]' for nil`
-- In ask VA, there is a `undefined method `[]' for nil` error. The source of the error points to this line.
-- Added additional nil checks in the structure.
- *(Which team do you work for, does your team own the maintenance of this …
> Add Blank and Nil Checks for presence of File attachments

- modules/vaos/app/controllers/vaos/v2/eps_appointments_controller.rb
- modules/vaos/app/services/eps/appointment_service.rb
- modules/vaos/app/services/eps/appointment_status_notification_callback.rb
- modules/vaos/app/sidekiq/eps/appointment_status_email_job.rb
- modules/vaos/app/sidekiq/eps/appointment_status_job.rb
- modules/vaos/spec/requests/vaos/v2/eps_appointments_spec.rb
- modules/vaos/spec/services/eps/appointment_service_spec.rb
- modules/vaos/spec/services/eps/appointment_status_notification_callback_spec.rb
- modules/vaos/spec/sidekiq/eps/appointment_status_email_job_spec.rb
- modules/vaos/spec/sidekiq/eps/appointment_status_job_spec.rb
- updates `Eps::AppointmentService#submit_appointment` to utilize `user.email` rather than `user.va_profile_email`
- Adds StatsD metric to track access of the appointment detail endpoint
- Updates error message in `Eps::AppointmentStatusJob` to be consistent
- Removes unnecessary tags from StatsD logging to avoid excessive cardinality
- Adds metric increment and error logging in `Eps::AppointmentStatusJob` for status check success / failure
https://github.com/orgs/department-of-veterans-affairs/projects/1323/views/35?pane=issue&itemId=117454991&issue=department-of-veterans-affairs%7Cva.gov-team%7C113087
(OPTIONAL)_What should the reviewers …
> Update outgoing error message and metrics tags for CC appts

- modules/claims_api/app/controllers/claims_api/v2/veterans/power_of_attorney/request_controller.rb
No regret refactor to help with the upcoming work for API-43735. Extracts method out to handle when a decision is 'declined'.
[API-47706](https://jira.devops.va.gov/browse/API-47706)
[API-43735](https://jira.devops.va.gov/browse/API-43735) (Parent ticket)
- No behavior changes related to this refactor
> API-prefactor-for-gathering-data-declined-workflow

- modules/accredited_representative_portal/app/sidekiq/accredited_representative_portal/submit_benefits_intake_claim_job.rb
- spec/support/vcr.rb
- spec/support/vcr_cassettes/accredited_representative_portal/sidekiq/accredited_representative_portal/submit_benefits_intake_claim_job_spec/performs.yml
This is a temporary workaround while there is configuration inconsistency between two Benefits Intake API Ruby clients in `vets-api`'s staging environment. The inconsistency between these Ruby clients matters because we use both of them in different parts of claims' lifecycles:
- `BenefitsIntakeService::Service`
- Points to Lighthouse's staging environment
- Used to submit claims initially
- `BenefitsIntake::Service`
- Points to Lighthouse's sandbox environment
- Used to check claims' statuses afterwards
> [ARP] Benefits Intake API configuration workaround

- modules/appeals_api/config/mailinglists/error_report_daily.yml
- modules/appeals_api/config/mailinglists/error_report_weekly.yml
- modules/appeals_api/config/mailinglists/report_daily.yml
- modules/appeals_api/config/mailinglists/report_weekly.yml
- modules/appeals_api/config/mailinglists/stats_report_monthly.yml
- modules/vba_documents/app/mailers/vba_documents/monthly_report_recipients.yml
- modules/vba_documents/app/mailers/vba_documents/unsuccessful_report_recipients.yml
This work is behind a feature toggle (flipper): *NO*
This PR updates the email recipients list for the Lighthouse Decision Reviews and Benefits Intake API email reports, to adjust to recent changes to the Lighthouse staff.
My team (Lighthouse Banana Peels) owns the `appeals_api` and `vba_documents` modules.
[API-47550](https://jira.devops.va.gov/browse/API-47550)
- Prior to this change, the reporting emails for the Decision Reviews and Benefits Intake APIs were sent to a slightly different list of recipients.
- To roll out the change, we'll simply merge the PR and allow the updated recipients lists to take effect for the email reports going forward.
None
This PR impacts the `appeals_api` and `vba_documents` modules, and specifically the email reporting features for the Lighthouse Decision …
> API-47550: Update Email Report Recipients for Lighthouse Decision Reviews and Benefits Intake APIs

- modules/vaos/app/controllers/vaos/v2/appointments_controller.rb
- modules/vaos/spec/controllers/v2/appointments_controller_spec.rb
- VAOS Referral provider slot search uses start time in the present or future. The EPS service is not able to handle dates in the past. Although EPS will fix that, we will also provide a fix for consistency since we do not care about any appointment slots in the past.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/113457
N/A
VAOS Referral scheduling appointments
> VAOS Referral provider slot search uses start time in the present or future

- modules/vaos/app/services/eps/provider_service.rb
- modules/vaos/spec/services/eps/provider_service_spec.rb
- spec/support/vcr_cassettes/vaos/eps/get_provider_slots/200_with_pagination.yml
- Referral provider slot search must paginate even if no slots present. We had a gate that stopped paginating if no slots are found on the response even when a nextToken is provided. Nate form EPS has stated that we still have to paginate in those cases.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/113478
Changed the pagination test to have one page with no slots.
N/A
> VAOS referral provider slot search must paginate even if no slots present

- config/features.yml
- Removing fully released feature toggles
- Appointments FE Team
- This PR should be merged only after the vets-website PR is merged and deployed.
- https://github.com/department-of-veterans-affairs/vets-website/pull/37475
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/113241
N/A
N/A
Appointments
> Remove va_online_scheduling_convert_slots_to_utc feature toggle

- app/controllers/concerns/sentry_controller_logging.rb
Updates UserIdentity guard clause in app/controllers/concerns/sentry_controller_logging.rb
-- Updates UserIdentity guard clause in app/controllers/concerns/sentry_controller_logging.rb
- *(What is the solution, why is this the solution?)* 
-- Implements defensive checks to avoid conditions under nil. …
> Fix for NoMethodError in Sentry

- lib/pdf_fill/forms/va2141422024.rb
- spec/lib/pdf_fill/forms/va2141422024_spec.rb
- Updated date formatting in PDF overflow to match MM-DD-YYYY format
- Updated tests for `combine_date_ranges_for_pdf`
[#112633](https://github.com/department-of-veterans-affairs/va.gov-team/issues/112633)
Decision Reviews 21-4142 Pathway
> Update date format for treatment date

- modules/vaos/spec/requests/vaos/v2/appointments_spec.rb
- Skip consistently failing VAOS EPS referral tests that have been affecting CI stability since June 27th
- Tests are being temporarily skipped while the root cause is investigated
- VAOS EPS referral tests started failing consistently around June 27th
- 37+ master branch failures identified with identical 9-test failure patterns
- Timeline correlates with commit 8326d1b12d which added `Rails.cache.clear` to test suite
- Failures are blocking CI for multiple unrelated PRs
@department-of-veterans-affairs/vfs-vaos team will investigate the root cause, likely related to the `Rails.cache.clear` addition in the test's `after` block.
Related files:
- `modules/vaos/spec/requests/vaos/v2/appointments_spec.rb:1225`
- Suspect commit: https://github.com/department-of-veterans-affairs/vets-api/commit/ …
> Skip flaky VAOS EPS referral tests

- modules/accredited_representative_portal/spec/requests/accredited_representative_portal/v0/form21a_spec.rb
Reverts department-of-veterans-affairs/vets-api#22961
These failures were related to a schema issue. See [Slack thread](https://dsva.slack.com/archives/C06ABHUNBRS/p1751469809273359?thread_ts=1738956153.238539&cid=C06ABHUNBRS) for more info.
> Revert "Skip Form21a flaky tests"

- modules/vaos/app/services/vaos/v2/appointments_service.rb
- modules/vaos/spec/factories/v2/appointment_forms.rb
- modules/vaos/spec/services/v2/appointment_service_spec.rb
- This work is to update the logic for determining telehealth modality. From the original ticket, here is the logic we now follow:
```
If appointment.kind === "telehealth" and vvsKind is not present:
Check appointment.extension.vvsVistaVideoAppt
If true, set telehealth modality to vaVideoCareAtHome.
If false, set modality to vaInPerson.
If vvsKind is present, continue using existing logic.
```
We are assuming that `vvsVistaVideoAppt` will always exist & return a boolean value
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/111669
- Unit tests to cover new scenarios
- Regression tested
> 111669 updated telehealth modality

- lib/lighthouse/veterans_health/models/immunization.rb
- lib/lighthouse/veterans_health/serializers/immunization_serializer.rb
- modules/my_health/spec/requests/my_health/v2/immunizations_spec.rb
This PR adds the human-readable location display name to the veterans health immunizations endpoint. The location information is sourced from the `immunization.location.display` field in the LH FHIR response.
> Add location name to veterans health immunizations

- app/controllers/concerns/authentication_and_sso_concerns.rb
- This PR adds an additional check to SSO auth that insures the `user.identity` redis exists before allowing authentication. And authenticated SSOe user should always have both a `user` redis record that is retrievable, and a `user.identity` record
- https://github.com/department-of-veterans-affairs/identity-documentation/issues/477
Authenticated routes
> Adding check for presence of user.identity to SSO auth

- app/models/saved_claim/veteran_readiness_employment_claim.rb
- app/sidekiq/vre/submit1900_job.rb
- lib/res/ch31_form.rb
- spec/factories/veteran_readiness_employment_claim.rb
- spec/lib/res/ch31_form_spec.rb
- This change handles forming the RES Service payload if no `veteranAddress` is submitted, setting it to `nil` instead of trying to access data that is not present. `veteranAddress` is an optional field on the form, and was not being treated as such, causing the form submission to fail on staging. My team is implementing a new version of the form in vets-website. This is not behind a feature toggle because the new form is not reachable in production.
- I work on the IIR Product team and we currently own the VR&E (Ch 31) form
- [1843](https://github.com/department-of-veterans-affairs/va-iir/issues/1843)
- This is all new functionality, supporting a new version of the Ch. 31 form.
This only impacts the new Ch. 31 form …
> Remove setting veteranAddress data if no address submitted

- modules/ivc_champva/app/models/ivc_champva/vha_10_7959a.rb
- modules/ivc_champva/spec/models/vha_10_7959a_spec.rb
This PR updates the metadata object created for form 10-7959a to indicate whether or not the submission is a resubmitted form.
It also adds basic unit tests
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/112032
- Previously the metadata object didn't reflect any of the resubmission data properties
NA
IVC CHAMPVA …
> 112032 - Add resubmission metadata properties to form submissions - form 10-7959a

- lib/sentry_logging.rb
Fixes the SentryLogging deprecation warning that appears during Rails application boot by moving the warning from module load time to method usage time.
Currently, the SentryLogging module shows a deprecation warning every time the application boots:
```
SentryLogging is deprecated and will be removed in October 2025. Use Vets::SharedLogging instead.
```
This creates noisy boot output and makes it harder to spot real issues during development.
**Move deprecation warning from module load to method usage:**
- ❌ **Before**: Warning appears when the module is required (at boot time)
- ✅ **After**: Warning appears only when `log_message_to_sentry` or `log_exception_to_sentry` methods are actually called
This is the first step in the broader SentryLogging → Vets::SharedLogging migration effort. …
> fix: move SentryLogging deprecation warning from boot to method usage

- config/features.yml
- modules/accredited_representative_portal/app/controllers/concerns/accredited_representative_portal/v0/representative_form_upload_concern.rb
- modules/accredited_representative_portal/config/initializers/bypass_olive_branch.rb
- modules/accredited_representative_portal/spec/requests/accredited_representative_portal/bypass_olive_branch_spec.rb
After adding new path normalization logic and observing that we won't break anything by bypassing for all existing client invocations in all environments.
Just some mess to get out of our hair before it languishes forever!
> [ARP] Always `BypassOliveBranch`. Once and for all

- modules/accredited_representative_portal/app/services/accredited_representative_portal/email_delivery_status_callback.rb
- modules/accredited_representative_portal/spec/services/accredited_representative_portal/email_delivery_status_callback_spec.rb
Update bug with configuring ARP VA Notify email callbacks.
- Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/114167
- Tests were updated.
ARP VA Notify email callbacks
> fix va callbacks

- .github/workflows/audit_service_tags.yml
- .github/workflows/code_checks.yml
- .github/workflows/gh-env-cleanup.yml
This PR tests a simpler approach to [fixing Docker cache issues](https://github.com/department-of-veterans-affairs/vets-api/pull/23021) by removing the ECR driver options from the Docker Buildx setup.
- Removed `driver-opts: image=${{ steps.ecr-login.outputs.registry }}/moby/buildkit:buildx-stable-1` from both workflows
- Reverted to original GitHub Actions cache (`type=gha`) instead of local cache
- Removed cache cleanup logic that was added in the previous approach
This tests whether the ECR driver options were the root cause of cache misses without the complexity of the previous caching solution.
> fix(ci): Remove ECR driver options to fix Docker cache

- config/initializers/betamocks.rb
- config/settings/test.yml
This PR changes the betamocks validation so it runs in all envs except prod (local, CI, dev, staging, and sandbox). There was an incident in May that would have been caught earlier is this was in place. This PR also changes the error handling so the custom error is reported. When this error happened in May, the error was:
```
bad argument (expected URI object or URI string) (ArgumentError)
```
It took some digging 🔬 to figure out where the true error was coming from. This PR rescues that `ArgumentError` and returns a more precise error. 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/109200
1. comment out `Settings.dmc.url` in test.yml. Expected result: CI should fail on startup. ✅ This happened. The [test …
> Validate betamocks config in all non-prod envs

- lib/mhv/account_creation/service.rb
- This PR adds a header to the MHV Account Creation API so that it caches the responses for a short period of time. This should prevent race conditions when calling the service
- https://github.com/department-of-veterans-affairs/identity-documentation/issues/515
- Testing will have to be done in staging, this should have no impact that we can measure on localhost
> [515] Add key to header for MHV Account Creation API service

- modules/claims_api/app/controllers/concerns/claims_api/poa_verification.rb
Adds some `current_user` details to logging when the POA verifier can't find (or finds too many) a representative in its search. This should let us more easily find the user by both login details and MPI details to see where things didn't match up. 
[API-47680](https://jira.devops.va.gov/browse/API-47680)
> API-47680 Add more logging when POA not found

- modules/simple_forms_api/spec/tasks/send_emails_by_date_range_spec.rb
- Skip the failing `send_emails_by_date_range_spec.rb` test due to flakey "Rake task not found" error
- This test was causing failures with the message: "Don't know how to build task 'simple_forms_api:send_emails_by_date_range'"
> Skip flakey send_emails_by_date_range test

- .github/CODEOWNERS
- This PR updates the CODEOWNERS for 10-10 health apps. An upcoming recompete merges the IVC portfolio with the Health Enrollment portfolio. This PR adds the 1010 BE group as a code owner to the IVC product portfolio.
none
- *What is the testing plan for rolling …
> [10-10] Add vfs-10-10 to champva-engineering owned codeowners entries

- lib/mhv/account_creation/service.rb
- This PR adds a header to the MHV Account Creation API so that it caches the responses for a short period of time. This should prevent race conditions when calling the service
- For now this should only apply in non-prod environments
- https://github.com/department-of-veterans-affairs/identity-documentation/issues/515
- Testing will have to be done in staging, this should have no impact that we can measure on localhost
> [515] Adding MHV account creation api cache header in non production environments

- db/migrate/20250717152023_create_event_bus_gateway_notification.rb
- db/schema.rb
We would like to implement code [in our callback](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/sidekiq/event_bus_gateway/va_notify_email_status_callback.rb) that retries `temporary-failure` Notifications.
We will use the VA Notify Notification ID in the callback to look up this object, which will include the template ID and the user account. We can then go through the user account to retrieve the participant ID (or ICN) and send it over to Notify alongside the template ID to be retried.
> [Event Bus Gateway]: Create DB table for tracking sent notifications

- config/features.yml
- lib/carma/client/mule_soft_auth_token_client.rb
- lib/carma/client/mule_soft_auth_token_configuration_v2.rb
- lib/carma/client/mule_soft_client.rb
- lib/carma/client/mule_soft_configuration_v2.rb
- spec/lib/carma/client/mule_soft_auth_token_client_spec.rb
- spec/lib/carma/client/mule_soft_auth_token_configuration_v2_spec.rb
- spec/lib/carma/client/mule_soft_client_spec.rb
- spec/lib/carma/client/mule_soft_configuration_v2_spec.rb
- Refactored the `CARMA::Client::MuleSoftClient` and `CARMA::Client::MuleSoftAuthTokenClient` classes and their corresponding configurations to be more readable.
-  No longer using the `form_10_10cg/carma/mulesoft/client_id` and `form_10_10cg/carma/mulesoft/client_secret` params since we use the token client to fetch a token for authentication. 
- Added a V2 that I will eventually rename back to the configuration after we fully test it in staging. I do not plan for both configurations to exist for long. 
- This PR is longer because I have specs for each side of the toggle, and the specs are largely very similar. 
- `caregiver_mulesoft_config_v2` flipper toggle
- …
> [10-10CG] Refactor MuleSoft client

- app/models/bgs_dependents_v2/base.rb
- spec/models/bgs_dependents_v2/base_spec.rb
- Pass nil to postal_cd where previously 'state' would have been passed, if the address is international. In V1, there was a Province field for international addresses and state was just passed as nil. However in V2, international addresses use the state field. State will still be passed to prvnc_nm after confirming that the field could take a longer string.
- assign state to nil before passing …
> pass nil to postal_cd and prvnc_nm if foreign address

- config/features.yml
- modules/claims_api/app/sidekiq/claims_api/one_off/header_hash_filler_job.rb
- modules/claims_api/spec/sidekiq/one_off/header_hash_filler_job_spec.rb
With the move away from md5 hashing of the headers of some models due to concerns with security & collisions, we still have many (> 500k) records without the new SHA256 `header_hash` in place. New records automatically have both fields generated, but old records from before the `header_hash` field have this remain empty.
This job will fill those in so that we may eventually remove the MD5 field.
Part 1 because we should test the behavior before turning this into scheduled job(s).
https://jira.devops.va.gov/browse/API-47460
This will affect old records that we have previously stored an md5 hash on and still need their modern header _hash filled.
> API-47460 Backfill header_hash (Part 1)

- modules/ivc_champva/app/models/ivc_champva/vha_10_7959a.rb
- modules/ivc_champva/spec/models/vha_10_7959a_spec.rb
This PR updates the metadata sent alongside form 10-7959a when we're dealing with a resubmission.
1. If it's a resubmission and there is a PDI number, there will be a metadata field `pdi_number` that contains the pdi number.
2. if it's a resubmission and there is a claim control number, there will be a metadata field `claim_number` that contains the claim control number.
3. If it's a new submission (not a resub), neither of these fields will be present.
4. These two properties are treated as mutually exclusive, so there will only ever be one of these metadata fields present depending on the circumstances
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/112032 …
> Update resubmission metadata properties - form 10-7959a

- config/features.yml
- Removes `mhv_medications_display_refill_content` feature toggle
- department-of-veterans-affairs/va.gov-team#114376
> Removes mhv_medications_display_refill_content feature toggle

- app/helpers/parameter_filter_helper.rb
- config/initializers/filter_parameter_logging.rb
- lib/logging/monitor.rb
Update logic to use `&` as the logic's lambda gets set to [] in the console which could cause confusion. We noticed in the `ConsoleFilterToggles` class that this `Rails.application.config.filter_parameters` gets overridden to `[]` when loading up the rails console `if defined?(Rails::Console)`. So if you were to test-run a Sidekiq job or something it would throw an error:
This fix is just to ensure it doesn't throw an error when running anything in the terminal
- Not ticket, noticed it while testing something else
> Update to avoid nil context

- lib/carma/client/mule_soft_client.rb
- lib/carma/client/mule_soft_configuration_v2.rb
- spec/lib/carma/client/mule_soft_client_spec.rb
- spec/lib/carma/client/mule_soft_configuration_v2_spec.rb
- Reverted change from https://github.com/department-of-veterans-affairs/vets-api/pull/23162 to generate the oauth bearer token in the client instead of the client configuration. 
- We had some 401 errors in prod after turning this on, and I suspect this is the culprit since the token has a higher likelihood of expiring when generating it in the config vs right when we call the perform method to make the request.
-  No longer using the `form_10_10cg/carma/mulesoft/client_id` and `form_10_10cg/carma/mulesoft/client_secret` params since we use the token client to fetch a token for authentication. 
- `caregiver_mulesoft_config_v2` flipper toggle
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/10107 …
> [10-10CG] Revert generating Oauth token in config to instead generate in perform in client class

- modules/representation_management/app/models/representation_management/accreditation_api_entity_count.rb
- modules/representation_management/app/services/representation_management/gclaws/client.rb
- modules/representation_management/app/sidekiq/representation_management/accredited_entities_queue_updates.rb
- modules/veteran/app/sidekiq/veteran/vso_reloader.rb
- modules/veteran/spec/sidekiq/veteran/vso_reloader_spec.rb
- *(Summarize the changes that have been made to the platform)*: All `webhook_url`s for `SlackNotify::Client` have been changed to a known good value.  I'm not sure how we got to a state where we were using two different values but this PR updates all to one value we know is working.  We know the good value is working because it is being used to ping our notifications channel as I write this.
- *(If bug, …
> Change slack webhook_url to known working value

- modules/mobile/spec/factories/maintenance_windows.rb
- modules/mobile/spec/models/service_graph_spec.rb
- modules/mobile/spec/requests/mobile/v0/maintenance_windows_spec.rb
- modules/mobile/spec/sidekiq/weekly_maintenance_window_logger_spec.rb
- This PR replaces our MW spec's references to EVSS with Lighthouse because the [next PR](https://github.com/department-of-veterans-affairs/vets-api/pull/23231) removes the final EVSS service, which would compromise the integrity of the spec. I believe the intent of each spec is maintained with these new references and associations
- https://github.com/department-of-veterans-affairs/va-mobile-app/issues/10514
> Replace EVSS references with Lighthouse in MW spec

- lib/kafka/enhanced_listener.rb
- lib/kafka/producer_manager.rb
- spec/lib/kafka/enhanced_listener_spec.rb
- Added additional broker statistics to the current `WaterDrop::Instrumentation::Vendors::Datadog::MetricsListener`.
- This required creating a subclass to add `service_check` functionality. This will invoke the corresponding method in the DataDog StatsD client.
- [VES #5129](https://github.com/department-of-veterans-affairs/VES/issues/5129)
- Also ran local [statsd-logger](https://github.com/jimf/statsd-logger) script to verify that DD metrics and service checks were being sent.
> Add DataDog metrics for broker health

- config/features.yml
This PR introduces two new feature toggles for controlling whether to add jumplinks between a filled PDF form and its redesigned overflow page. The feature toggles are not hooked up to code yet.
I'm on the Employee Experience team, which currently maintains the PDF generator.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/114060
No code is updated or introduced in this PR. Overview of testing plan:
- Each form that uses the v2 redesigned PDF generator must opt-in to jumplinks by adding configuration values for where jumplinks should jump to.
- On a per form basis, generated PDF rspec fixtures and test runs in staging/UAT will confirm that jumplinks work.
- We will roll this out first to form 0781, then to form 0969, the two forms currently using the redesigned PDF …
> Add two new feature toggles for jumplinks between PDF form and overflow page

- modules/claims_api/app/sidekiq/claims_api/one_off/header_hash_filler_job.rb
- modules/claims_api/spec/sidekiq/one_off/header_hash_filler_job_spec.rb
Optimizations for #23158. Doing a test run of the original on sandbox took 7 minutes to update 5000 records 😞 . This job refactors to add some common memory & processing-reduction steps to see if that improves performance, along with changing some arguments & logging so a naive call w/o args won't stall for 7 minutes 😛
#23158
> API-47460 Optimize header_hash filler job

- modules/decision_reviews/app/controllers/decision_reviews/v1/supplemental_claims_controller.rb
- modules/decision_reviews/spec/controllers/supplemental_claims_controller_spec.rb
- *(Which team do you work for, does your team own the maintenance of this component?)* Decision Reviews / yes
This PR fixes one of the most common errors we've been seeing that prevent users from submitting a Supplemental Claim via VA.gov. Lighthouse returns 422 Unprocessable Entity, with code 147 & message: "The (n) items provided did not match the definition", and a pointer to the `/data/attributes/evidenceSubmission/retrieveFrom` part of the schema (example [log from staging](https://vagov.ddog-gov.com/logs?query=env%3Aeks-staging%20service%3Avets-api%20%40payload.action%3A%22Overall%20claim%20submission%22&agg_m=count&agg_m_source=base&agg_t=count&clustering_pattern_field_path=message&cols=host%2Cservice&event=AwAAAZgyy2w8ph72lAAA …
> [Decision Reviews] Prevent schema errors related to evidence retrieval requests for duplicate facilities 

- modules/claims_api/app/sidekiq/claims_api/v2/poa_form_builder_job.rb
- modules/claims_api/lib/claims_api/v2/poa_pdf_constructor/base.rb
- modules/claims_api/lib/claims_api/v2/poa_pdf_constructor/individual.rb
- modules/claims_api/spec/lib/claims_api/v2/poa_pdf_constructor/individual_spec.rb
- modules/claims_api/spec/lib/claims_api/v2/poa_pdf_constructor/organization_spec.rb
- modules/claims_api/spec/sidekiq/v2/poa_form_builder_job_spec.rb
* The v2 PDF constructors where looking for the claimant (dependent) information based on the v1 form object.
This PR fixes that
* The tests for the PDf constructors were also using the v1 form.  This refactors those tests to expect the v2 form, and also removes the checks for actual PDf generation, preferring to make sure the data is correct and being handled correctly.
[API-48224](https://jira.devops.va.gov/browse/API-48224)
* Vet Claimant
* Dependent Claimant
modified:   modules/claims_api/app/sidekiq/claims_api/v2/poa_form_builder_job.rb
modified:   modules/claims_api/lib/claims_api/v2/poa_pdf_constructor/base.rb
modified:   modules/claims_api/lib/claims_api/v2/poa_pdf_constructor/individual.rb
modified:   modules/claims_api/spec/factories/claims_api_base_factory.rb
modified: …
> Api 48224 v2 poa pdf cleanup

- .github/CODEOWNERS
- lib/common/client/configuration/base.rb
- spec/lib/common/client/configuration/base_spec.rb
The [proc in breakers_matcher](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/common/client/configuration/base.rb#L104-L110) gets called for every Breakers service until one returns true (i.e. matches). It's been returning true prematurely for at least one service (`Rx`) because it will match by request URL on `SM` because there are many URI similarities between the two services. This PR makes it so the matcher sees that the `request_service_name` is "SM" and checks to see if it matches the `breakers_service.name` ("Rx"). They don't match, so the `breakers_matcher` returns false. yay. And when `request_service_name` does meet its match, it will return true. 
- Support request: …
> Don't match on URL if service name exists in breakers_matcher

- spec/requests/v0/form1010cg/attachments_spec.rb
- Skip 10-10CG attachment specs since they have been intermittently failing. We will look to refactor them to see why they are intermittently failing now. 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/112616 …
> [10-10CG] Skip flaky 10-10CG attachment specs

- modules/claims_api/app/controllers/claims_api/v2/veterans/power_of_attorney/request_controller.rb
- modules/claims_api/app/services/claims_api/power_of_attorney_request_service/accepted_decision_handler.rb
- modules/claims_api/app/services/claims_api/power_of_attorney_request_service/declined_decision_handler.rb
- modules/claims_api/spec/controllers/v2/veterans/power_of_attorney/request_controller_spec.rb
* Fixes a bug with the decision handler's return between the accepted and declined decisions.
* I missed taking into account the handling of the return when the decision is declined.
* This PR addresses this by adding a return (nil) and handling that to get back into the workflow of the decide method
* We also have two different returns based on `accepted` and `declined` and I had also missed that factor in this feature.
* The difference is one has a location URL in the response headers (accepted) and one does not (declined) 
[API-43734](https://jira.devops.va.gov/browse/API-43734)
* Added test for the different responses on the method
* Manual testing of the requets to verify behavior
(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything …
> Fixes return from decision handler

- config/initializers/filter_parameter_logging.rb
- lib/kafka/monitor.rb
- spec/lib/kafka/monitor_spec.rb
-  This adds `payload` to the `ALLOWLIST` for filter parameter logging. The `Logging::Monitor` class which is used to log failed/successful/exhausted Kafka Sidekiq jobs relies on the payload for some DataDog log filtering. We do scrub the payload of PII separately. 
- Additionally, I also added tags to the `Kafka::Monitor` StatsD call for easier filtering on the details we're interested in. 
- [VES #5241](https://github.com/department-of-veterans-affairs/VES/issues/5242)
> Added payload to ALLOWLIST; send custom tags to StatsD monitor

- modules/claims_api/app/controllers/claims_api/v2/veterans/power_of_attorney/request_controller.rb
- modules/claims_api/app/services/claims_api/power_of_attorney_request_service/accepted_decision_handler.rb
- modules/claims_api/app/services/claims_api/power_of_attorney_request_service/data_mapper/individual_data_mapper.rb
- modules/claims_api/app/services/claims_api/power_of_attorney_request_service/data_mapper/poa_auto_establishment_data_mapper.rb
- modules/claims_api/app/services/claims_api/power_of_attorney_request_service/decision_handler.rb
- modules/claims_api/app/services/claims_api/power_of_attorney_request_service/declined_decision_handler.rb
- modules/claims_api/spec/controllers/v2/veterans/power_of_attorney/request_controller_spec.rb
- modules/claims_api/spec/services/power_of_attorney_request_service/accepted_decision_handler_spec.rb
- modules/claims_api/spec/services/power_of_attorney_request_service/data_mapper/individual_data_mapper_spec.rb
- modules/claims_api/spec/services/power_of_attorney_request_service/data_mapper/poa_auto_establishment_data_mapper_spec.rb
- modules/claims_api/spec/services/power_of_attorney_request_service/decision_handler_spec.rb
* Two Bugs found in testing on Staging
* [First bug](https://vagov.ddog-gov.com/logs?query=%40named_tags.correlation_id%3A1d3e0e28-48ba-4284-a68f-dad552c00cd4%23416804&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AwAAAZhc_aJufiaqqgAAABhBWmhjX2JJREFBQjY4U1lpaXFCTDZnQVEAAAAkMDE5ODVkYjktY2IxMC00ZDEzLWIwMGEtMjY1NzJkOWJkMzdiAAh0oQ&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1750437361388&to_ts=1751042161388&live=true) a typo that caused an incorrect value to be sent as a param
* Tests added for the whole method to ensure no regression with this
* Possible Uncaught representative look up which would throw a 500
* Added check and error handling
* This PR also includes some general clean up …
> Fixing bugs from testing, some needed clean up

- config/features.yml
- modules/decision_reviews/app/sidekiq/decision_reviews/failure_notification_email_job.rb
- modules/decision_reviews/lib/decision_reviews/notification_callbacks/evidence_notification_callback.rb
- modules/decision_reviews/lib/decision_reviews/notification_callbacks/form_notification_callback.rb
- modules/decision_reviews/lib/decision_reviews/notification_callbacks/va_notify_local_testing_readme.md
- modules/decision_reviews/spec/lib/notification_callbacks/evidence_notification_callback_spec.rb
- modules/decision_reviews/spec/lib/notification_callbacks/form_notification_callback_spec.rb
- modules/decision_reviews/spec/sidekiq/failure_notification_email_job_spec.rb
- This PR removes feature flags that were used during our VA Notify callbacks migration. We had previously been using a custom callbacks endpoint our team built and maintained to track whether email notifications to veterans are successfully delivered. We've now switched over to the recommended VA Notify managed callback endpoint and are using the `VANotify::CustomCallback` class to manage our custom callback behavior. 
- This PR also addresses a few non-release-blocking issues we found during testing in staging, namely a missing `reference` field and `statsd_tags` (required by the `VANotify::DefaultCallback` class, and resulting in a non-critical error) not being passed correctly when instantiating the VANotify service with callback …
> Decision Reviews VA Notify callbacks migration cleanup, refactor, and minor bug fixes 

- lib/periodic_jobs.rb
- modules/claims_api/app/sidekiq/claims_api/one_off/header_hash_filler_batch_job.rb
- modules/claims_api/app/sidekiq/claims_api/one_off/header_hash_filler_job.rb
- modules/claims_api/spec/sidekiq/one_off/header_hash_filler_batch_job_spec.rb
Adds & schedules (gated behind the `lighthouse_claims_api_run_header_hash_filler_job` flag) an hourly batch job that enqueues an hours worth of HeaderHashFiller jobs for both the models that need it.
The schedule is set to only run the jobs from 9:10pm to ~4:00am Eastern time.
#23158 
https://jira.devops.va.gov/browse/API-47460
**Test plan:**
Keep `lighthouse_claims_api_run_header_hash_filler_job` disabled and manually run `#enqueue_jobs` to verify behavior & load on production. If clear, enable `lighthouse_claims_api_run_header_hash_filler_job` and let the schedule take over.
> API-47460 Backfill header_hash (Part 2)

- modules/claims_api/app/controllers/claims_api/v2/veterans/power_of_attorney/request_controller.rb
- modules/claims_api/spec/controllers/v2/veterans/power_of_attorney/request_controller_spec.rb
- modules/claims_api/spec/requests/v2/veterans/rswag_power_of_attorney_spec.rb
* Adds up front validation to ensure the rep ID passed in the submission matches that on the request.
* adds a test and updates related tests
[API-48515](https://jira.devops.va.gov/browse/API-48515)
modified:   modules/claims_api/spec/controllers/v2/veterans/power_of_attorney/request_controller_spec.rb
modified:   modules/claims_api/spec/requests/v2/veterans/rswag_power_of_attorney_spec.rb
> API-48515-upfront-rep-validation-for-decide

- modules/claims_api/app/sidekiq/claims_api/claim_uploader.rb
- modules/claims_api/spec/sidekiq/claim_uploader_spec.rb
This PR updates the `ClaimUploader` Slack alert language to better reflect what errors triggered the alert.
| [Jira ticket](https://jira.devops.va.gov/browse/API-47978) |
|-|
|<img width="981" height="764" alt="Screenshot 2025-07-31 at 13 47 31" src="https://github.com/user-attachments/assets/b762fd7b-8890-4761-b7ae-1ea6c7a5aa3a" />|
- Prior to this change the Slack alert language was a bit more vague. Now it includes more specifics related to the two cases where it might fire ('claims' or 'document'). …
> API 47978 - Update alert language

- modules/claims_api/app/controllers/claims_api/v2/veterans/power_of_attorney/request_controller.rb
- modules/claims_api/spec/controllers/v2/veterans/power_of_attorney/request_controller_spec.rb
* The `registration_id` comes in from the form as an integer so the check fails since `@representative.registration_id` is a string.
* This bug was just because the test I wrote I trusted but had the data wrong, fixing the test to send in an integer fixes this (and casting the `representative_id` to a string when checking obviously)
[API-40053](https://jira.devops.va.gov/browse/API-40053)
modified:   modules/claims_api/spec/controllers/v2/veterans/power_of_attorney/request_controller_spec.rb
(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, …
> Api 48515 fix validation check

- modules/claims_api/app/swagger/claims_api/description/v1.md
- modules/claims_api/app/swagger/claims_api/v1/swagger.json
This PR makes some minor text changes to the v1 API markdown file + regenerates the OAS to include the new text changes.
- [Jira ticket](https://jira.devops.va.gov/browse/API-45664)
NA
> API-45664 - Benefits Claims v1 OAS - Updates to align with v2

- app/models/accredited_individual.rb
- modules/representation_management/app/services/representation_management/accredited_entity_query.rb
- modules/representation_management/app/sidekiq/representation_management/accredited_entities_queue_updates.rb
- modules/representation_management/spec/requests/representation_management/v0/accredited_entities_for_appoint_spec.rb
- modules/representation_management/spec/services/representation_management/accredited_entity_query_spec.rb
- modules/representation_management/spec/sidekiq/representation_management/accredited_entities_queue_updates_spec.rb
- spec/models/accredited_individual_spec.rb
- *(Summarize the changes that have been made to the platform)*: This PR adds a `registration_number` value to any `AccreditedIndividual` records that have an `individual_type` of `'representative'`.  The `individual_type`s of `'attorney'` and `'claims_agent'` already set that value.  It also includes tests to ensure all three `individual_type`s set the value.  Additionally it removes the requirement for …
> Accreditation api add registration number to reps, remove location requirement for orgs

- db/schema.rb
- modules/accredited_representative_portal/db/migrate/20250731004219_add_recipient_type_to_ar_power_of_attorney_request_notifications.rb
This PR adds a new recipient_type field to ar_power_of_attorney_request_notifications for distinguishing notification targets
https://github.com/department-of-veterans-affairs/va.gov-team/issues/98668
*(Describe what parts of the site are impacted and*if*code …
> Add recipient_type to ar_power_of_attorney_request_notifications for distinguishing notification targets

- modules/claims_api/app/models/claims_api/auto_established_claim.rb
- modules/claims_api/app/sidekiq/claims_api/one_off/header_hash_filler_job.rb
- modules/claims_api/spec/sidekiq/one_off/header_hash_filler_job_spec.rb
* Fixes error when saving `header_hash` on record with an empty `form_data` field
* Adds ability to force a run even if the feature flag is disabled
#23158 Part 1
#23355 Part 2
https://jira.devops.va.gov/browse/API-47460
> API-47460 Fix when missing form_data field; Add job forcing

- app/services/bgs/dependent_v2_service.rb
- spec/services/bgs/dependent_v2_service_spec.rb
- This pull request refactors the `submit_pdf_job` method in the `BGS::DependentService` class to prevent errors being raised to the user if we have successfully sent the job to the backup path, and adds test coverage for the method. 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/115771
* an error is not shown in the UI
* the claim enters the backup path
Dependents
> Prevent error raising if backup triggered

- modules/claims_api/app/controllers/claims_api/v2/veterans/power_of_attorney/request_controller.rb
- modules/claims_api/spec/controllers/v2/veterans/power_of_attorney/request_controller_spec.rb
* Because we mock BGS calls in sandbox our `create` endpoint never returns an ID, which we need for the decide endpoint's URL. The only solution at the moment is to return a hard coded ID in sandbox used for mocking the return from `create` so we can use it in the `decide` endpoint.
[API-48516](https://jira.devops.va.gov/browse/API-48516)
modified:   modules/claims_api/spec/controllers/v2/veterans/power_of_attorney/request_controller_spec.rb
> API-48516-mocking-sandbox-id-return-from-create-for-decide

- modules/claims_api/app/controllers/concerns/claims_api/poa_verification.rb
- modules/claims_api/spec/concerns/claims_api/poa_verification_spec.rb
This PR adds some logging to the PoaVerification `exactly_one_rep_match?` method to help troubleshoot an edge case.
By adding an optional log triggered by the `find_by_poa_code` call, we hope to get some insight into POA verifications that fail despite (seemingly) returning a valid representative match.
This is meant to provide insight and is not expected to fix the actual issue described in the Jira ticket.
| [Jira ticket](https://jira.devops.va.gov/browse/API-48126)|
|-|
|<img width="966" height="742" alt="Screenshot 2025-08-05 at 14 46 37" src="https://github.com/user-attachments/assets/5ab34fd6-a629-4102-9017-e9cffdf59c8f" />|
- Previously there was no logging mechanism inside `exactly_one_rep_match?`. Now there is an optional extra param that triggers a log inside this call.
_Note: …
> API 48126 - Investigate poa_verification

- lib/pdf_fill/filler.rb
- modules/income_and_assets/lib/income_and_assets/benefits_intake/submit_claim_job.rb
- modules/income_and_assets/spec/lib/income_and_assets/benefits_intake/submit_claim_job_spec.rb
- spec/lib/pdf_fill/filler_spec.rb
This PR adds a new `omit_esign_stamp` option to the redesigned PDF generator, to allow omitting the built-in e-signature footer stamp in case it clashes with another footer stamp -- which is the case with the upcoming form 0969.
I work for the Employee Experience team, which owns maintenance of the redesigned PDF generator.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/114575
https://github.com/department-of-veterans-affairs/va.gov-team/issues/115787
- New behavior:
- Passing `omit_esign_stamp: true` to PdfFill will omit the e-signature stamp
- Updated test for `extras_redesign: true`
- New test for `extras_redesign: true, omit_esign_stamp: false`
- New test for `extras_redesign: false` …
> Allow redesigned 0969 to omit e-sign stamp to avoid footer clash

- app/services/form1010cg/service.rb
- app/sidekiq/form1010cg/submission_job.rb
- config/features.yml
- spec/services/form1010cg/service_spec.rb
- spec/sidekiq/form1010cg/submission_job_spec.rb
- Delete `caregiver_use_rails_logging_over_sentry` toggle and usage. We no longer need to toggle between Sentry and Rails logs. 
- We will delete it from the databases after merging and deploying
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/108604
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-Backendex …
> [10-10CG] Remove caregiver_use_rails_logging_over_sentry toggle and usage

- modules/claims_api/app/sidekiq/claims_api/one_off/header_hash_filler_job.rb
- modules/claims_api/spec/sidekiq/one_off/header_hash_filler_job_spec.rb
The batch job already counts & reports on remaining records. No need to do it for every individual job run, too.
#23158 Part 1
#23355 Part 2
#23371 Blank data fixes; forcing
https://jira.devops.va.gov/browse/API-47460
> API-47460 Remove redundant count query

- app/controllers/v0/event_bus_gateway_controller.rb
- config/features.yml
- spec/requests/v0/event_bus_gateway_spec.rb
After this is deployed, the actual Flipper should be removed via Flipper.remove in the console.
va.gov-team issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/102324
This feature is considered complete and so its feature flag can be removed.
> [CST] Removes references to Event Bus Gateway send-email flipper

- app/controllers/sign_in/client_configs_controller.rb
- app/controllers/sign_in/service_account_configs_controller.rb
- app/models/sign_in/client_config.rb
- app/models/sign_in/service_account_config.rb
- db/seeds/development/identity/client_configs.rb
- spec/controllers/sign_in/client_configs_controller_spec.rb
- spec/controllers/sign_in/service_account_configs_controller_spec.rb
- Updates client_configs and service_account_configs controller to work with new certs objects
- create certs and associations
-  destroy associations
- https://github.com/department-of-veterans-affairs/identity-documentation/issues/581
- `rails s`
- `rails c`
```ruby
```
Run these requests in the rails console - `rails c`
**Note:** if your token expires just request a new one
```ruby …
```
> [ID-581] - Update client configs api to accept certs attributes

- modules/claims_api/app/controllers/concerns/claims_api/revised_disability_compensation_validations.rb
- modules/claims_api/spec/requests/v1/forms/526_revised_validations_spec.rb
_This is a continuation of the work started [here](https://github.com/department-of-veterans-affairs/vets-api/pull/23421)._
This PR adds the separation location code validation functionality to the revised form 526 validation logic + introduces unit tests for that validator.
|| Business rules addressed|
|-|-|
|Strikethrough: obsolete rule; Red text: new messaging/behavior|<img width="865" height="234" alt="Screenshot 2025-08-06 at 17 09 59" src="https://github.com/user-attachments/assets/ac76dc9b-dee4-402c-b310-93d2b12fde04" />|
|[Jira ticket](https://jira.devops.va.gov/browse/API-47335)|
|-|
|<img width="967" height="801" alt="Screenshot 2025-08-06 at 08 58 46" src="https://github.com/user-attachments/assets/1e4504fb-25d0-40f1-81e1-83ca4124595c" />| …
> API 473351 - 526 Validation Rules 4a: `separationLocationCode`

- lib/lighthouse/benefits_claims/intent_to_file/monitor.rb
- spec/lib/lighthouse/benefits_claims/intent_to_file/monitor_spec.rb
- Updated pension ITF datadog monitor key prefixes to better differentiate v1 data from v0.
- Pension and Burials team to own this change.
- [*Link to ticket created in va.gov-team repo*](https://github.com/department-of-veterans-affairs/va.gov-team/issues/108930)
- *Describe the steps required to verify your changes are working as expected. …
> Added new key prefix to better differentiate v1 data

- modules/claims_api/app/controllers/claims_api/v2/veterans/power_of_attorney/request_controller.rb
- modules/claims_api/config/schemas/v2/decide.json
- modules/claims_api/spec/controllers/v2/veterans/power_of_attorney/request_controller_spec.rb
- modules/claims_api/spec/requests/v2/veterans/rswag_power_of_attorney_spec.rb
* Introduces schema file
* Adjusts related tests
* Cleans up validation code in controller
* Removes `validate_decide_params` method from controller, this is handled by the schema now.
* Removes casting the rep ID to a string since schema will enforce it as a string
[API-48575](https://jira.devops.va.gov/browse/API-48575)
* Send in a POST to the decide endpoint and it should accept a valid submission like:
```
{
"data": {
"decision": "DECLINED",
"declinedReason": "Reasons for the decline.",
"representativeId": "23456789" <------ (must match what you have in your DB and also match what the request was created with
}
}
}
```
* Sending in an invalid value for the rep ID or decision should return a 422
modified: …
> Api 48575 schema validation for decide endpoint

- app/controllers/concerns/authentication_and_sso_concerns.rb
- app/models/user.rb
- spec/controllers/v1/sessions_controller_spec.rb
- spec/models/user_spec.rb
- Update Cerner eligibility check to include facility ids
- https://github.com/department-of-veterans-affairs/identity-documentation/issues/582
- Sign in with SSOe
- You should see a `CERNER_ELIGIBLE` cookie in your browser
```ruby
[SessionsController] Cerner Eligibility -- { :eligible => true, :previous_value => nil, :cookie_action => :set, icn: <icn> }
```
cerner eligibility cookie
> [ID-582] Update cerner eligibility

- lib/sentry_logging.rb
Reverts department-of-veterans-affairs/vets-api#23060
Trying this while we debug CI tests. The output makes it hard to identify any failures. This will be temporary.
> Revert "fix: move SentryLogging deprecation warning from boot to method usage"

- config/settings.yml
- config/settings/development.yml
- config/settings/test.yml
This work is behind a feature toggle (flipper): *NO*
After a recent secrets and settings audit of the `vba_documents` module, we discovered three settings that were not in use anywhere in `vets-api` and could therefore be safely removed. This PR removes those settings from the repo.
My team (Lighthouse Banana Peels) owns the `vba_documents` module.
- [API-47722](https://jira.devops.va.gov/browse/API-47722)
- Confirmed that the settings were not in use anywhere in the application. Existing unit tests are all passing.
None
This PR impacts the `vba_documents` module only.
No specific feedback requested for this PR.
> API-47722: Remove Unused Settings for `vba_documents` Module

- modules/simple_forms_api/spec/tasks/send_emails_by_date_range_spec.rb
This was originally skipped in https://github.com/department-of-veterans-affairs/vets-api/pull/23123, but I saw all four tests failing again today in [this test run](https://github.com/department-of-veterans-affairs/vets-api/runs/47703525716) with the error:
```
simple_forms_api:send_emails_by_date_range when valid dates are provided FormSubmissionAttempts are not a Simple Form does not send a Notification::Email (modules.simple_forms_api.spec.tasks.send_emails_by_date_range_spec) failed 
RSpec::Core::MultipleExceptionError
\e[1mFailure/Error: \e[0mUnable to find matching line from backtrace
Don't know how to build task 'simple_forms_api:send_emails_by_date_range' (See the list of available tasks with `rake --tasks`)
Did you mean?  simple_forms_api:remediate_0781_and_0781v2_forms
Don't …
```
> Skip send_emails_by_date_range_spec

- modules/claims_api/app/controllers/concerns/claims_api/poa_verification.rb
- modules/claims_api/spec/concerns/claims_api/poa_verification_spec.rb
This PR rolls back the changes added in https://github.com/department-of-veterans-affairs/vets-api/pull/23414 now that we're reasonably confident the issue was due to misleading logging in the first place.
This PR also adjusts the logging output in `handle_not_found` so that it explicitly calls out when representative results are present via a name search, but not a match for the provided POA code.
| [Jira ticket](https://jira.devops.va.gov/browse/API-48126)|
|-|
|<img width="966" height="742" alt="Screenshot 2025-08-05 at 14 46 37" src="https://github.com/user-attachments/assets/5ab34fd6-a629-4102-9017-e9cffdf59c8f" />|
- *Describe the steps required to verify your changes are working as expected. Exclusively stating 'Specs run' …
> API 48126 - Remove debug logging from `exactly_one_rep_match?`

- modules/claims_api/app/controllers/claims_api/v2/blueprints/power_of_attorney_request_blueprint.rb
- modules/claims_api/app/controllers/claims_api/v2/veterans/power_of_attorney/request_controller.rb
* Small refactor to rename the blue printer method being called for the request `index`, `show` and `decide` endpoints
[API-48780](https://jira.devops.va.gov/browse/API-48780)
Submissions to the endpoint responded as expected.  All tests still green after change, but no new functionality was added, just a very small no-regret refactor.
modified:   modules/claims_api/app/controllers/claims_api/v2/blueprints/power_of_attorney_request_blueprint.rb
> API-48780-small-request-blueprinter-refactor

- app/models/saved_claim/veteran_readiness_employment_claim.rb
- spec/models/saved_claim/veteran_readiness_employment_claim_spec.rb
I'm Adam King, I work on the VA-IIR team, which owns this component.  
When the Chapter 31 form is submitted, an attempt is first made to send the `claim` to the VBMS eFolder.  If that attempt fails, a backup method to submit to a Lighthouse service is called into action.  Both of these services essentially save the state of the form.  VBMS accepts it as a PDF file which is filled out, Lighthouse accepts JSON.  After this step, the submission is sent to RES, which handles the application. 
During the Lighthouse request block, if such a method exists, [Lighthouse::SubmitBenefitsIntakeClaim.new.perform(id)](https://github.com/department-of-veterans-affairs/vets-api/blob/618ef094c0116ac02d3c719b44791b145635cd7f/app/models/saved_claim/veteran_readiness_employment_claim.rb#L323) calls a …
> Rename function - correct tightly-coupled object defect

- spec/lib/rx/client_spec.rb
- Removes the single instance found of `mhv_medications_migrate_to_api_gateway` feature toggle within the `spec` folder.
The Rx client configuration is currently using the `api_gateway` settings: [`lib/rx/configuration.rb`](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/rx/configuration.rb/#L30-L42)
- department-of-veterans-affairs/va.gov-team#115694
> Removes mhv_medications_migrate_to_api_gateway feature toggle

- Gemfile.lock
- config/features.yml
- Updates `vets-json-schema` dependency
- Feature toggle added for `GI Bill School Feedback Tool` education benefits question
- https://github.com/department-of-veterans-affairs/vets-website/pull/38215
- https://jira.devops.va.gov/browse/VEBT-2404
- N/A
- Screenshots linked in related `vets-website` PR
- Local testing to ensure VET TEC option appears accordingly when feature toggle is enabled
N/A
> VEBT-2404: FT - Implement follow up changes for 10297 (High Technology Program) into Edu benefits page

- modules/ivc_champva/app/controllers/ivc_champva/v1/uploads_controller.rb
- modules/ivc_champva/app/jobs/ivc_champva/tesseract_ocr_logger_job.rb
- modules/ivc_champva/spec/jobs/tesseract_ocr_logger_job_spec.rb
- modules/ivc_champva/spec/requests/ivc_champva/v1/forms/uploads_spec.rb
- modules/ivc_champva/spec/requests/ivc_champva/v1/integration/upload_data_transformation_ves_spec.rb
Reverts department-of-veterans-affairs/vets-api#23475
This is based off an old branch from 3 months ago, causing specs to fail and interrupting deployment.
> Revert "115118 background ocr fixes tempfile"

- app/controllers/v0/dependents_applications_controller.rb
- app/models/saved_claim/dependency_claim.rb
- app/sidekiq/bgs/submit_form674_job.rb
- app/sidekiq/bgs/submit_form674_v2_job.rb
- app/sidekiq/bgs/submit_form686c_job.rb
- app/sidekiq/bgs/submit_form686c_v2_job.rb
- app/sidekiq/lighthouse/benefits_intake/submit_central_form686c_job.rb
- app/sidekiq/lighthouse/benefits_intake/submit_central_form686c_v2_job.rb
- config/features.yml
- spec/controllers/v0/dependents_applications_controller_spec.rb
- spec/sidekiq/bgs/submit_form674_job_spec.rb
- spec/sidekiq/bgs/submit_form674_v2_job_spec.rb
- spec/sidekiq/bgs/submit_form686c_job_spec.rb
- spec/sidekiq/bgs/submit_form686c_v2_job_spec.rb
- spec/sidekiq/lighthouse/benefits_intake/submit_central_form686c_v2_job_spec.rb
- This pull request removes feature flags for dependents email notifications. It cleans up related flag definitions and updates tests accordingly. This simplifies the codebase by eliminating unnecessary Flipper checks and dead code paths, making the notification logic easier to read, test, and maintain.
Dependents
> Remove old flipper code

- app/services/bgs/dependent_v2_service.rb
- Instead of rebuilding the vet_info hash, pass encrypted_vet_info which had already been created to the backup path. This will help avoid the missing ssn issue.
[- *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses Jira*](https://github.com/department-of-veterans-affairs/va.gov-team/issues/116666)
- *Link to previous change of the code/bug …
> pass encrypted_vet_info instead of rebuilding vet_info

- lib/claim_letters/providers/claim_letters/lighthouse_claim_letters_provider.rb
- spec/lib/claim_letters/providers/lighthouse_claim_letters_provider_spec.rb
- instead of returning a full date stamp, only return year, month, day
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/115627 …
> bmt1/115627: only return date (no time stamp)

- modules/claims_api/app/controllers/claims_api/v2/veterans/power_of_attorney/request_controller.rb
- modules/claims_api/app/services/claims_api/power_of_attorney_request_service/index.rb
- modules/claims_api/spec/controllers/v2/veterans/power_of_attorney/request_controller_spec.rb
- modules/claims_api/spec/services/power_of_attorney_request_service/index_spec.rb
* Adds dependent `first_name` and `last_name` to the response, when it is included on the request, for returns in the index.  The names will appear inside the `claimant` key in the response (see screenshot below for example)
* In the Index class add the `claimant_icn` to the list if it is present.  It's presence means a dependent was included on the filing.
* We need to return to the request_controller to utilize the target_veteran build.
* Once back in the controller we get the target_veteran build from the dependent's ICN to get the first and last name and add them to the record
* This allows it to then show up in the Index method's response
* There were some small refactors done in the Index class to the altered functionality in an effort keep everything clean.  Just two bits of …
> API-48782-fix-index-response-with-claimant

- lib/pdf_fill/filler.rb
Form 21-686c-674 was logging too much info.
https://dsva.slack.com/archives/CBU0KDSB1/p1755289823971839
All of the logs contain this message:
So I'm removing the log completely. 
> Remove logging from lib/pdf_fill/filler.rb

- app/models/sign_in/client_config.rb
- app/models/sign_in/service_account_config.rb
- db/seeds/development/identity/client_configs.rb
- spec/controllers/sign_in/client_configs_controller_spec.rb
- spec/controllers/sign_in/service_account_configs_controller_spec.rb
- spec/models/sign_in/client_config_spec.rb
- spec/models/sign_in/service_account_config_spec.rb
- Update config certificate creation to initialize instead of create so if errors occur on config.save the errors are properly nested for multiple certs
```ruby
<ActiveModel::Error attribute=certs[0].pem, type=certificate is expired, options={}> 
```
- https://github.com/department-of-veterans-affairs/identity-documentation/issues/581
- `rails s`
- `rails c`
```ruby
```
Run these requests in the …
> Update config certificate api creation

- modules/burials/spec/lib/benefits_intake/submit_claim_job_spec.rb
- modules/dependents_verification/spec/lib/dependents_verification/benefits_intake/submit_claim_job_spec.rb
- modules/income_and_assets/spec/lib/income_and_assets/benefits_intake/submit_claim_job_spec.rb
- modules/pensions/spec/lib/benefits_intake/submit_claim_job_spec.rb
Fix flaky spec in SubmitClaimJob by updating the error matcher to use a regex. When jobs run in parallel, user_account_uuid may be passed as a symbol (:user_account_uuid) instead of a string, causing intermittent failures. This change ensures the spec reliably matches the ActiveRecord::RecordNotFound error regardless of symbol vs string formatting.
Other related specs were also updated because future RuboCop versions will not allow literal matches like …
> Updated Burials::BenefitsIntake::SubmitClaimJob to fix flakey failures

- app/models/sign_in/certificate.rb
- app/models/sign_in/client_config.rb
- app/models/sign_in/config_certificate.rb
- app/models/sign_in/service_account_config.rb
- spec/controllers/sign_in/client_configs_controller_spec.rb
- spec/sidekiq/sign_in/certificate_checker_job_spec.rb
- Update error handling so when certs are saved and have errors they show properly
- https://github.com/department-of-veterans-affairs/identity-documentation/issues/581
- `rails s`
- `rails c`
```ruby
```
Run these requests in the rails console - `rails c`
**Note:** if your token expires just request a new one
```ruby
assertion_payload = {
sub: …
```
> update certificate error handling

- lib/vets/type/primitive.rb
- modules/facilities_api/app/models/facilities_api/v2/lighthouse/facility.rb
- modules/facilities_api/app/models/facilities_api/v2/lighthouse/service.rb
- modules/facilities_api/app/models/facilities_api/v2/ppms/provider.rb
- modules/facilities_api/app/models/facilities_api/v2/ppms/specialty.rb
- modules/facilities_api/app/services/facilities_api/v2/lighthouse/response.rb
- modules/facilities_api/app/services/facilities_api/v2/mobile_covid/response.rb
- modules/facilities_api/app/services/facilities_api/v2/ppms/response.rb
- modules/facilities_api/spec/services/facilities_api/v2/lighthouse/client_spec.rb
- Virtus is being replace with `Vets::Model`. Differences include:
- There's no hash access for attributes `form[:attribute]` only dot notation `form.attribute`
- Syntax change for Array attributes
- Sorting uses a class method: `default_sort_by`
- booleans are temporarily `Bool`, until Virtus is completely gone
- This PR replaces `Common::Base` with `Vets::Model` and updates the _attributes_ and _implementation_ accordingly. 
- This change should not affect any functionality.
One change in the vets lib is to correct Boolean to String casting with `BooleanSafeString`
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/92444
> Replace Virtus with Vets::Model - FacilitiesApi

- modules/claims_api/app/controllers/concerns/claims_api/revised_disability_compensation_validations.rb
- modules/claims_api/spec/requests/v1/forms/526_revised_validations_spec.rb
_This is a continuation of the work started [here](https://github.com/department-of-veterans-affairs/vets-api/pull/23421)._
This PR adds more validation rules for disabilities.
|| Business rules addressed|
|-|-|
|Strikethrough: obsolete rule; Red text: new messaging/behavior|<img width="526" height="66" alt="Screenshot 2025-08-22 at 08 52 39" src="https://github.com/user-attachments/assets/69a24c87-8f7f-48d4-9de3-235bd2af591e" />|
|[Jira ticket](https://jira.devops.va.gov/browse/API-47335)|
|-|
|<img width="967" height="801" alt="Screenshot 2025-08-06 at 08 58 46" src="https://github.com/user-attachments/assets/1e4504fb-25d0-40f1-81e1-83ca4124595c" />|
- *Describe the steps required to verify your changes are working as expected. …
> API 47335 - 526 Validation Rules 7x: `disabilities`

- modules/vaos/app/services/vaos/v2/appointments_reason_code_service.rb
- modules/vaos/app/services/vaos/v2/appointments_service.rb
- modules/vaos/spec/services/v2/appointment_service_spec.rb
- modules/vaos/spec/services/v2/appointments_reason_code_service_spec.rb
- From Accessibility feedback we decided to use full weekday names (e.g. Friday) instead of abbreviations (e.g. Fri).
- United Appointments Experience
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/111877
N/A
Appointments
> Update preferred dates to use full weekday

- app/sidekiq/form_pdf_change_detection_job.rb
- spec/sidekiq/form_pdf_change_detection_job_spec.rb
- Add form pdf url to log when a new version is available. This makes it easier to get the new pdf file. 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/102906 …
> Add updated pdf form url to log in FormPdfChangeDetectionJob

- modules/vaos/app/models/vaos/v2/eps_appointment.rb
- modules/vaos/spec/models/v2/eps_appointment_spec.rb
- modules/vaos/spec/services/v2/appointment_service_spec.rb
- *(Summarize the changes that have been made to the platform)* : Adding new values to the EPS appointment class. These values are required on the frontend to enable rendering in the appointments list.
- *(Which team do you work for, does your team own the maintenance of this component?)* - Hydra/CC - yes.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/117401 …
> CC-117401: Add new variables to eps class

- modules/claims_api/app/services/claims_api/disability_compensation/docker_container_service.rb
- modules/claims_api/lib/claims_api/v2/error/lighthouse_error_mapper.rb
- modules/claims_api/lib/custom_error.rb
- modules/claims_api/lib/fes_service/base.rb
- modules/claims_api/spec/lib/fes_service/base_spec.rb
- modules/claims_api/spec/sidekiq/claim_custom_error_spec.rb
* Updates `get_error_info` to handle returning the text if `:errors` is the top key in `@original_body`
* Previously only `:messages` was handled, everything returned an empty array.
* Refactors the async flag so it is passed in correctly to the job instead of a default value being to the `custom_error_handler` since this service will be shared between v1 & v2
[API-49013](https://jira.devops.va.gov/browse/API-49013)
* You can manually test the errors by sending the data into FES that mimics the errors recorded in the following VCR cassettes:
*  `/claims_api/fes/submit/invalid_request`
* `/claims_api/fes/submit/bad_request` <--- For this one you will need to place that data in for `claim_data` in fes_service/base.rb to mimic it correctly
modified: …
> API-49103-update-custom-error-handler-for-fes

- modules/claims_api/lib/claims_api/v1/disability_compensation_fes_mapper.rb
- modules/claims_api/spec/lib/claims_api/v1/disability_compensation_fes_mapper_spec.rb
* Adds validations for the General / Headers
* Adds validations for veteran participant ID, transaction ID, claimant participant Id and form526 presence wrapped inside a data key
* [Attribute mapping doc](https://confluence.devops.va.gov/pages/viewpage.action?spaceKey=VAExternal&title=526+Attribute+Mapping)
* See required fields in image below
* One thing to note, _this PR does not yet address actually using the mapper in the workflow of submission, that is the final step, this is just building out the mappe_r.
[API-47336](https://jira.devops.va.gov/browse/API-47336)
new file:   modules/claims_api/lib/claims_api/v1/disability_compensation_fes_mapper.rb
new file:   modules/claims_api/spec/lib/claims_api/v1/disability_compensation_fes_mapper.rb …
> Adds General / Headers validations for v1 fes mapper

- modules/mobile/app/models/mobile/v0/adapters/vaos_v2_appointment.rb
- modules/mobile/app/models/mobile/v0/appointment.rb
- modules/mobile/app/serializers/mobile/v0/appointment_serializer.rb
- modules/mobile/docs/openapi.json
- modules/mobile/docs/schemas/Appointment.yml
- modules/mobile/spec/models/adapters/appointments_vaos_v2_adapter_spec.rb
- modules/mobile/spec/support/fixtures/VAOS_v2_appointments.json
- modules/vaos/app/controllers/vaos/v2/appointments_controller.rb
- modules/vaos/app/docs/vaos/v2/vaos_v2.yaml
- modules/vaos/app/schemas/appointments_index.json
- modules/vaos/app/services/vaos/v2/appointments_service.rb
- modules/vaos/spec/services/v2/appointment_service_spec.rb
- This PR updates the post processing steps for Cerner appointments as per design in the linked issue
- Use :identifier instead of :id to determine if an appointment is Cerner or not
- Do not include clinic information (service_name, physical_location) for Cerner appointments
- Include is_cerner in API response and update Mobile API to pass through the new field
- United Appointments Experience
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/117352
Appointments, Mobile
> Update Cerner appointment post-processing

- modules/check_in/app/services/travel_claim/service.rb
- modules/check_in/app/sidekiq/check_in/travel_claim_submission_job.rb
- modules/check_in/spec/services/travel_claim/service_spec.rb
- Added additional logging in the travel claim submission flow (`TravelClaim::Service#submit_claim` and `TravelClaimSubmissionJob#submit_claim`) to capture key state details (uuid presence, icn presence, appointment date presence, facility type, and a static service tag) for debugging production issues.
- This helps us collect more granular information when travel claims are being submitted in production, enabling us to better diagnose and resolve intermittent bugs affecting users.
- The solution adds Rails logger calls in the relevant service and job; these do not affect user-facing behavior, only what is captured in logs.
- Team: Platform Accessibility and Travel Claims. Yes, our team owns the maintenance of this component.
- No new …
> adding logging to nail down prod issues

- app/models/user.rb
- spec/controllers/v1/sessions_controller_spec.rb
- spec/models/user_spec.rb
- Only check for `cerner_id` for cerner eligibility 
- https://github.com/department-of-veterans-affairs/identity-documentation/issues/674
- https://github.com/department-of-veterans-affairs/identity-documentation/issues/545
- Login
- Find user and check eligibility if they have a 
- if they have a `cerner_id` returns `true`
- if they don't have a `cerner_id` returns `false`
```ruby
user = User.find(uuid)
user.cerner_eligible?
```
Cerner eligibility
> [ID-674] - Update cerner eligibility check

- modules/accredited_representative_portal/app/services/accredited_representative_portal/monitoring.rb
- modules/accredited_representative_portal/spec/services/accredited_representative_portal/monitoring_spec.rb
This is a tiny but important improvement.
Replaces manual error tagging (set_tag('error', ...)) with span.set_error(e) to ensure Datadog correctly captures and classifies span errors. Updates corresponding specs to assert set_error behavior instead of legacy tag checks.
This fix allows Datadog to classify the span as an official error instead of just having error metadata.
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide …
> refactor(monitoring): use official span.set_error for proper Datadog error tracing

- app/controllers/v0/profile/persons_controller.rb
- lib/va_profile/person/v2/service.rb
- modules/mobile/app/sidekiq/mobile/v0/vet360_linking_job.rb
- modules/mobile/spec/sidekiq/vet360_linking_spec.rb
- spec/lib/va_profile/person/v2/service_spec.rb
**NO LOGIC CHANGES, ONLY RENAMING SERVICES AFTER MIGRATION**
This PR renames VAProfile::V2::Person to VAProfile::Person::V2. The restructuring is part of the effort to deprecate and eventually eliminate the legacy Person V1 services.
The folder separation was intentionally maintained to avoid accidental modifications and reduce confusion during the integration process. Renaming these files improves clarity and helps developers more easily locate and work with …
> Renamed VAProfile::V2::Person to VAProfile::Person::V2

- modules/pensions/app/models/pensions/form_military_information.rb
- Virtus is being replace with `Vets::Model`. Differences include:
- There's no hash access for attributes `form[:attribute]` only dot notation `form.attribute`
- Syntax change for Array attributes
- Sorting uses a class method: `default_sort_by`
- booleans are temporarily `Bool`, until Virtus is completely gone
- This PR replaces `Virtus` with `Vets::Model` and updates the _attributes_ and _implementation_ accordingly. 
- This change should not affect any functionality.
One change in the vets lib is to allow valid iso8601 to pass without casting
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/111518
> Replace Virtus with Vets::Model - modules/pensions

- config/settings.yml
- config/settings/development.yml
- config/settings/test.yml
- modules/accredited_representative_portal/app/sidekiq/accredited_representative_portal/email_personalisations.rb
- modules/accredited_representative_portal/spec/sidekiq/accredited_representative_portal/email_personalisations_spec.rb
- Added `frontend_base_url` to `settings.yml`, resolving to staging, production, or localhost based on `accredited_representative_portal__base_url` or Rails.env.
- Updated `EmailPersonalisations#poa_request_url` to build links using this base URL instead of `Engine.routes.url_helpers`.
- Adjusted specs to expect URLs built from `frontend_base_url`.
Note: there is no staging.yml because the app is in production mode even in staging. Config gem relies on Rails.env to determine current environment so we need our own env var for this.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/98668
- *Describe the steps required to verify your changes are working as expected. Exclusively stating 'Specs run' is NOT acceptable …
> feat(arp): use environment-based frontend_base_url for POA request links

- config/features.yml
- Adds a toggle for showing an AI disclaimer to the chatbot/virtual agent
- Will be following up with vets-website PR to connect toggle to show disclaimer in the UI
- https://github.com/department-of-veterans-affairs/va-virtual-agent/issues/2531
- No new behavior added other than feature toggle
NA
Virtual agent
> add toggle

- modules/vaos/app/services/vaos/v2/appointments_service.rb
- Updates so that logging happens only if URL is missing and within 15 minutes of start time and adds fields to help diagnose why link may be missing (clinic/facility id and start time related boolean).
- UAE- Appointments team 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/117241
- Logged before, but not within time frame to help diagnose. Added more fields
N/A
Adds logging when processing appointment information for user, within a time frame around the appointment
Check that logs are correct in Datadog or rails console on staging/lower env
> UAE 117241 - Logging for missing telehealth link updated - changes to logging limits and fields

- modules/claims_api/app/controllers/concerns/claims_api/poa_verification.rb
- modules/claims_api/spec/concerns/claims_api/poa_verification_spec.rb
* Adjusts the error handling so we do not just raise a 401 in the event of any error
[API-48805](https://jira.devops.va.gov/browse/API-48805)
modified:   modules/claims_api/app/controllers/concerns/claims_api/poa_verification.rb
modified:   modules/claims_api/spec/concerns/claims_api/poa_verification_spec.rb
> API-48805-error-handling-update-in-poa-verification-file

- modules/claims_api/app/controllers/concerns/claims_api/v2/disability_compensation_validation.rb
- modules/claims_api/config/schemas/v2/526.json
- modules/claims_api/spec/lib/claims_api/v2/disability_compensation_validation_spec.rb
- modules/claims_api/spec/requests/v2/veterans/rswag_526_spec.rb
Reverts department-of-veterans-affairs/vets-api#23910
Need to revert this because we don't want the change to go out on a Friday (which would be the next daily deploy). I'll re-open the original PR on Monday 9/8/25.
> Revert "API 49489 - Add Federal Activation obligation dates requirement to v2 526 schema"

- config/initializers/filter_parameter_logging.rb
This PR adds a comment before the `ALLOWLIST` to make it clear that listing a key here disables filtering for that key across all of vets-api. 
This was discussed at the Backend CoP meeting. Meeting notes: https://vfs.atlassian.net/wiki/spaces/BCP/pages/4292280321/8+25+25
N/A
> Update comment in filter_parameter_logging.rb

- modules/claims_api/app/controllers/concerns/claims_api/v2/revised_disability_compensation_validation.rb
- modules/claims_api/spec/controllers/concerns/claims_api/v2/revised_disability_compensation_validation_spec.rb
- V2 FES Validations (Section 5 of the Validation guide, part 2)
- Note: This contains components from the previous PR that will get rebased out.
- Requirements doc attached for reference:
[EVSS->FES-validations-update.pdf](https://github.com/user-attachments/files/21722827/EVSS-.FES-validations-update.pdf)
Reference ticket: https://jira.devops.va.gov/browse/API-47330
526 v2 Validation Updates - Tracking Table
| Rule | Status | Implementation | Details |
|------|--------|----------------|---------|
| 5b(v) | IMPLEMENTED | Custom validator | internationalPostalCode for non-USA |
| 5b(vi) | IMPLEMENTED | Custom validator | Country list validation |
| 5b(vii) | IMPLEMENTED | Custom validator | BGS error handling |
| 5b(viii) | IMPLEMENTED | Custom validator | BGS unavailable handling |
> 47330 - V2 FES Validations (Section 5 of the Validation guide, part 2)

- config/features.yml
- This pull request makes a small configuration change to the `dependents_module_enabled` feature flag in `config/features.yml`. The feature will now be disabled by default in development environments. This is because the module isn't close enough to finished for standard use.
Dependents Benefits
> Disable Dependents Benefits module in development by default

- Gemfile
- Gemfile.lock
Dependabot [recently upgraded](https://github.com/department-of-veterans-affairs/vets-api/commit/1fd3c5de899081010bbb27b7bfcedb8f27be2a53) the `waterdrop` gem version from `2.8.6` to `2.8.7`. 
This caused several dependencies to be bumped as well which led to SSL cert location errors in the Kafka producer:
```
sasl_ssl://b-2.eventbuskafkasandb.xpmf9m.c3.kafka.us-gov-west-1.amazonaws.com:9098/bootstrap: kafka: error:80000002:system library::No such file or directory: calling stat(/tmp/static-openssl-3.0.16/ssl/certs)
```
and
```
rdkafka: [thrd:sasl_ssl://b-2.eventbuskafkasandb.xpmf9m.c3.kafka.us-gov-west-1]: sasl_ssl://b-2.eventbuskafkasandb.xpmf9m.c3.kafka.us-gov-west-1.amazonaws.com:9098/bootstrap: kafka: error:16000069:STORE routines::unregistered scheme: scheme=file
```
This is a …
> Revert dependabot's waterdrop version bump

- modules/veteran/app/sidekiq/veteran/vso_reloader.rb
- modules/veteran/spec/sidekiq/veteran/vso_reloader_spec.rb
The VSOReloader running in a daily job has been failing since late July, causing VSO reps and organizations to not be updated.
It fails because we automatically exit the job if we detect more than a 20% change in the count of organizations. We looked into the data, and in this case the organizations being removed were correctly being removed, they are mostly mock data or inactive organizations.
There is a manual bypass task that is defined to bypass this alert, but it appears to run too long to feasibly succeed in an ArgoCD session, probably by a significant degree. We were not able to run the task successfully on staging.
Secondly, we believe that the VSOReloader job does not actually remove organization records - we tested `Veteran::Service::Organization.import` and it appears to ingest …
> `VSOReloader::DECREASE_THRESHOLD` from `0.20` to `0.50`

- app/controllers/v0/health_care_applications_controller.rb
- spec/requests/v0/health_care_applications_spec.rb
- Update new logging and add statsD metrics to debug why some InProgressForms seem to not be getting deleted when they should. 
- I considered pulling out the logging to a concern, but the current plan is to turn this on in production and see if it is helpful. If we don't find anything we will just remove it. 
- `hca_in_progress_form_logging`
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/114338
- *Tests need to be written for both the flipper on …
> [10-10EZ] Add statsD metrics for InProgressForm deletes

- config/features.yml
- Simply adding a flipper toggle for use on the frontend
- Authenticated Experience Team AuthentiKnights
- Success: users are able to toggle the new experience on and off
- department-of-veterans-affairs/va.gov-team#113542
- N/A this is just adding the flipper
My VA Dashboard only when enabled
> 113542 - Add feature toggle for MyVA redesign switch

- app/models/sign_in/certificate.rb
- app/models/sign_in/client_config.rb
- app/models/sign_in/service_account_config.rb
- app/services/sign_in/assertion_validator.rb
- app/services/sign_in/base_assertion_validator.rb
- app/services/sign_in/client_assertion_validator.rb
- app/services/sign_in/errors.rb
- spec/controllers/v0/sign_in_controller_token_authorization_code_spec.rb
- spec/factories/sign_in/certificates.rb
- spec/models/sign_in/certificate_spec.rb
- spec/services/sign_in/assertion_validator_spec.rb
- spec/services/sign_in/base_assertion_validator_spec.rb
- spec/services/sign_in/client_assertion_validator_spec.rb
- spec/services/sign_in/code_validator_spec.rb
⚠️ Do not merge until Chatbot updates their private key ⚠️ 
- Check expiration of clients certs
- Only decode the JWT once by providing keyfinder proc to verify a signature
- Use built in JWT validity checks for some validations.
-  Other cleanup
- https://github.com/department-of-veterans-affairs/identity-documentation/issues/642
```ruby
assertion_payload = {
sub: 'vets.gov.user+0@gmail.com',
aud: 'http://localhost:3000/v0/sign_in/token',
iat: Time.zone.now.to_i,
exp: Time.zone.now.to_i + 1000,
scopes: …
```
> [ID-642] Update assertion validator 

- app/models/sign_in/certificate.rb
- app/sidekiq/sign_in/certificate_checker_job.rb
- spec/factories/sign_in/certificates.rb
- spec/models/sign_in/certificate_spec.rb
- spec/sidekiq/sign_in/certificate_checker_job_spec.rb
- Change `expiring` to `expiring_soon` - expiring in 60 days or less
- Add `expiring_later` - expiring in more than 60 days
- Change `active` to include `expiring_soon` and `expiring_later`
These should all print `true`
```ruby
ActiveRecord::Base.transaction do
expired = FactoryBot.build(:sign_in_certificate, :expired)
expired.save(validate: false)
soon  = FactoryBot.create(:sign_in_certificate, :expiring_soon)
later = FactoryBot.create(:sign_in_certificate, :expiring_later)
puts expired.expired?
puts soon.expiring_soon?
puts later.expiring_later?
puts soon.active?
puts later.active?
puts SignIn::Certificate.expired.pluck(:id).include?(expired.id)
puts SignIn::Certificate.expiring_soon.pluck(:id).include?(soon.id)
puts SignIn::Certificate.expiring_later.pluck(:id).include?(later.id)
puts …
```
> Update certificate active trait

- config/features.yml
- modules/travel_pay/app/services/travel_pay/expenses_service.rb
- modules/travel_pay/spec/services/expenses_service_spec.rb
- Adding a flag for a workaround for expense creation. The TP API requires a receipt for every expense call, but there are scenarios where may not want to include a receipt. This flag allows us to support the current behavior (for demoing) while the requirement is removed.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/119416
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/develope …
> [#119416] Travel Pay, Expense receipt placeholder

- .github/dependabot.yml
- Gemfile
- Gemfile.lock
Reverts department-of-veterans-affairs/vets-api#24130 because the version is pinned to `2.5.5` temporarily.
> Revert "Bump karafka-core from 2.5.5 to 2.5.6"

- modules/ivc_champva/app/services/ivc_champva/file_uploader.rb
- This work is behind a feature toggle (flipper): No
- Added logging to help confirm that the backend sets attachment ids correctly
- This is the solution because it adds visibility into which attachment ids are passed to downstream systems
- I work for the IVC Forms team and we own this module
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/119138
- Prior to this change the attachment ids were not being logged
- To verify that these …
> Champva 119138 added logging to help confirm that the backend sets attachment ids correctly

- app/models/saved_claim/dependency_claim.rb
- app/services/bgs/dependent_service.rb
- app/services/bgs/dependent_v2_service.rb
- app/sidekiq/vbms/submit_dependents_pdf_job.rb
- app/sidekiq/vbms/submit_dependents_pdf_v2_job.rb
- config/features.yml
- lib/dependents/monitor.rb
- *This work is behind a feature toggle (flipper): YES* 
- This PR restores targeted error logging using PII redaction capabilities added in #23760
On August 14, we discovered PII leaks in logs when error messages from VBMS (third-party service) were logged directly. As an immediate mitigation, we removed all error logging in the VBMS upload flow, which stopped PII leaks but eliminated crucial debugging context.
The current implementation prevents PII leaks but makes debugging difficult:
- Unable to distinguish between application errors and third-party service failures
- Loss of error context throughout the entire 686C-674 submission flow
- Overly broad removal of logging beyond just the VBMS response handling
This PR restores targeted error logging using PII redaction capabilities added …
> Restore safe error logging for 686C-674 VBMS upload flow

- modules/vaos/app/services/eps/provider_service.rb
- modules/vaos/spec/services/eps/provider_service_spec.rb
- *This work is behind a feature toggle (flipper):* **NO**
- *Summary of changes:*  
- Adds logging to StatsD for calls to EPS ProviderService endpoints when required parameters are missing or blank.
- Prevents sending requests to EPS provider-services endpoints without required parameters (`provider_id`, `provider_ids`, or `npi`) by raising an `ArgumentError` earlier in the service layer.
- Updates and adds unit tests to confirm that missing/blank parameters …
> eps logs and preventing sending no params

- app/helpers/parameter_filter_helper.rb
- config/initializers/filter_parameter_logging.rb
- spec/helpers/parameter_filter_helper_spec.rb
**This work is behind a feature toggle (flipper):** NO
Fixed the `ParameterFilterHelper` and Rails parameter filtering to properly
handle all data types and resolve console issues:
- Fixed `filter_params` returning `nil` in Rails console when
`filter_parameters` is empty
- Updated parameter filtering to handle all Ruby types (Integer, Symbol,
Boolean, etc.), not just Strings
- Modified the filter lambda to mutate values in place for compatibility with
Rails' `ActiveSupport::ParameterFilter`
**Bug:** When running in Rails console with `reveal!` enabled,
`ParameterFilterHelper.filter_params` returned `nil` instead of the original
params. Additionally, non-string values weren't being filtered properly.
**Solution:** Added `|| params` fallback in `ParameterFilterHelper` and updated
the filter …
> Correctly filter excluded fields

- modules/claims_api/app/controllers/concerns/claims_api/v2/revised_disability_compensation_validation.rb
- modules/claims_api/spec/controllers/concerns/claims_api/v2/revised_disability_compensation_validation_spec.rb
Implements FES (Form526 Establishment Service) validations for international mailing addresses and disability count limits in the Claims API v2.
- Added validation for international mailing addresses requiring city and country (FES rules 5.b.iii.2 and 5.b.iii.3)
- Added maximum 150 disabilities validation (FES rule 7.b)
- Leveraged existing schema validation for minimum 1 disability requirement (FES rule 7.a)
1. International Mailing Address (5.b.iii)
- City required for international addresses
- Country required for international addresses
2. Disabilities Count (7.a-b)
- Minimum 1 disability (handled by schema)
- Maximum 150 disabilities (custom validator)
> 47330 - FES V2 validations - Round2 - Part 1

- modules/income_and_assets/lib/income_and_assets/notification_email.rb
- modules/income_and_assets/spec/lib/income_and_assets/notification_email_spec.rb
If a value is missing from VANotify's email template then the email will not send. This PR adds some back up times to the email
- Add backup logic to email send
- Update test
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/119508 …
> 119508: Add backup dates for email

- lib/kafka/sidekiq/event_bus_submission_job.rb
- spec/lib/kafka/event_bus_submission_job_spec.rb
- In the sidekiq_retries_exhausted block of Kafka::EventBusSubmissionJob, the code was calling get_topic(use_test_topic:) as an instance method, but get_topic is defined as a class method on the Kafka module. This caused a NoMethodError when the exhausted callback executed, preventing the metric from being emitted.
- https://github.com/orgs/department-of-veterans-affairs/projects/1509/views/23?pane=issue&itemId=127917984&issue=department-of-veterans-affairs%7CVES%7C5383
- Added spec to test exhaustion block 
> Fix Kafka exhaustion error 

- app/sidekiq/form_pdf_change_detection_job.rb
- spec/sidekiq/form_pdf_change_detection_job_spec.rb
- Add additional logging for when the job starts/ends/fails to make tracking it running easier since it will be run daily. 
- `form_pdf_change_detection` flipper toggle
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/117843
- *What is the …
> Add additional logging for form pdf change detection job

- app/controllers/application_controller.rb
- app/controllers/concerns/traceable.rb
- app/controllers/sign_in/application_controller.rb
- app/services/sign_in/attribute_validator.rb
- spec/controllers/application_controller_spec.rb
- spec/controllers/sign_in/application_controller_spec.rb
Adds structured controller name logging to both SignIn and base ApplicationController to improve observability of MPI service interactions - which area of `vets-api` called the MPI service.
- Added `around_action :tag_with_controller_name` to `SignIn::ApplicationController`
- Added `around_action :tag_with_controller_name` to base `ApplicationController`
- Implemented `tag_with_controller_name` method using `SemanticLogger.named_tagged` in `Traceable` concern
- https://github.com/department-of-veterans-affairs/identity-documentation/issues/619
To make controller name tags visible in development logs, temporarily modify:
**config/environments/development.rb:**
```ruby
config.rails_semantic_logger.semantic = true   # Enable semantic mode
config.rails_semantic_logger.format = :json    # Use …
```
> [619] adds service tag logging to controllers

- config/features.yml
- lib/common/client/concerns/mhv_fhir_session_client.rb
- lib/common/client/concerns/mhv_jwt_session_client.rb
- lib/medical_records/client_session.rb
- modules/my_health/app/controllers/my_health/mr_controller.rb
- spec/lib/common/client/concerns/mhv_jwt_session_client_spec.rb
- spec/lib/medical_records/client_spec.rb
- spec/support/mr_client_helpers.rb
- Previously, MHV FHIR sessions were keyed by ICN. I have updated this to now be keyed by `current_user.uuid`.
- I am now persisting `user_uuid` when saving the session in `MhvFhirSessionClient`
- This is now behind a feature flag, `mhv_medical_records_uuid_for_jwt_session_locking`
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/118335
- This change should be fully transparent to the user.
- Accessing MHV Medical Records should work normally.
- Specs were added/updated to accommodate the change.
- Feature flag is tested on and off
> 118335 Update MHVJwtSessionClient redis caching to use appropriate values (with flag)

- app/services/sign_in/attribute_validator.rb
- spec/services/sign_in/attribute_validator_spec.rb
- This PR adds a boolean to the existing 'missing sec_id' log that is triggered when a user authenticates on Sign in Service and does not have a sec_id. This change shows whether the sec_id is truly missing, or is detected as missing because it's in PCE status
- https://github.com/department-of-veterans-affairs/identity-documentation/issues/731
Authentication
- Mock two users that you are able to authenticate with, for one user, remove any identifiers with `200PROV` to simulate missing sec_id. For the other user, update an existing `200PROV` identifier to end with `^PCE` instead of `^A`
- Authenticate with both users on Sign in Service, user with missing sec_id should create log: `mpi record missing sec_id, icn: xxxxx, pce_status: false`. User with PCE status sec_id should create log: …
> [731] Log missing sec_id PCE status when authenticating on sign in service

- modules/burials/lib/burials/notification_email.rb
- modules/burials/spec/lib/burials/notification_email_spec.rb
- modules/pensions/lib/pensions/notification_email.rb
- modules/pensions/spec/lib/pensions/notification_email_spec.rb
Add fallback logic to the date_received to avoid VANotify from failing to send emails if a value is nil
- Update Pension's NotifcationEmail class and its corresponding spec
- Update Burial's NotifcationEmail class and its corresponding spec
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/119781
- *What is the …
> 119781: Add backup logic for date_receive for notification emails

- .github/CODEOWNERS
- app/controllers/v1/post911_gi_bill_statuses_controller.rb
- app/models/saved_claim/education_benefits/va_10203.rb
- *(Summarize the changes that have been made to the platform)* Per this message from platform [here](https://dsva.slack.com/archives/C0460N83Y9G/p1754069591451589)... Searched codeowners for files the govcio-vfep-codereviewers own and filtered down to files that reference Sentry. Removed `include SentryLogging` from relevant files. There wasn't a need to replace with `Vets::ShareLogging` because there weren't any sentry logging methods being used and so the includes were probably leftover code.
- *(Which team do you work for, does your team own the maintenance of this component?)* VEBT, yes
- https://jira.devops.va.gov/browse/VEBT-3077
- https://jira.devops.va.gov/browse/VEBT-3078
> VEBT-3077/sentry logging cleanup

- modules/vaos/app/services/eps/appointment_service.rb
- modules/vaos/app/services/eps/provider_service.rb
- modules/vaos/spec/services/eps/provider_service_spec.rb
- **This work is behind a feature toggle (flipper):** NO
- **Summary:**  
Minor logging-related fixes to provider service handling.  
- The `get_provider_services_by_ids` method now returns an empty provider_services object instead of raising an exception when given a blank or nil provider_ids.
- The logic in `merge_provider_data_with_appointments` short-circuits and returns early if provider_ids is empty.
- Corresponding spec expectations updated to reflect new behavior.
- **Bug reproduction steps:**  
Call the provider service with blank or nil provider_ids.
- **Solution:**  
Returning an empty provider_services object improves robustness and avoids unnecessary errors for empty input, while still logging/monitoring the event.
- **Team ownership:**  
VAOS team; this component is …
> Minor log fixes

- app/controllers/v0/disability_compensation_forms_controller.rb
- lib/disability_compensation/loggers/monitor.rb
- spec/lib/disability_compensation/loggers/monitor_spec.rb
- Refactored logic of existing `DisabilityCompensation::Loggers::Monitor` to improve consistency across code syntax, log messaging, and Datadog metric naming
- added new method to track saved claim success
- implemented use of track_saved_claim_success in controller
closes department-of-veterans-affairs/va.gov-team#118697
n/a
- calls to disability compensation forms controller submit_all_claim action
> [118697] DisabilityCompensationFormsController uses Disability monitor

- config/identity_settings/environments/staging.yml
- This PR updates a simple typo in the SSOe get traits service. This service is not live, and this only impacts a staging setting, so this has no production impact
- Cannot test this change until it is deployed on staging. I took a cURL to the service at this new URL and tested manually on an argo pod
> Updating typo in URL for SSOe get traits service

- app/controllers/v0/health_care_applications_controller.rb
- app/sidekiq/hca/std_institution_import_job.rb
- spec/requests/swagger_spec.rb
- spec/requests/v0/health_care_applications_spec.rb
- spec/sidekiq/hca/std_institution_import_job_spec.rb
- *This work is behind a feature toggle (flipper): YES* - `hca_health_facilities_update_job`
- Still keeps scheduled runs of the job from flooding the Lighthouse DB, but allows individual runs for when the DB is empty and you try to retrieve Facilities.
- Health Enrollment 1010 EZ/CG
- *(If introducing a flipper, what is the success criteria being targeted?)* This is a permanent functionality switch.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/119304
- The `process` method now returns immediately unless the flag is enabled, but we still run the internal functionality when we can't proceed otherwise.
- I confirmed on local console that the job runs with the flag on, and does nothing with the flag off.
- 1010 EZ and CG Facilities dropdowns data updates …
> allow direct runs of the job while periodic runs stay flagged

- modules/decision_reviews/app/sidekiq/decision_reviews/saved_claim_status_updater_job.rb
- modules/decision_reviews/spec/sidekiq/sc_status_updater_job_spec.rb
- *This work is behind a feature toggle (flipper): **YES***
- To reproduce the bug in staging:
- Have a `SecondaryAppealForm` in error state with final_status: false (or missing) that's over 15 days old
- When the job runs and polls the Benefits Intake API, the API returns final_status: true (indicating the error is now permanent/final)
- The form gets updated with the new status containing final_status: true
- Bug: The monitoring function incorrectly logs …
> Decision Reviews: Fix status updater bug discovered in staging testing

- lib/kafka/enhanced_listener.rb
- spec/lib/kafka/enhanced_listener_spec.rb
- This PR updates which states of vets-api's connection to Kafka are treated as warnings per team discussions/recommendations.
- The recommendation from our partner team, the Event Bus team, is to warn when the connection to Kafka is in the `CONNECT` state.
- VES Submission Traceability. We do own this code/feature.
- https://github.com/department-of-veterans-affairs/VES/issues/5442 …
> VES 5442 Update Kafka status mapping for Datadog monitoring

- modules/my_health/catalog-info.yaml
Add .yaml file with new link to openapi_merged.yaml file from [platform-pst-console-ui-configuration]
After merge will then point to this .yaml file on code.va.gov
[[Meds / Documentation] Update API spec on code.va.gov /v1/prescriptions data](https://github.com/department-of-veterans-affairs/va.gov-team/issues/119850) va.gov-team#119850
To verify:
Make sure new .yaml file matches my-health-api.yaml with the new $text change
platform-pst-console-ui-configuration/backend-review-group/apis/my-health-api.yaml
*(Describe what parts of the site are impacted and*if*code touched other areas)*  No parts of va.gov are affected by this change.
(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you …
> Add my health api from code.va.gov with $text change

- .github/CODEOWNERS
- config/features.yml
- lib/common/client/concerns/mhv_session_based_client.rb
- spec/lib/common/client/concerns/mhv_session_based_client_spec.rb
- Hash the user_key (MHV Correlation ID) when creating MHV sessions to avoid storing PII in Redis
- This work is behind the Flipper `mhv_hash_id_for_mhv_session_locking`
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/118335
- This change should be fully transparent to the user.
- Accessing MHV Medical Records, Secure Messaging, and Medications should work normally.
- A spec was added to test the change.
- Feature flag is tested on and off
The impact of this is fairly widespread, as multiple clients and products use the `MHVSessionBasedClient` module to create and manage MHV sessions.
> Hash the MHV Correlation ID when locking MHV sessions

- modules/claims_api/lib/claims_api/v2/disability_compensation_fes_mapper.rb
- modules/claims_api/spec/lib/claims_api/v2/disability_compensation_fes_mapper_spec.rb
This PR updates the V2 FES mapper to extract all secondary disabilities nested inside primary disabilities and elevate them to the top-level disabilities array.
This maintains backwards compatibility with submissions that include secondary disabilities while also accounting for FES's lack of support for secondary disabilities.
|[Jira Ticket](https://jira.devops.va.gov/browse/API-50205)|
|-|
|<img width="901" height="730" alt="Screenshot 2025-09-26 at 11 06 32" src="https://github.com/user-attachments/assets/8bdf2367-81b2-4c29-9e7c-39b6dbd530d8" />|
To verify, 
- Add a byebug on line 258 of `modules/claims_api/lib/claims_api/v2/disability_compensation_fes_mapper.rb`
- Ensure the lighthouse_claims_api_v2_enable_fes flag is enabled
- Submit a request to …
> API-50205 - Update V2 FES mapper to handle secondary disabilities

- modules/claims_api/lib/claims_api/v2/disability_compensation_fes_mapper.rb
- modules/claims_api/spec/lib/claims_api/v2/disability_compensation_fes_mapper_spec.rb
Reverts department-of-veterans-affairs/vets-api#24408
Reverting because we're supposed to hold off on merges to master while a potential gov shutdown is in the works.
> Revert "API-50205 - Update V2 FES mapper to handle secondary disabilities"

- .github/workflows/code_checks.yml
Add `--format documentation` to the rspec command in CI to show each test description as it runs. Since [containerizing our parallelization](https://github.com/department-of-veterans-affairs/vets-api/pull/24419), our test logs are 1/24 the size previously allowing us to use the more useful verbose output.
When CI tests timeout, there's currently no output showing which test was running when the timeout occurred. This makes [debugging timeouts very difficult](https://dsva.slack.com/archives/CBU0KDSB1/p1759251128678749).
- Added `-o '--format documentation'` to the `parallel_test` command in the code_checks workflow
- Tests will now output their descriptions as they run, making it easy to identify hanging tests
Top 5 test groups by total lines:
- Group 16: 22,177 lines (12,167 test output) …
> ci: add documentation format to rspec for test visibility

- app/models/saved_claim_group.rb
- modules/dependents_benefits/lib/dependents_benefits/claim_behavior.rb
- modules/dependents_benefits/lib/dependents_benefits/claim_processor.rb
- modules/dependents_benefits/lib/dependents_benefits/monitor.rb
- modules/dependents_benefits/lib/dependents_benefits/sidekiq/dependent_submission_job.rb
- modules/dependents_benefits/spec/lib/dependents_benefits/sidekiq/dependent_submission_job_spec.rb
- This change is in a route not yet in use. 
- This pull request introduces the use of the SavedClaimGroup to the claim submission and tracking logic for dependent benefits. The main changes include adding explicit status constants and helper methods to the `SavedClaimGroup` model, refactoring job handling to improve status updates and error handling, and enhancing monitoring and notification capabilities throughout the submission pipeline.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/118683
Dependents Benefits Module
> Dependents Module | Add claim groups to submission job

- app/policies/mhv_messaging_policy.rb
- modules/mobile/app/controllers/mobile/messaging_controller.rb
- modules/mobile/spec/requests/mobile/v0/messaging/health/all_recipients_spec.rb
Mobile API messaging controller was not adding uuid to the session so current_user = User.find(session.user_uuid) is failing making it so regardless of the OH flipper being on mobile never includes the path param for the upstream to actually fetch the data. Take 2 - this time with tests
https://github.com/department-of-veterans-affairs/va.gov-team/issues/120991
- *Describe the steps required to verify …
> Bug user lookup failing mobile sm oh flipper

- .github/workflows/build.yml
- .github/workflows/code_checks.yml
- .github/workflows/deploy-template.yml
Implements the production-bypass branch infrastructure for the shutdown code freeze.
- **master branch** → deploys to `dev` and `staging` only
- **production-bypass branch** → deploys to `prod` and `sandbox` only
- Split `build.yml` deploy job into two separate jobs (`deploy_dev_staging` and `deploy_prod_sandbox`)
- Added `check_branch_protection` job with guardrail messaging
- Updated `code_checks.yml` to run on both `master` and `production-bypass` branches
- Updated `deploy-template.yml` to allow releases from `production-bypass` branch
Refs department-of-veterans-affairs/va.gov-team#121134
See: https://vfs.atlassian.net/wiki/spaces/LEAD/pages/4378460179/Production+Bypass+Deploy+Plan+Shutdown+Code+Freeze
> Add production-bypass branch for code freeze deploys

- .github/workflows/ready_for_review.yml
Fixes the workflow status check pagination issue that was causing false failures in the "Check Workflow Statuses" job.
**Problem:** The `gh run list` commands in the workflow status check were using the default limit of 30 results. When a PR's successful workflow run is older and falls outside the first 30 results, the check incorrectly reports it as failed.
**Solution:** Added `--limit 100` to both `gh run list` commands to check the last 100 workflow runs instead of just 30.
Issue observed in #24496.
> Fix workflow status check pagination issue

- Dangerfile
- This work is behind a feature toggle (flipper): **NO**
- Updated the Dangerfile `ChangeLimiter` to exclude spec files from PR line count checks
- **Problem:** Spec files can be verbose, causing developers to hit PR size limits even when adding appropriate test coverage alongside feature changes
- **Solution:** Added `spec/**/*.rb` and `modules/*/spec/**/*.rb` to the `EXCLUSIONS` array so all spec files are ignored in line count calculations (similar to existing exclusions for fixtures, factories, and VCR cassettes)
- **Team:** Backend Platform / discussed in Backend CoP on 9/15
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/121029
- **Old behavior:** Spec files counted toward the 200-line warning and 500-line error thresholds
- **New behavior:** Spec files are …
> 121029 exclude test files

- modules/dependents_benefits/app/controllers/dependents_benefits/v0/claims_controller.rb
- modules/dependents_benefits/app/models/dependents_benefits/form_profiles/va_686c674.rb
- modules/dependents_benefits/lib/dependents_benefits/monitor.rb
- modules/dependents_benefits/lib/dependents_benefits/sidekiq/dependent_submission_job.rb
- modules/dependents_benefits/lib/dependents_benefits/user_data.rb
- modules/dependents_benefits/spec/controllers/dependents_benefits/v0/claims_controller_spec.rb
- modules/dependents_benefits/spec/lib/dependents_benefits/user_data_spec.rb
- Add the encrypted user hash (as currently passed to Dependents jobs) to the parent saved claim group.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/118685
Dependents Benefits module
> Add user hash to claim group

- Gemfile.lock
Updates the `uri` gem from 1.0.3 to 1.0.4 to address CVE-2025-61594, a credential leakage bypass vulnerability.
- **CVE**: CVE-2025-61594
- **Title**: URI Credential Leakage Bypass over CVE-2025-27221
- **URL**: https://www.ruby-lang.org/en/news/2025/10/07/uri-cve-2025-61594
- Updated `uri` gem to version 1.0.4 in Gemfile.lock
> fix: update uri gem to 1.0.4 to address CVE-2025-61594

- lib/caseflow/schema/appeals_issue.json
- spec/lib/caseflow/service_spec.rb
- spec/requests/v0/appeals_spec.rb
- spec/support/schemas/appeals_issue.json
Reverts department-of-veterans-affairs/vets-api#24496
This branch was accidentally deployed to production before testing had been done.
Support ticket thread: https://dsva.slack.com/archives/CBU0KDSB1/p1759768363078149
> Revert "#121184 [Benefits Management Team 2] Update JSON schema for appeal issues to allow for `null` descriptions"

- .github/CODEOWNERS
The `benefits-admin` group was removed in https://github.com/department-of-veterans-affairs/vets-api/pull/24318. (The `benefits-admin` group was redundant since the entries are already covered by our team's `benefits-management-tools-be` group.)
This PR cleans up four remaining references to `benefits-admin` that were still present in `CODEOWNERS` and causing the file to fail validation.
Currently on `master` the GitHub UI shows `This CODEOWNERS file contains errors`:
```
Unknown owner on line 512: make sure the team @department-of-veterans-affairs/benefits-admin exists, is publicly visible, and has write access to the repository
…-affairs/backend-review-group @department-of-veterans-affairs/benefits-admin
Unknown owner on line 568: make sure the team …
```
> Remove redundant code owner entries for benefits-admin

- modules/dependents_benefits/lib/dependents_benefits.rb
- modules/dependents_benefits/lib/dependents_benefits/benefits_intake/submission_handler.rb
- modules/dependents_benefits/lib/dependents_benefits/engine.rb
- modules/dependents_benefits/spec/lib/dependents_benefits/benefits_intake/submission_handler_spec.rb
- This work adds `SubmssionHandler` for the backup path for `DependentsBenefits` module. We decided that it's best to keep lighthouse submissions as the combined `686c-674` form since we don't really know if they can process separated submissions correctly
- Lifetstage Benefits - Dependents Benefits 
- *https://github.com/department-of-veterans-affairs/va.gov-team/issues/106768*
- *Describe what the old behavior was prior to …
> Add submission handler for dependents benefits
