spec/jobs/evss/retrieve_claims_from_remote_job_spec.rb, spec/jobs/evss/update_claim_from_remote_job_spec.rb
Small refactor to eliminate Rspec warnings that are thrown when the specs run.
> WARNING: Using the `raise_error` matcher without providing a specific error or message risks false positives...
=> refactor specs to eliminate rspec warnings

spec/lib/vet360/contact_information/service_spec.rb
[This request](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/11692#issuecomment-407748989) from @steve-gov states:
> we should have logging in place to let us know that this user attempted to procure a Vet360ID and failed for $error reason.
As part of this, investigate if this applies to both the `POST` initialize a Vet360 ID endpoint, as well as the transaction status checking endpoint.
**This PR is to amend #2194, to fix an incorrectly named example**
=> Rename example to reflect correct tag

app/models/emis_redis/model.rb, lib/emis/responses.rb
Fixes https://github.com/department-of-veterans-affairs/vets.gov-team/issues/11205
Development environments were seeing issues deserializing cached EMIS responses. I think it
was basically a variant of this problem: https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#autoloading-and-sti
in that the deserialization was happening in `Oj`'s C code which was not autoloading-aware, hence
was running into undefined classes when deserializing cached objects.
This resolves the issue in my development environment, but willing to try other approaches based on feedback.
=> Fix autoloading for redis-cached EMIS responses

app/controllers/concerns/vet360/writeable.rb, app/controllers/v0/addresses_controller.rb, app/controllers/v0/profile/alternate_phones_controller.rb, app/controllers/v0/profile/emails_controller.rb, app/controllers/v0/profile/full_names_controller.rb, app/controllers/v0/profile/primary_phones_controller.rb, app/controllers/v0/profile/service_histories_controller.rb, app/policies/evss_policy.rb, spec/spec_helper.rb
During the UAT process for the Profile form, we added a lot of sentry logging to debug issues.  This needs to be removed, once the feature is in production, and working as desired.|
* Essentially reverse changes made in commit 77ffebb
=> Remove extra sentry logging added during Profile debugging

app/models/personal_information_log.rb, config/settings.yml, lib/common/client/middleware/logging.rb, lib/mvi/configuration.rb, spec/lib/common/client/middleware/logging_spec.rb, spec/lib/mvi/service_spec.rb, spec/models/personal_information_log_spec.rb
MVI profile lookups respond with a high rate of not founds. We suspect that this issue is caused either by a lack of associated MVI record, or potentially a misconfiguration in the request itself. 
Some recent stats for failure rates are provided in https://github.com/department-of-veterans-affairs/vets.gov-team/issues/12126. 
In order to collect more information, this change logs MVI request and response data to a `PersonalInformationLog` record. It provides a faraday middleware that can be used to log requests to any service configured with the common client when necessary.
Not applicable
Debug capability, link provided
Records sensitive information to a trusted location designed for temporary storage.
=> Log MVI findProfile lookups to temp PII table

config/betamocks/services_config.yml, config/settings.yml
We are trying out the iHub external service through their "Appointments" endpoint. We now have this integrated into Vets-API. Next step is to enable betamocks support so that the FE can build out the UI, with the standard iHub Appointments endpoint response in place to build against.
**Sibling PR in Mockdata repo**
https://github.com/department-of-veterans-affairs/vets-api-mockdata/pull/49
**Sibling Devops PR**
https://github.com/department-of-veterans-affairs/devops/pull/3142
Betamocks for appointments endpoint will respond with default data.
This cannot currently be flexible to create unique beta mock data responses, based on the signed in user.  This is due to a [regular expression matching rule in the betamocks gem](https://github.com/department-of-veterans-affairs/betamocks/blob/maste …
=> 12289-ihub-appointments-betamocks

app/controllers/v0/disability_compensation_forms_controller.rb, app/models/async_transaction/evss/va526ez_submit_transaction.rb, config/routes.rb, spec/request/disability_compensation_form_request_spec.rb
As per [this ticket](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/12024), we need an endpoint that takes a job_id and returns the status and response of that submission transaction.
=> Status endpoint

app/controllers/v0/disability_compensation_forms_controller.rb
Async job required user uuid, not user object (since jobs cannot be passed objects).
=> Fixed to pass user uuid, not user object

Gemfile.lock
Bumping json schema version for form526 schema updates
=> Update schema version

app/models/base_facility.rb, modules/va_facilities/app/controllers/va_facilities/v0/facilities_controller.rb, modules/va_facilities/spec/requests/facilities_request_spec.rb
Reported in https://github.com/department-of-veterans-affairs/vets-api-clients/issues/13
Omits dod_health facilities from the formerly `all` query used to generate the bulk facilities output. These facilities aren't really applicable to the VA facilities semantics, and are in the table for use by the autocomplete endpoint used elsewhere in vets.gov. 
Ultimately I'd like a cleaner solution for this, it's awkward to have that conditional all over the place, but this will un-break the bulk facilities API for the moment.
Seeded dod_health facilities in localhost, confirmed that with change in place, bulk facilities endpoint no longer throws a 500 error. Seeded a dod_health facility in the bulk facility spec. 
Bulk facilities resource no longer throws 500 error.
=> VA_Facilities: Omit dod_health pseudo-facilities

db/schema.rb
Had some migrations that were only run locally and later removed. However the schema file made it into a PR with a version of db/schema.rb which had those migrations applied. This PR reverts the schema file so that it matches the current migration files.
=> remove table from schema.rb that does not have a matching migration

app/workers/evss/disability_compensation_form/submit_form526.rb, db/schema.rb, spec/jobs/evss/disability_compensation_form/submit_form526_spec.rb
Add sentry logging for the form526 submission job when there is a hard failure or the job has exhausted.
Rspec tests.
Will be tested on staging.
=> Add sentry logging when theres a hard fail on the job (or its exhausted)

app/controllers/concerns/accountable.rb, app/controllers/v0/sessions_controller.rb, config/settings.yml, config/settings/test.yml, spec/controllers/v0/sessions_controller_spec.rb, spec/spec_helper.rb
The new `Account` table will establish a Vets-API generated uuid per user, removing our dependency on third parties.  There will be one unique record per user.  
To establish these new records, we favor checking/creating one on login.
https://github.com/department-of-veterans-affairs/devops/pull/3186
=> Creates an Account record on user login

app/models/form_profiles/complaint_tool.rb, spec/models/form_profile_spec.rb
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/12560
use 2 letter country codes for prefill
test in staging with a verified user that has a prefilled address
=> Country field not validating when information is prefilled

Dockerfile, app/models/evss_claim_document.rb, app/workers/central_mail/submit_saved_claim_job.rb, config/settings.yml, lib/pdf_info.rb, lib/shrine/plugins/validate_unlocked_pdf.rb, modules/vba_documents/app/workers/vba_documents/upload_processor.rb, spec/jobs/central_mail/submit_saved_claim_job_spec.rb, spec/lib/pdf_info/metadata_spec.rb, spec/lib/vic/service_spec.rb, spec/request/documents_spec.rb
The Ruby PDF::Reader library has a known issue where it is unable to open pdfs
that are close to the spec, but may violate it in some minor way (see:
https://github.com/yob/pdf-reader/issues/213). This results in users sending
pdfs that they can open on their device that we reject as being invalid.
This replaces that library with the pdfinfo command line tool based on the
poppler pdf rendering library that is more flexible with regards to pdf spec
compliance and gives us the data we need: pages counts and encryption
information.
=> Use pdfinfo tool to validate incoming pdf documents

app/workers/evss/disability_compensation_form/submit_uploads.rb, spec/jobs/evss/disability_compensation_form/submit_uploads_spec.rb
The Sidekiq panel in staging is reporting an issue when trying to run `perform_async` for submitted uploads for the form 526. This may be due to the job being a class method instead of an instance method (which is whats described in the Sidekiq docs). This change will update this method to be an instance method.
spec tests.
Testing this change in staging.
=> Turn perform into an instance method. Update test

app/models/form_profiles/va526ez.rb, spec/models/form_profile_spec.rb
Special Issues has been removed entirely from the form workflow. Its not supported on EVSS's end and will actually raise an exception if included.
Json schema changes are in this PR: https://github.com/department-of-veterans-affairs/vets-json-schema/pull/251
rspec tests.
Staging run throughs.
=> 526 remove specialissues prefill

app/models/disability_contention.rb, db/migrate/20180829235636_create_disability_contentions.rb, db/migrate/20180830212109_add_disability_contentions_medical_index.rb, db/migrate/20180830212116_add_disability_contentions_lay_index.rb, db/migrate/20180831155019_add_code_index_to_disability_contentions.rb, db/schema.rb, spec/factories/disability_contentions.rb, spec/models/disability_contention_spec.rb
Adds the model and migration for disability contentions (categories of conditions) which will be used for auto-suggesting disabilities in the all claims form (ch 2.2)
Unit tests, local db seeding
Dev API testing once all the contentions are loaded
=> disability contentions model

app/models/async_transaction/evss/va526ez_submit_transaction.rb
There have been instances of ArgumentErrors creeping up on staging. This is possibly due to using the incorrect `update` method when updating multiple attributes. This has been changed to `update_attributes` method which allows for multiple updates at once.
rspec tests.
Staging submission tests.
=> Change update to update_attributes

app/models/base_facility.rb, app/serializers/va_facility_serializer.rb, app/serializers/va_suggested_facility_serializer.rb, modules/va_facilities/README.yml, modules/va_facilities/lib/va_facilities/api_serialization.rb, modules/va_facilities/spec/requests/facilities_request_spec.rb, spec/request/va_facilities_request_spec.rb
Closes department-of-veterans-affairs/vets-api-clients#14
We had a user request being able to do a bulk fetch by id. This adds the ability to do a `GET facilities?ids=id1,id2` to do that. 
- Wrote RSpec tests
- Tested locally via curl
- None
=> Allow bulk fetch of facilities by id

Gemfile.lock, app/controllers/v0/disability_compensation_forms_controller.rb, app/models/async_transaction/evss/va526ez_submit_transaction.rb, app/models/disability_compensation_submission.rb, app/models/saved_claim/disability_compensation.rb, app/workers/evss/disability_compensation_form/submit_form526.rb, spec/factories/va526ez.rb, spec/jobs/evss/disability_compensation_form/submit_form526_spec.rb
Create associations in the models for disability claims and the va526 transactions via a cross reference table. This allows claims to be tied to the transactions which will make debugging significantly easier.
Local testing. Rspec tests.
Staging job submissions.
=> 526 update for xref table

app/models/gi_bill_feedback.rb
It appears that SalesForce requires `profile_data` to be present even if it's value is blank.
manual testing in dev/staging
manual testing in dev/staging/production
=> GIFBT:  ensure `profile_data` is always present in SalesForce request

lib/saml/url_service.rb, spec/controllers/v0/sessions_controller_spec.rb
The incoming `param[:success_relay]` was a `string` but `Settings.saml.relays.keys` was an array of symbols, so `Settings.saml.relays&.keys&.include?(success_relay)` always returned false.
This PR: 
- constantizes Settings.saml.relays.keys to be an array of strings
- adds two specs
=> Bug fix for dev-preview.va.gov login

app/controllers/v0/sessions_controller.rb, lib/saml/url_service.rb
This is a temporary solution to a redirect to dev.vets.gov vs dev-preview.vets.gov after the LOA1-LOA3 up-level process.
We opted for this approach to make today's code freeze deadline. We'll be working to establish a simpler URL whitelist approach - which will be documented in another ticket after this PR is accepted and merged for additional testing.
Testing included on-server dev-preview.va.gov, and dev.vets.gov.
=> hack fix for dev-preview login

config/locales/exceptions.en.yml, lib/evss/disability_compensation_form/service_exception.rb, spec/jobs/evss/disability_compensation_form/submit_form526_spec.rb, spec/support/vcr_cassettes/evss/disability_compensation_form/submit_500_with_max_ep_code.yml
Received this error on staging and it didn't have an error mapping described. In testing the '526' part of the yaml error keys wasn't being picked up so I changed it to 'disability_compensation_form'.
unit tests based on staging responses
staging testing
=> add max ep code error mapping for 526

app/controllers/application_controller.rb, app/controllers/v0/sessions_controller.rb, app/swagger/requests/sessions.rb, config/routes.rb, config/settings.yml, lib/saml/url_service.rb, spec/controllers/v0/sessions_controller_spec.rb, spec/request/swagger_spec.rb
Fixes: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/12540
This is part of a larger effort in #2271 
1. FE will `GET sessions/slo/new` (this endpoint still requires auth, which is how we know the session) it returns a URL to `GET sessions/logout?session=base64urlencodedtoken`. This url gets loaded in the popup by the FE once the signout button is clicked. 
2. The call to `sessions/logout` will destroy the session on vets-api side first before it automatically redirects through to the ID.me SLO flow. This endpoint does not require auth, hence why the base64urlencoded token needs to be passed to it.
3. Logging out and terminating the session no longer depends on the callback to return to destroy the user's session on vets-api side. Everything on the FE should work …
=> Fixes: Sessions Controller Delete/Destroy Action #12540

config/settings.yml
**NOTE:** [This corresponding PR](https://github.com/department-of-veterans-affairs/devops/pull/3284) in the `devops` repo should be merged first!
Flipping the `emis.mock` flag to `true` so that prefill works when testing locally.
Specs passed locally
=> [ON HOLD] Set `emis.mock = true` so prefill works locally

config/settings.yml
Search.gov provides a unique access key for accessing their Search API. This will need to be properly stored, and accessible across all environments.
https://github.com/department-of-veterans-affairs/devops/pull/3262
=> Env var for secure storage & reference of access key/value

config/locales/exceptions.en.yml
Updates the PIF in use error title so it's more descriptive in prometheus/grafana.
N/A
staging metric check
=> update 526 pif in use error title

app/models/gi_bill_feedback.rb, spec/factories/gi_bill_feedback.rb, spec/fixtures/gibft/transform_form.json
GIBFT will not send school `facility_code`.  Transform school address from 3 lines to 2 lines for SF submission.
specs
manual testing locally/dev/staging
=> Transform school address from 3 lines to 2 lines for SF submission.

rakelib/import_disability_contentions.rake
Add a rake task that takes a CSV and creates or updates DisabilityContention records for each line of the CSV.
Tested the rake task locally
Test the rake task in staging
=> add rake task

modules/vba_documents/app/models/vba_documents/upload_submission.rb, modules/vba_documents/spec/models/upload_submission_spec.rb
Resolves department-of-veterans-affairs/vets-contrib#234
Aliases Processing Success to 'processing' to avoid breaking existing consumers
Aliases Processing Error directly to 'error' without adding additional error
codes since it is unclear what exactly is different about this status.
Also cleaned the `response_object.blank?` check. It's already happening in the
`::refresh_statuses!` class method and rubocop was complaining about
`#map_downstream_status` being too long, so I added it and the logging that
to the `#refresh_status!` method.
Added unit tests for new statuses
Will need to test against Central Mail's staging environment to verify this works as intended
=> Add Processing Success and Processing Error status handling

app/workers/evss/disability_compensation_form/submit_uploads.rb, spec/jobs/evss/disability_compensation_form/submit_uploads_spec.rb
Noticed a 526 submit uploads job retrying because of a nil file body. Inspecting the job args revealed that the upload data has string rather than symbol based keys `{"name"=>"private_medical_record.pdf", "confirmationCode"=>"d44d6f52-2e85-43d4-a5a3-1d9cb4e482a0", "attachmentId"=>"L451"}`.
Unit tests
Staging integration tests
=> fix 526 upload data keys

app/models/preneeds/address.rb, app/models/preneeds/base.rb, app/models/preneeds/date_range.rb, spec/factories/preneeds/addresses.rb, spec/factories/preneeds/applicants.rb, spec/factories/preneeds/burial_forms.rb, spec/factories/preneeds/claimants.rb, spec/factories/preneeds/veterans.rb, spec/lib/preneeds/service_spec.rb, spec/models/preneeds/address_spec.rb
Preneeds:  ensure <state> attribute is present in XML request even wh
specs
manual testing in dev/staging
=> Preneeds:  ensure <state> attribute is present in XML request

app/controllers/application_controller.rb
Need to test on lower environments, cannot test locally.
=> enable secure only and va.gov domain for cookie

lib/benchmark/performance.rb, lib/benchmark/whitelist.rb, spec/lib/benchmark/performance_spec.rb, spec/lib/benchmark/whitelist_spec.rb
As part of the work being done for the [performance monitoring](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/13291), we need a way for the FE to pass page load times to the BE, and have those times sent to prometheus for analysis.
Created automated test coverage.
Will exercise this logic through a new endpoint.
=> 13353 Builds class to deliver page load metrics to StatsD

spec/models/account_spec.rb
The existing specs in `spec/models/account_spec.rb` are checking for explicit `Account.count`, but should be using the change matcher to expect a change in count.
=> Use change matcher in account_spec

app/swagger/requests/performance_monitoring.rb, lib/benchmark/performance.rb, spec/lib/benchmark/performance_spec.rb, spec/request/performance_monitorings_request_spec.rb, spec/request/swagger_spec.rb
In FE PR https://github.com/department-of-veterans-affairs/vets-website/pull/8533 , the new performance monitoring endpoint is being called with camelCase values. 
StatsD prefers keys be snake_case.
Automated testing.
=>  Snake_cases key before call to StatsD.measure

app/workers/evss/disability_compensation_form/submit_form526.rb, config/evss/all_claims_submission.json
In the sidekiq exhausted callback block we were accessing the job id via `jid`. This var isnt available and, rather, needs to be accessed via the passed in args.
Local testing via a testing job class.
Staging job submissions.
=> Update exhausted retries callback to properly pull the jid

app/swagger/requests/performance_monitoring.rb, lib/benchmark/whitelist.rb
Update the whitelist to include trailing slashes for simplicity and accuracy. 
Manually tested FE metrics requests are accepted when they match the whitelist. 
Will test in dev and staging va.gov that request data is being sent from each page. 
White list entries updated to include trailing slash.
=> Update whitelist for metrics with trailing slashes

config/betamocks/services_config.yml, config/settings.yml, lib/search/configuration.rb, lib/search/service.rb
Per precedence for integrating a third party service, we will want to add betamocks support for the new Search.gov API implementation.
https://github.com/department-of-veterans-affairs/vets-api-mockdata/pull/52
https://github.com/department-of-veterans-affairs/devops/pull/3381
Tested locally by curling the endpoint in dev.
=> 12697 betamocks for search

lib/sentry/processor/pii_sanitizer.rb, spec/lib/sentry/processor/pii_sanitizer_processor_spec.rb
Add bank account data to the PII sanitizer to prevent bank account data from being logged in Sentry
local rspec tests
Recreate error in staging and check that the Sentry error doesn't include bank account data
=> update pii sanitizer and specs

app/models/session.rb, lib/mvi/configuration.rb
MHV sign in users should pass the mhv icn into the cookie, regardless of whether or not we query MVI on our side or not. We might not be able to upgrade these users on vets.gov to "Premium" until they have successfully identity proofed, but we should still allow them the same level of access and set the cookie properly.
local testing only, need to test on staging.
will test on staging.va.gov as soon as code is merged.
Should be able to successfully pass back a cookie with ICN properly set for INTBADVANCE user.
=> adding mhv_icn to the cookie for mhv sign-in users regardless of LOA

app/workers/evss/disability_compensation_form/submit_form526.rb, spec/jobs/evss/disability_compensation_form/submit_form526_spec.rb
We currently can't differentiate EVSS internal server errors vs evss sub-system timeouts. This change sets the job to retry only if EVSS itself is timing out.
Unit tests
Local testing, Staging testing (once PPIU is back up)
=> only retry evss timeouts

modules/va_facilities/README.yml, modules/va_facilities/app/controllers/va_facilities/v0/facilities_controller.rb, modules/va_facilities/spec/requests/facilities_request_spec.rb
This updates the VA Facilities Docs to clarify handling of media types and required query parameters for the index routes. These resolve some user feedback we've gotten.
Added RSpec tests
=> Update VA Facilities Docs and Error Handling

modules/appeals_api/README.yml, modules/va_facilities/README.yml, modules/vba_documents/README.yml, modules/veteran_verification/DISABILITY_RATING.yml, modules/veteran_verification/SERVICE_HISTORY.yml
Now that the api.va.gov URLs are working we'd prefer users to use them instead of vets.gov one. This updates our documentation to refer to those urls. 
Resolves department-of-veterans-affairs/vets-contrib#342
=> Update API URLs to va.gov domains in documentation

rakelib/form526.rake
To ease the workload on the devs/devops, we are adding in a couple rake tasks that allow the user to pull out jobs and their statuses and then look up job details via the job ids.
Run locally with local data.
Staging.
=> Add rake tasks for retrieveing job information

rakelib/lint.rake
Since the release of bundler to 1.6.6, we've been seeing a warning from Bundler on some platform locking issues. While we figure out how to address those, one of the issues that popped up was a failing lint task due to some shell hackiness. This switches to a relative include and seems to work without doing that at all.
Launch a shell in container like Jenkins would:
`make bash`
Then run the linter:
`CI=true bundle exec rake lint`
ref: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/14125
=> use relative path to rubocop formatter

app/workers/evss/disability_compensation_form/submit_form526.rb, spec/jobs/evss/disability_compensation_form/submit_form526_spec.rb
On staging I ran into a bug where a timeout error saved in a async record and wasn't being parsed correctly when it was retrieved during polling by the FE. The error was a string but it needs to be a json string or json compatible hash (which the async transaction class will convert into json).
unit tests
=> async metadata must be json or json compatible hash

app/swagger/requests/search.rb
Search.gov's API docs prior some, but not all, details on their response to their search endpoint.  I contacted their support staff, and they sent me some updates on the response's structure.
=> Updates Swagger docs for /search endpoint

modules/va_facilities/lib/va_facilities/engine.rb
I moved migrations out of the global `db/migrations` in to the va facilities one and didn't get the initializer to load the migrations added. This fixes that by adding the initializer to va_facilities engine migrations will run properly.
=> Load va facilities migrations from subdirectory properly

db/schema.rb, modules/va_facilities/db/migrate/20181017120746_enable_post_gis_extension.rb
Not entirely sure why this seemed to work correctly on @ATeal's machine and mine originally, but GIS needs to be Gis so the migration file can be correctly loaded with Rails's inflector Rules.
=> Fix migration class name to work correctly with inflector

config/settings.yml
Search.gov requested the following for staging load testing:
- Please perform the test at 9am, to avoid our normal peak traffic time
- Please test against a separate search site that I've spun up and connected to our own index already, rather than Bing: https://search.usa.gov/sites/7552
- Site handle is vets.gov_test
=> Temporary change of affiliate for staging load testing for Search

lib/search/response.rb, spec/lib/search/service_spec.rb, spec/request/search_request_spec.rb, spec/support/schemas/search.json
We are seeing this error in sentry when conducting pre-load testing test:
http://sentry.vetsgov-internal/vets-gov/platform-api-staging/issues/49045/
The offset logic that was added in https://github.com/department-of-veterans-affairs/vets-api/pull/2356 is no longer needed, and will be properly removed in an upcoming PR.
This is a hot-fix so we can conduct our scheduled load testing today.
Local testing
=> Hot fix to remove bug that is pending removal, regardless

config/initializers/breakers.rb
We need to add the Search::Configuration to the breakers initialize for prometheus
=> Add Search::Configuration to breakers initializer

config/settings.yml
Changes were made in #2381, and now that we're done with this initial load test we are cleared (by Search.gov on 10/26/18) to do further testing on the actual site property we will use going forward.
=> Reverts search affiliate to va

app/controllers/v0/search_controller.rb, app/swagger/requests/search.rb, spec/request/search_request_spec.rb, spec/support/schemas/search.json
Stemming from [this conversation](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/13440#issuecomment-432793942), for the second iteration of the search pagination, we will implement a Google-like UI for the pagination end user experience.
Automated specs 
<hr/>
=> 14575 update search endpoint for pagination

app/controllers/application_controller.rb, spec/controllers/application_controller_spec.rb
Putting the automatic logout mechanism on va.gov to be disabled temporarily. This is probably what we should have done for production as well, but too late now.
loca testing
verify that staging.va.gov and staging.vets.gov login works again
=> introduce new toggle that can be used to enable sso loggout

db/schema.rb
The db/schema file got out of sync with the current set of migrations, probably due to picking the incorrect timestamp in a merge commit.
=> Correct schema version in db/schema file

app/swagger/requests/search.rb, config/locales/exceptions.en.yml, lib/search/pagination.rb, lib/search/service.rb, spec/lib/search/pagination_spec.rb, spec/lib/search/service_spec.rb, spec/request/swagger_spec.rb, spec/support/vcr_cassettes/search/exceeds_rate_limit.yml
1. Load testing failed due to our staging IP address being blacklisted.  Consequently, we were receiving `429` errors from Search.gov around too many requests.
2. Since Search.gov’s offset is maxed out at 999, we cannot view all of the potential search results.
For example, if the total search results are 35k, we would only be able to view the first 1000.
The total pages and total entries now accounts for this constraint.
Local testing
Load testing against the Search.gov API
=> Search endpoint accounts for Search.gov constraints 

Gemfile.lock
CVE-2018-16468 - Loofah XSS Vulnerability
https://github.com/flavorjones/loofah/issues/154
bumped the version of loofah 
read change log 
https://github.com/flavorjones/loofah/blob/master/CHANGELOG.md#223--2018-10-30
specs... no expected functionality changes
=> Update loofah gem to address CVE

app/controllers/v0/sessions_controller.rb, app/services/sso_service.rb, spec/controllers/v0/sessions_controller_spec.rb
We are seeing errors in Sentry 
http://sentry.vetsgov-internal/vets-gov/platform-api-production/issues/29280/
and http://sentry.vetsgov-internal/vets-gov/platform-api-production/issues/47158/
Both of these appear to be correlated, as we look at user IP.  Either something in the saml response was corrupted or the display of the SAML response in Sentry was not displaying correctly.
Additionally, we want to explicitly return false from persist_authentication! when the session is not persisted.
=> fix sso service

spec/controllers/application_controller_spec.rb
Settings.sso.cookie_signout_enabled is true in settings.yml, but a teardown was setting it to nil
=> Fix flapping application controller spec

modules/vba_documents/Gemfile.lock
Updates the `loofah` gem from 2.2.2 to 2.2.3 that is used by our `vba_documents` module/gem.
Command run:
```
williamryan:~/Github/vets-api (update-loofah) $ bundle update --source loofah
```
Ran local specs, i.e.:
```
williamryan:~/Github/vets-api (update-loofah) $ be rake spec SPEC=modules/vba_documents/
```
None.
- [ x ] Update gem with bundler
=> update loofah gem

modules/vba_documents/Gemfile.lock
Updates 2 gems in `vba_documents`:
- `sprockets`
- `rack-protection`
I used the following commands:
- `bundle update --conservative sprockets`
- `bundle update --conservative rack-protection`
Ran local rspecs.
None.
- [ x ] Update Gems
- [ x ] Does not contain any sensitive information (i.e. PII/credentials/internal URLs/etc., in logging, hardcoded, or in specs)
=> Updates rack-protection and sprockets for vba_documents

config/sidekiq_scheduler.yml
Update frequency of the polling for new maintenance windows on the backend. This is coupled with some caching we are doing at the proxy layer to ease burden on the API.
ref: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/14519
=> increase frequency on maintenance window polling

modules/va_facilities/README.yml, modules/vba_documents/README.yml, modules/veteran_verification/DISABILITY_RATING.yml, modules/veteran_verification/SERVICE_HISTORY.yml, modules/veteran_verification/VETERAN_CONFIRMATION.yml
And other documentation links.
When I updated to the documentation to link to api.va.gov I neglected to fix the service name.
=> Correct appeals to va_facilities

app/serializers/provider_serializer.rb, spec/factories/providers.rb, spec/serializers/provider_serializer_spec.rb
Adds Latitude and Longitude to the serialized attributes in the provider_serializer for compatibility with the search endpoint.
Added serializer level specs. Tested changes locally with fake data. Site to site connection issues prevented me from testing this in the review instance environment
This PR should allow the ablevets testing team to continue testing the provider locator features in staging
=> [Facility Locator] Provider serializer fix

app/models/emis_redis/veteran_status.rb, spec/models/emis_redis/veteran_status_spec.rb, spec/models/form_profile_spec.rb
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15086
raise `VeteranStatus::NotAuthorized` when trying to query for veteran status when a user does not have an edipi so that the user serializer does not return the ambiguous "server error" message. https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/serializers/user_serializer.rb#L67
=> user veteran status returning server error

app/controllers/openid_application_controller.rb, spec/controllers/openid_application_controller_spec.rb, spec/factories/okta_profiles.rb, spec/rails_helper.rb, spec/support/vcr_cassettes/okta/metadata.yml
Updates OpenidApplicationController to handle tokens from MHV and DSLogon credentials correctly, by populating certain mhv and dslogon-specific profile attributes from Okta profile and using those to build up the user session.
Part of https://github.com/department-of-veterans-affairs/vets-contrib/issues/457
Also goes with https://github.com/department-of-veterans-affairs/vets-saml-proxy/pull/10 which ensures that MHV attributes are propagated to Okta from the SAML IdP.
Will verify this with a sample app once deployed to a review instance.
=> OpenID MHV support

spec/controllers/openid_application_controller_spec.rb
Adds a spec to verify behavior of previous commit 02b1c8b1ea48889fceef1eca55326af82fe32f95, ensuring that LOA values are mapped through as numerics for all credential types.
This PR is a test
=> ID.me OpenID spec

app/models/form_profiles/va21686c.rb
change the 686 returnUrl from '/applicant-information' to '/veteran-information'
specs
=> change 686 returnUrl

app/models/saved_claim/disability_compensation.rb, rakelib/form526.rake
Updated the form 526 migration rake tasks to not use associations since they are broken. Added a new rake task to update the old saved_claim disability_compensation model `type`s to the new `SavedClaim::DisabilityCompensation::Form526IncreaseOnly` type. Added a default constant to the saved_claim disability_compensation base class so it doesn't break when accessing the old rows.
local console
staging migration tests.
=> Update 526 migration rake task

app/serializers/provider_serializer.rb, lib/facilities/ppms_client.rb
Quotes addresses to prevent ppms from interpreting certain addresses incorrectly. Tweaks the number of results to work around performance issues with the provider locator ppms endpoint identified in the staging environment. Results now limited to the amount necessary to display the current page (+1 so that a next page will show up in the front end if appropriate). Also fixes an inconsistency for the providers details page.
Tested using local front-end pointed to review instance API. conducted large radius searches to ensure that they were not timing out.
Performance issues addressed can only truly be tested in staging
=> [facility locator] Tweaking parameters to ppms calls for more consistent results

app/models/health_care_application.rb, config/locales/exceptions.en.yml, lib/evss/error_middleware.rb, lib/hca/soap_parser.rb, spec/request/health_care_applications_request_spec.rb
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15060
make all errors inside faraday middlewares in rainbows products subclasses of `Common::Exceptions::BackendServiceException`
=> fix issues with breakers middleware in rainbows products

app/models/okta_redis/model.rb
Setting the user on the `OktaRedis::App` caused it to have colliding cache keys, leading to weird results in operation. Changing the order of precedents fixes this.
resolves https://github.com/department-of-veterans-affairs/vets-contrib/issues/626
- local testing with the user from here https://github.com/department-of-veterans-affairs/vets-contrib/issues/626
=> Order of importance for cache keys

app/workers/central_mail/submit_form4142_job.rb, app/workers/evss/disability_compensation_form/submit_form0781.rb
**READY FOR THE MERGE**
Updated the text that is generated at the header and footer of the PDFs for the ancillary forms (21-4142, 21-4142A, 21-0781, 21-0781A so that it is helpful to the end user that will be receiving these PDFs after submission on the va.gov platform
Sample PDFs generated newly are attached to the connected story
- Unit testing
- Local testing
- Unit testing
- Cross-browser (by QA)
- Manual testing (by QA)
- Unit tests passed
- spec/jobs/central_mail/submit_form4142_spec.rb
- spec/jobs/evss/disability_compensation_form/submit_form0781_spec.rb
NA
=> BAH Sprint 8: Updated the header, footer stamping text for the ancillary forms

app/workers/evss/disability_compensation_form/submit_form526_cleanup.rb, spec/jobs/evss/disability_compensation_form/submit_form526_cleanup_spec.rb
Updates the 526 cleanup job to take submission_id, which then looks up the submission which includes user_uuid.
local unit tests
=> update cleanup job to take submission id

modules/va_facilities/README.yml, modules/va_facilities/app/controllers/va_facilities/v0/facilities_controller.rb, modules/va_facilities/spec/requests/facilities_request_spec.rb
Fixes https://github.com/department-of-veterans-affairs/vets-contrib/issues/612
Changes the format of the distances metadata so that facility IDs are not object keys, because object keys get snake_cased by olive branch, and when they do it's much harder for a consumer to match up the distances with the facility IDs from the main part of the response.
Consumer will have to build a map out of the distances array but that's pretty straightforward.
Manual testing, plus added a spec that ensures that IDs match up.
Entries in distance metadata should be easily correlate-able to overall response objects.
=> Change meta/distances format for facilities queries to avoid keys getting transformed

Gemfile, Gemfile.lock, modules/appeals_api/appeals_api.gemspec, modules/openid_auth/openid_auth.gemspec, modules/va_facilities/va_facilities.gemspec, modules/vba_documents/vba_documents.gemspec, modules/veteran_verification/veteran_verification.gemspec
Updates Rails 4.2.7.1 to 4.2.11 due to a CVE vulnerability in activejob.
No additional testing beyond `make ci`
=> Update rails 4.2.7.1 -> 4.2.11 due to activejob CVE

rakelib/form526.rake
Updates 526 submission report rake tasks to use Form526Submission model and associations. Also updates detail task to take one or more submission ids and list background job statuses, and user correlation ids.
local report runs
staging report runs
=> 13666 update 526 report rake task

spec/lib/common/client/base_spec.rb, spec/lib/common/client/middleware/request/remove_cookies_spec.rb
Housekeeping.  Namespacing a few classes that exist solely for test purposes because they exist globally (and not just within the scope of the specs)
specs
none
=> namespace test classes since they exist globally

app/controllers/concerns/accountable.rb, app/models/user.rb, app/swagger/requests/user.rb, config/settings.yml
We are ready to enable `Account` record creation in production.
https://github.com/department-of-veterans-affairs/devops/pull/3714
Logged into a staging instance and confirmed that `Account` record creation/checks are working as expected.
Once shipped, logging into a production instance to confirm things are working as expected.
=> 15393 enable account creation

app/controllers/v0/user_preferences_controller.rb, app/models/preference.rb, app/models/user_preference.rb, app/serializers/user_preference_serializer.rb, app/services/set_user_preferences.rb, app/swagger/requests/preferences.rb, config/routes.rb, db/migrate/20181128182716_remove_user_preference_indexes.rb, db/migrate/20181128183509_add_back_user_preference_indexes.rb, db/schema.rb, spec/request/swagger_spec.rb, spec/request/user_preferences_request_spec.rb, spec/services/set_user_preferences_spec.rb, spec/support/schemas/user_preferences.json
In order to create and/or update a new set of `UserPreference` for a given user, we need an endpoint with which the FE can communicate.
Comprehensive spec coverage
Swagger docs for new endpoint
=> Creates the endpoint for POSTing user preferences

lib/evss/disability_compensation_form/data_translation_all_claim.rb, spec/lib/evss/disability_compensation_form/data_translation_all_claim_spec.rb
Previously uncaught double `to_json` call was breaking the submission json down the pipe when being submitted to EVSS submission end point.
spec
staging e2e
=> Remove to_json conversion within the all claims translator

app/controllers/v0/preferences_controller.rb, app/serializers/preference_serializer.rb, app/serializers/preferences_serializer.rb, app/swagger/requests/preferences.rb, spec/controllers/v0/preferences_controller_spec.rb, spec/support/schemas/preference.json, spec/support/schemas/preferences.json
In the current swagger docs, it looks like this sample contract is off.  We’d want it to reflect that it is returning an array or pref/choice pairings:
`/v0/user/preferences/choices`: https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/preferences/getPreferences
This one has an extra `data` nested key in it:
`/v0/user/preferences/choices/{code}`: https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/preferences/getPreference 
Here is the contract:  https://github.com/department-of-veterans-affairs/vets.gov-team/issues/12399#issuecomment-442205111
Verified swagger docs match contract and endpoint returns correct shape
=> Update Preferences swagger doc

lib/sentry/processor/log_as_warning.rb, spec/lib/sentry/processor/log_as_warning_processor_spec.rb
Before the introduction of `Sentry::Processor::LogAsWarning`, `EVSS::ErrorMiddleware::EVSSError` exceptions were treated like `GatewayTimeout`s and logged as :warning. 
This restores that behavior by adding ` EVSS::ErrorMiddleware::EVSSError` to `Sentry::Processor::LogAsWarning`
To note:  `EVSS::ErrorMiddleware::EVSSError` is a subclass of `Common::Exceptions::BackendServiceException` and since they are no longer being `rescue`d in faraday middleware they can now trigger `breakers`
specs
=> log EVSS::ErrorMiddleware::EVSSErrors as :warning

bin/install-ubuntu-packages, docs/setup/native.md
I ran into a few hiccups getting the app up and running on ubuntu. This adds a script to do the tedious package installation and documents the manual fixes required. Hopefully we can get this on par with `setup-osx` in the future but this is a good first step.
=> Add setup instructions for ubuntu.

lib/benchmark/whitelist.rb
The location of the Facility Locator has moved to `/find-locations/` on VA.gov. This PR updates the FE Metrics routing whitelist to reflect this change per the comment [here](https://github.com/department-of-veterans-affairs/vets-website/blob/7e62d5e3debe24f65240a1604ecf3cec5597dec8/src/platform/monitoring/frontend-metrics/whitelisted-paths.js#L2).
Being done in coordination with this FE PR, https://github.com/department-of-veterans-affairs/vets-website/pull/9219.
None 🙁 
Depending entirely on your code review 🙂 
- Nothing unique
=> Update route to Facility Locator

modules/va_facilities/README.yml
Swagger Editor failed to validate the OpenAPI spec for the Facilities Service. These changes were required to validate. Other than the whitespace, which was just extra.
* Replaces schemas using `type: float` with `type: number` and `format: float`
* Removes trailing whitespace
* Adds parameter source definitions where necessary (`in: query`)
* Fixes incorrect `exploded` property with `explode`
* Fixes bad schema reference
This fix was developed outside of a contract. Please review and treat as an external contribution.
Tested changes in Swagger Editor. No validation errors. Have not tested against implementation.
=> Fix validation errors and formatting of Facilities Service OpenAPI spec

Gemfile, Gemfile.lock, db/seeds/development/preferences.seeds.rb, spec/controllers/v0/preferences_controller_spec.rb, spec/factories/preferences.rb
We need to allow for the developers who utilize the Docker workflow to test against Preferences changes. 
Tested by setting `RAILS_ENV` to both `test` and `production` and ensured the seeds did not trigger.
=> Add seedbank and development seeds

app/workers/evss/disability_compensation_form/submit_form526_cleanup.rb
Cleanup job was reporting errors when tracking job status, database tracking is working but metrics are not because it's missing the statsd prefix.
local integration tests
Cleanup job no longer throws errors on staging when tracking job status.
=> add statsd prefix to 526 cleanup job

config/initializers/breakers.rb
Breakers can be disabled with a `breakers_disabled: true` setting in `config/settings.local.yml`. By default, Breakers remains enabled.
In light of recent outages that may be due to breakers integration issues, this commit adds the ability to disable breakers with a configuration setting. Not sure we'll need to use this yet, but would like to have a PR ready just in case.
References:
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15765
`Breakers.disabled?` from local console is false when setting is not present. `Breakers.disabled?` is true when `breakers_disabled = true` in `config/settings.local.yml`
Confirm breakers is enabled when deployed. 
None
=> Ability to disable breakers with Settings.breakers_disabled

app/controllers/v0/facilities/va_controller.rb
Removed the hard feature flag for community care on the search endpoint in the facility locator. The new functionality will still be hidden behind the requirement to pass in an address parameter which only the updated UI will do. This is to support doing UAT in a production environment while not affecting behavior for regular users.
Supporting issue: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15807
The logic of falling back to old behavior if address is missing was tested earlier in the development cycle. Current change will only have impact in production environment
UAT for the provider locator will occur
=> [Facility Locator] Enable community care providers for UAT

app/serializers/user_serializer.rb, lib/vet360/contact_information/service.rb, spec/lib/vet360/contact_information/service_spec.rb, spec/request/user_request_spec.rb, spec/support/vcr_cassettes/vet360/contact_information/person_status_503.yml
In staging @BBarone1 experienced this error:
http://sentry.vetsgov-internal/vets-gov/platform-api-staging/issues/41168/?query=is:unresolved
This was when the below user tried to login via DS Logon.  User creds in below slack thread.
Here is the associated Slack conversation including @kfrz  and myself:  https://dsva.slack.com/team/U7NBNGSN6
Reproduced error and new specs written.
Testing in staging.
=> 15735 vet360 error handling

app/controllers/v0/facilities/va_controller.rb, app/models/provider.rb, spec/request/va_facilities_request_spec.rb
Removing community care providers from the all facility search and reverting back to the old functionality in that case. Community care providers can now only be searched by passing "type=cc_provider" into the search endpoint (by selecting community care from the dropdown in the UI). All code related to merging cc providers with va facilities has been removed to prevent dead code/failing coverage tests.
Tested changes locally to ensure all facilities searches do not attempt to fetch community care providers
Changes will be tested in staging prior to soft launch of provider locator.
=> [Facility Locator] removing community care providers from all facilities search

config/initializers/breakers.rb, config/settings.yml, lib/facilities/ppms_client.rb, lib/facilities/ppms_configuration.rb
Properly initializes breakers for the ppms backend. Changes the timeouts for the ppms client to be 60 seconds for clarity (it's limited to that amount of time by the forward-proxy anyway). Adds single quotes around CareSite names to ensure consistent results
Tested breakers locally and in review instance by editing the host for ppms. Tested parameter tweak against dev ppms in a review instance
Further testing in staging is planned prior to soft launch of provider locator
=> [facility locator] Enabling breakers for ppms web service

lib/breakers/statsd_plugin.rb, spec/lib/breakers/statsd_plugin_spec.rb
Updates the ID filtering on breakers metrics to prevent unchecked growth in metrics. This ID pattern is quite unusual, I'm not sure how to build this more generically without major surgery here.
=> Ww ppms id filter

modules/claims_api/EVSS_CLAIMS.yml
Documentation is pointing at the old url, this updates it to be in line with reality.
- documentation contains no references to the old URLs
=> Claims Documentation was still pointing at vets gov vs va gov

modules/appeals_api/README.yml, modules/claims_api/EVSS_CLAIMS.yml, modules/openid_auth/README.yml, modules/va_facilities/README.yml, modules/vba_documents/README.yml, modules/veteran_verification/DISABILITY_RATING.yml, modules/veteran_verification/SERVICE_HISTORY.yml, modules/veteran_verification/VETERAN_CONFIRMATION.yml
Add protocols in front all urls in documented server blocks. Fixes Swagger UI adding an extra URL in front of the server selection.
Resolves department-of-veterans-affairs/vets-contrib#756
Verified that this generates the correct blocks locally.
Nope should work!
=> Add protocols to swagger doc server blocks

config/initializers/statsd.rb, lib/search/service.rb, spec/lib/search/service_spec.rb
During our load testing of the Search.gov integration, we encountered many [429 errors](http://sentry.vetsgov-internal/vets-gov/platform-api-staging/issues/49190/) coming from their apache server.  We need to handle this error more gracefully. 
A follow up ticket will deal with PagerDuty alerting and/or Sentry logging, stemming from 429 errors. 
Local testing
=> 14820 StatsD tracking for Search.gov 429 errors

Gemfile.lock
Bumping json schema version for form526 schema updates
=> BAH Sprint 12: Updated to the latest vets-json-schema version

app/models/form_profiles/va526ez.rb
Catches for case when home phone from Vet360 does not exist
Local testing
Testing in staging with User 229
Resolves Sentry error http://sentry.vetsgov-internal/vets-gov/platform-api-staging/issues/55160/?query=is:unresolved
Resolves https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16158
=> Bugfix for Vet360 phone prefill on 526

app/controllers/v0/user_preferences_controller.rb
Per this [bug ticket](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16180), there was this issue:
```
"exception":"undefined method `id' for nil:NilClass",
"backtrace":[
"/src/vets-api/app/controllers/v0/user_preferences_controller.rb:64:in `user_preferences'",
"/src/vets-api/app/controllers/v0/user_preferences_controller.rb:26:in `index'",
```
This is happening because `id` was not being called off of the `@account` instance variable that is being set as part of the `before_action :set_account`, which mitigates against background jobs either failing or not running (which is what is happening here).
Local testing.  
Having @erikphansen retest locally
=> Bug fix for user/preferences giving 500s locally/in Docker

app/controllers/v0/sessions_controller.rb, spec/controllers/v0/sessions_controller_spec.rb
I tried to replace the raven logging in https://github.com/department-of-veterans-affairs/vets-api/pull/2413 but i neglected to re-raise so it was never logged. 
specs
=> log  NoMethodError to sentry

lib/evss/disability_compensation_form/data_translation_all_claim.rb, rakelib/form526.rake, spec/lib/evss/disability_compensation_form/data_translation_all_claim_spec.rb, spec/support/disability_compensation_form/all_claims_evss_submission.json, spec/support/disability_compensation_form/all_claims_fe_submission.json
EVSS has pushed a change through that updates the behavior of the treatment start/end dates. Instead of this being a date string it is now a date object that contains 'year', optional 'month', and optional 'day'. The back end translator had to be updated to account for this. Also, the `separationPayDate` field has been updated to take advantage of this as well.
Also, theres a small submissions rake task bug fix ninja'd on to this PR, my apologies.
Spec tests.
Staging e2e testing.
=> 16224 convert treatment date

modules/appeals_api/app/controllers/appeals_api/v0/appeals_controller.rb, modules/appeals_api/spec/requests/appeals_request_spec.rb, spec/support/vcr_cassettes/appeals/appeals_empty.yml
Fix a bug where we would try to access attributes on a nil object.
- ci / rspec
- staging calls
=> Nil safe deep accessing

config/locales/exceptions.en.yml, lib/mvi/responses/find_profile_response.rb, lib/mvi/service.rb, spec/lib/mvi/responses/find_profile_response_spec.rb, spec/lib/mvi/service_spec.rb, spec/models/mvi_spec.rb, spec/support/mvi/stub_mvi.rb
The [MVI::Service#find_profile](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/mvi/service.rb#L40-L64) call returns an instance of the `MVI::Responses::FindProfileResponse` class.  Should an error occur, we want to include the details of that error in this response class, so that we can bubble up those error details to the new `meta-outages` has in the `UserSerializer`.
Updated spec coverage
=> Collect MVI error details in MVI::Responses::FindProfileResponse objects

lib/pdf_fill/forms/form_helper.rb, spec/lib/pdf_fill/forms/form_helper_spec.rb
Fix for 4142 PDF generation due to non-us country in Veteran profile for mailing address
- PDF helper method fix
- Unit test update
- Unit testing
- Local testing
- Unit testing
- Cross-browser (by QA)
- Manual testing (by QA)
- Unit tests passed
- spec/lib/pdf_fill/forms/form_helper_spec.rb
- spec/lib/pdf_fill/filler_spec.rb
NA
=> BAH 4142 fix to avoid IsoCountryCodes::UnknownCodeError during PDF generation

app/models/base_facility.rb, modules/va_facilities/lib/tasks/facilities_tasks.rake
Resolves https://github.com/department-of-veterans-affairs/vets-contrib/issues/855 by allowing users to pass both a list of IDs and a lat/long in the same request. Didn't update the docs because they don't actually forbid this combination (which is why a user attempted it).
Also fixes a typo in an existing rake task, which will be used for https://github.com/department-of-veterans-affairs/vets-contrib/issues/990. Currently the majority of NCA, VBA, and VC facilities are missing location data, but running this task should solve that.
Verified against review instance and by running rake task locally
Will run task in dev/staging environments.
=> Fix facilities api bugs

lib/evss/disability_compensation_form/data_translation_all_claim.rb, spec/lib/evss/disability_compensation_form/data_translation_all_claim_spec.rb
Treatment end dates are optional. To avoid the possibility of a blank end date breaking the form translation, a short circuit return has been introduced when generating the approximate date.
spec tests
staging e2e
=> Form526 allow nil dates

modules/va_facilities/lib/tasks/facilities_tasks.rake
Adds environment task as a prereq so the task can access the database. Should be the final step before we can run the task for https://github.com/department-of-veterans-affairs/vets-contrib/issues/990
=> Add environment task to facilities migration

config/settings.yml
This updates the url for gids, so that it works locally by default. I'm not sure if there are other changes that have to happen along with this.
Ran GIBCT locally.
=> Fix url for gids in settings.yml

app/models/form526_submission.rb, app/workers/evss/disability_compensation_form/submit_uploads.rb, spec/jobs/evss/disability_compensation_form/submit_uploads_spec.rb, spec/models/form526_submission_spec.rb
EVSS has requested that upload jobs for 526 should be submitted sequentially and not in parallel. On top of that, uploads should not start until 60 seconds AFTER the 526 submission has gone through.
local
staging e2e
=> 16160 set upload delay

spec/request/swagger_spec.rb
fix hca spec not getting the content type of a file in rspec
=> hca spec fix

app/services/sso_service.rb, config/initializers/statsd.rb, lib/saml/user.rb, spec/support/saml/response_builder.rb
`saml_response.decrypted_document` is nil when a user clicks `deny`
http://sentry.vetsgov-internal/vets-gov/platform-api-staging/issues/56491/?query=is:unresolved
modified spec
=> tested authn_context for clicked_deny

app/models/emis_redis/veteran_status.rb, spec/models/emis_redis/veteran_status_spec.rb
This is part of the work to implement this RFC:
https://github.com/department-of-veterans-affairs/vets.gov-team/pull/15834
It enables the user serializer to return an HTTP status code for EMIS errors.  This is the sibling work to the changes in the MVI error response from this PR: https://github.com/department-of-veterans-affairs/vets-api/pull/2731
And will be leveraged in the new user endpoint’s `meta.errors` array being implemented in: https://github.com/department-of-veterans-affairs/vets-api/pull/2738
Added new spec coverage
=> Enables user serializer to return an HTTP status code for EMIS errors

app/services/sso_service.rb, lib/saml/auth_fail_handler.rb, spec/controllers/v0/sessions_controller_spec.rb, spec/support/saml/response_builder.rb
written with the understanding that a cleaner refactor will happen shortly, ensure that the proper auth too early codes are passed
specs
change my computer's clock and test on stage.
=> Fix too early late 

app/controllers/v0/apidocs_controller.rb, app/controllers/v0/in_progress_forms_controller.rb, app/controllers/v0/users_controller.rb, app/models/emis_redis/veteran_status.rb, app/models/mvi.rb, app/models/user.rb, app/serializers/user_serializer.rb, app/services/users/exception_handler.rb, app/services/users/profile.rb, app/services/users/scaffold.rb, app/services/users/services.rb, app/swagger/requests/user.rb, app/swagger/schemas/user_internal_services.rb, config/locales/exceptions.en.yml, lib/mvi/service.rb, modules/openid_auth/spec/requests/mvi_user_request_spec.rb, spec/factories/beta_registrations.rb, spec/lib/mvi/service_spec.rb, spec/models/mvi_spec.rb, spec/request/in_progress_forms_request_spec.rb, spec/request/swagger_spec.rb, spec/request/user_request_spec.rb, spec/serializers/user_serializer_spec.rb, spec/services/users/exception_handler_spec.rb, spec/services/users/profile_spec.rb, spec/services/users/scaffold_spec.rb, spec/services/users/services_spec.rb, spec/support/schemas/user_loa1.json, spec/support/schemas/user_loa3.json
Per [this RFC](https://github.com/department-of-veterans-affairs/vets.gov-team/pull/15834), if during the calling of the `/user` endpoint we experience any external service failures, we want to catch them and return a `296` response, indicating "success with some external service errors". 
In addition to that, return `null` in the data object for the failing service and include a `meta errors` object listing the service and the error(s) it received.  The error format should follow the [maintenance windows schema](https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/site/getMaintenanceWindows), per [FE request](https://github.com/department-of-veterans-affairs/vets.gov-team/pull/15834#issuecomment-454089359).
The three external service backed …
=> External service backed UserSerializer attributes return null & populate a meta-outages hash with error details

lib/evss/disability_compensation_form/data_translation_all_claim.rb, spec/lib/evss/disability_compensation_form/data_translation_all_claim_spec.rb
Disability condition name scrubbing needs to be moved to the backend. Any disability without a `classificationCode` will need to be scrubbed of any characters that do not pass EVSS's validation.
spec
staging e2e
=> 16721 scrub disability names

config/redis.yml
Vet360 team is seeing additional reads and writes.  From their team:
> The Vet360 team is seeing an increase in traffic from va.gov over the past few weeks, specifically a higher volume of writes/reads overall, but mainly a big spike in reads. Could you or someone on your team provide some clarity as to where that spike is coming from?
Associated Slack conversation with @kreek :  
https://dsva.slack.com/archives/CEDMA18AZ/p1549300089173600
We are also seeing increased Vet360 breaker activity and latency on the `v0/user` endpoint.  Associated conversation with @wyattwalter & @kreek :
https://dsva.slack.com/archives/C30LCU8S3/p1549539870720100
Currently the `ttl` for the user contact information coming from Vet360 is set to `60`.
Automated tests
Plan on merging this after our daily deploy …
=> Increases Vet360 Redis cache TTL to one day

modules/va_facilities/lib/va_facilities/engine.rb, modules/vba_documents/lib/vba_documents/engine.rb
Currently in master there is an issue with modules and how they load migrations.
Can be reproduced by doing this `bundle exec rake db:drop && bundle exec rake db:setup && bundle exec rake db:migrate`
This is because of the way setup figures out which migrations have been run.
resolves https://github.com/department-of-veterans-affairs/vets-contrib/issues/1310
- locally the above command now works
=> Module Migration Loading Issues

config/betamocks/services_config.yml
Allows non 10 digit + V+ 6 digit ICNS, needed due to some synthetic data we have. Adds the "id" part to the selector to avoid matching other numerics in the request body which appears as a single line. 
Manual testing with local env
=> Allow various kinds of ICN formats

config/betamocks/services_config.yml
Make betamocks stricter about ICN lookups to avoid over-matching SSN queries
Tested manually in rails console, verified both ICN and trait based lookups resolve correctly.
=> Split out before/after matching of ICNs in betamocks

app/models/user.rb
It looks like [here](https://github.com/department-of-veterans-affairs/vets-api/pull/1598/files#diff-4676c008b11a5480d73d4a6de01e45b9R40) ` delegate :first_name, to: :identity, allow_nil: true` may 
have unintentionally been left behind. As far as I can tell, it would be overwritten by `def first_name`
specs, should be no behavior change.
=> remove unnecessary code in user model

app/controllers/v0/sessions_controller.rb, spec/controllers/v0/sessions_controller_spec.rb
as a precursor or substitue to https://github.com/department-of-veterans-affairs/vets-api/pull/2816, log additional information about auth_too_late errors
specs
=> log more info for auth_too_late errors

db/schema.rb, modules/claims_api/app/models/claims_api/auto_established_claim.rb, modules/claims_api/db/migrate/20190211163050_create_auto_established_claims.rb, modules/claims_api/lib/claims_api/engine.rb, modules/claims_api/spec/factories/auto_established_claims.rb, modules/claims_api/spec/fixtures/form_526.json, modules/claims_api/spec/models/auto_establish_claim_spec.rb
In order to support the Auto CEST effort going on in the claims API, we need a DB model to capture things like form data, auth headers, and status of the submission.
for: https://github.com/department-of-veterans-affairs/vets-contrib/issues/1262
Originally in: #2800 
- quick rspec tests
- more when the code based changes come in
=> Art.526 auto cest model

lib/hca/enrollment_eligibility/status_matcher.rb
Refactor that eliminates the need to disable the rubocop rules:
`# rubocop:disable Metrics/CyclomaticComplexity`
`# rubocop:disable Metrics/PerceivedComplexity`
=> Us vs Rubocop

Gemfile.lock, app/controllers/concerns/filterable.rb, app/controllers/v0/messages_controller.rb, app/controllers/v0/prescriptions_controller.rb
Brakeman v4 warns about a SQL injection possibility because we aren't using strong parameters.
We aren't using strong parameters because we have other parameter checking in the `Filterable` module.
This changes syntax to use strong parameters and maintains our custom parameter checking.
specs
=> use strong parameters to appease Brakeman

lib/evss/disability_compensation_form/form0781.rb, spec/support/disability_compensation_form/all_claims_with_0781_fe_submission.json, spec/support/disability_compensation_form/form_0781.json
The FE is changing how they are submitting incident location addresses for form 781(a). Instead of submitting a single string address it will now be in a more common address object. The PDF creator, however, still expects a single string. The 781 translator will now build this string.
spec tests
staging e2e test
=> 17081 parse incident location

modules/veteran_verification/SERVICE_HISTORY.yml
Copied from department-of-veterans-affairs/vets-api/pull/2837.
Fixes error in https://github.com/department-of-veterans-affairs/vets-contrib/issues/1391
"toekn" -> "token"
Fix misspelling in Veteran Verification/Service History endpoint API docs ("toekn" -> "token")
None
None
=> Fix spelling error in service_history.yml

spec/models/async_transaction/base_spec.rb
`AsyncTransaction::Base` spec doesn't work on Feb 28th
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/17179
=> fix AsyncTransaction::Base spec

lib/mvi/responses/profile_parser.rb, spec/lib/mvi/responses/profile_parser_spec.rb, spec/support/mvi/find_candidate_response_nil_address.xml
In attempt to cut down on `unknown` error response from the evss claims service we need to sanitize the participant id that is returned. Essentially, this means making sure that it only contains digits (mostly removing `UNK` or `ASKU`).
Spec tests
=> 17176 sanitize participant id

app/models/form526_submission.rb
Because of a race condition due to a callback placed in the parent batch job and the `submitUploads` job being delayed via its `perform_in(...)` action, workflows are being marked as not complete even though all jobs are finishing successfully. To avoid this, the workflow complete handler is being moved to the child batch job.
=> Move workflow complete handler to ancillary job Batch

Dockerfile
The dockerfile we use to run our CI [recently removed `libgmp-dev`](https://github.com/docker-library/ruby/commit/73adf677cdb4b79ff4c98fb19aca11802e0d0ec9#diff-835bba16ea7fb377410c228971c0f4af) which is a dependency of `nokogiri`. This caused [`bundle install` to fail](http://jenkins.vetsgov-internal/blue/organizations/jenkins/testing%2Fvets-api/detail/upgrade_nokogiri/1/pipeline):
```
Fetching nokogiri 1.10.1
Installing nokogiri 1.10.1 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
```
This PR manually adds that back into our Dockerfile.
=> Fix nokogiri install during 'bundle install'

app/mailers/spool_submissions_report_mailer.rb, app/mailers/year_to_date_report_mailer.rb, spec/mailers/spool_submissions_report_mailer_spec.rb, spec/mailers/year_to_date_report_mailer_spec.rb
As a developer I need to make sure that all of the customer's requested emails are added to the distribution for the 0994 daily file.
- unit testing
- Verify with @Jennywalter or @dneel-bah that customers have received spool and ytd reports
- The following emails have been added to the distro for the 0994 daily report in staging and production:
- Brandon.Scott2@va.gov
- 224C.VBAVACO@va.gov
- peter.chou1@va.gov
- Joseph.Welton@va.gov
- 222A.VBAVACO@va.gov
=> VET TEC: Add new emails to distro for 0994 daily file #17286

lib/pdf_fill/forms/common_ptsd.rb, lib/pdf_fill/forms/va210781.rb, lib/pdf_fill/forms/va210781a.rb, spec/lib/pdf_fill/forms/common_ptsd_spec.rb, spec/support/disability_compensation_form/submissions/with_0781.json
The 781 pdf flow was potentially failing due to a few missing key values in the form hash. Almost all key/value pairs are optional when it comes to the form flow and this needs to be represented in the pdf fill. The offending issues have been corrected.
spec
staging e2e
=> 17233 781 upload retry bug

lib/evss/disability_compensation_form/data_translation_all_claim.rb, spec/lib/evss/disability_compensation_form/data_translation_all_claim_spec.rb
Turns out EVSS is actually validating disability names with apostrophes being acceptable characters, not right single quotes (as previously told). This updates the regex to account for that.
spec tests
=> Update disability name scrubbing

app/models/health_care_application.rb, spec/models/health_care_application_spec.rb
this changes fixes a bug where the hca e&e api would return 404 when mvi had a connection error
test on dev
=> don't return 404 when mvi has a connection error

lib/sentry/processor/pii_sanitizer.rb, spec/lib/sentry/processor/pii_sanitizer_processor_spec.rb
ICN and EDIPI while PII, are just primary keys, and they're needed for correlating our logs with downstream partners. These fields cannot really be used to cause problems since you can't use an ICN or EDIPI to open a credit card for example. They're tremendously useful for debugging purposes.
specs
none
Introduced an exceptions list. Since state gets triggered by regular expression, we will also check that whatever the key is, it is not in the exceptions list. There is a spec that tests that "state" is correctly filtered whereas relaystate, relayState, relay_state are not.
=> Improve PII Sanitizer, don't sanitize certain fields

modules/claims_api/app/models/claims_api/veteran.rb, modules/claims_api/spec/models/veteran_spec.rb, modules/claims_api/spec/requests/claims_request_spec.rb
This change is to remove the EDIPI as a required header when being passed for the 526 form.
Tested on staging that without mocks on. Verified that without the edipi, MVI is still getting the birls_number and pid for a veteran to pass to evss
=> Remove edipi for auto cest - 2

app/models/external_services_redis/status.rb, config/redis.yml, spec/models/external_services_redis/status_spec.rb
**User Story:** As a BE I want the pre-serialized status response from PagerDuty to be cached for performance, and assuring we do not exceed our rate limit.
Per PagerDuty's [rate limit docs](https://v2.developer.pagerduty.com/docs/rate-limiting), and this conversation with PagerDuty's support staff, PagerDuty's rate limit is 2,000/min (enforced at the account level):
> Feb 28, 15:10 PST
> 
> Hi Harry,
> 
> This is Tom from the PagerDuty support team. Sorry for missing you on chat earlier!
> 
> Our REST API's rate limit is 2,000/min (enforced at the account level).
> 
> API requests that exceed the API rate limit will return different HTTP status codes depending on which API you are using. REST v2 API will return a 429 code, and our v1 Events API will return a 403 code.
> 
> Please let me …
=> Status page: Caching layer for pre-serialized status response

app/workers/external_services_status_job.rb, config/sidekiq_scheduler.yml, spec/jobs/external_services_status_job_spec.rb
**User Story:** As a BE I want a background job that runs once a minute, using our PagerDuty service class, checking for the current status of our external services.
Automated specs
=> Status page: Background job checking status

db/schema.rb, modules/claims_api/app/models/claims_api/auto_established_claim.rb, modules/claims_api/db/migrate/20190305003907_add_md5_to_claims_api_auto_established_claims.rb, modules/claims_api/spec/factories/auto_established_claims.rb, modules/claims_api/spec/requests/disability_compensation_request_spec.rb
To prevent accepting duplicate claim requests we need a queryable field to allow us to spot dupes
resolves https://github.com/department-of-veterans-affairs/vets-contrib/issues/1432
- rspec
=> Accept no duplicate claim submissions

config/sidekiq_scheduler.yml, lib/pagerduty/external_services/response.rb, lib/pagerduty/external_services/service.rb, spec/lib/pagerduty/external_services/service_spec.rb, spec/models/external_services_redis/status_spec.rb
The OJ gem we use for JSON parsing throws "NoMemoryError: Too deeply nested." errors when trying to dump an array of Virtus model objects.  This was uncovered in [this hotfix PR](https://github.com/department-of-veterans-affairs/vets-api/pull/2911).
This is resolved by converting the Virtus model objects to hashes, before dumping them in the OJ gem.
There is no need for the statuses to be in the Virtus model format, as we end up serializing them in the next step.
I was able to reproduce the bug locally, with Redis running.  I was also able to prove that the `.to_h` addition fixes the issue, allow the [`Oj.dump(attributes)`](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/common/models/redis_store.rb#L81) call to complete successfully, and the data successfully …
=> Resolves "NoMemoryError: Too deeply nested." error from OJ gem

modules/veteran_verification/DISABILITY_RATING.yml, modules/veteran_verification/SERVICE_HISTORY.yml, modules/veteran_verification/VETERAN_CONFIRMATION.yml
This PR fixes [this bug](https://github.com/department-of-veterans-affairs/vets-contrib/issues/1563).
The description of all 3 of the Veteran Verification APIs started with "This API is provided as a proof of concept for a general-purpose VA API...", which is incorrect. They are no longer proof of concept APIs. In addition, the remainder of the first sentence contained some of the same info that was already in the second sentence. Therefore, I removed the first sentence entirely.
Also fixes a typo in the `Disability Rating` description: "…access the service history of a Veteran…“ changed to "…access the disability rating of a Veteran…“
None
None
=> Updated Veteran Verification API docs to remove "this is a proof of concept" verbiage

Dockerfile
Slim-jessie is no longer supported so Jenkins fails because it has been removed from mirrors.  One way to fix this is to use `slim-stretch`, though I'm open to other ways of handling this.
https://lists.debian.org/debian-devel-announce/2019/03/msg00006.html
````
W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
Service 'vets-api' failed to build: The command '/bin/sh -c groupadd -r vets-api && useradd -r -g vets-api vets-api && apt-get update -qq && apt-get install -y build-essential git libpq-dev libgmp-dev clamav imagemagick pdftk poppler-utils && freshclam' returned a non-zero code: 100
make: *** [ci] Error 1
script returned exit code 2 …
```
=> update debian version for docker

lib/evss/disability_compensation_form/configuration.rb, spec/lib/evss/disability_compensation_form/service_spec.rb, spec/support/vcr_cassettes/evss/disability_compensation_form/rated_disabilities.yml, spec/support/vcr_cassettes/evss/disability_compensation_form/rated_disabilities_400.yml, spec/support/vcr_cassettes/evss/disability_compensation_form/rated_disabilities_401.yml, spec/support/vcr_cassettes/evss/disability_compensation_form/rated_disabilities_403.yml, spec/support/vcr_cassettes/evss/disability_compensation_form/rated_disabilities_500.yml, spec/support/vcr_cassettes/evss/disability_compensation_form/submit_form_v2.yml
EVSS has stated that rated disabilities retrieved from v1 api need to be used and submitted to v1 submission endpoint and vice versa for v2. Currently, all rated disabilities are retrieved from v1. Since the release of v2 no new v1 forms are being created, ergo all GET rated_disabilities calls can be rerouted to the v2 api.
=> form526 default to v2 evss service

Jenkinsfile
Adds logic to Jenkinsfile to let us specify a staging and dev branch for environment deploys. Supports https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16825
=> deploy dev from rails upgrade branch

modules/claims_api/app/controllers/claims_api/v0/forms/disability_compensation_controller.rb, modules/claims_api/app/models/claims_api/auto_established_claim.rb
Remove va_eauth_issueinstant as it's always new
Ensure we're raising validation errors
- local curls
=> Bug in auto establish claim dedupe

config/initializers/new_framework_defaults.rb
It's causing rails console errors and will have not effect once we're >= rails 5.1
Unit tests/Ran console locally
Run console on dev
=> remove raise_on_unfiltered_parameters config

lib/saml/response.rb
Adds the original array of errors from the RubySAML errors array after it has processed the SAML Response if the array is non empty.
sessions controller has specs around all of this
none
=> add extra context to sentry for saml response errors if any

lib/evss/disability_compensation_form/data_translation_all_claim.rb, spec/lib/evss/disability_compensation_form/data_translation_all_claim_spec.rb, spec/support/disability_compensation_form/all_claims_fe_submission.json
For Form 526, veterans may be terminally Ill. To reflect this sad news in the form, some data will be prepended to the `overflowText` section of the form based conditionally on the `isTerimallyIll` key received in the payload.
spec tests
website e2e tests on staging
=> Prepend terminal illness text

Procfile
api via docker was running on port 5000 rather than 3000 after the rails upgrade
ran docker locally
N/A
=> add port to procfile

app/controllers/v0/sessions_controller.rb, lib/saml/url_service.rb, spec/controllers/v0/sessions_controller_spec.rb
Trying to better understand why logout requests cannot be found in certain circumstances. Should be able discover this in Rails logs after adding this additional logging.
specs only
after merging and getting a few failures in sentry, will use AWS api to try to track down where things get messed up.
=> add additional loggoing for logout requests and logout responses

Gemfile.lock, config/environments/production.rb, config/environments/test.rb, spec/jobs/education_form/forms/va1990_spec.rb, spec/jobs/education_form/forms/va1995_spec.rb, spec/lib/search/service_spec.rb
Various fixes to minimize various warnings that appear when running specs
specs
N/A
=> Cleanup spec warnings

app/models/health_care_application.rb, app/swagger/requests/health_care_applications.rb, lib/hca/enrollment_eligibility/parsed_statuses.rb, lib/hca/enrollment_eligibility/service.rb, lib/hca/enrollment_eligibility/status_matcher.rb, spec/lib/hca/enrollment_eligibility/service_spec.rb, spec/lib/hca/enrollment_eligibility/status_matcher_spec.rb, spec/models/health_care_application_spec.rb, spec/request/health_care_applications_request_spec.rb, spec/request/swagger_spec.rb
Per the discovery in [#17798](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/17798) around dismissed health care alerts, we will need to know when a user's current enrollment status became active.  Said otherwise, when their status changed from the former status, to the current enrollment status.
This data is already present in the [E&E API response](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16106#issuecomment-461677834) in the `enrollmentDeterminationInfo/effectiveDate` field.
Local and automated testing
Staging testing
=> Adds effective date to /v0/health_care_applications/enrollment_status response

config/betamocks/services_config.yml
department-of-veterans-affairs/vets-api/pull/2919 changed the rate disabilities to use the v2 API. This pull requests adds a mocked route for the new path, so that Betamocks can retrieve mockdata for it.
Resolves department-of-veterans-affairs/vets-contrib/issues/1796.
Added mocked route and no longer receive 500 error locally.
Once merged will verify that a `GET` request to `/ratedDisabilities` endpoint no longer receives a 500 error.
=> Add mock route for ratedDisabilities v2

spec/factories/form526_submissions.rb, spec/factories/preference_choices.rb, spec/models/saved_claims/pension_spec.rb, spec/models/user_preference_spec.rb
in rails 5.1 belongs_to associations will be required by default, this PR makes the specs pass for that change
=> Rails 5.1 belongs to changes

spec/factories/mvi_profiles.rb
Some specs that use the `mvi_profile_address` factory will fail json schema validation if city is over 20 characters.
local specs/irb testing
N/A
=> limit mvi profiles address factory city length to 20 chars

lib/evss/disability_compensation_form/service.rb
In an effort to debug instances where we are missing `birls_id` numbers in the header for `rated_disabilities`/`submit` calls to EVSS's 526 api we are adding in logging to inform on just that case. This is to sanity check and make sure this is actually origination from our call and not somewhere else.
None.
None.
=> Add a logging line for missing birls id in evss rated_disabilities call

app/workers/education_form/templates/0994.erb, spec/fixtures/education_benefits_claims/0994/kitchen_sink.spl, spec/fixtures/education_benefits_claims/0994/prefill.spl, spec/fixtures/education_benefits_claims/0994/simple.spl
Changes were made to the text of the spool file so content would be consistent with what is displayed on the web.
Originating issue: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/17982
Manual and Unit testing completed successfully
Execution of unit tests
- Update "Are you currently on active duty?" to "Are you on full-time duty in the Armed Forces? (This doesn't include active-duty training for Reserve and National Guard members.)"
- Update "Do you anticipate you will go on active duty during the VET TEC program?" to "Are you in the Selected Reserve or National Guard and do you expect to be called to duty for 30 days or more?"
- Removal of "Signature of applicant:"
=> 17982 :: VET TEC: Update spool file text for previously updated web questions : Update spool file content.

lib/hca/enrollment_eligibility/parsed_statuses.rb, lib/hca/enrollment_eligibility/status_matcher.rb, spec/lib/hca/enrollment_eligibility/status_matcher_spec.rb
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18093
add inelig_other status to backend status matcher
test on staging
=> hca backend statuses missing inelig_other

app/controllers/v0/sessions_controller.rb, lib/saml/url_service.rb
Ensures that cliendId is only added to the end of the URL, this will mean that AdBlocker and other extensions can drop this query string but not drop the rest of the query strings needed for validating the SAML request.
specs, and ensuring this doesn't break production.
just verifying in production
=> make sure clientId is only added to the end of the generated URL.

Gemfile, Gemfile.lock
Resolves gem vulnerability issues with Nokogiri that stems from a CVE for Nokogiri:
https://github.com/sparklemotion/nokogiri/issues/1892
=> Resolves gem vulnerability issues with Nokogiri

spec/workers/delete_old_transactions_job_spec.rb
Refactor of one spec to eliminate deprecation warning:
```
Deprecation Warnings:
Using `should_receive` from rspec-mocks' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` instead. Called from /Users/johnny/Projects/Oddball/vets-api/spec/workers/delete_old_transactions_job_spec.rb:21:in `block (3 levels) in <top (required)>'.
```
specs
N/A
=> refactor spec to eliminate `should` deprecation warning.

Jenkinsfile
=> deploy rails 5.1 to staging

app/controllers/concerns/notifications/validateable.rb, app/controllers/v0/apidocs_controller.rb, app/controllers/v0/notifications/dismissed_statuses_controller.rb, app/models/notification.rb, app/serializers/dismissed_status_serializer.rb, app/swagger/requests/notifications.rb, app/swagger/schemas/dismissed_status.rb, config/routes.rb, db/migrate/20190424212410_add_unique_index_combination_on_notifications.rb, db/schema.rb, spec/request/notifications/dismissed_statuses_request_spec.rb, spec/request/swagger_spec.rb, spec/support/schemas/dismissed_status.json
Per the discovery in [#17798](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/17798) around dismissed health care alerts, we need an endpoint where the FE can persist that a user has dismissed a given health care notification alert.
This will be based off of the user's current enrollment status details that the FE retrieves from our `GET /v0/health_care_applications/enrollment_status` endpoint. 
```javascript
{
subject: subject,
status: parsed_status,
status_effective_at: effective_date 
}
```
=> Endpoint to persist the dismissal of a user's health care notification status

app/controllers/concerns/notifications/validateable.rb, app/controllers/v0/apidocs_controller.rb, app/controllers/v0/notifications/dismissed_statuses_controller.rb, app/swagger/requests/notifications.rb, app/swagger/responses/record_not_found_error.rb, config/routes.rb, spec/factories/notifications.rb, spec/request/notifications/dismissed_statuses_request_spec.rb, spec/request/swagger_spec.rb
Per the discovery in [#17798](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/17798) around dismissed health care alerts, we need endpoint where the FE can update that a user has dismissed a given health care notification alert.
This will be based off of the user's current enrollment status details that the FE retrieves from our `GET /v0/health_care_applications/enrollment_status` endpoint, and the current dismissed status from the `GET /v0/notifications/dismissed_statuses/:subject` endpoint
```javascript
{
status: parsed_status,
status_effective_at: effective_date 
}
```
=> Endpoint to update the dismissal status of a user's health care notification 

Jenkinsfile
Adds build triggers for vagov-dev environment. We will have triggers for both the legacy environment and VAEC so that they are in sync during the transition. 
ref: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16410
=> add vagov-dev to deploy

app/models/base_facility.rb, modules/va_facilities/spec/requests/facilities_request_spec.rb
This change addresses [#1915](https://github.com/department-of-veterans-affairs/vets-contrib/issues/1915), which fixes an issue introduced in vets-api PR [#2992](https://github.com/department-of-veterans-affairs/vets-api/pull/2992) that causes the facilities index endpoint to throw a 500 error when a user tries to query with both ids and lat/long. 
Added a unit test for the combination of ids and and lat/long being queried.
=> Fix facilities error when querying for ids and lat/long

app/controllers/v0/apidocs_controller.rb, app/controllers/v0/notifications_controller.rb, app/serializers/notification_serializer.rb, app/swagger/requests/notifications.rb, app/swagger/schemas/notification.rb, config/routes.rb, spec/request/notifications_request_spec.rb, spec/request/swagger_spec.rb, spec/support/schemas/notification.json
Per the discovery in [#17421](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/17421), we will need to persist if a given In-Account notification has/hasn't been read by a veteran.  
This work involves endpoints to create, show, and update a given In-Account`Notification` record.
```javascript
{
subject: "dashboard_health_care_application_notification", 
read: false 
}
```
=> Endpoint to create a Notification record

Jenkinsfile
Removes triggering the deploy of the old dev environment. 
Part of https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16410
=> remove triggers of legacy dev deploys

app/controllers/v0/notifications_controller.rb, app/swagger/requests/notifications.rb, config/routes.rb, spec/request/notifications_request_spec.rb, spec/request/swagger_spec.rb
Per the discovery in [#17421](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/17421), we will need to persist if a given In-Account notification has/hasn't been read by a veteran.  
This work involves endpoints to create, show, and update a given In-Account`Notification` record.
=> Endpoint to get a Notification record

app/controllers/v0/notifications/dismissed_statuses_controller.rb, app/controllers/v0/notifications_controller.rb, app/swagger/requests/notifications.rb, config/routes.rb, spec/request/notifications_request_spec.rb, spec/request/swagger_spec.rb
Per the discovery in [#17421](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/17421), we will need to persist if a given In-Account notification has/hasn't been read by a veteran.  
This work involves endpoints to create, show, and update a given In-Account`Notification` record.
```javascript
{
read: true 
}
```
=> Endpoint to update a Notification record

modules/vba_documents/README.yml, modules/vba_documents/lib/vba_documents/multipart_parser.rb, modules/vba_documents/lib/vba_documents/upload_error.rb, modules/vba_documents/spec/lib/multipart_parser_spec.rb
In testing if someone uploads an empty file, it casues our code to bomb. We should instead error and return something useful instead of sticking in `uploaded` status.
resolves https://github.com/department-of-veterans-affairs/vets-contrib/issues/1960
- rspec
=> Validate Against Empty Files

app/controllers/application_controller.rb, app/controllers/concerns/authentication_and_sso_concerns.rb, config/application.rb
Added session expiration as a header in authenticated responses so the front end can display the session timeout modal and page at the appropriate time.
Front-end PR: department-of-veterans-affairs/vets-website#10033
Locally tested. The header is included in authenticated responses. Also modified the session TTL to a short enough duration to quickly test that the modal works.
The session timeout feature will initially be available only in lower environments for QA.
=> Session expiration header

modules/vba_documents/README.yml
According to w3, empty lines are required, so we use them
https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html
This makes our documentation more correct
=> VBA Documents Documentation Update

.rubocop.yml
We forgot to uptick the target Rails version in `.rubocop.yml`. This PR does that.
Rubocop runs locally with no violations.
CI 
~- [ ] Appropriate logging~
~- [ ] Swagger docs have been updated, if applicable~
~- [ ] Provide link to originating GitHub issue, or connected to it via ZenHub~
~- [ ] Does not contain any sensitive information (i.e. PII/credentials/internal URLs/etc., in logging, hardcoded, or in specs)~
~- [ ] Provide which alerts would indicate a problem with this functionality (if applicable)~
=> Uptick Rubocop target Rails version to 5.1

modules/va_facilities/README.v1.yml, modules/va_facilities/README.yml, modules/va_facilities/app/controllers/va_facilities/docs/v1/api_controller.rb, modules/va_facilities/config/routes.rb, modules/va_facilities/spec/requests/api_docs_request_spec.rb
This PR is the beginning of the first phase of work to provide drive times for VA facilities as required by the Mission Act. It provides documentation of a new endpoint `/nearby` for feedback from stakeholders and consumers. This endpoint is the start of VA Facilities v1 and incorporates schema changes unrelated to the drive time work that are wanted for v1 more generally.
Resolves department-of-veterans-affairs/vets-contrib/issues/1972
Includes schema changes for v1 from department-of-veterans-affairs/vets-contrib/issues/1228 and department-of-veterans-affairs/vets-contrib/issues/1869.
More information on Phase 1 can be found in the epic:
department-of-veterans-affairs/vets-contrib/issues/1971
=> Facilities Drive Times - Phase 1

config/sidekiq_scheduler.yml
Reverts department-of-veterans-affairs/vets-api#3040
This got turned around a lot quicker than I expected! It's been agreed that the arcGIS endpoints will stay active until an internal va replacement is available and we can move to it. We are safe to re-enable these jobs.
=> Revert "disabling facility location data jobs"

modules/va_facilities/README.v1.yml
It has been requested that we allow consumers to provide an address instead of lat/lng for requesting nearby facilities. This PR is for updating the `/nearby` endpoint documentation to align with this change.
We will pass the address to Bing Isochrone as a single string, but are requiring the consumer to past the address to us as separate params. This will allow us to better validate the inputs before passing them to Bing and quickly provide useful error messages instead of sending them on to Bing and either getting errors or unintended results back.
Speaking of getting unintended results back. We don't strictly need city, state, AND zip to get results, but my suspicion is that having all three (instead of just zip or city and state) will give us a higher chance of receiving an isochrone …
=> Update /nearby spec to accept address params not lat/lng

app/workers/central_mail/submit_form4142_job.rb
The `SubmitForm4142Job` sits under the `CentralMail` namespace rather than the `EVSS::DisabilityCompensationForm` namespace that the other 526 submit jobs live under. Therefore the job was encountering an error when trying to access `Metrics`. The full path was needed.
local dev testing
test by hand on a staging box
=> Added full namespace when call Metrics for form 4142 submit job

app/controllers/v0/user_preferences_controller.rb, app/models/user.rb, app/services/users/profile.rb, app/swagger/requests/user.rb, app/swagger/schemas/user_internal_services.rb, spec/models/user_spec.rb, spec/request/user_preferences_request_spec.rb
`user.account_uuid` makes a `.find_by` db call.  We are caching a user’s account record, so using:
```ruby
Account.cache_or_create_by!(user)
```
will first check if the account record is in the cache before making any database calls.
Under the hood this calls the Rails `find_or_create_by!` method.  So on the off chance there is a Redis or Rails error, we follow the same `rescue` pattern as the rest of the class, in order to ensure that the login flow is not blocked.  Rather, the errors are reported in the `meta.errors` hash.
=> Favors checking for cached Account prior to db calls

app/workers/facilities/access_data_download.rb, config/settings.yml, lib/facilities/bulk_json_client.rb, spec/fixtures/facility_access/wait_time_data.json
We have a new url to use for wait time data. The list of services has changed a bit since our last recording of the data so I updated that as well
local testing of the data format including visual spot checking in va.gov running locally. Rspec testing as well.
=> using a new url for wait time data, some shift in services since our last capture

Gemfile, Gemfile.lock, config/initializers/rubyzip.rb, config/settings/test.yml, modules/vba_documents/app/controllers/vba_documents/v0/uploads_controller.rb, modules/vba_documents/app/controllers/vba_documents/v1/uploads_controller.rb, modules/vba_documents/app/swagger/vba_documents/v0/controller_swagger.rb, modules/vba_documents/app/swagger/vba_documents/v1/controller_swagger.rb, modules/vba_documents/app/workers/vba_documents/upload_processor.rb, modules/vba_documents/config/routes.rb, modules/vba_documents/lib/vba_documents/payload_manager.rb, modules/vba_documents/spec/request/v0/uploads_request_spec.rb, modules/vba_documents/spec/request/v1/uploads_request_spec.rb
In order to help users onboard better. We've implemented an endpoint that will allow the user to "see what the server sees". It's gated by a setting that we'll only enable in dev and staging.
resolves https://github.com/department-of-veterans-affairs/vets-contrib/issues/2059
- rspec
- local requests
- adds ruby zip gem
=> VBA Docs Self Service

lib/pdf_fill/forms/va210781a.rb, spec/lib/pdf_fill/forms/va210781a_spec.rb
Since all keys are "optional" within a form 781/781a submission, all points of iterating over data need to be accounted for to prevent iteration errors. In this case, the pdf fill was attempting to iterate over a list using `each_with_index` and encountering a `undefined method `each_with_index' for nil:NilClass`. The offending iterator has been found and a guard clause has been added.
local testing
Test via staging website
=> Fix each_with_index error that could be potentially a nil value

modules/claims_api/app/swagger/claims_api/form_0966_v0_controller_swagger.rb, modules/claims_api/app/swagger/claims_api/form_0966_v1_controller_swagger.rb, modules/claims_api/app/swagger/claims_api/form_526_v0_controller_swagger.rb, modules/claims_api/app/swagger/claims_api/form_526_v1_controller_swagger.rb
Right now our swagger docs have a bug in the routing, leading to 404s if you import it into something that makes client from swagger
- local / swagger ui
=> fix the routing in the swagger for claims

modules/claims_api/app/controllers/claims_api/base_form_controller.rb, modules/claims_api/config/routes.rb
For Ticket https://github.com/department-of-veterans-affairs/vets-contrib/issues/2031 
We should be exposing our JSON Validation Schema publicly so that people can build forms against it so something like:
/services/claims/v1/forms/526/schema
/services/claims/v1/forms/0966/schema
but decided instead to go with
GET /services/claims/v1/forms/526
GET /services/claims/v1/forms/0966
This will ensure that people can quickly implement our form schema ahead of time and if hey do it right any changes that may come up on our will be easier for them to implement on their end.
Adding an Rspec test
Will build this into the Rails client app to test out automated form generation.
- Adding JSON Form schema
=> Get request for displaying JSON Schema for each form

modules/claims_api/app/controllers/claims_api/base_form_controller.rb, modules/claims_api/app/swagger/claims_api/form_0966_v0_controller_swagger.rb, modules/claims_api/app/swagger/claims_api/form_0966_v1_controller_swagger.rb, modules/claims_api/app/swagger/claims_api/form_526_v0_controller_swagger.rb, modules/claims_api/app/swagger/claims_api/form_526_v1_controller_swagger.rb
Wrapping up work for ticket https://github.com/department-of-veterans-affairs/vets-contrib/issues/2031
Adding documentation and minor JSON API compliance change.
Testing locally.
Testing against client implementation.
- Documentation is updated and json compliance achieved.
=> Adding Form Schema documentation and json api compliance

Gemfile.lock, app/workers/education_form/education_facility.rb, spec/jobs/education_form/education_facility_spec.rb
New education form routing rule: route all 1995 that are STEM applications to the Buffalo RPO
Unit tests updated, and QA review
N/A
=> 1995 STEM routing

app/controllers/v0/facilities/ccp_controller.rb
Small tweaks to make things slightly more clear/expressive. Builds on https://github.com/department-of-veterans-affairs/vets-api/pull/3082.
Pretty clueless on how Ruby handles docstrings, so gave it my best shot :-)
None.
Should be covered by existing unit tests.
=> more expressive constant name and docstring

README.md
Correcting link to local dev certificate.
Clicked through in browser.
None.
=> fixing link to certs, part deux

modules/appeals_api/app/controllers/appeals_api/v0/appeals_controller.rb, modules/appeals_api/spec/requests/appeals_request_spec.rb
Back whenever appeals was DigDug's purview we added some appeals logic. That was based on the idea that poa would come from kong and has since gone in a different direction. In order to remove some noise, I gutted it out. It was never really documented so no documentation changes were necessary.
resolves https://github.com/department-of-veterans-affairs/vets-contrib/issues/1907
- rspec
=> Remove POA from appeals

lib/central_mail/service.rb
Within the central mail service there is some logging to sentry that's getting called a boatload (25k - 30k depending on environment). I'm going to guess it's not needed.
resolves https://github.com/department-of-veterans-affairs/vets-contrib/issues/1968
=> Remove bulk logging

modules/vba_documents/app/swagger/vba_documents/v0/controller_swagger.rb
Documenting the specific rate limit for documents report.
=> add document report rate limit docs

modules/va_facilities/README.v1.yml
v1 of Facilities will only initially contain `/nearby` as an available endpoint. The rest will be upgraded later on. However, [the currently published OAS](https://dev-api.va.gov/services/va_facilities/docs/v1/api) has some language for the other endpoints that needs to be removed.
Fixes https://github.com/department-of-veterans-affairs/vets-contrib/issues/2352
Removed:
=> Remove non-applicable language from Facilities v1 OAS

modules/vba_documents/app/swagger/description.md
Misspelled a word in swagger docs
resolves https://github.com/department-of-veterans-affairs/vets-contrib/issues/2441
=> Typo in the word receive

Dockerfile, docker-compose.yml, docker-entrypoint.sh
Caches bundle install by moving it out of the docker build process and into an entry point script. Adding a new gem will no longer require reinstalling all our gems (which takes some time; looking at you nokogiri 👀) 
Added a new gem locally in both existing and fresh docker installs.
Confirm CI builds still run
=> docker cache bundled gems

app/controllers/v0/sessions_controller.rb, config/initializers/statsd.rb, spec/controllers/v0/sessions_controller_spec.rb
Part 1 of "Automatically deploy/remove DS Logon outage banner" is collecting metrics on login attempts.  
We already collect metrics on SAML responses (success and failure) but we're missing metrics on authentication attempts.  
These metrics will not be precise, but they will give us a broad picture of troubles.  That is to say the [saml_callback context](http://grafana.vetsgov-internal/dashboard/db/site-authentication?panelId=12&fullscreen&orgId=1&from=now-24h&to=now) will not have a 1-1 correspondence with the login attempts metrics, but I think we'll be able to say broadly if we see a significant dip in success rate we should be alerted and put up a banner. 
specs
view metrics in staging on new [Auth attempts by context](http://grafana.vetsgov-internal/dashboard/db/site-authentication? …
=> Add metrics for auth attempts

modules/appeals_api/README.yml, modules/va_facilities/README.v1.yml, modules/va_facilities/README.yml, modules/vba_documents/app/swagger/description.md, modules/veteran_verification/DISABILITY_RATING.yml, modules/veteran_verification/SERVICE_HISTORY.yml, modules/veteran_verification/VETERAN_CONFIRMATION.yml
Fixes https://github.com/department-of-veterans-affairs/vets-contrib/issues/2527
Noticed that all of our API docs that contain a `Reference` section with the `Raw Open API Spec` URLs have links for *dev* instead of *prod*. Also some were `http` instead of `https`.
=> Reference URL fixes in API docs

app/models/facilities_query/state_query.rb, modules/va_facilities/README.yml, modules/va_facilities/config/initializers/state_codes.rb, modules/va_facilities/lib/va_facilities/param_validators.rb, spec/models/facilities_query_spec.rb
Finishes [#2500](https://github.com/department-of-veterans-affairs/vets-contrib/issues/2500)
This PR does two things:
1. Adds state codes to the list that query params validate against
2. Allows for case insensitive state code queries
The list of codes to add came from the VA facilities we cache in Postgres that were not currently captured in the validation file. Finding those codes raised questions about some questions that are captured in the original issue.
- Added a new case-insensitive spec
- Manually validated new state codes work
=> Rt 2500 state code validation

modules/vba_documents/app/controllers/vba_documents/metadata_controller.rb
Resolves Ticket https://github.com/department-of-veterans-affairs/vets-contrib/issues/2491
- The 3 updates above (2 paths and 1 additional reference to the "vbms" status) are in place.
- v1 is listed as the current version of the Benefits Intake API, and 0.0.1 is marked as the previous version.
- Documentation for v1 is displayed by default on https://developer.va.gov/explore/benefits/docs/benefits.
=> Changing Benefits Intake V1 to default

app/workers/evss/disability_compensation_form/submit_form526.rb, spec/jobs/evss/disability_compensation_form/submit_form526_increase_only_spec.rb, spec/support/vcr_cassettes/evss/disability_compensation_form/submit_500_with_ep_not_valid.yml
EVSS has confirmed that, on a form526 submission, if an `EP Code is not valid` service error is raised we should not be retrying them because no amount waiting will allow the submission to go through successfully. Currently all upstream service errors force the submission job to retry until timeout or success so this case needs to have an exception in the logic.
spec tests.
Attempt on staging... but hard to reproduce.
=> 18950 dont retry ep codes

lib/evss/letters/service.rb, spec/lib/evss/letters/service_spec.rb, spec/support/vcr_cassettes/evss/letters/letters_unexpected_error.yml
Sentry has been logging issues for when theres a `get_letters` request to EVSS. Some service errors returned are coming back as string and not json bodies. Normally, we would handle this as a default BackendServiceException but there is a `dig` method call being made on the error body that is a string causing cascading failures. This has been refactored to avoid this problem in the future.
spec tests
=> 18719 undefined method dig error

modules/va_facilities/app/controllers/va_facilities/metadata_controller.rb
Removing internal only from the metadata controller for va facilities so the developer portal does not append the `internal only` label.  More info: https://github.com/department-of-veterans-affairs/vets-contrib/issues/2555
Manually checked the response from the metadata controller and ran the rspec files
* `Internal Only` is removed from the VA facilities developer portal
=> Change internal only to false for v0.0.1 meta data

modules/vba_documents/app/controllers/vba_documents/v1/uploads_controller.rb, modules/vba_documents/spec/factories/upload_submissions.rb, modules/vba_documents/spec/request/v1/uploads_request_spec.rb
We came to the conclusion that we wanted to revert the way we handle errors back to the v0 style 
resolves https://github.com/department-of-veterans-affairs/vets-contrib/issues/2641
- rspec
=> Art.revert v1 errors

modules/va_facilities/README.v1.yml
Fixes https://github.com/department-of-veterans-affairs/vets-contrib/issues/2662
This PR updates the `summary` fields for the Facilities v1 docs, to indicate that they are unavailable and in `DRAFT` status. This should make this distinction more prominent on the developer portal, and save the user from having to expand each one in order to view the status.
None (yet)
@rtravitz Is it possible to see what these changes would look like on the developer portal before merging? Just want to be sure there won't be any weird text overflow issues.
None
=> Add DRAFT to the summary for all unavailable Facilities v1 endpoints

modules/vba_documents/app/controllers/vba_documents/v0/uploads_controller.rb, modules/vba_documents/app/controllers/vba_documents/v1/uploads_controller.rb
Move the status override further down
also don't refresh if we're overriding
resolves https://github.com/department-of-veterans-affairs/vets-contrib/issues/2680
- local calls
=> Status Override Bug

modules/vba_documents/lib/vba_documents/payload_manager.rb, modules/vba_documents/spec/request/v0/uploads_request_spec.rb, modules/vba_documents/spec/request/v1/uploads_request_spec.rb
This will allow us to fall back to sending a download of the entire payload rather than erroring out. 
resolves https://github.com/department-of-veterans-affairs/vets-contrib/issues/2677
- rspec
- dev call
=> VBADocuments Payload Download Improving

lib/mvi/service.rb
https://github.com/department-of-veterans-affairs/va.gov-team/issues/271
In an effort to make our Sentry Alerting less noisy, we've decided to change the logging levels of connection problems to backend services from `ERROR` to `INFO`.
This changes two places where we log MVI connection problems as `ERROR` to `INFO`. [Sentry Alerted us](https://dsva.slack.com/archives/CJTDG22NM/p1563082714001000) of [`MVI find_profile connection failed.`](http://sentry.vfs.va.gov/vets-gov/platform-api-production/issues/46783)
Local rspecs.
None.
=> Change mvi log level from error to info

modules/vba_documents/lib/vba_documents/multipart_parser.rb
Apparently this could be called with an object or path
Tests yielded false postivie because it was being called with a file
object.
In code we always pass path, which 'filepath'.size.positive? Is
basically always true
- rspec / local
=> Validation Bug VBADocuments

rakelib/form526.rake
To help with tracking submissions (and errors) for prod 526 submissions we want to display the users participant_id in the rake task when showing all submissions within a datetime period.
Also, to help debug v1 submissions and to verify we arent creating new v1 forms somehow, we want to include a rake task that displays all v1 forms' created/updated date and its respective form id.
local runs.
Run via jenkins on staging. Log into staging box and run `show_v1` task.
=> Add pid to form526 rake

config/initializers/statsd.rb
Initializes GIBFT statsd metrics to 0.
Connects: https://github.com/department-of-veterans-affairs/va.gov-team/issues/625
None.
None / looking at GIBFT grafana dashboard
=> statsd init for gibft

modules/veteran_verification/DISABILITY_RATING.yml, modules/veteran_verification/SERVICE_HISTORY.yml
This PR fixes https://github.com/department-of-veterans-affairs/vets-contrib/issues/2773.
=> Fixes typos for Service History and Disability Rating

Gemfile, Gemfile.lock, spec/support/database_cleaner.rb
Reduces the rspec spec runtime by adding the DatabaseCleaner gem and its configuration under `spec/support/database_cleaner.rb` following the recommendations listed from this [article](https://devopsvoyage.com/2018/09/26/get-most-of-the-database-cleaner.html).
local specs
jenkins specs
=> 366 adds the database_cleaner gem and its configuration

Gemfile, Gemfile.lock, config/sidekiq_scheduler.yml, modules/vba_documents/app/controllers/vba_documents/v0/reports_controller.rb, modules/vba_documents/app/controllers/vba_documents/v1/reports_controller.rb, modules/vba_documents/app/models/vba_documents/upload_submission.rb, modules/vba_documents/app/serializers/vba_documents/upload_serializer.rb, modules/vba_documents/app/swagger/vba_documents/document_upload/status_attributes_swagger.rb, modules/vba_documents/app/swagger/vba_documents/document_upload/v1/status_attributes_swagger.rb, modules/vba_documents/app/swagger/vba_documents/v0/description.md, modules/vba_documents/app/swagger/vba_documents/v1/description.md, modules/vba_documents/app/workers/vba_documents/upload_status_updater.rb, modules/vba_documents/spec/factories/upload_submissions.rb, modules/vba_documents/spec/jobs/upload_status_updater_spec.rb, modules/vba_documents/spec/request/v0/reports_request_spec.rb, modules/vba_documents/spec/request/v1/reports_request_spec.rb
In order to make the reports endpoint function quicker, deal with timeouts, and various other reasons we decided rather than hit central mail on every request to reports, we would instead asynchronously sync that status of submissions and return the current value. Allowing the consumer to manually update individual status if an immediate update is necessary.
although closed, resolves 100% https://github.com/department-of-veterans-affairs/vets-contrib/issues/930
resolves https://github.com/department-of-veterans-affairs/vets-contrib/issues/2676
resolves https://github.com/department-of-veterans-affairs/vets-contrib/issues/2578
- rspec
- change in ideology in how we handle statuses for payloads
=> VBADocuments Submission Status Caching

modules/vba_documents/app/workers/vba_documents/upload_status_batch.rb, modules/vba_documents/app/workers/vba_documents/upload_status_updater.rb
After improvements made to the status caching jobs, and understanding the sidekiq setup it makes sense to move this back to the default queue
=> Make jobs process in the default queue

app/workers/education_form/education_facility.rb, spec/jobs/education_form/education_facility_spec.rb
Reorder education form routing rules to prevent 1995 STEM from being sent to western RO for Philippines facilities
Unit tests updated and QA reviewed
N/A
=> Reorder education form routing rules

lib/evss/vso_search/service.rb, spec/lib/evss/vso_search/service_spec.rb
Seeing if this change fixes an error ocuring in production that all of our mocks and even staging masks from ticket https://github.com/department-of-veterans-affairs/vets-contrib/issues/2859
- Makes sure that the VsoSearch doesn't return a 500 in production
=> Fixing production error being covered up by mocks

modules/veteran/app/workers/veteran/vso_reloader.rb
This change fixes the Invalid Byte Sequence issue happening when pulling in OGC data
This was tested by making the change on the staging worker server directly
=> Add a scrub to prevent invalid byte sequence

modules/veteran_verification/SERVICE_HISTORY.yml
Missing single quotes around the value of $ref caused an error because the value was treated as a comment and thus $ref equaled null.
Verified update caused no errors using https://editor.swagger.io/.
=> Fix $ref to Deployment schema

lib/vsopdf/vso_appointment_form.rb
Adds monitoring to the `/VADocument/upload` transaction in `VsoAppointmentForm`
spec suite, manually verified in console
=> Add monitoring to Vso Document Upload

config/initializers/saml.rb
Makes SAML initializer safe to missing key/cert files, for SSOe variants of those files. In response to issue where we were not injecting those files on worker instances. We will also make a change to inject those files, but this makes vets-api server/worker more robust.
Verified locally with dangling path references in settings.
=> Make SAML initializer safe to missing SSOe cert/key files

app/controllers/v1/sessions_controller.rb, config/routes.rb
Removes the code that munges the configured SAML callback and sets the host part to request.host. That was only needed when straddling the vets.gov/va.gov world, and causes problems when configuring any alternate callback URL. 
Fixes mis-configured route->controller action mapping.
Tested locally, verified contents of generated SAML request. Verified callback endpoint responds.
=> Remove unneeded request host mapping for SSOe SAML implementation

app/mailers/year_to_date_report_mailer.rb, spec/mailers/year_to_date_report_mailer_spec.rb
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets.gov-team/19517
Confirm that Lucas Tickner has received YTD emails after PR has been merged.
- Lucas.Tickner@va.gov
- Lucas.Tickner@va.gov
- Lucas.Tickner@va.gov
- Lucas.Tickner@va.gov
=> move email recipient to prod list

app/controllers/v0/ppiu_controller.rb, spec/controllers/v0/ppiu_controller_spec.rb
fail silently if vet360 raises an error and fall back on `current_user.email`
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19564
=> don't rely on vets360 contact information for direct deposit update

modules/va_facilities/README.yml
This PR adds some instructions to the Facilities API v0 docs for where to find the FAQs on wait time calculation. This info is provided by Access To Care, and will give greater visibility from the source on how the wait times that are returned by the API are calculated. In the future, we may try and scrape the FAQ text or copy it over entirely.
=> Add Access To Care wait times FAQ link to Facilities v0 docs

config/initializers/flipper.rb
fix the flipper initializer for developers who have not yet migrated the flipper tables but do already have a database.
````
michael@michael-Precision-T3600:~/oddball/vets-api$ rake db:setup --trace
** Invoke db:setup (first_time)
** Invoke db:schema:load_if_ruby (first_time)
** Invoke db:create (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "flipper_features" does not exist
LINE 1: SELECT "flipper_features".* FROM "flipper_features"
^
: SELECT "flipper_features".* FROM "flipper_features"
/home/michael/.rvm/gems/ruby-2.4.5/gems/activerecord-5.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:611:in `async_exec' …
```
=> Fix flipper initializer to allow for rake tasks pre-migration.

Rakefile
`rake spec` should run all module tests without requiring the developer to add a new module
=> Run specs for all modules with rake spec

Gemfile, Gemfile.lock
Our code was locked to a specific SHA1 of the factory_bot repo with a TODO note to undo the change when
possible. This PR handles that TODO.
We *cannot* upgrade to the latest factory_bot (5.x) because it deprecates static attributes which are used in many of our specs. We can fix those in a later PR through the process outlined here:
https://thoughtbot.com/blog/deprecating-static-attributes-in-factory_bot-4-11
The version was locked to < 4.11 since 4.11 adds noisy deprecation warnings in preparation for FactoryBot 5.0 removal of static attributes. Those deprecations will be handled in 4.11 on the way to 5.0 in another PR
Specs pass after the changes
Specs on staging should pass
=> Upgrade factory_bot to last version supporting static attributes

spec/lib/mvi/service_spec.rb
Followup to https://github.com/department-of-veterans-affairs/vets-api/pull/3247
I'm still a bit baffled on this one. I'm guessing a config changed somewhere in the middle of testing, but this code seems to be not needed...
=> small mvi rspec cleanup

.codeclimate.yml
Commit codeclimate config to .yml so that all who can write to the repo can modify config. 
I took codeclimate defaults + current plugin settings (though I did remove some unnecessary patterns from the `exclude_patterns`)
=> commit codeclimate config

modules/claims_api/app/swagger/claims_api/form_2122_v1_controller_swagger.rb
This fix is to update documentation that was referencing wring form
=> fixing documentation for 2122 payload

db/migrate/20190912172742_add_mobile_flag_to_base_facilities.rb, db/migrate/20190912185242_add_active_status_to_base_facilities.rb, db/schema.rb
This PR includes the migrations for department-of-veterans-affairs/vets-contrib/issues/2785 and department-of-veterans-affairs/vets-contrib/issues/2837. It will a `mobile` column and an `active_status` column to the `base_facilities` table. These migrations need to be merged into master before the code that references them to prevent errors before the migrations have run.
The code that will be using these new columns can been found in the PRs: department-of-veterans-affairs/vets-api/pull/3293 and department-of-veterans-affairs/vets-api/pull/3306.
- Verified that no errors occur when making a request to Facilities API after the migrations have been run
=> Base facilities migrations for `mobile` and `active_status` columns

spec/controllers/v0/preneeds/preneed_attachments_controller_spec.rb
There is a repeatable and persistent spec failure on multiple (all?)
local Ruby installations in this location: `/spec/controllers/v0/preneeds/preneed_attachments_controller_spec.rb:7`
The stacktrace is
```
2019-09-18 09:49:15.919951 D [28322:70295016921020] V0::Preneeds::PreneedAttachmentsController -- Processing #create
2019-09-18 09:49:19.287652 E [28322:70295016921020 sentry_logging.rb:57] Rails -- Failed to manipulate with MiniMagick, maybe it is not an image? Original Error: `identify /var/folders/yj/9j91j4gj2sqbkll8mrxy3h8r0000gn/T/mini_magick20190918-28322-1f7ayhd.pdf` failed with error:
.
2019-09-18 09:49:19.287793 E [28322:70295016921020 sentry_logging.rb:57] Rails -- /Users/johnpaul/work/oddball/vets-api/.bundle/gems/carrierwave-0.11.2/lib/carrierwave/processing/mini_magick.rb:2 …
```
=> Fix locally broken spec

.codeclimate.yml
Adding the Rubocop yaml files to the codeclimate exclude_patterns so they won't be included in diff-coverage.
=> adding the rubocop yaml files to the codeclimate exclude patterns

lib/facilities/vha_facility.rb, rakelib/jobs.rake
Move the call for `new` to the end of chain of methods that download and update facility objects. It needs to be moved because we want an accurate fingerprint on the attributes of the object.
=> Move the "new" method call to the end of download chain

app/services/facilities/website_url_service.rb, spec/services/facilities/website_url_service_spec.rb
In comparing the old and new VHA facilities responses, there were a few websites that were missing. The problem was that the letters at the end of some station numbers were lowercase. We currently own the CSV file that websites are populated from, so we could just change the case in the source, but that seems like a more brittle solution since in future we plan to offload the ownership of this data. 
- Added test to `website_url_service_spec.rb`
=> Handle lowercase station number in VHA website source

docs/setup/facilities_locator.md, spec/lib/facilities/vha_facility_spec.rb
Removes SQL52 docker information as that is not needed anymore.
=> Remove sql52 docker info

Gemfile, Gemfile.lock
Name: rubyzip
Version: 1.2.2
Advisory: CVE-2019-16892
Criticality: Unknown
URL: https://github.com/rubyzip/rubyzip/pull/403
Title: Denial of Service in rubyzip ("[zip bombs](https://en.wikipedia.org/wiki/Zip_bomb)")
Solution: upgrade to >= 1.3.0
=> update rubyzip to address CVE-2019-16892

app/controllers/application_controller.rb, spec/controllers/application_controller_spec.rb
we were sending a hash to sentry when it can only accept string values for tags. 
specs
sign_in_method is tagged in sentry
=> Sentry sign in tags must be strings, not a hash

Gemfile.lock, config/brakeman.ignore
When the brakeman gem was updated, there was one old/obsolete brakeman.ignore entry that was removed
There is a new brakeman issue that is now in the ignore file. Basically, its encouraging us to move from the older Rails <~ 4.2 default of storing cookies as marshalled objects to using JSON.
This led me down a small rabbit hole into looking at the new options for encrypting Rails cookies introduced in Rails ~> 5.2 that might replace our custom cookie encryptor and further simplify the app. https://blog.bigbinary.com/2018/06/26/rails-5-2-uses-aes-256-gcm-authenticated-encryption-as-default-cipher-for-encrypting-messages.html
Gem was updated, ignore file was updated to match, allowing any existing issues that can't be clearly remediated to be skipped.
Brakeman runs without additional …
=> Upgrade brakeman gem

lib/evss/service.rb
This removes legacy code prepending a service name to the source parameter when calling the raise_backend_exception method in the EVSS service class.
Related to this PR: https://github.com/department-of-veterans-affairs/vets-api/pull/3376
Comment reference:
https://github.com/department-of-veterans-affairs/vets-api/pull/3376/files/4c352ec0bbc6da70ce9b911a2109433af5d4ffac#diff-8e31094ed3344aef2cba919eba435beeR68
Test Suite passing status
=> remove EVSS prefix from source

modules/vba_documents/app/workers/vba_documents/upload_processor.rb, modules/vba_documents/spec/jobs/upload_processor_spec.rb
For ticket https://github.com/department-of-veterans-affairs/vets-contrib/issues/3261
- We've fixed and re-instituted our previous re-check logic
- The status we pass to consumers is not updated until we are done re-checking.
=> Fixing Benefits Intake Uploader logic with retries

modules/vba_documents/spec/jobs/upload_processor_spec.rb, spec/controllers/v0/sessions_controller_spec.rb, spec/controllers/v1/sessions_controller_spec.rb, spec/jobs/export_breaker_status_spec.rb, spec/lib/common/client/middleware/request/soap_headers_spec.rb, spec/request/breakers_integration_spec.rb, spec/request/statsd_middleware_spec.rb, spec/request/terms_and_conditions_request_spec.rb, spec/request/user_request_spec.rb
I found a number of `Timecop.freeze` calls that did not have corresponding `Timecop.return` calls.  
This was causing spec failures on certain runs.
Example:  
`rspec --seed 41882` resulted in [this expectation](https://github.com/department-of-veterans-affairs/vets-api/blob/a58358f8e2d57b242b6d04a2891c58d268f052c9/spec/controllers/v1/sessions_controller_spec.rb#L363) in `sessions_controller_spec` (wherein two timestamps were expected to be different) to fail because [this use of `Timecop.freeze`](https://github.com/department-of-veterans-affairs/vets-api/blob/a58358f8e2d57b242b6d04a2891c58d268f052c9/spec/request/user_request_spec.rb#L225) in 
`user_request_spec` was never unfrozen.
I also removed a couple of redundant method call stubs.
specs
n/a
=> Timecop fixes in specs

app/controllers/v1/sessions_controller.rb, config/routes.rb, config/settings.yml, lib/saml/url_service.rb
SSOe has a logout mechansim that is not based on SAML single logout. 
This PR adds logout routes and handling for the SSOe logout flow
- adds new route `v1/sessions/ssoe_slo/new` for SSOe logout
- adds callback route `/v1/sessions/ssoe_logout` as logout callback route
- adds handling for triggering logout flow with SSOe
Resolves https://github.com/department-of-veterans-affairs/va-sso/issues/32
This is an iterative change needed as part of debugging SSOe authentication. The complete flow can't be debugged locally because we don't have a VPN-enabled local development environment, and SSOe's dev environment is VPN-only.
n/a
dev/staging
=> Add logout URL for SSOe flow

config/settings.yml, config/sidekiq_scheduler.yml, modules/vba_documents/app/mailers/vba_documents/unsuccessful_report_mailer.rb, modules/vba_documents/app/mailers/vba_documents/views/unsuccessful_report.erb, modules/vba_documents/app/workers/vba_documents/report_unsuccessful_submissions.rb, modules/vba_documents/spec/jobs/report_unsuccessful_submissions_spec.rb, modules/vba_documents/spec/mailers/unsuccessful_report_mailer_spec.rb
In order to track trends in unsuccessful reports more closely, this report will allow us to gather data on whats going on with unsuccessful submissions.
resolves https://github.com/department-of-veterans-affairs/vets-contrib/issues/3321
- rspec
=> Implement Unsuccessful report and job on a schedule

modules/claims_api/app/controllers/claims_api/application_controller.rb
Importing LoA logic to be integer before going into MVI object, for ticket https://github.com/department-of-veterans-affairs/vets-contrib/issues/3332
- Make importing LoA an actual integer
=> LoA needs to be an integer going into the model

modules/claims_api/app/controllers/claims_api/application_controller.rb, modules/claims_api/app/controllers/claims_api/concerns/mvi_verification.rb
Last fix to MVI bug ticket https://github.com/department-of-veterans-affairs/vets-contrib/issues/3332
- Remove potential PII concerns from production logs in MVI error
=> Keeping PII out of production logs

config/initializers/rack_attack.rb, spec/middleware/rack/attack_spec.rb
Rapid polling of the claims status endpoint is causing multiple issues. This PR hopes to slow down the polling by adding throttling to rack attack middleware.
https://dsva.slack.com/archives/C30LCU8S3/p1571673172048900
=> Add evss claims async to rack attack throttling

config/initializers/flipper.rb
omit caching in development/test so that feature toggle values can be tested easier. 
This will mean that we can call `Flipper.enable('feature_name')` and `Feature.disable('feature_name')` in the setup/teardown of tests.
verified manuall
=> Omit caching from flipper in dev/test

modules/claims_api/app/controllers/claims_api/base_disability_compensation_controller.rb, modules/claims_api/app/controllers/claims_api/base_form_controller.rb, modules/claims_api/app/controllers/claims_api/v0/forms/disability_compensation_controller.rb, modules/claims_api/app/controllers/claims_api/v1/forms/disability_compensation_controller.rb
An attempt to finally fix the mock-override issue happening in staging, ticket https://github.com/department-of-veterans-affairs/vets-contrib/issues/3332
- Get Mock-Override from hitting a 500 error in staging
=> Moving Service Object to fix Mock-Override

app/models/facilities_query/radial_query.rb, modules/va_facilities/spec/requests/facilities_request_spec.rb, modules/va_facilities/spec/requests/nearby_request_spec.rb
When responding to a request which includes lat and long params, /facilities includes the distance from the lat/long and purports to be sorted by that distance. It was actually sorting by facility_type then by distance. That has been fixed.
For department-of-veterans-affairs/vets-contrib/issues/2501
Verified locally that response is sorted in correct order
Added expectations for the sort order to the appropriate tests
=> Fix sort order for facilities

lib/mvi/responses/id_parser.rb, spec/spec_helper.rb
Remove Flipper wrapping of MVI ID parser changes.
specs
N/A - changes already live in production
=> Remove Flipper toggle for MVI ID parser changes

Gemfile, Gemfile.lock
relates to: department-of-veterans-affairs/va.gov-team#2614
This bumps puma from 3.x to current 4.x and moves the statsd gem to current release.  This is in prep of trying to tune workers and threads on veta-api-server to address the behaviors we saw in department-of-veterans-affairs/va.gov-team#2633
- `rspec ./specs`
- load status page
Unsure here, this is my first PR to vets-api, would love some guidance specifically around running integration or e2e tests.
Things to look for in monitoring:
- site being served
- increase in sentry errors
- increase in cloudwatch logs
- per server cpu/memory usage
- api server throughput and timing
=> bump puma to current

lib/evss/vso_search/configuration.rb, spec/lib/evss/vso_search/configuration_spec.rb
This branch updates the url used in the VSO search to use version 11.6 over 11.0
local testing
checking on dev
=> update vso_search url

modules/veteran/app/workers/veteran/base_reloader.rb, modules/veteran/app/workers/veteran/vso_reloader.rb, modules/veteran/spec/workers/veteran/vso_reloader_spec.rb, spec/support/vcr_cassettes/veteran/ogc_attorney_data.yml, spec/support/vcr_cassettes/veteran/ogc_claim_agent_data.yml, spec/support/vcr_cassettes/veteran/ogc_vso_rep_data.yml
This PR fixes the issue with VSO Attorney and Claim agents not loading poa_codes
running the job in dev and staging once merged
=> fix VSO loader to capture poa codes on attorney's and claim agents

modules/va_facilities/README.yml
Add the `server` section back to the Facilities API v0 docs. This section is needed by the curl builder and will error if not present.
=> Add server section back to the Facilities API v0 docs now that curl builder needs it

spec/lib/common/client/base_spec.rb, spec/lib/common/client/concerns/log_as_warning_helpers_spec.rb, spec/lib/common/client/middleware/request/remove_cookies_spec.rb, spec/lib/common/client/monitoring_spec.rb, spec/rails_helper.rb, spec/support/default_configuration_helper.rb
To avoid module namespacing collisions and excessive setup/teardown, faraday configuration is now extracted into a shared helper for specs.
Spec tests pass
=> move faraday client configuration spec set up into shared helper

config/settings.yml
adding rian as a feature toggle admin.  
Because he's a veteran he's using his personal email address for production and his work address for staging.
=> add rian to feature toggle admins

lib/appeals/schema/appeals.json
[2803](https://github.com/department-of-veterans-affairs/va.gov-team/issues/2803)
switchDueDate is occasionally returned as null by the caseflow API, which would cause the appeals request to return a 500 error as the JSON validator within the service response class would flag at is not valid - this fixes that by allowing switchDueDate to be returned as null.
Change has been tested locally, appeals are returned successfully with change in place if switchDueDate is null, it returns a 500 while testing from master if switchDueDate is null
=> [2803] Appeals Response Validation BUGFIX

app/workers/facilities/pssg_download.rb
In looking through the code for the RGeo component [GeoJSON](https://github.com/rgeo/rgeo-geojson/blob/6028c8c7360f84727547d332907671dc901c351f/lib/rgeo/geo_json/interface.rb#L36) I found that it defaults to using a Cartesian coordinate system when decoding GeoJSON if you don't pass in factory. Specifying the spherical factory with the same options as the one used in our model greatly improves the decoding time. When run on my machine with the default factory it takes 139 seconds to decode the 30 features; with the spherical factory this was reduced to 9 seconds.
Part of department-of-veterans-affairs/vets-contrib/issues/3534.
Ran job locally
Run job in dev to verify speed increase
=> PSSG Download: override default Cartesian factory

modules/vaos/config/routes.rb
Adds health check and options routes for VAOS
N/A
integration tests
=> add VAOS healthcheck and options to routes

app/workers/facilities/pssg_download.rb, lib/appeals/schema/appeals.json, spec/jobs/facilities/pssg_download_spec.rb
The PSSG download ran in dev for 90 minutes and inserted 11451 drive time bands (~10% of the total). The bands are being inserted into the table at a little over 2 per second, but updates are currently much slower than that. In the interest of getting all of the drive time bands into the table, I have modified the download to skip trying to update existing records for now. This will allow the job to insert more new records each time it runs instead of just checking for updates to the existing records the whole time.
Part of department-of-veterans-affairs/vets-contrib/issues/3534.
Ran locally
Will run job in dev again to insert more records
=> PSSG Download: stop drivetime_bands from being updated

db/schema.rb, modules/claims_api/db/migrate/20191101133920_add_526_file_data.rb
Just the migration portion of ticket https://github.com/department-of-veterans-affairs/vets-contrib/issues/3435
- Just creating migration for storing 526 pdf data in the disability table
=> First Adding 526 pdf database changes before code

modules/va_facilities/README.yml
Corrects `min_time` and `max_time` data type to be integer instead of string.
Verified that the type in the /nearby response for these two attributes is indeed an integer.
=> Update NearbyFacility min_time and max_time type in doc

modules/vaos/spec/factories/vaos_users.rb
fixes an issue affecting docker builds being unable to require a gem that is only available in the test environment per Gemfile.
manual
=> fix faker issue

config/settings.yml
Originally tried using adhoc email, but I have already verified my identity using my personal email.  Changing email from narin@adhocteam.us to n.ratana@gmail.com
=> Update Narin's email for flipper admin

Jenkinsfile
**Refs: https://github.com/department-of-veterans-affairs/va.gov-team/issues/2514 && https://github.com/department-of-veterans-affairs/devops/pull/5923**
Working to reduce the duplication of vets-api-worker and vets-api-server warnings for database migrations (we think just having server post will suffice). Setting the parameter for migration_status on the apps specifically for deploys/releases will help accomplish this.
=> Working to reduce db migration noise

Gemfile.lock
Security vulnerabilities in Nokogiri and Rack-Cors are causing PR failures.
- Update nokogiri and rack-cors gems
=> Upgrade Security Vulnerabilities

config/settings.yml
This adds additional users who should be able to control the feature flags for VAOS.
=> Add additional admins for VAOS

modules/va_facilities/app/controllers/va_facilities/v0/nearby_controller.rb, modules/va_facilities/spec/requests/nearby_request_spec.rb
This PR addresses [#3673](https://github.com/department-of-veterans-affairs/vets-contrib/issues/3673). It returns an empty response when `Nutrition` or `Podiatry` are provided as services to the `/nearby` endpoint. This is a temporary measure until the datasource for services is replaced in an upcoming epic. There is a team building against `/nearby` that will need to provide these services, and it makes more sense for our part of the stack to change now since it will provide them soon.
- Added specs for providing the services and receiving empty responses
=> Return empty result when nutrition and podiatry are provided

modules/vba_documents/app/swagger/vba_documents/document_upload/status_guid_list_swagger.rb
ticket https://github.com/department-of-veterans-affairs/vets-contrib/issues/3695
- update: it is displayed in the DocumentUploadStatusGuidList model but incorrectly as maxItems: 100
=> Correctly Increasing Bulk End Point maxItems docs to 1000

modules/vaos/app/controllers/vaos/appointment_requests_controller.rb, modules/vaos/spec/request/appointment_requests_request_spec.rb
This was a difficult thing to debug. Apparently strong parameters require nested hashes to be permitted individually. I did my best to write a spec for this change, but because of how we're using VCR it is a bit tricky. I'd need to verify that the form is properly serialized. I think I will verify validation of the form object in a separate PR, but this is needed urgently for FE to do their piece.
Locally including verifying the parameters are set.
FE integration specs. Eventually when I add form validations, I'll write more comprehensive specs for the form and verify everything there is working as expected as well.
=> Fix appointment request strong params issue

db/migrate/20191204152342_add_visn_to_base_facilities.rb, db/schema.rb
This PR supports [#3638](https://github.com/department-of-veterans-affairs/vets-contrib/issues/3638)
It adds a column for `visn` to the `base_facilities` table.
- Ran and verified migration locally
- Will run and verify the migration in lower environments first
=> Add visn column to base_facilities table

config/settings.yml
Adds user @elwoodva to the allowed list for flipper admins
=> add elwood gary to flipper allowed list

app/workers/pager_duty/poll_maintenance_windows.rb, spec/jobs/pager_duty/poll_maintenance_windows_spec.rb
Limit retries to 3-ish minutes since the job runs every three minutes.  
Sidekiq will retry failures with an exponential backoff using [the formula](https://github.com/mperham/sidekiq/wiki/Error-Handling#automatic-job-retry).  3 retries is roughly 2.5 miniutes. 
* rename the files to be consistent with the class name
=> limit retries in pager_duty/poll_maintenance_windows

modules/vaos/app/controllers/vaos/apidocs_controller.rb, modules/vaos/app/controllers/vaos/appointment_requests_controller.rb, modules/vaos/app/controllers/vaos/appointments_controller.rb, modules/vaos/app/controllers/vaos/available_appointments_controller.rb, modules/vaos/app/controllers/vaos/base_controller.rb, modules/vaos/app/controllers/vaos/cancel_reasons_controller.rb, modules/vaos/app/controllers/vaos/clinics_controller.rb, modules/vaos/app/controllers/vaos/direct_scheduling_facilities_controller.rb, modules/vaos/app/controllers/vaos/facilities_controller.rb, modules/vaos/app/controllers/vaos/limits_controller.rb, modules/vaos/app/controllers/vaos/messages_controller.rb, modules/vaos/app/controllers/vaos/pact_controller.rb, modules/vaos/app/controllers/vaos/preferences_controller.rb, modules/vaos/app/controllers/vaos/systems_controller.rb, modules/vaos/app/controllers/vaos/visits_controller.rb
Basically I noticed that we were requiring dependencies that shouldn't be required. They were required because we were not properly namespacing our parent version of ApplicationController. And if you didn't manually require the dependency it would resolve to its parent ApplicationController which wouldn't be as expected. This helps alleviate and ensures we're also always being explicit about the namespace for inherited class as well.
All specs passing is good enough for me.
None
=> VAOS::BaseController instead of VAOS::ApplicationController

app/controllers/application_controller.rb, config/initializers/app_info.rb
This is a simple changeset to rename the GitRevision module to more general `AppInfo` and move the string constant for GitHub url. 
CI build
=> Rename initializer to AppInfo

.codeclimate.yml
Codeclimate complains a lot about similar code, but swagger is more like documentation than code, so exclude it from duplication checks.
I think that this change will only take effect once it's on master.
https://codeclimate.com/github/department-of-veterans-affairs/vets-api/issues?category%5B%5D=duplication&page=2&status%5B%5D=&status%5B%5D=open
=> exclude swagger from codeclimate similar code

app/controllers/application_controller.rb, app/controllers/v0/post911_gi_bill_statuses_controller.rb
Overrides the `def skip_sentry_exception_types` in the controller rather than defining the skip exception type in `application_controller`. No feature added in this PR, only a refactor of what was already done here: https://github.com/department-of-veterans-affairs/vets-api/pull/3674
Specs
None
=> Refactor how we ignore gibs OutsideWorkingHours exception

modules/claims_api/app/controllers/claims_api/application_controller.rb, modules/claims_api/app/controllers/claims_api/concerns/poa_verification.rb, modules/claims_api/app/controllers/claims_api/v1/forms/disability_compensation_controller.rb, modules/claims_api/app/controllers/claims_api/v1/forms/power_of_attorney_controller.rb, modules/claims_api/spec/requests/v0/claims_request_spec.rb, modules/claims_api/spec/requests/v1/claims_request_spec.rb
Fixing test sequence fix, bad loading of the test was masking our lack of requiring X-Consumer-Username in the code, running the test individually like charlie did causes it to fail, running it as a group causes it to pass.
- Fixed test sequence
=> Fixing bad test sequence

app/models/token.rb, lib/oidc/key_service.rb, lib/okta/service.rb, spec/controllers/openid_application_controller_spec.rb
https://github.com/department-of-veterans-affairs/vets-contrib/issues/3982
The /internal/auth/v0/validation endpoint has started sending a lot of events to sentry: http://sentry.vfs.va.gov/vets-gov/platform-api-production/issues/88135/. The error message here isn't very clear, but it seems to indicate that the public key specified by the access tokens being validated isn't being found. This PR adds some additional monitoring and more specific error messages to help us test our theories as we debug this problem.
=> Get more info about token validation failures

modules/veteran_confirmation/VETERAN_CONFIRMATION.yml
This PR addresses [#3657](https://github.com/department-of-veterans-affairs/vets-contrib/issues/3657)
It updates the Open API Spec for the new Veteran Confirmation API.
=> Add veteran confirmation language from hi-fi mocks

app/controllers/concerns/form_attachment_create.rb, spec/controllers/v0/hca_attachments_controller_spec.rb
https://github.com/department-of-veterans-affairs/va.gov-team/issues/4633
There was a bug introduced in https://github.com/department-of-veterans-affairs/vets-api/pull/3721 that attempted to save all of the parameters rather than just the file 
````
[1] pry(#<V0::HcaAttachmentsController>)> file_data
=> <ActionController::Parameters {"file_data"=>#<ActionDispatch::Http::UploadedFile:0x00007fdd6ded08f8 @tempfile=#<Tempfile:/var/folders/gs/qp8mkx392qjfgj22mv__h_br0000gn/T/RackMultipart20200107-29459-1gtucql.pdf>, @original_filename="extras.pdf", @content_type="", @headers="Content-Disposition: form-data; name=\"hca_attachment[file_data]\"; filename=\"extras.pdf\"\r\nContent-Type: \r\nContent-Length: 12161\r\n">} permitted: true>
````
specs
upload in staging
=> Bugfix: NoSuchKey error

config/settings.yml
Adding a BAH Team ID.me account to feature flags admins to be able to flip feature flag `gi_vet_tec_program_provider_filters`
Related to https://github.com/department-of-veterans-affairs/vets-api/pull/3605 and  https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19992
=> add bah ID.me account to feature flags admins

modules/veteran_confirmation/app/controllers/veteran_confirmation/docs/v0/api_controller.rb, modules/veteran_confirmation/config/routes.rb, modules/veteran_confirmation/spec/requests/api_docs_request_spec.rb
This update supports [#4022](https://github.com/department-of-veterans-affairs/vets-contrib/issues/4022). It fixes the route that serves the Open API Spec for the Veteran Confirmation API. At the moment, it sometimes loads the wrong ApplicationController and attempts to check authentication for incoming requests. Explicitly referencing `VeteranConfirmation::ApplicationController` uses the correct class. It also updates the route to be `/docs/v0/api`, which is in line with other Lighthouse documentation routes living in vets-api.
- Modified test for documentation route (which no longer fails periodically based on load order)
=> Update Veteran Confirmation documentation route

lib/common/virus_scan.rb
After deploying dockerized vets-api to production, we noticed some issues in [Sentry](http://sentry.vfs.va.gov/vets-gov/platform-api-production/issues/92658/?referrer=slack) relating to ClamD scans failing - the cause of which is the config file is not correctly picked up.
This PR changes the scan command to utilize custom config location. This fix will mediate the bug and allow us time to reengineer how we scan for virii in general.
Locally, staging box.
=> Use custom path for configuration file

config/puma.rb
I am hesitant to try this again due to what happened earlier in the week, but after talking with @wyattwalter and @johnpaulashenfelter, I think this will set a default in the Puma config to what is currently being used (meaning no changes should be seen by what is committed here) and allow for those configurations to be overwritten by environment variables. This would allow for us to do a dev-env deploy to test, allow for different settings dependent on environment, etc. 
Other than setting `- "-e PUMA_THREADS=16"` and `- "-e PUMA_WORKERS=1"` in the `docker_options` within the deployment configs, I am unsure what other changes would need to be made to align with the docker stuff @nathanhruby is working on. Any insight on that would be awesome.
In addition, I know there are some more …
=> Set default workers / threads

modules/vba_documents/lib/vba_documents/multipart_parser.rb, modules/vba_documents/spec/lib/multipart_parser_spec.rb
In production ruby's `sub` was failing due to memory with ~100mb base 64 payloads. Using sed is a bit more memory efficient
resolves https://github.com/department-of-veterans-affairs/vets-contrib/issues/4016
- prod server + worker server console parsing
- rerunning payloads once deployed
=> Use sed instead of ruby sub for memory performance

config/environments/test.rb, spec/jobs/mhv/account_statistics_job_spec.rb
There are a lot of logs written when running the specs, which are rarely useful. This
takes CPU and diskIO (since we're logging to file in the test environment). Occasionally in local
testing I've seen 
```
[42292:SemanticLogger::Appenders] SemanticLogger::Appenders -- Async: Appender thread has fallen behind by 61431867.117476 seconds with 1 messages queued up. Consider reducing the log level or changing the appenders
```
so I thought I'd try removing logging in the environment.
After 5 test runs, I am no longer receiving that error (almost always received it previously)
Test runs are also now faster
* ~7.25m before
* ~6.25m After
That's ~15% savings in time. I'm verifying that on CI`.
Hat tip to https://jtway.co/speed-up-your-rails-test-suite-by-6-in-1-line-13fedb869ec4
Testing time …
=> Ensure that the test environment is not using a real rails log

modules/veteran_confirmation/VETERAN_CONFIRMATION.yml, modules/veteran_confirmation/app/controllers/veteran_confirmation/v0/veteran_status_controller.rb, modules/veteran_confirmation/spec/requests/veteran_status_request_spec.rb
This PR addresses [#4047](https://github.com/department-of-veterans-affairs/vets-contrib/issues/4047). 
- Add two optional fields—`middle_name` and `gender`—to query the Veteran Confirmation `/status` endpoint. Having these optional fields present increases the likelihood of a successful MVI query for a given person of interest. 
- Update documentation to include the optional fields
- Added both fields to the happy path payload for the request spec
- Add tests to validate the incoming gender field to comply with the enum that MVI expects
=> Add optional fields to query Veteran Confirmation

modules/veteran_confirmation/app/controllers/veteran_confirmation/v0/veteran_status_controller.rb, modules/veteran_confirmation/spec/requests/veteran_status_request_spec.rb
This PR solves [#4065](https://github.com/department-of-veterans-affairs/vets-contrib/issues/4065). It addresses an issue introduced in PR #3787. The intent of the previous PR was to have `gender` be an optional attribute, but the controller validation for that attribute threw an exception because of the upcase method.
- Added an additional spec verifying the happy path without optional attributes
- Will verify expected results in DEV after deploy
=> Fix issue with upcasing an optional attribute

.dependabot/config.yml, db/schema.rb, modules/claims_api/db/migrate/20200117193734_add_headers_md5.rb
Initial migration for PR https://github.com/department-of-veterans-affairs/vets-api/pull/3786
- Migrate header_md5 string with index to power of attorney model
=> Migration for the header_md5 that we want to use in searching POA

modules/vaos/app/models/vaos/appointment_form.rb
apparently that hash_with_indifferent_access stuff did nothing, this has now been tested on staging as working
actually verified this is working on staging. In fact, I wrote all the code and committed directly from staging.
FE to verify.
=> VAOS Bug fix, round 2

Procfile
We have been using `bin/rails s` to start the rails server through foreman for quite some time, which is atypical. Typically the puma executable is used to start
the application (https://github.com/puma/puma#frameworks) so that its easier to configure. 
This wasn't a problem until we tried to use clustered mode to better use the capacity of our EC2 instances. Even running with a single worker in clustered mode,
no logfiles would be generated. Our production site experienced HUGE (2x+) memory usage and clear memory leakage that is 100% correlated with running in clustered
mode. Switching back to single mode in puma (PUMA_WORKERS=0) clearly put memory usage back in the normal range and restarted logfile collection. The "no logs"
problem was reproduced on staging and in local development, …
=> Use puma executable to start web application instead of bin/rails

modules/claims_api/app/controllers/claims_api/application_controller.rb, modules/claims_api/app/controllers/claims_api/base_disability_compensation_controller.rb, modules/claims_api/app/controllers/claims_api/v0/claims_controller.rb, modules/claims_api/app/controllers/claims_api/v0/forms/disability_compensation_controller.rb, modules/claims_api/app/controllers/claims_api/v1/claims_controller.rb, modules/claims_api/app/controllers/claims_api/v1/forms/disability_compensation_controller.rb, modules/claims_api/spec/requests/v0/claims_request_spec.rb, modules/claims_api/spec/requests/v1/claims_request_spec.rb
Reverts department-of-veterans-affairs/vets-api#3760
Talking to Tim they haven't been able to successfully test this in staging so we are going to revert for now before it makes it into production.
=> Revert "Exposing proper EVSS errors when query is made for claim status."

Gemfile.lock
Updates the version for the lighthouse bgs gem.
Original ticket here - https://github.com/department-of-veterans-affairs/va.gov-team/issues/5087
=> Updating lighthouse-bgs gem version

app/swagger/readme.md
This little guy got me good today. I tried to run Swagger locally through Option 2, but it was missing the `http` part of the `web_origin` so I kept getting a CORS error. This PR fixes that.
=> Add HTTP into example code in docs

modules/vaos/app/services/vaos/appointment_service.rb, modules/vaos/app/services/vaos/systems_service.rb
During UAT it was identified that certain endpoints related to direct scheduling do not return a response in under 45 seconds. This change is to increase the timeout to ~60~ 55 seconds for these three endpoints. This will ensure that breakers does not cause a disruption across all of the other services as well. 
VAOS shared services team is actively looking at improving the latency upstream. This is just a temporary fix for UAT. We will not want to go live with these changes.
None
Verify in staging that it's working.
=> Increase read timeout to 60 seconds for problem endpoints

db/migrate/20200205145700_add_index_to_in_progress_forms.rb, db/schema.rb
The query that takes the most time (total time) in our db is 
`SELECT "in_progress_forms".* FROM "in_progress_forms" WHERE "in_progress_forms"."user_uuid" = $1`
it averages 5ms but is called frequently. So, we should add an index.
=> Add index to In progress forms

db/migrate/20200203191620_add_vssc_extract_date_to_drivetime_bands.rb, db/migrate/20200205154839_update_vssc_extract_date_value.rb, db/schema.rb
PSSG receives updated drivetime bands from VSSC at the end of each month and has promised to update their polygons by the 15th of the following month. Checking each of the 11,000 drivetime bands' polygons each day to see if they should be updated or just updating all polygon's everyday would be a slow process. PSSG agreed to expose the date that VSSC extracted the bands in their API so that we can use that date to check when band needs to be updated.
This PR creates a migration to add the new column `vssc_extract_date` is being added to the Postgres table `drivetime_bands`. I have included a second migration to fill in this new field with an estimated date for the original extract date for our current drivetime bands. This will reduce the complexity of the update function. A default value …
=> Add vssc_extract_date column to drivetime_bands

config/sidekiq.yml
Currently our sidekiq threads are ramping up to 25. We only allow 16 connections to a DB, so this could solve a problem. This change sets sidekiq to only allow up to 16. The default in v4 of sidekiq is 20 and in v5 was changed to 10. The current version is v6, so we are 2 major versions behind. Maybe it's time for an upgrade?
There is currently no metrics for sidekiq being tracked, and may need to be addressed in another issue. (SEE: https://github.com/mperham/sidekiq/wiki/Pro-Metrics)
SEE: https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/2628
```
make up
docker exec -it 2cbfa98e7861 /bin/bash
ps aux | grep sidekiq
vets-api@2cbfa98e7861:~/src$ ps aux | grep sidekiq
vets-api    12  4.0 15.1 2153168 307676 pts/0  Sl+  20:19 …
```
=> va.gov-team#2628: Tune sidekiq to only kick off 16 threads concurrently

docker-compose.review.yml
Lowers the puma threads in review instances by default to 4. I just wanted to lower memory usage on these smaller instances and they shouldn't see much traffic. Does not affect production or any other environment besides review.
Part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/4617
=> reduce puma threads in review instances a bit

db/schema.rb, modules/va_forms/db/migrate/20200213160814_add_pdf_boolean_to_forms_api.rb
First PR for ticket https://github.com/department-of-veterans-affairs/vets-contrib/issues/4172 in attempting to give our API consumers a way to filter by whether pdf's are valid or not.
- Creating migration to check boolean validity of PDF's
=> Adding valid_pdf boolean to Forms

app/controllers/v0/facilities/ccp_controller.rb, app/models/provider.rb, app/serializers/provider_serializer.rb, lib/facilities/ppms/client.rb, lib/facilities/ppms/response.rb, spec/lib/facilities/ppms/client_spec.rb, spec/request/v0/facilities/ccp_request_spec.rb, spec/support/shared_contexts/facilities_ppms.rb, spec/support/vcr_cassettes/facilities/va/ppms.yml
This is a quick change to get posCode 17 and 20
Since we want the backend to combine the results from both pos searches this looked like a quick way to get it done.
This needs more testing around
| Urgent Care | Walk-In | Results                 |
| ----------- | ------- | ----------------------- |
| yes         | yes     | Urgent Care and Walk-in |
| yes         | no      | only Urgent Care        |
| no          | yes     | only Walk-In            |
| no          | no      | Empty Array             |
since the client class is handling the merge the controller just needs to keep doing what its doing.
department-of-veterans-affairs/va.gov-team#5713
All other functionality will be maintained
=> cc_urgent_care needs to get posCode 17 and 20

rakelib/github_stats.rake
Adding github_stats.rake that hits the Github API and grabs data on open PRs. This will only be called in Jenkins and will be removed if/when it is no longer needed.
=> Github PR stats rake job

config/settings.yml
Adding my ID.me account to the flipper admin list
also alphabetizing the list of admins because that's how I roll.
=> Adding my ID.me account to the flipper admin list

app/controllers/v0/profile/addresses_controller.rb, app/swagger/schemas/vet360/contact_information.rb, lib/vet360/models/address.rb, lib/vet360/models/base_address.rb, spec/lib/vet360/contact_information/service_spec.rb, spec/lib/vet360/models/address_spec.rb, spec/request/vet360/address_request_spec.rb, spec/support/vcr_cassettes/vet360/contact_information/put_address_ignore_eed.yml, spec/support/vcr_cassettes/vet360/contact_information/put_address_override.yml
This reverts commit 3daa4a729691a602e619466251a996de5907c79a.
The last commit seems to have introduced a breaking change that is preventing users from updating their addresses in the prod environment. Rolling this back as a short term fix.
=> Revert "require country_code_iso3 instead of country_name in contact info endpoint (#3911)"

modules/veteran_verification/app/controllers/veteran_verification/v0/keys_controller.rb, modules/veteran_verification/config/routes.rb, modules/veteran_verification/spec/requests/keys_request_spec.rb, spec/support/schemas/veteran_verification/keys.json
This PR supports [#3119](https://github.com/department-of-veterans-affairs/vets-contrib/issues/3119). It adds to functionality in PR #3858, which adds a service to sign Veteran Verification API responses with a JWS. This PR adds an endpoint to deliver public keys that can be used to verify those signatures.
- Adds a KeysController with one endpoint, which returns an array of keys. Each key contains information about the algorithm used, a `kid` (key id) to link it back to the JWTs that the corresponding private key signed, and a Base64URL encoded pem of the public key.
- Adds specs to verify the `pem` field matches for a given public key and for the overall response schema
- Verify in lower environments
=> Veteran Verification API Public Keys Endpoint

app/models/account.rb, app/models/user.rb, spec/factories/users.rb, spec/lib/common/models/concerns/active_record_cache_aside_spec.rb, spec/models/account_spec.rb, spec/models/user_spec.rb
Puts back in place the sec_id lookup code in account with two modifications based on observed Sentry behavior:
- Tolerates old cached Account objects with no sec_id accessor, using `try`
- Writes through updates to both redis and the database, previous iteration was not writing back to redis.
Additional test cases
I will execute login in dev/staging and ensure the observed errors don't re-occur.
=> Pv unrevert sec id lookup

app/models/account.rb, spec/models/account_spec.rb
AfterLoginJob/Account update happens on each callback so LOA1
logins should not overwrite previously established data with nil
Noticed in staging Sentry that account update warnings were flapping back and forth for a user between the LOA1/LOA3 logins.
Should not be a major impact because any LOA3-capable logins should wind up in the preferred state with all available data written, but we should avoid the flapping.
Unit testing, 
Will observe in further in sentry.
=> Avoids overwriting account attributes with nil values

config/betamocks/services_config.yml
Adds configuration to allow MDOT endpoints to use betamocks.
Corresponding mocked data PR: [PR](https://github.com/department-of-veterans-affairs/vets-api-mockdata/pull/116)
Tested locally with betamocks framework
None
Configuration allows betamocks to be utilized with MDOT endpoints
=> MDOT Betamocks Config Update

config/betamocks/services_config.yml
Was unable to sign in locally while running the APIs in Docker. This seems to fix it. More info in this thread https://dsva.slack.com/archives/CBU0KDSB1/p1583434294018300?thread_ts=1583432397.015700&cid=CBU0KDSB1
=> fix services_config.yml indent

modules/vaos/app/services/vaos/base_service.rb
VAMF appears to be doing some kind of DNS resolution on the HTTP Referrer we pass. I would like to make the change in Settings.hostname changing 'staging-api.vets.gov' to be the correct 'staging-api.va.gov' but I'm afraid this change might break something with how ID.me is configured so for now I'm just going to do a gsub.
verified on staging instance that making this change does not result in a Bad Request.
None
None
=> invalid Settings.hostname on staging instances causing Bad Requests

modules/vaos/app/services/vaos/systems_service.rb
Lowers only the VAOS clinics and PACT endpoint timeouts to 30s. This PR is related, and will be merged in before, #4004. 
Issue: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/6611
unit tests
VAOS get_facility_clinics and get_system_pact have a custom 30s timeout.
=> Lower only clinics and pact endpoints to 30s

lib/common/client/configuration/base.rb, modules/vaos/app/services/vaos/configuration.rb
Because VAOS makes calls out to a large number of different endpoints and they are all characterized as the same VAOS service name and all URI begin with the same hostname, there is greater risk that 1 or 2 of these endpoints might cause an outage across the entirety of the app.
As we continue to learn more we might look at coming up with custom matchers based on client class names that we use instead of URI. But for now, we just want to avoid this problem and we can do that by setting the error_threshold so high that it's unlikely to ever trigger a breakers outage without affecting all of the plugins such as STATSD and others which we depend on.
None
None
I believe this is the the first time someone has changed the error_threshold for a client configuration breakers service, there should …
=> VAOS change breakers error_threshold to 90 instead of 50

config/features.yml
This adds a past appointments toggle for VAOS, so that we can commit that page without pushing it live.
=> Add past appointments flag

modules/claims_api/app/controllers/claims_api/base_disability_compensation_controller.rb, modules/claims_api/app/controllers/claims_api/v0/forms/disability_compensation_controller.rb, modules/claims_api/app/controllers/claims_api/v1/forms/disability_compensation_controller.rb, modules/claims_api/spec/requests/v0/disability_compensation_request_spec.rb, modules/claims_api/spec/requests/v1/disability_compensation_request_spec.rb
Keeping the code and just commenting it out in the event that EVSS is able to improve their capacity down the line. For now though seems prudent to remove last check before submission.
Relates to ticket https://vasdvp.atlassian.net/secure/RapidBoard.jspa?rapidView=140&projectKey=DASH&modal=detail&selectedIssue=DASH-137&assignee=5e386d8f6061160ca042d953
The validate end point already exposes this particular feature and we should see more through put on our end but also more potential validation failures post submission in an errored claim potentially. This should increase our overall submissions though and sidekiq can handle the back end processing as well as retries if EVSS is down for any reason.
- Commenting out attempt to use EVSS validation as a catch all in the submit
=> Commenting out Last claims validation check because EVSS may no be able to handle request load

modules/vaos/app/services/vaos/appointment_service.rb, modules/vaos/spec/request/appointments_request_spec.rb
Adds a log line that records clinic information for sites that don't support VAOS (use the `VAOS_400` key)
Unit tests
Adds a warn log line with the clinic details hash
=> Log details for clinics who do not support VAOS

lib/saml/user_attributes/ssoe.rb, spec/factories/saml_attributes.rb, spec/lib/saml/ssoe_user_spec.rb
The authentication flow was incorrectly triggering upleveling
for DSLogon levels because it was detecting  loa_current as 2
and loa_highest as 3. This fixes loa_current calculation to
treat anything > 1 as "loa3" for vets-api purposes.
The new factory represents an actually-captured inbound SAML assertion from SSOe so accurately represents the use case. 
Closes va.gov-team6991
Will re-test with a DSLogon user in local env.
=> Updates upleveling logic for SSOe DSLogon users

Jenkinsfile, Makefile
This PR sets the default `ENV_ARG` variable to 'dev' in the Makefile.
This allows those than run `vets-api` via Docker to _not_ have to set the variable explicitly.
=> set default env to 'dev' in Makefile

modules/veteran_verification/VETERAN_VERIFICATION.yml, modules/veteran_verification/app/models/veteran_verification/service_history_episode.rb, modules/veteran_verification/app/serializers/veteran_verification/service_history_serializer.rb, modules/veteran_verification/spec/models/service_history_episode_spec.rb, spec/support/schemas/service_and_deployment_history_response.json, spec/support/vcr_cassettes/emis/get_military_service_episodes_v2/invalid_missing_pay_plan.yml
This PR supports https://vasdvp.atlassian.net/browse/IN-137.
In order to determine the grade for a military service member, a combination of Pay Plan Code and Pay Grade Code is needed.
Pay Grade is a value between 01 and 10.
Pay Plan is represented as a two-character code, and can be one of five values:
- CC (Commissioned Corps)
- MC (Cadet)
- ME (Enlisted)
- MO (Officer)
- MW (Warrant Officer)
Pay Plan needs to be concatenated with Pay Grade to determine the full grade, with the leading character (M or C) stripped from Pay Plan. For example, if a service member had Pay Plan=MW and Pay Grade=01, the concatenated value to be returned in the API would be W01.
Pay Plan exists in the eMIS getMilitaryServiceEpisodes response, so there's no additional service connectivity needed. It needs to be …
=> Update to Concatenate Pay Plan and Pay Grade

config/settings.yml, lib/saml/url_service.rb, spec/controllers/v1/sessions_controller_spec.rb
Instead of "cerner", use "myvahealth" as the application redirect value when a user lands on the standalone login page.
Also adding a check/spec for handling unknown application values.
closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/6917
- updated existing specs with new application key name
- added a new spec for ignoring unknown application redirect values
=> fix: using "myvahealth" as the key for a login redirect

Dockerfile, Gemfile, README.md, docker-compose.review.yml, docker-compose.yml
Changes Gemfile to install Sidekiq pro/ent if license is present
Removes need for `EXCLUDE_SIDEKIQ_ENTERPRISE` var
Developers often run into the scenario where they don't have the license set or the `EXCLUDE_SIDEKIQ_ENTERPRISE` variable set.  Then installation blows up when Bundler tries to install Sidekiq pro/ent.
With this change Sidekiq Pro/Ent gets installed if the license is present and it doesn't if the license is not present.  That's it.  No extra config.  No blow-ups.
TODO: Remove references to `EXCLUDE_SIDEKIQ_ENTERPRISE` from documentation.
N/A
=> install Sidekiq pro/ent if license is present

Gemfile
Got bit by using the safe operator on a `nil` value.
```ruby
''&.empty?     # true
nil&.empty?   # nil, which is falsey
```
I need to check explicitly for `nil` and an empty string.
Why?
Natively, when you have no Sidekiq license config set:
```ruby
Bundler::Settings.new['enterprise.contribsys.com']
```
However, if when you start up via Docker, it defaults the value of `BUNDLE_ENTERPRISE__CONTRIBSYS__COM` env variable to ''  and thus:
```ruby
Bundler::Settings.new['enterprise.contribsys.com']
```
=> fix Gemfile guard clause for installing Sidekiq Pro/Ent

app/controllers/v0/sessions_controller.rb, app/controllers/v1/sessions_controller.rb, config/routes.rb, lib/saml/url_service.rb, spec/controllers/v1/sessions_controller_spec.rb
Removes the SAML-based logout callback from v1 sessions controller, and cleans up extraneous routes and test cases. Also unifies the triggering URL for frontend to be `v1/sessions/slo/new` to match `v0/sessions/slo/new`.
SSOe does not implement SAML single logout, so we never expect a SAML response for a logout. Instead, they have a custom 'PKMS logout' endpoint that will terminate the IAM session and then redirect. back to an endpoint of your choosing via a simple redirect. The `ssoe_slo_callback` method is expected to receive that redirect and do the final additional redirect back to va.gov frontend.
Fixes va.gov-team#7137, but will need corresponding config change in devops repo to update pkms logout endpoint per-environment.
Awaiting testing in conjunction with IAM team; require them …
=> Cleanup v1 logout api

app/models/user_session_form.rb, lib/saml/errors.rb, lib/saml/user.rb, lib/saml/user_attributes/base.rb, lib/saml/user_attributes/ssoe.rb, spec/controllers/v0/sessions_controller_spec.rb, spec/controllers/v1/sessions_controller_spec.rb, spec/factories/saml_attributes.rb, spec/lib/saml/dslogon_user_spec.rb, spec/lib/saml/idme_user_spec.rb, spec/lib/saml/mhv_user_spec.rb, spec/lib/saml/ssoe_user_spec.rb, spec/support/saml/response_builder.rb
* Ensures that MHV account status and identifiers are mapped correctly into an identity object from the v1 session controller. SSOe user attribute class was missing the `mhv_account_type` attribute and was incorrectly populating the `sign_in` object. 
* An SSOe assertion has two potential sources for an MHV UUID; this change updates the class to read from either of them and throw a fatal login error in case of a mismatch. 
Fixes va.gov-team#7337
This PR is for merge to master but builds on top of https://github.com/department-of-veterans-affairs/vets-api/pull/4027. I will rebase this branch once that is merged but for now this diff is probably more illustrative:
https://github.com/department-of-veterans-affairs/vets-api/compare/eb-alternative-user-uuid...pv-fix-mhv-account-type-attribute …
=> Fix mhv account type attribute for v1 login

app/controllers/v0/sessions_controller.rb, app/controllers/v1/sessions_controller.rb, spec/controllers/v0/sessions_controller_spec.rb, spec/controllers/v1/sessions_controller_spec.rb
Adding 'version:v0' tags on the StatsD metrics coming from the v0 session controller and 'version:v1' tags on StatsD metrics coming from the v1 session controller.
closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/7323
- updated existing test cases to show that the tags are being sent
=> adding version tags to authentication StatsD metrics

Gemfile, Gemfile.lock, config/initializers/statsd.rb, lib/facilities/ppms/configuration.rb, spec/request/v0/facilities/ccp_request_spec.rb
department-of-veterans-affairs/va.gov-team#6675
Using Faraday Instrumentation and Active Support Notifications to measure how long each request to PPMS is taking
We need to make sure the review instance works. Hopefully, they are set up so we can see some of the metrics.
The time taken for each type of request to PPMS should show up in Prometheus
=> StatsD PPMS response logging

config/betamocks/services_config.yml, lib/mdot/client.rb, lib/mdot/configuration.rb, lib/mdot/schemas/supplies.json, spec/support/vcr_cassettes/mdot/get_supplies_200.yml, spec/support/vcr_cassettes/mdot/get_supplies_404.yml, spec/support/vcr_cassettes/mdot/get_supplies_502.yml, spec/support/vcr_cassettes/mdot/post_supplies_202.yml, spec/support/vcr_cassettes/mdot/post_supplies_404.yml, spec/support/vcr_cassettes/mdot/post_supplies_422.yml, spec/support/vcr_cassettes/mdot/post_supplies_502.yml, spec/support/vcr_cassettes/mdot/submit_order_202.yml, spec/support/vcr_cassettes/mdot/submit_order_400.yml, spec/support/vcr_cassettes/mdot/submit_order_502.yml
[link to original issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7507)
This PR includes a few changes to successfully connect with the stand-in DLC API. These changes include:
- Altering the `supplies.json` to allow some fields to be nullable, such as temporary address as not every veteran will have a temporary address.
- Changing the client connection URL to make calls to `/supplies` instead of `/mdot/supplies`
Has been tested and verified using a locally running instance of vets-api
=> MDOT-DLC API Integration Fixes

spec/request/swagger_spec.rb
Fix VCR cassette name.
Original name provided was for a cassette that did not exist.
specs
=> Fix VCR cassette name.

app/controllers/v0/performance_monitorings_controller.rb
We've identified a route that doesn't need CSRF protection.
It's also been determined that this route is no longer necessary at all.
We'll skip CSRF validation for now, and remove it altogether later after it's first been removed from the FE.
Pertains to department-of-veterans-affairs/va.gov-team-sensitive#61
specs
=> skip CSRF validation in PerformanceMonitoringsController

config/locales/exceptions.en.yml
[7559](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7559)
Adds an exception within exceptions.en.yml to handle scenarios where a veteran is deceased and a 403 error is returned to vets-api from the DLC.
Has been tested and verified locally
Error exception is added and when a deceased veteran attempts to call the API a 403 is returned.
=> [7559] Deceased Veteran Error Handling for MDOT

config/features.yml, lib/facilities/ppms/client.rb, spec/lib/facilities/ppms/client_spec.rb, spec/request/v0/facilities/ccp_request_spec.rb, spec/request/v0/facilities/va_request_spec.rb, spec/support/vcr_cassettes/facilities/va/ppms_new_query.yml
department-of-veterans-affairs/va.gov-team#7056
PPMS has added support for latitude/longitude in the address field. With this change, the number of mandatory fields has been reduced to `address`, `radius`, and `specialtycode1`.
Feature flags have been added to use the new search functionality and to suppress the unused parameters. 
This will be tested on the review instance to verify that we are getting responses.
When this is rolled out to production this needs to have the feature flags enabled.
=> 7056 pass lat long to ppms

modules/vaos/app/services/vaos/base_service.rb, modules/vaos/spec/services/base_service_spec.rb
Adds a `X-Request-ID` to each VAOS request so we can correlate vets-api cloudwatch logs with VAOS logs in Kibana.
unit tests, local integration tests
all VAOS requests include a `X-Request-ID` header
=> Add X-Request-ID to each VAOS request

config/settings.yml, lib/hca/configuration.rb, spec/lib/hca/service_spec.rb
department-of-veterans-affairs/va.gov-team#7764
Removing SSL config from HCA service configuration.
SSL connection negotiation is now handled by fwdproxy.
Specs
Tested submission of HCA application manually in review instance (staging environment)
Tested hitting `HCA::Service.new.health_check` manually in production.  
No errors were observed.
=> Remove SSL configuration and certs from HCA configuration.

app/mailers/spool_submissions_report_mailer.rb, app/mailers/year_to_date_report_mailer.rb, spec/mailers/spool_submissions_report_mailer_spec.rb, spec/mailers/year_to_date_report_mailer_spec.rb
re: department-of-veterans-affairs/va.gov-team#7949
Currently emails from certain GovDelivery addresses are not arriving for va.gov recipients.
The problem has been identified and is being investigated by OIT engineers.
In the meantime, we'll add alternate non-va.gov addresses so stakeholders can continue to receive their reports.
=> temporarily add addresses to daily reports

docs/setup/native.md
Point the link to the commercial Sidekiq credentials in `native.md` setup docs to the correct location.
=> Update link to Sidekiq commercial credentials

.github/PULL_REQUEST_TEMPLATE.md
Our PR template hasn't been reviewed in a while. It is definitely helpful to reviewers to have a link to the
original issue, so there's now a default entry in the appropriate format to autolink to the va.gov-team repo.
We also had a lot of boilerplate that ended up adding to the content/description of the PR without adding a lot of real value. Revised, removed, and moved to comments depending on details
department-of-veterans-affairs/va.gov-team#7531
This changes the default template for all vets-api pull requests, based on feedback from the backend team reviewers.
=> Add issue number link and clean up text on default pull request template

modules/veteran_verification/app/controllers/veteran_verification/v0/health_controller.rb, modules/veteran_verification/config/routes.rb, modules/veteran_verification/spec/requests/health_request_spec.rb
Creates a health endpoint for Veteran Verification in the style of health-api’s actuator endpoint. The endpoint should indicate the availability of the application (e.g. healthy/true if the endpoint is accessible).
https://vasdvp.atlassian.net/browse/PIV-310
Testing completed locally and new spec added for the controller addition.
=> Piv 310 veteran verification health check endpoint

app/controllers/application_controller.rb
Temporarily log CSRF token in response header
department-of-veterans-affairs/va.gov-team-sensitive#44
department-of-veterans-affairs/va.gov-team-sensitive#42
department-of-veterans-affairs/va.gov-team-sensitive#61
I want to temporarily log the CSRF token in the response headers so I can accurately paint a picture of the flow of tokens from server to client while I debug seemingly erroneous CSRF violations.
=> Temporarily log CSRF response token

Gemfile.lock, app/models/form_profile.rb, config/form_profile_mappings/MDOT.yml, spec/models/form_profile_spec.rb
Adds a field to the MDOT form profile mapping that shows the veterans last four digits of their social security number.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/8087
=> [8087] Add lastFourSsn Field to MDOT Form Profile Mapping

app/controllers/v0/coronavirus_chatbot/tokens_controller.rb, spec/controllers/v0/coronavirus_chatbot/tokens_controller_spec.rb
There was a typo in a call to settings.
N/A
None.
An assert was added to prevent this as a future regression
=> Fixed typo in call to Covid Chatbot settings

lib/flipper/views/features.erb
Move the sign in prompt from the bottom to the top of the page in the flipper admin screen so that it is more visible to users who need to log in or are not identity-verified.
before
After
=> move flipper sign in link to top

app/serializers/va_facility_serializer.rb, app/swagger/schemas/va_facilities.rb, config/features.yml, spec/rails_helper.rb, spec/request/swagger_spec.rb, spec/request/v0/facilities/va_request_spec.rb, spec/support/vcr_cassettes/lighthouse/facilities.yml
the new fields are :operating_status
Adding :operating_status to the facilities serializer
Until we switch over to using the lighthouse API instead of active record this is going to grab the single field we need from lighthouse.
department-of-veterans-affairs/va.gov-team#7452
This is adding the fields as `nil` until we switch over to the lighthouse client.
=> Adding fields to va facilities response

app/mailers/spool_submissions_report_mailer.rb, app/mailers/year_to_date_report_mailer.rb, spec/mailers/spool_submissions_report_mailer_spec.rb, spec/mailers/year_to_date_report_mailer_spec.rb
In order to test the validity of the YTD and Spool reports after making changes to them for [7272](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/7272) Two additional emails must be added to the staging recipients list.
[7272](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/7272)
This is just a change to add two additional email addresses to the staging recipients. Additionally, while making this change we are removing an email address for one of our team members from the production recipients list.
Testing passes locally and specs have been updated to reflect the appropriate email addresses.
=> Bah 7272 Addition and Removal of Emails from Report Mailers 

lib/mdot/address.rb, lib/mdot/schemas/submit.json, lib/mdot/schemas/supplies.json, lib/mdot/supply.rb, spec/models/form_profile_spec.rb, spec/support/vcr_cassettes/mdot/get_supplies_200.yml
This adds a field to the MDOT prefill for `is_military_base` which is attached to either a permanent or temporary address. This field signifies to the DLC that the incoming address is on a US military base.
Another field has also been added for `prescribedDate` - this will allow the veteran to see when their hearing aid was prescribed.
[8081](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8180)
[7304](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7304)
=> [8081 ] Add isMilitaryBase to MDOT Prefill Address

Dockerfile
move `git` installation to Dockerfile `base` section because `git` is called inside the Rails app (app_info.rb).
This is now causing an error that terminates the server process.
=> move `git` installation to Dockerfile `base` section

Gemfile.lock, modules/appeals_api/appeals_api.gemspec
We just upgraded to Rails 6.
Since all of our `modules` only live inside of `vets-api` (as opposed to being extracted as gems), specifying a rails version in the modules isn't necessary.
=> Remove explicit 'rails' dependency from modules/appeals_api

config/features.yml
eBenefits is currently working on a change that will allow users with an
SSOe session to stay authenticated when navigating over. However this
will only work if the user is proxied via the eauth.va.gov domain.  This
flag will be used within the vets-website to determine the URL format
that should be used when linking a user to eBenefits.
references https://github.com/department-of-veterans-affairs/va.gov-team/issues/8291
=> adding a new ssoe_ebenefits_links feature flag

lib/common/models/concerns/active_record_cache_aside.rb, lib/common/models/concerns/cache_aside.rb
Removes duplicate calls to 
```ruby
Rails.application.config_for(:redis)
```
since this is [already done in the `01_redis.rb` initializer](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/initializers/01_redis.rb#L4).
- department-of-veterans-affairs/va.gov-team#6865
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/6262
This PR closes out a few places that were forgotton in the main PR to consolidate redis config declarations here: https://github.com/department-of-veterans-affairs/vets-api/pull/4182
=> remove redundant redis conflig load calls

app/mailers/spool_submissions_report_mailer.rb, app/mailers/year_to_date_report_mailer.rb, spec/mailers/spool_submissions_report_mailer_spec.rb, spec/mailers/year_to_date_report_mailer_spec.rb
Removing personal email added as a workaround for issue blocking VA.gov emails. Also, removing client email who no longer wishes to receive these reports.
N/A
N/A
Build and deploy locally
=> Bah remove personal email

spec/models/saml_request_tracker_spec.rb
Fixes an issue where, with certain seeds e.g. `bin/rspec spec --seed 18337`, a rspec test [was failing](http://jenkins.vfs.va.gov/blue/organizations/jenkins/testing%2Fvets-api/detail/PR-4167/7/pipeline/) because of a timecop shift in another spec. Big ups 👍to @SMLuthi who figured out why the in_progress_form_cleaner_spec.rb was cleaning too many things.
local unit tests run with seed and without (a random one)
=> add timecop.return after saml request tracker specs that shift time

config/features.yml
This adds a feature flag specifically to toggle automatic establishment/disconnection of a `vets-api` session based on a user's SSOe session status. This is intended to be temporary so debugging this feature isn't a blocker to SSO as a whole.
=> Add feature flag for sso auto-login/logout

config/routes.rb, modules/vaos/spec/routing/vaos_routing_spec.rb
There is no specific issue -- this was something quickly identified as an issue while regression testing.
**IMPORTANT:** These changes must go out before the next production deploy, or we'd have to rollback previous changes.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/7823
Fixes one of the custom nested resource routes to correctly set the :system_id
Added a few specs. The issue was identified when encountering 404 on staging during a quick regression test.
=> VAOS - Urgent Fix for 404 routes

config/routes.rb, modules/vaos/spec/routing/vaos_routing_spec.rb
Found a few more 404 errors. This should be the last time this is an issue, because I took my own advice and introduced comprehensive specs for every single one of the 22 request types, and tested them both for /v0/vaos and /vaos/v0
Sorry for the grief on this one -- still need this urgently to avoid blowing up production.
All 44 specs are passing. I'm satisfied. 
https://github.com/department-of-veterans-affairs/vets-api/pull/4130/files
Nothing not already described above.
=> VAOS - urgent More 404 routing issues

app/swagger/requests/gibct/yellow_ribbon_programs.rb, app/swagger/schemas/gibct/yellow_ribbon_programs.rb
**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/8525
This PR updates the swagger docs for the new YR endpoint.
=> Update swagger docs for YR endpoint

app/controllers/v0/caregivers_assistance_claims_controller.rb, config/features.yml, config/routes.rb, lib/carma/models/submission.rb, spec/controllers/v0/caregivers_assistance_claims_controller_spec.rb, spec/lib/carma/models/submission_spec.rb
Add two feature flags:
**allow_online_10_10cg_submissions**
Will enable and diable to the ability to submit a caregiver's assistance claim (10-10cg).
**stub_carma_responses**
When enabled, this will prevent external requests to CARMA on 10-10cg submissions, and instead, use a stubbed CARMA response.
When disabled, this will push 10-10cg submission to CARMA.
N/A
Caregivers Assistance Claims (online 10-10cg submission) is a feature that has not been released yet. Disabling this functionality will not affect any users or existing services on va.gov.
Please enable these defaults when deployed:
**Staging**
**Production**
=> Add 10-10CG Feature Flags

docker-compose.review.yml, docker-compose.test.yml, docker-compose.yml
After releasing #4219 there were issues with starting the local Docker instance used for development:
```
rails aborted!
Errno::EADDRNOTAVAIL: Cannot assign requested address - connect(2) for [::1]:6379
/usr/local/bundle/gems/redis-3.3.5/lib/redis/connection/ruby.rb:199:in `connect_addrinfo'
/usr/local/bundle/gems/redis-3.3.5/lib/redis/connection/ruby.rb:239:in `block in connect'
/usr/local/bundle/gems/redis-3.3.5/lib/redis/connection/ruby.rb:237:in `each'
/usr/local/bundle/gems/redis-3.3.5/lib/redis/connection/ruby.rb:237:in `each_with_index'
/usr/local/bundle/gems/redis-3.3.5/lib/redis/connection/ruby.rb:237:in `connect'
/usr/local/bundle/gems/redis-3.3.5/lib/redis/connection/ruby.rb:313:in `connect'
/usr/local/bundle/gems/redis-3.3.5/lib/redis/client.rb:336:in `establish_connection' …
```
=> Override Redis configuration for development Docker container

app/models/evss_claims_sync_status_tracker.rb, config/initializers/01_redis.rb
Rails 6.1 will not support accessing values from the `Rails.application.config_for` with strings.
* changed `01_redis` initializer to pass `Redis.new` a plain hash instead of the `Rails::Application::NonSymbolAccessDeprecatedHash` generated from `ActiveSupport::OrderedOptions`
* changed `EVSSClaimsSyncStatusTracker` where it was using string keys for redis config
=> Resolve Rails 6.1 deprecation warning for ActiveSupport::OrderedOptions

README.md
The Sidekiq Enterprise setup instructions have been migrated from `vets.gov-team` to `va.gov-team-sensitive`. This PR updates the link to the Sidekiq Enterprise setup instructions.
https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/8334
Ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/8334
PR to delete content from vets.gov-team: https://github.com/department-of-veterans-affairs/vets.gov-team/pull/20117
PR to add content to va.gov-team-sensitive: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/102
PR to update link in vets-api: https://github.com/department-of-veterans-affairs/vets-api/pull/4239
=> Update link to Sidekiq Enterprise instructions

app/models/user.rb, spec/lib/mvi/messages/add_person_message_spec.rb, spec/policies/mvi_policy_spec.rb
We were troubleshooting an disability claim with a veteran and we were unable to retrieve a veteran's rated disability from evss because we were sending a nil value to evss for gender. The veteran had a gender in MVI, but gender was nil from the identity provider (id.me).  
https://github.com/department-of-veterans-affairs/vets-api/pull/1666 changed the order of presedence for the data. 
MHV gives us a limited subset of the attributes that the other identity providers so we were using `mhv_icn.present?` as a way to determine if the user logged in with MHV (and therefore we'd need to look up all the attributes in MVI). But now, there's no reason not to use the identity provider's data first, and MVI's data second (note: we only do MVI lookups for LOA3 users). …
=> [Bugfix] For user attributes, first look at the identity provider, then MVI

docker-compose.test.yml
CI uses the `docker-compose.test.yml` file to run. Running our specs uses fakeredis which basically stores everything in memory w/o the need for an actual redis instance.
None.
[This PR](https://github.com/department-of-veterans-affairs/vets-api/pull/4219/files) that changed how we configured redis, [broke some local developer environments using docker](https://dsva.slack.com/archives/CBU0KDSB1/p1588769539100500). Reason being that the redis settings in the docker-compose.yml file were not updated to reflect the latest changes to settings.yml.
That led us to [updating said docker-compose.yml environment settings](https://github.com/department-of-veterans-affairs/vets-api/pull/4229/files).
In all of that☝️, CI never failed. It doesn't need redis at all to run. It's probably best to remove …
=> remove redis from testing docker compose

app/services/form1010cg/service.rb, spec/lib/emis/veteran_status_service_spec.rb, spec/request/caregivers_assistance_claims_request_spec.rb, spec/request/swagger_spec.rb, spec/services/form1010cg/service_spec.rb
Resolves: https://github.com/department-of-veterans-affairs/va.gov-team/issues/8870
Add veteran verification to form 10-10cg submission. Send the veteran status with the submission to CARMA. Raise client error if veteran status cannot be confirmed.
- `Form1010cg::Service` has a new method called `:is_veteran` which takes a provided form subject and checks `eMIS` for their veteran status.
- `Form1010cg::Service#assert_veteran_status` now raises a client error if the veteran specified on the form cannot be verified as a veteran in `eMIS`.
- `Form1010cg::Service#build_metadata` returns an additional value in the `:veteran` namespace.
- It is considered a client error if the 10-10CG submission has a person in the veteran section who cannot be confirmed. These users will be directed to submit …
=> Add veteran verification to 10-10CG submissions

lib/forms/schemas/forms.json, modules/va_forms/app/models/va_forms/form.rb, modules/va_forms/app/serializers/va_forms/form_detail_serializer.rb, modules/va_forms/app/serializers/va_forms/form_list_serializer.rb, modules/va_forms/app/swagger/va_forms/forms/form_swagger.rb, modules/va_forms/app/workers/va_forms/form_reloader.rb, modules/va_forms/spec/factories/forms.rb, modules/va_forms/spec/models/form_spec.rb, modules/va_forms/spec/workers/form_reloader_spec.rb, spec/support/schemas/va_forms/form.json, spec/support/schemas/va_forms/forms.json
The Lighthouse service VA Forms generates a local DB via a `form_reloader` script that scrapes va.gov/vaforms/ to build a local DB. However, sometimes forms are deleted entirely off of va.gov/vaforms/. Currently, this change isn't reflected at all in the Lighthouse Forms DB. There isn't a "deleted" flag. However, there is a "valid_pdf" flag. This PR makes use of that by flipping the "valid_pdf" to false for all forms that are in the internal DB but not found during the latest scrape. It also exposes `valid_pdf` for each form model in `/services/va_forms/v0/forms` (Lighthouse) and `/v0/forms` (Vets-API standard route). During the next scrape, this should set about 50-100 forms to `valid_pdf: false` because a bunch of forms were removed off of `/vaforms` recently. …
=> [Lighthouse Forms] Update migration script to account for removed forms

rakelib/security.rake
As mentioned in the commit message, this temporarily ignores a CVE reported on the `rack` gem since the other locked gem versions block the upgrade (department-of-veterans-affairs/va.gov-team#8953)
=> Ignore CVE-2020-8161 until `rack` gem can be upgraded

docker-compose.yml
Our Docker container for development exports the Postgresql port on a non-standard local port so it can be accessed during development. We do not do the same for Redis until now.
This PR exposes Redis using a similar manner to what we currently do with Postgresql -- adding a zero to the standard port number `6379` + `0` => `63790`
None, but noticed as part of working on #4229
=> Expose redis port for Docker development

app/controllers/v0/post911_gi_bill_statuses_controller.rb, app/models/id_card_attributes.rb, app/models/user.rb, app/models/user_identity.rb, app/services/bgs/dependent_service.rb, lib/evss/jwt.rb, lib/saml/user_attributes/base.rb, lib/saml/user_attributes/ssoe.rb, spec/factories/users.rb, spec/lib/saml/ssoe_user_spec.rb
The prominent change is making email optional in the `UserIdentity` class, this will allow access for inbound SSOe users that do not have an email address on file.
There are a few cases in the vets-api where `user.email` is expected to always have a value.  To remedey this we've introduced a new `common_name` attribute that will be set to the `va_eauth_commonname` value when authenticated via SSOe and the user's email when not using SSOe.
In the cases where an email address is optional, we've updated the code to use `user.email` or an empty string.  In the cases where its required, we've found that the caller just needs a unique identifier, so we've updated those cases to use the new `common_name` attribute.
closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/8305
=> user email is now optional

app/controllers/v1/sessions_controller.rb, lib/saml/errors.rb, lib/saml/user_attributes/ssoe.rb, spec/controllers/v1/sessions_controller_spec.rb, spec/lib/saml/ssoe_user_spec.rb
SSOe may provide comma-separated multivalue attributes for some fields.
This makes the parsing code robust to that, and also enforces validation
on the MHV ID, EDIPI, and ICN fields to ensure that there are no
conflicting values.
- Parses comma-separated values in the mhvien and dodedipnid attributes from SSOe SAML
- Validates that there is one and only one value present for MHV ID, EDIPI, and ICN across all the fields where those values may appear.
- Prevents login if above is not true.
- Adds new "auth failed" codes that can be consumed by frontend (TBD) to present a more specific message to the user. Content for those messages will be borrowed from the current MHV-specific errors when multiple MHV IDs are present, and then submitted to appropriate website/content teams for review. …
=> Handles and validates multi-value fields in SSOe

config/settings.yml
Add backend tools engineers as flipper admins.
=> Add backend tools engineers to flipper admin

.codeclimate.yml, .rubocop.yml, rakelib/lint.rake
We already run rubocop through overcommit locally and as part of the CI process. The run on CodeClimate is duplicative *and* requires keeping up the version from a separate configuration which over time has drifter (v0.82 in code, v0.78 configured in CodeClimate config). 
Furthermore, the `rubocop-thread_safety` gem isn't well supported and has led to the situation where to make CodeClimate work, we've made it harder to run rubocop locally (without the -r flag to manually include the thread safety gem) *and* made it impossible to run our current configuration of `guard`.
This PR removes the duplicative plugins in CodeClimate in favor of running them in our CI environment.
Before:
```
vets-api (master) $ bundle exec rubocop
Error: …
```
=> Disable rubocop, brakeman, and bundler-audit CodeClimate plugins

app/services/form1010cg/service.rb, spec/request/caregivers_assistance_claims_request_spec.rb, spec/request/swagger_spec.rb, spec/services/form1010cg/service_spec.rb
Resolves: https://github.com/department-of-veterans-affairs/va.gov-team/issues/9117
Remove the veteran verification on 10-10cg form submissions. Allow a submission to be submitted and flow to CARMA as long as the veteran on the form is in MPI.
=> Remove vet verification on 10-10cg submissions. Update related specs.

Dockerfile
Revert "move `git` installation to Dockerfile `base` section because `git` is called inside the Rails app (app_info.rb). (#4175)"
This reverts commit 4e50ec8cf3e91a660aaa462ff414c03536476f6c.
The underlying issue that led to this PR being needed has been solved by
removing the dependency on `git` in the `AppInfo` module which is in #4275 
=> Remove temporary fix that put `git` in Dockerfile for production

config/initializers/app_info.rb
We used to have the current SHA of the release available in the initializer. This was broken when infra moved to Docker.
department-of-veterans-affairs/va.gov-team#9131
- Associated `devops` [pull request](https://github.com/department-of-veterans-affairs/devops/pull/6945)
=> Revise AppInfo to get ref from env

config/routes.rb, modules/vaos/spec/routing/vaos_routing_spec.rb
The vets-website has merged their changes and are now using the new 'vaos/v0' routing convention instead of the 'v0/vaos' so these rewrite rules can now safely be removed.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/8620
Nothing of note.
Have verified that the new routes are working as expected on staging and production and we have comprehensive test coverage of all of those routes in `vaos_routing_spec.rb`
=> VAOS - removing the temporary 'v0/vaos' routing.

app/controllers/application_controller.rb, spec/request/csrf_request_spec.rb
CSRF violations are currently returning 500 errors to the frontend.
This changes that behavior to return a 403 Forbidden response instead.
Tested on a review instance to verify that `ActionController::InvalidAuthenticityToken` events will [still be visible in Sentry](http://sentry.vfs.va.gov/vets-gov/platform-api-development/issues/120619/).
Response includes messaging to indicate that an invalid authenticity token is the reason for the 403.
Sample response:
`{"errors":[{"title":"Forbidden","detail":"Invalid Authenticity Token","code":"403","status":"403"}]}`
department-of-veterans-affairs/va.gov-team-sensitive#44
department-of-veterans-affairs/va.gov-team-sensitive#42
department-of-veterans-affairs/va.gov-team-sensitive#61
N/A
=> return 403 status code for CSRF token violations

modules/appeals_api/config/schemas/200996.json
resolves https://vajira.max.gov/browse/API-935
forgot to anchor the area code regex with `^$`
=> Decision Reviews API - Anchor Area Code Regex

app/models/user.rb, app/services/users/profile.rb, spec/request/user_request_spec.rb, spec/support/schemas/user_loa3.json
Provides indicators for conditions around MHV access eligibility in the user profile:
- va_patient - whether the user has registered identifiers at any VA treating facility
- mhv_account_state - whether the user has correlated MHV account identifiers in their MVI profile.
These are used by the frontend to gate access to MHV, in conjunction with https://github.com/department-of-veterans-affairs/vets-website/pull/12624. That PR eliminates the calls to create/upgrade MHV accounts when SSOe is used, in favor of sending the user to MHV to register/upgrade their account there. 
Eventually, these new profile attributes can replace the separate call to the mhv_account API endpoint, and all the complexity of tracking mhv account state can be eliminated. vets-api will do some basic …
=> Add patient info to profile

Gemfile, Gemfile.lock
Downgrade simplecov to < 0.18 due to bug with reporting to CodeClimate
https://github.com/codeclimate/test-reporter/issues/418
With `simplecov` v0.18:
```
[2020-05-19T22:12:14.445Z] Finished in 9 minutes 6 seconds (files took 13.95 seconds to load)
[2020-05-19T22:12:14.445Z] 5593 examples, 0 failures, 8 pending
[2020-05-19T22:12:14.699Z] 
[2020-05-19T22:12:14.699Z] Randomized with seed 7883
[2020-05-19T22:12:14.699Z] 
[2020-05-19T22:12:17.952Z] Coverage report generated for RSpec to /srv/vets-api/src/coverage. 32767 / 33066 LOC (99.1%) covered.
[2020-05-19T22:12:17.952Z] reporting coverage to CodeClimate
[2020-05-19T22:12:17.952Z] Error: json: cannot unmarshal object into Go struct field input.coverage of type []formatters.NullInt
[2020-05-19T22:12:17.952Z] Usage: …
```
=> Downgrade simplecov to < 0.18 due to bug with reporting to CodeClimate

modules/veteran_verification/VETERAN_VERIFICATION.yml
Minor update to correct documentation yml return type of the disability rating endpoint.
https://vajira.max.gov/browse/API-661
=> Updated disability-rating yml documentation for response type.

modules/vba_documents/app/workers/vba_documents/upload_processor.rb, modules/vba_documents/spec/jobs/upload_processor_spec.rb
One of our consumers sent us an array of json objects instead of just an actual json object which we never validated against so this PR fixes that and ensures we fail invalid non json objects for metadat in the future.
https://vajira.max.gov/browse/API-946
=> Validating JSON object instead of JSON content

app/models/user.rb, spec/request/user_request_spec.rb
When `va_profile.active_mhv_ids` is `nil` the `mhv_account_state` method can result in an error.
http://sentry.vfs.va.gov/vets-gov/platform-api-staging/issues/120906/?query=is%3Aunresolved
=> fix for when active_mhv_ids is nil

app/models/saved_claim/caregivers_assistance_claim.rb, spec/models/saved_claim/caregivers_assistance_claim_spec.rb
Allow a `CaregiversAssistanceClaim` to receive `:to_pdf` now that it has the capability.
=> Allow CaregiverAssistanceClaims to generate a PDF now.

docs/setup/native.md
This PR is the steps that I had to take to get vets-api running on Ubuntu 20.04. I did not use the 18.04 instructions because it has you use a script that installs things I don't need like `vlc`.
=> Update native install instructions to support Ubuntu 20.04

config/initializers/01_redis.rb
As part of duplicating our redis application data the VAEC redis instance, we accidentally configured the secondary to be the primary... so rather than duplicating data, we've been just calling commands twice on the same redis. 😊 😬 
- We've been doing this in `dev` since 👉 https://github.com/department-of-veterans-affairs/vets-api/pull/4210
- We've been doing this in `prod` since 👉 https://github.com/department-of-veterans-affairs/devops/pull/6967
Make the proper config change.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/6865
=> Redis duplication bug fix

app/models/user.rb, spec/models/user_spec.rb
Only call EVSS PCIU endpoints for LOA3 users with and EDIPI.  EVSS requires an EDIPI 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/8676
=> Only call EVSS - PCIU endpoints for LOA3 users with an edipi

app/controllers/v0/sessions_controller.rb, app/controllers/v1/sessions_controller.rb, config/initializers/statsd.rb, spec/controllers/v0/sessions_controller_spec.rb, spec/controllers/v1/sessions_controller_spec.rb
New tags have been added to track differences between v0 and v1 sessions, however the current statsd initialization code doesn't address all the new combinations of tags in use.  This PR addresses that, so we can accurately track increases in grafana.
refs https://github.com/department-of-veterans-affairs/va.gov-team/issues/9428
=> reworking session controllers statsd init

config/application.rb, config/settings.yml
Allows for configuration of allowed CORS origin domains using regex
https://github.com/department-of-veterans-affairs/va.gov-team/issues/9445
A default allowed value of `https://www.va.gov` is provided in `settings.yml`.
This will ensure that `Settings.web_origin_regex` is never `nil` and thus the evaluation of `Regexp.new(Settings.web_origin_regex)` won't raise an exception.
=> Allow regex for allowed CORS origin domains

config/settings.yml, modules/appeals_api/app/workers/appeals_api/higher_level_review_upload_status_batch.rb, modules/appeals_api/lib/appeals_api/form_schemas.rb, modules/appeals_api/spec/workers/higher_level_review_upload_status_batch_spec.rb, modules/appeals_api/spec/workers/higher_level_review_upload_status_updater_spec.rb, spec/support/vcr_cassettes/decision_review/200_contestable_issues.yml, spec/support/vcr_cassettes/decision_review/200_intake_status.yml, spec/support/vcr_cassettes/decision_review/200_review.yml, spec/support/vcr_cassettes/decision_review/202_intake_status.yml, spec/support/vcr_cassettes/decision_review/202_review.yml, spec/support/vcr_cassettes/decision_review/303_intake_status.yml, spec/support/vcr_cassettes/decision_review/400_contestable_issues.yml, spec/support/vcr_cassettes/decision_review/400_intake_status.yml, spec/support/vcr_cassettes/decision_review/400_review.yml, spec/support/vcr_cassettes/decision_review/403_intake_status.yml, spec/support/vcr_cassettes/decision_review/404_contestable_issues.yml, spec/support/vcr_cassettes/decision_review/404_get_intake_status.yml, spec/support/vcr_cassettes/decision_review/404_intake_status.yml, spec/support/vcr_cassettes/decision_review/404_review.yml, spec/support/vcr_cassettes/decision_review/409_intake_status.yml, spec/support/vcr_cassettes/decision_review/422_contestable_issues.yml, spec/support/vcr_cassettes/decision_review/422_intake_status.yml, spec/support/vcr_cassettes/decision_review/502_contestable_issues.yml, spec/support/vcr_cassettes/decision_review/502_intake_status.yml, spec/support/vcr_cassettes/decision_review/502_review.yml
This comment https://github.com/department-of-veterans-affairs/vets-api/pull/4293#discussion_r427291436
prompted me to look at `lib/decision_review` and realize that, at some point, we started putting our settings under `decision_review` ***which is not owned by the Lighthouse Appeals API team***. My best guess is that the va.gov front-end team (which will eventually be consuming the Appeals API) owns `decision_review` in `settings.yml`
=> Appeals API - Pull Our Settings Out of `decision_review`

lib/saml/user_attributes/ssoe.rb, spec/lib/saml/ssoe_user_spec.rb
Incoming SAML paylods from SSOe have birth date without
dashes between elements. This breaks other code that was
expecting the date in a certain format, so we coerce the
birth date field to match the expected format.
Fixes https://github.com/department-of-veterans-affairs/va.gov-team/issues/9623
=> Coerces SSOe-provided birth dates to ISO format

lib/saml/url_service.rb, spec/controllers/v1/sessions_controller_spec.rb
Adds support for an additional parameter `to` that can be specified along with `application` in the signin process. The to parameter is intended as a relative path that gets tacked on to the redirect URL derived from `application`, to construct a complete redirect URL. 
department-of-veterans-affairs/va.gov-team#8587
No feature flags or additional settings.
Allowing our system to redirect based on user input presents some risk, as described in https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html
We mitigate  this by:
- Not letting the caller specify the entire URL, but only the path part - the base URL/domain is derived from the `application` parameter whose configuration we control.
- Ensuring that we join the base URL and `to` parameter with …
=> Additional redirect parameter 

lib/evss/disability_compensation_form/data_translation_all_claim.rb, spec/lib/evss/disability_compensation_form/data_translation_all_claim_spec.rb
https://github.com/department-of-veterans-affairs/vets-api/pull/4302 significantly lowered our error rate for regex validations on the `treatmentCenterName` but didn't go far enough.  @annaswims figured out that mult spaces were also a cause for rejection.  This PR replaces mult whitespace characters with a single space.
Last 2 weeks of regex errors, blue line is deployment of PR 4302
http://grafana.vfs.va.gov/d/000000066/evss-526-submissions?panelId=16&fullscreen&orgId=1&from=now-15d&to=now
second PR for department-of-veterans-affairs/va.gov-team/issues/9121
- Instead of adding to that gsub line, I added a second gsub method- I thought this would make this mess more readable
=> BUG FIX- Form 526: Part 2, Remove mult whitespace from treatmentCenterName

app/controllers/application_controller.rb, spec/request/csrf_request_spec.rb
non-GET/non-HEAD unknown routes are resulting in CSRF violations.
This obscures what the root problem is (route is unkown).
[Sentry example.](http://sentry.vfs.va.gov/vets-gov/platform-api-staging/issues/120232)
=> exempt unknown routes from CSRF verification

config/initializers/breakers.rb, lib/evss/reference_data/configuration.rb, spec/lib/evss/reference_data/service_spec.rb
configure breakers so that we can see stats for EVSS reference data stats in [Backend Service Report ](http://grafana.vfs.va.gov/d/000000050/backend-service-report?orgId=1)
https://github.com/department-of-veterans-affairs/va.gov-team/issues/8387
=> add EVSS/AWS/ReferenceData to breakers

config/form_profile_mappings/686C-674.yml, spec/models/form_profile_spec.rb
This is a small adjustment to the prefill data structure associated with the 686c form. As that task evolves, so does the structure of the data.
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/9222
686c BE code is not quite ready. This just prefill data to help the veteran by populating info we already know about them.
From what I understand, there is no way to manually test if data is populating properly w/o going to staging, ~I've asked the engineer who initially implemented this to verify that's the case.~ Previous engineer responded. They relied on specs.
* Are there Swagger docs that were updated?
No
* Is there any PII concerns or questions?
No
Associated tests have been updated and are passing.
=> Form Prefill - config and yml changes to support FE form structure

modules/vaos/app/models/vaos/appointment_request_form.rb, modules/vaos/app/serializers/vaos/v0/appointment_requests_serializer.rb, modules/vaos/spec/models/cc_appointment_request_form_spec.rb, spec/support/schemas/vaos/appointment_request.json
This adds the reason_for_visit field to the appointment request form. This field holds the reason that users select when they make an express care appointment. It's unused for regular requests.
department-of-veterans-affairs/va.gov-team#9976
Verified that this change fixes the issue on a review instance and resolves the error in Scheduling Manager.
=> Add missing reason for visit field

spec/rails_helper.rb, spec/spec_helper.rb, spec/support/sidekiq/batch.rb
in https://github.com/department-of-veterans-affairs/vets-api/pull/4345 I intended to load the new `Sidekiq::Batch` definition once, after sidekiq-pro was loaded.  but I goofed. `before(:all)` ran not just once before all tests.  this fixes that.
=> fix sidekiq batch loading

Procfile, sidekiq-admin.ru
Allow sidekiq-admin to be run with basic authentication in any environment, including production
~`SIDEKIQ_USERNAME=foo SIDEKIQ_PASSWORD=bar bundle exec foreman s sidekiq-admin`~
`SIDEKIQ_USERNAME=foo SIDEKIQ_PASSWORD=bar REDIS_URL=redis://some.elasticache.aws.url bundle exec rackup sidekiq-admin.ru -p 3000 -o 0.0.0.0`
department-of-veterans-affairs/va.gov-team#8151
There are additional PRs to be done in the department-of-veterans-affairs/devops repo and credstash to add:
Not user-facing, so outside of ensuring that this does not run by default in any environment when using foreman, there's no more formal testing.
Tested on staging and production. It can take *minutes* to load the data, so be prepared.
=> Add sidekiq admin rack application

Makefile, README.md
This change adds a target that allows you to get a `help` from the makefile with inline documentation explaining what each of the targets do.
It also uses a more canonical way of setting a default target for the makefile for gnu make.
n/a
Tested running the target locally.
=> Adds help target to makefile

config/betamocks/services_config.yml
Add the routes for `/contestable_issues` endpoint mock data (vets-api-mockdata) to Betamocks services_config.yaml
[Related vets-api-mockdata PR](https://github.com/department-of-veterans-affairs/vets-api-mockdata/pull/139)
=> Lighthouse Appeals API - Contestable Issues Mock Data

lib/common/client/base.rb
I was trying to understand why the following Sentry issue (http://sentry.vfs.va.gov/vets-gov/platform-api-production/issues/121637/?query=vaos) is showing the wrong url, or more importantly why the URL doesn't make any sense. Then I came a cross this line of code that I committed 3 years ago and somehow no one has identified as broken. 
It's come full circle :)
No issue, just quick PR
Simple fix for Sentry extra_context logs.
=> Timeout Exception was logging base_path instead of actual path (fixed)

config/puma.rb
During the work to scale puma, the PUMA_PRELOAD environment variable
was added to make it easier to toggle application preloading in the
staging and production environments. With months of successful running
with this variable being TRUE in staging and production it is long past
time to clean up this env var here and in the devops repo.
department-of-veterans-affairs/va.gov-team#3849
This is effectively _removing_ a feature flag set by the devops configuration of environment variables in 
```
/ansible/deployment/config/vets-api-server-vagov-staging.yml
/ansible/deployment/config/vets-api-server-vagov-production.yml
```
Once this is merged, please also ensure the environment variables are removed from the devops repo by merging the following PR
Will monitor staging after deployed, but …
=> Remove PUMA_PRELOAD environment var guard clause

modules/claims_api/app/swagger/claims_api/description/v0.md
Update description with optional Base64 instructions and links to cURL and raw Base64 examples for individual PDFs.
The team decided to call out this option in the description because it works differently from the benefits-intake API and it generated some confusion among users. The proposed change addresses the issue.
@bastosmichael feel free to change write-up if we need to add any more details.
=> Add Optional Base64 Encoding Blurb

app/controllers/v1/sessions_controller.rb, config/initializers/statsd.rb, lib/saml/url_service.rb, spec/controllers/v1/sessions_controller_spec.rb
We have statsd counters to track all the new inbound requests we receive, however we don't have a good way to account for which SAML responses come back from SSOe that are for inbound requests.  Adding these metrics will allow us to track that.
=> adding metrics to track inbound ssoe success/failure responses

app/controllers/v0/vso_appointments_controller.rb, app/models/vso_appointment.rb, config/initializers/inflections.rb, lib/evss/vso_search/configuration.rb, lib/evss/vso_search/service.rb, lib/vsopdf/vso_appointment_form.rb, modules/claims_api/spec/unsynchronized_evss_claims_service_spec.rb, modules/veteran/app/models/veteran/user.rb, modules/veteran/app/workers/veteran/vso_reloader.rb, modules/veteran/lib/tasks/veteran_tasks.rake, modules/veteran/spec/models/veteran/user_spec.rb, modules/veteran/spec/workers/veteran/vso_reloader_spec.rb, spec/controllers/v0/vso_appointments_controller_spec.rb, spec/lib/evss/power_of_attorney_verifier_spec.rb, spec/lib/evss/vso_search/configuration_spec.rb, spec/lib/evss/vso_search/service_spec.rb, spec/lib/vsopdf/vso_appointment_form_spec.rb
Introduce VSO inflection as part of prep-work for enabling zeitwerk.  All references to `Vso` have become `VSO`.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/10165
=> Zeitwerk Prep - use VSO inflection

config/locales/exceptions.en.yml, lib/mdot/client.rb, spec/lib/mdot/client_spec.rb, spec/support/vcr_cassettes/mdot/get_supplies_503.yml
- Adds exception handling for 503 errors. If the DLC API is unavailable, this will be relayed to the frontend via a 503 error.
- Adds a 422 error response for handling submissions which have no supplies selected.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/10403
https://github.com/department-of-veterans-affairs/va.gov-team/issues/10024
- 503 Error was mimicked locally using https://stat.us/503
- 422 error handling was tested locally via the ordering tool
=> [10403] 422 No Supplies Selected Error Handling & 503 Service Unavailable Error Handling

config/settings.yml
This adds Filip Fafara from ThoughtWorks team to the list of flipper admins in preparation for VANotify (notifications engine) integration.
=> Add Filip Fafara to flipper admin list

modules/claims_api/app/controllers/claims_api/v0/forms/intent_to_file_controller.rb, modules/claims_api/app/controllers/claims_api/v1/forms/intent_to_file_controller.rb
This PR fixes a typo in the claims ITF error response that causes a 500 error when type is not equal to compensation
=> fix typo in itf error message

config/locales/exceptions.en.yml, lib/decision_review/service.rb, spec/lib/decision_review/service_spec.rb, spec/support/vcr_cassettes/decision_review/401_intake_status.yml
when vets-api calls lighthouse with an invalid API key we should return a 502 & a reasonable message to vets-website.
before:
cc: @Mottie
=> return a clear message when lighthouse API key is incorrect

modules/vaos/app/services/vaos/configuration.rb
Description of change
Previously we were concerned about that the breakers threshold at 50% might cause similar looking endpoints to get grouped within the same threshold and bring down the application. That concern was not borne out. Now I'm concerned that too high a threshold might adversely affect stability of the platform with increase in traffic should there be an actual outage and breakers cannot do what it is intended to do.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/10084
No additional testing planned, but we will continue to monitor Sentry and Grafana as we always do.
=> VAOS - set breakers threshold back to default (50)

modules/claims_api/app/controllers/claims_api/docs/v0/api_controller.rb, modules/claims_api/app/controllers/claims_api/docs/v1/api_controller.rb, modules/claims_api/app/swagger/claims_api/v1/claims_controller_swagger.rb, modules/claims_api/app/swagger/claims_api/v1/form_0966_controller_swagger.rb, modules/claims_api/app/swagger/claims_api/v1/form_2122_controller_swagger.rb, modules/claims_api/app/swagger/claims_api/v1/form_526_controller_swagger.rb, modules/claims_api/app/swagger/claims_api/v1/security_scheme_swagger.rb, modules/claims_api/app/swagger/claims_api/v1/swagger_root.rb
This PR fixes the swagger generation for curl generation on the Claims OAuth endpoints.
=> adding security class to loaded swagger classes and set security blocks

Gemfile.lock
This only updates vets-json schema.
The code to use the separation location data was done in https://github.com/department-of-veterans-affairs/vets-api/pull/4417
Issue: department-of-veterans-affairs/va.gov-team#10090
vets-json-schema changes: https://github.com/department-of-veterans-affairs/vets-json-schema/pull/442
=> update vets-json schema for form526 separation location

app/controllers/v1/sessions_controller.rb, lib/saml/post_url_service.rb, lib/saml/ssoe_settings_service.rb, lib/saml/templates/sso_post_form.html.erb, spec/controllers/v1/sessions_controller_spec.rb, spec/lib/saml/post_url_service_spec.rb, spec/support/saml/form_validation_helpers.rb
Updates v1 session controller to use SAML POST Binding. This is done at request of IAM SSOe team who believes doing so is more in line with intent for their stack and will resolve some outstanding bugs. 
The hard-working "URLService" was unfortunately forked since now it needs to generate SAML POST request form parameters instead of a straight up URL. I think this can be brought back together by the consuming classes being aware of the need to render a form vs. a redirect depending on the scenario. 
Testing in local and dev shows no regression relative to using the SAML Redirect binding. Jury is still out on whether it resolves the suspected list of issues.
department-of-veterans-affairs/va.gov-team#10468
=> Pv saml post binding

modules/appeals_api/app/controllers/appeals_api/metadata_controller.rb, modules/appeals_api/app/controllers/appeals_api/v0/appeals_controller.rb, modules/appeals_api/config/routes.rb, modules/appeals_api/lib/appeals_api/health_checker.rb, modules/appeals_api/spec/requests/metadata_request_spec.rb
This PR adds the metadata controller to the appeals api. Currently the controller just runs the healthcheck for caseflow,  but its supported for v0 and v1 of the api.
=> Add appeals metadata controller

modules/vaos/spec/services/middleware/vaos_logging_integration_spec.rb
Xs out the VAOS logging spec that is only failing on staging so that building is unblocked for other teams.
N/A
=> Temporarily disable flapping VAOS logging integration spec

modules/appeals_api/app/swagger/appeals_api/v1/swagger_root.rb, modules/appeals_api/spec/requests/v1/docs_controller_spec.rb
In preparation for production launch, add `api.va.gov` to Swagger documentation _server_ block.
resolves https://vajira.max.gov/browse/API-934
=> Add Production URL to Appeals API v1 Server Block

modules/vaos/lib/vaos.rb, modules/vaos/spec/services/middleware/vaos_logging_integration_spec.rb, modules/vaos/vaos.gemspec
The VAOS module currently has an issue where sidekiq jobs aren't running. After looking at how other modules are initialized, the VOAS one was generated without an empty module definition in the lib dir and a different load path is defined in the gemspec. Also temporarily disables a logging integration spec that is failing only on staging CI builds.
N/A
=> VAOS init namespace

config/features.yml
https://github.com/department-of-veterans-affairs/va.gov-team/issues/8201
https://github.com/department-of-veterans-affairs/vets-website/pull/12838 removes usages of the feature flag
=> CT-103: Remove 'eduSection103' Feature Flag #8201

Gemfile.lock, app/workers/education_form/education_facility.rb
Allow for form submission of type 22-10203 which is routed to Buffalo RPO 307
Only updates to schema and routing to Buffalo RPO 307 changes were needed as 10203 is already an acceptable form type [if the feature flag `edu_benefits_stem_scholarship` is enabled](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/education_benefits_claim.rb#L5). 
department-of-veterans-affairs/va.gov-team#7857
https://github.com/department-of-veterans-affairs/vets-website/pull/13379 to enable form submission for 10203
Schema changes https://github.com/department-of-veterans-affairs/vets-json-schema/pull/448
=> STEM: Update form 22-10203 submission. #7857

modules/appeals_api/config/schemas/200996.json, modules/appeals_api/spec/fixtures/valid_200996.json, modules/appeals_api/spec/fixtures/valid_200996_extra.json
As a developer, I want their to be as little translation layer between Caseflow and Vets-API, consequently, use Caseflow's field names verbatim (when possible).
Resolves https://vajira.max.gov/browse/API-1376
=> Appeals API v1 - Use Caseflow-style Field Names

Gemfile, Gemfile.lock, modules/vba_documents/spec/request/v1/uploads_request_spec.rb
There is a flapping/blinky spec, which appears to be triggered by an encoding error in the Origami PDF library. We have yet to determine the root cause (it's a difficult one), and in the meantime, we want to unblock production deploys.
We (the BE tools team) identified two immediate ways to unblock deploys:
* Retry the failing spec
* Disable the failing spec
We have an [open PR](https://github.com/department-of-veterans-affairs/vets-api/pull/4453) for disabling the failing spec, but doing so means we lose test coverage for that API endpoint. I don't mean the coverage report, but the loss of actual coverage.
This PR is for the retry option. Introducing `rspec-retry` could, if never removed, theoretically lead to it being used more often, which is not ideal. The trade-off is that we get to …
=> add rspec-retry, set retries=3 for uploads_request_spec, to unblock production deploys

app/controllers/v1/sessions_controller.rb, lib/saml/errors.rb, lib/saml/user_attributes/ssoe.rb, spec/lib/saml/ssoe_user_spec.rb
We want to consider consuming ID.me UUIDs from the accounts table but first are going to collect data about what percentage of inbound users this would help. 
No PII concerns, data is logged to cloudwatch and contains no user-specific identifiers.
=> Logs diagnostics about sessions without ID.me UUID

modules/appeals_api/app/models/appeals_api/higher_level_review.rb, modules/appeals_api/spec/factories/higher_level_reviews.rb, modules/appeals_api/spec/lib/higher_level_review_pdf_constructor_spec.rb
The pdf constructor was expecting there to always be an array for informalConferenceTimes, but, if an informalConference wasn't requested, it returned nil.
Switched it to returing [] when nil.
=> Appeals API v1 - informalConferenceTimes bug

app/controllers/v1/sessions_controller.rb, app/models/user_session_form.rb, spec/models/user_session_form_spec.rb
Detects a SAML payload that is missing an ID.me UUID, and attempts to look one up (based on the presented ICN) in the Accounts table. If a unique mapping is found, injects the idme_uuid into the User/UserIdentity before establishing a session.
There may be users who have ICNs that map to multiple ID.me UUIDs. For now, we are ignoring those until we can decide how to handle them correctly.
We found that ~80% of inbound SSOe sessions did not have an ID.me UUID present.
Of those, between 80-85% of a brief sample were present in the accounts table, and by doing this injection we let those users have auto-login without needing to re-authenticate.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/11096
Should I remove the diagnostic logging from the sessions controller, …
=> Inject ID.me UUID from accounts table

Gemfile, Gemfile.lock, modules/vaos/spec/request/v1/patient_request_spec.rb, spec/factories/mvi_profiles.rb
Removed faker/medical, as it's barely used and an unneeded additional dependency. Moved Faker into development and test group instead of just test group. The reason being that its very handy to use FactoryBot to setup a user in development console and many of our factories depend on Faker.
Specs
None
- [c] Provide which alerts would indicate a problem with this functionality (if applicable)
=> Remove faker medical

config/betamocks/services_config.yml
**Relates vets-api-mockdata PR**: https://github.com/department-of-veterans-affairs/vets-api-mockdata/pull/145
EMIS allows you to get a veteran's status by searching with either an EDIPI or ICN.
vets-api-mockdata only has a sample response for eMIS searches using EDIPI. I'd like to match a Betamocks response from a request searching via an ICN.
The current Betamocks config will filter the entire ICN out of the search resulting in a mockdata lookup of `../vets-api-mockdata/emis/veteran_status/.yml` vs `../vets-api-mockdata/emis/veteran_status/1012740600V714187.yml` (for an eMIS search of `icn: "1012740600V714187"`).
**Summary**
Update eMIS Betamocks config to support eMIS Veteran Status searchs with an ICN.
=> Allow Betamocks searches via ICN for Veteran Status in EMIS

modules/claims_api/lib/claims_api/health_checker.rb
This PR sets the claims healthchecks to be based on the mock flag for evss claims and for MVI
=> base claims healthchecks on the mock flag

lib/mdot/response.rb
MDT Eligibility object is dependent upon pluralized keys. The latest iteration of the DLC API has keys that are singular, this fixes this by pluralizing them prior to determining eligibility.
n/a
=> BUGFIX: Pluralize the Eligibility Keys

app/models/form_profile.rb, spec/models/form_profile_spec.rb
ignore evss pciu errors during prefill so that the rest of the prefill fields can be returned instead of returning a 500
https://github.com/department-of-veterans-affairs/va.gov-team/issues/10798
tested with automated tests
=> ignore evss pciu errors during prefill

app/services/form1010cg/service.rb, lib/carma/README.md, lib/carma/client/client.rb, lib/carma/models/attachments.rb, lib/carma/models/submission.rb, spec/lib/carma/client/client_spec.rb, spec/lib/carma/models/attachments_spec.rb, spec/lib/carma/models/submission_spec.rb, spec/services/form1010cg/service_spec.rb
Fixes: https://github.com/department-of-veterans-affairs/va.gov-team/issues/6686
Update CARMA to get an access token once per submission "session" (submitting data and attachment of a single claim).
Rather than waiting for a 401 from CARMA to get a new access token, I decided to just get a new access token every time a user submits a claim. This results in one request to get a token, second request to submit raw data, third request to send an attachment.
- Convert `CARMA::Client::Client` back to a regular object (revert singleton changes)
- Use a single instance of `CARMA::Client::Client` for the CARMA submission and attachments
- List all dependent services for `Form1010cg::Service` in private methods for clarity
=> Fetch a CARMA access token only once per user submission

app/controllers/concerns/authentication_and_sso_concerns.rb, spec/controllers/application_controller_spec.rb
If an unauthenticated user makes an API call to any controller that uses
the authentication and sso concern, the user's session cookie will
reset.  This is problematic as some forms can be submitted by
unauthenticated users, thus having their CSRF cookie reset early will
prevent the form submission from succeeding.
=> don't reset session cookies for unauthenticated users

config/settings.yml
This PR is to get my email added to the flipper list in settings.yml so that I can turn on flipper toggles in staging and test our flipper implimentation.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/11265
There is an addition to the settings.yml file
=> added my email to settings.yml

modules/claims_api/config/schemas/526.json
Removing unnecessary required field in schema, Mark Greenburge was able to show this validation on va.gov https://github.com/department-of-veterans-affairs/vets-website/blob/7e40a773626d8f0f58742fed6c90f9586707db6c/src/applications/disability-benefits/all-claims/pages/alternateNames.js I think this is a good enough argument then to change it on our end, I reached out to EVSS folks who were not responding but if it were required then every non filled in submission from VA.gov would automatically fail, good enough for me
=> Removing middle name from 526 alternateNames schema

.gitignore, Makefile
Provide a way to run clamav in the Docker container with the Makefile.
department-of-veterans-affairs/va.gov-team#11176
=> Add option to run ClamAV from `make up`

modules/vaos/app/controllers/vaos/v0/appointment_requests_controller.rb, modules/vaos/app/models/vaos/appointment_request_form.rb, modules/vaos/app/serializers/vaos/v0/appointment_requests_serializer.rb, modules/vaos/spec/models/cc_appointment_request_form_spec.rb, spec/support/schemas/vaos/appointment_request.json
This adds the additional information field to the vets-api request form, so that we can see that field on the FE.
department-of-veterans-affairs/va.gov-team#11002
=> Add additional info field to request mapping

modules/appeals_api/app/models/appeals_api/higher_level_review.rb, modules/appeals_api/spec/models/higher_level_review_spec.rb, modules/appeals_api/spec/workers/higher_level_review_upload_status_updater_spec.rb
flatten the Central Mail response to end up with a one-dimensional array of hashes or empty array
=> Appeals API v1 - Bug Fix: Empty Central Mail Response Causing Exception to be Thrown

modules/claims_api/app/controllers/claims_api/base_disability_compensation_controller.rb
the `service` method in app/controllers/claims_api/base_disability_compensation_controller.rb is not being used, as far as I can tell (checked parents and children)
=> Claims API - Remove Unused Method from BaseDisabilityCompensationController

modules/va_forms/app/workers/va_forms/form_reloader.rb
This PR fixes an issue in the VA Forms loader where the faraday adapter is not set when in prod.
=> update and set default faraday adapter when in prod settings

config/settings.yml
This pull request adds the email micah@adhocteam.us to settings.yml, so I can manage feature toggles in flipper for my team. 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/11265
n/a
=> mc - add email to settings

app/controllers/v1/sessions_controller.rb, app/models/user_session_form.rb, config/initializers/statsd.rb, lib/saml/errors.rb, lib/saml/user_attributes/ssoe.rb, spec/controllers/v1/sessions_controller_spec.rb
After reviewing the `user_login` function in the `V1::SessionController` it was noted that the `UserAttributeErrors` are raised when we initialize the `UserSessionForm`, not when we invoke the `valid?` method.  Thus any of these validation errors immediately bubble up to the `saml_callback` method and don't log `login_stats`.  Adding a begin/rescue block around this code will allow us to issue the login stats before moving back to the `saml_callback` method.
Additionally changes were made the tags associated to `api.auth.login.failure` so we can also track the error issued when a failure happens.
fixes https://github.com/department-of-veterans-affairs/va.gov-team/issues/11595
=> fix login status failure stats

app/swagger/swagger/schemas/user_internal_services.rb, lib/saml/user_attributes/ssoe.rb, spec/lib/saml/ssoe_user_spec.rb
this will only be available for users that authenticated via SSOe and is
needed to address a vulnerability with two users using the same
computer.
refs https://github.com/department-of-veterans-affairs/va.gov-team/issues/10303
=> adding transactionid to sign_in property in user serializer

lib/saml/templates/sso_post_form.html.erb
some versions of IE 11 don't work with addEventListner.  Using a
function closure at the end of the page should work for all browsers
fixes https://github.com/department-of-veterans-affairs/va.gov-team/issues/11596
=> using a browser safe ready function to post the saml request

.github/CODEOWNERS
Add @department-of-veterans-affairs/backend-review-group back to VAOS modules as a (co) CODEOWNER to facilitate bug fixes and systemic changes that aren't directly necessary for VAOS team to review. This restores our original capabilities while retaining the new capability of VAOS to review their own code without VSP review.
department-of-veterans-affairs/va.gov-team#11618
=> Add backend review group to vaos

app/mailers/dependents_application_failure_mailer.rb, app/mailers/views/dependents_application_failure.erb, app/services/bgs/people_service.rb, spec/mailers/dependents_application_failure_mailer_spec.rb
This PR adds a mailer and testing to verify all dynamic data is sent through.
The email will get fired if a user's 686c-674 submission fails. [Code for the 686c-674 form is moving through PR](https://github.com/department-of-veterans-affairs/vets-api/pull/4546) and being developed currently.
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/11339
* Mailer should already be configured for each env
* Not on this code particularly but the FE will use Flipper
* There are sentry alerts in other code associated with this process that will fire, …
=> Add 686c-674 failure mailer

lib/lighthouse/facilities/response.rb, spec/request/v1/facilities/va_request_spec.rb, spec/support/vcr_cassettes/lighthouse/facilities.yml
Fix to lib/lighthouse/facilities/response.rb to make pagination work with v1 API.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/11409
We were not returning the pagination metadata correctly.
Also, the use of the paginate method from will_paginate was causing results to be empty if page > 1.
Unit tests have been added to prevent this.
=> Fixes pagination bug: no data when page > 1.

app/models/bgs_dependents/benefit_claim.rb, app/models/bgs_dependents/divorce.rb, app/models/bgs_dependents/marriage_history.rb, spec/models/bgs_dependents/benefit_claim_spec.rb, spec/models/bgs_dependents/divorce_spec.rb, spec/models/bgs_dependents/marriage_history_spec.rb
This PR is a chunk broken off of [this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/4546). It was advised that we break that large PR into smaller more easily reviewable chunks of code to expedite the review process.
This PR is one of a few that are adding models for the 686c form submission. These models will be mostly responsible for serializing data that we are sending/receiving to/from BGS.
department-of-veterans-affairs/va.gov-team#11260
=> [686] Dependents application models 4

Dangerfile
I came across a PR where large changes were made to a `.csv` file that triggered the dangerbot warning. We should not be counting changes to `.csv` files.
Updated the Dangerbot exclusions list to include `.csv` files.
None.
=> exclude .csv files from danger bot

app/models/ppms/specialty.rb, app/serializers/ppms/specialty_serializer.rb, lib/lighthouse/facilities/configuration.rb, spec/request/v1/facilities/ccp_request_spec.rb
when promoting it to a first-class object I forgot the `name` attribute
Adding a missing attribute to the `PPMS::Specialty` object and serializer
department-of-veterans-affairs/va.gov-team#11987
=> Fixing an implementation error around PPMS::Specialty

modules/appeals_api/app/workers/appeals_api/higher_level_review_pdf_submit_job.rb
As Central Mail, I want to know where a HLR Submission came from. Currently, the `source` is whatever the Lighthouse user's consumer name is. Add `Appeals-HLR-` as a prefix so that Central Mail can quickly tell what API submitted the form.
resolves https://vajira.max.gov/browse/API-1661
=> When submitting to Central Mail, add `Appeals-HLR-` prefix to consumer name

spec/request/intent_to_files_request_spec.rb, spec/support/schemas_camelized/evss_errors.json, spec/support/schemas_camelized/intent_to_file.json, spec/support/schemas_camelized/intent_to_file_base.json, spec/support/schemas_camelized/intent_to_files.json
Introduces camel-inflected schemas for the specs used by intent_to_files_request_spec. This ensures we support X-Key-Inflection requests.
=> 11585 add camel inflected schemas for intent to file

spec/request/user_preferences_request_spec.rb, spec/support/schemas_camelized/delete_all_user_preferences.json, spec/support/schemas_camelized/errors.json, spec/support/schemas_camelized/user_preferences.json
#4538  Description of change
Introduces camel-inflected schemas for the specs used by `user_preferences_request_spec.rb`. This ensures we support X-Key-Inflection requests.
=> 11585 add camel inflected schemas to user preferences

spec/request/address_request_spec.rb, spec/support/schemas_camelized/address_domestic.json, spec/support/schemas_camelized/address_international.json, spec/support/schemas_camelized/address_military.json, spec/support/schemas_camelized/address_response.json, spec/support/schemas_camelized/control_information.json, spec/support/schemas_camelized/countries.json, spec/support/schemas_camelized/errors.json, spec/support/schemas_camelized/states.json
Introduces camel-inflected schemas for the specs used by address_request_spec.  This ensures we support `X-Key-Inflection` requests.
=> address request spec supports camel-inflected requests

config/locales/exceptions.en.yml, lib/debts/configuration.rb, lib/debts/get_letters_response.rb, lib/debts/schemas/debts.json, lib/debts/service.rb, spec/lib/debts/service_spec.rb
* Adds exception handling to the Debts service. 
* Adds a 400 Bad Request exception for debts within the exceptions yml file.
* Adds JSON schema validation for Debts responses.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/11791
Tested and verified locally.
=> Add Backend Exception Handling for Debts

Gemfile.lock
`danger` gem has a dependency on `kramdown` which has a vulnerability.  updated danger to get latest kramdown.
`danger`'s changes are merely cosmetic https://github.com/danger/danger/blob/master/CHANGELOG.md#803---804
https://github.com/department-of-veterans-affairs/vets-api/network/alert/Gemfile.lock/kramdown/open
=> update danger and include patched kramdown

modules/claims_api/app/workers/claims_api/vbms_upload_job.rb, modules/claims_api/spec/workers/vbms_upload_job_spec.rb
resolves https://vajira.max.gov/browse/API-1834
Turns out that OpenURI will sometimes return a `Tempfile` and sometimes a `StringIO`:
>The root of this problem is that if you use open(url) on a file smaller than 10kb it will convert it into a string IO object auto-magically instead of using a Tempfile. The StringIO object as everyone has pointed out does not have the path method defined on it.
https://stackoverflow.com/a/23666898
_As a dev, when using VbmsUploadJob, I want s3 urls to always open as Tempfiles, and not sometimes as StringIO's (causing an exception to be thrown because StringIO's don't respond to `:path`)._
My solution is an amalgamation of:
https://stackoverflow.com/a/22937649
https://stackoverflow.com/a/31527533
=> Claims API - Handle Streams That Don't Respond to Path (VbmsUploadJob)

Dangerfile
- Update the ruby danger-bot to ❌ `fail` ❌  PR's exceeding 1000 lines of code
- Updates wording for when these failures occur
https://github.com/department-of-veterans-affairs/va.gov-team/issues/11630
This has been tested over in this separate Draft PR where the message can be seen: https://github.com/department-of-veterans-affairs/vets-api/pull/4596
=> dangerbot to fail large PRs

spec/request/disability_compensation_form_request_spec.rb, spec/support/schemas/rated_disability_base.json, spec/support/schemas_camelized/rated_disabilities.json, spec/support/schemas_camelized/rated_disability_base.json, spec/support/schemas_camelized/submit_disability_form.json, spec/support/schemas_camelized/suggested_conditions.json
Adding camelCase version of tests and schema for the disability compensation form request spec.
=> 11585 add camel inflected schemas to disability compensation form

app/models/bgs_dependents/veteran.rb, lib/bgs/form686c.rb, lib/bgs/service.rb, lib/bgs/vnp_veteran.rb, spec/factories/686c/form_686c_674.rb, spec/lib/bgs/benefit_claim_spec.rb, spec/lib/bgs/dependents_spec.rb, spec/lib/bgs/form686c_spec.rb, spec/lib/bgs/marriages_spec.rb, spec/lib/bgs/service_spec.rb, spec/lib/bgs/student_school_spec.rb, spec/lib/bgs/vnp_benefit_claim_spec.rb, spec/lib/bgs/vnp_relationships_spec.rb, spec/lib/bgs/vnp_veteran_spec.rb, spec/models/bgs_dependents/veteran_spec.rb
This is an adjustment to support a passing in a user object in instead of a hash for the 686c form.
department-of-veterans-affairs/va.gov-team#11260
=> [686] Change User hash to User object

lib/tasks/support/schema_camelizer.rb, spec/lib/tasks/support/schema_camelizer_spec.rb
Some of the tests that use schema matchers refer to schemas in a directory nested under `spec/support/schemas` and this change is so the `SchemaCamelizer` supports those schema files.
Also cleaned up the error message around saving when the output path is not different.
=> 11585 schema camelizer supports nested directories

spec/request/full_name_request_spec.rb, spec/request/health_records_request_spec.rb, spec/support/schemas_camelized/eligible_data_classes.json, spec/support/schemas_camelized/extract_statuses.json, spec/support/schemas_camelized/full_name_response.json
CamelCase schema tests for two different specs, `/v0/health_records` and `/v0/profile/full_name`
=> 11585 add camel inflected schemas to full name and health records

spec/request/primary_phone_request_spec.rb
camelCase schemas used in tests for primary phone
this spec used already camelCase'd schemas
=> use the camelCase schemas for v0/profile/primary_phone

app/mailers/dependents_application_failure_mailer.rb, app/mailers/views/dependents_application_failure.erb, app/workers/bgs/submit_form686c_job.rb, config/locales/en.yml, spec/jobs/bgs/submit_form686c_job_spec.rb, spec/mailers/dependents_application_failure_mailer_spec.rb
The 686 form runs many calls to BGS in order to complete its objective of adding dependents to a veteran's benefits. We would like to inform the Veteran that their submission failed. We run retries in almost every call. We then raise an exception if all retries are exhausted.
The goal of this PR is to capture exceptions that have occured during the submission process (in the /lib/bgs directory) and fire a mailer informing the veteran that they need to either revisit the form or get in touch w/ someone at the VA to resolve their issue.
department-of-veterans-affairs/va.gov-team#12265
=> Add failure mailer for 686 form submission

Gemfile, Gemfile.lock, config/routes.rb, modules/covid_research/Gemfile, modules/covid_research/app/controllers/covid_research/application_controller.rb, modules/covid_research/app/controllers/covid_research/base_controller.rb, modules/covid_research/app/controllers/covid_research/volunteer/submissions_controller.rb, modules/covid_research/app/jobs/covid_research/application_job.rb, modules/covid_research/app/mailers/covid_research/application_mailer.rb, modules/covid_research/app/models/covid_research/application_record.rb, modules/covid_research/app/services/covid_research/volunteer/form_service.rb, modules/covid_research/bin/rails, modules/covid_research/config/routes.rb, modules/covid_research/covid_research.gemspec, modules/covid_research/lib/covid_research.rb, modules/covid_research/lib/covid_research/engine.rb, modules/covid_research/lib/covid_research/version.rb, modules/covid_research/lib/tasks/covid_research_tasks.rake, modules/covid_research/spec/covid_research_spec_helper.rb, modules/covid_research/spec/fixtures/files/no-name-submission.json, modules/covid_research/spec/fixtures/files/valid-submission.json, modules/covid_research/spec/requests/volunteer_request_spec.rb, modules/covid_research/spec/services/volunteer/form_service_spec.rb
This change introduces a new module for the handling of COVID Research related data and business logic.  This initial PR adds a controller for receiving form submissions and logic to validate those against a `vets_json_schema` definition.
There are two significant bodies of logic here: the controller, and a small service class.  The controller has a single action, `create`, which accepts a `POST` with the `JSON` payload for a form submission.  The service currently validates the payload against the schema in `vets_json_schema`.  The controller then returns an _unprocessable_ or _accepted_ response.
It is worth noting that authentication is not required or desired for this specific form.  It is desired that the volunteer process be open to anyone.
The first iteration is only intended to …
=> Covid research

spec/request/notifications/dismissed_statuses_request_spec.rb, spec/support/schemas_camelized/dismissed_status.json
camelCase version of the dismissed_status schema used in dismissed_statuses_request_spec
=> camelCase schema dismissed_status for v0/notifications/dismissed_statuses

spec/request/preneeds/attachment_types_request_spec.rb, spec/request/preneeds/branches_of_service_request_spec.rb, spec/request/preneeds/burial_forms_request_spec.rb, spec/request/preneeds/cemeteries_request_spec.rb, spec/request/preneeds/discharge_types_request_spec.rb, spec/request/preneeds/military_ranks_request_spec.rb, spec/request/preneeds/states_request_spec.rb, spec/support/schemas_camelized/preneeds/attachment_types.json, spec/support/schemas_camelized/preneeds/branches_of_service.json, spec/support/schemas_camelized/preneeds/cemeteries.json, spec/support/schemas_camelized/preneeds/discharge_types.json, spec/support/schemas_camelized/preneeds/military_ranks.json, spec/support/schemas_camelized/preneeds/receive_applications.json, spec/support/schemas_camelized/preneeds/states.json
Adding camelCase schemas for all the /v0/preneeds tests:
camelCase schema test for /v0/preneeds/attachment_types
camelCase schema test for /v0/preneeds/branches_of_service
camelCase schema test for /v0/preneeds/burial_forms
camelCase schema test for /v0/preneeds/cemeteries
camelCase schema test for /v0/preneeds/discharge_types
camelCase schema test for /v0/preneeds/military_ranks
camelCase schema test for /v0/preneeds/states
=> 11585 add camel inflected schemas to preneeds

modules/claims_api/app/controllers/claims_api/base_disability_compensation_controller.rb, modules/claims_api/spec/requests/v0/disability_compensation_request_spec.rb
This PR makes a more graceful handling of unknown issues during the claims api 526 upload endpoint
=> add more graceful handling of 526 error

modules/veteran_verification/spec/requests/disability_rating_request_spec.rb, modules/veteran_verification/spec/requests/keys_request_spec.rb, modules/veteran_verification/spec/requests/service_history_request_spec.rb, modules/veteran_verification/spec/requests/veteran_status_request_spec.rb, spec/support/schemas_camelized/disability_rating_response.json, spec/support/schemas_camelized/service_and_deployment_history_response.json, spec/support/schemas_camelized/veteran_verification/keys.json
uses camelCase versions of schema files for testing the veteran_verification endpoints
=> 11585 add camel inflected schemas to veteran verification

modules/claims_api/spec/requests/v0/claims_request_spec.rb, modules/claims_api/spec/requests/v1/claims_request_spec.rb, spec/support/schemas_camelized/claims_api/claim.json, spec/support/schemas_camelized/claims_api/claims.json
adding camelCase versions of schemas to support responses when camel-inflection headers used
=> 11585 add camel inflected schemas to claims api

config/features.yml
We're adding form 526 wizard to the introduction page.
This PR adds `show_526_wizard` feature flag to set the visibility of this change.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/10966
=> [Development] Add 526 intro wizard feature

config/features.yml
As a developer, I need a way to toggle when the SCO email is sent from the staging environment so that SCOs are not being sent test data unnecessarily.
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/12467
frontend pr: https://github.com/department-of-veterans-affairs/vets-website/pull/13883
local testing
=> Added stem sco email feature flag

app/controllers/v1/sessions_controller.rb, spec/controllers/v1/sessions_controller_spec.rb, spec/support/saml/response_builder.rb
Previously, the `login_stats(:failed...` call was only happening from the `user_login` function, this if an error was raised on line 57 when the SAML response was invalid, no login stats would be captured.
closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/12484
=> capture failed login stats when saml response is invalid

Gemfile, Gemfile.lock
The [upstream PR](https://github.com/pact-foundation/pact-ruby/pull/218) merged, so we no longer need the fork. 👯
=> use upstream pact-ruby instead of fork

Gemfile.lock, lib/bgs/service.rb
This PR adds error handlin' and retry to a couple calls in the 686 form flow. It also ensures that vets-api is using the latest from the [bgs-ext](https://github.com/department-of-veterans-affairs/bgs-ext) gem by updating the hash.
=> Adds more error handling and bumps bgs gem to get latest code

app/controllers/v0/apidocs_controller.rb, app/controllers/v0/hca_attachments_controller.rb, app/models/hca_attachment.rb, app/serializers/hca_attachment_serializer.rb, app/swagger/swagger/requests/hca_attachments.rb, app/uploaders/hca_attachment_uploader.rb, config/initializers/inflections.rb, lib/hca/enrollment_system.rb, spec/controllers/v0/hca_attachments_controller_spec.rb
`HCA` is used throughout the app as an acronym.  To support upcoming zeitwerk changes, the inflection to support it as an acronym was added.  Additionally, there were some variations of `HcaAttachment` that were updated to `HCAAttachment`.
department-of-veterans-affairs/va.gov-team#10976
=> 10976 use hca as acronym

config/initializers/sidekiq.rb, config/redis.yml, config/settings.yml
Our AWS architecture currently uses a single Elasticache Redis instance for both ephemeral
caching data and more mission-critical/persistent Sidekiq async jobs and scheduled tasks. The recommended configuration for Sidekiq includes a dedicated Redis instance (https://github.com/mperham/sidekiq/wiki/Using-Redis#multiple-redis-instances) which is exactly what this PR sets the stage to support.
department-of-veterans-affairs/va.gov-team#8149
By default, the settings file _uses the same Redis url for both caching and Sidekiq_ so on the surface, nothing has changed. Configuration of a 2nd instance requires changes to the `settings.yml` files created as part of the deployment process.
Developers can set up two local Redis instances by using a `settings.local.yml` file and using another local …
=> Separate Sidekiq Redis URL from caching/primary Redis URL

config/settings.yml
Cerner integration is beginning today and so we have shipped several products hooked up to Flipper flags. Search `cerner` on the list of feature flags to see which ones. We're adding a few users to the list of Flipper admins so that we can control the Flipper state ourselves.
- https://dsva.slack.com/archives/C52CL1PKQ/p1597934941010800
=> [Flipper] Add three new admins based on Cerner rollout

app/workers/education_form/education_facility.rb, config/features.yml
As a developer, I need to remove the feature flag for the RPO routing updates because it will not be disabled going forward.
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/10816
frontend pr: https://github.com/department-of-veterans-affairs/vets-website/pull/13889
Local Testing 
After applying to a school in Illinois, application gets routed to Buffalo
a. #10581
=> removed route_st_louis_rpo_to_buffalo_rpo feature flag

app/models/bgs_dependents/base.rb, app/models/bgs_dependents/relationship.rb, app/models/bgs_dependents/vnp_benefit_claim.rb, lib/bgs/dependents.rb
During integration testing, we discovered some fields that are required by BGS for certain calls.  These fields include:
`
child_prevly_married_ind, jrn_lctn_id
`
department-of-veterans-affairs/va.gov-team#12730
No additional settings or logging was added.  This PR just adds a few fields that were previously thought to be optional but we learned are required.
=> Adding/Updating BGS Required Fields

spec/factories/in_progress_forms/hca_forms.rb, spec/service_consumers/pact_helper.rb
This rspec config change was overlooked when implementing the pact helper. config.use_transactional_fixtures needs to be set to true in order to start each example with a clean database. Without wrapping in a transaction to rollback the data, the pact test gives misleading passing status based on pre existing data left hanging around.
Additionally, the class name for the HCA form factory needs to be defined. Pacts will pass once the frontend pushes pact updates to the broker.
=> use transactional fixtures for pact rspec config

Gemfile, Gemfile.lock, app/models/form526_job_status.rb, app/workers/evss/disability_compensation_form/job_status.rb, spec/jobs/evss/disability_compensation_form/submit_form526_all_claim_spec.rb, spec/models/form526_job_status_spec.rb
Upsert was added to vets-api in https://github.com/department-of-veterans-affairs/vets-api/pull/2418 before rails added upsert https://github.com/rails/rails/pull/35077 
Upsert was only used in Form526JobStatus
=> Remove unnecessary upsert gem

config/settings.yml, modules/covid_research/app/services/covid_research/volunteer/genisis_service.rb, modules/covid_research/app/workers/covid_research/volunteer/genisis_delivery_job.rb, modules/covid_research/spec/covid_research_spec_helper.rb, modules/covid_research/spec/services/covid_research/volunteer/genisis_service_spec.rb, modules/covid_research/spec/workers/covid_research/volunteer/genisis_delivery_job_spec.rb
This PR adds logic responsible for the delivery of a submitted Volunteer form to the `genISIS` backend.  
This PR does include new values for `settings.yml`, they are all name spaced under `genisis`.  Currently the settings are in place for dev and staging.  They will not be added for production until the implementation has been tested.  The next PR will introduce a flipper along with logic which actually makes this code live.  Currently the controller does nothing with a valid submission other than return a small static JSON body.
There are unit tests for all the new code.  The integration can't currently be tested outside the VA network and the code is not yet passing the data all the way through.
=> Covid research/form delivery

config/features.yml, modules/covid_research/app/controllers/covid_research/volunteer/submissions_controller.rb, modules/covid_research/app/services/covid_research/volunteer/form_service.rb, modules/covid_research/app/services/covid_research/volunteer/genisis_service.rb, modules/covid_research/app/workers/covid_research/volunteer/genisis_delivery_job.rb, modules/covid_research/lib/covid_research.rb, modules/covid_research/spec/covid_research_spec_helper.rb, modules/covid_research/spec/requests/volunteer_request_spec.rb, modules/covid_research/spec/services/covid_research/volunteer/form_service_spec.rb, modules/covid_research/spec/services/covid_research/volunteer/genisis_service_spec.rb
This PR cleans up the "full" flow for volunteer form delivery to `genISIS` as well as adding a feature flag to control how/where that flow actually executes.
This one is pretty straight forward.  The only "feature"/behavior it adds is the flag for the `genISIS` delivery.  It also has some corrections encountered while testing that flow.
I did not see anything in the documentation about defaulting a Flipper to off.  Is that something that happens for production by default?
Once these changes are merged my intent is to test actual form delivery to `genISIS` in development.  Once we confirm that that is working we will work with the `genISIS` team to setup a production instance of their application, add that configuration to `vets-api` (in the …
=> Covid research/genisis flag

app/workers/education_form/education_facility.rb
Moved states from `CENTRAL` to `EASTERN` because all submissions are now routed to only the Buffalo or Muskogee region.  Updated the comment to make clear that the empty list is required for historical reporting purposes.
This change doesn't modify any functionality but should make it clearer that there are only two possible regions for submissions.
department-of-veterans-affairs/va.gov-team#12818
=> Education spool file region cleanup

rakelib/load_test.rake, rakelib/mvi.rake, rakelib/vet360.rake
Checked rake tasks for missing `requires` commands, these are the ones I found
department-of-veterans-affairs/va.gov-team#10185
=> 10185 add missing requires to rake tasks

modules/claims_api/app/controllers/claims_api/concerns/document_validations.rb, modules/claims_api/app/controllers/claims_api/v1/forms/disability_compensation_controller.rb, modules/claims_api/app/swagger/claims_api/common/error_model_swagger.rb, modules/vba_documents/app/swagger/vba_documents/v1/error_model_swagger.rb
noticed this typo.
JSON:API errors can have property `detail` not `details`
https://jsonapi.org/format/#errors
=> Lighthouse APIs - use property detail instead of details

modules/covid_research/app/serializers/covid_research/genisis_serializer.rb, modules/covid_research/spec/fixtures/files/genisis-mapping.json, modules/covid_research/spec/serializers/covid_research/genisis_serializer_spec.rb
I overlooked the string requirement for QuestionValue.  This change maps true/false responses to ‘Yes’/‘No’ accordingly.
This is a very small and self contained change.  I don't think there is really anything significant about it.
=> This translates boolean values to strings

config/settings.yml
In preparation for Profile 2.0 we need to give Flipper access to a few members of our team so that we are able to add users on the fly during a UAT session.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/12878
=> Add additional Flipper admins for Profile 2.0 UAT

lib/mvi/service.rb, spec/lib/mvi/service_spec.rb
This is a first step in better understanding why some of our MVI calls fail with add_person.  I think we would be better sending the error to sentry when it is raised, rather than a message. 
department-of-veterans-affairs/va.gov-team#10524
=> Better MVI error reporting

app/models/form_profiles/va10203.rb, app/models/saved_claim/education_benefits/va10203.rb, spec/jobs/education_form/create_daily_fiscal_year_to_date_report_spec.rb, spec/jobs/education_form/create_daily_year_to_date_report_spec.rb, spec/models/saved_claim/education_benefits/va10203_spec.rb
As a developer, I need to modify feature flags to verify user has authorization to access the feature flag.
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/12944
=> Added user to feature flags for added email access

spec/service_consumers/pact_helper.rb
Basic auth is now implemented for the pact broker. In order to successfully publish verification results in CI, the username and password need to be passed in. PACT_BROKER_BASIC_AUTH_USERNAME and PACT_BROKER_BASIC_AUTH_PASSWORD are implemented as ENV variables in the CircleCI vets-api project settings.
department-of-veterans-affairs/va.gov-team#10224
=> Configure Pact Broker Auth Credentials for Pact

spec/models/saved_claim/disability_compensation/form526_all_claim_bdd_spec.rb
I wrote a time dependent test.
spec/models/saved_claim/disability_compensation/form526_all_claim_bdd_spec.rb:23 will fail if it's not more than 90 days before Dec 1, 2020
http://jenkins.vfs.va.gov/blue/organizations/jenkins/testing%2Fvets-api/detail/PR-4827/2/pipeline
=> Fix time-dependent test

lib/shrine/plugins/validate_virus_free.rb
Two sentry errors due to this issue:
http://sentry.vfs.va.gov/vets-gov/platform-api-production/issues/197997
http://sentry.vfs.va.gov/vets-gov/platform-api-production/issues/197996
=> validate_virus_free should require common/virus_scan

app/controllers/v0/sessions_controller.rb, app/controllers/v1/sessions_controller.rb, config/initializers/statsd.rb, spec/controllers/v0/sessions_controller_spec.rb, spec/controllers/v1/sessions_controller_spec.rb
If we increment a metric using tags that are different from the values used during initialization, the [statsd exporter raises an exception and triggers a restart](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logEventViewer:group=dsva-vagov-prod/var/log/prometheus/statsd_exporter.log;stream=deployment-vagov-prod-vets-api-server-20200903-190131-10.247.33.111;filter=restart;start=2020-09-02T19:54:38Z).  This will through off any prometheus queries that are attempting to calculate the rate of change over time, if triggered often.
[Slack thread that identified the issue](https://dsva.slack.com/archives/C30LCU8S3/p1599164567086300)
This PR addresses 3 problematic statsd metrics issues in the session controllers:
- `STATSD_SSO_CALLBACK_FAILED_KEY`: …
=> statsd metrics with tags not matching those initialized restart the StatsD agent

lib/mvi/responses/add_parser.rb, spec/lib/mvi/responses/add_parser_spec.rb
We are seeing a high rate of error for MVI add person calls and I hope that logging the response will provide more info.
department-of-veterans-affairs/va.gov-team#12376
=> log more info when MVI add_person fails

rakelib/form526.rake
EVSS has an issue where files were being corrupted and asked us to re upload files associated with some form526 claim submissions 
department-of-veterans-affairs/va.gov-team#12915
=> add a rake task to retry form526 evss uploads

app/workers/evss/document_upload.rb, spec/jobs/evss/document_upload_spec.rb
Delete unused code.  
I verified that this job is not run in Graana
It was transition code added in https://github.com/department-of-veterans-affairs/vets-api/commit/71792cb767f0ab939b26f80515ba36d9e3dd18cf
=> EVSSClaim detele unused code

README.md
based on this PR https://github.com/department-of-veterans-affairs/vets-api/pull/4868 because it can't be merged from a fork because pipeline didn't run
=> fix typo of ubuntu in readme

db/migrate/20200911143406_add_index_to_accounts.rb, db/schema.rb
The `accounts` table can be queried on the `icn` field as part of the SAML login callback.
This field is not indexed, resulting in slow query times.
This PR adds an index to `accounts` table on `icn` field
department-of-veterans-affairs/va.gov-team#13442
=> Add index to `accounts` table on `icn` field

Gemfile.lock
This is a gem version bump to support getting mock data from the BGS-Ext gem so that our FE team can continue with their feature. Here is the associated approved gem PR: https://github.com/department-of-veterans-affairs/bgs-ext/pull/34
department-of-veterans-affairs/va.gov-team#12000
=> Bump gem version

modules/claims_api/app/controllers/claims_api/v0/forms/power_of_attorney_controller.rb, modules/claims_api/app/controllers/claims_api/v1/forms/power_of_attorney_controller.rb, modules/claims_api/app/swagger/claims_api/v0/form_2122_controller_swagger.rb, modules/claims_api/app/swagger/claims_api/v1/form_2122_controller_swagger.rb, modules/claims_api/config/routes.rb, modules/claims_api/spec/requests/v0/power_of_attorney_request_spec.rb, modules/claims_api/spec/requests/v1/power_of_attorney_request_spec.rb
This adds the validate endpoint for v0 and v1 for form 21-22 (PowerOfAttorneyController). 
[Create an PoA /validate end point](https://vajira.max.gov/browse/API-1793)
Swagger docs were updated for v0 and v1 validate endpoints.
Tests were added for v0 and v1 request specs for the validate endpoint.
=> [API-1793] Create an PoA /validate end point

modules/vba_documents/app/mailers/vba_documents/unsuccessful_report_mailer.rb, modules/vba_documents/spec/mailers/unsuccessful_report_mailer_spec.rb
This PR adds new team member emails to the UnsuccessfulReportMailer 
[Add new team member emails to UnsuccessfulReportMailer](https://vajira.max.gov/browse/API-2253)
=> [API-2253] Add new team member emails to UnsuccessfulReportMailer

config/initializers/flipper.rb
Remove code that disables `ssoe` feature toggles in `development` environments.
SSOe is now functional in `development` environments (local, review instances)
department-of-veterans-affairs/va.gov-team#13449
=> Don't auto-disable `ssoe` feature toggles in `development`

config/sidekiq_scheduler.yml, modules/vba_documents/app/workers/vba_documents/run_unsuccessful_submissions.rb, modules/vba_documents/spec/jobs/run_unsuccessful_submissions_spec.rb
Setup a daily sidekiq job to find `UploadSubmissions` that are stuck in the `uploaded` status when SNS fails for some reason. The job runs the `UploadProcessor` worker.
[Create daily sidekiq job to find, catch and rerun "uploaded" statuses for when SNS fails](https://vajira.max.gov/browse/API-1188)
=> [API-1188] Create daily sidekiq job to find, catch and rerun "uploaded" statuses for when SNS fails

config/features.yml
Added the `stem_document_type` feature flag.  This will be used to determine the form ID used for 10203 spool files.
department-of-veterans-affairs/va.gov-team#12799
- Related PR using feature flag: https://github.com/department-of-veterans-affairs/vets-api/pull/4884
=> Add stem_document_type feature flag

app/controllers/v1/sessions_controller.rb, lib/saml/templates/sso_post_form.html.erb, spec/controllers/v1/sessions_controller_spec.rb
The SSOe SAML Tracker was added to give more clarity on how successful the SAML Post binding form is in submitting, however the numbers reported back are extremely low, and in some cases even lower than our SAML Response rates.  I believe the issue is that the XHR request is in some cases being canceled because the form submission is happening too quickly.  This PR addresses that, by only submitting the form once we receive acknowledgment from the XHR request that it has been received.
This will add a small delay to the user's experience, but should give us accurate metrics whether the SAML Post form JS block is loading properly.
This PR also fixes a param naming issue which is causing all the application logs to show up with SAML ids of `nil`.
closes …
=> SSOe SAML Tracker event changes

config/features.yml
As a developer, I need to create a feature flag for the school ratings UI functionality so that it is not displayed in production as development is completed.
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/13359
front end pr: https://github.com/department-of-veterans-affairs/vets-website/pull/14233
local testing
=> Added school ratings feature flag to the backend

app/controllers/v0/debt_letters_controller.rb, lib/debts/letter_downloader.rb, spec/lib/debts/letter_downloader_spec.rb, spec/support/stub_debt_letters.rb
This changes the filename of the debt letters that can be downloaded by the veteran from `letter.pdf` to a more user friendly filename, which is the concatenation of the document's type description along with the date.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/13357
Tested and verified locally.
=> [13357] Debt letter filename fix

lib/common/exceptions/routing_error.rb
found a spot with a missing `require`, will support https://github.com/department-of-veterans-affairs/vets-api/pull/4897
=> Add missing requires to routing_error

spec/service_consumers/provider_states_for/search.rb
Frontend Tools pushed a change to the pact search contract and renamed the interaction string. The string defined in the provider state MUST be an exact match to what's defined as the interaction in the contract. Otherwise, [verification fails](https://app.circleci.com/pipelines/github/department-of-veterans-affairs/vets-api/5769/workflows/63cff8fe-0093-45c0-b40c-6294a24c406f/jobs/8866). Pact verification will fail until this is merged
[Search Contract](https://vagov-pact-broker.herokuapp.com/pacts/provider/VA.gov%20API/consumer/Search/latest)
=> Update string to match contract in broker

modules/claims_api/app/workers/claims_api/claim_establisher.rb, modules/claims_api/spec/workers/claim_establisher_spec.rb
GDIT asked us to look up some ID's in Staging for test Claims V0 Submissions and found that the upstream 500 errors weren't being relayed downstream.
https://vajira.max.gov/browse/API-2387
=> EVSS 500 error catch and fix

app/mailers/views/school_certifying_officials.html.erb
Added ga tracking to links in SCO email
department-of-veterans-affairs/va.gov-team#12359
- SCO emails are behind the `stem_sco_email` feature flag
=> Update SCO email links

config/features.yml
Add facility_locator_predictive_location_search feature flag.
This will be used to toggle predictive location search in the Facility Locator.
Also, delete facility_locator_fe_use_v1 (unused)
Issue:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/12722
https://github.com/department-of-veterans-affairs/vets-website/pull/14187
=> Add facility_locator_predictive_location_search feature flag

config/routes.rb, lib/saml/templates/sso_post_form.html.erb
Renaming the `/v1/sessions/tracker` URL to `/v1/sessions/trace`.  Some browser ad blocker extensions (ie AdblockPlus) prevent XHR requests to urls with the word "track" in it.
I manually tested this locally with the following AdblockPlus settings enabled.  With the former URL, the form submission was blocked, however when using the `/v1/sessions/trace` URL, the POST SAML binding form was successfully submitted.
refs https://github.com/department-of-veterans-affairs/vets-api/pull/4806#issuecomment-694289957
=> renaming the ssoe tracker url to trace

lib/mdot/client.rb, spec/lib/mdot/client_spec.rb, spec/support/vcr_cassettes/mdot/get_supplies_200.yml
Birthdates that do not have hyphens between the month & year and day & month will not pass validation when they are submitted to DLC's API. In order to ensure that this format is always followed, I've added a method that will parse whatever date is gathered from the `@current_user`'s `birth_date` instance variable and format it appropriately so that it will be accepted by DLC's API.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/13658
tested and verified locally
=> [13658] Fix MDT birthdate formatting issue

modules/claims_api/app/swagger/claims_api/forms/form_526_response_swagger.rb, modules/claims_api/config/schemas/526.json, modules/claims_api/spec/requests/v0/disability_compensation_request_spec.rb, modules/claims_api/spec/requests/v1/disability_compensation_request_spec.rb
Add `specialIssues` to form 526 schema. 
[Add specialIssues to the Claims API 526 Schema](https://vajira.max.gov/browse/API-1480)
=> Add specialIssues to 526 form schema

config/initializers/flipper.rb
when a dev deletes a feature toggle in the code it should go away in the UI as well.  
For example in staging there's both ` show_526_wizard` and `show526_wizard`, due to a renaming.
for @Mottie
=> remove obsolete feature toggles

config/features.yml
Since the update for the feature flags, our feature was not enabled for development. We needed to have the `show_healthcare_experience_questionnaire` flag to be enabled in development.
=> added questionnaire to enabled by default

app/workers/form526_confirmation_email_job.rb
This is a small addition to the Form526ConfirmationEmailJob, which is to increment statsd on success. We've previously only incremented on failure.
department-of-veterans-affairs/notification-api#137
Increment statsd on success for Form526ConfirmationEmailJob
=> increment statsd on success of form526 confirmation email job

config/initializers/saml.rb, config/settings.yml, lib/saml/responses/login.rb
Adds support for a concurrent 2nd saml key for ID.me auth. 
Our existing certificate is expiring soon, and our private key has not changed for a while, and our existing certificate still has "vetsgov" references in it... so we generated a brand new keypair. We don't want to incur any login downtime, so this PR makes `vets-api` support both keys for login. Once ID.me makes the new certificate "active", we can remove this logic and just use the new key + cert.
`ruby-saml` has support for multiple certificates ([and it's what we used last time we rolled over](https://github.com/department-of-veterans-affairs/vets-api/pull/1431)), but that support requires both old and new cert to cryptographically chain back to the same private key. In our case, we have a _new_ private key. …
=> multi-key saml support when decrypting authn responses

app/controllers/concerns/authentication_and_sso_concerns.rb, app/controllers/v0/users_controller.rb, app/models/session.rb, app/models/user.rb, app/models/user_identity.rb, app/models/user_session_form.rb, app/serializers/user_serializer.rb, app/services/users/profile.rb, app/services/users/scaffold.rb, app/swagger/swagger/schemas/user_internal_services.rb, lib/saml/user.rb, lib/saml/user_attributes/base.rb, lib/saml/user_attributes/ssoe.rb, spec/factories/users.rb, spec/lib/saml/dslogon_user_spec.rb, spec/lib/saml/idme_user_spec.rb, spec/lib/saml/mhv_user_spec.rb, spec/lib/saml/ssoe_user_spec.rb, spec/models/session_spec.rb, spec/models/user_session_form_spec.rb, spec/serializers/user_serializer_spec.rb, spec/services/users/profile_spec.rb, spec/support/schemas/user_loa1.json, spec/support/schemas/user_loa3.json, spec/support/schemas_camelized/user_loa1.json, spec/support/schemas_camelized/user_loa3.json, spec/support/vcr_cassettes/complex_interaction/internal_interactions.yml
Copying the SSOe transaction id value from UserIdentity to the Session object and also serializing that info into the UserProfile.
refs https://github.com/department-of-veterans-affairs/va.gov-team/issues/13726
I ran the following manual test locally to verify that the change will work
1. In Firefox, I opened a tab with https://localhost:3000/v1/sessions/idme/new and completed the authentication process with testing user 262
1. In Firefox, I opened a tab with https://localhost:3000/v0/user and verified that both the transactionid in profile.sign_in and session matched
1. In Chrome, I opened a tab with https://localhost:3000/v1/sessions/idme/new and completed the authentication process with testing user 262
1. In Chrome, I opened a tab with https://localhost:3000/v0/user and verified that …
=> placing ssoe transaction in session object

config/features.yml
As a developer, I need a way to toggle when the new text message option question is displayed within the 10203 form, so that it can be delivered when EDU is ready to accept the data.
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/13826
front end pr: https://github.com/department-of-veterans-affairs/vets-website/pull/14380
local testing
=> added stem text FF to backend

app/mailers/transactional_email_mailer.rb, app/workers/transactional_email_analytics_job.rb, config/settings.yml, spec/jobs/transactional_email_analytics_job_spec.rb
Recently another `google_analytics` key was introduced to `settings.yml`.  This PR is to put them in the same namespace together
https://github.com/department-of-veterans-affairs/va.gov-team/issues/14053
https://github.com/department-of-veterans-affairs/va.gov-team/issues/14017
corresponding PR for devops https://github.com/department-of-veterans-affairs/devops/pull/7657
=> 14053 consolidate google analytics keys

lib/debts/schemas/debts.json, spec/support/schemas/debts.json, spec/support/vcr_cassettes/debts/get_letters.yml
Adds two new string fields (diary code and diary code description) to the debts response.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/14032
tested locally
=> [14032] Add Diary Code and Diary Code Description to Debts Response

Gemfile.lock
```
[2020-09-29T17:10:27.152Z] running bundle-audit to check for insecure dependencies...
[2020-09-29T17:10:27.715Z] Updating ruby-advisory-db ...
[2020-09-29T17:10:27.715Z] Cloning into '/srv/vets-api/.local/share/ruby-advisory-db'...
[2020-09-29T17:10:28.277Z] Updated ruby-advisory-db
[2020-09-29T17:10:28.277Z] ruby-advisory-db: 469 advisories
[2020-09-29T17:10:28.839Z] Name: webrick
[2020-09-29T17:10:28.839Z] Version: 1.6.0
[2020-09-29T17:10:28.839Z] Advisory: CVE-2020-25613
[2020-09-29T17:10:28.839Z] Criticality: Unknown
[2020-09-29T17:10:28.839Z] URL: https://www.ruby-lang.org/en/news/2020/09/29/http-request-smuggling-cve-2020-25613/
[2020-09-29T17:10:28.839Z] Title: Potential HTTP Request Smuggling Vulnerability in WEBrick
[2020-09-29T17:10:28.839Z] Solution: upgrade to >= 1.6.1
``` …
=> upgrade Webrick to 1.6.1 to resolve CVE

modules/va_forms/app/serializers/va_forms/form_detail_serializer.rb, modules/va_forms/app/serializers/va_forms/form_list_serializer.rb, modules/va_forms/app/swagger/va_forms/forms/form_swagger.rb
Documentation error is showing the valid_pdf as being an integer instead of it's stated boolean in the example. They also needed us to remove the forms_details_url for now until they are ready for production.
https://vajira.max.gov/browse/API-2585
https://vajira.max.gov/browse/API-2654
=> Fixing bad documentation for valid_pdf

lib/mvi/responses/add_parser.rb, lib/mvi/responses/parser_base.rb, lib/mvi/responses/profile_parser.rb
The MVI find profile response parser and the mvi add profile response parser shared a significant amount of code overlap.  
It looks like code was copy-pasted from `profile_parser` to `add-parser` [here](https://github.com/department-of-veterans-affairs/vets-api/pull/3632/files#diff-622e8b48f34f2d83fb6089237648d2ffR1
).
This PR cleans that up as a precursor to department-of-veterans-affairs/va.gov-team#11353 
Surely there's more to be done in reducing redundancy and increasing consistency, but this is a first step.
department-of-veterans-affairs/va.gov-team#11353
=> add_parser has too much code copy-pasted

modules/appeals_api/app/swagger/v0/appeals.yml
This PR updates the documentation to display an array instead of an object for the data field in the appeals status API. 
[Update the documentation for original appeals status endpoint](https://vajira.max.gov/browse/API-687)
=> [API 687] Update the documentation for original appeals status endpoint

lib/evss/letters/letter.rb, spec/lib/evss/letters/download_service_spec.rb
Does:
* Adds missing letter type `benefit_summary_dependent`
* Alphabetizes list
Notes:
[error example in sentry](http://sentry.vfs.va.gov/vets-gov/platform-api-production/issues/155640/?query=is%3Aunresolved%20invalid%20letter%20type) (see ADDITIONAL DATA / message)
More complete list found at https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/veteran-military-records/documents-and-letters/letters-api-docs-fe-notes.md
Related PR https://github.com/department-of-veterans-affairs/vets-website/pull/14446
=> Update Letter Types

config/features.yml
SSOe wasn’t working locally.  Because of that we had a line in an initializer to ensure that SSOe login was disabled for localhost.
SSOe is working locally.  I removed the line from the initializer that ensured SSOe login was disabled.  However, previously disabled SSOe flags remain disabled until manually enabled.
Since then, the new `enable_in_development` flag was added to `features.yml`.  
SSOe is the path forward and we will eventually remove the “old” login flow altogether.
Therefore, I'm setting `enable_in_development` to `true` for the SSOe toggles so that engineers will use SSOe locally by default. 
department-of-veterans-affairs/va.gov-team#14179
=> enable SSOe in development by default

modules/vba_documents/app/workers/vba_documents/upload_processor.rb, modules/vba_documents/spec/jobs/upload_processor_spec.rb
Checking status refreshing if Faraday::TimeoutError persists...
https://vajira.max.gov/browse/API-2488
=> Adding a timeout rescue with a status refresh check

modules/appeals_api/app/swagger/appeals_api/v1/responses_contestable_issues.json
Noticed that the error response examples for `GET /higher_level_reviews/contestable_issues/{benefit_type}` weren't properly nested (`errors` should be an array of objects, not just an object).
AC:
=> Fix Typo in HLR Documentation

lib/bgs/children.rb, lib/bgs/form686c.rb, lib/bgs/service.rb
During testing with BGS, we found we need to send the `vnPProcTypeCd` in update calls in order for that attribute to persist in their system and create a valid claim.
We also would like to capture the procId associated with the claim submission to help them debug their systems.
* No additional changes
* This feature is flagged, it is not available to the public
* We added a message log to get the procId which is a unique "procedure ID" for the submission
* No …
=> Add DEPCHG to update calls

app/services/form1010cg/service.rb, spec/services/form1010cg/service_spec.rb
Fixes: https://github.com/department-of-veterans-affairs/va.gov-team/issues/14273
**Description**:
When a user submits a 10-10CG, we generate a PDF of their submission and send it to CARMA as an attachment to the Case. There were, as of this time, two production submissions where the data and the attachment made it successfully to CARMA, but the user received a 500 error because we called `File.delete` on a file or directory that apparently didn't exist after it was sent to CARMA.
We are still not sure why the file cannot be found when it was generated just a few lines of code above where we try to delete it, but this fix will prevent any additional users from being told their submission failed when it actually didn't.
**Sentry**: …
=> Fix: 10-10CG PDF not found when attempting to delete it after submission

config/settings.yml, lib/caseflow/configuration.rb, spec/lib/caseflow/configuration_spec.rb
Make the timeout for the caseflow/appeals endpoint configurable and possibly increase it more in staging
department-of-veterans-affairs/va.gov-team#13547
=> Allow configurable Caseflow timeout

spec/lib/evss/disability_compensation_form/data_translation_all_claim_spec.rb
freeze time on BDD spec. BDD has a 3-month eligibility window.
=> fix time-dependent spec

modules/vaos/app/services/vaos/jwt_wrapper.rb, modules/vaos/app/services/vaos/middleware/vaos_logging.rb, modules/vaos/spec/services/middleware/vaos_logging_spec.rb
This issue is looking to enhance our ability to coordinate with VAMF when tracking down issues a user may encounter when interacting with VAOS. Prior to this change the code was logging the JTI present on the response object.  This was problematic if a response wasn't present due to a down-stream error.  In this case, we would lose the ability to identify a user to VAMF because we wouldn't have a JTI.  The solution was to record the JTI present in the request body/header (as opposed to the response) so in the case of a down-stream error, we would be able to access the JTI associated with the request which could then be presented to VAMF to facilitate identifying the error.
The `token` variable was also memoized in the jwt_wrapper as an optimization.
Also, we noticed that we’re using two …
=> updated logging to use the request instead of the response

lib/saml/templates/sso_post_form.html.erb
some ad blockers are preventing the bundle from being loaded via the
sentry dsn, in that case we need to check that the Sentry variable is
defined or else the call to `Sentry.init` will result in an error and
prevent the user from submitting.
I manually tested this locally running AdblockPlus in Chrome.  With all the settings enabled, `/v1/sessions/idme/new` raised an error and the submission halted, however after introducing this change the submission went forward.
=> only initialize Setnry if its defined

app/models/form526_submission.rb, spec/models/form526_submission_spec.rb
[notification-api#189]
hour should not have a zero pad if it is one digit, e.g. ' 3' rather than '03'
department-of-veterans-affairs/notification-api#189
=> no zero padding for the hour

config/form_profile_mappings/28-8832.yml, spec/models/form_profile_spec.rb
When we originally set up prefill for this form we did not map the prefill data to the correct fields in the form schema. This PR is to adjust both the way the prefill data is mapped and the spec that accompanies the prefill
https://github.com/department-of-veterans-affairs/va.gov-team/issues/12669
=> Adjusted form profile mappings and spec

lib/saml/user_attributes/ssoe.rb, spec/lib/saml/ssoe_user_spec.rb
The SSOe transaction data is now being stored in the Session object, as it is specific
to the user's session, not their profile, and can be removed from the
`sign_in` object as it should no longer be used
closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/13726
=> removing ssoe transaction data from the sign_in object

modules/health_quest/app/controllers/health_quest/v0/base_controller.rb, modules/health_quest/app/controllers/health_quest/v0/pgd_questionnaires_controller.rb, modules/health_quest/config/routes.rb, modules/health_quest/spec/request/appointments_request_spec.rb, modules/health_quest/spec/request/pgd_questionnaires_request_spec.rb
- Adding a basic endpoint that will be responsible for fetching questionnaires data.
- This endpoint currently only returns a 200 status.
- The route is: `GET /v0/pgd_questionnaires/:id`
- This is a placeholder route. It will return questionnaire data in the nearby future.
Zenhub link: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/13599
- Basic rspec tests have been written to test the endpoint.
- Swagger docs will be added separately for this endpoint.
=> 13599 add basic questionnaire endpoint

modules/health_quest/app/controllers/health_quest/v0/pgd_questionnaire_responses_controller.rb, modules/health_quest/config/routes.rb, modules/health_quest/spec/request/pgd_questionnaire_responses_request_spec.rb
- Adding a basic endpoint that will be responsible for fetching questionnaire responses data.
- This endpoint currently only returns a 200 status.
- The route is: `GET /v0/pgd_questionnaire_responses/:id`
- This is a placeholder route. It will return questionnaire responses data in the nearby future.
Zenhub link: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/13599
- Basic rspec tests have been written to test the endpoint.
- Swagger docs will be added separately for this endpoint.
=> add basic questionnaire responses endpoint

modules/appeals_api/app/swagger/appeals_api/v1/responses_contestable_issues.json
This PR updates responses_contestable_issues.json to include examples for the 200 response. 
[Add a Contestable Issues example - Decision Review API documentation](https://vajira.max.gov/browse/API-2913)
=> [API 2913] Add a Contestable Issues example (Decision Review API documentation)

rakelib/form526.rake
1. sort results of rake form526:errors by number of errors descending
2. take in extra arg that can force json output
=> Updates to `rake form526:errors`

app/controllers/v0/apidocs_controller.rb, app/controllers/v0/documents_controller.rb, app/services/evss_claim_service.rb, app/swagger/swagger/requests/claim_status.rb, spec/request/documents_spec.rb, spec/request/swagger_spec.rb
Before we start allowing password-protected pdf's (#5072) I want to make sure our file upload code is well-tested and documented.  
This adds swagger docs and rescues an exception that would've raised 500's
in #5070 I'm taking a look at the text of the error messages.
department-of-veterans-affairs/va.gov-team#14002
=> Add documentation and specs for Claim Status Tool file uploads

config/initializers/saml.rb, config/settings.yml, lib/saml/responses/login.rb
This reverts commit 34fbd2a75e499b8babe43ce55201b8a6ad66499b.
We introduced temporary code to support multiple ID.me SAML keys to decrypt auth responses ([link to PR](https://github.com/department-of-veterans-affairs/vets-api/pull/4965)). ID.me has now "activated" the new certificate and our key rollover phase is complete. We no longer need this code.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/14221
The settings.yml files have been updated to exclusively use the new key & new cert and do not need this code anymore:
- dev https://github.com/department-of-veterans-affairs/devops/pull/7689
- staging https://github.com/department-of-veterans-affairs/devops/pull/7696
- prod https://github.com/department-of-veterans-affairs/devops/pull/7691
=> Revert "multi-key saml support when decrypting authn responses (#4965)"

Gemfile.lock
update `breakers` gem to version 0.4.0.
This version reports "duration" metrics in milliseconds instead of seconds
The StatsD Exporter now expects time measurements in milliseconds, hence this change.
=> update `breakers` gem to version 0.4.0.

Gemfile.lock, app/services/bgs/people_service.rb
While implementing mock data for the View Payments functionality, it was discovered that one of the calls being used was not currently set up to use mock data services.  This PR updates that call to pass the identifier as a param to the BGS gem so that other developers can test the View Payments functionality without being connected to BGS.
This PR also bumps the bgs_ext gem version to match the latest in master for that repo.
department-of-veterans-affairs/va.gov-team#14595
This is a very minor PR so no additional logging or settings have been changed.
=> Add Identifier for BGS Mock Services

config/features.yml
In anticipation of asking the user for a password after attempting to upload an encrypted PDF, this feature flag is being added to allow thorough testing.
- All forms: https://github.com/department-of-veterans-affairs/va.gov-team/issues/14011
- Claim status tool: https://github.com/department-of-veterans-affairs/va.gov-team/issues/14723
- API: https://github.com/department-of-veterans-affairs/vets-api/pull/5072
Adding a `request_locked_pdf_password` feature flag
=> [Development] Add PDF password feature flag

modules/vaos/app/services/vaos/middleware/response/errors.rb, modules/vaos/spec/request/appointments_request_spec.rb, spec/support/vcr_cassettes/vaos/appointments/put_cancel_appointment_500.yml
VAMF recently started sending us a 500 error instead of a 409 error for something we had special handling around. We have to patch this temporarily while they work out a solution. More on that in the original issue below.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/14771
VCR cassette added. This patch is temporarily. It will still be noisy in Sentry. We're going to have to address that differently.
=> 14771 appointment cancellation bug temporary patch

lib/caseflow/service.rb, modules/appeals_api/app/controllers/appeals_api/docs/v1/docs_controller.rb, modules/appeals_api/app/controllers/appeals_api/v1/decision_reviews/base_contestable_issues_controller.rb, modules/appeals_api/app/controllers/appeals_api/v1/decision_reviews/higher_level_reviews/contestable_issues_controller.rb, modules/appeals_api/app/controllers/appeals_api/v1/decision_reviews/notice_of_disagreements/contestable_issues_controller.rb, modules/appeals_api/app/swagger/appeals_api/v1/higher_level_reviews_controller_swagger.rb, modules/appeals_api/app/swagger/appeals_api/v1/notice_of_disagreements_controller_swagger.rb, modules/appeals_api/app/swagger/appeals_api/v1/responses_contestable_issues.json, modules/appeals_api/config/routes.rb, modules/appeals_api/spec/requests/v1/contestable_issues_controller_spec.rb, modules/appeals_api/spec/requests/v1/higher_level_reviews/contestable_issues_controller_spec.rb, modules/appeals_api/spec/requests/v1/notifce_of_disagreements/contestable_issues_controller_spec.rb, modules/appeals_api/spec/support/shared_examples_contestable_issues.rb, spec/support/vcr_cassettes/caseflow/notice_of_disagreements/contestable_issues.yml
This PR:
- Refactors HigherLevelReviews/ContestableIssuesController to use a common base class `BaseContestableIssuesController` 
- Implements `NoticeOfDisagreements/ContestableIssuesController` which inherits from base class
- Updates specs using shared examples
- Updates documentation for `NoticeOfDisagreements/ContestableIssuesController`
[NOD contestable issues endpoint (vets-api)](https://vajira.max.gov/browse/API-2880)
=> [API 2880] NOD contestable issues endpoint (vets-api)

config/initializers/inflections.rb
MVI's use as an acronym that's not inflected is blocking enabling zeitwerk.  The plan is to move to using 'MPI' to reflect the real name, so the inflection will be added for that and then the MVI classes will be changed and be supported by the new inflection of MPI.  There are already starting to be places that refer to MPI, so this will help keep people on the right path.
=> add inflection for MPI

app/controllers/v0/ask/asks_controller.rb, app/models/form_profile.rb, app/models/form_profiles/va0873.rb, config/features.yml, config/form_profile_mappings/0873.yml, spec/models/form_profile_spec.rb, spec/request/user_request_spec.rb
Adding contact information prefill for the Contact Us (0873) form
department-of-veterans-affairs/orchid#120
- Sets `enable_in_development: true` for existing `get_help_ask_form` feature flag
- Added unit test for 0873 form into `form_profile_spec`
- Manual testing in review instance
=> Prefill for 0873 Contact Us form

app/controllers/v0/mvi_users_controller.rb, app/controllers/v0/profile/personal_informations_controller.rb, app/policies/mpi_policy.rb, app/services/users/services.rb, spec/policies/mpi_policy_spec.rb
app/policies/mvi_policy.rb defines MviPolicy and should become app/policies/mpi_policy.rb and use the inflection to be MPIPolicy. MPIPolicy is derived from the notion of policy classes from the pundit gem. The authorize before_action in the  mvi_users_controller automatically infers that mpi will have a matching MPIPolicy class. 
department-of-veterans-affairs/va.gov-team#14705
=> 14770 rename MviPolicy

modules/claims_api/app/controllers/claims_api/base_disability_compensation_controller.rb, modules/claims_api/app/controllers/claims_api/v0/forms/disability_compensation_controller.rb, modules/claims_api/app/controllers/claims_api/v1/forms/disability_compensation_controller.rb, modules/claims_api/spec/requests/document_validations_request_spec.rb, modules/claims_api/spec/requests/v0/disability_compensation_request_spec.rb
The `PdfInfo ` module is broken and was throwing errors for valid PDFs being submitted to the 526 attachment endpoint. This temporarily removes those checks
https://vajira.max.gov/browse/API-1979
- Manually tested by submitting different PDF attachments locally and uploading to s3
=> Remove broken pdf validation for 526 attachments

config/betamocks/services_config.yml
This PR adds a betamocks path for hitting the NOD endpoint on caseflow so we can record and use the new responses.
=> Add a betamocks route for Appeals NOD

config/features.yml
**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/14203
This PR creates Flipper feature toggles for the Cerner facilities.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/14203
No.
**Yes, two feature flags have been added.**
I added the following feature toggles:
```
cerner_override_668
cerner_override_757
```
These are used to force `is_cerner` to true for these 2 facilities.
No.
No.
* Are there Swagger docs that were updated?
No.
* Is there any PII concerns …
=> Add cerner override feature toggles

config/features.yml
Removed the `edu_benefits_stem_scholarship` flag.
department-of-veterans-affairs/va.gov-team#13850
- vets-api PR to remove usage: https://github.com/department-of-veterans-affairs/vets-website/pull/14619
=> Remove edu_benefits_stem_scholarship feature flag

app/workers/education_form/forms/va10203.rb, config/features.yml, spec/support/spool_helpers.rb
Remove the stem_document_type feature flag. 
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/13439
All 10203 submissions should be displayed in the spool file are V10203 document type.
=> remove stem_document_type feature flag

config/betamocks/services_config.yml, config/settings.yml
- We are mocking out the response from the staging MAP Appointment Service when the vets-api Health Quest module queries the service for an appointment by a given ID.
- The appropriate modifications have been made to the `config/settings.yml`: Setting `mock` to true for the `hqva_mobile` app.
- Added a new config in `config/betamocks/services_config.yml` for the MAP Appointment Service
- Mock data will be added to the `vets-api-mockdata` repository.
- Route(example: `'/health_quest/v0/appointments/132'` on the vets-api) will be tested on the staging environment in order to verify that it's pulling mock data from the vets-api-mockdata repository
=> configure betamocks for appointment service

config/environments/test.rb
In rails test mode, raise if we call a missing translation key
=> Raise on missing tranlsations in test

app/workers/evss/disability_compensation_form/submit_uploads.rb, app/workers/evss/document_upload.rb
app/workers/evss/disability_compensation_form/submit_uploads.rb
and app/workers/evss/document_upload.rb call the same EVSS endpoint.  We should retry the jobs in case of EVSS/partner downtime.  
The jobs were retrying fo4 4h or 21 days.  I've updated them both to be ~1d which is the likely max downtime.
=> Update EVSS file upload retry

docs/setup/native.md
Fix small markdown issue in document.
=> fix doc markdown

lib/saml/templates/sso_post_form.html.erb
we are still seeing a ~2% in the number of browsers that submit the SSOe
post binding SAML form (when comparing saml requests created to those
that are traced).  the initial hope was that Sentry would capture any of
these errors, however if the errors are related to the IIFE, then the
Sentry initialization code will never be executed.
here we are moving that initialization code outside of the IIFE, in hopes
that we will capture any errors in Sentry if the IIFE fails to load in
browsers.
=> moving the Sentry init code outside of the IIFE

config/settings.yml
Adding admin user email for access to flipper feature toggles on staging
Co-authored-by: Steven Garcia <sgarcia@thoughtworks.com>
We added an additional email to `settings.yml` config in order to have access to the staging flipper feature toggles. This is necessary to turn on and off our `get_help_ask_form` toggle.  
[department-of-veterans-affairs/orchid#139]
=> [department-of-veterans-affairs/orchid#139] Adding admin user email for access to flipper feature toggles on staging

app/controllers/application_controller.rb
This reverts the logging introduced in #4148
#4148
=> Revert extra CSRF token Rails logging

config/settings.yml
- Added cert and key access to config/settings.yml for the `hqva_mobile` section
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/14991
When querying mock appointment data, the vets-api is returning an error message because the proper key/cert info is not set under the `hqva_mobile` section in the config/settings.yml file. An example of a failing URI would be `localhost:3000/health_quest/v0/appointments/123123` This PR adds a cert/key to the settings, resolving the current problem.
Mock appointment data will be returned from all environments until the backend API for returning live appointment data is configured.
This will be tested/verified by the FE team when the code is …
=> adding key and cert to hqva_mobile

config/settings.yml
Remove no-longer-used emails from settings.yml flipper admin list.
These users no longer work on this project.
=> Remove no-longer-used emails from settings.yml flipper admin list

app/workers/structured_data/process_data_job.rb, lib/bip_claims/service.rb, spec/jobs/structured_data/process_data_job_spec.rb, spec/lib/bip_claims/service_spec.rb
Renames lookup_veteran_from_mvi to lookup_veteran_from_mpi in lib/bip_claims/service.rb as part of the renaming efforts for the Master Person Index.
department-of-veterans-affairs/va.gov-team#14787
=> Update lookup_veteran_from_mvi to mpi

modules/mobile/app/serializers/mobile/v0/user_serializer.rb, modules/mobile/spec/request/user_request_spec.rb
Some test users have nil birth dates in their provider traits. Since MPI dev is mocked out with staging data looking them up by the IAM dev ICN doesn't return a result and the birth date remains nil and throws an error.
department-of-veterans-affairs/va.gov-team#15292
testing done: local integration tests
testing planned: dev/staging integration tests
=> Catch nil birth dates in the mobile user serializer

lib/central_mail/service.rb, modules/appeals_api/app/controllers/appeals_api/metadata_controller.rb, modules/vba_documents/app/controllers/vba_documents/metadata_controller.rb, modules/vba_documents/config/routes.rb, modules/vba_documents/lib/vba_documents/health_checker.rb, modules/vba_documents/spec/request/metadata_request_spec.rb
Brings current vba_documents healthcheck inline with current healthcheck standards and ensures consumers of this API know the status of its various dependencies as well as this specific service health.
https://vajira.max.gov/browse/API-1544
This does change the functionality of the existing healthcheck endpoint. Previously it would present as down if any of this service's dependencies were down. That endpoint will still present up even if one of the downstream dependencies is down. This change includes a new endpoint, "upstream_healthcheck," which will present as down if any upstream dependencies are down and includes additional information about those dependencies.
Interacted with endpoints locally.
Updated specs to resolve existing tests and include new tests for the new endpoint.
=> API-1544: Report All Upstream Status Dependencies in our Healthchecks - Benefits Intake API

modules/openid_auth/app/serializers/openid_auth/mpi_lookup_serializer.rb
OpenidAuth::MPILookupSerializer (formerly OpenidAuth::MviLookupSerializer) uses the type 'user-mvi-icn'. This PR is renaming the type to 'user-mpi-icn' and doesn't have any downstream effects.
department-of-veterans-affairs/va.gov-team#14794
=> Update serializer type to use new mpi acronym

app/workers/evss/disability_compensation_form/job_status.rb, app/workers/evss/disability_compensation_form/submit_form526.rb, spec/jobs/evss/disability_compensation_form/job_status_spec.rb
in the logs we saw 
`{"host":"05086feeefd7","application":"vets-api-worker","timestamp":"2020-01-16T13:14:54.841379Z","level":"error","level_index":4,"pid":10,"thread":"47034767190920","file":"/srv/vets-api/src/app/workers/evss/disability_compensation_form/job_status.rb","line":39,"name":"Rails","message":"error tracking job exhausted","payload":{"error":"uninitialized constant EVSS::DisabilityCompensationForm::JobStatus::STATSD_KEY_PREFIX","class":"Class"}}`
and no exhausted metrics [this graph](http://grafana.vfs.va.gov/d/000000066/evss-526-submissions?viewPanel=8&orgId=1)
department-of-veterans-affairs/va.gov-team#15307
=> Form526 exhausted metric

app/models/form_profiles/va5655.rb
Fixes the `returnUrl` so end user can progress through the FSR form.
department-of-veterans-affairs/va.gov-team#15381
=> [15381] Fix returnUrl for Financial Status Report form

lib/saml/templates/sso_post_form.html.erb
Sentry bundle is causing JS execution issues on IE in compatibility
mode. This removes the Sentry tracing (which is not providing any useful
hits) while we investigate further.
=> Removes Sentry tracing from SAML POST binding form

modules/claims_api/app/swagger/claims_api/forms/form_526_example.json
Fixes auto-generated curl for 526 POST on https://developer.va.gov/explore/benefits/docs/claims?version=current
https://vajira.max.gov/browse/API-2936
This will require deployment of swagger docs to developer.va.gov 
Tested creating a 526 claim locally.
=> API-2936: autoCestPDFGenerationDisabled is not in 526 POST dev portal docs

rakelib/mvi.rake
This updates an mvi rakefile task to use the new MPIData model instead of the former.
=> Update rakefile to use MPIData

config/settings.yml
We are adding additional developer emails in order to have access to enable and disable our feature toggle `get_help_ask_form`
department-of-veterans-affairs/orchid#139
* Are there additions to a `settings.yml` file? Do they vary by environment? Yes for admin access to feature toggles
* Is there a feature flag? What is it? Yes, `get_help_ask_form` 
* Is there some Sentry logging that was added? What alerts are relevant? No
* Are there any Prometheus metrics being collected? What Grafana dashboard were they added do? No
* Are there Swagger docs that were updated? No
* Is there any PII concerns or questions? No
=> [department-of-veterans-affairs/orchid#139] Adding admin user emails for access to flipper feature toggles on staging

spec/service_consumers/provider_states_for/contact_us.rb
After approving this PR https://github.com/department-of-veterans-affairs/vets-api/pull/5173, I learned there's a cleaner way to do no provider states.
@jgacek we'll close this if you don't need it, but I just wished I had offered this to you yesterday when I was reviewing it but didn't learn until it was too late.
https://docs.pact.io/implementation_guides/ruby/provider_states/#ruby
=> Suggestion for Creates provider state for contact us pact

app/services/bgs/dependent_service.rb, app/workers/vbms/submit_dependents_pdf_job.rb, spec/services/bgs/dependent_service_spec.rb, spec/workers/vbms/submit_dependents_pdf_job_spec.rb
Some new classes were recently added using PDF. Previous investigation of inflections had determined not to inflect it. This PR updates SubmitDependentsPDFJob and other classes using the acronym to the camelcase version (Pdf)
department-of-veterans-affairs/va.gov-team#15531
=> update PDF to camel case

modules/appeals_api/spec/requests/metadata_request_spec.rb, modules/claims_api/app/controllers/claims_api/metadata_controller.rb, modules/claims_api/config/routes.rb, modules/claims_api/lib/claims_api/health_checker.rb, modules/claims_api/spec/lib/health_checker_spec.rb, modules/claims_api/spec/requests/metadata_request_spec.rb, modules/vba_documents/spec/request/metadata_request_spec.rb
Brings current claims healthcheck inline with current healthcheck standards and ensures consumers of this API know the status of its various dependencies as well as this specific service health.
https://vajira.max.gov/browse/API-3070
This does change the functionality of the existing healthcheck endpoint. Previously it would present as down if any of this service's dependencies were down. That endpoint will still present up even if one of the downstream dependencies is down. This change includes a new endpoint, "upstream_healthcheck," which will present as down if any upstream dependencies are down and includes additional information about those dependencies.
Interacted with endpoints locally.
Updated specs to resolve existing tests and include new tests for the new endpoint.
=> API-3070: Report All Upstream Status Dependencies in our Healthchecks - Claims API

modules/appeals_api/config/schemas/200996_headers.json
This PR fixes a bug where consumer user name was not interpolated in the stamp on the HLR generated PDF. 
[PDF Header Missing Consumer Name](https://vajira.max.gov/browse/API-3200)
The headers method inside of `HigherLevelReviewsController` stripped `X-Consumer-Username` from the headers stored in the HLR due to `X-Consumer-Username` being missing from `200996_headers.json`. 
```
def headers
HEADERS.reduce({}) do |acc, header_key|
header_value = request.headers[header_key]
header_value.nil? ? acc : acc.merge({ header_key => header_value })
end
end
```
I added `X-Consumer-Username` to `200996._headers.json` which should allow `X-Consumer-Username` to persist into the HLR model and be retrieved when stamping the PDF.
=> [API 3200] PDF Header Missing Consumer Name

Gemfile.lock, app/models/form_profiles/va5655.rb, config/form_profile_mappings/5655.yml, spec/models/form_profile_spec.rb
- Adds last four digits of fileNumber and SSN to the form prefill
https://github.com/department-of-veterans-affairs/vets-json-schema/pull/540
https://github.com/department-of-veterans-affairs/va.gov-team/issues/15526
Tested locally
=> [15526] Add filenumber/ssn to 5655 form prefill

config/settings.yml
Relates to: https://github.com/department-of-veterans-affairs/va.gov-team/issues/15114
**Description of change**
Updating config to reference the dev version of the CARMA PagerDuty service.
=> Add CARMA PagerDuty ID to config

app/controllers/v0/sessions_controller.rb, app/controllers/v1/sessions_controller.rb, spec/controllers/v0/sessions_controller_spec.rb, spec/controllers/v1/sessions_controller_spec.rb
This change shouldn’t affect the way the way the "SSNS DO NOT MATCH!!" V0::SessionsController#saml_callback errors are grouped in Sentry. Sentry uses a grouping algorithm (a “fingerprint”) to uniquely identify events by stack trace, exception, message, etc. From what I can tell, the additional data (`renaming identity_compared_with_mvi `to `identity_compared_with_mpi`) shouldn’t affect the default fingerprinting as seen [here](http://sentry.vfs.va.gov/organizations/vsp/issues/102/?query=is%3Aunresolved+SSNS+do+not&statsPeriod=14d). Other additional data such as headers, user, request_uuid and OS are dynamic and don’t appear to affect the groupings, so renaming the additional context shouldn’t have any side effects. Tag context appears to have the same functionality that extra context does …
=> Update additional context to mpi for sentry

modules/health_quest/app/serializers/health_quest/v0/va_appointments_serializer.rb, modules/health_quest/spec/request/appointment_request_by_id_spec.rb, modules/health_quest/spec/serializers/v0/va_appointments_serializer_spec.rb
- Adding `patient_icn` attribute to the va_appointments_serializer.
- Correcting typo: `booking_note` has to be `booking_notes`.
Specs written: modules/health_quest/spec/serializers/v0/va_appointments_serializer_spec.rb
=> modify attributes and add specs

app/workers/education_form/create_daily_spool_files.rb, config/features.yml, spec/jobs/education_form/create_daily_spool_files_spec.rb
- Changing prometheus stat `worker_education_benefits_claim_failed_formatting` to be `worker_education_benefits_claim_failed_formatting_<region_id>_22_<type>`
-  Adding a `rescue` to code that writes data to the spool file for each region, other files will still be created
```
rescue => error
exception = SpoolWriteError.new("Error creating #{filename}.\n\n#{error}")
log_exception_to_sentry(exception)
``` 
department-of-veterans-affairs/va.gov-team#14967
=> EDU: Add logging to spool file processing #14967

lib/evss/disability_compensation_form/data_translation_all_claim.rb, spec/lib/evss/disability_compensation_form/data_translation_all_claim_spec.rb, spec/models/saved_claim/disability_compensation/form526_all_claim_bdd_spec.rb, spec/support/disability_compensation_form/all_claims_evss_submission.json, spec/support/disability_compensation_form/bdd_evss_submission.json, spec/support/disability_compensation_form/submissions/526_bdd.json
If a veteran submits a form 526 we'll say it's not expired (expires in one year).  There was some complicated logic that presumably was ported from eBenefits, but Paul Schute says it is not necessary. 
department-of-veterans-affairs/va.gov-team#12690
=> 526 has future expiration date

config/settings.yml, spec/lib/caseflow/configuration_spec.rb
At peak traffic, 97/requests an hour are slower than 20s but average request time is about 700 ms.  Caseflow makes a series of requests to externals services and the more data there is the longer it takes. 
http://grafana.vfs.va.gov/d/000000035/appeals-status?viewPanel=13&orgId=1&from=now-14d&to=now
=> Increase appeals timeout

lib/mvi/models/mvi_profile.rb, lib/mvi/responses/id_parser.rb, lib/mvi/responses/profile_parser.rb, spec/factories/mvi_profiles.rb, spec/lib/mvi/responses/id_parser_spec.rb, spec/lib/mvi/responses/profile_parser_spec.rb, spec/lib/mvi/service_spec.rb
MVI::Responses::IdParser's `#parse` method returns the first active BIRLS ID found in the MPI response, and ignores the rest. A veteran could possibly have multiple BIRLS IDs (although probably only one is valid). As a developer, I would like all the BIRLS IDs returned so I can find the right one.
=> Provide a Way to Access All Active BIRLS IDs (MPI lib)

lib/vet360/contact_information/service.rb, spec/lib/vet360/contact_information/service_spec.rb
log 404 errors for the va profile get_person endpoint in order to find out why it's being called excessively
https://github.com/department-of-veterans-affairs/va.gov-team/issues/15810
=> log get_person 404 errors

app/workers/evss/disability_compensation_form/submit_form526.rb
[EVSS was down](http://grafana.vfs.va.gov/d/000000066/evss-526-submissions?orgId=1&from=1604709955087&to=1604803869104) for more than a day this weekend, so up the retry count to ~36h
=> increase form526 retry count

lib/decision_review/configuration.rb, spec/lib/caseflow/configuration_spec.rb, spec/lib/decision_review/configuration_spec.rb
HLR's decision review service should not time out if Lighthouse's Caseflow service has. 
department-of-veterans-affairs/va.gov-team#16030
=> Decision review timeout matches Lighthouse timeout

modules/va_forms/app/controllers/va_forms/docs/v0/api_controller.rb, modules/va_forms/app/swagger/va_forms/forms/form_swagger.rb
modules/va_forms/app/swagger/va_forms/forms/form_swagger.rb defines a class named Form, it should be FormSwagger to match it's filename. It's used in modules/va_forms/app/controllers/va_forms/docs/v0/api_controller.rb
department-of-veterans-affairs/va.gov-team#15901
=> update classname from Form to FormSwagger

Dangerfile
[My PR](https://github.com/department-of-veterans-affairs/vets-api/pull/5244) is blocked because Danger (rightfully) says there are too many lines of code modified. But many of the LOC changes are to a generated API doc file that we commit. I want to skip this error and get my code merged!
There are a few options that I considered, this PR implements option 3.
This is a fine option, but as we build more into the mobile api, we will most likely run into this problem again. Breaking up the yaml from the generated docs is not semantic and I'd prefer not to do that.
This option is not bad, as the doc can be generated locally as needed. But then non-technical folks will not be able to consume the generated docs easily.
**This is the option I chose here**. This allows our team to continue …
=> Add Danger exclusion for generated docs

lib/vet360/contact_information/person_response.rb, spec/models/vet360_redis/contact_information_spec.rb
cache 404 responses from va profile get_person api
https://github.com/department-of-veterans-affairs/va.gov-team/issues/15971
testing in staging planned
=> Cache VA profile get_person calls that return 404s

config/features.yml
Removes the feature flag that will not be used [after this corresponding FE PR is merged.](https://github.com/department-of-veterans-affairs/vets-website/pull/14932)
https://github.com/department-of-veterans-affairs/vets-website/pull/14932 has been merged so this is clear to merge as well.
department-of-veterans-affairs/va.gov-team#15737
=> remove dashboard_show_covid19_alert feature flag

app/controllers/openid_application_controller.rb, app/models/token.rb, modules/openid_auth/app/controllers/openid_auth/application_controller.rb, modules/openid_auth/app/controllers/openid_auth/v0/validation_controller.rb, modules/openid_auth/app/controllers/openid_auth/v1/validation_controller.rb, modules/openid_auth/spec/requests/validation_request_spec.rb
Adds Lighthouse token validation support for Okta Client Credentials tokens.  These tokens do not contain normal parameters like uuid from Okta, so session & current_user build up has to be skipped.
https://vajira.max.gov/browse/API-3019
* A follow on task, API-3500 will utilize a new OAuth proxy service to retrieve the launch context to populate the ICN in the token response.
* The V0 token validation endpoint is slated for removal (API-3589), but until then it has similar logic to skip the current_user.icn lookup if a client credentials token.
=> Api 3019 client credentials validation endpoint
