department-of-veterans-affairs/vets-api

lib/bgs/auth_headers.rb
modules/claims_api/app/controllers/claims_api/base_form_controller.rb
modules/claims_api/app/workers/claims_api/claim_establisher.rb
modules/claims_api/spec/fixtures/form_526_json_api.json
modules/claims_api/spec/workers/claim_establisher_spec.rb

Publish any flashes submitted with a 526 on successful claim establishment.
https://vajira.max.gov/browse/API-3251
Tested hitting endpoint to submit 526 claim locally.
Updated specs.

API-3251: Updating the claim establisher job to pull and trigger flashes

---

app/workers/education_form/forms/va10203.rb
config/features.yml
spec/support/spool_helpers.rb

As a developer, I need to remove the feature flag for 10203 text message question because it will not be disabled going forward.
[Originating Issue](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/13827)
This is the PR that contains the changes to remove the `stem_text_message_question` from `vets-api`

13827: Removal of stem_text_message_question feature flag.

---

app/workers/education_form/create_daily_fiscal_year_to_date_report.rb
config/features.yml
spec/jobs/education_form/create_daily_fiscal_year_to_date_report_spec.rb

As a developer, I need to remove the 'education_reports_cleanup' feature flag toggle so that it is no longer configurable, and the new functionality is permanent.
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/13860
Removal of a the `education_reports_cleanup` feature flag.
Tested manually

13860: Removal of 'education_reports_cleanup' feature flag.

---

config/features.yml

Adds a new feature toggle for VAOS which enables a new version of the flat facility page for users who are registered to the Sacramento VAMC.
Front end PR: https://github.com/department-of-veterans-affairs/vets-website/pull/14936
department-of-veterans-affairs/va.gov-team#15817

Add feature toggle for VAOS flat facility page for Sacramento

---

app/models/gi_bill_feedback.rb
spec/factories/gi_bill_feedback.rb
spec/fixtures/gibft/transform_form.json
spec/models/gi_bill_feedback_spec.rb

Removed usage of the `social_security_number_last_four` which is being removed from vets-website and the feedback tool schema.
department-of-veterans-affairs/va.gov-team#15978
- vets-website PR: https://github.com/department-of-veterans-affairs/vets-website/pull/14924
- vets-json-schema PR: https://github.com/department-of-veterans-affairs/vets-json-schema/pull/547

Remove reference to feedback tool SSN field

---

modules/vaos/app/services/vaos/middleware/vaos_logging.rb
modules/vaos/spec/services/middleware/vaos_logging_integration_spec.rb
modules/vaos/spec/services/middleware/vaos_logging_spec.rb

As part of the upgrade path for Zeitwerk, the VaosLogging middleware needs to be updated to use the VAOS inflection to properly autoload the classname. 
department-of-veterans-affairs/va.gov-team#15898

update vaos logging middleware to use inflection

---

app/workers/evss/disability_compensation_form/evss_document.rb
app/workers/evss/disability_compensation_form/form8940_document.rb

As part of the upgrade path for Zeitwerk, the EvssDocument classname needs to be updated to use the EVSS inflection to properly autoload.
department-of-veterans-affairs/va.gov-team#15894

update EvssDocument to use EVSS inflection

---

app/controllers/v0/apidocs_controller.rb
app/swagger/swagger/requests/post911_gi_bill_statuses.rb

Description of change
As part of the upgrade path for Zeitwerk, the Post911GiBillStatuses class needs to be updated to use the GI inflection to properly autoload the classname.
department-of-veterans-affairs/va.gov-team#15887

update Gi to inflected version

---

modules/mobile/config/initializers/va_facilities.rb

Splitting [PR 5319](https://github.com/department-of-veterans-affairs/vets-api/pull/5319) into two to reduce the line size. The timezone data is not available via API and the va.gov client, which does the data transformation on the FE, has a similar [json file](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/vaos/utils/timezones.json). This set of data uses a Hash (Dictionary) by facility id rather than array for faster lookup and we don't need `currentTZ` as Rails can figure that out dynamically - e.g. it's not PST year round it's also PDT so that should not be hard coded - we can also go with just 'Pacific' if switching between PST and PDT is confusing to users.
department-of-veterans-affairs/va.gov-team#16056 
* Should be merged first before …

16056  VA facilities names and timezones for mobile appointments

---

app/controllers/concerns/sentry_controller_logging.rb
spec/controllers/application_controller_spec.rb

Sentry expects id, not uuid. https://docs.sentry.io/platforms/ruby/enriching-events/identify-user/
The user's uuid is meaningless on its own but it rather useful in tracking down what the issue is in cases like a validation error where data is relevant.   We've been sending it all along, but not with the proper hash key. 
department-of-veterans-affairs/va.gov-team#16216

Correctly Identify user for Sentry

---

modules/veteran/app/controllers/veteran/application_controller.rb

The modules/veteran/app/controllers/veteran/application_controller.rb file is not being used by any other code and causes a loading error for Zeitwork autloading. This PR removes the file.
department-of-veterans-affairs/va.gov-team#15892

remove VeteranApi::ApplicationController

---

config/features.yml

Add feature flag to toggle typeahead functionality for search.
department-of-veterans-affairs/va.gov-team#14452
Added a new feature flag: search_typeahead_enabled

Srsuddath 1 add typeahead feature flag

---

modules/claims_api/app/models/claims_api/auto_established_claim.rb
modules/claims_api/app/workers/claims_api/claim_establisher.rb

Automatically adds "Homeless" and/or "Terminally Ill" flashes to claim if legacy content regarding these items was sent in the payload.
https://vajira.max.gov/browse/API-3609
Will most likely have to be tweaked within this ticket: https://vajira.max.gov/browse/API-3260
Existing spec tests

API-3609: Flashes - Assuming Homelessness/Terminally Ill flash from their sections of the 526 payload

---

app/controllers/v1/sessions_controller.rb
lib/saml/url_service.rb
spec/controllers/v1/sessions_controller_spec.rb

This change cleans up SAML cookie content creation logic to reduce unnecessary random ID creation by storing the current SAML transaction ID in Redis, as well as including it in the `saml_request_stats` and `saml_response_stats` methods that generate the SAML values logged with Rails logger.
department-of-veterans-affairs/va.gov-team#15179
Manual testing has been done on logins to check for SAML transation IDs, unit tests still need to be updated as mocked SAML request trackers are not generating transaction IDs.

SAML cookie logging

---

modules/health_quest/app/controllers/health_quest/v0/questionnaire_responses_controller.rb
modules/health_quest/app/services/health_quest/patient_generated_data/questionnaire_response/factory.rb
modules/health_quest/app/services/health_quest/patient_generated_data/questionnaire_response/map_query.rb
modules/health_quest/config/routes.rb
modules/health_quest/spec/request/questionnaire_responses_request_spec.rb
modules/health_quest/spec/services/patient_generated_data/questionnaire_response/factory_spec.rb
modules/health_quest/spec/services/patient_generated_data/questionnaire_response/map_query_spec.rb

- Adding the `/health_quest/v0/questionnaire_responses` route to the health_quest module to get all QuestionnaireResponses for a logged-in user.
- The QuestionnaireResponse Service communicates with the PGD FHIR service and GETs all of a patients QuestionnaireResponse resources in a Bundle.
department-of-veterans-affairs/va.gov-team#15007
- Tested locally by visiting http://localhost:3000/health_quest/v0/questionnaire_responses
- RSpec tests written

15007 get questionnaire responses from pgd

---

app/models/bgs_dependents/base.rb
app/models/bgs_dependents/child.rb
app/models/bgs_dependents/relationship.rb
app/models/bgs_dependents/spouse.rb
app/models/bgs_dependents/veteran.rb
app/models/bgs_dependents/vnp_benefit_claim.rb
lib/bgs/children.rb
lib/bgs/marriages.rb
lib/bgs/vnp_veteran.rb
spec/lib/bgs/vnp_veteran_spec.rb
spec/models/bgs_dependents/child_spec.rb
spec/models/bgs_dependents/veteran_spec.rb

This PR is to update the VA Form 686c with a few yes/no questions for pension eligibility.  There are 2 APIs that are updated:
-  `VnpPtcpntRlnshpWebService` - added a flag for `depHasIncomeInd`
-  `VnpBnftClaimWebService` - added a flag for `netWorthOverLimitInd`
department-of-veterans-affairs/va.gov-team#8780
This is just an addition to existing functionality, no additional configuration or logging needed.  
Specs have been updated to reflect the new data.

Adding Pension Questions to 686

---

app/swagger/swagger/schemas/dismissed_status.rb

Swagger::Schemas namespace has a Notification class. app/swagger/swagger/schemas/dismissed_status.rb refers to Notification but doesn't mean in the same namespace, so to refer to the Notification model, the scope must be escaped.
department-of-veterans-affairs/va.gov-team#15888

fix scoping for notification

---

db/migrate/20201118233113_add_flashes_to_claims_api_auto_established_claim.rb
db/schema.rb

Migration to add `flashes` array to `AutoEstablishedClaim`. Related to changes in  department-of-veterans-affairs/vets-api#5333.
https://vajira.max.gov/browse/API-3260

Add migration files for AutoEstablishedClaim flashes

---

modules/appeals_api/app/swagger/appeals_api/v1/higher_level_reviews_controller_swagger.rb

Clarify the difference between `eligible` vs `contestable` in the docs of the /contestable_issues endpoint.
https://vajira.max.gov/browse/API-3594
* Swagger documentation update

Doc Update for /contestable_issues

---

lib/evss/base_headers.rb
spec/lib/evss/disability_compensation_auth_headers_spec.rb

If we can't get the date of birth from MPI get it from the identity provider for EVSS headers.
department-of-veterans-affairs/va.gov-team#6298

fall back to identity provider birth date for evss headers

---

app/controllers/v0/profile/persons_controller.rb

app/controllers/v0/profile/persons_controller.rb has an after_action for `invalidate_mvi_cache` which is now renamed to `invalidate_mpi_cache`. This effort is part of the upgrade path for renaming mvi to mpi related to the Zeitwerk upgrade.
department-of-veterans-affairs/va.gov-team#14783

update method from mvi to mpi

---

modules/apps_api/app/controllers/apps_api/v0/directory_controller.rb

Changing the return order of directory applications to be alphabetical. Prior to this change they were returning in the order they were created.

Ordering applications by name ascending

---

spec/factories/iam_users.rb

A larger upcoming PR requires that the IAM user factories have a static ICN rather than the random one generated by the MVI Profile using Faker.
department-of-veterans-affairs/va.gov-team#14838
N/A

Add ICN to the IAM user factories

---

Gemfile.lock

Set the vets-json-schema reference back to master in Gemfile.lock.
**What happened**
In a [previous PR](https://github.com/department-of-veterans-affairs/vets-api/pull/5264#discussion_r525576625) I used GitHub's suggested commit feature to update Gemfile to reference the master branch before merging. This updates Gemfile but left Gemfile.lock pointing to the previous branch. This PR just runs `bundle update vets_json_schema` to update Gemfile.lock to reference the correct branch and SHA.

reference master branch on vets json schema

---

app/mailers/school_certifying_officials_mailer.rb
app/mailers/stem_applicant_confirmation_mailer.rb
app/mailers/views/school_certifying_officials.html.erb
spec/mailers/school_certifying_officials_mailer_spec.rb
spec/mailers/stem_applicant_confirmation_mailer_spec.rb

Removed references to email CC field from new education mailers becuase CC is not supported.
department-of-veterans-affairs/va.gov-team#16433

Removed CC from SCO email

---

modules/veteran_verification/app/services/emis/mock_military_information_configuration_v2.rb

This PR corrects an issue with the URI build up for the Veteran Verification API call to the mock-emis service.
https://github.com/department-of-veterans-affairs/vets-api/pull/5262

Veteran Verification fix for mock-emis URI build up

---

Gemfile
Gemfile.lock
lib/mpi/messages/find_profile_message.rb
lib/mpi/messages/find_profile_message_fields.rb
spec/lib/mpi/messages/find_profile_message_fields_spec.rb
spec/lib/mpi/messages/find_profile_message_spec.rb
spec/spec_helper.rb

To help Identity, et al, trace SSOe interaction errors.
We would raise an error with `required keys are missing` if any required profile keys were missing, and `required values are missing` if any required profile keys were present but had empty values. We did not however indicate which keys were missing, or were missing values.
We now indicate which keys were missing, or were missing values, in the error message.

MVI FindProfileMessage log missing keys on raise

---

modules/claims_api/app/models/claims_api/auto_established_claim.rb
modules/claims_api/app/workers/claims_api/claim_establisher.rb
modules/claims_api/app/workers/claims_api/flash_updater.rb
modules/claims_api/spec/workers/claim_establisher_spec.rb
modules/claims_api/spec/workers/claim_uploader_spec.rb
modules/claims_api/spec/workers/flash_updater_spec.rb
modules/vaos/spec/workers/extend_session_job_spec.rb
spec/services/users/profile_spec.rb

Persists any responses from bgs if an exception occurs.
https://vajira.max.gov/browse/API-3261
Requires database migration work found here: https://github.com/department-of-veterans-affairs/vets-api/pull/5335
Specs updated and added.

API-3261: Flashes - Track the successes for Flashes by claim

---

app/controllers/openid_application_controller.rb
config/settings.yml
modules/openid_auth/spec/requests/validation_request_spec.rb

This change adds support for Lighthouse Client Credentials tokens to fetch the smart launch context from the OAuth proxy `token.payload['scp'].include?('launch/patient')`.
The Lighthouse OAuth proxy has been added as an entry in the devops fwd proxy.
https://github.com/department-of-veterans-affairs/devops/pull/8066
An accompanying devops PR will configure the url per environment starting with dev.
https://vajira.max.gov/browse/API-3500
* A new `Settings.oidc.smart_launch_url` is required, it will vary by environment and will be specified in an accompanying Devops PR.
* At this time, Client Credentials tokens are only enabled for use in Dev and Sandbox

Api 3500 lighthouse client credentials smart launch fetching

---

app/controllers/v0/dependents_applications_controller.rb
app/models/saved_claim/dependency_claim.rb
app/workers/vbms/submit_dependents_pdf_job.rb

When a dependency claim is submitted (VA Form 686c), sometimes attachments are required as "supporting evidence" that are part of the claim submission.  Examples of this include marriage certificate, birth certificate, etc.  This PR takes the documents that have been submitted with the claim, and uploads them to VBMS.
department-of-veterans-affairs/va.gov-team#15129
The form submission process was already generating a PDF and submitting to VBMS, so no additional configuration or logging was required.  This PR just adds to that existing process and uploads any additional documents if they are present.

Supporting Documents for 686c

---

modules/health_quest/app/controllers/health_quest/v0/questionnaire_responses_controller.rb
modules/health_quest/app/services/health_quest/patient_generated_data/options_builder.rb
modules/health_quest/app/services/health_quest/patient_generated_data/questionnaire_response/factory.rb
modules/health_quest/spec/services/patient_generated_data/options_builder_spec.rb
modules/health_quest/spec/services/patient_generated_data/questionnaire_response/factory_spec.rb

- Get QuestionniareResponse resources by a given appointment id
department-of-veterans-affairs/va.gov-team#16377
- RSpec test coverage
- Manual testing by visiting `/health_quest/v0/questionnaire_responses/?filters[appointment_id]=<appointment_id>`

fetch QRs by appointment id

---

modules/appeals_api/app/models/appeals_api/notice_of_disagreement.rb
modules/appeals_api/lib/appeals_api/notice_of_disagreement_pdf_constructor.rb
modules/appeals_api/lib/appeals_api/notice_of_disagreement_pdf_options.rb
modules/appeals_api/spec/workers/notice_of_disagreement_pdf_submit_job_spec.rb

Add additional administrative page to pdf where necessary. Currently adds the hearing type requested by the Veteran. Is a separate page since Issues have their own callout for separate pages in the form.
https://vajira.max.gov/browse/API-3752

API-3752 Hearing page for NOD pdf

---

app/controllers/concerns/form_attachment_create.rb
app/controllers/v0/hca_attachments_controller.rb
app/controllers/v0/preneeds/preneed_attachments_controller.rb
app/controllers/v0/vic/supporting_documentation_attachments_controller.rb
spec/request/swagger_spec.rb
spec/request/upload_supporting_evidence_spec.rb

Rather than excluding all form attachment controllers from authenticating, it should be done on a case-by-case basis. upload_supporting_evidence is called from form 526 which requires all users to be authenticated.  By not skipping authentication, it will make it easier to troubleshoot which users are having problems with uploads, now that the user's uuid is in sentry.
department-of-veterans-affairs/va.gov-team#16216

Only skip authentication for some attachment controllers

---

modules/apps_api/lib/apps_api/directory_application_creator.rb

Currently we are using the okta api to store the static application logo urls for the applications in the directory, however the quality of these images are a mixed bag, so moving forward all image sources will be from a new S3 bucket.

Changing application logo url to s3 source url

---

modules/claims_api/app/controllers/claims_api/application_controller.rb
modules/claims_api/app/controllers/claims_api/v0/forms/disability_compensation_controller.rb
modules/claims_api/app/controllers/claims_api/v0/forms/power_of_attorney_controller.rb
modules/claims_api/app/controllers/claims_api/v1/forms/disability_compensation_controller.rb
modules/claims_api/app/controllers/claims_api/v1/forms/power_of_attorney_controller.rb
modules/claims_api/app/models/claims_api/power_of_attorney.rb
modules/claims_api/spec/requests/v0/claims_request_spec.rb
modules/claims_api/spec/requests/v0/power_of_attorney_request_spec.rb
modules/claims_api/spec/requests/v1/claims_request_spec.rb

Protect api from invalid source requesting information solely by id.
https://vajira.max.gov/browse/API-3366
Spec tests.

API-3366: Need to filter 526 and 2122 find_by methods using the source label

---

app/models/okta_redis/grants.rb

Fully intend to roll this back, but adding some sentry-info logging in order to see if I can glean some more information about the reason connected apps aren't refreshing immediately.

add some sentry logging for activity around okta service calls

---

config/settings.yml
config/settings/test.yml
lib/vre/ch31_form.rb
lib/vre/service.rb
spec/support/vcr_cassettes/veteran_readiness_employment/failed_send_to_vre.yml
spec/support/vcr_cassettes/veteran_readiness_employment/send_to_vre.yml

During staging testing, I realized that we didn't have the endpoint url config for an API call. The config itself was superfluous so I added the url to the code base. Also during testing, the dev on the other team with the API we consume asked for a an application_intake id so I added that temporarily while we're testing in staging.
No issue attached to this PR
Just a removal
This feature is not available to the public
Yes, we added a message log to get a reference id
No
* Are there Swagger docs that were …

Add ch31 vendor endpoint

---

.rubocop.yml

Adds config to the root-level rubocop to ignore the db migration files for all sub-modules.
In short, PR's were excluding `module/whatever/db/migration/*.rb` when running `rubocop`, whereas `master` CI would still run on these files. This meant that if a linting error was introduced in one of these files in a PR the CI would not catch it. Once merged however, the `master` CI `rubocop` would run on that file and fail. [This ultimately blocked a daily deploy](https://dsva.slack.com/archives/C0MQ281DJ/p1606763358227700?thread_ts=1606762827.226800&cid=C0MQ281DJ).
- [I logged a bug with rubocop](https://github.com/rubocop-hq/rubocop/issues/9132) that goes into the gory details of how using `--force-exclusion` behaves differently than when not using it.
- PR's only lint the files that were …

rubocop ignore migrations for all modules

---

lib/evss/disability_compensation_form/data_translation_all_claim.rb
spec/lib/evss/disability_compensation_form/data_translation_all_claim_spec.rb

if a user submits a form with redacted banking info we should fetch the unredacted info from ppiu
https://github.com/department-of-veterans-affairs/va.gov-team/issues/11773

get banking info from ppiu if submitted info is redacted

---

modules/apps_api/app/controllers/apps_api/v0/directory_controller.rb
modules/apps_api/config/routes.rb
modules/apps_api/spec/requests/v0/application_directory_request_spec.rb

Added show method to the directory controller to allow for getting a single application in the directory. Previously there was only an index method that returned all records. The `routes.rb` for the apps_api module has been updated.
https://vajira.max.gov/browse/API-3843?workflowName=Lighthouse+Default+Workflow&stepId=3
tests have been updated to account for new route method.

added directory#show

---

app/models/user.rb
spec/models/user_spec.rb

When I call @current_user.birth_date, I'd expect the date to be returned in the same format.  I don't anticipate any issues with this global change because we were already returning the dashed format most of the time. 
Before the dates were both strings in different formats: 
`@current_user.mpi&.profile&.birth_date => "19801201" `
`@current_user.identity.birth_date => "1980-12-01"`
department-of-veterans-affairs/va.gov-team#16649

consistent User#birth_date format

---

app/models/okta_redis/grants.rb

This PR removes the use of Redis to cache connected applications (grants) for a user. (See "original issue" below for reason this change is needed.)
* the `all` method just use in-memory caching to prevent additional requests to okta during a single request to the api
* delete no longer needs to delete a cache key since the cache isn't used
* delete also refactored to not track a boolean since the logic breaks with the exception, not a `false`-y value.
The `Grant` class should probably not inherit from `Model` which inherits from `Common::RedisStore` but the way this code is accessed is through the `App` service referencing some meta programming in the user class.  Untangling that is a bigger project, so feedback on other changes this PR should include are welcome. …

13444 refactor okta grant caching

---

app/models/bgs_dependents/veteran.rb
lib/bgs/benefit_claim.rb
lib/bgs/vnp_veteran.rb
spec/lib/bgs/vnp_veteran_spec.rb

During integration testing for Dependency Claims (VA Form 686c), it was determined that we need to populate the SOJ field with the Regional Office number closest to the Veteran (based on their zip code).  This PR updates the Form 686c submission process to pass the SOJ field to BGS.
department-of-veterans-affairs/va.gov-team#16696
department-of-veterans-affairs/va.gov-team#12425
This is a minor PR update to an existing feature so no new settings or logging have been added.

Pass Regional Office in SOJ field for 686c Submission

---

app/controllers/v0/sessions_controller.rb
lib/mpi/service.rb
spec/controllers/v0/sessions_controller_spec.rb

Updates the v0 authentication logout route (`/sessions/slo/new`) to ONLY load the user and destroy the session before issuing an SLO call to ID.me (similar to what's happening in v1).  Previously the `authenticate` method would also "extend" the session, before issuing SLO.  While in the majority of cases this works, sometimes we need to query MPI to get data in order to "extend" the session.  If the [MPI query fails](http://sentry.vfs.va.gov/organizations/vsp/issues/6593/?environment=production&project=3&query=is%3Aunresolved+%22MVI%3A%3AErrors%3A%3AInvalidRequestError%22&statsPeriod=14d) this can result in an error for the user, but these are unnecessary as the user SHOULD NOT need to do this.
In addition, temporary logging of outgoing XML in the event that InvalidRequestError is …

MVI slo improvements and and additional error logging

---

.circleci/config.yml

Added a step in the `pact_verification` CircleCI workflow to trigger vets-website's `can-i-deploy` workflow.
This is meant to build on top of #5288.
Related to department-of-veterans-affairs/va.gov-team#16325.
The newly added `notify_pact_consumers` job uses a parameter `consumer_branch`.
That parameter's expected to be passed in from the vets-website job that triggered the `pact_verification` workflow.

Refactored Pact verification workflow to work independently of webhooks

---

app/controllers/v1/sessions_controller.rb
lib/saml/responses/login.rb
spec/controllers/v1/sessions_controller_spec.rb
spec/lib/saml/responses/login_spec.rb
spec/support/saml/response_builder.rb

This change improves the `handle_callback_error` function to attempt to tease out more specific `status_detail` information in a failed SAML response to be logged to Sentry instead of logging them all together in a bundle, which does not provide much actionable data to go off of.
department-of-veterans-affairs/va.gov-team#15009
Unit testing was included for the new status_detail method and updated to include a status_detail test case for saml_callback method; manual testing was done with the logged error SAML response via an API client and by attempting to submit a SAML form to ID.ME with an expired timestamp.

Saml response errors

---

modules/appeals_api/app/controllers/appeals_api/v1/decision_reviews/notice_of_disagreements_controller.rb
modules/appeals_api/app/models/appeals_api/notice_of_disagreement.rb
modules/appeals_api/app/serializers/appeals_api/notice_of_disagreement_serializer.rb
modules/appeals_api/config/locales/en.yml
modules/appeals_api/config/routes.rb
modules/appeals_api/spec/requests/v1/notice_of_disagreements_controller_spec.rb

Notice of disagreement show endpoint implemented. Includes newly migrated status - only designed to handle the default 'pending' status for now.
https://vajira.max.gov/browse/API-3628
Documentation update to follow once feedback on PR received.
NOD controller spec updated to check for status = 'pending'

Add nod show endpoint and surface status

---

Gemfile
Gemfile.lock

There's [a bug in Puma 4.3.5](https://github.com/puma/puma/issues/2304) which prevents some compilers from building the native extensions required for Puma.
I was running into this issue on macOS Big Sur. Updating fixed it.

Update Puma to 4.3.7

---

modules/claims_api/app/controllers/claims_api/v1/forms/power_of_attorney_controller.rb
modules/claims_api/app/controllers/concerns/claims_api/mpi_verification.rb
spec/lib/common/exceptions/parameters_missing_spec.rb

System is returning a generic 500 response if the endpoint consumer has not provided Veteran information in the auth headers and said consumer is not in MPI. This should resolve that and respond with a 400 response as expected.
https://vajira.max.gov/browse/API-3036
Tested locally

API-3036: 2122 (John Doe) Http 500 Error

---

db/migrate/20201205223834_add_covid_registration_submissions.rb
db/schema.rb

DB migration and schema update for covid_vaccine module. This migration is tested in dev/review instances, extracted from this PR: https://github.com/department-of-veterans-affairs/vets-api/pull/5439/commits
so that we can apply it separately. 
This feature does store PII in the `encrypted_form_data` table - this contains the raw submission to the covid vaccine registration endpoint. This storage is approved by product owner @batemapf. Vets-api is not the source of truth for this data, but we're retaining it in case we need to replay submissions to the underlying system.

Migrations for covid_vaccine schema

---

lib/iam_ssoe_oauth/session_manager.rb
spec/lib/iam_ssoe_oauth/session_manager_spec.rb

Needed to set last_signed_in for mobile iam users in order to user EVSS services
No issue created, hot fix
Set last_signed_in and updated tests to check that the field is non-null

need to set last_signed_in for mobile iam users

---

app/controllers/v0/education_career_counseling_claims_controller.rb
app/models/saved_claim/education_career_counseling_claim.rb
spec/factories/education_career_counseling_claim.rb
spec/factories/education_career_counseling_claim_no_vet_information.rb
spec/models/saved_claim/education_career_counseling_claim_spec.rb

This PR is to fix the CH36 form submission to CentralMail.  CentralMail expects a field called "veteranSocialSecurityNumber" to be at the root level of the hash/payload, so this PR is a fix to ensure that this value is set and in the appropriate location/level.
department-of-veterans-affairs/va.gov-team#16219
This is a minor bug fix PR so no additional settings or logging was necessary.

Fix for CH36 add veteranSocialSecurityNumber field

---

db/migrate/20201208215916_set_guid_as_uuid_on_form1010cg_submissions.rb
db/schema.rb

Made a migration yesterday https://github.com/department-of-veterans-affairs/vets-api/pull/5444 to create the `form1010cg_submissions` table but mistyped the data type for `claim_guid`. This removes the column, creates it again (as uuid), and adds the index.
**Original issue(s)**
https://github.com/department-of-veterans-affairs/va.gov-team/issues/10280

update claim_guid column on form1010cg_submissions as uuid type

---

app/models/saved_claim/veteran_readiness_employment_claim.rb
lib/vre/ch31_form.rb
lib/vre/service.rb
spec/support/vcr_cassettes/veteran_readiness_employment/failed_send_to_vre.yml
spec/support/vcr_cassettes/veteran_readiness_employment/send_to_vre.yml

During testing, we discovered our partner had to change their endpoints we submit to. We also learned that one of the values we send is now expected to be an array so we have accounted for that as well in the PR.
department-of-veterans-affairs/va.gov-team#17125

Add VRE updates

---

spec/service_consumers/provider_states_for/coronavirus_vaccination.rb

Regarding ticket - https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/16989
Create Pact provider state file for the following states for the Coronavirus Vaccination app:
- authenticated user application data
- unauthenticated user application data
The consumer (FE) tests which create the Pact contracts are currently in this branch - https://github.com/department-of-veterans-affairs/vets-website/tree/16989_create_pact_tests

16989 create pact tests covid vaccine

---

modules/appeals_api/lib/appeals_api/base_pdf_constructor.rb
modules/appeals_api/lib/appeals_api/notice_of_disagreement_pdf_constructor.rb

This PR address [API-3827](https://vajira.max.gov/browse/API-3827)
Instead of saving temp pdf files (that are created in the process of building up to the final pdfs) in `Rails.root/tmp` we are saving temp files in `/tmp` to allow for easier cleanup.
- Remove any pre-existing tmp files in `Rails.root/tmp`
- Run all the spec in the appeals_api module `rspec modules/appeals_api/spec`
- Verify that there are no pdfs files at `Rails.root/tmp`

Change location of appeals_api temp pdf files

---

modules/claims_api/app/controllers/claims_api/base_form_controller.rb
modules/claims_api/app/controllers/claims_api/v1/forms/intent_to_file_controller.rb
modules/claims_api/app/swagger/claims_api/v1/form_0966_controller_swagger.rb
modules/claims_api/spec/requests/v1/intent_to_file_request_spec.rb

VSRs that are absent in MPI cannot submit ITFs for type `burial`. This rescues that error and provides a more accurate description of that error in the response.
https://vajira.max.gov/browse/API-3631

[API-3631] Fail gracefully on ITF submit calls for invalid VSRs

---

modules/covid_vaccine/app/services/covid_vaccine/v0/registration_service.rb
modules/covid_vaccine/app/services/covid_vaccine/v0/vetext_service.rb
modules/covid_vaccine/spec/services/covid_vaccine/v0/registration_service_spec.rb
modules/covid_vaccine/spec/services/covid_vaccine/v0/vetext_service_spec.rb
spec/support/vcr_cassettes/covid_vaccine/vetext/put_vaccine_registry_200.yml

Fixes the method used for submissions to VEText, and reconciles the expected form data
parameters with what the frontend is sending.
This is a subset of https://github.com/department-of-veterans-affairs/vets-api/pull/5476/files
without the facility API changes to facilitate a quicker fix for current staging env. 

Fix vetext params and request method

---

Dangerfile

Added a .tsv in place of a .txt file in https://github.com/department-of-veterans-affairs/vets-api/pull/5476/files
to better represent the format. This excludes that datafile from Dangerbot checks.

Exclude .tsv (tab-separated-value) from Dangerbot

---

modules/covid_vaccine/app/controllers/covid_vaccine/v0/registration_controller.rb
modules/covid_vaccine/app/models/covid_vaccine/v0/registration_submission.rb
modules/covid_vaccine/app/serializers/covid_vaccine/v0/registration_submission_serializer.rb
modules/covid_vaccine/app/serializers/covid_vaccine/v0/registration_summary_serializer.rb
modules/covid_vaccine/app/services/covid_vaccine/v0/vetext_configuration.rb
modules/covid_vaccine/spec/factories/registration_submissions.rb
modules/covid_vaccine/spec/request/covid_vaccine/v0/registration_request_spec.rb
modules/covid_vaccine/spec/services/covid_vaccine/v0/vetext_service_spec.rb
spec/support/vcr_cassettes/covid_vaccine/vetext/post_vaccine_registry_200.yml
spec/support/vcr_cassettes/covid_vaccine/vetext/post_vaccine_registry_loa1.yml
spec/support/vcr_cassettes/covid_vaccine/vetext/post_vaccine_registry_loa3.yml
spec/support/vcr_cassettes/covid_vaccine/vetext/post_vaccine_registry_unauth.yml

Serializes the submitted/persisted covid_vaccine form submission attributes back as
a response to the `GET` operation. 
- The GET operation does now return PII but will only return a result to an LOA3 user. Anonymous or LOA1 users will not receive any of those attributes. 
- The POST operation only returns a summary of the submission - created at time, vaccine interest, and zip code

Adds serialized submission attributes to post/get

---

modules/covid_vaccine/app/services/covid_vaccine/v0/registration_service.rb
modules/covid_vaccine/config/initializers/statsd.rb

Adds Statsd instrumentation around the potentially expensive parts of the registration flow -
the MPI query and the vetext call. 
(Facilities query instrumentation added in that PR). 
Tested locally and verified stats measure and increment calls appearing in logs.

Instrument registration flow

---

config/settings.yml

Adds the baseline settings.yml value for covid vaccine module's use of VANotify. The env-specific values are already set in the devops repo, and the implementation work is restricted to a codeowners module so can happen in a separate PR:
https://github.com/department-of-veterans-affairs/vets-api/pull/5478/files

Adds setting stub for covid vaccine vanotify use

---

modules/claims_api/app/swagger/claims_api/forms/form_0966_v1_example.json
modules/claims_api/app/swagger/claims_api/v1/form_0966_controller_swagger.rb

Additional endpoint schema documentation for burial needed to be updated. Also removed participant_id from v1 0966 post endpoint. 
https://vajira.max.gov/browse/API-3631
Viewed in developer-portal locally

fix example and update additional doc around burial

---

Dangerfile

The code that was added to not count whitespace when determining lines of code changed was not working properly and thus dangerbot was not alerting when PRs exceeded the LOC limit. This change should fix that issue.

Fixing whitespace code for Dangerfile

---

config/features.yml

This feature flag is still being used by the front-end but was removed in a [previous PR](https://github.com/department-of-veterans-affairs/vets-api/commit/651ef0461afd268557c1525fd7b167ebc3cb1fb6). Needs to be added back in so the 10-10CG form doesn't redirect visitors.

Add allow_online_10_10cg_submissions feature flag

---

db/migrate/20201211213957_add_columns_for_covid_async_submission.rb
db/schema.rb

Updates covid_vaccine schema in preparation for the changes in this PR to support asynchronous form processing:
https://github.com/department-of-veterans-affairs/vets-api/pull/5499
- Adds an encrypted raw_form_data field for the submission received from the user
- Makes sid nullable, so that we can create a record before submitting to the vetext API
* raw_form_data column may contain PII but is encrypted
* Tested locally with async submission process

Adds migrations to allow async covid registration

---

modules/covid_vaccine/app/controllers/covid_vaccine/v0/registration_controller.rb
modules/covid_vaccine/app/jobs/covid_vaccine/submission_job.rb
modules/covid_vaccine/app/models/covid_vaccine/v0/registration_submission.rb
modules/covid_vaccine/app/serializers/covid_vaccine/v0/registration_submission_serializer.rb
modules/covid_vaccine/app/serializers/covid_vaccine/v0/registration_summary_serializer.rb
modules/covid_vaccine/app/services/covid_vaccine/v0/facility_lookup_service.rb
modules/covid_vaccine/app/services/covid_vaccine/v0/registration_service.rb
modules/covid_vaccine/config/initializers/statsd.rb
modules/covid_vaccine/spec/factories/registration_submissions.rb
modules/covid_vaccine/spec/jobs/covid_vaccine/submission_job_spec.rb
modules/covid_vaccine/spec/request/covid_vaccine/v0/registration_request_spec.rb
modules/covid_vaccine/spec/services/covid_vaccine/v0/registration_service_spec.rb
modules/covid_vaccine/spec/services/covid_vaccine/v0/vetext_service_spec.rb
spec/support/vcr_cassettes/covid_vaccine/facilities/query_97212.yml
spec/support/vcr_cassettes/covid_vaccine/registration_facilities.yml
spec/support/vcr_cassettes/covid_vaccine/vetext/post_vaccine_registry_599.yml

Updates covid_vaccine submission to be asynchronous. 
Saves raw submission to db, then spawns worker to perform the MPI and facilities queries and vetext submision. This means submission from frontend is much faster and decoupled from
failures in any backend systems. 
Return value of POST is unchanged, except that the `id` attribute will always be blank. 
Return value of GET changes slightly in that the fields will be closer to what was submitted rather than reflecting what was posted to vetext. There is still possibility that for LOA3 users, if first/last/dob/etc in current_user are different than what was submitted, that's what will get returned. 
Note DB migration is being submitted separately as:
https://github.com/department-of-veterans-affairs/vets-api/pull/5500
will rebase once …

COVID module asynchronous submission processing

---

db/schema.rb

Removes form526_opt_ins table that was removed in
9bc0045041f390427599031dbd4562e8800f0c2e
but then added back accidentally in
17653c161ebfc88f3cc79c144a781bd47b4da35f
https://dsva.slack.com/archives/CQHBJ5U06/p1607724582144200

Removes db table that was inadvertently added back

---

modules/apps_api/lib/apps_api/directory_application_creator.rb

This is not scalable. Endpoints to create and update records are in development, being tracked under https://vajira.max.gov/browse/API-4055. 
Corrected privacy and terms of service urls for Coral Health.
No other changes

corrected privacy and tos url

---

modules/covid_vaccine/app/controllers/covid_vaccine/v0/registration_controller.rb
modules/covid_vaccine/app/models/covid_vaccine/v0/raw_form_data.rb
modules/covid_vaccine/spec/models/covid_vaccine/v0/raw_form_data_spec.rb
modules/covid_vaccine/spec/request/covid_vaccine/v0/registration_request_spec.rb

This introduces validations on `%w[email zip_code vaccine_interest]`.
email validation is performed using REGEX from `URI::MailTo::EMAIL_REGEXP`
zip_code validation is performed using REGEX = /\A^\d{5}(-\d{4})?$\z/
vaccine_interest is just a non blank, presence check.

Adding basic validations to the CovidVaccine form data

---

modules/covid_vaccine/app/jobs/covid_vaccine/registration_email_job.rb
modules/covid_vaccine/spec/jobs/covid_vaccine/registration_email_job_spec.rb

Note: I've only verified that VaNotify service receives this reference attribute and that it sends it to Notification gem. I have not done an end to end verification that the reference attribute can actually get serialized and gets sent to VaNotify. 
On going work for Covid-Vaccine... we want to be able to pass the confirmation id to VANotify so that we can later go to them with that confirmation_id if any reconciliation is needed to verify why or why not an email was sent.
Tagging @philherbert since he is most familiar with the notification gem and VaNotify as an integration on vets-api.

add reference as one of the attributes we send to VANotify

---

app/controllers/v0/caregivers_assistance_claims_controller.rb
app/services/form1010cg/auditor.rb
app/services/form1010cg/service.rb
app/workers/form1010cg/deliver_pdf_to_carma_job.rb
spec/controllers/v0/caregivers_assistance_claims_controller_spec.rb
spec/services/form1010cg/auditor_spec.rb
spec/services/form1010cg/service_spec.rb
spec/workers/form1010cg/deliver_pdf_to_carma_job_spec.rb

Fixes: https://github.com/department-of-veterans-affairs/va.gov-team/issues/17468
**Summary**

Log when Form 10-10CG Attachment Job is successful

---

spec/workers/form1010cg/deliver_pdf_to_carma_job_spec.rb

Create the `tmp/pdfs` directory before creating a fixture file in `Form1010cg::DeliverPdfToCARMAJob` spec. This is to resolve the issue of Jenkins build failing because the file in the test cannot be generated.
```
[2020-12-15T14:33:32.395Z] Failures:
[2020-12-15T14:33:32.395Z] 
[2020-12-15T14:33:32.395Z]   1) Form1010cg::DeliverPdfToCARMAJob#perform integration processes attachment
[2020-12-15T14:33:32.395Z]      Got 1 failure and 1 other error:
[2020-12-15T14:33:32.395Z] 
[2020-12-15T14:33:32.395Z]      1.1) Failure/Error: File.open(file_path, 'w') { |f| f.write('<PDF_CONTENTS>') }
[2020-12-15T14:33:32.395Z] 
[2020-12-15T14:33:32.395Z]           Errno::ENOENT:
[2020-12-15T14:33:32.395Z]             No such file or directory @ rb_sysopen - …
```

Create dir before creating file in Form 10-10cg attachment job spec

---

Gemfile.lock

[Original Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17141)
This PR is to bump the version number for `vets-json-schema` in vets-website for changes that were made as a result of the above ticklet

bumped version number for vets-json-schema

---

modules/covid_vaccine/app/controllers/covid_vaccine/v0/registration_controller.rb

Adds mix-in to avoid reporting the expected RecordNotFound errors from the `#show` method in Sentry.

Avoids reporting CovidVaX RecordNotFound to Sentry

---

modules/covid_vaccine/app/models/covid_vaccine/v0/raw_form_data.rb
modules/covid_vaccine/app/services/covid_vaccine/v0/registration_service.rb
modules/covid_vaccine/spec/factories/registration_submissions.rb
modules/covid_vaccine/spec/models/covid_vaccine/v0/raw_form_data_spec.rb
modules/covid_vaccine/spec/request/covid_vaccine/v0/registration_request_spec.rb
modules/covid_vaccine/spec/services/covid_vaccine/v0/registration_service_spec.rb

Adds check that date is valid enough to be turned into an MPI query,
since it is possible for a partial date like '2000-12-XX" to be submitted.
Solves this Sentry issue: http://sentry.vfs.va.gov/organizations/vsp/issues/11421/events/523bfe0e64124ad989fbed943b7ee779/?query=is%3Aunresolved+CovidVaccine&statsPeriod=14d
We can also tighten up the frontend submission, but we want to add this PR so that current submissions with this issue will be retried succesfully by sidekiq.
Added spec based on observed production behavior.

Tightens up guard around covid vaccine MPI query

---

Gemfile
Gemfile.lock
config/boot.rb

This PR adds the `bootsnap` gem for `test` and `development` environments to speed up the process of file loading. The speed improvements should be fairly dramatic (I was seeing specs load in roughly half the time). Production deployment should be tested since the `boot.rb` file was changed, but if working properly, production should not be affected.
`bootsnap` simply caches files that Rails loads, and it watches for file changes to update these files. It basically makes `spring` unnecessary, and is a lot safer than `spring` anyway.
https://github.com/department-of-veterans-affairs/vets-api/issues/5378
- This solution assumes `ENV['RAILS_ENV']` is defined by time we initialize Rails in `boot.rb`. I've seen application implementations where this is a problem. If so, we have a workaround …

Adding bootsnap gem to improve dev and test environment performance

---

modules/appeals_api/lib/appeals_api/base_pdf_constructor.rb
modules/appeals_api/lib/appeals_api/higher_level_review_pdf_constructor.rb
modules/appeals_api/lib/appeals_api/notice_of_disagreement_pdf_constructor.rb
modules/appeals_api/spec/fixtures/valid_200996_extra.json
modules/appeals_api/spec/lib/higher_level_review_pdf_constructor_spec.rb
modules/appeals_api/spec/workers/higher_level_review_pdf_submit_job_spec.rb

This PR addresses [API-3830](https://vajira.max.gov/browse/API-3830)
This updates the `BasePdfConstructor#merge_page` method so both the HLR and NOD subclasses can use it without having to override it.

Clean up appeals_api base pdf constructor

---

app/models/account.rb

our least performant query is 
`SELECT "accounts".* FROM "accounts" WHERE ("accounts"."idme_uuid" = $1 AND "accounts"."idme_uuid" IS NOT NULL OR "accounts"."sec_id" IS NULL AND "accounts"."sec_id" IS NOT NULL)`
{"total"=>44972.5460984851, "avg"=>1267.0309644372}
It's meant to be “match whichever id we have, but make sure we don’t match a nil id”
but `OR "accounts"."sec_id" IS NULL AND "accounts"."sec_id" IS NOT NULL` is bad news when `OR 1=0` would do. 

fix non-performant query

---

app/workers/evss/disability_compensation_form/job_status.rb
spec/jobs/evss/disability_compensation_form/submit_form526_all_claim_spec.rb

This graph was missing the bdd tag for success http://grafana.vfs.va.gov/d/000000066/form-526-disability-compensation?viewPanel=24&orgId=1&from=now-7d&to=now

[bugfix] Add missing tag to bdd metrics

---

modules/claims_api/app/workers/claims_api/report_unsuccessful_submissions.rb
modules/claims_api/spec/workers/report_unsuccessful_submissions_spec.rb

Resolve report issue if evss_response is anything but a string
https://vajira.max.gov/browse/API-4100
Tested via email previews.
Added spec test.

API-4100: ClaimsApi::ReportUnsuccessfulSubmissions erroring out due to the gsub of an array type

---

lib/saml/user.rb
lib/saml/user_attributes/base.rb
lib/saml/user_attributes/ssoe.rb
spec/controllers/v1/sessions_controller_spec.rb
spec/lib/saml/ssoe_user_spec.rb
spec/support/saml/response_builder.rb

In an effort to reduce the amount of non-necessary errors logged to sentry, we are only raising and logging an error for missing idme_uuids when the login request is:
* outbound
* using v1 sessions_controller
This change prevents an error from being raised if the idme_uuid is missing and either the login request is inbound or the sessions_controller for the request is v0.
department-of-veterans-affairs/va.gov-team#17306
* Unit tests updated to include passing/failing cases for `should_raise_idme_uuid_error`
* Unit tests for other sessions_controller methods updated where new inclusion of `saml_response.settings` is needed
* Manual testing with hard-coded missing_uuid values for inbound and outbound logins

ignores missing id.me uuid for v0 and inbound v1 logins [#17306]

---

config/features.yml

EVSS has implemented PDF splitting (into 50MB chunks) for large PDF files. To test this feature, we are increasing the upload file size limit to 150MB for Form 526 service treatment records and the claims status tool.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/17643
- https://github.com/department-of-veterans-affairs/vets-website/pull/15187
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/16003 (FE)
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/16004 (BE)
- https://github.com/department-of-veterans-affairs/devops/pull/7990
Adding a feature flag

Add evss 150MB upload size feature flag

---

config/settings.yml

Added government cio email for [10758](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10758) Vets-website feature flipping!
department-of-veterans-affairs/va.gov-team#10758
- Added gov cio email to flipper list; it's the same email I will use throughout all envs.

Added my email to flipper list.

---

db/migrate/20201217223026_add_missing_indexes.rb
db/schema.rb

As an additional follow-up to the outage on 12/15, look add missing indexes.
I got the data to find the missing indexes using pghero.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/17692
queries fixed by indexes:
|total in minutes  | average time in ms| query| notes|
|------------------|-------------------|---------------------------------|---|
| 100.306020547243 | 0.218478372151198 |SELECT  "evss_claims".* FROM "evss_claims" WHERE "evss_claims"."user_uuid" = $1 AND "evss_claims"."evss_id" = $2 LIMIT $3"}| not that that query needs help, but evss_claims would filter to 1 row, where user_uuid filters to 12 |
| 142.275733151266 | 674.399114321061 |SELECT COUNT(*) FROM "education_benefits_submissions" WHERE "education_benefits_submissions"."created_at" BETWEEN $1 AND $2 …

Add db indexes

---

modules/veteran_confirmation/app/services/veteran_confirmation/status_service.rb
modules/veteran_confirmation/spec/services/veteran_confirmation/status_service_spec.rb

API-4095 Veteran Confirmation - Handle empty EMIS responses
https://vajira.max.gov/browse/API-4095
Handles empty eMIS response rather than hitting `undefined method `title38_status_code' for nil:NilClass`.
Tested locally and also added rspec for empty items array case.

API-4095 Veteran Confirmation - Handle empty EMIS responses

---

lib/statsd_middleware.rb

This was found in the rails logs a warn, adding to the source app names to ensure logging is properly configured for coronavirus-vaccination.
Adding coronavirus-vaccination app to list of apps for statsd
small change to update the app list.
minor change to update the app list for statsd

add coronavirus-vaccination to app list

---

app/controllers/v0/sessions_controller.rb
app/controllers/v1/sessions_controller.rb
spec/controllers/v0/sessions_controller_spec.rb
spec/controllers/v1/sessions_controller_spec.rb

This PR prevents the specific SAML callback error, when a user has multiple MHV IDs, from logging to sentry, instead choosing simply to log a warning to the Rails logger. We are doing this because although this results in an error response, it is expected and the user has a route to fix the issue, despite not being to log in. We decided this sort of error was just polluting Sentry at the moment.
department-of-veterans-affairs/va.gov-team/issues/17325
* We should watch sentry after merging this PR to make sure we are indeed not getting this type of error anymore.
* It may be useful to set up a dashboard and come up with some metrics for the multiple mhv id error
* To test this, in `lib/saml/user_attributes/ssoe.rb`, I hacked the `def mhv_id_mismatch?`to just return `true`,
* Then confirmed …

17325 prevent multiple mhv id error from logging sentry

---

docs/setup/mailer.md
lib/config_helper.rb

this should make both http://localhost:3000/rails/mailers and https://staging-api.va.gov/rails/mailers/ available to use. This should not enable this in production
department-of-veterans-affairs/va.gov-team#17363

Enable https://staging-api.va.gov/rails/mailers/

---

Gemfile.lock
lib/okta/service.rb

Calls to the okta metadata endpoint and keys endpoint do not require a ssws key. Vets-API calls were using this key. Since it is sensitive information, the key should not be used when unnecessary.
https://vajira.max.gov/browse/API-3866
[API3866_Tests.docx](https://github.com/department-of-veterans-affairs/vets-api/files/5712439/API3866_Tests.docx)

Api 3866 remove unecessary swss headers

---

lib/facilities/ppms/v0/client.rb
lib/facilities/ppms/v1/client.rb

Someone seems to be trying to download all of PPMS Data through the facilities API
Clamping the max results to 50 `(maxResults = page * per_page)`
department-of-veterans-affairs/va.gov-team#17782
PPMS doesn't provide a paginated API, we are limiting the number of results to 50

Clamping the max results to 50

---

app/uploaders/evss_claim_document_uploader.rb
app/uploaders/supporting_evidence_attachment_uploader.rb
app/uploaders/validate_evss_file_size.rb
spec/services/evss_claim_service_spec.rb
spec/uploaders/evss_claim_document_uploader_spec.rb
spec/uploaders/validate_evss_file_size_spec.rb

EVSS will accept PDF's that are larger than 50mb and the other files must be less than 50mb
department-of-veterans-affairs/va.gov-team#16004
I'll wait until EVSS gives us the go-ahead before merging.

Allow larger file for EVSS

---

modules/appeals_api/app/models/appeals_api/higher_level_review.rb
modules/appeals_api/app/models/appeals_api/notice_of_disagreement.rb

The appeals_api test suite was reporting deprecation errors when run.
- update `where.not` when querying multiple attributes 
https://vajira.max.gov/browse/API-4168

Refactor deprecated code

---

modules/claims_api/app/swagger/claims_api/v1/form_526_controller_swagger.rb

Updates documentation around the 526 PUT endpoint to better clarify its usage.
https://vajira.max.gov/browse/API-4096
Looked at within the dev portal locally:

API-4096: Update 526 PUT documentation with PDF info

---

db/schema.rb
modules/claims_api/db/migrate/20201214164818_add_special_issues_to_auto_established_claim.rb

Adds a "special_issues" column to the existing ClaimsApi::AutoEstablishedClaim database table. Will be used to store special issues for a claim long-term.
https://vajira.max.gov/browse/API-3265
Migrated locally and implemented functionality around storing data in this new column. Have a spec to test the storing of that data in the next pr for this.

API-3265: [database-schema] Special Issues - Add special issues persistence for established claim

---

modules/claims_api/app/models/claims_api/auto_established_claim.rb
modules/claims_api/spec/factories/auto_established_claims.rb
modules/claims_api/spec/fixtures/form_526_json_api.json
modules/claims_api/spec/models/auto_establish_claim_spec.rb

Writes special issues to log when an ClaimsApi::AutoEstablishedClaim record is created, for tracking purposes.
https://vajira.max.gov/browse/API-3274
spec

API-3274: Special Issues - Set up logging to capture what we need

---

modules/claims_api/app/workers/claims_api/claim_establisher.rb
modules/claims_api/app/workers/claims_api/special_issue_updater.rb
modules/claims_api/spec/factories/auto_established_claims.rb
modules/claims_api/spec/fixtures/form_526_json_api.json

Kicks off special issue updater job if special issues are found on the claim submission.
Also ensures the equality checks within the special issue updater job doesn't have issues with some items being strings and others being integers.
https://vajira.max.gov/browse/API-3267
Updated a fixture to ensure this new code section gets executed within existing specs.

API-3267: Special Issues - Update the claim establisher job to check for special issues

---

modules/claims_api/app/controllers/claims_api/base_form_controller.rb
modules/claims_api/app/controllers/claims_api/v0/forms/disability_compensation_controller.rb
modules/claims_api/app/controllers/claims_api/v1/forms/disability_compensation_controller.rb
modules/claims_api/spec/fixtures/form_526_json_api.json
modules/claims_api/spec/requests/v1/disability_compensation_request_spec.rb

Stores special issues for a particular claim long-term.
https://vajira.max.gov/browse/API-3265
Ensured existing specs still worked and added spec for this particular functionality.

API-3265: [logic] Special Issues - Add special issues persistence for established claim

---

Dangerfile

csv files are for data and shouldn't block PRs (but they should still be reviewed)
also made a few style changes while I was in there

add csv files to dangerbot

---

app/controllers/v1/facilities/ccp_controller.rb
app/models/ppms/provider_facility.rb
config/features.yml
spec/request/v1/facilities/ccp_request_spec.rb
spec/request/v1/facilities/va_ccp_request_spec.rb
spec/service_consumers/provider_states_for/facilities.rb

We are happy with how the new feature flags are working and the significant performance increase in response times.
removing the ppms v1 client flag and the skip round trip flags and associated code
department-of-veterans-affairs/va.gov-team#15330
* `facility_locator_ppms_use_v1_client`
* `facility_locator_ppms_skip_additional_round_trips`

15330 removing ppms v1 clients and round trip feature flags

---

config/settings.yml
lib/debt_management_center/debts_configuration.rb
lib/debt_management_center/debts_service.rb
lib/debt_management_center/financial_status_report_configuration.rb
spec/lib/debt_management_center/debts_service_spec.rb

Debts Portal is currently using the wrong URL in production, will need to be changed over to the old style URL. Changed format to facilitate this change easier, as lower envs and prod will be using different style URLs for the time being.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/18135

[HOTFIX] PROD Issue - Debts Portal

---

app/models/bgs_dependents/child_marriage.rb
app/models/saved_claim/dependency_claim.rb
lib/bgs/children.rb
spec/lib/bgs/children_spec.rb
spec/models/bgs_dependents/child_marriage_spec.rb

During testing of the 686 (Dependency Claims), we discovered that when reporting the marriage of a child under 18, the child previously married indicator must be set to Y and the relationship type must be set to Biological.  This PR is a fix to update those flags accordingly.
department-of-veterans-affairs/va.gov-team#17810
department-of-veterans-affairs/va.gov-team#12425
No additional settings or configuration have been added.  The dependency application process is already in place, this PR is just updating a couple flags for a specific workflow.

BGS 686 Set Child Married Indicator

---

app/models/saved_claim/dependency_claim.rb
app/services/bgs/dependent_service.rb
app/workers/bgs/submit_form674_job.rb
app/workers/vbms/submit_dependents_pdf_job.rb
spec/factories/dependency_claim.rb
spec/models/saved_claim/dependency_claim_spec.rb
spec/services/bgs/dependent_service_spec.rb
spec/workers/vbms/submit_dependents_pdf_job_spec.rb

When a dependency claim is submitted on VA.gov, one of the options is to submit a VA Form 674.  This PR adds the functionality of generating a 674 PDF and uploading it to VBMS when the form is submitted by the user.
department-of-veterans-affairs/va.gov-team#17517
The code to generate and submit a 686 PDF was already in place, this PR just adds the additional functionality of also generating a 674 PDF.  No additional logging or settings were needed.

Form 674 PDF Submission to VBMS

---

db/schema.rb
modules/appeals_api/db/migrate/20210105174800_add_source_to_hlr.rb
modules/appeals_api/db/migrate/20210105181435_add_source_to_nod.rb

This PR is part of [API-4180](https://vajira.max.gov/browse/API-4180).
To allow for metrics to be better reported we need to add a `source` field to both the NoticeOfDisagreement and HigherLevelReview models.

Add source field to NOD and HLR

---

lib/breakers/statsd_plugin.rb
spec/lib/breakers/statsd_plugin_spec.rb

This work is to provide more clarity around the VAOS Latency graph. Currently the graph displays individual urls for each service related to eligibility service calls (e.g. /cce/v1/patients/xxx/eligibility/Nutrition, /cce/v1/patients/xxx/eligibility/Optometry, /cce/v1/patients/xxx/eligibility/Audiology, etc...), this level of detail is unnecessary and detracts from the overall readability of the graph. 
To resolve this, the service portion (e.g. Nutrition, Optometry, Audiology, etc...) will use a mask (zzz) instead, allowing all associated urls to roll-up under /cce/v1/patients/xxx/eligibility/zzz
department-of-veterans-affairs/va.gov-team#18128

added update to statsd_pulugin url filtering and updated rspecs

---

lib/common/exceptions/detailed_schema_errors.rb
modules/appeals_api/config/schemas/200996_headers.json
spec/fixtures/json/detailed_schema_errors_schema.json
spec/lib/common/exceptions/detailed_schema_errors_spec.rb

Fixes errors of DetailedSchemaErrors where translations were not receiving the proper interpolated values to display as expected.
Before: `:detail => "'%{value}' did not fit within the defined length limits"`
After: `:detail => "'Ed' did not fit within the defined length limits"`

Fix DetailedSchemaErrors

---

modules/apps_api/lib/apps_api/directory_application_creator.rb

This PR updates the OneRecord app description and fixes mismatched quotation marks.
https://vajira.max.gov/browse/API-4086
- updated app description, locally tested

Fix quote mismatch in OneRecord description

---

modules/appeals_api/app/swagger/appeals_api/v1/schemas/notice_of_disagreements.rb

Update `included` key in nodCreateOptions for swagger documentation to reflect schema minItems.
[4239](https://vajira.max.gov/browse/API-4239)

Update Swagger docs to reflect schema minItems for included

---

modules/appeals_api/app/models/appeals_api/notice_of_disagreement.rb
modules/appeals_api/spec/models/notice_of_disagreement_spec.rb

Model header data retrieval methods were using the wrong keys and returning blank strings, causing downstream calls to CentralMail to fail despite it being a valid API request.
https://vajira.max.gov/browse/API-4074

API-4074 Fix NOD header data retrieval

---

modules/appeals_api/app/workers/appeals_api/notice_of_disagreement_pdf_submit_job.rb

CentralMail requires a 5-digit zipcode in its metadata or else it will error. Supply it with 0's for now.
https://vajira.max.gov/browse/API-4074

API-4074 Temporarily use 0s for centralmail zip

---

modules/mobile/app/serializers/mobile/v0/user_serializer.rb
modules/mobile/spec/request/user_request_spec.rb

In the serializer for the mobile user profile the work number shows the mobile number and vice versa.
department-of-veterans-affairs/va.gov-team#18296

Fix mobile user's work and mobile phone numbers being flipped in profile response

---

modules/claims_api/app/controllers/claims_api/application_controller.rb
modules/claims_api/spec/requests/v0/claims_request_spec.rb
modules/claims_api/spec/requests/v1/claims_request_spec.rb

Ensures environments with mocked EVSS has some sort of resemblance to how production behaves if an invalid identifier is passed in to the "get claim by id" endpoint.
https://vajira.max.gov/browse/API-4231
Fixed broken specs.
Tested manually hitting the endpoint locally.

API-4231: Benefits Claims- GET request for specific claim resulting in valid response

---

modules/vba_documents/app/controllers/vba_documents/docs/v0/api_controller.rb
modules/vba_documents/app/controllers/vba_documents/docs/v1/api_controller.rb
modules/vba_documents/app/swagger/vba_documents/document_upload/failure_swagger.rb
modules/vba_documents/app/swagger/vba_documents/document_upload/metadata_swagger.rb
modules/vba_documents/app/swagger/vba_documents/document_upload/status_attributes_swagger.rb
modules/vba_documents/app/swagger/vba_documents/document_upload/status_guid_list_swagger.rb
modules/vba_documents/app/swagger/vba_documents/document_upload/status_report_swagger.rb
modules/vba_documents/app/swagger/vba_documents/document_upload/status_swagger.rb
modules/vba_documents/app/swagger/vba_documents/document_upload/submission_swagger.rb
modules/vba_documents/app/swagger/vba_documents/document_upload/v1/pdf_dimension_attributes_swagger.rb
modules/vba_documents/app/swagger/vba_documents/document_upload/v1/pdf_upload_attributes_swagger.rb
modules/vba_documents/app/swagger/vba_documents/document_upload/v1/status_attributes_swagger.rb
modules/vba_documents/app/swagger/vba_documents/v0/controller_swagger.rb
modules/vba_documents/app/swagger/vba_documents/v0/security_scheme_swagger.rb
modules/vba_documents/app/swagger/vba_documents/v0/swagger_root.rb
modules/vba_documents/app/swagger/vba_documents/v1/controller_swagger.rb
modules/vba_documents/app/swagger/vba_documents/v1/error_model_swagger.rb
modules/vba_documents/app/swagger/vba_documents/v1/security_scheme_swagger.rb
modules/vba_documents/app/swagger/vba_documents/v1/swagger_root.rb

VbaDocuments occurs in the VBADocuments swagger classes and should be changed to respect the inflectiono
department-of-veterans-affairs/va.gov-team#18283

VBADocuments uses VBA inflection

---

modules/appeals_api/app/models/appeals_api/notice_of_disagreement.rb
modules/appeals_api/app/swagger/appeals_api/v1/schemas/notice_of_disagreements.rb
modules/appeals_api/app/workers/appeals_api/notice_of_disagreement_pdf_submit_job.rb
modules/appeals_api/config/schemas/10182.json
modules/appeals_api/spec/fixtures/invalid_10182.json
modules/appeals_api/spec/fixtures/valid_10182.json
modules/appeals_api/spec/fixtures/valid_10182_minimum.json
modules/appeals_api/spec/models/notice_of_disagreement_spec.rb
modules/appeals_api/spec/support/pdf_matcher.rb

We require a zip code to talk to CentralMail, so this change makes `data.attributes.veteran.address.zipCode5` a required part of the NOD create form data.
Note: HLR is already requiring this, so the precedent has already been set.
https://vajira.max.gov/browse/API-4074

API-4074 Add zipcode into NOD schema

---

modules/claims_api/app/controllers/claims_api/base_disability_compensation_controller.rb
modules/claims_api/app/controllers/claims_api/v0/forms/disability_compensation_controller.rb
modules/claims_api/app/controllers/claims_api/v1/forms/disability_compensation_controller.rb
modules/claims_api/app/swagger/claims_api/v1/form_526_controller_swagger.rb
modules/claims_api/spec/requests/v1/disability_compensation_request_spec.rb

No longer runs the ClaimEstablisher background job on POST submission if autoCestPDFGenerationDisabled is set to true. In this case, a 526 pdf form is required to be sent in through the PUT endpoint before the claim can be established.
Note: This only applies to v1. 
https://vajira.max.gov/browse/API-4263
Updated existing broken specs and added new to handle this new workflow.
Added a bit of clarification to the developer portal documentation around both these changes and the fact that 526 POST submission is an asynchronous process.

API-4263: 404 "Claim not found" error on PUT to /526 after successful POST

---

lib/generators/module/module_generator.rb

This adds a specific commit message for the module generator when creating a new module in vets-api. The commit message will be used/searched via Github as a success metric to track developer usage.
department-of-veterans-affairs/va.gov-team#18348

create commit message for module success metric tracking

---

config/settings.yml
config/sidekiq_scheduler.yml
modules/appeals_api/app/mailers/appeals_api/decision_review_mailer.rb
modules/appeals_api/app/views/appeals_api/decision_review_mailer/mailer.html.erb
modules/appeals_api/app/workers/appeals_api/decision_review_report_job.rb
modules/appeals_api/lib/appeals_api/decision_review_report.rb
modules/appeals_api/spec/factories/higher_level_reviews.rb
modules/appeals_api/spec/factories/notice_of_disagreements.rb
modules/appeals_api/spec/lib/decision_review_report_spec.rb
modules/appeals_api/spec/mailers/decision_review_report_mailer_spec.rb
modules/appeals_api/spec/workers/decision_review_report_spec.rb
spec/mailers/previews/appeals_api_decision_review_preview.rb

This PR addresses [API-4180](https://vajira.max.gov/browse/API-4180)
Initial implementation of email report for HLR and NODs.
- How often should this report go out? (will need to update sidekiq scheduler)
- Who all should be included?
- Should the report be turned on (via the `settings.yml`) by default?

Api 4180 - appeals_api report email

---

rakelib/docker_debugging.rake

Adding a sidekiq debugging flag. If true, appends job=0 to foreman command.
department-of-veterans-affairs/va.gov-team#API-4284
Local testing was done in Docker. Verified that setting flag enables or disables Sidekiq as intended.

API-4284 Adding a sidekiq debugging flag

---

modules/claims_api/app/swagger/claims_api/v1/form_2122_controller_swagger.rb

Add note around eased authentication around active POA endpoint.
https://vajira.max.gov/browse/API-4354
Viewed through local developer portal.

API-4354: Discover and document response when POA active endpoint is used by someone that is not POA

---

config/initializers/rack_attack.rb
spec/middleware/rack/attack_spec.rb

Adds RackAttack rate-limiting to all POST and PUT covid-vaccine endpoints. 
Of the following routes:
```
get 'registration', to: 'registration#show'
post 'registration', to: 'registration#create'
post 'registration/unauthenticated', to: 'registration#create'
put 'registration/opt_out', to: 'registration#opt_out'
put 'registration/opt_in', to: 'registration#opt_in'
```
the last 4 will be grouped into a single bucket, such that any POST or PUT requests to ANY of those endpoints will be considered part of the same bucket, and limited to only 4 of either variant within a 5 minute time period for a given IP address. For more details see the rspec example.

adding in rack attack for covid-vaccine

---

app/services/bgs/awards_service.rb

Lookup fails sometimes when looking up award amounts via participant id. Secondary look up within the `get_awards` method added to attempt the look up via SSN if first lookup fails.
department-of-veterans-affairs/va.gov-team#18427
Tested and verified locally using both BGS calls and mock data.

18427 BGS Awards Lookup Fix

---

rakelib/form526.rake

The method previously returned a hash. It returns an array now.

Remove Outdated Comment

---

config/settings.yml
modules/health_quest/app/services/health_quest/lighthouse/claims_token.rb
modules/health_quest/app/services/health_quest/lighthouse/redis_handler.rb
modules/health_quest/app/services/health_quest/lighthouse/request.rb
modules/health_quest/app/services/health_quest/lighthouse/session.rb
modules/health_quest/app/services/health_quest/lighthouse/token.rb
modules/health_quest/app/services/health_quest/patient_generated_data/fhir_client.rb
modules/health_quest/spec/services/lighthouse/claims_token_spec.rb
modules/health_quest/spec/services/lighthouse/redis_handler_spec.rb
modules/health_quest/spec/services/lighthouse/request_spec.rb
modules/health_quest/spec/services/lighthouse/session_spec.rb
modules/health_quest/spec/services/lighthouse/token_spec.rb

- Provide the ability for the Health Quest module to request an access_token from Lighthouse so that the vets-api can use it to procure FHIR resources from that service for a signed-in user
- First, we check to see if a lighthouse session exists in Redis. If it does we return it back so that the user can access FHIR resources from the lighthouse.
- If the lighthouse session does not exist, then we make an HTTP POST call to the lighthouse service to obtain an access_token. This is then stored in Redis as a SessionStore and then returned back to the user so that they can use it during subsequent calls to the lighthouse.
department-of-veterans-affairs/va.gov-team#17904
- There are additions to `settings.yml` and the values will vary by environment.
- The entire feature is on a Flipper: …

Get lighthouse access_token

---

modules/claims_api/app/controllers/claims_api/v0/forms/disability_compensation_controller.rb
modules/claims_api/app/controllers/claims_api/v1/forms/disability_compensation_controller.rb

Added logic to return a 422 with the relevant error message if a claim submission creation fails for whatever reason.
semi-related to https://vajira.max.gov/browse/API-3273
Tested locally and ensured all existing specs still pass.

Improve claim submission error response if issues in record creation

---

db/schema.rb
modules/apps_api/db/migrate/20210113203803_add_index_to_directory_applications.rb

Added unique index to `name` column so that uniqueness can be verified when hitting `#create` method of `DirectoryController` in PR to come shortly. This PR was made to seperate `db` and `app` changes.

added index on name column for directory_applications

---

modules/appeals_api/app/models/appeals_api/higher_level_review.rb
modules/appeals_api/app/models/appeals_api/notice_of_disagreement.rb
modules/appeals_api/app/models/concerns/appeals_api/central_mail_status.rb
modules/appeals_api/spec/models/concerns/appeals_api/central_mail_status_spec.rb

Both HLR and NOD models contain identical code, controlling the updating of instance statuses to match the status returned from central mail. We want to consolidate this code into a shared concern. 
https://vajira.max.gov/browse/API-4219
Refactoring validations (see raises) into tests

Consolidate hlr/nod central mail status logic into concern

---

app/controllers/v0/in_progress_forms_controller.rb
spec/request/in_progress_forms_request_spec.rb

the `#update` and `#destroy` renders should use `key_transform: :unaltered` just like `#index`

Prevent snake_casing For Update and Destroy Response (InProgressFormsController)

---

modules/mobile/app/controllers/mobile/v0/appointments_controller.rb
modules/mobile/app/services/mobile/v0/appointments/service.rb
modules/mobile/config/initializers/statsd.rb
modules/mobile/spec/request/appointments_request_spec.rb
modules/mobile/spec/services/appointments_service_spec.rb
modules/mobile/spec/support/vcr_cassettes/appointments/get_facilities.yml

Fixes a couple issues found during appointments staging integration testing. 
- Fixes missing or invalid startDate and endDate params handling
- Fixes the params format in the cal to the facilities API that retrives VA location data 
Also updates the endpoint to still return some appointments if one of the VA or Community Care appointment services is down.
department-of-veterans-affairs/va.gov-team#14853

14853 mobile GET appointments fixes

---

Gemfile.lock

Running `make up` previously failed on M1 Macs running Docker. This update to pg_query fixes it.

M1 Mac Docker Support

---

Gemfile.lock
spec/rails_helper.rb

When there's a logger provided to BGS it won't output to console (which makes test output hard to read).

point BGS at Rails.logger so it doesn't ouput during tests

---

modules/health_quest/app/controllers/health_quest/v0/questionnaires_controller.rb
modules/health_quest/app/services/health_quest/patient_generated_data/questionnaire/factory.rb
modules/health_quest/app/services/health_quest/patient_generated_data/questionnaire/map_query.rb
modules/health_quest/config/routes.rb
modules/health_quest/spec/request/questionnaires_request_spec.rb
modules/health_quest/spec/services/patient_generated_data/questionnaire/factory_spec.rb
modules/health_quest/spec/services/patient_generated_data/questionnaire/map_query_spec.rb

- Create the service and endpoints to query for Questionnaires by a given ID or by a set of parameters/filters.
department-of-veterans-affairs/va.gov-team#17420
- Functionality is under the `show_healthcare_experience_questionnaire` feature flip.
- RSpec tests written and passing
- Entire vets-api test suite passing

Create the Questionnaire FHIR service

---

config/settings.yml
modules/appeals_api/app/mailers/appeals_api/decision_review_mailer.rb
modules/appeals_api/spec/mailers/decision_review_report_mailer_spec.rb

Moves decision review report email recipients from a constant to Settings. This allows the list to be changed per environment.
https://vajira.max.gov/browse/API-4491
A corresponding PR for updating the settings in devops is here: https://github.com/department-of-veterans-affairs/devops/pull/8384

API-4491 Move report recipients to settings

---

app/models/saved_claim/dependency_claim.rb
spec/models/saved_claim/dependency_claim_spec.rb

When submitting a 686c (Dependency Application) the Veteran's address is not being passed properly.  This PR is a fix to ensure the address gets passed.
department-of-veterans-affairs/va.gov-team#18672
This is a quick fix/revert so no additional settings or logging has been added.

686 Dependency Claim Address Fix

---

app/models/okta_redis/app.rb
app/serializers/okta_app_serializer.rb
app/swagger/swagger/schemas/connected_applications.rb
modules/apps_api/app/models/directory_application.rb

This PR adds a privacy url property to the `profile/connected_applications` response object. This property is needed to update the third party app disconnect copy.
[Ticket](https://vajira.max.gov/browse/API-4003)
[Discussion in vets-website PR](https://github.com/department-of-veterans-affairs/vets-website/pull/15653)

Add privacy policy url to profile/connected_applications response

---

config/routes.rb
lib/generators/module/module_generator.rb

This PR updates the formatting for the lines of code that are inserted into the routes, spec_helper and simplecov_helper when invoking the module generator. The location of where the generator inserted into the routes file was incorrect. The code was updated to use the insert_into_file helper instead of the route helper. The simplecov and spec helper lines were multiline and are now updated to remove the newline character to match the preferred formatting.

Tweak module generator file insert

---

config/features.yml

As a developer, I need to create a feature flag for including state abbreviations in search so that the functionality can be toggled on or off until it's ready for production.
[Originating Issue](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/18312)
Testing passes locallly

18312: Add State Search Feature Flag

---

app/serializers/vet_payment_history_serializer.rb
app/services/bgs/payment_service.rb
spec/controllers/v0/profile/payment_history_controller_spec.rb
spec/services/bgs/payment_service_spec.rb

We recently launched view payments functionality 🥳 which allows vets to see their payment and return payment history.
We were alerted to rare 500 errors occurrences where we were calling `[]` on nil.
This PR checks for the `payment` hash so we don not call it on `nil`. It also adjusts the empty default payload that we had set in the service.
What changed in the empty default payload/Why was it not right in the beginning? The short answer is I'm not sure. Throughout the development of this feature, we had to stumble through a few services to find the one that was _just_ right; the service that had everything we wanted. I think we had set the empty payload according to one of those services and then once we got to the one we're using now, never updated the empty default to reflect what the …

Address 500's for when payments are empty

---

modules/claims_api/app/controllers/concerns/claims_api/document_validations.rb

Noticed we were returning a 500 if an invalid pdf is provided. Changed to be a 400 with brief explanation that the pdf provided is invalid:
```
{
"errors": [
{
"status": 400,
"source": "temp_upload_1610564138.pdf",
"detail": "temp_upload_1610564138.pdf is invalid"
}
]
}
```
semi-related to https://vajira.max.gov/browse/API-4406
Test locallly

API-4406: Proper 400 response if pdf provided is invalid

---

modules/apps_api/app/controllers/apps_api/v0/directory_controller.rb
modules/apps_api/app/models/directory_application.rb
modules/apps_api/config/routes.rb
modules/apps_api/spec/requests/v0/application_directory_request_spec.rb

Added `#create` `#update` and `#destroy` to `DirectoryController`. The endpoints added all require a correct Authorization header stored in credstash and are only intended for internal use when managing the Application Directory.
https://vajira.max.gov/secure/RapidBoard.jspa?rapidView=777&view=detail&selectedIssue=API-4055
Sentry logging to be added later. 
Tests have been included and code coverage is above the required `%`.

Added controller methods, model validation, and tests

---

modules/appeals_api/app/swagger/appeals_api/v1/schemas/notice_of_disagreements.rb
modules/appeals_api/config/schemas/10182.json

This change updates the JSON Schema for Notice of Disagreement to accept a max of included contestable issues.
It also updates the swagger documentation to reflect the change. 
The additional acceptance criteria listed in the ticket was handled by the NOD refactor outlined in [4306](https://vajira.max.gov/browse/API-4306)
[4240](https://vajira.max.gov/browse/API-4240)

Update swagger/schema for max contestable issues

---

modules/va_forms/app/workers/va_forms/form_reloader.rb
modules/va_forms/lib/tasks/va_forms.rake

For those of us running within docker
This rake task
rake va_forms:fetch_latest
fails to run over socks on the host machine (Faraday bombs out).
Adding in a curl based approach for populating our forms db.
rake va_forms:fetch_latest_curl
https://vajira.max.gov/browse/API-4088

Cris.shupp/api 4088 forms api db rake

---

Dangerfile

Excluded files test is only necessary when something excluded in dangerbot warning

cleaner dangerbot text

---

modules/appeals_api/app/services/appeals_api/pdf_construction/higher_level_review/v1/form_fields.rb
modules/appeals_api/spec/services/appeals_api/pdf_construction/higher_level_review/v1/form_fields_spec.rb

This PR commits the lengthy parts (FormFields) of the HLR refactor in order to get around the 'too large PR' issue from dangerbot on PR [5723](https://github.com/department-of-veterans-affairs/vets-api/pull/5723).
[4527](https://vajira.max.gov/browse/API-4527)
This PR is a blocker for PR 5723

Add Form Fields to separate PR for size constraints

---

app/services/bgs/dependent_service.rb
app/workers/vbms/submit_dependents_pdf_job.rb
spec/services/bgs/dependent_service_spec.rb
spec/workers/vbms/submit_dependents_pdf_job_spec.rb

During testing, it was discovered that the PDF submission job for the 686/674 was failing.  Apparently, Sidekiq does not support keyword arguments.  This PR is a fix to change the arguments so that the PDF job gets kicked off successfully.
department-of-veterans-affairs/va.gov-team#18789
This is a tiny PR fix to change the arguments and no longer use keyword arguments.  No additional logging or settings have been added.

Fix 686 Submission PDF Job

---

README.md
modules/claims_api/app/workers/claims_api/flash_updater.rb
modules/claims_api/spec/workers/flash_updater_spec.rb

Calls BGS after adding all flashes to a Veteran and verifies flashes have been added successfully.
Stores a message in the bgs_flash_responses if a flash the job was supposed to add is not found to be assigned to the Veteran.
https://vajira.max.gov/browse/API-4405
Existing and new specs

API-4405: Validate flash sent to BGS was successfully added to Veteran

---

app/controllers/v0/apidocs_controller.rb
app/controllers/v0/search_click_tracking_controller.rb
app/swagger/swagger/requests/search_click_tracking.rb
config/initializers/breakers.rb
config/initializers/statsd.rb
config/locales/exceptions.en.yml
config/routes.rb
config/settings.yml
config/settings/test.yml
lib/search_click_tracking/configuration.rb
lib/search_click_tracking/service.rb
lib/statsd_middleware.rb
spec/lib/search_click_tracking/configuration_spec.rb
spec/lib/search_click_tracking/service_spec.rb
spec/request/search_click_tracking_request_spec.rb
spec/request/swagger_spec.rb
spec/support/vcr_cassettes/search_click_tracking/missing_parameter.yml
spec/support/vcr_cassettes/search_click_tracking/success.yml

This change adds an endpoint to access search.gov's click tracking api
department-of-veterans-affairs/va.gov-team#16367
This POST request is unique in that it sends all information as query params rather than as part of the body

Add search_gov click tracking endpoint

---

modules/appeals_api/app/mailers/appeals_api/decision_review_mailer.rb
modules/appeals_api/app/views/appeals_api/decision_review_mailer/mailer.html.erb
modules/appeals_api/spec/mailers/decision_review_report_mailer_spec.rb
spec/mailers/previews/appeals_api_decision_review_preview.rb

Adds environment name to the reporting email in both the email subject & body.
https://vajira.max.gov/browse/API-4615

API-4615 Add environment to report email

---

modules/appeals_api/app/services/appeals_api/pdf_construction/higher_level_review/v1/structure.rb

Adds missing `final_page_adjustments` method to the HLR PDF Structure
PRs #5703 and #5754 were created separately and each had passed CI and review.
#5730 added the `final_page_adjustment` method but #5754 was not aware of the need to include it in its own code. Had tests been re-run between merging either PR, the issue would have been caught. Since both were already green, however, they were merged in and caused the issue after the fact.
Luckily the timing worked in our favor and #5754 was merged after the final deploy time on Fri, Jan 21 so won't cause issues on production over the weekend.

Add missing method - fixes failing specs

---

config/settings.yml
config/settings/test.yml
modules/health_quest/app/services/health_quest/lighthouse/token.rb
modules/health_quest/app/services/health_quest/patient_generated_data/fhir_client.rb
modules/health_quest/app/services/health_quest/patient_generated_data/fhir_headers.rb
modules/health_quest/app/services/health_quest/patient_generated_data/patient/factory.rb
modules/health_quest/app/services/health_quest/patient_generated_data/patient/map_query.rb
modules/health_quest/app/services/health_quest/patient_generated_data/questionnaire/factory.rb
modules/health_quest/app/services/health_quest/patient_generated_data/questionnaire/map_query.rb
modules/health_quest/app/services/health_quest/patient_generated_data/questionnaire_response/factory.rb
modules/health_quest/app/services/health_quest/patient_generated_data/questionnaire_response/map_query.rb
modules/health_quest/spec/request/patients_request_spec.rb
modules/health_quest/spec/request/questionnaire_responses_request_spec.rb
modules/health_quest/spec/request/questionnaires_request_spec.rb
modules/health_quest/spec/services/patient_generated_data/fhir_client_spec.rb
modules/health_quest/spec/services/patient_generated_data/fhir_headers_spec.rb
modules/health_quest/spec/services/patient_generated_data/patient/factory_spec.rb
modules/health_quest/spec/services/patient_generated_data/patient/map_query_spec.rb
modules/health_quest/spec/services/patient_generated_data/questionnaire/factory_spec.rb
modules/health_quest/spec/services/patient_generated_data/questionnaire/map_query_spec.rb
modules/health_quest/spec/services/patient_generated_data/questionnaire_response/factory_spec.rb
modules/health_quest/spec/services/patient_generated_data/questionnaire_response/map_query_spec.rb

- This PR adds a `pgd_path` to the settings.yml file so that PGD services in the health-quest module can now "talk" to the Lighthouse PGD server in the sandbox environment.
- Refactoring the code and the tests so that the health-quest services use the access_token obtained from the Lighthouse PGD to query for FHIR resources from the Lighthouse PGD FHIR server(the sandbox only).
department-of-veterans-affairs/va.gov-team#18921
- Adding `pgd_path` variable to `settings.yml`. Appropriate values will be added for development and staging environments.
-  Feature flag: show_healthcare_experience_questionnaire
- RSpec tests written and passing.

Cleanup after moving to lighthouse PGD

---

modules/appeals_api/app/models/appeals_api/notice_of_disagreement.rb
modules/appeals_api/app/workers/appeals_api/notice_of_disagreement_pdf_submit_job.rb
modules/appeals_api/spec/models/notice_of_disagreement_spec.rb
modules/appeals_api/spec/workers/notice_of_disagreement_pdf_submit_job_spec.rb

[API-3817](https://vajira.max.gov/browse/API-3817)
This ticket sends the NOD line of business with parameter 'lob' to CentralMail uploading, using the NOD value of 'BVA', in order to route the 10182 correctly.

Add 'lob' to CentralMail upload

---

.github/CODEOWNERS

The Form526 Rake Task is just helper code for Benefits & Memorials 1 Team --largely stats and reporting stuff (some migration stuff). I propose that _BAM Team_ owns it for reviewing purposes.

Adding VSA/BAM1 Ownership of Form526 Rake Task

---

app/models/bgs_dependents/vnp_benefit_claim.rb

During integration testing with BGS, it was discovered that one of the values we are passing for a pension eligibility question was not being saved on their side.  After some debugging, they realized that it was being overwritten.  This PR is a quick fix to add the `netWorthOverLimitInd` field to the `vnpBnftClaimUpdate` call so that it doesn't get overwritten during the update.
department-of-veterans-affairs/va.gov-team#19003
This is a minor fix so no new settings or logging have been added.

Fixing 686 Pension Eligibility Question

---

README.md
modules/claims_api/app/models/claims_api/auto_established_claim.rb
modules/claims_api/app/workers/claims_api/claim_establisher.rb
modules/claims_api/spec/workers/claim_establisher_spec.rb

After working through this, im not 100% sure why this is working correctly in production now, but it definitely is somehow.
When i run through the internals of the ClaimEstablisher job in sandbox it fails to save because of the `uniqueness` validation on the record's md5. That md5 will always be the same at that point in the logic, because it is generated from the record's `auth_headers` and `form_data` which are unchanged at that point.
Even weirder is that calling `save` once more, after the initial save fails, succeeds (all in sandbox i should reiterate). I'm not sure why this is the case...
Hopefully this change makes overall sense for this logic (and also seems to resolve sandbox as a nice side-effect). It essentially only validates the uniqueness of the md5 on create, not update. …

API-4589: Record not saving in sandbox after claim establishment through EVSS

---

modules/claims_api/app/controllers/claims_api/application_controller.rb
modules/claims_api/app/controllers/claims_api/v0/forms/disability_compensation_controller.rb
modules/claims_api/app/controllers/claims_api/v1/forms/disability_compensation_controller.rb
modules/claims_api/app/serializers/claims_api/auto_established_claim_serializer.rb
modules/claims_api/app/serializers/claims_api/claim_detail_serializer.rb
modules/claims_api/spec/requests/v1/claims_request_spec.rb

Always return our database uuid for the id value in every claim response.
The only time the evss_id will be used is if the user provides an evss_id (in the case where the particular claim may not have been submitted through our api).
https://vajira.max.gov/browse/API-4568
Tested locally.
Updated and add specs.

API-4568: Don't replace GUID with EVSS Claim ID

---

config/features.yml

This PR just adds a feature flag for the Covid Vaccine app that allows the sign-in button to be hidden.
Related vets-website PR: https://github.com/department-of-veterans-affairs/vets-website/pull/15758
Not much more to add.  
I have tested the feature flag functionality locally, and implemented a Cypress test for the FE

Add feature flag to hide Sign-in button for Covid Vaccine app

---

modules/appeals_api/app/swagger/appeals_api/v1/schemas/notice_of_disagreements.rb
modules/appeals_api/config/schemas/10182.json

This PR updates our NOD contestable issues `issue` field to be 255 chars (in both the docs and the schema). This is based on Caseflow's Contention class that truncates at 255 bytes (https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/contention.rb).
https://vajira.max.gov/browse/API-4076

API-4076 - Change max length of nod issue

---

modules/health_quest/app/controllers/health_quest/v0/questionnaire_responses_controller.rb
modules/health_quest/app/controllers/health_quest/v0/questionnaires_controller.rb
modules/health_quest/app/services/health_quest/patient_generated_data/options_builder.rb
modules/health_quest/app/services/health_quest/patient_generated_data/questionnaire/factory.rb
modules/health_quest/app/services/health_quest/patient_generated_data/questionnaire/map_query.rb
modules/health_quest/app/services/health_quest/patient_generated_data/questionnaire_response/factory.rb
modules/health_quest/app/services/health_quest/patient_generated_data/questionnaire_response/map_query.rb
modules/health_quest/spec/request/questionnaire_responses_request_spec.rb
modules/health_quest/spec/request/questionnaires_request_spec.rb
modules/health_quest/spec/services/patient_generated_data/options_builder_spec.rb
modules/health_quest/spec/services/patient_generated_data/questionnaire/factory_spec.rb
modules/health_quest/spec/services/patient_generated_data/questionnaire_response/factory_spec.rb

- GET Questionnaire Responses from the Lighthouse PGD by a given appointment ID
- Refactoring the `options_builder.rb` and related rspec tests so that filters can be scoped by QuestionnaireResponse and Questionnaire resources respectively.
department-of-veterans-affairs/va.gov-team#17207

GET questionnaire_responses by appointment_id

---

modules/appeals_api/app/workers/appeals_api/higher_level_review_pdf_submit_job.rb

The pre-submitted status  for the HLR PDF - "submitting" was accidentally removed during a Refactor. This puts it back.

put back submitting status

---

modules/claims_api/app/controllers/claims_api/application_controller.rb
modules/claims_api/app/models/claims_api/power_of_attorney.rb
modules/claims_api/app/serializers/claims_api/power_of_attorney_serializer.rb
modules/claims_api/app/swagger/claims_api/forms/form_2122_response_swagger.rb

Removes Participant ID from any public facing responses. We don't currently require it, and all the lookups for it are internal, so there's no need to expose it at this time
https://vajira.max.gov/browse/API-4400

API-4400 Remove participant ID from responses for Claims Endpoints

---

modules/apps_api/app/controllers/apps_api/v0/directory_controller.rb
modules/apps_api/spec/requests/v0/application_directory_request_spec.rb

This is a small hotfix to use the correct value of `Settings.directory.key` instead of `Settings.directory.secret` inside the `directory_controller`. This typo wormed its way through past PRs due to my `Settings.local.yml` having `key` instead of `secret`.
Slack thread where this typo was found: https://dsva.slack.com/archives/CBU0KDSB1/p1611861312392800
The `credstash` calls that reference this value  in the devops repo are correct and do not need to be updated.
Value of secret checked inside credstash and inside the Rails Console of the `vets-api` dev environment.

Changed typo in DirectoryController

---

app/controllers/appeals_base_controller.rb
app/controllers/concerns/failed_request_loggable.rb
app/controllers/v0/higher_level_reviews/contestable_issues_controller.rb
app/controllers/v0/higher_level_reviews_controller.rb
spec/request/v0/higher_level_reviews_controller_request_spec.rb

from [the ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19143)
>Currently we aren't capturing the complete request data anywhere when an HLR request fails. Now that we've soft launched, let's capture the complete request data in the PersonalInformationLog (which gets cleared every 2 weeks) for failures so that we can better debug failed requests.

Log Failed HLR-related Requests to the PII Log

---

app/models/emis_redis/model.rb
app/models/okta_redis/grants.rb

`require_dependency` is obsoleted by zeitwerk.  More PRs will come for modules directories.
"All these problems are solved in zeitwerk mode, it just works as expected, and require_dependency should not be used anymore, it is no longer needed." https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#ruby-constant-lookup-compliance
department-of-veterans-affairs/va.gov-team#14688

remove require_dependency from app directory

---

config/environments/test.rb
modules/appeals_api/app/controllers/appeals_api/metadata_controller.rb
modules/appeals_api/config/routes.rb
modules/appeals_api/lib/appeals_api/health_checker.rb
modules/appeals_api/spec/lib/health_checker_spec.rb
modules/appeals_api/spec/requests/metadata_request_spec.rb

[4695](https://vajira.max.gov/browse/API-4695)
This PR adjusts the HealthChecker for AppealsAPI to accommodate multiple upstream services for different versions of our API.

Api 4695/update healthcheck to include central mail

---

app/models/saved_claim/dependency_claim.rb
app/workers/vbms/submit_dependents_pdf_job.rb
spec/models/saved_claim/dependency_claim_spec.rb

When submitting a 674 (VA Form 21-674b), we generate a PDF and send it to VBMS but currently we are using the incorrect document type. We need to set the document type that corresponds to the 674 form, instead of using the default doc type.
department-of-veterans-affairs/va.gov-team#19089
This is a minor fix so no new settings or logging have been added.

Setting Appropriate Doc Type for Form 674

---

config/features.yml

This pull request adds a new feature toggle that will allow the view dependents page to house an in development application for directly managing dependents instead of feeding users into the 686 form flow.
department-of-veterans-affairs/va.gov-team#17564

add manage dependents toggle

---

lib/facilities/ppms/v1/response.rb
spec/lib/facilities/ppms/v1/client_spec.rb
spec/request/v1/facilities/ccp_request_spec.rb

we are now deduping providers the same way we dedupe places of service.
PPMS results provide a `uniqueId` this isn't a uniqueId and several providers at different locations use the same unique id...
we are now deduping providers the same way we dedupe Places of Service....
department-of-veterans-affairs/va.gov-team#19045
* This makes the ID useless for looking up specific providers (ie details page) but we don't do that anymore.

PPMS provider_id is not unique

---

modules/appeals_api/app/services/appeals_api/pdf_construction/generator.rb

[API-4720](https://vajira.max.gov/browse/API-4720)
CombinePDF currently displays a warning if it's receiving a null object.
The
`appeals_api/spec/services/appeals_api/pdf_construction/generator_spec.rb`
file generates a whole bunch of warnings when we try to use CombinePDF during the routine PDF generation.
The goal is to keep the functionality we currently have while adjusting the tests to handle the null object that CombinePDF is struggling with.
Couldn't connect reference for {:is_reference_only=>true, :indirect_generation_number=>0, :indirect_reference_id=>396, :referenced_object=>nil}
Since CombinePdf is working as expected with these errors, using pdftk in favor of CombinePdf... makes sense.

replace CombinePdf with pdftk#cat

---

modules/appeals_api/config/schemas/200996.json
modules/appeals_api/lib/appeals_api/form_schemas.rb

This PR removes TODO comments in our code, with corresponding tickets to apportion out the work.
[4821](https://vajira.max.gov/browse/API-4821)
[4822](https://vajira.max.gov/browse/API-4822)

Remove TODOs, tickets created

---

lib/common/client/configuration/base.rb
spec/jobs/evss/disability_compensation_form/submit_form526_all_claim_spec.rb
spec/request/swagger_spec.rb

When we get a 500 range response Faraday raises `Faraday::ClientError`. [ It seems like breakers intends](https://github.com/department-of-veterans-affairs/breakers/blob/master/lib/breakers/uptime_middleware.rb#L58) to count any response in the 500-range, but [rescue block](https://github.com/department-of-veterans-affairs/breakers/blob/master/lib/breakers/uptime_middleware.rb#L85) doesn't include  `Faraday::ClientError`
we found this when [EVSS 500 errors in sentry ](http://sentry.vfs.va.gov/organizations/vsp/issues/466/?project=3&query=is%3Aunresolved+500&statsPeriod=14d) weren't being counted as errors in the [Backend service report](http://grafana.vfs.va.gov/d/000000050/backend-service-report?orgId=1)
department-of-veterans-affairs/va.gov-team#19394
There will likely be more external …

Breakers should consider 500 range errors outages

---

modules/mobile/app/controllers/mobile/v0/appointments_controller.rb
modules/mobile/spec/request/appointments_request_spec.rb

This is actually a bug in the upstream VAOS service but there's no timeline for them to fix it. This patch in our middleware will filter out any appointments not within the date range passed to out API endpoint.
department-of-veterans-affairs/va.gov-team#19361

Add a date range filter to mobile Community Care appointments

---

db/migrate/20210128150813_add_column_to_education_stem_automated_decisions.rb
db/schema.rb

Added the `encrypted_auth_headers_json_iv` column to the `education_stem_automated_decisions` table because the `_iv` column is required for the encrypted field to function correctly.
department-of-veterans-affairs/va.gov-team#18622
- Tested locally and QA reviewed.
- Used in https://github.com/department-of-veterans-affairs/vets-api/pull/5793

Add _iv column to education_stem_automated_decisions table

---

app/workers/education_form/send_school_certifying_officials_email.rb
config/features.yml
spec/jobs/education_form/send_school_certifying_officials_email_spec.rb

As a developer, I need to remove the stem_applicant_email feature flag toggle so that it is no longer configurable, and the new functionality is permanent.
[Originating Issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17551)

17551: Removal of stem_applicant_email feature flag

---

modules/appeals_api/spec/serializers/higher_level_review_serializer_spec.rb
modules/appeals_api/spec/serializers/notice_of_disagreement_serializer_spec.rb

This PR adds a spec for NODSerializer, to maintain parity between HLR/NOD. Currently HLR serializer is being tested, NOD is not.
[4704](https://vajira.max.gov/browse/API-4704)

Add NODSerializer spec to have parity with HLR

---

config/sidekiq_scheduler.yml
modules/appeals_api/app/mailers/appeals_api/decision_review_mailer.rb
modules/appeals_api/app/views/appeals_api/decision_review_mailer/mailer.html.erb
modules/appeals_api/app/workers/appeals_api/decision_review_report_daily.rb
modules/appeals_api/app/workers/appeals_api/decision_review_report_weekly.rb
modules/appeals_api/spec/mailers/decision_review_mailer_spec.rb
modules/appeals_api/spec/workers/decision_review_report_weekly_spec.rb

This PR adds a weekly report (same format/data points as the current daily email with the exception of adding `Daily`/`Weekly` to the subject and title) for reporting stats and errors on HLR and NOD. It renames the current daily email job to better differentiate between the daily and weekly email.
https://vajira.max.gov/browse/API-4807

Appeals api - weekly appeals report

---

lib/evss/letters/service.rb
spec/support/vcr_cassettes/evss/letters/letters_invalid_address.yml

Starting in april 2020,  EVSS stopped sending http 500 for validation errors. So, we need to rescue slightly differently.
department-of-veterans-affairs/va.gov-team#7701
department-of-veterans-affairs/va.gov-team#7816

evss no longer sends 500 for address error

---

modules/health_quest/app/controllers/health_quest/v0/questionnaire_manager_controller.rb
modules/health_quest/app/services/health_quest/questionnaire_manager/factory.rb
modules/health_quest/config/routes.rb
modules/health_quest/spec/request/questionnaire_manager_request_spec.rb
modules/health_quest/spec/services/questionnaire_manager/factory_spec.rb

- This PR establishes the QuestionnaireManager module which will ultimately return an aggregated data structure for the FE UI to consume
- This PR creates the basic structure of the questionnaire manager module and tests and invokes the Patient service
- The final response to the `/health_quest/v0/questionnaire_manager` route will be built over several PRs
- This PR invokes the Patient service only and returns a "Placeholder" hash for now
- Feature flip: show_healthcare_experience_questionnaire

Questionnaire Manager invoke patient service

---

modules/appeals_api/app/workers/appeals_api/higher_level_review_pdf_submit_job.rb
modules/appeals_api/app/workers/appeals_api/notice_of_disagreement_pdf_submit_job.rb
modules/appeals_api/spec/workers/higher_level_review_pdf_submit_job_spec.rb
modules/appeals_api/spec/workers/notice_of_disagreement_pdf_submit_job_spec.rb

[API-4763](https://vajira.max.gov/browse/API-4763)
We're not currently changing the status of an appeal unless the error thrown is an Upload error from Central Mail.
This changes the error handling pattern to capture _any_ error during the PDF submission, and update it's status accordingly.

Update Appeal status if error throws during PDF submit job

---

config/features.yml

Remove the flat facility feature flag because the VAOS application no longer calls on the flat facility flag names.

remove two of VAOS flat facility feature flags

---

.rubocop.yml
.rubocop_todo.yml
app/controllers/concerns/vet360/writeable.rb
app/models/form_profile.rb
app/models/form_profiles/va_686c674.rb
app/models/user.rb
app/models/va_profile_redis/cache.rb
app/models/va_profile_redis/contact_information.rb
config/redis.yml
spec/lib/common/models/concerns/cache_aside_spec.rb
spec/models/form_profile_spec.rb
spec/models/va_profile_redis/cache_spec.rb
spec/models/va_profile_redis/contact_information_spec.rb

rename `Vet360Redis` to `VAProfileRedis`
vet360 name is no longer in use and they want us to rename all references of vet360 to va_profile
all existing Vet360Redis caches will be invalidated, but it should just fetch data again and there shouldn't be any problems
https://github.com/department-of-veterans-affairs/va.gov-team/issues/19201

Rename Vet360Redis to VAProfileRedis

---

modules/health_quest/app/services/health_quest/questionnaire_manager/factory.rb
modules/health_quest/spec/request/questionnaire_manager_request_spec.rb
modules/health_quest/spec/services/questionnaire_manager/factory_spec.rb

- This PR invokes the health-quest AppointmentService via the QuestionnaireManager module and retrieves appointments for the signed-in Patient by a default date range.
- The final response to the /health_quest/v0/questionnaire_manager route will be built over several PRs.
- This PR returns a **placeholder** hash `{ data: 'WIP' }`  as the success response when the above route is called.
- Feature flip: show_healthcare_experience_questionnaire

Questionnaire Manager get appointments

---

db/schema.rb
modules/test_user_dashboard/db/migrate/20210203204200_add_account_types.rb

Adds new columns to store a test user accounts id_type, auth_type, and account_type information for filtering purposes.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/17208

adds id_type, auth_type, account_type columns to tud_accounts table

---

rakelib/form526.rake

Cleans up `print_total` function for BDD mode (removes colon and space). Switch to using ISO8601 styles dates for CSV output (to ensure that dates are lexicographically sortable and don't contain commas).

Minor Tweaks to Form526 Reports Rake Task

---

app/models/form_profiles/va_21p530.rb
spec/models/form_profile_spec.rb

Fixes `undefined method 'country' for nil:NilClass`
([sentry](http://sentry.vfs.va.gov/organizations/vsp/issues/17590/?query=is%3Aunresolved+InProgressFormsController&statsPeriod=14d))
(not sure which team this form belongs to)

Prevent Country Code Lookup When There's No Address Info (VA 21P530 Form Profile)

---

config/features.yml

Fixes: https://github.com/department-of-veterans-affairs/va.gov-team/issues/19395
Removing the `allow_online_10_10cg_submissions` feature toggle since it's no longer in use.
All references to this feature flip, in the UI, were removed in this pr: https://github.com/department-of-veterans-affairs/vets-website/pull/15625

remove toggle :allow_online_10_10cg_submissions

---

config/locales/exceptions.en.yml
lib/common/exceptions/detailed_schema_errors.rb
spec/fixtures/json/detailed_schema_errors_schema.json
spec/lib/common/exceptions/detailed_schema_errors_spec.rb

This PR adds support for the `const` keyword, as seen [here](https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.6.1.3) to the `DetailedSchemaErrors` class.
[API-4864](https://vajira.max.gov/browse/API-4864)

Add support for const keyword to DetailedSchemaErrors

---

app/controllers/concerns/sentry_controller_logging.rb
spec/controllers/application_controller_spec.rb
spec/lib/sidekiq/error_tag_spec.rb

Add a sentry tag with the front end app name for all reqests that have the  `Source-App-Name` header.  The Source-App-Name header should be present for all apps because of our [frontend to backend mapping stats](http://grafana.vfs.va.gov/d/zGS4XzkMk/backend-to-frontend-app-mapping?orgId=1)
I did an end to (almost) end test by making a call from vets-website, to vets-api and verifying that the tag was present in the sidekiq job to create a sentry issue. 
department-of-veterans-affairs/va.gov-team#7249

Add sentry tag for each app

---

modules/health_quest/app/services/health_quest/patient_generated_data/fhir_client.rb
modules/health_quest/app/services/health_quest/questionnaire_manager/factory.rb
modules/health_quest/app/services/health_quest/questionnaire_manager/transformer.rb
modules/health_quest/config/mock/appointments.yml
modules/health_quest/spec/request/questionnaire_manager_request_spec.rb
modules/health_quest/spec/services/questionnaire_manager/factory_spec.rb
modules/health_quest/spec/services/questionnaire_manager/transformer_spec.rb

- This PR invokes the health-quest Questionnaire service via the QuestionnaireManager module and retrieves questionnaires from the PGD
- The final response to the /health_quest/v0/questionnaire_manager route will be built over several PRs.
- This PR returns a placeholder hash { data: 'WIP' } as the success response when the above route is called.

Questionnaire Manager get PGD questionnaires

---

modules/mobile/app/models/mobile/v0/adapters/community_care_appointments.rb
modules/mobile/app/models/mobile/v0/adapters/va_appointments.rb
modules/mobile/app/services/mobile/v0/appointments/proxy.rb
modules/mobile/spec/request/appointments_request_spec.rb
modules/mobile/spec/support/vcr_cassettes/appointments/get_appointments_200_with_error.yml

The underlying VAOS VistA Scheduling Service can throw an error but have VAOS still return an empty result. Adds a VCR cassette and a spec for this case.
N/A

Handle VA appointment errors that include a partial response

---

modules/health_quest/app/services/health_quest/patient_generated_data/options_builder.rb
modules/health_quest/app/services/health_quest/questionnaire_manager/factory.rb
modules/health_quest/spec/request/questionnaire_manager_request_spec.rb
modules/health_quest/spec/request/questionnaires_request_spec.rb
modules/health_quest/spec/services/patient_generated_data/options_builder_spec.rb
modules/health_quest/spec/services/questionnaire_manager/factory_spec.rb

- This PR invokes the health-quest QuestionnaireResponse service via the QuestionnaireManager module and retrieves questionnaire responses from the PGD
- The final response to the /health_quest/v0/questionnaire_manager route will be built out in the next couple of PRs.
- This PR returns a placeholder hash { data: 'WIP' } as the success response when the above route is called.

19015 questionnaire manager questionnaire responses

---

modules/health_quest/app/services/health_quest/questionnaire_manager/factory.rb
modules/health_quest/spec/services/questionnaire_manager/factory_spec.rb

- This PR invokes the health-quest QuestionnaireResponse service via the QuestionnaireManager module and retrieves SIP(save in progress) data for the user/form from the vets-api PostgreSQL database.
- The final response to the /health_quest/v0/questionnaire_manager route will be built out in the next two PRs.
- This PR returns a placeholder hash { data: 'WIP' } as the success response when the above route is called.

Questionnaire Manager get SIP data

---

config/settings.yml
spec/mailers/spool10203_submissions_report_mailer_spec.rb

As an Education Services team member, I need reporting done on the number of 10203 submissions and denials each day, so that I can monitor the number of automated denials vs the total number of submissions.
a. robert.shinners@va.gov is included in the production report distribution
https://github.com/department-of-veterans-affairs/va.gov-team/issues/19333

19333: Add user to 10203 report

---

app/workers/evss/disability_compensation_form/submit_form526_cleanup.rb
app/workers/evss/disability_compensation_form/submit_uploads.rb
app/workers/evss/disability_compensation_form/upload_bdd_instructions.rb
lib/evss/error_middleware.rb
spec/lib/evss/error_middleware_spec.rb

Ensure that we are sending job exhausted metrics for Form526-related workers.
Also, add response body to sentry for EVSS errors.
department-of-veterans-affairs/va.gov-team#19568

Exhausted metrics for disability compensation

---

spec/lib/common/exceptions/detailed_schema_errors_spec.rb

Spec would fail when run on its own, but pass when in a collection. Using `rails_helper` instead of `spec_helper` included the missing pieces needed to run the spec file on its own.

Fix DetailedSchemaErrors when running individually

---

lib/bgs/service.rb

During 686 testing, BGS asked us to update the proc state type from `Manual` to `MANUAL_VAGOV` so they can see that VA.gov is the application that is setting the claim to manual. 
department-of-veterans-affairs/va.gov-team#19087
This is a very tiny PR that just changes one value, so no additional logging or configurations have been added.

Update Proc State Type Code for 686

---

app/controllers/concerns/sentry_controller_logging.rb
spec/controllers/application_controller_spec.rb

When I made #5866 I didn't know that the front end already had a called `source` for the same values.  I'm renaimg the BE tag to make it easier to search BE and FE errors together. 
department-of-veterans-affairs/va.gov-team#7249

rename sentry tag to source

---

lib/generators/module/templates/lib/namespace/engine.rb.erb

It was brought up in the #vsp-tools-be channel that some initialization code needs to be added to the module generator engine template to load factories automatically when running specs. This PR adds the code and the changes are confirmed as working when invoking the generator. 
department-of-veterans-affairs/va.gov-team#19647

add code for engine factory initializer

---

modules/health_quest/app/services/health_quest/questionnaire_manager/factory.rb
modules/health_quest/spec/services/questionnaire_manager/factory_spec.rb

- Obtain patient, questionnaire, questionnaire_response, and save_in_progress data in a multi-threaded fashion and cut down on the number of sequential http requests that we make to the PGD and vets-api; Helps cut down lag and improves overall performance.

19015 concurrent pgd and api calls

---

modules/appeals_api/config/schemas/200996.json

This PR updates our HLR schema to check supplied emails against the JSON schema draft 7 email format.
https://vajira.max.gov/browse/API-4822

Update HLR schema to check email against JSON API email spec

---

modules/appeals_api/app/models/appeals_api/notice_of_disagreement.rb
modules/appeals_api/config/schemas/10182.json
modules/appeals_api/spec/fixtures/invalid_10182.json
modules/appeals_api/spec/models/notice_of_disagreement_spec.rb
modules/appeals_api/spec/requests/v1/notice_of_disagreements_controller_spec.rb
spec/fixtures/json/detailed_schema_errors_schema.json
spec/lib/common/exceptions/detailed_schema_errors_spec.rb

A Veteran's address is dependent on whether they are experiencing homelessness
We were validating this on the model
This PR moves the validation from the model to json schema.
https://vajira.max.gov/browse/API-4816
Test removed from model spec and added to detailed_schema_errors_spec

Move model validation for address

---

config/sidekiq_scheduler.yml

Changed the FormReloader task to run from midnight ET to 2am ET. We are seeing Faraday timeout errors in CloudWatch and think we might have a timing issue conflicting with the CMS system.
https://vajira.max.gov/browse/API-4655
Tested locally and verified Cron syntax against crontab.guru

Changed forms loader job to 2AM ET from midnight

---

config/features.yml

Flag to display new field operationalHoursSpecialInstructions for VA facilities
https://github.com/department-of-veterans-affairs/va.gov-team/issues/19615
https://github.com/department-of-veterans-affairs/vets-website/pull/16004/files

Add new flag for operationalHoursSpecialInstructions on FL

---

app/workers/education_form/process10203_submissions.rb

Added a null check to the process10203_submissions job because have records in staging without `auth_headers` (this won't be true in prod)
department-of-veterans-affairs/va.gov-team#18622
- The STEM automated decision functionality is behind the stem_automated_decision feature flag.

10203 STEM Automated Decision - additional null check

---

modules/claims_api/app/swagger/claims_api/claims/claims_response_swagger.rb

Adds the following statuses to the `ClaimsShow` Swagger schema ::
- `pending`
- `errored`
[API-4737](https://vajira.max.gov/browse/API-4737)
The JSON output from http://localhost:3000/services/claims/docs/v1/api will now include the two new statuses.

[API-4737] - Add missing statuses to "ClaimsShow" Swagger schema

---

modules/claims_api/config/schemas/526.json

Linter caught this double value, removing one of them.

Remove double value of 'POW' in 526 specialIssues enum array

---

config/settings.yml

Adding a new PagerDuty service for the Health Care Questionnaire. Following the directions provided [here](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/downtime-notifications/)
Our app is not in production yet, so no users should be affected. 
[Github Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18237)

added pagerduty for health care questionnaire

---

modules/health_quest/app/services/health_quest/questionnaire_manager/factory.rb
modules/health_quest/app/services/health_quest/questionnaire_manager/transformer.rb
modules/health_quest/spec/request/questionnaire_manager_request_spec.rb
modules/health_quest/spec/services/questionnaire_manager/factory_spec.rb
modules/health_quest/spec/services/questionnaire_manager/transformer_spec.rb

- Questionnaire Manager now returns an aggregated set of data when the `/health_quest/v0/questionnaire_manager` route is invoked.
- The `transformer.rb` class is a bit heavy on the data structure and algorithms implementation and is intentionally imperative in style and design. We can think about abstracting some of the code away into newer classes if necessary but I feel that having the computation heavy pieces in one area will make the code easier to read and understand.

Questionnaire Manager must return aggregated data

---

spec/factories/lighthouse/facilities/lighthouse_facility.rb

A random thing I ran into, that probably only affects development?
I was getting a ruby class loading error when invoking a mobile API endpoint, related to Lighthouse::Facilities::Facility, and backtracing to the Lighthouse Facilities FactoryBot file. 
Our various rails engines (such as modules/mobile) append to the FactoryBot definition file paths, and this is seemingly causing an attempt to load classes referenced in factories.
(see for example modules/mobile/lib/mobile/engine.rb)
But for whatever reason the class (Lighthouse::Facilities::Facility) referenced in this factory was not  findable from the engine and was causing the classloading error. 
Changing this reference to a string (which is valid for FactoryBot) seems to clear up the issue. Maybe we should be doing that  across the …

Updates facilities factory to use string class reference to avoid class loading issue

---

rakelib/form526.rake

Running BDD stats is very slow as it must decrypt many submissions.

Allow Specifying a Date Range For BDD Stats Mode (form526 rake task)

---

README.md
modules/claims_api/app/swagger/claims_api/v0/claims_controller_swagger.rb
modules/claims_api/app/swagger/claims_api/v0/form_0966_controller_swagger.rb
modules/claims_api/app/swagger/claims_api/v0/form_2122_controller_swagger.rb
modules/claims_api/app/swagger/claims_api/v0/form_526_controller_swagger.rb
modules/claims_api/app/swagger/claims_api/v1/claims_controller_swagger.rb
modules/claims_api/app/swagger/claims_api/v1/form_0966_controller_swagger.rb
modules/claims_api/app/swagger/claims_api/v1/form_2122_controller_swagger.rb
modules/claims_api/app/swagger/claims_api/v1/form_526_controller_swagger.rb

There was confusion around the verbiage of "to fetch" for headers descriptions in a non-GET endpoint.
This has been changed to "being represented" to hopefully clear up any confusion.
https://vajira.max.gov/browse/API-2275
Viewed in the developer portal locally.

API-2275: Clarify Wording on Claims API headers documentation

---

README.md
modules/claims_api/app/swagger/claims_api/forms/form_2122_response_swagger.rb

Update possible status values for 2122 response schema in documentation.
https://vajira.max.gov/browse/API-4733
Viewed in developer portal locally.

API-4733: 2122 status schema is missing a possible status

---

modules/vaos/app/models/vaos/message_form.rb
modules/vaos/spec/models/message_form_spec.rb
modules/vaos/spec/request/messages_request_spec.rb

We removed validation for `message_text` in `appointment_request` model and instead made it a required field.
Tests were updated to reflect this change

18732 - removed message text length validation, and removed unnecessary tests

---

app/workers/cypress_viewport_updater/viewport_preset_js_file.rb

Add missing `\n` to end of rewritten `viewportPreset.js` file
All tests pass locally.
The `vets-website` files that are re-written by the Cypress Viewport Updater pass in Jenkins and Circle - https://github.com/department-of-veterans-affairs/vets-website/pull/16047

Add missing \n to end of rewritten viewportPreset.js file

---

app/models/user.rb
lib/saml/user_attributes/ssoe.rb
spec/factories/saml_attributes.rb
spec/factories/users.rb
spec/lib/saml/ssoe_user_spec.rb

Add parsing person_type from SSOe for use in User roles.
https://app.zenhub.com/workspaces/vsp-identity-5f5bab705a94c9001ba33734/issues/department-of-veterans-affairs/va.gov-team/19600

add person_types to SSOe parsing

---

app/models/iam_user.rb
app/models/iam_user_identity.rb
spec/factories/iam_introspection_responses.rb
spec/models/iam_user_identity_spec.rb

Adds MHV identifier to IAM user identity payload, for use in invoking MHV APIs. 
Also fixes LOA interpretation to match VA.gov's, so that DSLogon or MHV assurance level 2 will be interpreted as LOA3 for authorization purposes.

Updates IAM user model with MHV id, LOA fix

---

app/models/form526_submission.rb
spec/models/form526_submission_spec.rb

Working with (getting/setting) the BIRLS ID for a Form526Submission is difficult as it's stored as a field in `auth_headers_json`. (We will be manipulating the BIRLS ID more in [an upcoming PR.](https://github.com/department-of-veterans-affairs/vets-api/pull/5245/))

Add BIRLS ID Accessor Methods (Form526Submission)

---

modules/claims_api/app/controllers/claims_api/base_form_controller.rb
modules/claims_api/spec/requests/v0/intent_to_file_request_spec.rb

v0 does not have the concept of submitting a form 0966 on behalf of a veteran.
It doesn't make sense for a deceased veteran to submit an intent-to-file for their own burial.  
So when a v0 intent-to-file request with the `type` set as `"burial"` is received, forbid the request.
[API-4120](https://vajira.max.gov/browse/API-4120)

[API-4120] - Return error 403 when v0 intent-to-file type is 'burial'

---

config/redis.yml
config/settings.yml
modules/mobile/app/services/mobile/v0/messaging/client.rb
modules/mobile/app/services/mobile/v0/messaging/client_session.rb
modules/mobile/app/services/mobile/v0/messaging/configuration.rb
modules/mobile/spec/services/messaging_client_spec.rb

Adds a  mobile-app-specific MHV profile - i.e. a unique appToken configuration, and a separate session store to avoid userid collisions. 
~Note this is based on top of https://github.com/department-of-veterans-affairs/vets-api/pull/5929 which I expect to get merged first.~ Merged
- Adds a new settings.yml element for the  new mobile-specific MHV appToken.  
Planned test: Invoke SM API with configured staging appToken and verify difference  in MHV account activity logs.

Add mobile-specific SM backend integration profile

---

modules/mobile/app/controllers/mobile/messaging_controller.rb
modules/mobile/app/controllers/mobile/v0/folders_controller.rb
modules/mobile/app/controllers/mobile/v0/triage_teams_controller.rb
modules/mobile/app/helpers/mobile/routing.rb
modules/mobile/app/helpers/mobile/url_helper.rb
modules/mobile/app/serializers/mobile/v0/folder_serializer.rb
modules/mobile/app/serializers/mobile/v0/triage_team_serializer.rb
modules/mobile/config/routes.rb
modules/mobile/spec/request/folders_request_spec.rb
modules/mobile/spec/request/triage_teams_request_spec.rb
modules/mobile/spec/support/mobile_sm_client_helper.rb

Adds initial revision of mobile-specific secure messaging APIs - folders and triage teams and supporting code.
Mobile secure messaging APIs parts 1 and 2 of 3
(Splitting to avoid flagging by dangerbot)

Adds mobile messaging folders API

---

modules/mobile/app/models/mobile/v0/appointment.rb
modules/mobile/spec/models/appointment_spec.rb

Fixed a bug where ids with secondary appointment facility identifiers where not toggled correctly in staging because only the main clinic's id was being returned.
department-of-veterans-affairs/va.gov-team#14965

Mobile appointment address bug fix

---

lib/common/exceptions/detailed_schema_errors.rb
modules/appeals_api/app/models/appeals_api/notice_of_disagreement.rb
modules/appeals_api/config/schemas/10182.json
modules/appeals_api/spec/models/notice_of_disagreement_spec.rb
modules/appeals_api/spec/requests/v1/notice_of_disagreements_controller_spec.rb

If a veteran is experiencing homelessness, including an address is optional. However, CentralMail requires a 5-digit zip code from our request. We've refactored so that `zipCode5 => 00000` is sent via the request in cases of homelessness with no address. 
https://vajira.max.gov/browse/API-4832
`zipCode5 formatting` tested in model spec
`address presence if not experiencing homelessness` tested in controller spec

Refactor zipCode5 for zeros if homeless and no address

---

modules/test_user_dashboard/app/models/test_user_dashboard/tud_account.rb

Update to remove `standard` colum from `tud_accounts` table as we are dropping the standard vs. custom tud_accounts feature from the TUD MVP
https://github.com/department-of-veterans-affairs/va.gov-team/issues/17208

adds 'standard' as ignored_column in preparation for removal

---

config/settings.yml
config/settings/test.yml
modules/health_quest/app/services/health_quest/health_api/patient/factory.rb
modules/health_quest/app/services/health_quest/lighthouse/claims_token.rb
modules/health_quest/app/services/health_quest/lighthouse/session.rb
modules/health_quest/app/services/health_quest/lighthouse/token.rb
modules/health_quest/app/services/health_quest/patient_generated_data/questionnaire/factory.rb
modules/health_quest/app/services/health_quest/patient_generated_data/questionnaire_response/factory.rb
modules/health_quest/spec/services/health_api/patient/factory_spec.rb
modules/health_quest/spec/services/lighthouse/claims_token_spec.rb
modules/health_quest/spec/services/lighthouse/session_spec.rb
modules/health_quest/spec/services/lighthouse/token_spec.rb
modules/health_quest/spec/services/patient_generated_data/questionnaire/factory_spec.rb
modules/health_quest/spec/services/patient_generated_data/questionnaire_response/factory_spec.rb
modules/health_quest/spec/services/questionnaire_manager/factory_spec.rb

- The vets-api health-quest module will interact with two APIs in the Lighthouse: PGD and Health API.
- Health-quest module was already obtaining access_tokens from the PGD API and was getting and creating resources in that system.
- When Lighthouse introduced the new Health API, the health-quest module had to be modified to obtain access_tokens from this new service as well.
- In this PR, the vets-api health-quest module acquires the capability to fetch access_tokens from both the PGD and Health API services and hence have the authorization to make HTTP requests for resources from both Lighthouse services.
department-of-veterans-affairs/va.gov-team#19059

fetch access tokens from health and pgd api

---

modules/health_quest/app/services/health_quest/patient_generated_data/questionnaire_response/resource.rb
modules/health_quest/app/services/health_quest/shared/identity_meta_info.rb
modules/health_quest/spec/services/patient_generated_data/questionnaire_response/resource_spec.rb
modules/health_quest/spec/services/shared/identity_meta_info_spec.rb

- This PR implements the code which sets an `Appointments` reference URL in the Questionnaire Response's `subject` field and **also** sets the `Patient's` reference URL in the Questionnaire Response's `source` field.
- We're removing the code which was setting the `author` field since it's not a requirement by the Lighthouse PGD.
- The `questionnaire` field is being set directly as a string value instead of as a reference.
department-of-veterans-affairs/va.gov-team#19209

Add source and subject to questionnaire response

---

modules/health_quest/app/controllers/health_quest/v0/questionnaire_manager_controller.rb
modules/health_quest/app/controllers/health_quest/v0/questionnaire_responses_controller.rb
modules/health_quest/app/services/health_quest/patient_generated_data/questionnaire_response/map_query.rb
modules/health_quest/app/services/health_quest/questionnaire_manager/factory.rb
modules/health_quest/config/routes.rb
modules/health_quest/spec/request/questionnaire_manager_request_spec.rb
modules/health_quest/spec/request/questionnaire_responses_request_spec.rb
modules/health_quest/spec/services/questionnaire_manager/factory_spec.rb

-  This PR creates a new route, controller action, and a factory method for letting the UI(frontend) submit Questionnaire Response data to the vets-api health-quest module.
department-of-veterans-affairs/va.gov-team#19454

Post questionnaire response data

---

app/controllers/v0/disability_compensation_in_progress_forms_controller.rb

rather than checking if a veteran has seen the rated disabilities page, check if they have selected any rated disabilities for increase before sending them back to that page if the list has updated.
department-of-veterans-affairs/va.gov-team#18681

form526: updated rated disabilities location

---

modules/health_quest/app/services/health_quest/patient_generated_data/questionnaire/factory.rb
modules/health_quest/app/services/health_quest/patient_generated_data/questionnaire_response/factory.rb
modules/health_quest/app/services/health_quest/shared/options_builder.rb
modules/health_quest/spec/services/patient_generated_data/questionnaire/factory_spec.rb
modules/health_quest/spec/services/patient_generated_data/questionnaire_response/factory_spec.rb
modules/health_quest/spec/services/shared/options_builder_spec.rb

- This pr moves the `options_builder.rb` class from inside the `patient_generated_data` folder into the `shared` folder. This way, services created within the `health_api` folder can also share the functionality provided by the `options_builder.rb` class: Build and return search parameters for either the Lighthouse `PGD` or `Health API`
department-of-veterans-affairs/va.gov-team#19656

move options_builder to shared folder

---

lib/apps/client.rb
spec/lib/apps/client_spec.rb
spec/support/vcr_cassettes/apps/200_apple_health_query.yml

Originally the `get_app` method used `URI.escape` to handle a `search_term` with whitespace in it (IE: 'Apple Health'). Rubocop throws a deprecation error for `URI.escape` and suggests using `CGI.escape`. The test written for `get_app` used `iBlueButton` as the `search_term`, and therefor didn't catch the issue when replacing `URI.escape` with `CGI.escape`. When passing a `search_term` with whitespace in it , IE: `"Apple Health"`, `CGI.escape` parses that as "Apple+Health" instead of "Apple%20Health" as `URI.escape` did.
The method now uses `ERB::Util.url_encode`, which works as expected, and a test has been included to ensure it parses whitespace correctly.

Hotfix for lib/apps/client.rb#get_app

---

modules/health_quest/app/services/health_quest/patient_generated_data/questionnaire_response/resource.rb
modules/health_quest/spec/services/patient_generated_data/questionnaire_response/resource_spec.rb

- Questionnaire Response FHIR objects need to be created with `subject` and `source` fields set as `reference`s. This is a FHIR protocol requirement.
department-of-veterans-affairs/va.gov-team#19053

set subject and source as references

---

config/features.yml

As a developer, I need to remove the 'gibctBenefitFilterEnhancement' feature flag toggle and related functionality so that dead code is no longer in the codebase.
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/13364
Frontend PR: https://github.com/department-of-veterans-affairs/vets-website/pull/16112
local testing

Removed gibctBenefitFilterEnhancement from features.yml

---

modules/appeals_api/app/workers/appeals_api/higher_level_review_pdf_submit_job.rb
modules/appeals_api/app/workers/appeals_api/notice_of_disagreement_pdf_submit_job.rb

CentralMail expects its `receiveDt` to be in Central timezone. This fixes the bug where we were sending the date in UTC instead of Central timezone.
https://vajira.max.gov/browse/API-5366

[Bugfix] Send CentralMail receiveDt in central timezone

---

Dangerfile

Change to dangerfile to exclude mobile cassette directory from change limit
N/A
Should help us have to split PRs up less due to length of some cassettes

added mobile vcr directory to exclude list

---

Gemfile.lock
app/uploaders/evss_claim_document_uploader.rb
app/uploaders/hca_attachment_uploader.rb
app/uploaders/preneed_attachment_uploader.rb
app/uploaders/profile_photo_attachment_uploader.rb
app/uploaders/supporting_documentation_attachment_uploader.rb
app/uploaders/supporting_evidence_attachment_uploader.rb
config/locales/en.yml
spec/request/upload_supporting_evidence_spec.rb
spec/uploaders/supporting_documentation_attachment_uploader_spec.rb
spec/uploaders/supporting_evidence_attachment_uploader_spec.rb

upgrade carrierwave gem. [changelog](https://github.com/carrierwaveuploader/carrierwave/blob/master/CHANGELOG.md#220---2021-02-23) includes several bug fixes and a few deprecated method names.

upgrade carrierwave

---

modules/vaos/app/controllers/vaos/v0/appointments_controller.rb
modules/vaos/app/services/vaos/appointment_service.rb
modules/vaos/spec/request/appointments_request_spec.rb
spec/support/schemas/vaos/cc_appointments.json
spec/support/schemas/vaos/va_appointments.json
spec/support/schemas_camelized/vaos/cc_appointments.json
spec/support/schemas_camelized/vaos/va_appointments.json

Add errors partial to meta. Updates schema definitions for both va_appointments and cc_appointments schemas. Will always include an errors array even when no elements in the array. When errors are present http status will become 207 Multi Status, essentially successful with partial errors. 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/20483

Handle partial results returned from MAS; Fixes #20483

---

modules/appeals_api/app/mailers/appeals_api/decision_review_mailer.rb
modules/appeals_api/app/workers/appeals_api/daily_error_report.rb
modules/appeals_api/app/workers/appeals_api/decision_review_report_daily.rb
modules/appeals_api/app/workers/appeals_api/decision_review_report_weekly.rb

Removes old setting that were needed for backwards compatibility while devops was being updated.
https://vajira.max.gov/browse/API-4997

API-4997 - remove old settings

---

modules/health_quest/app/controllers/health_quest/v0/lighthouse_appointments_controller.rb
modules/health_quest/app/services/health_quest/health_api/appointment/factory.rb
modules/health_quest/app/services/health_quest/health_api/appointment/map_query.rb
modules/health_quest/app/services/health_quest/shared/options_builder.rb
modules/health_quest/spec/request/lighthouse_appointments_request_spec.rb
modules/health_quest/spec/services/health_api/appointment/factory_spec.rb
modules/health_quest/spec/services/health_api/appointment/map_query_spec.rb
modules/health_quest/spec/services/shared/options_builder_spec.rb

- This PR provides the `health-quest` module the ability to fetch a list of `appointments` for a `patient` from the `Lighthouse Health API`.
department-of-veterans-affairs/va.gov-team#19656

Fetch appointments from lighthouse

---

modules/appeals_api/app/swagger/appeals_api/v1/responses_contestable_issues.json

Our documentation needs to account for contestable issues, lastestIssuesInChain IDs as integers in addition to the already expected string type.
**Ticket**
https://vajira.max.gov/browse/API-5455

Add integer type to latestIssuesInChain

---

modules/health_quest/app/controllers/health_quest/v0/lighthouse_appointments_controller.rb
modules/health_quest/app/services/health_quest/health_api/appointment/factory.rb
modules/health_quest/app/services/health_quest/health_api/appointment/map_query.rb
modules/health_quest/spec/request/lighthouse_appointments_request_spec.rb
modules/health_quest/spec/services/health_api/appointment/factory_spec.rb
modules/health_quest/spec/services/health_api/appointment/map_query_spec.rb

- This PR gives the health-quest module the ability to fetch a single appointment resource by its ID from the Lighthouse Health API.
department-of-veterans-affairs/va.gov-team#19656

19656 get lighthouse appointment

---

modules/claims_api/app/controllers/claims_api/v0/forms/power_of_attorney_controller.rb
modules/claims_api/app/swagger/claims_api/v0/form_2122_controller_swagger.rb
modules/claims_api/spec/requests/v0/power_of_attorney_request_spec.rb

In `/claims/v0/forms/2122/active` and `/claims/v0/forms/2122/{id}/status`, it's possible that a Power of Attorney (POA) cannot be found.  When that happens, we need to return a 404 rather than allowing the code to blow up and return a 500.
[API-5338](https://vajira.max.gov/browse/API-5338)

API-5338 - Provide better error when v0 form2122 endpoints can't find POA

---

modules/claims_api/app/controllers/claims_api/v1/forms/disability_compensation_controller.rb
modules/claims_api/app/controllers/claims_api/v1/forms/intent_to_file_controller.rb
modules/claims_api/app/controllers/claims_api/v1/forms/power_of_attorney_controller.rb
modules/claims_api/spec/requests/v1/disability_compensation_request_spec.rb
modules/claims_api/spec/requests/v1/intent_to_file_request_spec.rb
modules/claims_api/spec/requests/v1/power_of_attorney_request_spec.rb

Allow the `ClaimsAPI` `Form` "schema" endpoints (see below) to be accessed without authentication.
- `GET /services/claims/v1/forms/526`
- `GET /services/claims/v1/forms/0966`
- `GET /services/claims/v1/forms/2122`
[API-4808](https://vajira.max.gov/browse/API-4808)

[API-4808] - Do not require auth for claims api schema endpoints

---

config/features.yml

Form 526 contains subforms 8940 and 4192 which are currently only visible in a non-production environment. Adding feature flags to enable a future rollout.
Also added `enable_in_development` settings for various forms we support.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/13848
* Adding 8940 & 4192 combined feature flag
* Adding `enable_in_development` settings for existing form 526 & 996 features

Feature flags for 526 subforms

---

app/models/form526_submission.rb
spec/models/form526_submission_spec.rb

Veterans sometimes have multiple BIRLS IDs, but, currently, we only try the first one returned. This PR tweaks Form526Submission model to keep track of which BIRLS IDs have been tried so far when trying to submit to EVSS.
The column in the DB is already set up (encrypted string for storing JSON).
An example of the shape of `birls_ids_tried`:
```
{
'111' => ['2021-01-01T0000Z'], # a tried BIRLS ID
'222' => [],  # an untried BIRLS ID
'333' => []   # an untried BIRLS ID
}
```
--a hash where the keys are the BIRLS ID and the values are arrays of timestamps which record when that BIRLS ID was used for a submit job.
Manually manipulating this data structure is cumbersome and error-prone. This PR introduces methods for working with the `birls_ids_tried` column.

Add `birls_ids_tried` Helper Methods to Form526Submission Model

---

db/schema.rb
modules/appeals_api/db/migrate/20210225160010_create_evidence_submission.rb

This PR is the migration for `AppealsApi::EvidenceSubmission`, which we will use to track the status of supporting evidence uploads for both NoticeOfDisagreement appeals and SupplementalClaims (eventually).
Epic Link: [4117-Evidence-Submission](https://vajira.max.gov/browse/API-4117)

Add AppealsApi::EvidenceSubmission

---

spec/jobs/cypress_viewport_updater/viewport_spec.rb

While working on [this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/5997), I hit [a failing spec](https://github.com/department-of-veterans-affairs/vets-api/pull/5997/files#diff-538bb209a64e00cdefa341e0341fb6d8a97e0c1f83c4d5c6bbf617557b2c93ebL69).
Being in a hurry and considering it was a static string already, I changed the dates with the intent to make a more permanent solution in a separate PR. @bosawt HMU on slack asking about it and this is the PR from that conversation.
Trevor suggested `Timecop.freeze(Time.zone.parse('2021-03-01')` but I couldn't get that to work.
I'm not _wild_ about my solution. Seems to just do what the code is doing that it's supposed to test. I added another expectation as another option.
No issue for this
* Are there additions to a …

Permanent fix viewport spec

---

lib/sm/client.rb
lib/sm/configuration.rb

Secure Messaging `POST` requests that include a body such as sending a message and replying to a message were not being sent correctly because args were being passed as `ActionController:Parameters` instead of hashes.
department-of-veterans-affairs/va.gov-team#20189
May need additional changes to support file uploads

Fix Secure Messaging POSTs

---

app/models/form526_submission.rb
app/workers/form526_confirmation_email_job.rb
spec/jobs/form526_confirmation_email_job_spec.rb
spec/models/form526_submission_spec.rb

Adding `first_name` to personalization parameters to send form526 confirmation email job. Upon successful addition of this parameter, will create a separate PR to remove full_name from personalization parameters in order to be HIPPA compliant.
department-of-veterans-affairs/notification-api#357
* This is part of existing feature flag "form526_confirmation_email", which is currently enabled in production.
* Motivation for this change is to be HIPPA compliant. Upon successful addition of first_name parameters, will create separate PR to remove full_name from personalization parameters to email confirmation job.
* Made modifications to respective unit and integration tests.

[#357] Add first name to personalization params for Form526ConfirmationEmailJob

---

modules/claims_api/app/controllers/claims_api/v1/forms/disability_compensation_controller.rb
modules/claims_api/spec/requests/v1/disability_compensation_request_spec.rb

Copy/paste mistake introduced a 500 response when uploading supporting documents for a 526 submission.
https://vajira.max.gov/browse/API-5512
Ensured tests were failing before implementing the fix.

API-5512: 500 response for 526 uploading supporting documents in sandbox

---

modules/veteran_verification/VETERAN_VERIFICATION.yml

Specifying in the documentation that service history endpoint returns an array of ServiceHistoryEpisode objects. Adding 401 unauthorizes status code response to all veteran verification endpoints. 
https://vajira.max.gov/browse/API-5382
Veteran Verification swagger docs were updated.
Verified that the documentation was parsing and displaying correctly in the editor.swagger.io webpage.

API-5382 Return service history as array type, add 401 status code

---

spec/service_consumers/pact_helper.rb

This PR renames the vet360 directory to va_profile. This was renamed recently and was breaking the pact verification

Rename directory to va_profile

---

modules/health_quest/app/controllers/health_quest/v0/organizations_controller.rb
modules/health_quest/app/services/health_quest/shared/options_builder.rb
modules/health_quest/config/routes.rb
modules/health_quest/spec/request/organizations_request_spec.rb
modules/health_quest/spec/services/shared/options_builder_spec.rb

- This PR provides the health-quest module the ability to fetch `Organization` resources from the Lighthouse Health API.

fetch organizations from lighthouse

---

app/models/form526_submission.rb
app/workers/form526_confirmation_email_job.rb
spec/jobs/form526_confirmation_email_job_spec.rb
spec/models/form526_submission_spec.rb

This is a follow-up change to remove `full_name` from personalization parameters for the form526ez confirmation email. We've successfully incorporated `first_name` recently. These changes are meant to be HIPPA compliant.
department-of-veterans-affairs/notification-api#357
This is part of existing feature flag "form526_confirmation_email", which is currently enabled in production.
Motivation for this change is to be HIPPA compliant. Had recently successfully added `first_name` to personalization parameters and updated template accordingly on the notification-api end in prod. Therefore we are ready to now remove `full_name` from personalization parameters to the form526ez email confirmation job.
* Made modifications to respective unit and integration tests.
* Have already manually tested …

[notification-api#357] Remove full name from personalization param for form526ez confirmation email

---

spec/lib/generators/module_component/module_components_generator_spec.rb

Fixing module_components_generator_spec to prevent user prompt if tests are run out of order
This fixes an issue with module_components_generator_spec that would generate a user prompt asking to overwrite modules/foo/app/services/foo/v0/configuration.rb if the tests happen to run out of order.

Fixing spec to prevent user prompt

---

app/controllers/v0/disability_compensation_in_progress_forms_controller.rb
spec/request/v0/disability_compensation_in_progress_forms_controller_request_spec.rb

After a disuccion with @Mottie we settled on adding a `updatedRatedDisabilities` element to the form rather than replacing `ratedDisabilities` and adding something to the metadata.  This controller is not yet used in prod. 
department-of-veterans-affairs/va.gov-team#18681

updated rated disablities

---

Gemfile
Gemfile.lock
modules/identity/Gemfile
modules/identity/README.rdoc
modules/identity/Rakefile
modules/identity/bin/rails
modules/identity/config/routes.rb
modules/identity/identity.gemspec
modules/identity/lib/identity.rb
modules/identity/lib/identity/engine.rb
modules/identity/lib/identity/version.rb
modules/identity/spec/spec_helper.rb
spec/simplecov_helper.rb
spec/spec_helper.rb

Use vtk to create new identity module for code refactors and consolidation
Identity team is implementing a consistent interface to Identity / Sessions / MPI information.

New identity module

---

app/controllers/v0/letters_controller.rb
app/policies/evss_policy.rb
app/swagger/swagger/requests/letters.rb
spec/request/swagger_spec.rb

A veteran must have an address available to EVSS before we can make a call to the letters api or [we see an error](http://sentry.vfs.va.gov/organizations/vsp/issues/6135/?query=source%3Aletters&statsPeriod=14d).  
In a roundabout way, if we see there is an address in Va Profile then we know that EVSS can get the address. 
department-of-veterans-affairs/va.gov-team#7816

veteran must have an address in order to make an evss letters call

---

config/sidekiq_scheduler.yml

Reports were coming in the previous day that were supposed to be sent the following - e.g. On Sunday we would receive Monday's email, since midnight+1second UTC is technically Monday even though after timezone adjustments the email would get sent out Sunday night for anywhere with a negative UTC offset.
This adjust the time the job is scheduled to be at the end of the desired day rather than beginning by technicality.

Adjust AppealsAPI Job Schedules

---

app/controllers/v0/higher_level_reviews/contestable_issues_controller.rb
app/controllers/v0/higher_level_reviews_controller.rb
spec/request/v0/higher_level_reviews_controller_request_spec.rb

resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/21302
We weren't saving the exception's class name in the `error_class` field when creating a `PersonalInfomationLog`. Adding it to aid in debugging.

Add Exception's Class Name to PII Log `error_class` Field (HLR)

---

spec/jobs/cypress_viewport_updater/viewport_spec.rb

There's been a flapping spec related to dates/times. To make the dates more permanent, this PR adds a Timecop.freeze to the spec. This spec tends to randomly fail in CI based on the random test run ordering.  
Link to [slack conversation](https://dsva.slack.com/archives/CBU0KDSB1/p1615385008425700)

add timecop freeze and return

---

config/sidekiq_scheduler.yml

Sidekiq scheduler reads previous config as invalid cron. Switching to simpler "every 12 hours" configuration
https://vajira.max.gov/browse/API-5477

invalid cron

---

modules/health_quest/app/services/health_quest/questionnaire_manager/factory.rb
modules/health_quest/app/services/health_quest/shared/options_builder.rb
modules/health_quest/spec/services/questionnaire_manager/factory_spec.rb

- PR series: #6120
- Adding the ability for the Questionnaire Response Factory to fetch locations from the Lighthouse.
- Note that we're still fetching appointments from the MAP/MAS service. This ability will be removed once the rest of the code has been added to the Questionnaire Manager and other classes. The reason for keeping the MAP appointments around, for the time being, is so that the tests don't break if they get removed and we don't end up going on a large refactoring spree!

adding ability to get location resources

---

modules/health_quest/app/services/health_quest/questionnaire_manager/factory.rb
modules/health_quest/app/services/health_quest/questionnaire_manager/factory_types.rb
modules/health_quest/spec/services/questionnaire_manager/factory_spec.rb
modules/health_quest/spec/services/questionnaire_manager/factory_types_spec.rb

- PR series: #6120, #6127
- Adding the ability for the Questionnaire Manager Factory to fetch Organizations from the Lighthouse.
- Note that we're still fetching appointments from the MAP/MAS service. The MAP/MAS appointment code will be removed from the Questionniare Manager Factory in the next PR.

Adding ability to fetch organizations

---

modules/claims_api/app/controllers/claims_api/v1/forms/power_of_attorney_controller.rb
modules/claims_api/app/swagger/claims_api/forms/form_2122_response_swagger.rb
modules/claims_api/app/swagger/claims_api/v0/form_2122_controller_swagger.rb
modules/claims_api/app/swagger/claims_api/v1/form_2122_controller_swagger.rb
modules/claims_api/spec/requests/v1/power_of_attorney_request_spec.rb

Make the `v1 ​GET /forms​/2122​/active` endpoint return a 404 if there is not a Lighthouse POA submission.  If there is a Lighthouse POA submission, return it, but also check BGS to see if it has a POA.  If BGS, does have a POA, set the `previous_poa` attribute to the value of the BGS POA, else `previous_poa` attribute will be `null`.
[API-5517](https://vajira.max.gov/browse/API-5517)

[API-5517] - Attempt to make from2122 active endpoints less confusing

---

modules/mobile/app/controllers/mobile/v0/messages_controller.rb

Updates the mobile messaging controller to handle posting messages with/without attachments. 
A message with attachments gets sent as a `multipart/form-data`, and current implementation of ActionController::Parameters treats the JSON payload in a multipart payload as a String instead of parsing it into a Hash. So we coerce that into an object that we can do strong parameter validation on. 
Then also turn Parameters objects into Hashes before passing to the SM client. 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/20750
Tested locally to make sure eventual payload to SM client was correct in all cases.

Pv sm attachment fix

---

modules/appeals_api/app/workers/appeals_api/decision_review_report_daily.rb
modules/appeals_api/app/workers/appeals_api/decision_review_report_weekly.rb
modules/appeals_api/spec/workers/decision_review_report_daily_spec.rb
modules/appeals_api/spec/workers/decision_review_report_weekly_spec.rb

Having a daily or weekly report retry for 21 days doesn't really make a whole lot of sense. This PR adjusts the retry count to be more sensible for each report type.
It also makes sure that the start time of the reports is less dependent on the runtime of the job, setting itself to the beginning of the day the job is ran to avoid missing something as the retries get longer and longer.
https://vajira.max.gov/browse/API-5651

API-5651 Adjust retry attempts for email report jobs

---

db/schema.rb
modules/appeals_api/db/migrate/20210309193554_add_meta_data_to_evidence_submissions.rb

This PR adds a column called `file_data` to the EvidenceSubmission model for AppealsApi.
related issue: [API-5224](https://vajira.max.gov/browse/API-5224)

add encrypted file data to evidence_submissions

---

modules/health_quest/app/services/health_quest/questionnaire_manager/organization_formatter.rb
modules/health_quest/app/services/health_quest/questionnaire_manager/resource_hash_id_formatter.rb
modules/health_quest/app/services/health_quest/questionnaire_manager/transformer.rb
modules/health_quest/spec/services/questionnaire_manager/organization_formatter_spec.rb
modules/health_quest/spec/services/questionnaire_manager/resource_hash_id_formatter_spec.rb

- PR series: #6120, #6127, #6130, #6142
- Adding the formatter for creating a hash of locations by their ids
- Adding the formatter for creating a hash of organizations by location ids
- Adding the helper methods to the Transformer class
- Adding relevant specs

20248 formatters for organization and general resources

---

modules/va_forms/db/migrate/20200817140442_add_form_details_url_to_va_forms.rb

_for any poor soul who does `db:drop` then `db:migrate` (or clones vets-api for the first time and does a `db:migrate`)..._
I think this migration just got overlooked by the zeitwerk / inflection PRs.
When loading `modules/va_forms/db/migrate/20200817140442_add_form_details_url_to_va_forms.rb`, Rails predicts that the class will be named `AddFormDetailsUrlToVAForms` (capital VA) not `AddFormDetailsUrlToVaForms` (like the migration has).
The relevant code in active record:
```
def migrations
migrations = migration_files.map do |file|
version, name, scope = parse_migration_filename(file)
raise IllegalMigrationNameError.new(file) unless version
version = version.to_i
name = name.camelize 
MigrationProxy.new(name, version, file, scope)
end
``` …

Inflection Fix - Old-style Inflection in va_forms Migration

---

modules/appeals_api/app/controllers/appeals_api/v1/decision_reviews/notice_of_disagreements/evidence_submissions_controller.rb
modules/appeals_api/config/routes.rb
modules/appeals_api/spec/requests/v1/notice_of_disagreements/evidence_submissions_controller_spec.rb

Adding basic NOD evidence submission upload endpoint
It should:
- take in a document and uuid
- validate document
- return meaningful response if document is invalid
Ticket
https://vajira.max.gov/browse/API-5221

Add basic upload endpoint

---

app/models/saved_claim/education_benefits/va_10203.rb
app/workers/education_form/create10203_applicant_decision_letters.rb
app/workers/education_form/create10203_spool_submissions_report.rb
app/workers/education_form/process10203_submissions.rb
config/sidekiq_scheduler.yml
spec/jobs/education_form/create10203_applicant_decision_letters_spec.rb
spec/jobs/education_form/create10203_spool_submissions_report_spec.rb
spec/jobs/education_form/process10203_submissions_spec.rb
spec/models/saved_claim/education_benefits/va10203_spec.rb

Removed feature flag check around automated processing of 10203 STEM claims.  The creation of `education_stem_automated_decision` records is still be behind the feature flag, so the job will only be processing claims from UAT next week.
Updated frequency of `EducationForm::Process10203Submissions` job to run every 2 minutes.  This change will be reverted after UAT testing

Removed feature flag for 10203 processing

---

modules/mobile/app/controllers/mobile/v0/claims_and_appeals_controller.rb
modules/mobile/app/services/mobile/v0/claims/proxy.rb

Created to get the line count down for https://github.com/department-of-veterans-affairs/vets-api/pull/6089
Moves claims and appeals logic in the controller to a proxy that sits between it and the service so that a background worker can also use the proxy to pre-cache claims and appeals data for a user.
department-of-veterans-affairs/va.gov-team#19464

19464 create mobile claims proxy (pre-req for caching in worker)

---

app/controllers/openid_application_controller.rb
spec/controllers/openid_application_controller_spec.rb

In preparation for SSOi and SSOe access tokens usage with the Lighthouse API's, this adds a small foundation for detecting those non-JWT tokens prior to the Token.rb instantiation which relies on JWT access token structure.
https://vajira.max.gov/browse/API-5576
* This is a first step PR only to gracefully handle SSOi & SSOe opaque tokens rather than stack trace errors on JWT decode failures.
* Future additions will add support for introspect calls, scope validation, etc.

Added catch for opaque tokens.

---

app/controllers/concerns/failed_request_loggable.rb

Adding [these methods](https://github.com/department-of-veterans-affairs/vets-api/pull/6159/commits/096e99f3cc4db78df4ccc1d1f2cf0555b880b2e8#diff-e49eb6621cc44ba8b5d20efbd30dd4a10ea4332ce02b746d05ead7a355011d81R10) to `exception_hash` (hard to see in final rubocopping)

Add Some More Introspection Methods to exception_hash (FailedRequestLoggable)

---

config/features.yml

This pull request adds a new feature toggle to vets-api for dependency verification services
department-of-veterans-affairs/va.gov-team#20291

add dependency verification feature toggle to vets-api

---

modules/health_quest/app/services/health_quest/questionnaire_manager/basic_questionnaire_manager_formatter.rb
modules/health_quest/app/services/health_quest/questionnaire_manager/questionnaire_response_collector.rb
modules/health_quest/app/services/health_quest/questionnaire_manager/questionnaire_responses_formatter.rb
modules/health_quest/app/services/health_quest/questionnaire_manager/save_in_progress_collector.rb
modules/health_quest/app/services/health_quest/questionnaire_manager/transformer.rb
modules/health_quest/spec/services/questionnaire_manager/basic_questionnaire_manager_formatter_spec.rb
modules/health_quest/spec/services/questionnaire_manager/questionnaire_response_collector_spec.rb
modules/health_quest/spec/services/questionnaire_manager/questionnaire_responses_formatter_spec.rb
modules/health_quest/spec/services/questionnaire_manager/save_in_progress_collector_spec.rb
modules/health_quest/spec/services/questionnaire_manager/transformer_spec.rb

- PR series: #6120, #6127, #6130, #6142, #6154, #6167
- Pass appointments, locations, and organizations to the Transformer
- Build the basic questionnaire manager data structure using the new Lighthouse data

20248 initial lighthouse data aggregation

---

modules/claims_api/app/workers/claims_api/claim_establisher.rb
modules/claims_api/app/workers/claims_api/special_issue_updater.rb
modules/claims_api/spec/workers/flash_updater_spec.rb
modules/claims_api/spec/workers/special_issue_updater_spec.rb

Switches the ClaimsAPI SpecialIssuesUpdater worker to require simple arguments. This should prevent the problems that occur when marshalling/unmarshalling complex JSON objects into and out of REDIS.
[API-5536](https://vajira.max.gov/browse/API-5536)

[API-5536] - Update SpecialIssueUpdater worker to use simple arguments

---

modules/mobile/spec/models/adapters/va_appointments_adapter_spec.rb
modules/mobile/spec/support/fixtures/va_appointments_missing_status.json

Adds Timecop before and after hooks to a time based spec for the mobile appointments status field.
N/A

Fix mobile appointments hidden status spec

---

modules/health_quest/app/services/health_quest/questionnaire_manager/factory.rb
modules/health_quest/app/services/health_quest/questionnaire_manager/responses_group.rb
modules/health_quest/app/services/health_quest/resource/client_model/questionnaire_response.rb
modules/health_quest/spec/services/questionnaire_manager/factory_spec.rb
modules/health_quest/spec/services/questionnaire_manager/responses_group_spec.rb
modules/health_quest/spec/services/resource/client_model/questionnaire_response_spec.rb

- PR series: #6120, #6127, #6130, #6142, #6154, #6167, #6168
- Process lighthouse data passed into the Transformer class
- Combine the processed data and return the aggregate to the Factory

20248 final lighthouse appointment integration

---

lib/common/models/collection.rb
spec/request/folders_request_spec.rb

Checks for out-of-bounds pagination parameter and generates a 400
response instead of a 500 internal server error
While validating that the secure messaging API pagination was working correctly, I idly tested with an out-of-bounds `page` parameter and got a 500. This PR adds a check for the `out_of_bounds?` accessor in the pagination library and returns a more helpful 400. 
There are probably other invalid pagination parameters like negative numbers, etc, that are not covered, but this is a small iterative improvement, and I could see a client accidentally walking past the end of the pages more easily than some other errors.  
https://github.com/department-of-veterans-affairs/va.gov-team/issues/21454

Generates 400 error on out-of-bounds pagination

---

lib/evss/disability_compensation_auth_headers.rb
modules/health_quest/app/services/health_quest/jwt_wrapper.rb
modules/vaos/app/models/vaos/appointment_form.rb
modules/vaos/app/models/vaos/appointment_request_form.rb
modules/vaos/app/services/vaos/jwt_wrapper.rb

Further refactoring of the User model to internally handle requests for identity information, this change takes out most `user.mpi` calls that occur outside of the model. This should not result in no noticeable change with the exception of instances when the cached SAML payload's information differs from MPI's, since the User model defaults to using the SAML payload's information over MPI.
department-of-veterans-affairs/va.gov-team#5411
Existing unit tests continue to pass and cover User model methods replacing User.mpi calls

Remove most direct user.mpi calls [#5411]

---

config/locales/exceptions.en.yml

Adds additional exception mappings based on version 2.5 of the MHV API docs: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/secure-messaging/mhv-api/Secure_Messaging_API_Veteran_2.5.doc
Also removes some duplicates I found for non-SM errors.
department-of-veterans-affairs/va.gov-team#20770

Add missing Secure Messaging exceptions

---

config/initializers/sidekiq.rb
config/settings.yml
lib/sidekiq/monitored_worker.rb
lib/sidekiq/retry_monitoring.rb
lib/sidekiq/retry_monitoring/monitored_worker.rb
modules/appeals_api/app/workers/appeals_api/higher_level_review_pdf_submit_job.rb
modules/appeals_api/app/workers/appeals_api/higher_level_review_upload_status_updater.rb
modules/appeals_api/app/workers/appeals_api/notice_of_disagreement_pdf_submit_job.rb
modules/appeals_api/app/workers/appeals_api/notice_of_disagreement_upload_status_updater.rb
modules/appeals_api/lib/appeals_api/sidekiq_retry_notifier.rb
modules/appeals_api/spec/lib/sidekiq_retry_notifier_spec.rb
modules/appeals_api/spec/support/shared_examples_for_monitored_worker.rb
modules/appeals_api/spec/workers/higher_level_review_pdf_submit_job_spec.rb
modules/appeals_api/spec/workers/higher_level_review_upload_status_updater_spec.rb
modules/appeals_api/spec/workers/notice_of_disagreement_pdf_submit_job_spec.rb
modules/appeals_api/spec/workers/notice_of_disagreement_upload_status_updater_spec.rb
spec/lib/sidekiq/retry_monitoring_spec.rb

[API-4765](https://vajira.max.gov/browse/API-4765)
This PR adds sidekiq middleware to handle sidekiq job retry threshold notfiications. When a monitored worker hits a designated retry limit, a notify callback will be called within that monitored worker. 
AppealsAPI makes use of a Slack incoming webhook to post this retry warning directly to slack.
This will be unit tested with shared examples for each monitored worker, testing that the interface called by the middleware is defined.
This PR will add middleware to ALL sidekiq jobs, but will only "work" if the included `Sidekiq::MonitoredWorker` is included.

Api 4765/add slack notification for sidekiq retries

---

modules/veteran_verification/VETERAN_VERIFICATION.yml
modules/veteran_verification/app/models/veteran_verification/disability_rating.rb
modules/veteran_verification/app/serializers/veteran_verification/disability_rating_serializer.rb
modules/veteran_verification/spec/models/disability_rating_spec.rb
spec/support/schemas/disability_rating_response.json
spec/support/schemas_camelized/disability_rating_response.json

Addition of the legal effective date to the Disability Rating response for the Veteran Verification API, so that the date the disability became effective is correctly displayed in the USA Jobs application for Veteran Preference.
https://vajira.max.gov/browse/API-5577
* Field addition utilizing existing recordings
* Awaiting final confirmation on the language used in the Dev Portal yml

API-5577 Add Legal Effective Date to Veteran Verification API

---

app/uploaders/evss_claim_document_uploader.rb

bug fix for https://github.com/department-of-veterans-affairs/vets-api/pull/5995
[AWS S3 objects don't have a close method.](http://sentry.vfs.va.gov/organizations/vsp/issues/30394/?end=2021-03-18T23%3A59%3A59&environment=production&project=3&query=is%3Aunresolved&start=2021-03-18T14%3A00%3A00&utc=true)

Fix Uploader Bug For AWS S3 Objects (EVSSClaimDocumentUploader)

---

Gemfile
Gemfile.lock

As the next step in the gem update series, this PR updates the awesome_print gem to the latest minor version. It's best to update each gem individually, in order to avoid issues when rolling back.

Update awesome print to latest minor version

---

Gemfile.lock

As the next step in the gem update series, this PR updates the danger gem to the latest minor version. It's best to update each gem individually, in order to avoid issues if a roll back is needed.

update danger to latest minor

---

Gemfile.lock

As the next step in the gem update series, this PR updates the parallel_tests gem to the latest minor version. It's best to update each gem individually, in order to avoid issues if a roll back is needed.

bump to latest minor version of parallel_tests 3.5.2

---

Jenkinsfile
Makefile
docker-compose.test.yml

This PR adds parallel spec functionality for Jenkins test runs. This should provide the same coverage as the existing single-threaded spec run, but at a significantly faster completion time
department-of-veterans-affairs/va.gov-team/21030

[21030] Add parallel spec functionality for Jenkins test runs

---

db/migrate/20210317132241_create_spool_file_event.rb
db/schema.rb

Add a table to track spool file creation successes and failures in CreateDailySpoolFiles.
This table will be used to prevent multiple spool files per RPO being created during retries.
The goal is to create this flow for when a failure happens during a scheduled run:
- failure for eastern RPO happens, only western RPO is spool file is created
- retry attempt 1 out of 5: doesn’t make a new western RPO cause not a “new” run of job, successfully makes an eastern RPO file
- sftps western RPO from first run and eastern RPO from first retry
Database PR for https://github.com/department-of-veterans-affairs/vets-api/pull/6169
department-of-veterans-affairs/va.gov-team#21243
department-of-veterans-affairs/va.gov-team#21246

create spool_file_events table

---

Makefile
spec/simplecov_helper.rb

The test coverage step was disabled when we enabled parallel specs for Jenkins, and we did not have a followup step to run the tests. This PR adds this step to inspect the coverage report and output the test results appropriately
department-of-veterans-affairs/vets-api/issues/6220

Adding test coverage step to Jenkins

---

Gemfile.lock

As the next step in the gem update series, this PR updates the webmock gem to the latest minor version. It's best to update each gem individually, in order to avoid issues if a roll back is needed.

bump webmock to the latest minor version

---

Gemfile.lock

As part of the gem update series, this PR updates the pact gem (test group) to the latest minor version. It's best to update each gem individually, in order to avoid issues if a roll back is needed.

update pact gem to lastest minor version

---

Gemfile.lock

As part of the gem update series, this PR updates the pact-mock_service gem (test group) to the latest minor version. It's best to update each gem individually, in order to avoid issues if a roll back is needed.

Pact mock service gem minor update

---

Gemfile.lock

As part of the gem update series, this PR updates the super_diff gem (test group) to the latest minor version. It's best to update each gem individually, in order to avoid issues if a roll back is needed.

update super_diff to latest minor version

---

Gemfile.lock

As part of the gem update series, this PR updates the database_cleaner gem to the latest major version.. Gems are being updated individually (separate PRs), in order to avoid issues if a roll back is needed.

bump database_cleaner to latest major version

---

config/sidekiq_scheduler.yml

Changes weekly report schedule to report on Monday through Sunday (before it was Tuesday through Monday).
https://vajira.max.gov/browse/API-5780

API-5780 Move weekly report to Sunday eve

---

README.md
modules/claims_api/app/swagger/claims_api/forms/form_2122_example.json

Example provides 1AQ as a poa code. Neither of the documented representatives have that as their poa code, but they do have A1Q.
We believe this may be causing issues with an invalid poa being set for Veterans in sandbox.
https://vajira.max.gov/browse/API-5917
Viewed in developer portal locally

API-5917: Documentation example has a typo

---

db/migrate/20210323001250_add_vaccine_expansion_fields.rb
db/schema.rb

Adds additional fields to the vaccine registration db schema in support of the expanded eligibility flow. 
The enrollment_id and email_confirmation_id let us track response ids for submissions to those systems. The expanded and sequestered flags let us differentiate the new submission flow and temporarily set them aside until they can be processed by the HCA enrollment system. 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/21894
- This adds columns with default values. All our AWS environments are running Postgres 11 where columns with default values can be added safely (without locking the table). The strong_migrations documentation backs this up.

Adds additional fields for vaccine expansion flow

---

config/features.yml

Adding a feature flag for the Notice of Disagreement (NOD) form for VSA claims & appeals team
https://github.com/department-of-veterans-affairs/va.gov-team/issues/21954

Add NOD feature flag

---

modules/mobile/app/controllers/mobile/v0/emails_controller.rb

In which Alastair learns controller params !== hashes. Correctly adds the `effective_end_date` key to the params used to soft delete an email in Vet360.
department-of-veterans-affairs/va.gov-team#21584

21584 mobile delete email fix

---

Gemfile.lock

CI was failing due to mimemagic v0.3.5 being removed. This PR bumps mimemagic to 0.3.6
"Your bundle is locked to mimemagic (0.3.5), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of mimemagic (0.3.5) has removed it. You'll need to update your bundle to a version other than mimemagic (0.3.5) that hasn't been removed"

bump mimemagic to 0.3.6 (0.3.5 tag was removed)

---

modules/claims_api/app/controllers/claims_api/application_controller.rb
modules/claims_api/app/swagger/claims_api/v0/claims_controller_swagger.rb
modules/claims_api/app/swagger/claims_api/v0/form_0966_controller_swagger.rb
modules/claims_api/app/swagger/claims_api/v0/form_2122_controller_swagger.rb
modules/claims_api/app/swagger/claims_api/v0/form_526_controller_swagger.rb
modules/claims_api/app/swagger/claims_api/v1/claims_controller_swagger.rb
modules/claims_api/app/swagger/claims_api/v1/form_0966_controller_swagger.rb
modules/claims_api/app/swagger/claims_api/v1/form_2122_controller_swagger.rb
modules/claims_api/app/swagger/claims_api/v1/form_526_controller_swagger.rb
modules/claims_api/spec/requests/document_validations_request_spec.rb
modules/claims_api/spec/requests/v0/claims_request_spec.rb
modules/claims_api/spec/requests/v0/disability_compensation_request_spec.rb
modules/claims_api/spec/requests/v0/intent_to_file_request_spec.rb
modules/claims_api/spec/requests/v0/power_of_attorney_request_spec.rb
modules/claims_api/spec/requests/v1/disability_compensation_request_spec.rb
modules/claims_api/spec/requests/v1/intent_to_file_request_spec.rb
modules/claims_api/spec/requests/v1/power_of_attorney_request_spec.rb

Removes documentation and logic references for EDIPI header from v0 and v1 ClaimsAPI endpoints, as it does not appear that the EDIPI header is actually used.
[API-5826](https://vajira.max.gov/browse/API-5826)

[API-5826] - Remove EDIPI header from claims api endpoints

---

.rubocop.yml

This PR adds rubocop exclusions for the RSpec/FilePath and RSpec/MultipleDescribes cops that were failing CI 

exclude failing offenses

---

modules/claims_api/app/controllers/claims_api/v1/forms/power_of_attorney_controller.rb
modules/claims_api/spec/requests/v1/power_of_attorney_request_spec.rb

The issue presents with "representative" in the response payload being null if a "previous poa" is present.
https://vajira.max.gov/browse/API-5947
Fixed specs to detect this issue and double-checked through debugging locally

API-5947: 2122 active endpoint issue when "previous poa" exists

---

config/settings.yml
config/settings/test.yml
modules/health_quest/app/services/health_quest/facilities/request.rb
modules/health_quest/app/services/health_quest/questionnaire_manager/factory.rb
modules/health_quest/app/services/health_quest/questionnaire_manager/organization_formatter.rb
modules/health_quest/app/services/health_quest/questionnaire_manager/transformer.rb
modules/health_quest/spec/services/facilities/request_spec.rb
modules/health_quest/spec/services/questionnaire_manager/factory_spec.rb
modules/health_quest/spec/services/questionnaire_manager/organization_formatter_spec.rb

- Request a list of facilities from the Facilities API by organizations
- Add phone numbers from facilities to associated organizations
- The Questionnaire Manager fetches a list of facilities from the `Facilities API` for a given set of Organization resources belonging to a user's appointments.
- We then patch the `Organizations` `telecom` field with the phone numbers from the corresponding facilities which we pulled down from the Facilities API.

get facilities by organization ids

---

db/migrate/20210325230116_add_expanded_covid_registration.rb
db/schema.rb

Adds a new DB table/model for the expanded covid vaccine registration workflow.
Because these submissions wind up having a quite different processing model than the original covid vaccine registrations, we opted to fork the model. Key differences:
- We will be resolving some eligibility info and need to store a record of that. This may include lookup data from MPI/EMIS so we encrypt that attribute.
- We will be pushing the objects through various offline ETL processes so we need the `state` and `batch_id` parameters to keep track of where they are in that pipeline. 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/22118

Add db migration for expanded covid registration model

---

config/settings.yml

Adds a VANotify template ID entry for covid vaccine expansion workflow. This will send a slightly different confirmation email that the original KMI flow, hence a new template.
Template IDs are already configured in devops repo in 
https://github.com/department-of-veterans-affairs/devops/pull/8797/files
Change that consumes this setting will happen in a CODEOWNERS-ed PR in the covid_vaccine module.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/22118
Yes, see above comment.

Adds settings entry for vaccine expansion mailer

---

README.md
modules/claims_api/app/controllers/claims_api/application_controller.rb
modules/claims_api/app/swagger/claims_api/v0/claims_controller_swagger.rb
modules/claims_api/app/swagger/claims_api/v0/form_0966_controller_swagger.rb
modules/claims_api/app/swagger/claims_api/v0/form_2122_controller_swagger.rb
modules/claims_api/app/swagger/claims_api/v0/form_526_controller_swagger.rb
modules/claims_api/app/swagger/claims_api/v1/claims_controller_swagger.rb
modules/claims_api/app/swagger/claims_api/v1/form_0966_controller_swagger.rb
modules/claims_api/app/swagger/claims_api/v1/form_2122_controller_swagger.rb
modules/claims_api/app/swagger/claims_api/v1/form_526_controller_swagger.rb
modules/claims_api/spec/requests/document_validations_request_spec.rb
modules/claims_api/spec/requests/v0/claims_request_spec.rb
modules/claims_api/spec/requests/v0/disability_compensation_request_spec.rb
modules/claims_api/spec/requests/v0/intent_to_file_request_spec.rb
modules/claims_api/spec/requests/v0/power_of_attorney_request_spec.rb
modules/claims_api/spec/requests/v1/disability_compensation_request_spec.rb
modules/claims_api/spec/requests/v1/intent_to_file_request_spec.rb
modules/claims_api/spec/requests/v1/power_of_attorney_request_spec.rb

Removes documentation and logic references for USER header from v0 and v1 ClaimsAPI endpoints.
[API-5827](https://vajira.max.gov/browse/API-5827)

[API-5827] - Remove User Header from ClaimsAPI endpoints

---

modules/covid_vaccine/app/jobs/covid_vaccine/expanded_registration_email_job.rb
modules/covid_vaccine/app/models/covid_vaccine/v0/expanded_registration_submission.rb
modules/covid_vaccine/spec/request/covid_vaccine/v0/expanded_registration_request_spec.rb
spec/support/vcr_cassettes/covid_vaccine/vanotify/send_email.yml

[Commit 1606376](https://github.com/department-of-veterans-affairs/devops/commit/16063769de866ae15a8f42a9d7a3201fc52bdbbb) added template IDs for the new registration email for expanded eligibility.
This commit fixes the `expanded_registration_email_job` (added in #6295) to use the new template ID, instead of the old registration template ID.

uses VANotify template for expanded registration

---

modules/health_quest/app/controllers/health_quest/v0/questionnaire_manager_controller.rb
modules/health_quest/app/services/health_quest/questionnaire_manager/factory.rb
modules/health_quest/config/routes.rb
modules/health_quest/spec/request/questionnaire_manager_request_spec.rb
modules/health_quest/spec/services/questionnaire_manager/factory_spec.rb

department-of-veterans-affairs/va.gov-team#19023

19023 questionnaire manager pdf endpoint

---

app/controllers/v0/dependents_verifications_controller.rb
app/services/bgs/dependency_verification_service.rb
app/swagger/swagger/requests/dependents_verifications.rb
config/routes.rb
spec/controllers/v0/dependents_verifications_controller_spec.rb
spec/request/swagger_spec.rb

This PR adds an endpoint that allows the veteran to verify the status of their dependents. Here are the possible scenarios.
1. Veteran clicks button verifying their dependent status
* FE sends `{update_diaries: 'true'}`
* we run update diary service which pulls the diaries for that veteran, updates a date and sends to bgs
2. Veteran just doesn't click the button 🤷🏻 
department-of-veterans-affairs/va.gov-team#21261
* No settings added
*  This feature is not live yet
* No sentry logs added for this PR
* none …

21261 endpoint for diary entries

---

.rspec_parallel
Makefile
docker-compose.test.yml
modules/covid_research/spec/mailers/covid_research/volunteer/submission_mailer_spec.rb
modules/covid_research/spec/rails_helper.rb
modules/covid_research/spec/requests/volunteer_request_spec.rb
modules/covid_research/spec/serializers/covid_research/genisis_serializer_spec.rb
modules/covid_research/spec/serializers/covid_research/volunteer/name_serializer_spec.rb
modules/covid_research/spec/services/covid_research/volunteer/form_crypto_service_spec.rb
modules/covid_research/spec/services/covid_research/volunteer/form_service_spec.rb
modules/covid_research/spec/services/covid_research/volunteer/genisis_service_spec.rb
modules/covid_research/spec/spec_helper.rb
modules/covid_research/spec/workers/covid_research/volunteer/confirmation_mailer_job_spec.rb
modules/covid_research/spec/workers/covid_research/volunteer/genisis_delivery_job_spec.rb
modules/mobile/app/serializers/mobile/v0/push_get_prefs_serializer.rb
modules/mobile/app/serializers/mobile/v0/push_register_serializer.rb
modules/va_forms/spec/models/form_spec.rb
modules/va_forms/spec/workers/form_reloader_spec.rb
modules/vba_documents/spec/request/v1/uploads_request_spec.rb
spec/controllers/v1/sessions_controller_spec.rb
spec/service_consumers/pact_helper.rb
spec/spec_helper.rb
spec/support/vcr_cassettes/va_forms/gql_forms.yml

This PR updates the Jenkins parallel RSpec run so that the `modules` directory is included  in the spec run, turns out they weren't being run with the previous `parallel_specs` implementation`. Additionally, this adds back the code-climate reporting that was in the previous implementation
department-of-veterans-affairs/vets-api/issues/6303

[6303] Update Jenkins parallel spec run so that modules directory is properly run

---

Gemfile.lock

Commits Gemfile.lock update that was omitted from https://github.com/department-of-veterans-affairs/vets-api/pull/6334

Updates Gemfile.lock update missed in PR #6334

---

modules/covid_vaccine/app/controllers/covid_vaccine/v0/expanded_registration_controller.rb
modules/covid_vaccine/spec/factories/expanded_registration_submissions.rb
modules/covid_vaccine/spec/request/covid_vaccine/v0/expanded_registration_request_spec.rb

Adds an audit log line to covid vaccine expanded registration controller. Logs limited attributes suitable for aggregation in Cloudwatch Insights or similar. 
* No PII - attributes are limited to country/state/applicant_type/preferred facility/presence or absence of email address.

Adds audit log line to vaccine controller

---

modules/covid_vaccine/app/models/covid_vaccine/v0/raw_expanded_form_data.rb
modules/covid_vaccine/spec/factories/expanded_registration_submissions.rb
modules/covid_vaccine/spec/request/covid_vaccine/v0/expanded_registration_request_spec.rb

Updates covid vaccine expanded submission endpoint to only enforce zip/zip+4 format for USA addresses.

Suppresses zip code validation for non-US addresses

---

lib/mpi/models/mvi_profile.rb
lib/mpi/models/mvi_profile_identity.rb
lib/mpi/models/mvi_profile_ids.rb
lib/mpi/models/mvi_profile_relationship.rb
lib/mpi/responses/profile_parser.rb
spec/factories/mvi_profiles.rb
spec/lib/mpi/responses/profile_parser_spec.rb
spec/support/mpi/find_candidate_missing_name_response.xml
spec/support/mpi/find_candidate_with_relationship_response.xml

This PR adds the `relationships` field to the `MVIProfile` class, which is a recursive `MVIProfile` that defines an entity with a relationship to the MPI User. This definition is parsed from the `personalRelationship` tag in an MPI Response
department-of-veterans-affairs/va.gov-team/issues/21004
- There shouldn't be any changes on the frontend at this point, and we currently do not have access to relationship data with MPI, so basically testing should just show that this currently doesn't break anything.
- On local, if you check out the branch `https://github.com/department-of-veterans-affairs/vets-api-mockdata/tree/5987_development_branch_mpi_relationship_mock`, and sign in with `vets.gov.user+dependent.1@gmail.com`, you should get a mocked response from MPI with relationship information

[21004] Add relationship object to MPI Profile

---

app/models/form526_submission.rb
spec/models/form526_submission_spec.rb

Rather than beginning the next upload after the previous has succeeded enqueue them all with a delay. That way if a document fails it won't prevent the others from being sent. 
department-of-veterans-affairs/va.gov-team#20704

upload all files

---

lib/pdf_fill/forms/va210781a.rb
spec/support/disability_compensation_form/submissions/with_0781.json

`nil + "string"` errors so use  "#{nil} string"
department-of-veterans-affairs/va.gov-team#22439

Allow nil name in PTSD trauma form

---

README.md
modules/vba_documents/spec/jobs/report_monthly_submissions_spec.rb
spec/request/v1/facilities/va_request_spec.rb

I noticed this test fail in the pipeline for my [unrelated PR](https://github.com/department-of-veterans-affairs/vets-api/pull/5931). Looks like the test broke with UTC rolling over to April.

Fix Flakey Test (VBA Documents)

---

db/migrate/20210401071242_add_covid_vaccine_expanded_state_index.rb
db/schema.rb

Adds an index on the state column of the covid_vaccine_expanded_registration_submission table. The need for this was observed when implementing https://github.com/department-of-veterans-affairs/vets-api/pull/6392 which batch processes records according to their current state. 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/22490
* Given the number of columns in this table currently, this is not a drop-everything-and-deploy kind of schema change, but it will be increasingly important as that table grows.
* Tested locally, confirmed that without the index the where(state: received) query was doing a seq scan; with the index it is doing an index scan.

Adds index for state column for covid vax table

---

lib/bgs/form686c.rb

When submitting a 686c (Dependents Application), there are currently 3 use cases that automatically get set to `MANUAL_VAGOV`.  These include death of a child, death of a parent, and reporting a school age child has stopped going to school.  Our partners at BGS have now asked us to expand that to any time we are removing a child.  The new use cases include a child getting married and a stepchild leaving the household.  
This PR accounts for those 2 new use cases and automatically sets the status to `MANUAL_VAGOV`.
Note to the reviewer: I've added a couple comments because for me it is hard to visualize without seeing the structure of the data, but if you feel the comments are not helpful, I'm happy to remove them. 
department-of-veterans-affairs/va.gov-team#22167
This is just a minor …

Form 686c Update Manual Status for Any Child Removal

---

modules/vba_documents/app/workers/vba_documents/slack_notifier.rb
modules/vba_documents/spec/jobs/slack_notifier_spec.rb

Removing success status from slack alerts
https://vajira.max.gov/browse/API-6104
RSPEC testing updated.

Removing success from monitoring

---

spec/request/v1/facilities/va_request_spec.rb

[Added this `require` to help CI/CD pass](https://github.com/department-of-veterans-affairs/vets-api/pull/6391), but it shouldn't be necessary ([other tests that use `instrument` method don't need it](https://github.com/department-of-veterans-affairs/vets-api/pull/6391#issuecomment-811617928)), _also_ I don't even think this require works (running that line locally on my comp later returned `false`) **therefore I'm removing it**

Remove Unnecessary Require in Test

---

app/workers/vbms/submit_dependents_pdf_job.rb

When submitting VA Form 674, we upload a PDF and currently it is using the doc type referencing Form 674b.  During integration testing, we were asked to update the doc type to reference Form 674 rather than 674b.  
department-of-veterans-affairs/va.gov-team#22488
This is just a minor PR to update the doc type code being used, so no new settings or logging have been added.

Updating Doc Type for 674

---

modules/openid_auth/README_V2.yml
modules/openid_auth/app/controllers/openid_auth/docs/v2/validation_controller.rb
modules/openid_auth/config/routes.rb

API-4750 adds a V2 token validation endpoint for Lighthouse API's to support SSOi and Client Credentials auth scenarios where different identifiers were needed for the responses.
https://community.max.gov/display/VAExternal/Token+Validation+v2
Main PR: https://github.com/department-of-veterans-affairs/vets-api/pull/6359
https://vajira.max.gov/browse/API-4750
- This is a new V2 endpoint that will not interfere with existing validation endpoint calls
- Testing includes unit testing and local testing with standard auth code, client credentials, and SSOi based access tokens

Added v2 validation documentation route.

---

Gemfile.lock

As part of the gem update series, this PR updates the typhoeus gem (default group) to the latest minor version. Gems are being updated individually (separate PRs), in order to avoid issues if a roll back is needed.
https://github.com/typhoeus/typhoeus/blob/master/CHANGELOG.md
department-of-veterans-affairs/va.gov-team##22278

bump typhoeus to the latest minor verison

---

app/models/user.rb
spec/factories/mvi_profile_relationships.rb
spec/factories/mvi_profiles.rb
spec/factories/users.rb
spec/lib/mpi/responses/profile_parser_spec.rb
spec/models/user_spec.rb

This PR adds a function on the `User` model, `relationships`, that describes the parsed relationships from the `MPI` response. Right now these `relationships` have just a subset of the MPI data for a relationship. We'll expand the data presented here as necessary
department-of-veterans-affairs/va.gov-team/issues/21005
- This shouldn't have negative impacts on a user without a relationship defined. 
- For testing, you'll have to check out the `5987_development_branch_mpi_relationship_mock` branch in `vets-api-mockdata`, then log in with `vets.gov.user+dependent.1@gmail.com`
- No data will be serialized to the frontend yet, so you'll have to set a `binding.pry` in the codebase somewhere after the user has been authenticated and `MPI` has been called, one place is in `sessions_controller`, …

21005 add relationship hash to user model

---

app/controllers/v0/dependents_verifications_controller.rb
app/models/saved_claim/veteran_readiness_employment_claim.rb
spec/models/saved_claim/veteran_readiness_employment_claim_spec.rb

This PR makes changes to the CH31 form.
The CH31 form is doing a 'soft rollout' to our partner (VRE/CMS) meaning we will only send them JSON data when vets close to a certain office fill out the form. We will always send the PDF to VBMS efolder.
After a few email exchanges with our VA partners, we understood that we were starting ONLY with a certain office so this PR removes some of the others. As time goes on we'll add more office numbers (about 5 total) and then completely remove office number whitelisting altogether.
This PR also prioritizes VAFileNumber as the id to send to VBMS when submitting to eFolder. We were using SSN which would have worked the majority of the time but in those few instances that va file number is diff from SSN VBMS would have looked up a vet by file number …

Add filenumber check for submission

---

config/settings.yml
modules/appeals_api/app/controllers/appeals_api/v1/decision_reviews/notice_of_disagreements/evidence_submissions_controller.rb
modules/appeals_api/app/models/appeals_api/evidence_submission.rb
modules/appeals_api/spec/requests/v1/notice_of_disagreements/evidence_submissions_controller_spec.rb

Instead of taking in actual uploaded documents, we will provide the consumer with an s3 url, after creating an evidence submission instance and, when possible, linking it to an existing Appeal.
https://vajira.max.gov/browse/API-6002
Tests updated in controller spec

Api 6002 - Refactor submissions#create to return submission data and signed url

---

config/settings.yml
modules/covid_vaccine/app/services/covid_vaccine/v0/enrollment_upload_service.rb
modules/covid_vaccine/spec/services/covid_vaccine/v0/enrollment_upload_service_spec.rb

Updates covid vaccine SFTP connection to use a separate port setting from settings.yml. This needed for Net::SFTP because we are connecting over a non-default port. 
Corresponding devops PR: https://github.com/department-of-veterans-affairs/devops/pull/8876
https://github.com/department-of-veterans-affairs/va.gov-team/issues/22613

Updates covid vax SFTP to use separate port config

---

modules/covid_vaccine/app/services/covid_vaccine/v0/expanded_registration_csv_generator.rb
modules/covid_vaccine/spec/services/covid_vaccine/v0/expanded_registration_csv_generator_spec.rb

Updates CSV generation for to map values to "M","F",or empty string as expected by enrollment service. 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/22643

Maps birth sex values as expected by enrollment service upstream

---

app/controllers/openid_application_controller.rb
modules/openid_auth/app/controllers/openid_auth/v2/validation_controller.rb
modules/openid_auth/spec/requests/validation_request_spec_v2.rb

One additional change to new v2 token validation endpoint to ensure Client Credentials Auth does not incorrectly populate the `act` field in the token validation response.
- https://vajira.max.gov/browse/API-4750
- https://github.com/department-of-veterans-affairs/vets-api/pull/6359

API-4750 Corrected issue with Client Credentials token v2 token auth

---

modules/covid_vaccine/app/models/covid_vaccine/v0/expanded_registration_submission.rb
modules/covid_vaccine/app/models/covid_vaccine/v0/registration_submission.rb

Import json_marshal class where used for attr_encrypted. Not causing any runtime issues generally, but causes some rake tasks to break when run with Zeitwerk loader. 
Workaround is to add this require to the top of your rake task definition. 

Adds imports for json_marshal dependency

---

lib/evss/documents_service.rb

EVSS takes forever, even for successful large document uploads.  If we let the request timeout after 6 minutes, then we keep sending the document several times.  Each one is actually successful, but we don't get the response in time so we retry later.  It's better to just up the timeout until EVSS can respond faster. 
I'm sad to do this, but it beats sending the same document several times.
fixes http://sentry.vfs.va.gov/organizations/vsp/issues/30718/?environment=production&project=3&query=evss+transaction%3ASidekiq%2FEVSS%3A%3ADisabilityCompensationForm%3A%3ASubmitUploads&statsPeriod=14d and 
http://sentry.vfs.va.gov/organizations/vsp/issues/30719/?environment=production&project=3&query=evss+transaction%3ASidekiq%2FEVSS%3A%3ADisabilityCompensationForm%3A%3ASubmitUploads&statsPeriod=14d …

longer evss document timeout

---

modules/covid_vaccine/app/services/covid_vaccine/v0/enrollment_processor.rb
modules/covid_vaccine/spec/services/covid_vaccine/v0/enrollment_processor_spec.rb
rakelib/covid_vaccine.rake

Adds a rake task to manually move a specified batch into `enrollment_pending` state. This is needed for the (so far) 1 batch that we had to submit to ES out of band.
There's room here to reconcile the static and non-static variations of this method. 

Adds rake task to manually update submission state

---

rakelib/github_stats.rake

To accurately calculate PR review time metrics for the QASP report, this PR updates the logic in the github_stats rake task. The review time duration was being calculated for PRs with no review and the logic was inaccurately influencing the review time metrics
[Grafana Board](http://grafana.vfs.va.gov/d/jmb16qwWk/pull-request-dashboard?orgId=1&from=now-2d&to=now)

Update gh stats rake task

---

app/workers/education_form/create_daily_spool_files.rb
app/workers/education_form/process10203_submissions.rb
spec/jobs/education_form/create_daily_spool_files_spec.rb
spec/jobs/education_form/process10203_submissions_spec.rb

Too many emails were being sent when a submission can't be formatted, turning off email notifications for this error

Spool: Disable emails for invalid submissions

---

config/features.yml

Renaming previously introduced `unenrolled_vaccine_scheduling` feature flag to `va_online_scheduling_unenrolled_vaccine` in order to properly scope it with the other VAOS feature flags.
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/22079
This change is based on the previously merged code from https://github.com/department-of-veterans-affairs/vets-api/pull/6442

changed unenrolled vaccine feature flag name to be under VAOS scope

---

modules/covid_vaccine/app/controllers/covid_vaccine/v0/expanded_registration_controller.rb
modules/covid_vaccine/spec/factories/expanded_registration_submissions.rb
modules/covid_vaccine/spec/request/covid_vaccine/v0/expanded_registration_request_spec.rb

The FE does not require email address. Previously the BE automatically kicks off an email confirmation job for all submissions. Updates the `ExpandedRegistrationController#create` action to only perform the `CovidVaccine::ExpandedRegistrationEmailJob` if an email is present in the submission. Added specs to confirm the other parts of the submission still work with a blank email.
department-of-veterans-affairs/va.gov-team#22738

Don't perform covid email jobs if submissions have a blank email

---

lib/mpi/responses/profile_parser.rb
spec/factories/mvi_profiles.rb
spec/lib/mpi/responses/profile_parser_spec.rb
spec/lib/mpi/service_spec.rb
spec/support/mpi/find_candidate_missing_attrs_response.xml
spec/support/mpi/find_candidate_missing_name_response.xml
spec/support/mpi/find_candidate_multiple_mhv_response.xml
spec/support/mpi/find_candidate_response.xml
spec/support/mpi/find_candidate_response_nil_address.xml
spec/support/mpi/find_candidate_valid_response.xml
spec/support/mpi/find_candidate_with_relationship_response.xml

This PR parses Person Type from an MPI Response. Currently it isn't being used on the frontend, and we don't yet propagate this to the `User` model, so this is just in the Profile Parsing logic
department-of-veterans-affairs/va.gov-team/issues/21961
- To test this, will have to set a `binding.pry` somewhere after the MPI Response has been returned
- A good place is probably when we create the `MPIData` object: `app/models/mpi_data.rb`, breakpoint somewhere in the `self.for_user` function

21961 add person type field from mpi

---

modules/claims_api/app/controllers/claims_api/v1/application_controller.rb

Missed method definition during previous version breakout that is causing issues with oauth for v1 claims endpoints.
https://lighthouseva.slack.com/archives/CT0G8GMS7/p1617802856052200

added method back in

---

README.md
modules/claims_api/app/models/claims_api/power_of_attorney.rb

Current find for the "active" poa endpoint gets the first record with the same header_md5 in the database. This order isn't guaranteed, but very possible to be the incorrect record if there are several records with the same header_md5.
This change ensures the last record (according to create_at) is the one that is chosen if there are multiples.
https://vajira.max.gov/browse/API-6192
All existing tests still pass.

API-6192: Issue when multiple POA changes are submitted with the same headers

---

rakelib/covid_vaccine.rake

Adds a rake task to run the facility fix up process for existing records in a batch,in case we need to do manual resubmission due to issues like in https://github.com/department-of-veterans-affairs/va.gov-team/issues/22841
https://github.com/department-of-veterans-affairs/va.gov-team/issues/22841
Tested locally

Adds helper rake task for facility id fixup

---

config/settings/test.yml
modules/health_quest/app/models/health_quest/questionnaire_response.rb
modules/health_quest/app/services/health_quest/questionnaire_manager/factory.rb
modules/health_quest/spec/models/questionnaire_response_spec.rb
modules/health_quest/spec/services/questionnaire_manager/factory_spec.rb

- Add the QuestionnaireResponse model and specs
- Questionnaire Manager saves QR and User demographics to DB upon QR creation
- Ability to save QR snapshot to DB
- Add the QuestionnaireResponse model and specs
- Questionnaire Manager saves QR and User demographics to DB upon QR creation
department-of-veterans-affairs/va.gov-team#19061

19061 Ability to save QR snapshot to DB

---

.rubocop_todo.yml

Master broke due to a Metrics/AbcSize violation after [this PR](https://github.com/department-of-veterans-affairs/vets-api/commit/1ca8300e87858cb85ffedf737a83faa52d275322) was merged in. It looks like the branch wasn't updated with the latest master before merging

fix Metrics/AbcSize violation

---

.github/dependabot.yml

Setting config for dependabot Gemfile code execution 
"Dependabot refused to execute external code. 
Dependabot blocked external code required for this update. Please set insecure-external-code-execution: allow in the config if you trust all dependencies' supply chain."

set insecure-external-code-execution config

---

app/controllers/openid_application_controller.rb
spec/controllers/openid_application_controller_spec.rb

With the addition of Lighthouse SSOi token validation support, it was identified that Okta profile fetching was occurring for every non-Client Credentials token validation request rather than previously where only the first time a token was used.
This PR updates the fetch profile to only occur when a session is nil and the token is not a client credentials token.
- https://vajira.max.gov/browse/API-6279
- https://github.com/department-of-veterans-affairs/vets-api/pull/6359
- Future update to token validation will cache the fetch_profile response

API-6279 Prevent Repeated Okta Profile Fetching

---

.github/dependabot.yml

This supplies a target-branch for dependabot to run against. Purely for testing if dependabot is setting enterprise.contribsys.com creds correctly.

supply target-branch for dependabot

---

db/migrate/20210408191850_add_covid_vaccine_expanded_batch_id_index.rb
db/schema.rb

Adds an index to the `covid_vaccine_expanded_registration_submissions` table on `batch_id` which is used in `CovidVaccine::V0::ExpandedRegistrationSubmission` queries.
N/A
N/A
Testing planned: run queries on staging

Add index to covid_vaccine_expanded_registration_submissions on batch_id

---

.rubocop_todo.yml

This [PR branch](https://github.com/department-of-veterans-affairs/vets-api/commit/39ca5b6abe920a32063ee372044f6f319875dfac) didn’t have the latest master before merging in and introduced a rubocop failure.

add to rubocop_todo for failing deploy

---

modules/veteran_verification/app/controllers/veteran_verification/application_controller.rb

The underlying `authenticate_token` method contained in the openid_application_controller.rb parent class was updated to fetch the Okta profile earlier to detect SSOi tokens.  The Veteran Verification API had overridden that method to utilize a mock-emis endpoint.
Update the Veteran Verification API contained `authenticate_token` method to similarly fetch the Okta profile if a session is not already established and pass that to the `establish_session` method.
- https://github.com/department-of-veterans-affairs/vets-api/pull/6520

Add missing fetch profile call

---

modules/appeals_api/app/controllers/appeals_api/v1/decision_reviews/notice_of_disagreements/evidence_submissions_controller.rb
modules/appeals_api/app/models/appeals_api/evidence_submission.rb
modules/appeals_api/app/serializers/appeals_api/evidence_submission_serializer.rb
modules/appeals_api/spec/factories/evidence_submissions.rb
modules/appeals_api/spec/models/evidence_submission_spec.rb
modules/appeals_api/spec/requests/v1/notice_of_disagreements/evidence_submissions_controller_spec.rb
modules/appeals_api/spec/serializers/evidence_submission_serializer_spec.rb

Updates the EvidenceSubmission create & show endpoints to follow the research we've done with the Matsumoto team to talk to VBADocuments::UploadSubmission directly.
❗ ❗ ~Requires #6571 (db migrations)~  ❗ ❗ 
https://vajira.max.gov/browse/API-6346
https://vajira.max.gov/browse/API-6221
Will need to follow up with other PRs to remove code that is no longer needed.

Api 6346 Update Evidence submission create & show

---

modules/appeals_api/app/models/appeals_api/event_subscription.rb
modules/appeals_api/app/models/appeals_api/higher_level_review.rb
modules/appeals_api/app/models/appeals_api/notice_of_disagreement.rb
modules/appeals_api/app/models/appeals_api/status_update.rb
modules/appeals_api/app/services/appeals_api/events/handler.rb
modules/appeals_api/app/services/appeals_api/events/status_updated.rb
modules/appeals_api/app/services/events/handler.rb
modules/appeals_api/app/workers/appeals_api/events_worker.rb
modules/appeals_api/config/initializers/event_subscriptions.rb
modules/appeals_api/spec/services/appeals_api/events/handler_spec.rb
modules/appeals_api/spec/services/appeals_api/events/status_updated_spec.rb
modules/appeals_api/spec/workers/appeals_api/events_worker_spec.rb

[API-6001](https://vajira.max.gov/browse/API-6001)
This PR adds functionality for Status Update audit logging, to track meta data around statuses changing in our API.
It does this by using an lightweight EventSourced model to decouple the event from the effect.
‼️ This PR is dependent on [this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/6527) ‼️

Api 6001/audit logging event sourcing

---

modules/claims_api/app/swagger/claims_api/forms/form_526_response_swagger.rb
modules/claims_api/config/schemas/526.json

Fixes the casing of the example values for POST Form 526 `directDeposit.accountType` attribute.
[api-6386](https://vajira.max.gov/browse/API-6386)

[API-6386] - Fix swagger example for "directDeposit.accountType"

---

app/mailers/veteran_readiness_employment_mailer.rb
app/mailers/views/veteran_readiness_employment.html.erb
app/models/saved_claim/veteran_readiness_employment_claim.rb
spec/mailers/veteran_readiness_employment_mailer_spec.rb

When a user submits a Form 28-1900 on VA.gov, an email needs to be sent to the office of Veteran Readiness and Employment (VR&E).  The regional office where the email should get sent is dependent upon the zip code that the user enters on the form.  
department-of-veterans-affairs/va.gov-team#23024
This is an update (adding an email notification) to an existing form submission, so no new logging or settings have been added.

Adding Email Notifications for VA Form 28-1900 (Chapter 31)

---

rakelib/form526.rake

Ignore Form526JobStatuses that are submit jobs **IF** any submit job has succeeded or is still being attempted (form526 rake task).

Tweak Form526 "Errors Report" Rake Task for New Definition of Success

---

modules/covid_vaccine/app/services/covid_vaccine/v0/expanded_registration_service.rb
modules/covid_vaccine/spec/factories/expanded_registration_submissions.rb

This PR:
* fixes a bug discovered when processing records where a lookup for the eligibility_info['preferred_facility'] was using an object (`:preferred_facility`) instead of a string (`'preferred_facility'`).
* Adds detail to the Exception raised when look up fails in MPI
The [test case factory trait](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/covid_vaccine/spec/factories/expanded_registration_submissions.rb#L102) that injects the preferred_facility into eligibility_info has been updated
This path is tested with this test case: 
* https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/covid_vaccine/spec/services/covid_vaccine/v0/expanded_registration_service_spec.rb#L124
The test cases for the MPI lookup exceptions are:
* …

update eligibilty_info check to use string instead of object key

---

modules/covid_vaccine/app/services/covid_vaccine/v0/expanded_registration_service.rb
modules/covid_vaccine/spec/factories/expanded_registration_submissions.rb

Fix bug where form system is sending `email_address` but code was using `email` and thus missing the email in submission
tests have been updated to ensure email_address is the field name in test data

fix bug with email vs email_address

---

app/controllers/concerns/failed_request_loggable.rb
app/controllers/v0/sessions_controller.rb
app/controllers/v1/sessions_controller.rb
app/models/gi_bill_feedback.rb
app/models/id_card_attributes.rb
app/models/mhv_account.rb
app/models/mpi_data.rb
app/models/user.rb
app/services/mhv_accounts_service.rb
app/services/users/profile.rb
lib/va_profile/contact_information/transaction_response.rb
modules/openid_auth/app/controllers/openid_auth/application_controller.rb
modules/openid_auth/spec/requests/validation_request_spec.rb
modules/openid_auth/spec/requests/validation_request_spec_v2.rb
rakelib/connectivity.rake
rakelib/mvi.rake
spec/controllers/v0/sessions_controller_spec.rb
spec/controllers/v1/sessions_controller_spec.rb
spec/models/form_profile_spec.rb
spec/models/user_spec.rb
spec/request/in_progress_forms_request_spec.rb
spec/request/letters_request_spec.rb
spec/services/users/profile_spec.rb

This change removes `va_profile` references from outside the User class as part of a larger refactor and move to keep specific User trait calls (Identity vs. MPI) contained within the User class to reduce complexity across vets-api. This change is intended only to simplify existing functionality and should not cause any noticeable changes.
department-of-veterans-affairs/va.gov-team#18740
New unit tests have been added for explicit MPI getter & setter methods.

Remove external 'User.va_profile' references

---

README.md
modules/claims_api/app/models/claims_api/power_of_attorney.rb

Sets a default value for external_uid (used for tracking within BGS) if the representative in question does not have an ICN.
Found during this work: https://vajira.max.gov/browse/API-6451
Related sentry error can be found here: http://sentry.vfs.va.gov/organizations/vsp/issues/30399/?environment=sandbox&project=3&query=is%3Aunresolved+level%3Aerror+transaction%3A%22%2AClaimsApi%3A%3A%2A%22&statsPeriod=14d

API-6451: Prevent issue with updating POA if representative does not have an ICN

---

modules/appeals_api/app/swagger/appeals_api/v1/schemas/notice_of_disagreements.rb

[API-6486](https://vajira.max.gov/browse/API-6486)
This PR adds some missing values to the nodCreateInput schema documentation.

add enum values to nodCreateInput docs

---

config/settings.yml

This removes folks from the flipper admin list who have left the platform and makes updates to include additional personnel.

Remove & update flipper personnel

---

README.md
docker-compose-deps.yml
docs/setup/hybrid.md

Adds instructions and a docker-compose file for running Postgres
and Redis in docker but running vets-api natively.
This is a setup that works well for me and I thought others might benefit. Happy to have either the documentation or the setup itself altered if people see an opportunity for streamlining. 
* It's possible to map Redis and Postgres straight through on their default ports, but I figured if people already had either of those things running natively it would conflict and generate support questions, so I went with `default port * 10`
* If redis is mapped to its default port, then no settings.local.yml stanza is needed. A local configuration *is* still needed for Postgres because the default settings tries to connects on a unix domain socket which doesn't work with Docker without …

Adds and documents "hybrid mode" vets-api setup.

---

app/models/user.rb
modules/mobile/app/serializers/mobile/v0/user_serializer.rb
spec/models/form_profile_spec.rb

Followup PR to #6433, this change contains the last removal of external `user.va_profile` method calls and reorders various User model getter and setter methods to flow alphabetically.
department-of-veterans-affairs/va.gov-team#18740
No unit test changes were made, full test suite was performed as well as manual login/logout workflow tests.

reorganize user model methods (#18742)

---

modules/vba_documents/app/models/vba_documents/git_items.rb
modules/vba_documents/spec/models/git_items_spec.rb

Changes notifications of deployments for benefits intake and for forms into their own channels. Previously they shared a channel.
https://vajira.max.gov/browse/API-6406
RSPEC tests modified.

Split up forms and benefits deployment notifications

---

modules/covid_vaccine/app/controllers/covid_vaccine/v0/registration_controller.rb

Disabled CSRF protection on the covid KMI opt_out endpoint which is triggered via an email opt out link. Working theory is that since it essentially triggers the API request immediately, there may be a race condition vs. getting the CSRF token during page load. 
However it's also the case that the frontend was not passing the CSRF token at all, as remedied here: https://github.com/department-of-veterans-affairs/vets-website/pull/16880
But there is little value in CSRF protection on this particular endpoint so it may be safest to disable it. 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/23542

Skip CSRF check on KMI opt_out endpoint

---

modules/covid_vaccine/app/services/covid_vaccine/v0/expanded_registration_service.rb
modules/covid_vaccine/spec/jobs/covid_vaccine/expanded_submission_job_spec.rb
modules/covid_vaccine/spec/services/covid_vaccine/v0/expanded_registration_service_spec.rb

Comment out raising of an exception so we stop triggering a Sidekiq job to log a Sentry error every time a record is not found. Not finding a record is an expected and acceptable outcome. We want to know when it happens for evaluation purposes, but we don't need an error throw every time.
Tracking this [over here for now](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23580).

Set more appropriate log level for KMI MVI records not found

---

config/environments/production.rb

This PR simply adds a default `account_uuid: 'some-account=uuid'` to every Rails logger event, set to `nil` if the current user is not yet authenticated.
department-of-veterans-affairs/vets-api/issues/6600
- Can only test this on production-like environments, so will need to test on staging, or a PR instance
- I wasn't able to figure out how to test this on the deployed instance here, but I tried this locally (by moving the logger config over to the `development` environment), and I confirmed these changes did not break the logging

[6600] Adding account uuid to default rails logging

---

modules/covid_vaccine/app/services/covid_vaccine/v0/expanded_registration_service.rb

Classic KMI passes a string for the `vaccineInterest` attribute to VEText. This change aligns new SLA KMI with classic KMI by passing the string `'INTERESTED'` rather than `true` for all submissions. All submissions are considered interested in receiving a vaccine.
Separately, the VEText team will set all received SLA KMI submissions to `vaccineInterest = 'INTERESTED'` to complete the cleanup.

Pass string instead of boolean to VEText for expanded KMI vaccine interest

---

app/controllers/v0/virtual_agent_token_controller.rb
config/features.yml
config/settings.yml
spec/controllers/v0/virtual_agent_token_controller_spec.rb
spec/request/swagger_spec.rb
spec/support/vcr_cassettes/virtual_agent/webchat_token_a.yml
spec/support/vcr_cassettes/virtual_agent/webchat_token_b.yml

Creates a toggle to switch between two bots in each environment, using two different webchat secrets
- Added two values to `settings.yml`
- related devops PR to update secrets: https://github.com/department-of-veterans-affairs/devops/pull/9041
department-of-veterans-affairs/va-virtual-agent#150
New feature flag, `virtual_agent_bot_a`
Updated unit tests and did manual testing locally

Enables blue-green deployment for virtual agent

---

modules/mobile/app/serializers/mobile/v0/user_serializer.rb
modules/mobile/spec/request/user_request_spec.rb

Adds secure messaging to the list of authorized/available services using the `mhv_messaging_policy` and updates specs.
User should only be authorized to use SM if they have a Premium MHV account.
department-of-veterans-affairs/va.gov-team#23139

Add secure messaging to service dictionary

---

modules/mobile/app/controllers/mobile/v0/appointments_controller.rb
modules/mobile/app/models/mobile/v0/concerns/redis_caching.rb
modules/mobile/spec/request/appointments_request_spec.rb

Adds a controller action after hook to clear the appointments cache when an appointment is cancelled.
department-of-veterans-affairs/va.gov-team#23635

23635 mobile clear appointments cache on cancel appointment

---

spec/controllers/concerns/form_attachment_create_spec.rb
spec/controllers/v0/decision_review_evidences_controller_spec.rb
spec/controllers/v0/hca_attachments_controller_spec.rb
spec/controllers/v0/preneeds/preneed_attachments_controller_spec.rb
spec/controllers/v0/upload_supporting_evidences_controller_spec.rb
spec/controllers/v0/vic/supporting_documentation_attachments_controller_spec.rb
spec/factories/decision_review_evidence_attachment.rb
spec/factories/supporting_evidence_attachment.rb
spec/request/decision_review_evidences_request_spec.rb
spec/request/upload_supporting_evidence_request_spec.rb

This PR creates a common controller test suite for all controllers that accept document uploads as form submission attachments.
- `V0::HCAAttachmentsController`
- `V0::UploadSupportingEvidencesController`
- `V0::Preneeds::PreneedAttachmentsController`
- `V0::VIC::SupportingDocumentationAttachmentsController`
- `V0::DecisionReviewEvidencesController`
- `V0::Form1010cg::AttachmentController` *added in next PR [#6661](https://github.com/department-of-veterans-affairs/vets-api/pull/6661)
- [#21906](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21906)
| Next [#6661](https://github.com/department-of-veterans-affairs/vets-api/pull/6661)

Create a shared FormAttachmentCreate controller spec

---

modules/appeals_api/app/controllers/appeals_api/v1/decision_reviews/higher_level_reviews_controller.rb
modules/appeals_api/app/controllers/appeals_api/v1/decision_reviews/notice_of_disagreements/evidence_submissions_controller.rb
modules/appeals_api/app/controllers/appeals_api/v1/decision_reviews/notice_of_disagreements_controller.rb
modules/appeals_api/spec/requests/v1/higher_level_reviews_controller_spec.rb
modules/appeals_api/spec/requests/v1/notice_of_disagreements/evidence_submissions_controller_spec.rb
modules/appeals_api/spec/requests/v1/notice_of_disagreements_controller_spec.rb

We added `source` to our nod, hlr, and evidence submission models but never persisted the attribute upon creation. This is the fix.
https://vajira.max.gov/browse/API-6414

Ensure source tracked

---

modules/appeals_api/spec/requests/v1/notice_of_disagreements/evidence_submissions_controller_spec.rb

The `before do` request was creating some intermittent failure modes locally when the request would return a 500 or just not process for every example.

I think this fixes it 😬

---

README.md
modules/claims_api/app/controllers/claims_api/v0/forms/power_of_attorney_controller.rb
modules/claims_api/app/controllers/claims_api/v1/claims_controller.rb
modules/claims_api/app/controllers/claims_api/v1/forms/disability_compensation_controller.rb
modules/claims_api/app/controllers/claims_api/v1/forms/intent_to_file_controller.rb
modules/claims_api/app/controllers/claims_api/v1/forms/power_of_attorney_controller.rb
modules/claims_api/app/controllers/concerns/claims_api/poa_verification.rb
modules/claims_api/spec/requests/v0/power_of_attorney_request_spec.rb
modules/claims_api/spec/requests/v1/power_of_attorney_request_spec.rb

This change adds a check to ensure the poa code submitted to assign to a Veteran is found as active in the OGC dataset.
This change also adds a check, for the v1 representative flow only, to ensure the representative submitted the poa change request is associated with the poa_code they are submitting.
https://vajira.max.gov/browse/API-6439
Existing tests broke with new functionality.
Modified existing tests to reflect change in response.
Added tests to cover new expectations.

API-6439: validate POA code

---

Gemfile
Gemfile.lock
modules/vba_documents/app/workers/vba_documents/upload_processor.rb
modules/vba_documents/spec/jobs/upload_processor_spec.rb

We are adding in an application-level lock to ensure an upload submission never occurs more than once.
https://vajira.max.gov/browse/API-6651
A detailed RSPEC test is being added that has sub-processes to test the application lock.  If the lock is removed the tests do fail!!

Cris.shupp api 6651 duplicate uploads

---

app/models/health_care_application.rb
spec/models/health_care_application_spec.rb
spec/request/health_care_applications_request_spec.rb

Adds `primary_eligibility` attribute as part of enrollment_status on `healthcare_applications_controller`
This is needed by VAOS direct scheduling to ensure we’re only allowing veterans and not spouses, caretakers, etc who might have recently received a vaccine from the VA.
@grossb1 can you update with ticket number?

Adds primary_eligibility attribute as part of enrollment_status on healthcare_applications_controller

---

config/sidekiq_scheduler.yml

This PR just removes the delay before starting `CovidVaccine::ExpandedSubmissionStateJob`
Existing tests all still pass

Covid Vaccine - update sidekiq_scheduler to remove delay

---

modules/covid_vaccine/spec/jobs/covid_vaccine/scheduled_batch_job_spec.rb

This spec fails sporadicaly during CI runs. Temporarily disabling while a solution to setup and tear down the spec correctly is researched.
N/A

Temporarily disable the flaky (on CI) covid schedule batch logging spec

---

.github/workflows/pact.yml

This PR migrates the `pact:verify` rake task to GitHub Actions. Pact will be removed entirely from CircleCI in a separate PR.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/22374

Migrate Pact tests to GitHub Actions

---

modules/health_quest/app/services/health_quest/questionnaire_manager/basic_questionnaire_manager_formatter.rb
modules/health_quest/app/services/health_quest/questionnaire_manager/factory.rb
modules/health_quest/spec/services/questionnaire_manager/basic_questionnaire_manager_formatter_spec.rb
modules/health_quest/spec/services/questionnaire_manager/factory_spec.rb
modules/health_quest/spec/services/questionnaire_manager/transformer_spec.rb

- Lighthouse Location resource no longer has the Organization key
- Use the Organization identifiers to retrieve the list of facilities

21632 Fix get_facilities method

---

modules/appeals_api/app/models/appeals_api/notice_of_disagreement.rb
modules/appeals_api/app/services/appeals_api/pdf_construction/notice_of_disagreement/v1/form_data.rb
modules/appeals_api/app/swagger/appeals_api/v1/notice_of_disagreements_controller_swagger.rb
modules/appeals_api/config/schemas/10182_headers.json
modules/appeals_api/spec/fixtures/valid_10182_headers.json
modules/appeals_api/spec/fixtures/valid_10182_headers_minimum.json
modules/appeals_api/spec/requests/v1/notice_of_disagreements_controller_spec.rb
modules/appeals_api/spec/services/appeals_api/pdf_construction/notice_of_disagreement/v1/form_data_spec.rb

This updates the naming conventions (for the request headers) used in the NOD. Previously we were using `X-VA-Veteran-First-Name` instead of how the HLR is structured `X-VA-First-Name`.
https://vajira.max.gov/browse/API-6718

API-6718 - Update NOD header schema

---

Gemfile.lock

brakeman was failing [here ](https://github.com/department-of-veterans-affairs/vets-api/pull/6706/checks?check_run_id=2458536776) because it wanted to be updated.

upgrade brakeman

---

config/features.yml

We created some feature flags in advance of work that has now been delayed for several years, so I think it makes sense to remove them.
Front end change: https://github.com/department-of-veterans-affairs/vets-website/pull/16948/files#diff-c2a50f0603156c6db59de7ab566a362de04d87684c55d2f2b0b6a68e9d901e79
https://github.com/department-of-veterans-affairs/va.gov-team/issues/23691
None of these flags are used on the BE.

Remove unnecessary VAOS feature flags

---

Gemfile.lock

As part of the gem update series, this PR updates the aws-sdk-s3 gem(default group) to the latest minor version. Gems are being updated individually (separate PRs), in order to avoid issues if a roll back is needed.
https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-s3/CHANGELOG.md

bump aws-sdk-s3 to latest minor version

---

Gemfile.lock

As part of the gem update series, this PR updates the octokit gem(default group) to the latest minor version. Gems are being updated individually (separate PRs), in order to avoid issues if a roll back is needed.
https://github.com/octokit/octokit.rb/releases

bump octokit to latest minor

---

modules/appeals_api/app/workers/appeals_api/higher_level_review_pdf_submit_job.rb
modules/appeals_api/lib/appeals_api/sidekiq_retry_notifier.rb
modules/appeals_api/spec/workers/higher_level_review_pdf_submit_job_spec.rb

[API-6424](https://vajira.max.gov/browse/API-6424)
This PR:
HLRPDFSubmitJob is potentially sending duplicate requests to CentralMail. We _think_ that the reason is because we're both relying on CentralMail::Utilities#retry_errors, which manually schedules another job, and then some failure (for which no logging exists) then raises and is retried automatically by sidekiq.
This PR attempts to add some logging to both error states, and removes the dependency on CentralMail::Utilities.
Potential Issue - this change will mean that any UploadError due to upstream outages (DOC201) will need to manually be retried, as the HLR will be in 'error' state. (which is kinda what it's for anyway)
This issue will present for NOD as well, assuming this is the problem.
CC: @nathanbwright (co-authored)

Rely on sidekiq retry and add logging for duplicate HLRPDFSubmitJob

---

modules/claims_api/app/controllers/claims_api/v0/forms/power_of_attorney_controller.rb
modules/claims_api/app/controllers/claims_api/v1/forms/power_of_attorney_controller.rb
modules/claims_api/app/models/claims_api/power_of_attorney.rb
modules/claims_api/spec/requests/v0/power_of_attorney_request_spec.rb
modules/claims_api/spec/requests/v1/power_of_attorney_request_spec.rb

We initially added the POA `status` to the md5 hash to make it pass validation for uniqueness via this flow:
- set to rep A
- set to rep B
- set back to rep A
However, this still fails on this workflow after a few go-rounds, since there's only a handful of status options it will have:
set to rep A (with status `pending` -> 'updated`)
set to rep B (with status `pending` -> `updated`)
set back to rep A (with status `pending` -> failing on uniqueness going to `updated`)
set back to rep B (with status `pending` -> failing on uniqueness going to `updated`)
set back to rep A ( failing on uniqueness for `pending` and `updated`
Since the lookups can happen with just the header_md5, I'm not sure if the md5 is even needed at all now, but at least removing the uniqueness requirement avoids …

Remove unique md5 requirement for POA records

---

modules/claims_api/app/swagger/claims_api/v0/form_526_controller_swagger.rb
modules/claims_api/app/swagger/claims_api/v1/form_526_controller_swagger.rb

Updated documentation to mention either a wet signature or an e-signature is fine for a Veteran's original claim.
https://vajira.max.gov/browse/API-6628
Viewed through developer portal locally.

API-6628: Update docs to accept eSignature

---

.circleci/config.yml
.github/workflows/code_checks.yml
rakelib/security.rake

We added these ignores because upgrading to `rexml` 3.2.5 caused breaking changes to `ruby-saml` therefore broke login. After upgrading both `rexml` and `ruby-saml` that issue is now resolved and the CVE taken care of. 
department-of-veterans-affairs/va.gov-team#24019

Remove ignores for CVE-2021-28965

---

Gemfile.lock

As part of the gem update series, this PR updates the aasm gem (default group) to the latest minor version. Gems are being updated individually via separate PRs, in order to avoid issues if a roll back is needed.
https://github.com/aasm/aasm/blob/master/CHANGELOG.md

bump aasm to latest minor

---

modules/appeals_api/app/workers/appeals_api/higher_level_review_upload_status_updater.rb
modules/appeals_api/app/workers/appeals_api/notice_of_disagreement_pdf_submit_job.rb
modules/appeals_api/app/workers/appeals_api/notice_of_disagreement_upload_status_updater.rb

[API-6437](https://vajira.max.gov/browse/API-6437)
lower threshold to catch retries earlier

lower threshold

---

app/services/form1010cg/service.rb
config/features.yml
spec/request/caregivers_assistance_claims_request_spec.rb
spec/services/form1010cg/service_spec.rb

Fixes: https://github.com/department-of-veterans-affairs/va.gov-team/issues/23825
- Direct Form 10-10cg Submissions to use the new `Form1010cg::DeliverAttachmentsJob`.
- Remove `:async_10_10_cg_attachments` feature flag and logic
- Remove deprecated `Form1010cg::Service#submit_attachment` method.
- Epic [#18347](https://app.zenhub.com/workspaces/vsa---caregiver-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/18347
)
- We will not remove the `Form1010cg::DeliverPdfToCARMAJob` just yet, so pending jobs in prod can be completed.

Route 10-10CG submissions to new job

---

modules/covid_vaccine/app/services/covid_vaccine/v0/expanded_registration_service.rb
modules/covid_vaccine/spec/factories/expanded_registration_submissions.rb
modules/covid_vaccine/spec/services/covid_vaccine/v0/expanded_registration_service_spec.rb
rakelib/covid_vaccine.rake

This PR adds a rake task that can be invoked to reprocess records that are stuck with state=enrollment_complete.  A conditional check is also added to prevent attempts to make illegal state transitions. 
Test cases have been added that begin with state=enrollment_complete
The rake task will be manually invoked as needed to handle these rare cases.

conditional and rake task to kick off reprocess of stuck records

---

modules/appeals_api/app/controllers/appeals_api/v1/decision_reviews/notice_of_disagreements/evidence_submissions_controller.rb
modules/appeals_api/app/controllers/appeals_api/v1/decision_reviews/notice_of_disagreements_controller.rb
modules/appeals_api/app/models/appeals_api/evidence_submission.rb
modules/appeals_api/app/models/appeals_api/notice_of_disagreement.rb
modules/appeals_api/app/services/appeals_api/evidence_submission_request_validator.rb
modules/appeals_api/app/services/appeals_api/pdf_construction/notice_of_disagreement/v1/form_data.rb
modules/appeals_api/config/locales/en.yml
modules/appeals_api/spec/factories/evidence_submissions.rb
modules/appeals_api/spec/factories/notice_of_disagreements.rb
modules/appeals_api/spec/models/notice_of_disagreement_spec.rb
modules/appeals_api/spec/requests/v1/notice_of_disagreements/evidence_submissions_controller_spec.rb
modules/appeals_api/spec/serializers/evidence_submission_serializer_spec.rb
modules/appeals_api/spec/services/appeals_api/pdf_construction/notice_of_disagreement/v1/form_data_spec.rb

Step 1
In order to validate our nod evidence submissions, we need to persist a nod's board_review_option upon its creation in order to check that it's marked as evidence_submission.
Step 2
Validate the board_review_option for incoming evidence submission.
**Step 3 In Progress**
Validate agains NOD's Veteran SSN _if_ PII still available
---
This PR is a follow up to the recent addition of board_review_option to our nod model schema.
Relates to https://vajira.max.gov/browse/API-6166
Updates made to the multiple specs with the addition of the new NOD attribute.
Also includes fix for: https://vajira.max.gov/browse/API-6840

API-6116 Add evidence submission validation

---

modules/appeals_api/app/models/appeals_api/higher_level_review.rb
modules/appeals_api/app/models/appeals_api/notice_of_disagreement.rb
modules/appeals_api/spec/models/higher_level_review_spec.rb
modules/appeals_api/spec/models/notice_of_disagreement_spec.rb

[API-6411](https://vajira.max.gov/browse/API-6411)
This PR emits a status updated event in the [newly created](https://github.com/department-of-veterans-affairs/vets-api/pull/6731) `update_status!` interface for both NOD and HLR.
As a result, it's also dependent on that PR.
Potential Issues: As of right now, it seems that the module namespaced initializer isn't working as expected, and the EventSubscriptions are not being created locally. Will continue to investigate, this won't break any of the code that exists.

Api 6411/status update event

---

config/settings.yml
modules/appeals_api/app/swagger/appeals_api/v1/notice_of_disagreements_controller_swagger.rb

[API-6887](https://vajira.max.gov/browse/API-6887)
This PR removes the flag that disabled NOD endpoints in production. It also changes the name of the flag for future use, so we can use it for any swagger doc path.
[devops PR](https://github.com/department-of-veterans-affairs/devops/pull/9114)

remove PATH_ENABLED flag from NOD docs

---

modules/appeals_api/app/controllers/appeals_api/docs/v1/docs_controller.rb
modules/appeals_api/app/swagger/appeals_api/v1/notice_of_disagreements_controller_swagger.rb
modules/appeals_api/app/swagger/appeals_api/v1/security_scheme_swagger.rb

This PR should fix the issue with the fact that our example curl commands weren't getting generated properly (when you add an API Key).
To test you will need to have the developer portal running locally and point it at your local instance of vets-api.
https://vajira.max.gov/browse/API-6954

Api 6954/bug with swagger docs curl generation

---

modules/appeals_api/app/workers/appeals_api/higher_level_review_pdf_submit_job.rb
modules/appeals_api/app/workers/appeals_api/notice_of_disagreement_pdf_submit_job.rb

[API-6894](https://vajira.max.gov/browse/API-6894)
This optional parameter for PDF submit job allows for multiple versions of pdf generation to occur

add versioning parameter to pdf submit job

---

app/models/user.rb
app/services/users/profile.rb
rakelib/mvi.rake

Adds deprecation notices to User `va_profile` methods in preparation for removal and removes last invocation of it from a rakefile. Also renames scaffolded User.va_profile getter method; the serialized `va_profile` will remain an attribute sent to the front end for the time being.
department-of-veterans-affairs/va.gov-team#18742
Manual testing of the deprecation notice and continuing functionality of the rakefile and serializer.

#18742 adds deprecation warnings for User va_profile methods

---

app/controllers/v0/financial_status_reports_controller.rb
app/models/form_profiles/va_5655.rb

- Rescue from the default StandardError
- Savon soap fault exception is too narrow and restrictive
- The user's social security needs to be returned if anything goes wrong
department-of-veterans-affairs/va.gov-team#24402

24402 rescue standard errors

---

config/features.yml

[Original Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23958)
Now that we are farther along on the Certificate of Eligibility app we need to gate it and the pages that access it behind a feature toggle. This PR adds the code for the feature toggle to the back end.

added feature toggle

---

app/models/user.rb
lib/evss/vso_search/service.rb

This change adds a new, temporary, Sentry logging call in the case of an EVSS `getCurrentInfo` call that is to be performed without the needed EDIPI. We suspect that the failure to produce an EDIPI is due to this method (`request_headers`) being called on a user that has either not been authenticated to LOA3 or is missing their mhv_icn.
This PR should not change any existing functionality.

[22732] adds message log when failing to look up edipi

---

modules/appeals_api/app/models/appeals_api/evidence_submission.rb
modules/appeals_api/app/serializers/appeals_api/evidence_submission_serializer.rb
modules/appeals_api/spec/factories/evidence_submissions.rb
modules/appeals_api/spec/requests/v1/notice_of_disagreements/evidence_submissions_controller_spec.rb
modules/appeals_api/spec/serializers/evidence_submission_serializer_spec.rb

While testing, claims and appeals hit our #show endpoint and received a `status: error` but no `code` or `detail`.
This PR delegates `AppealsApi::EvidenceSubmission` `code` and `detail` to `VBADocuments::UploadSubmission` in both the model and serializer so that when serialized, or called, the attributes inherits from the associated vba upload record.
Dependent migration PR: https://github.com/department-of-veterans-affairs/vets-api/pull/6826
Ticket: https://vajira.max.gov/browse/API-7009

Refactor code and detail delegation

---

Gemfile.lock

As part of the gem update series, this PR updates the factory_bot_rails gem (dev/test group) to the latest minor version. Gems are being updated individually (separate PRs), in order to avoid issues if a roll back is needed.
https://github.com/thoughtbot/factory_bot_rails/blob/master/NEWS.md

bump factory_bot_rails to the latest minor

---

Gemfile.lock

As part of the gem update series, this PR updates the parallel_tests gem (dev/test group) to the latest minor version. Gems are being updated individually (separate PRs), in order to avoid issues if a roll back is needed.
https://github.com/grosser/parallel_tests/blob/master/CHANGELOG.md

bump parallel_tests to lastest minor

---

Gemfile.lock

As part of the gem update series, this PR updates the super_diff gem (test group) to the latest minor version. Gems are being updated individually (separate PRs), in order to avoid issues if a roll back is needed.
https://github.com/mcmire/super_diff/blob/master/CHANGELOG.md

bump super_diff to latest minor

---

Gemfile.lock

As part of the gem update series, this PR updates the bootsnap gem (dev/test group) to the latest patch version. Gems are being updated individually (separate PRs), in order to avoid issues if a roll back is needed.
https://github.com/Shopify/bootsnap/blob/master/CHANGELOG.md

bump bootsnap to latest patch

---

db/schema.rb
modules/appeals_api/db/migrate/20210510202141_remove_error_fields_from_evidence_submissions.rb

**Going to require a merge before this will pass - PR forthcoming**
We will be delegating `code` and `detail` to to `VBA::UploadSubmission`,  so dropping from our table
Ticket: https://vajira.max.gov/browse/API-7009

API-7009: Migration - remove code and detail from evidence submissions table

---

config/features.yml

Adds a feature flag that will be used to toggle the availability of covid-19 vaccine scheduling links in the facility locator frontend. Also sorts the feature flags using http://yaml-sorter.herokuapp.com/.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/22139

Sort flags and add covid_vaccine_scheduling_frontend

---

modules/appeals_api/app/controllers/appeals_api/docs/v2/docs_controller.rb
modules/appeals_api/app/controllers/appeals_api/metadata_controller.rb
modules/appeals_api/app/swagger/appeals_api/v2/swagger_root.rb
modules/appeals_api/config/routes.rb

[API-6900](https://vajira.max.gov/browse/API-6900)
This PR adds the ability for our docs endpoints to serve a V2 docset

v2 documentation

---

modules/appeals_api/app/controllers/appeals_api/v2/decision_reviews/higher_level_reviews_controller.rb
modules/appeals_api/app/controllers/appeals_api/v2/decision_reviews/notice_of_disagreements/evidence_submissions_controller.rb
modules/appeals_api/app/controllers/appeals_api/v2/decision_reviews/notice_of_disagreements_controller.rb
modules/appeals_api/config/routes.rb

[API-6897](https://vajira.max.gov/browse/API-6897)
This PR adds the new V2 routes, and adds non-implemented response for NOD. 
There are some unfinished pieces here which are relying on other PRs, such as a completed V2 schema.
I believe that I'll get dinged on coverage here, in which case I'll wait for the schema PR before continuing, because testing the HLR controller is impossible without it.

Api 6897/new v2 route matchers

---

modules/appeals_api/app/controllers/concerns/appeals_api/header_modification.rb
modules/appeals_api/spec/controllers/concerns/appeals_api/header_modification_spec.rb

[API-7102](https://vajira.max.gov/browse/API-7102)
This PR adds a concern to allow us to deprecate routes in the AppealsApi namespace.

add deprecation ability

---

config/routes.rb

Enable form 10-10cg attachment route in production.
- Epic [#18347](https://app.zenhub.com/workspaces/vsa---caregiver-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/18347
)
- Security review: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/260

Enable Form 10-10cg Attachments Route

---

Gemfile.lock

Bump betamocks version that relaxes the Faraday dependency
department-of-veterans-affairs/va.gov-team#24619

Bump betamocks version

---

Gemfile.lock

As part of the gem update series, this PR updates the webmock gem and associated gems (default group) to the latest minor version. Gems are being updated individually (separate PRs), in order to avoid issues if a roll back is needed.
https://github.com/rubyzip/rubyzip/blob/master/Changelog.md
https://github.com/bblimke/webmock/blob/master/CHANGELOG.md

bump webmock to latest minor

---

Gemfile.lock

1.11.4 / 2021-05-14¶
Security¶
[CRuby] Vendored libxml2 upgraded to v2.9.12 which addresses:
CVE-2019-20388
CVE-2020-24977
CVE-2021-3517
CVE-2021-3518
CVE-2021-3537
CVE-2021-3541
Note that two additional CVEs were addressed upstream but are not relevant to this release. CVE-2021-3516 via xmllint is not present in Nokogiri, and CVE-2020-7595 has been patched in Nokogiri since v1.10.8 (see #1992).
Please see nokogiri/GHSA-7rrm-v45f-jp64 or #2233 for a more complete analysis of these CVEs and patches.
Dependencies¶
[CRuby] vendored libxml2 is updated from 2.9.10 to 2.9.12. (Note that 2.9.11 was skipped because it was superseded by 2.9.12 a few hours after its release.)

update nokogiri to address CVE's

---

app/workers/vbms/submit_dependents_pdf_job.rb

When submitting a dependency application (VA Form 21-686c) the user is able to attach additional documents as supporting evidence (marriage certificate, adoption decree, etc).  During integration testing, we noticed an error when uploading the supporting evidence attachments to VBMS.  This PR implements a fix which first generates a local temp file and then uploads that file to VBMS.  
department-of-veterans-affairs/va.gov-team#22758
This is a minor fix so no new logging or settings have been added.

Supporting Evidence Attachment Fix

---

app/models/message.rb
spec/lib/sm/client/messages_spec.rb
spec/request/messages_request_spec.rb
spec/support/vcr_cassettes/sm_client/messages/gets_a_message_with_id.yml

The MHV Secure Messaging API is returning message titles and subjects with HTML entities for certain symbols such as:
* Double quotes: `&ldquo;`
* Single quotes: `&lsquo;`
* Less than: `&lt;`
* Greater than: `&gt;`
* Ampersands: `&amp;`
This PR uses Nokogiri to parse a message's subject and body upon Message initialization.
For example: `"Subject &ldquo;Test&rdquo;"` is transformed to `Subject: “Test”`
department-of-veterans-affairs/va.gov-team#24625

Decode HTML entities coming back from MHV on subject and body

---

modules/claims_api/app/controllers/claims_api/v2/veteran_identifier_controller.rb
modules/claims_api/app/swagger/claims_api/v2/veteran_identifier_controller_swagger.rb
modules/claims_api/spec/requests/v2/veteran_identifier_request_spec.rb

Adds logic to the new `ClaimsApi` V2 veteran-id endpoint to return a 404 if the received data does not match the test veteran's data.
[API-7226](https://vajira.max.gov/browse/API-7226)

[API-7226] - Adds 404 logic to ClaimsApi veteran id endpoint prototype

---

modules/appeals_api/app/swagger/appeals_api/v1/notice_of_disagreements_controller_swagger.rb
modules/appeals_api/app/swagger/appeals_api/v1/swagger_root.rb
modules/appeals_api/app/swagger/appeals_api/v2/swagger_root.rb

This PR makes it possible to remove the security block from a given endpoint and that makes the endpoint show up without an API key field on the front end. This is useful for the S3 endpoint (evidence submission upload) that doesn't use an API key.
https://vajira.max.gov/browse/API-7289

API-7289 - Swagger updates

---

app/models/gi_bill_feedback.rb
app/models/user.rb
spec/models/user_spec.rb

Further cleanup/consolidation of User MPI getter methods, this change removes the `sec_id_mpi` method and replaces the one place that is called in the vets-api codebase with a `sec_id` call.
department-of-veterans-affairs/va.gov-team#18741
Functionality should not change, unit tests updated to remove `sec_id_mpi` test.

[18741] removes sec_id_mpi method

---

Jenkinsfile

Danger is now being ran as a Github action. Will no longer need to be ran on Jenkins.
department-of-veterans-affairs/va.gov-team#24197

Remove Danger stage from Jenkins

---

modules/facilities_api/app/controllers/facilities_api/v1/ccp_controller.rb
modules/facilities_api/config/routes.rb
modules/facilities_api/spec/requests/facilities_api/v1/ccp_request_spec.rb

Converting the `type` param into separate routes.
We scrub all of the params from logs so it's difficult to tell what `type` of search we are handling.
department-of-veterans-affairs/va.gov-team#22183

Converting the type parameter to separate Routes

---

modules/appeals_api/app/controllers/appeals_api/v2/decision_reviews/higher_level_reviews_controller.rb

[API-4821](https://vajira.max.gov/browse/API-4821)
This PR updates the HLR v2 controller to read in the v2 schema, as well as updates the error types to use the new DetailedSchemaError class
Note: This PR is dependent on [this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/6875)

Api 4821/error types for hlr v2

---

config/features.yml

Adds a new feature flag to toggle the facility locator routes to use the new Rails engine.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/22701

Add facility_locator_rails_engine feature flag

---

app/uploaders/decision_review_evidence_attachment_uploader.rb
spec/jobs/decision_review/submit_upload_spec.rb
spec/request/decision_review_evidences_request_spec.rb

Allow only some file types for NOD supporting evidence uploads
department-of-veterans-affairs/va.gov-team#24632

Allow only some file types for NOD supporting evidence uploads

---

Gemfile.lock

Dependabot updated the benchmark-ips gem from 2.8.4 to 2.9.0 and it caused issues with running vets-api locally. Rolling back for now.

rolling back benchmark-ips gem because it is causing issues

---

modules/appeals_api/app/swagger/appeals_api/v1/higher_level_reviews_controller_swagger.rb

In preparation for rollout of v2.
Add deprecation key:value pair to trigger the fading and crossing out of these v1 routes in our developer portal docs.

API-6902 Add deprecated key to v1 hlr swagger routes

---

modules/claims_api/config/initializers/okcomputer.rb

Attempts to ensure all healthcheck calls return a response instead of timing out. This helps us always know which upstream dependency is having issues.
https://vajira.max.gov/browse/API-6614
WSDL path for the VBMS healthcheck was added due to base url check not working in production (though it worked fine in sandbox).
WSDL path addition allows healthcheck to work in both sandbox and production.

API-6614: Ensure upstream_healthcheck does not timeout for any upstream dependencies

---

modules/claims_api/app/models/claims_api/veteran.rb
modules/claims_api/spec/models/veteran/service/user_spec.rb
modules/veteran/app/models/veteran/user.rb

Undefined method issue cropped up over the weekend, after a deploy on Friday it looks like.
I believe this was the culprit: https://github.com/department-of-veterans-affairs/vets-api/pull/6924
http://sentry.vfs.va.gov/share/issue/bbb51c4a609043a5a9712a61067cb30a/
Ideally this should go out with today's deploy because it has rendered one of our endpoints completely broken :(

undefined method `mpi_icn' for #<ClaimsApi::Veteran:0x000055f83e6cf160>

---

.github/workflows/code_checks.yml
.github/workflows/danger.yml
Dockerfile
Makefile
README.md
docs/setup/running_docker.md
docs/setup/running_natively.md
rakelib/ci.rake

- Alphabetize most yaml keys (leaving `name:` at the top, and `user` before `pass`).
- Removed unneeded system packages install for linting/security
- Moved some ENV vars into the specific step that needed it
- Removed redis (wasn't being used)
- Fix deprecation warning for `comment_on_pr` in Test Results action
- Looked into merging Danger workflow. We could but then everything would run twice because we'd need to add `pull_request` and `push` to our `on:` block.
- Move result publishing to its own job that runs on GH cloud runners since our self-hosted runners have SSL issues due to MITM cert.
- Remove Code Climate in favor of SimpleCov (GH artifacts and coverage report).

Clean up lint checks in GHA

---

config/features.yml
modules/apps_api/lib/apps_api/notification_service.rb
modules/apps_api/spec/lib/notification_service_spec.rb

This PR prevents notifications being sent out when a user connects or disconnects an application from/to their VA Profile Connected Accounts. This feature was enabled for the lower environments for testing purposes, and is now causing rate limit warnings in Okta when large batches of zombie accounts/apps are being deleted in Okta. There's no need for emails to be sent in staging/testing so this feature can be disabled outside of Production without issue.
slack thread discussing the need for a feature flag in lower environments
https://lighthouseva.slack.com/archives/C01SABWSGRY/p1621863254056700
devops pr adding environment variable https://github.com/department-of-veterans-affairs/devops/pull/9222
Unit test has been added to …

Feature flag for notifications triggered for connected accounts in lower environments

---

modules/appeals_api/config/schemas/v2/200996.json

For the new hlr form, we are increasing the character limit for veteran email. The limit for v1 is currently 44 chars. After researching, it was discovered that:
~100 chars the font size reduces to 8pt
~110 chars, characters are cut off
Please see ticket and ticket comments for more details on how the 100-character limit was determined.
Ticket: https://vajira.max.gov/browse/API-7038

API-7038 Update emailAddressText character limit from 44 to 100

---

modules/claims_api/app/workers/claims_api/special_issue_updater.rb

Error discovered in sentry. It seems the `find_contentions_by_ptcpnt_id` BGS can sometimes return nil instead of an empty array if no contentions are found.
https://vajira.max.gov/browse/API-6823

API-6823: SpecialIssueUpdater background job issue regarding no claims found

---

app/models/mpi_data.rb

find_profile raises an ArgumentError if the user doesnt have an ssn or birthdate. this was trickling up and resulting in a 500 response to the consumer.
there is quite a bit of logic in place that expects a simple nil response if the profile can't be found, this ensures that effect.
https://vajira.max.gov/browse/API-6792
Tested locally using both John Doe (to ensure we receive a 400 response) and with Tamara Ellis to ensure everything still functions with someone who is in MPI.

API-6792: Internal Server Error when retrieving claims for John Doe in sandbox

---

README.md
modules/claims_api/app/workers/claims_api/special_issue_updater.rb

Resolves issue with methods called from `sidekiq_retries_exhausted` within a sidekiq job. 
https://vajira.max.gov/browse/API-6822
https://medium.com/appaloosa-store-engineering/make-a-failing-sidekiq-worker-call-a-method-after-a-specific-number-of-retries-709d7f2cb9f3
is where i got the idea to use class level methods for `sidekiq_retries_exhausted`

API-6822: SpecialIssueUpdater background job issue with logging maximum failures

---

db/migrate/20210524134112_add_service_name_to_active_storage_blobs.active_storage.rb
db/migrate/20210524134113_create_active_storage_variant_records.active_storage.rb
db/schema.rb

This PR makes some necessary migrations for the Rails 6.1 upgrade. Some of the specs were failing with `NoMethodError (undefined method 'service_name' for #<ActiveStorage::Blob:0x0000558b5edfbeb8>)`. db migrations were needed for the ActiveStorage blobs (specifically to add the service_name column) Used the solution suggested [here](https://github.com/rails/rails/issues/40895#issuecomment-748811171)
department-of-veterans-affairs/va.gov-team#18862
department-of-veterans-affairs/va.gov-team#22271

Rails 6.1 migrations and schema update

---

app/workers/education_form/process10203_submissions.rb
lib/evss/vso_search/service.rb
modules/veteran/app/models/veteran/user.rb

Fix to catch empty string `va_eauth_dodedipnid` headers that were being incorrectly used as a reference for a user's EDIPI; this is causing [500 errors](http://sentry.vfs.va.gov/organizations/vsp/issues/31328/?environment=production&project=3&query=is%3Aunresolved+message%3A%22EducationForm%3A%3AProcess10203EVSSError%22&statsPeriod=14d) to occur within EVSS when calls are made to their service with a blank EDIPI.
The `presence` method should check both for the existence of the appropriate header within the hash as well as the existence of a truthy value for that header.
Some Sentry logging added to the EVSS service has been maintained; if the related errors stop occurring it will be removed.

[22732] adds check for empty string to EVSS service request_headers

---

app/models/triage_team.rb
app/serializers/triage_team_serializer.rb
modules/mobile/app/serializers/mobile/v0/triage_team_serializer.rb
modules/mobile/spec/support/fixtures/triage_teams.json
spec/models/triage_team_spec.rb
spec/support/schemas/triage_team.json
spec/support/schemas_camelized/triage_team.json
spec/support/vcr_cassettes/sm_client/triage_teams/gets_a_collection_of_triage_team_recipients.yml

Adds the `preferred_team` attribute to the TriageTeam model.  This attribute corresponds with the user preference on the MHV website which toggles whether the recipient/triage team displays in their contact list or not.
department-of-veterans-affairs/va.gov-team#22933

Add preferred_team attribute, update specs

---

app/models/user.rb
lib/mpi/models/mvi_profile.rb
lib/mpi/responses/profile_parser.rb
spec/lib/mpi/responses/profile_parser_spec.rb
spec/lib/mpi/service_spec.rb
spec/support/vcr_cassettes/mpi/find_candidate/valid_id_theft_flag.yml

Adds the MPI identity theft flag to the MPI profile parser and from there to the user model.
The intent is that this flag can be used in scenarios like Mobile OAuth where we don't authenticate as frequently, to block user access. That change would come as a separate PR. 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/25057 describes some of the impetus
Tested with a staging user for whom we had the identity flag set in MPI's SQA environment.

Add MPI id theft flag to user model

---

README.md
modules/claims_api/app/workers/claims_api/special_issue_updater.rb
modules/claims_api/spec/workers/special_issue_updater_spec.rb

If a single contention is present on a claim, the object is a hash. If multiple contentions are present on a claim, the object is an array. This change should fix the "single contention on a claim" scenario.
https://vajira.max.gov/browse/API-6820
Add spec to test for single contention situation.

API-6820: SpecialIssueUpdater background job issue regarding contentions

---

modules/claims_api/app/models/claims_api/auto_established_claim.rb
modules/claims_api/spec/requests/v0/disability_compensation_request_spec.rb
modules/claims_api/spec/requests/v1/disability_compensation_request_spec.rb

Restrict `PUT /forms/526` endpoint in v0 and v1 to only work with pending claims.
[API-6821](https://vajira.max.gov/browse/API-6821)

[API-6821] - Only allow "PUT /forms/526" to function on "pending" claims

---

modules/appeals_api/app/controllers/appeals_api/v1/decision_reviews/higher_level_reviews_controller.rb
modules/appeals_api/app/controllers/appeals_api/v1/decision_reviews/notice_of_disagreements_controller.rb
modules/appeals_api/app/controllers/appeals_api/v2/decision_reviews/higher_level_reviews_controller.rb
modules/appeals_api/app/services/appeals_api/pdf_construction/generator.rb

[API-7380](https://vajira.max.gov/browse/API-7380)
This PR adds the storage of pdf fill version and api versions to HLR/NOD. It's dependent on [this](https://github.com/department-of-veterans-affairs/vets-api/pull/7031) PR.
We'll add a backfilling PR that's dependent on this PR next.

Api 7380/update generator to add versionsb

---

config/settings.yml

Adds Cameron Testerman and Riley Anderson to flipper admin list.

add Cameron and Riley to flipper admin

---

modules/appeals_api/app/services/appeals_api/pdf_construction/higher_level_review/v2/form_data.rb
modules/appeals_api/config/schemas/v2/200996.json

1. Discovered how many autosized characters fit for representative first and last names (takes into account the potential future digital rep signature)
2. Entered limits in schema
3. Added representative email to schema
4. Added rep email character limit to schema (same as veteran email length)
Ticket: https://vajira.max.gov/browse/API-7421

API-7421 Add representative name character limits and email to schema

---

modules/health_quest/app/services/health_quest/shared/options_builder.rb
modules/health_quest/spec/services/shared/options_builder_spec.rb

- Provides the ability for the vets-api to query FHIR Location resources which belong to an Organization
- Example local routes which are now functional: `http://localhost:3000/health_quest/v0/organizations?identifier=vha_688` and `http://localhost:3000/health_quest/v0/locations?organization=I2-YCRI7L52BYQL63ZFALGWIWF2WU000000`
department-of-veterans-affairs/va.gov-team#25530

Ability to find locations by org

---

app/models/iam_user_identity.rb
app/models/mpi_data.rb
lib/iam_ssoe_oauth/session_manager.rb
modules/mobile/spec/controllers/application_controller_spec.rb
spec/factories/iam_users.rb

Uses the id_theft_flag attribute set in MPI (and newly available in user record) to prevent mobile OAuth sessions from being established. 
This is warranted for mobile because otherwise flagged users would be able to continue using the OAuth long-lived session refresh mechanism for up to 45 days. This is not an issue for SAML-based auth on VA.gov because re-authentication is required every time a session expire, and authentication is blocked by the id theft flag. 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/25057
* I plan to re-test this but it will require the IAM team to remove then re-add the id theft flag for a user so we can log in to the app, block them, and then make sure session refresh is blocked.

Uses id theft flag to block mobile session refresh

---

modules/health_quest/app/services/health_quest/shared/options_builder.rb
modules/health_quest/spec/services/shared/options_builder_spec.rb

- Break the registry methods hash into their own relevant hashes
- Making it easy to add other parameters to the registries
- Seeing the potential to extract registries into their own objects in the future
- Add the ability to change the resource count
department-of-veterans-affairs/va.gov-team#25428

25428 decompose the registry method

---

README.md
modules/claims_api/app/controllers/claims_api/v1/forms/power_of_attorney_controller.rb
modules/claims_api/app/swagger/v1/swagger.json
modules/claims_api/spec/requests/v1/power_of_attorney_request_spec.rb
modules/claims_api/spec/requests/v1/rswag_power_of_attorney_request_spec.rb
spec/support/schemas/claims_api/forms/power_of_attorney/active.json

This updates the `service_organization` sub-property of the `/forms/2122/active` response to the following, splitting up `name` and adding `organization_name`:
```json
{
"first_name": "Jane",
"last_name": "Doe",
"organization_name": null,
"phone_number": "555-555-5555"
}
```
```json
{
"first_name": null,
"last_name": null,
"organization_name": "Some Org",
"phone_number": "555-555-5555"
}
```
https://vajira.max.gov/browse/API-7464

Update service_organization properties for /active POA responses

---

modules/health_quest/app/services/health_quest/questionnaire_manager/factory.rb

- Adding a default count of 100 to the Questionnaire Manager.
- Questionnaire Manager by default passes in a count of 100 when querying for appointments and questionnaire_responses.
department-of-veterans-affairs/va.gov-team#25438

25438 Add default count

---

Gemfile.lock

Bumps aws-sdk-sns to the latest minor version. Dependabot has the maximum PRs open and just doing some house keeping

bump aws-sdk-sns

---

lib/decision_review/service.rb
spec/lib/decision_review/service_spec.rb

the benefits api's upstream partner only accepts some characters.  But, they use a fuzzy match so it should be ok. 
department-of-veterans-affairs/va.gov-team#25163

Transliterate names for lighthouse

---

modules/health_quest/app/services/health_quest/questionnaire_manager/factory.rb
modules/health_quest/spec/services/questionnaire_manager/factory_spec.rb

- Fetch all locations for a users appointments in one request using the `_id` param.
department-of-veterans-affairs/va.gov-team#25623

25623 fetch locations by _id param

---

app/controllers/openid_application_controller.rb
app/models/openid_user_identity.rb
app/models/token.rb
lib/okta/user_profile.rb
spec/models/openid_user_identity_spec.rb
spec/support/okta_users_helpers.rb
spec/support/vcr_cassettes/okta/metadata-ssoe.yml

Adding 2 small changes to support Lighthouse SSOe integration.
1. Adds support for `profile['uuid']` with fallback to the `token.identifiers.uuid`
2. Updates the `derived_loa` method to handle when SSOe traits are used to populate the profile
https://vajira.max.gov/browse/API-7461
Behavior should 100% reverse compatible with non-SSOe logins.  Redis cache entries are based on the uuid so different IDP uses will not result in multiple cache entries as long as the same underlying login method is used.

Api 7461 lighthouse ssoe token validation support

---

modules/health_quest/app/services/health_quest/questionnaire_manager/factory.rb
modules/health_quest/spec/services/questionnaire_manager/factory_spec.rb

- Fetch all organizations for a given set of locations for a users appointments in one request using the `_id` param.
department-of-veterans-affairs/va.gov-team#25637

25637 Fetch organizations by id param

---

app/models/iam_user_identity.rb
modules/mobile/spec/request/payment_information_request_spec.rb
spec/factories/iam_introspection_responses.rb
spec/factories/iam_users.rb
spec/models/iam_user_identity_spec.rb

Mobile OAuth is not brokered through ID.me, so MHV/DSL credentials
by definition to not have multifactor authentication present. This
change ensures that that attribute is derived correctly for all
credential types available for OAuth.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/20190
@kreek I noticed that `authorized_services` for payment is derived only from "can access evss" and not also "can access ppiu" - so it's now inaccurate in this case. The payment controller itself is correctly authorized. Do we want to make `authorized_services` smarter so it can check both of those policies?

Derives multifactor correctly for mobile OAuth

---

app/controllers/v0/caregivers_assistance_claims_controller.rb

Fixes: department-of-veterans-affairs/va.gov-team#24989
Breakman (`Brakeman -t FileAccess`) will not allow us to use an attribute (or return value of a method) of an instance that was built with user-provided params, as a file name sent in the response.
To avoid the breakman warning, we interpreted the file path. This resulted in errors reading the file because PDF Fill will provide a different name for PDFs that have an "extras" file (`{guid}_final.pdf` instead of `{guid}.pdf`).
This change allows us to get the file name from PDF Fill while also not violating the breakman warning.
- Ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/24989
- Related Slack Threads:
- https://dsva.slack.com/archives/CBU0KDSB1/p1595341676422700
- …

Fix 10-10CG PDF download (file reference) bug

---

modules/appeals_api/app/models/concerns/appeals_api/hlr_status.rb
modules/appeals_api/app/services/appeals_api/central_mail_updater.rb
modules/appeals_api/app/swagger/appeals_api/v1/schemas/higher_level_reviews.rb
modules/appeals_api/app/swagger/appeals_api/v2/api_description.md
modules/appeals_api/app/swagger/appeals_api/v2/schemas/higher_level_reviews.rb
modules/appeals_api/app/swagger/appeals_api/v2/swagger_root.rb
modules/appeals_api/spec/factories/higher_level_reviews.rb
modules/appeals_api/spec/lib/decision_review_report_spec.rb
modules/appeals_api/spec/models/concerns/appeals_api/hlr_status_spec.rb
modules/appeals_api/spec/requests/v1/docs_controller_spec.rb
modules/appeals_api/spec/services/appeals_api/central_mail_updater_spec.rb

This PR adds support for the HLR model to have two different sets of statuses depending on the `api_version`.
https://vajira.max.gov/browse/API-7341

API-7341 - HLR v2 statuses

---

modules/claims_api/app/swagger/claims_api/v1/swagger.json
spec/support/schemas/claims_api/forms/intent_to_file/active.json

Appears that the creation_date field in the 0966/active response can be null.
Updated the spec and re-generated openapi documentation.

rswag: creation_date can be null

---

config/features.yml

After discussing feature flips with our team, we want to namespace our flips. This PR renames our flip, to begin with `check-in`
- [Spike](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25214)
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)

Health care check in feature flip name space

---

modules/appeals_api/app/services/appeals_api/pdf_construction/higher_level_review/v2/form_data.rb
modules/appeals_api/app/services/appeals_api/pdf_construction/higher_level_review/v2/form_fields.rb
modules/appeals_api/app/services/appeals_api/pdf_construction/higher_level_review/v2/structure.rb
modules/appeals_api/config/schemas/v2/200996.json
modules/appeals_api/spec/services/appeals_api/pdf_construction/higher_level_review/v2/form_data_spec.rb

[API-7578](https://vajira.max.gov/browse/API-7578)
This PR adds a default countryCode for HLR v2 if it doesn't exist
The ticket lists adding a requirement for countryCode on the schema, but I'm not sure if requiring a value and then providing a default makes sense. Will discuss in standup

add default country code for HLR v2

---

modules/mobile/app/controllers/mobile/application_controller.rb
modules/mobile/app/workers/mobile/v0/vet360_linking_job.rb
modules/mobile/spec/support/vcr_cassettes/profile/init_vet360_id_status_400.yml
modules/mobile/spec/workers/vet360_linking_spec.rb

Fixes the `Mobile::V0::Vet360LinkingJob` by having it take a `user.uuid` rather than user object. Added a spec for the error case.
department-of-veterans-affairs/va.gov-team#25789

Mobile Vet360LinkingJob fix

---

modules/appeals_api/spec/factories/higher_level_reviews.rb
modules/appeals_api/spec/fixtures/valid_200996_headers_v2.json

HLR v2 no longer requires the Veteran Service Number to be passed through the headers and printed on the form.
Our spec files and factories for HLR v2 were using the HLR v1 header fixtures, which worked, but continued one continued to pass in the veteran service number, making the distinction between the two expectations confusing.
A fixture file for valid v2 headers has been added, with the veteran service number removed.
Ticket: https://vajira.max.gov/browse/API-6697

API-6697 Differentiate between v1 and v2 header fixtures

---

lib/common/client/middleware/response/mhv_errors.rb
spec/services/mhv_account_type_service_spec.rb
spec/support/vcr_cassettes/mhv_account_type_service/error_empty_body.yml

While looking at this issue in Sentry: http://sentry.vfs.va.gov/organizations/vsp/issues/44/?environment=staging&project=3&query=is%3Aunresolved+mobile&statsPeriod=14d
I noticed that the MHV client middleware was unable to handle one response from MHV - a 400 with no message body. The upshot of this is the same - that we can't get an MHV account type for this user - but this avoids us writing a spec against an internal error in the client implementation - that `string not matched` was coming from the mhv_errors middleware, trying to treat an empty string as a Hash. 
This seems to happen in staging because of garbage MHV IDs in MPI, so I don't know if it's essential to fix but seems like it will help with diagnosability. 

Adds spec for additional error case from MHV API

---

modules/appeals_api/app/services/appeals_api/pdf_construction/higher_level_review/v2/form_data.rb

Not yet supporting claimant on HLR v2. Removed a method in form_data referencing the attribute.
Ticket: https://vajira.max.gov/browse/API-6698

API-6698 Remove claimant method from form_data hlr v2

---

config/settings.yml
spec/lib/caseflow/configuration_spec.rb
spec/lib/decision_review/configuration_spec.rb

Obviously the right solution is for Caseflow to return results faster, but I'm increasing the timeout in the meantime.  I think it's preferable from our user's standpoint to wait for a result than it is to show them some sort of error message.
It seems that the more issues a user has the slower caseflow returns a result.  Or, to put this in human terms this disproportionately affects our more disabled users. 
department-of-veterans-affairs/va.gov-team#25914
This timeout is used by both lighthouse and va.gov for caseflow-related timeouts.

increase Caseflow timeout

---

modules/mobile/app/controllers/mobile/messaging_controller.rb

Call to MHVLoggingService from mobile-specific messaging
controller was not working and also not needed, so removing it.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/25819

Removes obsolete call to MHVLoggingService

---

modules/appeals_api/app/controllers/concerns/appeals_api/json_format_validation.rb
modules/appeals_api/spec/requests/v1/higher_level_reviews_controller_spec.rb
modules/appeals_api/spec/requests/v1/notice_of_disagreements_controller_spec.rb
modules/appeals_api/spec/requests/v2/higher_level_reviews_controller_spec.rb

Instead of returning the entire invalid json body, return the text that states the body is invalid.
https://vajira.max.gov/browse/API-4183

API-4183 - Clean up invalid json error

---

modules/appeals_api/app/services/appeals_api/pdf_construction/higher_level_review/v2/form_fields.rb
modules/appeals_api/app/services/appeals_api/pdf_construction/higher_level_review/v2/structure.rb

While wiring up the contestable issues soc date printing, it was pointed out that we would be better off using constants for number of rows in a column on each the first and second pages of contestable issues. Additionally, these constants should be managed by the hlr v2 `structure` file.
Ticket: https://vajira.max.gov/browse/API-7873

API-7873 Handle row number constants in hlr v2 structure

---

modules/mobile/app/models/mobile/v0/adapters/claims_overview_errors.rb
modules/mobile/spec/request/claims_and_appeals_overview_request_spec.rb
modules/mobile/spec/workers/pre_cache_claims_and_appeals_job_spec.rb

Fixes claims and appointments error message parsing. Adds specs for each case. Removes some duplication in the claims request specs.
department-of-veterans-affairs/va.gov-team#25916

25916 mobile fix pre cache claims error handling

---

app/controllers/v0/caregivers_assistance_claims_controller.rb
spec/controllers/v0/caregivers_assistance_claims_controller_spec.rb
spec/request/caregivers_assistance_claims_request_spec.rb

Allow users to download the prefilled 10-10cg PDF, even if their data is not valid against the schema.
- Fixes: https://github.com/department-of-veterans-affairs/va.gov-team/issues/14287

Allow download of pre-filled 10-10CG PDF with invalid data

---

Gemfile.lock

As part of the gem update series, this PR updates the oj gem (default group) to the latest patch version. Gems are being updated individually (separate PRs), in order to avoid issues if a roll back is needed.
https://github.com/ohler55/oj/blob/develop/CHANGELOG.md

bump oj to latest patch

---

config/settings.yml
modules/appeals_api/app/views/appeals_api/decision_review_mailer/mailer.html.erb

This PR add "NOD" to the evidence submission report and splits out the email recipients into two sections for daily and weekly reports (the actual functionality cannot be added yet until the devops [PR](https://github.com/department-of-veterans-affairs/devops/pull/9409) gets merged/applied).
https://vajira.max.gov/browse/API-7871

Api 7871/update email report

---

lib/sidekiq/retry_monitoring.rb
modules/appeals_api/app/workers/appeals_api/higher_level_review_pdf_submit_job.rb

[API-8002](https://vajira.max.gov/browse/API-8002)
Sidekiq provides a nil value on the first retry check. We don't want to add +1 to 0 retries, so we return false early.

fix retry monitoring

---

app/workers/education_form/process10203_submissions.rb
lib/evss/service.rb
lib/evss/vso_search/service.rb
spec/jobs/education_form/process10203_submissions_spec.rb
spec/lib/evss/vso_search/service_spec.rb

This PR changes the EVSS service instantiation to properly take a user as an argument so that the user's attribute values will be available as backup values in the event that `additional_headers' is missing an attribute value. It is a quick & partial reversal of [this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/5793/files) that changed the EVSS service from being instantiated with a `User` instance to using authentication_headers.
For further information related to this change, see my writeup in the linked issue thread.
Unit tests passed, manual testing of EVSS::VSOSearch service creation with only backup user object to confirm backup functionality is working.

[22732] adds user to EVSS VSOSearch service instantiation

---

app/models/user.rb

The `user.va_profile` methods as an abstraction of `user.mpi` have been deprecated in favor of direct User model getter methods, more information about this decision can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/e4401eb1ab6478ac386117e714694789639a97e0/docs/adr/0007-remove-user-model-va-profile.md)
department-of-veterans-affairs/va.gov-team#24622
Unit tests were double checked for `va_profile` calls, manual authentication workflow testing.

[24622] removes user.va_profile methods

---

modules/claims_api/app/swagger/claims_api/v1/swagger.json
modules/claims_api/spec/requests/v1/rswag_claims_request_spec.rb
modules/claims_api/spec/requests/v1/rswag_disability_compensation_request_spec.rb
modules/claims_api/spec/requests/v1/rswag_intent_to_file_request_spec.rb
modules/claims_api/spec/requests/v1/rswag_power_of_attorney_request_spec.rb
spec/swagger_helper.rb

This updates the [security definitions](https://swagger.io/docs/specification/authentication/oauth2/) in claims v1 swagger to properly reflect that it's using OAuth for authentication.
https://vajira.max.gov/browse/API-7860
In and of itself, this doesn't give us anything extra within swagger ui. The developer portal doesn't currently have the OAuth flow implemented from swagger ui, and even when using https://editor.swagger.io/, I don't think that it'll redirect properly.
This will require dev work on the portal and registering the portal as a valid OAuth consumer for in-browser requests to work properly. TBD if that's a route us or other teams are interested in pursuing, but this lays the groundwork for that.

Update security properties for claims v1 swagger

---

app/models/iam_user_identity.rb
config/initializers/statsd.rb
lib/iam_ssoe_oauth/session_manager.rb
modules/mobile/app/controllers/mobile/application_controller.rb
spec/lib/iam_ssoe_oauth/session_manager_spec.rb

Adds logging of obscured token and user info when new token is
presented. Adds obscured token to request logging. Adds statsd metrics
for new vs. refresh tokens for use in alerting.
More or less follows the approach used in VA.gov:
* Log a bunch of user info when session is first established. I'm open to not logging the secid directly but VA.gov does log ICN and I believe SECID as well. These are linkable PII but considered fair game for logging. 
* Log user UUID and obscured token in payload of each request.
I also reworked the statsd metric to allow us to distinguish between token issued immediately after authenticating vs. refresh tokens so we can define some alerts, and combined the credential type metric with that one. 
https://github.com/department-of-veterans-affairs/va.gov-team/iss …

Adds metrics and logging for OAuth sessions

---

config/settings.yml
modules/appeals_api/app/mailers/appeals_api/decision_review_mailer.rb
modules/appeals_api/app/workers/appeals_api/decision_review_report_daily.rb
modules/appeals_api/app/workers/appeals_api/decision_review_report_weekly.rb
modules/appeals_api/spec/mailers/decision_review_mailer_spec.rb
modules/appeals_api/spec/workers/decision_review_report_daily_spec.rb
modules/appeals_api/spec/workers/decision_review_report_weekly_spec.rb

This PR changes the `DecisionReviewMailer` class to take in the list of recipients so that we can have separate lists of recipients for the daily and weekly reports. It depends on the changes from this [PR](https://github.com/department-of-veterans-affairs/devops/pull/9409) being active in each of the envs **before** merging!
https://vajira.max.gov/browse/API-7871

API-7871 - Weekly and daily email report

---

modules/vaos/app/controllers/vaos/v2/facilities_controller.rb
modules/vaos/app/docs/vaos/v2/vaos_v2.yaml
modules/vaos/app/services/vaos/v2/mobile_facility_service.rb
modules/vaos/spec/request/v2/facilities_request_spec.rb
modules/vaos/spec/services/v2/mobile_facility_service_spec.rb
spec/support/schemas_camelized/vaos/v2/get_facilities.json
spec/support/vcr_cassettes/vaos/v2/mobile_facility_service/get_facilities_200.yml

Updated v2 facilities controller to accept []= query parameters. Added tests and VCR Cassettes interactions where multiple facility ids were passed in.
department-of-veterans-affairs/va.gov-team#26178

 Vets Api '/v2/facilties' does not accept []= query parameters fix

---

config/settings.yml

specifically being added for ssoe purposes
Adding new flipper admins for Identity SSOe purposes.

add identity team members to flipper admin

---

modules/vaos/app/models/vaos/v2/appointment_form.rb
modules/vaos/spec/factories/v2/appointment_forms.rb
modules/vaos/spec/models/v2/appointment_form_spec.rb

vaos service does not accept an empty object for the `slot` field in the post appointment request body.  The code has been updated to drop an empty `slot` object from the request body, should it exist
Tests were added to verify that an empty `slot` object is dropped from the request

empty slot hash is dropped from post appointment request object

---

lib/sidekiq_stats_instrumentation/client_middleware.rb

When ClientMiddleware was being called for EVSS::DisabilityCompensationForm::SubmitUploads, it was passed as a `String` instead of a class. This fix ensures that whatever is passed when the middleware is called will be handled appropriately, regardless if that is an actual `Class` or string.
department-of-veterans-affairs/va.gov-team#26326

[26326] Sidekiq Stats Instrumentation Fix

---

bin/rspec
bin/spring

The binned rspec had spring support. We want to keep this as it makes our test suite faster.

Add bin/rspec back

---

config/initializers/rswag-ui.rb
modules/claims_api/config/routes.rb

Display swagger-ui for interactions with claims api.
Should display at the following url: `{root_url, localhost, env, etc}/services/claims/docs/swagger`
https://vajira.max.gov/browse/API-7861
This initially caused a breakage in deploys due to the following error showing up in [logs](http://grafana.vfs.va.gov/explore?orgId=1&left=%5B%221624397956921%22,%221624399756921%22,%22Loki%20(Dev)%22,%7B%22expr%22:%22%7Bapp%3D%5C%22vets-api-server%5C%22%7D%20%7C%3D%20%5C%22Rswag%5C%22%22%7D,%7B%7D%5D):
```log
21:40:12 web.1       |   /srv/vets-api/src/config/initializers/rswag-ui.rb:3:in `<main>'
21:40:12 web.1       | NameError: uninitialized constant Rswag
21:40:12 web.1       | bundler: failed to load command: puma (/usr/local/bundle/bin/puma)
21:40:12 web.1       | [8] ! Unable to load …
```

API-7861 Add swagger-ui for claims endpoints

---

app/controllers/v0/financial_status_reports_controller.rb
config/redis.yml
lib/debt_management_center/financial_status_report_downloader.rb
lib/debt_management_center/financial_status_report_service.rb
lib/debt_management_center/models/financial_status_report.rb
lib/debt_management_center/responses/financial_status_report_response.rb
spec/controllers/v0/financial_status_reports_controller_spec.rb
spec/lib/debt_management_center/financial_status_report_downloader_spec.rb
spec/lib/debt_management_center/financial_status_report_service_spec.rb

This PR refactors the error handling of downloading a persisted FSR's PDF. It stops using the [broken](https://github.com/department-of-veterans-affairs/va.gov-team/issues/24402#issuecomment-866900423) `Common::Exceptions::BackendServiceException`, and instead logs an exception to sentry with additional context.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/24402
- When an FSR form is submitted, the `filenet_id` returned from DMC should be persisted. If it's not persisted, when the user attempts to download the PDF, the corresponding service will raise an error for the missing attribute. When this error is raised, it will raise a Type error and the original exception is lost ([details here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/24402# …

Refactor error handling for FSR PDF downloads

---

modules/appeals_api/lib/appeals_api/sidekiq_retry_notifier.rb
modules/appeals_api/spec/lib/sidekiq_retry_notifier_spec.rb

[API-8264](https://vajira.max.gov/browse/API-8264)
This PR renames a key name to reflect what is actually in the devops repo.

Api 8264/slack auth borken

---

config/settings.yml

GCIO is changing it's email for it's employees. I'd like to be ready when that happens.

Flipper - Adding new email prior to company email change on July 12th

---

modules/appeals_api/app/workers/appeals_api/higher_level_review_upload_status_updater.rb
modules/appeals_api/app/workers/appeals_api/notice_of_disagreement_upload_status_updater.rb
modules/appeals_api/lib/appeals_api/sidekiq_retry_notifier.rb

[API-8396](https://vajira.max.gov/browse/API-8396)
This PR makes a few adjustments to the sidekiq retry notifier message and thresholds.
For the StatusUpdater job for both HLR and NOD, it was a bit noisy in the lower environments, so we've changed the thresholds to reflect that.
Additionally the message has been updated to be more accurate regarding the retry, and the environment was added.

adjustments to thresold and messages

---

modules/check_in/config/routes.rb
modules/health_quest/config/routes.rb

All latest browsers, mobile, and desktop alike implement a DNS prefetch feature which looks for links on a web page and attempt to resolve the DNS for those URLs via pre-flight calls to those server resources. The Safari mobile and desktop browsers seem to make these pre-flight calls without closing the connection to the server even though the request/response cycle has successfully completed.
This story attempts to provide a fix for the issue by explicitly catching the calls to the health_quest and check_in modules in their individual route files.
department-of-veterans-affairs/va.gov-team#2685

2685 providing explicit prefetch routes for safari

---

Gemfile.lock
app/workers/vre/create_ch31_submissions_report.rb
spec/factories/veteran_readiness_employment_claim.rb
spec/workers/vre/create_ch31_submissions_report_spec.rb

This PR alters the order (from `created_at` ASC using SQL to `regionalOffice` using `sort_by` since the form data is encrypted) of the Veteran Readiness Employment Claims that is provided to the Ch31 Submissions Report.
department-of-veterans-affairs/va.gov-team/issues/24945
There is a new spec to describe the new functionality.

24945 change sorting of daily summary report email

---

.github/CODEOWNERS

Adds the Identity team as codeowners for the `test_user_dashboard` module within vets-api

adds Identity team as TUD module codeowners

---

app/controllers/v0/disability_compensation_forms_controller.rb
app/controllers/v0/profile/personal_informations_controller.rb
app/controllers/v0/profile/persons_controller.rb
app/models/user.rb
modules/health_quest/app/controllers/health_quest/v0/base_controller.rb
modules/health_quest/app/services/health_quest/questionnaire_manager/factory.rb
modules/health_quest/spec/services/questionnaire_manager/factory_spec.rb
rakelib/mvi.rake
spec/models/user_spec.rb

This change removes the last few calls of the User model's `mpi` method and makes it private. It also returns the `mpi_profile` method to private as well and cleans up some testing surrounding these two changes.
department-of-veterans-affairs/va.gov-team#24862
Affected unit specs update and manual login/logout workflow.

[24862] makes User mpi and mpi_profile methods private

---

app/workers/education_form/create_daily_spool_files.rb
config/features.yml
spec/jobs/education_form/create_daily_spool_files_spec.rb

Removed `spool_testing_error_1` feature flag.  This feature was only used to manually cause an error state for testing on staging.
department-of-veterans-affairs/va.gov-team#22044
- Tested locally and QA reviewed.

Remove feature flag: spool_testing_error_1 

---

modules/check_in/app/services/chip_api/service.rb
modules/check_in/spec/request/patient_check_ins_request_spec.rb
modules/check_in/spec/services/chip_api/service_spec.rb

- Temporarily mock the GET and POST CHIP endpoints
- Mocking the CHIP endpoint responses until the CHIP sandbox environment is up and running in AWS.
department-of-veterans-affairs/va.gov-team#26890

26890 mock chip response

---

app/models/emis_redis/military_information.rb
app/models/emis_redis/military_information_v2.rb
modules/veteran_verification/app/models/veteran_verification/service_history_episode.rb
modules/veteran_verification/spec/models/service_history_episode_spec.rb
spec/support/vcr_cassettes/emis/get_military_service_episodes_v2/valid_multiple_episodes_end_date_null.yml

Veteran Verification service history endpoint will take into consideration episode end_dates that are null. If they are null, deployments with a start date closes to their own will be matched with them.
Some test user behavior may change because of this PR. Some users that threw 500 errors on the service history endpoint will now have valid data. Also, the logic may order the array of service episodes or deployment in a different order, but they should remain equivalent.
User `va.api.user+idme.028@gmail.com` before the change
```json
500 
```
User `va.api.user+idme.028@gmail.com` before the change
```json
{
"data": [
{
"id": "75f7f8c0-8412-58ea-8eb8-8062e2675c35",
"type": "service_history_episodes",
"first_name": "Sam",
"last_name": "Gardner",
"branch_of_service": "Navy", …
```

Created Check for service history null dates

---

config/settings.yml

Jim and Candy are designers on our team and often run research sessions with Veterans. It would be helpful to get them added to the flipper list of admin emails so they can add participants in a pinch if they need to. This PR adds them to the list.

Added Jim and Candy to flipper toggles

---

modules/appeals_api/app/workers/appeals_api/higher_level_review_upload_status_updater.rb
modules/appeals_api/app/workers/appeals_api/notice_of_disagreement_upload_status_updater.rb

This error notification was firing off more than we wanted for the lower envs. Upping the threshold to try to quiet it down somewhat.
https://vajira.max.gov/browse/API-8438

API-8438 - Update status job error threshold in lower envs

---

modules/claims_api/app/controllers/claims_api/v1/forms/power_of_attorney_controller.rb
modules/claims_api/app/workers/claims_api/vbms_updater.rb
modules/claims_api/spec/workers/vbms_updater_spec.rb

Allows a power of attorney (poa change submitted through claims api) to change the address of that Veteran within VBMS.
https://vajira.max.gov/browse/API-6719

API-6719: Ensures new power of attorney has authorization to update Veteran's address

---

lib/bgs/power_of_attorney_verifier.rb
modules/claims_api/app/controllers/concerns/claims_api/poa_verification.rb
modules/veteran/app/models/veteran/service/representative.rb
spec/lib/bgs/power_of_attorney_verifier_spec.rb

We noticed an issue that can occur if a user is an accredited representative (not the Veteran themself) but has the same first and last name as another representative. A while back I was discovered there is at least one instance of duplicate first and last names within our current OGC data-set.
We've discussed alternative methods for matching a user to OGC data with the maintainers of OGC but unfortunately they dont store ssn or birthdate information. (and dont have any plan to in the near future)
This code change has the following effect:
In the small instances that an accredited representative both has the same first and last name, our system will respond with unauthorized to both users with the following message:
"Ambiguous VSO Representative Results" …

API-8413: Prevent user matching multiple accredited representatives from using system

---

README.md
modules/claims_api/app/workers/claims_api/special_issue_updater.rb

Unexpected error was noticed in sentry with regards to our background job to update special issues for a claim submission.
This appears to be happening in the situation where the Veteran has more than one contention but none of them match the particular claims that was submitted.
https://vajira.max.gov/browse/API-8244
No new tests are present because there was already an existing test for this exact situation. It was unfortunately already "passing" because it simply detected if an exception was raised (which causes the job to be queued back up).

API-8244: SpecialIssueUpdater Background Job Error

---

modules/claims_api/app/controllers/claims_api/v1/forms/intent_to_file_controller.rb
modules/claims_api/app/swagger/claims_api/v1/swagger.json
modules/claims_api/spec/requests/v1/intent_to_file_request_spec.rb
modules/claims_api/spec/requests/v1/rswag_intent_to_file_request_spec.rb

Adds logic to prevent case where Veteran would be submitting an ITF for their own burial.
[API-8289](https://vajira.max.gov/browse/API-8289)

[API-8289] - ClaimsApi prevent burial ITF submission from Veteran

---

app/models/iam_user_identity.rb
spec/models/iam_user_identity_spec.rb

Fixes an issue where the EMIS military history service is returning a `MIS-ERR-005 EDIPI_BAD_FORMAT EDIPI incorrectly formatted` error due to IAMUsers (via IAMUserIdentity) not parsing EDIPI as 'NOT_FOUND' as nil.
department-of-veterans-affairs/va.gov-team#26486

Sanitize edipi in iam user identity

---

config/application.rb
config/initializers/sidekiq.rb
config/settings.yml
config/settings/test.yml

adds Rack::Session::Cookie to config in order to persist the rack session 
[Devops PR](https://github.com/department-of-veterans-affairs/devops/pull/9533) with updated settings

add rack session config 

---

lib/decision_review/schemas/NOD_create_request_body_schema.json

[Lighthouse is updating](https://github.com/department-of-veterans-affairs/vets-api/pull/7353/files) its schema to allow for longer email addresses so we can too. 
department-of-veterans-affairs/va.gov-team#21757

update schema with lighthouse changes

---

app/models/in_progress_form.rb

it seems that InProgressForm metadata can be in either case (snake or camel), depending on how old it is, update sql to reflect this. 

update sql for InProgressForms to allow either case

---

app/workers/sidekiq_stats_job.rb

Adds a new gauge to StatsD to report the retry queue size.
department-of-veterans-affairs/va.gov-team#17794

[17794] Add Sidekiq Retry Queue Size to Grafana

---

modules/vba_documents/app/workers/vba_documents/upload_remover.rb
modules/vba_documents/spec/factories/upload_submissions.rb
modules/vba_documents/spec/jobs/upload_remover_spec.rb

A job is repeatedly ran to clear out old files from our S3 storage. If someone were to manually remove a file from S3 and they forgot to check the s3_deleted flag to 'true', then the loop to remove old files would 'break' instead of moving to the 'next' file. This PR allows the upload remover job to move past these manually removed files and still remove other old files.
[API 8294](https://vajira.max.gov/browse/API-8294)
rspec test has been included inside ./modules/vba_documents/spec/jobs/upload_remover_spec.rb
The new rspec test fails before the change. After the change, the test passes.

Kevin.cranmer/api 8294 s3 file remover bug

---

modules/mobile/app/models/mobile/v0/adapters/va_appointments.rb

To reduce the load on prometheus replace the statsd calls that collect facility and appointment type metrics in the mobile va appointment adapter with log lines. CloudWatch will then become the data source for those Grafana dashboards.
department-of-veterans-affairs/va.gov-team#27058

Replace the mobile appointment facility and appointment type statsd metrics with log lines

---

app/mailers/views/ch31_submissions_report.html.erb
spec/mailers/ch31_submissions_report_mailer_spec.rb

Switches `spec/mailers/ch31_submissions_report_mailer_spec.rb` so that the `submitted_claims` helper used is not a duplicate (and outdated) implementation of the logic inside `VRE::CreateCh31SubmissionsReport#get_claims_submitted_in_range`, which is the method responsible for generating the object passed to `Ch31SubmissionsReportMailer`. 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/27114
The spec that should have failed during https://github.com/department-of-veterans-affairs/vets-api/pull/7320's CI was altered to now rely on the preparatory class and pass the same type of object used in production. Once I got that to fail, I just fixed the bug.

27114 ch31 report find_each bug

---

modules/mobile/app/services/mobile/v0/claims/proxy.rb
modules/mobile/spec/request/individual_claim_request_spec.rb
spec/support/vcr_cassettes/evss/claims/claim_doc_with_errors.yml

If there's an error listed in the EVSS claims response the lib middleware will raise a `EVSS::ErrorMiddleware::EVSSError` which is returned as a 500. PR updates our proxy to catch that error and map it to a 502 so that the app knows the error is from EVSS rather than the mobile API.
department-of-veterans-affairs/va.gov-team#27039

Add EVSS middleware error handling to the mobile claims proxy

---

modules/claims_api/spec/models/veteran/service/user_spec.rb
modules/veteran/app/models/veteran/user.rb

Fixes an issue when a Veteran's POA history contains only a single record.
The structure of this response is an array when there is more than one historical POA record.
However, if the response has only a single record, its unfortunately a hash instead of an array.
https://vajira.max.gov/browse/API-8523

API-8523:     no implicit conversion of Symbol into Integer - ClaimsApi::V1::Forms::PowerOfAttorneyController#submit_form_2122

---

config/settings.yml

Changing email for Flipper now that GCIO email is live.
N/A

GCIO email change for flipper

---

Gemfile

This allows installations of the latest 2.6.x to run vets-api

Relax the version of Ruby required

---

modules/test_user_dashboard/app/controllers/test_user_dashboard/tud_accounts_controller.rb
modules/test_user_dashboard/app/serializers/test_user_dashboard/tud_account_serializer.rb
modules/test_user_dashboard/config/routes.rb
modules/test_user_dashboard/spec/requests/tud_accounts_request_spec.rb
modules/test_user_dashboard/spec/support/spec_users.csv

This change adds routing, business logic, and specs for updating a test account's `notes` field to the TUD module. 
department-of-veterans-affairs/va.gov-team#26884
TUD unit tests have been updated to include the new PUT route; manual testing of reading and updating a tud account's notes via an API client was also done.

[26884] Tud notes logic

---

modules/appeals_api/app/workers/appeals_api/higher_level_review_pdf_submit_job.rb
modules/appeals_api/lib/appeals_api/sidekiq_retry_notifier.rb
modules/appeals_api/spec/lib/sidekiq_retry_notifier_spec.rb

* Added job arguments to notifier output
* Adjusted a few params for HLRPDFSubmitJob to take advantage of the changes
** Also updated the retry notify limits of the job to alert us for longer, should the job error for a while.
https://vajira.max.gov/browse/API-8570

Add job arguments to sidekiq retry notifier output

---

app/models/saved_claim/veteran_readiness_employment_claim.rb
spec/factories/veteran_readiness_employment_claim.rb
spec/models/saved_claim/veteran_readiness_employment_claim_spec.rb

This PR is the backend side of removing two fields from Ch31 frontend form: SSN, and VA File Number. Instead of using the form data, the user object is the desired source going forward.
The related FE PR's are:
- https://github.com/department-of-veterans-affairs/vets-json-schema/pull/616
- https://github.com/department-of-veterans-affairs/vets-website/pull/17783
https://github.com/department-of-veterans-affairs/va.gov-team/issues/26822
I updated the spec so that the ssn and va_file_number are still included in the keys returned from the parsed_form but they are at the end since their values are merged into the form data in `SavedClaim::VeteranReadinessEmploymentClaim#add_veteran_info`

26822 remove ssn and va file number from ch31

---

app/services/bgs/dependency_verification_service.rb
spec/services/bgs/dependency_verification_service_spec.rb

The changes in this code will filter the BGS diaries' dependency_decisions in order to:
- remove duplicate dependents
- remove dependents that are not on award
- remove dependents from being displayed based on award decisions that are in the future
https://github.com/department-of-veterans-affairs/va.gov-team/issues/25790
1. Removed, was an old example that made two assertions:
1. That the first dependency decision (the veteran) had exact keys included, which were different from the dependents.
a. this was removed since the queried veteran was filtered out and never needed in the first place
2. That the total dependency decisions was greater than two.
a. This was arbitrary as there were 4 or 5 in the fixture data.
2. four new examples were added that covered:
``` …
```

25790 dependent verification listing adjustment

---

app/models/saved_claim/dependency_claim.rb

Alters `SavedClaim::DependencyClaim#upload_to_vbms` so it sends the `va_file_number` primarily, and the `ssn` secondarily, if needed.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/21680
Since the VA file number and the SSN were identical in the test data, then there's no need to test implementation details. The form still uploads with using the `va_file_number`.

Send VA file number to VBMS instead of ssn

---

config/initializers/flipper.rb

Since all environments (dev, sandbox, staging, prod) have RAILS_ENV set to "production", the enable_in_development flag currently does not work as intended. This change attempts to remedy that by having flipper check vsp_environment in settings.yml. 
https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/24868

Modify flipper to enforce enable_in_development setting

---

db/migrate/20210713192552_add_veteran_icn_to_claims_api_auto_established_claims.rb
db/schema.rb

Adds a `veteran_icn` column to the `ClaimsApi::AutoEstablishedClaim` table.
[API-8394](https://vajira.max.gov/browse/API-8394)

API-8394 - Add "veteran_icn" column to ClaimsApi::AutoEstablishedClaim table

---

modules/appeals_api/app/workers/appeals_api/notice_of_disagreement_pdf_submit_job.rb
modules/appeals_api/spec/workers/notice_of_disagreement_pdf_submit_job_spec.rb

[API-8595](https://vajira.max.gov/browse/API-8595)
This PR updates our error handling for NOD PDF submit job in accordance with the changes made in HLR PDF Submit job.
It no longer relies on central mail utilities manual retrying of the jobs, but rather hooks into Sidekiqs failure mechanism to automatically retry.

Api 8595/update nod pdf submit job errors b

---

lib/bgs/form674.rb
lib/bgs/form686c.rb
spec/lib/bgs/form674_spec.rb
spec/lib/bgs/form686c_spec.rb
spec/lib/bid/awards/service_spec.rb
spec/support/vcr_cassettes/bid/awards/get_awards_pension.yml

When submitting a Dependents Application (VA Form 21-686c or VA Form 21-674), there are certain use cases that are not able to be processed automatically so we set those statuses to `MANUAL_VAGOV` for manual processing. We have been asked by our partners to add a check to determine whether or not the Veteran is currently receiving pension benefits, and change the claim type label depending on the response.
This PR does the following: if the status is `MANUAL_VAGOV`, call the awards API, then set the claim type based on whether or not the Veteran is currently receiving pension benefits.  Otherwise, use the default claim type label for claims that are not being set to manual.
department-of-veterans-affairs/va.gov-team#27272
This is an update to existing functionality, no new logging or …

Dependents Application Claim Label Adjustment

---

Gemfile.lock

This PR bumps the activerecord_import gem to the latest minor version. After some discovery, The Veteran::VSOReloader job runs at 2:00 everyday (0 2 * * *) and utilizes the activerecord_import gem to do a bulk insert for VSO's.There are 93 Veteran::Service::Organization records in the prod database currently. I think it's necessary to keep this gem until if/when this job becomes old or stale. 
department-of-veterans-affairs/va.gov-team#9482

bump activerecord_import to the latest minor

---

config/locales/exceptions.en.yml

When @Mottie was testing the NOD profile modal in staging he was using bogus numbers and got error messages that were unmapped. 
the phone number `1005551212`  got 
http://sentry.vfs.va.gov/organizations/vsp/issues/6192/events/0825f4b392d945e59e72aa9527f95547/?environment=staging&project=3&query=is%3Aunresolved
the phone number `1987651212` got 
http://sentry.vfs.va.gov/organizations/vsp/issues/6192/events/4783b9b86254441cb2d932839685b65c/?environment=staging&project=3&query=is%3Aunresolved
Apparently the authoritative source for error messages is/was https://github.com/department-of-veterans-affairs/mdm-cuf-person/blob/development/mdm-cuf-person-server/src/inttest/resources/mdm/cuf/person/testData/error_codes.csv but I don't have access or the link changed. …

add additional VA profile error codes

---

lib/pdf_fill/forms/va686c674.rb

When generating a PDF for VA Form 21-686c, the middle initial was not being extracted properly in some places and was causing an error.  This PR adds a fix to extract the middle initial successfully from the full name and print it on the PDF.  
department-of-veterans-affairs/va.gov-team#27639
This is a minor bug fix so no new config/settings have been added.

Updating VA Form 21-686c PDF Generation

---

app/models/vet_info.rb

When submitting a Dependents Application (VA Form 21-686c) we are generating a PDF and uploading it to VBMS.  We recently made a change to use VA File Number as the identifier for uploading instead of SSN.  This works on our local testing environments, however, in staging we are seeing an error that says "Invalid format for Veteran Identifier".  We determined that the error is being caused by the way the response comes back from BGS when we get the file number - instead of a `String`, it is a `Nori::StringWithAttributes`, which is causing the upload to VBMS to fail.  This PR is a small fix that sets the VA File Number to a String.
department-of-veterans-affairs/va.gov-team#27651
This is just a quick fix PR so no new logging or settings have been added.

Updating VA File Number Class Type When Submitting VA Form 21-686c

---

app/models/saved_claim/dependency_claim.rb

Reverts department-of-veterans-affairs/vets-api#7430
@thilton-oddball we are having a weird bug in staging (not dev or test) so we are reverting this for now so testing can continue.
original issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/21680

Revert "Send VA file number to VBMS instead of ssn"

---

app/models/saved_claim/dependency_claim.rb
app/services/bgs/dependent_service.rb
app/workers/bgs/submit_form674_job.rb
app/workers/bgs/submit_form686c_job.rb
spec/jobs/bgs/submit_form674_job_spec.rb
spec/jobs/bgs/submit_form686c_job_spec.rb
spec/services/bgs/dependent_service_spec.rb

When submitting a Dependents Application (VA Form 21-686c), the form submission is processed by a Sidekiq job.  At the end of the job, it generates a PDF and then uploads it to VBMS.  This job was failing when uploading the PDF to VBMS, so this PR moves the PDF job to a different part of the 686c submission workflow.
department-of-veterans-affairs/va.gov-team#27651

Dependents Application PDF Upload to VBMS

---

app/controllers/concerns/authentication_and_sso_concerns.rb
app/workers/after_login_job.rb
spec/jobs/after_login_job_spec.rb

This change updates the gating of TUD-related features in the afterlogin and afterlogout Sidekiq jobs to use the same Settings as the [TUD module's route configuration](https://github.com/department-of-veterans-affairs/vets-api/pull/7404)
department-of-veterans-affairs/va.gov-team#26888
Unit tests updated, manual test of TUD checked-in/checked-out feature

[26888] updates afterlogin and afterlogout job TUD flags to use Settings

---

app/workers/cypress_viewport_updater/cypress_json_file.rb

In reference to some work in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/pull/27779):
This is a quick update to a Sidekiq job that updates a couple of Cypress files in `vets-website` once a month.
This update sets the default width and height in the `config/cypress.json` file. The updated width and height is derived from the top desktop viewport width and height as reported by Google Analytics for the VA.gov property.
I ran this job locally and it successfully submitted a PR with the updated viewport values - https://github.com/department-of-veterans-affairs/vets-website/pull/17985
Previously, the default Cypress viewport was set manually. This PR will allow it to be set automatically based on GA data, once a month.
I didn't commit `Gemfile.lock` because of …

Update default Cypress viewport values in Sidekiq job

---

config/initializers/rack_attack.rb
spec/middleware/rack/attack_spec.rb

- We wish to throttle the publicly exposed Check-in endpoints.
- GET and POST calls to the `/check_in/v0/patient_check_ins` will be throttled by `rack_attack`
- No more than 10 requests per IP will be allowed to hit the endpoints in under a minute. This limit can be changed based on security and business requirements.
department-of-veterans-affairs/va.gov-team#27740

27740 Throttling check_in endpoints

---

config/sidekiq_scheduler.yml
spec/jobs/education_form/process10203_submissions_spec.rb

Changes the frequency the EducationForm::Process10203Submissions job to every 4 hours to avoid having multiple of the same job running at the same time.

Change EducationForm::Process10203Submissions job frequency

---

.github/workflows/pact.yml

Add's dockerhub credentials to pact action. This is to avoid reaching our pull rate limit

add dockerhub creds to pact gha

---

lib/saml/errors.rb
lib/saml/user_attributes/ssoe.rb
spec/lib/saml/ssoe_user_spec.rb

As part of a broader effort to systematically manage how we handle users that have multiple conflicting IDs, this change extends existing checks for conflicting mhv_ids and edipis to also cover birls_ids and corp_ids. The second part of this change will be to implement an automatic monthly report of any users that triggered one of these mismatch errors so that their case can be resolved.
department-of-veterans-affairs/va.gov-team#26795
Unit tests updated, manual login/logout tests performed.

[26795] adds error handling for multiple BIRLS and CORP ids

---

modules/mobile/app/controllers/mobile/v0/folders_controller.rb

Change the folder's useCache to not always be true, allowing the count on folders to update in real-time
department-of-veterans-affairs/va.gov-team#27453
This pairs with a front-end PR to actually solve the issue listed in the ticket. This PR only solves the issue of the backend folders requests ignoring the useCache parameter, which was discovered during the process of solving the issue in the ticket.
For testing, pushed this up to a review instance and mapped it to Postman.
Checked the count in a GET folders
Saved a draft
Checked the count in GET folders again to make sure it incremented when useCache=false

change use cache default

---

lib/debt_management_center/financial_status_report_service.rb

When a user submits an FSR, the "signature" and "date signed" should be sent to the DMC along with the rest of the submission data.
This is a follow-up to [PR #7476](https://github.com/department-of-veterans-affairs/vets-api/pull/7476) where the signature was enabled as a parameter.
Fixes: https://github.com/department-of-veterans-affairs/va.gov-team/issues/27442

Set date on FSR singature

---

config/features.yml
config/settings.yml
lib/bgs/form674.rb
lib/bgs/form686c.rb
spec/lib/bgs/form674_spec.rb
spec/lib/bgs/form686c_spec.rb

Adding a new flipper feature to determine whether or not the 686/674 (Dependents Application) should check if it is a pension claim when we are setting the claim to be manually reviewed.  Currently this feature should only be enabled in staging and not in production.
department-of-veterans-affairs/va.gov-team#28052

Adding New Flipper Feature for 686 Pension Check

---

lib/saml/errors.rb
lib/saml/user_attributes/ssoe.rb
spec/lib/saml/ssoe_user_spec.rb

After a [previous PR](https://github.com/department-of-veterans-affairs/vets-api/pull/7531) added error catching for user logins with multiple BIRLS and CORP ids we have determined users possessing multiple BIRLS ids is a semi-frequent occurrence, as such this PR downgrades the BIRLS SAML error to a warning that is logged to Sentry. 
department-of-veterans-affairs/va.gov-team#26795
Specs updated, manual logins performed.

changes multiple birls ids error to a warning [26795]

---

modules/claims_api/app/controllers/claims_api/v1/forms/disability_compensation_controller.rb
modules/claims_api/spec/requests/v1/disability_compensation_request_spec.rb

We discovered several validations that EVSS would kick our claims back for so we decided to validate them before submitting upstream.
One of those validations is making sure `claimDate` is not in the future.
** Jira is down **

validate claim date

---

app/controllers/v0/disability_compensation_in_progress_forms_controller.rb
spec/request/v0/disability_compensation_in_progress_forms_controller_request_spec.rb

http://grafana.vfs.va.gov/d/000000066/form-526-disability-compensation?orgId=1&from=now-7d&to=now
resuming an in-progress was failing when EVSS is down (nightly). Updating rated disabilities is nice to have but not essential so they should be able to continue if evss errors
department-of-veterans-affairs/va.gov-team#28300

allow vets to resume a 526 form when EVSS is not responding

---

lib/evss/disability_compensation_form/data_translation_all_claim.rb
spec/lib/evss/disability_compensation_form/data_translation_all_claim_spec.rb

EVSS accepts 
> militaryPostOfficeTypeCode:
>   type: “string”
>   enum:
>   - “APO”
>   - “DPO”
>   - “FPO”
and we've seen errors:
>   Invalid value: apo
>   Invalid value: Apo
>   Invalid value: fpo
so, upcase.
department-of-veterans-affairs/va.gov-team#28204

Form 526 - always upcase militaryPostOfficeTypeCode

---

app/models/webhooks/utilities.rb
modules/vba_documents/app/models/vba_documents/upload_submission.rb
modules/vba_documents/spec/request/v2/uploads_request_submission_spec.rb

This PR verifies that the v2_enabled feature flag has been checked before querying the database for v2 tables.
No changes required. This is a fix

Feature flag checking

---

config/settings.yml
config/settings/test.yml
modules/check_in/app/services/chip_api/service.rb
modules/check_in/app/services/chip_api/token.rb
modules/check_in/spec/services/chip_api/request_spec.rb
modules/check_in/spec/services/chip_api/service_spec.rb

- Changing the base URL path for the CHIP API to `dev`. Production configuration files in devops repo will reflect the appropriate value.
department-of-veterans-affairs/va.gov-team#27690

27690 Change URL path for prod prep

---

config/settings.yml
config/settings/test.yml
modules/check_in/app/services/chip_api/service.rb
modules/check_in/app/services/chip_api/token.rb
modules/check_in/spec/services/chip_api/request_spec.rb
modules/check_in/spec/services/chip_api/service_spec.rb
modules/check_in/spec/services/chip_api/token_spec.rb

- Faraday might be using the URI base instead of the additional path
- Adding the base path as config in settings
department-of-veterans-affairs/va.gov-team#28064

28064 address subtle bug

---

modules/appeals_api/app/controllers/appeals_api/metadata_controller.rb
modules/appeals_api/app/controllers/appeals_api/v1/decision_reviews/higher_level_reviews/contestable_issues_controller.rb
modules/appeals_api/app/controllers/appeals_api/v1/decision_reviews/higher_level_reviews_controller.rb
modules/appeals_api/app/swagger/appeals_api/v1/higher_level_reviews_controller_swagger.rb

This PR removes the conditional logic related to our V2 endpoints (now that they are fully rolled out).
https://vajira.max.gov/browse/API-9114

API-9114 - Remove conditional logic around HLR v2 stuff

---

app/models/saved_claim/education_benefits/va_10203.rb
app/workers/education_form/process10203_submissions.rb
spec/jobs/education_form/process10203_submissions_spec.rb
spec/models/saved_claim/education_benefits/va10203_spec.rb

Removed EVSS calls for user POA from 10203 processing.  This was always failing and we think it was contributing to the long runtimes of the processing job.  The removal is behind the `stem_automated_decision` feature flag
department-of-veterans-affairs/va.gov-team#27920

10203 Claim Processing - EVSS POA Removal

---

config/features.yml

Removes the `dashboard_show_dashboard_2` flag as it's no longer needed or referenced in the FE; [all usage was removed in this PR](https://github.com/department-of-veterans-affairs/vets-website/issues/17940)

remove dashboard_show_dashboard_2 flag

---

modules/claims_api/app/controllers/claims_api/v1/application_controller.rb
modules/claims_api/app/controllers/claims_api/v1/forms/disability_compensation_controller.rb
modules/claims_api/app/controllers/claims_api/v1/forms/intent_to_file_controller.rb
modules/claims_api/spec/requests/v1/power_of_attorney_request_spec.rb

Changes to only require Veteran to be in birls if they are submitting a 526 or a 0966. All other interactions only require the Veteran to have a participant_id
https://vajira.max.gov/browse/API-9060

API-9060: Only require birls for 526 and 0966 submission

---

modules/appeals_api/app/models/appeals_api/higher_level_review.rb
modules/appeals_api/app/services/appeals_api/events/appeal_received.rb
modules/appeals_api/spec/services/appeals_api/events/appeal_received_spec.rb

Fix to use the proper personalization keys keys for the email template VANotify uses to send our HLR received emails
https://vajira.max.gov/browse/API-8966

Fix HLR VaNotify service call

---

lib/sentry/processor/pii_sanitizer.rb
spec/lib/sentry/processor/pii_sanitizer_processor_spec.rb

After adding some [additional logging to identify users with duplicate IDs](http://sentry.vfs.va.gov/organizations/vsp/issues/44529/?environment=production&project=3&project=4&query=is%3Aunresolved+User+attributes+contain+multiple+distinct&statsPeriod=14d), @bosawt noticed that the `va_eauth_gcIds` field was not sanitized and contained information, such as BIRLS IDs, that were supposed to be sanitized. This PR updates the sanitizer to scrub the `va_eauth_gcIds` field.
department-of-veterans-affairs/va.gov-team#26795
Unit tests updated to test for `va_eauth_gcIds` field.

updates sanitzer to scrub va_eauth_gcIds

---

modules/appeals_api/config/schemas/v2/200996.json

[API-9148](https://vajira.max.gov/browse/API-9148)
This PR adjusts the regex pattern for areaCodes for HLRv2. 
We still limit the area code to 3 characters, but allow for any digit to be present in the pattern.

allowing any digit in the 3 digit area code

---

modules/vba_documents/spec/models/upload_submission_spec.rb

Very rarely a spec test would fail because of timing issues. This PR freezes timestamps so the timestamps will always be what we expect of them.
https://vajira.max.gov/browse/API-8996
No to all
The spec file in question was tested multiple times

Timecop freeze instead of Timecop travel to have expected timestamps

---

app/controllers/openid_application_controller.rb
modules/veteran_verification/app/controllers/veteran_verification/application_controller.rb

OpenId modules use hashed access_tokens as redis keys for user information. Remove any unhashed access token redis lookups.
https://github.com/department-of-veterans-affairs/vets-api/pull/7561

Remove Rolling  unhashed access_token lookup

---

config/settings.yml
spec/lib/caseflow/configuration_spec.rb
spec/lib/decision_review/configuration_spec.rb

Ideally, caseflow would respond fast, but I think we should give vets the option to wait for the response.
department-of-veterans-affairs/va.gov-team#28676

raise caseflow timeout

---

Gemfile.lock

This reverts commit b55d38d48f990fc21412ecb2ed0d94cf3e5b3390.
The gem update may have introduced a breaking change related to the way that we use headless policies. The changelog says that there was a breaking change introduced related to the policy return value and it looks like it may apply to us. It also seems like there’s quite a few Sentry errors related to pundit/access over the weekend. We use the headless policies https://github.com/varvet/pundit#headless-policies https://github.com/department-of-veterans-affairs/vets-api/tree/master/app/policies.
Reverting until this change is understood 

Revert "Bump pundit from 2.1.0 to 2.1.1 (#7641)"

---

modules/claims_api/app/controllers/claims_api/v1/forms/disability_compensation_controller.rb
modules/claims_api/app/swagger/claims_api/v1/swagger.json
modules/claims_api/config/schemas/526.json
modules/claims_api/spec/requests/v1/disability_compensation_request_spec.rb

Adds logic to validate that the `servicePay` attribute provided in a Form526 submission meet EVSS expectations.
**EVSS expectations**
```
'receiving' and 'willReceiveInfuture' cannot have the same value if they are not null
For "Currently receiving military retired pay" and "Will receive military retired pay in the future" fields, the only valid combinations are "True/False" or "False/True"
```
[API-9012](https://vajira.max.gov/browse/API-9012)

[API-9012] - Adds EVSS validation checks for Form526 "servicePay" attributes

---

config/initializers/rack_attack.rb
spec/middleware/rack/attack_spec.rb

This reverts commit d1de315fb63ad7f57b32af929552df268b1ce230.
This is causing 429's for the facility locator. Reverting and further debugging needed

Revert "rate-limit PPMS lookup to curb abuse (#7664)"

---

config/initializers/rack_attack.rb
spec/middleware/rack/attack_spec.rb

In response to ongoing DOS activity against the Facility Locator remote Bing Maps lookup.
Please see https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/2021-08-16-facility-locator-possible-DOS.md for add'l details.
Now with `remote_ip`, because we're behind an ELB.

rate-limit PPMS lookup to curb abuse (REDUX)

---

modules/vaos/app/controllers/vaos/v2/appointments_controller.rb
modules/vaos/app/serializers/vaos/v2/vaos_serializer.rb

The work represents a temporary update to the appointment endpoints to facilitate testing of the vaos 2.0 service endpoints.
The original FastJsonApi serializer will be reinstated as part of the work in Zenhub ticket #28798

Appointment endpoints no longer use the FastJsonApi serializer

---

config/settings.yml
config/settings/test.yml
modules/check_in/app/services/chip_api/request.rb
modules/check_in/spec/services/chip_api/request_spec.rb

- Adding breakers, service_name, request and response type(JSON) to the Faraday connection.
department-of-veterans-affairs/va.gov-team#28785

28785 update faraday connection

---

app/services/medical_copays/vista_account_numbers.rb

- Assert padding for vista account id is at least 0
[Sentry Error](http://sentry.vfs.va.gov/organizations/vsp/issues/56248/?environment=production&project=3&query=medical_copays&statsPeriod=14d)
- Temp fix until we can recognize the structure of prod data

Temporary fix for negative argument error

---

.github/CODEOWNERS
.rubocop.yml
Gemfile
Gemfile.lock
config/routes.rb
config/settings.yml
modules/dhp_connected_devices/.rubocop.yml
modules/dhp_connected_devices/Gemfile
modules/dhp_connected_devices/README.rdoc
modules/dhp_connected_devices/Rakefile
modules/dhp_connected_devices/bin/rails
modules/dhp_connected_devices/config/routes.rb
modules/dhp_connected_devices/dhp_connected_devices.gemspec
modules/dhp_connected_devices/lib/dhp_connected_devices.rb
modules/dhp_connected_devices/lib/dhp_connected_devices/engine.rb
modules/dhp_connected_devices/lib/dhp_connected_devices/version.rb
modules/dhp_connected_devices/spec/spec_helper.rb
spec/simplecov_helper.rb
spec/spec_helper.rb

This PR scaffolds the DHP Connected Devices module. We needed to make a tweak to `spec/simplecov_helper.rb` because `rails generate module` updates that file and causes the linting CI step to fail. We also set the CODEOWNERS to the digital health platform team. 
Collaboration Cycle Kickoff: https://github.com/department-of-veterans-affairs/va.gov-team/issues/34264
IA Request from Digital Health Platform team: https://github.com/department-of-veterans-affairs/va.gov-team/issues/35290
N/A

DHP-92 Scaffold dhp connected devices module

---

app/models/inherited_proofing/mhv_identity_data.rb
config/redis.yml
spec/factories/inherited_proofing/mhv_identity_data.rb
spec/models/inherited_proofing/mhv_identity_data_spec.rb

This PR creates a redis-backed model to temporarily store MHV inherited proofing data. This will be used as part of the larger inherited proofing initiative which involves storing data retrieved via API from MHV and forwarding that data to Login.gov
https://github.com/department-of-veterans-affairs/va.gov-team/issues/35657

Mhv identity model 35659

---

modules/appeals_api/app/swagger/appeals_api/v1/notice_of_disagreements_controller_swagger.rb

Learned that a deprecated key is necessary for each endpoint in swagger blocks to complete the process.
[Ticket](https://vajira.max.gov/browse/API-13787)

API-13787 Add deprecate key to swagger blocks for nod v1

---

lib/va_profile/models/base_address.rb
spec/lib/va_profile/models/address_spec.rb

Remove international post code as a required field when adding or updating an address.
See ticket [#40324](https://github.com/department-of-veterans-affairs/va.gov-team/issues/40324) for more information.
* The validation is dependent on the `profile_do_not_require_international_zip_code` feature flag.  If the flag is on, international postal code is not required.  If the flag is off, international postal code is required.

Remove validation of international postal code

---

lib/debt_management_center/payments_service.rb
lib/debt_management_center/workers/va_notify_email_job.rb

PII being logged in Sentry statements that is unnecessary for the specific errors.
[- department-of-veterans-affairs/va.gov-team-sensitive#666](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/666)
- Assure RSpec passes
- Errors will not break with removed attributes
N/A
Logging

Remove PII attributes from being logged in sentry

---

db/migrate/20221214161602_add_backup_submitted_claim_id_to_form526submissions.rb
db/schema.rb

- This will add a column to the Form526Submission table (adding the `backup_submitted_claim_id` attribute to the Form526Submission model)
- This new field is to keep track of 526 submissions that end up going the backup/paper submission route. For all claims that get successfully established via the mail EVSS route, this field will be `nil`, for claims that get PDFs generated and send to Central Mail (through Lighthouse Benefits Intake API), this field will be the returned CMP ID returned from the LH BI API `upload` endpoint) https://developer.va.gov/explore/benefits/docs/benefits?version=current
https://github.com/department-of-veterans-affairs/va.gov-team/issues/50111
https://github.com/department-of-veterans-affairs/vets-api/pull/11317
- Testing covered in other related PRs rpec tests …

Pulling DB stuff into it's own PR

---

app/models/mpi_data.rb
app/models/user_session_form.rb
app/services/sign_in/attribute_validator.rb
lib/mpi/constants.rb
lib/mpi/errors/errors.rb
lib/mpi/responses/add_person_response.rb
lib/mpi/service.rb
lib/mpi/services/add_person_response_creator.rb
modules/claims_api/spec/requests/v1/disability_compensation_request_spec.rb
spec/controllers/v0/sign_in_controller_spec.rb
spec/lib/mpi/responses/add_person_response_spec.rb
spec/lib/mpi/service_spec.rb
spec/lib/mpi/services/add_person_response_creator_spec.rb
spec/models/mpi_data_spec.rb
spec/models/user_session_form_spec.rb
spec/services/sign_in/attribute_validator_spec.rb
spec/support/vcr_cassettes/mpi/add_person/add_person_internal_error_request.yml
spec/support/vcr_cassettes/mpi/add_person/addadd_person_already_exists_person_success.yml
spec/support/vcr_cassettes/mpi/add_person/update_profile_server_error.yml
spec/support/vcr_cassettes/mpi/add_person_internal_error_response.yml
spec/support/vcr_cassettes/spec/support/mpi/add_person_internal_error_response.yml

- This PR refactors the `MPI::Service.new.add_person_implicit_search` function, so that instead of taking a `UserIdentity` object, the function now takes a series of attributes
- As further refactors, the rest of the functions in `MPI::Service will be refactored shortly
- department-of-veterans-affairs/vets-api#11329
- I removed a mocked user for user228, then authenticated with loa3 idme sign in service: `localhost:3000/v0/sign_in/authorize?type=idme&code_challenge_method=S256&acr=loa3&client_id=mobile&code_challenge=1BUpxy37SoIPmKw96wbd6MDcvayOYm3ptT-zbe6L_zM=`
- Confirmed successful add person log: `[MPI][Services][AddPersonResponseCreator] add_person_implicit, icn=1234567891V123456, idme_uuid=, logingov_uuid=, transaction_id=f8ba53155f0b607c07bbeb02`
- Authentication

[11329] Refactoring MPI Service add_person_implicit_search

---

modules/claims_api/app/swagger/claims_api/v2/dev/swagger.json
modules/claims_api/app/swagger/claims_api/v2/production/swagger.json
spec/support/schemas/claims_api/v2/veterans/claims/claim.json

- Updates schema documentation to clarify the available list of values.
- [API-23284](https://vajira.max.gov/browse/API-23284)
- [API_18165](https://vajira.max.gov/browse/API-18165)
- 
- [test rswag before merging](https://community.max.gov/display/VAExternal/Test+rSwag+docs+before+merging)
vets-api

Adds tracked items status to oas

---

modules/forms_api/app/controllers/forms_api/v1/uploads_controller.rb

Note: `form_id` is a parameter defined in the vets-website code. The user cannot change it and thus cannot contain PII, PHI, or anything compromising.
- Add identifying tag to active trace
- https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/263
- Need to test in deployed env
Forms submitted via forms_api (currently none in prod)

Forms api: set tag with form_id on active traces

---

.github/CODEOWNERS

The new codeowners file was generated with from the platform-codeowners database. 
- department-of-veterans-affairs/va.gov-team#62715
- [platform codeowners repo](https://github.com/department-of-veterans-affairs/platform-codeowners)

Generated new codeowners file from platform-codeowners database

---

modules/claims_api/app/controllers/claims_api/v2/veterans/disability_compensation_controller.rb
modules/claims_api/lib/claims_api/v2/disability_compensation_evss_mapper.rb
modules/claims_api/lib/claims_api/v2/disability_compensation_pdf_mapper.rb
modules/claims_api/spec/lib/claims_api/v2/disability_compensation_pdf_mapper_spec.rb

- Allow retrying a submission if EVSS fails
- Add logging around the EVSS mapper
- Fix alternateNames (must now be an array)
- Allow a nil zipLastFour
- [API-28294](https://jira.devops.va.gov/browse/API-28294)
- `rspec`
- POST local /services/claims/v2/veterans/:icn/526
It takes a bit, but should give you a 200. If you don't it the "too many EP code" issue, you should be able to look in the [dsva-vetsgov-sandbox-evss](https://us-gov-west-1.console.amazonaws-us-gov.com/s3/buckets/dsva-vetsgov-sandbox-evss) bucket for the LH claim UUID and find the generated PDF.
V2 526 submissions

Api 28294 cleanup part 1

---

app/controllers/v0/profile/direct_deposits/disability_compensations_controller.rb

Add SSO logging for C&P direct deposit updates.
Original ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/64875

Add SSO logging to CnP direct deposit updates

---

app/models/prescription_details.rb
app/swagger/swagger/schemas/health/prescriptions.rb
modules/my_health/app/controllers/my_health/v1/prescriptions_controller.rb
modules/my_health/app/serializers/my_health/v1/prescription_details_serializer.rb
modules/my_health/spec/request/v1/prescriptions_request_spec.rb
spec/support/schemas/my_health/prescriptions/v1/prescription_details.json
spec/support/schemas_camelized/my_health/prescriptions/v1/prescription_details.json
spec/support/vcr_cassettes/rx_client/prescriptions/gets_a_sorted_by_custom_field_list_of_all_prescriptions_v1.yml

Updated the logic for sorting by dispensed date and added new field 'sortedDispensedDate' to be used on front end.
[Sorting issue](https://jira.devops.va.gov/browse/MHV-49233)
> Last Fill First sorting is incorrect. Currently we are showing the first fill as what we are sorting for the last filled first but it should be the last fill date that we are sorting on. 
- Locally Tested
- Created new test 
- Ran tests locally
Sorting by llast_dispensed_date was out of order
*Describe the steps required to verify your changes are working as expected. Exclusively stating 'Specs run' is NOT acceptable as appropriate testing*
Visit medication list all page, expect dates to be in desc order …

Fix sorting on RX Index page

---

lib/sidekiq/form526_backup_submission_process/submit.rb

- Previously approved, resubmitting after PII git history cleaning
- bumps retries for our form 526 backup submission worker to 14, bringing it inline with our established paradigm
- [ticket](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/70888)
- Class instantiation is sufficient to ensure continuity
Form 526 submissions backup path

[DBX-70888] bump 526 backup retries to 14

---

modules/claims_api/app/controllers/concerns/claims_api/v2/disability_compensation_validation.rb

- Updates validation method `type_of_date_format?` to remove the question mark, as Ruby conventions generally reserve such usage for methods returning a boolean.
[API-32002](https://jira.devops.va.gov/browse/API-32002)
- Postman validation testing
- Ran rspec tests
modules/claims_api/app/controllers/concerns/claims_api/v2/disability_compensation_validation.rb

API-32002 Update method name to follow Ruby conventions

---

modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb
modules/simple_forms_api/spec/requests/v1/uploads_spec.rb

This PR makes use of the `MetadataValidator` previously introduced in [this commit](https://github.com/department-of-veterans-affairs/vets-api/commit/a1df17cb0f099ca0a40db74e18508846ff581c17). It calls the validator on the metadata that we construct in the Simple Forms API and will hopefully result in more errors being surfaced sooner.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/70638
Automated tests updated to confirm that we always call this when submitting forms.
Currently only the Simple Forms API but it is intended to be more widely applicable.
(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. …

Use the MetadataValidator in the simple forms uploads controller

---

config/features.yml

- Remove the Yellow Ribbon MVP enhancement feature flag that does not appear to be used
- I work for the VA.gov Iterate, Innovate, and Run (IIR) Team
- [VA-IIR 165](https://app.zenhub.com/workspaces/va-iir-6508c0bd79e64e0fb5855caf/issues/gh/department-of-veterans-affairs/va-iir/165)
- Checked `http://localhost:3000/flipper/features` to make sure the yellow_ribbon_mvp_enhancement flag is no longer listed
This should not impact any areas of the site since the feature flag is not being used.

Remove yellow_ribbon_mvp_enhancement feature flag

---

modules/simple_forms_api/app/services/simple_forms_api/pdf_stamper.rb
modules/simple_forms_api/spec/fixtures/form_json/vba_21_4142_resubmission.json
modules/simple_forms_api/spec/requests/v1/uploads_spec.rb

This PR is useful _only_ for our resubmission process for 21-4142 (to be completed by EOD tomorrow, Tuesday, hopefully). It handles forms that get passed in with an extra piece of data, `'in_progress_form_created_at'`. If a 21-4142 form has this flag set to something, then the stamper will add an extra date stamp (see screenshot below).
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/71085
Tested locally and lookin' good 😎 

Simple forms - 21-4142 - handle date stamp for resubmission

---

db/migrate/20231124170404_add_access_token_attributes_to_service_account_configs.rb
db/schema.rb

This PR adds the `access_token_user_attributes` column to the `service_account_configs` table, allowing us to validate claims provided by a service account as part of the assertion used to obtain service account access tokens.
- department-of-veterans-affairs/va.gov-team#70537
- Verify migration runs successfully.
- Verify new column is added with specified default.
Not relevant.
This impacts service account authentication.
No additional feedback requested.

[70537] Add access_token_user_attributes to service_account_configs

---

.github/CODEOWNERS

Semi-recently, team Banana Peels was added as codeowner to a large number of files and folders that they are not responsible for nor own. This has caused multiple teams to be blocked by the unnecessary need for Banana Peels' PR approval.
NOTE: The CODEOWNERS error does not seem to be related to this commit.
I did my best to go through and look at the commit history of any entry I changed to see if Banana Peels had historically had a hand in them. I tried to be conservative with the changes.
* https://dsva.slack.com/archives/C053U7BUT27/p1701369389899689
* https://dsva.slack.com/archives/CBU0KDSB1/p1697466964935119
* https://github.com/department-of-veterans-affairs/vets-api/pull/13963/files

Remove Banana Peels from Codeowners entries

---

app/models/sign_in/service_account_access_token.rb
app/models/sign_in/service_account_config.rb
app/services/sign_in/constants/service_account_access_token.rb
app/services/sign_in/service_account_access_token_jwt_decoder.rb
app/services/sign_in/service_account_access_token_jwt_encoder.rb
db/seeds/development.rb
spec/factories/sign_in/service_account_access_tokens.rb
spec/factories/sign_in/service_account_configs.rb
spec/models/sign_in/service_account_access_token_spec.rb
spec/models/sign_in/service_account_config_spec.rb
spec/services/sign_in/service_account_access_token_jwt_decoder_spec.rb
spec/services/sign_in/service_account_access_token_jwt_encoder_spec.rb

This PR validates the contents of the `access_token_user_attributes` field to ensure that only allowed values are set.
- department-of-veterans-affairs/va.gov-team#70539
- Use the Rails console to load a service account config.
```ruby
config = SignIn::ServiceAccountConfig.last
```
- Attempt to store an invalid value (`['foobar'] }`)
```ruby
config.access_token_user_attributes = ['foobar']
```
- Verify the validation fails.
- Attempt to store a valid value (`['icn']`)
```ruby
config.access_token_user_attributes = ['icn']
```
- Verify the validation succeeds.
Not relevant.
This PR impacts service account authentication.
(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, …

[70539] Validate access_token_user_attributes for service_account_configs

---

app/models/sign_in/service_account_access_token.rb
app/services/sign_in/assertion_validator.rb
app/services/sign_in/service_account_access_token_jwt_decoder.rb
app/services/sign_in/service_account_access_token_jwt_encoder.rb
spec/controllers/v0/sign_in_controller_spec.rb
spec/factories/sign_in/service_account_access_tokens.rb
spec/models/sign_in/service_account_access_token_spec.rb
spec/services/sign_in/assertion_validator_spec.rb
spec/services/sign_in/service_account_access_token_jwt_decoder_spec.rb
spec/services/sign_in/service_account_access_token_jwt_encoder_spec.rb

This PR allows service accounts to pass a `user_attributes` claim in the assertion used to request a service account access token which will then be included in the generated access token. Some endpoints that use service account authentication (such as the in-progress MAP STS endpoint) require additional attributes about a user to perform a given action; this PR provides a mechanism for service accounts to provide that information and for the endpoints to retrieve it from the service account access token.
- department-of-veterans-affairs/va.gov-team#70023
- Open the Rails console and generate an assertion.
```ruby
private_key = OpenSSL::PKey::RSA.new(
File.read('spec/fixtures/sign_in/sample_service_account.pem')
)
payload = {
'iss' => 'http://localhost:3001',
'sub' => …
```

[70023] Allow user_attributes claim for service account access tokens

---

modules/va_forms/app/models/va_forms/form.rb

Updates sorting of outputs when searching by form number so that deleted versions of forms come _after_ non-deleted versions.
Since there may also be multiple _current_ versions of forms with the same name (because the language or the suffix (a, b, etc.) may vary), this also sorts results by the `title` after the `name`. This tends to have the effect of putting spanish versions after english versions when the `language` attribute of the form is incorrectly set to `en` for spanish, because their titles tend to be along the lines of "form name (espanol)" vs the original "form name".
**Here are some examples that I tried out in the staging console:**
Form 10-493b (which initiated this change) - previously, the deleted result was first, followed by the Spanish version, followed by the current …

API-31525 Update default sorting of results in VA Forms API

---

lib/medical_records/client.rb
spec/support/vcr_cassettes/mr_client/get_a_list_of_clinical_notes.yml

I updated the loinc code for care summaries and notes/physician procedure notes to 11506-3. This was based on advice received from @JohnMoehrke after he did work on mapping coordination with KBS. The loinc code was previously 11505-5. 
- Unit tests were updated with the new loinc code (11506-3)
No UI changes. 
MHV medical records - care summaries and notes
AC1 Make sure all the fields listed in the comments are mapped appropriately
AC2 Don't access the contained[] resources directly – do a lookup via performer/reaction respectively (see allergy for reference).

MHV-48196: Physician procedure note loinc updated

---

lib/periodic_jobs.rb

- Deletes the CentralMail::DeleteOldClaims cron registery so that we stop deleting old claims that may need remediation.

deregistering job that is deleting old CM claims v2

---

.github/CODEOWNERS
lib/common/client/configuration/base.rb
modules/check_in/app/services/v2/chip/client.rb
spec/sidekiq/evss/disability_compensation_form/submit_form526_all_claim_spec.rb

Addition to https://github.com/department-of-veterans-affairs/vets-api/pull/14552/files#diff-d09ea66f8227784ff4393d88a19836f321c915ae10031d16c93d67e6283ab55f
* update `ClientError` to `ServerError`
* `body` should be `response_body` in this context, but tests aren't properly catching issue

Faraday 1.10 Patch

---

lib/va_profile/prefill/military_information.rb
spec/lib/va_profile/prefill/military_information_spec.rb
spec/support/vcr_cassettes/va_profile/military_personnel/service_history_200_many_episodes_dup_end.yml

We are noticing an issue with sorting nil end dates. This sorts the nil end dates as the most recent.

sorting for nil end dates

---

modules/appeals_api/app/models/concerns/appeals_api/model_validations.rb
modules/appeals_api/spec/models/supplemental_claim_spec.rb

We decided to allow retrieve evidence end dates to be on or before the submission date.  Occasionally, we get vets that visits a medical provider and files a supplemental claim on the same day.  It's not clear where the original restriction(had to be before submission date) came from, we think it was added just as a sanity check, but after considering the situation, this seems like a reasonable change.
Team banana peels, we own this code
Original ticket that introduced the rule:
https://jira.devops.va.gov/browse/API-17448
Ticket for this change:
https://jira.devops.va.gov/browse/API-31707
- Unit test coverage
*Supp Claims evidence retrieval start date and end date validation

Allow same day as submission treatment dates

---

lib/simple_forms_api_submission/metadata_validator.rb
spec/lib/simple_forms_api_submission/metadata_validator_spec.rb

This PR improves the metadata validator by running strings through `I18n.transliterate` before conforming to the strict regex required by Lighthouse. The transliteration involves converting letters like `ö` to `o` or `ñ` to `n` instead of just stripping them as the prior implementation would have done.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/71306
Test updated to exercise `ö` converting to `o`.
So far just Simple Forms API.

Use I18n.transliterate in metadata validator

---

app/controllers/v0/rated_disabilities_controller.rb
app/controllers/v0/rated_disabilities_discrepancies_controller.rb

Uses new Traceable concern to tag rated disability controllers so their spans will be categorized appropriately in Datadog.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/66141

Adds trace service tags for disability rating endpoints

---

Gemfile
Gemfile.lock

Octokit was originally held back [here](https://github.com/department-of-veterans-affairs/vets-api/pull/8948) because Faraday was behind. We should be able to catch up now

Remove oktokit hold and bump

---

Gemfile.lock

Bump Betamocks to new version after [this](https://github.com/department-of-veterans-affairs/betamocks/pull/62) PR

Bump Betamocks -> 0.11.0

---

db/migrate/20231207022742_create_form_submissions.rb
db/migrate/20231207022820_create_form_submission_attempts.rb
db/schema.rb

This pulls out the database changes required for saving form submissions and form submission attempts from [this, old, PR](https://github.com/department-of-veterans-affairs/vets-api/pull/14798). The related model changes for this PR [are here](https://github.com/department-of-veterans-affairs/vets-api/pull/14802). Looks like we have protections against combining database changes and other application changes in one PR, so it's isolated here.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/71336

Database changes for adding form submission models

---

modules/mobile/app/controllers/mobile/v0/claims_and_appeals_controller.rb
modules/mobile/spec/request/claims_and_appeals_overview_request_spec.rb

Adds in appeals to claims count for mobile
- [department-of-veterans-affairs/va.gov-team#7468](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/7468)
Changed test to check claims + appeals count
meta description of single mobile endpoint

Mobile: Add in appeals to claims count

---

config/locales/exceptions.en.yml
lib/medical_records/client.rb
lib/medical_records/patient_not_found.rb
modules/my_health/app/controllers/my_health/v1/allergies_controller.rb
modules/my_health/app/controllers/my_health/v1/vaccines_controller.rb
spec/lib/medical_records/client_spec.rb

When a user accesses their FHIR records for the first time, their patient record has not yet been created. The FHIR server returns a specific 500-error in this case. In the frontend, if we receive this response, we poll the backend until we stop getting that error.
Previously we were translating that 500 error into a 404. This PR changes it to be a 202. It is an expected part of the application flow, so should not be an error.
Also made some general error-handling improvements.
Frontend Component: https://github.com/department-of-veterans-affairs/vets-website/pull/27005
> Change vets-api response for Patient Record Not Found
> 
> When a patient's records are accessed for the first time, they will not have a Patient Record until it is created. During that time, the backend will return …

MHV-51341 Change 404 status to 202 when Patient record is not ready

---

Gemfile.lock

This updates the vets-json-schema, where there were updates to the appeals (v1) schemas to remove the timezone enums — it was causing issues because it needed to be updated after Lighthouse updated their timezone schemas and we decided for better maintainability we would just rely on Lighthouse to validate the timezone value. 
> Which team do you work for
Benefits Decision Reviews
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/70429
- Manual tests locally — went through each form and confirmed I could submit them all. I even hard coded the original timezone (`America/Ciudad_Juarez`) into the frontend to make sure that it could submit and it did.
**NOTE**: I'm not sure that it'll be a huge issue once we switch to v2 NOD, but v1 NOD is still being used and _that_ …

[DR-70429] update vets-json-schema to use version with timezone enums removed

---

config/features.yml
modules/mobile/app/controllers/mobile/v0/claims_and_appeals_controller.rb
modules/mobile/app/controllers/mobile/v0/decision_letters_controller.rb
modules/mobile/spec/request/claims_and_appeals_overview_request_spec.rb
modules/mobile/spec/request/decision_letters_request_spec.rb

this adds logs to determine if the flag `decisionLetterSent` in a claim, always matches up with a decision letter. This is two different logs that will have to be done manually by taking both logs and comparing the user icn or uuid and matching up the counts of letters
https://github.com/department-of-veterans-affairs/va-mobile-app/issues/7234
(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific …

mobile - adds logging to claims and decisions letters

---

app/sidekiq/bgs/flash_updater.rb
app/sidekiq/evss/disability_compensation_form/submit_uploads.rb
app/sidekiq/evss/disability_compensation_form/upload_bdd_instructions.rb
lib/sidekiq/form526_job_status_tracker/job_tracker.rb
spec/lib/sidekiq/form526_job_status_tracker/job_tracker_spec.rb
spec/sidekiq/bgs/flash_updater_spec.rb
spec/sidekiq/evss/disability_compensation_form/submit_uploads_spec.rb
spec/sidekiq/evss/disability_compensation_form/upload_bdd_instructions_spec.rb

- add / update / homogenize on-exhaustion hooks for 526 related sidekiq async jobs.  This allows for logs that can be aggregated on in Datadog, as well as the addition of stats D metrics.
- [PR 1 of 2](https://github.com/department-of-veterans-affairs/vets-api/pull/14737)
- [ticket](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/67288)
- added RSpec tests
- manual click through and instantiation
- 526 Async submission

Add exhaustion logging for 526 jobs (2 of 2)
