config/features.yml

Adds a feature flag for Project Cheetah discovery work
department-of-veterans-affairs/va.gov-team#17412

Add feature flag for VAOS Project Cheetah

---

modules/va_forms/app/serializers/va_forms/form_detail_serializer.rb
modules/va_forms/app/serializers/va_forms/form_list_serializer.rb

Removing the filter now that the downloaded pages have been published.
https://vajira.max.gov/browse/API-4164

Uncommenting forms_url so that va.gov Forms team can feature test

---

config/routes.rb

Adding routes for appeals notice of disagreement endpoints
- contestable_issues#index
- notice_of_disagreements#create
- notice_of_disagreements#show
https://vajira.max.gov/browse/API-4208

Add NOD routes to vets-api

---

config/locales/exceptions.en.yml
lib/common/exceptions/detailed_schema_errors.rb
modules/appeals_api/app/controllers/appeals_api/v1/decision_reviews/notice_of_disagreements_controller.rb
modules/appeals_api/app/models/appeals_api/notice_of_disagreement.rb
modules/appeals_api/config/locales/en.yml
modules/appeals_api/lib/appeals_api/form_schemas.rb
modules/appeals_api/spec/fixtures/invalid_10182.json
modules/appeals_api/spec/fixtures/schema_error_schema.json
modules/appeals_api/spec/models/notice_of_disagreement_spec.rb
modules/appeals_api/spec/requests/v1/notice_of_disagreements_controller_spec.rb
spec/fixtures/json/detailed_schema_errors_schema.json
spec/lib/common/exceptions/detailed_schema_errors_spec.rb

Changed NOD error handling to follow [JSON API 1.0 ErrorObject](https://jsonapi.org/format/1.0/#error-objects) formatting.
Extracted json schema errors out into the Common::Exceptions::DetailedSchemaErrors class which currently supports:
* Invalid enum values (adds `meta` details of the allowed values)
* Pattern mismatches (adds `meta` details of the expected regex)
* Missing required fields (adds `meta` details of the missing fields)
* Data type mismatch (e.g. expected boolean, got string)
* Maximum & minimum lengths (adds `meta` details of the min/max lengths)
* Range outliers (adds `meta` details of the min/max allowed for the range)
* Extra data provided that is not in the schema
* Invalid Arrays of items (adds `meta` details about size constraints & uniqueness)
* Error titles & …

API-3182 JSON Schema Errors

---

config/features.yml

Add a feature toggle for the front-end to show multiple address fields for the veteran on the 10-10EZ. Also updated a typo from my previous feature toggle description.

Add multiple_address_10_10ez feature toggle

---

config/settings.yml

- Adding myself to Flipper admin
department-of-veterans-affairs/va.gov-team#17943

Add Dillo Raju to flipper admin

---

app/models/in_progress_form.rb
app/services/form_durations/all_claims_duration.rb
app/services/form_durations/custom_duration.rb
app/services/form_durations/standard_duration.rb
app/services/form_durations/worker.rb
config/features.yml
spec/models/in_progress_form_spec.rb
spec/services/form_durations/all_claims_duration_spec.rb
spec/services/form_durations/custom_duration_spec.rb
spec/services/form_durations/standard_duration_spec.rb
spec/services/form_durations/worker_spec.rb

- Implement custom expiration for save-in-progress forms.
- The entire feature is on a Flipper: in_progress_form_custom_expiration.
- Existing production forms will not be impacted until feature flip is enabled.
- We want the Questionnaire List form for the Health Care team to start testing the custom expiration ability in the staging environment to begin with.
department-of-veterans-affairs/va.gov-team#17206
- The entire feature is on a Flipper: in_progress_form_custom_expiration.
- RSpec tests written and passing
-  Manual local testing

custom expiration for in_progress_form

---

db/schema.rb
modules/claims_api/db/migrate/20201231033748_add_bgs_special_issues_responses_column_to_auto_established_claims.rb

Adds necessary database migration for future work.
https://vajira.max.gov/browse/API-3277
Migration ran against local environment.

API-3277: [database schema] Special Issues - Track the successes for special issues by claim

---

app/workers/evss/disability_compensation_form/submit_form526.rb
lib/evss/disability_compensation_form/service.rb
lib/evss/disability_compensation_form/service_unavailable_exception.rb
spec/jobs/evss/disability_compensation_form/submit_form526_all_claim_spec.rb
spec/lib/evss/disability_compensation_form/service_spec.rb

retry 526 form submissions when we receive a 503 service unavailable error
http://sentry.vfs.va.gov/organizations/vsp/issues/509/events/bd8bea7dcf6345f0bcc17ed58256e8dd/?project=3&statsPeriod=14d
https://github.com/department-of-veterans-affairs/va.gov-team/issues/13949

retry 526 form submissions when we receive a 503 error

---

modules/appeals_api/app/swagger/appeals_api/v1/notice_of_disagreements_controller_swagger.rb
modules/appeals_api/app/swagger/appeals_api/v1/schemas/notice_of_disagreements.rb
modules/appeals_api/config/schemas/10182.json
modules/appeals_api/config/schemas/10182_headers.json

Copy updates to NOD swagger documentation
[4222](https://vajira.max.gov/browse/API-4222)
[3725](https://vajira.max.gov/browse/API-3725)

API-4222/3725 character limits and copy changes

---

modules/claims_api/app/models/claims_api/auto_established_claim.rb
modules/claims_api/app/workers/claims_api/special_issue_updater.rb
modules/claims_api/spec/workers/special_issue_updater_spec.rb

Handles storing errors onto the AutoEstablishedClaim database record.
https://vajira.max.gov/browse/API-3277
Updated existing and added new specs

API-3277: [logic] Special Issues - Track the successes for special issues by claim

---

modules/claims_api/app/swagger/claims_api/description/v0.md
modules/claims_api/app/swagger/claims_api/description/v1.md
modules/claims_api/app/swagger/claims_api/forms/form_526_example.json

Add some basic documentation regarding special issues.
Also adds example special issues to the example curl request within our documentation.
https://vajira.max.gov/browse/API-3270
Viewed in developer portal locally.

API-3270: Special Issues - Portal documentation for any new / changed features from consumer standpoint

---

config/settings.yml

Add new Flipper admin user to settings.yml.  This is to assist VSA Healthcare-Experience team in determining regression-testing needs for their implementation of custom expiration date for save-in-progress forms [see ticket link below].
https://github.com/department-of-veterans-affairs/va.gov-team/issues/17206
This is a non-functional settings change, but if some kind of local testing's still required please do let me know.

Add tze@adhocteam.us to Flipper admin user emails list.

---

modules/apps_api/lib/apps_api/directory_application_creator.rb

This PR updates the description for the OneRecord third party app.
https://vajira.max.gov/browse/API-4086
- app description has been reviewed by UX and left unedited
- corresponding front-end PR to handle newlines: [15545](https://github.com/department-of-veterans-affairs/vets-website/pull/15545)

Update OneRecord app description

---

config/features.yml

the flag will toggle how we display covid19 information
Adding a feature flag for the front end.
department-of-veterans-affairs/va.gov-team#17908
* `facility_locator_lighthouse_covid_vaccine_query`

Adding a feature flag for facility locator front end

---

lib/vre/service.rb
spec/support/vcr_cassettes/veteran_readiness_employment/failed_send_to_vre.yml
spec/support/vcr_cassettes/veteran_readiness_employment/send_to_vre.yml

During development of the CH31 form, our partner has asked that we update the auth url and the endpoint we post to. I have requested a credstash change from VSP to update the auth url. This PR updates the endpoint.
department-of-veterans-affairs/va.gov-team#18073
* no settings change credstash is updated
* This feature is not public yet. No FF added in this PR
* No new Sentry logging
* No Prometheus metrics collected for the feature currently
* Are there Swagger docs that were updated?
* none updated
* Is …

Add endpoint change per partner request

---

app/controllers/v0/profile/ch33_bank_accounts_controller.rb
app/swagger/swagger/requests/disability_compensation_form.rb
app/swagger/swagger/responses/bad_gateway_error.rb
app/swagger/swagger/schemas/errors.rb
spec/request/swagger_spec.rb
spec/support/vcr_cassettes/evss/reference_data/get_intake_sites_500.yml

when reviewing https://github.com/department-of-veterans-affairs/vets-website/pull/15525 I saw that we hadn't properly documented error responses for form 526.
https://github.com/department-of-veterans-affairs/vets-website/pull/15525

Add docs for disability compensation

---

rakelib/form526.rake

EVSS returns warnings as well as errors.  Warnings do not prevent the form from being submitted so we should filter them (at least until the errors are better handled. 

update form 526 rake task to skip warnings

---

modules/claims_api/app/swagger/claims_api/forms/form_526_response_swagger.rb
modules/claims_api/app/swagger/claims_api/v1/form_526_controller_swagger.rb

Create new schema for expected 526 form submission response and present within documentation.
https://vajira.max.gov/browse/API-4232
Viewed through developer portal locally.

API-4232: Benefits Claims- POST requests response is different from expected.

---

app/uploaders/evss_claim_document_uploader.rb
app/uploaders/supporting_evidence_attachment_uploader.rb
app/uploaders/validate_evss_file_size.rb
spec/uploaders/validate_evss_file_size_spec.rb

EVSS inflection should apply to ValidateEVSSFileSize
department-of-veterans-affairs/va.gov-team#18282

ValidateEVSSFileSize should use EVSS inflection

---

spec/lib/generators/module/module_generator_spec.rb

Rspec was complaining about using "should" instead of "expect."  Also added some code to hide generator output during specs.

cleanup for generator specs

---

config/settings.yml
config/sidekiq_scheduler.yml
modules/appeals_api/app/workers/appeals_api/higher_level_review_clean_up_week_old_pii.rb
modules/appeals_api/app/workers/appeals_api/notice_of_disagreement_clean_up_week_old_pii.rb
modules/appeals_api/spec/workers/higher_level_review_clean_up_week_old_pii_spec.rb
modules/appeals_api/spec/workers/higher_level_review_upload_status_batch_spec.rb
modules/appeals_api/spec/workers/notice_of_disagreement_clean_up_week_old_pii_spec.rb
modules/appeals_api/spec/workers/notice_of_disagreement_upload_status_batch_spec.rb

Adding flags for expunging PII and batch updating status for NOD and HLR.
Ticket: https://vajira.max.gov/browse/API-4361

Api-4361 pii and status flags and specs

---

modules/appeals_api/app/models/concerns/appeals_api/central_mail_status.rb

This PR fixes the warnings introduced here: https://github.com/department-of-veterans-affairs/vets-api/pull/5623
Ticket: https://vajira.max.gov/browse/API-4523
---
- The central mail concern is included in both our HLR and NOD classes
- Via the concern, constants were defined within the `included` block
- The `included` block was running for each HLR and NOD, thus the code was attempting to redefine the constants
- Removing the constants from the `included` block allows the definitions to occur one time only

Api 4523 fix already defined constants warnings

---

config/features.yml

This pull request adds a feature toggle for `Search Representative`, a frontend application that will allow users to...search for a new representative. 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/18207
- added support for a new feature flag, tested locally in vets-api.

18207 - add search rep toggle

---

config/settings.yml
config/settings/test.yml
modules/health_quest/app/services/health_quest/lighthouse/claims_token.rb

- Adding configuration settings to test.yml so that we're not checking for the Lighthouse configuration settings by the current environment within the code, on the fly.
department-of-veterans-affairs/va.gov-team#18676
- Adding healthquest module(hqva_mobile) to `config/settings/test.yml` file
- All RSpec tests passing

Add settings to test.yml

---

app/controllers/v0/in_progress_forms_controller.rb

Some refactoring that I wanted to do in [my last PR](https://github.com/department-of-veterans-affairs/vets-api/pull/5582)

Refactor InProgressFormsController

---

modules/vba_documents/app/workers/vba_documents/run_unsuccessful_submissions.rb
modules/vba_documents/app/workers/vba_documents/upload_processor.rb

https://vajira.max.gov/browse/API-4570
Added logging of RunUnsuccessfulSubmission job so that we can track the state by the GUID within CloudWatch.

added rails logging for debugging of cron job

---

modules/appeals_api/app/swagger/appeals_api/v1/higher_level_reviews_controller_swagger.rb
modules/appeals_api/app/swagger/appeals_api/v1/notice_of_disagreements_controller_swagger.rb
modules/appeals_api/config/schemas/200996.json

* More closely aligns HLR and NOD documentation for similar endpoints. 
* Places endpoints into the same order for consistency.
https://vajira.max.gov/browse/API-2790
https://vajira.max.gov/browse/API-3989
https://vajira.max.gov/browse/API-4392

Update HLR & NOD dev docs

---

modules/health_quest/app/services/health_quest/patient_generated_data/common/identity_meta_info.rb
modules/health_quest/app/services/health_quest/patient_generated_data/fhir_client.rb
modules/health_quest/app/services/health_quest/patient_generated_data/patient/factory.rb
modules/health_quest/app/services/health_quest/patient_generated_data/patient/map_query.rb
modules/health_quest/app/services/health_quest/patient_generated_data/patient/resource.rb
modules/health_quest/app/services/health_quest/patient_generated_data/questionnaire_response/factory.rb
modules/health_quest/app/services/health_quest/patient_generated_data/questionnaire_response/map_query.rb
modules/health_quest/app/services/health_quest/patient_generated_data/questionnaire_response/resource.rb
modules/health_quest/spec/services/patient_generated_data/common/identity_meta_info_spec.rb
modules/health_quest/spec/services/patient_generated_data/patient/map_query_spec.rb
modules/health_quest/spec/services/patient_generated_data/patient/resource_spec.rb
modules/health_quest/spec/services/patient_generated_data/questionnaire_response/map_query_spec.rb
modules/health_quest/spec/services/patient_generated_data/questionnaire_response/resource_spec.rb

- Upgrading the `health_quest` module to FHIR version 4 from version 2. This is necessary since the Lighthouse PGD FHIR servers runs on FHIR version 4.
department-of-veterans-affairs/va.gov-team#18183
- RSpec test suite passing

Convert to FHIR version 4

---

modules/health_quest/app/controllers/health_quest/v0/patients_controller.rb
modules/health_quest/app/services/health_quest/patient_generated_data/patient/factory.rb
modules/health_quest/config/routes.rb
modules/health_quest/spec/request/patients_request_spec.rb
modules/health_quest/spec/services/patient_generated_data/patient/factory_spec.rb

- Adding routes/endpoints for getting and creating Patient FHIR resources on the PGD.
- Renaming a couple of methods in order to be consistent with the rest of the PGD services.
department-of-veterans-affairs/va.gov-team#17429
- RSpec tests written and passing

Endpoints for getting and creating FHIR patient

---

modules/claims_api/spec/workers/vbms_upload_job_spec.rb
modules/mobile/spec/request/user_request_spec.rb
spec/serializers/in_progress_form_serializer_spec.rb

remove puts from specs

---

modules/health_quest/app/services/health_quest/patient_generated_data/questionnaire_response/factory.rb

- Making the `Factory` class `get` method more explicit. The delegate essentially makes it hard to find this important part of the code when scanning the object and I've decided that explicitly writing it out will be the better approach in this particular case.
department-of-veterans-affairs/va.gov-team#17200
- RSpec test suite passing

Making factory method call explicit

---

modules/vba_documents/app/mailers/vba_documents/unsuccessful_report_recipients.yml

Adding Molly Gotti to unsuccessful report recipient list 
https://vajira.max.gov/browse/API-4613
To be tested with individual user

API-4613 - adding Molly Gatti to the reports list

---

app/controllers/v0/ppiu_controller.rb
app/controllers/v0/profile/ch33_bank_accounts_controller.rb
app/mailers/direct_deposit_mailer.rb
app/mailers/views/direct_deposit.html.erb
app/swagger/swagger/requests/profile.rb
app/workers/direct_deposit_email_job.rb
spec/controllers/v0/profile/ch33_bank_accounts_controller_spec.rb
spec/jobs/direct_deposit_email_job_spec.rb
spec/mailers/direct_deposit_mailer_spec.rb

add confirmation email to chapter 33 direct deposit updates
https://github.com/department-of-veterans-affairs/va.gov-team/issues/18262
swagger updated

Set up direct deposit for edu confirmation email

---

config/features.yml

Set up toggle in anticipation of the next iteration of the homepage and appointment cards.
department-of-veterans-affairs/va.gov-team#17098
* Are there additions to a `settings.yml` file? Do they vary by environment? No
* Is there a feature flag? What is it? Yes. va_online_scheduling_homepage_refresh
* Is there some Sentry logging that was added? What alerts are relevant? No
* Are there any Prometheus metrics being collected? What Grafana dashboard were they added do? No
* Are there Swagger docs that were updated? No
* Is there any PII concerns or questions? No

Added toggle for appointments home page refresh

---

spec/lib/generators/module/module_generator_spec.rb
spec/lib/generators/provider_state/provider_state_generator_spec.rb

In an effort to remove some stdout output during test runs, I came across this way to test output to stdout and applied it to these generator tests.

expectations for generator test output

---

lib/generators/module/module_generator.rb
spec/simplecov_helper.rb

Moves add_filter and add_group lines to their own methods due to their combined size reaching the assignment branch condition limit of 40 lines. This is being done in preparation for the addition of a new module which would push the ABC over 40 lines.
All unit tests continue to pass with this change.

moves simplecov helper add_filter and add_group lines to separate methods

---

modules/appeals_api/.rubocop.yml
modules/appeals_api/app/swagger/appeals_api/v1/notice_of_disagreements_controller_swagger.rb
modules/appeals_api/app/swagger/appeals_api/v1/response_nod_show_not_found.json
modules/appeals_api/app/swagger/appeals_api/v1/schemas/notice_of_disagreements.rb

This PR adds documentation for the NOD show route.
https://vajira.max.gov/browse/API-4520

Api-4520 Add NOD show to docs

---

config/sidekiq_scheduler.yml
lib/central_mail/utilities.rb
modules/vba_documents/app/workers/vba_documents/upload_processor.rb

scheduling updated to received straggler job to run every hour.
api 4570

Greg.bowman api 4570 update cron schedule

---

config/settings/test.yml
modules/health_quest/app/services/health_quest/appointment_service.rb
modules/health_quest/spec/request/appointment_request_by_id_spec.rb
modules/health_quest/spec/serializers/v0/va_appointments_serializer_spec.rb
modules/health_quest/spec/services/appointment_service_spec.rb

- Get an appointment by ID from MAP mobile appointment service.
department-of-veterans-affairs/va.gov-team#12776
- RSpec test suite passing

GET appointment by ID

---

Dangerfile
Gemfile.lock

Prevent developers from accidentally removing sidekiq enterprise.
department-of-veterans-affairs/va.gov-team#18830

18830 dangerbot checks for enterprise gemfile change

---

modules/health_quest/app/services/health_quest/patient_generated_data/options_builder.rb
modules/health_quest/spec/services/patient_generated_data/options_builder_spec.rb

- GET Questionnaire resources from the lighthouse PGD by a given UseContext(facility id and location id combined)
department-of-veterans-affairs/va.gov-team#19018

GET Questionnaires by UseContext

---

config/features.yml

Feature Flag for Yellow Ribbon enhancements. 
See tool live: [YR School Tool](https://www.va.gov/education/yellow-ribbon-participating-schools/)
department-of-veterans-affairs/va.gov-team#18854
* Is there a feature flag? **yellow_ribbon_mvp_enhancement**

Added Yellow Ribbon enhancement Feature Flag

---

lib/gibft/service.rb

update to correct username for salesforce gibft

update to correct username for salesforce gibft

---

modules/claims_api/app/mailers/claims_api/unsuccessful_report_mailer.rb
modules/claims_api/spec/mailers/unsuccessful_report_mailer_spec.rb

Offboarding myself off the lighthouse program and making sure I get removed from reporting.
https://vajira.max.gov/browse/API-4542

Offboarding myself from emails and reports

---

modules/test_user_dashboard/app/serializers/test_user_dashboard/tud_account_serializer.rb

Adds serializer to return TudAccount information in standard JSON API format
https://app.zenhub.com/workspaces/vsp-identity-5f5bab705a94c9001ba33734/issues/department-of-veterans-affairs/va.gov-team/17211

adds serializer for TudAccount

---

app/workers/evss/disability_compensation_form/submit_form526.rb
spec/jobs/evss/disability_compensation_form/submit_form526_all_claim_spec.rb
spec/support/vcr_cassettes/evss/disability_compensation_form/submit_502.yml
spec/support/vcr_cassettes/evss/disability_compensation_form/submit_503.yml

when we receive a http 503 from EVSS we should categorize the error as retriable. 
department-of-veterans-affairs/va.gov-team#18960

Categorize EVSS 502 errors as retriable for form 526

---

app/workers/vbms/submit_dependents_pdf_job.rb

This is a minor PR fix to use keyword arguments for a method that was recently updated when uploading supporting evidence to a 686 claim.  
department-of-veterans-affairs/va.gov-team#19350
This is a very minor PR - no additional logging or configuration has been added.

Update Method for Attaching Supporting Evidence

---

app/serializers/lighthouse/facilities/facility_serializer.rb
lib/lighthouse/facilities/facility.rb
spec/lib/lighthouse/facilities/client_spec.rb
spec/request/v1/facilities/va_ccp_request_spec.rb
spec/request/v1/facilities/va_request_spec.rb

Lighthouse has added a new field. `operational_hours_special_instructions`
this exposes it on the api
department-of-veterans-affairs/va.gov-team#18987
adding a single new column to the VA facilities responses

18987 lighthouse operation hours special instructions

---

modules/health_quest/app/services/health_quest/appointment_service.rb
modules/health_quest/config/mock/appointments.yml

- Return mock appointments for the appointments service if the current environment is dev.
- Working on this ticket in small steps so that the PR doesn't get overwhelmingly large.
- Feature flip: show_healthcare_experience_questionnaire
- RSpec tests passing

Return mock appointments hash in dev env

---

app/mailers/failed_claims_report_mailer.rb
spec/mailers/failed_claims_report_mailer_spec.rb

update emails for claims report

---

Gemfile.lock

#5800 added gems to Gemfile but didn't commit changes to Gemfile.lock.

add Gemfile.lock for #5800

---

modules/mobile/spec/support/vcr_cassettes/appointments/get_cancel_reasons.yml
modules/mobile/spec/support/vcr_cassettes/appointments/get_cancel_reasons_500.yml
modules/mobile/spec/support/vcr_cassettes/appointments/get_cancel_reasons_invalid.yml
modules/mobile/spec/support/vcr_cassettes/appointments/put_cancel_appointment.yml
modules/mobile/spec/support/vcr_cassettes/appointments/put_cancel_appointment_409.yml
modules/mobile/spec/support/vcr_cassettes/appointments/put_cancel_appointment_500.yml

Reducing the line count of PR https://github.com/department-of-veterans-affairs/vets-api/pull/5844
department-of-veterans-affairs/va.gov-team#14839

VCR cassettes for the mobile cancel appointment endpoint

---

modules/test_user_dashboard/app/models/test_user_dashboard/tud_account.rb

makes email a unique field for `tud_accounts` to prevent accidental duplicate account creation

adds email uniqueness validation to tud_accounts

---

modules/health_quest/app/services/health_quest/questionnaire_manager/basic_questionnaire_manager_formatter.rb
modules/health_quest/app/services/health_quest/questionnaire_manager/questionnaire_formatter.rb
modules/health_quest/app/services/health_quest/questionnaire_manager/questionnaire_response_collector.rb
modules/health_quest/app/services/health_quest/questionnaire_manager/questionnaire_responses_formatter.rb
modules/health_quest/app/services/health_quest/questionnaire_manager/responses_group.rb
modules/health_quest/app/services/health_quest/questionnaire_manager/save_in_progress_collector.rb
modules/health_quest/app/services/health_quest/questionnaire_manager/save_in_progress_formatter.rb
modules/health_quest/app/services/health_quest/questionnaire_manager/transformer.rb
modules/health_quest/spec/services/questionnaire_manager/basic_questionnaire_manager_formatter_spec.rb
modules/health_quest/spec/services/questionnaire_manager/questionnaire_formatter_spec.rb
modules/health_quest/spec/services/questionnaire_manager/questionnaire_response_collector_spec.rb
modules/health_quest/spec/services/questionnaire_manager/questionnaire_responses_formatter_spec.rb
modules/health_quest/spec/services/questionnaire_manager/responses_group_spec.rb
modules/health_quest/spec/services/questionnaire_manager/save_in_progress_collector_spec.rb
modules/health_quest/spec/services/questionnaire_manager/save_in_progress_formatter_spec.rb
modules/health_quest/spec/services/questionnaire_manager/transformer_spec.rb

- This PR implements a refactor of the `modules/health_quest/app/services/health_quest/questionnaire_manager/transformer.rb` class.
- Refactoring for code clarity, ease of maintenance, and for facilitating quick additions and changes to the feature with minimal coupling and dependency(upcoming tickets and requirements)
- Test coverage of the `transformer.rb` class was at 100% and passing before undertaking the refactor, and is at 100% and passing after the refactor
- Decomposed dependencies into several classes, each with a hundred lines or less, and will full test coverage

Refactor the transformer.rb class

---

config/features.yml

The application that relies on this feature toggle is available in production to 100% of users, so it is no longer needed.
department-of-veterans-affairs/va.gov-team#19553

remove view payments feature toggle

---

modules/mobile/app/controllers/mobile/v0/messages_controller.rb
modules/mobile/app/serializers/mobile/v0/category_serializer.rb
modules/mobile/app/serializers/mobile/v0/message_serializer.rb
modules/mobile/app/serializers/mobile/v0/messages_serializer.rb
modules/mobile/spec/request/folders_request_spec.rb
modules/mobile/spec/request/messages_request_spec.rb

Mobile secure messaging APIs part 3 of 3
(Splitting to avoid flagging by dangerbot)

Adds mobile SM messages API

---

modules/test_user_dashboard/app/serializers/test_user_dashboard/tud_account_serializer.rb

Supporting backend update to allow #19677 to be closed fully by [vsp-test-user-dashboard PR](https://github.com/department-of-veterans-affairs/vsp-test-user-dashboard/pull/16#pullrequestreview-590684150) and provide more detailed test account information (MPI services, id_type, loa, account_type) to the frontend TUD app
https://github.com/department-of-veterans-affairs/va.gov-team/issues/17211

adds services as serializable attribute

---

app/controllers/concerns/vet360/writeable.rb
spec/request/vet360/address_request_spec.rb

log to pii logs table when a va profile record fails validation (frontend validations are supposed to match backend validations so this should not happen normally)
https://github.com/department-of-veterans-affairs/va.gov-team/issues/20025

store invalid addresses in PII logs table

---

lib/bgs/dependent_higher_ed_attendance.rb
spec/lib/bgs/dependent_higher_ed_attendance_spec.rb

During partner integration testing of VA Form 674, it was determined that we should default child type to `Biological` rather than to `Other`.  This is a small PR that changes the default value from `Other` to `Biological`.
department-of-veterans-affairs/va.gov-team#20179
This is a very minor PR - no new settings or logging have been added.

Update Child Type for VA Form 674

---

modules/health_quest/app/controllers/health_quest/v0/lighthouse_appointments_controller.rb
modules/health_quest/app/services/health_quest/health_api/appointment/factory.rb
modules/health_quest/app/services/health_quest/health_api/appointment/map_query.rb
modules/health_quest/app/services/health_quest/health_api/patient/map_query.rb
modules/health_quest/app/services/health_quest/lighthouse/fhir_client.rb
modules/health_quest/app/services/health_quest/patient_generated_data/questionnaire/map_query.rb
modules/health_quest/app/services/health_quest/patient_generated_data/questionnaire_response/map_query.rb
modules/health_quest/config/routes.rb
modules/health_quest/spec/request/lighthouse_appointments_request_spec.rb
modules/health_quest/spec/services/health_api/appointment/factory_spec.rb
modules/health_quest/spec/services/health_api/appointment/map_query_spec.rb
modules/health_quest/spec/services/health_api/patient/map_query_spec.rb
modules/health_quest/spec/services/lighthouse/fhir_client_spec.rb
modules/health_quest/spec/services/patient_generated_data/questionnaire/map_query_spec.rb
modules/health_quest/spec/services/patient_generated_data/questionnaire_response/map_query_spec.rb

- This is the preliminary PR in building the vets-api service which will fetch appointments from the Lighthouse's new Health API
- This PR builds the basic structure necessary to accomplish the requirement stated above and creates the basic structure, classes, and tests necessary to accomplish this
- This step is also being taken so that future PRs built on top of this will aim to remain small within the allowed guild lines.
department-of-veterans-affairs/va.gov-team#19053

Setup harness for lighthouse appointments

---

db/migrate/20210211192624_create_active_storage_tables.active_storage.rb
db/migrate/20210215155459_add_column_active_storage_to_upload_submission.rb
db/schema.rb

Migrations only for:
https://vajira.max.gov/browse/API-5142
Simple migrations for upcoming pull request

Adding in migrations

---

modules/veteran_confirmation/VETERAN_CONFIRMATION.yml
modules/veteran_verification/VETERAN_VERIFICATION.yml

Content updates to Veteran Confirmation and Veteran Verification for developer-portal.
https://vajira.max.gov/browse/API-5275

[API-5275] Veteran Confirmation and Veteran Verification Content Updates

---

modules/mobile/app/models/mobile/v0/adapters/claims_overview.rb
modules/mobile/spec/request/claims_and_appeals_overview_request_spec.rb

Changed which values our updateAt field is based on for claims and appeals. This change puts us in line with .gov
N/A
Fixing some bad assumptions from the initial implementation.

fixes for claims overview updateAt dates

---

Gemfile.lock

forgot to build my last vets-json-schema PR 😣
[vets-json-schema PR](https://github.com/department-of-veterans-affairs/vets-json-schema/pull/565)

update Gemfile.lock for vets-json-schema (#2)

---

lib/statsd_middleware.rb
spec/request/statsd_middleware_spec.rb

update list of allowed source app names
And while I'm in the neighboorhood, get rid of the term `whitelist`
department-of-veterans-affairs/va.gov-team#20521

update allowlist for source apps

---

config/features.yml

This pull request removes the feature toggle for chapter 36, as it's no longer needed. 
department-of-veterans-affairs/va.gov-team#19557

remove chapter 36 feature toggle

---

db/schema.rb
modules/test_user_dashboard/db/migrate/20210226193901_add_idme_uuid_to_tud_accounts.rb

updates `tud_accounts` table to add a column for holding an account's `idme_uuid`
department-of-veterans-affairs/va.gov-team#18967

adds idme_uuid column to tud_accounts table

---

modules/health_quest/app/controllers/health_quest/v0/questionnaire_responses_controller.rb

- Permit the questionnaire_response params only.
department-of-veterans-affairs/va.gov-team#17413

permit questionnaire response params

---

config/features.yml

This PR adds the following feature toggles:
```
cerner_override_463
cerner_override_531
cerner_override_648
cerner_override_653
cerner_override_668
cerner_override_687
cerner_override_692
```
**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/20442

Add cerner facility feature toggles

---

modules/health_quest/app/services/health_quest/resource/client_model/questionnaire_response.rb
modules/health_quest/app/services/health_quest/resource/query.rb
modules/health_quest/spec/services/resource/client_model/questionnaire_response_spec.rb
modules/health_quest/spec/services/resource/query_spec.rb

- Refactor step one: Adding the resource `query` object, the `questionnaire_response` client model, and supporting tests.

refactor - adding query and resource classes

---

modules/openid_auth/spec/requests/validation_request_spec.rb
spec/lib/oidc/key_service_spec.rb

Addressing intermittent unit test failures in validation_request_spec

Removed problem tests

---

modules/health_quest/app/services/health_quest/resource/client_model/patient.rb
modules/health_quest/spec/services/resource/client_model/patient_spec.rb

- Refactor step two: Adding the `patient` client model, and supporting tests.

refactor - adding patient client model

---

modules/health_quest/app/controllers/health_quest/v0/locations_controller.rb
modules/health_quest/app/services/health_quest/shared/options_builder.rb
modules/health_quest/config/routes.rb
modules/health_quest/spec/request/locations_request_spec.rb
modules/health_quest/spec/services/shared/options_builder_spec.rb

- Refactor step four: Adding the ability to fetch `Location` resources plus dependencies.

Adding locations controller and dependencies

---

modules/health_quest/app/controllers/health_quest/v0/lighthouse_appointments_controller.rb
modules/health_quest/app/controllers/health_quest/v0/patients_controller.rb
modules/health_quest/app/controllers/health_quest/v0/questionnaire_responses_controller.rb
modules/health_quest/app/controllers/health_quest/v0/questionnaires_controller.rb
modules/health_quest/spec/request/lighthouse_appointments_request_spec.rb
modules/health_quest/spec/request/patients_request_spec.rb
modules/health_quest/spec/request/questionnaire_responses_request_spec.rb
modules/health_quest/spec/request/questionnaires_request_spec.rb

- Refactor step five: Modify controller factory params and related request specs.

modify controllers and request specs

---

modules/health_quest/app/services/health_quest/questionnaire_manager/factory.rb
modules/health_quest/spec/request/questionnaire_manager_request_spec.rb
modules/health_quest/spec/services/questionnaire_manager/factory_spec.rb

- Refactor step six: Modify questionnaire manager `factory` and related request specs.

refactor- questionnaire manager factor and specs

---

modules/health_quest/app/services/health_quest/resource/factory.rb
modules/health_quest/app/services/health_quest/resource/query.rb

- Adding back YARD doc for `factory` and `query` classes
- Tiny code cleanup
department-of-veterans-affairs/va.gov-team#20247

adding back yardoc plus cleanup

---

app/workers/education_form/create10203_applicant_decision_letters.rb
app/workers/education_form/process10203_submissions.rb

`@time` wasn't being set
http://sentry.vfs.va.gov/organizations/vsp/issues/28358/?environment=staging&project=3&query=is%3Aunresolved
department-of-veterans-affairs/va.gov-team#17770

Fix issue with EducationForm::Create10203ApplicantDecisionLetters	sidekiq job

---

modules/test_user_dashboard/app/models/test_user_dashboard/tud_account.rb

Preparation for removing `standard` & `available` columns from the `test_user_dashboard_tud_accounts` table.
https://github.com/department-of-veterans-affairs/vets-api/pull/6086

makes standard and available ignored columns

---

db/schema.rb
modules/test_user_dashboard/db/migrate/20210121161138_add_tud_accounts.rb
modules/test_user_dashboard/db/migrate/20210305155617_remove_standard_available_from_tud_accounts.rb

Cleanup of TUD table, removes unused `standard` and `available` columns

removes standard and available columns

---

rakelib/test_user_account.rake

Rakefile change to accept path to population .csv as an argument
department-of-veterans-affairs/va.gov-team#20740
Manual testing of rakefile filepath/argument change

Test users rakefile

---

modules/claims_api/config/schemas/526.json

I compared our 526 JSON schema to that of the [EVSS definition](https://www.ebenefits.va.gov/wss-form526-services-web-v2/swagger-ui/index.html?url=https://www.ebenefits.va.gov/wss-form526-services-web-v2/rest/swagger.yaml#/form526/submit) looking for places where we either aren't performing a translation, we're neglecting to limit input values to a defined subset, or general mistakes.  This is what I found.
[API-5459](https://vajira.max.gov/browse/API-5459)

[API-5459 - Ensure 526 submission structure sent to evss is valid

---

README.md
modules/claims_api/app/controllers/claims_api/base_form_controller.rb

Issue with null value in the situation that no flashes are supplied in the request but there is homelessness or terminally ill values separately in the request.
http://sentry.vfs.va.gov/organizations/vsp/issues/6142
Tested locally to ensure change would resolve the null value issue

undefined method `push' for nil:NilClass

---

app/policies/ch33_dd_policy.rb
spec/controllers/v0/profile/ch33_bank_accounts_controller_spec.rb
spec/factories/users.rb

Add multifactor verification to ch33 direct deposit apis
https://github.com/department-of-veterans-affairs/va.gov-team/issues/21231

Add multifactor verification to ch33 direct deposit apis

---

Gemfile
Gemfile.lock
config/routes.rb
modules/facilities_api/Gemfile
modules/facilities_api/README.rdoc
modules/facilities_api/Rakefile
modules/facilities_api/app/models/facilities_api/v1/ppms/provider.rb
modules/facilities_api/app/models/facilities_api/v1/ppms/specialty.rb
modules/facilities_api/bin/rails
modules/facilities_api/config/routes.rb
modules/facilities_api/facilities_api.gemspec
modules/facilities_api/lib/facilities_api.rb
modules/facilities_api/lib/facilities_api/engine.rb
modules/facilities_api/lib/facilities_api/version.rb
modules/facilities_api/spec/factories/facilities_api/v1/ppms/providers.rb
modules/facilities_api/spec/factories/facilities_api/v1/ppms/specialties.rb
modules/facilities_api/spec/models/facilities_api/v1/ppms/provider_spec.rb
modules/facilities_api/spec/models/facilities_api/v1/ppms/specialty_spec.rb
modules/facilities_api/spec/spec_helper.rb
spec/simplecov_helper.rb
spec/spec_helper.rb

This creates a new rails engine FacilitiesApi
I've modified the generated files so they are able to work in the scope of the engine
Copying over the Provider and Specialties models as well as inverting the version naming convention (v1/ppms instead of ppms/v1)
department-of-veterans-affairs/va.gov-team#11608
department-of-veterans-affairs/va.gov-team#18526
This is a small building block to puting facilities in an engine.

18526 copy ppms models to engine

---

lib/decision_review/configuration.rb

Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/20695

Increase Breakers Error Threshold (DecisionReview Service)

---

app/mailers/stem_applicant_denial_mailer.rb
spec/mailers/stem_applicant_denial_mailer_spec.rb

Had `stage` instead of `staging` in the email which doesn't exist
department-of-veterans-affairs/va.gov-team#17770

AD: Applicant Denial email change claims status url from stage to staging

---

modules/health_quest/app/services/health_quest/questionnaire_manager/factory.rb
modules/health_quest/spec/services/questionnaire_manager/factory_spec.rb

- PR series: #6120, #6127, #6130
- Removing the MAP/MAS appointments from the Questionnaire Manager.
- Following PRs will rebuild the Questionnaire Manager aggregator modules with appointments from Lighthouse.

remove map appointment from questionnaire manager factory

---

lib/identity/parsers/gc_ids.rb
lib/identity/parsers/gc_ids_helper.rb
spec/lib/identity/parsers/gc_ids_helper_spec.rb

This is part of the effort of splitting up: https://github.com/department-of-veterans-affairs/vets-api/pull/6071
department-of-veterans-affairs/va.gov-team/issues/16582
At this point, this PR should have no effect on Functionality. This adds a new class but doesn't wire it up to anything yet

[16582] Adding helper functions for GC Ids parsing

---

Gemfile.lock

Rolling back update of rubocop-thread_safety

Rolling back update of rubocop-thread_safety

---

modules/health_quest/app/controllers/health_quest/v0/questionnaire_manager_controller.rb
modules/health_quest/app/services/health_quest/questionnaire_manager/factory.rb
modules/health_quest/app/services/health_quest/resource/client_model/questionnaire_response.rb
modules/health_quest/spec/request/questionnaire_manager_request_spec.rb

- Fix an issue with POSTing Questionnaire Responses params to the Questionnaire Manager.

20248 Fix questionnaire manager QR post issue

---

db/migrate/20210312211214_add_metadata_to_upload_submission.rb
db/schema.rb

These migrations enable tracking of file size and status changes in benefits intake API
https://vajira.max.gov/browse/API-5293
https://vajira.max.gov/browse/API-5694
migration only

Adding migration and schema

---

db/migrate/20210315162119_add_email_sent_at_to_education_stem_automated_decision.rb
db/schema.rb

Database changes for https://github.com/department-of-veterans-affairs/vets-api/pull/6173
department-of-veterans-affairs/va.gov-team#21522

Update EducationStemAutomatedDecision to have email sent timestamps DB

---

modules/health_quest/lib/health_quest/engine.rb

- PR series: #6120, #6127, #6130, #6142, #6154
- Configure the FHIR client log levels for production and other environments.

20248 set FHIR log level

---

modules/vba_documents/app/swagger/vba_documents/document_upload/metadata_swagger.rb
modules/vba_documents/app/swagger/vba_documents/document_upload/put_description.md

Updating swagger docs for line of business.
https://vajira.max.gov/browse/API-5554
https://vajira.max.gov/browse/API-5719
Testing was done via bringing up docs locally via npm start.

Updating swagger docs.

---

config/settings.yml

Addition of:
- elder_joseph@bah.com
- mccurdy_devin@bah.com
- turner_desiree@bah.com
to `flipper.admin_user_emails` config

Add new users to config file

---

.github/CODEOWNERS

- Requesting code ownership of `modules/health_quest` and `spec/support/*/health_quest/`

Requesting code ownership of modules/health_quest and spec/support/*/health_quest/

---

modules/vba_documents/app/models/vba_documents/upload_submission.rb

…ata key
Bug fix. Status changes were failing to record the status change time when the key was not present on existing records.
department-of-veterans-affairs/va.gov-team#5293

bugfix - updating existing records without the metadata status key

---

modules/claims_api/app/controllers/claims_api/v1/forms/power_of_attorney_controller.rb
modules/claims_api/app/swagger/claims_api/forms/form_2122_response_swagger.rb
modules/claims_api/app/swagger/claims_api/v0/form_526_controller_swagger.rb
modules/claims_api/app/swagger/claims_api/v1/form_526_controller_swagger.rb
modules/claims_api/config/initializers/okcomputer.rb
modules/claims_api/config/schemas/2122.json
modules/claims_api/spec/requests/metadata_request_spec.rb

Just a couple quick fixes i found when doing my audit.
Misspelling in the docs and one of BGS's services not being optional as it is currently defined.
https://vajira.max.gov/browse/API-5769

Audit quick fixes

---

modules/vba_documents/app/swagger/vba_documents/document_upload/metadata_swagger.rb

https://vajira.max.gov/browse/API-5594
Tested locally

Last fix and some additional line breaks

---

lib/evss/disability_compensation_auth_headers.rb
modules/health_quest/app/services/health_quest/jwt_wrapper.rb
modules/vaos/app/models/vaos/appointment_form.rb
modules/vaos/app/models/vaos/appointment_request_form.rb
modules/vaos/app/services/vaos/jwt_wrapper.rb

Reverts department-of-veterans-affairs/vets-api#6160

Revert "Remove most direct user.mpi calls [#5411]"

---

modules/health_quest/app/services/health_quest/resource/client_model/patient.rb
modules/health_quest/app/services/health_quest/resource/client_model/questionnaire_response.rb
modules/health_quest/app/services/health_quest/shared/identity_meta_info.rb
modules/health_quest/spec/services/resource/client_model/patient_spec.rb
modules/health_quest/spec/services/resource/client_model/questionnaire_response_spec.rb
modules/health_quest/spec/services/shared/identity_meta_info_spec.rb

- The meta tag on the FHIR resource should be an array of FHIR coding
- Identifier values on FHIR resources should be of the appropriate types.

Fix identifier and meta tags on resources

---

app/controllers/v0/notice_of_disagreements_controller.rb
spec/request/v0/notice_of_disagreements_controller_request_spec.rb

putting this skeleton in place so that the following PRs (adding methods to the controller) can be reviewed in parallel

NOD - Create Skeleton Controller

---

Gemfile.lock

As part of the gem update series, this PR updates the webrick gem (test group) to the latest minor version. It's best to update each gem individually, in order to avoid issues if a roll back is needed.

bump webrick to the latest minor version

---

config/sidekiq_scheduler.yml
spec/jobs/education_form/process10203_submissions_spec.rb

Set scheduled time back to original to reduce load on sidekiq

Reset 10203 sidekiq job schedule times

---

modules/claims_api/app/swagger/claims_api/description/v0.md
modules/claims_api/app/swagger/claims_api/description/v1.md
modules/claims_api/app/swagger/claims_api/v0/claims_controller_swagger.rb
modules/claims_api/app/swagger/claims_api/v0/form_0966_controller_swagger.rb
modules/claims_api/app/swagger/claims_api/v0/form_2122_controller_swagger.rb
modules/claims_api/app/swagger/claims_api/v0/form_526_controller_swagger.rb
modules/claims_api/app/swagger/claims_api/v0/swagger_root.rb
modules/claims_api/app/swagger/claims_api/v1/claims_controller_swagger.rb
modules/claims_api/app/swagger/claims_api/v1/form_0966_controller_swagger.rb
modules/claims_api/app/swagger/claims_api/v1/form_2122_controller_swagger.rb
modules/claims_api/app/swagger/claims_api/v1/form_526_controller_swagger.rb
modules/claims_api/app/swagger/claims_api/v1/swagger_root.rb

Update swagger documentation
https://vajira.max.gov/browse/API-5445
Viewed in developer portal locally.

API-5445: Deploy updated Benefits Claims Documentation 

---

modules/health_quest/app/services/health_quest/questionnaire_manager/factory.rb

- Optimize the number of organization and location request numbers
- Build a unique list of location ids from the appointments so that we're not making duplicate calls to the Location endpoint
- Build a unique list of organization ids from the unique locations so that we're not making duplicate calls to the Organization endpoint

21632 optimize organization and location request numbers

---

config/features.yml

Removed `gibct_state_search` feature flag
department-of-veterans-affairs/va.gov-team#18214

Removed gibct_state_search feature flag

---

modules/appeals_api/app/swagger/appeals_api/v1/schemas/notice_of_disagreements.rb

Our NOD swagger docs needed updating to include the socOptIn boolean.
https://vajira.max.gov/browse/API-5792

Add socOptIn to NOD documentation

---

modules/appeals_api/app/swagger/appeals_api/v1/notice_of_disagreements_controller_swagger.rb

Update Swagger docs to reflect previously removed Claimant info - claimant headers specifically.
https://vajira.max.gov/browse/API-5889

Remove swagger blocks related to Claimant - NOD

---

Makefile

- Invoking `bundle exec` before certain `make` tasks.

invoke bundle exec before tasks

---

config/features.yml

Fixes: https://github.com/department-of-veterans-affairs/va.gov-team/issues/21857

Add "can_upload_10_10cg_poa" feature flip

---

.rubocop.yml
app/workers/education_form/create_daily_spool_files.rb

Adding a rescue around all code in the job to send an error notification to Sentry and increase metric for alert in https://github.com/department-of-veterans-affairs/devops/pull/8783
department-of-veterans-affairs/va.gov-team#21949

SPOOL: Create PagerDuty Alert

---

config/features.yml

This PR simply adds a Feature Flag for the coronavirus-vaccination app that allows expanded eligibility functionality to be exposed. 
department-of-veterans-affairs/va.gov-team#21876
vets website PR: https://github.com/department-of-veterans-affairs/vets-website/pull/16488

Add feature flag for covid vaccine expanded eligibility

---

app/models/form_profile.rb
app/models/user.rb
app/models/va_profile_redis/contact_information.rb
config/settings.yml
lib/va_profile/address_validation/configuration.rb
lib/va_profile/configuration.rb
lib/va_profile/contact_information/configuration.rb
spec/models/form_profile_spec.rb
spec/models/va_profile_redis/contact_information_spec.rb
spec/support/vcr.rb

Change vet360 reference in settings.yml to preferentially use `va_profile` key
https://github.com/department-of-veterans-affairs/va.gov-team/issues/18259

Change vet360 reference in settings.yml

---

app/models/form_profile.rb
app/models/user.rb
app/models/va_profile_redis/contact_information.rb
config/settings.yml
lib/va_profile/address_validation/configuration.rb
lib/va_profile/configuration.rb
lib/va_profile/contact_information/configuration.rb
spec/models/form_profile_spec.rb
spec/models/va_profile_redis/contact_information_spec.rb
spec/support/vcr.rb

Reverts department-of-veterans-affairs/vets-api#6238
bug in this PR breaks va profile config

Revert "Change vet360 reference in settings.yml"

---

modules/covid_vaccine/app/models/covid_vaccine/v0/raw_expanded_form_data.rb
modules/covid_vaccine/spec/factories/expanded_registration_submissions.rb
modules/covid_vaccine/spec/request/covid_vaccine/v0/expanded_registration_request_spec.rb

Updates controller validations to match what is currently being sent by the frontend. 

Updates vax expansion validation to match frontend

---

config/features.yml
modules/covid_vaccine/app/controllers/covid_vaccine/v0/expanded_registration_controller.rb
modules/covid_vaccine/spec/request/covid_vaccine/v0/expanded_registration_request_spec.rb

Adds a feature flag `covid_vaccine_registration_expanded` that will let us individually control the new iteration of the KMI tool API, without impacting availability of the original KMI tool. 
Tested locally and via specs.

Adds feature flag specific to expanded vaccine API

---

.rspec_parallel

- Output RSpec XML for each test database that we create on the Jenkins CI environment.

output rspec xml for each test database

---

modules/health_quest/app/controllers/health_quest/v0/questionnaire_manager_controller.rb

- Permit nested questionnaire response parameters:
- Permit appointment and nested params
- Permit questionnaire and nested params
- Permit item and nested params

21632 permit nested questionnaire response parameters

---

modules/va_forms/app/models/va_forms/form.rb
modules/va_forms/app/serializers/va_forms/form_list_serializer.rb

Rolling back to do more testing

---

lib/forms/schemas/forms.json
spec/support/schemas/va_forms/forms.json

Fix for the schema and sha256 Forms API

Fixing schema

---

app/workers/education_form/templates/0994.erb
spec/fixtures/education_benefits_claims/0994/kitchen_sink.json
spec/fixtures/education_benefits_claims/0994/kitchen_sink.spl
spec/fixtures/education_benefits_claims/0994/prefill.spl
spec/fixtures/education_benefits_claims/0994/simple.spl

Updated 0994 spool file to include "Enter the date you expect to be released from active duty" question.
department-of-veterans-affairs/va.gov-team#22359
- Tested locally and QA reviewed.
- Change is behind `edu_form_omb_and_expiration` flag

Update 0994 spool file

---

db/schema.rb
modules/appeals_api/db/migrate/20210330170327_add_fields_to_evidence_submissions.rb

Adds additional fields to the Evidence Submission table to better track relevant information.
https://vajira.max.gov/browse/API-6017

API-6017 - Add fields to evidence submissions table

---

Gemfile.lock

Update vets-json-schema reference.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/21868
Related vets-json-schema change: https://github.com/department-of-veterans-affairs/vets-json-schema/pull/574

update vets-json-schema ref

---

Jenkinsfile
modules/vaos/app/controllers/vaos/v0/facilities_controller.rb
modules/vaos/app/serializers/vaos/v0/limit_serializer.rb
modules/vaos/app/services/vaos/systems_service.rb
modules/vaos/spec/request/facilities_request_spec.rb
modules/vaos/spec/services/systems_service_spec.rb
spec/support/schemas/vaos/facilities_limits.json
spec/support/vcr_cassettes/vaos/systems/get_facility_limits.yml

The work here is to fix a small bug related to the format of the response for the new request limits call.  The format has been updated to conform with the standard array response format.
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/22157
Unit tests and VCR cassettes have been updated to reflect this change

Updated tests and controller to use correct serializer

---

Jenkinsfile
modules/vaos/app/serializers/vaos/v0/va_appointments_serializer.rb
modules/vaos/spec/request/appointments_request_spec.rb
spec/support/schemas/vaos/va_appointment_raw.json
spec/support/schemas_camelized/vaos/va_appointment_raw.json

The work here is to ensure the `char4` code provided by VAMF associated with appointments is passed through to vets-website.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/21540
Associated vcr cassette was updated to reflect this change.

char4 code pass-through on appointment model

---

.github/CODEOWNERS

We (VSA Claims & Appeals Team) already own the rake task --everyone cool with us owning the spec too?

Own the Test Too (Form526 rake task)

---

spec/uploaders/evss_claim_document_uploader_spec.rb

it's jpeg in ci and jpg locally but either is fine

nobody cares if it is jpg or jpeg

---

app/workers/vbms/submit_dependents_pdf_job.rb

During integration testing, we noticed that documents attached to VA Form 686 as supporting evidence are not being uploaded properly to VBMS.  This PR fixes the file path of the attachment(s) so that the file gets uploaded properly.  For local development, all files get uploaded to a directory prefixed with `tmp` but for other environments the `tmp` dir is not used.
department-of-veterans-affairs/va.gov-team#22535
This is a minor PR so no new logging or settings have been added.

Supporting Evidence Attachments for VA Form 686

---

lib/evss/disability_compensation_form/data_translation_all_claim.rb
spec/support/disability_compensation_form/bdd_evss_submission.json
spec/support/disability_compensation_form/bdd_large_fe_submission.json

exculde guard/resereve periods from Release from active duty date calculations 
department-of-veterans-affairs/va.gov-team#22559

form526 - exclude guard/reserves period from BDD RAD date

---

Gemfile.lock

As a more cautious approach to update our production gems, the upgrade path was split into three sub-steps. It was discussed to break out each gem into a ticket individually, as the risk level increases. This ticket details the upgrade of the aasm gem (production group) to it's latest minor version
https://github.com/department-of-veterans-affairs/va.gov-team/issues/22245

update aasm to 5.1.1

---

modules/vba_documents/app/workers/vba_documents/slack_notifier.rb
modules/vba_documents/spec/jobs/slack_notifier_spec.rb

Adding in rspec test for slack notifier.
Also adding in change to daily notifier to not include 'success'
https://vajira.max.gov/browse/API-6086

Testing feature flag on slack notifier

---

app/workers/education_form/templates/1990s.erb
spec/fixtures/education_benefits_claims/1990s/kitchen_sink.spl
spec/fixtures/education_benefits_claims/1990s/simple.spl

Update 1990s Spool Template file

---

lib/evss/disability_compensation_form/data_translation_all_claim.rb
spec/lib/evss/disability_compensation_form/data_translation_all_claim_spec.rb

Handle nils for #6421
fixes http://sentry.vfs.va.gov/organizations/vsp/issues/32329/?environment=production&project=3&query=is%3Aunresolved+assigned%3Ame+url%3Ahttps%3A%2F%2Fapi.va.gov%2Fv0%2Fdisability_compensation_form%2Fsubmit_all_claim&statsPeriod=14d

add nil check for RAD date

---

config/sidekiq_scheduler.yml
modules/vba_documents/app/mailers/vba_documents/monthly_report_mailer.rb
modules/vba_documents/app/mailers/vba_documents/monthly_report_recipients.yml
modules/vba_documents/app/views/vba_documents/monthly_report_mailer/monthly_report.html.erb
modules/vba_documents/app/workers/vba_documents/report_monthly_submissions.rb
modules/vba_documents/spec/jobs/report_monthly_submissions_spec.rb
modules/vba_documents/spec/mailers/monthly_report_mailer_spec.rb

…es to processing results set
https://vajira.max.gov/browse/API-5948
Modified the processing query and html report to include pending submission and change the date range for long running processing status uploads

modified recipent list and schedule for this report - changed query

---

Gemfile.lock

As part of the gem update series, this PR updates the pghero gem(default group) to the latest minor version. Gems are being updated individually (separate PRs), in order to avoid issues if a roll back is needed.
https://github.com/ankane/pghero/blob/master/CHANGELOG.md
department-of-veterans-affairs/va.gov-team##22681

bump pghero to latest minor version

---

config/features.yml

Added feature flag for unenrolled vaccine scheduling discovery work.
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/22079

added unenrolled vaccine scheduling flag

---

modules/va_forms/app/swagger/va_forms/forms/form_swagger.rb
modules/va_forms/config/locales/en.yml

Fixes to make the Forms API LOAST complaint
https://vajira.max.gov/browse/API-5982
Locally tested against LOAST

LOAST fixes

---

modules/va_forms/app/swagger/va_forms/forms/form_swagger.rb

Small property tweak
https://vajira.max.gov/browse/API-5982
Tested locally

Small tweak for property

---

config/settings.yml

added cwheeler@governmentcio.com to flipper admin
updated `config/settings.yml` to add cwheeler@governmentcio.com to flipper admin_user_emails

add cwheeler@governmentcio.com to flipper admin

---

modules/vaos/app/docs/vaos/v0/vaos.yaml

This ticket is to add a swagger entry for the appointment_availability endpoint in VAOS

updated vaos.yml to include the appointment_availability endpoint

---

Gemfile.lock
app/controllers/v0/apidocs_controller.rb
app/controllers/v0/search_typeahead_controller.rb
app/swagger/swagger/requests/search_typeahead.rb
config/initializers/breakers.rb
config/initializers/statsd.rb
config/locales/exceptions.en.yml
config/routes.rb
config/settings.yml
config/settings/test.yml
lib/search_click_tracking/service.rb
lib/search_typeahead/configuration.rb
lib/search_typeahead/response.rb
lib/search_typeahead/service.rb
lib/statsd_middleware.rb
spec/lib/search_typeahead/configuration_spec.rb
spec/lib/search_typeahead/service_spec.rb
spec/request/search_typeahead_request_spec.rb
spec/request/swagger_spec.rb
spec/support/vcr_cassettes/search_typeahead/missing_query.yml
spec/support/vcr_cassettes/search_typeahead/success.yml

This PR adds the search suggestions endpoint to vets-api. It requires a query, and uses an access key and name param provided by vets-api
https://github.com/department-of-veterans-affairs/va.gov-team/issues/21794
Settings.yml has been updated to include necessary parameters, swagger docs have also been updated to include the new endpoint
spec and configuration tests have been added, as well as manual testing of the endpoint via postman

Srsuddath search suggestions 21794

---

db/migrate/20210331131558_create_questionnaire_responses.health_quest.rb
db/migrate/20210331131559_add_index_to_health_quest_questionnaire_responses_fields.health_quest.rb
db/migrate/20210331131560_add_index_to_health_quest_questionnaire_responses_encrypted_questionnaire_response_data_iv.health_quest.rb
db/migrate/20210331131561_add_index_to_health_quest_questionnaire_responses_encrypted_user_demographics_data_iv.health_quest.rb
db/schema.rb

- Add health_quest_questionnaire_responses table
- Add migration files for indexing appropriate fields
- Add migrations for questionnaire_responses
- Add health_quest_questionnaire_responses table
- Add migration files for indexing appropriate fields
department-of-veterans-affairs/va.gov-team#19061

19061 Add migrations for questionnaire_responses

---

.github/CODEOWNERS

Setting up code ownership for the facilities_api module

Setting vsa-facilities-backend as a CODEOWNER

---

Gemfile.lock

Update vets-json-schema to `v20.1.0`

update vets_json_schema gem

---

config/settings.yml

This adds Lauren Ernest, the VAOS product manager, to the feature flag admin list.

Add Lauren E to feature flag list

---

modules/mobile/app/models/mobile/v0/adapters/claims_overview.rb
modules/vaos/app/docs/vaos/v0/vaos.yaml

This ticket is part of a continuing effort to update the VAOS swagger file so it better reflects the interface between vets-website and vets-api

Added query params to direct scheduling facility swagger documentation

---

modules/vaos/app/docs/vaos/v0/vaos.yaml

this work is part of a continuing effort to ensure the vaos swagger file is current.

updated documentation for facilities_limits

---

modules/mobile/app/models/mobile/v0/adapters/claims_overview.rb

rubocop fixes

---

modules/vaos/app/docs/vaos/v0/vaos.yaml

This work is part of a continuing effort to update the vaos swagger file with the latest changes.

updated documentation for the appointment_requests messages endpoint

---

modules/vaos/app/docs/vaos/v0/vaos.yaml

This work is part of a continuing effort to bring the vaos swagger document current.

Added swagger documentation for the facilities visits endpoint

---

Gemfile

This updates the conditional for dependabot to be able to succesfully install the sidekiq-pro and ent gems

Better way to check if credentials are set for dependabot

---

modules/vaos/app/docs/vaos/v0/vaos.yaml

This work is part of an ongoing effort to make the vaos swagger documentation current.

updated swagger documentation for systems endpiont

---

config/settings.yml

add flipper account access

---

modules/vaos/app/docs/vaos/v0/vaos.yaml

This work is part of an on-going effort to ensure the vaos swagger documentation is up to date.

added swagger documentation for request_eligibility_criteria endpoint

---

modules/vba_documents/spec/fixtures/git_items_benefits.json
modules/vba_documents/spec/fixtures/git_items_forms.json

These are the fixtures for the deployments notifier.  Due to their size they are going in a separate PR.
https://vajira.max.gov/browse/API-5580
Fixtures only.

fixtures for deployment notifier

---

modules/covid_research/app/views/covid_research/volunteer/signup_confirmation.html.erb

Replaces general feedback address with more specific research address.

Update email address in confirmation email

---

lib/decision_review/schemas.rb

This is actually a [***super*** tiny refactor](https://github.com/department-of-veterans-affairs/vets-api/pull/6560#discussion_r611831085).

Tiny Refactor - Open Module Manually So That File Load Order Isn't Important (DecisionReview::Schemas)

---

modules/covid_research/app/views/covid_research/volunteer/signup_confirmation.html.erb

Updates confirmation email text per request of VHA Office of Research & Development.

Update confirmation email text for COVID research app

---

db/schema.rb
modules/appeals_api/db/migrate/20210412175709_add_upload_submission_to_evidence_submissions.rb

Migrations needed for work on API-6346
❗ ❗ Requires #6572 (backwards compat) ❗ ❗ 
https://vajira.max.gov/browse/API-6346

API-6346 EvidenceSubmission migration

---

modules/vaos/app/docs/vaos/v0/vaos.yaml

This is the final pass of the vaos swagger document.

final pass for vaos swagger

---

app/serializers/lighthouse/facilities/facility_serializer.rb
lib/lighthouse/facilities/facility.rb
modules/facilities_api/app/models/facilities_api/v1/lighthouse/facility.rb
modules/facilities_api/spec/models/facilities_api/v1/lighthouse/facility_spec.rb
modules/facilities_api/spec/services/facilities_api/v1/lighthouse/client_spec.rb
spec/lib/lighthouse/facilities/client_spec.rb
spec/request/v1/facilities/va_ccp_request_spec.rb
spec/request/v1/facilities/va_request_spec.rb
spec/support/vcr_cassettes/lighthouse/facilities.yml

Lighthouse has added a new field `detailed_services` to the facilities API, this PR passes the contents to the Front End.
department-of-veterans-affairs/va.gov-team#22736

22736 lighthouse covid19 scheduling data

---

modules/mobile/app/serializers/mobile/v0/push_get_prefs_serializer.rb
modules/mobile/spec/support/schemas/get_prefs_base.json

Removed some array data from get push preferences response array based on front end feedback

removed array data at front end request

---

app/models/saved_claim/education_benefits/va_10203.rb
app/workers/education_form/process10203_submissions.rb

Added additional logging to 10203 processing so that we can verify that user `edipi` is available for claims.
department-of-veterans-affairs/va.gov-team#22822
Tested locally and QA reviewed

Add additional logging to 10203 processing

---

app/mailers/veteran_readiness_employment_mailer.rb
spec/mailers/veteran_readiness_employment_mailer_spec.rb

We recently just implemented a new email notification for VRE form submissions.  This is just a minor PR to adjust the "send to" email address in our staging environment.
department-of-veterans-affairs/va.gov-team#23024
As mentioned above, this is just a minor PR to adjust the email address so no new logging or settings have been added.

Testing VRE emails in staging

---

.rubocop.yml
app/controllers/v0/apidocs_controller.rb
app/swagger/swagger/requests/appeals/appeals.rb
app/swagger/swagger/requests/decision_review_evidence.rb
app/swagger/swagger/schemas/appeals/notice_of_disagreement.rb
lib/decision_review/schemas.rb
lib/decision_review/schemas/NOD_create_request_body_schema.json
modules/appeals_api/config/schemas/10182.json
modules/mobile/app/controllers/mobile/v0/push_notifications_controller.rb
spec/request/swagger_spec.rb

Document NOD API
department-of-veterans-affairs/va.gov-team#23282

Add Docs for va.gov Notice of Disagreement endpoints. 

---

modules/vba_documents/app/workers/vba_documents/report_monthly_submissions.rb
modules/vba_documents/lib/vba_documents/console_utilities.rb
modules/vba_documents/lib/vba_documents/sql_support.rb
modules/vba_documents/spec/fixtures/monthly_report/final_monthly_results.yml
modules/vba_documents/spec/fixtures/monthly_report/max_avg.yml
modules/vba_documents/spec/fixtures/monthly_report/mode.yml
modules/vba_documents/spec/fixtures/monthly_report/still_processing.yml
modules/vba_documents/spec/fixtures/monthly_report/still_success.yml

https://vajira.max.gov/browse/API-5948
breaking up PR to reduce line limit - moving fixtures into this PR

Greg.bowman/api-5948 break out1

---

modules/vba_documents/app/workers/vba_documents/slack_notifier.rb
modules/vba_documents/spec/jobs/slack_notifier_spec.rb

Modifying notification of stuck submissions to notify on all (up to ten) if at least one notification is requiring a notification.
https://vajira.max.gov/browse/API-6188
This check-in controlls internal alerting only.
RSPEC testing

Initial check in

---

config/sidekiq_scheduler.yml
modules/vba_documents/app/views/vba_documents/monthly_report_mailer/_monthly_processing_success.html.erb
modules/vba_documents/app/views/vba_documents/monthly_report_mailer/monthly_report.html.erb
modules/vba_documents/spec/fixtures/monthly_report/monthly_mode_pages.yml

breaking out partial to reduce PR line limitation
https://vajira.max.gov/browse/API-5948

Greg.bowman/api 5948 break out2

---

config/settings.yml

update flipper admins

---

README.md
modules/claims_api/app/swagger/claims_api/forms/form_526_response_swagger.rb
modules/claims_api/config/schemas/526.json

Documentation was out of date.
https://vajira.max.gov/browse/API-6434

API-6434: 422 on Service Branch

---

lib/iam_ssoe_oauth/session_manager.rb

Adds additional IAM SSOe logging around user session creation.
department-of-veterans-affairs/va.gov-team#23475

Add additional IAM SSOe logging around user session creation

---

modules/appeals_api/app/swagger/appeals_api/v1/api_description.md

Updates to our docs to clarify how often statuses are updated.
https://vajira.max.gov/browse/API-5349

API-5349 - Update docs

---

app/controllers/v0/financial_status_reports_controller.rb

- `ages_of_other_dependents` parameter must be an array
- fix typo in `amount_can_be_paid_toward_debt` param
department-of-veterans-affairs/va.gov-team#23588
- Behind Feature flag
- RSpec passing
- Rubocop passing

23588 fix unpermitted params error

---

config/settings.yml

This PR cleans up personnel who are no longer working on the platform

Cleanup flipper personnel

---

config/environments/production.rb

Reverts department-of-veterans-affairs/vets-api#6602

Revert "[6600] Adding account uuid to default rails logging"

---

modules/covid_vaccine/app/jobs/covid_vaccine/scheduled_batch_job.rb
modules/covid_vaccine/spec/jobs/covid_vaccine/scheduled_batch_job_spec.rb

In staging there's no SFTP connection so the enrollment upload job shouldn't run there. This PR updates the scheduled batch job to only kick off an enrollment job if the covid_vaccine enrollment_service job_enabled setting is true.
department-of-veterans-affairs/va.gov-team#23535

Only perform the enrollment upload job if the setting is enabled

---

app/mailers/stem_applicant_denial_mailer.rb

Add GA tracking to STEM denial email link
department-of-veterans-affairs/va.gov-team#22812

Stem tracking

---

modules/claims_api/app/models/claims_api/power_of_attorney.rb
modules/claims_api/lib/tasks/claims_tasks.rake

Also including a rake task to run this in staging, prod, etc
https://vajira.max.gov/browse/API-6192

Add POA status to md5 properties

---

modules/health_quest/app/services/health_quest/questionnaire_manager/basic_questionnaire_manager_formatter.rb
modules/health_quest/spec/services/questionnaire_manager/basic_questionnaire_manager_formatter_spec.rb
modules/health_quest/spec/services/questionnaire_manager/transformer_spec.rb

- Adding the questions and answers from a Questionnaire to the questionnaire_manager index action response

21632 add questions and answers to qr manager

---

modules/vba_documents/app/models/vba_documents/upload_submission.rb
modules/vba_documents/lib/vba_documents/console_utilities.rb

Using the metadata jsonb column we are adding in a flag indicating that the success record updated will stay in success and will not move to vbms. This is done via the console as a monthly manual update process.
https://vajira.max.gov/browse/API-6289

Greg.bowman/api 6289 monthly manual update final success flag

---

config/features.yml

Feature flag for this frontend PR:
https://github.com/department-of-veterans-affairs/vets-website/pull/16759

add feature toggle for sharable links on faq pages ##16759

---

app/controllers/v0/search_click_tracking_controller.rb
app/swagger/swagger/requests/search_click_tracking.rb
config/settings.yml
lib/search_click_tracking/service.rb
spec/lib/search_click_tracking/service_spec.rb
spec/request/search_click_tracking_request_spec.rb
spec/request/swagger_spec.rb

This code updates the module code parameter to have a default value but still take input
https://github.com/department-of-veterans-affairs/va.gov-team/issues/22131
Tweak the settings.yml

Add module code as variable

---

Gemfile.lock

https://github.com/department-of-veterans-affairs/vets-api/pull/6671 upgraded rexml, but it breaks login

revert rexml upgrade

---

modules/vaos/app/services/vaos/appointment_service.rb
modules/vaos/app/services/vaos/systems_service.rb

The work here was to remove outdated timeouts in service calls to VAMF.  The timeouts were included as temporary fixes for latency issues that have since been resolved.

removed outdated timeouts for service calls

---

Jenkinsfile

Use the new [`content_branch` parameter](https://github.com/department-of-veterans-affairs/devops/pull/9043) in the `vets-review-instance-deploy` job.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/22158

Use content_branch param in review instance deploy

---

app/controllers/v0/veteran_readiness_employment_claims_controller.rb
app/models/saved_claim/veteran_readiness_employment_claim.rb
spec/models/saved_claim/veteran_readiness_employment_claim_spec.rb

We have been asked to create a daily report of Chapter 31 submissions.  In the report, they have asked us to include the regional office location where the form was submitted.  Currently, we do not store the regional office location associated with the user in the form, so this PR updates the claim to include the regional office number.  
\* Please note that the PR for the report itself will be in a separate PR due to LoC limits.
department-of-veterans-affairs/va.gov-team#23577
This is a minor update to existing functionality, so no new settings or logging have been added.

Adding Regional Office to Chapter 31 Form

---

app/policies/ch33_dd_policy.rb
config/features.yml
spec/controllers/v0/profile/ch33_bank_accounts_controller_spec.rb

remove backend ch33 direct deposit feature flag because it has already been enabled for 100% of users
https://github.com/department-of-veterans-affairs/va.gov-team/issues/23448
tested with automated tests

remove backend ch33 direct deposit feature flag

---

modules/facilities_api/app/controllers/facilities_api/v1/va_controller.rb
modules/facilities_api/spec/requests/facilities_api/v1/va_request_spec.rb

My last PR was over the 500 lines, the easiest way to peel the onion was to remove the controller and tests (480 lines) and add them to this PR.
department-of-veterans-affairs/va.gov-team#18532

Re adding the VA controller into the engine

---

lib/decision_review/service.rb

Lighthouse is changing header names in pr #6702 so we are making the corresponding chnges.  The VCR cassettes already have the names of the new headers.

update NOD headers

---

modules/vba_documents/app/mailers/vba_documents/monthly_report_recipients.yml
modules/vba_documents/app/models/vba_documents/upload_submission.rb
modules/vba_documents/app/workers/vba_documents/report_monthly_submissions.rb
modules/vba_documents/app/workers/vba_documents/upload_status_batch.rb
modules/vba_documents/lib/vba_documents/console_utilities.rb
modules/vba_documents/lib/vba_documents/sql_support.rb

…sv file; refactored VBMS_IMPLEMENTATION_DATE moving it from upload_status_batch.rb to upload_submission.rb;
update monthly report to look at the new final_success_status flag in upload_submission that is updated monthly based on the csv report
https://vajira.max.gov/browse/API-6671

update monthly report to use final_success_status in metadata

---

.circleci/config.yml
.github/workflows/code_checks.yml
rakelib/security.rake

Temporarily ignore this CVE as REXML 3.2.5 has some breaking changes 
department-of-veterans-affairs/va.gov-team#23835

Ignore CVE-2021-28965

---

modules/health_quest/app/services/health_quest/questionnaire_manager/transformer.rb

- Removed line of code which was preventing Questionnaire Responses from showing up on the QR manager index.

21632 fix qr manager questionnaire responses

---

modules/va_forms/app/workers/va_forms/form_reloader.rb

https://vajira.max.gov/browse/API-6703
No to all
Local testing

Blanking out form detail URL when a form is unpublished

---

app/controllers/v0/debts_controller.rb
app/controllers/v0/financial_status_reports_controller.rb
app/models/form_profiles/va_5655.rb
app/policies/debt_policy.rb
lib/debt_management_center/base_service.rb
lib/debt_management_center/payments_service.rb
spec/models/form_profile_spec.rb
spec/policies/debt_policy_spec.rb

- Implementing Debt access policy
- Better error handling when calling BGS People and Payments services.
department-of-veterans-affairs/va.gov-team#23588

Fix debt bgs user issue

---

modules/vba_documents/app/mailers/vba_documents/monthly_report_recipients.yml
modules/vba_documents/app/models/vba_documents/upload_submission.rb
modules/vba_documents/lib/vba_documents/sql_support.rb

updated for upcoming monthly report run tomorrow
https://vajira.max.gov/browse/API-6289

updated recipient list; casting avg time as integer; updated success_sql

---

modules/va_forms/app/workers/va_forms/form_reloader.rb

https://vajira.max.gov/browse/API-6703
No to all

rolling back until wednesday

---

modules/claims_api/app/swagger/claims_api/forms/form_2122_response_swagger.rb

Updates documentation to match current implementation.
https://vajira.max.gov/browse/API-6498
Reviewed within developer portal locally.

API-6498: Limited Consent Schema Incorrect

---

db/schema.rb

This adds the necessary schema changes for this [PgHero PR](https://github.com/department-of-veterans-affairs/vets-api/pull/6744)
https://github.com/department-of-veterans-affairs/vets-api/pull/6744
department-of-veterans-affairs/va.gov-team#24001

add schema changes for PgHero gem

---

modules/va_forms/app/workers/va_forms/form_reloader.rb

https://vajira.max.gov/browse/API-6703
No to all
Local testing

Removing URL when unpublished

---

app/mailers/ch31_submissions_report_mailer.rb
spec/mailers/ch31_submissions_report_mailer_spec.rb

We recently created a daily report for Chapter 31 submissions.  This PR is just a slight modification to add an additional email address to the email send to addresses.  
department-of-veterans-affairs/va.gov-team#23577
This is a very minor PR that just adds an additional email address so no new logging or settings have been added.

Adding another email to send Chapter 31 daily submissions report

---

db/migrate/20210504163547_pghero_query_stats.rb
db/schema.rb

This adds the pghero_query_stats migration file needed to add this table to the database

add pghero migration

---

modules/appeals_api/spec/factories/evidence_submissions.rb
modules/appeals_api/spec/requests/v1/notice_of_disagreements/evidence_submissions_controller_spec.rb
modules/appeals_api/spec/serializers/evidence_submission_serializer_spec.rb

Experiencing build failures corresponding to this spec file. Attempting to fix.

Attempt at fixing our build bug

---

modules/appeals_api/app/services/appeals_api/evidence_submission_request_validator.rb
modules/appeals_api/config/locales/en.yml
modules/appeals_api/spec/factories/status_updates.rb
modules/appeals_api/spec/services/appeals_api/evidence_submission_request_validator_spec.rb

[API-6669](https://vajira.max.gov/browse/API-6669)
This PR adds a check ensuring that the NOD is within the submission window for evidence submission (90 days)

Api 6669/91 day validation evidence window

---

app/models/appeal_submission.rb
db/migrate/20210429131042_notice_of_disagreement.rb
db/schema.rb

migrations to go with #6764 - Ready for review, despite status

---

modules/va_forms/app/swagger/va_forms/v0/controller_swagger.rb

https://vajira.max.gov/browse/API-6809
No to all
Tested locally

Adding a 429 Response to Swagger

---

db/migrate/20210505180038_add_vrrap_to_edu_submissions.rb
db/schema.rb
spec/models/education_benefits_claim_spec.rb

Database changes for https://github.com/department-of-veterans-affairs/vets-api/pull/6784
department-of-veterans-affairs/va.gov-team#24192

Add vrrap column to EducationBenefitsSubmission

---

app/controllers/v0/search_typeahead_controller.rb

This PR adds a status pass through for the proxy endpoint
https://github.com/department-of-veterans-affairs/va.gov-team/issues/24305

pass response status through

---

db/migrate/20210507122840_add_stats_extension.rb
db/schema.rb

This PR adds the pg_stat_statements extension to the db via migration
department-of-veterans-affairs/va.gov-team#24250

add pg_stat_statements extension

---

lib/decision_review/schemas/NOD_create_request_body_schema.json

updates NOD schema to match lighthouse's form 10182 schema
https://github.com/department-of-veterans-affairs/va.gov-team/issues/24273

update NOD schema to match lighthouse schema

---

modules/vaos/app/controllers/vaos/v2/appointments_controller.rb
modules/vaos/app/docs/vaos/v2/vaos_v2.yaml
modules/vaos/app/models/vaos/v2/appointment_form.rb
modules/vaos/app/services/vaos/v2/appointments_service.rb
modules/vaos/config/routes.rb
modules/vaos/spec/factories/v2/appointment_forms.rb
modules/vaos/spec/request/v2/appointments_request_spec.rb
modules/vaos/spec/services/v2/appointment_service_spec.rb
spec/support/schemas/vaos/v2/appointment.json
spec/support/vcr_cassettes/vaos/v2/appointments/post_appointments.yml
spec/support/vcr_cassettes/vaos/v2/appointments/post_appointments_500.yml

Added full vertical integration for post_appointment for the new VAOS service. Once the service is hosted in staging, VCR cassettes will be officially recorded and further unit testing will commence.

Full vertical integration for post_appointment endpoint

---

app/controllers/v0/virtual_agent_token_controller.rb

Adds a couple of lines of code to log in sentry
department-of-veterans-affairs/va-virtual-agent#164
Sentry logging was added for the case in which the token exchange endpoint returns anything other that 200

Adds sentry logs to virtual agent

---

modules/vba_documents/app/workers/vba_documents/deployments_notifier.rb

Fixing duplicate notifications that occur if the job is called multiple times.
https://vajira.max.gov/browse/API-6527

Fixing duplicate notifications

---

modules/vba_documents/app/views/vba_documents/common/_table_styling.html.erb
modules/vba_documents/app/views/vba_documents/monthly_report_mailer/_elapsed_status_times.html.erb
modules/vba_documents/app/views/vba_documents/monthly_report_mailer/_time_btw_statuses.html.erb

Updated table styling
https://vajira.max.gov/browse/API-6861

updated table formatting

---

.github/workflows/code_checks.yml
Jenkinsfile

Moves Danger back into the Jenkinsfile as a stage because it was running correctly as a GitHub Action.

Revert Danger to Jenkinsfile

---

modules/appeals_api/config/schemas/v2/200996.json
modules/appeals_api/config/schemas/v2/200996_headers.json

Updates schema for HLR v2 form.
Ticket: https://vajira.max.gov/browse/API-6892

API-6892 First pass update v2 schema

---

modules/veteran/app/models/veteran/user.rb
modules/veteran/spec/models/veteran/user_spec.rb

Sorting issue with previous poa codes list.
https://vajira.max.gov/browse/API-7126
Tested logic change in sandbox first to understand and verify.
Added spec to test for the correct sort.

API-7126: Previous/active POA still not working as expected in sandbox

---

app/workers/education_form/process10203_submissions.rb

Additional logging PR following #6857 to determine the source of the missing EDIPI for EVSS PoA request errors.

[22732] adds auth_headers to debug EVSS 502 errors 

---

modules/vba_documents/app/mailers/vba_documents/monthly_report_recipients.yml
modules/vba_documents/app/mailers/vba_documents/unsuccessful_report_recipients.yml

Publishing reports to slack
https://vajira.max.gov/browse/API-6641

publishing reports to slack

---

modules/appeals_api/app/controllers/appeals_api/docs/v2/docs_controller.rb
modules/appeals_api/app/swagger/appeals_api/v2/higher_level_reviews_controller_swagger.rb
modules/appeals_api/app/swagger/appeals_api/v2/schemas/higher_level_reviews.rb
modules/appeals_api/app/swagger/appeals_api/v2/security_scheme_swagger.rb

Adds swagger files for HLR v2 docs.
https://vajira.max.gov/browse/API-6901

API-6901 - Add hlr v2 swagger files

---

config/settings.yml

Make status simulation disabled by default.
https://vajira.max.gov/browse/API-7287

API-7287 - Status simulation

---

modules/vba_documents/lib/vba_documents/upload_validator.rb
modules/vba_documents/spec/jobs/upload_processor_spec.rb
modules/vba_documents/spec/request/v2/uploads_request_spec.rb

Rolling back name validations
https://vajira.max.gov/secure/RapidBoard.jspa?rapidView=1521&selectedIssue=API-7343

Rolling back validations

---

config/features.yml

add language support feature flag for https://github.com/department-of-veterans-affairs/va.gov-team/issues/23305

add language support feature flag

---

Gemfile.lock
spec/factories/veteran_readiness_employment_claim.rb

This updates the version of vets-json-schema in Gemfile.lock
department-of-veterans-affairs/va.gov-team#23998

23998 - update vets-json-schema version

---

modules/vaos/app/services/vaos/appointment_service.rb

Increased timeout threshold for get_appointments endpoint
All tests / rubocop green!

Increased timeout threshold for get_appointments endpoint

---

modules/vba_documents/app/swagger/vba_documents/document_upload/metadata_swagger.rb
modules/vba_documents/lib/vba_documents/upload_validator.rb
modules/vba_documents/spec/fixtures/valid_metadata_space_in_name.json
modules/vba_documents/spec/jobs/upload_processor_spec.rb
modules/vba_documents/spec/request/v2/uploads_request_spec.rb

Adding in spaces to the allowed list of characters in first/last name validators
https://vajira.max.gov/browse/API-7344
RSPEC added

Adding in space to name validation

---

app/mailers/ch31_submissions_report_mailer.rb
config/settings.yml
spec/mailers/ch31_submissions_report_mailer_spec.rb

We have a daily report email that gets generated for Chapter 31 submissions.  This PR is just to add to the list of recipients currently receiving the email.
department-of-veterans-affairs/va.gov-team#24943
Minor PR that just adds email addresses so no new settings or logging have been added.

Add email recipients to Chapter 31 daily report

---

modules/appeals_api/app/controllers/appeals_api/v1/decision_reviews/notice_of_disagreements/evidence_submissions_controller.rb
modules/appeals_api/app/services/appeals_api/evidence_submission_request_validator.rb
modules/appeals_api/config/locales/en.yml
modules/appeals_api/spec/requests/v1/notice_of_disagreements/evidence_submissions_controller_spec.rb

[API-7288](https://vajira.max.gov/browse/API-7288)
This PR updates the reference identifier for the Notice of Disagreement in Evidence Submissions to be more consistent with the rest of decision reviews.

update nod reference for evidence submission

---

modules/claims_api/app/swagger/claims_api/v2/swagger_root.rb

Adds the "development" environment as a selectable option on the v2 curl generation docs.
[API-7232](https://vajira.max.gov/browse/API-7232)

[API-7232] - Adds "dev" as a selectable option for ClaimsApi v2 docs

---

.rspec_parallel

We want to put this back to help debug failing specs and fix the space

put back progress format

---

modules/health_quest/lib/tasks/lighthouse.rake

- Create rake task for creating Questionnaires on Lighthouse
- Create rake task for updating Questionnaires on Lighthouse

21632 Questionnaire rake task

---

Gemfile.lock

This pull request is to update the version of vets-json-schema to the one merged in here - https://github.com/department-of-veterans-affairs/vets-json-schema/pull/593
https://github.com/department-of-veterans-affairs/va.gov-team/issues/24211
The corresponding vets-json-schema update adds a new schema for VA Form 21-0538

Bumping vets-json-schema version

---

app/models/saved_claim/veteran_readiness_employment_claim.rb
spec/models/saved_claim/veteran_readiness_employment_claim_spec.rb

The VR&E pilot is being paused and needs to stop data from being sent to the CMS for an unknown period of time.  I've removed some code to prevent submissions going to their system.  I've also commented out some lines of code in the specs - I know we don't love doing this, but we are going to be putting it back so didn't want to remove them completely.
department-of-veterans-affairs/va.gov-team#25334
This is a minor PR to temporarily prevent Chapter 31 submissions from being sent to the VR&E system for processing.

Pause Chapter 31 Submissions

---

db/migrate/20210527143944_add_column_ranking_to_va_forms_forms.rb
db/migrate/20210528151724_add_column_tags_to_va_forms_forms.rb
db/schema.rb

Adding a couple columns for future code release 
https://vajira.max.gov/browse/API-7354
No to all

Updates for ranking

---

modules/appeals_api/app/swagger/appeals_api/v2/api_description.md
modules/appeals_api/app/swagger/appeals_api/v2/swagger_root.rb

This PR copies our v1 API description markdown file to v2 so that we can update it as necessary with subsequent PRs.
https://vajira.max.gov/browse/API-6901

API-6901 - v2 docs api description file

---

modules/health_quest/app/marshallers/health_quest/json_marshaller.rb
modules/health_quest/app/models/health_quest/questionnaire_response.rb
modules/health_quest/spec/marshallers/json_marshaller_spec.rb

- Copying dependency from the main Rails app to our HealthQuest Engine.
- Behind feature flag
- Tests passing
- Rubocop passing

21632 porting json marshaller into health-quest

---

modules/health_quest/lib/tasks/lighthouse.rake

- Moving helpers and constants inside the tasks for now so that other teams are not blocked by rake-related issues. Will implement a better solution in the near future.

Move helpers inside task to unblock other teams

---

config/features.yml

Adding feature flip for new Check-in experience
- [Spike](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25214)
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)

Added check-in feature flip

---

db/migrate/20210602154022_add_insert_ranking_to_va_forms_forms.rb
db/schema.rb

Populating new columns with data
https://vajira.max.gov/browse/API-7383

Populating data

---

modules/health_quest/app/services/health_quest/shared/options_builder.rb
modules/health_quest/spec/services/shared/options_builder_spec.rb

- Adding ability to paginate FHIR resources
department-of-veterans-affairs/va.gov-team#25430

25430 Adding ability to paginate FHIR resources

---

modules/claims_api/app/swagger/claims_api/v0/claims_controller_swagger.rb
modules/claims_api/app/swagger/claims_api/v1/claims_controller_swagger.rb
modules/claims_api/app/swagger/claims_api/v2/veterans/claims_controller_swagger.rb
modules/claims_api/app/swagger/v1/swagger.json
modules/claims_api/spec/requests/v1/rswag_claims_request_spec.rb

Update documentation verbiage to make it clear the claims we provide are not medical.
https://vajira.max.gov/browse/API-6750

API-6750: Update description for Benefits Claims API

---

Gemfile.lock

Bumps google-apis-generator to the latest minor version. Dependabot has the maximum PRs open and just doing some house keeping

bump google-apis-generator   minor version

---

modules/health_quest/lib/health_quest/engine.rb

- Removing a line that's essentially a relic from when the app was originally created.
department-of-veterans-affairs/va.gov-team#25608

25608 Remove environment check and redundant load

---

modules/health_quest/app/services/health_quest/shared/options_builder.rb
modules/health_quest/spec/services/shared/options_builder_spec.rb

- Ability to search for a location by it's clinic identifier.
department-of-veterans-affairs/va.gov-team#25620

25620 search location by identifier

---

app/workers/decision_review/submit_upload.rb
lib/decision_review/service.rb
spec/lib/decision_review/service_spec.rb
spec/support/vcr_cassettes/decision_review/NOD-GET-UPLOAD-URL-200.yml
spec/support/vcr_cassettes/decision_review/NOD-GET-UPLOAD-URL-404.yml

lighthouse renamed the param so we should too.

rename nod_id to nod_uuid

---

app/workers/decision_review/submit_upload.rb
config/initializers/statsd.rb
spec/jobs/decision_review/submit_upload_spec.rb

Add NOD worker metrics

---

config/settings.yml
spec/mailers/year_to_date_report_mailer_spec.rb

department-of-veterans-affairs/va.gov-team#24562

VRRAP: Update YTD prod report distribution

---

Gemfile.lock

Updates Brakeman to 5.0.2
department-of-veterans-affairs/va.gov-team#25767

Update brakeman to 5.0.2

---

.github/CODEOWNERS
Gemfile
Gemfile.lock
config/routes.rb
modules/check_in/Gemfile
modules/check_in/README.rdoc
modules/check_in/Rakefile
modules/check_in/bin/rails
modules/check_in/check_in.gemspec
modules/check_in/config/routes.rb
modules/check_in/lib/check_in.rb
modules/check_in/lib/check_in/engine.rb
modules/check_in/lib/check_in/version.rb
modules/check_in/spec/spec_helper.rb
spec/simplecov_helper.rb
spec/spec_helper.rb

- Generating a new Rails engine for the `Check-in` project
- Adding to the CODEOWNERS file

25713 Generate check_in Rails engine

---

config/settings.yml

The PM on our team would like to be able to enable and disable feature toggles, this PR ads his email to the list of admins for feature toggles.

Added Jason Wolf to feature toggle admins

---

Gemfile
Gemfile.lock

bump brakeman to 5.0.4

---

modules/openid_auth/README_V2.yml

Update the v2 TV OAS to be more complete.
* Add examples
* Expand response schema(s)
* Add error schema(s)
* Add request body
* Update descriptions.
https://vajira.max.gov/browse/API-7463

API-7463 - Update v2 TV OAS

---

modules/appeals_api/config/schemas/v2/200996.json

Needed to clarify the role of POA as related to the Veteran's conference rep.
Ticket: https://vajira.max.gov/browse/API-6693

API-6693 Add description for conference rep to swagger docs

---

modules/vaos/app/controllers/vaos/v2/appointments_controller.rb
modules/vaos/app/models/vaos/v2/appointment_form.rb
modules/vaos/app/services/vaos/v2/appointments_service.rb
modules/vaos/spec/factories/v2/appointment_forms.rb
modules/vaos/spec/request/v2/appointments_request_spec.rb
modules/vaos/spec/services/v2/appointment_service_spec.rb

This is to fix an issue where the patientIcn was not being correctly passed to VAMP.  Explicitly merging user.icn into the request_body
Tests were updated to reflect this change.

Explicitly merging user.icn into the request_body

---

app/controllers/v1/sessions_controller.rb

This PR adds a set of logs to Sessions Controller, and adds the Account UUID, which should help with traceability of the user through the auth flow.
department-of-veterans-affairs/vets-api/issues/6697

[6697] Adding Account UUID to Session Controller Auth Logs

---

config/features.yml

Removing Higher-Level Review form feature flag
https://github.com/department-of-veterans-affairs/va.gov-team/issues/25829

Remove HLR feature flag

---

modules/health_quest/app/controllers/health_quest/v0/base_controller.rb
modules/health_quest/app/controllers/health_quest/v0/questionnaire_manager_controller.rb
modules/health_quest/app/services/health_quest/questionnaire_manager/factory.rb
modules/health_quest/spec/services/questionnaire_manager/factory_spec.rb
spec/spec_helper.rb

- We need additional logging around the Questionnaire Manager while testing in production with our pilot facility
- Additional logging will be removed once we're satisfied that the feature is operating adequately for all involved users
- Temporarily turning off test coverage for the QuestionnaireManager Factory class. We will revert this change once testing in production has been completed.
department-of-veterans-affairs/va.gov-team#25927

25927 adding extra logging around QR manager feature

---

modules/health_quest/app/services/health_quest/questionnaire_manager/factory.rb

- Fetch appointments and questionnaire responses two weeks from now and a month ago from now
department-of-veterans-affairs/va.gov-team#25957

25957 changing the date range for resources

---

modules/vaos/app/controllers/vaos/v2/appointments_controller.rb
modules/vaos/app/models/vaos/v2/appointment_form.rb
modules/vaos/app/services/vaos/v2/appointments_service.rb

Permit validation has been updated to validate correctly against nested object/arrays.

WIP for RI

---

config/features.yml

Removed Form 526 Feature Flags that are no longer needed.

Remove feature flags

---

config/settings.yml
config/settings/test.yml
modules/health_quest/app/services/health_quest/facilities/request.rb
modules/health_quest/spec/services/facilities/request_spec.rb

- Switch the Questionnaire feature over to the new Facilities endpoint.
department-of-veterans-affairs/va.gov-team#25440

25440 use new facilities endpoint

---

app/controllers/v0/caregivers_assistance_claims_controller.rb

Downloading a pre-filled 10-10CG should not require fully valid 10-10cg data. Allow pdf download even if veteran's name is missing.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/14287

Allow download of 10-10cg with no veteran name

---

app/controllers/v0/example_controller.rb

Updates the welcome message of api.va.gov to reflect the updated naming convention of the overall site.
Really nothing much extra to know here, simple naming convention update.

update welcome message

---

modules/claims_api/app/mailers/claims_api/unsuccessful_report_mailer.rb
modules/claims_api/spec/mailers/unsuccessful_report_mailer_spec.rb

Mark requested we remove Valerie from our daily unsuccessful claims report.

remove Valerie from claims report

---

modules/va_forms/postman_tests/Automated Forms API.postman_collection.json
modules/va_forms/postman_tests/Forms_Postman.md
modules/vba_documents/postman_tests/Benefits Intake.postman_collection.json
modules/vba_documents/postman_tests/Benefits_Intake_Postman.md
modules/vba_documents/postman_tests/Sandbox Environment.postman_environment.json
modules/vba_documents/postman_tests/localhost Environment.postman_environment.json

New automated Postman testing functionality added for the Benefits Intake and Forms APIs.
https://vajira.max.gov/browse/API-7592
https://vajira.max.gov/browse/API-7808
Not affecting production code.

Kevin.cranmer/api 7592 postman testing

---

config/settings.yml
modules/health_quest/lib/tasks/lighthouse.rake

- Do not require an icn to create or update a questionnaire
- Update Lighthouse client_id in the settings.yml file
department-of-veterans-affairs/va.gov-team#26154

26154 questionnaire rake update

---

config/features.yml

Adding a feature toggle for medical copays so we can begin development
[Ticket](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/26261)

Add feature toggle for medical copays

---

modules/appeals_api/app/views/appeals_api/decision_review_mailer/mailer.html.erb

Fixes duplicate word on mailer.
https://vajira.max.gov/browse/API-7871

API-7871 - fix typo

---

modules/check_in/app/controllers/check_in/application_controller.rb
modules/check_in/app/controllers/check_in/v0/patient_check_ins_controller.rb
modules/check_in/check_in.gemspec
modules/check_in/config/routes.rb
modules/check_in/spec/request/patient_check_ins_request_spec.rb
modules/check_in/spec/spec_helper.rb

- Creating new basic and minimal GET and POST routes
- Adding controllers
- Adding request specs
- Configuration
department-of-veterans-affairs/va.gov-team#25899
department-of-veterans-affairs/va.gov-team#25976

25899 Check-In basic routes

---

config/initializers/rswag-ui.rb
modules/claims_api/config/routes.rb

Display swagger-ui for interactions with our API.
Should display at the following style url:  http://localhost:3000/services/claims/docs/swagger
https://vajira.max.gov/browse/API-7861

API-7861: Replace existing sample app for sandbox with swagger-ui

---

app/swagger/swagger/requests/preneeds_claims.rb
lib/preneeds/service.rb
spec/request/swagger_spec.rb

https://github.com/department-of-veterans-affairs/va.gov-team/issues/26441

Add /v0/preneeds/cemeteries documentation

---

modules/vba_documents/app/swagger/vba_documents/document_upload/put_description.md
modules/vba_documents/app/swagger/vba_documents/v1/description.md

Swagger updates
https://vajira.max.gov/browse/API-7810
Yes to swagger, no to all others

Swagger updates for Benefit API

---

modules/check_in/app/controllers/check_in/application_controller.rb
modules/check_in/spec/request/patient_check_ins_request_spec.rb

- Calling requests must pass in the approved cookie_id to proceed
department-of-veterans-affairs/va.gov-team#26267

26267 basic module authorization

---

lib/evss/vso_search/service.rb

Restores a conditional to the check for a user's SSN to fix NoMethodError occurances

[22732] restores conditional user ssn check

---

modules/facilities_api/app/services/facilities_api/v1/ppms/client.rb

We are in the process of upgrading the URL that we use to talk to PPMS, this change should have been behind a feature flag and went out pre-maturely. 
department-of-veterans-affairs/va.gov-team#26543

The secure url was not behind a flipper

---

config/initializers/rswag-ui.rb
modules/claims_api/config/routes.rb

Something's still up with deploys, seeing `LoadError: cannot load such file -- rswag`. Reverting until we can verify this pre-merge 😞 
https://vajira.max.gov/browse/API-7861

Revert swagger-ui changes

---

modules/appeals_api/app/controllers/appeals_api/v2/decision_reviews/notice_of_disagreements_controller.rb
modules/appeals_api/config/routes.rb
modules/appeals_api/spec/requests/v2/notice_of_disagreements_controller_spec.rb

[API-8151](https://vajira.max.gov/browse/API-8151)
This PR copies over NOD V1 to V2, as per the lighthouse versioning requirements.

Api 8151/move nod v1 to v2

---

modules/appeals_api/app/controllers/appeals_api/application_controller.rb
modules/appeals_api/spec/controllers/application_controller_spec.rb

[API-8155](https://vajira.max.gov/browse/API-8155)
Automatically deactivate endpoint based on defined sunset date

automatically shut off endpoint if sunset date is defined

---

modules/test_user_dashboard/app/controllers/test_user_dashboard/application_controller.rb
modules/test_user_dashboard/spec/requests/tud_accounts_request_spec.rb

While steps have been taken to place the TUD frontend behind SOCKS and add basic auth, the TUD API route is available publicly; direct requests to it would allow anyone to receive all of the test user information available in the app, including user passwords. This change will add authentication based on a shared secret key passed through a JWT.
department-of-veterans-affairs/va.gov-team#25292
This PR is a WIP.

[25292] TUD API Route Authentication

---

modules/test_user_dashboard/app/services/test_user_dashboard/create_test_user_account.rb
modules/test_user_dashboard/spec/services/create_test_user_account_spec.rb
modules/test_user_dashboard/spec/support/spec_users.csv

The TUD application was originally designed to fetch a list of a test account's available services from MPI upon its instantiation. After being informed that this functionality was only returning default services, I investigated further and discovered that a lack of LOA3 authentication is preventing calls from being made to MPI; as these are test users who have not been authenticated to vets-api at the time the call is being made, LOA3 authentication and thus live services information from MPI is not possible.
This change does away with attempting to query MPI for these services and instead includes them with the rest of the tud_account information in the `test_users.cvs` file that is maintained [here.](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Adm …

[25158] updates TUD population to pull services from the test_users.csv file

---

modules/appeals_api/app/controllers/appeals_api/v1/decision_reviews/higher_level_reviews/contestable_issues_controller.rb
modules/appeals_api/app/controllers/appeals_api/v1/decision_reviews/notice_of_disagreements/contestable_issues_controller.rb
modules/appeals_api/app/controllers/appeals_api/v2/decision_reviews/higher_level_reviews/contestable_issues_controller.rb
modules/appeals_api/app/controllers/appeals_api/v2/decision_reviews/notice_of_disagreements/contestable_issues_controller.rb
modules/appeals_api/app/swagger/appeals_api/v1/higher_level_reviews_controller_swagger.rb

[API-8152](https://vajira.max.gov/browse/API-8152)
This PR adds deprecation headers to V1 HLR Contestable Issues endpoint.

Api 8152/deprecate v1 contestable issues

---

config/settings.yml
config/settings/test.yml
modules/check_in/app/controllers/check_in/v0/patient_check_ins_controller.rb
modules/check_in/app/services/chip_api/request.rb
modules/check_in/app/services/chip_api/service.rb
modules/check_in/spec/request/patient_check_ins_request_spec.rb
modules/check_in/spec/services/chip_api/request_spec.rb
modules/check_in/spec/services/chip_api/service_spec.rb

26057 chip api basic harness
- Setup configuration
- Setup the Chip API request functionality
- Setup the Chip API service object
- Setup routing and controllers
- Setup basic testing
department-of-veterans-affairs/va.gov-team#26057

26057 chip api harness

---

config/features.yml
config/settings.yml

Added a new feature flag for walk-in availability to covid vaccine related search results in facility locator
https://github.com/department-of-veterans-affairs/va.gov-team/issues/26282
I also added my email to the flipper section of `settings.yml`

Flipper - add facility_locator_covid_vaccine_walk_in_availability_text_frontend

---

config/settings.yml

Add self to flipper white list.

Flipper - add Dat Tran flipper access

---

config/settings.yml

I am a backend dev on the eBenefits migration team and could use access to help with User Acceptance Testing issues where testers need access to certain features so the testing doesn't get cancelled and can be done.

Adding KEVIN MUSIORSKI (GCIO) as a feature flipper admin

---

modules/health_quest/app/controllers/health_quest/v0/base_controller.rb
modules/health_quest/app/controllers/health_quest/v0/questionnaire_manager_controller.rb
modules/health_quest/app/services/health_quest/questionnaire_manager/factory.rb
modules/health_quest/spec/services/questionnaire_manager/factory_spec.rb
spec/spec_helper.rb

- Remove the Rails loggers we set up to test in staging and prod environments. These are no longer needed.
department-of-veterans-affairs/va.gov-team#25944

25944 roll back additional logging

---

modules/appeals_api/app/swagger/appeals_api/v2/higher_level_reviews_controller_swagger.rb

[API-8462](https://vajira.max.gov/browse/API-8462)
Edit swagger copy to reflect new API versioning changes

fix v2 contestable issues

---

config/features.yml
modules/va_forms/app/controllers/va_forms/v0/forms_controller.rb

https://vajira.max.gov/browse/API-7383
Tested on staging with va.gov team

Removing feature flag for form search algorithm

---

modules/va_forms/app/controllers/va_forms/v0/forms_controller.rb
modules/va_forms/lib/tasks/update_form_tags.rake
modules/va_forms/lib/va_forms/regex_helper.rb
modules/va_forms/spec/lib/regex_helper_spec.rb

https://github.com/department-of-veterans-affairs/va.gov-team/issues/26970
no to all

Mark.viterna/form alg 10101

---

config/features.yml

corresponding change in `vets-website`: https://github.com/department-of-veterans-affairs/vets-website/pull/17800
https://github.com/department-of-veterans-affairs/va.gov-team/issues/26837

Add profile_notification_settings feature flag

---

modules/health_quest/lib/tasks/lighthouse.rake

- Perform a refactor that will extract the duplicate code into its own module/class within the rake file.
department-of-veterans-affairs/va.gov-team#25945

25945 refactoring to remove duplication

---

modules/appeals_api/app/models/appeals_api/higher_level_review.rb
modules/appeals_api/app/models/concerns/appeals_api/contestable_issue.rb
modules/appeals_api/app/services/appeals_api/pdf_construction/higher_level_review/pages/v1/additional_issues.rb
modules/appeals_api/app/services/appeals_api/pdf_construction/higher_level_review/pages/v2/additional_issues.rb
modules/appeals_api/app/services/appeals_api/pdf_construction/higher_level_review/v1/structure.rb
modules/appeals_api/app/services/appeals_api/pdf_construction/higher_level_review/v2/form_data.rb
modules/appeals_api/app/services/appeals_api/pdf_construction/higher_level_review/v2/structure.rb
modules/appeals_api/spec/models/concerns/appeals_api/contestable_issue_spec.rb
modules/appeals_api/spec/models/higher_level_review_spec.rb

[API-7661](https://vajira.max.gov/browse/API-7661)
This PR is pulled out of [this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/7334) to allow for the 500 line limit].
It pulls out contestable issues into an abstractions, updates references and refactors validations.

Api 7661/contestable issue class

---

config/routes.rb
config/settings.yml
config/settings/test.yml
modules/test_user_dashboard/spec/requests/tud_accounts_request_spec.rb

This PR updates the gating of the TUD API endpoints to use system settings instead of checking the Rails environment. This is a cleaner and easier way to manage whether or not the TUD endpoints should be made available on a specific instance.
department-of-veterans-affairs/va.gov-team#26888
Manual testing through an API client and frontend requests to confirm availability/unavailability of both TUD routes.

[26888] Tud routes

---

config/features.yml
config/settings.yml

Add a backend-specific feature toggle to support future work.
department-of-veterans-affairs/va.gov-team#26269
Also add myself to the flipper white list.

Add ezcg_use_facility_api feature flag

---

app/controllers/v0/search_click_tracking_controller.rb
app/swagger/swagger/requests/search_click_tracking.rb
config/settings.yml
lib/search_click_tracking/service.rb
spec/lib/search_click_tracking/service_spec.rb
spec/request/search_click_tracking_request_spec.rb
spec/request/swagger_spec.rb
spec/support/vcr_cassettes/search_click_tracking/missing_parameter.yml
spec/support/vcr_cassettes/search_click_tracking/success.yml

This PR removes the Client IP address param from search click tracking, and updates the local settings for search
department-of-veterans-affairs/va.gov-team#24992
This PR updates an existing endpoint, and should be very low impact.
There is a settings.yml file update, but it only affects local envs

Search local settings update

---

Gemfile.lock

**Draft until https://github.com/department-of-veterans-affairs/vets-api/pull/7416 has been merged**
this pull request updates the entry for vets-json-schema in gemfile.lock.
department-of-veterans-affairs/va.gov-team#26290
Related to https://github.com/department-of-veterans-affairs/vets-json-schema/pull/616

26290 update vets-json-schema gemfile.lock

---

config/settings.yml

- Adding CHIP API settings for the Check-In project.
- These will be used to test in dev and staging. Production settings will be added later.
department-of-veterans-affairs/va.gov-team#26899

26899 add check_in settings

---

config/initializers/event_subscriptions.rb
modules/appeals_api/app/models/appeals_api/higher_level_review.rb
modules/appeals_api/app/services/appeals_api/events/appeal_received.rb
modules/appeals_api/config/initializers/event_subscriptions.rb
modules/appeals_api/lib/appeals_api/data_migrations/event_subscription_subscriber.rb
modules/appeals_api/spec/factories/higher_level_reviews.rb
modules/appeals_api/spec/services/appeals_api/events/appeal_received_spec.rb
rakelib/appeals_api_event_subscriber.rake

[API-6021](https://vajira.max.gov/browse/API-6021)
This PR triggers a notification for VANotify when an HLR is received (in version 2).

Api 6021/add received notification for hlr

---

modules/va_forms/app/controllers/va_forms/v0/forms_controller.rb
modules/va_forms/app/workers/va_forms/form_reloader.rb
modules/va_forms/lib/va_forms/regex_helper.rb
modules/va_forms/spec/lib/regex_helper_spec.rb
modules/va_forms/spec/requests/v0/forms_request_spec.rb

https://vajira.max.gov/browse/API-8614
no

Removing GSA and SF regex

---

config/locales/exceptions.en.yml
config/settings/test.yml

- Adding config to test.yml for the Check-in project.
- Adding exceptions to locales.
department-of-veterans-affairs/va.gov-team#26899

26899 Adding config to test.yml

---

app/mailers/views/school_certifying_officials.html.erb
config/features.yml

Removed `edu_form10203_updates` feature flag.
department-of-veterans-affairs/va.gov-team#25507

Remove 10203 email content feature flag

---

modules/check_in/app/controllers/check_in/v0/patient_check_ins_controller.rb
modules/check_in/app/services/chip_api/claims_token.rb
modules/check_in/app/services/chip_api/redis_handler.rb
modules/check_in/app/services/chip_api/request.rb
modules/check_in/app/services/chip_api/service.rb
modules/check_in/app/services/chip_api/session.rb
modules/check_in/app/services/chip_api/token.rb
modules/check_in/app/services/middleware/check_in_logging.rb
modules/check_in/app/services/middleware/errors.rb
modules/check_in/check_in.gemspec
modules/check_in/spec/request/patient_check_ins_request_spec.rb
modules/check_in/spec/services/chip_api/claims_token_spec.rb
modules/check_in/spec/services/chip_api/redis_handler_spec.rb
modules/check_in/spec/services/chip_api/request_spec.rb
modules/check_in/spec/services/chip_api/service_spec.rb
modules/check_in/spec/services/chip_api/session_spec.rb
modules/check_in/spec/services/chip_api/token_spec.rb
modules/check_in/spec/services/middleware/check_in_logging_spec.rb
modules/check_in/spec/services/middleware/errors_spec.rb

26899 CHIP API auth and integration
- Setup the signed claims token for CHIP
- Setup the Session handler for CHIP
- Setup the Token object for data exchange between CHIP and vets-api
- Setup the Redis handler for adding and retrieving tokens objects
- Setup the Redis handler for adding and retrieving tokens objects
- Setup the claims token configuration
- Wire up the CHIP API authentication code to the main Check-in
department-of-veterans-affairs/va.gov-team#26899

CHIP API auth and integration

---

config/features.yml

Need to adjust Feature Flags for Find Forms
See FRONT END CHANGES for more context => https://github.com/department-of-veterans-affairs/vets-website/pull/17898

Added new Flags

---

Gemfile.lock

Updates Brakeman to the latest version in order to get our brakeman checks passing

update brakeman to the latest minor version

---

lib/bgs/form674.rb
lib/bgs/form686c.rb
spec/lib/bgs/form674_spec.rb
spec/lib/bgs/form686c_spec.rb

We are adding a new service to check for Pension eligibility when a Dependents Application is submitted.  We are doing some integration testing and I accidentally added a "requires" to the spec instead of to the file itself.  This PR is a quick update to add the requires in the right place.  
department-of-veterans-affairs/va.gov-team#26831

Adding Pension Check to Dependents Applications

---

modules/check_in/app/controllers/check_in/v0/apidocs_controller.rb
modules/check_in/app/docs/check_in/v0/check_in.yaml
modules/check_in/config/initializers/statsd.rb
modules/check_in/config/routes.rb
modules/check_in/spec/request/apidocs_request_spec.rb
modules/check_in/spec/request/patient_check_ins_request_spec.rb

- Generate swagger JSON for the Check-in project.
- JSON can be viewed at `/check_in/v0/apidocs`
department-of-veterans-affairs/va.gov-team#27522

27522 Check In Swagger Docs

---

config/settings.yml
lib/vbs/client.rb
lib/vbs/configuration.rb
spec/lib/vbs/client_spec.rb
spec/lib/vbs/configuration_spec.rb

- Create the client library for VBS (`/lib/vbs`).
- Add configuration and `#exec` method
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/26207

Create VBS client library

---

modules/check_in/app/services/chip_api/request.rb
modules/check_in/config/initializers/statsd.rb
spec/spec_helper.rb

- Count the number of total requests made to the CHIP API
- Count the number of failed requests made to the CHIP API
- Measure how long it takes to make a request to the CHIP API
department-of-veterans-affairs/va.gov-team#27524

27524 StatsD functionality

---

config/settings.yml

updated flipper admin email from cwheeler@governmentcio.com to craig.wheeler@gcio.com
updated `admin_user_emails` in `config/settings.yml` to change cwheeler@governmentcio.com to craig.wheeler@gcio.com

Update flipper admin email for cwheeler@governmentcio.com

---

README.md

Adds a link to the Test User Dashboard module backend documentation. The TUD app is an internal tool in a private repository, so we cannot copy over the relevant documentation into the vets-api repository like with the other optional features.
department-of-veterans-affairs/va.gov-team#20219

[20219] adds link to TUD setup documentation

---

db/migrate/20210722175727_create_webhook_tables.rb
db/schema.rb

The Benefits Intake team is creating a new POC v2 endpoint that will enable the use of webhooks for status checking. These are 4 tables that we need to ensure are in dev before we open up those new v2 routes. There will be some beta testing in dev before we commit to a new version in prod
https://vajira.max.gov/browse/API-8724
No to all
tested locally

migration and schema file

---

.github/workflows/code_checks.yml

Adds dockerhub authentication to avoid hitting our pull rate limit

GitHub Actions auth with dockerhub

---

modules/mobile/docs/openapi.yaml
modules/mobile/docs/schemas/SecureMessageNewMessageRequest.yml
modules/mobile/docs/schemas/SecureMessageReplyRequest.yml

Updates OpenAPI docs to include info about sending drafts
department-of-veterans-affairs/va.gov-team#27742

Update OpenAPI docs with info on sending drafts

---

config/features.yml

Need a Discharge Wizard feature flag.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/23071
FE change => https://github.com/department-of-veterans-affairs/vets-website/pull/17987

DT-23071 Added new FF

---

modules/check_in/app/services/middleware/errors.rb
modules/check_in/spec/services/middleware/errors_spec.rb

- Refactoring errors.rb to reflect the needs of the Check-in module
department-of-veterans-affairs/va.gov-team#26899

26899 refactoring errors.rb

---

db/migrate/20210723134730_create_supplemental_claims.rb
db/schema.rb

[API-8634](https://vajira.max.gov/browse/API-8634)
This PR is the db migration for supplemental claims.

supplemental claims

---

modules/vba_documents/app/controllers/vba_documents/metadata_controller.rb

Some tweaks for the v2 swagger docs

Mark.viterna/swagger fix

---

modules/check_in/app/docs/check_in/v0/check_in.yaml
modules/check_in/app/services/chip_api/service.rb
modules/check_in/spec/services/chip_api/service_spec.rb

- Handle a 401 status from the CHIP API
- Update relevant swagger and specs
department-of-veterans-affairs/va.gov-team#27898

27898 handle 401 from CHIP

---

Gemfile.lock
modules/claims_api/app/controllers/claims_api/v2/blueprints/claim_blueprint.rb
modules/claims_api/app/controllers/claims_api/v2/veterans/claims_controller.rb
modules/claims_api/app/services/claims_api/bgs_to_lighthouse_claims_mapper_service.rb
modules/claims_api/app/swagger/claims_api/v2/swagger.json
modules/claims_api/spec/fixtures/v2/veterans/claims/claim_by_id_response.json
modules/claims_api/spec/fixtures/v2/veterans/claims/claims_by_participant_id_response.json
modules/claims_api/spec/requests/v2/veterans/claims_request_spec.rb
modules/claims_api/spec/requests/v2/veterans/rswag_claims_request_spec.rb
modules/claims_api/spec/services/bgs_to_lighthouse_claims_mapper_service_spec.rb
spec/support/schemas/claims_api/v2/veterans/claims/claim.json
spec/support/schemas/claims_api/v2/veterans/claims/claims.json

Refactors the new/unreleased V2 Claims `index` and `show` actions to consume BGS `ebenefits` services.
[API-8399](https://vajira.max.gov/browse/API-8399)

[API-8399] - ClaimsApi V2 return claims status

---

config/features.yml

This adds a new feature toggle for upcoming VAOS work.
department-of-veterans-affairs/va.gov-team#27861
Front end PR: https://github.com/department-of-veterans-affairs/vets-website/pull/18023

Add new feature toggle for VAOS

---

modules/vba_documents/app/workers/vba_documents/report_unsuccessful_submissions.rb

… consumer_names that was preventing the report from running due to a 'forensics' record existing.
Fixed nil error with daily report run
https://vajira.max.gov/browse/API-8965

Fix daily report run

---

config/features.yml

Adding a feature flag to present/submit the Higher-Level Review form changes and submission to the v2 endpoint.
Related:
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/28199
- Epic: https://github.com/department-of-veterans-affairs/va.gov-team/issues/28113
- Lighthouse: https://developer.va.gov/explore/appeals/docs/decision_reviews?version=current
- The v2 endpoint hasn't been finalized

Add HLR v2 feature flag

---

config/features.yml

Adding new feature flips for the next iteration of features for the check-in app
https://github.com/department-of-veterans-affairs/va.gov-team/issues/28229

added new feature flips for check-in app

---

lib/bgs/benefit_claim.rb
lib/bgs/form686c.rb
lib/bgs/vnp_veteran.rb

Adds logging for BGS troubleshooting with Linda.

Add two log events for bgs

---

modules/check_in/app/controllers/check_in/v0/patient_check_ins_controller.rb
modules/check_in/app/docs/check_in/v0/check_in.yaml
modules/check_in/app/models/check_in/patient_check_in.rb
modules/check_in/app/services/chip_api/service.rb
modules/check_in/spec/models/check_in/patient_check_in_spec.rb
modules/check_in/spec/request/patient_check_ins_request_spec.rb
modules/check_in/spec/services/chip_api/service_spec.rb
spec/middleware/rack/attack_spec.rb

- Validate the UUID before GETing or POSTing to CHIP
- Return an appropriate message and status back to the client if UUID is not in the correct format
department-of-veterans-affairs/va.gov-team#28064

Validate UUID

---

rakelib/in_progress_forms.rake

there was a new safety check included in a rails upgrade
https://github.com/rails/rails/issues/32995#issuecomment-392245004
department-of-veterans-affairs/va.gov-team#20410

fix sql for in_progress_forms.rake

---

modules/appeals_api/app/services/appeals_api/events/appeal_received.rb

[API-8966](https://vajira.max.gov/browse/API-8966)
updating key reference from va_gov to lighthouse

update key reference

---

app/models/saved_claim/veteran_readiness_employment_claim.rb
modules/claims_api/lib/claims_api/vbms_uploader.rb

This adds new logging to confirm a temp file exists throughout the whole upload process, and also logs the upload_response from VBMS.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/28136
None.

add sentry logging to confirm the pdf file exists in a few spots

---

.github/CODEOWNERS

- Codeowner ship setup for the VSA Debt Resolution team.
- Github team is @department-of-veterans-affairs/vsa-debt-resolution
department-of-veterans-affairs/va.gov-team#28442

28442 Debt resolution codeownership

---

app/controllers/v0/financial_status_reports_controller.rb
lib/debt_management_center/financial_status_report_service.rb
spec/fixtures/dmc/fsr_submission.json
spec/support/vcr_cassettes/dmc/submit_fsr.yml

DMC requires a key `applicantCertification` for the veteran signature and date.

Update key for veteran signature on FSR submission

---

config/locales/en.yml

This PR updates the 686 root url used in the email that notifies users when a submission has failed. 
Related PRs:
- https://github.com/department-of-veterans-affairs/devops/pull/9743
- https://github.com/department-of-veterans-affairs/content-build/pull/434
- https://github.com/department-of-veterans-affairs/vets-website/pull/18177
department-of-veterans-affairs/va.gov-team#27514

27514 update 686 root url in email

---

config/features.yml

This enables us to break out the current mega menu into separate menus for mobile and desktop. See: https://github.com/department-of-veterans-affairs/content-build/pull/420
https://github.com/department-of-veterans-affairs/va.gov-team/issues/25659

Add new feature toggle for va_online_mobile_specific_menu

---

modules/claims_api/spec/requests/v1/disability_compensation_request_spec.rb

A few tests were broken by newer changes in master that implicitly broke things in my branch's updates. This fixes that.
department-of-veterans-affairs/va.gov-team#9006

Fix broken request specs missing a VCR request

---

modules/appeals_api/spec/support/schemas/contestable_issue.json
modules/appeals_api/spec/support/schemas/hlr_validate.json

Adds schema files for the contestable issues and hlr validate endpoints.
https://vajira.max.gov/browse/API-8467

API-8467 - Add additional schemas for rswag

---

spec/support/vcr_cassettes/caseflow/higher_level_reviews/bad_date.yml
spec/support/vcr_cassettes/caseflow/higher_level_reviews/not_found.yml
spec/support/vcr_cassettes/caseflow/higher_level_reviews/server_error.yml

Adds some additional vcr cassettes to support the upcoming hlr rswag spec.
https://vajira.max.gov/browse/API-8467

API-8467 - vcr_cassettes for hlr v2 rswag specs

---

app/models/saved_claim/veteran_readiness_employment_claim.rb
lib/bgs/form674.rb
modules/claims_api/lib/claims_api/vbms_uploader.rb

This improves logging for trying to figure out the Ch31 issues.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/28692

Kmm improve ch31 logging add pid etc

---

app/policies/ch33_dd_policy.rb
app/policies/ppiu_policy.rb
config/features.yml
lib/evss/ppiu/service.rb
spec/lib/evss/ppiu/service_spec.rb
spec/policies/ch33_dd_policy_spec.rb
spec/policies/ppiu_policy_spec.rb

add feature flipper to direct deposit apis in order to control access to the apis due to fraud
https://github.com/department-of-veterans-affairs/va.gov-team/issues/28728

Direct Deposit: Temporarily disable direct deposit functionality on the backend

---

modules/claims_api/app/models/claims_api/auto_established_claim.rb
modules/claims_api/spec/models/auto_establish_claim_spec.rb

Contains logic to submit a BDD type disability claim. Kicks exception out to the consumer in certain situations.
https://vajira.max.gov/browse/API-9102

API-9102: Submit BDD type disability claims

---

modules/claims_api/lib/claims_api/vbms_uploader.rb

Improves logging logic.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/28692

Kmm adjust logging unless and use if's instead

---

modules/facilities_api/app/services/facilities_api/v1/ppms/configuration.rb

Disabling breakers due to an early timout issue.
department-of-veterans-affairs/va.gov-team#28780

Temporarily disabling breaker

---

config/initializers/rack_attack.rb
spec/middleware/rack/attack_spec.rb

In response to ongoing DOS activity against the Facility Locator remote Bing Maps lookup.
Please see https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/2021-08-16-facility-locator-possible-DOS.md for add'l details.

rate-limit PPMS lookup to curb abuse

---

modules/facilities_api/app/services/facilities_api/v1/ppms/configuration.rb

Reverts department-of-veterans-affairs/vets-api#7658

Revert "Temporarily disabling breaker"

---

modules/appeals_api/spec/docs/v2/hlr_spec.rb
modules/appeals_api/spec/support/swagger_shared_components.rb

Adds `/higher_level_reviews/validate` rswag spec.
https://vajira.max.gov/browse/API-8467

API-8467 - Add additional hlr rswag examples

---

modules/appeals_api/spec/support/rswag_config.rb

I'm refactoring the rswag config and can't do it all in one PR due to the line limits... :( Moving the schemas out into their own methods will make it easier to keep them organized and allow for better writing back to the json schema (when that comes).
**Another PR will finish this refactor...**
https://vajira.max.gov/browse/API-8467

API-8467 - refactoring rswag config

---

modules/claims_api/app/mailers/claims_api/unsuccessful_report_mailer.rb
modules/claims_api/spec/mailers/unsuccessful_report_mailer_spec.rb

Adds Jeff Wallace to daily email report for Benefits Claims 526 submissions.

add Jeff to daily report email

---

modules/claims_api/app/controllers/claims_api/v1/forms/disability_compensation_controller.rb
modules/claims_api/spec/requests/v1/disability_compensation_request_spec.rb

serviceInformation.reservesNationalGuardService.title10Activation must be after the earliest "activeDutyEndDate" and on or before the current date.
https://vajira.max.gov/browse/API-9009

API-9009: [Form526 EVSS Validations] - "serviceInformation.reservesNationalGuardService.title10Activation"

---

.gitignore
config/settings.yml

Also added a new .gitignore entry for JetBrains IDE config files.

Add michael.pelz-sherman@gcio.com to flipper admin_user_emails.

---

config/initializers/rack_attack.rb
spec/middleware/rack/attack_spec.rb

- Throttle the `/v0/medical_copays` endpoint if more than twenty requests are made from the same IP in sixty seconds.
department-of-veterans-affairs/va.gov-team#224400

224400 Enable throttling on GET route

---

app/services/medical_copays/vbs/request_data.rb
app/services/medical_copays/vista_account_numbers.rb
spec/services/medical_copays/vbs/request_data_spec.rb
spec/services/medical_copays/vista_account_numbers_spec.rb

- Build the user's Vista Account Numbers from the vha_facilities_hash
department-of-veterans-affairs/va.gov-team#22440

22440 vista account numbers

---

docs/setup/rswag_setup.md

Creating a doc to show a minimum implementation of Rswag in vets-api (to make it play nice with rails engines).

Add rswag setup doc

---

modules/claims_api/app/controllers/claims_api/v1/forms/disability_compensation_controller.rb
modules/claims_api/app/swagger/claims_api/v1/swagger.json
modules/claims_api/config/schemas/2122.json
modules/claims_api/config/schemas/526.json
modules/claims_api/spec/requests/v1/disability_compensation_request_spec.rb

Adds some validation around the changeOfAddress portion of a 526 submission, based on information given to us from EVSS.
https://vajira.max.gov/browse/API-9011
Requires this PR for sandbox (and any other mocked environment)
https://github.com/department-of-veterans-affairs/vets-api-mockdata/pull/174

API-9011: [Form526 EVSS Validations] - "veteran.changeOfAddress"

---

modules/vaos/app/controllers/vaos/v0/clinics_controller.rb
modules/vaos/app/controllers/vaos/v2/clinics_controller.rb
modules/vaos/spec/request/facilities_request_spec.rb
modules/vaos/spec/request/v2/clinics_request_spec.rb

Updates to the clinic data logging functionality to facilitate more convenient and comprehensive parsing in Loki/Grafana by surfacing the data as JSON
department-of-veterans-affairs/va.gov-team#28637

28637 updates to clinic data logging Loki/Grafana

---

modules/va_notify/app/services/va_notify/find_in_progress_forms.rb
modules/va_notify/spec/services/find_in_progress_forms_spec.rb
modules/va_notify/spec/workers/in_progress_forms_spec.rb

Updates to the cadence of which in progress forms should be notified.
https://app.zenhub.com/workspaces/forms-strike-team-620c2914e703390013c4b414/issues/department-of-veterans-affairs/vanotify-team/157

VaNotify InProgressForm reminder

---

modules/dhp_connected_devices/config/initializers/fitbit_api.rb

Debugging PKCE challenge changing '=' to '||=' to see if it make it less flaky

DHP-256 change = to ||= in PKCE challenge

---

app/models/health_care_application.rb
spec/models/health_care_application_spec.rb

Add 1010ez submissions to the personal information log when a validation error occurs to help diagnose the errors
https://github.com/department-of-veterans-affairs/va.gov-team/issues/40660

Log 1010ez validation errors 

---

Gemfile.lock
config/features.yml
config/settings.yml
modules/mobile/app/controllers/mobile/v0/letters_controller.rb
modules/mobile/app/models/mobile/v0/letter.rb
modules/mobile/app/models/mobile/v0/lighthouse_assertion.rb
modules/mobile/app/models/mobile/v0/lighthouse_params_factory.rb
modules/mobile/app/serializers/mobile/v0/letters_serializer.rb
modules/mobile/app/services/mobile/v0/lighthouse_health/configuration.rb
modules/mobile/app/services/mobile/v0/lighthouse_health/service.rb
modules/mobile/app/services/mobile/v0/lighthouse_letters/configuration.rb
modules/mobile/app/services/mobile/v0/lighthouse_letters/service.rb
modules/mobile/spec/models/lighthouse_assertion_spec.rb
modules/mobile/spec/models/lighthouse_params_factory_spec.rb
modules/mobile/spec/request/letters_lighthouse_request_spec.rb
modules/mobile/spec/request/letters_request_spec.rb
modules/mobile/spec/support/vcr_cassettes/lighthouse_letters/letters_200.yml
modules/mobile/spec/support/vcr_cassettes/lighthouse_letters/letters_404.yml
modules/mobile/spec/support/vcr_cassettes/lighthouse_letters/letters_503.yml

Adds a flipper that will enable mobile eligible letters endpoint to use lighthouse as it's upstream service rather then EVSS. this service is still not on production so the flipper will be used to only enable it in production once available. 
Rest of letter endpoints will come in future PRs due to LOC limit.   
https://app.zenhub.com/workspaces/va-mobile---backend-61d75d03a7505500147ec7f6/issues/department-of-veterans-affairs/va-mobile-app/4195

add letters service

---

modules/meb_api/app/controllers/meb_api/v0/education_benefits_controller.rb

If claimant service cannot find a valid claimant is returns an id of 0.  We need to check for that so we don't submit enrollment verification with a bad claimant id.
[department-of-veterans-affairs/va.gov-team#39113
](https://jira.np.afsp.io/browse/SA-39113)

check if claimant_service returned a valid claimant_id

---

Gemfile.lock
spec/lib/preneeds/service_spec.rb

This reverts commit 187aa2edeecff73f9c7041ce442c9778363effe6. …

Revert "Bump mail from 2.7.1 to 2.8.0 (#11396)"

---

.rubocop.yml
app/uploaders/uploader_virus_scan.rb
lib/shrine/plugins/validate_virus_free.rb
spec/lib/shrine/plugins/validate_virus_free_spec.rb
spec/models/persistent_attachments/dependency_claim_spec.rb
spec/models/persistent_attachments/lgy_claim_spec.rb
spec/models/persistent_attachments/pension_burial_spec.rb
spec/requests/claim_documents_spec.rb
spec/simplecov_helper.rb
spec/spec_helper.rb
spec/support/uploader_helpers.rb
spec/uploaders/uploader_virus_scan_spec.rb

Fixes clam based specs after we made some updates to clamav. We no longer use the clam_scan gem and we use clamav-client. I also updated the shrine plugin `Shrine::Plugins::ValidateVirusFree` to place files in the /tmp dir because /tmp and /vets-api dirs are set as volume mounts between the two containers/used for scanning. Files need to be in /tmp
- *Describe …

Fix clam specs and update scanning dir

---

config/features.yml

The `facility_locator_ppms_forced_unique_id` flipper is no longer being used on the front-end, so it can be removed from the list of features.
- An unused feature is removed from the config.
- Facilities team, which does not own maintenance of this component.
- *(If using a flipper, what is the end date of the flipper being …

[VA-11593] Remove PPMS Remove Forced Unique ID feature

---

config/features.yml
modules/meb_api/lib/dgi/submission/service.rb

Modifies the Submission service params to include a person criteria object that includes the user's SSN. This value is needed in backend processing.
Tested authenticated flow and submitted the form on localhost with the DGI backend setup on localhost to simulate the environment.
1990EZ form

Adds flipper gate to newly formatted submission parameters

---

modules/claims_api/app/swagger/claims_api/v2/dev/swagger.json
modules/claims_api/config/schemas/v2/request_bodies/disability_compensation/example.json
modules/claims_api/lib/claims_api/v2/disability_compensation_pdf_mapper.rb
modules/claims_api/spec/lib/claims_api/v2/disability_compensation_pdf_mapper_spec.rb

- formats ssn
?
- rspec
- Postman
1. use staging as your fwd proxy
2. use the example.json file in this PR to test
modified:   modules/claims_api/lib/claims_api/v2/disability_compensation_pdf_mapper.rb
modified:   modules/claims_api/spec/lib/claims_api/v2/disability_compensation_pdf_mapper_spec.rb
modified:   modules/claims_api/config/schemas/v2/request_bodies/disability_compensation/example.json

API-526-v2-fix-ssn

---

config/initializers/sidekiq.rb

re-reverts this: https://github.com/department-of-veterans-affairs/vets-api/pull/14704

Force ipv4

---

db/migrate/20231201160018_remove_column_and_index_from_veteran_organizations_table.rb
db/schema.rb

Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/71008
I added the `representative_number` column to the `veteran_organizations` table last week and later determined that we don't need it. It's never been used. This PR removes the column.
The PR to ignore the `representative_number` attribute in the associated model for the `veteran_organizations` table has been merged - https://github.com/department-of-veterans-affairs/vets-api/pull/14717
- *(If using a flipper, what is the end date of the flipper being required/success …

Remove representative_number from veteran_organizations

---

modules/veteran/app/models/veteran/service/organization.rb

Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/71008
This is the 3rd in a series of PRs to remove a table column:
1. https://github.com/department-of-veterans-affairs/vets-api/pull/14717
2. https://github.com/department-of-veterans-affairs/va.gov-team/issues/71008
This PR removes the following line from the model associated with the `veteran_organizations` table:
```
self.ignored_columns += ['representative_number']
```
- *(If using a flipper, what is the end date of the flipper being required/success criteria being …

Remove self.ignored_columns from Service::Organization

---

Gemfile.lock

Update brakeman to 6.1.0

---

modules/claims_api/app/swagger/claims_api/v2/dev/swagger.json

Adds docs for v2 swagger dev. which were missed in the my PR for this ticket
[API-31426](https://jira.devops.va.gov/browse/API-31426)
* RSpec
* Postman
* Visually check docs
modules/claims_api/app/swagger/claims_api/v2/dev/swagger.json

Adds dev swagger docs for v2

---

Gemfile
Gemfile.lock
config/initializers/sidekiq.rb

Trying 127.0.0.1 with new dogstatsd

---

config/features.yml

- adds feature flag for blocked triage groups on Secure Messaging va.gov
- [MHV-52370](https://jira.devops.va.gov/browse/MHV-52370)
va.gov - Secure Messaging
(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have …

added feature flag for blocked triage groups on Secure Messaging va.gov

---

.github/CODEOWNERS
config/initializers/add_local_config.rb
config/settings.yml

Created the development.local.yml for vets-api-dev. This settings configuration will override settings.local.yml and settings.yml. If this is successful, this will be pushed to other environments.
If VSP_ENVIRONMENT is defined and VSP_ENVIRONMENT == development, the development.local.yml file should override settings.yml file.
- department-of-veterans-affairs/va.gov-team#66823
- [manifest pr ](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2467)

Add environment.local.yml file if local environment file exists

---

modules/claims_api/lib/claims_api/v2/disability_compensation_pdf_mapper.rb
modules/claims_api/spec/lib/claims_api/v2/disability_compensation_pdf_mapper_spec.rb

Reverts department-of-veterans-affairs/vets-api#14760
Reverting due to code failures, https://github.com/department-of-veterans-affairs/vets-api/actions/runs/7131158671/job/19419551477.

Revert "Api 32103 bdd separation date"

---

lib/hca/enrollment_eligibility/service.rb
spec/lib/hca/enrollment_eligibility/service_spec.rb
spec/requests/health_care_applications_request_spec.rb

- Changed a method call to return the inverse boolean value.
- [department-of-veterans-affairs/va.gov-team#0000](https://github.com/department-of-veterans-affairs/va.gov-team/issues/71492)

10-10EZR: Refactored Means Test Method Call

---

modules/ask_va_api/app/controllers/ask_va_api/v0/inquiries_controller.rb
modules/ask_va_api/app/lib/ask_va_api/inquiries/creator.rb
modules/ask_va_api/app/services/attachment_uploader.rb
modules/ask_va_api/app/services/dynamics/service.rb
modules/ask_va_api/spec/app/lib/ask_va_api/inquiries/creator_spec.rb
modules/ask_va_api/spec/requests/v0/inquiries_spec.rb
modules/ask_va_api/spec/services/attachment_uploader_spec.rb
modules/ask_va_api/spec/services/dynamics/service_spec.rb

- Updated `creator` to have a `static` response.
- Updated `attachment_upload` endpoint
- Updated response from `static_data#index` endpoint to troubleshoot in `staging`
- department-of-veterans-affairs/ask-va#359

BE | Ask VA API: Updated `inquiries/creator` and `dynamics/service`

---

config/initializers/add_local_config.rb

…T defined
When VSP_ENVIRONMENT is defined, the #{{environment}}.local.yml will replace the current settings.yml and settings.local.yml
- department-of-veterans-affairs/va.gov-team#66823
- *Describe …

Applying environment settings to all environments 

---

config/initializers/add_local_config.rb
config/settings/local.yml

Calling prepend_source instead of add_source. From the config gem documentation, the prepend method will load the given settings file first.
- department-of-veterans-affairs/va.gov-team#66823
- …

Prepend settings file instead of callign add_source

---

modules/ask_va_api/app/services/dynamics/service.rb

- updated `Dynamics::Service` error response

BE | Ask VA APi: Update Service error response

---

modules/ask_va_api/app/services/dynamics/service.rb

- Add in a rescue all for `token`

BE | Ask VA API: updated service class

---

app/controllers/v0/profile/direct_deposits/disability_compensations_controller.rb
config/features.yml
spec/controllers/v0/profile/direct_deposits/disability_compensations_controller_spec.rb

Remove `profile_lighthouse_direct_deposit ` feature toggle.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/71150

Remove feature toggle for LH Direct Deposit

---

.github/CODEOWNERS
Brewfile
docker-compose-deps.yml
docker-compose.review.yml
docker-compose.test.yml
docker-compose.yml
docs/setup/native.md

Reverts department-of-veterans-affairs/vets-api#14790

Revert "Changes after postgres upgrade"

---

modules/vaos/app/services/vaos/v2/appointments_service.rb
modules/vaos/spec/services/v2/appointment_service_spec.rb

- updating avs response field to contain a message in case of a service error
- department-of-veterans-affairs/va.gov-team#63692

avs error msg

---

modules/ask_va_api/app/services/dynamics/service.rb

- *Describe the tests completed and the …

BE | Ask VA API: more test in service class

---

docker-compose.yml

This change is for post Postgres upgrade.

Ks postgres upgrade change

---

modules/avs/app/controllers/avs/v0/avs_controller.rb
modules/avs/spec/request/v0/avs_request_spec.rb

- Updates API to sync with new rootUrl per https://dsva.slack.com/archives/C04UBETRY8N/p1696266645089739?thread_ts=1692218774.597929&cid=C04UBETRY8N
- https://github.com/department-of-veterans-affairs/content-build/pull/1829#pullrequestreview-1778209692
- AVS app only

Update path for AVS app

---

modules/claims_api/app/swagger/claims_api/v2/dev/swagger.json
modules/claims_api/spec/requests/v2/veterans/rswag_power_of_attorney_spec.rb
spec/support/schemas/claims_api/veterans/power-of-attorney/get.json

- This pr adds the bones of POA V2 swagger docs
- [API 32086](https://jira.devops.va.gov/browse/API-32086)

API 32086 Add v2 poa rswag structure

---

modules/ask_va_api/app/services/dynamics/service.rb
modules/ask_va_api/spec/services/dynamics/service_spec.rb

- *Describe the tests completed and the …

BE | Ask VA API: Updated `Service#token`

---

config/initializers/sidekiq.rb

Reverts department-of-veterans-affairs/vets-api#14854
https://dsva.slack.com/archives/C0460N83Y9G/p1702489514981809

Revert "Prepend env settings in vets-api-dev"

---

.github/CODEOWNERS
Makefile
app/controllers/claims_base_controller.rb
app/controllers/v0/pension_claims_controller.rb
app/models/saved_claim/pension.rb
app/sidekiq/benefits_intake_status_job.rb
app/sidekiq/lighthouse/pension_benefit_intake_job.rb
config/features.yml
config/initializers/sidekiq.rb
config/redis.yml
config/settings.local.yml.example
db/migrate/20231213145347_rename_form_data_to_form_data_ciphertext.rb
db/schema.rb
lib/benefits_intake_service/service.rb
lib/periodic_jobs.rb
lib/sidekiq/attr_package.rb
modules/claims_api/app/swagger/claims_api/description/v2.md
modules/claims_api/app/swagger/claims_api/v2/dev/swagger.json
modules/claims_api/app/swagger/claims_api/v2/production/swagger.json
modules/claims_api/spec/requests/v2/veterans/rswag_disability_compensation_request_spec.rb
modules/claims_api/spec/support/rswag_config.rb
modules/simple_forms_api/app/form_mappings/vba_20_10206.json.erb
rakelib/lint.rake
spec/factories/form_submissions.rb
spec/lib/sidekiq/attr_package_spec.rb
spec/requests/pension_claims_controller_spec.rb
spec/sidekiq/benefits_intake_status_job_spec.rb
spec/sidekiq/lighthouse/pension_benefit_intake_job_spec.rb
spec/support/vcr_cassettes/lighthouse/benefits_intake/200_lighthouse_intake_bulk_status_report_error.yml
spec/support/vcr_cassettes/lighthouse/benefits_intake/200_lighthouse_intake_bulk_status_report_success.yml

Fixing merge conflict

---

config/features.yml

- Add Flipper feature-toggle for new form-app Personal Record Request (20-10206)
- Team: Veteran Facing Forms
- Flipper end-date TBD
[vets-website](https://github.com/department-of-veterans-affairs/vets-website/pull/27093)
- department-of-veterans-affairs/va.gov-team-forms#786
- Local browser testing was successful
This form ONLY

20-10206: Add Flipper feature-toggle

---

.github/workflows/check-git-log.yml

- Adding branch detector to check-git-log.yml
- Phrasing.

Report branch matching sha for GHA git log checker

---

modules/ask_va_api/app/services/redis_client.rb
modules/ask_va_api/spec/services/redis_client_spec.rb

- Created `RediClient` class
- department-of-veterans-affairs/ask-va#511
- specs
- test in development

BE | Ask VA API: Create` RedisClient` class

---

modules/claims_api/catalog-info.yaml

Updated Hub entry for Claims API to specify v1. There will be a new entry created for v2.
- [API-30616](https://jira.devops.va.gov/browse/API-30616)
- n/a

API-30616 The Hub Updates for Claims API v1

---

modules/ask_va_api/app/services/dynamics/crm_token.rb
modules/ask_va_api/app/services/dynamics/service.rb
modules/ask_va_api/app/services/redis_client.rb
modules/ask_va_api/spec/app/lib/ask_va_api/inquiries/creator_spec.rb
modules/ask_va_api/spec/requests/v0/inquiries_spec.rb
modules/ask_va_api/spec/requests/v0/static_data_spec.rb
modules/ask_va_api/spec/services/dynamics/crm_token_spec.rb
modules/ask_va_api/spec/services/dynamics/service_spec.rb

- created `CrmToken` class to either retrieve `token` from `redis` or make a call to `microsoftonline`
- refactored `Dynamics::Service` class
- update `specs`
- department-of-veterans-affairs/ask-va#512

BE | Ask VA API: Create `CrmToken` Class

---

.rubocop_todo.yml
app/validators/preferred_name_validator.rb
lib/va_profile/models/preferred_name.rb
spec/lib/va_profile/models/preferred_name_spec.rb

Updated preferred name validation rules to match VA Profile's validation rules.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/71381
Added specs to test for...
- empty spaces.
- acute, grave, diaeresis, circumflex, and tilde.
- special characters.

Preferred name validation

---

app/controllers/v0/virtual_agent/virtual_agent_appeal_controller.rb
spec/controllers/v0/virtual_agent/virtual_agent_appeal_spec.rb
spec/support/vcr_cassettes/caseflow/virtual_agent_appeals/lighthouse_mock_appeal_sc_recieved.yml

Added a new status, `sc_recieved`, to the list of appeals status
Load a user with a compensation appeal with the status of `sc_recieved`
we added the errant status to our list of statuses
Virtual Agent chatbot team, and yes we own this controller
- https://github.com/department-of-veterans-affairs/va-virtual-agent/issues/1288
The user would see unknown status prior
- *Describe the steps …

[#1288] Adding sc_recieved to appeal status list

---

lib/map/sign_up/configuration.rb
lib/map/sign_up/service.rb
spec/lib/map/sign_up/service_spec.rb
spec/support/vcr_cassettes/map/sign_up_service_200_responses.yml

Update terms of use version mapping and add `legal_display_version` field
- department-of-veterans-affairs/va.gov-team#72039
terms of use

Update terms of use version mapping

---

config/features.yml

- Added feature toggle for the new version of the Burial form (21P-530)
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/71045
- Manual

Added feature flag for Burial form v2

---

config/features.yml

- removes `my_va_lighthouse_claims` feature flag from config/features.yml
- this feature flag is no longer used by MyVA now that evss -> lighthouse migration is complete
- MyVA Auth Exp Team
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/59817
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/61808
Note: the related [vets-website PR](https://github.com/department-of-veterans-affairs/vets-website/pull/25974) to remove usage of this flag should be merged and deployed first.
- verified removal of feature flag locally
- specs pass locally
This feature flag was used by MyVA while migrating from evss to lighthouse, so that MyVA code could use one service or the other in case we needed to switch.  Once the related vets-website PR is merged, this flag …

Remove my_va_lighthouse_claims feature flag

---

modules/ask_va_api/app/lib/ask_va_api/inquiries/entity.rb
modules/ask_va_api/app/lib/ask_va_api/inquiries/serializer.rb
modules/ask_va_api/config/locales/get_inquiries_mock_data.json
modules/ask_va_api/spec/app/lib/ask_va_api/inquiries/entity_spec.rb
modules/ask_va_api/spec/app/lib/ask_va_api/inquiries/serializer_spec.rb
modules/ask_va_api/spec/requests/v0/inquiries_spec.rb
modules/ask_va_api/spec/services/dynamics_mock_service_spec.rb

1. **Enhancement of `get_inquiries_mock_data.json`:**
- **Addition of New Records:** Integrated 6 new records under the `personal` category, each augmented with `attachment` features. This enhancement broadens the diversity of the dataset and bolsters its utility for testing scenarios.
2. **Refinement of `Inquiries::Entity` and Related Tests:**
- **Attribute Integration:** Adapted `Inquiries::Entity` to include new attributes, aligning it with the updated `inquiry` record format. This development enhances the entity's data model congruence and its representational robustness.
3. **Upgrade of `Inquiries::Serializer` and Relevant Tests:**
- **Attribute Expansion:** Augmented the serializer to encompass an expanded attribute set, mirroring the recent updates to the `inquiry` record. This …

BE | Ask VA API: Updated inquiries_mock_data

---

lib/statsd_middleware.rb

- Update middleware source app to include ezr.
-[https://github.com/department-of-veterans-affairs/va.gov-team/issues/72472](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72472)

Add ezr to the source apps for statsd

---

app/models/message.rb
app/models/message_thread_details.rb
lib/sm/client.rb
modules/my_health/app/controllers/my_health/v1/messages_controller.rb
modules/my_health/app/serializers/my_health/v1/message_details_serializer.rb
modules/my_health/docs/openapi.yaml
modules/my_health/docs/openapi_merged.yaml
modules/my_health/docs/schemas/SecureMessageListInThread.yml
modules/my_health/docs/schemas/SecureMessageListInThreadWithFullBody.yml
modules/my_health/spec/request/v1/messages_request_spec.rb
spec/models/message_spec.rb
spec/support/vcr_cassettes/sm_client/messages/gets_a_message_thread_full.yml
spec/support/vcr_cassettes/sm_client/messages/gets_a_message_thread_full_body.yml

- MHV SM Patient API introduced a new endpoint `/mhv-sm-api/patient/v1/message/:messageId/allmessagesforthread/:is_full_body`. Response format below
```javascript
[
{
"messageId": 3188928,
"threadId": 3188781,
"senderId": 251391,
"senderName": "MHVDAYMARK, MARK",
"recipientId": 3188767,
"recipientName": "TG API TESTING",
"sentDate": "2023-12-11T20:40:41.000+00:00",
"draftDate": null,
"triageGroupName": "TG API TESTING",
"hasAttachments": true,
"subject": "Test Inquiry",
"category": "TEST_RESULTS",
"folderId": -1,
"messageBody": "REPLY DRAFT",
"proxySenderName": null,
"readReceipt": "READ",
"attachment1Id": 3188925,
"attachment1Name": "BIRD 1.jfif",
"attachment1Size": 31127,
"attachment1MimeType": "image/jpeg",
"attachment2Id": 3188926,
"attachment2Name": "SPREADSHEET, 2021, DOC (1).xlsx", …
```

MHV-44453 Secure Messaging: return full body and attachments on /thread call

---

modules/ask_va_api/app/controllers/ask_va_api/v0/inquiries_controller.rb
modules/ask_va_api/app/lib/ask_va_api/attachments/retriever.rb
modules/ask_va_api/app/lib/ask_va_api/correspondences/entity.rb
modules/ask_va_api/app/lib/ask_va_api/correspondences/retriever.rb
modules/ask_va_api/app/lib/ask_va_api/correspondences/serializer.rb
modules/ask_va_api/app/lib/ask_va_api/inquiries/retriever.rb
modules/ask_va_api/app/lib/ask_va_api/inquiries/serializer.rb
modules/ask_va_api/app/services/dynamics_mock_service.rb
modules/ask_va_api/config/locales/get_attachments_mock_data.json
modules/ask_va_api/config/locales/get_inquiries_mock_data.json
modules/ask_va_api/config/locales/get_replies_mock_data.json
modules/ask_va_api/config/routes.rb
modules/ask_va_api/spec/app/lib/ask_va_api/correspondences/entity_spec.rb
modules/ask_va_api/spec/app/lib/ask_va_api/correspondences/retriever_spec.rb
modules/ask_va_api/spec/app/lib/ask_va_api/correspondences/serializer_spec.rb
modules/ask_va_api/spec/app/lib/ask_va_api/inquiries/retriever_spec.rb
modules/ask_va_api/spec/app/lib/ask_va_api/inquiries/serializer_spec.rb
modules/ask_va_api/spec/requests/v0/inquiries_spec.rb
modules/ask_va_api/spec/services/dynamics_mock_service_spec.rb

1. **Enhanced Inquiry Retrieval Mechanism:**
- **Modification in Retrieval Criteria:** Transitioned to fetching `inquiry` records by `ID` instead of using `inquiry_number`. This change aligns with a more standardized approach and improves data retrieval accuracy.
2. **Updates to `Correspondences::Entity` and Associated Tests:**
- **Attribute Overhaul:** Revamped the class attributes to reflect the latest data structure and requirements. This update ensures the entity remains in sync with current data models.
3. **Enhancements in `Correspondences::Retriever` …

BE | Ask VA API: Updated mock data

---

db/migrate/20231215141612_create_vye_user_infos.vye.rb
db/migrate/20231215141613_create_vye_awards.vye.rb
db/schema.rb
modules/vye/db/migrate/20231120034639_create_vye_user_infos.rb
modules/vye/db/migrate/20231120034755_create_vye_awards.rb

Starting development for **VYE (Verify Your Enrollment)** API.
- This API is part of the migration of WAVE (https://www.gibill.va.gov/wave/vba/) from a standalone Java app to the main va.gov Ruby or Rails site.
- It's being done to bring the app to a code base when development is more active.
- This pull request does the following:
- Adds migrations for the UserInfo & Award model
- there are no related issues for this pull request
- This is a new feature so there is no old behavior prior to the change
- Basic specs were added to exercise the model; more will be added in future sprints. 
- No areas of the site are impacted
- *will be added as API gets fleshed out further in future commits*
- *will be added as API gets fleshed out further in future commits*
- *will be added as API gets …

database migrations for UserInfo & Award models

---

app/sidekiq/benefits_intake_status_job.rb

This PR uses StatsD instead of manually incrementing an integer. Hopefully this will let us chart results on DataDog.
I've never used StatsD before so please check that what I'm doing makes sense!!

Use StatsD for form polling job

---

.github/CODEOWNERS
app/controllers/v0/virtual_agent_token_nlu_controller.rb
app/swagger/swagger/requests/virtual_agent_token_nlu.rb
config/features.yml
config/routes.rb
config/settings.yml
spec/controllers/v0/virtual_agent_token_nlu_controller_spec.rb

Added a new API endpoint for the virtual agent chatbot experiance
n/a
Virtual agent platform team, and yes
Once we are able to decide between NLU and CQA we will remove the flipper.
link to related [pr](https://github.com/department-of-veterans-affairs/vets-website/pull/27254) for the flipper.
https://github.com/department-of-veterans-affairs/va-virtual-agent/issues/1355
- *Link to previous change of …

1355 - virtual agent adding NLU to API

---

config/initializers/sidekiq.rb

Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/72573

Sidekiq Death Handler: Log an error on job death

---

modules/ask_va_api/app/services/crm/crm_token.rb
modules/ask_va_api/app/services/crm/static_data.rb
modules/ask_va_api/app/services/redis_client.rb
modules/ask_va_api/config/locales/static_data.json
modules/ask_va_api/spec/services/crm/static_data_spec.rb
modules/ask_va_api/spec/services/redis_client_spec.rb

- created `static_data.rb`
- look for the data in `cache`, if not, make a call to `CRM API`
- refactored `redis_client.rb`
-  client is changed to dynamically received the `key`, `data`, and `ttl` to `cache` and retrieve the `cache`
- refactored `crm_token.rb`
-  need to get updated due to the change in `redis_client.rb` 
- department-of-veterans-affairs/ask-va#492
- created `specs`
- tested on `localhost`

BE | Ask VA API: Created `static_data.rb`

---

modules/ask_va_api/app/controllers/ask_va_api/v0/static_data_controller.rb
modules/ask_va_api/app/lib/ask_va_api/categories/entity.rb
modules/ask_va_api/app/lib/ask_va_api/categories/retriever.rb
modules/ask_va_api/app/lib/ask_va_api/categories/serializer.rb
modules/ask_va_api/spec/app/lib/ask_va_api/categories/entity_spec.rb
modules/ask_va_api/spec/app/lib/ask_va_api/categories/retriever_spec.rb
modules/ask_va_api/spec/app/lib/ask_va_api/categories/serializer_spec.rb
modules/ask_va_api/spec/requests/v0/static_data_spec.rb

Issue #492
- Updated `StaticDataControllers#categories`
- Updated `Categories::Entity`
- Updated `Categories::Retriever`
- UPdated `Categories::Serializer`
- department-of-veterans-affairs/ask-va#492
- Updated `unit/integration` tests

BE | Ask VA API: Updated `Categories` Endpoint

---

modules/ask_va_api/app/controllers/ask_va_api/v0/static_data_controller.rb
modules/ask_va_api/app/lib/ask_va_api/categories/retriever.rb
modules/ask_va_api/app/lib/ask_va_api/inquiries/retriever.rb
modules/ask_va_api/app/lib/ask_va_api/sub_topics/retriever.rb
modules/ask_va_api/app/lib/ask_va_api/topics/retriever.rb
modules/ask_va_api/app/services/crm/base_retriever.rb
modules/ask_va_api/spec/app/lib/ask_va_api/categories/retriever_spec.rb
modules/ask_va_api/spec/app/lib/ask_va_api/inquiries/retriever_spec.rb
modules/ask_va_api/spec/app/lib/ask_va_api/subtopics/retriever_spec.rb
modules/ask_va_api/spec/app/lib/ask_va_api/topics/retriever_spec.rb

Introduce BaseRetriever class for shared retrieval logic
This PR introduces the BaseRetriever class in the AskVAApi::DataRetrieval module. The new abstract class consolidates common functionality previously duplicated across the Categories::Retriever, Topics::Retriever, and SubTopics::Retriever classes. This refactoring enhances maintainability and adheres to the DRY (Don't Repeat Yourself) principle.
Key Changes:
- BaseRetriever class abstracts shared logic for data fetching and error handling.
- Derived retriever classes (Categories, Topics, SubTopics) now inherit from BaseRetriever.
- Abstract method 'filter_data' implemented in subclasses for specific data filtering logic.
- Improved readability and reduced code duplication across retriever classes.
This change sets a foundation for …

BE | Ask VA API: Create `Crm::BaseRetriever`

---

config/settings.yml
lib/okta/directory_service.rb
lib/okta/service.rb
modules/apps_api/app/controllers/apps_api/v0/directory_controller.rb
modules/apps_api/spec/requests/v0/application_directory_request_spec.rb
spec/lib/okta/directory_service_spec.rb
spec/support/vcr_cassettes/okta/benefits-scopes.yml
spec/support/vcr_cassettes/okta/health_scopes.yml
spec/support/vcr_cassettes/okta/invalid_scopes.yml
spec/support/vcr_cassettes/okta/verification-scopes.yml
spec/support/vcr_cassettes/okta/verification_scopes.yml

Reverts department-of-veterans-affairs/vets-api#14936

Revert "API-32337 Transition App Directory Service"

---

Gemfile.lock

- Gem Update: activerecord-import
- Gem Update: combine_pdf
- Gem Update: dry-types
- Gem Update: oj
- Gem Update: okcomputer
- Gem Update: typhoeus
- Gem Update: tzinfo-data

Gem Updates: Patch level gems

---

modules/claims_api/app/swagger/claims_api/v2/production/swagger.json

- Fix merge issue
- [API-32136](https://jira.devops.va.gov/browse/API-32136)
- built rswag docs
v2 docs for POA

Update rswag merge confliction

---

app/policies/mhv_prescriptions_policy.rb

Adding logging to determine what's causing certain users who can't access RX on mobile, but are able to access it on MHV
- department-of-veterans-affairs/va-mobile-app#7680
No additional testing
(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to …

Rx access denied logging

---

config/features.yml
modules/vye/.gitignore
modules/vye/.rubocop.yml
modules/vye/app/controllers/vye/application_controller.rb
modules/vye/app/controllers/vye/v1/application_controller.rb
modules/vye/app/controllers/vye/v1/user_infos_controller.rb
modules/vye/app/models/concerns/vye/gen_digest.rb
modules/vye/app/models/vye/user_info.rb
modules/vye/app/policies/vye/user_info_policy.rb
modules/vye/app/serializers/vye/award_serializer.rb
modules/vye/app/serializers/vye/pending_document_serializer.rb
modules/vye/app/serializers/vye/user_info_serializer.rb
modules/vye/app/serializers/vye/verification_serializer.rb
modules/vye/config/routes.rb
modules/vye/spec/models/vye/user_info_spec.rb
modules/vye/spec/requests/vye/v1/show_spec.rb

Starting development for **VYE (Verify Your Enrollment)** API.
- This API is part of the migration of WAVE (https://www.gibill.va.gov/wave/vba/) from a standalone Java app to the main va.gov Ruby or Rails site.
- It's being done to bring the app to a code base when development is more active.
- This pull request does the following:
- Adds a master feature toggle for the project at the controller level
- Removes the feature toggle on GenDigest now that the controllers have a feature toggle
- scheduled local.rake to be ignored in  .rubocop.yml and .gitignore
- added ApplicationController which drops request if flipper toggle is not enabled (bad_request) or if the user is not found (forbidden).
- added UserInfosController which displays user information …

added UserInfosController and moved feature toggle to controller level

---

Gemfile.lock

Bump fitbit_api to 0.17.1
* can bump to 1.0.0 once we bump oauth2/fhir_client

Bump fitbit_api to 0.17.1

---

config/features.yml

Adds Feature Flag name for new functionality of integrating pre-filled direct deposit component on 1990EZ form.
[FE Pull Request](https://github.com/department-of-veterans-affairs/vets-website/pull/27415/)
Feature Flag Addition Only
WIll be used in the Meb API module.

Adds Feature flag for pending direct deposit prefill functionality

---

.github/workflows/sync_branch.yml

This will notify the BE cop notifications channel if the k8s sync_branch workflow fails.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/63012

Notify on failure of k8s sync

---

Gemfile
Gemfile.lock

Reverts department-of-veterans-affairs/vets-api#15099

Revert "Update govdelivery-tms to 4.0.0"

---

.github/CODEOWNERS
app/controllers/v0/benefits_claims_controller.rb
spec/controllers/v0/benefits_claims_controller_spec.rb

Updating the `#show` method of the `BenefitsClaimsController` to add a `EVSSClaim` record (if there isn't already one). We were already doing this on the `#index` method to maintain compatibility with EVSS services, but it needs to be done on the `#show` method as well.
This covers an edge case where users may bypass the claims list page in CST (and therefore bypass the #index method) and navigate directly to the details of one of their claims. In this scenario, when they go to upload files for their claim, the `DocumentsController#create` method checks for the presence of an `EVSSClaim` record linking the claim id to the logged-in user.
**Note:** EVSS doesn't do any sort of validation to determine if the claim in question belongs to the logged in user, so we do it for them via the …

[CST] Fix issues with 404s on document uploads

---

.github/CODEOWNERS

Delete extra preneeds lines in codeowners

---

modules/vye/app/controllers/vye/v1/direct_deposit_changes_controller.rb
modules/vye/app/models/vye/direct_deposit_change.rb
modules/vye/app/models/vye/user_info.rb
modules/vye/config/routes.rb
modules/vye/spec/factories/vye/direct_deposit_changes.rb
modules/vye/spec/models/vye/direct_deposit_change_spec.rb
modules/vye/spec/rails_helper.rb
modules/vye/spec/requests/vye/v1/bank_info/create_spec.rb
modules/vye/spec/spec_helper.rb

Starting development for **VYE (Verify Your Enrollment)** API.
- This API is part of the migration of WAVE (https://www.gibill.va.gov/wave/vba/) from a standalone Java app to the main va.gov Ruby or Rails site.
- It's being done to bring the app to a code base when development is more active.
- This pull request does the following:
- adds the DirectDepositChange model, controller, and test
https://jira.devops.va.gov/browse/VYE-116
**As:**
VYE Developer
**I need:**
To create a Banking API POST request
**So that:**
Upon Banking information being submitted, it can be POSTed to the VYE Database
**Considerations:**
No Other considerations
**Acceptance Criteria:**
Enter the acceptance criteria that will be used to test the user story.
-   API that handles the POST request of a changed Banking …

Added DirectDepositChange model

---

modules/mobile/app/sidekiq/mobile/v0/pre_cache_claims_and_appeals_job.rb
modules/mobile/spec/sidekiq/pre_cache_claims_and_appeals_job_spec.rb

Log error instead of raising it for PreCacheClaimsAndAppealsJob
https://github.com/department-of-veterans-affairs/va-mobile-app/issues/7654
(OPTIONAL)_What should the reviewers …

Log error instead of raising it for PreCacheClaimsAndAppealsJo

---

modules/claims_api/app/swagger/claims_api/v2/dev/swagger.json
modules/claims_api/app/swagger/claims_api/v2/production/swagger.json
modules/claims_api/config/schemas/v2/request_bodies/veteran_identifier/request.json

* Updates 'iso' in the schema description to be uppercase
* Compiles dev and production docs to reflect change.
[API-31568](https://jira.devops.va.gov/browse/API-31568)
modified:   modules/claims_api/config/schemas/v2/request_bodies/veteran_identifier/request.json

API-31568 v2 veteran identifier doc update

---

modules/claims_api/app/swagger/claims_api/v2/dev/swagger.json
modules/claims_api/app/swagger/claims_api/v2/production/swagger.json
modules/claims_api/spec/requests/v2/veterans/rswag_intent_to_file_request_spec.rb
spec/support/schemas/claims_api/v2/veterans/intent_to_file/intent_to_file.json

* Makes updates to ITF GET request docs
* Compiles dev and production swagger
* Removes a comment that is no longer applicable
[API-31571](https://jira.devops.va.gov/browse/API-31571)
modified:   modules/claims_api/spec/requests/v2/veterans/rswag_intent_to_file_request_spec.rb
modified:   spec/support/schemas/claims_api/v2/veterans/intent_to_file/intent_to_file.json

Updates docs for ITG GET in dev and production

---

db/migrate/20240122212019_create_flagged_veteran_representative_contact_data.rb
db/schema.rb

References https://github.com/department-of-veterans-affairs/va.gov-team/issues/72661
This PR creates a new migration file for the new `flagged_veteran_representative_contact_data` table.
This table will save the data "Find an Accredited Representative" search user's flag for representatives, namely a representative's `phone`, `email`, `address`, and `other`.
References https://github.com/department-of-veterans-affairs/va.gov-team/issues/72661
NA
NA

Create migration for new flagged_veteran_representative_contact_data table

---

.github/CODEOWNERS
lib/evss/claims_service.rb

- Removes the ambiguity from a service class creation of which the base class of that service class does not support.
- #65824
- Implementations of this service class were not using anything other than the `headers` argument
- safe to remove ambiguous instantiation of class
- regression unit tests are passing, thus proving the "safeness"

dbex/65824: update EVSS::ClaimsService constructor parameters

---

lib/periodic_jobs.rb
modules/ask_va_api/app/services/crm/static_data.rb
modules/ask_va_api/app/sidekiq/crm/static_data_job.rb
modules/ask_va_api/spec/services/crm/static_data_spec.rb
modules/ask_va_api/spec/sidekiq/crm/static_data_job_spec.rb

- created StaticDataJob
- retrieve data from CRM API
- cache data
- Update StaticData class
- separate fetch to crm api and fetching cache
- added StaticDataJob to periodic_job.rb
- https://github.com/department-of-veterans-affairs/ask-va/issues/680

BE | Ask VA Api: Create Job for StaticData

---

modules/ask_va_api/app/controllers/ask_va_api/v0/static_data_controller.rb
modules/ask_va_api/app/services/crm/service.rb
modules/ask_va_api/spec/requests/v0/static_data_spec.rb

- this is to test out retrieving `optionset` from CRM API

BE | Ask VA API: Updated StaticData#index

---

modules/meb_api/app/controllers/meb_api/v0/education_benefits_controller.rb

fix typo in begin/rescue block

---

modules/ask_va_api/app/controllers/ask_va_api/v0/static_data_controller.rb
modules/ask_va_api/spec/requests/v0/static_data_spec.rb

- removed authenticating user for index endpoint.

BE | Ask VA API: Remove authenticating user

---

modules/mobile/app/controllers/mobile/v0/claims_and_appeals_controller.rb
modules/mobile/spec/request/claims_and_appeals_overview_request_spec.rb
spec/support/vcr_cassettes/mobile/appeals/pagination_required_appeals.yml

Update active claims count to ignore pagination
https://github.com/department-of-veterans-affairs/va-mobile-app/issues/7778
Added new test to make sure this bug doesn't happen again

Mobile: Update active claims count to ignore pagination

---

config/features.yml

- This work is behind a feature toggle (flipper): YES, it is the feature toggle
- This adds a feature flag that will be used for changes to the way Find a Yellow Ribbon school search works in an external repo (GIDS). The GIDS endpoint will use the toggle to make sure changes to the search functionality are working as expected.
- I'm on the IIR Product team, responsible for the Find a Yellow Ribbon school tool
- The success criteria being targeted for this flipper implementation is enhancements (additions and performance) to the search functionality with no errors
- https://app.zenhub.com/workspaces/va-iir-6508c0bd79e64e0fb5855caf/issues/gh/department-of-veterans-affairs/va-iir/303
- I have verified locally that when setting this toggle, I am able to obtain the value in the GIDS service …

Add feature flag for Find a Yellow Ribbon school search changes

---

config/locales/exceptions.en.yml
lib/search/service.rb
spec/lib/search/service_spec.rb
spec/support/vcr_cassettes/search/503.yml
spec/support/vcr_cassettes/search/504.yml

- NO
- Added a function to the search service to catch 503 and 504 errors from the upstream API
- Only reproducible when the search.gov API is experiencing issues that cause them to give 503/504 errors. Currently when these errors happen, it causes additional errors in the search service due to the way the response body is structured with those errors.
- Add explicit error handling for 503 and 504 errors to allow them to be properly raised even though they may have a different response body than what is expected with other client errors.
- *(Which team do you work for, does your team …

VACMS-16784: Adds error handling for 503 and 504 responses from the search.gov API

---

.github/CODEOWNERS
app/models/emis_redis/veteran_status.rb
app/services/form1010cg/service.rb
app/services/users/exception_handler.rb
app/services/users/profile.rb
config/initializers/breakers.rb
lib/emis/models/military_service_eligibility_info.rb
lib/emis/models/veteran_status.rb
lib/emis/responses/get_military_service_eligibility_info_response.rb
lib/emis/responses/get_veteran_status_response.rb
lib/emis/veteran_status_configuration.rb
lib/emis/veteran_status_service.rb
modules/veteran_confirmation/VETERAN_CONFIRMATION.yml
modules/veteran_confirmation/app/controllers/veteran_confirmation/v0/veteran_status_controller.rb
modules/veteran_confirmation/app/services/veteran_confirmation/status_service.rb
modules/veteran_confirmation/config/mock_veteran_status_config.rb
modules/veteran_confirmation/config/routes.rb
modules/veteran_confirmation/spec/requests/health_request_spec.rb
rakelib/redis.rake
spec/lib/emis/responses/get_veteran_status_response_spec.rb
spec/models/emis_redis/veteran_status_spec.rb
spec/services/users/exception_handler_spec.rb
spec/services/users/profile_spec.rb
spec/support/emis/getVeteranStatusResponse.xml
spec/support/stub_va_profile.rb

Reverts department-of-veterans-affairs/vets-api#15320

Revert "eMIS code deletion for veteran_status"

---

.github/dependabot.yml

Enable dependabot updates for GHA

---

lib/statsd_middleware.rb

This work is not behind a feature toggle.
In https://github.com/department-of-veterans-affairs/vets-api/pull/14582 and https://github.com/department-of-veterans-affairs/vets-website/pull/26772, we added a `Source-App-Name` to the supplemental claims form, to allow us to distinguish between it and the NOD form in our logs.
This PR adds the source app name to a statsd allowlist, so that vets-api doesn't needlessly log warnings to DataDog (see [DataDog](https://vagov.ddog-gov.com/logs?query=env%3Aeks-prod%20%40message_content%3A%2AHTTP_SOURCE_APP_NAME%2A%20%40message_content%3A%2A%5C%5B995%5C-supplemental%5C-claim%5C%5D%2A%20&cols=host%2Cservice&index=%2A&messageDisplay=inline&refresh_mode=sliding&stream_sort=desc&viz=stream&from_ts=1704210149521&to_ts=1706802149521&live=true)).
I work for …

[69546] Add 995-supplemental-claim to statsd middleware allowlist.

---

modules/simple_forms_api/spec/fixtures/form_json/vba_40_0247.json
modules/simple_forms_api/spec/requests/v1/uploads_spec.rb

Reverts department-of-veterans-affairs/vets-api#15370 as it's breaking deploys (can't merge into k8s from master).
When re-adding this, a PR for both k8s and master will be needed to resolve the conflict.

Revert "Refactor Simple Forms tests"

---

modules/debts_api/spec/fixtures/pre_submission_fsr/enhanced_fsr_expenses.json
modules/debts_api/spec/fixtures/pre_submission_fsr/non_enhanced_fsr_expenses.json

This is a sub-pr of 72791 attempting to skirt the dreaded 500 line limit.
[72791](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/72791)
None, these are fixtures devoid of any meaningful context.
none

fixtures for 72791

---

lib/form1010_ezr/service.rb
lib/hca/service.rb
lib/va1010_forms/utils.rb

No
Refactor duplicate code in 1010EZR and HCA service classes
1010 team
https://github.com/department-of-veterans-affairs/va.gov-team/issues/74719
1010EZ form, 1010EZR form

Refactor duplicate code in ezr service class

---

modules/mobile/app/serializers/mobile/v2/user_serializer.rb
modules/mobile/spec/request/v2/user_request_spec.rb

Removes environment specific handling that does not work. We found a test user with staging user 556. 
https://github.com/department-of-veterans-affairs/va-mobile-app/issues/7861
Specs.

7861: remove environment handling for cerner transition

---

modules/vye/app/controllers/vye/v1/verifications_controller.rb
modules/vye/app/models/concerns/vye/gen_digest.rb
modules/vye/app/models/vye/award.rb
modules/vye/app/models/vye/user_info.rb
modules/vye/app/models/vye/verification.rb
modules/vye/lib/vye/batch_transfer/egress_files.rb
modules/vye/lib/vye/batch_transfer/ingress_files.rb
modules/vye/lib/vye/engine.rb
modules/vye/spec/factories/vye/awards.rb
modules/vye/spec/factories/vye/user_infos.rb
modules/vye/spec/factories/vye/verifications.rb
modules/vye/spec/lib/vye/batch_transfer/egress_files_spec.rb
modules/vye/spec/lib/vye/batch_transfer/ingress_files_spec.rb
modules/vye/spec/models/vye/address_change_spec.rb
modules/vye/spec/models/vye/award_spec.rb
modules/vye/spec/models/vye/direct_deposit_change_spec.rb
modules/vye/spec/models/vye/pending_document_spec.rb
modules/vye/spec/models/vye/user_info_spec.rb
modules/vye/spec/models/vye/verification_spec.rb
modules/vye/spec/requests/vye/v1/address/create_spec.rb
modules/vye/spec/requests/vye/v1/bank_info/create_spec.rb
modules/vye/spec/requests/vye/v1/show_spec.rb

https://jira.devops.va.gov/browse/VYE-215
As:
A developer
I need:
To validate verifications are getting to BDN
So that: 
My verifications are recorded and can receive checks mailed.
n/a
script generates batch file reporting verifications for the day
standard unit testing

Verification update

---

.github/CODEOWNERS

update codeowners file for pension related coverage
https://github.com/department-of-veterans-affairs/va.gov-team/issues/74646
N/A
Pensions

Pension 74646 Codeowner Cleanup

---

app/models/health_care_application.rb

This is an attempt to debug https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/75417.  We've tracked the issue through production console and it works, but it does not work when going through vets-api from the frontend.  
https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/75417
- manual and automated

75417 Debug facilityAPI validation issue

---

config/features.yml

- feature flag for whitelisting users on MHV SM Oracle Health Transition pilot environment
- https://jira.devops.va.gov/browse/MHV-53913
- feature flag - no testing required
My Health - Secure Messages `/my-health/secure-messages-pilot`

MHV-53913 SM: feature flag for MHV SM Oracle Health transition pilot environment

---

modules/veteran/app/controllers/veteran/v0/base_accredited_representatives_controller.rb
modules/veteran/app/models/veteran/service/representative.rb
modules/veteran/spec/requests/v0/base_accredited_representatives_shared_spec.rb
modules/veteran/spec/requests/v0/other_accredited_representatives_shared_spec.rb
modules/veteran/spec/requests/v0/other_accredited_representatives_spec.rb
modules/veteran/spec/requests/v0/vso_accredited_representatives_spec.rb

Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/75155
The `distance` param should be `nil` (for all records) or an integer that is >= 50 (for records within the integer's radius).
https://github.com/department-of-veterans-affairs/va.gov-team/issues/75155 …

Handle distance as a param instead of a default value

---

modules/vba_documents/lib/vba_documents/upload_validator.rb

https://github.com/department-of-veterans-affairs/vets-api/security/code-scanning/406

Resolve CodeQL 406: Upload Validator RegEx Anchor

---

app/sidekiq/benefits_intake_status_job.rb
modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb
modules/simple_forms_api/app/models/simple_forms_api/vba_21_4142.rb
modules/simple_forms_api/app/services/simple_forms_api/intent_to_file.rb
modules/simple_forms_api/app/services/simple_forms_api/pdf_stamper.rb

I'm adding/improving logging here because I can't seem to get Datadog to play nicely with the `statsd` metrics that I already have in the Benefits Intake Status Job. So, I'm hoping that if I have logs that do pretty much the same thing, then I'll be able to visualize this how I want. **But if someone knows their way around Datadog and thinks I can make a meaningful pie chart out of metrics, I'd love to talk!!**

Improve logging in Simple Forms and BI Status Job

---

modules/ask_va_api/app/controllers/ask_va_api/v0/static_data_controller.rb

- Updated `StaticData#index` endpoint to send `icn`
- https://github.com/department-of-veterans-affairs/ask-va/issues/506

BE | Ask Va Api: updated endpoint for testing

---

modules/veteran/app/models/veteran/flagged_veteran_representative_contact_data.rb

Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/75840
- Update FlaggedVeteranRepresentativeContactDatauniqueness validation
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/75840
*(Describe what parts of the …

Update FlaggedVeteranRepresentativeContactDatauniqueness validation

---

modules/veteran/app/models/veteran/flagged_veteran_representative_contact_data.rb

References https://github.com/department-of-veterans-affairs/va.gov-team/issues/75842
Ignore column in model before running migration to remove it:
```
=== Dangerous operation detected #strong_migrations ===
Active Record caches attributes, which causes problems
when removing columns. Be sure to ignore the column:
class FlaggedVeteranRepresentativeContactDatum < ApplicationRecord
self.ignored_columns = ["flagged_value_updated"]
end
Deploy the code, then wrap this step in a safety_assured { ... } block.
class DropColumnFlaggedValueUpdatedInFlaggedVeteranRepresentativeContactDataTable < ActiveRecord::Migration[7.0]
def change
safety_assured { remove_column :flagged_veteran_representative_contact_data, :flagged_value_updated }
end
end
```
- …

Ignore flagged_value_updated column

---

.github/CODEOWNERS
helmCharts/vets-api/Chart.yaml
helmCharts/vets-api/templates/NOTES.txt
helmCharts/vets-api/templates/deployment.yaml
helmCharts/vets-api/templates/ingress.yaml
helmCharts/vets-api/templates/required.yaml
helmCharts/vets-api/templates/service.yaml
helmCharts/vets-api/templates/settings-local-configmap.yaml
helmCharts/vets-api/values.yaml

- This helmChart as part of the master branch will allow building/publishing of the k8s docker file with the helm chart - matching their versions.
- This particular helm chart will be used for initial preview environments, and should not be used for non-preview environment deployments. After review instances are de-commissioned, work will begin to reconcile the helm chart in the parent-helm-chart branch and the environment wrapper charts to move towards a single deployment chart pattern as part of the master branch of vets-api
- Platform-reliability
- https://app.zenhub.com/workspaces/reliability-team-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/74850
- The helm chart has been run and tested …

74850 - Preview Environment Helm Chart to master to allow Preview Envs

---

modules/veteran/app/models/veteran/flagged_veteran_representative_contact_data.rb

Reverts department-of-veterans-affairs/vets-api#15511

Revert "Remove ignored columns from FlaggedVeteranRepresentativeContactData"

---

config/features.yml

- Added feature flags for remaining Medical Records domains.
> Create Feature Flag for all domains
> 
> User Story: As a Medical Record team, we want to Create Feature Flag for Vitals
> 
> GIVEN:
> WHEN:
> THEN:
> 
> Feature Flag Y/N ? N
> 
> AC1 Feature Flag for all domains have been created
> AC2
> AC3
> AC4
> 
> Links to UCD:
> Sketch Link:
> Other Design Notes
> 
> Architectural Notes:
- Manually tested to ensure frontend could see the new flags
- No automated testing required for simple change

MHV-52912 Added feature flags for remaining MR domains

---

modules/check_in/app/services/travel_claim/client.rb
modules/check_in/spec/services/travel_claim/client_spec.rb

This PR adds a method to submit claims to BTSSS api with a different patient identifier type than ICN. Currently this method is not used, but will be in future.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/75554
* check-in travel claim submission

75554 add submit_claim method with patient identifier type

---

modules/ask_va_api/app/controllers/ask_va_api/v0/inquiries_controller.rb
modules/ask_va_api/app/controllers/ask_va_api/v0/static_data_controller.rb
modules/ask_va_api/app/lib/ask_va_api/profile/entity.rb
modules/ask_va_api/app/lib/ask_va_api/profile/retriever.rb
modules/ask_va_api/app/lib/ask_va_api/profile/serializer.rb
modules/ask_va_api/config/locales/constants.yml
modules/ask_va_api/config/locales/get_profile_mock_data.json
modules/ask_va_api/config/routes.rb
modules/ask_va_api/spec/app/lib/ask_va_api/inquiries/entity_spec.rb
modules/ask_va_api/spec/app/lib/ask_va_api/inquiries/serializer_spec.rb
modules/ask_va_api/spec/app/lib/ask_va_api/profile/entity_spec.rb
modules/ask_va_api/spec/app/lib/ask_va_api/profile/retriever_spec.rb
modules/ask_va_api/spec/app/lib/ask_va_api/profile/serializer_spec.rb
modules/ask_va_api/spec/requests/v0/inquiries_spec.rb
modules/ask_va_api/spec/requests/v0/static_data_spec.rb
modules/ask_va_api/spec/services/dynamics_mock_service_spec.rb

In this update, we've focused on augmenting the user profile management system to bolster our application's data handling and service communication capabilities. Here's a breakdown of the components introduced:
- **`Profile::Serializer`**: This new serializer is tasked with converting user profile objects into a serialized format suitable for external API communications. It ensures that the data structure aligns with our API's expected schema and enhances the security and efficiency of data transmission.
- **`Profile::Entity`**: Represents the domain model for user profiles within our system. It serves as a central definition for the structure and behavior of profile data, encapsulating the attributes and methods related to a user's profile. This addition streamlines data manipulation and …

Created `/profile` endpoint

---

modules/ask_va_api/app/controllers/ask_va_api/v0/static_data_controller.rb

- fix typo in test endpoint
*(Describe what parts of the …

BE | Ask Va Api: update test endpoint for /announcement

---

modules/ask_va_api/app/controllers/ask_va_api/v0/static_data_controller.rb
modules/ask_va_api/app/lib/ask_va_api/announcements/entity.rb
modules/ask_va_api/app/lib/ask_va_api/announcements/retriever.rb
modules/ask_va_api/app/lib/ask_va_api/announcements/serializer.rb
modules/ask_va_api/config/locales/get_announcements_mock_data.json
modules/ask_va_api/config/routes.rb
modules/ask_va_api/spec/app/lib/ask_va_api/announcements/entity_spec.rb
modules/ask_va_api/spec/app/lib/ask_va_api/announcements/retriever_spec.rb
modules/ask_va_api/spec/app/lib/ask_va_api/announcements/serializer_spec.rb
modules/ask_va_api/spec/requests/v0/static_data_spec.rb

In this pull request, I've introduced a set of new components and a controller action aimed at improving our application's announcements management system. Here's a breakdown of the updates:
- **`Announcements::Entity`**: This class represents the domain model for announcements within our system. It encapsulates all the attributes and methods related to an announcement, ensuring a clear separation of concerns and a solid foundation for our business logic.
- **`Announcements::Retriever`**: A service object designed to abstract the complexity of fetching announcements from our data store. Whether it's retrieving a single announcement, a collection of announcements for a specific date, or applying certain filters, this class handles all data retrieval operations, ensuring efficiency and …

Created `/announcements` endpoint

---

modules/ask_va_api/app/lib/ask_va_api/base_retriever.rb
modules/ask_va_api/app/lib/ask_va_api/optionset/retriever.rb
modules/ask_va_api/spec/app/lib/ask_va_api/optionset/retriever_spec.rb
modules/ask_va_api/spec/app/lib/ask_va_api/topics/retriever_spec.rb

- Updated:
- `topics` to `Topics`
-  `optionset` to `OptionSet`
- https://github.com/department-of-veterans-affairs/ask-va/issues/754

BE | Ask Va Api: Update endpoint to Topics and OptionSet

---

config/features.yml

Burials v2 feature flag
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/75226
- Tested toggle works locally in development. vets-website responds correctly.

Add burial v2 feature flag

---

modules/vye/app/controllers/vye/v1/user_infos_controller.rb
modules/vye/app/models/vye/address_change.rb
modules/vye/app/models/vye/user_info.rb
modules/vye/app/models/vye/verification.rb
modules/vye/spec/factories/vye/user_infos.rb
modules/vye/spec/models/vye/address_change_spec.rb

As:
I need:
To create a daily reports for address change.
So that: 
It can be sent to BDN.
Need to figure out the format of the file current produced in WAVE
Enter the acceptance criteria that will be used to test the user story. 
Should produce a text file in the staging environment
The file format should be aligned with current file format 
Not for this sprint. 
None

Address handling update

---

app/services/evss_claim_service.rb
spec/services/evss_claim_service_spec.rb

EVSS has a requirement that the `va_eauth_birlsfilenumber` header must be present / not empty. This header is populated from the `birls_id` attribute from the User model. For non-Veteran users, we suspect that the `birls_id` attribute is always nil which presents us with an issue where we cannot satisfy the "not empty" part of their requirement for the `va_eauth_birlsfilenumber` header. We have discovered that all claims in BGS are associated with a Veteran, even if the claimant is not a Veteran / the Veteran the claim is associated with. If we pull the claim details from BGS we are able to get the Participant ID of the Veteran associated with the claim and we can then use the Participant ID to call BGS and get the Veterans file number to use for the `va_eauth_filenumber` header when …

[CST] Workaround for EVSSClaimService with non-Veteran users (Second attempt)

---

modules/ask_va_api/app/controllers/ask_va_api/v0/static_data_controller.rb
modules/ask_va_api/spec/requests/v0/static_data_spec.rb

- updated static data to be more dynamics

BE | Ask Va Api: Updated `staticdata#index`

---

.github/CODEOWNERS

Updating the CODEOWNERS for the EVSS claims services. Removing vfs-authenticated-experience-backend and replacing the team with benefits-management-tools-be. I think this was a misassignment in the first place
- department-of-veterans-affairs/va.gov-team/issues/76597
CODEOWNERS

Update CODEOWNERS for EVSS Claims services

---

app/controllers/v0/map_services_controller.rb
lib/map/security_token/service.rb
spec/lib/map/security_token/service_spec.rb
spec/requests/v0/map_services_controller_request_spec.rb

- Adds additional logging to the MAP STS token request, including
- a `token request` log that runs before every request for a MAP STS token
- updates `token success` log to occur after MAP STS response is parsed
- error logs for MAP STS-returned errors, missing ICN, and application mismatch
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/75174
To test, create a [Service Account token](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Products/Sign-In%20Service/Engineering%20Docs/auth_flows/service_account.md), then use that to query the [MAP STS token endpoint](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Products/Service%20Account%20Endpoints/MAP%20STS%20Token.md).
You should …

75174 add MAP STS logging

---

modules/veteran/app/sidekiq/representatives/update.rb

Reverts department-of-veterans-affairs/vets-api#15605
This approach ended up blocking the queue for some reason. Here's a thread about it - https://dsva.slack.com/archives/CBU0KDSB1/p1708549095036479

Revert "FAR: Add rate limiting for Trexler File Sidekiq jobs"

---

config/features.yml
modules/my_health/app/controllers/my_health/v1/prescriptions_controller.rb
modules/my_health/config/routes.rb
modules/my_health/spec/request/v1/prescriptions_request_spec.rb
spec/support/vcr_cassettes/rx_client/prescriptions/gets_a_list_of_refillable_prescriptions.yml

- Added logic to refill multiple prescriptions
- Added logic to retrieve a list of only refillable/renewable prescriptions
- Added test for new endpoint
https://jira.devops.va.gov/browse/MHV-55039
> As a Medications developer, I want to create a new subpage for refilling so that it matches mocks
- Ran tests locally
- Added test
MHV Medications App

MHV-55309-Add-Refill-Logic

---

lib/pdf_fill/forms/va21p527ez.rb

- This fix updates the expected value received for marriage_type. We are now correctly passing in marriage type of `CEREMONY` instead of `In a civil or religious ceremony with an officiant who signed my marriage license`.
- Pension benefits team to own this change.
- [*Link to ticket created in va.gov-team repo*](https://github.com/department-of-veterans-affairs/va.gov-team/issues/74762)
- [*Link to epic if not included in ticket*](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/74762)
- *Describe the steps required to verify your changes are working as expected. Exclusively stating 'Specs run' is …

update expected marriage_type value

---

modules/vaos/app/services/vaos/v2/appointments_service.rb
modules/vaos/spec/services/v2/appointment_service_spec.rb

Reverts department-of-veterans-affairs/vets-api#15663
Convo here: https://dsva.slack.com/archives/C0460N83Y9G/p1708980748429359

Revert "VAOS Remove Appointment Telehealth Information Logging"

---

modules/vaos/app/services/vaos/v2/appointments_service.rb
modules/vaos/spec/services/v2/appointment_service_spec.rb

Reverts department-of-veterans-affairs/vets-api#15682
Found the issue in another PR
https://dsva.slack.com/archives/C0460N83Y9G/p1708983646461079?thread_ts=1708980748.429359&cid=C0460N83Y9G

Revert "Revert "VAOS Remove Appointment Telehealth Information Logging""

---

.github/workflows/build.yml
app/services/users/form_526_user_identifiers_status_service.rb
app/services/users/profile.rb
app/sidekiq/bgs/job.rb
app/sidekiq/bgs/submit_form674_job.rb
app/sidekiq/bgs/submit_form686c_job.rb
app/sidekiq/education_form/create_daily_spool_files.rb
config/features.yml
modules/simple_forms_api/app/services/simple_forms_api/pdf_stamper.rb
modules/vaos/app/controllers/vaos/v2/clinics_controller.rb
modules/vaos/app/services/vaos/v2/appointments_service.rb
modules/vaos/spec/request/v2/clinics_request_spec.rb
spec/services/users/form526_user_identifiers_status_service_spec.rb
spec/services/users/profile_spec.rb
spec/sidekiq/bgs/submit_form674_job_spec.rb
spec/sidekiq/bgs/submit_form686c_job_spec.rb
spec/support/schemas/user_loa1.json
spec/support/schemas/user_loa3.json
spec/support/schemas_camelized/user_loa1.json
spec/support/schemas_camelized/user_loa3.json

K8s feb 28

---

modules/claims_api/app/sidekiq/claims_api/report_hourly_unsuccessful_submissions.rb

* Fixes the search window for error claims in the hourly slack message
- *This work is behind a feature toggle (flipper):  NO
[API-33700](https://jira.devops.va.gov/browse/API-33700)
- *If this work is behind a flipper:* NO
- *Tests need to be written for both the flipper …

Fixes my oversight when updating the window for searching and reporting

---

modules/my_health/docs/openapi.yaml
modules/my_health/docs/openapi_merged.yaml
modules/my_health/docs/schemas/Prescription.yml
modules/my_health/docs/schemas/PrescriptionDetail.yml
modules/my_health/docs/schemas/PrescriptionList.yml

- Update Swagger docs to include the endpoints
- https://jira.devops.va.gov/browse/MHV-55145
- Tested locally.

MHV-55145 Update Swagger docs to include the endpoints

---

Gemfile.lock

Update json schema with new validation for 1010EZ form
I work for the 1010 team
https://github.com/department-of-veterans-affairs/va.gov-team/issues/77291
1010EZ form

10-10EZ - TERA: Update JSON Schema validation for freeform text field

---

Gemfile.lock

https://github.com/department-of-veterans-affairs/vets-website/pull/28291
https://github.com/department-of-veterans-affairs/vets-json-schema/pull/850
New JSON-SCHEMA has been merged, and this pr is rebuilding the GEM with the new JSON-SCHEMA

updated schema version

---

config/features.yml

- Adds 3 new toggles that are required for work around direct deposit for ch33 edu benefit migrations
- feature toggles will be present through April 20th-ish + 1-2 months to complete migration and deal with any lingering issues.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/76725
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/76714
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/76724
- tested locally, but just adding the flag names at this point
No ui changes
Profile

Add direct deposit toggles

---

modules/veteran/app/models/veteran/service/representative.rb
modules/veteran/spec/models/veteran/service/representative_spec.rb
modules/veteran/spec/sidekiq/representatives/queue_updates_spec.rb

Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/77629
I misread an error in staging regarding the Trexler File job the other day. I got it again this morning when running the job manually in staging. Basically, no records were updated.
```
{"host":"vets-api-web-76768f4f4c-xpcmv","application":"vets-api-server","environment":"production","timestamp":"2024-03-05T15:11:08.656149Z","level":"error","level_index":4,"pid":711,"thread":"12380","file":"/app/lib/sentry_logging.rb","line":57,"named_tags":{"dd":{"env":"eks-staging","service":"vets-api","version":"","trace_id":"0","span_id":"0"},"ddsource":"ruby"},"name":"Rails","message":"QueueUpdates error: Error queuing address updates: undefined method `values_at' for nil:NilClass"}
I, [2024-03-05T15:11:08.675746 …
```

Fix bug in Trexler File job

---

.github/workflows/delete_stale_branches.yml
config/settings.local.yml.example
docs/setup/docker.md
spec/lib/debt_management_center/payments_service_spec.rb

- cleaning up diffs with master …

77219 - minor changes to k8s branch to match master

---

app/controllers/v0/rated_disabilities_controller.rb
spec/controllers/v0/rated_disabilities_controller_spec.rb
spec/support/vcr_cassettes/lighthouse/veteran_verification/disability_rating/200_inactives_response.yml
spec/support/vcr_cassettes/lighthouse/veteran_verification/show/200_inactives_response.yml

Removing the ICN from the LH response before it gets passed to the Frontend. Also added in some code to account for the face that ratings can have an end date in the future and are considered active until that date passes
- *This work is behind a feature toggle (flipper): YES (FE feature toggle gates whether this controller is called or not)*
Added a new cassette to cover active vs inactive ratings
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer- …

[Rated Disabilities] Remove PII from the LH response

---

modules/ask_va_api/app/lib/ask_va_api/attachments/entity.rb
modules/ask_va_api/app/lib/ask_va_api/attachments/retriever.rb
modules/ask_va_api/config/locales/get_attachment_mock_data.json
modules/ask_va_api/spec/app/lib/ask_va_api/attachments/entity_spec.rb
modules/ask_va_api/spec/app/lib/ask_va_api/attachments/retriever_spec.rb
modules/ask_va_api/spec/app/lib/ask_va_api/attachments/serializer_spec.rb
modules/ask_va_api/spec/app/lib/ask_va_api/inquiries/entity_spec.rb
modules/ask_va_api/spec/requests/v0/inquiries_spec.rb

In this pull request, I’ve made targeted updates to key components within our attachment handling subsystem, aiming to improve performance, reliability, and code readability. Below is a breakdown of the changes:
1. **Updated `Attachment::Retriever`:**
- **What Changed:** Optimized data retrieval logic. 
2. **Updated `Attachment::Entity`:**
- **What Changed:** Refined the `Attachment::Entity` model to better encapsulate attachment-related data. 
- https://github.com/department-of-veterans-affairs/ask-va/issues/500
- *Tests need to be written …

BE | Ask Va Api: Updated `attachment` endpoint

---

Gemfile.lock

Bump i18n -> 1.14.3

---

config/locales/en.yml

> Updating error message shown when an incorrect PDF password is entered - removing mail in evidence
> Content update recommedation
- [#69617](https://github.com/department-of-veterans-affairs/va.gov-team/issues/69617)
- [Design](https://www.figma.com/file/BplQkEDZzD8NPPNmLrhvXv/Request-a-Board-Appeal-%2F-Notice-of-Disagreement-(VA-10182)?type=design&node-id=0-6232&mode=design&t=bOLyHRTyUYTFoIEw-0) …

Update incorrect_password error message part 2

---

modules/simple_forms_api/app/form_mappings/vba_40_10007.json.erb
modules/simple_forms_api/app/models/simple_forms_api/vba_40_10007.rb
modules/simple_forms_api/spec/fixtures/form_json/vba_40_10007_with_supporting_document.json

Updated get_attachments method in the 40-10007 model to append attachments to PDF
https://jira.devops.va.gov/browse/MBMS-59988
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretoggl …

MBMS-59988 updated get attachments method and erb

---

lib/lighthouse/benefits_education/configuration.rb

This is a bug, caused by a missing `require` statement.  To reproduce:
1. In `vets-api` - disable authentication on controller by modifying 
`class Post911GIBillStatusesController < ApplicationController` to
`class Post911GIBillStatusesController < ActionController::API`
2. create a `current_user` function, like this:
```
def current_user
@current_user ||= OpenStruct.new(icn: "1012667145V762142")
end
```
3. replace instances of `@current_user` with `current_user`
4. run `vets-api` locally
5. In postman, execute a get request to …

Add missing "require" statement

---

.github/CODEOWNERS
Jenkinsfile

Reverts department-of-veterans-affairs/vets-api#15843

Revert "Remove Build AMI step"

---

modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb
modules/simple_forms_api/app/models/simple_forms_api/vba_26_4555.rb

This PR improves how we submit data to the LGY service endpoint and also fixes the return JSON to the front end so that we can display the confirmation number.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/702

Fix some issues with 26-4555

---

modules/ask_va_api/app/controllers/ask_va_api/v0/health_facilities_controller.rb
modules/ask_va_api/config/routes.rb
modules/ask_va_api/spec/requests/health_facilities_spec.rb

- created `HealthFacilities` endpoints for `index` and `show`
- https://github.com/department-of-veterans-affairs/ask-va/issues/718

BE | Ask Va Api: Create `HealthFacilities` endpoint

---

Jenkinsfile

Clean up JenkinsFile and only target pull requests in UI by removing this section:
This stops the job from running unnecessarily in master:

Platform Test - Cleanup Jenkins

---

Gemfile.lock
spec/fixtures/pdf_fill/21P-527EZ/merge_fields.json

- Updated vets_json_schema to the latest version to account for recent schema changes made in the pensions form.
- *[Link to ticket created in va.gov-team repo](https://github.com/department-of-veterans-affairs/va.gov-team/issues/76777)*
- [*Link to epic if …

Updated vets_json_schema to version 21.0.1

---

modules/vye/app/controllers/vye/application_controller.rb

name spacing application controller

name spacing application controller

---

modules/simple_forms_api/app/models/simple_forms_api/vba_21_0845.rb

This PR implements user tracking for simple forms form 21-0845.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/1108

Track users on 21-0845

---

config/features.yml

- Removes the blocked triage group feature flag (`mhv_secure_messaging_blocked_triage_group_1_0`) from vets-api, now that it is no longer necessary
> Now that the Blocked Triage Group alert is deployed and running, we can remove the feature flag from the list of feature flags on vets-website and vets-api
> 
> AC1 remove mhv_secure_messaging_blocked_triage_group_1_0 from vets-api feature flags
> AC2 remove mhvSecureMessagingBlockedTriageGroup1p0 from vets-website feature flags
- Manual testing to ensure vets-website still runs without feature flag
_Note: …

removed blockedTG feature flag

---

spec/fixtures/form1010_ezr/valid_form_with_tera.json
spec/lib/form1010_ezr/service_spec.rb
spec/requests/form1010_ezrs_request_spec.rb
spec/support/vcr_cassettes/form1010_ezr/authorized_submit_with_tera.yml

- Adds request and unit test for 10-10 EZR TERA
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/74953
- A request and unit test have been added
10-10 EZR form

10-10 EZR: Add TERA Tests

---

config/features.yml

added va_online_scheduling_datadog_RUM feature toggle

#78115: Add a new feature flag for Datadog RUM

---

config/features.yml

- While working [this](https://github.com/department-of-veterans-affairs/vets-website/pull/28523) ticket I found that we could remove the omni-link configuration and feature toggle since we will no longer be using it. 
- Removed the feature toggle omni_channel_link
- [Parent Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/77675) 
- [Front End Ticket](https://github.com/department-of-veterans-affairs/vets-website/pull/28523) …

Remove feature toggle omni_channel_link

---

config/features.yml

- Add Flipper feature-flag for new form-app Priority Processing (20-10207)
- Team: Veteran Facing Forms
[vets-website](https://github.com/department-of-veterans-affairs/vets-website/pull/28533)
- _department-of-veterans-affairs/va.gov-team-forms#1083
- Local browser-testing was successful
This form ONLY

20-10207 - Add feature-flag

---

modules/claims_api/app/sidekiq/claims_api/poa_updater.rb

* Related clean up to [API-34542](https://jira.devops.va.gov/browse/API-34542) PR.
* Removed the unneeded check but missed cleaning out the now unused error message formatter.
* Clean up related to work done on [API-34542](https://jira.devops.va.gov/browse/API-34542) .  Ticket is [API-34859](https://jira.devops.va.gov/browse/API-34859).
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-Backendexample). …

API-34859 remove unused error message formatter

---

modules/claims_api/lib/claims_api/cid_mapper.rb

- Add VetraSpec to mapper for emails
- [API-34663](https://jira.devops.va.gov/browse/API-34663)
Nightly emails

API-34663 Add VetraSpec to mapper

---

modules/my_health/app/controllers/my_health/v1/all_triage_teams_controller.rb
modules/my_health/app/controllers/my_health/v1/triage_teams_controller.rb

- anywhere where there is a guard clause like: `raise Common::Exceptions::InternalServerError if resource.blank?`
This will throw a Ruby `ArgumentError` , essentially masking what's really going on, because InternalServerError requires an argument of type exception.
- Adding a fix would to raise a `RecordNotFound` , since that's actually what's happening - a fetch of a given resource is returning an empty response.
- https://jira.devops.va.gov/browse/MHV-49427
- https://dsva.slack.com/archives/C03ECSBGSKX/p1694120096384079 …

MHV-49427 Secure Messaging - Address InternalServerError exceptions

---

modules/mobile/app/models/mobile/v0/adapters/vaos_v2_appointment.rb
modules/mobile/spec/models/adapters/appointments_vaos_v2_adapter_spec.rb
modules/mobile/spec/request/appointments_vaos_v2_list_request_spec.rb

Updating field to nil until we decide what the actual purpose should be for it, if any. Setting to nil will make the FE work in a more desirable way in the meantime.  …

tests updated

---

modules/vye/app/models/vye/address_change.rb
modules/vye/app/models/vye/user_info.rb
modules/vye/app/serializers/vye/address_change_serializer.rb
modules/vye/app/serializers/vye/user_info_serializer.rb
modules/vye/spec/factories/vye/user_infos.rb
modules/vye/spec/models/vye/address_change_spec.rb

https://jira.devops.va.gov/browse/VYE-253
https://jira.devops.va.gov/browse/VYE-254
As:
I need:
To separate data  from transient date.
So that: 
 Data that's not transient does not get purged.
No considerations
 Data that's not transient does not get purged.
Have to be moved out in separate tables
ICN
SSN 
Claim number 
Not a new feature, so there's no test component
No other considerations
As:
I need:
 To separate address data from BDN
So that: 
 It could be added to the addresses array in user profile
No considerations
So front end can see all the addresses
Will only show the last address to populate from
Testing …

serparating address from bdn import

---

modules/representation_management/app/models/representation_management/flagged_veteran_representative_contact_data.rb

Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/78750
Remove `flagged_value_updated` from `ignored_columns`
NA
Find a Representative search

Remove flagged_value_updated from ignored_columns

---

modules/appeals_api/config/mailinglists/report_daily.yml

https://lighthouseva.slack.com/archives/CKUCFQAHJ/p1710959836938229?thread_ts=1699284572.857799&cid=CKUCFQAHJ

Add Derek Fong to Decision Reviews daily email list

---

config/settings/test.yml
modules/travel_pay/app/controllers/travel_pay/claims_controller.rb
modules/travel_pay/app/controllers/travel_pay/pings_controller.rb
modules/travel_pay/app/models/travel_pay/claim.rb
modules/travel_pay/app/serializers/travel_pay/claim_serializer.rb
modules/travel_pay/app/services/travel_pay/client.rb
modules/travel_pay/config/routes.rb
modules/travel_pay/spec/controllers/claims_controller_spec.rb
modules/travel_pay/spec/controllers/pings_controller_spec.rb
modules/travel_pay/spec/services/client_spec.rb

This commit sets up the structure & methods needed to support getting claims from the BTSSS get claims endpoint. The get claims BTSSS endpoint is not yet finished, so mock data is needed for this vets-api endpoint to be fully finished.

Btsss 77373 mock status endpoint

---

.github/CODEOWNERS

PRs were being blocked by inaccurate file & folder assignments. This fixes those up.
https://lighthouseva.slack.com/archives/C03UA9MV1EH/p1711546898009279

Update CODEOWNERS file to more accurately reflect current ownerships

---

config/features.yml

- Added representative_status_enabled toggle to registry
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/77607

Adding feature toggle for new representative status widget

---

modules/mobile/app/controllers/mobile/v0/locations_controller.rb

The location id was a hard coded substring index which makes it brittle against location id length changes. This pr changes it to a more logical `split`
https://github.com/department-of-veterans-affairs/va-mobile-app/issues/8028
Existing tests cover the change

Mobile: Update logic for getting location id substring

---

.github/CODEOWNERS
app/controllers/v1/pension_ipf_callbacks_controller.rb

- Added some temporary logging to help debug authentication issue in staging. Will remove once issue is resolved.
- Pension benefits team to own this change.
- https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2780
- https://github.com/department-of-veterans-affairs/vets-api/pull/15883
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-g …

added temp logging to debug in staging

---

.devcontainer/devcontainer.json
.devcontainer/on-create.sh
.devcontainer/post-create.sh
.devcontainer/post-start.sh
.gitignore

- **Codespaces: Create on-create.sh**
- **Codespaces: Start Rails/Sidekiq on attach**
- **Codespaces: Prewarn bootsnap and add homebrew to zshrc**
- **Codespaces: open preview on rails server port open**
- **:retab file**
- **Codespaces: fix asdf -> zshrc syntax**
- **Codespaces: Missing packages; run apt update**
- **Codespaces: Use ruby image**
- **Codespaces: Remove asdf**
- **Codespaces: ruby 3.2**
- **Codespaces: change back to notify on port 3000 open**
- **Codespaces: open codespaces readme**
- **Codespaces: Implode RVM**
- **Codespaces: Move RVM implosion as it didn't exist yet**
- **Codespaces: RVM doesn't like to be sudoed**
- **Codespaces: remove rvm implosion; not working**
- **Codespaces: Remove unused docker extension**
- **Codespaces: Set ruby lsp version manager to none**

Codespaces Optmizations

---

app/controllers/v0/rated_disabilities_discrepancies_controller.rb
spec/controllers/v0/rated_disabilities_discrepancies_controller_spec.rb

Adding the length of both responses and the rating ids of both responses to help simplify the manual debugging process
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/79937
Updated specs to account for the changes made to the log contents …

[Rated Disabilities] Update discrepancy logging to include more fine-grained data

---

app/models/prescription_details.rb
modules/my_health/app/serializers/my_health/v1/prescription_details_serializer.rb
modules/my_health/docs/openapi_merged.yaml
modules/my_health/docs/schemas/PrescriptionDetail.yml
modules/my_health/spec/request/v1/prescriptions_request_spec.rb
spec/models/prescription_details_spec.rb
spec/support/schemas/my_health/prescriptions/v1/prescription_details.json
spec/support/schemas_camelized/my_health/prescriptions/v1/prescription_details.json

- Updated prescription object model
- Updated unit tests, schemas
- Updated swagger docs
https://jira.devops.va.gov/browse/MHV-55960
> As a Medications user, I want to update when I see the medication description so that I can see accurate and helpful information about my medication
- Updated tests
- Ran tests locally
MHV medications app on VA.gov

Added new fields to prescription object, updated spec test

---

modules/mobile/spec/request/user_request_spec.rb

enable vaos feature flag in user request spec

---

modules/claims_api/app/controllers/concerns/claims_api/poa_verification.rb
modules/claims_api/spec/concerns/claims_api/poa_verification_spec.rb

- Fix rep lookup (fixed the wrong file in #15613)
- [API-35438](https://jira.devops.va.gov/browse/API-35438)
- Should lookup by poa_code if multiple found by first/last/middle
POA

Api 35438 vso not found take2

---

modules/appeals_api/config/routes.rb
modules/appeals_api/spec/requests/metadata_request_spec.rb
modules/appeals_api/spec/requests/v1/appeals_controller_spec.rb

This PR removes the following Appeals API routes that were never in use or are no longer in use. These endpoints were confirmed to have received no traffic over the past 3 months using the API Gateway logs.
Removed routes:
- `/services/appeals/v1/appeals_healthcheck` (replaced by `/services/appeals/v0/healthcheck`; v1 was never correct)
- `/services/appeals/v1/appeals_upstream_healthcheck` (replaced by `/services/appeals/v0/upstream_healthcheck`; v1 was never correct)
- `/services/appeals/v1/appeals` (replaced by `/services/appeals/appeals-status/v1/appeals`)
- `/services/appeals/docs/v1/appeals` (replaced by `/services/appeals/appeals-status/v1/docs`)
- `/services/appeals/docs/v0/ci` (replaced by `/services/appeals/appealable-issues/v0/docs`)
- `/services/appeals/docs/v0/hlr` (replaced …

API-34203: Remove Unused Appeals API Routes

---

modules/mobile/spec/request/authorized_services_spec.rb

Fixes a flaky test
None, existing tests cover the issue

Mobile: Fix flaky test

---

lib/pdf_fill/forms/va21p530v2.rb

- *This work is behind a feature toggle (flipper): YES va_burial_v2*
- Removed middle name from appearing on the overflow page.
- Solution is to remove references to middle name with length 0 so that it doesn't have the opportunity to appear anywhere on the pdf.
-VA Benefits and Claims
- [*Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses Jira*](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80498)
- Previously middle name appeared on the overflow page.
-Create a Burial V2 claim with middle names …

remove middle name from overflow page

---

lib/statsd_middleware.rb

- includes new mhv-secure-messaging and mhv-secure-messaging-pilot app names in the allowed list on vets-api
- https://dsva.slack.com/archives/C03ECSBGSKX/p1712843347393979 …

added sm and sm-pilot to allowed list

---

config/features.yml

- yes
- updates features.yml, feature to be used in vets-website
- unknown? We've collected feedback for months and intend to do incremental release after development and completion of successful staging review
- https://github.com/department-of-veterans-affairs/vagov-claim-classification/issues/414
*(Describe what parts of the site are …

add new feature flag for add disabilities page updates

---

db/migrate/20240411235242_create_pega_table.rb
db/schema.rb

For the IVC Champva application to communication with DOCMP PEGA systems, we need to create a callback API. This will need a small lightweight database to record status updates.
None. This is the first database integration with Pega systems. The most related issue is with lighthouse API.
https://github.com/department-of-veterans-affairs/vets-api/pull/14801/files#diff-d2a13a1ef61a18e96f57d956873c0e1c596dec5d504c97ee2f87405ed9321a52 …

add pega table

---

app/controllers/v0/health_care_applications_controller.rb
config/routes.rb
spec/requests/health_care_applications_request_spec.rb
spec/support/vcr_cassettes/lighthouse/facilities/v1/200_facilities_facility_ids.yml

Adds new V1 lighthouse facilities endpoint to health care application controller. 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/79437
- Staging
- Spec
EZ10

add facilities endpoint to health care applications

---

lib/common/client/concerns/mhv_fhir_session_client.rb
modules/simple_forms_api/spec/requests/v1/uploads_spec.rb
spec/controllers/v0/virtual_agent/virtual_agent_claim_spec.rb
spec/lib/common/client/concerns/mhv_fhir_session_client_spec.rb
spec/lib/simple_forms_api_submission/service_spec.rb

- This PR fixes flaky specs that seem to crop up around file creation/destruction with PDF

Fixing flaky specs related to pdf generation

---

app/sidekiq/terms_of_use/sign_up_service_updater_job.rb
spec/sidekiq/terms_of_use/sign_up_service_updater_job_spec.rb

- Remove uniqueness and drop retry count
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/80261
- Updated unit tests
- Nothing new to really test since this is just changing sidekiq config
Terms of use

SignUpServiceUpdaterJob: Remove unique and reduce retries

---

modules/simple_forms_api/app/services/simple_forms_api/pdf_stamper.rb

This PR makes some small adjustments to the signature stamping in 20-10207, to bring it in line with the logic used in the form model itself.

Fix signature in 20-10207

---

modules/ask_va_api/app/lib/ask_va_api/inquiries/retriever.rb

- Fix small bug in `Inquiries::Retriever`
- https://github.com/department-of-veterans-affairs/ask-va/issues/494

BE | Ask VA API: update Inquiriies::Retriever

---

modules/check_in/app/services/check_in/vaos/appointment_service.rb
modules/check_in/app/services/check_in/vaos/configuration.rb
modules/check_in/spec/services/check_in/vaos/appointment_service_spec.rb

Includes specs for appointment service
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/68696

68696 appointment service specs

---

db/migrate/20240411153910_create_accredited_individuals.rb
db/schema.rb

References https://github.com/department-of-veterans-affairs/va.gov-team/issues/80656
This PR creates the following new table:
- accredited_individuals
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/80656
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/78731
- NA
The database
The schema.rb file

Create accredited_individuals table

---

config/features.yml

-Adds a feature flag to handle new duplicate contact info check functionality in TOE app

add feature flag for toe dup call

---

modules/ask_va_api/app/lib/ask_va_api/correspondences/creator.rb

- fix minor bug in `Correspondences::Creator`

BE | Ask VA Api: fix bug

---

app/sidekiq/education_form/templates/10203.erb

vfep-1341 - remove feature flags for 10203 spool file changes
- remove feature flag for recent 10203 spool file changes
- VFEP
- [vfep-1341](https://jira.devops.va.gov/browse/VFEP-1341)
- [github 16388](https://github.com/department-of-veterans-affairs/vets-api/issues/16388)
- changes to 10203 spool file behind feature flags
- changes to 10203 spool file show on production

vfep-1341 - remove feature flags for 10203 spool file changes

---

modules/appeals_api/app/services/appeals_api/remove_pii.rb
modules/appeals_api/spec/services/appeals_api/remove_pii_spec.rb

- This uses Datadog to trace the activity of the `RemovePii` service, which is responsible for clearing PII from records in our Sidekiq jobs.
- It also sends a notification to Slack with details about the failure.
- This is part of the acceptance criteria for this ticket, and it will help me debug an odd error I'm seeing when clearing PII from some specific records in staging (the flag for the new PII removal policy is not turned on in production yet).
- [API-34961](https://jira.devops.va.gov/browse/API-34961)
- Logs extra information when removing PII from any appeal record

API-34961 Trace appeals PII removal with Datadog

---

modules/simple_forms_api/spec/requests/v1/uploads_spec.rb

Preventing future merge conflict

---

modules/check_in/app/services/v2/lorota/redis_client.rb
modules/check_in/spec/services/v2/lorota/redis_client_spec.rb

This PR adds fetch_attributes to LoROTA redis client class. The attributes from appointment identifiers most sensibly belong to LoROTA's redis client since that is what writes the appointment identifiers to Redis. Otherwise we'd need to have other redis client classes (like TravelClaims::RedisClient or Map::RedisClient) implement duplicate methods.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/80854

80854 Add fetch_attibutes to Lorota Redis Client

---

modules/ask_va_api/app/controllers/ask_va_api/v0/inquiries_controller.rb
modules/ask_va_api/app/lib/ask_va_api/correspondences/creator.rb

- Change `post` to `put` method

BE | Ask VA Api: Update `post` to `put`

---

modules/mobile/app/controllers/mobile/v0/payment_information_controller.rb
modules/mobile/spec/request/payment_information_request_spec.rb

Direct deposits is now including EDU along with C&P direct deposit information. We do not need differentiate between the two but we do want to make sure all wording associated with it is generic and not C&P specific. This PR changes the confirmation email to use a generic direct deposit wording rather then C&P. 
https://github.com/department-of-veterans-affairs/va-mobile-app/issues/8332
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature …

Mobile Payment information - use generic direct deposit confirmation email 

---

.github/CODEOWNERS
app/models/accredited_individual.rb
app/models/accredited_organization.rb
lib/accredited_representation/constants.rb
spec/factories/accredited_individuals.rb
spec/factories/accredited_organizations.rb
spec/models/accredited_individual_spec.rb
spec/models/accredited_organization_spec.rb

- This pr adds `AccreditedIndividual` and `AccreditedOrganization` models and factories
- The intent of the pr is to just get us started on a path moving forward with the new accreditation tables, the models are not meant to have everything we could ever want at this time.
- [78732](https://github.com/department-of-veterans-affairs/va.gov-team/issues/78732)
No impact yet as no code references the new models

[78732] Create AccreditedIndividual and AccreditedOrganization models

---

lib/pdf_fill/forms/va21p530v2.rb

- *This work is behind a feature toggle (flipper): yes va_burial_v2
- Broke out the object that contains the response to the tribal land question so that it appears in the pdf correctly.
- Expanded tribalAndLocation in addition to cemeteryLocation
-[ *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses Jira*](https://github.com/department-of-veterans-affairs/va.gov-team/issues/81372)
- …

fix tribal land not appearing

---

.github/CODEOWNERS
app/models/form_profile.rb
app/models/form_profiles/va_107959f1.rb
config/form_profile_mappings/10-7959F-1.yml
config/settings.yml

Fixed Dockerfile merge conflict

---

modules/ask_va_api/app/lib/ask_va_api/correspondences/creator.rb
modules/ask_va_api/app/lib/ask_va_api/inquiries/creator.rb
modules/ask_va_api/spec/app/lib/ask_va_api/correspondences/creator_spec.rb
modules/ask_va_api/spec/app/lib/ask_va_api/inquiries/creator_spec.rb
modules/ask_va_api/spec/requests/v0/inquiries_spec.rb

- fix error response for submit inquiry and submit reply

BE | Ask Va Api: fix error response for submit inquiry and reply

---

modules/ask_va_api/app/lib/ask_va_api/correspondences/creator.rb
modules/ask_va_api/app/lib/ask_va_api/inquiries/creator.rb
modules/ask_va_api/spec/app/lib/ask_va_api/correspondences/creator_spec.rb
modules/ask_va_api/spec/app/lib/ask_va_api/inquiries/creator_spec.rb
modules/ask_va_api/spec/requests/v0/inquiries_spec.rb

Fix k8s 2024 0424

---

modules/ask_va_api/app/controllers/ask_va_api/v0/inquiries_controller.rb
modules/ask_va_api/app/lib/ask_va_api/inquiries/retriever.rb
modules/ask_va_api/spec/app/lib/ask_va_api/inquiries/retriever_spec.rb
modules/ask_va_api/spec/requests/v0/inquiries_spec.rb

- fix `Inquiries::Retriever` error handling
- remove authentication from `InquiriesController#show` action

BE | Ask Va Api: `Inquiries` retriever error handling

---

modules/vye/app/controllers/vye/v1/verifications_controller.rb
modules/vye/app/models/vye/address_change.rb
modules/vye/app/models/vye/award.rb
modules/vye/app/models/vye/bdn_clone.rb
modules/vye/app/models/vye/pending_document.rb
modules/vye/app/models/vye/user_info.rb
modules/vye/app/models/vye/user_profile.rb
modules/vye/app/models/vye/verification.rb
modules/vye/spec/factories/vye/awards.rb
modules/vye/spec/factories/vye/bdn_clones.rb
modules/vye/spec/factories/vye/user_infos.rb
modules/vye/spec/factories/vye/user_profiles.rb
modules/vye/spec/factories/vye/verifications.rb
modules/vye/spec/models/vye/bdn_clone_spec.rb
modules/vye/spec/models/vye/verification_spec.rb
modules/vye/spec/requests/vye/v1/verify/create_spec.rb

https://jira.devops.va.gov/browse/VYE-338
As:
I need:
To updated the API to reflex and display the updated interface for addresses, and pending enrollment verification.
So that: 
Frontend developers can display on the website
N/A
API show new interface
N/A
N/A

Wire up the backend API to frontend (Backend)

---

modules/ask_va_api/app/lib/ask_va_api/base_retriever.rb
modules/ask_va_api/app/lib/ask_va_api/correspondences/retriever.rb
modules/ask_va_api/app/lib/ask_va_api/inquiries/retriever.rb
modules/ask_va_api/spec/app/lib/ask_va_api/correspondences/retriever_spec.rb
modules/ask_va_api/spec/app/lib/ask_va_api/inquiries/retriever_spec.rb
modules/ask_va_api/spec/requests/v0/inquiries_spec.rb

- Updated `Inquiries::Retriever` and `Correspondences::Retriever`

BE | Ask Va Api: Update `Inquiries::Retriever` and `Correspondences::Retriever`

---

modules/travel_pay/app/services/travel_pay/client.rb
modules/travel_pay/spec/services/client_spec.rb

Related to department-of-veterans-affairs/va.gov-team#73503
The BTSSS API token response structure has changed. This PR updates the way we get the token from the repsonse accordingly.

Fixes token access path.

---

modules/ask_va_api/app/lib/ask_va_api/correspondences/creator.rb
modules/ask_va_api/app/lib/ask_va_api/inquiries/creator.rb
modules/ask_va_api/app/lib/ask_va_api/optionset/retriever.rb
modules/ask_va_api/app/services/crm/cache_data.rb
modules/ask_va_api/spec/app/lib/ask_va_api/correspondences/creator_spec.rb
modules/ask_va_api/spec/app/lib/ask_va_api/inquiries/creator_spec.rb
modules/ask_va_api/spec/app/lib/ask_va_api/optionset/retriever_spec.rb
modules/ask_va_api/spec/requests/v0/inquiries_spec.rb
modules/ask_va_api/spec/requests/v0/static_data_spec.rb
modules/ask_va_api/spec/services/crm/cache_data_spec.rb

- Rework `Inquiries::Creator` error handling
- Rework `Correspondences::Creator` error handling
- Rework `CacheData` error handling
- Updated `optionset` class and spec to reflect changes in `CacheData`

BE | Ask Va Api:  Update `Inquiries::Creator` `Correspondences::Creator` Error Handling

---

lib/pdf_fill/forms/va21p530v2.rb

- Changed the overflow length to match the field. updated the question number.
- This is the solution because previously it allowed 75 characters and the overflow did not transfer to the overflow page. Now it transfers earlier.
[- *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses Jira*](https://github.com/department-of-veterans-affairs/va.gov-team/issues/81782) …

change limit on place and location. update question number

---

modules/ask_va_api/app/controllers/ask_va_api/v0/inquiries_controller.rb
modules/ask_va_api/app/controllers/ask_va_api/v0/static_data_controller.rb
modules/ask_va_api/app/lib/ask_va_api/attachments/retriever.rb
modules/ask_va_api/spec/app/lib/ask_va_api/attachments/retriever_spec.rb
modules/ask_va_api/spec/requests/v0/inquiries_spec.rb
modules/ask_va_api/spec/requests/v0/static_data_spec.rb

- **Removed** `test_create` endpoint: This endpoint was removed as it was no longer necessary for our application’s functionality or testing purposes.
- **Removed** `Inquiries#index` action: Previously used solely as a test endpoint, this action has been eliminated to streamline our controller's operations.
- **Reworked Error Handling:** Improved the error handling mechanism to provide more precise and useful error responses, enhancing the robustness and reliability of the attachment retrieval process.

BE | Ask VA Api: Refactor classes and specs

---

modules/meb_api/lib/dgi/submission/service.rb

- We need to debug this service but it only exists in staging so adding loggers to get an idea of what is happening.
- *If this work is behind a …

add loggers to see what dd api call is doing in staging

---

.github/workflows/code_checks.yml
modules/claims_api/app/sidekiq/claims_api/service_base.rb
modules/claims_api/app/sidekiq/claims_api/v2/disability_compensation_docker_container_upload.rb
modules/claims_api/app/sidekiq/claims_api/v2/disability_compensation_pdf_generator.rb
modules/claims_api/spec/sidekiq/v2/disability_compensation_docker_container_upload_spec.rb
modules/meb_api/lib/dgi/submission/service.rb
modules/vaos/app/schemas/appointments_index.json

Fix k8s 2024 0429

---

Dangerfile

I'm updating the Dangerbot message. One URL was bad and the message was partially inaccurate. Migrations ARE run automatically 🎉 
I saw the need for this update while on support, so I'll link our support epic:
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/75908
The Dangerbot message when someone submits a PR with db files + other files.

Dangerfile updates for db migration

---

Dockerfile

k8s Dockerfile

---

docker-compose.yml

Reverted docker compose

---

modules/meb_api/lib/dgi/submission/service.rb

- Update params.dig call to use correct hash keys
- logger to see if masking is returning true and if we're inside the if statement

upadte param dig call

---

lib/evss/disability_compensation_form/data_translation_all_claim.rb

This corrects an issue with the current mapping with regards to the toxic exposure flow
Disability Benefits Team 1 (DBEX-TREX 🦖 ) …

Toxic Exposure - fix to disabilities mapping logic

---

.github/CODEOWNERS
app/controllers/v1/apidocs_controller.rb
app/swagger/swagger/v1/requests/ivc_champva_forms.rb

This pull request introduces the initial implementation of Swagger documentation for the IVC CHAMPA forms API. We are collaborating with the DOCMP PEGA team to integrate our API with their system. Our API will consume the payload sent by DOCMP's system via an HTTP POST request and update our database accordingly.
Key Changes:
1. Added Swagger documentation for the API endpoints and request/response models.
This work lays the foundation for the IVC CHAMPA forms integration with DOCMP's system, enabling seamless data exchange and processing.
Next Steps:
- Collaborate with DOCMP team for end-to-end testing in staging environments.
- Finalize documentation and prepare for production deployment.
- Implemented the endpoint to receive and process DOCMP's payload.
- Added database update logic to …

swagger ivc forms v1

---

db/migrate/20240501164739_attempt_may1_remove_ssn_and_icn_from_vye_tables.vye.rb
db/migrate/20240501164740_attempt_may1_remove_address_details_from_vye_user_infos.vye.rb
db/migrate/20240501164741_attempt_may1_change_datetime_to_date.vye.rb
db/migrate/20240501164742_attempt_may1_update_verifications.vye.rb
db/migrate/20240501164743_attempt_may1_create_vye_bdn_clones.vye.rb
db/migrate/20240501164744_attempt_may1_add_to_vye_user_infos.vye.rb
db/migrate/20240501164745_attempt_may1_remove_from_vye_pending_document.vye.rb
db/schema.rb
modules/vye/db/migrate/20240501000100_attempt_may1_remove_ssn_and_icn_from_vye_tables.rb
modules/vye/db/migrate/20240501000101_attempt_may1_remove_address_details_from_vye_user_infos.rb
modules/vye/db/migrate/20240501000102_attempt_may1_change_datetime_to_date.rb
modules/vye/db/migrate/20240501000103_attempt_may1_update_verifications.rb
modules/vye/db/migrate/20240501000104_attempt_may1_create_vye_bdn_clones.rb
modules/vye/db/migrate/20240501000105_attempt_may1_add_to_vye_user_infos.rb
modules/vye/db/migrate/20240501000106_attempt_may1_remove_from_vye_pending_document.rb

guarded migrations to redo what was reverted in 55a6fbb530

guarded migrations to redo what was reverted in 55a6fbb530

---

modules/facilities_api/app/controllers/facilities_api/application_controller.rb
modules/facilities_api/app/models/facilities_api/v2/lighthouse/facility.rb
modules/facilities_api/app/services/facilities_api/v2/lighthouse/client.rb
modules/facilities_api/app/services/facilities_api/v2/mobile_covid/client.rb
modules/facilities_api/app/services/facilities_api/v2/mobile_covid/configuration.rb
modules/facilities_api/app/services/facilities_api/v2/mobile_covid/response.rb
modules/facilities_api/config/routes.rb
modules/facilities_api/spec/models/facilities_api/v2/lighthouse/facility_spec.rb
modules/facilities_api/spec/services/facilities_api/v2/mobile_covid/client_spec.rb

- Added Facilities API v2 mobile_covid services to prepare for a migration from Lighthouse Facilities API v0 to v1. The controllers will come in the next PR to complete the implementation.
- Not a bug
- Solution is to create a v2 of Facilities API that will make calls to Lighthouse Facilities API v1 while allowing v1 of Facilities API to stay intact for …

IIR 599 Facilities API v2 mobile_covid

---

Makefile

- add bundle exec to foreman in make up command

Makefile up command fix

---

lib/evss/disability_compensation_form/form526_to_lighthouse_transform.rb
spec/factories/form526_submissions.rb
spec/lib/evss/disability_compensation_form/form526_to_lighthouse_transform_spec.rb
spec/support/disability_compensation_form/all_claims_fe_submission.json
spec/support/disability_compensation_form/submissions/with_everything_toxic_exposure.json

This PR maps transforms Lighthouse request disability attributes based on new toxic exposure information, namely:
- `isRelatedToToxicExposure` (from matching to the `toxicExposure/conditions` collection)
- `exposureOrEventOrInjury` (from the FE caption label for `cause` ("NEW", "WORSENED", "SECONDARY", "VA")
- *This work is behind a feature toggle (flipper): YES* `disability_526_toxic_exposure`
Disability Benefits Experience Team 1 (DBEX-TREX 🦖)
Toxic Exposure - Data Transformation #3 - Add Conditions#[81426](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/departm …

Toxic Exposure - Data Transformation #3 - Add Conditions

---

db/migrate/20240501183550_attempt_may1_add_index_to_verifications.vye.rb
db/schema.rb
modules/vye/db/migrate/20240501000107_attempt_may1_add_index_to_verifications.rb

migration to redo what was reverted in 55a6fbb530

migration to redo what was reverted in 55a6fbb530

---

config/features.yml

- Add a feature flag to toggle between displaying the lefthand navigation on Secure Messaging (current) or removing it for the new navigation solution (upcoming)
> Feature flag for release of secondary nav and breadcrumb changes (coordinate with other teams and potentially use the same FeatureFlag)
> 
> NOTE:  Design is pending cartography team.  
> 
> Kickoff meeting 4/30/24
> 
> Implementation plan:
> 
> https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/rollout/integrat …

added remove lefthand nav feature toggle

---

config/features.yml

Reverts department-of-veterans-affairs/vets-api#16368

Revert "Removed feature toggle profile_show_proof_of_veteran_status"

---

modules/representation_management/app/controllers/representation_management/v0/apidocs_controller.rb
modules/representation_management/app/docs/representation_management/v0/power_of_attorney_controller.yaml
modules/representation_management/config/routes.rb

Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/78101
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/78101
- *Tests need …

Document poa endpoint

---

modules/vye/app/controllers/vye/v1/verifications_controller.rb
modules/vye/app/models/vye/address_change.rb
modules/vye/app/models/vye/award.rb
modules/vye/app/models/vye/bdn_clone.rb
modules/vye/app/models/vye/pending_document.rb
modules/vye/app/models/vye/user_info.rb
modules/vye/app/models/vye/user_profile.rb
modules/vye/app/models/vye/verification.rb
modules/vye/spec/factories/vye/awards.rb
modules/vye/spec/factories/vye/bdn_clones.rb
modules/vye/spec/factories/vye/user_infos.rb
modules/vye/spec/factories/vye/user_profiles.rb
modules/vye/spec/factories/vye/verifications.rb
modules/vye/spec/models/vye/bdn_clone_spec.rb
modules/vye/spec/models/vye/verification_spec.rb
modules/vye/spec/requests/vye/v1/verify/create_spec.rb

redo what was reverted in 55a6fbb530

redo what was reverted in 55a6fbb530

---

config/features.yml

added feature toggle for address and direct deposit forms
- *Link to previous change of …

added feature toggle for address and direct deposit forms

---

modules/facilities_api/app/models/facilities_api/v2/ppms/provider.rb
modules/facilities_api/app/models/facilities_api/v2/ppms/specialty.rb
modules/facilities_api/app/services/facilities_api/v2/ppms/configuration.rb
modules/facilities_api/app/services/facilities_api/v2/ppms/middleware/ppms_parser.rb
modules/facilities_api/config/routes.rb
modules/facilities_api/spec/models/facilities_api/v2/ppms/provider_spec.rb
modules/facilities_api/spec/models/facilities_api/v2/ppms/specialty_spec.rb

- Added v2 of Facilities API CCP routes and PPMS model, config, and middleware for a migration from Lighthouse Facilities API v0 to v1. This PR is the first in several of porting over the CCP/PPMS functionality to Facilities API v2.
- Solution is to create a v2 of Facilities API that will make calls to Lighthouse Facilities API v1 while allowing v1 of …

Iir 628 facilities api v2 ppms

---

app/sidekiq/evss/disability_compensation_form/submit_form526.rb

- adds the `flipper user` to the form526 `disability_compensation_lighthouse_submit_migration` flipper flag call
- [#18611](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/81611)
- tests already written. this covers the "user" flipper flag senario

dbex/81611: create and send in flipper user

---

db/migrate/20240506214134_add_index_on_veteran_icn_on_claims_api_auto_established_claims.rb
db/schema.rb

Created index on claims_api_auto_established_claims (veteran_icn) as PGHero has requested.
is the success criteria being targeted?)*
- department-of-veterans-affairs/va.gov-team#[79050](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80648)

Created Index on claims_api_auto_established_claims (veteran_icn)

---

config/features.yml

> YES
> Adding a feature toggle for showing an updated Notice of Disagreement confirmation page with form data & a link to a downloadable PDF
> Building based on user testing
> After feature is fully released and we've established that the changes are benefiting the Veteran
> [NOD | Confirmation …

DR | Add confirmation page feature flag

---

modules/facilities_api/app/services/facilities_api/v2/ppms/client.rb
modules/facilities_api/app/services/facilities_api/v2/ppms/response.rb
modules/facilities_api/spec/factories/facilities_api/v2/ppms/providers.rb
modules/facilities_api/spec/services/facilities_api/v2/ppms/response_spec.rb

- Added v2 of Facilities API PPMS client and response services for a migration from Lighthouse Facilities API v0 to v1. This PR is one of several that are porting over the CCP/PPMS functionality to Facilities API v2.
- Solution is to create a v2 of Facilities API that will make calls to Lighthouse Facilities API v1 while allowing v1 of Facilities API to …

Add v2 facilities_api ppms client and response

---

modules/vye/.rubocop.yml
modules/vye/app/models/concerns/vye/needs_enrollment_verification.rb

https://jira.devops.va.gov/browse/VYE-236
Update API with logic from Frontend so that it can be consolidated on the backend instead of distributed between IVR, Frontend, and Backend.  Based on Jared's scaffolding.
As:
Backend developer
I need:
To recreate enrollment logic in Ruby
So that: 
It could be utilize in APIs as needed. 
Enrollment logic was recreated from WAVA java and sql files into JavaScript for testing purposes. The enrollment logic now needs to be translated into RUBY where it will reside on the backend.
Enrollment logic is implemented in backend
Testing will be created{}
Other Considerations: NA

vye-236-enrollment-logic

---

modules/vye/lib/tasks/vye.rake
modules/vye/lib/vye/batch_transfer/ingress_files.rb
modules/vye/lib/vye/load_data.rb
modules/vye/spec/lib/vye/batch_transfer/ingress_files_spec.rb

https://jira.devops.va.gov/browse/VYE-338
As:
I need:
To updated the API to reflex and display the updated interface for addresses, and pending enrollment verification.
So that: 
Frontend developers can display on the website
N/A
API show new interface
N/A
N/A

vye-338-wire-to-frontend

---

modules/check_in/app/services/check_in/vaos/facility_service.rb
modules/check_in/spec/services/check_in/vaos/facility_service_spec.rb

- *Get Clinic method implmentation for CIE VAOS appointments endpoint*
- *https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/81881*
NA

81881 cie vaos get clinic implementation

---

lib/periodic_jobs.rb
modules/claims_api/app/mailers/claims_api/submission_report_mailer.rb
modules/claims_api/app/sidekiq/claims_api/report_monthly_submissions.rb
modules/claims_api/app/views/claims_api/submission_report_mailer/submission_report.html.erb
modules/claims_api/spec/mailers/report_monthly_submissions_spec.rb
modules/claims_api/spec/sidekiq/report_monthly_submissions_spec.rb
spec/mailers/previews/claims_api_submission_report_mailer_preview.rb

* Changes timeframe for the report
* Removes yearly reporting code
* Updates email template
* Updates related tests
_A lot of the lines changes are related to the tests added/updated_
[API-35932](https://jira.devops.va.gov/browse/API-35932)
- http://localhost:3000/rails/mailers/claims_api_submission_report_mailer/build (uses hard coded data to populate display)
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogg …

API-35932 monthly email updates

---

docs/setup/native.md

fixing k8s

---

docs/setup/hybrid.md
docs/setup/native.md
docs/setup/running_natively.md

Rcassity fix k8s 2024 08 may 2

---

lib/admin/postgres_check.rb

- Follow up to https://github.com/department-of-veterans-affairs/vets-api/pull/16629
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/74637

change error to info in ArgoCD Database check

---

config/features.yml

- Created a new feature toggle called `cst_claim_phases` to vets-api
- Link to ticket created in va.gov-team repo: https://github.com/department-of-veterans-affairs/va.gov-team/issues/82361
- Link to Frontend PR https://github.com/department-of-veterans-affairs/vets-website/pull/29674
Claim Status Tool

[CST] - Add new feature toggle cst_claim_phases to vets-api

---

app/models/saved_claim/veteran_readiness_employment_claim.rb
lib/pdf_fill/forms/va281900.rb

- *This work is behind a feature toggle (flipper): no*
- I overrode the saved claim to_pdf method so that the vre saved claims will pass the created_at date to their pdfs for the signature date. 
- This solution follows the pattern in 686c and 21p-530v2, passing a specific date in the options. additionally passed the date when sending to vbms initially.
- VA benefits and claims
[- *Link to ticket created in va.gov-team repo OR screenshot of Jira …

vre signature set to created at date

---

modules/ask_va_api/app/controllers/ask_va_api/v0/inquiries_controller.rb
modules/ask_va_api/app/lib/ask_va_api/profile/retriever.rb
modules/ask_va_api/config/locales/en.yml
modules/ask_va_api/spec/app/lib/ask_va_api/inquiries/entity_spec.rb
modules/ask_va_api/spec/app/lib/ask_va_api/inquiries/serializer_spec.rb
modules/ask_va_api/spec/app/lib/ask_va_api/profile/retriever_spec.rb
modules/ask_va_api/spec/requests/v0/inquiries_spec.rb
modules/ask_va_api/spec/services/dynamics_mock_service_spec.rb

- more refactoring of `InquiriesController`
- https://github.com/department-of-veterans-affairs/ask-va/issues/728

BE | Ask VA API: refactored InquiriesController

---

modules/check_in/app/services/check_in/vaos/facility_service.rb
modules/check_in/spec/services/check_in/vaos/facility_service_spec.rb

- *Implementation for caching clinic data & rspecs*
- *https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/82602*
NA

82602 Rspecs for caching facility functionality

---

db/schema.rb
lib/evss/disability_compensation_form/form526_to_lighthouse_transform.rb
spec/lib/evss/disability_compensation_form/form526_to_lighthouse_transform_spec.rb
spec/support/disability_compensation_form/all_claims_fe_submission.json
spec/support/disability_compensation_form/submissions/with_everything_toxic_exposure.json

This PR transforms the incoming Gulf War Hazard locations from the front end to the `toxicExposure.gulfWarHazardService.servedInGulfWarHazardLocations` field on the Lighthouse request.
- *This work is behind a feature toggle (flipper): YES* `disability_526_toxic_exposure`
Added to the `Form526ToLighthouseTransform.transform()` method + related unit tests
Disability Benefits Experience Team 1 - DBEX/TREX 🦖
- *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket …

Toxic Exposure:  Gulf War Hazards #3 - Transform to Lighthouse request

---

modules/simple_forms_api/app/models/simple_forms_api/vba_26_4555.rb

This PR fixes a typo that was preventing SAH from receiving our data.

Send the right data to SAH from Simple Forms

---

.github/workflows/build.yml
.github/workflows/deploy-template.yml

add deploy to build workflow

---

db/migrate/20240507200527_update_ivc_champva_forms_indices.rb

Fixing a [failing deploy](https://dsva.slack.com/archives/C30LCU8S3/p1715792625636229).

fix: add if_not_exists to failing add_index

---

modules/ask_va_api/app/controllers/ask_va_api/v0/education_facilities_controller.rb
modules/ask_va_api/config/routes.rb
modules/ask_va_api/spec/requests/v0/education_facilities_spec.rb

- Created `EducationFacilitiesController`
- https://github.com/department-of-veterans-affairs/ask-va/issues/961

BE | Ask VA Api: Create `EducationFacilitiesController`

---

docs/setup/running_docker.md

A support ticket was opened because of some errors while running `make up`. A `make build` helped fix them. 
- https://dsva.slack.com/archives/CBU0KDSB1/p1715613047265469?thread_ts=1715198228.415129&cid=CBU0KDSB1
- Tested by @szarrougtw 
Documentation in vets-api repo (this doc is not on the platform website)

Update troubleshooting section of docker readme

---

modules/claims_api/spec/requests/v2/veterans/disability_compensation_request_spec.rb

- fixes broken test
modified:   modules/claims_api/spec/requests/v2/veterans/disability_compensation_request_spec.rb

Fixes broken test

---

.github/CODEOWNERS
app/controllers/v0/veteran_onboardings_controller.rb
config/routes.rb
spec/controllers/v0/veteran_onboardings_controller_spec.rb
spec/factories/veteran_onboardings.rb

This PR represents the final backend changes needed to implement a "Veteran Onboarding Experience" for newly-transitioned veterans.  Here are the previous PRs:
[Feature Toggle](https://github.com/department-of-veterans-affairs/vets-api/pull/16573)
Migrations/Schema Updates [here](https://github.com/department-of-veterans-affairs/vets-api/pulls?q=is%3Apr+author%3AAdamKing0126+#:~:text=2-,VA%2DIIR%20649%3A%20Pull%20migration%20and%20schema%20changes%20into%20separate%20PR,-%2316596%20by%20AdamKing0126) and [here](https://github.com/department-of-veterans-affairs/vets-api/pull/16626)
[Model](https://github.com/department-of-veterans-affairs/vets-api/pulls?q=is%3Apr+author%3AAdamKing0126+#:~:text=Add%20VeteranOnboarding%20model)
[Serializer …

VA-IIR 636: Add new Rails controller for Veteran Onboarding

---

modules/vye/app/models/vye/user_info.rb
modules/vye/spec/factories/vye/user_infos.rb
modules/vye/spec/requests/vye/v1/show_spec.rb

Removing enums for mr_status and indicator in UserInfo because the clients have been develop to take them as is from BDN.

Remove enums

---

config/features.yml

- This PR adds a new flipper feature flag to features.yml
- This flipper feature flag is for use w/ a follow-up PR to route traffic to a new endpoint in VRO
- https://github.com/department-of-veterans-affairs/vagov-claim-classification/issues/471

add feature flag for multicontention classification in VRO

---

config/features.yml

- *This work is behind a feature toggle (flipper): No*
- Added a flipper so that phase 2 of Dependents work can begin on the FE
[- *Link to ticket created in va.gov-team repo OR screenshot of Jira ticket if your team uses Jira*](https://github.com/department-of-veterans-affairs/va.gov-team/issues/81048)
- Confirm flipper is present with other flippers.
(OPTIONAL)_What should the …

add va dependents v2 flipper

---

config/features.yml

Updated `features.yml` to include a feature flag for the Medical-Records-Settings button, allowing control over its active or inactive state.
[MHV-58385](https://jira.devops.va.gov/browse/MHV-58385) - Add settings button to Left Navigation
Update Content and Left Navigation for Health Conditions-see latest designs
https://www.figma.com/design/mGZRdLypKGaFsHo5xp2kaZ/Medical-Records?node-id=4467-36464&t=NouvL14iCrDlRZ5S-0 
From Amelia:  We will need to include the settings page and download all records page. Content for those is most likely changing, too–hopefully we will have those change asap.  (Do we need a separate ticket?)
User Story: As a Medical Records User, I want to see updated content and left navigation so that the latest designs are displayed.
Feature Flag Y/N ? N
Manual …

MhV-58385 Add Settings Button To Left Navigation

---

config/features.yml

Add feature flag for enabling/disabling new Lighthouse ITF logic
department-of-veterans-affairs/va.gov-team#82186
- _Link to epic if not included in ticket_
https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/82186

Add new Lighthouse ITF flipper

---

lib/medical_records/client.rb
modules/my_health/docs/openapi.yaml
modules/my_health/docs/openapi_merged.yaml
modules/my_health/spec/request/v1/clinical_notes_request_spec.rb
modules/my_health/spec/request/v1/conditions_request_spec.rb
modules/my_health/spec/request/v1/labs_and_tests_request_spec.rb
modules/my_health/spec/request/v1/vaccines_request_spec.rb
modules/my_health/spec/request/v1/vitals_request_spec.rb
spec/lib/medical_records/client_spec.rb
spec/support/vcr_cassettes/mr_client/get_a_diagnostic_report.yml
spec/support/vcr_cassettes/mr_client/get_a_list_of_chemhem_labs.yml
spec/support/vcr_cassettes/mr_client/get_a_single_lab_or_test.yml

- Simplified the Labs & Tests endpoints. Now they are just basic FHIR calls like all our other calls.
- Updated the openapi docs to fix the path to the referenced FHIR documentation
- Fixed a few random spec tests
> For Labs & Tests, we used to combine the results of three API calls into one list to be returned to the frontend. This no longer needs to be done, since Radiology was recently pulled out of the mix. Instead turn this into a nice simple API call to pull all DiagnosticReport entries.
> 
> Feature Flag Y/N ?
> 
> DataDog/Analytics Y/N ? N
> 
> 
> 
> 
> UCD Validation Y/N N
> 
> 
> 
> 
> 
> AC1  The list_labs_and_tests function returns all relevant DiagnosticReport types …

MHV-47757 Updates to labs and tests API

---

modules/ivc_champva/app/controllers/ivc_champva/v1/uploads_controller.rb
modules/ivc_champva/app/models/ivc_champva/vha_10_7959c.rb
modules/ivc_champva/spec/models/vha_10_7959c_spec.rb

This PR enables attachments and the attachments metadata for Form 7959c. The attachments and metadata will now be successfully uploaded to AWS S3.
This PR is also dependent on the successful merge of the front end change (ticket # 29883)
https://github.com/department-of-veterans-affairs/vets-api/pull/16726
https://github.com/department-of-veterans-affairs/vets-website/pull/29883
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles …

add 7959c metadata and attachments

---

modules/travel_pay/app/controllers/travel_pay/claims_controller.rb
modules/travel_pay/app/services/travel_pay/service_error.rb
modules/travel_pay/spec/controllers/claims_controller_spec.rb

Adding more robust logging for error monitoring on datadog. 
Related to department-of-veterans-affairs/va.gov-team#79500

Add more robust logging for errors to support datadog

---

app/sidekiq/evss/disability_compensation_form/form526_document_upload_failure_email.rb
spec/sidekiq/evss/disability_compensation_form/form526_document_upload_failure_email_spec.rb

This mailer job was initially implemented  ([by me](https://github.com/department-of-veterans-affairs/vets-api/pull/16359)) without properly using the rather obtuse Job Tracking module in `lib/sidekiq/form526_job_status_tracker/job_tracker.rb`. Adds this behavior as there were some failures in testing this mailer in staging that were throwing in the job tracker and obscuring actual errors that need to be surfaced.
In addition, it was required to refactor these tests to use `perform_async` and `described_class.drain`, as calling perform on these jobs doesn't appear to create a job id (`jid` is the available var in Sidekiq callbacks) and the Job Tracker relies on this for a lot of its logging paradigm. In the wild, these jobs will be executed with `perform_async` anyway.
- *This work is …

Implement with_tracking block in Form526DocumentUploadFailureEmail

---

config/features.yml

- Added feature toggle so that we can test middleware POC in multiple environments 
- https://github.com/department-of-veterans-affairs/va-virtual-agent/issues/1736
- Webchat

add feature toggle for component testing

---

modules/claims_api/spec/requests/v2/veterans/disability_compensation_request_spec.rb

- Added tests for 526 endpoint submissions with special issues.
[API-36434](https://jira.devops.va.gov/browse/API-36434)
- rspec 
modules/claims_api/spec/requests/v2/veterans/disability_compensation_request_spec.rb

Add tests for 526 special issues scenarios

---

modules/facilities_api/app/controllers/facilities_api/v2/va_controller.rb

- This adds a skip of verify_authentication_token to the Facilities API VA Controller so that requests to the search endpoint don't return a 403 when there's not an authenticity token available.
- Currently the preview-prod environment is recreating the request producing the 403 at an incredible rate. This will remove the chance of receiving a 403 when …

Add skip_before verify_auth_token to controller

---

config/routes.rb
modules/ivc_champva/spec/requests/v1/uploads_spec.rb

This PR's goal is to add more unit tests to the IVC uploads controller to increase code coverage.

add unit test to uploads controller

---

modules/vye/db/seed/staging/alfredo-m-armstrong.yaml
modules/vye/db/seed/staging/allan-butler.yaml
modules/vye/db/seed/staging/andrea-l-mitchell.yaml
modules/vye/db/seed/staging/anthony-joey-williams.yaml
modules/vye/lib/vye/load_data.rb

staging data

---

lib/lighthouse/benefits_claims/service.rb

Ensure current user and icn is present when initializing the BenefitsClaims service
- department-of-veterans-affairs/va.gov-team#81916
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Feat …

Put logs for BC service

---

config/features.yml

We need this feature flag to default to false in development as the direct deposit API is unavailable in that environment.
- There is not a specific issue, but our testing in the development environment is effected when this flag is defaulted to being ON.
- *Tests need to be written for both the flipper on and …

changes default to false in development for show_dgi_direct_deposit_1990EZ

---

modules/ivc_champva/app/jobs/ivc_champva/missing_form_status_job.rb
modules/ivc_champva/spec/jobs/missing_form_status_job_spec.rb

Remove space for StatsD

---

modules/simple_forms_api/app/models/simple_forms_api/vba_40_10007.rb

Added rails logging to the 40-10007 form
https://jira.devops.va.gov/browse/MBMS-66758
- *What is the …

MBMS-66758 Added rails logging to 40-10007

---

app/models/form526_submission.rb
lib/lighthouse/benefits_claims/service.rb
rakelib/form526.rake

This work is a combination of tickets 82149 and 83433.  In 82149 the `validate526` service method for the lighthouse class is added to support the /validate endpoint following the pattern established by the service method `submit526`.  Ticket 83433 calls for a sycronious method in the Form526Submission model to use this new lighthouse end point.  It also calls for a new rake task to review entries from the database using the new `form_content_valid?` method in the model. …

Adding instance method "validate526" to BenefitsClaims::Service class

---

app/policies/mhv_messaging_policy.rb

Added logging to help debug this issue: https://dsva.slack.com/archives/C018V2JCWRJ/p1717514902962589
- *Tests …

added logging

---

config/features.yml

This PR adds a form_upload_flow flipper for the front end.
[FE PR here.](https://github.com/department-of-veterans-affairs/vets-website/pull/30163)

Add form_upload_flow flipper

---

modules/debts_api/lib/debts_api/v0/fsr_form_transform/bankruptcy_calculator.rb
modules/debts_api/lib/debts_api/v0/fsr_form_transform/streamlined_calculator.rb
modules/debts_api/spec/lib/debt_api/v0/fsr_form_transform/bankruptcy_calculator_spec.rb
modules/debts_api/spec/lib/debt_api/v0/fsr_form_transform/streamlined_calculator_spec.rb

This is part of the larger effort to move the transformation logic for the FSR form from the front end to the back end. This pull request is for part five of this effort addressing many of the miscellaneous transformations, specifically `bankruptcy` and `streamlined`. These are only two of the miscellaneous properties to transform and is not enough to close the ticket on its own.
I am on the VA debt team, which owns maintenance of this code. This work is not behind a feature toggle.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/81058
_This has not been added at the time of this pull request._
- *Describe the steps required to verify your changes are working as expected. Exclusively stating 'Specs run' is …

Full transform on backend, Part 5 [Extra Data] (81058)

---

app/sidekiq/central_mail/submit_form4142_job.rb
app/sidekiq/evss/disability_compensation_form/form4142_document_upload_failure_email.rb
config/features.yml
config/settings.yml
spec/sidekiq/central_mail/submit_form4142_job_spec.rb
spec/sidekiq/evss/disability_compensation_form/form4142_document_upload_failure_email_spec.rb

Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/80044
After a Veteran submits a Form 526 to apply for disability benefits, one of our follow-up jobs, `SubmitForm4142Job`, attempts to submit a Form 4142 to Central Mail as well.
If this job fails and exhausts all of its retries, we now want to send this email to the Veteran letting them know the steps needed to resolve this problem:
This behavior is protected behind the `form526_send_4142_failure_notification` feature toggle.
Disability Benefits engineering
Mailer sends successfully in staging …

[Document Upload Failure] Mail veteran on form 4142 upload retry exhaustion

---

modules/facilities_api/app/services/facilities_api/v2/lighthouse/response.rb

- This work is not behind a feature toggle
- This change sets the Facilities API v2 Response data to empty array if the downstream data source does not return 'data' in its response. I noticed that I was able to supply filters that would not match any data in the Lighthouse Facilities v1 API, and when that happens, the Lighthouse endpoint does not return a 'data' key in its response.
- I work on the IIR team, and the Sitewide Facilities team owns the component. I am assisting them with this migration project.
- …

Set Response data to empty array if not returned from Lighthouse API

---

modules/simple_forms_api/app/models/simple_forms_api/vba_21_4138.rb

[SIMPLE_FORMS] fix: 21-4138 -  update metadata to rectify errors

---

app/models/form526_submission.rb

Faraday::Response#status is the proper way to access the response status code as an integer.
- *Describe the steps required to verify your changes are working as …

dbx-83433v2 change response.code to response.status

---

config/features.yml

- Added toggle for user tracking feature for SM 
- No formal tickets, just  private slack channels threads

(feature toggle) added toggle for unique user tracking in SM

---

modules/simple_forms_api/app/models/simple_forms_api/vba_40_10007.rb

Updated labels for readability in datadog widgets
https://jira.devops.va.gov/browse/MBMS-66758
- …

MBMS-66758 Updated datadog dashboard labels

---

lib/evss/disability_compensation_form/form526_to_lighthouse_transform.rb
spec/lib/evss/disability_compensation_form/form526_to_lighthouse_transform_spec.rb
spec/support/disability_compensation_form/all_claims_fe_submission.json

This PR transforms front end JSON elements relating to Hazards to the LH submit/generatePDF request, which maps to question 15D of the 526ez digital form.
- *This work is behind a feature toggle (flipper): YES* `disability_526_toxic_exposure` 🐬
Modifications to the Form526ToLighthouseTransform logic + tests + data
Disability Benefits Experience Team 1 (DBEX TREX 🦖)
Toxic Exposure - …

Toxic Exposure - Data Transformation - Hazards (FE to LH request)

---

config/features.yml

-  fixed typo in features togggle for vye  …

fixed typo with toggles name

---

app/sidekiq/terms_of_use/sign_up_service_updater_job.rb
spec/sidekiq/terms_of_use/sign_up_service_updater_job_spec.rb

- Update log to include necessary info to pass along to SuS if there are failures
- adds `agreement_version`, `response` (accepted or declined), and `response_time`
- Log looks like - 
```ruby
Rails -- [TermsOfUse][SignUpServiceUpdaterJob] retries exhausted -- { :icn => "icn", :agreement_version => "v1", :attr_package_key => "some-key", :response => "accepted", :response_time => "2024-06-07T15:59:05Z", :exception_message => "some-error" }
```
- nothing to really test. updated unit tests
Terms of use

Update SignUpServiceUpdater retries exhausted log

---

modules/mobile/app/controllers/mobile/v0/appointments_controller.rb
modules/mobile/config/locales/exceptions.en.yml
modules/mobile/lib/mobile/v0/exceptions/custom_errors.rb
modules/mobile/spec/exceptions/custom_error_spec.rb
modules/mobile/spec/request/appointments_vaos_v2_list_request_spec.rb

https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/BackEnd/Features/CustomErrorResponses/
https://adhoc.slack.com/archives/C0212B872MT/p1717780791608929
https://github.com/department-of-veterans-affairs/va-mobile-app/issues/8810 …

add mobile custom error

---

modules/vba_documents/spec/serializers/shared_upload_serializer.rb
modules/vba_documents/spec/serializers/upload_serializer_spec.rb
modules/vba_documents/spec/serializers/v1/upload_serializer_spec.rb
modules/vba_documents/spec/serializers/v2/upload_serializer_spec.rb
spec/support/serializer_spec_helper.rb

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/83648

Add Unit Tests for VBA Document Serializers

---

modules/test_user_dashboard/spec/serializers/tud_account_serializer_spec.rb

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/83646

Add Unit Tests for TestUserDashboard AMS Serializers

---

modules/veteran/spec/serializers/service/representation_serializer_spec.rb

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/83649

Add Unit Tests for Veteran (module) Serializers

---

modules/mobile/app/controllers/mobile/v0/messages_controller.rb
modules/mobile/spec/request/folders_request_spec.rb

Remove logs to debug sorting issue.
https://github.com/department-of-veterans-affairs/va-mobile-app/issues/8714
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-Backend …

mobile - remove sorting logging

---

app/models/concerns/form526_claim_fast_tracking_concern.rb
config/settings.yml
spec/support/vcr_cassettes/virtual_regional_office/multi_contention_classification.yml

- During the bug bash session testing interactions between staging.va.gov -> sandbox vro environment, I observed that the submit_form526 jobs were 404'ing when trying to contact the classifier service.
- I believe that prepending `contention-classification/` should fix this
- I also added an extra logging statement to make it easier to debug failed calls to classifier
- https://github.com/department-of-veterans-affairs/vagov-claim-classification/issues/480
- related slack thread: https://dsva.slack.com/archives/C01Q7979Z7D/p1717794187033839 …

fix urlpath for CC endpoint in VRO

---

modules/claims_api/app/controllers/claims_api/v2/veterans/power_of_attorney/base_controller.rb
modules/claims_api/app/controllers/claims_api/v2/veterans/power_of_attorney/request_controller.rb
modules/claims_api/app/services/claims_api/power_of_attorney_request_service/create_request.rb
modules/claims_api/config/routes.rb
modules/claims_api/config/schemas/v2/poa_request.json
modules/claims_api/spec/fixtures/v2/veterans/power_of_attorney/request_representative/invalid_claimant_schema.json
modules/claims_api/spec/fixtures/v2/veterans/power_of_attorney/request_representative/invalid_poa.json
modules/claims_api/spec/fixtures/v2/veterans/power_of_attorney/request_representative/invalid_schema.json
modules/claims_api/spec/fixtures/v2/veterans/power_of_attorney/request_representative/valid.json
modules/claims_api/spec/requests/v2/veterans/power_of_attorney_new_poa_request_spec.rb
modules/claims_api/spec/requests/v2/veterans/power_of_attorney_request_spec.rb

- This pr adds new POA request functionality to the placeholder endpoint.
- This pr moves the endpoint into it's own class
- [API-36517](https://jira.devops.va.gov/browse/API-36517)
- tested requests locally with BGS forward proxy in Postman and rails console
Impacts Claims API and ARM once it is in use. No 3rd party consumers for now.

[API-36517] Add new poa request controller and specs

---

lib/evss/disability_compensation_form/form526_to_lighthouse_transform.rb
spec/lib/evss/disability_compensation_form/form526_to_lighthouse_transform_spec.rb
spec/support/disability_compensation_form/all_claims_fe_submission.json

This PR populates the multiple exposures array of the Lighthouse submit/generatePDF request with hazard information coming in from the front end. Lighthouse then populates the 15E overflow of the 526ez digital form with each hazard and its corresponding date ranges.
`disability_526_toxic_exposure`
Modifications to the Form526ToLighthouseTransform logic + tests 
Disability Benefits Experience Team 1 (DBEX TREX 🦖)
- *Link to …

Handle multiple exposure durations -  hazards/other hazards

---

.github/workflows/deploy_delay_notifications.yml

Notifications were going off every 10 mins if dev or staging wasn't up to date

fix: Date comparison was using test operator

---

db/migrate/20240611183430_update_veteran_icn_name_on_intent_to_file_queue_exhaustions.rb
db/schema.rb

- Renamed veteran_icn column to user_uuid on IntentToFileQueueExhaustions tables. This is necessary, because we can only lookup the User Redis datastore by user_uuid.
- Pension benefits team to own this change
- [*Link to ticket created in va.gov-team repo*](https://github.com/department-of-veterans-affairs/va.gov-team/issues/81536)
- [*Link to epic*](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/81536)
- …

update pension itf schema

---

modules/debts_api/lib/debts_api/v0/fsr_form_transform/personal_data_calculator.rb
modules/debts_api/spec/fixtures/pre_submission_fsr/post_transform.json
modules/debts_api/spec/fixtures/pre_submission_fsr/pre_transform.json
modules/debts_api/spec/lib/debt_api/v0/fsr_form_transform/personal_data_calculator_spec.rb

This is part of the larger effort to move the transformation logic for the FSR form from the front end to the back end. This pull request is for part five of this effort addressing many of the miscellaneous transformations, specifically the `personal_data.` This is only one of the miscellaneous properties to transform and is not enough to close the main ticket on its own.
I am on the VA debt team, which owns maintenance of this code. This work is not behind a feature toggle.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/84076
_This has not been added at the time of this pull request._ …

Full transform on backend, Part 5 [Personal Data] (84076)

---

modules/debts_api/lib/debts_api/v0/fsr_form_transform/discretionary_income_calculator.rb
modules/debts_api/lib/debts_api/v0/fsr_form_transform/installment_contracts_other_debts_calculator.rb
modules/debts_api/spec/lib/debt_api/v0/fsr_form_transform/discretionary_income_calculator_spec.rb
modules/debts_api/spec/lib/debt_api/v0/fsr_form_transform/installment_contracts_other_debts_calculator_spec.rb

This is part of the larger effort to move the transformation logic for the FSR form from the front end to the back end. This pull request is for part five of this effort, addressing many of the miscellaneous transformations, specifically for `discretionaryIncome`, `installmentContractsAndOtherDebts`, and `totalOfInstallmentContractsAndOtherDebts`. These are only three of the miscellaneous properties to transform, and they are not enough to close the main ticket on their own.
I am on the VA debt team, which owns maintenance of this code. This work is not behind a feature toggle.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/84076
_This has not been added at the time of this pull request._
- *Describe the …

Full transform on backend, Part 5 [Contracts, Other Debts] (84076)

---

app/models/form526_submission.rb

Corrects https://github.com/department-of-veterans-affairs/vets-api/pull/17077, properly assigning the default mock response status as well as capturing the entirety of the actual response detail, not only the description as some responses do not include additional information describing the error. Also includes a minor refactor to extract the validation error handling into a private method.
- **Responsible team:** Disability Benefits Experience Team 2 (dBeX Carbs 🥖)
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/82149
- https://github.com/department-of-veterans-affairs/vets-api/pull/17077
-  no existing unit tests cover the modified methods as they are not currently intended to be utilized by the …

[DBEX] capture default status and error detail

---

modules/debts_api/lib/debts_api/v0/fsr_form_transform/discretionary_income_calculator.rb
modules/debts_api/lib/debts_api/v0/fsr_form_transform/installment_contracts_other_debts_calculator.rb
modules/debts_api/lib/debts_api/v0/fsr_form_transform/personal_data_calculator.rb
modules/debts_api/lib/debts_api/v0/fsr_form_transform/utils.rb

This is a light refactoring of the methods used in the FSR form backend transfoorm. It moves methods that are duplicated and/or not specific to certain data groups to the utils module.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/81058
Affected classes are already covered by existing unit tests. As long as the existing tests pass, this should be good.

[81058]: Method refactoring for backend full transform

---

config/features.yml

- department-of-veterans-affairs/va.gov-team#77290
- The toggle will be removed once testing is fully completed in the Staging environment and after a predetermined amount of time has passed without any failures or errors. The specific timeframe will be decided by the team based on the stability and performance observed during the testing phase. This ensures that the feature is reliable and ready for full deployment.

Added feature toggle for supporting docs

---

.github/CODEOWNERS
spec/factories/form526_job_statuses.rb
spec/factories/form526_submissions.rb
spec/factories/gi_bill_feedback.rb
spec/serializers/form526_job_status_serializer_spec.rb
spec/serializers/full_name_serializer_spec.rb
spec/serializers/gender_identity_serializer_spec.rb
spec/serializers/gi_bill_feedback_serializer_spec.rb
spec/serializers/hca_attachment_serializer_spec.rb
spec/serializers/hca_rating_info_serializer_spec.rb

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/83654

Add Unit Tests for Root AMS Serializers - Part 6

---

.github/CODEOWNERS
spec/factories/evss_intent_to_files.rb
spec/factories/health_care_application.rb
spec/serializers/health_care_application_serializer_spec.rb
spec/serializers/intent_to_file_serializer_spec.rb
spec/serializers/letter_beneficiary_serializer_spec.rb
spec/serializers/letters_serializer_spec.rb

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/83654

Add Unit Tests for Root AMS Serializers - Part 7

---

.github/CODEOWNERS
modules/mobile/spec/serializers/mobile/v0/message_serializer_spec.rb
spec/serializers/folder_serializer_spec.rb
spec/serializers/lighthouse_rating_info_serializer_spec.rb
spec/serializers/maintenance_window_serializer_spec.rb
spec/serializers/message_serializer_spec.rb
spec/serializers/messages_serializer_spec.rb
spec/serializers/messaging_preference_serializer_spec.rb

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/83654

Add Unit Tests for Root AMS Serializers - Part 8

---

config/features.yml

-Removal of unused feature toggle. 
No ticket, but here is a slack thread: https://dsva.slack.com/archives/CBU0KDSB1/p1717685697982189
N/A
N/A
MHV on  va.gov

(feature toggle) removed toggle for unique user tracking in SM

---

modules/ivc_champva/app/form_mappings/vha_10_7959c.json.erb

This PR updates the PDF mapping on form 10-7959c so that the "new address" checkbox is appropriately checked/unchecked based on data from frontend.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/85939
- https://github.com/department-of-veterans-affairs/vets-website/pull/30411 …

85939 Update PDF mapping for new address checkbox - form 10-7959c

---

Gemfile.lock
app/sidekiq/copay_notifications/new_statement_notification_job.rb
spec/sidekiq/copay_notifications/new_statement_notification_job_spec.rb

[An engineer from the benefits team alerted us to a sizable number of queue exhaustions](https://dsva.slack.com/archives/CPE4AJ6Q0/p1718374820439319). It was recommended we add a queue exhaustion block to remediate the issue, this adds the block.
- *This work is behind a feature toggle (flipper):*
- Technically, this is not behind a feature flag but the heart of the feature is turned off for now so there should be no impact on the veteran experience.
- We have added the sidekiq_retries_exhausted block to log what happened and maybe gain some insight to an issue.
- We can be reached on the #debt-resolution slack channel
[Zenhub …

85964 Add Queue Exhaustion for VODA notification job

---

modules/mobile/app/controllers/mobile/v0/messages_controller.rb

add logging to debug non json response from upstream
https://github.com/department-of-veterans-affairs/va-mobile-app/issues/8472
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretog …

add logging

---

Gemfile.lock
modules/claims_api/app/controllers/claims_api/v1/application_controller.rb
modules/claims_api/spec/requests/v1/power_of_attorney_request_spec.rb

* Updates header check to also verify first name and last name are not empty string
* Adds one additional test for the scenario
[API-37228](https://jira.devops.va.gov/browse/API-37228)
modified:   modules/claims_api/app/controllers/claims_api/v1/application_controller.rb
modified:   modules/claims_api/spec/requests/v1/power_of_attorney_request_spec.rb

API 37228 mpi fix headers first & last name check

---

modules/pensions/README.md
modules/pensions/README.rdoc
modules/pensions/documentation/readme.md

This PR is just updates to documentation

Updates to documentation

---

modules/pensions/README.md
modules/pensions/documentation/readme.md

Fix bad links

---

modules/debts_api/lib/debts_api/v0/fsr_form_transform/additional_data_calculator.rb
modules/debts_api/lib/debts_api/v0/fsr_form_transform/asset_calculator.rb
modules/debts_api/lib/debts_api/v0/fsr_form_transform/bankruptcy_calculator.rb
modules/debts_api/lib/debts_api/v0/fsr_form_transform/discretionary_income_calculator.rb
modules/debts_api/lib/debts_api/v0/fsr_form_transform/enhanced_expense_calculator.rb
modules/debts_api/lib/debts_api/v0/fsr_form_transform/expense_calculator.rb
modules/debts_api/lib/debts_api/v0/fsr_form_transform/full_transform_service.rb
modules/debts_api/lib/debts_api/v0/fsr_form_transform/income_calculator.rb
modules/debts_api/lib/debts_api/v0/fsr_form_transform/personal_data_calculator.rb
modules/debts_api/lib/debts_api/v0/fsr_form_transform/personal_identification_calculator.rb
modules/debts_api/lib/debts_api/v0/fsr_form_transform/streamlined_calculator.rb
modules/debts_api/lib/debts_api/v0/fsr_form_transform/utils.rb
modules/debts_api/spec/fixtures/pre_submission_fsr/kitchen_sink/post_transform.json
modules/debts_api/spec/fixtures/pre_submission_fsr/kitchen_sink/pre_transform.json
modules/debts_api/spec/fixtures/pre_submission_fsr/sw_long/minimal_asset_post_transform.json
modules/debts_api/spec/fixtures/pre_submission_fsr/sw_long/minimal_asset_pre_transform.json
modules/debts_api/spec/fixtures/pre_submission_fsr/sw_short/minimal_asset_post_transform.json
modules/debts_api/spec/fixtures/pre_submission_fsr/sw_short/minimal_asset_pre_transform.json
modules/debts_api/spec/lib/debt_api/v0/fsr_form_transform/expense_calculator_spec.rb
modules/debts_api/spec/lib/debt_api/v0/fsr_form_transform/full_transform_service_spec.rb
modules/debts_api/spec/lib/debt_api/v0/fsr_form_transform/income_calculator_spec.rb
modules/debts_api/spec/request/debts_api/v0/financial_status_reports_calculations_controller_spec.rb

Add fixtures to FSR transform service specs
- [84447](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/84447)
- [81058](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/81058)
Fixtures added, specs green.
FSR test suite
Reliable input & output fixtures added which demonstrate the FE transform logic.

84447 add fixtures

---

app/sidekiq/evss/disability_compensation_form/submit_form526.rb

This PR conditionally handles the response from the LH submit request
- Disability Benefits Experience Team 1 (DBEX-TREX 🦖) (rawr)
- *Describe the steps required to …

Conditionally handle LH response in 526 submit

---

app/models/form526_submission.rb
app/sidekiq/evss/disability_compensation_form/submit_form526.rb
lib/evss/disability_compensation_form/form526_to_lighthouse_transform.rb

- fixes issues summarized in the ticket
- department-of-veterans-affairs/va.gov-team#86496
n/a
- Form526 to Lighthouse submission

dbex/86496: fix issues with `Form526ToLighthouseTransform`

---

config/features.yml

- Removes `check_in_experience_pre_check_in_action_link_top_placement` and `check_in_experience_travel_logic`
- (https://github.com/department-of-veterans-affairs/va.gov-team/issues/84396)[https://github.com/department-of-veterans-affairs/va.gov-team/issues/84396]
_Note: …

Remove old feature flags

---

modules/check_in/app/sidekiq/check_in/travel_claim_status_check_worker.rb
modules/check_in/spec/sidekiq/travel_claim_status_check_worker_spec.rb
spec/support/vcr_cassettes/check_in/btsss/claim_status/claim_status_200.yml
spec/support/vcr_cassettes/check_in/btsss/claim_status/claim_status_500.yml

- *Implmenting new sidekiq worker for checking submitted claim status*
- *https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/84764*
NA

84764 Implementing new sidkiq worker for claim status check

---

config/features.yml

This adds the feature flag to `vets-api` as part of the Payment History VBA Pre-MVP 1.0.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/85880
N/A
N/A
VA Debt and Payment History

[85880] Add Payment History VBA feature flag for vets-api

---

modules/pensions/documentation/readme.md

add link to other ADR

---

.github/workflows/build-and-publish.yaml

fix to build nd publish workflow due to crendentialing error - switch to role based
- This is a fix to the build and publish workflow which stopped working due to an AWS credential issue
*Build pipeline*

Correct build and publish workflow

---

config/features.yml

This PR adds a feature flag for form 10-10d so it can be slow rolled out in production.
- Adds flipper for form 10-10d
- Success criteria for flipper: gated access to form 10-10d in a controlled percentage as we begin rolling out to production in the coming weeks/months.
- https://github.com/department-of-veterans-affairs/vets-website/pull/30556
- *Tests need to be written for both the flipper on and flipper off scenarios. [Docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-Backend …

86998  add feature flag for form 10-10d

---

modules/ask_va_api/app/controllers/ask_va_api/v0/inquiries_controller.rb
modules/ask_va_api/app/lib/ask_va_api/base_retriever.rb
modules/ask_va_api/app/lib/ask_va_api/inquiries/status/retriever.rb
modules/ask_va_api/spec/app/lib/ask_va_api/inquiries/status/retriever_spec.rb
modules/ask_va_api/spec/requests/v0/inquiries_spec.rb

This pull request includes significant updates to improve the handling of responses from the CRM API and to enhance the functionality of the `InquiriesController#Status` endpoint.
1. **Refactor `Status::Retriever`**
- Updated `Status::Retriever` to handle the new response format from the CRM API.
- Revised parsing logic to accommodate additional fields and structures in the CRM API response.
- Improved error handling for unexpected response formats.
- Enhanced unit tests to cover new response scenarios and ensure robustness.
2. **Revise `InquiriesController#Status` Endpoint**
- Updated `InquiriesController#Status` endpoint to improve response handling and data processing.
- Refactored the method to ensure compatibility with the latest CRM API changes.
- Enhanced error handling to provide …

BE | Ask va api:  update inquiries status endpoint

---

modules/ivc_champva/app/controllers/ivc_champva/v1/pega_controller.rb
modules/ivc_champva/spec/requests/v1/pega_spec.rb

Update pega json render

---

modules/ask_va_api/app/controllers/ask_va_api/v0/health_facilities_controller.rb
modules/ask_va_api/config/routes.rb
modules/ask_va_api/spec/requests/v0/health_facilities_spec.rb

- Updated HealthFacilitiesController to utilize facilities_api/v2.
- Replaced the deprecated facilities_api/v0 with the latest version.
- Ensured all endpoints and methods are compatible with the new API version.
- https://github.com/department-of-veterans-affairs/ask-va/issues/1162 …

BE | Ask VA API: Refactored HealthFacilitiesController to use facilities_api/v2

---

modules/ask_va_api/app/controllers/ask_va_api/v0/health_facilities_controller.rb

- Add logging to `HealthFacilitiesController`
- https://github.com/department-of-veterans-affairs/ask-va/issues/1162

Add logging to HealthFacilitiesController

---

modules/ask_va_api/app/lib/ask_va_api/inquiries/status/retriever.rb
modules/ask_va_api/spec/requests/v0/inquiries_spec.rb

- Updated `payload` from ` { inquiry_number: '123'}` to `{ InquiryNumber: '123'}`
- https://github.com/department-of-veterans-affairs/ask-va/issues/1074

BE | Ask VA API: fixed payload in crm api call
